tools/fault-injection-service/CMakeLists.txt, tools/fault-injection-service/README.md
Fixing a minor build issue that can cause failure on some platforms while unable to find Threads library.
https://issues.apache.org/jira/browse/HDDS-4844
Build on the Ubuntu and Debian platform after making the changes.
This does not affect the Ozone build of CI tests.
=> HDDS-4844. Fixing build issue for some platforms.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconAsPassiveScm.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconNodeManager.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconNodeManager.java
https://issues.apache.org/jira/browse/HDDS-4845
Possibly due to Recon ignoring `setNodeOperationalStateCommand` ([HDDS-4766](https://github.com/apache/ozone/pull/1857/files#diff-9ef008cf91342ca17b33f4edf0f8ecf1bff0b3c954f04dda9a02d6ae9d9e9d16R426)), `NodeStatus` isn't being updated for its `operationalState` and `opStateExpiryEpochSeconds` fields (but `DatanodeInfo`'s `persistedOpState` and `persistedOpStateExpiryEpochSec` are correct):
- Tested manually so far with temporarily inserted assertions.
- Updated UT.
=> HDDS-4845. Update NodeStatus OperationalState for Datanodes in Recon

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OzoneFileStatus.java, hadoop-ozone/dist/src/main/compose/xcompat/clients.yaml, hadoop-ozone/dist/src/main/compose/xcompat/test.sh, hadoop-ozone/dist/src/main/smoketest/compatibility/read.robot, hadoop-ozone/dist/src/main/smoketest/compatibility/write.robot, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
HDDS-4731 missed some places related to file status where client version needs to be considered for protobuf conversion.  These can be reproduced by `ozone fs` operations:
```
$ ozone fs -mkdir o3fs://bucket1.vol1/dir/
$ ozone fs -ls o3fs://bucket1.vol1/dir/
$ ozone fs -put /etc/passwd o3fs://bucket1.vol1/dir/
-put: No enum constant org.apache.hadoop.hdds.protocol.DatanodeDetails.Port.Name.REPLICATION
$ ozone fs -ls o3fs://bucket1.vol1/dir/
-ls: No enum constant org.apache.hadoop.hdds.protocol.DatanodeDetails.Port.Name.REPLICATION
```
https://issues.apache.org/jira/browse/HDDS-4851
Added acceptance test cases.  0.5.0 client had to be removed from the test due to another incompatibility:
```
Message missing required fields: getFileStatusResponse.status.status, ...
```
=> HDDS-4851. More compatibility problem with DatanodeDetails.Port.Name.REPLICATION

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeDecommissionManager.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DecommissionSubCommand.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/ListInfoSubcommand.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/MaintenanceSubCommand.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/RecommissionSubCommand.java
https://issues.apache.org/jira/browse/HDDS-4849
1. Right now running `ozone admin datanode decommission` command alone doesn't give any feedback.
With patch:
```bash
bash-4.2$ ozone admin datanode decommission
Incomplete command
Usage: ozone admin datanode decommission [-hV] [--scm=<scm>] [<hosts>...]
Decommission a datanode
[<hosts>...]   List of fully qualified host names
-h, --help         Show this help message and exit.
--scm=<scm>    The destination scm (host:port)
-V, --version      Print version information and exit.
```
2. When a decommission command is executed successfully, it lacks feedback on the client (it does log on the server side).
With patch:
```bash
bash-4.2$ ozone admin datanode decommission 172.18.0.7 172.18.0.2
Started decommissioning datanode(s):
172.18.0.7 …
```
=> HDDS-4849. Improve Ozone admin shell decommission/recommission/maintenance commands user experience

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/ListInfoSubcommand.java
https://issues.apache.org/jira/browse/HDDS-4846
One line cosmetic change. Pls refer to the original jira for slightly more info on it.
=> HDDS-4846. Add line break when node has no pipelines for `ozone admin datanode list` command

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChecksumByteBufferImpl.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/NativeCheckSumCRC32.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/PureJavaCrc32ByteBuffer.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/PureJavaCrc32CByteBuffer.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/util/NativeCRC32Wrapper.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/util/package-info.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/common/TestChecksumImplsComputeSameValues.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/genesis/BenchMarkCRCBatch.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/genesis/BenchMarkCRCStreaming.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/genesis/Genesis.java
Add a Genesis benchmark to compare the performance of various CRC32 implementations.
https://issues.apache.org/jira/browse/HDDS-4808
Benchmarks were execute manually. One new test added to validate that all CRC implementations give the same result.
=> HDDS-4808. Add Genesis benchmark for various CRC implementations

hadoop-ozone/dist/src/main/compose/ozonesecure/test.sh, hadoop-ozone/dist/src/main/smoketest/admincli/replicationmanager.robot
HDDS-4834 added a new test case in `ozonesecure`, which apparently causes flakiness in later container-related test.
This PR moves the replication test, which requires datanode restart, to the end of the test suite.  Hopefully this fixes the flakiness.
https://issues.apache.org/jira/browse/HDDS-4850
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/584182478
acceptance (secure) 10x:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/584359630
https://github.com/adoroszlai/hadoop-ozone/actions/runs/584573002
=> HDDS-4850. Intermittent failure in ozonesecure due to unable to allocate block

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAUtils.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMNodeInfo.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/TestHddsUtils.java
Use SCM serviceID and nodeID to figure SCM Datanode address and port in HA from SCM address key and SCM Datanode port config or else fall back to ozone.scm.names
https://issues.apache.org/jira/browse/HDDS-4837
Added UT.
=> HDDS-4837. Use SCM service ID in finding SCM Datanode address.

hadoop-ozone/dist/src/main/dockerlibexec/entrypoint.sh
I think it may be the previous mistake that caused the copy path error, so I modified the copy path.
https://issues.apache.org/jira/browse/HDDS-4853
no test.
=> HDDS-4853. libexec/entrypoint.sh might copy from wrong path

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/NodeEndpoint.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/DatanodeMetadata.java, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/db.json, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/types/datanode.types.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/datanodes/datanodes.tsx, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java
We should show the Datanode OperationalState in Recon Datanode page as well as it provides valuable information.
https://issues.apache.org/jira/browse/HDDS-4832
- Manually tested with docker-compose cluster so far. Decommissioned a datanode via command line `ozone admin datanode decommission <HOST/IP>`
- Updated UT to check response of the new `OperationalState` field of the API.
=> HDDS-4832. Show Datanode OperationalState in Recon

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemV1.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/ITestOzoneContractCreate.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/ITestOzoneContractDelete.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/ITestOzoneContractGetFileStatus.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/ITestOzoneContractMkdir.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/ITestOzoneContractOpen.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/ITestOzoneContractRename.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/ITestOzoneContractRootDir.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/ITestOzoneContractSeek.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/ITestOzoneContractUnbuffer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/ITestOzoneContractUtils.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/OzoneContract.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java
This change makes OzoneFs Contract tests parameterised with a parameter that denotes whether it is FS Optimised (V1 layout version) and runs all the combinations for client and server. This change also fixes few  test failures obtained when running the contract tests. 
https://issues.apache.org/jira/browse/HDDS-4513
Via ozone contract tests
=> HDDS-4513.[FSO]OzoneContract unit test case fixes

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/SCMConnectionManager.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java
Background:
The current retry policy of DN is to retry sending with a 1s interval. Given at some time-point, all the DNs lost connection with the SCM at the same time, due to the restart of SCM, all DNs will send container report to SCM nearly at the same time, which is a ContainerReport Storm.
Solution:
Manually adjust the rpc-retry-interval with rpc-retry-count could mitigate extreme cases such as OOM, when facing up a huge cluster.
Make the rpc-retry-interval configurable. 
https://issues.apache.org/jira/browse/HDDS-4754
CI
=> HDDS-4754. Make scm heartbeat rpc retry interval configurable

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/JavaUtils.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/Checksum.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChecksumByteBufferFactory.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChecksumByteBufferImpl.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/common/TestChecksumByteBuffer.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/common/TestChecksumImplsComputeSameValues.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/genesis/BenchMarkCRCStreaming.java
Based on the results in  HDDS-4808 (https://github.com/apache/ozone/pull/1910#issuecomment-775165462) it is clear we should switch the CRC32 implementations used by Ozone, as there are other better performing implementations.
Specifically:
`org.apache.hadoop.ozone.common.PureJavaCrc32ByteBuffer` to `Java.util.zip.CRC32`
`org.apache.hadoop.ozone.common.PureJavaCrc32CByteBuffer` to `Java.util.zip.CRC32C` if Java 9 or greater, otherwise `org.apache.hadoop.util.PureJavaCrc32C`
https://issues.apache.org/jira/browse/HDDS-4138
Small change to an existing test
=> HDDS-4138. Improve crc efficiency by using Java.util.zip.CRC when available

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBMetrics.java
Make RDBMetrics#unRegister() synchronized. Accessing the instance object inside RDMBetrics#create() is synchronized, and therefore RDBMetrics#unRegister() should be made synchronized to protect the instance object.
https://issues.apache.org/jira/browse/HDDS-4722
=> HDDS-4722. Creating RDBStore fails due to RDBMetrics instance race

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OzoneFSUtils.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestObjectStoreV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java
This task is to perform #listKeys by searching the startKey, keyPrefix in Dir & File Tables.
https://issues.apache.org/jira/browse/HDDS-4683
Added only one UT now.  I will add more test cases. I'm thinking something like large dirs and sub-dirs/files.
Also, there is an open point: #listKeys("key-a-"), basically partial keyName and startKey. For example, actual keyName stored in DB are "key-a-10", "key-a-11", "key-a-12"..."key-z-10", "key-z-11", "key-z-12".
=> HDDS-4683. [FSO]ListKeys: do lookup in dir and file tables

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/protocol/SCMSecurityProtocol.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/protocolPB/SCMSecurityProtocolClientSideTranslatorPB.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/CertificateServer.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/CertificateStore.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/DefaultCAServer.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/authority/MockCAStore.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/authority/TestDefaultCAServer.java, hadoop-hdds/interface-client/src/main/proto/hdds.proto, hadoop-hdds/interface-server/src/main/proto/ScmServerSecurityProtocol.proto, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/metadata/SCMDBDefinition.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/metadata/SCMMetadataStore.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/metadata/SCMMetadataStoreImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/SCMSecurityProtocolServerSideTranslatorPB.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMCertStore.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMSecurityProtocolServer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestSCMStoreImplWithOldPipelineIDKeyFormat.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/server/TestSCMSecurityProtocolServer.java
This Jira is to implement generatePeerSCMCertificate which will be called during bootStrap and also during init by primary SCM. This is similar to how OM and DN gets certificate.
During implementation as the validCerTable key is SerialId which is BigInteger, created a new table validScmCertsTable to store scm certs. This is being done so that we can implement querySCMCertificates which can return all SCM certs.
Also, I see there is a TODO for list Certs based on role. Not sure if there is a way in the current code to return certs from the table. If there is any approach, will rework this PR based on review comments.
https://issues.apache.org/jira/browse/HDDS-4861
=> HDDS-4861. [SCM HA Security] Implement generate SCM certificate.

hadoop-hdds/common/pom.xml, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocol.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/protocolPB/StorageContainerLocationProtocolClientSideTranslatorPB.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMContainerLocationFailoverProxyProvider.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMProxyInfo.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocolServerSideTranslatorPB.java
Scope
admin command includes rm start/stop and safe mode exit.
 
Requirement
1, When admin stops rm, rm in all SCM should stop, re-election should not trigger rm to start in the new leader.
2, When admin starts rm, only rm in leader and out of safe mode should take effect. Given leader is in safe mode, even if admin starts rm explicitly, it does not take effect.
3, This admin rm start/stop can not survive restart for a SCM instance. When admin decides to stop rm of the SCM cluster, he should pay attention if any of the SCM crashes.
 
Status
1, For now, admin rm start/stop will create/destroy the rm thread.
2, SCMContainerLocationFailoverProxyProvider has been proxied by FailoverProxyProvider, it will round robin SCMs in ozone.scm.names, until it is successfully handled. In ServerSide, …
=> HDDS-4740. Admin command should take effect on all SCM instance

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogImplV2.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogStateManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMStateMachine.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestDeletedBlockLog.java
Only trigger a Ratis oncall when in-memory retry count exceed max_retry. 
Relevant doc: https://docs.google.com/document/d/1hjHs2pt3fD7jRiMwu90SK4uY2hgrFIjEsygt5kJP8NY/edit?usp=sharing
https://issues.apache.org/jira/browse/HDDS-4761
UT
=> HDDS-4761. Implement increment count optimization in DeletedBlockLog V2

pom.xml
JIRA: https://issues.apache.org/jira/browse/HDDS-4869
> com.fasterxml.jackson.core:jackson-databind is a library which contains the general-purpose data-binding functionality and tree-model for Jackson Data Processor.
> 
> Affected versions of this package are vulnerable to Deserialization of Untrusted Data due to an incomplete black list (incomplete fix for CVE-2017-7525). It doesn't block common-configuration JNDI classes org.apache.commons.configuration.JNDIConfiguration and org.apache.commons.configuration2.JNDIConfiguration
More information: https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-559106
CI + checking if jackson jars are replaced:
```
cd hadoop-ozone/dist/target/ozone-1.1.0-SNAPSHOT/share/ozone/lib
s -lah *jackson*
Permissions Size User Date Modified Name …
```
=> HDDS-4869. Bump jackson version number

hadoop-ozone/csi/src/main/java/org/apache/hadoop/ozone/csi/CsiServer.java, hadoop-ozone/csi/src/main/java/org/apache/hadoop/ozone/csi/IdentityService.java, hadoop-ozone/dist/src/main/smoketest/csi.robot
Replace class name `IdentitiyService` with `IdentityService `
[https://issues.apache.org/jira/browse/HDDS-4847](https://issues.apache.org/jira/browse/HDDS-4847)
unit tests
=> HDDS-4847. Fix CSI typo

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/states/ContainerAttribute.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/states/TestContainerAttribute.java
- Keep the original value in ContainerAttribute when inserting ContainerId.
https://issues.apache.org/jira/browse/HDDS-4769
Unit test in TestContainerAttribute.testInsert() validates the correctness.
=> HDDS-4769. Simplify insert operation of ContainerAttribute

.github/workflows/post-commit.yml
Fix `Never cache local artifacts` step in Github Actions workflow.  There were 2 problems:
1. The cache and the cleanup were in different jobs.
2. The repo does not have `hdds` and `ozone` subdirectories, only ones like `hadoop-hdds-common`, etc.
https://issues.apache.org/jira/browse/HDDS-4858
Temporarily enabled verbose output to print items being removed:
```
2021-02-23T14:16:41.5399844Z ##[group]Run #Never cache local artifacts
2021-02-23T14:16:41.5400509Z #Never cache local artifacts
2021-02-23T14:16:41.5401104Z rm -rfv ~/.m2/repository/org/apache/hadoop/hadoop-hdds*
2021-02-23T14:16:41.5401913Z rm -rfv ~/.m2/repository/org/apache/hadoop/hadoop-ozone*
...
2021-02-23T14:16:41.5541337Z ##[endgroup]
...
2021-02-23T14:16:41.5665616Z removed directory …
```
=> HDDS-4858. Useless Maven cache cleanup

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/ListInfoSubcommand.java, hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestListInfoSubcommand.java
This change adds the health state to the "ozone admin datanode list" command and ensures that all nodes registered in SCM are returned in the output. Previously, the health state was not displayed and only healthy nodes were shown. Any stale or dead nodes were omitted.
The new output looks like:
```
$ ozone admin datanode list
Datanode: 839e594c-2dd8-4d19-a932-acb2c7acebb9 (/default-rack/172.22.0.4/ozone_datanode_4.ozone_default/2 pipelines)
Operational State: IN_SERVICE
Health State: HEALTHY   ******** Newly added line
Related pipelines:
93c1ecce-e0ed-49ab-be6d-e0c0ec07e3e9/ONE/RATIS/OPEN/Leader
fde8dd62-c677-4a05-89f0-a7d0eb450736/THREE/RATIS/OPEN/Leader
```
The output is also sorted so healthy DNs are listed first, then stale and then dead at the bottom. …
=> HDDS-4867. Ozone admin datanode list should report dead and stale nodes

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystemV1.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestReadRetries.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMetrics.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/TrashOzoneFileSystem.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java
Add atomic rename and delete api's to BasicRootedOzoneFileSystem (OFS).  
https://issues.apache.org/jira/browse/HDDS-4490
Unit tests. (Same as TestRootedOzoneFileSystem) but with FSO configs.
=> HDDS-4490.[FSO]RenameAndDelete : make ofs#rename and ofs#delete an atomic operation.

hadoop-hdds/docs/content/recipe/BotoClient.md, hadoop-ozone/dist/pom.xml, hadoop-ozone/dist/src/main/smoketest/s3/boto3.robot, hadoop-ozone/dist/src/main/smoketest/s3/boto_client.py
HDDS-4864. Add acceptance tests to certify Ozone with boto3 python client.
Add an acceptance tests to certify Ozone with boto3 python client.
https://issues.apache.org/jira/browse/HDDS-4864
- Did a full build and tested it locally.
- adoroszlai executed my patch locally in: ozone compose, ozonesecure and ozone-ha, all passed.
=> HDDS-4864. Add acceptance tests to certify Ozone with boto3 python client.

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/ListInfoSubcommand.java, hadoop-ozone/dist/src/main/smoketest/admincli/datanode.robot
Fix UUID comparison for `ozone admin datanode list`.
https://issues.apache.org/jira/browse/HDDS-4885
Added acceptance test.
https://github.com/adoroszlai/hadoop-ozone/runs/2006084493#step:7:1022
=> HDDS-4885. ozone admin datanode list filter by UUID broken

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NodeSchemaLoader.java
Convert classloader URL enumeration to list for more user-friendly output in log.
https://issues.apache.org/jira/browse/HDDS-4887
Started `ozone` compose cluster, verified message in log:
```
[main] INFO net.NodeSchemaLoader: Loading schema from [file:/etc/hadoop/network-topology-default.xml, jar:file:/opt/hadoop/share/ozone/lib/hadoop-hdds-common-1.1.0-SNAPSHOT.jar!/network-topology-default.xml]
```
=> HDDS-4887. Useless message about node schema location

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMServiceManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerV2Impl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconAsPassiveScm.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/ClusterStateEndpoint.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/ContainerEndpoint.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconContainerManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconPipelineManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStorageContainerManagerFacade.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/fsck/TestContainerHealthTask.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/AbstractReconContainerManagerTest.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconIncrementalContainerReportHandler.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconPipelineManager.java
- Use PipelineManagerV2Impl in Recon
- Enable ignored Recon test cases.
```
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/ContainerEndpoint.java
// TODO: Fix ME, This has to be ReconContainerManager
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/ClusterStateEndpoint.java
// TODO: Fix ME, This has to be ReconContainerManager
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/fsck/TestContainerHealthTask.java
testRun
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconIncrementalContainerReportHandler.java
testProcessICR
testProcessICRStateMismatch
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconAsPassiveScm.java
testDatanodeRegistrationAndReports
testReconRestart
``` …
=> HDDS-4894. Use PipelineManagerV2Impl in Recon and enable ignored Recon test cases.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/DownloadAndImportReplicator.java
Increase the log that helps users to use.
https://issues.apache.org/jira/browse/HDDS-4873
No test.
=> HDDS-4873. Re-replication failure throws NPE

hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/PosixRootedOzoneFileSystem.java
The question is same to: HDDS-3492
Now, we are able to support the cp operation of FUSE using o3fs via HDDS-3492. But ofs does not support, and so increase the PosixRootedOzoneFileSystem to make ofs support FUSE cp , just like what we did in HDDS-3492.
https://issues.apache.org/jira/browse/HDDS-4910
Used [hcfsfuse](https://github.com/opendataio/hcfsfuse) or hdfs-fuse to mount the OFS tested
=> HDDS-4910. Cp command not working on Ozone ofs mounted using hdfs-fuse or hcfsfuse.	

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/exception/SCMSecurityException.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/utils/CertificateCodec.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/protocolPB/SCMSecurityProtocolClientSideTranslatorPB.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMSecurityFailoverProxyProvider.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMSecurityProtocolFailoverProxyProvider.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/DefaultCAServer.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificates/utils/CertificateSignRequest.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HAUtils.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java, hadoop-hdds/interface-server/src/main/proto/ScmServerSecurityProtocol.proto, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/SCMSecurityProtocolServerSideTranslatorPB.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMSecurityProtocolServer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecureOzoneCluster.java
Implement failover proxy provider for SCM Security Server Protocol.
https://issues.apache.org/jira/browse/HDDS-4876
Updated few tests and also existing tests should cover. (For HA, later tests will be added end to end)
=> HDDS-4876. [SCM HA Security] Add failover proxy to SCM Security Server Protocol

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAUtils.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHADBTransactionBufferImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisServerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMStateMachine.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMSnapshot.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestSCMInstallSnapshotWithHA.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestStorageContainerManagerHA.java
The idea here is to add  an optional config "ozone.scm.primordial.node.id".  if the config is set, it will cause scm --init to only take effect on
the specific node and ignore scm --bootstrap cmd. Similarly, scm --init will be ignored on the non-primordial scm nodes.
If the cluster is upgraded from non-ratis to ratis version , scm --init needs to re-run for switching from non-ratis based SCM to ratis-based SCM on the primary node.
https://issues.apache.org/jira/browse/HDDS-4896
Unit tests added
=> HDDS-4896. Need a tool to upgrade current non-HA SCM node to single node HA cluster

.github/workflows/close-pending.yaml, .github/workflows/comments.yaml
Avoid versions `latest` (for runners) and `master` (for actions) in Github Actions workflows.
https://issues.apache.org/jira/browse/HDDS-4891
Tested a command comment on my fork:
https://github.com/adoroszlai/hadoop-ozone/pull/8#issuecomment-788974590
https://github.com/adoroszlai/hadoop-ozone/runs/2014250387
=> HDDS-4891. Avoid latest/master in Github Actions

hadoop-ozone/dist/src/main/smoketest/basic/ozone-shell-lib.robot, hadoop-ozone/dist/src/main/smoketest/basic/ozone-shell.robot, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/prefix/OMPrefixAddAclRequest.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/OzoneAddress.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/prefix/AddAclPrefixHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/prefix/GetAclPrefixHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/prefix/PrefixCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/prefix/PrefixUri.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/prefix/RemoveAclPrefixHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/prefix/SetAclPrefixHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/prefix/package-info.java, hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneAddress.java
Draft patch that adds the Prefix ACL CLI. 
https://issues.apache.org/jira/browse/HDDS-4905
New acceptance tests added.
=> HDDS-4905. Add prefix CLI.

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OzoneFSUtils.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientMultipartUploadV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java
This task is to implement prefix based FSO for the OzoneBucket#listParts API.
https://issues.apache.org/jira/browse/HDDS-4924
Added UTs
=> HDDS-4924. [FSO]S3Multipart: Implement OzoneBucket#listParts

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeStateManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestNodeStateManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/scm/node/TestSCMNodeMetrics.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java
Currently, when a datanode is registered with SCM, it is added as HEALTHY_READONLY, regardless of its metadata layout version. On the next heartbeat, the layout is checked against that of SCM's to determine if it matches and can be moved to HEALTHY. This Jira will add the check for layout match when the datanode is registered, as well as on each heartbeat, so nodes whose MLV matches SCM's on registration will move directly from HEALTHY_READONLY to HEALTHY without needing to wait for a heartbeat.
HDDS-4946
Recon `TestEndpoints` unit test updated to pass layout version on heartbeat.
`TestNodeStateManager` updated to test the new behavior.
=> HDDS-4946. Do not wait one heartbeat to move newly registered datanodes that match SCM's MLV from HEALTHY_READONLY to HEALTHY

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestSCMInstallSnapshotWithHA.java
The test assumes that a follower node must be behind the leader during the final validation assertions. Fix is to not start the follower server itself , so that it always lags behind the leader at any point of time.
https://issues.apache.org/jira/browse/HDDS-4957
Fixed UT
=> HDDS-4957. Fix flaky test TestSCMInstallSnapshotWithHA#testInstallCorruptedCheckpointFailure

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeInfo.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestHddsVolume.java
HDFS support reserved space for all dirs: https://github.com/apache/hadoop/blob/trunk/hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/ReservedSpaceCalculator.java
But we also need to support reserved space for single dir, because different dir maybe need different reserved space, for example, maybe only one dir needs reserved space.
https://issues.apache.org/jira/browse/HDDS-4879
new ut
=> HDDS-4879. Support reserved space for single dir

.github/workflows/post-commit.yml
Reuse [binaries created by _compile_ check](https://github.com/adoroszlai/hadoop-ozone/runs/2076199087#step:3:51) instead of [running a full build](https://github.com/apache/ozone/runs/2075932144#step:3:3997) for coverage.  This saves ~12 minutes for non-PR builds (`push`, `schedule`).
https://issues.apache.org/jira/browse/HDDS-4947
Regular CI after temporarily enabled _coverage_ check in forks.
https://github.com/adoroszlai/hadoop-ozone/actions/runs/638883332
Verified that combined [coverage](https://github.com/adoroszlai/hadoop-ozone/suites/2223105407/artifacts/46054459) is around the same as on [`master`](https://github.com/apache/ozone/suites/2222440551/artifacts/46051808):
1. download _coverage_ artifacts for both builds
2. unzip and open `all/index.html`
=> HDDS-4947. Reuse compiled binaries in combined coverage calculation

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileCreateRequestV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMAllocateBlockRequestV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequestV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRenameRequestV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3InitiateMultipartUploadRequestV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/file/OMFileCreateResponseV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMAllocateBlockResponseV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyCreateResponseV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyRenameResponseV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3InitiateMultipartUploadResponseV1.java
This task is to cleanup New FileTables when the request is not successful in the following requests.
```
-> OMAllocateBlockRequestV1,
-> OMFileCreateRequestV1,
-> OMKeyCreateRequestV1,
-> OMKeyRenameRequestV1,
-> S3InitiateMultipartUploadRequestV1
```
https://issues.apache.org/jira/browse/HDDS-4973
Existing UTs.
=> HDDS-4973. [FSO] Missed to cleanup new FileTables in OMRequests

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/SCMPipelineManager.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmDirectoryInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/WithParentObjectId.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemPrefixParser.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/PrefixParser.java
Add a tool to parse entries in the prefix format
https://issues.apache.org/jira/browse/HDDS-4790
Added a new unit test
` Type:Bucket
Path: /
DB Path: /pnfrljixwf/jprltiklhg
Object Id: 9223372036854776576
Parent object Id: 0
Type:Intermediate Dir
Path: /a
DB Path: 9223372036854776576/a
Object Id: 9223372036854777089
Parent object Id: 9223372036854776576
Type:Intermediate Dir
Path: /a/b
DB Path: 9223372036854777089/b
Object Id: 9223372036854777090
Parent object Id: 9223372036854777089
Type:Intermediate Dir
Path: /a/b/c
DB Path: 9223372036854777090/c
Object Id: 9223372036854777091
Parent object Id: 9223372036854777090
Type:Directory
Path: /a/b/c/d
DB Path: 9223372036854777091/d
Object Id: 9223372036854777092
Parent object Id: 9223372036854777091
Type:File
Path: /a/b/c/file1
DB Path: …
=> HDDS-4790. Add a tool to parse entries in the prefix format

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyAclRequestV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyAddAclRequestV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyRemoveAclRequestV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeySetAclRequestV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/acl/OMKeyAclResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/acl/OMKeyAclResponseV1.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyAclRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyAclRequestV1.java
Implement ACL api's like getAcl, addAcl, setAcl ,removeAcl in the new layout V1.
https://issues.apache.org/jira/browse/HDDS-4917
Added Unit test
=> HDDS-4917.[FSO]Implement ACL requests for new layout

hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/TrashPolicyOzone.java
This change adds 2 new configs in ozone. One thing to note here is that ozone trash is not fully independent from the hadoop-configurations i.e (`fs.trash.interval`) . This config (`fs.trash.interval`) will still control enabling/disabling of trash feature whereas the newly added configs (`ozone.fs.trash.interval` & `ozone.fs.trash.checkpoint.interval` ) would set values if trash is enabled . These will add flexibility if ozone user wants to set ozone specific interval period. 
https://issues.apache.org/jira/browse/HDDS-4971
Unit test
=> HDDS-4971. Define Ozone specific trash-interval and checkpoint interval

.github/workflows/post-commit.yml, hadoop-ozone/dev-support/checks/junit.sh, hadoop-ozone/dist/src/main/compose/ozone-mr/test.sh, hadoop-ozone/dist/src/main/compose/test-all.sh, hadoop-ozone/dist/src/main/compose/testlib.sh, hadoop-ozone/dist/src/main/compose/upgrade/test.sh, hadoop-ozone/dist/src/test/shell/compose_testlib.bats
Currently most CI checks run to completion even if other checks fail.  This is useful if we want to find as many problems as possible in a single CI run.  However, it is a waste of resources when trying to get a clean run before merge.
I propose to make checks fail faster for PR runs, but keep existing behavior for `push` and `schedule` builds.
https://issues.apache.org/jira/browse/HDDS-4933
1. Introduced unit test failure, verified that test execution is stopped after failed test if `FAIL_FAST=true`, but continues with unrelated modules if `false`:
```
$ FAIL_FAST=true ./hadoop-ozone/dev-support/checks/unit.sh
...
[INFO] Reactor Summary for Apache Hadoop Ozone Main 1.1.0-SNAPSHOT:
[INFO]
[INFO] Apache Hadoop Ozone Main ........................... SUCCESS [  0.824 s]
[INFO] Apache Hadoop …
```
=> HDDS-4933. Make CI checks fail faster

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAInvocationHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisRequest.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMStateMachine.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestSCMRatisRequest.java, hadoop-ozone/dist/src/main/compose/ozonesecure/docker-compose.yaml, hadoop-ozone/dist/src/main/compose/ozonesecure/test.sh, hadoop-ozone/dist/src/main/compose/testlib.sh
Use actual method parameter type when invoking a method, instead of deriving it from actual argument. (This will help when the actual arg param type is subclass, where as method param type is superclass. If we don't use actual method param type during invoke, we get MethodNotFoundException.
https://issues.apache.org/jira/browse/HDDS-4985
Updated docker ozone-secure to run with ratis enabled.
=> HDDS-4985. [SCM HA Security] When Ratis enable, SCM secure cluster is not working.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HAUtils.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManagerStarter.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServer.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/Gateway.java
Do not start ozone services when security and SCM HA is enabled
https://issues.apache.org/jira/browse/HDDS-4978
Tested it with docker-compose ozone-ha cluster by settingozone.security.enabled=true
Verified that all services failed to come up
Snippet of partial log.
```
om2_1       | Ozone Services cannot be started on a secure SCM HA enabled cluster
om2_1       | 2021-03-15 12:09:15,429 [shutdown-hook-0] INFO om.OzoneManagerStarter: SHUTDOWN_MSG:
om2_1       | /************************************************************
om2_1       | SHUTDOWN_MSG: Shutting down OzoneManager at om2/172.27.0.4
om2_1       | ************************************************************/
scm1_1      | Ozone Services cannot be started on a secure SCM HA enabled cluster
scm1_1      | 2021-03-15 12:09:15,686 …
```
=> HDDS-4978. [SCM HA Security] Ozone services should be disabled in SCM HA enabled and security enabled cluster

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/ProfileServlet.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/http/TestProfileServlet.java
Due to the update of Async profiler 2.0, the output format is changed from svg to html.
https://issues.apache.org/jira/browse/HDDS-4984
Local test.
=> HDDS-4984. Support async profiler 2.0

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java
- Remove redundant state check for handleDeleteChunk.
https://issues.apache.org/jira/browse/HDDS-4792
Locally test.
=> HDDS-4792. Remove redundant state check for handleDeleteChunk

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelinePlacementPolicy.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelinePlacementPolicy.java
`pick` always not null. `fallBackPickNodes` will throw exception if unable to find fall back node.
it's not a good way that throw exception in `fallBackPickNodes`. we can move the check logic to the end.
https://issues.apache.org/jira/browse/HDDS-4802
Update related tests.
=> HDDS-4802. Fix an internal variable always not null in PipelinePlacementPolicy

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/CertificateStore.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/DefaultApprover.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/DefaultCAServer.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/authority/MockCAStore.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMCertStore.java
Make storeValidCertificate idempotent.
Steps done:
1. Move checkValidCertID to the caller.
2. Perform signAndStoreCertificate under lock. (As doing sign only under lock, so it is not a huge overhead, as anyway writing to DB is done already under lock. And this approach will change in HDDS-4998. This is a temporary fix, until we have proper solution which can work across SCM nodes. This is required because without this for the secure cluster with ratis enabled after a restartt SCM will fail to start.)
https://issues.apache.org/jira/browse/HDDS-4998
=> HDDS-4998. [SCM HA Security] Make storeValidCertificate method idempotent

hadoop-ozone/dist/src/shell/ozone/ozone-functions.sh
- Removed CMS GC options for Java 15.
https://issues.apache.org/jira/browse/HDDS-4814
Tested on Java 8, Java 11, Java 15.
=> HDDS-4814. Remove CMS GC options for Java 15

hadoop-hdds/common/pom.xml, pom.xml
Upgrade `kotlin-stdlib`, transitive dependency via `jaeger-client`, to 1.4.31 (latest release).
https://issues.apache.org/jira/browse/HDDS-4996
Verified Jaeger tracing still works OK:
```
cd hadoop-ozone/dist/target/ozone-1.1.0-SNAPSHOT/compose/ozone
export COMPOSE_FILE=docker-compose.yaml:monitoring.yaml
docker-compose up -d --scale datanode=3
docker-compose exec scm ozone freon ockg -n1 -t1
open http://localhost:16686/
```
Verified JARs in Ozone package:
```
$ ls -1 hadoop-ozone/dist/target/ozone-1.1.0-SNAPSHOT/share/ozone/lib/*kotlin*
hadoop-ozone/dist/target/ozone-1.1.0-SNAPSHOT/share/ozone/lib/kotlin-stdlib-1.4.31.jar
hadoop-ozone/dist/target/ozone-1.1.0-SNAPSHOT/share/ozone/lib/kotlin-stdlib-common-1.4.31.jar
```
=> HDDS-4996. Upgrade kotlin-stdlib

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java
Use Log4j to print error messages for Datanode startup, instead of System.err
https://issues.apache.org/jira/browse/HDDS-5006
The updated result is as follows, which will be much easier for the users to find the root cause of Datanode failing to start:
=> HDDS-5006. Use Log4j to print error messages for Datanode startup

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/EmptyContentTypeFilter.java, hadoop-ozone/s3gateway/src/main/resources/webapps/s3gateway/WEB-INF/web.xml, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/TestEmptyContentTypeFilter.java
As reported the `Content-Type: ""` is not handled by Ozone S3g but handled by AWS. 
With a simple filter we can make Ozone more similar to AWS and mimic this strange behavior.
https://issues.apache.org/jira/browse/HDDS-4856
Started locally the S3g, reproduced the problem and tested with the new filter and worked well...
=> HDDS-4856. Ruby S3 SDK never get authenticated by Ozone

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/PrometheusMetricsSink.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/http/TestPrometheusMetricsSink.java
Currently, PrometheusMetricsSink adds **# TYPE** definition to each metrics line even though the metrics are repeatedly appearing in the endpoint due to differing in labels, e.g.
```
hdds_dispatcher_counter{type="PutBlock",hostname="host1"} 0
hdds_dispatcher_counter{type="ReadContainer",hostname="host1"} 0
```
Expected format is:
```
hdds_dispatcher_counter{type="PutBlock",hostname="host1"} 0
hdds_dispatcher_counter{type="ReadContainer",hostname="host1"} 0
```
https://issues.apache.org/jira/browse/HDDS-5010
Unit test added + manually.
=> HDDS-5010 Fixing Prometheus duplicated TYPE definition

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/DatanodeLayoutStorage.java
Since older versions of the code did not have a VERSION file for datanodes, use the presence of the datanode.id file to determine whether the datanode is being started on a fresh install and should use the latest layout version, or being started as part of an upgrade and should use the initial layout version.
HDDS-5023
Added fix to HDDS-4181 acceptance tests, and the MLV tests there verified that pre-finalize datanodes are using the correct MLV when pre-finalized.
=> HDDS-5023. Datanodes should always use MLV 0 when no VERSION file is present.

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientManager.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ReplicationType.java, hadoop-hdds/interface-client/src/main/proto/hdds.proto, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/keys/PutKeyHandler.java
Introduce the EC replication type. This is required by multiple other patches, it can be easier to add it as a separated patch.
For example having this EC in the enum the EcPipelineProvider can be started to implement (though ReplicationConfig is also required long-term.
https://issues.apache.org/jira/browse/HDDS-5003
It's a simple change, any incompatibilities should be detected by unit tests.
Also tested with end2end key creation with https://github.com/elek/ozone/tree/ec (where this is the first commit)
=> HDDS-5003. Introduce EC replication type

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/DatanodeAdminError.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/client/ScmClient.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocol.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/protocolPB/StorageContainerLocationProtocolClientSideTranslatorPB.java, hadoop-hdds/interface-admin/src/main/proto/ScmAdminProtocol.proto, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeDecommissionManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocolServerSideTranslatorPB.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestNodeDecommissionManager.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ContainerOperationClient.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DecommissionSubCommand.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/MaintenanceSubCommand.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/RecommissionSubCommand.java, hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestDecommissionSubCommand.java, hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestMaintenanceSubCommand.java, hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestRecommissionSubCommand.java
With the current decommission / recommission / maintenance mode commands, you can pass a list of hosts to perform the operation on. If any of these hosts fail to enter the decommission / maintenance workflow, the command gives no feedback about the error. Some of the hosts can silently fail and the only way to know is to inspect the SCM log.
The most common way a host can fail, is if a node which is undergoing maintenance is instructed to go to decommission and vice versa as this is a transition which is not allowed.
This change will allow any failed nodes to feed back to the client. If the client detects that any of the nodes have failed, details will be written to stderr and the command exit code will be non-zero.
Note that even though the exit code is non-zero, the command may have …
=> HDDS-4989. Decommission CLI should return details of nodes which fail

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/metadata/DBTransactionBuffer.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/metadata/SCMDBTransactionBufferImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/MockSCMHADBTransactionBuffer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHADBTransactionBufferImpl.java
The root cause of this warning is due to misleadingly using generic classes instead of generic methods.
The generic class specifies the real type when instantiating,  and the generic method specifies the real type when it is being called.
There are two methods under DBTransactionBuffer, the method` addToBuffer` and `removeFromBuffer`.
According to where these methods call, they are actually designed to write keys into separate tables or remove them. 
The key and value of different table are different, and so are the types. This is where generic methods work.
Thus I modified the generic methods and erased the generic class.
https://issues.apache.org/jira/browse/HDDS-4982
CI
=> HDDS-4982.Solve intellj warnings on DBTransactionBuffer

.github/workflows/post-commit.yml
Github pull requests can be created as (or converted to) draft. This is useful for gathering early feedback from other contributors about proof-of-concept code. Such code may not even compile, and style issues are usually ignored.
Since further commits are generally expected in this case, I think it makes sense to skip CI build/test until the PR is marked as "ready for review".  The goal is to save CI cycles for other issues.
If CI feedback is desired, the author should enable workflows in their fork so we can check push builds there.
https://issues.apache.org/jira/browse/HDDS-4995
Tested with a draft PR in my fork: https://github.com/adoroszlai/hadoop-ozone/pull/12
Builds:
* commit 1
* push: https://github.com/adoroszlai/hadoop-ozone/actions/runs/665327555 (cancelled manually)
* PR: …
=> HDDS-4995. Skip CI for draft pull requests

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OFSPath.java
I setup yarn cluster on ozone, and kerberos is enable. NodeManager can't download resource package in ContainerLocalizer stage, show error like this
```
2021-03-22 19:56:42,004 WARN org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ResourceLocalizationService: \{ ofs://test1/tmp/hadoop-yarn/staging/$user/.staging/job_1616412423610_0008/job.splitmetainfo, 1616414199202, FILE, null } failed: hadoop-yarn/staging/$user/.staging/job_1616412423610_0008/job.splitmetainfo: No such file or directory!
java.io.FileNotFoundException: hadoop-yarn/staging/$user/.staging/job_1616412423610_0008/job.splitmetainfo: No such file or directory!
```
The reason is that this wrong way to get user. For kerberos principal in different machine are not same, so …
=> HDDS-5019. Inconsistent tmp bucket name on different nodes when Kerberos is enabled

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisServer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisServerImpl.java
Added Timeout support for ratis requests.
https://issues.apache.org/jira/browse/HDDS-5049
Existing UT
=> HDDS-5049. Add timeout support for ratis requests in SCM HA.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainer.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java
https://issues.apache.org/jira/browse/HDDS-4987
Import container should also delete the whole container directory in case of import failure.
=> HDDS-4987. Import container should not delete container contents if container already exists

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/protocol/DatanodeDetails.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java
When SCM HA is enabled, after restart DN, the SCM may not know the full ports of that DN.
**The issue is:** 
SCMNodeManager just record the DatanodeDetails once during register. But for DN, it won’t record the admin, server, client port into DatanodeDetails until its ratis server is up. Thus there is contention here: if the register request is reported before ratis server is up, SCM won’t know full port list of that DN.
**The solution is**
If SCM HA is enabled, OzoneContainer#start() will be called multi-times from VersionEndpointTask. The first call should do the initializing job, the successive calls should wait until OzoneContainer is initialized.
https://issues.apache.org/jira/browse/HDDS-5033
CI and integration test inside tencent.
=> HDDS-5033. SCM may not be able to know full port list of Datanode after Datanode is started.

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ChunkInputStream.java, hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/DummyChunkInputStream.java, hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestChunkInputStream.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChunkBufferImplWithByteBufferList.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/IncrementalChunkBuffer.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/utils/BufferUtils.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/FilePerBlockStrategy.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/FilePerChunkStrategy.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/interfaces/ChunkManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestChunkInputStream.java
We currently wait for reading up till the Chunk EOF before releasing the buffers in ChunkInputStream (or when the stream is closed). Let's say a client reads first 3 MB of a chunk  of size 4MB and does not close the stream immediately. This would lead to the 3MB of data being cached in the ChunkInputStream buffers till the stream is closed.
After HDDS-4552, a chunk read from DN would return the chunk data as an array of ByteBuffers. After each ByteBuffer is read, it can be released. This would greatly help with optimizing memory usage of ChunkInputStream.
https://issues.apache.org/jira/browse/HDDS-4553
Added unit tests
=> HDDS-4553. ChunkInputStream should release buffer as soon as last byte in the buffer is read

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/ContainerReader.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestContainerReader.java
https://issues.apache.org/jira/browse/HDDS-5032
=> HDDS-5032. DN stopped to load containers on volume a container load exception

hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/conf/TestGeneratedConfigurationOverwrite.java, hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigurationReflectionUtil.java
- Use default config values to initialize configurations
https://issues.apache.org/jira/browse/HDDS-5035
The user's assembled fat jar works fines now.
=> HDDS-5035. Use default config values to solve generated config file conflict

hadoop-ozone/recon/pom.xml
Recon build is broken since yesterday due to a new pnpm@6.0.0 release
```
[INFO] Running 'npx pnpm config set store-dir ~/.pnpm-store' in /home/elek/projects/ozone/hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web
[INFO] npx: installed 1 in 1.057s
[INFO] ERROR: This version of pnpm requires at least Node.js v12.17
[INFO] The current version of Node.js is v12.14.1
[INFO] Visit https://r.pnpm.io/comp to see the list of past pnpm versions with respective Node.js version support.
```
This is because the frontend maven plugin uses [npx](https://www.npmjs.com/package/npx) which downloads the required tools (`pnpm` in our case) on-demand if they are not available locally.
This download uses the latest version (by default).  
I recommend using a fixed version from `pnpm` to …
=> HDDS-5066. Use fixed version from pnpm to build recon

NOTICE.txt, hadoop-ozone/dist/src/main/license/bin/NOTICE.txt
JIRA: https://issues.apache.org/jira/browse/HDDS-5064
Fixing the name of the project (use Apache Ozone instead of Apache Hadoop) to avoid any confusions.
```
cd hadoop-ozone/dist
mvn clean install -Dmaven.javadoc.skip=true  -DskipTests -Psign,dist,src -Dtar -Dgpg.keyname=$CODESIGNINGKEY
cd target
tar -O -xf hadoop-ozone-1.1.0-SNAPSHOT.tar.gz ozone-1.1.0-SNAPSHOT/NOTICE.txt | head
tar -O -xf hadoop-ozone-1.1.0-SNAPSHOT-src.tar.gz hadoop-ozone-1.1.0-SNAPSHOT-src/NOTICE.txt
```
=> HDDS-5064. Fix project name in NOTICE.txt

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/RatisReplicationConfig.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ReplicationConfig.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/StandaloneReplicationConfig.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/scm/protocol/TestReplicationConfig.java
This patch introduces the usage of `ReplicationConfig` on mater instead of using `replicationType` and `replicationFactor`. It is required by EC (see #2068 and #1973)
Using java based `ReplicationFactor` requires further changes in SCM (and OM) and we decidede to make the generic part of the refactor on master (it doesn't introduce any new logic only the java representation of the data is changing)  
https://issues.apache.org/jira/browse/HDDS-5011
It contains unit tests. It introduces only new Java classes, therefore it's safe to include.
=> HDDS-5011. Introduce Java based ReplicationConfig implementation

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestStorageContainerManagerHA.java
IN SCM HA, the primary node starts up the ratis server while other bootstrapping nodes will get added to the ratis group. Now, if all the bootstrapping SCM's get stopped, the primary node will now step down from leadership as it will loose majority. If the bootstrapping nodes are now bootstrapped again,  the bootsrapping node will try to first validate the cluster id from the leader SCM with the persisted cluster id , but as there is no leader existing, bootstrapping wil keep on failing and retrying until it shuts down. 
The issue can be very easily simulated in kubernetes deployments, where bootstrap and init cmds are run repeatedly on every restart.
The Jira aims to bypass the cluster id validation if a bootstrapping node already has a cluster id. …
=> HDDS-5062. Add a config to bypass clusterId validation for bootstrapping SCM.

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestContainerReader.java
Fix findbugs violation introduced by #2109.
https://issues.apache.org/jira/browse/HDDS-5032
1. findbugs: https://github.com/adoroszlai/hadoop-ozone/runs/2281053506
2. unit test:
```
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.366 s - in org.apache.hadoop.ozone.container.ozoneimpl.TestContainerReader
```
=> HDDS-5032. Fix findbugs

hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OzoneFSUtils.java, hadoop-ozone/dist/src/main/compose/ozone/docker-compose.yaml, hadoop-ozone/dist/src/main/compose/ozone/test.sh, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestDirectoryDeletingServiceWithFSOBucket.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneDirectory.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileInterfacesV1.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileOps.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemPrefixParser.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/OzoneContract.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientMultipartUploadV1.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestReadRetries.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestHadoopDirTreeGeneratorV1.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestObjectStoreV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketCreateRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/TestOMRequestUtils.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestBucketRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestOMBucketCreateRequestV1.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/file/TestOMDirectoryCreateRequestV1.java
Modify 'ozone.om.layout.version' config and respective classes to FSO feature specific
https://issues.apache.org/jira/browse/HDDS-4727
CI
=> HDDS-4727. [FSO]OMConfig: Modify 'ozone.om.layout.version' config

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/CertificateStore.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/HASecurityUtils.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/MockSCMHAManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAInvocationHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisServer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisServerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/SCMSecurityProtocolServerSideTranslatorPB.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestReplicationAnnotation.java
This Jira is to handle when primary SCM is not leader SCM and bootstrap is failing due to this.
https://issues.apache.org/jira/browse/HDDS-5027
Existing docker ozonesecure-ha, as modified code to use RatisClient for propagation of SCM certs.
=> HDDS-5027. [SCM HA Security] Handle leader changes during bootstrap.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemV1.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestRecursiveAclWithFSOBucket.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
This change makes recursive ACL checks on directory subpaths for directory ops like delete and rename.
https://issues.apache.org/jira/browse/HDDS-4691
Added unit tests
=> HDDS-4691. [FSO]Authorizer: OM can do recursive ACL check for subpaths

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsConfigKeys.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/x509/SecurityConfig.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/DefaultCAServer.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/authority/TestDefaultCAServer.java
Use max duration for sub-ca certs similar to self-signed root certs.
Fix description of config in ozone-default.xml
When max duration is set less than cert duration fail.
https://issues.apache.org/jira/browse/HDDS-5071
Added test
=> HDDS-5071. [SCM HA Security] Fix duration of sub-ca certs.

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/DefaultApprover.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/HASecurityUtils.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsHAURLs.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestDelegationToken.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecureOzoneCluster.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerConfiguration.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestSecureOzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMStorage.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/genesis/GenesisUtil.java
This Jira is to handle leader change between getScmInfo and getScmSignedCert.
**Problem:**
Leader is SCM1 - Returned SCMID is SCM1ID
ScmInfo returns the leader SCMID which is SCM1ID.
Leader is SCM2 - SCM ID is SCM2ID
getSCMSignedCert, during generate certificate it has a check compare the scmId passed in CSR, is same as current SCM scmID
In this case when the leader change between these 2 calls OM will fail to get a Certificate.
**Proposed Solution:**
Discuss with Xiaoyu offline, and we decided to eliminate persist scmId and check SCMID during OM startup.
We persist SCM ClusteriD for both HA/non-HA in OzoneManager.
And in SCM we remove the SCMID check and keep the SCM ClusterID check. (ClusterID is unique for a single Ozone cluster)
In SCM previously sub-CA subject looks like …
=> HDDS-5052. [SCM HA Security] Handle leader changes between SCMInfo and getSCMSigned Cert in OM/SCM.

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/ExitManager.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/NodeDetails.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/package-info.java, hadoop-hdds/pom.xml, hadoop-hdds/server-scm/pom.xml, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHANodeDetails.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMNodeDetails.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestSCMInstallSnapshotWithHA.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ha/OMNodeDetails.java
JIRA: https://issues.apache.org/jira/browse/HDDS-5057
HDDS is the block-management layer and on the top of it we created Ozone components which uses this lower-level block-management layer.
This separation is not actively used (today we don't have any other upper layer which uses HDDS, only Ozone, but it may be possible).
This dependency is also reflected by the maven project hierarchy. HDDS projects don't depend on Ozone project, only Ozone projects depends on HDDS.
If something is required for both Ozone and HDDS components it should be added to the hdds-framework (or common if it's also required by clients).
This dependency hierarchy -- which makes the project easier to maintain -- is broken since #1722.
In this PR I suggest moving the required utilities back to HDDS and remove the …
=> HDDS-5057. Remove backward direction dependency between HDDS->Ozone

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ha/RetriableWithNoFailoverException.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAUtils.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMBlockLocationFailoverProxyProvider.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMContainerLocationFailoverProxyProvider.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMSecurityProtocolFailoverProxyProvider.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/SCMSecurityProtocolServerSideTranslatorPB.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/ScmBlockLocationProtocolServerSideTranslatorPB.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocolServerSideTranslatorPB.java
Added failover and retry logic based on exception received from server.
https://issues.apache.org/jira/browse/HDDS-5050
Existing UT.
=> HDDS-5050. Add retry policy for ratis requests in SCM HA.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestDirectoryDeletingServiceWithFSOBucket.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/DirectoryDeletingService.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/AbstractOMKeyDeleteResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyDeleteResponseV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMPathsPurgeResponseV1.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeyDeleteResponse.java
Added unit test to verify whether `KeyDeletingService` deletes FSO files. The `DirectoryDeletingService` is responsible for moving subfiles of deleted directories into the `DeletedTable`. The `DeletedTable` however expects the older key format (volume/bucket/key) . The fix in this change ensures that the right key format is written into the `DeletedTable`
https://issues.apache.org/jira/browse/HDDS-5042
UT
=> HDDS-5042.[FSO] Improve KeyDeletingService to cleanup FSO files

hadoop-hdds/docs/content/design/namespace-support.md
HDDS-2939 is already added to the design doc section of the Ozone documentation, but we can update it with:
* Updating the time
* Adding the link of the overview page
* Set the status
Based on my understanding @rakeshadr had significant contribution to the original design doc, therefore his name also should be added to the authors (let me know of somebody else is still missing). 
https://issues.apache.org/jira/browse/HDDS-5092
```
cd hadoop-hdds/docs
hugo serve
firefox http://localhost:1313/design/namespace-support.html
```
=> HDDS-2939. Update statis links in the design doc section of the Ozone docs

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/AbstractDatanodeStore.java
The DN process uses around 20 GB of RSS after startup and does not release the memory even though rocksdb is closed for every container.
The capacity used by AbstractDatanodeStore is default capacity * MB. Since default capacity is 64MB therefore block cache is passed a capacity of 64TB. After the fix the DN memory usage drops to ~3GB.
https://issues.apache.org/jira/browse/HDDS-5053
Cluster deployment
=> HDDS-5053. RocksDB block cache capacity is wrongly configured

pom.xml
JIRA: https://issues.apache.org/jira/browse/HDDS-5074
Guava has a tmp directory related CVE ([CVE-2020-8908](https://github.com/advisories/GHSA-5mg8-w23w-74h3)).
Based on my best knowledge Ozone is not affected, but it's hard to explain this situation for all the automated tools. Let's just bump the version to the latest one... 
Full CI passed.
And checked if guava jar is really updated in the final distribution:
=> HDDS-5074. Bump Guava version

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/metadata/SCMMetadataStore.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/CertInfo.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/CertificateStore.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/package-info.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/authority/MockCAStore.java, hadoop-hdds/interface-client/src/main/proto/hdds.proto, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/metadata/CertInfoCodec.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/metadata/SCMDBDefinition.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/metadata/SCMMetadataStoreImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMCertStore.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestSCMStoreImplWithOldPipelineIDKeyFormat.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/server/TestSCMCertStore.java
Add timestamp to REVOKED_CERTS table in SCM db. 
Instead of modifying the definition of the existing column family, this patch introduces a new column family to make it easier for the finalize upgrade action to support upgrades from older versions.
The changes required to make it backward compatible is tracked here - https://issues.apache.org/jira/browse/HDDS-5088
The changes required to make the persistence happen via Ratis is tracked here - https://issues.apache.org/jira/browse/HDDS-5095
https://issues.apache.org/jira/browse/HDDS-4842
Unit tests
=> HDDS-4842. Add timestamp to Revoked Certs table in SCM DB

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/SCMSecurityProtocolServerSideTranslatorPB.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMSecurityProtocolServer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
Fixed the issue of SCM not coming up after the upgrade, and also SCM Client commands failing due to NPE with setX509RootCACertificate. For more info refer to Jira for stack trace.
https://issues.apache.org/jira/browse/HDDS-5078
Tested it manually. Thank You @fapifta for reporting and also for trying out the fix.
=> HDDS-5075. NPE during secure SCM initialization with HA code updated to an already existing cluster

hadoop-ozone/dist/src/main/compose/ozonesecure-ha/test.sh, hadoop-ozone/dist/src/main/smoketest/s3/commonawslib.robot
Enable s3 test suite for ozone secure-ha. In this way, the s3 test suite will run in SCM/OM HA Secure env.
https://issues.apache.org/jira/browse/HDDS-5080
Added s3 test suite to run in secure-ha.
=> HDDS-5080. enable s3 test suite for secure-ha

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMStateMachine.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeDecommissionManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestNodeDecommissionManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java
**The problem**
The decommission/maintenance info is saved in memory of SCM, and if SCM is restarted, it relearns this info during re-register of Datanode.
Only leader SCM handles the decommissionNodes(), recommissionNodes(), startMaintenanceNodes() request, and not replicate these info to follower SCM, thus when failover happens, the new leader SCM will lose this info, since they are saved in memory of previous leader SCM.
**Current status**
If a SCM is restarted, then upon re-registration the datanode will already be in DECOMMISSIONING or ENTERING_MAINTENANCE or IN_MAINTENANCE state. In that case, it needs to be added back into the monitor to track its progress.
For a registered node, the information stored in SCM is the source of truth. If SCM finds that the opState or …
=> HDDS-5090. make Decommission work under SCM HA.

hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/TestStorageContainerManagerHttpServer.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHttpServer.java
`TestStorageContainerManagerHttpServer` (and presumably `TestOzoneManagerHttpServer`) recently started failing after changing from Docker-based builder env to Github runner (in e8d001f5130e5da4f193f94e41b4b697fc9ae63f).  The problem is intermittent, but happens quite frequently in CI.
https://issues.apache.org/jira/browse/HDDS-5110
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/runs/2360374629
50x repeated run of `TestStorageContainerManagerHttpServer` (with JUnit5):
https://github.com/adoroszlai/hadoop-ozone/runs/2360503963#step:4:3982
=> HDDS-5110. TestStorageContainerManagerHttpServer fails in CI

hadoop-ozone/dist/dev-support/bin/dist-layout-stitching, hadoop-ozone/dist/src/main/assemblies/ozone-src.xml
JIRA: https://issues.apache.org/jira/browse/HDDS-5084
During the ozone-1.1.0 vote I realized that `HISTORY.md`/`SECURITY.md`/`CONTRIBUTING.md` files are missing from the `bin` and `src` artifacts. I think they include very useful information and would be better to include them in the release artifacts.
```
mvn clean install -Dmaven.javadoc.skip=true -DskipTests -Psign,dist,src -Dtar -Dgpg.keyname=$CODESIGNINGKEY
cd hadoop-ozone/dist/target/
tar tzf hadoop-ozone-1.1.0-SNAPSHOT.tar.gz
tar tzf hadoop-ozone-1.1.0-src-SNAPSHOT.tar.gz
```
=> HDDS-5084. Include HISTORY.md/SECURITY.md/CONTRIBUTING.md in the release artifacts.

.github/workflows/cancel-ci.yaml
Currently most CI checks run to completion even if other checks fail.  HDDS-4933 added cancellation for concurrent builds of the same check (eg. _acceptance_).  This change extends the separate _Cancelling_ workflow introduced in HDDS-4988, to abort PR builds with any checks already failing.  (Eg. avoid waiting 1.5 hours for acceptance if checkstyle has error).
https://issues.apache.org/jira/browse/HDDS-5026
Tested similar change in my fork.
=> HDDS-5026. Cancel failing PR workflow runs

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/upgrade/HDDSLayoutVersionManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/upgrade/ScmHAUnfinalizedStateValidationAction.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/upgrade/TestSCMHAUnfinalized.java
Make sure that if a pre-finalized cluster (whose metadata layout version is behind SCM HA) is started with an SCM HA enabled configuration, SCM will fail to start with an error.
HDDS-5086
Unit test added.
=> HDDS-5086. Add pre-finalize validation action for SCM HA.

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneAtRestEncryption.java
Maintain a KeyProvider cache for Ozone RPC client and ensure Key provider is closed upon removal from the cache. 
https://issues.apache.org/jira/browse/HDDS-5087
UT added.
=> HDDS-5087. Ozone RPC client leaks KeyProvider instances.

hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMSecurityProtocolFailoverProxyProvider.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DefaultCertificateClient.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HAUtils.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/HASecurityUtils.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMSnapshotProvider.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
Following changes are done:
1. For Datanode used max retryCount so that Datanode will retry for ever during startup to get Signed Cert from SCM.
2. For OM/SCM used fixed duration to give response to end-user performing init/bootstrap.
3. Updated to use max retryCount for fetching CAList which is required during DN/OM startup.
4. Updated to use max retry count for get certificate From SCM which is used in BlockToken Verification/OMToken Verification when cert is not there in its local cache.
https://issues.apache.org/jira/browse/HDDS-5116
Tested manually, started OM/DN before SCM Startup and they are retrying more than default 15 retry count.
docker-compose up --build om1 datanode1
After some time greater than default retry completed start scm
docker-compose up --build scm1.org scm2.org …
=> HDDS-5116. Secure datanode/OM may exit if it cannot connect to SCM.

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/TestOMRequestUtils.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCommitRequest.java
This task is to improve the key location updation logic during commit block.
https://issues.apache.org/jira/browse/HDDS-5061
Added UT.
=> HDDS-5061. Improve block commit

hadoop-ozone/dist/src/main/compose/ozonesecure/docker-compose.yaml, hadoop-ozone/dist/src/main/compose/ozonesecure/test.sh, hadoop-ozone/dist/src/main/compose/testlib.sh
As [spotted](https://github.com/apache/ozone/pull/2052#discussion_r616570112) by @elek, `ozonesecure` acceptance test is run twice: with SCM Ratis enabled and disabled.  This doubles execution time.  Now that `ozonesecure-ha` acceptance test also has SCM HA (implies Ratis enabled), I don't think it's necessary to run `ozonesecure` (single SCM) with Ratis enabled.
https://issues.apache.org/jira/browse/HDDS-5125
Now _acceptance (secure)_ is only 1 hour:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/768286122
=> HDDS-5125. Only test ozonesecure with SCM Ratis disabled

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAUtils.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/Storage.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisServerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMStorageConfig.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManager.java
Fixed SCM reinitialization logic 
https://issues.apache.org/jira/browse/HDDS-5122
Modified UTs
=> HDDS-5122. SCM Reinitialization can end up leaking Ratis Segmented RaftLogWorker threads

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/util/RFC1123Util.java
jira: HDDS-5124. Use existing constants for org.apache.hadoop.ozone.s3.endpoint.ObjectEndpoint#addLastModifiedDate
https://issues.apache.org/jira/browse/HDDS-5124?filter=-2
The "GMT" already defined in OzoneConsts, so why not user it.
we can use Ozone.Consts.OZONE_TIME_ZONE instead of "GMT"
=> HDDS-5124. Use OzoneConsts.OZONE_TIME_ZONE instead of "GMT"

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/InterSCMGrpcClient.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/InterSCMGrpcProtocolService.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMNodeDetails.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMSnapshotDownloader.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMSnapshotProvider.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMStateMachine.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMInstallSnapshot.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestSCMInstallSnapshotWithHA.java, pom.xml
Fixed install snapshot behaviour
https://issues.apache.org/jira/browse/HDDS-5103
Enabled Unit tests
=> HDDS-5103. Fix Install Snapshot Mechanism in SCMStateMachine.

.github/workflows/post-commit.yml
Default timeout for one GitHub action job is 6 hours. It turned out that in some unfortunate case the acceptance tests were pending at this time, for example in https://github.com/apache/ozone/runs/2053572861?check_suite_focus=true
We need to turn on stricter timeouts for each of our jobs to avoid unnecessary build time usage.
https://issues.apache.org/jira/browse/HDDS-5131
Executed the full build on my fork.
https://github.com/elek/ozone/actions/runs/776651574
=> HDDS-5131. Use timeout in github actions

.github/workflows/post-commit.yml, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/TestStorageContainerManagerHttpServer.java, hadoop-ozone/dev-support/checks/_lib.sh, hadoop-ozone/dev-support/checks/docs.sh
Currently docs are implicitly built in _integration_ checks.  (They used to be built in few other checks, too, but those no longer have Hugo available.)  If there is a syntax error in the docs, all of these fail due to the same cause.  Also, one needs to dig into build logs to find any problem, because Hugo errors are not collected.
This PR adds a separate check for building `hadoop-hdds/docs` with Hugo, collecting summary of Hugo-specific failures in the regular way.
https://issues.apache.org/jira/browse/HDDS-4889
```
> Run hadoop-ozone/dev-support/checks/docs.sh
...
Installed hugo in /home/runner/work/hadoop-ozone/hadoop-ozone/.dev-tools/hugo
~/work/hadoop-ozone/hadoop-ozone
Start building sites … 
| EN | ZH  
-------------------+----+-----
Pages            | 81 | 49  
Paginator pages …
```
=> HDDS-4889. Add simple CI check for docs

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMNodeInfo.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/TestHddsUtils.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/datanode/InitDatanodeState.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/TestHddsServerUtil.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/TestHddsServerUtils.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestHddsClientUtils.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerRestInterface.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/conf/StorageContainerManagersCommandHandler.java
Make HA config when SCM HA is enabled to figure out SCM client address.
https://issues.apache.org/jira/browse/HDDS-5127
Added test.
=> HDDS-5127. Fix getServiceList when SCM HA is enabled

hadoop-ozone/dist/src/main/compose/ozone/test.sh
Today we execute ozonefs/ozonefs.robot with compose/ozone/test.sh with multiple matrix parameters:
```
for scheme in ofs o3fs; do
for bucket in link bucket; do
#test ozonefs/ozonefs.robot
done
done
```
HDDS-2939 doubles these 4 executions with introducing the layout parameter (simple vs prefix). At the same time the execution time of acceptance (unsecure) tests are increased from 37 minutes to 57 minutes.
I would suggest suggesting to use only selected tests from this 2 x 2 x 2 matrix.
For example:
```
bucket / o3fs / prefix
link / ofs / simple
bucket / ofs / prefix
```
https://issues.apache.org/jira/browse/HDDS-5093
CI tests. Checked the artifacts (new test names are included) and compared the time. 
Build times: 55 min (before patch) ,47 min (after this patch), 41 min (master)
But this …
=> HDDS-5093. [FSO] Reducing time of ozonefs acceptance testmatrix

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMStateMachine.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestSCMInstallSnapshotWithHA.java, pom.xml
Bump ratis version to 2.1.0-ff8aa66-SNAPSHOT
https://issues.apache.org/jira/browse/HDDS-5148
CI
=> HDDS-5148. Bump ratis version to 2.1.0-ff8aa66-SNAPSHOT

hadoop-hdds/common/pom.xml, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ratis/ServerNotLeaderException.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/ratis/TestServerNotLeaderException.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMBlockLocationFailoverProxyProvider.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMContainerLocationFailoverProxyProvider.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMSecurityProtocolFailoverProxyProvider.java
When hostname is having "." the regex is not matching properly with suggested leader and fail over is failing with below exception.
```
Caused by: java.util.NoSuchElementException: No value present
at java.util.Optional.get(Optional.java:135)
at org.apache.hadoop.hdds.scm.proxy.SCMBlockLocationFailoverProxyProvider.performFailoverToAssignedLeader(SCMBlockLocationFailoverProxyProvider.java:166)
at org.apache.hadoop.hdds.scm.proxy.SCMBlockLocationFailoverProxyProvider$1.shouldRetry(SCMBlockLocationFailoverProxyProvider.java:273)
at 
```
https://issues.apache.org/jira/browse/HDDS-5152
Added tests
=> HDDS-5152. Fix Suggested leader in Client.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeDecommissionManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestNodeDecommissionManager.java
If you run the decommission or "enter maintenance" command on a node which is already dead, then it should immediately go to the DECOMMISSIONED or IN_MAINTENANCE state. As the node is already dead, there is no way to replicate its containers in a controlled way, and hence the decommission process does not need to run.
https://issues.apache.org/jira/browse/HDDS-5153
New unit tests
=> HDDS-5153. Decommissioning a dead node should complete immediately

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneVolume.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OzoneAclUtil.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/security/acl/IAccessAuthorizer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/BucketEndpoint.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ListMultipartUploadsResult.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/PutBucketAclRequestUnmarshaller.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/S3Acl.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/S3BucketAcl.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/S3Owner.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/exception/S3ErrorTable.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/ObjectStoreStub.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneBucketStub.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneVolumeStub.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestBucketAcl.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestBucketList.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestBucketPut.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestPermissionCheck.java, hadoop-ozone/s3gateway/src/test/resources/groupAccessControlList.xml, hadoop-ozone/s3gateway/src/test/resources/userAccessControlList.xml
https://issues.apache.org/jira/browse/HDDS-4585 
Design document:
https://issues.apache.org/jira/browse/HDDS-4550
=> HDDS-4585. Support bucket acl operation in S3g

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneKeyLocation.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
add keyOffset in the key info result
https://issues.apache.org/jira/browse/HDDS-4983
example:sh key info /vol1/bucket1/key3
```
{
"bucketName" : "bucket1",
"name" : "key3",
"dataSize" : 644930593,
"creationTime" : "2021-04-20T09:22:15.206Z",
"modificationTime" : "2021-04-20T09:22:20.869Z",
"replicationType" : "RATIS",
"replicationFactor" : 3,
"ozoneKeyLocations" : [ {
"containerID" : 3,
"localID" : 107544261427200003,
"length" : 268435456,
"offset" : 0,
"keyOffset" : 0
}, {
"containerID" : 4,
"localID" : 107544261427200004,
"length" : 268435456,
"offset" : 0,
"keyOffset" : 268435456
}, {
"containerID" : 5,
"localID" : 107544261427200005,
"length" : 108059681,
"offset" : 0,
"keyOffset" : 536870912
} ],
"fileEncryptionInfo" : null
}
```
=> HDDS-4983. Display key offset for each block in command key info

hadoop-ozone/dist/src/shell/ozone/ozone
The option of "OZONE_OPTS" was assigned twice for Freon and SH, so the error of "duplicate jdwp options" prompts. Need the remove the duplicate assignment of "OZONE_OPTS".
https://issues.apache.org/jira/browse/HDDS-5166
Manually test. The following command works normal now.
```
export OZONE_FREON_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5011
bin/ozone freon randomkeys --num-of-volumes=1 --num-of-buckets 1 --num-of-keys 10  --replication-type=RATIS --factor=THREE
export OZONE_SH_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5011
bin/ozone sh volume ls /
```
=> HDDS-5166. Remove duplicate assignment of OZONE_OPTS for freon and sh

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMStartupWithLayout.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
Start an existing OM using new PREFIX configuration layout format, which(OM) already contains old buckets.
**Scenario:**
1. Start cluster with configs,
OZONE-SITE.XML_ozone.om.enable.filesystem.paths=true
OZONE-SITE.XML_ozone.om.metadata.layout=simple
2. create /vol1/bucket1/dir1/dir2/key1
3. Stop OM
4. Update config OZONE-SITE.XML_ozone.om.metadata.layout=prefix
5. Start OM.
Output: Failed to start OM as there is a bucket with old layout format.
https://issues.apache.org/jira/browse/HDDS-5094
Added unit test case.
=> HDDS-5094. [FSO] Fail OM startup when turn on prefix layout with old buckets

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeStateManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestNodeStateManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java
Fix race condition in NodeStateManager#addNode that gave the background pipeline creator thread a small window of time to use newly added healthy readonly nodes in pipelines.
HDDS-5170
Condition was discovered because of flaky unit test `TestSCMNodeManager#testScmLayoutOnRegister`. Without the patch, the test fails after 15-30 consecutive runs. With the patch, I was able to do 400 consecutive runs and did not see any failures.
`TestSCMNodeManager#testScmLayoutOnHeartbeat` was also checked just to be safe. It is not flaky both before and after the patch based on 200 consecutive runs (which took about half an hour).
=> HDDS-5170. Race condition in NodestateManager#addNode allows datanodes with lower MLV to be used in pipelines.

hadoop-ozone/dist/src/main/compose/testlib.sh
If any acceptance test fails, `test-all.sh` (and in turn `acceptance.sh`) should exit with error code (1).  But if a successful test is run after a failing one, it will now wrongly exit with success (0).
```
$ export OZONE_TEST_SELECTOR='failing1\|ozone-csi'
$ ./hadoop-ozone/dev-support/checks/acceptance.sh
...
$ echo $?
0
```
The problem is that the variable `ret` in the functions `run_test_scripts` and `run_test_script` are intended to be independent, but are the same (global) one.
https://issues.apache.org/jira/browse/HDDS-5182
```
$ export OZONE_TEST_SELECTOR='failing1\|ozone-csi'
$ ./hadoop-ozone/dev-support/checks/acceptance.sh
...
$ echo $?
1
```
=> HDDS-5182. Acceptance test may exit with 0 in case of error

CONTRIBUTING.md
Update link of wiki pages.
https://issues.apache.org/jira/browse/HDDS-5178
No test.
=> HDDS-5178. Update project information of Contribution guideline

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ECReplicationConfig.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/pipeline/Pipeline.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/pipeline/MockPipeline.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipeline.java, hadoop-hdds/interface-client/src/main/proto/hdds.proto, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/ScmBlockLocationProtocolServerSideTranslatorPB.java
HDDS-5047 / #2096 started to use `ReplicationConfig` in `Pipeline` and pipeline related SCM service on master. `ReplicationConfig` was introduced in HDDS-5011, but it has two versions one for master #(2089) and one for the EC branch.(#2068)
Merging master after HDDS-5047 requires small modification in the code to make HDDS-5047 compatible the ec version of HDDS-5011:
During the proto serialization / deserialization we should use optional ECReplicationConfig (if exists).
https://issues.apache.org/jira/browse/HDDS-5145
With CI, The EC branch has compilation failure without this patch.
=> HDDS-5145. Extend Pipline/ReplicationConfig refactor with ECReplicationConfig

pom.xml
Bump `commons-io` version to latest.
https://issues.apache.org/jira/browse/HDDS-5185
https://github.com/adoroszlai/hadoop-ozone/actions/runs/809654660
=> HDDS-5185. Update commons-io to 2.8.0

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeConfiguration.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/MutableVolumeSet.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/TestDatanodeConfiguration.java
Make datanode periodic disk check interval configurable, originally it is fixed 15min.
https://issues.apache.org/jira/browse/HDDS-5159
extended existing ut
manual test
=> HDDS-5159. Make periodic disk check interval configurable.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
The name of volume created in `testListBucketsOnEmptyVolume` or `testListKeyOnEmptyBucket` might contain the prefix used in `testListVolume`:
```
... Creating Volume: vol-71454, ...
...
... Creating Volume: vol-714-a-0-78727, ...
```
which leads to unexpected number of volumes with that prefix:
```
Tests run: 80, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 175.065 s <<< FAILURE! - in org.apache.hadoop.ozone.client.rpc.TestOzoneRpcClient
testListVolume  Time elapsed: 0.086 s  <<< FAILURE!
java.lang.AssertionError: expected:<20> but was:<21>
...
at org.apache.hadoop.ozone.client.rpc.TestOzoneRpcClientAbstract.testListVolume(TestOzoneRpcClientAbstract.java:1867)
```
This fix simply changes to fix volume name for `testListBucketsOnEmptyVolume` and a different fix prefix for …
=> HDDS-5192. Intermittent failure in TestOzoneRpcClient due to volume name conflict

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAUtils.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
SCM init should work when primordial node is specified in the config and SCM HA is not enabled.
https://issues.apache.org/jira/browse/HDDS-5186
Existing Tests
=> HDDS-5186. If primordial SCM id is set, a non-HA cluster can not be initialized.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocol.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/protocolPB/StorageContainerLocationProtocolClientSideTranslatorPB.java, hadoop-hdds/interface-admin/src/main/proto/ScmAdminProtocol.proto, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerStateManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocolServerSideTranslatorPB.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconContainerManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconContainerReportHandler.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconIncrementalContainerReportHandler.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/StorageContainerServiceProvider.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/StorageContainerServiceProviderImpl.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestContainerEndpoint.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/AbstractReconContainerManagerTest.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconContainerManager.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconIncrementalContainerReportHandler.java
in my test environment,  400000 containers exist. when bootstrap a new recon, every container will be checked and added to recondb.but , for now , recon check all the containers in a container report one by one , and each check will take a rpc call to scm. this is too slow and in my test environment , it leads to recon oom, because too many containers to be consumed are waitting in the message queue . It is better for recon to check new containers of a container report with batch.
https://issues.apache.org/jira/browse/HDDS-5126
unit test
=> HDDS-5126. Recon should check new containers of a container report with batch

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAUtils.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMContainerLocationFailoverProxyProvider.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMSecurityProtocolFailoverProxyProvider.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HAUtils.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecureOzoneCluster.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestFailoverWithSCMHA.java
For AccessControlException do not perform failover, as even with retry it would yield the same result.
https://issues.apache.org/jira/browse/HDDS-5183
Added tests and also ran a sample test in docker.
```
bash-4.2$ ozone admin scm roles --service-id=scmservice
Exception encountered while connecting to the server
org.apache.hadoop.security.AccessControlException: Client cannot authenticate via:[KERBEROS]
at org.apache.hadoop.security.SaslRpcClient.selectSaslClient(SaslRpcClient.java:173)
at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:390)
at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:622)
at org.apache.hadoop.ipc.Client$Connection.access$2300(Client.java:413)
at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:822)
at …
```
=> HDDS-5183. For AccessControlException do not perform failover.

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestSchemaOneBackwardsCompatibility.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/testutils/BlockDeletingServiceTestImpl.java
Fixes for intermittent unit test failures found in  hdds.container-service _TestSchemaOneBackwardsCompatibility_ and in _TestBlockDeletingService_.  Current implementation for unit tests uses the _BackgroundService_ for block deletion.  This service uses a thread pool executor that uses worker thread tasks that run asynchronously.  The unit test callers for this service 'start' the _PeriodicalTask_ of the _BackgroundService_ and expect the workers to finish deleting blocks when they do checks for expected results.  The thread pool executor runs the worker tasks, _however_ they do not run to completion prior to returning control to the unit test callers.  This leads to an **intermittent error** due to results not ready when the unit test caller checks for expected results.
Patch …
=> HDDS-5099. Error with unit test for hdds.container-service TestSchemaOneBackwardsCompatibility

hadoop-ozone/dist/src/shell/ozone/ozone
Fix an issue where `OZONE_*_OPTS` are not actually passed to daemon invocations.
[HDDS-5197](https://issues.apache.org/jira/browse/HDDS-5197)
Partially tested in one of datanodes in our production environment.
=> HDDS-5197. Pass option variables to OZONE_OPTS before adding default GC opts

pom.xml
[Maven 3.8.1](https://maven.apache.org/docs/3.8.1/release-notes.html) blocks http repos by default for security.  Github Actions runner environment was [already updated](https://github.com/actions/virtual-environments/commit/08dd8f3a6aca4ced2b7315b316f2e052e40af105) to this new version.  We need to fix the JBoss repo definition in `pom.xml`, either by changing to https or removing it completely.  I have tried building without Maven cache both ways, both were OK, all dependencies were found elsewhere.  So I think it is safe to remove it.
https://issues.apache.org/jira/browse/HDDS-5198
CI, with [Maven cache temporarily removed](https://github.com/adoroszlai/hadoop-ozone/commit/c4f3dfe701613ee864e4e90772a482af3d594d18):
https://github.com/adoroszlai/hadoop-ozone/actions/runs/827254915
``` …
```
=> HDDS-5198. Remove JBoss repo definition

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/InterSCMGrpcClient.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/MockSCMHAManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMSnapshotDownloader.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMSnapshotProvider.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMStateMachine.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMInstallSnapshot.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestSCMInstallSnapshotWithHA.java
As mentioned in https://issues.apache.org/jira/browse/RATIS-1370
During `notifyInstallSnapshotFromLeader`, `StateMachineUpdater` may call `applyTransactions` when StateMachine is in PAUSED state.
Just divide snapshot related work into `notifyInstallSnapshotFromLeader` and `reinitialize` for `SCMStateMachine`.
During `notifyInstallSnapshotFromLeader`, SCM just downloads snapshot but not modify StateMachine, since StateMachineUpdater is in RUNNING state, may call applyTransactions during this period.
During `reinitialize`, SCM can safely reload the StateMachine, such as rocksdb and in-memory state. During this period, StateMachineUpdater is in RELOAD state, thus there will be no contention between SCM and StateMachineUpdater.
https://issues.apache.org/jira/browse/HDDS-5173
CI
=> HDDS-5173. Divide snapshot related work into notifyInstallSnapshotFromLeader and reinitialize for SCMStateMachine.

hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestRatisPipelineProvider.java
`testCreatePipelineWithFactorThree` fails intermittently with two 3-nodes pipeline being assigned to the same set of nodes, while only a single pipeline per datanode is allowed.  The problem is that `MockNodeManager` ignores this config and has a separate variable, which tests need to set.  Similar setting in other test:
https://github.com/apache/ozone/blob/8e8a01dfd20899cd9dc95ab3de744b636a807ab2/hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelinePlacementPolicy.java#L91-L92
https://issues.apache.org/jira/browse/HDDS-5207
100x repeated `TestRatisPipelineProvider`:
https://github.com/adoroszlai/hadoop-ozone/runs/2549825702
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/829491474
=> HDDS-5207. Intermittent failure in TestRatisPipelineProvider#testCreatePipelineWithFactorThree

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisServerImpl.java
Make roles command work when SCM host is unresolvable.
https://issues.apache.org/jira/browse/HDDS-5200
Manually verified the fix.
```
docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED              STATUS              PORTS                                              NAMES
d3c720b431aa        apache/ozone-runner:20210329-1   "/usr/local/bin/dumb…"   About a minute ago   Up About a minute   0.0.0.0:32787->9876/tcp                            ozone-ha_scm1_1
ddf8f150611b        apache/ozone-runner:20210329-1   "/usr/local/bin/dumb…"   About a minute ago   Up About a minute   0.0.0.0:32789->9862/tcp, 0.0.0.0:32786->9874/tcp   ozone-ha_om1_1
f3a1418485bd        apache/ozone-runner:20210329-1   "/usr/local/bin/dumb…"   About a minute ago   Up About …
```
=> HDDS-5200. Fix scm roles command if one of the host is unresolvable.

pom.xml
JIRA: https://issues.apache.org/jira/browse/HDDS-5214
Use logical release name 'glacier' for Ozone 1.2 as discussed during the community sync. (Next letter was G and Glacier was the obvious choice)
```
./ozone version                             
//////////////                 
////////////////////              
////////     ////////////////        
//////      ////////////////          
/////      ////////////////  /         
/////            ////////   ///         
////           ////////    /////        
/////         ////////////////           
/////       ////////////////   //        
////     ///////////////   /////        
/////  ///////////////     ////         
/////       //////      /////          
//////   //////       /////           
///////////     //////// …
```
=> HDDS-5214. Bump logical release name of Ozone 1.2

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntryPool.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerProtocolServerSideTranslatorPB.java
On the OM server side, NotLeaderException and LeaderNotReadyExceptions can be suppressed. Otherwise, OM1 log is flooded with NotLeaderExceptions as clients always try OM1 before moving to the next OM. Instead we can change these exception logs to DEBUG.
Some BlockOutputStream and BlockOutputStreamEntryPool logs should be DEBUG level instead of INFO. For example, block allocation with an exclude list need not be logged at INFO level.
https://issues.apache.org/jira/browse/HDDS-5164
No new tests. Changing only LOG levels.
=> HDDS-5164. Improve client and server logging.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/utils/HddsVolumeUtil.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/HddsVolume.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/MutableVolumeSet.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainer.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/BlockUtils.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/ChunkUtils.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/ChunkManagerDispatcher.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/ChunkManagerFactory.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/FilePerBlockStrategy.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/FilePerChunkStrategy.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerPersistence.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/ChunkLayoutTestInfo.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/helpers/TestChunkUtils.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/impl/TestFilePerChunkStrategy.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/DatanodeTestUtils.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/volume/TestDatanodeHddsVolumeFailureDetection.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/ChunkManagerDiskWrite.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/containergenerator/GeneratorDatanode.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/genesis/BenchmarkChunkManager.java
Check hdds volume on io exceptions to detect bad disks quickly.
For now ozone only has a periodic disk checker which only check for disk errors at fixed interval.
https://issues.apache.org/jira/browse/HDDS-5089
manual tests
a new integration test
=> HDDS-5089. On-demand disk checker for hdds volume

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/ha/OMFailoverProxyProvider.java
Currently in an OM HA setup, client by default does 15 failovers before giving up. If there are 3 OMs and a leader has not been elected yet, then the client will try each OM in a round robin way, wait for 2 secs and then try all the OMs again. This gives the client around 10 seconds before it exhausts all its failover attempts and fails. 
This Jira proposes to increase the failover attempts to 100.
https://issues.apache.org/jira/browse/HDDS-5059
=> HDDS-5059. Increase number of client retries/ failovers to OMs

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/ScmBlockLocationProtocolServerSideTranslatorPB.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocolServerSideTranslatorPB.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
SCM server should start accepting requests when it is leader and isLeaderReady.
We need isLeaderReady also because Statemachine should apply all the log committed transactions to start accepting requests.
So, instead of scmContext#isLeader, use scm#checkLeader.
https://issues.apache.org/jira/browse/HDDS-5202
Existing CI
=> HDDS-5202. Use scm#checkLeader before processing client requests .

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerData.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/OzoneDebug.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/container/ContainerCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/container/ExportSubcommand.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/container/InfoSubcommand.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/container/ListSubcommand.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/container/package-info.java
Add a subcommand to debug to get datanode local container info,
get as much information as possible, a bit different from `admin container info`
https://issues.apache.org/jira/browse/HDDS-4976
manual tests
=> HDDS-4976. Add container replica related commands to debug

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/DBCheckpointServlet.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDBCheckpointServlet.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMDbCheckpointServlet.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMDbCheckpointServlet.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMDBCheckpointServlet.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
Update OM DB checkpoint servlet to enforce access restrictions only when both ACL and SPNGEO auth are enabled. Also, updated the rules to allow recon by default.
https://issues.apache.org/jira/browse/HDDS-5165
Unit tests and tested in a real cluster.
=> HDDS-5165. OM DB checkpoint servlet not accessible in a secure cluster

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerRocksDBLogging.java, pom.xml
now , the rocksdb version used in ozone is 6.8.1, which is build on Apr 16 , 2020.
this PR bumps rockdsb to 6.20.3, which is build on May 5, 2021, and includes many new bug-fix
https://issues.apache.org/jira/browse/HDDS-5208
no need to add additional tests
=> HDDS-5208. bump rocksdb version to 6.20.3

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/OzoneClientProducer.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/TestOzoneClientProducer.java
- Return WebApplicationException instead of OS3Exception in OzoneClientProducer.
https://issues.apache.org/jira/browse/HDDS-5128
Test passed with S3-SDK requests. Can test with the following Steps:
1. Remove credentials. 
```
mv ~/.aws ~/.aws_bak
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
```
2. List objects using S3 SDK via S3gateway.
```
AmazonS3 s3 = AmazonS3ClientBuilder.standard()
.withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://localhost:9878", Regions.DEFAULT_REGION.getName()))
.withPathStyleAccessEnabled(true)
.build();
ListObjectsV2Result result = s3.listObjectsV2(bucket_name);
```
3. Before the patch the error message is as follows:
```
Server Error (Service: Amazon S3; Status Code: 500; Error Code: 500 Server Error; Request ID: null; S3 …
```
=> HDDS-5128. Return specific error messages for S3-SDK

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java
Currently Ozone datanodes use a default block cache capacity of 64MB. We can increase the default block cache capacity to a higher value like 512MB..1GB.
https://issues.apache.org/jira/browse/HDDS-5176
Existing UT.
=> HDDS-5176. Increase default block cache capacity for Datanodes

hadoop-hdds/docs/content/interface/ReconApi.md, hadoop-hdds/docs/content/interface/ReconApi.zh.md, hadoop-ozone/dev-support/checks/_lib.sh
Hugo 0.83 is reported to be failing while generating Ozone docs. See https://issues.apache.org/jira/browse/HDDS-5189 for more details.
https://issues.apache.org/jira/browse/HDDS-5189
```
./hadoop-ozone/dev-support/checks/docs.sh
```
+ full ci test on my fork
=> HDDS-5189. fix markdown files to make them hugo83 compatible (and valid)

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMBlockLocationFailoverProxyProvider.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMContainerLocationFailoverProxyProvider.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMSecurityProtocolFailoverProxyProvider.java
In OzoneManager, SCM client is shared across RpcHandler threads.
Where we have observed that failOver across multiple threads causing failover to happen incorrectly on same SCM and is exhausting retry count.
And also one thing I have observed is
If we observe the error is no route to scm3, but retry happened on scm1/172.31.0.9:9863
```
2021-05-11 05:59:53,202 [IPC Server handler 10 on default port 9862] INFO retry.RetryInvocationHandler: com.google.protobuf.ServiceException: java.net.NoRouteToHostException: No Route to Host from  om1/172.31.0.11 to scm3:9863 failed on socket timeout exception: java.net.NoRouteToHostException: No route to host; For more details see:  http://wiki.apache.org/hadoop/NoRouteToHost, while invoking $Proxy32.send over nodeId=scm1,nodeAddress=scm1/172.31.0.9:9863 …
```
=> HDDS-5216. Fix race condition causing SCM failOverProxy which is causing failover wrongly.

.github/workflows/post-commit.yml, hadoop-ozone/dev-support/checks/build.sh, hadoop-ozone/dev-support/checks/junit.sh
Disable Maven HTTP connection pooling to avoid intermittent [download errors](https://github.com/apache/ozone/runs/2454639477#step:6:2576) like:
```
[ERROR] Plugin org.apache.maven.plugins:maven-shade-plugin:3.2.4 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-shade-plugin:jar:3.2.4: Could not transfer artifact org.apache.maven.plugins:maven-shade-plugin:pom:3.2.4 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-shade-plugin/3.2.4/maven-shade-plugin-3.2.4.pom: Connection timed out (Read failed)
```
The solution is taken from https://github.com/actions/virtual-environments/issues/1499#issuecomment-689467080 and …
=> HDDS-5187. Avoid Maven connection errors in CI

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAConfiguration.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/MockSCMHAManager.java, hadoop-ozone/dist/src/main/compose/ozone-ha/docker-compose.yaml, hadoop-ozone/dist/src/main/compose/ozonesecure-ha/docker-compose.yaml, hadoop-ozone/dist/src/main/smoketest/admincli/scmha.robot
Currently, by default scm ratis and scm grpc ports are defined to be 9865 and 9866 by default. These ports are also used for datanode https and datanode ports for hdfs by default hence may lead to port conflict issue in ozone deployment alongside hdfs . These ports are replaced with port numbers 9894 and 9895 respectively.
https://issues.apache.org/jira/browse/HDDS-5234
Tested manually on a docker scm ha cluster
=> HDDS-5234. Change default grpc and ratis ports for scm ha

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/pipeline/Pipeline.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/pipeline/MockPipeline.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipeline.java
ReplicaIndex and ReplicationConfig were added to the Pipeline class, but we missed loading the serialized ReplicaIndex when a Pipeline is created from the protobuf message.
https://issues.apache.org/jira/browse/HDDS-5222
New unit test.
=> HDDS-5222. ReplicaIndex in Pipeline should be deserialized in the protobuf message

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/SCMCommonPlacementPolicy.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestContainerPlacementFactory.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementCapacity.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackAware.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRandom.java
When use placement policy to choose datanodes, we should check whether a datanode has a volume that
has enough space to hold the container, not check the space from all volumes together, because a container
could only be on a single volume not spread across volumes.
https://issues.apache.org/jira/browse/HDDS-5209
extended existing ut.
=> HDDS-5209. Datanode hasEnoughSpace check should apply on volume instead of global DN

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HAUtils.java
Wait forever to obtain the CA list.
And also made retry wait configurable.
https://issues.apache.org/jira/browse/HDDS-5246
Tested with docker-compose ozonesecure-ha (with few changes to remove WAITFOR scm3.org)
```
docker-compose up scm1.org
docker-compose om1
docker-compose datanode1
```
```
om1_1        | 2021-05-19 09:02:16,082 [main] INFO utils.RetriableTask: Execution of task getCAList failed, will be retried in 10000 ms
om1_1        | 2021-05-19 09:02:26,102 [main] INFO utils.HAUtils: Expected CA list size 4, where as received CA List size 2.
om1_1        | 2021-05-19 09:02:26,103 [main] INFO utils.RetriableTask: Execution of task getCAList failed, will be retried in 10000 ms
om1_1        | 2021-05-19 09:02:36,147 [main] INFO utils.HAUtils: Expected CA list size 4, where as received …
```
=> HDDS-5246. Wait for ever to obtain CA list which is needed during OM/DN startup

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisServerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMStateMachine.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManager.java
…iled.
Initialize version file before and then perform Ratis Server initialize. In this way, we shall use the same groupID in failure scenarios.
https://issues.apache.org/jira/browse/HDDS-5233
Existing CI.
=> HDDS-5233. SCM subsequent init failed when previous scm init failed.

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HAUtils.java
Avoid calls to SCM during OM startup to obtain the CA list.
https://issues.apache.org/jira/browse/HDDS-5257
Existing docker secure tests should test this code path.
=> HDDS-5257. Avoid SCM call to get CA certs in non-HA from OM.

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ScmUtils.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHANodeDetails.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestSCMHAConfiguration.java
If config is appended with serviceId and nodeId use that, else fall back to config appended without service id and node id. If that is also not defined, fall back to a default value.
https://issues.apache.org/jira/browse/HDDS-5256
Added UT.
=> HDDS-5256. Fix fall back of config in SCM HA Cluster

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OFSPath.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
https://issues.apache.org/jira/browse/HDDS-5041
Note: this commit changes the username set inside OFS `.Trash` directory when Kerberos is enabled from principal name to mapped shorted user name.
=> HDDS-5041. Use getShortUserName in getTrashRoot(s)

hadoop-ozone/recon/pom.xml
https://issues.apache.org/jira/browse/HDDS-5260
Let's bump nodejs version used by Recon UI.
=> HDDS-5260. Bump node to v16.2.0 for Recon

hadoop-hdds/docs/content/interface/S3.md, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecureOzoneCluster.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/security/S3GetSecretRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/security/S3RevokeSecretRequest.java
This is an addendum to #2239 .
Fixes the typo which wasn't caught in the previous review for s3 getsecret / revokesecret admin permission check.
=> HDDS-5206. Addendum: Support revoking S3 secret

hadoop-hdds/container-service/pom.xml, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/stream/DirectoryServerDestination.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/stream/DirectoryServerSource.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/stream/DirstreamClientHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/stream/DirstreamServerHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/stream/StreamingClient.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/stream/StreamingDestination.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/stream/StreamingServer.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/stream/StreamingSource.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/stream/package-info.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/stream/TestStreamingServer.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/Freon.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/StreamingGenerator.java, pom.xml
This was discussed offline a few times. (cc @bshashikant @mukul1987)
Today we have server/client utilities/API for Hadoop RPC and GRPC based services but we don't have any unified and tested API for data streaming.
It is suggested to create a generic API for streaming.
As I need to modify the closed container replication I already created a POC based on Netty (instead of GRPC).
This patch shows the first proposed version.
1. It uses a file-based API (the files should be specified to stream for a given id) because we can use Netty/native streaming without buffering in Java memory. 
2. Offsets can be supported (but not supported yet).
3. Freon test is included which shows 8x better performance compared to the old GRPC based container replication. (220Mb / sec vs 1.6-1.7 Gb/sec, using one …
=> HDDS-5142. Make generic streaming client/service for container re-replication, data read, scm/om snapshot download

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerReportHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/IncrementalContainerReportHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerReportHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestIncrementalContainerReportHandler.java
During testing we came across an issue with ICR and FCR handing.
The following log shows the issue:
```
2021-05-18 13:14:15,394 DEBUG org.apache.hadoop.hdds.scm.container.ContainerReportHandler: Processing replica of container #1 from datanode 945aa180-5cff-4298-a8ad-8197542e4562{ip: 172.27.108.136, host: quasar-nqdywv-7.quasar-nqdywv.root.hwx.site, ports: [REPLICATION=9886, RATIS=9858, RATIS_ADMIN=9857, RATIS_SERVER=9856, STANDALONE=9859], networkLocation: /default, certSerialId: null, persistedOpState: IN_SERVICE, persistedOpStateExpiryEpochSec: 0}
2021-05-18 13:14:15,394 DEBUG org.apache.hadoop.hdds.scm.container.IncrementalContainerReportHandler: Processing replica of container #1001 from datanode 945aa180-5cff-4298-a8ad-8197542e4562{ip: 172.27.108.136, host: …
```
=> HDDS-5249. Race Condition between Full and Incremental Container Reports

hadoop-ozone/dist/src/main/k8s/definitions/ozone/definitions/persistence.yaml, hadoop-ozone/dist/src/main/k8s/examples/ozone-ha/datanode-statefulset.yaml, hadoop-ozone/dist/src/main/k8s/examples/ozone/datanode-statefulset.yaml
Containers are 5Gb by default, however pvc is 2Gb.
it needs to be changed.
HDDS-5191
manual tests
=> HDDS-5191. Increase default pvc storage size

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelinePlacementPolicy.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestDeadNodeHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelinePlacementPolicy.java
Pipeline placement policy should filter out those datanodes that do not even have enough space for a single container, otherwise even if the pipeline creation succeeds, a datanode may quickly report that it fails to create a container and there will be successive failures because we will choose that node again and again.
https://issues.apache.org/jira/browse/HDDS-5252
a new ut.
manual test.
=> HDDS-5252. PipelinePlacementPolicy filter out datanodes with not enough space.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/DFSConfigKeysLegacy.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeConfiguration.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/HddsVolumeChecker.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/MutableVolumeSet.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestSchemaOneBackwardsCompatibility.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerPersistence.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestHddsDispatcher.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/TestDatanodeConfiguration.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestVolumeSet.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestVolumeSetDiskChecks.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueBlockIterator.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerCheck.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueHandler.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestContainerReader.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/metrics/TestContainerMetrics.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/server/TestSecureContainerServer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/DatanodeTestUtils.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/volume/TestDatanodeHddsVolumeFailureDetection.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/volume/TestDatanodeHddsVolumeFailureToleration.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/container/ContainerCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/ChunkManagerDiskWrite.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/ClosedContainerReplicator.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/containergenerator/GeneratorDatanode.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/genesis/BenchMarkDatanodeDispatcher.java
Datanode has config 'dfs.datanode.failed.volumes.tolerated', but it does not work,
this makes it to work.
https://issues.apache.org/jira/browse/HDDS-5219
a new integration-test case
an extended ut
=> HDDS-5219. Limit number of bad volumes by dfs.datanode.failed.volumes.tolerated

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMMXBean.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/main/resources/webapps/scm/scm-overview.html, hadoop-ozone/dist/src/main/compose/ozone-ha/docker-config
Add the following info to SCM Web UI
1. SCM leader/follower information.
2. Primordial SCM / CA server information.
https://issues.apache.org/jira/browse/HDDS-5241
=> HDDS-5241. SCM UI should have leader/follower and Primordial SCM information

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/report/ReportPublisher.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/report/TestReportPublisher.java
- Fix ReportPublisher to publish report only when Datanode is not shutdown
https://issues.apache.org/jira/browse/HDDS-5275
- Added unit tests
=> HDDS-5275. Datanode Report Publisher publishes one extra report after DN shutdown

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
In SCM sub-ca certs are set up during init, if a cluster is converted to secure later, in else part of the scmInit, we need to initialize security.
https://issues.apache.org/jira/browse/HDDS-5273
I Will test out the fix on the cluster and update here. Posting fix for CI run.
Tested this on a cluster and later it is converted to secure.
```
2021-05-26 01:15:23,478 INFO org.apache.hadoop.hdds.scm.ha.HASecurityUtils: Init response: GETCERT
2021-05-26 01:15:23,815 INFO org.apache.hadoop.hdds.scm.ha.HASecurityUtils: Successfully stored SCM signed certificate.
2021-05-26 01:15:23,822 INFO org.apache.hadoop.hdds.scm.server.StorageContainerManager: SCM already initialized. Reusing existing cluster id for sd=/var/lib/hadoop-ozone/scm/data/scm;cid=CID-9efddf03-b533-4134-816a-a35b87eec46b; …
```
=> HDDS-5273. Handle unsecure cluster convert to secure cluster for SCM.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java, hadoop-ozone/dist/src/main/smoketest/ozonefs/setup.robot
Most of our smoketests can be executed multiple times, which helps us to debug the tests locally.
Unfortunately, it's not the case `ozonefs/ozonefs.robot`. This test uses hard-coded bucket/volume names instead of using randomized bucket names.
For example:
docker-compose up -d --scale datanode=3
docker-compose exec scm bash
robot smoketest/ozonefs/ozonefs.robot
robot smoketest/ozonefs/ozonefs.robot
The second execution fails which makes harder to debug test problems.
It seems to be better to follow existing pattern and adding a random prefix to the user bucket names.
https://issues.apache.org/jira/browse/HDDS-5272
```
cd compose/ozone
docker-compose up -d --scale datanode=3
docker-compose exec scm bash
robot smoketest/ozonefs/ozonefs.robot
robot smoketest/ozonefs/ozonefs.robot
```
=> HDDS-5272. Make ozonefs.robot execution repeatable

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ContainerOperationClient.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ScmOption.java, hadoop-ozone/insight/src/main/java/org/apache/hadoop/ozone/insight/BaseInsightPoint.java
We can avoid listCA which is not required for most admin commands. It is required only for ChunkKeyHandler.
This will help when ACLS are configured for SCM security protocol where only admin/service principals can make calls to the SCMSecurityProtocol server, then we don't need to add all the users to them to make these commands work.
As for few of the commands like pipeline list, safe mode status we don't require admin privilege.
https://issues.apache.org/jira/browse/HDDS-5280
Existing admin test suite should cover this.
=> HDDS-5280. Make XceiverClientManager creation when necessary in ContainerOperationClient

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CloseContainerCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/endpoint/HeartbeatEndpointTask.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/SCMCommand.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/token/ContainerTokenGenerator.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/token/ContainerTokenSecretManager.java, hadoop-hdds/interface-server/src/main/proto/ScmServerDatanodeHeartbeatProtocol.proto, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/CloseContainerEventHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ReplicationManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMContext.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeProtocolServer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestSCMContext.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestSCMServiceManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestSCMSafeModeManager.java, hadoop-ozone/dist/src/main/smoketest/admincli/container.robot
Close container command from SCM fails due to lack of token.  This change adds the token to `SCMCommand`.
https://issues.apache.org/jira/browse/HDDS-5264
Updated acceptance test to verify that the container actually gets `CLOSED` (previously it was stuck in `CLOSING`).
=> HDDS-5264. SCM should send token for CloseContainer command

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java, hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/audit/parser/TestAuditParser.java, hadoop-ozone/tools/src/test/resources/testaudit.log, hadoop-ozone/tools/src/test/resources/testloadaudit.log
`ozone auditparser ~/audit.db load /logs/om-audit.log`
The command throw out of bound exception:
Index 6 out of bounds for length 6.
The audit log like this
There is "\n" after "partNumber: 1" and "partName***"
so, `bReader.readLine()` only read before the first "\n"
https://issues.apache.org/jira/browse/HDDS-5240?filter=-2
UT
=> HDDS-5240. Fix out of bound exception when loading auditparser

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SequenceIdGenerator.java
After installSnapshot, the bootstrapped SCM crashed in a short time while there is on-going write workload.
Clues from the core dump file, the new added SCM crashed in thread StateMachineUpdater, while accessing RocksDB. 
```
#
#
#
#
#
#
---------------  T H R E A D  ---------------
Current thread (0x00007fcf3ded2800):  JavaThread "7a85dabc-3f8c-47e1-bf0a-de75abe92820@group-691FBC3A273C-StateMachineUpdater" daemon [_thread_in_native, id=1559, stack(0x00007fceecacb000,0x00007fceecbcc000)]
siginfo: si_signo: 11 (SIGSEGV), si_code: 128 (SI_KERNEL), si_addr: 0x0000000000000000
```
```
Stack: [0x00007fceecacb000,0x00007fceecbcc000],  sp=0x00007fceecbc96a0,  free space=1017k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C …
```
=> HDDS-5281. Add reinitialize() for SequenceIdGenerator.

hadoop-ozone/dist/src/main/compose/testlib.sh, hadoop-ozone/dist/src/test/shell/compose_testlib.bats, hadoop-ozone/dist/src/test/shell/failing1/test.sh
Acceptance tests are split into a few suites, which can be activated by setting `OZONE_ACCEPTANCE_SUITE`.  CI checks execute 3 splits for faster feedback:
* `secure`
* `unsecure`
* `misc` + anything without `suite`
There are some other tests, tagged `suite:failing`, which exist only to test the behavior of the acceptance test runner when failures happen.
The goal of this change is to skip the `failing` suite by default, i.e. when acceptance tests are run without suite filter.  This would allow running all tests in sequence (e.g. in nightly job) while retaining the ability to run these special tests by setting `OZONE_ACCEPTANCE_SUITE=failing`.
https://issues.apache.org/jira/browse/HDDS-5242
1. Added _bats_ test case.
2. Ran `test-all.sh` with a small tweak to exit after finding tests.  The …
=> HDDS-5242. Skip `failing` acceptance suite by default

.github/workflows/cancel-ci.yaml, .github/workflows/post-commit.yml
GitHub Actions now provides [support to cancel duplicate workflows](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency) (and limit workflow concurrency).  This usage of the `cancel-workflow-runs` action can be replaced.
As previously, only PR workflows are cancelled, not ones triggered by commits or schedule.  This is made possible by using commit SHA to form concurrency group for non-PR builds (and PR number for PRs).
https://issues.apache.org/jira/browse/HDDS-5276
Tested in my fork:
https://github.com/adoroszlai/hadoop-ozone/pull/19
https://github.com/adoroszlai/hadoop-ozone/actions
=> HDDS-5276. Use built-in cancel support for duplicates

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DeadNodeHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeStatus.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/PipelineSyncTask.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconDeadNodeHandler.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconNodeManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStorageContainerManagerFacade.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/StorageContainerServiceProvider.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/StorageContainerServiceProviderImpl.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/ReconTaskConfig.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconNodeManager.java
Recon relies on DN heartbeats to understand Node operational state. If the node goes down before it reports itself as DECOMMISSIONED, then there is a loss of information on Recon side. It is the SCM that moves a node form DECOMMISSIONING to DECOMMISSIONED state first, then the Datanode persists the state change locally, and then heartbeats with the new state to SCM & Recon subsequently. If the DN is shutdown before it can heartbeat the state change to Recon, then Recon lives with the stale information.
This patch adds a DeadNodeHandler for Recon that updates the node operational status information from SCM if needed. It also adds a step in the Recon SCM Sync Task that updates the node operational status from SCM for every dead node as seen from Recon. …
=> HDDS-5277. Recon shows operational status as "DECOMMISSIONING" for "DECOMMISSIONED" DNs

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/report/CRLStatusReportPublisher.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/report/ReportPublisherFactory.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/StateContext.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestDatanodeStateMachine.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/report/TestReportPublisher.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/report/TestReportPublisherFactory.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/TestStateContext.java, hadoop-hdds/interface-server/src/main/proto/ScmServerDatanodeHeartbeatProtocol.proto, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/container/common/TestEndPoint.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMiniOzoneCluster.java
- Datanodes should generate and publish CRL Status reports via heartbeats
- The CRL Status report will contain last received CRL id and pending CRL ids 
https://issues.apache.org/jira/browse/HDDS-4483
- Unit tests and integration tests
=> HDDS-4483. Datanodes should send last processed CRL sequence ID in heartbeats

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/report/TestReportPublisher.java
HDDS-5154 made `x509CRL` mandatory in `CRLInfo`.  HDDS-4483 added a unit test where `x509CRL` is not set.  These two changes were tested without each other, hence passed.  Together they fail on `master`: https://github.com/apache/ozone/runs/2732634889#step:4:853
https://issues.apache.org/jira/browse/HDDS-5295
```
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.196 s - in org.apache.hadoop.ozone.container.common.report.TestReportPublisher
```
https://github.com/adoroszlai/hadoop-ozone/runs/2734503211#step:4:918
=> HDDS-5295. testCRLStatusReportPublisher fails to create CRLInfo

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeDecommissionManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestNodeDecommissionManager.java
After some discussion with István Fajth and Siddharth Wagle we believe that the change in HDDS-5153 should be reverted.
If a DN starts decommissioning or maintenance, but goes dead before it completes the process, then the node is moved back to a state of IN_SERVICE and DEAD by the decommission monitor when it notices it has become dead. This is because decommission should gracefully remove the node, but it goes dead first, we may not be able to replicate its containers. In this case decommission effectively fails.
In HDDS-5153, we decided that if a node is already dead and you decommission it, it should immediately move to DECOMMISSIONED. However that is not really consistent with the above behaviour.
Also, there is no real value in decommissioning a dead node - it does not do anything …
=> HDDS-5274. Revert "HDDS-5153. Decommissioning a dead node should complete immediately (#2190)"

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/BlockManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/WritableContainerFactory.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/WritableContainerProvider.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/WritableRatisContainerProvider.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMConfigurator.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
When implementing EC, we need to allocate blocks to containers on EC pipelines as well as Ratis pipelines (the current code path). The class `BlockManager.allocateBlock(...)` currently does this work.
To allow EC implementation to progress more smoothly, I would like to have BlockManager user a new interface to obtain a container for a block, namely the WritableContainerProvider interface.
This change is just a refactor to add the interface. Existing functionality is unchanged.
https://issues.apache.org/jira/browse/HDDS-5292
Existing tests
=> HDDS-5292. Introduce the WritableContainerInterface to SCM

hadoop-ozone/csi/pom.xml, pom.xml
Replaces uses of `netty.version` and uses `netty-bom` in top level pom `dependencyManagement` section to ensure consistent Netty version.
https://issues.apache.org/jira/browse/HDDS-5298
`mvn clean verify`
=> HDDS-5298. Use netty-bom to ensure consistent Netty version

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/fsck/ContainerHealthStatus.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/fsck/ContainerHealthTask.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStorageContainerManagerFacade.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/fsck/TestContainerHealthTask.java
Recon doesn't have a service for the state transition from `Closed` to `Deleted`. This patch adds the transition in ContainerHealthTask and avoid deleted containers to be set to Missing State.
https://issues.apache.org/jira/browse/HDDS-5235
unit test.
=> HDDS-5235. Add precheck to avoid ContainerHealthTask setting Deleted containers to Missing state

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyArgs.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerImpl.java, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
Currently, OM queries all history versions of locations for a key and replied to clients, which may exceed the IPC response size and cost OM many resources to process history key locations.
This patch added a config that can be specified to let OM return only the latest key location to clients.
https://issues.apache.org/jira/browse/HDDS-5243
Unit test
=> HDDS-5243. Return latest key location for clients

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/RatisReplicationConfig.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/StandaloneReplicationConfig.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerInfo.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogImplV2.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerStateManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ReplicationManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/states/ContainerStateMap.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/TestUtils.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestDeletedBlockLog.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerStateManager.java, hadoop-ozone/dist/src/main/smoketest/admincli/container.robot, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerStateManagerIntegration.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneAtRestEncryption.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestSecureOzoneRpcClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/scrubber/TestDataScrubber.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/ContainerEndpoint.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/fsck/ContainerHealthStatus.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestContainerEndpoint.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/fsck/TestContainerHealthStatus.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/fsck/TestContainerHealthTask.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/fsck/TestContainerHealthTaskRecordGenerator.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/AbstractReconContainerManagerTest.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconContainerManager.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/containergenerator/GeneratorScm.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/genesis/BenchMarkContainerStateMap.java
We introduced ReplicationConfig to most classes already, but we missed ContainerInfo.
This change will ensure that ContainerInfo uses ReplicationConfig rather than the legacy Type and Factor fields
https://issues.apache.org/jira/browse/HDDS-5313
Existing tests
=> HDDS-5313. ContainerInfo should use ReplicationConfig

hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerDoubleBufferWithOMResponse.java
`TestOzoneManagerDoubleBufferWithOMResponse` is flaky because double buffer involves another thread.  `flushTransactions` updates `flushedTransactionCount`, then somewhat later also updates `lastAppliedIndex`.  The test waits for the former, but simply checks the latter with assertion.  We need to wait for this update, too.
https://issues.apache.org/jira/browse/HDDS-5318
Repeated `TestOzoneManagerDoubleBufferWithOMResponse` 50x:
https://github.com/adoroszlai/hadoop-ozone/runs/2771888499
Regular CI (pending):
https://github.com/adoroszlai/hadoop-ozone/actions/runs/918284218
=> HDDS-5318. Intermittent failure in TestOzoneManagerDoubleBufferWithOMResponse

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/BackgroundPipelineCreatorV2.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMInstallSnapshot.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMSnapshot.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestStorageContainerManagerHA.java
1. Mini cluster in SCM HA tests waits for two events sequentially:
- SCM leader election
- datanode registration, pipeline creation
The same 2 minutes timeout applies to both of these separately.
This change makes single SCM _with Ratis enabled_ also wait for leader election, to allow for time spent to start up Ratis.  Most timeouts are observed in tests with such setup (single SCM with Ratis).
2. Increase frequency of pipeline creation attempts for some integration tests.
3. Fix `BackgroundPipelineCreatorV2#stop()`: the thread was always considered "not running" due to wrong condition for return value of `compareAndSet` (returns `true` if update is successful).
4. Guard `oneShotRun` value assignment in `notifyEventTriggered` by `serviceLock`, similar to other access in `shouldRun`. …
=> HDDS-5312. Intermittent failure in SCM Ratis integration test

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogStateManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogStateManagerImpl.java
Add class-level javadoc for DeletedBlockLogStateManager and DeletedBlockLogStateManagerImpl.
https://issues.apache.org/jira/projects/HDDS/issues/HDDS-5285
No test.
=> HDDS-5285. Document block deleting service classes

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineReportHandler.java
Avoid distracting logs in SCM followers during report processing. These logs don't add much value, better avoid them.
https://issues.apache.org/jira/browse/HDDS-5323
Patched the cluster and now I don't see error logs on the report processing on followers.
=> HDDS-5323. Avoid unncessary report processing log messages in follower.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ha/RetriableWithFailOverException.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAUtils.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/HASecurityUtils.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/RatisUtil.java
On SCM check if it is SCMSecurityException with errorCode NOT_A_PRIMARY_SCM return a RetriableWithFailOverException. In this way, FailOverProxyProvider performs failOver and Retry to the next SCM. And also increased Ratiis client retry count to a longer value.
https://issues.apache.org/jira/browse/HDDS-5317
Tested manually on docker-compose where I have changed the order of node ids to scm2,scm3,scm1
And started  SCM1, SCM2, and SCM3 in this order. SCM during bootstrap it will connect to scm2, and see whether it is able to bootstrap or not.
SCM3 connected to SCM2 and it is throwing RetriableWithFailOverException.
```
scm2.org_1   | org.apache.hadoop.hdds.scm.ha.RetriableWithFailOverException: org.apache.hadoop.hdds.security.exception.SCMSecurityException: Get SCM Certificate can be run …
```
=> HDDS-5317. BootStrapped SCM fails to bootstrap if it connects to another bootstrapped SCM first.

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyLocationInfo.java
Block tokens do not need to be stored in OM DB.
https://issues.apache.org/jira/browse/HDDS-5315
=> HDDS-5315 Skip storing unwanted block tokens on OM DB

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/SCMBlockDeletingService.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ReplicationManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMContext.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMStateMachine.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/BackgroundPipelineCreatorV2.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/ContainerSafeModeRule.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/DataNodeSafeModeRule.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/HealthyPipelineSafeModeRule.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/OneReplicaPipelineSafeModeRule.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/SCMSafeModeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/SafeModeExitRule.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestBlockManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestSCMContext.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestSCMPipelineManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestHealthyPipelineSafeModeRule.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestOneReplicaPipelineSafeModeRule.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestSCMSafeModeManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestSCMInstallSnapshotWithHA.java
After unclean SCM shutdown, SCM may not come out of safemode.
Attached a document to Jira with the problem statement and the proposal.
Proposal:
1. Use leader ready to start Background services.
2. In apply transaction after apply is complete if SCM is in safemode, refresh and validate safemode rules with current state.
3. For leader ready have a back ground daemon thread and check is leader ready using Ratis API. And also call notifyStatusChanged in SCMServices and also update isLeader in SCMContext.
https://issues.apache.org/jira/browse/HDDS-5263
Tested the fix on a cluster.
Testing is described here [link](https://github.com/apache/ozone/pull/2294#issuecomment-854422133)
Performed failover testing also to check leader status is properly propogated.
Added tests for SCMContext new API.
=> HDDS-5263. SCM may stay in safe mode forever after a unclean shutdown of SCM.

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeysDeleteRequest.java
If you fail to delete keys, you can avoid unnecessary calls to decNumKeys.
https://issues.apache.org/jira/browse/HDDS-5324
=> HDDS-5324. Delete unnecessary calls to decNumKeys in OMKeysDeleteRequest

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ReplicationManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestReplicationManager.java
ReplicationManager has a LockManager object that creates locks based on the ContainerInfo.getContainerID().However, this lockManager is not shared with other classes in SCM. It seems to be passed into only RM.When processing a container, RM locks using this.ICRs and FCRs can change the replicas and details stored in ContainerInfo and they lock a container using synchronized(containerInfo) while processing that Container in the report.As RM and ICR/FCR use different locks the locks do not protect against changes in each other.
this PR aims to remove LockManager from RM and just make it synchronize on the containerInfo object it is processing. 
https://issues.apache.org/jira/browse/HDDS-5329
unit test
=> HDDS-5329. remove lockmanager and synchronize on containerinfo in replication manager

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/StorageVolumeChecker.java
After HDDS-5268, disk check is timing out although all volumes are healthy:
```
2021-06-21 09:35:49,202 [Periodic HDDS volume checker] INFO volume.ThrottledAsyncChecker: Scheduling a check for /data/hdds/hdds
2021-06-21 09:35:49,204 [Periodic HDDS volume checker] INFO volume.StorageVolumeChecker: Scheduled health check for volume /data/hdds/hdds
2021-06-21 09:35:49,205 [DataNode DiskChecker thread 1] DEBUG volume.StorageVolumeChecker: Volume /data/hdds/hdds is HEALTHY.
2021-06-21 09:36:19,169 [Periodic HDDS volume checker] WARN volume.StorageVolumeChecker: checkAllVolumes timed out after 30000 ms
2021-06-21 09:36:19,169 [Periodic HDDS volume checker] WARN volume.MutableVolumeSet: checkAllVolumes got 1 failed volumes - [/data/hdds/hdds]
2021-06-21 09:36:19,172 [Periodic HDDS volume …
```
=> HDDS-5363. Datanode shutdown due to too many bad volumes in CI

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/x509/crl/CRLStatus.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/CertificateStore.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/authority/MockCAStore.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/crl/CRLStatusReportHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/crl/package-info.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/events/SCMEvents.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMCertStore.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeHeartbeatDispatcher.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/TestUtils.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/crl/TestCRLStatusReportHandler.java
- Add a heartbeat handler for CRLStatusReport received from DNs
- Store CRL Status of each DN in SCM (in memory)
- Add unit tests
Todo:
Send command to DNs to process new CRL. This will be covered in https://issues.apache.org/jira/browse/HDDS-5346
https://issues.apache.org/jira/browse/HDDS-4692
Added unit tests to test the report processing part.
=> HDDS-4692. Handle CRLStatusReport got from DN heartbeats and persist them

hadoop-ozone/dist/src/main/compose/ozone-mr/test.sh, hadoop-ozone/dist/src/main/compose/test-all.sh, hadoop-ozone/dist/src/main/compose/upgrade/test.sh
Make sure HTML report is generated even after failing tests.  Previously it was missing due to early exit from `test-all.sh` script.
https://issues.apache.org/jira/browse/HDDS-5342
Ran failing tests, verified `log.html` is generated:
```
$ OZONE_ACCEPTANCE_SUITE=failing ./hadoop-ozone/dev-support/checks/acceptance.sh
...
Output:  hadoop-ozone/dist/target/ozone-1.2.0-SNAPSHOT/compose/result/failing1.xml
...
Output:  hadoop-ozone/dist/target/ozone-1.2.0-SNAPSHOT/compose/result/failing2.xml
...
Log:     hadoop-ozone/dist/target/ozone-1.2.0-SNAPSHOT/compose/result/log.html
Report:  hadoop-ozone/dist/target/ozone-1.2.0-SNAPSHOT/compose/result/report.html
$ open target/acceptance/log.html
```
Also verified HTML reports are present in both successful and failed acceptance test artifacts: …
=> HDDS-5342. HTML report missing from acceptance results

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMBlockProtocolServer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeProtocolServer.java
Use RpcServer addSuppressedLoggingExceptions to supress ServerNotLeaderException to reduce NotLeaderException on folower node logs.
https://issues.apache.org/jira/browse/HDDS-5361
Manually verified it, now during startup made scm2 as primary SCM, I don't see any NotLeaderException logs logged on SCM1(As client contacts first SCM1 according to config)
=> HDDS-5361. Suppress logging of ServerNotLeaderException.

.github/workflows/post-commit.yml
1. Cache key for integration tests is incomplete, hash of pom.xml files is missing:
```
Run actions/cache@v2
with:
path: ~/.m2/repository
key: maven-repo--8-
restore-keys: maven-repo--8
maven-repo-
maven-repo-
...
Cache restored from key: maven-repo--8-
```
Path for `hashFiles` needs to include the custom checkout dir for _integration_ check.
2. Fix reference to undefined `matrix.check` in _integration_ and _coverage_ checks.
https://issues.apache.org/jira/browse/HDDS-5347
Verified cache restore key in CI:
```
Run actions/cache@v2
with:
path: ~/.m2/repository
key: maven-repo-56cc6f8280fca1fe3170b0f76702498cdbcf129fe0d6acde06a612c2a210b2c8-8-filesystem-hdds
restore-keys: maven-repo-56cc6f8280fca1fe3170b0f76702498cdbcf129fe0d6acde06a612c2a210b2c8-8 …
```
=> HDDS-5347. Wrong cache key for integration tests

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
```
//ContainerStateMachine
private ExecutorService getCommandExecutor(
ContainerCommandRequestProto requestProto) {
int executorId = (int)(requestProto.getContainerID() % executors.length);
return executors[executorId];
}
```
In the code above, different containers having the same remainder (mod executors.length ) will use the same executor even if some other executors are idle.  Ideally, different containers should use a different executor if there are executors available.
https://issues.apache.org/jira/browse/HDDS-5355
=> HDDS-5355. In ContainerStateMachine, share the executor threads between the containers.

hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MockOmTransport.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneClient.java
Added allocateBlock API in MockOmTransport.
https://issues.apache.org/jira/browse/HDDS-5350
Added a test which triggers allocateBlock. Without source changes, test fails and with source changes test passed.
=> HDDS-5350 :  Add allocate block support in MockOmTransport

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/LocalStream.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/StreamDataChannel.java
Use RATIS-Streaming to make ContainerStateMachine support writing streaming to the local.
https://issues.apache.org/jira/browse/HDDS-5366
CI test will be added after the client is finished
=> HDDS-5366.  [Ozone-Streaming] Implement stream method to ContainerStateMachine.

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/audit/parser/common/DatabaseHelper.java
If batchSize = 1000, and the auditEntries size also 1000.
Now the executeBatch will execute twice.
https://issues.apache.org/jira/browse/HDDS-5353?filter=-2
=> HDDS-5353. Avoid unnecessary executeBatch call in insertAudits

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineStateManagerV2Impl.java
Ensure getPipeline() is called inside write lock()
https://issues.apache.org/jira/browse/HDDS-5381
Existing UT
=> HDDS-5381. SCM terminated with exit status 1: null.

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/ProfileServlet.java
Sharing the output directory causes permission error, because typically they are run by separate users.
We should use an output directory specific to Ozone to avoid the permission issue.
https://issues.apache.org/jira/browse/HDDS-5387
No need.
=> HDDS-5387. ProfileServlet to move the default output location to an ozone specific directory

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/pipeline/Pipeline.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/pipeline/MockPipeline.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipeline.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementMetrics.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/ECPipelineProvider.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineFactory.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerV2Impl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineStateManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineStateManagerV2Impl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineStateMap.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/SCMPipelineManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/StateManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/WritableContainerFactory.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/WritableECContainerProvider.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackAware.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/MockPipelineManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestECPipelineProvider.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineStateMap.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestWritableECContainerProvider.java
This chance creates an ECPipelineProvider instance to allow for EC Pipelines to be created in the PipelineManager.
It also adds the the WritableEcContainerProvider, so a writable container can be selected from the open pipelines, or created if necessary.
https://issues.apache.org/jira/browse/HDDS-4892
New unit tests
=> HDDS-4892. EC: Implement basic EC pipeline provider

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMBlockLocationFailoverProxyProvider.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMSecurityProtocolFailoverProxyProvider.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/update/client/CRLClientUpdateHandler.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/PKIProfiles/DefaultProfile.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/update/server/MockCRLStore.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/TrashPolicyOzone.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/exception/BadRequestExceptionMapper.java
Eliminate expensive string creation in debug log messages(For example: toString()).
https://issues.apache.org/jira/browse/HDDS-5383
No test.
=> HDDS-5383. Eliminate expensive string creation in debug log messages

hadoop-hdds/docs/content/interface/O3fs.md, hadoop-hdds/docs/content/interface/O3fs.zh.md
The new version of o3fs must require Service ID.
https://issues.apache.org/jira/browse/HDDS-5389
Local Hugo pass.
=> HDDS-5389. Include ozoneserviceid in fs.defaultFS when configuring o3fs

hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/update/server/MockCRLStore.java
Fix negligence issue conditional expressions in line 109.
https://issues.apache.org/jira/browse/HDDS-5396
No test.
=> HDDS-5396. Fix negligence issue conditional expressions in MockCRLStore.java

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ReplicationManager.java
There are a few debug log entries in replication manager like this:
```
LOG.debug("Handling under-replicated container: {}",
container.getContainerID());
LOG.debug("Deleting empty container {} replicas,", container.containerID());
```
Especially the latter one, will always allocates a new ContainerID object on each call, even if debug is not enabled.
If we just pass "container" then it will use the container.toString() method inside the logger, only if debug is enabled. The `ContainerInfo.toString()` looks like:
```
@Override
public String toString() {
return "ContainerInfo{"
+ "id=" + containerID
+ ", state=" + state
+ ", pipelineID=" + pipelineID
+ ", stateEnterTime=" + stateEnterTime
+ ", owner=" + owner
+ '}';
}
```
It contains some extra information, but some of that may be useful if …
=> HDDS-5398. Avoid object creation in ReplicationManger debug log statements

hadoop-hdds/interface-admin/src/main/proto/ScmAdminProtocol.proto, hadoop-hdds/interface-client/src/main/proto/hdds.proto, hadoop-hdds/interface-server/src/main/proto/SCMRatisProtocol.proto, hadoop-hdds/interface-server/src/main/proto/ScmServerDatanodeHeartbeatProtocol.proto, hadoop-hdds/interface-server/src/main/proto/ScmServerProtocol.proto, hadoop-hdds/interface-server/src/main/proto/ScmServerSecurityProtocol.proto, hadoop-ozone/interface-client/src/main/proto/Security.proto
Changes the proto version of all the proto files to explicitly use proto2 as the syntax
https://issues.apache.org/jira/browse/HDDS-5406
Compilation succeeds and existing unit tests
=> HDDS-5406. add proto version to all the proto files.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/HddsVersionInfo.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/VersionInfo.java, hadoop-hdds/common/src/main/resources/hdds-version-info.properties, hadoop-hdds/interface-admin/pom.xml, hadoop-hdds/interface-client/pom.xml, hadoop-hdds/interface-server/pom.xml, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/util/OzoneVersionInfo.java, hadoop-ozone/common/src/main/resources/ozone-version-info.properties, hadoop-ozone/csi/pom.xml, hadoop-ozone/dist/pom.xml, hadoop-ozone/interface-client/pom.xml, hadoop-ozone/interface-storage/pom.xml, pom.xml
Refactor the pom files to differentiate proto files compiled for hadooprpc and grpc related proto files
https://issues.apache.org/jira/browse/HDDS-5405
compilation succeeds and existing unit tests pass
=> HDDS-5405. Refactor pom files for HadoopRpc and Grpc/Ratis compilation properties.

hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/TestUtils.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java
Fix `TestSCMNodeManager#testScmLayoutOnRegister` and `testScmLayoutOnHeartbeat` to register nodes with metadata capacity after HDDS-5269.
HDDS-5415
Failed tests pass after the change is applied.
=> HDDS-5415. Fix TestSCMNodeManager after merge of master at 1d8f972 into upgrade branch

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerData.java
Fix json parse stackoverflow for cmd ozone debug container list.
Detailed descriptions in the JIRA.
https://issues.apache.org/jira/browse/HDDS-5417
manual test.
=> HDDS-5417. Fix json parse stackoverflow for cmd ozone debug container list.

hadoop-hdds/server-scm/pom.xml, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestSCMPipelineManager.java
`MockNodeManager` allows 2 pipelines per node by default, ignoring the limit set for `ozone.scm.datanode.pipeline.limit`.  Thus sometimes 2 of the 5 pipelines created in `testPipelineReload` are placed on the same set of nodes (first and fourth pipelines here):
```
... (PipelineStateManager.java:addPipeline(55)) - Created pipeline Pipeline[ Id: 19231930-d31f-484c-a11d-3dcfe3ebc089, Nodes: 524b9db9-a0ad-4f72-9414-75ea62214723{...}0cc76e30-a109-4d81-b126-e550c71e8aa4{...}5a51c647-2566-4b22-a60d-f36c81395608{...}, ...
... (PipelineStateManager.java:addPipeline(55)) - Created pipeline Pipeline[ Id: 70b80e88-6ccf-4b26-9d63-f613e05ef486, Nodes: 98ece774-30e7-44c9-8013-4d4b472308c8{...}12638ad9-e21f-49cb-ae18-8f89c94ab110{...}13304be9-7453-401d-b4f5-1a33c88e6266{...}, ...
... …
```
=> HDDS-5416. Intermittent test failure in TestSCMPipelineManager#testPipelineReload

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/ECPipelineProvider.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineFactory.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerV2Impl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineProvider.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/RatisPipelineProvider.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/SCMPipelineManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/SimplePipelineProvider.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/WritableECContainerProvider.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/MockPipelineManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestECPipelineProvider.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestRatisPipelineProvider.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestWritableECContainerProvider.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconPipelineFactory.java
The WritableECContainerProvider needs to be able to create pipelines with excluded nodes. This Jira extends the pipelineManager interface to allow for passing the excluded nodes, which are already passed by the client, into pipelineManager.createPipeline(...). 
https://issues.apache.org/jira/browse/HDDS-5375
New unit tests
=> HDDS-5375. EC: Extend PipelineManager.createPipeline API to support excluded nodes

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/pipeline/Pipeline.java
Pipeline list command prints the creation time in UTC format, this should be in the system's local timezone.
Options
HDDS-5424.
Manual testing done
=> HDDS-5424. Pipeline list command's output should be in local timezone.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ReplicationManager.java
remove infilght action if node goes into NON-IN-SERVICE
https://issues.apache.org/jira/browse/HDDS-5400
unit test
=> HDDS-5400. remove infilght action if node goes into NON-IN-SERVICE

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
After this change _StorageContainerManager#getScmRatisRoles_ will return **STANDALONE** when SCM HA is not enabled.
HDDS-5421
Manual testing
=> HDDS-5421. SCM throws NPE during JMX call.

hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/StorageUnit.java
Because of floating point imprecision, you’re unlikely to get the value you expect from the `BigDecimal(double)` constructor.
Instead, you should use `BigDecimal.valueOf`, which uses a string under the covers to eliminate floating point rounding errors.
https://issues.apache.org/jira/projects/HDDS/issues/HDDS-5428
No need.
=> HDDS-5428. Fix potential BigDecimal precision in StorageUnit.java

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java
Re-interrupt the thread while catching InterruptedException.
https://issues.apache.org/jira/projects/HDDS/issues/HDDS-5427
No need.
=> HDDS-5427. Either re-interrupt this method or rethrow the "InterruptedException" that can be caught here

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/ContainerReader.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/MetadataKeyFilters.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/SCMBlockDeletingService.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineStateMap.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/WithObjectID.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java
Some calls to `Preconditions.check...` eagerly format the error message, resulting in unnecessary allocations.
https://issues.apache.org/jira/browse/HDDS-5422
:eyes:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1011814193
=> HDDS-5422. Avoid eager string formatting in preconditions

hadoop-hdds/common/src/main/resources/hdds-version-info.properties, hadoop-hdds/interface-admin/pom.xml, hadoop-hdds/interface-client/pom.xml, hadoop-hdds/interface-server/pom.xml, hadoop-ozone/common/src/main/resources/ozone-version-info.properties, hadoop-ozone/interface-client/pom.xml, hadoop-ozone/interface-storage/pom.xml, pom.xml
Simple change to rename hadooprpc.protobuf.version to proto2.hadooprpc.protobuf.version
https://issues.apache.org/jira/browse/HDDS-5433
Compilation works
=> HDDS-5433. Rename hadooprpc proto compilation in pom to refer to proto2.

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyLocationInfoGroup.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmKeyLocationInfoGroup.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
Reduce the CPU/heap allocation overhead of listStatus
HDDS-5384
Please find the flamegraph attached in the corresponding JIRA for the cpu and heap allocation before and after the change.
=> HDDS-5384 OM refreshPipeline should not invoke the expensive OmKeyLocationInfoGroup.getLocationList()

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconControllerModule.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconUtils.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/NSSummary.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/codec/NSSummaryCodec.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/ReconNamespaceSummaryManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/ReconNamespaceSummaryManagerImpl.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/FileSizeCountTask.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/NSSummaryTask.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/OMDBUpdateEvent.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/OMMetadataManagerTestUtils.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/spi/impl/TestReconNamespaceSummaryManagerImpl.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestContainerKeyMapperTask.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestNSSummaryTask.java
FileSizeCountTask counts the number of bins inside each buckets.
Try to build on FileSizeCountTask to count what we need for NSSummary as well.
[6.28] Added an independent Recon task to process namespace summary info per objectID in the attempt to decouple with other task modules.
https://issues.apache.org/jira/browse/HDDS-5386
Unit test: org.apache.hadoop.ozone.recon.tasks.TestNSSummaryTask
=> HDDS-5386. Add a NSSummaryTask to write NSSummary info into RDB

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/hdds/freon/FakeRatisFollower.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/report/ReportManager.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/XceiverServerGrpc.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/GrpcReplicationClient.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationServer.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/update/client/CRLClientUpdateHandler.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/update/client/SCMUpdateServiceGrpcClient.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/InterSCMGrpcClient.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/InterSCMGrpcProtocolService.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/update/server/SCMUpdateServiceGrpcServer.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/TrashPolicyOzone.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/ChunkKeyHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/BaseFreonGenerator.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/FollowerAppendLogEntryGenerator.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/RandomKeyGenerator.java
`InterruptedExceptions` should never be ignored in the code. The throwing of the `InterruptedException` clears the interrupted state of the Thread, so if the exception is not handled properly the information that the thread was interrupted will be lost. 
Instead, `InterruptedExceptions` should either be rethrown - immediately or after cleaning up the method’s state - or the thread should be re-interrupted by calling `Thread.interrupt()`.
https://issues.apache.org/jira/projects/HDDS/issues/HDDS-5434
No test.
=> HDDS-5434. Fix potential InterruptedException in Ozone

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/HddsVersionInfo.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/VersionInfo.java, hadoop-hdds/common/src/main/resources/hdds-version-info.properties, hadoop-hdds/interface-client/dev-support/findbugsExcludeFile.xml, hadoop-hdds/interface-client/pom.xml, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/util/OzoneVersionInfo.java, hadoop-ozone/common/src/main/resources/ozone-version-info.properties, hadoop-ozone/interface-client/dev-support/findbugsExcludeFile.xml, hadoop-ozone/interface-client/pom.xml, pom.xml
For Ozone to work with both hadoop2 and pre hadoop 3.3 versions, it needs to compile both proto2 and proto3 versions of the protofiles
https://issues.apache.org/jira/browse/HDDS-5431
Build succeeds and current tests pass
=> HDDS-5431. compile both proto2 and proto3 versions of Client to OM interaction proto files.

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/OzoneClientProducer.java
`OzoneClientProducer` catches any `Throwable` while creating the Ozone client and logs it at debug level.  Errors such as `OutOfMemoryError` should not be suppressed like this.
https://issues.apache.org/jira/browse/HDDS-5392
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1025056374
=> HDDS-5392. Avoid catching Error while creating Ozone client

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
Add link method to ContainerStateMachine for Ratis streaming.
https://issues.apache.org/jira/browse/HDDS-5452
CI test will be added after the client is ready.
=> [HDDS-5452] Add link method to ContainerStateMachine for Ratis streaming

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/MonotonicClock.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ReplicationManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestReplicationManager.java, hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/TestClock.java
Replication Manager currently uses Time.monotonicNow() in a few places to check if a pending command should be timed out. 
This is difficult to test without adding sleeps in the tests. 
We should inject a Clock object to use rather than making calls to SystemTime directly to allow tests more flexibility.
https://issues.apache.org/jira/browse/HDDS-5456
New Unit test
=> HDDS-5456. Inject a Clock into Replication Manager to allow timeouts to be tested

hadoop-ozone/dist/src/main/compose/ozone-mr/hadoop33/.env, hadoop-ozone/dist/src/main/compose/ozone-mr/hadoop33/docker-compose.yaml, hadoop-ozone/dist/src/main/compose/ozone-mr/hadoop33/docker-config, hadoop-ozone/dist/src/main/compose/ozone-mr/hadoop33/test.sh, hadoop-ozone/dist/src/main/smoketest/ozonefs/hadoopo3fs.robot
Add `ozone-mr` test run for Hadoop 3.3.1, and also upgrade `ozonesecure-mr` to the new version.
https://issues.apache.org/jira/browse/HDDS-5436
https://github.com/adoroszlai/hadoop-ozone/runs/3096436774
=> HDDS-5436. Add acceptance test for Hadoop 3.3

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientMultipartUploadWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCommitPartRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartUploadCompleteRequest.java
I have verified with aws s3 end point when uploading same content for same part, PartName is always same.
In AWS S3 case it is md5sum, as in ozone we don't generate based on md5sum, to solve this issue temporarily we can use same partNames when a part upload is override again. In Aws s3 cp case, file is divided in to parts, so in this case content will be same, so it is expecting same ETag/PartName I beleive for now I will provide a fix, to generate partNames in a predictable fashion to solve this issue. (So, if same content/different content part names will still be same for same part)
```
aws s3api upload-part --bucket b1-1993 --key mpu1 --part-number 1 --body /tmp/part1 --upload-id V7QlWzticX051N0BrQBAKAm.piipdYjHJ569P4aFAB5Ti_inSpvEyXS4cKEA7sHHendCFo5WOsmF.psmTMm7lFZMtsGw1e_iLyfXoD1KEh …
```
=> HDDS-5005. Multipart Upload fails due to partName mismatch.

hadoop-ozone/dist/src/main/compose/ozone/docker-compose.yaml
Need to escape `false` in yaml for the latest Docker for Mac to work properly.
https://issues.apache.org/jira/browse/HDDS-5457
=> HDDS-5457. services.s3g.environment.OZONE-SITE.XML_ozone.om.enable.filesystem.paths must be a string, number or null

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ReplicationManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestReplicationManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestSCMContainerPlacementPolicyMetrics.java
The method `ReplicationManager.processContainersNow()` only wakes up the thread, and returns before the containers have been processed.
This results in all RM tests having a `sleep(100)` after all calls to this method.
With a small refactor to RM, we can avoid this sleep. After this change all tests run about 100ms faster, and the code in the tests is slightly better.
https://issues.apache.org/jira/browse/HDDS-5459
Existing tests
=> HDDS-5459. Replication Manager should process containers synchronously for tests

hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestReplicationManager.java
#2429 removed `ReplicationManager.processContainersNow()`, but #2349 added some new calls it in the meantime.  So now when both PRs are merged, we have [compile errors](https://github.com/apache/ozone/runs/3120179167#step:6:1214).
```
[ERROR] /home/runner/work/ozone/ozone/hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestReplicationManager.java:[1123,23] cannot find symbol
[ERROR]   symbol:   method processContainersNow()
[ERROR]   location: variable replicationManager of type org.apache.hadoop.hdds.scm.container.ReplicationManager
...
```
https://issues.apache.org/jira/browse/HDDS-5459
Compiled Ozone.  Ran `TestReplicationManager`.
=> HDDS-5459. Fix compile errors in TestReplicationManager

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
1. Fix an inconsistency in parsing the request in `stream()` method with the `startTransaction()` method. This inconsistency caused the stream close issue in our POC code. Refer to the JIRA for more details.
2. Add `@Override` annotation to `link()` method.
https://issues.apache.org/jira/browse/HDDS-5481
This patch is tested in our POC code, see this [commit](https://github.com/ckj996/ozone/commit/a2da593cfdb608c0de496acdea3ce98114bbe5ca), so we dont need to do ugly workarounds like this [commit](https://github.com/ckj996/ozone/commit/e199582d1b811e6258a34133935746f0617a84ff).
Unit tests will be added later after the client is finished.
=> HDDS-5481. Fix stream() and link() method in ContainerStateMachine

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/ImmutableVolumeSet.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/MutableVolumeSet.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/StorageVolumeChecker.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeSet.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestPeriodicVolumeChecker.java
Eliminate the need for costly sleep in `TestPeriodicVolumeChecker`:
```
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 132.95 s - in org.apache.hadoop.ozone.container.common.volume.TestPeriodicVolumeChecker
```
https://github.com/apache/ozone/runs/3112345557#step:4:923
by:
* manually calling `checkAllVolumeSets` instead of waiting for the real executor to schedule it,
* and using `FakeTimer` to "advance" time between the calls.
https://issues.apache.org/jira/browse/HDDS-5468
```
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.276 s - in org.apache.hadoop.ozone.container.common.volume.TestPeriodicVolumeChecker
```
https://github.com/adoroszlai/hadoop-ozone/runs/3115013489#step:4:1100
=> HDDS-5468. Avoid long sleep in TestPeriodicVolumeChecker

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/util/ContinueToken.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/util/TestContinueToken.java
https://issues.apache.org/jira/browse/HDDS-5479
=> HDDS-5479. s3g bucket list failed when there is non-english key name.

hadoop-ozone/dist/src/main/smoketest/s3/bucketcreate.robot
Stop using the well known ${BUCKET} value due to side effects of having created a bucket other tests will test for. Uses a randomized bucket name instead that is then confirmed to exist before the second bucket creation command is executed.
https://issues.apache.org/jira/browse/HDDS-5443
The issue is really only seen when running tests manually and substituting in a custom bucket name, per test instructions and that bucket didn't happen to exist and you were expecting it to still not exist after the test is run. 
The changes were tested manually and as part of the s3 acceptance tests since this test is run as part of the s3 acceptance tests.
=> HDDS-5443 Create and then recreate a bucket with a randomized name

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/protocolPB/ScmBlockLocationProtocolClientSideTranslatorPB.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMAllocateBlockRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyRequest.java
Allow EC block requests to propagate from OM to SCM, as currently only STANDALONE and RATIS are supported.
https://issues.apache.org/jira/browse/HDDS-5174
=> HDDS-5174. EC: Allow EC blocks to be requested from OM

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/containergenerator/GeneratorDatanode.java, hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/freon/containergenerator/TestGeneratorDatanode.java
JIRA: https://issues.apache.org/jira/browse/HDDS-5462
Freon does have an offline generator test suite to generate quickly local data (rocksdb + container) for load testing.
But today, the datanode generator doesn't support different replication sets for the same node. Containers are generated in a way where the replication sets ("pipelines") are always include the same nodes:
In this case, if `node1` is down, only `node2` and `node3` can be used as the source of the nodes.
With multi-raft option enabled, it's possible to have a placement were more than two nodes are used as source.
This patch uses a very simple permutation based approach to have similar layout but still keep the generation to be predictable.
With the new `--overlap` argument, different containers can have slightly …
=> HDDS-5462. Multi-raft style placement with permutations for offline data generator

hadoop-ozone/dev-support/checks/_lib.sh
Replace hard-coded `Linux` in Flekszible download URL with OS/architecture-specific value.
https://issues.apache.org/jira/browse/HDDS-5489
Tested on a Mac:
```
$ ./hadoop-ozone/dev-support/checks/kubernetes.sh
Installed flekszible in /Users/.../ozone/.dev-tools/flekszible
...
Skip installing k3s, not supported on Mac.  Make sure a working Kubernetes cluster is available.
...
Basic :: Smoketest ozone cluster startup
Check webui static resources                                          | PASS |
Start freon testing                                                   | PASS |
----------------------------------------------------------------- …
```
=> HDDS-5489. Install OS-specific flekszible

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneKey.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyArgs.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneBucketStub.java
Avoid refresh pipeline for headObject API
https://issues.apache.org/jira/browse/HDDS-5450
Added a test for new API. S3 test suite should test usage of headObject from s3 interface.
=> HDDS-5450. Avoid refresh pipeline for S3 headObject

hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/container/ContainerTestHelper.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/ContainerUtils.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/helpers/TestContainerUtils.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueHandlerWithUnhealthyContainer.java
Fix the issue that Ozone Insight prints binary data for `dataBuffers`:
```
[TRACE|org.apache.hadoop.ozone.container.common.impl.HddsDispatcher|OzoneProtocolMessageDispatcher] [service=DatanodeClient] [type=ReadChunk] request is processed. Response:
cmdType: ReadChunk
traceID: ""
result: SUCCESS
readChunk {
...
dataBuffers {
buffers: "4w7u1Zp8@{"
buffers: "<redacted>"
}
}
```
This is caused by appending to the list of buffers in `processForDebug` instead of replacing the list with a single item.
https://issues.apache.org/jira/browse/HDDS-5414
Added unit test.  Also tested on compose-based cluster:
```
ozone insight logs -v datanode.dispatcher -f datanode=ozone_datanode_1
ozone freon ockg -n10 -t1 -p test -s 10
ozone freon ockv -n10 -t1 -p test
```
Output:
``` …
```
=> HDDS-5414. Data buffers incorrectly filtered for Ozone Insight

hadoop-ozone/dist/src/main/k8s/examples/testlib.sh
_kubernetes_ tests wait for cluster startup, checking some conditions with retry.  In worst case all conditions are checked 100 times with 3 seconds delay, so the test may take 15 minutes to fail.
Skip waiting for SCM and OM readiness if retries for previous conditions are exhausted.
https://issues.apache.org/jira/browse/HDDS-5494
Currently the test in `ozone` env. fails to start the cluster, so the change is verified by the failing CI check:
```
...
99 'all_pods_are_running' is failed...
4 pods are running out from the 5
100 'all_pods_are_running' is failed...
**** Executing robot tests scm-0 ****
...
```
https://github.com/adoroszlai/hadoop-ozone/runs/3159798487#step:6:797
The happy path is verified by successful startup in `getting-started` env.:
```
...
-1 pods are running. Waiting …
```
=> HDDS-5494. Reduce retry in Kubernetes test

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/utils/db/DatanodeDBProfile.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/utils/db/package-info.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/AbstractDatanodeStore.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBProfile.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
Currently datanodes shares a common DB profile with other components like SCM and OM etc. The jira aims to create a different profile for datanodes which also makes sure that column family options are shared by containers.
https://issues.apache.org/jira/browse/HDDS-5184
Existing UT, PR adds a UT to test columnfamilyoptions are shared.
=> HDDS-5184. Use separate DB profile for Datanodes.

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/acl/OMBucketAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/acl/OMBucketAddAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/acl/OMBucketRemoveAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/acl/OMBucketSetAclRequest.java
I found that if the ACL operation of the bucket fails, onFailure has the same operation in OMBucketAddAclRequest、OMBucketRemoveAclRequest、OMBucketSetAclRequest.
So maybe we can move the onfailure operation to the parent class.
https://issues.apache.org/jira/browse/HDDS-5465
=> HDDS-5465. Delete redundant code when set、add and remove bucket acl

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java, hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/RatisBlockOutputStream.java, hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestBlockOutputStreamCorrectness.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntry.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStreamFlushDelay.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStreamWithFailures.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStreamWithFailuresFlushDelay.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestWatchForCommit.java
We propose to make BlockOutputStream abstract and move out the Ratis specific code out. Then, other implementations such as ECBlockOutputStream can extend it and reuse the common parts.
https://issues.apache.org/jira/browse/HDDS-5466
Modified existing tests.
=> HDDS-5466. Refactor BlockOutputStream.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystemWithFSO.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
https://issues.apache.org/jira/browse/HDDS-5279
`ClientProtocol#getBucketDetails` can throw `VOLUME_NOT_FOUND` **when ACL is enabled** because `checkAcls()` will attempt to retrieve volume owner with [getVolumeOwner()](https://github.com/apache/ozone/blob/1290b8733dc1c9fcf4351c6d3d4a08a8ec4c5b4a/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java#L1824), which `getBucket()` didn't handle previously.
Thanks @avijayanhwx for the initial fix.
Updated the UT with new parameter.
=> HDDS-5279. OFS mkdir -p does not work when Volume is not pre-created

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java
Race condition upon dn restart at prefinalization.
More details in the jira below.
https://issues.apache.org/jira/browse/HDDS-5513
CI
=> HDDS-5513. Race condition upon dn restart at prefinalization.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/stream/DirectoryServerSource.java
Resources should be closed.Failure to properly close resources will result in a resource leak.
Resource should be created using `try-with-resources` pattern and will be closed automatically.
https://issues.apache.org/jira/projects/HDDS/issues/HDDS-5524
No need.
=> HDDS-5524. Use try-with-resources to properly close resources in DirectoryServerSource.java

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/protocolPB/ScmBlockLocationProtocolClientSideTranslatorPB.java
We missed a break statement in the EC branch of the switch statement, so calls for EC blocks are falling through to the exception case.
https://issues.apache.org/jira/browse/HDDS-5509
=> HDDS-5509. EC: Add missing break in switch statement when requesting EC blocks

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java
Validate block file length during put block .
https://issues.apache.org/jira/browse/HDDS-5483
Only a validation check.
=> HDDS-5483. Validate block file length during put block

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/ContainerPlacementPolicyFactory.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineFactory.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestContainerPlacementFactory.java
EC will need a different container placement policy than the default "two on the first rack and one on the second". This Jira should allow the EC placement policy to be set to a different value than for Ratis containers. By default, it can use the Ratis setting for now.
https://issues.apache.org/jira/browse/HDDS-5325
Added unit test for the method.
=> HDDS-5325. EC: Add configuration to set an EC container placement policy

hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/dist/src/main/compose/ozonesecure-ha/docker-config, hadoop-ozone/dist/src/main/compose/ozonesecure/docker-config, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/Gateway.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/S3GatewayConfigKeys.java
Add support to put/get/mpu from encrypted bucket from S3G.
https://issues.apache.org/jira/browse/HDDS-5501
```
Manually tested the fix on secure KMS Cluster.
**S3Gatway**
<property><name>ozone.s3g.kerberos.keytab.file</name><value>/tmp/ozone.keytab</value></property>
<property><name>ozone.s3g.kerberos.principal.key</name><value>s3g/_HOST@ROOT.HWX.SITE</value></property>
**Ranger KMS**
<property><name>hadoop.kms.proxyuser.s3g.users</name><value>*</value></property
<property><name>hadoop.kms.proxyuser.s3g.hosts</name><value>*</value></property><property><name>hadoop.kms.proxyuser.s3g.groups</name><value>*</value></property>
Configure  credentials
[root@xx ~]# kinit -kt /var/run/cloudera-scm-agent/process/71-hbase-REGIONSERVER/hbase.keytab hbase/xx@ROOT.HWX.SITE
[root@xx ~]# ozone s3 …
```
=> HDDS-5501. Support to upload/read keys from encrypted buckets through S3G

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyLocationInfoGroup.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmKeyLocationInfoGroup.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmBlockVersioning.java
Currently the keyLocation of different versions is stored redundantly in OmKeyInfo. 
OmKeyInfo:
keyLocationVersions: List<OmKeyLocationInfoGroup>  stores different versions of information in a list.
OmKeyLocationInfoGroup:
locationVersionMap: Map<Long, List<OmKeyLocationInfo>> stores different versions of location in a map.
If the versions are large, the redundent location is causing the large GC overhead for OM, in our cluster, the OM even crashes because of OOM.
This ticket is to remove the redundant location information to keep OM healthy.
https://issues.apache.org/jira/browse/HDDS-5472
unit test
=> HDDS-5472. Old versions of location in OmKeyLocationInfoGroup causes OOM of OM

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ReplicationConfig.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/client/TestReplicationConfig.java
…
ReplicationConfig#getDefault uses the passed config defaults instead of hardcoding to RATIS.
https://issues.apache.org/jira/browse/HDDS-5460
Added a unit test.
=> HDDS-5460: ReplicationConfig#getDefault is hardcoded with RatisReplicationConfig

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/SCMCommonPlacementPolicy.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ScmUtils.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelinePlacementPolicy.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestMultiRaftSetup.java
The patch disallows same set of datanodes to participate in multiple pipelines.Right now, the behaviour is controlled by a config.
[https://issues.apache.org/jira/browse/HDDS-5441]
Added unit tests
=> HDDS-5441. Disallow same set of DNs to be part of multiple pipelines 

hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStore.java
The assertion that the expected value is the same as the actual value is meaningless.
`Assert.assertArrayEquals(nextValue, nextValue);`
This change is to fix the previously wrong `Assert.assertArrayEquals()`.
https://issues.apache.org/jira/projects/HDDS/issues/HDDS-5539
Local TestRDBStroe pass.
=> HDDS-5539. Fix actual value in assertion in TestRDBStore

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerManagerImpl.java
ReplicationConfig handling was missed in ContainerManagerImpl
Handled the replication config cases.
https://issues.apache.org/jira/browse/HDDS-5510
Added init tests for verifying this patch.
=> HDDS-5510: allocateContainer should handle ec replication config

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/ITestOzoneContractDistCp.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/rooted/ITestRootedOzoneContractDistCp.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/server/TestSecureContainerServer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestCloseContainer.java
Add post-test cleanup for some tests where I found large leftover files.
https://github.com/adoroszlai/hadoop-ozone/runs/3232120118#step:4:3832
https://github.com/adoroszlai/hadoop-ozone/runs/3232120118#step:4:3845
https://github.com/adoroszlai/hadoop-ozone/runs/3232120118#step:4:10313
https://github.com/adoroszlai/hadoop-ozone/runs/3232120118#step:4:14016
https://issues.apache.org/jira/browse/HDDS-5532
Printed space after tests, verified that `test-dir` disk usage is in acceptable range.
https://github.com/adoroszlai/hadoop-ozone/runs/3234909921#step:8:28
https://github.com/adoroszlai/hadoop-ozone/runs/3234909972#step:8:28
https://github.com/adoroszlai/hadoop-ozone/runs/3234910003#step:8:28
=> HDDS-5532. Missing integration test cleanup

.github/workflows/post-commit.yml
#846 moved tests to `/mnt`, because it had more space at that time.  Currently we have much more space in `/`, while tests are intermittently failing due to lack of disk space.
Initial disk usage (before checkout, build and tests):
```
/dev/sdb1        84G   42G   42G  50% /
/dev/sda1        14G  4.1G  9.0G  32% /mnt
```
So this PR moves tests back to the root partition.
https://issues.apache.org/jira/browse/HDDS-5527
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1092599536
=> HDDS-5527. Move tests back to root partition

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/upgrade/ScmHAUnfinalizedStateValidationAction.java
Duplicate metrics registered while running checkScmHA upon scm startup.
More details in the jira below.
Here we reuse the LayoutManager instance from scm when scm is running,
and create a LayoutManager instance in scmInit() which should be in a single cmd line run, so no duplicate happens.
https://issues.apache.org/jira/browse/HDDS-5516
manual test.
=> HDDS-5516. Duplicate metrics registered while running checkScmHA upon scm startup.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/OnDemandContainerReplicationSource.java
https://issues.apache.org/jira/browse/HDDS-5538
=> HDDS-5538. Uncaught NPE in GrpcReplicationService.

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/upgrade/BasicUpgradeFinalizer.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/upgrade/DataNodeUpgradeFinalizer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/upgrade/SCMUpgradeFinalizer.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/upgrade/OMUpgradeFinalizer.java
On finalize upgrade actions not running.
Actually it is just a default function `action()` that does not got overrided for HDDSLayoutFeature,
and we could pass it in as done in runPrefinalizeStateActions.
https://issues.apache.org/jira/browse/HDDS-5503
manual test.
=> HDDS-5503. On finalize upgrade actions not running.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeConfiguration.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/container/common/TestEndPoint.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/TestContainerReplication.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java
https://issues.apache.org/jira/browse/HDDS-5360
=> HDDS-5360. DN failed to process all delete block commands in one heartbeat interval

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerRatisServer.java
Provide clear exception message when there is a change in OM Service ID.
https://issues.apache.org/jira/browse/HDDS-5546
Existing tests
=> HDDS-5546.OM Service ID change causes OM startup failure.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/ContainerPlacementPolicyFactory.java
The method name itself contradicts the public modifier, also the method is only used inside the class, so it worth to change it to private. (This change is added on just the EC branch so far.)
https://issues.apache.org/jira/browse/HDDS-5562
No extra tests were done, as the method is used just within the class, and the only change is the visibility.
=> HDDS-5562 EC: ContainerPlacementPolicyFactory#getPolicyInternal() should not be public

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestECKeyOutputStream.java
Client side cache uses pipeline ids as keys. In EC case we wanted to use IP:Host in keys so that we can get different keys for each node in block group.
https://issues.apache.org/jira/browse/HDDS-5425
Added tests to verify the behavior.
=> HDDS-5425: Client side pipeline cache key should use host and port combination

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/JsonUtils.java, hadoop-ozone/dist/src/main/smoketest/basic/links.robot, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/bucket/InfoBucketHandler.java
Avoid showing unnecessary metadata for link buckets. This is to avoid confusion like when link is to encrypted bucket showing encryption key null would confuse shell users
https://issues.apache.org/jira/browse/HDDS-5531
Manual test and also updated robot test
bash-4.2$ ozone sh bucket info /linkvol/linkbuck
```
{
"volumeName" : "linkvol",
"bucketName" : "linkbuck",
"sourceVolume" : "vol1",
"sourceBucket" : "buck1",
"creationTime" : "2021-08-05T06:51:24.815Z",
"modificationTime" : "2021-08-05T06:51:24.815Z"
}
bash-4.2$ ozone sh bucket info /vol1/buck1
{
"name" : "buck1",
"creationTime" : "2021-08-05T06:50:46.936Z",
"modificationTime" : "2021-08-05T06:50:46.936Z", …
```
=> HDDS-5531. For Link Buckets avoid showing metadata.

hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/TimeDurationUtil.java
Avoid methods that generate NPE when calling `unit()`.
https://issues.apache.org/jira/projects/HDDS/issues/HDDS-5558
No need.
=> HDDS-5558. vUnit invocation unit() may produce NPE

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManagerFSO.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/NSSummaryEndpoint.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/DUResponse.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/NamespaceSummaryResponse.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/OMMetadataManagerTestUtils.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestNSSummaryEndpoint.java
In addition to actual key size, Recon 'du' should also return the replicated size of a key.
For example, for a 3 way replicated key of size = 1MB, Recon 'du' should return '1MB' as the size of the key, and '3MB' as the replicated size if the key is fully replicated.
[Refactoring]
1. DU response now shows a "structure"
2. DU key response shouldn't have subpaths
https://issues.apache.org/jira/browse/HDDS-5449
Since this is an improvement/refactoring feature on top of HDDS-5378, no additional unit test is implemented. I tested remotely on the cluster endpoint with the following configs:
All keys are three-way replicated except `key3`
[Root DU]
http://localhost:9888/api/v1/namespace/du?path=/&replica=true
[Volume DU]
http://localhost:9888/api/v1/namespace/du?path=/vol&replica=true
[Bucket DU] …
=> HDDS-5449 Recon namespace summary 'du' information should return replicated size of a key

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerRatisServer.java, pom.xml
value of `pendingRequestsByteLimit` couldn’t be set beyond 2GB because of the integer limit.  Similarly there were other places where getStorageSize was cast to int.  Converted to long where possible and changed the scale of the variable if not. 
https://issues.apache.org/jira/browse/HDDS-5283
CI
=> HDDS-5283. getStorageSize cast to int can cause issue

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/upgrade/SCMUpgradeFinalizer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/upgrade/TestHDDSUpgrade.java
Have containers close normally during a regular upgrade with all datanodes up by not force closing pipelines.
HDDS-5498
Integration test modified.
=> HDDS-5498. Containers are always quasi closed during finalization.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
ContainerBalancer should be stopped in `StorageContainerManager#stop`.
https://issues.apache.org/jira/browse/HDDS-5603
=> HDDS-5603. Stop ContainerBalancer when SCM is stopped.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineClose.java
TestPipelineClose.testPipelineCloseWithLogFailure is failing in a lot of PRs and is flaky. Disabling it to improve the build stability.
https://issues.apache.org/jira/browse/HDDS-5624
Existing tests
=> HDDS-5624. Disable test TestPipelineClose.testPipelineCloseWithLogFailure

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java
https://issues.apache.org/jira/browse/HDDS-5606
=> HDDS-5606. Intermittent failure in TestBlockDeletion#testContainerStatisticsAfterDelete

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/SCMCommonPlacementPolicy.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRackAware.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelinePlacementPolicy.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRandom.java
This ticket consists of the following changes in SCMCommonPlacementPolicy.
refactor getRequiredRackCount() to getRequiredRackCount(int numReplicas)
Add a method to check if a datanode is available.
Currently getRequiredRackCount() ingests no input arguments and the default value is ususally 1 or 2, but for EC placement policy, the required racks will be based on the numReplicas.
The availability check method is added to SCMCommonPlacementPolicy so that it can be reused by other PlacementPolicy subclasses.
https://issues.apache.org/jira/browse/HDDS-5622
unit test
=> HDDS-5622. Some improvements in SCMCommonPlacementPolicy

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/InnerNode.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/InnerNodeImpl.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NetworkTopology.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NetworkTopologyImpl.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/net/TestNetworkTopologyImpl.java
Currently, NetworkTopology has a function of "getNumOfNodes", which can be used to get the number of nodes in one level.
This ticket is to add a function which can be used be get all the nodes in one level. Which will be quite useful to spread datanodes across all racks.
https://issues.apache.org/jira/browse/HDDS-5621
unit test
=> HDDS-5621. Support returning nodes of a level in NetworkTopology

hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/HttpServer2.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/http/TestHttpServer2.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java
The default value of `hadoop.http.idle_timeout.ms` seems to be inteneded as 10k in `HttpServer2.java`, but it is ignored and actually falls into 1000 defined in core-site.xml from hadoop-common implemented in HADOOP-15696 . I would also propose extending the default value to 60k, which is commonly used value among other Hadoop projects.
HDDS-5620
- manual tests in laptop
- a unit test is added as `TestHttpServer2`
=> HDDS-5620. Fix and extend hadoop.http.idle_timeout.ms to 60k

hadoop-ozone/integration-test/pom.xml, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneHAClusterImpl.java
Root cause is when MiniOzoneHAClusterImpl#bootstrapOzoneManager is creating a new OM, it may encounter a port conflict, this function will retry with a new port, but before that, the metadataManager of the first OM didn't close the lock on the rocksdb, which causes the test to fail for the retry.
Options to solve:
I tried to add a "metadataManager.stop()" in the constructor of OM when it fails to start RPC server, but it will prompt another error about the lock on ratis directory.
I tried to stop the ratisServer too, but in https://github.com/apache/ratis/blob/dc0b68b4c0b8c187a08f669422a2cd099d7be0b7/ratis-common/src/main/java/org/apache/ratis/util/LifeCycle.java#L308, the close function will not be called, so the lock won't be released. Tried to call the closeMethod for State.NEW, but …
=> HDDS-5632. Intermittent failure in TestOzoneManagerBootstrap#testBootstrapTwoNewOMs

hadoop-ozone/dist/src/main/k8s/examples/testlib.sh
Replace hard-coded version number with actual version from POM.  (This is used only when running from source dir.)
https://issues.apache.org/jira/browse/HDDS-5495
```
$ cd hadoop-ozone/dist/src/main/k8s/examples/getting-started
$ ./test.sh
**** Modifying Kubernetes resources file for test ****
(mounting current Ozone directory to the containers, scheduling containers to one node, ...)
WARNING: this test can be executed only with local Kubernetes cluster
(source dir should be available from K8s nodes)
INFO[2021-07-26T11:16:21+02:00] Input dir: hadoop-ozone/dist/src/main/k8s/examples/getting-started, output dir: hadoop-ozone/dist/src/main/k8s/examples/getting-started
INFO[2021-07-26T11:16:21+02:00] Reading resources from hadoop-ozone/dist/src/main/k8s/examples/getting-started/resources …
```
=> HDDS-5495. Ozone version mismatch in Kubernetes test lib

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/GrpcReplicationClient.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationServer.java
Add all CA Certs to trust manager while creating GRPC Replication Server between datanodes.
https://issues.apache.org/jira/browse/HDDS-5556
Tested with docker-compose by bringing up the following containers initially in ozonesecure-ha environment:
```
docker-compose up -d kdc kms scm1.org scm2.org scm3.org recon om1 om2 om3 datanode1
// To change the SCM leader node
docker-compose stop scm1.org
// Start datanode2 to get its cert signed by new SCM leader (scm2.org)
docker-compose up -d datanode2
// Change leader again
docker-compose start scm1.org
docker-compose stop scm2.org
// Start dn3
docker-compose up -d datanode3
// put a file
docker-compose exec om bash
kinit -kt /etc/security/keytabs/om.keytab om/om
ozone sh vol create vol1
ozone sh bucket create vol1/bucket1
ozone sh key put …
```
=> HDDS-5556. GrpcReplication Client might fail in SCM HA Cluster

hadoop-ozone/dist/src/main/compose/test-all.sh, hadoop-ozone/dist/src/main/compose/testlib.sh
This change adds the capability of Ozone acceptance tests to generate result in xunit/junit format as well.
https://issues.apache.org/jira/browse/HDDS-5540
Tested in house with private runs and verified xunit/junit result file was generated.
=> HDDS-5540. Acceptance test: able to generate result in xunit/junit format as well

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java
Handle InterruptedException in [DeleteBlocksCommandHandler](https://sonarcloud.io/project/issues?id=hadoop-ozone&open=AXsvaqG__dIWFQzeEnbC&resolved=false&sinceLeakPeriod=true&types=BUG).
Handle InterruptedException in [ContainerBalancer](https://sonarcloud.io/project/issues?id=hadoop-ozone&open=AXs66eHhmEe61HHPN0_O&resolved=false&sinceLeakPeriod=true&types=BUG).
https://issues.apache.org/jira/projects/HDDS/issues/HDDS-5658
Minor fix, no testing done.
=> HDDS-5658. Handle InterruptedException in DeleteBlocksCommandHandler and ContainerBalancer

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestRandomKeyGenerator.java
The patch ensures readStateMachine/writeStateMachine data gets executed on the same thread for the same block.
https://issues.apache.org/jira/browse/HDDS-5619
Enabled few tests.
=> HDDS-5619. Ozone data corruption issue on follower node.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/RatisUtil.java
This bug missed the merge boat and got stale. In the current context, what this bug really means now is to make sure in RatisUtil, the call to Log.Appender.setBufferElementLimit is set to queue num-elements: 1024 and not queue byte-limit: 32 * 1024 * 1024 using the current HA config pattern.
SCMHAConfiguration used to provide this:
@Config(key = "ratis.log.appender.queue.num-elements",
type = ConfigType.INT,
defaultValue = "1024",
tags = {SCM, OZONE, HA, RATIS},
description = "Number of operation pending with Raft's Log Worker."
)
private int raftLogAppenderQueueNum = 1024;
@Config(key = "ratis.log.appender.queue.byte-limit",
type = ConfigType.SIZE,
defaultValue = "32MB",
tags = {SCM, OZONE, HA, RATIS},
description = "Byte limit for Raft's Log Worker queue."
)
private int …
=> HDDS-5391 Fix issues in SCMHAConfiguration

hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/TestHddsUtils.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/WritableRatisContainerProvider.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/MockPipelineManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconPipelineManager.java
Acquire pipelineManager during allocateContainer to avoid any updates to pipelineState.
And also updated to use ReentrantReadWriteLock in PipelineManager, to allow multiple allocateBlock requests happen. This way, pipelineManager lock will not create contention.
https://issues.apache.org/jira/browse/HDDS-5655
Existing tests
=> HDDS-5655. SCM terminates when allocatecontainer happens on closed pipeline.

hadoop-hdds/common/src/main/resources/ozone-default.xml
Fix TestOzoneConfigurationFields which is failing after HDDS-5391 Fix issues in SCMHAConfiguration (#2567).
The test is failing due to as new config key is not added to ozone-default.xml
https://issues.apache.org/jira/browse/HDDS-5668
Updated test
=> HDDS-5668. Fix TestOzoneConfigurationFields.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAWithData.java
Some tests in TestOzoneManagerHAWithData can naturally be combined. For example some run the same test with all OMs up and then one OM down.
Some other tests can be run on the same cluster in isolated buckets, as they do not restart any nodes.
This test suit typically runs for about 490 seconds , so it would be good to reduce its runtime.
```
[INFO] Running org.apache.hadoop.ozone.om.TestOzoneManagerHAWithData
Warning:  Tests run: 12, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 490.975 s - in org.apache.hadoop.ozone.om.TestOzoneManagerHAWithData
```
https://issues.apache.org/jira/browse/HDDS-5692
Existing tests
=> HDDS-5692. Combine some tests in TestOzoneManagerHAWithData to reuse mini-Clusters

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
change the place where the RatisMetricReporters registers
https://issues.apache.org/jira/browse/HDDS-5680
CI
right now the metrics all appears
=> HDDS-5680. Fix bug for incomplete SCM ratis metrics

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneCluster.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterProvider.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/node/TestDecommissionAndMaintenance.java
The integration (ozone) test suit is the slowest part of the github actions build, taking over 2 hours usually. In a random PR I checked, 2hr16.
Often in integration tests, a large part of the test time is spent creating a new mini-Ozone cluster for each test, which can take 10 - 20 seconds to startup.
I also timed stopping a mini-cluster and found that can take up to 10 seconds.
Changing the tests to reuse the same cluster can be difficult and make the tests less standalone and more brittle, which is not a good thing. Changing the tests is also time consuming work.
Assuming a test runs for longer than the time taken to setup a mini-cluster and stop it, it would make the tests faster if we pre-created a mini-cluster in the background. Then when one test completes, the next cluster is …
=> HDDS-5644. Speed up decommission tests using a background Mini Cluster provider

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManagerMetrics.java
Fix ReplicationManager zero metrics for inflight actions.
https://issues.apache.org/jira/browse/HDDS-5706
manual test
after change we could get actual numbers instead of all 0.
=> HDDS-5706. Fix ReplicationManager zero metrics for inflight actions.

hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackAware.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/TestContainerReplication.java
TestContainerReplication#testSkipDecommissionAndMaintenanceNode() was added as part of HDDS-5296. The test runs 3 times and sleeps for 30 seconds on each run to wait to ensure replication never hits an out of service node. Aside from the 30 second sleep, each run of the test takes about 1 minute, so 3 minutes in total for this test.
This class takes about 370 seconds on every pull request:
```
[INFO] Running org.apache.hadoop.ozone.container.TestContainerReplication
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 368.92 s - in org.apache.hadoop.ozone.container.TestContainerReplication
```
I feel this integration test is not needed. The logic we are testing here, is actually part of the placement policy and we can test for the original defect in …
=> HDDS-5690. Speed up TestContainerReplication by removing testSkipDemmissionAndMaintenanceNode

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogImpl.java
for now, blockingDeleting service will delete keys periodically and thus `removeTransactionsFromDB` will  be called periodically  , which is generate a raft log when scm ha is enabled.  if nothing to remove, a raft log will also be generated , which will delele nothing. this is not needed.
https://issues.apache.org/jira/browse/HDDS-5709
no need
=> HDDS-5709. do not call removeTransactionsFromDB if nothing to remove

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
Handle unsecure SCM HA converted to secure SCM HA. This PR covers for bootstrapped SCMs, unlike HDDS-5273 which has taken care only for primordial/single node SCM.
https://issues.apache.org/jira/browse/HDDS-5678
Tested following scenario.
1. Setup SCM HA Cluster with out security
2. Enabled Kerberos
3. Started Ozone Services
**Logs from testing** (Skipped unncessary part of logs to show actual logs to show this PR has fixed the problem.
```
STARTUP_MSG: Starting StorageContainerManager
STARTUP_MSG:   host = bv-oz-4.bv-oz.root.hwx.site/172.27.99.0
STARTUP_MSG:   args = [--bootstrap]
STARTUP_MSG:   version = 1.1.0.7.2.12.0-200
2021-08-30 07:50:55,866 INFO org.apache.hadoop.hdds.scm.server.StorageContainerManager: Skipping clusterId validation during bootstrap command.  ClusterId id …
```
=> HDDS-5678. Handle unsecure SCM HA converted to secure SCM HA.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/node/TestDecommissionAndMaintenance.java
There are a few scenarios in the decommission and maintenance integration tests that can be combined into the same test, reducing the number of mini-clusters needed. There changes reduce the number of tests (and clusters) by 3.
The last runtime for the decommission tests was:
```
[INFO] Running org.apache.hadoop.ozone.scm.node.TestDecommissionAndMaintenance
[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 389.226 s - in org.apache.hadoop.ozone.scm.node.TestDecommissionAndMaintenance
```
https://issues.apache.org/jira/browse/HDDS-5719
Existing tests
=> HDDS-5719. Reduce number of mini-clusters needed for decommission tests

hadoop-ozone/dist/src/main/compose/ozonesecure-ha/docker-compose.yaml
In a Secure HA docker compose recon didn't come up. Added the volumes that contains the keytabs for recon.
https://issues.apache.org/jira/browse/HDDS-5638
This patch was manually tested by spinning up the Secure HA cluster and made sure recon showed up, and also with GitHub CI tests.
https://github.com/aswinshakil/ozone/actions/runs/1151968641
=> HDDS-5638. Fixed docker-compose to make Recon come up.

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/GrpcOzoneManagerServer.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManagerServiceGrpc.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestGrpcOzoneManagerServer.java
This PR includes the Grpc server service servicing `OzoneManagerProtocol` requests over gRPC invoked by the OM.  The server consists of `GrpcOzoneManagerServer` that is started by the OM and establishes the persistent connection between the om and the s3 gateway (current port 8981 and configurable by java configuration class).  The server creates the connection with the `OzoneManagerServiceGrpc` that services `OMRequests` through the  `OzoneManagerProtocolServerSideTranslatorPB`.
The `OzoneManagerServiceGrpc` requires creating a thread context '`Server.Call`' for every ratis transaction request processed through the `OzoneManagerProtocolServerSideTranslatorPB`.
The Grpc server service is enabled / disabled through the boolean configuration key : `OZONE_OM_S3_GPRC_SERVER_ENABLED` and …
=> HDDS-5211. Start OM Grpc server as part of the OM bootstrap

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerConfiguration.java
Currently, ContainerBalancer creates a new OzoneConfiguration in ContainerBalancer#start and uses that. Instead, it should get the OzoneConfiguration object from ContainerBalancerConfiguration.
https://issues.apache.org/jira/browse/HDDS-5670
TestContainerBalancer UT
=> HDDS-5670. ContainerBalancer should get OzoneConfiguration from ContainerBalancerConfiguration.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java
for container balancer cli, for example
`./ozone admin containerbalancer start -i -1 -t 0.000001 -d 1 -s 5000`
if we specify `-i` with `-1` , balancer should run infinitely
https://issues.apache.org/jira/browse/HDDS-5711
unit test
=> HDDS-5711. support -1 for running balancer infinitely

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisServerImpl.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/scm/GetScmRatisRolesSubcommand.java
Add RaftpeerId for the shell command " ozone admin scm roles"
In the current scm log files, some of the raft related logs lack explicit Addresses, so it is hard to distinguish the SCM nodes from the abstract UUID.  We can add the RaftPeerId into the command -> ozone admin scm roles, which can help find the SCM node mentioned in logs.
https://issues.apache.org/jira/browse/HDDS-5724
CI
=> HDDS-5724. Add RaftpeerId when getting scm roles

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestXceiverClientManager.java
TestXceiverClientManager takes about 158 seconds to run:
```
[INFO] Running org.apache.hadoop.ozone.scm.TestXceiverClientManager
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 158.045 s - in org.apache.hadoop.ozone.scm.TestXceiverClientManager
```
It runs 4 tests each in a fresh mini-cluster. We can reuse the same cluster for each test and reduce the runtime to about 25% of the original.
On my laptop the runtime goes form 104 seconds -> 41.
https://issues.apache.org/jira/browse/HDDS-5718
Existing tests
=> HDDS-5718. Refactor TestXceiverClientManager to reuse mini-clusters.

.github/workflows/post-commit.yml
Increase acceptance test timeout from 120 minutes to 150 minutes, since new upgrade/downgrade acceptance tests sometimes push the acceptance test run time over 2 hours.
HDDS-5723
- Existing acceptance test run.
=> HDDS-5723. Increase time limit of Ozone acceptance tests.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java
Make XceiverServerRatis#raftGids a thread-safe set.
More descriptions in the JIRA below.
https://issues.apache.org/jira/browse/HDDS-5715
no need.
=> HDDS-5715. Make XceiverServerRatis#raftGids a thread-safe set.

hadoop-hdds/docs/content/interface/ReconApi.md, hadoop-hdds/docs/content/interface/ReconApi.zh.md
When I read the Recon API documentation, the current link cannot be linked to the external Prometheus HTTP API Reference.
As shown below:
**It has been replaced by the available Prometheus HTTP API Reference link.**
https://issues.apache.org/jira/projects/HDDS/issues/HDDS-5735
Local hugo pass.
=> HDDS-5735. Prometheus HTTP API Reference cannot be displayed normally

hadoop-ozone/dist/src/main/k8s/examples/testlib.sh
Fix missing directory name in messages like:
```
**** Applying k8s resources from  ****
```
Print path in `start_k8s_env` instead of expecting it to be passed (as it is not).  Current dir can be used because test execution requires `cd` to test dir anyway.
https://issues.apache.org/jira/browse/HDDS-5496
Verified log in CI run:
```
**** Applying k8s resources from getting-started ****
...
**** Applying k8s resources from minikube ****
...
**** Applying k8s resources from ozone-dev ****
...
**** Applying k8s resources from ozone ****
```
https://github.com/adoroszlai/hadoop-ozone/runs/3349882860#step:5:124
https://github.com/adoroszlai/hadoop-ozone/runs/3349882860#step:5:318
https://github.com/adoroszlai/hadoop-ozone/runs/3349882860#step:5:461 …
=> HDDS-5496. Missing directory name in `start_k8s_env` log

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileInterfaces.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileInterfacesWithFSO.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCreateRequestWithFSO.java
TestOzoneFileInterfaces currently takes about 563 seconds to run:
```
[INFO] Running org.apache.hadoop.fs.ozone.TestOzoneFileInterfaces
Warning: Tests run: 18, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 563.677 s - in org.apache.hadoop.fs.ozone.TestOzoneFileInterfaces
```
It can be changed quite easily to re-use the same mini-cluster across many tests, saving a lot of run time.
On my laptop, after this change, it runs in less than 60 seconds.
https://issues.apache.org/jira/browse/HDDS-5720
Existing tests
=> HDDS-5720. Reuse mini-clusters in TestOzoneFileInterfaces

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ReplicationManager.java
Use more defensive sizeRequired for replication manager for container replication,
this prevents replication from failure due to out of space.
https://issues.apache.org/jira/browse/HDDS-5679
manual test
=> HDDS-5679. Use more defensive sizeRequired for replication manager for container replication.

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockDataStreamOutput.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/Checksum.java
If checksum is disabled, byteBuffer does not need to be converted. We need to advance if judgments to avoid unnecessary conversions
https://issues.apache.org/jira/browse/HDDS-5742
=> HDDS-5742. [Ozone-Streaming] Avoid unnecessary Bytebuffer conversions

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFSWithObjectStoreCreate.java
TestOzoneFSWithObjectStoreCreate typically runs in about 212 seconds:
```
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 212.789 s - in org.apache.hadoop.fs.ozone.TestOzoneFSWithObjectStoreCreate
[INFO] Running org.apache.hadoop.fs.ozone.TestOzoneFileSystem
```
Refactoring to re-use the mini-cluster across all tests should greatly reduce this runtime.
https://issues.apache.org/jira/browse/HDDS-5748
Existing tests
=> HDDS-5748. Reuse mini-clusters in TestOzoneFSWithObjectStoreCreate

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerListVolumes.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
TestOzoneManagerListVolumes takes about 215 seconds to run, as it has several tests, and each tests creates a new mini-cluster:
```
[INFO] Running org.apache.hadoop.ozone.om.TestOzoneManagerListVolumes
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 215.633 s - in org.apache.hadoop.ozone.om.TestOzoneManagerListVolumes
```
We can refactor the test to use the same Mini-Cluster and just restart the OM component between each test, saving a lot of time.
Note that this requires a small change in the OzoneManagerImpl class too.
On my laptop the runtime went from 176 seconds -> 20 seconds.
https://issues.apache.org/jira/browse/HDDS-5717
Existing tests and a changes to existing tests.
=> HDDS-5717. Refactor TestOzoneManagerListVolumes to reuse mini-ozone clusters

hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/common/pom.xml, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/GrpcOmTransport.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/GrpcOmTransportFactory.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/protocolPB/TestS3GrpcOmTransport.java, hadoop-ozone/common/src/test/resources/log4j.properties, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/protocolPB/TestGrpcOmTransport.java
S3 gateway to issue s3 commands through `OzoneManagerProtocol` over gRPC OmTransport.  This PR includes the implementation of the gRPC OmTransport provided by` GrpcOmTransport` created through a `GrpcOmTransportFactory`. 
The `GrpcOmTransport` provides a persistent channel connection between the s3gateway and the ozone manager.  The port used for the connection (8981) is configurable through a defined configuration class.  Similarly, the host is configurable through configuration file through _OZONE_OM_ADDRESS_KEY_.  
In addition, the connection is persistent and recoverable though internal gRPC channel implementation retry as recommended by gRPC dev community.
https://issues.apache.org/jira/browse/HDDS-5212
Patch tested with new unit tests testing OmTransport Grpc service provider …
=> HDDS-5212. Create implementation of OmTransport which uses Grpc

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/pipeline/Pipeline.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipeline.java
The replica indexes are not copied to the new pipeline when the pipeline is cloned.
https://issues.apache.org/jira/browse/HDDS-5745
New unit test
=> HDDS-5745. EC: Pipeline builder should copy replica indexes from original pipeline

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsHAURLs.java
TestOzoneFsHAURLs runs in about 104 seconds:
```
[INFO] Running org.apache.hadoop.fs.ozone.TestOzoneFsHAURLs
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 104.905 s - in org.apache.hadoop.fs.ozone.TestOzoneFsHAURLs
```
Reusing the mini-cluster across all the tests can reduce this time.
https://issues.apache.org/jira/browse/HDDS-5749
Existing tests
=> HDDS-5749. Reuse mini-clusters in TestOzoneFsHAURLs

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/TopologySubcommand.java, hadoop-ozone/dist/src/main/smoketest/topology/cli.robot
Currently, printTopology CLI display all DN information as output.
This task is to add NodeOperationalState and NodeState as the CLI options to the command, and display the DN accordingly.
https://issues.apache.org/jira/browse/HDDS-5402
bin/ozone admin printTopology -n IN_SERVICE
=> HDDS-5402 Support list node based on NodeOperationalState and NodeState options in printTopology CLI

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/metrics/SCMNodeStat.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeUsageInfo.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancer.java
ContainerBalancer gets a list of datanodes sorted according to their utilizations using `NodeManager#getMostOrLeastUsedDatanodes`.
There are two ways of calculating utilization:
1.  ```used space / capacity```
2.  ```(capacity - remaining) / capacity```
`Used` space is obtained using the DU or DF command (`SpaceUsageSource`), while `remaining` can either be `capacity - used` or calculated using the `java.io.File#getUsableSpace` method. This means the two ways of calculating utilization might give different results (when `used` is not equal to `capacity - remaining`).
Currently, `NodeManager#getMostOrLeastUsed` uses method 2 while balancer uses method 1.
Instead, both should consistently use the same approach. We prefer method 2 since the `remaining` space calculation will also account for …
=> HDDS-5728. ContainerBalancer should use remaining space to calculate utilization.

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockOutputStreamEntryPool.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MockOmTransport.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java
Consolidates the block stream information per the block group.
https://issues.apache.org/jira/browse/HDDS-5477
To check current tests impact.
=> HDDS-5477 : EC: commit key should consolidate and create one keyLocationInfo per blockGrp

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/upgrade/TestHDDSUpgrade.java
TestHDDSUpgrade is one of the longest running test suits as it creates many mini-clusters:
```
[INFO] Running org.apache.hadoop.hdds.upgrade.TestHDDSUpgrade
Warning:  Tests run: 13, Failures: 0, Errors: 0, Skipped: 4, Time elapsed: 694.753 s - in org.apache.hadoop.hdds.upgrade.TestHDDSUpgrade
```
It is not possible to reuse the same clusters across multiple tests here, so we can use the MiniClusterProvider to create the clusters in the background and speed things up.
On my laptop the test runtime went from 9min 14s to 5min 12s.
https://issues.apache.org/jira/browse/HDDS-5751
Existing tests
=> HDDS-5751. Use Mini Cluster Provider to speed up TestHDDSUpgrade

.github/workflows/post-commit.yml, hadoop-ozone/dist/src/main/compose/ozone-ha/test.sh, hadoop-ozone/dist/src/main/compose/ozone-mr/hadoop27/test.sh, hadoop-ozone/dist/src/main/compose/ozone-mr/hadoop31/test.sh, hadoop-ozone/dist/src/main/compose/ozone-mr/hadoop32/test.sh, hadoop-ozone/dist/src/main/compose/ozone-mr/hadoop33/test.sh, hadoop-ozone/dist/src/main/compose/ozone-mr/test.sh, hadoop-ozone/dist/src/main/compose/ozonesecure-ha/test.sh, hadoop-ozone/dist/src/main/compose/ozonesecure-mr/test.sh
Extract some tests from _acceptance (misc)_ into separate suites: _acceptance (HA)_ and _acceptance (MR)_.
https://issues.apache.org/jira/browse/HDDS-5753
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1242183045
=> HDDS-5753. Split parts of misc suite

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketSetPropertyRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/OMVolumeSetQuotaRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestOMBucketSetPropertyRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/volume/TestOMVolumeSetQuotaRequest.java
failed with exception
java.lang.IllegalArgumentException: Total buckets quota in this volume should not be greater than volume quota : the total space quota is set to:256000. But the volume space quota is:102400
at org.apache.hadoop.ozone.om.request.bucket.OMBucketSetPropertyRequest.checkQuotaBytesValid(OMBucketSetPropertyRequest.java:281)
at org.apache.hadoop.ozone.om.request.bucket.OMBucketSetPropertyRequest.validateAndUpdateCache(OMBucketSetPropertyRequest.java:172)
at org.apache.hadoop.ozone.protocolPB.OzoneManagerRequestHandler.handleWriteRequest(OzoneManagerRequestHandler.java:246)
at org.apache.hadoop.ozone.om.ratis.OzoneManagerStateMachine.runCommand(OzoneManagerStateMachine.java:472)
at org.apache.hadoop.ozone.om.ratis.OzoneManagerStateMachine.lambda$2(OzoneManagerStateMachine.jav …
=> HDDS-5761. should not shutdown om when setting a bigger bucket quota  than volume quota

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmMetrics.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerConfiguration.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHA.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAMetadataOnly.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerListVolumes.java
Many of the OzoneManager integration tests do not really use SCM or the datanodes. Therefore we can skip the safemode check in SCM and start zero datanodes to make the mini-cluster come up faster.
With just this change, on my laptop:
```
TestOzoneManagerConfiguration went from 6min -> 3min 40s.
TestOzoneManagerHAMetadataOnly went from 4min 19s -> 1min 9s.
TestOzoneManagerListVolumes went from 40s -> 20s
TestOMMetrics went from 2min 6 -> 39s 55s
```
The runtime for these tests on Github is:
```
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 273.591 s - in org.apache.hadoop.ozone.om.TestOzoneManagerConfiguration
Warning: Tests run: 10, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 363.67 s - in org.apache.hadoop.ozone.om.TestOzoneManagerHAMetadataOnly
[INFO] …
```
=> HDDS-5766. Speed up some OM tests by skipping SCM safemode check

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerRocksDBLogging.java
TestOzoneManagerRocksDBLogging can be made faster by skipping the SCM safemode check and setting the number of datanodes to 0 in the mini cluster.
Last runtime was:
```
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 81.735 s - in org.apache.hadoop.ozone.om.TestOzoneManagerRocksDBLogging
```
https://issues.apache.org/jira/browse/HDDS-5768
Existing tests
=> HDDS-5768. Skip safemode check in TestOzoneManagerRocksDBLogging

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterProvider.java
`MiniOzoneClusterProvider` may timeout (100 seconds) while waiting for a cluster to become available.  In this case it simply returns `null` without warning.  This results in NPE when trying to use the cluster in test.
```
testAllDataNodeFailuresAfterScmPostFinalizeUpgrade  Time elapsed: 100.076 s  <<< ERROR!
at org.apache.hadoop.hdds.upgrade.TestHDDSUpgrade.init(TestHDDSUpgrade.java:173)
at org.apache.hadoop.hdds.upgrade.TestHDDSUpgrade.setUp(TestHDDSUpgrade.java:135)
```
This change makes `MiniOzoneClusterProvider` throw exception if cluster could not be started.  This way test failure is a bit more explicit.
https://issues.apache.org/jira/browse/HDDS-5765
Regular CI.
https://github.com/adoroszlai/hadoop-ozone/runs/3651226035
=> HDDS-5765. Test cluster provider possibly returns null

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/volume/TestDatanodeHddsVolumeFailureToleration.java
In TestDatanodeHddsVolumeFailureToleration, the tests wait for a long time on a DN to be marked dead by SCM. This is because the stale, dead and heartbeat intervals have not been set low enough, as they are using default. Changing the various timers, the runtime is reduced from about 4mins to 53 seconds on my laptop.
Further, there are two tests - one that fails one volume on a DN and ensures it can restart ok. Then a test which fails 2 volumes and ensure it fails to start. We can combine these two tests into 1 and save creating a second mini-Cluster. This further reduces the runtime to ??.
On github, this test runs in:
```
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 236.534 s - in org.apache.hadoop.ozone.dn.volume.TestDatanodeHddsVolumeFailureToleration
``` …
=> HDDS-5771. Speed up TestDatanodeHddsVolumeFailureToleration by reducing dead interval

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneCluster.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmMetrics.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerConfiguration.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerListVolumes.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerRocksDBLogging.java
Avoid code duplication by making it a bit easier to start a mini cluster without datanodes.
https://issues.apache.org/jira/browse/HDDS-5773
Regular CI, but _integration (ozone)_ was not yet run because it
> is waiting for a hosted runner to come online.
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1257175959
=> HDDS-5773. Avoid code duplication for mini cluster without datanodes

hadoop-ozone/ozone-manager/pom.xml, pom.xml
HDDS-4319 temporarily switched to a fork of the `aspectj-maven-plugin` due to lack of Java 11 support in the official one.  A [newer version](https://github.com/mojohaus/aspectj-maven-plugin/releases/tag/aspectj-maven-plugin-1.14.0) is now available, which adds that missing support.  This PR upgrades the plugin, and also AspectJ to match the plugin's expectation.
https://issues.apache.org/jira/browse/HDDS-5759
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1244949654
=> HDDS-5759. Bump aspectj version

hadoop-ozone/dev-support/checks/_lib.sh
Fail immediately when k3s install fails.
https://issues.apache.org/jira/browse/HDDS-5770
kubernetes tests correctly report the failure here:
https://github.com/GeorgeJahad/ozone/runs/3659216789?check_suite_focus=true
=> HDDS-5770. Silent failures of k3s install are difficult to debug

hadoop-ozone/dist/src/main/license/jar-report.txt, hadoop-ozone/httpfsgateway/pom.xml
This reverts commit e8b15f4223fe4ac225c41fda832591dedb32b523.
This pull request is reverting the changes in HDDS-5695. Previously the Zookeeper and Curator dependencies were deleted, as we thought they were unnecessary. But later we found out, that in the CI the server couldn't start, because the it is unable to initialize WebAppContext. It happened because the DelegationTokenAuthenticationFilter class is using Zookeeper through curator, as the class is using delegation tokens and the token details are stored in ZooKeeper. So the ZK and the Curator dependencies are needed.
https://issues.apache.org/jira/browse/HDDS-5695
Built it without problems.
=> HDDS-5695 Review ZK and Curator dependencies, and get rid of them.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ECReplicationConfig.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/client/TestECReplicationConfig.java, hadoop-hdds/interface-client/src/main/proto/hdds.proto, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MultiNodePipelineBlockAllocator.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/SinglePipelineBlockAllocator.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
We need to store the codes (rs / xor / etc) and the EC stripe size in ECReplicationConfig.
https://issues.apache.org/jira/browse/HDDS-5775
New and existing tests
=> EC: Add Codec and Stripe Size to ECReplicationConfig

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestNSSummaryAdmin.java
TestNSSummaryAdmin can run successfully with zero datanodes. It current takes about 44 seconds, but should be much faster without any datanodes in the mini-cluster:
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 44.693 s - in org.apache.hadoop.ozone.shell.TestNSSummaryAdmin
On my laptop it went from 36 -> 10 seconds.
https://issues.apache.org/jira/browse/HDDS-5792
Existing tests
=> HDDS-5792. Speed up TestNSSummaryAdmin by having zero Datanodes

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/conf/DatanodeRatisGrpcConfig.java
https://issues.apache.org/jira/browse/HDDS-5782
=> HDDS-5782. DatanodeRatisGrpcConfig use wrong type for config keys.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/utils/CertificateCodec.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DNCertificateClient.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DefaultCertificateClient.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/OMCertificateClient.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/SCMCertificateClient.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
On a upgraded cluster with SCM HA version code, SCM fails to start when hdds.container.token.enabled is set to true.
In a upgraded cluster and SCM non-HA SCMCertificateClient is not initialized and sub-CA is not started. Initialize SCMCertificateClient with RootCA Cert and initialize ContainerTokenManager.
https://issues.apache.org/jira/browse/HDDS-5789
Manually Verified this on a cluster.
**Before fix:**
```
2021-09-28 22:28:01,554 ERROR org.apache.hadoop.hdds.scm.server.StorageContainerManagerStarter: SCM start failed with exception
at org.apache.hadoop.hdds.scm.server.StorageContainerManager.createContainerTokenSecretManager(StorageContainerManager.java:726)
at org.apache.hadoop.hdds.scm.server.StorageContainerManager.initializeCAnSecurityProtocol(StorageC …
```
=> HDDS-5789. Enabling container tokens on a upgraded cluster fails SCM to start up.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyAclRequestWithFSO.java
When we repeatedly write a key and then delete the key. We should count all versions of the key and subtract them from bucket usedBytes.
Previously we only subtracted the key size of the last version, which resulted in inaccurate bucket usedBytes.
https://issues.apache.org/jira/browse/HDDS-5800
UT added
=> HDDS-5800. Bucket usedByte was incorrect when deleting duplicate keys.

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockDataStreamOutput.java
Streaming supports writing in Pipline mode
https://issues.apache.org/jira/browse/HDDS-5486
=> HDDS-5486. [Ozone-Streaming] Streaming supports writing in Pipline mode

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeUsageInfo.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/SimpleMockNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancer.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/container/testutils/ReplicationNodeManagerMock.java
when i test container balancer in k8s cluster,  i use the command line :
./ozone admin containerbalancer start -i -1 -t 0.000001 -d 1 -s 500, and set the contaienr size to 1G.
i found that balancer thread can not stop when the cluster is close to balance.
in my cluster , i have three datanodes d1,d2,d3(disk usage are 67G, 67G, 68G), and the fourth d4 datanode's disk usage is 1G. when i start balancer, it begin to balance and work well, many containers have been moved from d1,d2,d3 to d4. but when the cluster is close to balance(the disk usages of the four datanodes are 50G,52G,50G,51G), the balancer is still running , it will move container among those datanodes again and again.
let us see a general example. if we have two datanode d1 and  d2,  the disk usage are 3G and 7G respectively, …
=> HDDS-5757. balancer should stop when the cluster can not be balanced any more

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHA.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAMetadataOnly.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAWithData.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAWithFailover.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerPrepare.java
Currently tests under TestOzoneManagerHA take long to execute since MiniOzoneClusterHA is setting up freshly for each test case.
This is a proposal to spin up a shared MiniOzoneClusterHA for all the tests extending TestOzoneManagerHA, allowing them to reuse the same cluster and not have to spin up a new one every time.
This brings down the cumulative time to run all suites extending TestOzoneManagerHA down from ~720s to ~260s
https://issues.apache.org/jira/browse/HDDS-5788
Manual Testing
=> HDDS-5788. Reduce run time for TestOzoneManagerHA tests

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SequenceIdGenerator.java
2021-09-03 12:50:38,632 [1114efaf-c975-4ea0-bc8b-c3309a57cc8d@group-58D600BFB107-StateMachineUpdater] WARN org.apache.hadoop.hdds.scm.ha.SequenceIdGenerator: Failed to allocate a batch for localId, expected lastId is 0, actual lastId is 107544261438510000.
https://issues.apache.org/jira/browse/HDDS-5710
current unit test
=> HDDS-5710. initialize sequenceIdToLastIdMap when SequenceIdGenerator#StateManager reinitializes

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStreamWithFailures.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStreamWithFailuresFlushDelay.java
Combine some test cases in `TestBlockOutputStreamWithFailures` and `TestBlockOutputStreamWithFailuresFlushDelay` to reduce cluster creation/startup time.
https://issues.apache.org/jira/browse/HDDS-5793
Before:
```
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 585.121 s - in org.apache.hadoop.ozone.client.rpc.TestBlockOutputStreamWithFailuresFlushDelay
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 584.137 s - in org.apache.hadoop.ozone.client.rpc.TestBlockOutputStreamWithFailures
```
https://github.com/apache/ozone/runs/3728055559#step:4:2863
After:
```
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 294.082 s - in org.apache.hadoop.ozone.client.rpc.TestBlockOutputStreamWithFailuresFlushDelay
[INFO] Tests run: 2, …
```
=> HDDS-5793. Speed up TestBlockOutputStreamWithFailures by combining test cases

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeInfo.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneCluster.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMiniOzoneCluster.java
Support setting `org.apache.hadoop.hdds.scm.ScmConfigKeys#HDDS_DATANODE_DIR_DU_RESERVED` for each volume in each Datanode in `MiniOzoneCluster` (sets the same reserved space for each volume).
https://issues.apache.org/jira/browse/HDDS-5797
Passed `TestMiniOzoneCluster`
=> HDDS-5797. Support setting Datanode Reserved Space in MiniOzoneCluster.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java
Reduce trash interval in `TestOzoneFileSystem` for some speed gain.
https://issues.apache.org/jira/browse/HDDS-5799
Before:
```
[INFO] Tests run: 132, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 274.35 s - in org.apache.hadoop.fs.ozone.TestOzoneFileSystem
```
After:
```
[INFO] Tests run: 132, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 212.662 s - in org.apache.hadoop.fs.ozone.TestOzoneFileSystem
```
https://github.com/adoroszlai/hadoop-ozone/runs/3754181848#step:4:2881
(part of the difference is due to the latter CI run being faster overall)
=> HDDS-5799. Speed up TestOzoneFileSystem by using shorter trash interval

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestDataUtil.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
In BasicRootedOzoneClientAdapterImpl, Inherit bucket default replication config only in the case of EC
https://issues.apache.org/jira/browse/HDDS-5784
Added tests
=> HDDS-5784: EC: In BasicRootedOzoneClientAdapterImpl, Inherit bucket default replication config only in the case of EC.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ECReplicationConfig.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockInputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneClient.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestECKeyOutputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestECBlockInputStream.java
The EC Chunksize is currently hard coded in ECBlockInputStream and ECBlockOutputStream. Now that ECReplicationConfig carries the chunkSize and codec, we can remove these hardcoded values.
https://issues.apache.org/jira/browse/HDDS-5775
Existing tests
=> HDDS-5741. EC: Remove hard coded chunksize and get from from ReplicationConfig

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/GrpcOmTransport.java, hadoop-ozone/dist/src/main/compose/ozone/docker-config, hadoop-ozone/dist/src/main/compose/ozone/test.sh, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/OzoneClientCache.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/OzoneClientProducer.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/UgiFilter.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/signature/AWSSignatureProcessor.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/signature/StringToSignProducer.java, hadoop-ozone/s3gateway/src/main/resources/webapps/s3gateway/WEB-INF/web.xml, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/TestOzoneClientProducer.java
This patch adds to the s3gateway gRPC feature three main items.  CDI filter extracting user aws authentication and creating  user thread context, a cached ozone client and changes to the OzoneManagerProtocol.   The cached ozone client processes s3 requests through a persistent connection between the s3 gateway and the om.   This single OzoneClient services all s3 requests.  S3 http requests are processed through a CDI interface that includes a CDI filter that extracts s3 authentication information, `awsAccessId` & `signature`, generates the `stringToSign` and adds these to an OzoneToken processed through the single cached OzoneClient.  The OzoneClient submits the request to the om through the` OzoneManagerProtocol` (`OmRequest`) over gRPC OmTransport.
The CDI filter servicing http …
=> HDDS-5612. Create Ozone s3 authentication token and client authentication transport

pom.xml
Update `commons-io` to 2.11.0.
https://issues.apache.org/jira/browse/HDDS-5808
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1304376420
```
$ mvn -DskipTests -Dskip.installnpx -Dskip.npx -DskipShade clean package
$ find hadoop-ozone/dist/target/ozone* -name 'commons-io*jar'
hadoop-ozone/dist/target/ozone-1.2.0-SNAPSHOT/share/ozone/lib/commons-io-2.11.0.jar
```
=> HDDS-5808. Update commons-io to 2.11.0

pom.xml
Define properties for some of the dependencies (e.g. `commons-io`, etc.).  This makes it easier to override versions.
https://issues.apache.org/jira/browse/HDDS-5817
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1307847487
Compared list of artifacts in `share/ozone/lib` before/after the change, verified there is no difference.
=> HDDS-5817. Extract properties for some dependency versions

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
Currently the RPCClient sets the open key session to the KeyOutputStream during a write initialization.
From the OpenKeySession, the KeyOutputStream fetches the OMKeyInfo, and then from that the FileEncryptionInfo.
The sole reason to do this is to provide a getter for the FileEncryptionInfo object, which then retrieved by the RPCClient later on.
So that the reference can be removed from KeyOutputStream as it is unnecessary, this PR is here to remove it.
https://issues.apache.org/jira/browse/HDDS-5815
Standard JUnit tests + CI, simple change no extra test efforts added.
=> HDDS-5815 FileEncryptionInfo is not necessary to be referenced inside KeyOutputStream

hadoop-ozone/dist/src/main/compose/ozone/test.sh, hadoop-ozone/dist/src/main/smoketest/httpfs/operations.robot, hadoop-ozone/dist/src/main/smoketest/httpfs/operations_tests.robot
Added robot tests for the HttpFS gateway. In the tests we use curl command to try out the operations and check the response for the expected objects. The robot tests are added in the compose/ozone test.sh script.
https://issues.apache.org/jira/browse/HDDS-5615
The robot tests were run by the test.sh script in the compose/ozone directory and all the test cases passed.
=> HDDS-5615 Add a simple test suite for HTTPFS GW

CONTRIBUTING.md
At present, Ozone recommends that `idea.max.intellisense.filesize` is set to `5000`, but it can no longer bear some protoc files in the Ozone project, such as `OzoneManagerProtocolProtos.java`. (As shown below)
The purpose of this PR is to make the change of **idea.max.intellisense.filesize=10000** in the Apache Ozone Contribution guide more in line with the needs of the current project.
https://issues.apache.org/jira/projects/HDDS/issues/HDDS-5830
After increasing `idea.max.intellisense.filesize`, the error message disappeared.
=> HDDS-5830. Increase idea.max.intellisense.filesize

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntry.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntryPool.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java
During Erasure Coding development, we would like to reuse BlockOutputStreamEntryPool, BlockOutputStreamEntry, and BlockOutputStream, to handle most of the work as the general way of handling writes, and only add specialisations as needed.
In order to prepare for this, some changes are necessary in the basic classes, this JIRA is to bring in those changes to the master so that we do not have too distinct versions in the two branch making merges much more complicated than necessary.
Some more changes might be required during the development, these are related to the changes in HDDS-5755.
https://issues.apache.org/jira/browse/HDDS-5816
junit+CI, changes should no change how the logic works, no new tests added.
=> HDDS-5816 Rearrange code and refactor some logic into new methods in prep for EC addition.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java
This test was added in arallel to ECREplicationCOnfig change. Since pr CI's ran independetly they both got green. But one change impacted other without conflicts. 
Now fixed the test to adapt the ECReplicationConfig change. Besically ECKeyOutputStream#close has issue with partial chunk size(HDDS-5825). So, keeping the chunk config to match 1024.
https://issues.apache.org/jira/browse/HDDS-5833
Failed test passing.
=> HDDS-5833: EC: Fix TestRootedOzoneFileSystem.testBucketDefaultsShouldBeInheritedToFileForEC failure in branch

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/LocalStream.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/conf/DatanodeRatisServerConfig.java
RATIS-1406 added a new API for providing an Executor to StateMachine.DataStream. In this JIRA, we use this new API to provide an Executor for each LocalStream in ContainerStateMachine.
https://issues.apache.org/jira/browse/HDDS-5763
No new tests are needed.
=> HDDS-5763. Provide an Executor for each LocalStream in ContainerStateMachine

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestSecureOzoneRpcClient.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerProtocolServerSideTranslatorPB.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/S3SecurityUtil.java
When OMRequest has S3Authentication for read requests validate S3Authentication and then proceed with processing the request.
Note: This PR is dependent on HDDS-5884, for ease of review included HDDS-5884.
https://issues.apache.org/jira/browse/HDDS-5884
Added tests
=> HDDS-5885. OM Auth Validate for read requests and handle non ratis enabled code.

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmKeyInfo.java
This is happening due to bug in a copyObject where we are not using Version uploaded isMPU or not.
This issue will cause reads to fail, as the returned OmKeyInfo version will not have MPU flag set.
https://issues.apache.org/jira/browse/HDDS-5908
Added test
=> HDDS-5908. MPU getKey can fail, if completeMPU result is still in cache.

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/GrpcOmTransport.java, hadoop-ozone/dist/src/main/compose/ozonesecure/docker-config, hadoop-ozone/dist/src/main/compose/ozonesecure/test.sh, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/OMClientRequest.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/EndpointBase.java
… error responses to client on error (fixing general 500 response in current gateway).
S3 gateway Gprc support for all ozone s3 supported client requests with security and ACLs enabled.  This PR adds s3g Grpc acl support with patches to the `OMClientRequest` user thread context and to the `ozone manager`.  
Included in this PR are enhancements to the s3 gateway client to return meaningful error responses, http return codes and descriptions, to the caller on error.  For example a user accessing a resource **_without_** permission is returned `HTTP 403` `AccessDenied`.  Previously all errors on client creation return `HTTP 500`.
All secure cluster smoke tests are re-enabled in this PR.  Secure cluster is updated to enable s3g Grpc and to enable all s3 gateway acceptance tests. …
=> HDDS 5781. Enable ACLs and support for all s3 file operations.

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/S3Auth.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/S3Authentication.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerClientProtocol.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/OzoneClientProducer.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/BucketEndpoint.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/EndpointBase.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/RootEndpoint.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/TestOzoneClientProducer.java
S3G client will now set the S3 Auth information for
each OM Request. S3G itself will authenticate as S3G
identity registered with Kerberos but Request
Processing should be done via the S3 Auth set in the
protobuf request.
https://issues.apache.org/jira/browse/HDDS-5883
This was tested with code for 
https://issues.apache.org/jira/browse/HDDS-5884 and
https://issues.apache.org/jira/browse/HDDS-5885
Objects created were inspected in the OM DB. Objects were created using OM's key tab 
``` "fileName": "key2",
"acls": [
{
"type": "USER",
"name": "om/om@EXAMPLE.COM",
"aclBitSet": [
0,
0,
0,
0,
0,
0,
0,
1
],
"aclScope": "ACCESS"
},
{
"type": "GROUP",
"name": "root",
"aclBitSet": [
0,
0,
0,
0,
0,
0,
0,
1
],
"aclScope": "ACCESS"
}
],
"parentObjectID": 0,
"objectID": -9223372036854773504, …
```
=> HDDS-5883 Change S3G client to set S3 Auth per req

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockInputStream.java, hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ChunkInputStream.java, hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/DummyBlockInputStreamWithRetry.java, hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestBlockInputStream.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/storage/ContainerProtocolCalls.java
Retry when getChunks/readChunk fail with IOException due to DN connectivity issue/down.
https://issues.apache.org/jira/browse/HDDS-5864
Added UT.
=> HDDS-5864. Retry when DN connection issue during getBlock/ReadChunk call during Ozone key Read

hadoop-hdds/docs/themes/ozonedoc/layouts/partials/navbar.html, hadoop-hdds/docs/themes/ozonedoc/layouts/partials/sidebar.html
Update navbar from Hadoop to Ozone on doc page.
https://issues.apache.org/jira/browse/HDDS-5736
Local hugo test.(as shown below)
=> HDDS-5736. Update navbar from Hadoop to Ozone on doc page

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStoreIterator.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TableIterator.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStoreIterator.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogStateManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileRequest.java
It was found that there is discrepancy in the implementation of the next(), key() and value() methods in the RDBStoreIterator wrapper class.
next() returns the current rocksdb entry and moves ahead to the next entry.
key() returns current rocksdb entry's key.
value() returns current rocksdb entry's value.
This means that during iteration next() returns the current value, and subsequent calls to key() / value() after next() will return the next value. To solve this, we can remove those 2 APIs from the iterator class, and have the usages follow this pattern.
https://issues.apache.org/jira/browse/HDDS-3983
Unit tests locally.
=> HDDS-3983 Ozone RocksDB Iterator wrapper should not expose key() and value() API.

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java
HandleFlush involves the write process. The write process is complex, and some unexpected exceptions can occur. For example, the client is missing some JAR dependencies due to misconfiguration. Some NoClassDefFoundError occurs, which is not catch and makes it difficult for the user to know why the write failed.
This PR we will display a more detailed log.
https://issues.apache.org/jira/browse/HDDS-5924
=> HDDS-5924. Support more detailed error log when handleFlush.

hadoop-hdds/docs/content/feature/Topology.md, hadoop-hdds/docs/content/start/FromSource.md, hadoop-ozone/dist/README.md
Fix some broken links in `hadoop-ozone/dist/README.md`.
https://issues.apache.org/jira/browse/HDDS-5931
:eyes:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1418092516
=> HDDS-5931. Broken link in dist/README

hadoop-hdds/docs/content/security/SecuringOzoneHTTP.md
Suffix 'anonymous_allowed' is wrong SecuringOzoneHTTP.md, then we can't authorize the anonymous user use this config.
https://issues.apache.org/jira/browse/HDDS-5925
manual tests
=> HDDS-5925. Fix SecuringOzoneHTTP doc

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/OzoneManagerServiceProviderImpl.java
Fix a typo in OzoneManagerServiceProviderImpl.java: `isOmSpengoEnabled` --> `isOmSpnegoEnabled`.
https://issues.apache.org/jira/browse/HDDS-5944
=> HDDS-5944. Fix typo in OzoneManagerServiceProviderImpl.java

hadoop-ozone/pom.xml
Bump Spring Framework to most recent release on the same line (5.2.18).
https://issues.apache.org/jira/browse/HDDS-5935
```
$ mvn -DskipTests clean package
...
$ cd hadoop-ozone/dist/target/ozone-1.2.0-SNAPSHOT/share/ozone/lib
$ ls | grep spring
spring-beans-5.2.18.RELEASE.jar
spring-core-5.2.18.RELEASE.jar
spring-jcl-5.2.18.RELEASE.jar
spring-jdbc-5.2.18.RELEASE.jar
spring-tx-5.2.18.RELEASE.jar
```
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1420193725
=> HDDS-5935. Bump Spring to 5.2.18

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockInputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockReconstructedStripeInputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/InsufficientLocationsException.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestECBlockInputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestECBlockReconstructedStripeInputStream.java
This PR introduces a class called ECBlockReconstructedStripeInputStream. This class is intended to read an EC block when one or more of the data blocks are missing. Its interface allows for full EC stripes of data to be returned to the client, where some of the data is reconstructed via EC Decoding.
It is not intended for this class to be part of a public facing API. It will instead be used inside a public "EC Input Stream" class which will decide to use a non-reconstruction or reconstruction read depending on how many locations are available or how if any reads fail. This public class is yet to be adapted to use this new class, and that will be taken care of in further PR.
As part of this change, changes were made to ECBlockInputStream to allow some common code to be shared by this new …
=> HDDS-5551. EC: Implement an Input Stream to reconstruct EC blocks on demand

pom.xml
JIRA: https://issues.apache.org/jira/browse/HDDS-5947
Bump the version of Mina dependency to avoid https://github.com/advisories/GHSA-6mcm-j9cj-3vc3
Full CI
=> HDDS-5947. Remove unused mina-core and sshd-core dependencies

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/S3Auth.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/OzoneClientProducer.java
Ensure that if the client has asked for S3 style auth, each request
sent has S3 Auth information set.
https://issues.apache.org/jira/browse/HDDS-5910
Set the validation to trip always and insure it catches the missing auth.
=> HDDS-5910 Add additional verification for S3 Auth.

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/BucketArgs.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/bucket/CreateBucketHandler.java
CreateBucketHandler exposes "--type" argument, its good to reflect the layout behavior in the option name.
```
@Option(names = \{ "--type", "-t" },
description = "Allowed Bucket Types: ${COMPLETION-CANDIDATES}",
defaultValue = "OBJECT_STORE")
```
This task is to correct the option name to "-bucketlayout", "-l"
https://issues.apache.org/jira/browse/HDDS-5960
existing tests
=> HDDS-5960. Change option name to bucketlayout instead of type

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystemWithFSO.java
…n Shell
There is a bug in the info being displayed from the Ozone Shell regarding the bucket layouts. The information displayed is inconsistent with the actual underlying behaviour.
The bucketLayout is being listed as LEGACY when you use the list command (which is incorrect) and is being shown as FILE_SYSTEM_OPTIMIZED when using the info command (which is the correct value)
```
bash-4.2$ ozone sh volume create /vol1
bash-4.2$ ozone sh bucket create /vol1/buck1 --type=FILE_SYSTEM_OPTIMIZED
bash-4.2$ ozone sh bucket list /vol1/
[
{ "metadata" : { }
,
"name" : "buck1",
"creationTime" : "2021-11-02T05:55:35.311Z",
"modificationTime" : "2021-11-02T05:55:35.311Z", …
```
=> HDDS-5937. Inaccurate bucket info returned from bucket list command in Shell

hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/codec/OmKeyInfoCodec.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/file/TestOMFileCreateRequestWithFSO.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyAclRequestWithFSO.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCommitRequestWithFSO.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/file/TestOMFileCreateResponseWithFSO.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMAllocateBlockResponseWithFSO.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeyCommitResponseWithFSO.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeyCreateResponseWithFSO.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeyDeleteResponseWithFSO.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestNSSummaryEndpoint.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestNSSummaryTask.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/PrefixParser.java
THe cluster wide isBucketFSOptimized is not needed anymore, this code removes this flag.
https://issues.apache.org/jira/browse/HDDS-5982
=> HDDS-5982. Remove isBucketFSOptimized flag.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeSchemaOneDBDefinition.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/DBDefinitionFactory.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/DBScanner.java, hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/debug/TestDBDefinitionFactory.java
Currently the LDB DBScanner Tool only supports DatanodeDBDefinition Schema V2. The aim here is to support both schemas V1 and V2.
https://issues.apache.org/jira/browse/HDDS-5906
`bin/ozone debug ldb --db=/Users/sadanand.shenoy/4-dn-container.db scan --column_family=default -d=V1
`
=> HDDS-5906. Fix DBScanner to support Datanode DB

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/PrefixParser.java
Prefix Parser tool will only work against FSO buckets, this jira adds a check for that
https://issues.apache.org/jira/browse/HDDS-5983
Existing tests
=> HDDS-5983. Prefix Parser tool should only work for FSO buckets.

pom.xml
Preparing for the **native** (not using x86 JVM via Rosetta 2) Apple Silicon (darwin/osx aarch64/arm64 architecture) development environment.
See plugin release notes: https://github.com/salesforce/proto-backwards-compat-maven-plugin/releases
Side note: I am able to dev and run tests in IntelliJ with darwin arm64 native JVM after compiling 3 different protobuf versions for arm64, and compiling rocksdbjni 6.25.3 for osx-aarch64. Running native arm64 is significantly faster than using x86 JVM with Rosetta 2 translation layer on an M1-series Mac. Docker [ozone-runner](https://github.com/apache/ozone-docker-runner) still only has x86 containers for now (which can be run in x86 qemu for testing, but slow).
=> HDDS-5957. Bump proto-backwards-compatibility from 1.0.5 to 1.0.7

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/BucketManagerImpl.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestBucketManagerImpl.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
https://issues.apache.org/jira/browse/HDDS-5891
1. `BucketManagerImpl#getBucketInfo` can now throw `VOLUME_NOT_FOUND` if the parent volume **doesn't exist**, and will only throw `BUCKET_NOT_FOUND` if the parent volume **exists** but the bucket doesn't. Before this change it throws `BUCKET_NOT_FOUND` regardless of whether parent volume exists. Related prior comment: https://github.com/apache/ozone/pull/2412#discussion_r672513719
- And the new behavior is more in line with [BucketManagerImpl#createBucket](https://github.com/apache/ozone/blob/18f0fe14034c048a810365f130e3147001c27da8/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/BucketManagerImpl.java#L126-L137). Thanks @fapifta for pointing this out.
2. With the patch, `BasicRootedOzoneClientAdapterImpl#getBucket` will …
=> HDDS-5891. OFS mkdir -p does not work as expected for bucket creation when volume exists due to volume create ACL check

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneAtRestEncryption.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java
We should reset the file encryption info during MPU complete request.
https://issues.apache.org/jira/browse/HDDS-5980
Updated test.
=> HDDS-5980. [S3- TDE] Get on a key which is overwrite through MPU on a TDE bucket, the data does not match with uploaded data.

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/UsageInfoSubcommand.java
Improved readability of `usageinfo` by showing sizes in appropriate units. Also added the `Total Used` field. Here's a description of the output:
- `Capacity`: Total capacity of the datanode, read from the SCM.
- `Ozone Used`: Space used by Ozone, read from the SCM.
- `Remaining`: Total remaining space, read from the SCM.
- `Total Used`: `Capacity` - `Remaining`, or the total used space.
https://issues.apache.org/jira/browse/HDDS-5870
Manual testing using docker-compose.
=> HDDS-5870. Make Datanode usageinfo command output more readable

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientWithRatis.java
https://issues.apache.org/jira/browse/HDDS-5879
OzoneBucket and RpcClient not support multipart upload with Stream.
Add the createMultipartStreamKey method
=> HDDS-5879. [Ozone-Streaming] OzoneBucket add the createMultipartStreamKey method

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/rpc/RpcClientTest.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/ServiceInfo.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/OzoneClientProducer.java
To avoid an S3G that sets S3 Auth via proto messages
talking to an older version of OM. Add a check to
validate OM's client protocol version.
https://issues.apache.org/jira/browse/HDDS-5898
=> HDDS-5898 S3G in secure mode checks OM version.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMStateMachine.java
If the IO exception is met during the raft log being written for the leader SCM, it will endlessly be stuck in the timeout exception.
We should let the leader SCM crash for this kind of IO issue and possibly this will **notice the maintainer**.
After the SCM crashes, there are two scenarios: 
1. IO-err SCM restarted: 
Most likely, it will become a follower and even it cannot commit a raft log, it won't affect the leader.
2. IO-err SCM not restarted:
There are two SCMs remain working, which is still doable for ratis.
https://issues.apache.org/jira/browse/HDDS-5976
manual test in K8S
=> HDDS-5976. add raftlog IOException notifier for SCM ratis

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMStartupWithBucketLayout.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
I have a ozone cluster, prefix is enable when setup cluster. when restart om, then error below:
```
java.io.IOException: Failed to start OM in PREFIX layout format as existing bucket has a different layout SIMPLE metadata format
```
This issue is similar to HDDS-5094. Later in  HDDS-5362, bucket layout is supported, then addFSOptimizedBucketDetails is removed in this https://github.com/apache/ozone/commit/7df192530810a07d3b976c3a56c46328c0b1d591. So om crash when restart if layout is PREFIX.
I think there is no need to validate bucket type since HDDS-5362.
https://issues.apache.org/jira/browse/HDDS-5664
unit tests and manual tests.
=> [FSO] Allow existing/old buckets with any layout during OM startup

hadoop-ozone/httpfsgateway/src/main/java/org/apache/ozone/fs/http/server/HttpFSServer.java
In this PR I went through the handling of the operations in the HttpFSServer class. There are operations that are not implemented yet in the BasicOzoneFileSystem or in the BasicRootedOzoneFileSystem. In these cases I throw an UnsupportedOperationException in the HttpFSServer.
In the jira it is mentioned to also handle of invalid operations on volumes or buckets. I checked these and we throw IOException from the BasicRootedOzoneClientAdapterImpl in these cases.
https://issues.apache.org/jira/browse/HDDS-5828
Built the project successfully.
=> HDDS-5828 [HTTPFSGW] Add proper handling for unsupported operations

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerConfiguration.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancer.java
Changes to support excluding certain Datanodes from balancing. The configurations can be provided as a list of comma separated host names or IP addresses.
Include Nodes: Include only these nodes in the balancing process.
Exclude Nodes: Exclude these nodes from the balancing process.
Nodes that are specified in both these lists should be excluded.
The configurations are read and these nodes are excluded in the `initializeIteration` method in `ContainerBalancer`.
https://issues.apache.org/jira/browse/HDDS-5897
Added a UT to `TestContainerBalancer`
=> HDDS-5897. Support configuration for including/excluding datanodes for balancing

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientSpi.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/ContainerUtils.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/helpers/TestContainerUtils.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineFailures.java
Remove binary data from write chunk requests before printing to log or adding to exception message.
https://issues.apache.org/jira/browse/HDDS-5989
Added assertion in existing integration test.
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1470982770
=> HDDS-5989. Binary content printed for failed chunk write

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockReconstructedInputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/ECStreamTestUtil.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestECBlockInputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestECBlockReconstructedInputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestECBlockReconstructedStripeInputStream.java
ECBlockReconstructedStripeInputStream allows an EC block to be read and reconstructed stripe by stripe. We need an InputStream to wrap this, so clients can read and seek the stream via the usual InputStream read methods.
https://issues.apache.org/jira/browse/HDDS-6001
New unit tests
=> HDDS-6001. EC: Create ECBlockReconstructedInputStream to wrap ECBlockReconstructedStripeInputStream

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/DatanodeChunkGenerator.java
Freon Datanode Chunk Generator fails with NPE in secure cluster. It is should give a meaningful message about not being supported in secure cluster.  It seems this was broken in HDDS-4475.
```
$ cd hadoop-ozone/dist/target/ozone-*/compose/ozonesecure
$ docker-compose up -d --scale datanode=3
$ docker-compose exec scm ozone freon dcg -n1 -t1
...
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:880)
at org.apache.hadoop.hdds.scm.XceiverClientManager.<init>(XceiverClientManager.java:94)
at org.apache.hadoop.hdds.scm.XceiverClientManager.<init>(XceiverClientManager.java:82)
at org.apache.hadoop.ozone.freon.DatanodeChunkGenerator.call(DatanodeChunkGenerator.java:107)
at org.apache.hadoop.ozone.freon.DatanodeChunkGenerator.call(DatanodeChunkG …
```
=> HDDS-6011. Freon datanode chunk generator fails with NPE in secure cluster

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementCapacity.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementCapacity.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/container/placement/TestContainerPlacement.java
SCMContainerPlacementCapacity to choose lower utilized node. Right now instead of choosing a lower utilized node, a higher utilized node is being chosen.
https://issues.apache.org/jira/browse/HDDS-5804
This patch is tested using CI tests.
=> HDDS-5804. SCMContainerPlacementCapacity to choose lower utilized node

hadoop-ozone/dist/src/main/smoketest/s3/objectdelete.robot
Remove an assertion from S3 delete-object test, where the response from S3G was expected not to contain `500`.  Values of `Key`, `LastModified` or `ETag` headers may contain this substring, causing the test to fail unnecessarily, as observed in these runs:
* https://github.com/elek/ozone-build-results/tree/master/2021/07/14/8932/acceptance-unsecure/
* https://github.com/elek/ozone-build-results/tree/master/2021/10/29/11160/acceptance-unsecure/
* https://github.com/elek/ozone-build-results/tree/master/2021/11/02/11195/acceptance-unsecure/
I have not found any other test that checks for HTTP 500 code.  The result code of `aws` command reflects whether it was successful or not, and `Execute` checks for that code, expecting `0`.  Thus I think the assertion is not needed.
On the other hand, we …
=> HDDS-5917. S3 acceptance test failure due to too wide assertion

hadoop-ozone/dist/src/main/smoketest/basic/ozone-shell-single.robot, hadoop-ozone/dist/src/main/smoketest/basic/ozone-shell.robot
`Test ozone shell` is a parameterized test case in `basic` smoketest.  It is executed with arguments `"", ""` (`${EMPTY}, ${EMPTY}`) twice for `ozone` and `ozonesecure` environments (_acceptance (unsecure)_ and _acceptance (secure)_): both by `ozone-shell-single.robot` and `ozone-shell.robot`.  This PR eliminates duplicate execution to save ~3 minutes runtime for these runs.
https://issues.apache.org/jira/browse/HDDS-5936
https://github.com/adoroszlai/hadoop-ozone/runs/4105130510?check_suite_focus=true#step:5:171
https://github.com/adoroszlai/hadoop-ozone/runs/4105130564?check_suite_focus=true#step:5:233
=> HDDS-5936. Duplicate Test Ozone Shell invocation

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockReconstructedStripeInputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestECBlockReconstructedStripeInputStream.java
Add tests to ensure that ECBlockReconstructedStripeInputStream works when there are no missing indexes. If there are no missing indexes, avoid padding and EC decoding the buffers.
https://issues.apache.org/jira/browse/HDDS-6009
Modified existing tests
=> HDDS-6009. EC: Optimize ECBlockReconstructedStripeInputStream where there are no missing data indexes

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/OzoneClientConfig.java, hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockDataStreamOutput.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneCluster.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockDataStreamOutput.java
Currently, putBlock call gets executed only during close() when a block is written. The aim here is to have a putBlock boundary similar to async path where the putBlock gets executed which updates the key length and help reduce some memory on client. The  default boundary here is set at 32 MB where a putBlock is executed.  Also a limit is set on the ByteBuffer size the client can send  here (4mb).
https://issues.apache.org/jira/browse/HDDS-5851
Unit test
=> HDDS-5851. [Ozone-Streaming] Define a PutBlock/maxBuffer fixed boundary for streaming writes.

hadoop-ozone/dist/src/main/smoketest/freon/generate.robot, hadoop-ozone/dist/src/main/smoketest/freon/validate.robot, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/DatanodeChunkGenerator.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/DatanodeChunkValidator.java
Datanode chunk validator was failing because datanode would not return the requested chunk due to bcsID mismatch (check added in HDDS-4986):
```
StorageContainerException: Unable to find the block with bcsID 2 .Container 1 bcsId is 0.
at org.apache.hadoop.ozone.container.keyvalue.helpers.BlockUtils.verifyBCSId(BlockUtils.java:206)
at org.apache.hadoop.ozone.container.keyvalue.KeyValueHandler.handleReadChunk(KeyValueHandler.java:604)
```
https://issues.apache.org/jira/browse/HDDS-6000
Added smoketest.
```
$ ozone freon dcg -p dcg
[main] INFO freon.BaseFreonGenerator: Executing test with prefix dcg
[Thread-4] INFO freon.ProgressBar: Progress: 0.00 % (0 out of 1000)
...
[Thread-4] INFO freon.ProgressBar: Progress: 100.00 % (1000 out of 1000)
[shutdown-hook-0] INFO metrics: type=TIMER, …
```
=> HDDS-6000. Freon datanode chunk validator fails checksum validation

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OzoneFSUtils.java, hadoop-ozone/dist/src/main/compose/ozone-mr/common-config, hadoop-ozone/dist/src/main/compose/ozonesecure/docker-config, hadoop-ozone/dist/src/main/compose/xcompat/docker-config, hadoop-ozone/dist/src/main/smoketest/createmrenv.robot, hadoop-ozone/dist/src/main/smoketest/ozonefs/setup.robot, hadoop-ozone/dist/src/main/smoketest/security/ozone-secure-fs.robot, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFSInputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileInterfaces.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemMissingParent.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemWithLinks.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsHAURLs.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/OzoneContract.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestHadoopDirTreeGenerator.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestHadoopNestedDirGenerator.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestObjectStore.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientUtils.java
Throw an exception if a bucket accessed via OFS is in OBJECT_STORE layout. Allowed layouts are FILE_SYSTEM_OPTIMIZED and LEGACY.
https://issues.apache.org/jira/browse/HDDS-5959
Related integration tests.
=> HDDS-5959. Handles bucket layout validation logic in ofs/o3fs client.

hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/TestUgiFilter.java
Adding a test for new ugi filter.  This code was written entirely by [Neil Joshi](https://github.com/neils-dev)
https://issues.apache.org/jira/browse/HDDS-5778
```
cd hadoop-ozone/s3gateway
mvn -Dtest=TestUgiFilter test
```
=> HDDS-5778. Client side unit tests

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/DatanodeChunkValidator.java
Fix pipeline ID comparison in datanode chunk validator.  The problem was that the result of `PipelineID.toString()` includes the prefix `PipelineID=`, and this was being compared to the plain pipeline ID provided in command-line argument.  We should be comparing only the actual ID.
https://issues.apache.org/jira/browse/HDDS-5999
Manual test:
```
$ p=$(ozone admin pipeline list --filterByFactor ONE | cut -f1 -d',' | cut -f3 -d' ' | head -1)
$ ozone freon dcg -n10 -t1 -p dcg1 --pipeline "$p"
...
2021-12-01 07:01:35,208 [main] INFO freon.DatanodeChunkGenerator: Writing to pipeline: PipelineID=6fedc039-b936-43b3-969a-2e3d75331c44
...
Successful executions: 10
$ ozone freon dcv -n10 -t1 -p dcg1 --pipeline "$p"
...
Successful executions: 10
```
CI: …
=> HDDS-5999. Freon datanode chunk validator does not find pipeline from param

hadoop-hdds/interface-admin/src/main/resources/proto.lock, hadoop-hdds/interface-client/src/main/resources/proto.lock, hadoop-hdds/interface-server/src/main/resources/proto.lock, hadoop-ozone/interface-client/src/main/resources/proto.lock
Cherry pick proto.lock changes from ozone-1.2 release branch to master, so that all builds will check for protobuf backwards incompatibilities between master and 1.2.0.
Note: proto locks were not updated after 1.1.0 release so the change set is extra large.
[Original commit](https://github.com/apache/ozone/commit/62bbaef9ef44bb78f2f3f29c4ccf5ec5b7151e98) on the release branch.
HDDS-6014
Normal build process which runs the proto-backwards-compatability check.
=> HDDS-6014. Add proto.lock files from ozone-1.2 release branch to master

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeConfiguration.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/XceiverServerGrpc.java
https://issues.apache.org/jira/browse/HDDS-5962
=> HDDS-5962. Limit grpc threads in XceiverServerGrpc.

pom.xml
Upgrade `aws-java-sdk` to 1.12.
https://issues.apache.org/jira/browse/HDDS-6058
CI
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1526858610
=> HDDS-6058. Bump aws-java-sdk to latest 1.12

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ratis/RatisHelper.java
In secure environments, datanode's request to addGroup in other datanodes fails with `Network closed for unknown reason`.  Thus pipeline creation essentially becomes async, just like before HDDS-2679.
The problem is that Ratis sends group management request via a separate admin channel, but currently only real "client" channel is configured for TLS when performing the add group request.  We need to configure TLS for talking to the admin endpoint, too.
https://issues.apache.org/jira/browse/HDDS-6061
Added temporary code to consistently reproduce the problem.  By ignoring create pipeline command from SCM, the datanode relies on peers to add the Ratis group.
```
diff --git hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CreatePi …
```
=> HDDS-6061. Peer datanode cannot add group for pipeline in secure env 

hadoop-hdds/interface-client/src/main/proto/hdds.proto, hadoop-ozone/recon-codegen/src/main/java/org/hadoop/ozone/recon/schema/ContainerSchemaDefinition.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/codec/ContainerReplicaHistoryListCodec.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/fsck/ContainerHealthStatus.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/persistence/ContainerHealthSchemaManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/persistence/ContainerHistory.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ContainerReplicaHistory.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ContainerReplicaHistoryList.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconContainerManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/ReconContainerMetadataManagerImpl.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/ReconDBDefinition.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestContainerEndpoint.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/fsck/TestContainerHealthTask.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconContainerManager.java
The ContainerHealthTask in Recon currently classifies a container whose 3 replicas are UNHEALTHY as 'MISSING'. Although the 3 UNHEALTHY replica state could also be potentially bad, Recon should be able to distinguish between the two.
The above case can merely be classified as UNDER REPLICATED, with the metadata from Recon DB carrying the actual vs desired replica count for further analysis.
This patch also adds support to track the bcsId reported by datanodes to Recon. This information is kept in the container cache, and flushed to disk only periodically. 
https://issues.apache.org/jira/browse/HDDS-5965
https://issues.apache.org/jira/browse/HDDS-6050
=> HDDS-5965. Recon should be able to distinguish between containers that have no replicas and those have all replicas as UNHEALTHY.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeConfiguration.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
Changing the stateMachine caching gurantees.
https://issues.apache.org/jira/browse/HDDS-3227
Existing UTs
=> HDDS-3227. Ensure eviction of stateMachineData from cache only when both followers catch up

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainer.java
Currently, we do not have enough debugging information on the datanode to debug unhealthy state.
This patch adds a simple debugging logging statement to help debug the issue
https://issues.apache.org/jira/browse/HDDS-6067
Existing tests
=> HDDS-6067. Improve Debugging around unhealthy container state on Datanode.

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BadDataLocationException.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockInputStreamFactoryImpl.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockInputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockInputStreamFactory.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockInputStreamFactoryImpl.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockInputStreamProxy.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockReconstructedStripeInputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockStreamFactoryImpl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/ECStreamTestUtil.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestBlockInputStreamFactoryImpl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestECBlockInputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestECBlockInputStreamProxy.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestECBlockReconstructedStripeInputStream.java
When all data locations are available, the most efficient reader is ECBlockInputStream. It also uses less memory as it does not need to buffer the full stripe. When some data locations are missing, we need to use ECBlockReconstructedStripeInputStream and ECBlockReconstructedInputStream together. There needs to be a wrapper class which creates and uses the correct underlying stream depending on data location availability.
https://issues.apache.org/jira/browse/HDDS-6010
New tests
=> HDDS-6010. EC: Create ECBlockInputStreamProxy to choose between reconstruction and normal reads

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/ResourceLimitCache.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/utils/TestResourceLimitCache.java
`ResourceLimitCache` limits its size by using a group of permits.  `put` requires free permit before it can add data.  However, `removeIf` does not release permits.
https://issues.apache.org/jira/browse/HDDS-6071
Also, previously `TestRandomKeyGenerator` has been [timing out](https://github.com/apache/ozone/runs/4440507728?check_suite_focus=true#step:4:3010) since HDDS-3227 was merged.  It is passing with the patch.
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1549379969
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1549427103
=> HDDS-6071. ResourceLimitCache leaks permits

hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/OzoneContract.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestStandardOutputUtil.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientMultipartUploadWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestReadRetries.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestHadoopDirTreeGeneratorWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestRecursiveAclWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestNSSummaryAdmin.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketCreateRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/TestOMRequestUtils.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestBucketRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestOMBucketCreateRequestWithFSO.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/file/TestOMDirectoryCreateRequestWithFSO.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/DiskUsageSubCommand.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/FileSizeDistSubCommand.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/NSSummaryAdmin.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/NSSummaryCLIUtils.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/QuotaUsageSubCommand.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/SummarySubCommand.java
This task is to remove the metadata layout config as bucket type will be an argument. Also, will define `ozone.bucket.type.default` to handle a case where the user is not passing any args.
https://issues.apache.org/jira/browse/HDDS-5385
related integration tests
=> HDDS-5385. [FSO] Remove ozone.om.metadata.layout config in OM

hadoop-hdds/docs/content/concept/Containers.md, hadoop-hdds/docs/content/concept/Datanodes.md, hadoop-hdds/docs/content/concept/OzoneManager.md, hadoop-hdds/docs/content/concept/Recon.md, hadoop-hdds/docs/content/feature/OM-HA.md, hadoop-hdds/docs/content/feature/PrefixFSO.md, hadoop-hdds/docs/content/feature/SCM-HA.md, hadoop-hdds/docs/themes/ozonedoc/layouts/shortcodes/image.html
This task is to fix images' alignment in different docs pages and prevent overflow on x-axis.
https://issues.apache.org/jira/browse/HDDS-6073
UI changes
=> HDDS-6073. Document: Fix images alignment in the doc pages

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/CopyObjectResponse.java
This PR renames the root element of `CopyObjectResponse` to "CopyObjectResult".
(https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html#API_CopyObject_ResponseSyntax)
https://issues.apache.org/jira/browse/HDDS-6069
Since this modification is trivial, I didn't run any tests.
=> HDDS-6069: Fix XmlRootElement for CopyObjectResponse

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmKeyResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRenameRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRenameRequestWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMTrashRecoverRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/AbstractOMKeyDeleteResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyCommitResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyCreateResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyDeleteResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyRenameResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyRenameResponseWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMPathsPurgeResponseWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMTrashRecoverResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OmKeyResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/TestCleanupTableInfo.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeyRenameResponse.java
This is a refactoring task to avoid overriding #getBucketLayout() to FILE_SYSTEM_OPTIMIZED in FSO subclasses. The idea is basically to instantiate bucketLayout member variable in the object.
https://issues.apache.org/jira/browse/HDDS-5974
Tested Manually
=> HDDS-5974. Remove OMClientResponse#getBucketLayout override in subclasses - part1

hadoop-ozone/dev-support/checks/acceptance.sh, hadoop-ozone/dev-support/checks/kubernetes.sh
Most CI checks collect standard output to a file, which is then included in the result bundle.  We should have the same for Robot-based checks (acceptance and kubernetes).
https://issues.apache.org/jira/browse/HDDS-6090
```
$ unzip -t acceptance-misc.zip output.log
Archive:  acceptance-misc.zip
testing: output.log               OK
No errors detected in acceptance-misc.zip for the 1 file tested.
$ unzip -t kubernetes.zip output.log
Archive:  kubernetes.zip
testing: output.log               OK
No errors detected in kubernetes.zip for the 1 file tested.
```
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1562215053
=> HDDS-6090. Collect output.log from acceptance tests

hadoop-ozone/dist/src/main/smoketest/s3/objectcopy.robot, hadoop-ozone/dist/src/main/smoketest/s3/objectdelete.robot, hadoop-ozone/dist/src/main/smoketest/s3/objectmultidelete.robot, hadoop-ozone/dist/src/main/smoketest/s3/objectputget.robot, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/AWSV4AuthValidator.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/signature/AuthorizationV4QueryParser.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/signature/StringToSignProducer.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/util/S3Utils.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectPut.java
S3 copy object fails for source key with special char.  Noticed with `=`, as in `key=value`, which is used for Spark SQL partitioned tables.
`put-object` creates the key with literal `=`:
```
Running command 'aws s3api --endpoint-url http://s3g:9878 put-object --bucket bucket-ozone-test-9766114691 --key ozone-test-7644827888/copyobject/key=value/f1 --body /tmp/copyfile'
...
Running command 'aws s3api --endpoint-url http://s3g:9878 list-objects --bucket bucket-ozone-test-9766114691 --prefix ozone-test-7644827888/copyobject/key=value/'
${output} = {
"Contents": [
{
"LastModified": "2021-12-11T14:19:26.002Z", 
"ETag": "2021-12-11T14:19:26.002Z", 
"StorageClass": "STANDARD", 
"Key": "ozone-test-7644827888/copyobject/key=value/f1", 
"Size": 29
}
]
}
```
But the source key path for …
=> HDDS-6096. S3 copy object fails for source key with special char

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/interfaces/Handler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CloseContainerCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCloseContainerCommandHandler.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineFailures.java
If a container is in closing state, the next state for it should be
quasi closed for containers without a pipeline.
https://issues.apache.org/jira/browse/HDDS-6018
=> HDDS-6018 Closing state to quasiclosed

pom.xml
Update log4j version to 2.16.0.
https://lists.apache.org/thread/d6v4r6nosxysyq9rvnr779336yf0woz4
https://issues.apache.org/jira/browse/HDDS-6104
Log version only change, exisiting tests
=> HDDS-6104. Update log4j version to 2.16.0 version.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/ContainerScrubberConfiguration.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestContainerScrubberConfiguration.java
Fix too short container scrubber data scan interval.
1 minute -> 1 day
With some improvement of the default value definitions and config value validations.
https://issues.apache.org/jira/browse/HDDS-6053
no test.
=> HDDS-6053. Fix too short container scrubber data scan interval.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsConfigKeys.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/x509/SecurityConfig.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/utils/CertificateCodec.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationServer.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/TestHddsSecureDatanodeInit.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/CertificateClient.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DNCertificateClient.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DefaultCertificateClient.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/OMCertificateClient.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/SCMCertificateClient.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/keys/KeyCodec.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/keys/SecurityUtil.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HAUtils.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/TestDefaultCertificateClient.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/keys/TestKeyCodec.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/HASecurityUtils.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/server/TestContainerServer.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/OzoneDelegationTokenSecretManager.java
- Add configs to support externalization of root CA
- Introduce a flag to enable external root CA
- Introduce configs to feed in keystore and trust store files for each component
- Update the security bootstrap flow of all the components to honor the flag to enable external root CA
https://issues.apache.org/jira/browse/HDDS-6031
This patch was tested by replacing jars in a cluster and updating the configs to work with an external root CA signed certs in JKS and Truststore.
=> HDDS-6031. Add configs to support externalization of root CA

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ContainerDownloader.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/DownloadAndImportReplicator.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/SimpleContainerDownloader.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestReplicationSupervisor.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestSimpleContainerDownloader.java
The logic in `SimpleContainerDownloader.getContainerDataFromReplicas()` is hard to follow and could be written in a simpler way, with the same functionality.
This Jira is a small refactor of the logic in the above method, which hopefully makes it easier to understand.
https://issues.apache.org/jira/browse/HDDS-6080
No functionality changes. Existing tests cover this.
=> HDDS-6080. Simplify the logic in SimpleContainerDownloader.getContainerDataFromReplicas

hadoop-ozone/dist/src/main/assemblies/ozone-src.xml
Hugo 0.89:
> Hugo now writes an empty file named `.hugo_build.lock` to the root of the project when building
We should exclude this lock file from the source tarball of releases.
```
$ mvn -DskipTests -Psrc clean package
$ tar tzvf hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT-src.tar.gz | grep hugo | wc -l
1
```
https://issues.apache.org/jira/browse/HDDS-6107
```
$ mvn -DskipTests -Psrc clean package
$ tar tzvf hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT-src.tar.gz | grep hugo | wc -l
0
```
=> HDDS-6107. Exclude hugo lock file from source tarball

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/XceiverServerGrpc.java
HDDS-5962 increased integration test execution time by 20-30 minutes for each split.
With the current order of shutdown, `server.awaitTermination` takes 5 seconds in each case.  No matter how much we increase timeout (e.g. to several minutes), it always takes all specified time.  It seems the event that `awaitTermination` expects does not happen if `eventLoopGroup` has already been shutdown.
https://issues.apache.org/jira/browse/HDDS-6072
Verified that `XceiverServerGrpc.stop` no longer takes 5 seconds.
Each split of the integration suite still takes ~10 minutes more than before HDDS-5962, but at least they are 10-20 minutes quicker than on current `master`.
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1554131459
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1554416354 …
=> HDDS-6072. Fix increased integration test execution time

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServerConfigKeys.java
for now , ozone.scm.db.cache.size.mb, ozone.om.db.cache.size.mb and ozone.recon.container.db.cache.size.mb are not used for setting cache of  rocksdb, they are used for setting cache of leveldb, which is not used now. 
these config keys are confused for users of ozone if not removed
https://issues.apache.org/jira/browse/HDDS-6105
no need
=> HDDS-6105. remove db cache size config

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockInputStreamProxy.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockReconstructedStripeInputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestECBlockReconstructedStripeInputStream.java
To make reconstruction reads faster, ECBlockReconstructedStripeInputStream could read from the block streams in parallel rather than serially.
https://issues.apache.org/jira/browse/HDDS-5952
Existing tests
=> HDDS-5952. EC: ECBlockReconstructedStripeInputStream should read from blocks in parallel

.gitignore
With Hugo 0.89 or later, untracked file appears after build:
```
$ mvn -DskipTests clean package
...
$ git status
...
Untracked files:
(use "git add <file>..." to include in what will be committed)
hadoop-hdds/docs/.hugo_build.lock
```
https://issues.apache.org/jira/browse/HDDS-6110
```
$ git status
...
nothing to commit, working tree clean
```
=> HDDS-6110. Add hugo lock file to gitignore

hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3MultipartUploadAbortResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3MultipartUploadAbortResponseWithFSO.java
This task is to fix a unit test and add tighter assertions for MPU abort with `MultipartOpenKey` in FSO scenario.
https://issues.apache.org/jira/browse/HDDS-5795
related unit tests.
=> HDDS-5795. [FSO] Fix unit test case for MPU open key during abort.

hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/ExitManager.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/cli/OzoneAdmin.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/ha/OMFailoverProxyProvider.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OMNodeDetails.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OMAdminProtocol.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OMConfiguration.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OMAdminProtocolClientSideImpl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestAddRemoveOzoneManager.java, hadoop-ozone/interface-client/src/main/proto/OMAdminProtocol.proto, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ha/OMHANodeDetails.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerRatisServer.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/OzoneManagerSnapshotProvider.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OMAdminProtocolServerSideImpl.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/OzoneServiceProvider.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/DecommissionOMSubcommand.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/OMAdmin.java
Adds support to remove an OM node from an HA cluster.
To remove an OM, we need to follow the below steps:
1. Update ozone-site.xml of each OM node by adding the to be decommissioned nodeId to the config `ozone.om.decommissioned.nodes.<om-service-id>`.
2. Run the following command:
`ozone admin om decommission -id=<om-service-id> -nodeid=<decommissioned-node-id> -hostname=<decommissioned-node-hostname [(optional) force]`
The DecommssionOM subcommand will verify that all the existing OMs configs have been updated with the decommissioned node. If the verification is successful, it will send a decommission request via OMAdmin protocol to the leader OM. The Leader OM will submit a SetConfiguration request to Ratis to remove the decommissioned peer from Raft conf and OM state.
If the force …
=> HDDS-5490. Remove an OM node from HA ring

pom.xml
Update log4j version to 2.17.0.
[CVE-2021-45105](https://logging.apache.org/log4j/2.x/index.html)
https://issues.apache.org/jira/projects/HDDS/issues/HDDS-6124
After updating `log4j2` to `2.17.0`, Ozone can be built with Apache Maven.
=> HDDS-6124. Update log4j version to 2.17.0 version

hadoop-hdds/docs/config.yaml
Update config.yaml for Hugo to whitelist the environment variable OZONE_VERSION following the doc https://gohugo.io/about/security-model/
https://issues.apache.org/jira/browse/HDDS-6125
Built locally
=> HDDS-6125. Support Hugo 0.91.0.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/AbstractFindTargetGreedy.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerConfiguration.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/FindTargetGreedy.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/FindTargetGreedyByNetworkTopology.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/FindTargetGreedyByUsageInfo.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancer.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestFindTargetStrategy.java
always choose the nearest one as the target in the candidates according to networkTopology
https://issues.apache.org/jira/browse/HDDS-5602
ut
=> HDDS-5602. make it configurable to choose the nearest one as the target in the candidates according to networkTopology

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HAUtils.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeProtocolServer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
in our cluster , we put scm db and ratis in different directories which in different disk partitions. but when bootstraping this cluster , we found the ozone cluster does not work well because the follower scm fail to install snapshot. after investigating, we found the db checkpoint will be downloaded to the directory the same as the ratis log by default. when replacing the old db, scm will use `files.move` to move the checkpoint to the db directory. but according to the description of `files.move`, When moving a directory requires that its entries be moved then this method fails (by throwing an IOException). 
https://issues.apache.org/jira/browse/HDDS-6101
current UT
=> HDDS-6101. use FileUtils.moveDirectory instead of Files.move when installing snapshot

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/SetReplicationConfigOptions.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/bucket/BucketCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/bucket/SetReplicationConfigHandler.java
Added the CLI options to set the replication config parameters on a bucket.
One can re-set the replication config on bucket with the following arguments on bucket:
"set-replication-config", bucketPath, "-t",  "EC", "-r", "rs-3-2-1024k"
https://issues.apache.org/jira/browse/HDDS-6065
Added the test to verify the behavior.
=> HDDS-6065: EC: Provide CLI option to reset the bucket replication config

hadoop-ozone/dist/src/main/smoketest/s3/awss3.robot, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/commontypes/CommonPrefix.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/commontypes/KeyMetadata.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/commontypes/ObjectKeyNameAdapter.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/commontypes/TestObjectKeyNameAdapter.java
Add an url-encode feature for key and prefix to fix an S3G issue that cannot handle keys named like 'a+b+c'.
The problem is that S3G currently does not care about URL encoding on special meaning characters like '+'. There is a compatibility issue between Ozone and aws cli because it assumes a object key name in ListBucketResponse is served in url-encoded chars.
Example: a bucket has an object named 'a+b+c' -- In this case, `aws s3 ls` or `aws s3 rm --recursive` will not work properly because aws cli decodes 'a+b+c' as 'a b c'.
This patch introduces an encoding feature on special meaning characters and this converts plus '+' char to '%2B'. Here is a example:
- 'a+b+c' (includes plus) --> 'a%2Bb%2Bc'
- 'abc/' (includes a slash) --> 'abc/' (keep slash; not to encode)
- 'a b c' (includes …
=> HDDS-5975. Serve url-encoded key and prefix name for ListObjectResponse

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneAtRestEncryption.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequestWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3InitiateMultipartUploadRequestWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequestWithFSO.java
This task is to merge [HDDS-4653](https://issues.apache.org/jira/browse/HDDS-4653) to support Transparent Data Encryption for MPU Keys in FSO bucket layout.
Presently it's throwing a NOT_SUPPORTED exception.
```
10:01:29.283 [OM StateMachine ApplyTransaction Thread - 0] ERROR OMAudit - user=xyz | ip=127.0.0.1 | op=INITIATE_MULTIPART_UPLOAD {volume=d05a32f8-29a0-46f3-9215-d3b8ace658c5, bucket=dcdf3716-970d-4e66-a6ba-f857d9311aa7, key=mpu_test_key_1, dataSize=0, replicationType=STAND_ALONE, replicationFactor=ONE} | ret=FAILURE
org.apache.hadoop.ozone.om.exceptions.OMException: MultipartUpload is not yet supported on encrypted buckets
at org.apache.hadoop.ozone.om.request.s3.multipart.S3InitiateMultipartUploadRequestWithFSO.validateAndUpdateCache(S3InitiateMultipartUploadRequestWithFSO.java:1 …
```
=> HDDS-5807. [FSO] Merge HDDS-4653 changes to support TDE for MPU Keys in FSO bucket layout.

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockDataStreamOutput.java, hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/StreamCommitWatcher.java
See: https://issues.apache.org/jira/browse/HDDS-6130
Existing tests: testPutBlockAtBoundary
=> HDDS-6130. [Ozone-Streaming]  When releaseBuffers will get “Couldn 't find the required future”

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeAdminMonitorImpl.java
When the DatanodeAdminMonitor is processing a host entering decommission or maintenance, we have seen it get stuck due to issues with the containers preventing them replicating. As it stands, the AdminMonitor prints out only a list of problem container IDs, but it does not give any details about the containers or their replicas.
On each pass, when checking a node, we should log detailed information about 5 under replicated and 5 unhealthy containers, which will aid debugging later if there are any problems. There many be many more containers than this, but giving a sample of 5 should be enough for debugging. If we want all the containers, we can set the log level to DEBUG which will print them all.
From docker-compose, these are the log messages, which are very information rich. The main …
=> HDDS-6121. DatanodeAdminMonitor should log detailed information for a limited number of containers

pom.xml
Release notes: https://github.com/apache/logging-log4j2/blob/rel/2.17.1/RELEASE-NOTES.md
Looks like there's another RCE ([CVE-2021-44832](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-44832)) in 2.17.0. Also according to this article:
https://www.bleepingcomputer.com/news/security/log4j-2171-out-now-fixes-new-remote-code-execution-bug/
=> HDDS-6143. Update log4j version to 2.17.1

pom.xml
Root `pom.xml` includes `org.jdom:jdom` in `dependencyManagement`, but it is not used at all, can be removed.
https://issues.apache.org/jira/browse/HDDS-6142
```
$ mvn --no-transfer-progress dependency:tree | grep jdom
$
```
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1630521474
=> HDDS-6142. Remove unused dependency: jdom

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/DFSConfigKeysLegacy.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/conf/OzoneConfiguration.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java, hadoop-hdds/docs/content/security/SecuringDatanodes.md, hadoop-hdds/docs/content/security/SecuringDatanodes.zh.md, hadoop-ozone/dist/src/main/compose/ozonesecure-ha/docker-config, hadoop-ozone/dist/src/main/compose/ozonesecure-mr/docker-config, hadoop-ozone/dist/src/main/compose/ozonesecure/docker-config
The current settings to configure the keytab file to be used by the datanode follows the same naming convention as the other components.
https://issues.apache.org/jira/browse/HDDS-6119
Local hugo test.
=> HDDS-6119. Reset the property name to configure the datanode kerberos keytab

hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/authority/TestDefaultCAServer.java
`TestDefaultCAServer#testIntermediaryCA` started failing on Jan 1st, because the test relies on the exact return value of `LocalDate#compare`:
```
expected:<10> but was:<9>
```
For dates in different years, `LocalDate#compare` seems to return the difference in years, but this is an implementation detail.  Return values of `compare` (and `compareTo`) should only be checked against 0, not specific other values.
A period of 3650 days (`P3650D`) is always less than 10 whole years due to leap years, which have an extra day.  However, "today" + 3650 days usually falls in the 10th year from now, except for the first 2-3 days of each year (depending on the number of leap years in the period).
```
2031-12-30 cmp 2022-01-01 = 9
2031-12-31 cmp 2022-01-02 = 9
``` …
=> HDDS-6146. TestDefaultCAServer#testIntermediaryCA failure

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyLocationInfo.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientWithKeyLatestVersion.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileCreateRequestWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequestWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
We do not need to refresh pipeline info when a key is override. As older version of blocks are not really useful, we have a client side flag(OZONE_CLIENT_KEY_LATEST_VERSION_LOCATION) to return all versions or only latest version.
But irrespective of this flag or versioning we do not need to refresh pipeline for older version of blocks, as we require only latest version of blocks with pipeline information.
https://issues.apache.org/jira/browse/HDDS-6103
Added tests
=> HDDS-6103. Avoid refresh pipeline for key override in Key/File Create.

hadoop-ozone/dev-support/checks/acceptance.sh, hadoop-ozone/dev-support/checks/kubernetes.sh
Fix the problem that _acceptance_ test `output.log` does not include container start/stop messages from Docker Compose.
https://issues.apache.org/jira/browse/HDDS-6145
Verified `output.log` in _acceptance_ artifacts:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1638682309
=> HDDS-6145. Include docker-compose output in acceptance test output.log

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneCluster.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecureOzoneCluster.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/TestCSMMetrics.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestSecureOzoneContainer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/server/TestSecureContainerServer.java
Integration tests should not trigger real `System.exit` call, because it prevents further tests in the surefire fork (`Crashed tests`).  In these cases we only get the test output, not test results.
https://issues.apache.org/jira/browse/HDDS-6123
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1593529883
=> HDDS-6123. Disable system exit in integration tests

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockOutputStreamEntry.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java
Removed the release in handled stripe failure case and added the test to verify.
This is an important issue as it throws NPE if we write additional stripe after failure recovery.
https://issues.apache.org/jira/browse/HDDS-6132
Added test to verify.
=> HDDS-6132: EC: HandleStripeFailure should not release the cachebuffers.

hadoop-hdds/common/pom.xml, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/tracing/TestStringCodec.java
These unit tests are skipped currently, because they are annotated with JUnit5's `@Test`, which the JUnit4 runner does not know about:
```
hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/ratis/conf/TestRatisClientConfig.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/ratis/conf/TestRaftClientConfig.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/tracing/TestStringCodec.java
```
This PR adds JUnit5 test dependency in the affected module (`hdds-common`).
It also tweaks `TestStringCodec`, which was broken (without noticing it, since it was not being run) by the most recent Jaeger update (HDDS-4980).
https://issues.apache.org/jira/browse/HDDS-6094
Verified that previously missing tests were executed: …
=> HDDS-6094. Some unit tests are skipped due to using JUnit4 runner

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/conf/OzoneConfiguration.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/conf/TestOzoneConfiguration.java
OzoneConfiguration constructor which takes a configuration as parameter can override input configuration keys with default resources.
```
public OzoneConfiguration(Configuration conf) {
super(conf);
//load the configuration from the classloader of the original conf.
setClassLoader(conf.getClassLoader());
if (!(conf instanceof OzoneConfiguration)) {
loadDefaults();
}
}
```
https://issues.apache.org/jira/browse/HDDS-6075
Adds a UT.
=> HDDS-6075. OzoneConfiguration constructor overrides input configuration keys.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocol.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/protocolPB/StorageContainerLocationProtocolClientSideTranslatorPB.java, hadoop-hdds/interface-admin/src/main/proto/ScmAdminProtocol.proto, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocolServerSideTranslatorPB.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManagerHttpServer.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OMNodeDetails.java, hadoop-ozone/dist/src/main/compose/ozone-csi/docker-config, hadoop-ozone/dist/src/main/compose/ozone/docker-config, hadoop-ozone/dist/src/main/compose/ozonesecure-mr/docker-config, hadoop-ozone/dist/src/main/compose/ozonesecure/docker-config, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManagerHA.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManagerHttpServer.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconConstants.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServerConfigKeys.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/fsck/ContainerHealthTask.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconNodeManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStorageContainerManagerFacade.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/StorageContainerServiceProvider.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/OzoneManagerServiceProviderImpl.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/StorageContainerServiceProviderImpl.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/spi/impl/TestStorageContainerServiceProviderImpl.java
On Recon startup, get the latest SCM DB (if needed) and bootstrap the container data.
https://issues.apache.org/jira/browse/HDDS-4177
This patch was manually tested.
=> HDDS-4177. SCM Container DB bootstrap on Recon startup

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancer.java
In HDDS-6070, we did some refactoring on ContainerBalancerConfiguration, and we added a method called validateConfiguration to check the configurations. 
Currently the method returns "void", but it's more reasonable to return a boolean to indicate the validate result of the configurations.
This ticket is to change the return parameter from "void" to boolean to check the parameters before doing container balancer work.
https://issues.apache.org/jira/browse/HDDS-6148
unit test
=> HDDS-6148. Validate ContainerBalancerConfiguration before start ContainerBalancer

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockInputStreamFactoryImpl.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockInputStreamFactoryImpl.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockReconstructedInputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockReconstructedStripeInputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestECBlockReconstructedInputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestECBlockReconstructedStripeInputStream.java
When reading and writing EC, we often have to allocate chunk sized Bytebuffers. It would be good if we could reuse them across multiple input / output instances to save freeing and re-allocating memory.
https://issues.apache.org/jira/browse/HDDS-5949
Existing tests
=> HDDS-5949. EC: Create reusable buffer pool shared by all EC input and output streams

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HAUtils.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMStateMachine.java
Initialize exitManager and throw exception when installSnapshot fails, so that we can propogate this error to SM and the ratis handles it appropriately by terminating process.
https://issues.apache.org/jira/browse/HDDS-6161
Exisiting tests in TestSCMInstallSnapshotWithSCMHA
=> HDDS-6161. SCM StateMachine failing to reinitialize doesn't terminate the process.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerReplicaCount.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ReplicationManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ReplicationManagerReport.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManagerMetrics.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestReplicationManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestReplicationManagerReport.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManagerMetrics.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/states/TestContainerReplicaCount.java
Replication Manager processes all the containers in SCM periodically, and so has a view of the health of the system. However it does not count up the replicas in each state and hence that overview of the system health is not easily visible.
This Jira adds a ReplicationManagerReport object, which ReplicationManager can populate by incrementing various counters as it processes the containers. The report allows the number of containers in each lifecycle state to be counted, while also counting the number of containers in various health states, eg under replicated, over replicated etc. The report also allows a sample of the container IDs in the state are stored in the report (max of 100 per state) and these can be extracted later for debugging (a later Jira will provide the extra feature, …
=> HDDS-6170. Add metrics to replication manager to track container health states

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockInputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyInputStream.java
Most public methods in `KeyInputStream` and `BlockInputStream` are `synchronized`.  This PR makes a few remaining public methods also `synchronized`:
1. Private methods and member variables need to be protected consistently.
2. Ensure atomicity of public operations.
https://issues.apache.org/jira/browse/HDDS-6157
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1663001708
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1663008249
=> HDDS-6157. More consistent synchronization in InputStreams

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/ITestOzoneContractDistCpWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/OzoneContract.java
Add FSO variant of ITestOzoneContractDistcp contract test. This is a follow-up task to [HDDS-4513](https://issues.apache.org/jira/browse/HDDS-4513).
https://issues.apache.org/jira/browse/HDDS-4743
Related integration tests.
=> HDDS-4743. [FSO] Add FSO variant of ITestOzoneContractDistcp.

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
When operations are performed, we should use S3Auth credentials if it is set like how we used in getAclList. This Jira is to fix issue with proxyUser to use the UGI from S3Auth
https://issues.apache.org/jira/browse/HDDS-6175
This issue will be encountered only when KMS acls is enabled. So this needs to be tested with real cluster.
=> HDDS-6175. Use s3Auth during proxy during decrypt in RpcClient.

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockDataStreamOutput.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockDataStreamOutputEntry.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockDataStreamOutput.java
In the current streaming code we maintain only one bufferList for retry. Buffers in the list are removed only during watchForCommit. So there might occur a case if putBlock is followed by another putBlock  the commitInfoMap has the same list for both indexes  which will cause incorrect computation of totalAckDatalength which is used during retry
https://issues.apache.org/jira/browse/HDDS-6139
unit test
=> [Ozone-Streaming] HDDS-6139. Fix incorrect computation of totalAckDataLength.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/TestUtils.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/upgrade/TestSCMHAUnfinalizedStateValidationAction.java, hadoop-ozone/dist/src/main/compose/ozonesecure/docker-config, hadoop-ozone/dist/src/main/compose/upgrade/compose/ha/docker-config, hadoop-ozone/dist/src/main/compose/upgrade/compose/non-ha/docker-config, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/container/metrics/TestSCMContainerManagerMetrics.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestMultiRaftSetup.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/upgrade/TestHDDSUpgrade.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecureOzoneCluster.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBCSID.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachine.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineFailures.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineFlushDelay.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/ratis/TestDnRatisLogParser.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManagerHA.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/node/TestDecommissionAndMaintenance.java
Enable ratis by default for SCM.
https://issues.apache.org/jira/browse/HDDS-5740
Existing Uts
=> HDDS-5740. Enable ratis by default for SCM.

hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestKeyDeletingService.java
`TestKeyDeletingService.checkIfDeleteServiceWithFailingSCM` seems to be intermittently failing frequently on both CI and local setups.
Attached logs archive from failed CI run.
https://github.com/apache/ozone/runs/4821162701?check_suite_focus=true
Cause:
KeyDeletingService can sometimes take more than a few milliseconds to pick up the keys queued up for deletion. If the assertion runs before this is allowed to happen it can cause a test failure.
https://issues.apache.org/jira/browse/HDDS-6183
Unit Tests.
=> HDDS-6183. Intermittent failure in TestKeyDeletingService.checkIfDeleteServiceWithFailingSCM.

hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/volume/TestOMVolumeSetOwnerRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/volume/TestOMVolumeSetQuotaRequest.java
UT assertions periodically failing locally in:
```java
TestOMVolumeSetQuotaRequest.testValidateAndUpdateCacheSuccess
TestOMVolumeSetOwnerRequest.testValidateAndUpdateCacheSuccess
```
Cause:
The assertion would periodically fail since `modificationTime` and `creationTime` could be the same to the precision of a millisecond.
https://issues.apache.org/jira/browse/HDDS-4190
Related Unit Tests
=> HDDS-4190. Intermittent failure in TestOMVolumeSetOwnerRequest and TestOMVolumeSetQuotaRequest.

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBStore.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStore.java, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
In HDDS-1391, the API to get delta updates from OM is added.
In a busy cluster, the delta updates may be very large that could affect the OM's performance while the API is being invoked. This issue happens when Recon is trying to retrieve large delta updates from OM.
This ticket is to add a new API to limit the update counts clients can retrieve each time.
https://issues.apache.org/jira/browse/HDDS-6147
unit test
=> HDDS-6147. Add ability in OM to get limited delta updates

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/OzoneClientConfig.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/container/common/helpers/ExcludeList.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/container/common/helpers/TestExcludeList.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntryPool.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockOutputStreamEntryPool.java
Introduced a daemon in exclude list class to expire the nodes after certain time period. That time could be generally node expiry time.
https://issues.apache.org/jira/browse/HDDS-6021
Added test and I will be adding few more tests.
=> HDDS-6021: EC: Client side exclude nodes list should expire after certain time period or based on the list size.

hadoop-ozone/dist/pom.xml, hadoop-ozone/dist/src/main/dockerlibexec/entrypoint.sh, hadoop-ozone/dist/src/main/k8s/examples/testlib.sh
Update Ozone to latest `ozone-runner` docker image (`20211202-1` currently).
Also apply the same version to K8S tests, as these have been using hard-coded version that got outdated.
https://issues.apache.org/jira/browse/HDDS-6167
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1676705266
=> HDDS-6167. Update ozone-runner version to 20211202-1

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmBucketArgs.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmBucketInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OzoneManagerProtocol.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketSetOwnerRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/bucket/OMBucketSetOwnerResponse.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/bucket/BucketCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/bucket/UpdateBucketHandler.java
Right now, the bucket owner is set when the bucket is created. We need an API to change the owner of a bucket after the bucket is created.
https://issues.apache.org/jira/browse/HDDS-6171
This patch was tested manually and using integration tests.
=> HDDS-6171. Create an API to change Bucket Owner

hadoop-ozone/dist/src/main/docker/Dockerfile
Change environment variables assigned to self-built Docker image generated by
```
$ mvn -Pdocker -Ddocker.image=<name>:<version> -DskipTests -Pdist clean package
```
Without these changes, StatefulSets which reside in `kubernetes/examples/ozone` never start since the init container fails in finding the file `ozone` in its `$PATH`:
```
$ kubectl logs scm-0 -c init
/opt/hadoop/libexec/entrypoint.sh: line 162: exec: ozone: not found
```
According to the `apache/ozone:1.2.0` container image, I believe that
- `HADDOP_LOG_DIR` and `HADOOP_CONF_DIR` should NOT be defined
- `OZONE_LOG_DIR` and `OZONE_CONF_DIR` should be defined instead
but it seems there's no way to unset environment variables already defined in the underlying container image. So I changed the values of `HADOOP_LOG_DIR` and …
=> HDDS-6163. Change env vars for docker container image

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineFailures.java
The underlying exceptions should not be mapped to RuntimeException.
This results in higher layers not retrying on valid failure scenarios.
https://issues.apache.org/jira/browse/HDDS-6109?filter=-1
Included integration tests that introduce a single and dual replica failure both of which should result in the unflushed data to be written to a new location.
=> HDDS-6109 Preserve the underlying exception raised in client lib.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/GrpcReplicationClient.java
If the target temporary directory is small, the concurrent downloading threads will have a contest for space and leave incomplete files. These should be cleaned up.
https://issues.apache.org/jira/browse/HDDS-6203
manual tests
=> HDDS-6203. CleanUp incomplete gz files during Container move

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMOpenKeysDeleteRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMOpenKeysDeleteRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/upgrade/TestOMCancelPrepareRequest.java
Move OMOpenKeysDeleteRequest from org.apache.hadoop.ozone.om.response.key to org.apache.hadoop.ozone.om.request.key
https://issues.apache.org/jira/browse/HDDS-6216
unit tests was changed
=> HDDS-6216. Move OMOpenKeysDeleteRequest to package om.request.key

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestDeleteWithSlowFollower.java
`TestDeleteWithSlowFollower` is failing intermittently at an assertion about pipeline leader being present.  This is expected to pass, since we have waited for the pipeline to open (which happens when leader is first elected).
The problem is that a new leader election may be triggered any time (e.g. due to communication error), so the pipeline may lose its leader after it is opened.  This is normally OK, as client should retry until a new leader is elected (within limits defined by retry policy).  See [comment on Jira issue](https://issues.apache.org/jira/browse/HDDS-6191?focusedCommentId=17477168&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17477168) for more details.
Since we cannot guarantee having a leader, this PR proposes to change the test to …
=> HDDS-6191. Intermittent failure in TestDeleteWithSlowFollower

hadoop-hdds/docs/themes/ozonedoc/layouts/shortcodes/image.html
It was noticed that the images on the ozone docs website are not responsive despite being rendered with the appropriate CSS applied to their shortcode. This problem is not seen when building the website locally.
This might be due to bootstrap CSS classes being loaded after the inline styles and hence overriding them.
This task makes the image shortcode use a built-in bootstrap class for sizing the images down to prevent such conflicts.
https://issues.apache.org/jira/browse/HDDS-6211
Screenshot
=> HDDS-6211. [Docs] Image styling on deployed site does not replicate local builds.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestDataUtil.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneAtRestEncryption.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientMultipartUploadWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestSecureOzoneRpcClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/TestHelper.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCloseContainerHandler.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestDeleteContainerHandler.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/scrubber/TestDataScrubber.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/volume/TestDatanodeHddsVolumeFailureDetection.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestContainerReportWithKeys.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestKeyPurging.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestObjectStoreWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHA.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerPrepare.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManagerFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestStorageContainerManagerHA.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneBucketStub.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectHead.java
Changing the bulk of our tests that are still based on the STAND_ALONE replication type for writes, that we do not use anymore in general for writes. (Though some clients still support writing with it)
One thing remains after this, the TestContainerMapper class, that is a problematic one, as its assertions can not be simply translated to assertions against the RATIS client. Probably that is a more involved thing to change the whole test, or find out what assertions we can safely make. I will create a separate JIRA to track that one test.
https://issues.apache.org/jira/browse/HDDS-6219
Run the integration tests set a couple of times during dealing with some of the issues, the last run failed only the TestContainerMapper, which I have reverted to still use the STAND_ALONE replication type. …
=> HDDS-6219. Switch to RATIS ReplicationType from STAND_ALONE in our tests.

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientUtils.java, hadoop-ozone/ozonefs-common/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneClientUtils.java
Client side we are giving bucket defaults preference in case if bucket has non ec configs. 
In other cases, we will determine the client side configs either from configured value or API passed value.
https://issues.apache.org/jira/browse/HDDS-6131
Running existing test and will add tests
=> HDDS-6131: EC: Replication config from bucket should be refreshed in o3fs

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneConfigUtil.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOzoneConfigUtil.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientUtils.java, hadoop-ozone/ozonefs-common/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneClientUtils.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/keys/PutKeyHandler.java
Handled the client side configuration precedence and passing the null to server if no client configs available. Before this patch, client always passing values.
https://issues.apache.org/jira/browse/HDDS-6184
Added test to check the behavior.
=> HDDS-6184: EC: put command should create EC key if bucket is EC

hadoop-hdds/docs/content/feature/Observability.md, hadoop-hdds/docs/content/feature/Observability.zh.md
add Observability.zh.md
https://issues.apache.org/jira/browse/HDDS-6192
local hugo test
=> HDDS-6192. feature/Observability.md translated to Chinese

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClient.java
After creating a bucket using the shell:
ozone sh bucket create /vol1/testec -t EC -r rs-3-2-1024k 
And then listing the bucket info, the EC Replication details are not reflected in the output:
```
{
"name" : "testec",
"creationTime" : "2022-01-27T17:29:54.289Z",
"modificationTime" : "2022-01-27T17:29:54.289Z",
"bucketLayout" : "OBJECT_STORE",
"owner" : "hadoop",
},
"link" : false
} 
```
The issue is caused by a missing parameter into the new BucketObject from getBucketDetails vs ListBuckets. After this change the CLI …
=> HDDS-6233. EC: Bucket does not display correct EC replication details

hadoop-ozone/dist/src/main/compose/ozonesecure-mr/test.sh
CentOS 8 is EOL, package repository moved to vault.centos.org on Jan/31.  `ozonesecure-mr` test needs to install the `krb5-workstation` package.  This is a quick and dirty workaround to update repository config to access the new location.  (Base image needs to be updated in the long run.)
https://issues.apache.org/jira/browse/HDDS-6239
https://github.com/adoroszlai/hadoop-ozone/runs/5018254007#step:5:660
=> HDDS-6239. ozonesecure-mr failing with No URLs in mirrorlist

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/ContainerController.java
Fix NPE for DataScanner with scanned container deleted by others.
https://issues.apache.org/jira/browse/HDDS-6201
CI: https://github.com/guihecheng/ozone/actions/runs/1717838258
The problem and fix should be obvious by reading the error log on the JIRA.
=> HDDS-6201. Fix NPE for DataScanner with scanned container deleted by others.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineStateManagerImpl.java
for any exception thrown from `@Replicated` methods, we should throw it, so that scm statemachine can catch this exception and terminate scm process, which will avoid diverging of scms in HA case.
https://issues.apache.org/jira/browse/HDDS-5529
current UT
=> HDDS-5529. For any IOexception from @Replicated method we should throw it

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockOutputStreamEntry.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestECKeyOutputStream.java
Passing the close flag correctly on end of blockgroup or file close.
https://issues.apache.org/jira/browse/HDDS-6237
Added a test check the behavior.
=> HDDS-6237: EC: putBlock should pass close flag true on end of block group/close file.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerInfo.java
The replication config, which includes type and factor is already present in the Json output. The getters for ContainerInfo:
```
getReplicationType()
getReplicationFactor()
```
Therefore do not need to be displayed in the JSON output, as they duplicate the replication config information.
Additionally, EC containers do not have a "factor" which causes an error when the JSON is displayed:
```
bash-4.2$ ozone admin container info --json 4      
Replication configuration of type EC does not have a replication factor property. (through reference chain: org.apache.hadoop.hdds.scm.container.common.helpers.ContainerWithPipeline["containerInfo"]->org.apache.hadoop.hdds.scm.container.ContainerInfo["replicationFactor"])
```
This change simply removes the two getters from the JSON output. …
=> HDDS-6240. EC: Container Info command with json switch fails for EC containers

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/exception/S3ErrorTable.java
Frequent errors such as NoSuchBucket or NoSuchKey must not be written as errors, while they are. They should be in audit logs in principle, because the system is not wrong, not knowing how to handle them. Otherwise, we may miss important errors like NullPointerException that does not appear in healthy system. To make sure that we can keep eyes on system health than access by applications, errors that stem from applications must not be printed in normal log files.
Update: Internal Errors should be written as ERROR to system log. So, the log in S3ErrorTable will be:
- if it's internal error, it's unexpected, then write as ERROR.
- otherwise, it's known error in S3 API specification, then write as DEBUG.
For auditing purpose, I files another issue as …
=> HDDS-6206. Application errors must not flood system log

hadoop-ozone/dist/src/main/smoketest/admincli/datanode.robot
Get expected count of nodes in specific state via unfiltered command, filtering by `grep`.  This allows running the test with any number of datanodes.
https://issues.apache.org/jira/browse/HDDS-6251
```
$ cd hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/ozone
$ docker-compose up -d --scale datanode=5
$ docker-compose exec scm robot smoketest/admincli/datanode.robot
Datanode :: Test ozone admin datanode command
List datanodes                                                        | PASS |
Filter list by UUID …
```
=> HDDS-6251. Smoketest for ozone admin datanode expects exactly 3 nodes

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/BaseFreonGenerator.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/DatanodeChunkValidator.java
Avoid unnecessarily using `getLegacyFactory`, to make Datanode Chunk Validator work even if there are EC pipelines in the cluster.
https://issues.apache.org/jira/browse/HDDS-6252
```
$ ozone sh volume create /vol1
$ ozone sh bucket create --replication rs-3-2-1024k --type EC /vol1/becket
$ ozone sh key put /vol1/becket/passwd /etc/passwd
$ echo log4j.logger.org.apache.hadoop.ozone.freon=DEBUG >> /etc/hadoop/log4j.properties
$ ozone freon dcg -t1 -n100 -p dcg
...
$ ozone freon dcv -t1 -n100 -p dcg
...
[main] DEBUG freon.DatanodeChunkValidator: Found pipeline PipelineID=47a983b3-6b22-4330-9406-75601aeba8e1
...
[main] INFO freon.DatanodeChunkValidator: Using pipeline PipelineID=28f4f444-a174-4607-8e9e-060339a8801b
...
Successful executions: 100
$ ozone admin pipeline list | grep …
```
=> HDDS-6252. Datanode Chunk Validator fails on encountering EC pipeline

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
If the pending keys to be flushed grows and includes a lot of deletes,
list operations can grow the memory quite a bit by caching deleted keys.
The cache for deleted keys can be skipped entirely.
https://issues.apache.org/jira/browse/HDDS-6238
Existing tests were updated.
=> HDDS-6238 Reduce memory requirements for list keys.

hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStore.java
Remove intermittent `testRocksDBKeyMayExistApi`, which was an "integration" test checking if RocksDB `keyMayExist` call is cheaper than `get` call for the same key.
There are several problems with it:
* No warmup, so order matters. (Adding warmup reduces time of both calls.)
* Same key names are used for both `get` and `keyMayExist` calls, the result of get might be cached at RocksDB level. (This should help `keyMayExist` due to current order. Reordering the loops indicates that `keyMayExist` takes longer than `get`.)
* Too few measurements, no check of whether the difference is statistically significant.
* Tests a completely empty database (does not match real life usage)
* Measured time includes `getBytesUtf16` calls, not only the RocksDB call being tested.
A real JMH-based …
=> HDDS-2919. Remove intermittent TestRDBStore#testRocksDBKeyMayExistApi

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ReplicationManager.java
Until we get replication and recovery working for EC, we need to tell Replication Manager to ignore EC containers.
https://issues.apache.org/jira/browse/HDDS-6255
No new tests. This is a simple temporary change which will be removed later when the EC recovery work starts.
=> HDDS-6255. EC: Replication Manager should skip EC Containers

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MockDatanodeStorage.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java
As part of buffers pool reusing([HDDS-5949](https://issues.apache.org/jira/browse/HDDS-5949)) we started creating parity buffers in full size and setting the right limits when we need less than chunk. In writes, we were using ByteBuffer.array and ByteBuffer.array.length. When we convert ByteBuffer into array, it will not respect the limits anymore. So, instead of array.length, using the ByteBuffer.limit to indicate the len.
https://issues.apache.org/jira/browse/HDDS-6256
Reproduced this issue with a test and passed the same after fix.
=> HDDS-6256: EC: Parity blocks are padded incorrectly with zeros to the chunk size

hadoop-ozone/dist/src/main/compose/ozone/test.sh
HDDS-6041 changed `ozone` docker-compose environment to use FSO by default.  Some of the FSO-specific test statements were left over, so now they are run twice with the same config.
https://issues.apache.org/jira/browse/HDDS-6253
https://github.com/adoroszlai/hadoop-ozone/runs/5042337481
=> HDDS-6253. Unnecessary duplicate smoketest after defaulting to FSO

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/OzoneClientProducer.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/exception/S3ErrorTable.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/TestOzoneClientProducer.java
Currently in some cases where the authorization header is wrong, S3Gateway returns wrong status code. For example,
1. 500 for no such bucket, or
2. 404 for malformed request.
Some cases are not reproducible for me, but it's apparently wrong in code. 1. is because OS3Exception is doubly wrapped by WebApplicationError and thus failing to catch in the `catch (OS3Exception ex)`  clause and goes through to `catch (Exception ex)` clause. 2. just comes from wrong definition in S3ErrorTable.
Here are some examples against our production cluster for case 1:
```sh
$ curl -H "Authorization: invalid" https://ozone.example.com/no-such-bucket
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Internal Server Error</title>
</head>
<body><h2>HTTP ERROR 500 …
```
=> HDDS-6204. Cleanup handling malformed authorization header

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerReplicaInfo.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerReplicaInfo.java, hadoop-hdds/interface-client/src/main/proto/hdds.proto, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/container/InfoSubcommand.java, hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/container/TestInfoSubCommand.java
[HDDS-6177](https://issues.apache.org/jira/browse/HDDS-6177) added replica details to the container info command on the master branch. On the EC branch, we need to extend it to add the new replica index field.
The new output includes the replica index in both Json and the human readable format, eg:
```
bash-4.2$ ozone admin container info 2
Container id: 2
Pipeline id: 8a62f588-0fff-497d-9589-aa14ef43c86b
Container State: QUASI_CLOSED
Datanodes: [aef6aa64-1251-4707-aaaa-141c9d03b6b1/ozone_datanode_2.ozone_default,
9b650b01-a361-471a-98a8-2aa4daff5fee/ozone_datanode_5.ozone_default,
d4d57905-08c8-4f4f-8a5f-cf04b066b82c/ozone_datanode_3.ozone_default]
Replicas: [State: QUASI_CLOSED; ReplicaIndex: 5; Origin: aef6aa64-1251-4707-aaaa-141c9d03b6b1; Location: …
```
=> HDDS-6250. EC: Add replica index to the output in the container info command

dev-support/ci/selective_ci_checks.bats, dev-support/ci/selective_ci_checks.sh
`ozone-runner` image version is defined in `hadoop-ozone/dist/pom.xml`.  Changing it triggers a complete CI run, although it does not affect unit or integration tests in any way.  Actually, `hadoop-ozone/dist` does not have any Java code, as it assembles other modules after build.  So we can skip all Java-specific checks.
https://issues.apache.org/jira/browse/HDDS-6169
Added test case in `selective_ci_checks.bats`.
```
$ bats dev-support/ci/selective_ci_checks.bats
...
✓ runner image update
...
17 tests, 0 failures
```
The script includes instructions on how to run:
https://github.com/apache/ozone/blob/a31b79a0cf0677a11dda1e9d3de70cf22f7b045a/dev-support/ci/selective_ci_checks.bats#L17-L31
=> HDDS-6169. Selective checks: skip junit tests on ozone-runner image update

hadoop-ozone/dist/src/main/smoketest/compatibility/read.robot, hadoop-ozone/dist/src/main/smoketest/compatibility/setup.robot
`compatibility` test uses `/etc/passwd` for write/read tests, relying on the assumption that the file does not change.  But if we want to upgrade Ozone runner base image, the assumption may be broken, as @smengcl found, since we use old images for existing Ozone versions.
This PR changes the test to use a dedicated file created during test setup.
https://issues.apache.org/jira/browse/HDDS-6270
https://github.com/adoroszlai/hadoop-ozone/runs/5098198093?check_suite_focus=true#step:5:4582
=> HDDS-6270. Use a dedicated file instead of /etc/passwd for xcompat acceptance test

hadoop-hdds/docs/content/security/SecuringTDE.md, hadoop-hdds/docs/content/security/SecuringTDE.zh.md
Fixing some small issues in the existing document SecuringTDE.md:
1. Added note for `--layout=FILE_SYSTEM_OPTIMIZED` that could provide HCFS access. Otherwise access from ofs/o3fs will be rejected due to bucket layout being `OBJECT_STORE` by default.
2. Bucket names doesn't support upper case letters. The example in the doc won't work.
https://issues.apache.org/jira/browse/HDDS-6273
- Ran `hugo serve` locally and checked that the page http://localhost:1313/security/securingtde.html rendered as expected:
=> HDDS-6273. Amend doc SecuringTDE.md

hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServerConfigKeys.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/OzoneManagerServiceProviderImpl.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/spi/impl/TestOzoneManagerServiceProviderImpl.java
In HDDS-6147, a new API was added to get limited delta updates from OM.
This ticket will let Recon use this new API to call OM to get limited updates. By default, Recon will fetch at least 2000 delta updates 10 times each time trying to sync from OM.
https://issues.apache.org/jira/browse/HDDS-6215
unit test
=> HDDS-6215. Recon get limited delta updates from OM

.github/workflows/post-commit.yml, hadoop-ozone/dev-support/checks/bats.sh
Selective CI checks has a test suite, but currently it needs to be run manually.  This PR adds it to the _bats_ check in CI.
The test verifies the list of selective checks triggered for some known commits.  Thus we need to checkout the repo with full history for the _bats_ check.
https://issues.apache.org/jira/browse/HDDS-6226
Verified that _bats_ check includes the test for selective checks script:
```
1..16
ok 1 checkstyle and bats
ok 2 compose only
ok 3 compose and robot
ok 4 check script
ok 5 integration only
ok 6 kubernetes only
ok 7 docs only
ok 8 java-only change
ok 9 java and compose change
ok 10 java and docs change
ok 11 pom change
ok 12 CI lib change
ok 13 CI workflow change
ok 14 root README
ok 15 ignored code
ok 16 other README
``` …
=> HDDS-6226. Run tests for selective CI checks in CI

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/BucketEndpoint.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java
Follow-up for HDDS-6206: avoid logging exception as error when they are known cases (e.g. invalid bucket name, checking existence (`head`) of non-existing bucket, permission denied, etc.).
https://issues.apache.org/jira/browse/HDDS-6247
Ran S3 acceptance tests before and after the change.  Verified S3 Gateway logs no longer have verbose stack trace for these requests.  We can still see request problems by setting log level to DEBUG, e.g.:
```
s3g_1       | 2022-02-03 12:54:57,459 [qtp690052870-16] DEBUG exception.S3ErrorTable: <?xml version="1.0" encoding="UTF-8"?>
s3g_1       | <Error>
s3g_1       |   <Code>InvalidBucketName</Code>
s3g_1       |   <Message>The specified bucket is not valid.</Message>
s3g_1       |   <Resource>a_b_c</Resource>
s3g_1       |   <RequestId/>
s3g_1       | …
```
=> HDDS-6247. Avoid logging stack trace for user input problems

hadoop-ozone/dist/src/main/compose/upgrade/compose/ha/docker-config
Use proper comment syntax in `docker-config` to prevent warnings related to parse issues.
Fix is extracted from feature branch PR #3018.
https://issues.apache.org/jira/browse/HDDS-6289
https://github.com/smengcl/hadoop-ozone/runs/5118089024#step:5:1301
=> HDDS-6289. Upgrade acceptance test log flooded with parse error

hadoop-ozone/dist/src/main/license/update-jar-report.sh, pom.xml
Update ratis version to 2.3.0-94db58b-SNAPSHOT version
https://issues.apache.org/jira/browse/HDDS-6281
=> HDDS-6281. Update ratis version to 2.3.0-94db58b-SNAPSHOT version

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockInputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockInputStreamProxy.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockReconstructedStripeInputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/ECStreamTestUtil.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestECBlockInputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestECBlockInputStreamProxy.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestECBlockReconstructedStripeInputStream.java
Attempting to read a key less than 1 chunk, with 3 of the 5 nodes stopped (both when not yet stale or stale), the read hangs for sometime and fails with:
```
$ ozone sh key get /vol1/bucket/ec1 /tmp/3_down
java.lang.IllegalStateException
at org.apache.ratis.util.Preconditions.assertTrue(Preconditions.java:33)
at org.apache.hadoop.ozone.client.io.ECBlockReconstructedStripeInputStream.selectParityIndexes(ECBlockReconstructedStripeInputStream.java:432)
at org.apache.hadoop.ozone.client.io.ECBlockReconstructedStripeInputStream.init(ECBlockReconstructedStripeInputStream.java:179)
at org.apache.hadoop.ozone.client.io.ECBlockReconstructedStripeInputStream.readStripe(ECBlockReconstructedStripeInputStream.java:285)
at org.apache.hadoop.ozone.client.io.ECBlockReconstructedInputStream.readStripe(ECBl …
```
=> HDDS-6258. EC: Read with stopped but not dead nodes gives IllegalStateException rather than InsufficientNodesException

hadoop-ozone/client/pom.xml, hadoop-ozone/dist/src/main/smoketest/mapreduce.robot, hadoop-ozone/dist/src/main/smoketest/ozonefs/hadoopo3fs.robot, hadoop-ozone/ozonefs-shaded/pom.xml
`slf4j-log4j12` was accidentally introduced as compile-time dependency for `ozone-client` in 9644f83c0.  This made it leak into the Ozone FS shaded jars:
```
[INFO] Including org.slf4j:slf4j-log4j12:jar:1.7.30 in the shaded jar.
```
https://github.com/apache/ozone/runs/4756057859#step:6:2442
It also appears in MR test logs:
```
nm_1        | *** Launching "yarn nodemanager"
nm_1        | SLF4J: Class path contains multiple SLF4J bindings.
nm_1        | SLF4J: Found binding in [jar:file:/opt/hadoop/share/hadoop/common/lib/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
nm_1        | SLF4J: Found binding in [jar:file:/opt/ozone/share/ozone/lib/ozone-filesystem-hadoop3-1.3.0-SNAPSHOT.jar!/org/slf4j/impl/StaticLoggerBinder.class]
nm_1        | SLF4J: See …
```
=> HDDS-6291. Do not let slf4j-log4j12 leak into Ozone FS shaded jar

hadoop-ozone/dist/src/main/compose/ozonesecure-mr/test.sh
`ozonesecure-mr` is now intermittently failing with timeout downloading packages.
Based on the log message:
```
Package krb5-workstation-1.17-18.el8.x86_64 is already installed
```
we can skip installing `krb5-workstation` during `ozonesecure-mr` test.  It seems this was only necessary with older Hadoop image.
https://issues.apache.org/jira/browse/HDDS-6285
https://github.com/adoroszlai/hadoop-ozone/runs/5110698986#step:5:687
=> HDDS-6285. ozonesecure-mr intermittently failing with timeout downloading packages

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
Remove deleted cache
https://issues.apache.org/jira/browse/HDDS-6278
Unit tests in CI test should exercise this code.
=> HDDS-6278 Improve memory profile for listStatus API call.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/ECPipelineProvider.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineFactory.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineProvider.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/RatisPipelineProvider.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/SimplePipelineProvider.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/MockPipelineManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestECPipelineProvider.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestRatisPipelineProvider.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconPipelineFactory.java
Note this also containers #3048, so it will need to be committed first and then this one rebased.
The pipeline returned from SCM for EC closed containers and closed pipelines does not carry the correct replica index with 
the datanode list. This means the replicas are not returned in the correct order resulting in strange errors reading EC data, such as wrong data returned and "insufficient nodes" errors when there are enough nodes available.
https://issues.apache.org/jira/browse/HDDS-6259
New and existing tests along with some manual testing in docker.
=> HDDS-6259. EC: Pipelines for closed containers should contain correct replica indexes

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/OzoneClientConfig.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/BaseFileChecksumHelper.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/ReplicatedFileChecksumHelper.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/checksum/TestReplicatedFileChecksumHelper.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientAdapter.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientUtils.java, hadoop-ozone/ozonefs-common/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneClientUtils.java
Make use of the file checksum helper added in HDDS-6086 to implement Ozone file system getFileChecksum() API.
https://issues.apache.org/jira/browse/HDDS-6088
Contact test to be added.
=> HDDS-6088. Implement O3FS/OFS getFileChecksum() using file checksum helpers.

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java
Co-authored-by: Uma Maheswara Rao G <umagangumalla@cloudera.com>
Fix unaligned stripe write failure due to length overflow and
eliminate the unnecessary variable `currentBlockGroupLen`.
https://issues.apache.org/jira/browse/HDDS-6295
existing UT in CI: https://github.com/guihecheng/ozone/actions/runs/1827271876
manual test:
./bin/ozone sh bucket create vol1/bucket1 --layout=FILE_SYSTEM_OPTIMIZED --replication=rs-10-4-1024k --type EC
./bin/ozone sh key put /vol1/bucket1/hosts /etc/hosts
a new ut suggested by Uma, tested before and after apply patch.
=> HDDS-6295. EC: Fix unaligned stripe write failure due to length overflow.

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OzoneClientKeyGenerator.java
see: https://issues.apache.org/jira/browse/HDDS-6194
NA.
=> HDDS-6194. EC: Freon ockg support EC write

hadoop-ozone/dist/pom.xml
Update Ozone to latest `ozone-runner:20220212-1` docker image.
https://issues.apache.org/jira/browse/HDDS-6309
CI
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1836991719
=> HDDS-6309. Update ozone-runner version to 20220212-1

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockDataStreamOutput.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockDataStreamOutput.java
Just as what we did in HDDS-3155. Streaming also need support FlushDelay. This part is similar to BlockOutputStream.
Currently, the default value for FlushDelay is true.
https://issues.apache.org/jira/browse/HDDS-5487
=> HDDS-5487. [Ozone-Streaming] BlockDataStreamOutput support FlushDelay.

pom.xml
When updating Ozone's version with "mvn versions:set", the content of "ozone.version" is not updated.
This ticket is to add a maven-enforcer to make sure the ozone.version equals project.version. So that it can notice the inequality for the builder of the project.
https://issues.apache.org/jira/browse/HDDS-6304
Test by changing the ozone.version in pom.xml. The following error would happen if the ozone.version doesn't equal to project.version.
=> HDDS-6304. Add enforcer to make sure ozone.version equals project.version

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/SetNodeOperationalStateCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/datanode/InitDatanodeState.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestDatanodeStateMachine.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/TestHddsServerUtils.java
Cleanup unnecessary datanode id path checks.
More details on the JIRA below.
https://issues.apache.org/jira/browse/HDDS-6190
CI: https://github.com/guihecheng/ozone/actions/runs/1706899399
=> HDDS-6190. Cleanup unnecessary datanode id path checks.

pom.xml
Update json-smart to the latest version from the current 2.3.1.
Ozone's json-smart comes transitively from Hadoop. Note that Hadoop 3.3.1 is already using json-smart 2.4.2. So we shouldn't have problem updating to the 2.4 line.
Reason for the update: https://nvd.nist.gov/vuln/detail/CVE-2021-27568 and https://nvd.nist.gov/vuln/detail/CVE-2021-31684
https://issues.apache.org/jira/browse/HDDS-6310
=> HDDS-6310. Update json-smart to 2.4.7.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/states/ContainerStateMap.java
In `ContainerStateMap`, there are several maps to hold various details, eg:
```
private final Map<ContainerID, ContainerInfo> containerMap;
private final Map<ContainerID, Set<ContainerReplica>> replicaMap;
```
When we add a new container, we add an entry to both of these sets. When a container is removed, we don’t see to remove from replicaMap (see below). There doesn’t seem to be any way to remove the replicas later once the containerMap entry is gone, so removing the container is leaking the replicas.
```
public void removeContainer(final ContainerID id) {
Preconditions.checkNotNull(id, "ContainerID cannot be null");
if (contains(id)) {
// Should we revert back to the original state if any of the below
// remove operation fails?
final ContainerInfo info = containerMap.remove(id); …
```
=> HDDS-6313. Remove replicas in ContainerStateMap when a container is deleted

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockDataStreamOutput.java
Fix BlockDataStreamOutput#doFlushIfNeeded NPE
https://issues.apache.org/jira/browse/HDDS-6282
=> HDDS-6282. Fix BlockDataStreamOutput#doFlushIfNeeded NPE

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/OzoneManagerServiceProviderImpl.java
This bug was imported in [HDDS-6215](https://issues.apache.org/jira/browse/HDDS-6215), the root cause is we used `dbUpdates.getData().size()` to accumulate the sequenceNumber. But these two terms are different, a DBUpdates with data size of 10 could have a difference of sequenceNumber of 30 or more.
The bug can be reproduced by adding the following configurations and running `TestReconWithOzoneManager`.
```
conf.setLong(RECON_OM_DELTA_UPDATE_LIMIT, 2);
conf.setLong(RECON_OM_DELTA_UPDATE_LOOP_LIMIT, 10);
```
https://issues.apache.org/jira/browse/HDDS-6322
unit test.
=> HDDS-6322. Fix Recon getting inccorrect sequenceNumber from OM

hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/RawErasureDecoder.java
When [HDFS-16422](https://issues.apache.org/jira/browse/HDFS-16422) is resolved, we should replicate the fix to Ozone, as the same classes have been copied into the Ozone repo.
https://issues.apache.org/jira/browse/HDDS-6271
Existing tests - this is a simple change ported directly from HDFS.
=> HDDS-6271. EC: Apply fix for HDFS-16422 to the Ozone EC libraries

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/OzoneClientProducer.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/EndpointBase.java
In `ClientProtocol`:
```
setTheadLocalS3Auth -> setThreadLocalS3Auth
clearTheadLocalS3Auth -> clearThreadLocalS3Auth
```
Should just fix this before 1.3.0 is released.
https://issues.apache.org/jira/browse/HDDS-6325
- All existing tests shall pass.
=> HDDS-6325. Fix interface ClientProtocol methods typo setThreadLocalS3Auth and clearThreadLocalS3Auth

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/ClusterStateEndpoint.java
The Overview tab in Recon does not display the correct number of total keys in the cluster. Currently, only the keys present in `OBJECT_STORE` buckets are counted.
This task is to add the keys present in `FILE_SYSYEM_OPTIMIZED` buckets to the count.
https://issues.apache.org/jira/browse/HDDS-6311
Test Script
```bash
ozone sh volume create /vol1
ozone sh bucket create /vol1/bucket-obs
ozone sh bucket create /vol1/bucket-fso --layout FILE_SYSTEM_OPTIMIZED
ozone sh bucket list /vol1 
ozone sh key put /vol1/bucket-obs/key1 README.md 
ozone sh key put /vol1/bucket-obs/not-a-dir/key1 README.md
ozone sh key put /vol1/bucket-fso/dir1/key1 README.md
ozone sh key put /vol1/bucket-fso/key2 README.md
ozone sh key put /vol1/bucket-fso/dir1/dir3/key3 README.md
```
UI (should display Number of keys = 5)
=> HDDS-6311. Fix number of keys displayed in Recon Overview.

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMetrics.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketCreateRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestOMBucketCreateRequestWithFSO.java
Added `numFSOBucketCreates` metrics to reflect the number of FSO bucket creation requests.
https://issues.apache.org/jira/browse/HDDS-6305
=> HDDS-6305: Add metrics - number of FSO bucket creates

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMDBCheckpointProvider.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/TestHddsServerUtils.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemWithLinks.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMiniOzoneOMHACluster.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManagerHA.java
Remove unnecessary duplicate semicolons.
https://issues.apache.org/jira/browse/HDDS-6330
N/A
=> HDDS-6330. Remove unnecessary duplicate semicolons

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/dist/src/main/smoketest/ec/basic.robot, hadoop-ozone/dist/src/main/smoketest/ozone-lib/shell.robot, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequest.java
Use `ozone.server.default.replication` and `ozone.server.default.replication.type` as cluster level replication configs.
ReplicationConfig will be decided in the following order:
1. Client-passed config
2. Bucket-level config
3. Cluster-level config
When creating new buckets, the default bucket-level config is set to `null`.
When listing buckets, buckets with no bucket-level replicationConfig will not show `replicationConfig`.
https://issues.apache.org/jira/browse/HDDS-6294
integration tests and acceptance tests.
=> HDDS-6294. EC: Make cluster-wide EC configuration take effect

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
Change ContainerStateMachine ContainerOpExecutor name
https://issues.apache.org/jira/browse/HDDS-6283
=> HDDS-6283. Change ContainerStateMachine ContainerOpExecutor name

.github/workflows/post-commit.yml
CI can be retriggered for PRs in three ways:
* pushing new commit
* "re-run all checks" in Github Actions run result view
* closing/reopening PR
New (empty) commit makes CI history visible in the PR, but it triggers two runs: one for the PR and another in the source branch.
Github has recently improved run result view by including UI element for previous runs.  Earlier this was available only via the repository's  _Actions_ view, which lists all action runs, so finding the specific run was not easy.
Closing/reopening to trigger build has two disadvanteges: it produces unnecessary noise (in the PR and email notifications), and CI history is still hard to find.
We should disable build on reopen and prefer "re-run all checks".
https://issues.apache.org/jira/browse/HDDS-6324
Not tested, …
=> HDDS-6324. Do not trigger CI by reopening PR

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingService.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerDeletionChoosingPolicy.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/testutils/BlockDeletingServiceTestImpl.java
Add BlockDeletingService worker size config
https://issues.apache.org/jira/browse/HDDS-6284
=> HDDS-6284. Add BlockDeletingService worker size config

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerManagerImpl.java
- Introduced `getContainerStateCount()` to get the size of containers in a particular `LifeCycleState`
- To make `getContainers()` methods thread safe.
https://issues.apache.org/jira/browse/HDDS-6314
This patch was tested using CI tests.
=> HDDS-6314. ConcurrentModificationException getting SCMContainerMetrics

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/ListInfoSubcommand.java
In this change I fixed the handling of options when using `ozone admin datanode list`. Previously there was a condition check that only let using the --ip and --id options, in other cases it returned all the datanodes without filtering. 
https://issues.apache.org/jira/browse/HDDS-6290
Existing tests (unit and acceptance) and tested in docker environment.
=> HDDS-6290. operational-state and node-state options in datanode list CLI not working correctly

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/protocolPB/OMPBHelper.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerProtocolServerSideTranslatorPB.java
Similar to HDDS-4271, we need to filter some binary data in OM proto messages.
https://issues.apache.org/jira/browse/HDDS-6262
```
$ cd hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/ozone
$ ./run.sh -d
$ sleep 60
$ docker-compose exec scm ozone freon ockg -n1 -t1 -F ONE
$ docker-compose exec scm ozone insight logs -v om.protocol.client
...
[OM] ... [type=DBUpdates] request is processed. Response:
cmdType: DBUpdates
traceID: ""
success: true
status: OK
dbUpdatesResponse {
sequenceNumber: 18446744073709551615
data: "<redacted>"
}
```
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1796465657
=> HDDS-6262. ozone insight log stops working after OM DBUpdates message

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockOutputStreamEntry.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java
Fix large write with multiple stripes upon stripe failure.
https://issues.apache.org/jira/browse/HDDS-6342
a new ut covers this case.
manual test with ockg.
=> HDDS-6342. EC: Fix large write with multiple stripes upon stripe failure.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/states/ContainerStateMap.java
Inside ContainerStateMap, the replicas for a container are stored in a Set backed by a ConcurrentHashMap.
When you ask for the current replicas of a container, this method is used:
```
public Set<ContainerReplica> getContainerReplicas(
final ContainerID containerID) {
Preconditions.checkNotNull(containerID);
final Set<ContainerReplica> replicas = replicaMap.get(containerID);
return replicas == null ? null : Collections.unmodifiableSet(replicas);
} 
```
Note that it pulls out the Set, wraps it as unmodifiable and returns it.
There is a problem here, in that if the Set is updated by ICR / FCR at the same time as another part of the code has taken a reference to it, the other part of the code can make incorrect decisions. Eg:
```
Set<> replicas = getContainerReplicas(...)
replicaCount = …
```
=> HDDS-6292. Ensure immutable ContainerReplica set is returned from ContainerStateManagerImpl

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/StandardOutputTestBase.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/StandardOutputTestUtil.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestNSSummaryAdmin.java
Improvements similar to [HDDS-6227](https://issues.apache.org/jira/browse/HDDS-6227).
Rename some test helper classes to match Ozone's naming conventions for tests (`Test*` class should have tests).
https://issues.apache.org/jira/browse/HDDS-6350
Related Tests.
=> HDDS-6350. Test helpers should observe naming conventions - 2.

hadoop-ozone/dist/src/main/compose/upgrade/testlib.sh
It turns out when the upgrade test suite execution failed, the `rebot` command inside `generate_report` will exit the script when it finished generating the HTML reports. That skipped the `copy_results` call immediately following the `generate_report` call. Swapping the position of these two lines should alleviate the issue. See the comments under jira HDDS-6327 for more information.
https://issues.apache.org/jira/browse/HDDS-6327
- All existing test cases should pass. In the case of upgrade acceptance test failure (in misc), related `docker-*.log` should be collected.
=> HDDS-6327. Upgrade acceptance test doesn't collect logs when the test fails

hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/CodecRegistry.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/AbstractNativeRawDecoder.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/ErasureCodeNative.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/NativeRSRawDecoder.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/NativeRSRawEncoder.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/NativeRSRawErasureCoderFactory.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/NativeXORRawDecoder.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/NativeXORRawEncoder.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/NativeXORRawErasureCoderFactory.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/util/CodecUtil.java, hadoop-hdds/erasurecode/src/main/resources/META-INF/services/org.apache.ozone.erasurecode.rawcoder.RawErasureCoderFactory, hadoop-hdds/erasurecode/src/test/java/org/apache/ozone/erasurecode/TestCodecRegistry.java, hadoop-hdds/erasurecode/src/test/java/org/apache/ozone/erasurecode/rawcoder/TestCodecRawCoderMapping.java, hadoop-hdds/erasurecode/src/test/java/org/apache/ozone/erasurecode/rawcoder/TestNativeRSRawCoder.java, hadoop-hdds/erasurecode/src/test/java/org/apache/ozone/erasurecode/rawcoder/TestNativeXORRawCoder.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockReconstructedStripeInputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/ECStreamTestUtil.java
Taken the Native Integration of Java side classes with fallback coder support from hadoop. When native coders not available, it will fallback to java.
https://issues.apache.org/jira/browse/HDDS-6188
There are tests added to verify the behavior and also integrated with Ozone EC IO streams.
=> HDDS-6188: EC: Adapt java side native coder classes from hadoop.

hadoop-hdds/docs/content/feature/PrefixFSO.md
The documentation lists out of date information about File System Optimization features.
We no longer recommend using `ozone.om.enable.filesystem.paths` configuration for enabling File System Optimization. We now have support for bucket layout features to support bucket-specific metadata formats.
Examples of outdated documentation:
[LINK](https://ozone.apache.org/docs/1.2.1/feature/prefixfso.html)
```
...
Note: This feature works only when ozone.om.enable.filesystem.paths is enabled which means that Hadoop Compatible File System compatibility is favored instead of S3 compatibility. Some irregular S3 key names may be rejected or normalized.
...
By default the feature is disabled. It can be enabled with the following settings in ozone-site.xml:<property> …
```
=> HDDS-6351. [Docs] Update prefix-based FSO documentation.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/ECStreamTestUtil.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestECBlockInputStream.java
Fixed a race condition in test. When creating stream we used arraylist in stub class. Using ArrayList add in multithreaded envs tend to be problematic. It could induce null values in array list. Due to NPE, randomly test failing.
https://issues.apache.org/jira/browse/HDDS-6341
Verified the test by keeping it in tight loop.
=> HDDS-6341: EC: Fix the race condition in TestECBlockReconstructedStripeInputStream.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerSet.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/interfaces/Handler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/report/ContainerReportPublisher.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/report/IncrementalReportSender.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/StateContext.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/datanode/RunningDatanodeState.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestHddsDispatcher.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/TestStateContext.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/events/FixedThreadPoolWithAffinityExecutor.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/events/TestEventQueue.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/events/SCMEvents.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeHeartbeatDispatcher.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
This is the DB side of changes. It includes
1. Serialization for ICR and FCR generation.
2. Collapsing ICR and FCR if part of the same HB. Such that FCR has the most recent changes.
3. SCM uses the same thread for a given DN serializing processing of ICR and FCR with FCR being processed before ICR.
https://issues.apache.org/jira/browse/HDDS-5267
ToDo:
=> HDDS-5267 Merge ICR and FCR for containers if part of the same HB

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntryPool.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java
Changed the logic to pass the actual determined length instead of using the cellBuffer.limit
CellBuffer would have beed modified by adding padding bytes by the time of retries. So, it's safe to use determined expected len instead of of just using cellBuffer.limit
https://issues.apache.org/jira/browse/HDDS-6348
Added a test check the behavior.
=> HDDS-6348: EC: PartialStripe failure handling logic is writing padding bytes also to DNs

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OzoneClientKeyGenerator.java
The `NotImplementedException` from `flush()` is causing problems in applications.
Let's replace this exception by log, since we are not going to implement `flush()` API.
(Behave same as HDFS EC.)
https://github.com/apache/hadoop/blob/62c86eaa0e539a4307ca794e0fcd502a77ebceb8/hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DFSStripedOutputStream.java#L1012-L1024
https://issues.apache.org/jira/browse/HDDS-6372
manual tests
=> HDDS-6372. EC: Do not throw NotImplementedException in flush()

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/MultipartCryptoKeyInputStream.java, hadoop-ozone/dist/src/main/compose/ozonesecure/docker-config, hadoop-ozone/dist/src/main/compose/ozonesecure/test.sh, hadoop-ozone/dist/src/main/smoketest/s3/MultipartUpload.robot, hadoop-ozone/dist/src/main/smoketest/s3/commonawslib.robot, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneAtRestEncryption.java
`MultipartCryptoKeyInputStream` may need to adjust read position and/or length to make sure it reads enough data to fill the crypto buffer.  Position adjustment means read starts at a location before the actual requested position.  Length adjustment means more data is read at the end.  Extra data is discarded in both cases.
This PR fixes a bug in length adjustment: the position of the underlying stream was left at the position after the discarded part, this is where the next read started.  Thus this part was missing from the final data at the client side.
The bug can be reproduced with MPU parts that are not whole multiples of the crypto buffer size, which defaults to 8KB.  Hence test case is added where the first part has 1KB more, to trigger length adjustment in the second part.
The PR …
=> HDDS-6349. IncompleteReadError on get MPU key from TDE bucket

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerStateManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerStateManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerReportHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerStateManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestIncrementalContainerReportHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestReplicationManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerStateManagerIntegration.java
In ContainerManagerImpl, most of the methods accept a ContainerID object. This is then converted into `HddsProtos.ContainerID` to pass to ContainerStateManagerImpl. The data is stored in ContainerStateMap, where it is all keyed on ContainerID, so the `HddsProtos.ContainerID` has to be converted back to ContainerID again, which seems wasteful.
There are some methods in the ContainerStateManager interface that are annotated `@Replicate`, and they need to continue to passed the ContainerID Protobuf, but they are few and can be handled as special cases.
There are also some TODO's in the code suggesting it was always the intention to make this change, but it never happened, eg:
```
@Override
public boolean contains(final HddsProtos.ContainerID id) {
lock.readLock().lock();
try {
// TODO: …
```
=> HDDS-6334. Remove ContainerID to Proto to ContainerID conversion in ContainerStateManagerImpl

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java
Refactor the code to make it cleaner, here is a summary of the changes.
1. Instead of treating `head/middle/tail` differently, use a general way to write data into buffers.
2. No more `allocateBlockIfNeeded` parameters being passed around.
3. Stream will be closed if any exception happens, and `IOException` will be thrown.
https://issues.apache.org/jira/browse/HDDS-6358
Unit tests.
=> HDDS-6358. EC: Refactor ECKeyOutputStream#write()

hadoop-hdds/docs/content/concept/Containers.md, hadoop-hdds/docs/content/concept/Datanodes.md, hadoop-hdds/docs/content/concept/OzoneManager.md, hadoop-hdds/docs/content/concept/Recon.md, hadoop-hdds/docs/content/feature/OM-HA.md, hadoop-hdds/docs/content/feature/PrefixFSO.md, hadoop-hdds/docs/content/feature/SCM-HA.md, hadoop-hdds/docs/dev-support/bin/generate-site.sh, hadoop-hdds/docs/dev-support/bin/make_images_responsive.py, hadoop-hdds/docs/themes/ozonedoc/layouts/shortcodes/image.html
Currently, if we want to add responsive images to the documentation website, we must use a Hugo shortcode introduced in [HDDS-6073](https://issues.apache.org/jira/browse/HDDS-6073) (#2898).
This looks like:
```
{{< image src="image-name.png">}} 
```
While this shortcode gets converted into an HTML `img` in the production build after running `hugo -d`, IDEs and GitHub are not able to parse this as an image and make it harder to review pull requests when this format is used.
This Jira introduces a python script that will be called as a part of the maven build process, which will automatically replace all markdown images with their respective shortcodes - allowing developers to use familiar native markdown syntax (readable by GitHub and IDEs).
https://issues.apache.org/jira/browse/HDDS-6361 …
=> HDDS-6361. Modify docs build flow to replace image tags with shortcodes.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/MeasuredReplicator.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestMeasuredReplicator.java
The current logic to calculate the queue time of a ReplicationTask is as follows:
```
(Instant.now().getNano() - task.getQueued().getNano()) / 1_000_000; 
```
But Instant's nano only records the nanosecond part, it's like operation of mod.
For example, if nano part of getQueued is 500_000_000,  and queue time is 600ms
| item | time|
|---| ---|
|getQueued|500_000_000|
|in Queue|600_000_000|
|getProcessed|1100_000_000|
|call getNano()|100_000_000|
Then the result of the code mentioned above would be (100_000_000 - 500_000_000) / 1_000_000, which is -400.
This ticket is to solve this bug by using Duration.between to get the correct queueTime.
https://issues.apache.org/jira/browse/HDDS-6374
unit test.
=> HDDS-6374. Fix incorrect queueTime metrics of ReplicationTask

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/QuotaUtil.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestQuotaUtil.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequestWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadAbortRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCommitPartRequest.java
OM keeps a running total of the space consumed in a bucket each time a key is created or deleted. The space tracked, is the total space used by the key, including replication. As it stands, the datasize is multipied by the Factor to give the total space used. For EC, this is not correct.
This PR is to change all the places the bucket total is adjusted in OM, to cater for both Ratis and EC.
https://issues.apache.org/jira/browse/HDDS-6279
New tests for the replication calculation. Manually for EC keys for now.
=> HDDS-6279. EC: Calculate EC replication correctly when updating bucket usage

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzonePrefixPathImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/OMClientRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyDeleteRequestWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRenameRequestWithFSO.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyDeleteRequestWithFSO.java
If a directory under an FSO bucket does not contain any subfiles/directories - set the recursive flag for Ranger#getAcl call to false.
**Ranger Policy 1:**
Key Resource | Permission | User
-- | -- | --
dir1/dir11, dir1/dir11/ | Read, Write, Delete | user2
**Ranger Policy 2:**
Key Resource | Permission | User
-- | -- | --
dir* | Read, Write, Delete | user1
**Case:**
<p>1) user2 has created a directory dir1/dir11. Since the explicit policy defined for user2, it will successfully create the directories.</p>
<p>2) user1 has recursive permission, he can create any dirs under " dir* ". Say, user1 created a file under directory "dir1/dir11/file".</p>
<p>3) user2 issues recursive delete on "dir1/dir11". <strong>(Recursive flag is sent to Ranger from internal Ozone call)</strong>.</p>
<pre …
=> HDDS-6337. [FSO] Disable recursive access check flag for directories with no children.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ECReplicationConfig.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/RatisReplicationConfig.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/StandaloneReplicationConfig.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneKey.java, hadoop-ozone/dist/src/main/smoketest/ozonefs/ozonefs.robot
Listing they key details looks like the following:
```
$ ozone sh key info /vol1/bucket1/key5
{
"bucketName" : "bucket1",
"name" : "key5",
"dataSize" : 174,
"creationTime" : "2022-02-27T21:38:48.816Z",
"modificationTime" : "2022-02-27T21:38:49.526Z",
"replication" : "THREE",
},
"ozoneKeyLocations" : [ {
"containerID" : 5,
"localID" : 109611004723200006,
"length" : 174,
"offset" : 0,
"keyOffset" : 0
} ],
"replicationType" : "RATIS",
"replicationFactor" : 3
} 
```
ReplicationType and Factor are now contained in ReplicationConfig, so we should not display them in the JSON output. Also note that the replicationFactor is duplicated inside …
=> HDDS-6380. EC: Key Info command should not display legacy replication fields as they duplicate ReplicationConfig

hadoop-ozone/dev-support/checks/acceptance.sh, hadoop-ozone/dist/src/main/compose/testlib.sh
Include audit log files in acceptance test bundle, except empty ones.  For better usability, logs for each environment, including docker logs, are moved to a subdirectory.
https://issues.apache.org/jira/browse/HDDS-6268
Checked contents of bundles created in CI run:
```
$ unzip -t acceptance-HA.zip
Archive:  acceptance-HA.zip
testing: jacoco-combined.exec     OK
testing: log.html                 OK
testing: output.log               OK
testing: ozone-ha.xml             OK
testing: ozone-ha/                OK
testing: ozonesecure-ha.xml       OK
testing: ozonesecure-ha/          OK
testing: report.html              OK
testing: summary.html             OK
testing: ozone-ha/docker-ozone-ha-ozone-ha-ozone-shell-single-scm1.log   OK
testing: ozone-ha/om-audit-om1.log   OK
testing: …
```
=> HDDS-6268. Include audit log in acceptance test bundle

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServer.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/metrics/ReconTaskStatusMetrics.java
Add an ability to Recon to export a new metrics about timestamps from `ReconTaskStatus` table in Derby DB. Recon also has OzoneManagerSyncMetrics for OM snapshot related tasks but this metrics focuses entire Recon sub-tasks.
```
recon_task_status_metrics_last_updated_seq_number{type="ContainerHealthTask",hostname="localhost"} 0
recon_task_status_metrics_last_updated_seq_number{type="ContainerKeyMapperTask",hostname="localhost"} 2
recon_task_status_metrics_last_updated_seq_number{type="FileSizeCountTask",hostname="localhost"} 2
recon_task_status_metrics_last_updated_seq_number{type="NSSummaryTask",hostname="localhost"} 2
recon_task_status_metrics_last_updated_seq_number{type="OmDeltaRequest",hostname="localhost"} 2
recon_task_status_metrics_last_updated_seq_number{type="OmSnapshotRequest",h …
```
=> HDDS-6317: Export ReconTaskStatus as Prometheus metrics

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBUpdatesWrapper.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/DBUpdates.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManager.java, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/metrics/OzoneManagerSyncMetrics.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/OzoneManagerServiceProviderImpl.java
In [HDDS-6312](https://issues.apache.org/jira/browse/HDDS-6312), Recon is regulated to retrieve a limited number of delta updates from OM, which eliminates the possibility of large delta updates causing OM's OOM.
We did this control by setting the configuration of "recon.om.delta.update.limit" and "recon.om.delta.update.loop.limit", the default consume speed would be 2000*10 per 10 minutes, but we are not sure if we are consuming at an optimal speed.
This ticket is to add a metric to record the lag between Recon and OM, which can help to set an appropriate value and prepare for other near real-time works on the Recon side.
https://issues.apache.org/jira/browse/HDDS-6333
unit test.
=> HDDS-6333. Add a metric to record sequence number lag between Recon and OM

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerMetrics.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancer.java
The `ContainerBalancerMetrics` class is responsible for recording metrics. These metrics always show 0 when accessed through JMX, while expected values are greater than 0. 
I deleted some metrics of the type `MutableGaugeLong` and instead used the type `MutableCounterLong`. Introduced a new metric `countIterations` that keeps count of the number of iterations that balancer has run for.
https://issues.apache.org/jira/browse/HDDS-6244
Updated TestContainerBalancer#testMetrics()
=> HDDS-6244. ContainerBalancer metrics don't show updated values in JMX

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzonePrefixPathImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/TrashOzoneFileSystem.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
Reduce RPC calls by avoiding content-related operations (refresh pipeline, etc.) for ACL check.  Reuse `isHeadOp` flag for this purpose.
https://issues.apache.org/jira/browse/HDDS-6321
Reproduced manually on `master` in `ozonesecure` environment.
Added integration test:
```
[ERROR] Tests run: 20, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 16.828 s <<< FAILURE! - in org.apache.hadoop.ozone.om.TestKeyManagerImpl
[ERROR] testCheckAccessForFileKey  Time elapsed: 0.044 s  <<< FAILURE!
org.mockito.exceptions.verification.NeverWantedButInvoked:
storageContainerLocationProtocol.getContainerWithPipelineBatch(
<any>
);
Never wanted here:
-> at org.apache.hadoop.ozone.om.TestKeyManagerImpl.testCheckAccessForFileKey(TestKeyManagerImpl.java:486)
But invoked here:
-> at …
```
=> HDDS-6321. Avoid refresh pipeline for key lookup in checkAcls

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerInfo.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/AbstractContainerReportHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/HddsTestUtils.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerReportHandler.java
The current container report handling logic in AbstractContainerReportHandler does not update the container usage and key count correctly in SCM for EC containers. The current logic says:
```
for (ContainerReplica r : otherReplicas) {
// Open containers are generally growing in key count and size, the
// overall size should be the min of all reported replicas.
if (containerInfo.getState().equals(HddsProtos.LifeCycleState.OPEN)) {
usedBytes = Math.min(usedBytes, r.getBytesUsed());
keyCount = Math.min(keyCount, r.getKeyCount());
} else {
// Containers which are not open can only shrink in size, so use the
// largest values reported.
usedBytes = Math.max(usedBytes, r.getBytesUsed());
keyCount = Math.max(keyCount, r.getKeyCount());
}
} 
```
For EC Containers, the bytes used will be different …
=> HDDS-6384. EC: Ensure EC container usage is updated correctly when handling reports

hadoop-hdds/docs/content/tools/TestTools.md, hadoop-hdds/docs/content/tools/TestTools.zh.md
Fix typo in TestTools.md (and TestTools.zh.md)
```
diff --git a/hadoop-hdds/docs/content/tools/TestTools.md b/hadoop-hdds/docs/content/tools/TestTools.md
index 83b40cb5f..bde400d84 100644
--- a/hadoop-hdds/docs/content/tools/TestTools.md
+++ b/hadoop-hdds/docs/content/tools/TestTools.md
@@ -59,7 +59,7 @@ cd compose/ozone
Blockade tests are implemented with the help of tests and can be started from the `./blockade` directory of the distri>
-cd blocakde
+cd blockade
pip install pytest==2.8.7,blockade
python -m pytest -s .
```
https://issues.apache.org/jira/browse/HDDS-6423
No tests, just an improvement on a document.
=> HDDS-6423. Fix typo in TestTools.md

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelinePlacementPolicy.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelinePlacementPolicy.java
In this change I modified the currentPipelineCount() method. I found that when the method calculated the current pipeline count in a datanode it counted in the STANDALONE pipelines. We shouldn't count the single node pipelines in, only the RATIS/THREE ones. So I renamed the method to currentRatisThreePipelineCount() and changed it to count the datanodes non closed RATIS/THREE pipelines. With this I fixed the problem, when we reached the pipeline limit with STANDALONE/ONE pipelines so it didn't create a RATIS/THREE pipeline. 
With the modified method some tests started failing in the TestPipelinePlacementPolicy. It was because some tests are using the insertHeavyNodesIntoNodeManager method which were only inserting the datanodes and its pipelines into the nodeManager and not into the …
=> HDDS-6379. Not deducting the STANDALONE pipelines when counting pipelines on each datanode to check the pipeline limit

hadoop-ozone/dist/src/main/compose/ozone/docker-config, hadoop-ozone/dist/src/main/compose/ozone/test.sh, hadoop-ozone/dist/src/main/compose/testlib.sh, hadoop-ozone/dist/src/main/smoketest/debug/ozone-debug-corrupt-block.robot, hadoop-ozone/dist/src/main/smoketest/debug/ozone-debug-dead-datanode.robot, hadoop-ozone/dist/src/main/smoketest/debug/ozone-debug-modified-env.robot, hadoop-ozone/dist/src/main/smoketest/debug/ozone-debug-stale-datanode.robot, hadoop-ozone/dist/src/main/smoketest/debug/ozone-debug-tests.robot, hadoop-ozone/dist/src/main/smoketest/debug/ozone-debug.robot
In this change I added acceptance robot tests to the previously added read-replicas debug CLI tool. There was an already existing ozone-debug.robot test which I made into a resource file with keywords to check the JSON file generated with read-replicas. I made an ozone-debug-tests.robot for the chunkinfo and read-replicas CLI tool related tests in basic environment. I added two test files, one for the case when one of the block replicas became corrupt and one when one of the datanodes is unavailable. I changed the block size in the compose/ozone docker environment, so I can test the read-replicas command with a key with more than one block and it won't take that much to execute it. I am executing the added tests in the compose/ozone’s test.sh via a method in testlib.sh. …
=> HDDS-6153. Add simple integration test to the read-replicas debug tool.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java
Debug logs added to identify Over-Utilized and Under-Utilized DNs.
[HDDS-6415](https://issues.apache.org/jira/browse/HDDS-6415)
Jar was build after applying the patch. Jar was replaced in live cluster and tested 
Test output:
```
2022-03-07 12:56:53,064 INFO org.apache.hadoop.hdds.scm.container.balancer.ContainerBalancer: Container Balancer has identified 3 Over-Utilized and 5 Under-Utilized Datanodes that need to be balanced.
2022-03-07 12:56:53,064 DEBUG org.apache.hadoop.hdds.scm.container.balancer.ContainerBalancer: Datanode quasar-usholy-1.quasar-usholy.root.hwx.site 9063cde0-96df-4368-bd57-e5dc60c2fd7d is Over-Utilized.
2022-03-07 12:56:53,064 DEBUG org.apache.hadoop.hdds.scm.container.balancer.ContainerBalancer: Datanode quasar-usholy-2.quasar-usholy.root.hwx.site …
```
=> HDDS-6415 - add Over-Utilized and Under-Utilized DN details in debug log

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/pipeline/ListPipelinesSubcommand.java, hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/pipeline/TestListPipelinesSubCommand.java
In ListPipeline.java we have:
```
@Override
public void execute(ScmClient scmClient) throws IOException {
Stream<Pipeline> stream = scmClient.listPipelines().stream();
if (!Strings.isNullOrEmpty(factor)) {
stream = stream.filter(
p -> ReplicationConfig.getLegacyFactor(p.getReplicationConfig())
.toString().compareToIgnoreCase(factor) == 0);
}
if (!Strings.isNullOrEmpty(state)) {
stream = stream.filter(p -> p.getPipelineState().toString()
.compareToIgnoreCase(state) == 0);
}
stream.forEach(System.out::println);
} 
```
This code will fail if the pipeline is an EC pipeline. We should also allow for filtering on EC pipelines.
https://issues.apache.org/jira/browse/HDDS-6382
New unit tests and verified in docker cluster
=> HDDS-6382. EC: ListPipelines command should consider EC Containers

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ContainerBalancerStartSubcommand.java
After this change, picocli warnings will be no more seen in ozone container balancer. 
[HDDS-6306](https://issues.apache.org/jira/browse/HDDS-6306)
This patch was tested using docker-compose
=> HDDS-6306 - Fix picocli warnings in ozone container balancer help

hadoop-ozone/dist/src/main/smoketest/s3/awss3.robot, hadoop-ozone/dist/src/main/smoketest/s3/bucketlist.robot, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/OzoneClientProducer.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/exception/S3ErrorTable.java
For many errors, S3g return a fuzzy error log which are not easy for users and maintainers to find the root cause of the error.
The current error is like follows:
```
An error occurred (500) when calling the ListBuckets operation (reached max retries: 4): Internal Server Error 
```
This ticket is to fix this issue and return more detailed messages.
https://issues.apache.org/jira/browse/HDDS-6419
Test example
1. List bucket with empty auth.
* Clean the key and secret in ~/.aws/credentials
* Run the command of `aws s3api --endpoint=http://localhost:9878 list-buckets`
* Before fix the return error is 
`An error occurred () when calling the ListBuckets operation:`
* After fix the return error is
`An error occurred (AuthorizationHeaderMalformed) when calling the ListBuckets operation: The …
=> HDDS-6419. Add detail error message instead of generic INTERNAL SERVER ERROR for S3g

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneClientFactory.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/TestOzoneClientFactory.java
In OzoneClientFactory.getClientProtocol(), if we get a RemoteException which wraps the true exception inside, we can not get the real error message from the exception. The default error message of "Couldn't create RpcClient protocol" would be returned to users, which is not good for users to get the root cause of the error.
This ticket is to unwrap the real exception from RemoteException.
https://issues.apache.org/jira/browse/HDDS-6407
manual test.
=> HDDS-6407. Unwrap RemoteException in getClientProtocol

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequestWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequestWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3MultipartUploadCompleteResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3MultipartUploadCompleteResponseWithFSO.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartUploadCompleteRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3MultipartResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3MultipartUploadCompleteResponseWithFSO.java
This pull request aims at porting my work in HDDS-5461 ( https://github.com/apache/ozone/pull/2433 ) to multipart-uploaded objects. The change is almost same; on committing multipart objects (moving the OmKeyInfo from multipart table to key table), move the previous version of the key info to delete table.
CC: @bharatviswa504 
HDDS-5656
Unit tests updated
=> HDDS-5656. Move old objects to delete table on overwriting multipart objects

hadoop-hdds/common/pom.xml, hadoop-hdds/framework/pom.xml, hadoop-ozone/ozonefs-shaded/pom.xml, pom.xml
Ozone FS shaded jars started including Log4J2 jars with version 1.0.0:
```
$ unzip -t ozone-0.5.0-beta/share/ozone/lib/hadoop-ozone-filesystem-lib-current-*.jar | grep -c org.apache.logging.log4j
0
$ unzip -t ozone-1.0.0/share/ozone/lib/hadoop-ozone-filesystem-hadoop3-*.jar| grep -c org.apache.logging.log4j
1286
$ unzip -t ozone-1.2.1/share/ozone/lib/ozone-filesystem-hadoop3-*.jar | grep -c org.apache.logging.log4j
1381
```
Since Ozone uses Log4J2 only for audit logging, which is a server-side feature, client does not need this dependency, so I think we can remove it.
This patch:
1. `hdds-common` only needs `log4j-api`, not the implementation (except for unit test).  Move the implementation dependencies to the `hdds-server-framework` module, shared among server-side components.
2. Exclude …
=> HDDS-6299. Remove Log4J2 from Ozone FS shaded jars

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneManagerVersion.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/TestComponentVersionInvariants.java
Similarly to ClientVersion and DatanodeVersion, this PR is to introduce OzoneManagerVersion. This is a pre-requisite for the change proposed in HDDS-6393.
https://issues.apache.org/jira/browse/HDDS-6392
The PR is introducing a new enum, without uses. Tests that rely on the new enum to be defined in the follow-up JIRA HDDS-6393.
=> HDDS-6392. Introduce OzoneManagerVersions enum

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequestWithFSO.java
FSO bucket info was not updated correctly, which causes incorrect `usedBytes`.
This patch fixes the problem.
https://issues.apache.org/jira/browse/HDDS-6431
New integration test was added.
=> HDDS-6431. Fix usedBytes for FSO bucket

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockReconstructedInputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockReconstructedStripeInputStream.java
Due to the issue described in [HDDS-6424](https://issues.apache.org/jira/browse/HDDS-6424), where KeyInputStream opens all its inputStreams for the entire key upfront, we should avoid allocating buffers in the EC Reconstruction InputStreams until they are actually needed (ie on first read).
https://issues.apache.org/jira/browse/HDDS-6437
Existing tests
=> HDDS-6437. EC: Avoid allocating buffers in EC Reconstruction Streams until first read

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/DatanodeVersion.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/ClientVersion.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneManagerVersion.java
Avoid frequent usage of `values()` in component version enums by implementing `toProtoValue` as a map lookup.
https://issues.apache.org/jira/browse/HDDS-6439
```
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in org.apache.hadoop.hdds.TestComponentVersionInvariants
```
https://github.com/adoroszlai/hadoop-ozone/runs/5533214782#step:5:3181
=> HDDS-6439. Minor perf optimization in component version enums

hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
Address usage of `ReplicationConfig.getLegacyFactor()` in `OzoneManagerRequestHandler` and ensure the ECReplicationConfig is returned when the key is EC.
https://issues.apache.org/jira/browse/HDDS-6413
=> HDDS-6413. EC: OzoneManagerRequestHandler needs to handle ECReplicaonConfig

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/client/ScmClient.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocol.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/protocolPB/StorageContainerLocationProtocolClientSideTranslatorPB.java, hadoop-hdds/interface-admin/src/main/proto/ScmAdminProtocol.proto, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocolServerSideTranslatorPB.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ContainerOperationClient.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/container/ListSubcommand.java, hadoop-ozone/dist/src/main/smoketest/admincli/container.robot, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
The container list command currently allows filtering by Factor, but with EC, it needs to be extended to filter by replication type and EC / Ratis replication schemes.
https://issues.apache.org/jira/browse/HDDS-6248
Manually via docker compose, plus some existing acceptance tests list ratis containers with factor ONE and THREE.
=>  HDDS-6248. EC: Container list command should allow filtering of EC containers

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestRatisPipelineLeader.java, pom.xml
Update the Ratis SNAPSHOT version.
https://issues.apache.org/jira/browse/HDDS-6461
=> HDDS-6461. Update Ratis version to 2.3.0-da5d868-SNAPSHOT.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneCluster.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java
DEFAULT_PIPELIME_LIMIT was changed to DEFAULT_PIPELINE_LIMIT in MiniOzoneCluster.java
https://issues.apache.org/jira/browse/HDDS-4171
N/A since a typo
=> HDDS-4171. DEFAULT_PIPELIME_LIMIT typo in MiniOzoneCluster

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequestWithFSO.java
The incorrect preAllocatedBlocks for EC keys HDDS-6452(#3194) revealed the bug.
The correctedSpace in commitKey should be calculated against preAllocatedBlocks instead of the actual blocks in the final.
~~Steps to reproduce the bug:~~
~~First, cherry-pick f826d124aa1d8063d37a1ef3c1809787401b7b0b from master (already included in this PR).~~
~~`KEYSIZE=$(expr 256 '*' 1024 '*' 1024 '+' 1)`~~
~~`ozone sh volume create vol1`~~
~~`ozone sh bucket create vol1/bucket1 -l FILE_SYSTEM_OPTIMIZED -t EC -r rs-3-2-1024k`~~
~~`ozone freon ockg --volume vol1 --bucket bucket1 -s $KEYSIZE -n 1 -p foobar`~~
~~`ozone freon ockr --volume vol1 --bucket bucket1 -n 1 -p foobar`~~
~~`ozone sh bucket info vol1/bucket1`~~
~~usedBytes should be 0 instead of 1342177280.~~ …
=> HDDS-6450. [FSO] Fix correctedSpace for usedBytes in commitKey

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAWithData.java
This assertion is wrong in TestOzoneManagerHAWithData#testOMRestart().
Because the lagging follower OM may catch up asynchronously.
```java
// Restart the stopped OM.
followerOM1.restart();
// Get the latest snapshotIndex from the leader OM.
long leaderOMSnaphsotIndex = leaderOM.getRatisSnapshotIndex();
// The recently started OM should be lagging behind the leader OM.
long followerOMLastAppliedIndex =
followerOM1.getOmRatisServer().getLastAppliedTermIndex().getIndex();
Assert.assertTrue(
followerOMLastAppliedIndex < leaderOMSnaphsotIndex);
```
Example of CI failure on master: https://github.com/apache/ozone/runs/5593803014
Result of running this test 100x: https://github.com/kaijchen/ozone/actions/runs/2007487998
https://issues.apache.org/jira/browse/HDDS-6470 …
=> HDDS-6470. Fix TestOzoneManagerHAWithData#testOMRestart()

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmAcls.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/acl/OMBucketAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyAclRequestWithFSO.java
The resource type checked in BucketACL and KeyACL are now currently VOLUME, need to change to the correct resource type.
https://issues.apache.org/jira/browse/HDDS-6468
unit test
=> HDDS-6468. Set correct resource Type for BucketACL and KeyACL

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCreateRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyRequest.java
OM is pre-allocating too much blocks for EC keys.
Assume the replication config is `rs-3-2-1024k`.
| KeySize | PreAllocatedSpace (Expected) |  PreAllocatedSpace (Current) |
| --- | --- | --- |
| 1 MB | blockSize * 5 | blockSize * 5 |
| blockSize + 1 MB | blockSize * 5 | blockSize * 5 * 2 |
| blockSize * 2 + 1 MB | blockSize * 5 | blockSize * 5 * 3 |
| blockSize * 3 + 1 MB | blockSize * 5 * 2 | blockSize * 5 * 4 |
https://issues.apache.org/jira/browse/HDDS-6452
New integration test was added.
=> HDDS-6452. EC: Fix number of preAllocatedBlocks for EC keys

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/ha/OMFailoverProxyProvider.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/Hadoop3OmTransport.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/ha/TestOMFailoverProxyProvider.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAMetadataOnly.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAWithFailover.java, hadoop-ozone/ozonefs-hadoop2/src/main/java/org/apache/hadoop/fs/ozone/Hadoop27RpcTransport.java
Perform failover in the correct interface that is guaranteed to be called only once in a multi-threaded environment.
https://issues.apache.org/jira/browse/HDDS-5228
=> HDDS-5228 Make OM FailOverProxyProvider work across threads

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/BaseFileChecksumHelper.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/ReplicatedFileChecksumHelper.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/checksum/TestReplicatedFileChecksumHelper.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientUtils.java
Initial support for composite CRC. Configured by ozone.client.checksum.combine.mode
https://issues.apache.org/jira/browse/HDDS-6087
=> HDDS-6087. Compute composite CRC file checksum using chunk checksums from DataNodes.

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMDbCheckpointServlet.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMiniOzoneOMHACluster.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMDbCheckpointServlet.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmAcls.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmInit.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHA.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerListVolumes.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerRestart.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestSecureOzoneManager.java, hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OpenKeyCleanupService.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmMetadataManager.java
Move config keys for open key cleanup service from OzoneConfigKeys to OMConfigKeys. 
Change key names and default values as the design doc.
This change was part of #1511. The differences are:
1. `org.apache.ratis.util.TimeDuration` was replaced by `java.time.Duration`.
2. `Instant.now()` is only called once per query in `getExpiredOpenKeys()`.
Since the service needs refinement such as Quota and FSO support,
let's update the config keys first. 
https://issues.apache.org/jira/browse/HDDS-6228
Integration tests.
=> HDDS-6228. Update config keys for open key cleanup service

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/WritableECContainerProvider.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestWritableECContainerProvider.java
In [HDDS-6384](https://issues.apache.org/jira/browse/HDDS-6384) we decided that the size tracked in SCM of an EC container is the usedBytes in the first replica or any parity replica. In WritableECContainerProvider, we currently check if there is enough space in the container by comparing the container UsedBytes against the blockSize requested. However the blockSize needs to be divided by the EC DataNum, as it will be stripped across blocks in the group. There was a TODO left in the code to address this decision later:
```
ContainerInfo containerInfo = getContainerFromPipeline(pipeline);
// TODO - For EC, what is the block size? If the client says 128MB,
//        is that 128MB / 6 (for EC-6-3?)
if (containerInfo == null
|| !containerHasSpace(containerInfo, size)) {
// This is O(n), which …
```
=> HDDS-6460. EC: Adjust requested size by EC DataNum in WritableECContainerProvider

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyLocationInfoGroup.java, hadoop-ozone/dist/src/main/compose/upgrade/testlib.sh, hadoop-ozone/dist/src/main/compose/upgrade/upgrades/non-rolling-upgrade/1.1.0-1.2.0/callback.sh, hadoop-ozone/dist/src/main/smoketest/upgrade/generate.robot, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmBlockVersioning.java
- Set new block version to be always 0 when old block versions are cleared (if bucket versioning is disabled), so that OM won't [crash](https://github.com/apache/ozone/blob/ozone-1.1.0/hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java#L80-L82) when overwriting a key if downgraded from 1.3.0 to 1.1.0 while previously having overwritten the same key with 1.3.0 OM (where the last and only key version becomes larger than 0). For more details, see the jira description.
https://issues.apache.org/jira/browse/HDDS-6261
- The existing upgrade test has been slightly modified to repro the issue on my [test branch](https://github.com/smengcl/hadoop-ozone/commits/HDDS-6261-test1) (where this fix is not applied). The repro is …
=> HDDS-6261. OM crashes when trying to overwrite a key during upgrade downgrade testing

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmMultipartKeyInfo.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmMultipartKeyInfo.java, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
Add ECReplicationConfig in `MultipartKeyInfo` proto message and its `OmMultipartKeyInfo` counterpart.
https://issues.apache.org/jira/browse/HDDS-6411
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1997562855
=> HDDS-6411. EC: OmMultipartKeyInfo needs to handle ECReplicationConfig

hadoop-ozone/dist/src/main/compose/testlib.sh
The following warning messages will be removed from the Smoke Tests log:
```
--no-ansi option is deprecated and will be removed in future versions. Use `--ansi never` instead.
```
This is caused by the deprecated option is specified to `docker-compose` in `hadoop-ozone/dist/src/main/compose/testlib.sh`.
https://issues.apache.org/jira/browse/HDDS-6490
```
$ cd hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose
$ script
$ bash ./test-all.sh
$ (CTRL+D to stop script)
$ grep no-ansi typescript
```
=> HDDS-6490. Suppress --no-ansi option is deprecated warnings from Smoke Tests

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/bucket/OMBucketCreateResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/bucket/OMBucketDeleteResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/file/OMFileCreateResponseWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMAllocateBlockResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMAllocateBlockResponseWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyCommitResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyCommitResponseWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyCreateResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyCreateResponseWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyDeleteResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyDeleteResponseWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeysDeleteResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMOpenKeysDeleteResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3MultipartUploadAbortResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3MultipartUploadCommitPartResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3MultipartUploadCompleteResponse.java
The CleanupTableInfo for subclasses of OmKeyResponse is missing some tables.
Especially for the BUCKET_TABLE when bucket usedBytes were updated.
https://issues.apache.org/jira/browse/HDDS-6480
Existing CI
=> HDDS-6480. Add missing CleanupTableInfo to OM responses

hadoop-ozone/dist/src/main/compose/testlib.sh, hadoop-ozone/dist/src/main/smoketest/debug/ozone-debug-corrupt-block.robot, hadoop-ozone/dist/src/main/smoketest/debug/ozone-debug-stale-datanode.robot
Smoketest for `read-replicas` [assumes](https://github.com/apache/ozone/pull/3187#discussion_r825649889) `chunkinfo` and `read-replicas` return datanodes in the same order.  This turned out to be false, causing intermittent failures.
This PR eliminates this assumption, improving the test to not rely on replica order.
https://issues.apache.org/jira/browse/HDDS-6488
Temporarily changed `execute_debug_tests` to corrupt replica=2 instead of replica=0.
Excerpt from `read-replicas` manifest:
```
"replicas": [
{
"hostname": "ozone_datanode_1.ozone_default",
"uuid": "00fab883-5d74-403c-ad54-2d31da07e445"
},
{
"hostname": "ozone_datanode_5.ozone_default",
"uuid": "ff218756-b571-41e9-9d4b-65f79dee30f0"
},
{
"hostname": "ozone_datanode_3.ozone_default",
"uuid": …
```
=> HDDS-6488. Intermittent failure in ozone debug read-replicas with one datanode STALE

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainer.java
* Tests using mini cluster tried to start 3 datanodes with the same fixed port.  Only start one datanode.
* `runTestOzoneContainerViaDataNode` and `testCloseContainer` had leftover assertions after HDDS-5359, which removed delete chunk/block requests
* Disable `testBothGetandPutSmallFile`, which is failing due to HDDS-6473, not a test bug.
https://issues.apache.org/jira/browse/HDDS-6472
50x runs of `TestOzoneContainer`:
https://github.com/adoroszlai/hadoop-ozone/runs/5620046984
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2013240882
=> HDDS-6472. Errors in TestOzoneContainer integration test

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneManagerVersion.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/rpc/RpcClientTest.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/ServiceInfo.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/OzoneClientProducer.java
Change to the new OzoneManagerVersion enum in ServiceInfo message in OM client protocol.
https://issues.apache.org/jira/browse/HDDS-6393
JUnit tests changed to conform the new approach.
=> HDDS-6393. Change the OzoneManager ServiceInfo message to carry the int version from OzoneManagerVersions.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/protocolPB/ContainerCommandResponseBuilders.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainer.java
Fix the bug that `GetSmallFile` response always has empty `data` for V0 request (when reading into a single `ByteBuffer` instead of `ByteBuffer[]`).
https://issues.apache.org/jira/browse/HDDS-6473
```
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 159.229 s - in org.apache.hadoop.ozone.container.ozoneimpl.TestOzoneContainer
```
=> HDDS-6473. Empty data in response for V0 GetSmallFile request

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestSecureOzoneRpcClient.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMetrics.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
This is a simple fix to add a small metric to track amount of data committed into OM. tracking this will help in tracking the amount of write activity in the cluster
https://issues.apache.org/jira/browse/HDDS-6098
Added a new test
=> HDDS-6098. Add a metric to track amount of data committed.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemMissingParent.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystemWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/rooted/ITestRootedOzoneContractRootDir.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestObjectStoreWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
OmMetadataManagerImpl#isBucketEmpty only checks the key table. This means it is possible to delete an FSO bucket that still has data, orphaning the remaining data on the OM.
This patch adds a new code path for File System Optimized buckets. In the case of FSO layout, we check the directory and file tables for any entries that might be present under the said bucket.
In buckets with FSO layout, the metadata entry for a
-  **Top-level directory** would be of the format `<bucket ID>/dirName` inside the `dirTable`.
- **Top-level file** (a file directly placed under the bucket without any sub paths) would be of the format `<bucket ID>/fileName` inside the `fileTable`.
We seek any keys in these tables that begin with the requested bucket's ID - if we find any such entries in the table or the …
=> HDDS-6425. OmMetadataManagerImpl#isBucketEmpty does not work on FSO buckets.

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/HttpServer2.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/S3GatewayHttpServer.java
When checking the JMX or Prometheus or other pages of S3g from browser, the following error was throw from S3g. (From docker container, might be different from local service)
```
2022-03-23 15:32:57,281 [qtp124888672-18] INFO ozone.OmUtils: ozone.om.internal.service.id is not defined, falling back to ozone.om.service.ids to find serviceID for OzoneManager if it is HA enabled cluster
2022-03-23 15:32:57,282 [qtp124888672-18] INFO ozone.OmUtils: No OzoneManager ServiceID configured.
Mar 23, 2022 3:32:57 PM org.glassfish.jersey.internal.Errors logErrors
WARNING: The following warnings have been detected: WARNING: Unknown HK2 failure detected:
MultiException stack 1 of 1
javax.ws.rs.WebApplicationException: User doesn't have the right to access this resource.
```
The reason for this issue is …
=> HDDS-6497. S3gateway throw exception when checking jmx or prom pages from browser

hadoop-hdds/dev-support/checkstyle/checkstyle.xml
Enable `setterCanReturnItsClass` in checkstyle `HiddenField` so it will not yield `'fieldName' hides a field` error in Builders.
For example:
```java
public Builder setVolumeName(String volumeName) { // not allowed before
this.volumeName = volumeName;
return this;
} 
```
https://issues.apache.org/jira/browse/HDDS-6509
Checkstyle
=> HDDS-6509. Checkstyle: Enable setterCanReturnItsClass in HiddenField

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/AbstractDataStreamOutput.java, hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockDataStreamOutput.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ratis/RatisHelper.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/container/ContainerTestHelper.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/KeyValueStreamDataChannel.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockDataStreamOutputEntryPool.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyDataStreamOutput.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockDataStreamOutput.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineStream.java
Optimized the putBlock method of BlockDataStreamOutput
1. PutBlock does not use RaftRpc, but through the stream close() method
```
// putBlock metadata
ByteBuffer buf =
ContainerCommandRequestMessage.toMessage(putBlockRequestProto, null)
.getContent().asReadOnlyByteBuffer();
out.writeAsync(buf, StandardWriteOption.CLOSE); 
```
2.Mark the stream data boundary by sending an empty stream packet
```
// Mark the stream data boundary
out.writeAsync(ByteBuffer.allocateDirect(0).asReadOnlyBuffer()); 
```
3. Flush is also in the form of async RPC, because putBlock needs to fetch bcsId (Raft log index)
https://issues.apache.org/jira/browse/HDDS-6137
Use the existing UT
=> HDDS-6137. [Ozone-Streaming] Optimized the putBlock method of BlockDataStreamOutput

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMDirectoryCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRenameRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMOpenKeysDeleteRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/file/TestOMDirectoryCreateRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/file/TestOMFileCreateRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyRenameRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMOpenKeysDeleteRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/upgrade/TestOMCancelPrepareRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/TestCleanupTableInfo.java
We should pass the bucket layout to the request constructors extending OMKeyRequest, every time we call them.
https://issues.apache.org/jira/browse/HDDS-6499
Unit tests.
=> HDDS-6499. Cleanup OMKeyRequest class constructors.

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockDataStreamOutput.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ratis/RatisHelper.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/storage/ContainerProtocolCalls.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/KeyValueStreamDataChannel.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/StreamDataChannelBase.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/impl/TestKeyValueStreamDataChannel.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockDataStreamOutput.java, pom.xml
Retain the buffers (using [RATIS-1556](https://issues.apache.org/jira/browse/RATIS-1556)) so that the PutBlockRequest can be deserialized when the stream is closed.
https://issues.apache.org/jira/browse/HDDS-6500
New unit tests.
=> HDDS-6500. [Ozone-Streaming] Buffer the PutBlockRequest at the end of the stream.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerData.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/KeyValueContainerUtil.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingService.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeTable.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/SchemaOneDeletedBlocksTable.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestSchemaOneBackwardsCompatibility.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueBlockIterator.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStoreIterator.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBTable.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/Table.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStoreIterator.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBTableStore.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMCertStore.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManagerHelper.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/PrefixParser.java
Add prefix iterator support to RDBTable.
A sample from the `metadata` column family of the current per-container rocksdb instance as follows:
"#BCSID" -> 9
"#BLOCKCOUNT" -> 1
"#BYTESUSED" -> 10240000
After rocksdb-merge, it will be like:
"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0004#BCSID" -> 9
"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0004#BLOCKCOUNT" -> 1
"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0004#BYTESUSED" -> 10240000
Those chars as a prefix are the containerID encoded in IOS-8859-1(An extension of the ASCII charset).
After rocksdb-merge, every container on the disk will get all its metadata KV pairs in a per-disk rocksdb instance.
When we want to access the metadata KV of a specific container, we have to do a `seek` operation in the column family to the right postion. …
=> HDDS-6428. [Merge rocksdb in datanode] Add prefix iterator support to RDBTable.

hadoop-ozone/common/pom.xml, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/GrpcOmTransport.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OmTransportFactory.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java, hadoop-ozone/dist/src/main/license/bin/LICENSE.txt, hadoop-ozone/dist/src/main/license/jar-report.txt, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/ozone-manager/pom.xml, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/GrpcOzoneManagerServer.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestGrpcOzoneManagerServer.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/OzoneClientCache.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/OzoneClientProducer.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/EndpointBase.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/protocolPB/TestGrpcOmTransport.java, pom.xml
…sync with Ozone master containing s3gateway perisistent connection hadoop rpc from HDDS-5881.  This commit also includes functionality to configure omtransport choosiing either hrpc (default) or Grpc OmTransport s3gateway om channel - HDDS-5813.
Support for TLS secured Grpc OmTransport channel between s3gateway, s3g, and the ozone manager, om.  TLS is enabled for the s3g persistent connection between the s3g and the om through the configuration "_**hdds.grpc.tls.enabled**_" boolean.
Included is selection of OmTransport used between s3g and om through configuration "_**ozone.om.transport.class**_", `org.apache.hadoop.ozone.om.protocolPB.Hadoop3OmTransportFactory` (default) or `org.apache.hadoop.ozone.om.protocolPB.GrpcOmTransportFactory`.  Allowing use of Hadoop rpc, hrpc, (HDDS-5581) …
=> HDDS-5545. Enable TLS for GRPC OmTransport implementation

hadoop-ozone/ozonefs-shaded/pom.xml
Relocate Kotlin in shaded Ozone Filesystem jar, to avoid possible version mismatch in downstream projects.
https://issues.apache.org/jira/browse/HDDS-6516
```
$ unzip -t hadoop-ozone/dist/target/ozone-*/share/ozone/lib/ozone-filesystem-hadoop3-*.jar | grep kotlin | head
testing: org/apache/hadoop/ozone/shaded/kotlin/   OK
testing: org/apache/hadoop/ozone/shaded/kotlin/ranges/   OK
testing: org/apache/hadoop/ozone/shaded/kotlin/experimental/   OK
testing: org/apache/hadoop/ozone/shaded/kotlin/comparisons/   OK
testing: org/apache/hadoop/ozone/shaded/kotlin/native/   OK
testing: org/apache/hadoop/ozone/shaded/kotlin/native/concurrent/   OK
testing: org/apache/hadoop/ozone/shaded/kotlin/js/   OK
testing: org/apache/hadoop/ozone/shaded/kotlin/contracts/   OK
testing: …
```
=> HDDS-6516. Shade Kotlin for Ozone Filesystem

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocol.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/protocolPB/StorageContainerLocationProtocolClientSideTranslatorPB.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocolServerSideTranslatorPB.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ContainerOperationClient.java
Pass current version from `ContainerOperationClient` to SCM.  Let SCM use it during datanode details proto conversion, instead of its own current client version.
https://issues.apache.org/jira/browse/HDDS-6429
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1999677055
=> HDDS-6429. getContainerReplicas should respect client version

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerStateManagerIntegration.java
Fix TestContainerStateManagerIntegration:
* Set pipeline limit, as the test assumes single pipeline per datanode (which used to be the default).
* `testReplicaMap` had a consistent `fail()` call, which used to be part of a try-catch block where exception was expected before HDDS-5607.
* Remove two test cases that were testing the same code path as others due to always passing an empty set of excluded container IDs.
* Use a fixed thread pool for `testGetMatchingContainerMultipleThreads`.  It was failing in CI with `unable to create new native thread`, because [`supplyAsync` launches a new thread for each task when parallelism is 1](https://issues.apache.org/jira/browse/RATIS-1497?focusedCommentId=17480241&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-174802 …
=> HDDS-6505. TestContainerStateManagerIntegration consistently fails

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerMetrics.java
Add aggregate metrics such as total number of container moves and total size moved across all the iterations of Container Balancer. Currently, only metrics specific to an iteration are present.
https://issues.apache.org/jira/browse/HDDS-6362
Existing UTs. An integration test or manual testing will be more comprehensive.
=> HDDS-6362. Add aggregate metrics to ContainerBalancerMetrics

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/protocolPB/ContainerCommandResponseBuilders.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/container/ContainerTestHelper.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestHddsDispatcher.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueHandler.java
https://issues.apache.org/jira/browse/HDDS-5963
=> HDDS-5963. Implement ListBlock command

hadoop-ozone/dist/src/main/compose/ozone-ha/docker-config, hadoop-ozone/dist/src/main/compose/ozone-ha/test.sh
To _**re-enable**_ an acceptance test that was disabled in the feature branch for incremental development and PR merges.  Test _**re-enabled**_ is to execute s3 acceptance tests in the `ozone-ha` cluster.  
During the development of the s3-performance Grpc feature branch, s3 acceptance tests for the development clusters were temporarily disabled and re-enabled when the feature supported them (HDDS-5648).  The tests were disabled by commenting out the acceptance test call in the test.sh execution script for the development clusters ie.  `hadoop-ozone/dist/src/main/compose/ozonesecure-ha/test.sh (#execute_robot_test ${SCM} s3).`  - see comments in HDDS-5648 for tests disabled then re-enabled as the feature branch supported the tests.
This PR re-enables the last disabled acceptance test for …
=> HDDS-5648. Track CI workflow tests temporarily disabled for feature branch

hadoop-ozone/pom.xml
Update Spring to 5.2.20 to fix cve-2022-22965 aka Spring4shell.
https://issues.apache.org/jira/browse/HDDS-6538
=> HDDS-6538. Update Spring to 5.2.20 to fix CVE-2022-22965 aka Spring4shell.

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/OMDBUpdateEvent.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/OMDBUpdatesHandler.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestOMDBUpdatesHandler.java
In this change I fixed a bug in Recon. In the OMDBUpdatesHandler class when we process the events, if there were multiple actions on the same key the old value was not correct. The events are iterated upon before the actual Recon's OM copy DB is updated with these set of events. When we set the old value of the event's we set it from the DB, so after the second action the old value wasn't correct. 
I changed it to get the old value from this batch if there were a previous event with the key. I did some refactoring in the TestOMDBUpdatesHandler and added a test case when we operate on the same entry in the same batch. In the OMDBUpdateEvent class I added the table to the hash method, as it was missing from there.  
https://issues.apache.org/jira/browse/HDDS-5119
Added integration tests.
=> HDDS-5119. Recon file count by size page has incorrect data when keys are deleted

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java, hadoop-ozone/integration-test/pom.xml, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientMultipartUploadWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/BucketEndpoint.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/util/S3StorageType.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneBucketStub.java, pom.xml
Handle EC replication in more multipart upload-related code paths.  (Some were already addressed in HDDS-6412 and HDDS-6411.)
https://issues.apache.org/jira/browse/HDDS-6409
Updated integration test `TestOzoneRpcClientAbstract` to run some multipart upload tests with EC replication, too.
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2101125588 (intermittent failure in acceptance secure)
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2098462708 (intermittent failure in acceptance HA)
=> HDDS-6409. EC: OzoneMultipartUpload needs to handle ECReplicationConfig

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestECKeyOutputStream.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java
Updated the repconfig when key already exist.
https://issues.apache.org/jira/browse/HDDS-6434
Added tests.
=> HDDS-6434: EC: Overwriting an EC key with a Ratis key fails

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/ContentGenerator.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OzoneClientKeyGenerator.java
Add an option to createKey via streaming api in Freon via OzoneClientKeyGenerator. 
https://issues.apache.org/jira/browse/HDDS-5666
Tested the command via docker
=> HDDS-5666. Add option to createKey via streaming api in Freon

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/lock/ActiveLock.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/lock/LockManager.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/lock/LockUsageInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/lock/OMLockMetrics.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/lock/OzoneManagerLock.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/lock/TestOzoneManagerLock.java
To provide useful information by exposing write lock waiting, held time metrics to understand OzoneManagerLock timestamp
https://issues.apache.org/jira/browse/HDDS-6436
Added UTs
=> HDDS-6436. Add write lock waiting and held time metrics

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/StateContext.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CommandDispatcher.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteContainerCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/ReplicateContainerCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/endpoint/HeartbeatEndpointTask.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisor.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/TestStateContext.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/states/endpoint/TestHeartbeatEndpointTask.java, hadoop-hdds/interface-server/src/main/proto/ScmServerDatanodeHeartbeatProtocol.proto
To allow SCM to make better decisions about scheduling commands on datanodes, the datanodes should report their current command queue size in the heartbeat. This change adds a section to the heartbeat protobuf message to allow the queued command count for each command type to be reported in each heartbeat.
There will be a count reported for each registered command, with a zero count if the queue is empty.
A follow up change will be needed to use this information on SCM. With this Jira in place, the data will be sent but never used on SCM.
https://issues.apache.org/jira/browse/HDDS-6554
Some new unit tests and existing tests
=> HDDS-6554. Have the datanode heartbeat include queued command counts

hadoop-ozone/s3gateway/pom.xml, pom.xml
Update to latest Jackson to get the fix for CVE-2020-36518.
https://issues.apache.org/jira/browse/HDDS-6552
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2095611064
=> HDDS-6552. Bump Jackson Databind

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/utils/DatanodeStoreCache.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/BlockUtils.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/KeyValueContainerUtil.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestDatanodeStoreCache.java
A new Cache for per-disk db handles after rocksdb-merge.
Originally we have the ContainerCache for per-container db handles.
And we should have a new DatanodeStoreCache for per-disk db handles which should be relatively small.
We could choose whether to use the  DatanodeStoreCache or the ContainerCache according to the schema version in BlockUtils.getDB().
https://issues.apache.org/jira/browse/HDDS-6540
A new UT.
=> HDDS-6540. [Merge rocksdb in datanode] Add a Cache for per-disk DB handles.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/StateContext.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/datanode/RunningDatanodeState.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/endpoint/RegisterEndpointTask.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconNodeManager.java
Currently DN-Recon and DN-SCM have same heartbeat interval. The Datanode to Recon heartbeat interval should be independently configurable.
https://issues.apache.org/jira/browse/HDDS-5862
Tested using CI tests.
=> HDDS-5862. Datanode to Recon heartbeat interval independently configurable

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/BucketEndpoint.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/EndpointBase.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/metrics/S3GatewayMetrics.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/metrics/TestS3GatewayMetrics.java
Added Unit Tests for Bucket Endpoint Metrics for S3-Gateway 
https://issues.apache.org/jira/browse/HDDS-6528
Wrote Unit tests for existing metrics 
@jojochuang @aryangupta1998 @siddhantsangwan @adoroszlai
=> HDDS-6528. Adding Unit-Test cases for S3-Gateway Bucket-Endpoint Metrics.

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneManagerVersion.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/protocolPB/ScmBlockLocationProtocolClientSideTranslatorPB.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/pipeline/CreatePipelineSubcommand.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
The change adds a new OzoneManagerVersion against which the clients can check whether the OM is supporting EC or not.
Added check for replication config arguments in the relevant requests/commands to ensure we do not send an ECReplicationFactor instance to a cluster that does not have support for it.
The affected mutations: CreateKey, CreateFile, CreateBucket, SetBucketProperty, InitiateMultipartUpload.
These 5 places are enough as later on the replication config supplied in those are used passed and used between the client and the server.
https://issues.apache.org/jira/browse/HDDS-6209
Current CI should cover some of the new additions here, some tests may be adjusted as part of this PR later on, but posting this so that the additional production code can already be reviewed.
=> HDDS-6209. EC: [Forward compatibility issue] New client to older server could fail due to the unavailability for client default replication config

hadoop-ozone/ozonefs-hadoop3/src/main/resources/META-INF/services/org.apache.hadoop.security.token.DtFetcher, hadoop-ozone/ozonefs-hadoop3/src/main/resources/META-INF/services/org.apache.hadoop.security.token.TokenIdentifier, hadoop-ozone/ozonefs-hadoop3/src/main/resources/META-INF/services/org.apache.hadoop.security.token.TokenRenewer, hadoop-ozone/ozonefs-shaded/pom.xml, hadoop-ozone/ozonefs/src/main/resources/META-INF/services/org.apache.hadoop.security.token.TokenRenewer
Ozone Token Renewer's are implemented in [BasicOzoneClientAdapterImpl.java#L401](https://github.com/apache/ozone/blob/master/hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java#L401) and [BasicRootedOzoneClientAdapterImpl.java#L830](https://github.com/apache/ozone/blob/master/hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java#L830) , which are not present in the ozone-filesystem-hadoop3-*.jar fat jar.
https://issues.apache.org/jira/browse/HDDS-6535
Existing tests and build.
=> HDDS-6535. Ozone TokenRenewer not found

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/container/InfoSubcommand.java, hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/container/TestInfoSubCommand.java
Adds a command line option called --addReplicaDetails to print replica related information for container info command
https://issues.apache.org/jira/browse/HDDS-6579
Fixed an existing test
=> HDDS-6579. Add commandline argument for Container Info command.

hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/tenant/OMTenantCreateRequest.java
This `tenantDefaultPolicyName` field is no longer in-use and didn't get removed in [HDDS-6396](https://issues.apache.org/jira/browse/HDDS-6396).
https://issues.apache.org/jira/browse/HDDS-6575
=> HDDS-6575. [Multi-Tenant] Clean up unused tenantDefaultPolicyName field in CreateTenantRequest protobuf message

hadoop-ozone/recon/pom.xml
Bump Recon's node to latest LTS: https://nodejs.org/en/download/
https://issues.apache.org/jira/browse/HDDS-6593
=> HDDS-6593. Bump node to v16.14.2 for Recon

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/OzoneManagerSnapshotProvider.java
1. Delete the snapshot file which is failed to transfer.
2. Fix the dir where snapshot should be downloaded 
https://issues.apache.org/jira/browse/HDDS-6547
CI
=> HDDS-6547. om snapshot failed file not deleted.

hadoop-hdds/server-scm/src/main/resources/webapps/scm/scm-overview.html
A one-line patch to add the missing header `HEALTHY_READONLY` in SCM Web UI.
https://issues.apache.org/jira/browse/HDDS-6587
=> HDDS-6587. SCM Web UI is not displaying `HEALTHY_READONLY` header in node status

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/dist/src/main/compose/ozonesecure-ha/docker-config, hadoop-ozone/dist/src/main/smoketest/s3/bucketlist.robot, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/bucket/InfoBucketHandler.java
Currently if a bucket is created using S3 API via S3 Gateway, the bucket owner is always set to "s3g" (whoever S3 Gateway authenticated itself as to the Ozone Manager).
```bash
$ ozone sh bucket list /tenant1
[ {
"volumeName" : "s3v",
"name" : "bucket1",
"creationTime" : "2022-04-07T14:51:49.053Z",
"modificationTime" : "2022-04-07T14:51:49.053Z",
"bucketLayout" : "OBJECT_STORE",
"owner" : "s3g",  <---
"link" : false
} ]
```
This bucket owner field should be set to the user behind the accessId (short name) as this should be the intended behavior.
```bash
$ ozone sh bucket list /tenant1
[ {
...
"bucketLayout" : "OBJECT_STORE",
"owner" : "hive", …
```
=> HDDS-6574. Set owner of buckets created via S3 Gateway to actual user rather than `s3g`; print LinkBucket owner field on the client

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsConfigKeys.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/audit/AuditLogger.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/audit/AuditMessage.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/audit/TestOzoneAuditLogger.java
Currently the READ operation are omitted in audit log. This is intentionally configured to avoid the massive logs that could hurt the services' performance.
But in a production cluster, audit logs for both READ and WRITE operations would be valuable when comes to data security and audit. 
This ticket is to add the feature that users can specify the operations that they'd like to exclude in audit log, so that the performance of service and valuable operation logs can both be retained.
https://issues.apache.org/jira/browse/HDDS-6562
unit test
=> HDDS-6562. Exclude specific operations in Audit log

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java
TestRootedOzoneFileSystem fails due to missing cleanup in some tests.
This patch fixed this issue by creating new volume and bucket before each test, and cleaning them after each test.
This problem is hided by HDDS-6095, please check [detailed logs](https://github.com/kaijchen/ozone/runs/6088575259?check_suite_focus=true#step:4:3068) in old CI below.
(P.S. I will revert it next time when repeating CI)
https://issues.apache.org/jira/browse/HDDS-6515
100x TestRootedOzoneFileSystem (old): https://github.com/kaijchen/ozone/actions/runs/2193371915
100x TestRootedOzoneFileSystem (new): https://github.com/kaijchen/ozone/actions/runs/2193660965
=> HDDS-6515. Intermittent failure in TestRootedOzoneFileSystem

.github/workflows/post-commit.yml, hadoop-ozone/dev-support/checks/integration.sh, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerStateManagerIntegration.java
HDDS-6095 included a change to re-run failing integration tests a few times.  It was intended to only repeat flaky tests, but currently applies to all integration tests.  This may hide real problems.
The change in this PR was already included in #3148 (7e4578c), but then reverted (22f4964) for some reason, and it seems I forgot to re-add it.
https://issues.apache.org/jira/browse/HDDS-6471
Regular CI (on top of #3234):
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2043639817
=> HDDS-6471. Only repeat flaky tests
