hadoop-hdds/pom.xml, hadoop-ozone/pom.xml, pom.xml
Please create an issue in ASF JIRA before opening a pull request,
the corresponding JIRA issue number. (e.g. HADOOP-XXXXX. Fix a typo in YYY.)
For more details, please see https://cwiki.apache.org/confluence/display/HADOOP/How+To+Contribute
=> HDDS-2305. Update Ozone to latest ratis snapshot(0.5.0-3f446aa-SNAPSHOT). Contributed by  Mukul Kumar Singh.

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/security/acl/IAccessAuthorizer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmAcls.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/security/acl/TestOzoneNativeAuthorizer.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketDeleteRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMDirectoryCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMAllocateBlockRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyDeleteRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRenameRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/acl/OzoneNativeAuthorizer.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyRequest.java
Reverts apache/hadoop-ozone#24
=> Revert "HDDS 2181. Ozone Manager should send correct ACL type in ACL requests to Authorizer"

pom.xml
Updated ratis.version in pom.xml
https://issues.apache.org/jira/browse/HDDS-2340
Tested that the build succeeds, also verified a failing unit tets works locally, with the patch.
=> HDDS-2340. Updated ratis.version to get latest snapshot.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/DBStoreBuilder.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDBConfiguration.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerDoubleBuffer.java
Turn on Sync flag when doublebuffer commits, the batch commit will be flushed to disk.
https://issues.apache.org/jira/browse/HDDS-2333
Ran docker-compose ozone cluster and ran freon.
=> HDDS-2333. Enable sync option for OM non-HA.

README.md, README.txt, hadoop-ozone/dist/dev-support/bin/dist-layout-stitching
**This is the follow-up PR after reverting #55**
Replace the almost empty README with an Ozone specific one.
https://issues.apache.org/jira/browse/HDDS-2292
:eyes:
=> HDDS-2292. Create Ozone specific README.md to the new hadoop-ozone repository

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/MetadataStoreBuilder.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/RocksDBStore.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/ContainerUtils.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainer.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestHddsDispatcher.java
https://issues.apache.org/jira/browse/HDDS-2363
=> HDDS-2363. Fail to create Ratis container.

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/ObjectStore.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/bucket/AddAclBucketHandler.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/bucket/RemoveAclBucketHandler.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/bucket/SetAclBucketHandler.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/keys/AddAclKeyHandler.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/keys/RemoveAclKeyHandler.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/keys/SetAclKeyHandler.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/volume/AddAclVolumeHandler.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/volume/RemoveAclVolumeHandler.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/volume/SetAclVolumeHandler.java
Add a ```checkAclExist()``` method in ```ObjectStore.java``` and let the method called by ```addAclHandler``` to show the proper messages.
https://issues.apache.org/jira/browse/HDDS-2255
Build and check the message.
=> HDDS-2255. Improve Acl Handler Messages

CONTRIBUTION.md, README.md
Update mailing list information and contact email address, replacing **hdfs-dev** with **ozone-dev** in CONTRIBUTION and README files.
https://issues.apache.org/jira/browse/HDDS-2399
=> HDDS-2399. Update mailing list information.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/report/ReportPublisher.java
Updated the condition for re-scheduling in ReportPublisher
HDDS-2452
=> HDDS-2452: Wrong condition for re-scheduling in ReportPublisher

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/DBProfile.java
https://sonarcloud.io/project/issues?id=hadoop-ozone&issues=AW5md-0AKcVY8lQ4ZsKR&open=AW5md-0AKcVY8lQ4ZsKR
https://issues.apache.org/jira/browse/HDDS-2494
Existing unit tests and clean local build
=> HDDS-2494 Sonar BigDecimal Cleanup

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java
Add explicit return statements to each case branch to fix Sonar warnings.
https://issues.apache.org/jira/browse/HDDS-2483
Ran local unit tests and rat, findbugs, checkstyle.
=> HDDS-2483. Fix Sonar warnings in HddsUtils

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
This continues the list trash feature and adds server side handling for the new command.
https://issues.apache.org/jira/browse/HDDS-2418
New tests will be added on the next PR for the core logic.  
mvn local build, rat, check style and find bugs
=> HDDS-2418 Add the list trash command to the server side handling

hadoop-ozone/insight/src/main/java/org/apache/hadoop/ozone/insight/LogSubcommand.java, hadoop-ozone/insight/src/main/java/org/apache/hadoop/ozone/insight/datanode/RatisInsight.java
Fix sonar issues found in RatisInsight class.
https://issues.apache.org/jira/browse/HDDS-2502
Only syntactic changes.
=> HDDS-2502. Close ScmClient in RatisInsight.

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java
This patch will remove the unused private filed. 
https://issues.apache.org/jira/browse/HDDS-2513
Unit Tests
=> HDDS-2513. Removed unused private field

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/client/HddsClientUtils.java
Change anonymous class based initialization to sonar rule compatible way.
https://issues.apache.org/jira/browse/HDDS-2489
Simple change verified the build succeeds and TestHddsClientUtils passed.
=> HDDS-2489. Change anonymous class based initialization in HddsUtils.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/conf/HddsConfServlet.java
https://issues.apache.org/jira/browse/HDDS-2526
=> HDDS-2526. Sonar : use format specifiers in Log inside HddsConfServlet

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java
This patch will remove the unused method parameter.
https://issues.apache.org/jira/browse/HDDS-2514
Unit Tests
=> HDDS-2514. removed unused method param

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientManager.java
Reorder the modifiers to comply
https://issues.apache.org/jira/browse/HDDS-2546
mvn builds and unit tests
=> HDDS-2546. Reorder the modifiers to comply

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java
Refactored for unnecessary toString
https://issues.apache.org/jira/browse/HDDS-2544
Unit Tests and mvn builds.
=> HDDS-2544. Refactored for unnecessary toString

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java
This patch will fix the sonar issue related to logging message formatting. 
https://issues.apache.org/jira/browse/HDDS-2543
Unit Test and maven build.
=> HDDS-2543. Refactored for log format.

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/keys/GetAclKeyHandler.java
Fixing sonar cloud Warning: Ensure OzoneClient is closed in Ozone Shell handlers
https://issues.apache.org/jira/browse/HDDS-2550
Clean Build and basic smoketest.
=> HDDS-2550. Sonar: OzoneClient should be closed in GetAclKeyHandler

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java
Removing the empty statement. 
https://issues.apache.org/jira/browse/HDDS-2545
mvn and unit test.
=> HDDS-2545. Remove empty statement

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/lease/Lease.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/lease/LeaseCallbackExecutor.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/lease/LeaseManager.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/lease/package-info.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/lease/TestLeaseManager.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/lease/package-info.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/events/EventExecutor.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/events/EventHandler.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/events/EventPublisher.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/events/EventQueue.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/events/EventWatcher.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/events/EventWatcherMetrics.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/events/SingleThreadExecutor.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/events/TypedEvent.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/events/package-info.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/events/EventHandlerStub.java
Fix warnings in `EventQueue` and related classes.
https://issues.apache.org/jira/browse/HDDS-2516
Unit tests, checkstyle, `ozone` acceptance test.
=> HDDS-2516. Code cleanup in EventQueue

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/keys/GetKeyHandler.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/keys/PutKeyHandler.java
1. Ensure input/output streams are closed in `GetKeyHandler` and `PutKeyHandler`
2. Remove unreachable `else` branch (`dataFilePath` is never `null`)
3. Use more generic types (`InputStream`/`OutputStream`)
4. Replace `Boolean.valueOf` with `Boolean.parseBoolean` (avoid unnecessary boxing)
5. Fix typo in overwrite error message (`will` -> `would`)
https://issues.apache.org/jira/browse/HDDS-2580
Tested both `key put` and `key get` on compose-based cluster:
```
$ ozone freon ockg -t 1 -n 1 -p key
...
$ ozone sh key put vol1/bucket1/key/test /etc/passwd
$ ozone sh key get vol1/bucket1/key/test test.txt
$ diff -q test.txt /etc/passwd
$ ozone sh --verbose key put vol1/bucket1/key/verbose /etc/group
Volume Name : vol1
Bucket Name : bucket1
Key Name : key/verbose
File Hash : …
```
=> HDDS-2580. Ensure resources are closed in Get/PutKeyHandler

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
Fix all the issues except the TODO items.
https://issues.apache.org/jira/browse/HDDS-2498
Only syntactic changes, waiting on UT and acceptance runs.
=> HDDS-2498. Fix sonar issues found in StorageContainerManager.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/tracing/TraceAllMethod.java
Sonar cleanup for: https://sonarcloud.io/project/issues?id=hadoop-ozone&issues=AW5md-2WKcVY8lQ4ZsNQ&open=AW5md-2WKcVY8lQ4ZsNQ
https://issues.apache.org/jira/browse/HDDS-2512
Local build, rat, check style, existing unit tests
=> HDDS-2512 Sonar TraceAllMethod NPE Could be Thrown

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/client/HddsClientUtils.java
Removed unused filed
https://issues.apache.org/jira/browse/HDDS-2598
mvn builds
=> HDDS-2598. Remove unused private field "LOG"

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/client/ContainerOperationClient.java
Removed unnecessary toString
https://issues.apache.org/jira/browse/HDDS-2597
mvn builds
=> HDDS-2597. Remove toString() as log calls it implicitly

hadoop-ozone/dist/src/main/smoketest/omha/testOMHA.robot
In one CI run, testOMHA.robot failed because robot framework SSH commands failed. This Jira aims to verify that the command execution succeeds.
https://issues.apache.org/jira/browse/HDDS-2454
acceptance test - smoketest/omha/testOMHA.robot
=> HDDS-2454. Improve OM HA robot tests.

pom.xml
Reverts apache/hadoop-ozone#251
=> Revert "HDDS-2595. Update Ratis version to latest snapshot version"

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/BackgroundPipelineCreator.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestRatisPipelineCreateAndDestroy.java
Make auto creation for RATIS ONE pipeline configurable.
#HDDS-2602
https://issues.apache.org/jira/browse/HDDS-2602
UT 
=> HDDS-2602 Make auto creation for RATIS ONE pipeline configurable.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml
#2635 Minor: Fix typo in HddsConfigKeys/
https://issues.apache.org/jira/browse/HDDS-2635
No test needed.
=> HDDS-2635 Minor:Fix typo in HddsConfigKeys and ozone-default.

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/CommitWatcher.java
https://issues.apache.org/jira/browse/HDDS-2528
Resolves issues reported in CommitWatcher.java
=> HDDS-2528. Sonar : code smell category issues in CommitWatcher

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/pipeline/Pipeline.java
Reverts apache/hadoop-ozone#279
=> Revert "HDDS-2640 Add leaderID information in pipeline list subcommand"

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneHAClusterImpl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMiniOzoneHACluster.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/ozShell/TestOzoneShellHA.java, hadoop-ozone/ozonefs/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsHAURLs.java
Implement MiniOzoneHAClusterImpl#getOMLeader
https://issues.apache.org/jira/browse/HDDS-2455
1. Added a new test class
2. Ran the two previous unit tests that I have changed to use the new method, both passed: `TestOzoneFsHAURLs#testWithQualifiedDefaultFS` and `TestOzoneShellHA#testOzoneShCmdURIs`.
=> HDDS-2455. Implement MiniOzoneHAClusterImpl#getOMLeader

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java, hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BufferPool.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChunkBuffer.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChunkBufferImplWithByteBuffer.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/IncrementalChunkBuffer.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/common/TestChunkBuffer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestCommitWatcher.java
See https://issues.apache.org/jira/browse/HDDS-2386
=> HDDS-2386. Implement incremental ChunkBuffer.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/SCMPipelineManager.java
Sonar fix for https://sonarcloud.io/project/issues?id=hadoop-ozone&issues=AW6BMuREm2E_7tGaNiTh&open=AW6BMuREm2E_7tGaNiTh
https://issues.apache.org/jira/browse/HDDS-2571
No testing, simple change.
=> HDDS-2571. Handle InterruptedException in SCMPipelineManager

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/client/HddsClientUtils.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestHddsClientUtils.java
https://issues.apache.org/jira/browse/HDDS-2530
refactored method to reduce cognitive complexity score (CC) + 2 other minor Sonar issues.
Added a unit test.
=> HDDS-2530. Sonar : refactor verifyResourceName in HddsClientUtils to fix Sonar errors

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/ContainerKeyService.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/TaskStatusService.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/UtilizationService.java
Fix all sonar issues in package org.apache.hadoop.ozone.recon.api.
https://issues.apache.org/jira/browse/HDDS-2687
Unit testing, checkstyle, SonarLint.
=> HDDS-2687. Fix sonar issues in package org.apache.hadoop.ozone.recon.api.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java
https://issues.apache.org/jira/browse/HDDS-2668
fixes all sonar "code smell" issues in org.apache.hadoop.ozone.container.keyvalue.impl.BlockManagerImpl.java
=> HDDS-2668. Sonar : fix issues reported in BlockManagerImpl

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/pipeline/CreatePipelineSubcommand.java
#HDDS-2650 Fix createPipeline CLI.
https://issues.apache.org/jira/browse/HDDS-2650
CLI ran locally
=> HDDS-2650 Fix createPipeline CLI.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineStateManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/SCMPipelineManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineStateManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestRatisPipelineProvider.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestSimplePipelineProvider.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestRatisPipelineProvider.java
Resolved all Sonar "code smell" category issues in PipelineStateManager.java, including removal of unused parameter 'conf' from the constructor.
https://issues.apache.org/jira/browse/HDDS-2675
existing junits:
TestRatisPipelineProvider.java
TestPipelineStateManager.java
=> HDDS-2675. Sonar : fix issues in PipelineStateManager

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/SCMContainerManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestCloseContainerEventHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestSCMContainerManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestContainerPlacement.java
Fix sonar warnings in SCMContainerManager. The synchronized on pipeline parameter is required for correctness.
https://issues.apache.org/jira/browse/HDDS-2539
No logical modifications made.
=> HDDS-2539. Sonar: Fix sonar warnings in SCMContainerManager class.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/pipeline/Pipeline.java
fixes 3 sonar "code-smell" type issues reported in Pipeline.java. links to the sonar issues captured in the jira.
https://issues.apache.org/jira/browse/HDDS-2669
NA. Only debug log message arguments have been modified.
=> HDDS-2669. Sonar : fix issues in scm Pipeline

hadoop-ozone/dist/dev-support/bin/dist-tar-stitching, hadoop-ozone/dist/pom.xml, pom.xml
Reverts apache/hadoop-ozone#334
=> Revert "HDDS-2704. Source tar file is not created during the relase build"

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntryPool.java
1. Print log only if excludeList is not empty.
2. ExcludeList is initialized from the constructor only, marked it final
https://issues.apache.org/jira/browse/HDDS-2652
Only minimal changes. Build succeeded.
=> HDDS-2652. Remove unnecessary log statement.

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntry.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntryPool.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java
Fixed sonar issues in SCMBlockProtocolServer, BlockOutputStreamEntryPool and KeyOutputStream.
https://issues.apache.org/jira/browse/HDDS-2762
Only refactoring changes. build passed.
=> HDDS-2762. Sonar warnings fixed.

hadoop-ozone/dist/pom.xml, pom.xml
Source tar ball is not generating
https://issues.apache.org/jira/browse/HDDS-2704
Ran the build command, now I see tar ball.
This PR is taken from @elek original PR #334. Thank You @elek for PR.
=> HDDS-2704. Source tar file is not created during the relase build.

hadoop-hdds/docs/themes/ozonedoc/layouts/partials/navbar.html
Fix the wrong source link in ozone docs site
https://issues.apache.org/jira/browse/HDDS-2788
=> HDDS-2788. Fix the wrong source link in docs

hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java, hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientAdapterFactory.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/DatanodeChunkGenerator.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/RandomKeyGenerator.java
Sonarlint fixes for BasicOzoneClientAdapterImpl, OzoneClientAdapterFactory, DatanodeChunkGenerator, RandomKeyGenerator
https://issues.apache.org/jira/browse/HDDS-2787
Verified that the project compiles successfully.
=> HDDS-2787. Use try-with-resources or close resource in finally block

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/genesis/GenesisUtil.java
Save and reuse Random object in GenesisUtil
https://issues.apache.org/jira/browse/HDDS-2552
Verified that the project compiles successfully.
=> HDDS-2552. Sonar: Save and reuse Random object in GenesisUtil

hadoop-ozone/dist/src/main/compose/testlib.sh
`start_docker_env` has a 10-second sleep after environment is up.  I think it was originally added to give SCM a chance to get out of safe mode after all datanodes are up.  Now that acceptance test has a proper `wait_for_safemode_exit` condition, I think the sleep is no longer necessary.
https://issues.apache.org/jira/browse/HDDS-2830
https://github.com/adoroszlai/hadoop-ozone/runs/371306676
=> HDDS-2830. Remove unnecessary sleep in acceptance test

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/x509/SecurityConfig.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java, hadoop-hdds/docs/content/security/SecureOzone.md, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/security/OzoneDelegationTokenSecretManager.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/security/OzoneTokenIdentifier.java, hadoop-ozone/common/src/main/proto/OzoneManagerProtocol.proto, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/TestOzoneDelegationTokenSecretManager.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/AWSV4AuthParser.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/OzoneClientProducer.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/exception/S3ErrorTable.java
Renamed references of S3TOKEN to S3AUTHINFO
https://issues.apache.org/jira/browse/HDDS-2719
Ran project unit tests
=> HDDS-2719. Rename S3Token to S3AuthInfo

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/audit/OMAction.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmMetrics.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMetrics.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
New Metrics for Trash Key Lists and Fails
https://issues.apache.org/jira/browse/HDDS-2484
Updated TestOmMetrics with new metrics
=> HDDS-2484 New Metrics for Trash Key Lists and Fails

pom.xml
Update Ozone to latest ratis snapshot
https://issues.apache.org/jira/browse/HDDS-2835
Made sure the build succeeds and basic freon runs
=> HDDS-2835. update ozone to latest ratis.

hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/bin/start-chaos.sh, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/MiniOzoneLoadGenerator.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/TestMiniChaosOzoneCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/utils/LoadBucket.java
This change proposes to add filesystem tests into MiniOzoneChaosCluster to test the filesystem path along with key api path.
https://issues.apache.org/jira/browse/HDDS-2710
By running MiniOzoneChaosCluster
=> HDDS-2710. Add Filesystem functionality in MiniOzoneChaosCluster.

hadoop-hdds/docs/content/start/OnPrem.zh.md, hadoop-hdds/docs/content/start/_index.zh.md
two markdown files
https://issues.apache.org/jira/browse/HDDS-2727
hugo server -D
=> HDDS-2727. start/OnPrem.md translated to Chinese

hadoop-hdds/docs/content/start/FromSource.zh.md
https://issues.apache.org/jira/browse/HDDS-2740
hugo server -D
=> HDDS-2740. start/FromSource.md translation

hadoop-hdds/docs/content/start/StartFromDockerHub.zh.md, hadoop-hdds/docs/content/start/_index.zh.md
two .md files modifed
https://issues.apache.org/jira/browse/HDDS-2726
hugo server -D
=> HDDS-2726. start/StartFromDockerHub.md translated to Chinese

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerRocksDBLogging.java
Swap positive and negative test cases of RocksDB logging to avoid log messages from finalizer affecting the non-logging case.
https://issues.apache.org/jira/browse/HDDS-2866
Tested locally, as well as on branch with integration tests enabled:
```
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 39.749 s - in org.apache.hadoop.ozone.om.TestOzoneManagerRocksDBLogging
```
https://github.com/adoroszlai/hadoop-ozone/runs/382195722
=> HDDS-2866. Intermittent failure in TestOzoneManagerRocksDBLogging

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OzoneFileStatus.java, hadoop-ozone/common/src/main/proto/OzoneManagerProtocol.proto, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileInterfaces.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java, hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java, hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java, hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/FileStatusAdapter.java, hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/FilteredClassLoader.java
Reverts apache/hadoop-ozone#331.
Due to some issues in handling Hive OrcFileInputFormat in HDDS-2914.
=> Revert "HDDS-2188. Implement LocatedFileStatus & getFileBlockLocations to pro…"

hadoop-hdds/docs/content/start/Kubernetes.zh.md
one new .md file
https://issues.apache.org/jira/browse/HDDS-2733
hugo server -D
=> HDDS-2733. start/Kubernetes.md translated to Chinese

hadoop-hdds/docs/content/start/Minikube.zh.md
(https://issues.apache.org/jira/browse/HDDS-2738
hugo server -D
=> HDDS-2738. start/Minikube.md translated to Chinese

hadoop-hdds/docs/content/shell/_index.zh.md
one markdown file
https://issues.apache.org/jira/browse/HDDS-2741
hugo server -D
=> HDDS-2741. shell/_index.md translation

hadoop-hdds/docs/content/shell/Format.md, hadoop-hdds/docs/content/shell/Format.zh.md
one .md file
https://issues.apache.org/jira/browse/HDDS-2742
hugo server -D
=> HDDS-2742. shell/Format.md translation

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java, hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientManager.java, hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientRatis.java, hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java, hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/CommitWatcher.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ratis/RatisHelper.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientSpi.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntry.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/RatisTestHelper.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/Test2WayCommitInRatis.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStreamWithFailures.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestCloseContainerHandlingByClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestCommitWatcher.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestFailureHandlingByClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestKeyInputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestMultiBlockWritesWithDnFailures.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientRetriesOnException.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestReadRetries.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestWatchForCommit.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestDataValidate.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestOzoneClientKeyGenerator.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestRandomKeyGenerator.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/DatanodeChunkGenerator.java
Reverts apache/hadoop-ozone#472
=> Revert "HDDS-2920. Remove ozone ratis client specific config keys."

hadoop-hdds/docs/content/shell/VolumeCommands.zh.md
one .md file
https://issues.apache.org/jira/browse/HDDS-2743
hugo server -D
=> HDDS-2743. shell/VolumeCommands.md translation

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/utils/CRLCodec.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/utils/TestCRLCodec.java
Added more Unit Tests for CRLCodec
https://issues.apache.org/jira/browse/HDDS-2906
mvn build and unit tests. 
@anuengineer
=> HDDS-2906. Added Unit Test Cases ofr CRLCodec

hadoop-hdds/docs/content/shell/BucketCommands.md
Adding document on bucket creation document with -k option.
https://issues.apache.org/jira/browse/HDDS-2937
hugo server -D
=> HDDS-2937. Document bucket encryption option in shell/BucketCommands.md.

hadoop-hdds/docs/content/interface/_index.zh.md
inteface/_index.md added
https://issues.apache.org/jira/browse/HDDS-2746
hugo server -D
=> HDDS-2746. inteface/_index.md translation

hadoop-hdds/docs/content/interface/JavaApi.zh.md
interface/JavaApi.md added.
https://issues.apache.org/jira/browse/HDDS-2747
hugo server -D
=> HDDS-2747. interface/JavaApi.md

hadoop-hdds/docs/content/interface/OzoneFS.zh.md
interface/OzoneFS.md added
https://issues.apache.org/jira/browse/HDDS-2748
hugo server -D
=> HDDS-2748. interface/OzoneFS.md translation

hadoop-hdds/docs/content/interface/S3.zh.md
interface/S3.zh.md added
https://issues.apache.org/jira/browse/HDDS-2749
hugo server -D
=> HDDS-2749. interface/S3.md translation

hadoop-hdds/docs/content/gdpr/_index.zh.md
gdpr/_index.zh.md added
https://issues.apache.org/jira/browse/HDDS-2758
hugo server -D
=> HDDS-2758. gdpr/_index.md translation

hadoop-hdds/docs/content/concept/_index.zh.md
concept/_index.zh.md added
https://issues.apache.org/jira/browse/HDDS-2789
hugo server -D
=> HDDS-2789. concept/_index.md translation

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java, hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java
Fix root deletion logic.
https://issues.apache.org/jira/browse/HDDS-2973
Added UT in TestOzoneFileSystem
=> HDDS-2973. Fix root deletion logic in delete API.

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java
A fix of a typo in OzoneManagerRatisUtils#createClientRequest.
https://issues.apache.org/jira/browse/HDDS-2892
Ran Maven build.
=> HDDS-2892 Fixed typo in createClientRequest of OzoneManagerRatisUtils

hadoop-hdds/docs/content/gdpr/GDPR in Ozone.zh.md
gdpr/GDPR in Ozone.zh.md
https://issues.apache.org/jira/browse/HDDS-2759
hugo server -D
=> HDDS-2759. gdpr/GDPR in Ozone.md translation

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/DBStoreBuilder.java
1. Reduce log level of "using default/custom profile ..." messages to `debug`.
2. Avoid logging both "default" and "custom" for the same table by refactoring the code.
3. Add constant for `String` version of `DEFAULT_COLUMN_FAMILY`.
https://issues.apache.org/jira/browse/HDDS-2955
Verified log in compose cluster.
with default info level:
```
recon_1     | 2020-01-29 17:14:39,085 [pool-8-thread-1] INFO impl.OzoneManagerServiceProviderImpl: Got new checkpoint from OM : /data/metadata/recon/om.snapshot.db_1580318078998
recon_1     | 2020-01-29 17:14:39,085 [pool-8-thread-1] INFO recovery.ReconOmMetadataManagerImpl: Cleaning up old OM snapshot db at /data/metadata/recon/om.snapshot.db_1580317479076.
recon_1     | 2020-01-29 17:14:39,231 [pool-8-thread-1] INFO …
```
=> HDDS-2955. Unnecessary log messages in DBStoreBuilder

hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java
Fix CI test failure for TestSCMNodeManager.
https://issues.apache.org/jira/browse/HDDS-3007
UT
=> HDDS-3007 Fix CI test failure for TestSCMNodeManager.

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/persistence/JooqPersistenceModule.java
Add system property to suppress the message.
https://issues.apache.org/jira/browse/HDDS-3037
Minor change verified by running unit test.
=> HDDS-3037. Hide self ad jooq message.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/datanode/RunningDatanodeState.java
Cache EndPoint tasks instead of creating them all the time in the class RunningDatanodeState.
https://issues.apache.org/jira/browse/HDDS-2927
This is just a code refactoring change. Existed unit tests can cover this change.
=> HDDS-2927. Cache EndPoint tasks instead of creating them all the time in RunningDatanodeState

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServer.java
Avoid starting Recon in case an exception happens in initialization.
https://issues.apache.org/jira/browse/HDDS-3045
https://github.com/adoroszlai/hadoop-ozone/runs/458192165
=> HDDS-3045. Integration test crashes due to ReconServer NPE

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestMultiBlockWritesWithDnFailures.java
Modified the rpc and watc request timeouts in the test for the client and server.
https://issues.apache.org/jira/browse/HDDS-3016
Ran the unit test to verify.
=> HDDS-3016. Fix TestMultiBlockWritesWithDnFailures.java.

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/bucket/AddAclBucketHandler.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/bucket/GetAclBucketHandler.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/bucket/RemoveAclBucketHandler.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/bucket/SetAclBucketHandler.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/keys/AddAclKeyHandler.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/keys/GetAclKeyHandler.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/keys/RemoveAclKeyHandler.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/keys/SetAclKeyHandler.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/volume/AddAclVolumeHandler.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/volume/GetAclVolumeHandler.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/volume/RemoveAclVolumeHandler.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/volume/SetAclVolumeHandler.java
Improve Ozone Shell ACL operations' help text readability
https://issues.apache.org/jira/browse/HDDS-3057
Compile and run ozone shell ACL commands and manually check the results.
=> HDDS-3057. Improve Ozone Shell ACL operations' help text readability

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
Changed the auditing used in OzoneManager#listStatus from write to read.
https://issues.apache.org/jira/browse/HDDS-3026
Ran Maven build and unit tests.
=> HDDS-3026 Changed auditing in OzoneManager#listStatus to read

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java, hadoop-hdds/container-service/src/main/proto/StorageContainerDatanodeProtocol.proto, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineReportHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/SCMPipelineManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/SCMPipelineMetrics.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/pipeline/TestSCMPipelineBytesWrittenMetrics.java
#HDDS-1590 Aggregate bytesWrite metrics from container to datanode and all the way to SCM.
https://issues.apache.org/jira/browse/HDDS-1590
UT.
Also tested in env:
TYPE scm_pipeline_metrics_num_pipeline_bytes_write_ratis_three_2f0b4887_a6a4_4ab5_ba41_36aa5cfc9056 counter
scm_pipeline_metrics_num_pipeline_bytes_write_ratis_three_2f0b4887_a6a4_4ab5_ba41_36aa5cfc9056{hostname="VM_50_210_centos"} 102400
TYPE scm_pipeline_metrics_num_pipeline_bytes_write_ratis_three_9b3b4890_b347_4e14 …
=> HDDS-1590 Aggregate bytes write metrics from container to datanode and to SCM

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingService.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestDeleteWithSlowFollower.java
Modified to test to use new Delete API. Added configs for rpc and watch timeout for ratis client and server.
https://issues.apache.org/jira/browse/HDDS-3044
Ran and verified the test
=> HDDS-3044. Fix TestDeleteWithSlowFollower.java.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestFailureHandlingByClient.java
Added configs for rpc and watch timeouts for ratis client and server.
https://issues.apache.org/jira/browse/HDDS-3043
Ran the unit test to verify.
=> HDDS-3043. Fix TestFailureHandlingByClient.java.

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/web/ozShell/keys/ListKeyHandler.java
Fix ozone shell description.
https://issues.apache.org/jira/browse/HDDS-2816
Run on docker-compose.
=> HDDS-2816. Fix shell description for --start parameter of listing keys

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java, hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java, hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/OFSPath.java, hadoop-ozone/ozonefs/src/test/java/org/apache/hadoop/fs/ozone/TestOFSPath.java
Fix listStatus continuation in ofs://
https://issues.apache.org/jira/browse/HDDS-3073
Added test `testListStatusRootAndVolumeContinuation`.
=> HDDS-3073. Implement ofs://: Fix listStatus continuation

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/RatisPipelineProvider.java
The RatisPipelineProvider has a ForkJoinPool that is never used anywhere except when it is shutdown.
I suspect it was used previously and then some refactoring has made it redundant and it got left behind.
This jira is to remove that unused code.
https://issues.apache.org/jira/browse/HDDS-3108
Just compiled it and it worked fine. This change only removes dead code so existing tests should cover it.
=> HDDS-3108 Remove unused ForkJoinPool in RatisPipelineProvider

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestHddsDispatcher.java
Clear code issue so fixed the NPE site and added a unit test for the code path.
https://issues.apache.org/jira/browse/HDDS-3115
Added a unit test.
=> HDDS-3115. NPE seen in datanode log as ApplyTransaction failed.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestDataValidate.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestDataValidateWithDummyContainers.java
Remove duplicate test case from `TestDataValidate`.
https://issues.apache.org/jira/browse/HDDS-3092
Ran related tests and checkstyle locally.
=> HDDS-3092. Duplicate large key test

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/EndpointStateMachine.java
Reverts apache/hadoop-ozone#632
=> Revert "HDDS-3124. Fix time interval calculate error"

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/OzoneClientProducer.java, pom.xml
Reverts apache/hadoop-ozone#611
=> Revert "HDDS-3041. Memory leak of s3g"

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsConfigKeys.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/lock/LockManager.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/lock/TestLockManager.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerDoubleBufferWithOMResponse.java
=> HDDS-3118. Possible deadlock in LockManager. (#627)

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/security/acl/OzoneAclConfig.java
https://issues.apache.org/jira/browse/HDDS-3132
=> HDDS-3132. NPE when create RPC client.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/states/ContainerStateMap.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/SCMCLI.java
Changed the exception text.
https://issues.apache.org/jira/browse/HDDS-3075
Verified using docker.
=> HDDS-3075. Fix ScmCli exception message when container not found

hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestDeadNodeHandler.java
Fix issue in TestNodeHandler which was caused due to the race condition between the 3 Factor pipeline creation in SCM, and the explicit opening of all pipelines in the Test.
https://issues.apache.org/jira/browse/HDDS-3100
Ran the test a few times in the IDE and command line.
=> HDDS-3100. Fix TestDeadNodeHandler.

README.md
Fixed some docker startup commands.
https://issues.apache.org/jira/browse/HDDS-3157
No need.
=> HDDS-3157. Fixed docker startup command.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneHAClusterImpl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManagerHA.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconControllerModule.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServer.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconUtils.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/recovery/ReconOmMetadataManagerImpl.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/OzoneManagerServiceProviderImpl.java
Implemented changes proposed in the Jira and added an integration test.
https://issues.apache.org/jira/browse/HDDS-2848
New integration test added.
=> HDDS-2848. Recon changes to make snapshots work with OM HA.

hadoop-hdds/docs/content/beyond/RunningWithHDFS.md, hadoop-hdds/docs/content/beyond/RunningWithHDFS.zh.md, hadoop-hdds/docs/content/gdpr/_index.zh.md
doc
https://issues.apache.org/jira/browse/HDDS-2797
hugo server -D
=> HDDS-2797. beyond/RunningWithHDFS.md translation

hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java, hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java
Get the necessary changes in OFS dev branch after the rebase to master branch. See the description and comments in https://github.com/apache/hadoop-ozone/pull/721
https://issues.apache.org/jira/browse/HDDS-3279
Tested in https://github.com/apache/hadoop-ozone/pull/721
=> HDDS-3279. Rebase OFS branch

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerStateManager.java
Upate allocateContainer not to try creating pipeline every time.
https://issues.apache.org/jira/browse/HDDS-3156
Not needed.
=> HDDS-3156 update allocateContainer to remove additional createPipeline step.

hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/MiniOzoneChaosCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/MiniOzoneDatanodeChaosCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/MiniOzoneLoadGenerator.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/MiniOzoneOMChaosCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/TestMiniChaosOzoneCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/utils/LoadBucket.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneHAClusterImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
This jira proposes to add OzoneManager to MiniOzoneChaosCluster with OzoneHA implementation done. This will help in discovering bugs in Ozone Manager HA
https://issues.apache.org/jira/browse/HDDS-2339
Tested by running chaos cluster locally.
=> HDDS-2339. Add OzoneManager to MiniOzoneChaosCluster

hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/MiniOzoneLoadGenerator.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/loadgenerators/AgedLoadGenerator.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/loadgenerators/DataBuffer.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/loadgenerators/FilesystemLoadGenerator.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/loadgenerators/LoadExecutors.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/loadgenerators/LoadGenerator.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/loadgenerators/ReadOnlyLoadGenerator.java
This jira adds a read only load generator to MiniOzoneChaosCluster.
https://issues.apache.org/jira/browse/HDDS-3320
Tested by running MiniOzoneChaosCluster.
=> HDDS-3320. Add read only based load generator to MiniOzoneChaosCluster.

README.md
… README.md
Specify a more accurate link address(https://issues.apache.org/jira/projects/HDDS/issues) to create an issue in README.md
And fix the Contribution guideline link from ./CONTRIBUTION.md to ./CONTRIBUTING.md
https://issues.apache.org/jira/browse/HDDS-3349
Read it, please.
=> HDDS-3349. Fix two link addresses in README.md

hadoop-hdds/docs/content/tools/AuditParser.zh.md
doc
https://issues.apache.org/jira/browse/HDDS-2802
hugo server -D
=> HDDS-2802. tools/AuditParser.md translation

hadoop-ozone/pom.xml, hadoop-ozone/recon-codegen/pom.xml, hadoop-ozone/recon/pom.xml
Upgraded spring-jdbc due to CVE.
https://issues.apache.org/jira/browse/HDDS-3384
Ran the relevant test with success.
=> HDDS-3384. Update SpringFramework to 5.1.14.

hadoop-ozone/csi/pom.xml, pom.xml
Upgate grpc/netty dependencies in ozone
https://issues.apache.org/jira/browse/HDDS-3398
Ran MiniOzoneChaosCluster test.
=> HDDS-3398. Update grpc/netty dependencies

hadoop-ozone/csi/pom.xml, pom.xml
Reverts apache/hadoop-ozone#840
=> Revert "HDDS-3398. Update grpc/netty dependencies"

pom.xml
Organized log4j dependency
https://issues.apache.org/jira/browse/HDDS-3468
Build  ozone source code.
=> HDDS-3468. Organize log4j dependency in pom.xml.

pom.xml
Update the ratis snapshot version in ozone.
https://issues.apache.org/jira/browse/HDDS-3471
Ran a build.
=> HDDS-3471. Update to latest Ratis Snapshot 0.6.0-490b689-SNAPSHOT.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelinePlacementPolicy.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelinePlacementPolicy.java
Pipeline placement should select lowest load datanode as anchor.
https://issues.apache.org/jira/browse/HDDS-3139
UT
=> HDDS-3139. Pipeline placement should max out pipeline usage

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmBucketInfo.java
Adding bucket encryption key info to bucket create audit log.
https://issues.apache.org/jira/browse/HDDS-3388
Manual testing with the real cluster upon bucket creation.
=> HDDS-3388. Add bucket encryption key info to bucket create audit log.

hadoop-hdds/docs/content/recipe/_index.zh.md
https://issues.apache.org/jira/browse/HDDS-2809
hugo server -D
=> HDDS-2809. recipe/_index.md translation

hadoop-hdds/docs/content/recipe/Prometheus.zh.md
https://issues.apache.org/jira/browse/HDDS-2810
hugo server -D
=> HDDS-2810. recipe/Prometheus.md translation

hadoop-hdds/docs/content/tools/Genconf.zh.md
doc
https://issues.apache.org/jira/browse/HDDS-2801
hugo server -D
=> HDDS-2801. tools/Genconf.md translation

hadoop-hdds/docs/content/tools/TestTools.md, hadoop-hdds/docs/content/tools/TestTools.zh.md
https://issues.apache.org/jira/browse/HDDS-2804
hugo server -D
=> HDDS-2804. tools/TestTools.md

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml
Disabled jaeger tracing by default.
https://issues.apache.org/jira/browse/HDDS-3507
Config change.
=> HDDS-3507. Disable Jaeger tracing by default.

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/ha/OMFailoverProxyProvider.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/ha/TestOMFailoverProxyProvider.java
Consistent DT service name for HA enabled OM setup.
https://issues.apache.org/jira/browse/HDDS-3515
UT added + Real cluster with spark jobs.
=> HDDS-3515. Ensure consistent OM token service field in HA environment.

hadoop-hdds/docs/content/interface/OzoneFS.md, hadoop-hdds/docs/content/interface/OzoneFS.zh.md
Notice that OzoneFileSystem and OzFs are a pair, BasicOzoneFileSystem and BasicOzFs is another pair. 
https://issues.apache.org/jira/browse/HDDS-3495
Just document fix, no need to test.
=> HDDS-3495. Clarify the document of OzoneFs

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/components/AutoReloadPanel/AutoReloadPanel.less, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/components/AutoReloadPanel/AutoReloadPanel.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/constants/autoReload.constants.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/constants/breadcrumbs.constants.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/utils/autoReloadHelper.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/utils/common.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/Datanodes/Datanodes.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/Overview/Overview.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/Pipelines/Pipelines.tsx
- Add ability to auto-reload all the pages
- Add error handling in all the pages
https://issues.apache.org/jira/browse/HDDS-3333
Tested with docker compose.
=> HDDS-3333. Recon UI: All the pages should auto reload

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/ContainerMetadataScanner.java
Fix 2 instances of the sonar lint issues "InterruptedException" in ContainerMetadataScanner.
https://issues.apache.org/jira/browse/HDDS-2567
Compiles successfully without any errors in local.
=> HDDS-2567. Handle InterruptedException in ContainerMetadataScanner

hadoop-hdds/docs/content/concept/Datanodes.md
Fix a typo in Datanodes.md
https://issues.apache.org/jira/browse/HDDS-3634
=> HDDS-3634. Fix a typo in Datanodes.md

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/Table.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketDeleteRequest.java
Introduce a getReadCopy in table method.
Fixed only OMBucketCreateRequest and OMBucketDeleteRequest.
Will file a new Jira to see where all this API can be used in OM.
https://issues.apache.org/jira/browse/HDDS-3623
Tested it on pseudo deployed cluster.
=> HDDS-3623. Implement getReadCopy in Table.

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmMultipartKeyInfo.java, hadoop-ozone/common/src/main/proto/OzoneManagerProtocol.proto, hadoop-ozone/common/src/main/proto/proto.lock, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmKeyInfo.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmMultipartKeyInfo.java
Adding support for FileHandle field in KeyInfo.
https://issues.apache.org/jira/browse/HDDS-3631
Basic Build
=> HDDS-3631. KeyInfo related changes to support fileHandle.

hadoop-hdds/docs/content/shell/KeyCommands.md, hadoop-hdds/docs/content/shell/KeyCommands.zh.md
Add documentation for Cat Key Command
https://issues.apache.org/jira/browse/HDDS-3649
No need, just docs changes.
=> HDDS-3649. Add documentation for Cat Key Command

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMSecurityProtocolServer.java
Handled InterruptedException to address Sonar violations.
Also resolved other sonar violations in this file.
https://issues.apache.org/jira/browse/HDDS-2572
Clean build, checkstyle and sonar in local.
=> HDDS-2572. Handle InterruptedException in SCMSecurityProtocolServer

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/NodeEndpoint.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/DatanodeMetadata.java, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/datanodes/datanodes.tsx
Without this PR, i don't distinguish each datanode when some datanode from same node.
https://issues.apache.org/jira/browse/HDDS-3663
=> HDDS-3663. Display uuid in recon datanode page to distinguish each datanode

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/datanode/RunningDatanodeState.java
Handled InterruptedException and addressed other sonar violations
https://issues.apache.org/jira/browse/HDDS-2563
Clean build, checkstyle, sonar in local.
=> HDDS-2563. Handle InterruptedException in RunningDatanodeState

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/ContainerDataScanner.java
Handled InterruptedException and addressed other Sonar code smells.
https://issues.apache.org/jira/browse/HDDS-2566
Clean build, checkstyle, sonar in local.
=> HDDS-2566. Handle InterruptedException in ContainerDataScanner

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/UniqueId.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ContainerTestHelper.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/genesis/BenchMarkDatanodeDispatcher.java
https://issues.apache.org/jira/browse/HDDS-3633
=> HDDS-3633. Improve UniqueId.next() efficiency.

pom.xml
Update gRPC to 1.29.0
https://issues.apache.org/jira/browse/HDDS-3691
Build works
=> HDDS-3691. Update gRPC to 1.29.0.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/BlockManagerImpl.java
Fix a typo in BlockManagerImpl#allocateBlock.
https://issues.apache.org/jira/browse/HDDS-3690
No need
=> HDDS-3690. Fix a typo in BlockManagerImpl#allocateBlock

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/rooted/ITestRootedOzoneContractCreate.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/rooted/ITestRootedOzoneContractDelete.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/rooted/ITestRootedOzoneContractDistCp.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/rooted/ITestRootedOzoneContractGetFileStatus.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/rooted/ITestRootedOzoneContractMkdir.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/rooted/ITestRootedOzoneContractOpen.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/rooted/ITestRootedOzoneContractRename.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/rooted/ITestRootedOzoneContractRootDir.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/rooted/ITestRootedOzoneContractSeek.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/rooted/RootedOzoneContract.java, hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java
Add OFS contract tests.
https://issues.apache.org/jira/browse/HDDS-2969
By the patch itself.
=> HDDS-2969. Implement ofs://: Add contract test

hadoop-hdds/docs/content/recipe/SparkOzoneFSK8S.zh.md
https://issues.apache.org/jira/browse/HDDS-2811
hugo server -D
=> HDDS-2811. recipe/SparkOzoneFSK8s.md translation

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineFactory.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerV2Impl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelinePlacementPolicy.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineProvider.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineStateManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineStateManagerV2Impl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/RatisPipelineProvider.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/RatisPipelineUtils.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/SCMPipelineManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/SimplePipelineProvider.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/StateManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/MockRatisPipelineProvider.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelieManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineDatanodesIntersection.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineStateManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconPipelineManager.java
Switch to new StateManager for PipelineManager.
https://issues.apache.org/jira/browse/HDDS-3693
UT
=> HDDS-3693 Switch to new StateManager interface.

hadoop-hdds/docs/content/shell/KeyCommands.md, hadoop-hdds/docs/content/shell/KeyCommands.zh.md
Add a documents for cp key command
https://issues.apache.org/jira/projects/HDDS/issues/HDDS-3653
Just documents debt. no need to test
=> HDDS-3653. Add documentation for Copy key command

hadoop-hdds/docs/content/gdpr/_index.md
fix typo in GDPR doc
https://issues.apache.org/jira/browse/HDDS-3708
no need
=> HDDS-3708. fix typo in GDPR doc

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
Handle InterruptedException and also addressed few sonar code smells.
https://issues.apache.org/jira/browse/HDDS-2564
Build works
=> HDDS-2564. Handle InterruptedException in ContainerStateMachine

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/RatisDropwizardExports.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/RatisNameRewriteSampleBuilder.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAMetadataOnly.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, pom.xml
Update Ozone to latest Ratis Snapshot(0.6.0-1720b1f-SNAPSHOT).
https://issues.apache.org/jira/browse/HDDS-3564
Build was successful.
=> HDDS-3564. Update Ozone to latest Ratis Snapshot (0.6.0-3596a58-SNAPSHOT).

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java, hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientRatis.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OzoneAclUtil.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerImpl.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/acl/TestOzoneNativeAuthorizer.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java, hadoop-ozone/ozonefs-hadoop2/pom.xml, hadoop-ozone/ozonefs-hadoop2/src/main/java/org/apache/hadoop/fs/ozone/Hadoop27RpcTransport.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OmKeyGenerator.java
https://issues.apache.org/jira/browse/HDDS-3715
=> HDDS-3715. Improvement for OzoneFS client to work with Hadoop 2.7.3.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/pipeline/Pipeline.java
PR to fix checkstyle issues caused by HDDS-3749.
=> HDDS-3749. Addendum: Fix checkstyle issue.

hadoop-hdds/docs/content/design/ozone-volume-management.md
Add proposed implementation details to Ozone S3 volume mapping design doc.  The primary goal is to be able to discuss it before going forward with big code changes.
https://issues.apache.org/jira/browse/HDDS-3612
Checked preview on GitHub.
=> HDDS-3612. Document details of bucket mount design

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ReplicationManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestReplicationManager.java
1.  increase replication timeout.
2. if datanode is not healthy, remove the replicate action from inflightActions 
https://issues.apache.org/jira/browse/HDDS-3481
Existed tests.
=> HDDS-3481. SCM ask too many datanodes to replicate the same container

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/StorageContainerNodeProtocol.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/container/testutils/ReplicationNodeManagerMock.java
Fix a typo in StorageContainerNodeProtocol#register
https://issues.apache.org/jira/browse/HDDS-3768
No need.
=> HDDS-3768. Fix a typo in StorageContainerNodeProtocol#register

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/exception/S3ErrorTable.java
https://issues.apache.org/jira/browse/HDDS-3772
=> Hdds 3772. Add LOG to S3ErrorTable for easier problem locating. 

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientWithRatis.java
Fix couple test cases that were failing in TestOzoneRpcClientWithRatis
https://issues.apache.org/jira/browse/HDDS-3428
Clean build and acceptance test
=> HDDS-3428. Fix failing test cases in TestOzoneRpcClientWithRatis.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCloseContainerByPipeline.java
Enabled the test as it seems to be stable with latest ratis upgrade.
https://issues.apache.org/jira/browse/HDDS-3263
Manually verified.
=> HDDS-3263. Fix TestCloseContainerByPipeline.java.

hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestSCMRatisResponse.java
Add test for SCMRatisResponse.
https://issues.apache.org/jira/browse/HDDS-3652
UT
=> HDDS-3652 Add test for SCMRatisResponse.

hadoop-hdds/docs/content/security/SecureOzone.zh.md
doc
https://issues.apache.org/jira/browse/HDDS-2765
hugo server -D
=> HDDS-2765. security/SecureOzone.md translation

hadoop-hdds/interface-client/pom.xml, pom.xml
fix typo
https://issues.apache.org/jira/browse/HDDS-3884
Exisitng CI
=> HDDS-3884. Fix typo in pom.xml.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisRequest.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestSCMRatisRequest.java
HDDS-3651 Add tests for SCMRatisRequest.
https://issues.apache.org/jira/browse/HDDS-3651
UT
=> HDDS-3651 Add tests for SCMRatisRequest.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/OneReplicaPipelineSafeModeRule.java
OneReplicaPipelineSafeModeRule class
remove Unnecessary logic
=> HDDS-3888 OneReplicaPipelineSafeModeRule Unnecessary logic

hadoop-hdds/docs/content/design/ofs.md
Add/update OFS user guide `ofs.md`.
https://issues.apache.org/jira/browse/HDDS-3803
No testing necessary.
=> HDDS-3803. [OFS] Add User Guide

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManager.java
Enabling TestStorageContainerManager
https://issues.apache.org/jira/browse/HDDS-3421
Clean build, Unit Test. If anything in CI fails, I will address it.
=> HDDS-3421. Enabling TestStorageContainerManager.

hadoop-hdds/docs/content/interface/OzoneFS.md, hadoop-hdds/docs/content/interface/OzoneFS.zh.md
HDDS-2665 has been merged into the master. Currently, ozone supports ofs, so some ofs  usage needs to be added to Doc.
https://issues.apache.org/jira/browse/HDDS-3891
update doc no need test.
=> HDDS-3891. Add the usage of ofs in doc.

hadoop-ozone/dist/src/main/compose/ozone-csi/docker-config, hadoop-ozone/dist/src/main/compose/ozone-mr/hadoop27/docker-config, hadoop-ozone/dist/src/main/compose/ozone-mr/hadoop31/docker-config, hadoop-ozone/dist/src/main/compose/ozone-mr/hadoop32/docker-config, hadoop-ozone/dist/src/main/compose/ozone-om-ha-s3/docker-config, hadoop-ozone/dist/src/main/compose/ozone-om-ha/docker-config, hadoop-ozone/dist/src/main/compose/ozone-topology/docker-config, hadoop-ozone/dist/src/main/compose/ozone/docker-config, hadoop-ozone/dist/src/main/compose/ozoneblockade/docker-config, hadoop-ozone/dist/src/main/compose/ozones3-haproxy/docker-config, hadoop-ozone/dist/src/main/compose/ozonescripts/docker-config, hadoop-ozone/dist/src/main/compose/ozonesecure-mr/docker-config
For internal acceptance test, which have configured proxy for http, test cases for recon will be affected.
https://issues.apache.org/jira/browse/HDDS-3917
CI
=> HDDS-3917. Add recon to no_proxy of docker-config for acceptance test

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyDeleteRequest.java
Make log message easier to understand.
https://issues.apache.org/jira/browse/HDDS-3929
Trivial change.
=> HDDS-3929. Prettify OMDeleteRequest error log.

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/ObjectStore.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java
Implement getTrashRoots for trash cleanup
https://issues.apache.org/jira/browse/HDDS-3705
Will add a new test.
=> HDDS-3705. [OFS] Implement getTrashRoots for trash cleanup

hadoop-ozone/recon-codegen/src/main/java/org/hadoop/ozone/recon/codegen/JooqCodeGenerator.java
Add system property to hide this self-ad message from the log output.
https://issues.apache.org/jira/browse/HDDS-3932
Check compiled logs.
=> HDDS-3932. Hide jOOQ logo message from the log output on compile

hadoop-hdds/interface-client/src/main/proto/proto.lock, hadoop-ozone/interface-client/src/main/proto/proto.lock
update proto.lock files that were missed in HDDS-426
https://issues.apache.org/jira/browse/HDDS-3939
No testing needed.
=> HDDS-3939. Update proto.lock files

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/pipeline/ListPipelinesSubcommand.java
Remove the redundancy if condition code in ListPipelinesSubcommand
to remove redundancy code in ListPipelinesSubCommand
https://issues.apache.org/jira/browse/HDDS-3747
through CI checks
=> HDDS-3747. Redundancy if condition code in ListPipelinesSubcommand

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java
1. if role is follower, ozone will throw exception.
https://issues.apache.org/jira/browse/HDDS-3861
Existed tests
=> HDDS-3861. Fix handlePipelineFailure throw exception if role is follower

hadoop-ozone/integration-test/src/test/resources/log4j.properties
Remove accidentally added DEBUG log levels.
https://issues.apache.org/jira/browse/HDDS-3967
N/A (yet)
=> HDDS-3967. Remove leftover debug setting

hadoop-hdds/docs/content/security/SecuringTDE.md, hadoop-hdds/docs/content/security/SecuringTDE.zh.md
translation to https://hadoop.apache.org/ozone/docs/0.5.0-beta/security/securingtde.html
https://issues.apache.org/jira/browse/HDDS-2767
hugo server
=> HDDS-2767. security/SecuringTDE.md

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMMXBean.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/main/resources/webapps/scm/scm-overview.html
https://issues.apache.org/jira/browse/HDDS-3923
=> HDDS-3923. Display the safemode status on scm page

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/StorageLocationReport.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/XceiverServerSpi.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/MutableVolumeSet.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainer.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java, hadoop-hdds/interface-server/src/main/proto/ScmServerDatanodeHeartbeatProtocol.proto
Add ratis volume info to  node report
https://issues.apache.org/jira/browse/HDDS-3807
=> HDDS-3807. Propagate raft log disks info to SCM from datanode.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java, pom.xml
Update ratis version to 1.0.0
https://issues.apache.org/jira/browse/HDDS-3813
Existing UT
=> HDDS-3813. Integrate with ratis 1.0.0 release binaries for ozone 0.6.0 release.

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/util/RangeHeader.java
Correct the toString format of RangeHeader
HDDS-3980
No need.
=> HDDS-3980. Correct the toString of RangeHeader

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/volume/CreateVolumeHandler.java
Delete the redundant word of the description
https://issues.apache.org/jira/browse/HDDS-4003
=> HDDS-4003. Delete the redundant word of the description

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java
Generate encryption info for the bucket outside bucket lock
https://issues.apache.org/jira/browse/HDDS-4007
Perf improvement, it is order of code is change.
=> HDDS-4007. Generate encryption info for the bucket outside bucket lock.

hadoop-hdds/docs/content/design/decommissioning.md, hadoop-hdds/docs/content/design/multiraft.md, hadoop-hdds/docs/content/design/ozone-enhancement-proposals.md, hadoop-hdds/docs/content/design/recon2.md, hadoop-hdds/docs/content/design/scmha.md
https://issues.apache.org/jira/browse/HDDS-3973
=> HDDS-3973. Update main feature design status.

hadoop-ozone/ozone-manager/src/main/resources/webapps/ozoneManager/main.html, hadoop-ozone/ozone-manager/src/main/resources/webapps/ozoneManager/om-overview.html, hadoop-ozone/ozone-manager/src/main/resources/webapps/ozoneManager/ozoneManager.js
Add a Status table for OM, after this PR, we can bring more status item to the status table.
HDDS-3905.
=> HDDS-3905. Show status of OM in the OM web ui

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
Fix the definition of dTokenTable.
https://issues.apache.org/jira/browse/HDDS-3511
Just fix definition, so we don't need to add test.
=> HDDS-3511. Fix definition of DelegationTokenTable in OmMetadataManagerImpl

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerRestart.java
Enable and address failure for TestOzoneManagerRestart test cases.
https://issues.apache.org/jira/browse/HDDS-3446
Running TestOzoneManagerRestart case multiple times.
=> HDDS-3446. Enable TestOzoneManagerRestart and address any failure.

hadoop-hdds/interface-server/src/main/proto/proto.lock, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/BlockManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/CloseContainerEventHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAUtils.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisServer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisServerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NewNodeHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NonHealthyToHealthyNodeHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/BackgroundPipelineCreator.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerMXBean.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerV2Impl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/SCMSafeModeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/MockSCMHAManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineActionHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestSCMSafeModeManager.java
Add isLeader check in SCMHAManager.
https://issues.apache.org/jira/browse/HDDS-3837
UT
=> HDDS-3837 Add isLeader check in SCMHAManager.

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OMTransactionInfo.java
To help debugging, It would be helpful to print actual transaction info by toString().
https://issues.apache.org/jira/browse/HDDS-4067
N/A
=> HDDS-4067. Implement toString for OMTransactionInfo

hadoop-hdds/docs/content/interface/CSI.zh.md
Keep the CSI.zh.md consistent with CSI.md
HDDS-4111
No need.
=> HDDS-4111. Keep the CSI.zh.md consistent with CSI.md

hadoop-hdds/docs/content/_index.md, hadoop-hdds/docs/content/concept/OzoneManager.md, hadoop-hdds/docs/content/concept/StorageContainerManager.md, hadoop-hdds/docs/content/feature/Observability.md, hadoop-hdds/docs/themes/ozonedoc/static/css/ozonedoc.css
- Fix logo display in the header
- Fix table display in OM and SCM pages
- Fix typos
https://issues.apache.org/jira/browse/HDDS-4208
This patch was tested by rendering docs in local machine by `hugo serve`.
Before the patch:
After the patch:
=> HDDS-4208. Fix table rendering and logo display in docs

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerImpl.java
Fixed testCheckAccessForFileKey() and testCheckAccessForNonExistentKey().
https://issues.apache.org/jira/browse/HDDS-3441
=> HDDS-3441. Enable TestKeyManagerImpl test cases.

hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java
- Fix flakiness in the test
https://issues.apache.org/jira/browse/HDDS-4150
Tested by running the test several times locally.
=> HDDS-4150. recon.api.TestEndpoints test is flaky

hadoop-hdds/interface-server/src/main/proto/ScmServerDatanodeHeartbeatProtocol.proto
Add current HDDS layout version to DataNode heartbeat/registration
https://issues.apache.org/jira/browse/HDDS-4174
Successful Build
=> HDDS-4174. Add current HDDS layout version to Datanode heartbeat/registration

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestOzoneClientKeyGenerator.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java
Enable TestOzoneClientKeyGenerator.
https://issues.apache.org/jira/browse/HDDS-3297
Tested Manually
Also, test triggered 20 times
https://github.com/aryangupta1998/hadoop-ozone/actions/runs/267051707
=> HDDS-3297. Enable TestOzoneClientKeyGenerator.

hadoop-ozone/dist/src/main/k8s/examples/ozone-dev/csi/csi-provisioner-deployment.yaml, hadoop-ozone/dist/src/main/k8s/examples/ozone/csi/csi-provisioner-deployment.yaml
Improve the emptyDir syntax, from `emptyDir: null` to `emptyDir: {}`
https://issues.apache.org/jira/browse/HDDS-4282
unit tests
=> HDDS-4282. Improve the emptyDir syntax

hadoop-hdds/docs/content/tools/TestTools.md, hadoop-hdds/docs/content/tools/TestTools.zh.md
At present, the link to the Freon introduction document is 0.4.0, and now 1.0 has been released. We no longer need a url of 0.4.0, just need to add a little content to complete it.
https://issues.apache.org/jira/browse/HDDS-4215
update doc no need test.
=> HDDS-4215. update freon doc.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java
Enable TestOMRatisSnapshots.
https://issues.apache.org/jira/browse/HDDS-3966
Also triggered the test 20 times
https://github.com/aryangupta1998/hadoop-ozone/actions/runs/267042410
=> HDDS-3966. Enable TestOMRatisSnapshots.

hadoop-ozone/insight/src/main/java/org/apache/hadoop/ozone/insight/BaseInsightSubCommand.java
The registration of the already implemented insight-point seems to be missing.
https://issues.apache.org/jira/browse/HDDS-4290
```
ozone insight logs -v scm.protocol.heartbeat
```
=> HDDS-4290. Enable insight point for SCM heartbeat protocol

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/upgrade/OMLayoutVersionManagerImpl.java
Fix class scanner initialization such that it does not scan test packages.
https://issues.apache.org/jira/browse/HDDS-4314
Ran integration test without and with the fix.
=> HDDS-4314. OM Layout Version Manager init throws silent CNF error in integration tests.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/protocol/DatanodeDetails.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeAdminMonitorImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NewNodeHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeDecommissionManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeStateManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestDataUtil.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/node/TestDecommissionAndMaintenance.java
Add a series of integration tests to prove decommission works, and that decommission can survive a restart of SCM.
As part of adding these tests, some issues were discover that were fixed in the process of debugging the tests.
https://issues.apache.org/jira/browse/HDDS-4322
New integration tests added
=> HDDS-4322. Add integration tests for Decommission and resolve issues detected by the tests.

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java
Fix s3g met NPE exception while write file by multiPartUpload.
For more detail, please refer to conversions of https://github.com/apache/hadoop-ozone/pull/1228
HDDS-3995
CI
=> HDDS-3995. Fix s3g met NPE exception while write file by multiPartUpload

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeAdminMonitor.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeAdminMonitorImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeDecommissionManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/node/TestDecommissionAndMaintenance.java
Add a series of intergration tests to prove nodes can enter and leave maintenance correctly and address any issues in the code when adding the tests
https://issues.apache.org/jira/browse/HDDS-4323
Added new tests in this PR
=> HDDS-4323. Add integration tests for putting nodes into maintenance and fix any issues uncovered in the tests

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/EndpointStateMachine.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/datanode/RunningDatanodeState.java
In Tencent production environment, after start Recon for a while, we got warnings that all DNs become stale/dead at SCM side. After kill recon, all DNs become healthy in a very short time.
**The root cause is:**
1. EndpointStateMachine for SCM and that for Recon share the thread pool created by DatanodeStateMachine, which is a fixed size thread pool:
```
executorService = Executors.newFixedThreadPool(
getEndPointTaskThreadPoolSize(),
new ThreadFactoryBuilder()
.setNameFormat("Datanode State Machine Task Thread - %d").build());
```
```
private int getEndPointTaskThreadPoolSize() {
// TODO(runzhiwang): current only support one recon, if support multiple
//  recon in future reconServerCount should be the real number of recon
int reconServerCount = 1;
int totalServerCount = reconServerCount; …
```
=> HDDS-4386: Each EndpointStateMachine uses its own thread pool to talk with SCM/Recon

hadoop-hdds/docs/content/feature/Quota.md, hadoop-hdds/docs/content/feature/Quota.zh.md
The space Quota feature is now nearly complete, so add a description of how to use it
https://issues.apache.org/jira/browse/HDDS-3731
no need test
=> HDDS-3731. [doc]add storage space quota document.

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManagerStarter.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerRatisServer.java
Fix compilation and findbugs issue.
https://issues.apache.org/jira/browse/HDDS-4401
Checked the branch commit CI run.
=> HDDS-4401. Fix compilation issue in HDDS-3698-upgrade branch.

hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java, hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/codec/UserVolumeInfoCodec.java, hadoop-ozone/interface-storage/src/main/proto/OmStorageProtocol.proto, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/VolumeManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/codec/OMDBDefinition.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/OMVolumeCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/OMVolumeDeleteRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/OMVolumeRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/OMVolumeSetOwnerRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/volume/OMVolumeCreateResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/volume/OMVolumeDeleteResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/volume/OMVolumeSetOwnerResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/TestOMRequestUtils.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/volume/TestOMVolumeCreateRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/volume/TestOMVolumeSetOwnerRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/volume/TestOMVolumeCreateResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/volume/TestOMVolumeDeleteResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/volume/TestOMVolumeSetOwnerResponse.java
Copy UserVolumeInfo to PersistedUserVolumeInfo in interface-storage
https://issues.apache.org/jira/browse/HDDS-4317
UT
=> HDDS-4317. Copy UserVolumeInfo to PersistedUserVolumeInfo in interface-storage

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/IncrementalContainerReportHandler.java
According to the instructions I replace error to warn.
https://issues.apache.org/jira/browse/HDDS-4420
Ran UTs pass.
=> HDDS-4420. Missing a container shouldn't log message at ERROR level

pom.xml
Bump Jetty version.
https://issues.apache.org/jira/browse/HDDS-4446
Existing tests should cover this change well.
=> HDDS-4446. Update Jetty version to 9.4.34.

hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestReplicationManager.java
Test Fix
https://issues.apache.org/jira/browse/HDDS-4436
Ran test multiple times locally.
=> HDDS-4436.TestReplicationManager#testUnderReplicatedQuasiClosedContainerWithUnhealthyReplica fails intermittently.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogImpl.java
HDDS-4366 also counts transactions belonging to open containers. Although SCM skips these transactions, it still counts them which leads to sending a lower number of transactions to the datanodes.
https://issues.apache.org/jira/browse/HDDS-4438
Tested in a cluster.
=> HDDS-4438. Avoid counting skipped transactions belonging to open containers.

README.md
Fix typo in README.md doc. `side` to `site`.
https://issues.apache.org/jira/browse/HDDS-4455
No need.
=> HDDS-4455. Fix typo in README.md doc

hadoop-hdds/docs/content/feature/Recon.zh.md
I created ZH translation of Recon.md in doc.
https://issues.apache.org/jira/browse/HDDS-4083
I tested the correctness of the document through hugo server.
=> HDDS-4083. Create ZH translation of Recon.md in doc

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/StorageContainerNodeProtocol.java, hadoop-hdds/interface-client/src/main/proto/hdds.proto, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/events/SCMEvents.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeInfo.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeStateManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NonHealthyToReadOnlyHealthyNodeHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/ReadOnlyHealthyToHealthyNodeHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeMetrics.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/states/NodeStateMap.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeHeartbeatDispatcher.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestContainerPlacement.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestStatisticsUpdate.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/container/testutils/ReplicationNodeManagerMock.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/scm/node/TestSCMNodeMetrics.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/ClusterStateEndpoint.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconNodeManager.java
Add DataNode state and transitions for a node going through upgrade
https://issues.apache.org/jira/browse/HDDS-4342
UTs. I will fix any CI failure.
=> HDDS-4342. Add DataNode state and transitions for a node going through upgrade.

hadoop-hdds/docs/content/concept/Containers.zh.md
Create ZH translation of Containers.md in doc.
https://issues.apache.org/jira/browse/HDDS-4079
=> HDDS-4079. Create ZH translation of Containers.md in doc.

.asf.yaml
Change URL on github page to the new TLP domain.
Thanks the report for @cxorm
See #1540 https://github.com/apache/ozone/pull/1540#issuecomment-722217690
https://issues.apache.org/jira/browse/HDDS-4466
Not tested. "Sors bona, nihil aliud" ;-)
=> HDDS-4466. Update url in .asf.yaml to use TLP project

hadoop-hdds/docs/content/feature/HA.zh.md
Fix the parent tag in ZH translation of the HA.md doc.  At the same time, modify the link of `interface/_index.md` to point to its Chinese translation version
https://issues.apache.org/jira/browse/HDDS-4476
Run the /hadoop-hdds/docs/dev-support/bin/generate-site.sh and Passed all unit tests.
=> HDDS-4476. Improve the ZH translation of the HA.md in doc.

pom.xml
Upgrade slf4j to 1.7.30
https://issues.apache.org/jira/browse/HDDS-4528
`mvn clean verify`
=> HDDS-4528. Upgrade slf4j to 1.7.30

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerDataYaml.java, pom.xml
Upgrade snakeyaml to 1.26
https://issues.apache.org/jira/browse/HDDS-4529
`mvn clean verify`
=> HDDS-4529. Upgrade snakeyaml to 1.26

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/upgrade/HDDSLayoutFeatureCatalog.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMOpenKeysDeleteRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/upgrade/ECFeatureOnFinalizeAction.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/upgrade/OMLayoutFeature.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/upgrade/OMLayoutFeatureUtil.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/upgrade/OMLayoutVersionManagerImpl.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/UnsupportedMockNewOMRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/OMMockECKeyCreateRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/upgrade/TestOMVersionManager.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/upgrade/TestOmVersionManagerRequestFactory.java
- Add test to make sure an unsupported OM request is rejected.
- Add test to make sure all new OM requests have the getRequestType method defined.
- Minor code refactor. 
https://issues.apache.org/jira/browse/HDDS-4536
Unit testing.
=> HDDS-4536. Add more unit tests for OM layout version manager.

pom.xml
Upgrade aws-java-sdk to 1.11.901
https://issues.apache.org/jira/browse/HDDS-4547
`mvn clean verify`
=> HDDS-4547. Upgrade aws-java-sdk to 1.11.901

HISTORY.md, README.md, tools/fault-injection-service/README.md
Fix typos in documents
https://issues.apache.org/jira/browse/HDDS-4549
No need
=> HDDS-4549. Fix typos in documents

hadoop-hdds/docs/README.md, hadoop-hdds/docs/content/_index.md, hadoop-hdds/docs/content/_index.zh.md, hadoop-hdds/docs/pom.xml, hadoop-hdds/docs/static/ozone-logo-monochrome.svg, hadoop-hdds/docs/themes/ozonedoc/layouts/partials/header.html, hadoop-hdds/docs/themes/ozonedoc/layouts/partials/navbar.html
Update Ozone documents, replaced "Apache Hadoop Ozone" with "Apache Ozone"
https://issues.apache.org/jira/browse/HDDS-4396
Local Hugo test.
=> HDDS-4396. Ozone TLP - update documents

hadoop-hdds/docs/content/_index.zh.md
Fix homepage text display error.
https://issues.apache.org/jira/browse/HDDS-4555
No test.
=> HDDS-4555. Delete a duplicate character in ZH Docs homepage

hadoop-ozone/pom.xml
Upgrade Spring to latest 5.2 release (5.2.11).
https://issues.apache.org/jira/browse/HDDS-4499
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/379817881
=> HDDS-4499. Upgrade Spring Framework to more recent 5.2

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerData.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/report/ReportPublisher.java
The following is not easy to be quickly understood
```
!(ContainerDataProto.State.INVALID == state); 
```
https://issues.apache.org/jira/browse/HDDS-4572
no need.
=> HDDS-4572. Simplify inequality condition

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineStateManagerV2Impl.java
Add ReadWriteLock into PipelineStateManagerV2Impl to protect contentions between RaftServer and PipelineManager.
If current leader SCM (as leader of term N) steps down while there are on-going transactions, there might be read/write contentions that new leader SCM (as leader of term N+1) has replicated some raft log entries encapsulating method addPipeline()/removePipeline()/updatePipelineState() to the underlying RaftServer that are being applied by StateMachineUpdater, and at the same time PipelineManager is calling getPipelines().
https://issues.apache.org/jira/browse/HDDS-4560
CI
=> HDDS-4560: Add ReadWriteLock into PipelineStateManagerV2Impl to protect contentions between RaftServer and PipelineManager

hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java
https://issues.apache.org/jira/browse/HDDS-4591
=> HDDS-4591. BasicOzoneFileSystem reports StorageUnit class not found.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientRetriesOnException.java
`TestOzoneClientRetriesOnException#testMaxRetriesByOzoneClient` intermittently fails with:
```
testMaxRetriesByOzoneClient(org.apache.hadoop.ozone.client.rpc.TestOzoneClientRetriesOnException)  Time elapsed: 42.789 s  <<< FAILURE!
java.lang.AssertionError: Expected exception not thrown
at org.junit.Assert.fail(Assert.java:88)
at org.apache.hadoop.ozone.client.rpc.TestOzoneClientRetriesOnException.testMaxRetriesByOzoneClient(TestOzoneClientRetriesOnException.java:235)
```
The problem happens if the number of distinct containers used for the key is less than 4.  In this case max number of retries (3) is never reached.
Normal execution:
```
block: conID: 1 locID: 105357240184995843 bcsId: 0
block: conID: 2 locID: 105357240185061380 bcsId: 0
block: conID: 3 locID: 105357240185061381 bcsId: 0 …
```
=> HDDS-4577. Intermittent failure in TestOzoneClientRetriesOnException#testMaxRetriesByOzoneClient

hadoop-hdds/docs/content/security/SecuringOzoneHTTP.md
Modify the document to match the corresponding config keys.
https://issues.apache.org/jira/browse/HDDS-4586
Local hugo
=> HDDS-4586. Mismatch in prefix of DN and SCM http.auth.type config key

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/ContainerUtils.java
Change close container exception logging to debug level.
https://issues.apache.org/jira/browse/HDDS-3701
CI
=> HDDS-3701. Change Close container exception logging to debug in ContainerUtils#logAndReturnError

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/token/BlockTokenVerifier.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/OzoneBlockTokenSecretManager.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/TestOzoneBlockTokenSecretManager.java
Adding read/write access mode check for ozone block token. 
https://issues.apache.org/jira/browse/HDDS-4558
adding unit tests and existing acceptance test.
=> HDDS-4558. Support Ozone block token with access mode check.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
add time unit
https://issues.apache.org/jira/browse/HDDS-4637
no need
=> HDDS-4637. Improve the log infomation when CSM take snapshot

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
Remove redundant log placeholders
https://issues.apache.org/jira/browse/HDDS-4646
unit
=> HDDS-4646. Remove redundant log placeholders

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerStateManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/states/ContainerStateMap.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerV2Impl.java
This dead lock is found when trying to replace the MockRatisServer with single server SCMRatisServer in MiniOzoneCluster.
It can be reproduced by case TestContainerStateMachineFlushDelay#testContainerStateMachineFailures, when replacing the mock ratis server with the real one.
**The root cause is**
when close a pipeline, it will first close the open containers of this pipeline, then remove the pipeline. The contention here is:
1. ContainerManager has committed the log entry that containing updateContainerState, and the StateMachineUpdater is applying this method, waiting for the lock of PipelineManagerV2Impl. Since when a container transitions from open to un-open, it needs to call PipelineManager#removeContainerFromPipeline, thus need the lock of PipelineManagerV2Impl.
2. In …
=> HDDS-4630: Solve deadlock triggered by PipelineActionHandler.

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/SafeModeWaitSubcommand.java
`ozone admin safemode wait` may conclude without actually checking status, if it takes more time to create SCM client than the timeout specified.  This change makes sure at least one check is performed after creating SCM client.
https://issues.apache.org/jira/browse/HDDS-4639
Added `sleep(5000)` in `createScmClient()`.  Executed with cluster already up:
```
$ time ozone admin safemode wait -t 1
SCM is out of safe mode.
real	0m8.302s
user	0m6.327s
sys	0m1.141s
```
and with only SCM running:
```
$ time ozone admin safemode wait -t 1
SCM is in safe mode. No more retries.
Safe mode is not ended within the timeout period.
real	0m8.568s
user	0m5.217s
sys	0m1.047s
```
=> HDDS-4639. Safemode wait may end without checking

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/RatisNameRewriteSampleBuilder.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/http/TestRatisDropwizardExports.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAMetadataOnly.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyDeletingService.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerRatisServer.java, pom.xml
Upgrade ratis to 1.1.0-35f17fa-SNAPSHOT to address incompatible changes
https://issues.apache.org/jira/browse/HDDS-4649
no need to add new ut
=> HDDS-4649. Upgrade ratis to 1.1.0-35f17fa-SNAPSHOT to address incompatible changes

hadoop-hdds/common/pom.xml, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/upgrade/HDDSLayoutFeatureCatalog.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/Storage.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/upgrade/BasicUpgradeFinalizer.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/DataNodeStorageConfig.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/FinalizeNewLayoutVersionCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/upgrade/DataNodeLayoutActionCatalog.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/upgrade/DataNodeLayoutVersionManager.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/upgrade/DataNodeUpgradeAction.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/upgrade/DataNodeUpgradeActionFirstUpgradeVersion.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/upgrade/DataNodeUpgradeFinalizer.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/upgrade/TestDataNodeStartupSlvLessThanMlv.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeProtocolServer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/upgrade/SCMLayoutActionCatalog.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/upgrade/SCMUpgradeAction.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/upgrade/SCMUpgradeActionFirstUpgradeVersion.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/upgrade/SCMUpgradeFinalizer.java
Implement Datanode Finalization
https://issues.apache.org/jira/browse/HDDS-4175
Build/UT. I will address CI failures if any.
=> HDDS-4175. Implement Datanode Finalization.

hadoop-hdds/docs/content/interface/S3.md
fix the typos in the S3.md
https://issues.apache.org/jira/browse/HDDS-4662
only update the content of docs
=> [HDDS-4662] Fix typo in S3.md

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ha/OMHANodeDetails.java
Remove redundant log statement, here are two log statements. should remove one.
https://issues.apache.org/jira/browse/HDDS-4664
no need.
=> HDDS-4664. Remove redundant log statement

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ContainerOperationClient.java
Add authorization check about stopReplicationManager, forceExitSafeMode, startReplicationManager, deactivatePipeline, closePipeline in `SCMClientProtocolServer` .
https://issues.apache.org/jira/browse/HDDS-4530
Add unit test.
=> HDDS-4530. Add authorization check for SCM

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/acl/OMBucketAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/acl/OMBucketAddAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/acl/OMBucketRemoveAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/acl/OMBucketSetAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyAddAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyRemoveAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeySetAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/prefix/OMPrefixAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/prefix/OMPrefixAddAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/prefix/OMPrefixRemoveAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/prefix/OMPrefixSetAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/acl/OMVolumeAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/acl/OMVolumeAddAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/acl/OMVolumeRemoveAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/acl/OMVolumeSetAclRequest.java
https://issues.apache.org/jira/browse/HDDS-4621
=> HDDS-4621. Set, add and remove ACL have no audit logs

hadoop-ozone/dev-support/checks/acceptance.sh, hadoop-ozone/dev-support/checks/blockade.sh, hadoop-ozone/dev-support/checks/kubernetes.sh, pom.xml
=> HDDS-4671. Use mvn to get ozone.version instead of complex shell commands

hadoop-hdds/docs/content/design/decommissioning.md, hadoop-hdds/docs/content/tools/AuditParser.md, hadoop-ozone/dist/src/main/compose/ozone/README.md
Fix several typos in docs
https://issues.apache.org/jira/browse/HDDS-4682
no need
=> HDDS-4682. Fix several typos in docs

hadoop-hdds/docs/dev-support/bin/generate-site.sh
=> HDDS-4671. Use mvn to get ozone.version instead of complex shell commands (addendum)

hadoop-hdds/docs/content/interface/S3.zh.md
Translate missing content.
https://issues.apache.org/jira/browse/HDDS-4663
No need.
=> HDDS-4663. Missing "Expose any volume" content in S3.md (ZH Docs)

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/token/BlockTokenVerifier.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/CertificateClient.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DefaultCertificateClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/CertificateClientTestImpl.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/TestOzoneBlockTokenSecretManager.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/TestOzoneManagerBlockToken.java
Adding validity check for the block token verification. 
https://issues.apache.org/jira/browse/HDDS-4571
Adding additional UTs along with existing ones.
=> HDDS-4571. DN handle expired certificates when validate block token.

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/OzoneDelegationTokenSecretManager.java
check signer cert validity before using it to validate tokens
https://issues.apache.org/jira/browse/HDDS-4641
Existing UTs.
=> HDDS-4641. OM handle expired certificate when verify token signature.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/TrashOzoneFileSystem.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/TrashPolicyOzone.java
Fix failing test   when OM Ratis is enabled.
https://issues.apache.org/jira/browse/HDDS-4669
=> HDDS-4669.TestOzoneFileSystem#testTrash() fails when OM Ratis is enabled

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/OzoneQuota.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
Allow Default Space Quota Unit as Bytes.
https://issues.apache.org/jira/browse/HDDS-4721
UT
=> HDDS-4721. Allow Default Space Quota Unit as Bytes

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisRequest.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisResponse.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/io/Codec.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/io/CodecFactory.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/io/EnumCodec.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/io/GeneratedMessageCodec.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/io/ListCodec.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/io/LongCodec.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/io/package-info.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestSCMRatisRequest.java
Support encode and decode ArrayList and Long
HDDS-4695
New unit test added
=> HDDS-4695. Support encode and decode ArrayList and Long.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/upgrade/DataNodeUpgradeFinalizer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/upgrade/TestHDDSUpgrade.java
Added integration test for SCM + Datanodes going through upgrades.
https://issues.apache.org/jira/browse/HDDS-4614
Running the tests.
=> HDDS-4614. Add Integration test for HDDS upgrade: Happy path cases.

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneDirectory.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestObjectStoreV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyDeleteRequestV1.java
Few test cases failing when OM raits enabled to true. Also, delete file was wrongly updated keyName.
https://issues.apache.org/jira/browse/HDDS-4717
Updated existing UT cases.
=> HDDS-4717. Fix TestOzoneFileSystemV1 and TestObjectStoreV1 cases

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/genesis/BenchMarkSCM.java
JIRA: https://issues.apache.org/jira/browse/HDDS-4748
Signed-off-by: Mahendran Mookkiah <mahendran.mookkiah@gmail.com>
SonarQube issue -  https://sonarcloud.io/project/issues?id=hadoop-ozone&issues=AW5md-cWKcVY8lQ4Zr22&open=AW5md-cWKcVY8lQ4Zr22
No JIRA ticket - code improvement contribution
Ran the below command which resulted into success
`mvn -T4 clean install`
=> HDDS-4748. sonarqube issue fix - "static" members should be accessed statically

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java
TestOzoneFileSystem all 4 parameterized iterations are running always with enabledFileSystemPaths=false and omRatisEnabled=false, which is basically due to the wrong init function using @BeforeClass.
https://issues.apache.org/jira/browse/HDDS-4752
Modified TestOzoneFileSystem and verified using this test. 
With this changes, `TestOzoneFileSystem#testTrash` is expected to fail as this case was not running earlier in the build. HDDS-4751 issue is raised to handle the TestOzoneFileSystem#testTrash failure.
=> HDDS-4752. TestOzoneFileSystem is not picking the configured 'Parameters'

CONTRIBUTING.md
Run configurations startup order
NO
=> HDDS-4785. Document run configuration launch order

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/OMAdmin.java
Re-format the error message of om admin getserviceroles.
https://issues.apache.org/jira/browse/HDDS-4098
manual tests
=> HDDS-4098. Improve om admin getserviceroles error message

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmMultipartKeyInfo.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientMultipartUploadV1.java, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/codec/OMDBDefinition.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3InitiateMultipartUploadRequestV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3InitiateMultipartUploadResponseV1.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3InitiateMultipartUploadRequestV1.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3InitiateMultipartUploadResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3InitiateMultipartUploadResponseV1.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3MultipartResponse.java
This task is to implement Initiate multipart upload for a specified key.
https://issues.apache.org/jira/browse/HDDS-4771
Added S3 multipart UT cases.
=> HDDS-4771. [FSO]S3MultiPart: Implement InitiateMultiPartUpload

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconPipelineManager.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestContainerEndpoint.java
TestContainerEndpoint is broken after merging master to HDDS-2823 at Feb.
https://issues.apache.org/jira/browse/HDDS-4800
CI
=> HDDS-4800. Fix TestContainerEndpoint after merging master to HDDS-2823.

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMContainerLocationFailoverProxyProvider.java
For now, `SCMContainerLocationFailoverProxyProvider` first use `ozone.scm.names` to create rpcProxy, if `ozone.scm.names` is not set, it falls back to use `ozone.scm.client.address`. However, it breaks the master's behavior, which directly use `ozone.scm.client.address` to build the rpcProxy.
In `ozone admin --verbose pipeline list --scm unknown-host`, `unknown-host` will be set to `ozone.scm.client.address`, the created rpcProxy will trigger "java.net.UnknownHostException: Invalid host name: "
This Jira https://issues.apache.org/jira/browse/HDDS-4556 and PR https://github.com/apache/ozone/pull/1671  adds a smoketest for `ozonescripts` environment, helps to find this bug.
https://issues.apache.org/jira/browse/HDDS-4806
CI
=> HDDS-4806. Fix misc acceptance test: List pipelines on unknown host

hadoop-hdds/server-scm/dev-support/findbugsExcludeFile.xml, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/MockPipelineManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestSCMSafeModeManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconAsPassiveScm.java
After spotbugs is enabled with HDDS-2195, there are additional issues reported by findbugs. These issues have to fixed.
https://issues.apache.org/jira/browse/HDDS-4797
CI
=> HDDS-4797: Fix findbugs issues after HDDS-2195

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileOps.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemV1.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestReadRetries.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestObjectStoreV1.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/file/TestOMDirectoryCreateRequestV1.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCreateRequestV1.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3InitiateMultipartUploadRequestV1.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/file/TestOMDirectoryCreateResponseV1.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/file/TestOMFileCreateResponseV1.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeyCommitResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeyCreateResponseV1.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3InitiateMultipartUploadResponseV1.java
After spotbugs is enabled with HDDS-2195, there are additional issues reported by findbugs. This task is to fix those cases in the feature branch.
https://issues.apache.org/jira/browse/HDDS-4805
Findbug fix
=> HDDS-4805. [FSO]Fix findbugs issues after HDDS-2195

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/states/ContainerAttribute.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/states/ContainerStateMap.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineStateMap.java
- Check the update state in PipelineStateMap.updatePipelineState
https://issues.apache.org/jira/browse/HDDS-4734
manual test.
=> HDDS-4734. Validate update state in PipelineStateMap.updatePipelineState

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileOps.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientMultipartUploadV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3InitiateMultipartUploadRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3InitiateMultipartUploadRequestV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCommitPartRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCommitPartRequestV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3MultipartUploadCommitPartResponseV1.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartUploadCommitPartRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartUploadCommitPartRequestV1.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3MultipartResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3MultipartUploadCommitPartResponseV1.java
Implemented create and commit upload part file request.
https://issues.apache.org/jira/browse/HDDS-4781
Added UT cases.
=> HDDS-4781. [FSO]S3MultiPart: Implement create and commit upload part file

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/FilePerChunkStrategy.java
- Add comment for code easy to get confused.
https://issues.apache.org/jira/browse/HDDS-4809
No need test, only add comment.
=> HDDS-4809. Add comment to FilePerChunkStrategy for readability

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/RatisUtil.java
https://issues.apache.org/jira/browse/HDDS-4786
UT
=> HDDS-4786. Disable Ratis pre-vote feature in SCM HA

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/RatisUtil.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHANodeDetails.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisServerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMStateMachine.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMStorageConfig.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManager.java
Move ratis initilaization to scm --init phase
https://issues.apache.org/jira/browse/HDDS-4812
Added test.
=> HDDS-4812. Move Ratis group creation to scm --init phase

hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/MiniOzoneChaosCluster.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsHAURLs.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneCluster.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneOMHAClusterImpl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMiniOzoneHACluster.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMiniOzoneOMHACluster.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHA.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAMetadataOnly.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAWithData.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/parser/TestOMRatisLogParser.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneManagerSnapshotProvider.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManagerHA.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestScmAdminHA.java
Rename MiniOzoneHACluster to MiniOzoneOMHACluster
https://issues.apache.org/jira/browse/HDDS-4829
Simple refactoring change.
=> HDDS-4829. Rename MiniOzoneHACluster to MiniOzoneOMHACluster.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientMultipartUploadV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCommitPartRequestV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequestV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3MultipartUploadCompleteResponseV1.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartUploadCompleteRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartUploadCompleteRequestV1.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3MultipartResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3MultipartUploadCompleteResponseV1.java
This task is to implement prefix based FSO for the S3MultipartUploadCompleteRequest. 
https://issues.apache.org/jira/browse/HDDS-4813
Added UT cases
=> HDDS-4813. [FSO]S3Multipart: Implement UploadCompleteRequest

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java, hadoop-hdds/interface-client/dev-support/findbugsExcludeFile.xml, hadoop-hdds/interface-client/pom.xml, hadoop-hdds/interface-client/src/main/proto/InterSCMProtocol.proto, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/InterSCMGrpcClient.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/InterSCMGrpcProtocolService.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/InterSCMGrpcService.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/MockSCMHAManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMDBCheckpointProvider.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMGrpcClient.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMGrpcOutputStream.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMGrpcProtocolService.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMGrpcService.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAConfiguration.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAUtils.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMSnapshotDownloader.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMSnapshotProvider.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMInstallSnapshot.java
Aims to add the transfer rocks db checkpointing functionality for SCM HA.
https://issues.apache.org/jira/browse/HDDS-4773
Added Unit tests
=> HDDS-4773. Add functionality to transfer Rocks db checkpoint from leader to follower

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
https://issues.apache.org/jira/browse/HDDS-4848
=> HDDS-4848. Commit key audit log has inaccurate factor and type.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ReplicationType.java
=> HDDS-4857. Format ReplicationType.java which indentation are confusion

hadoop-ozone/dev-support/intellij/runConfigurations/Datanode2.xml, hadoop-ozone/dev-support/intellij/runConfigurations/Datanode3.xml
Add specific ports to datanode to resolve port conflicts among multiple datanodes.
https://issues.apache.org/jira/browse/HDDS-4871
Manual tests with intellij.
=> HDDS-4871: fix intellij runConfigurations for datanode

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAUtils.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HAUtils.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHANodeDetails.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
This Jira is to fix an issue in removing self ID when building proxy objects to submit requests.
https://issues.apache.org/jira/browse/HDDS-4880
=> HDDS-4880. Fix removing local SCM when submitting request to other SCM.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManagerV2.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconTasks.java
=> HDDS-4884. Fix and enable TestReconTasks.

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/CertificateServer.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/CertificateStore.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/DefaultCAServer.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/authority/MockCAStore.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMCertStore.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/server/TestSCMCertStore.java
This Jira is to implement list certificates based on role.
HDDS-4861 added scm Certs to scmCert Table. In this Jira, listCerts will be modified to list all SCM Certificates for VALID_CERTS.
https://issues.apache.org/jira/browse/HDDS-4874
=> HDDS-4874. [SCM HA Security] Implement listCertificates based on role

hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java
Fix and enable TestEndpoints.java.
https://issues.apache.org/jira/browse/HDDS-4886
Tests re-added
=> HDDS-4886. Fix and enable TestEndpoints.java.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconAsPassiveScm.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/NodeEndpoint.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/DatanodeMetadata.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconNodeManager.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java
Simple change to add Layout version information to Recon datanode info API.
https://issues.apache.org/jira/browse/HDDS-4902
=> HDDS-4902 Add Layout version information to Recon datanode info API.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3InitiateMultipartUploadRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java
https://issues.apache.org/jira/browse/HDDS-4898
=> HDDS-4898. ACL is not inherited on multiupload object

hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/MiniOzoneChaosCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/MiniOzoneLoadGenerator.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/loadgenerators/LoadExecutors.java
Fixes some spelling
https://issues.apache.org/jira/browse/HDDS-4918
=> HDDS-4918. Fix spelling

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientMultipartUploadV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadAbortRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadAbortRequestV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCommitPartRequestV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequestV1.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3MultipartUploadAbortResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3MultipartUploadAbortResponseV1.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3InitiateMultipartUploadRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3InitiateMultipartUploadRequestV1.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartUploadAbortRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartUploadAbortRequestV1.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3MultipartResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3MultipartUploadAbortResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3MultipartUploadAbortResponseV1.java
This task is to implement prefix based FSO for the S3MultipartUploadAbortRequest.
https://issues.apache.org/jira/browse/HDDS-4835
Added UTs.
=> HDDS-4835. [FSO]S3Multipart: Implement UploadAbortRequest

hadoop-ozone/dist/pom.xml, hadoop-ozone/dist/src/main/smoketest/s3/commonawslib.robot
Upgrade `ozone-runner` to newest image with pre-installed `awscli`.
https://issues.apache.org/jira/browse/HDDS-4881
https://github.com/adoroszlai/hadoop-ozone/actions/runs/631673202
=> HDDS-4881. Pre-install awscli in ozone-runner

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/TransactionInfo.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisServerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMStateMachine.java
refactor code in SCMStateMachine.
https://issues.apache.org/jira/browse/HDDS-4922
CI
=> HDDS-4922. refactor code in SCMStateMachine.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/SCMConnectionManager.java
Fix typo.
https://issues.apache.org/jira/browse/HDDS-4972
No test.
=> HDDS-4972. Fix typo in SCMConnectionManager.java

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingService.java
https://issues.apache.org/jira/browse/HDDS-4975
=> HDDS-4975. Refine missing delete block failure log

.github/workflows/post-commit.yml, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/client/ScmClient.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocol.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/SCMConnectionManager.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeInfo.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestHddsVolume.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/protocolPB/StorageContainerLocationProtocolClientSideTranslatorPB.java, hadoop-hdds/interface-admin/src/main/proto/ScmAdminProtocol.proto, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/SCMContainerManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocolServerSideTranslatorPB.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerManagerImpl.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/cli/OzoneAdmin.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ContainerOperationClient.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/container/ListSubcommand.java, hadoop-ozone/dist/src/main/smoketest/admincli/container.robot, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java, hadoop-ozone/interface-storage/src/test/java/org/apache/hadoop/ozone/om/helpers/TestInstanceHelper.java, hadoop-ozone/interface-storage/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmPrefixInfo.java
Back-port HDDS-4911 (List container by container state) to ContainerManagerV2
test whether this commit can pass the CI checks
https://issues.apache.org/jira/browse/HDDS-4968
add new unit test
=>  CI check for HDDS-4968

hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/MiniOzoneChaosCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/OzoneChaosCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/TestAllMiniChaosOzoneCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/TestDatanodeMiniChaosOzoneCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/TestMiniChaosOzoneCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/TestOzoneManagerMiniChaosOzoneCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManagerMiniChaosOzoneCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/failure/Failures.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneHAClusterImpl.java
This jira adds SCM HA to Chaos tests
https://issues.apache.org/jira/browse/HDDS-4899
Added a new chaos test
=> HDDS-4899. Add SCM HA to Chaos tests.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/StateContext.java
- Use for loop only for incremental reports
https://issues.apache.org/jira/browse/HDDS-4824
The original test can validate the correctness already. This update is mainly for code improvement.
=> HDDS-4824. Remove repeated value set of reports in StateContext.addReport

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SequenceIdGenerator.java
We set up the three node SCM HA cluster for test purpose.
From ozone dbug ldb tool, we found that the localIDs are not same accross the three SCM.
**The root cause here is:**
when localId is not set in the sequenceId table, SCM will initialize it to be UniqueId.next(). When setup 3 SCM from scratch, each of them will individually set their localId to be their own UniqueId.next(), thus the sequenceId is diverged from the very beginning.
**Short term solution is:**
make the 3 empty SCM achieve an agreement about the localId.
**Long tem solutos is:**
Check HDDS-5016.
During bootstrap, the new SCM always downloads checkpoint from leader SCM, and replace their own scm.db with that of leader.
**The short term solution is safe:**
upgrade in-memory scm to bypass-ratis scm: not affected.
upgrade …
=> HDDS-5015. localId is not consistent across SCMs when setup a multi node SCM HA cluster.

pom.xml
JIRA: https://issues.apache.org/jira/browse/HDDS-5020
Bump Apache Ratis version to the latest stable 2.0.0 version
Full CI test.
=> HDDS-5020. Bump ratis version to 2.0.0

hadoop-ozone/dist/dev-support/bin/dist-layout-stitching
https://issues.apache.org/jira/browse/HDDS-5024
=> HDDS-5024. Remove empty share/hadoop directory in dist package.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SequenceIdGenerator.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestSequenceIDGenerator.java
Remove SequenceIdGenerator#StateManagerImpl
https://issues.apache.org/jira/browse/HDDS-4981
unit test
=> HDDS-4981. Remove SequenceIdGenerator#StateManagerImpl

hadoop-hdds/docs/content/design/nonrolling-upgrade.md, hadoop-hdds/docs/content/design/omprepare.md
Add doc pages.
https://issues.apache.org/jira/browse/HDDS-5014
NA
=> HDDS-5014. Add non-rolling upgrade design docs.

.github/workflows/post-commit.yml
Fixing CI build issues related to ozone binary name change
https://issues.apache.org/jira/browse/HDDS-5069
Build/CI run
=> HDDS-5069. Fix issues related to Ozone binary name change

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestRecursiveAclWithFSOBucket.java
Addendum patch to fix compilation error
https://issues.apache.org/jira/browse/HDDS-5072
Existing testsuites.
=> HDDS-5072. [FSO] Addendum patch to fix compilation error

hadoop-hdds/docs/content/feature/OM-HA.zh.md, hadoop-hdds/docs/content/feature/SCM-HA.md, hadoop-hdds/docs/content/feature/SCM-HA.zh.md
Increase translation documents for SCM-HA and OM-HA.
https://issues.apache.org/jira/browse/HDDS-5038
Local test.
=> HDDS-5038. Create and update ZH translation of SCM-HA.md and OM-HA.md in doc

hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/docs/content/feature/PrefixFSO.md, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java, hadoop-ozone/dist/src/main/compose/ozone/docker-compose.yaml, hadoop-ozone/dist/src/main/compose/ozone/test.sh
Rename layout property value LEGACY to SIMPLE.
https://issues.apache.org/jira/browse/HDDS-5079
Existing test cases.
=> HDDS-5079. [FSO] Rename om metadata layout configuration value LEGACY

hadoop-hdds/docs/content/design/how-to-do-a-nonrolling-upgrade.md, hadoop-hdds/docs/content/design/omprepare.md, hadoop-hdds/docs/content/design/upgrade-dev-primer.md
More docs on upgrades.
https://issues.apache.org/jira/browse/HDDS-5014
NA
=> HDDS-5014. Upgrade usage primer documentation.

HISTORY.md
JIRA: https://issues.apache.org/jira/browse/HDDS-5091
As @mukul1987 notified us in #2140 the `HISTORY.md` is not updated recently. I think the two main events since the last update are the first stable release and the project separation to TLP.
I added a paragraph about these events. 
This is a readme change. No test is required just :eye:
=> HDDS-5091. Add project separation and first stable release to the HISTORY.md

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/crl/CRLInfo.java, hadoop-hdds/interface-client/src/main/proto/hdds.proto, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMCertStore.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/server/TestSCMCertStore.java
Include CRL Sequence ID to CRLInfo proto
https://issues.apache.org/jira/browse/HDDS-5117
Unit tests.
=> HDDS-5117. CRLInfo should include CRL Sequence ID

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/container/common/helpers/BlockData.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/BlockUtils.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/helpers/TestBlockData.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueHandlerWithUnhealthyContainer.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestContainerReader.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestSecureOzoneRpcClient.java
https://issues.apache.org/jira/browse/HDDS-4986
=> HDDS-4986. Read failure because of unhealthy container.

hadoop-ozone/dist/src/main/compose/ozonesecure-ha/docker-compose.yaml, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStorageContainerManagerFacade.java
Fix Recon after HDDS-4133
HDDS-4195
Manual Testing
=> HDDS-4195. Fix Recon after HDDS-4133.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/client/ScmClient.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocol.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/upgrade/BasicUpgradeFinalizer.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/upgrade/UpgradeFinalizer.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/protocolPB/StorageContainerLocationProtocolClientSideTranslatorPB.java, hadoop-hdds/interface-admin/src/main/proto/ScmAdminProtocol.proto, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocolServerSideTranslatorPB.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ContainerOperationClient.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OzoneManagerProtocol.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/upgrade/TestHDDSUpgrade.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMUpgradeFinalization.java, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/FinalizationStatusSubCommand.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/FinalizeUpgradeSubCommand.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/OMAdmin.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/scm/FinalizationScmStatusSubcommand.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/scm/FinalizeScmUpgradeSubcommand.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/scm/ScmAdmin.java
Add command to get status of Finalize in OM & SCM
https://issues.apache.org/jira/browse/HDDS-4818
a new ut
manual test
=> HDDS-4818. Add command to get status of Finalize in OM & SCM

hadoop-ozone/dist/src/main/compose/upgrade/compose/ha/docker-config, hadoop-ozone/dist/src/main/compose/upgrade/compose/non-ha/docker-config
Delete some configurations to solve the NoSuchMethodException problem.
https://issues.apache.org/jira/browse/HDDS-4959
Local upgrade acceptance test pass.
=> HDDS-4959. NoSuchMethodException when wrapping RpcException on downgrade

hadoop-ozone/dist/src/main/license/bin/LICENSE.txt, hadoop-ozone/dist/src/main/license/bin/licenses/LICENSE-org.aspectj.html, hadoop-ozone/dist/src/main/license/bin/licenses/LICENSE-org.reflections-reflections.txt
Update licenses for non-rolling upgrade new dependencies.
https://issues.apache.org/jira/browse/HDDS-5137
lincense files only, no test.
=> HDDS-5137. Update licenses for non-rolling upgrade new dependencies.

README.md
Update link of weekly calls in README
https://issues.apache.org/jira/projects/HDDS/issues/HDDS-5177
no need
=> HDDS-5177. Update link of weekly calls

hadoop-ozone/dist/src/main/compose/ozonesecure-ha/docker-config
https://issues.apache.org/jira/browse/HDDS-5040
=> HDDS-5040. Append om1,om2,om3 to ozone.administrators config for secure OM HA docker config

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyAclRequest.java
Now, the modificationTime modified Whether setAcls successful or not.
We should only modify it when setAcl success.
https://issues.apache.org/jira/browse/HDDS-5224
=> HDDS-5224. The modificationTime should modify when setAcl success

NOTICE.txt, hadoop-ozone/dist/src/main/license/bin/NOTICE.txt
Update copyright year in NOTICE.
https://issues.apache.org/jira/browse/HDDS-5229
:eye:
=> HDDS-5229. Update copyright year of NOTICE in all Ozone repositories

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/BaseHttpServer.java
Create http Basedir if not exist
https://issues.apache.org/jira/browse/HDDS-5239
no need to add additional tests
=> HDDS-5239. Create http Basedir if not exist

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java
Fix the TLS configuration for OzoneContainer.
https://issues.apache.org/jira/browse/HDDS-5245
Existing acceptance tests.
=> HDDS-5245. Fix OzoneContainer TLS configuration.

hadoop-ozone/dist/src/shell/ozone/ozone
If noz does not continue to develop, whether we need to delete it?
https://issues.apache.org/jira/browse/HDDS-5261?filter=-2
=> HDDS-5261. Delete Useless ozone subcommand 'noz'

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCommitPartRequest.java
HDDS-5266 Misspelt words in S3MultipartUploadCommitPartRequest.java line 202
https://issues.apache.org/jira/browse/HDDS-5266
=> HDDS-5266 Misspelt words in S3MultipartUploadCommitPartRequest.java line 202

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/datanodes/datanodes.tsx
Fix the sorting of operational state.
https://issues.apache.org/jira/browse/HDDS-5288
Local pnpm test pass.
=> HDDS-5288. Recon UI cannot sort DN by operational state

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMDBCheckpointProvider.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHANodeDetails.java
Add class-level javadoc for SCMDBCheckpointProvider and SCMHANodeDetails.
https://issues.apache.org/jira/projects/HDDS/issues/HDDS-5286
No test.
=> HDDS-5286. Document SCM HA classes

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
Fix minor checkstyle warnings after branch rebase
https://issues.apache.org/jira/browse/HDDS-5320
Existing test cases.
=> HDDS-5320. [FSO] Fix minor checkstyle warnings

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineStateManagerV2Impl.java
Ignored PipelineNotFoundException in updatePipelineState() call.
https://issues.apache.org/jira/browse/HDDS-5284
Exusting tests
=> HDDS-5284. [SCM-HA] SCM start failed with PipelineNotFoundException.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMStateMachine.java
Remove below log added during HDDS-5263 debugging.
LOG.info("bharat starting from sm");
https://issues.apache.org/jira/browse/HDDS-5334
Existing tests. Code is just removing unnecessary log.
=> HDDS-5334. Remove unncessary log added durig HDDS-5263.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeInfo.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeUsage.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestHddsVolume.java
This tries to fix the datanode reserved space calculation, details in the issue description and code comments.
https://issues.apache.org/jira/browse/HDDS-5316
new UTs.
=> HDDS-5316. Fix datanode reserved space calculation.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/BackgroundPipelineCreatorV2.java
If `BackgroundPipelineCreatorV2` tries to trigger one-shot run while pipeline creation is in progress (before entering `wait()`), then its `notifyAll()` call is lost.  This can result in unnecessary wait, as it will only check if it needs to run after the wait is over.
I think this may contribute to tests timing out waiting for SCM safemode exit.
This change adds a simple check for one-shot run flag before entering wait.
https://issues.apache.org/jira/browse/HDDS-5348
Repeated some integration tests that have been failing recently.
10x `TestOzoneManagerConfiguration` and `TestOzoneFileInterfaces`:
https://github.com/adoroszlai/hadoop-ozone/runs/2826594684
10x `TestOzoneManagerHA*`:
https://github.com/adoroszlai/hadoop-ozone/runs/2826131709
Regular CI: …
=> HDDS-5348. Pipeline creator may miss one-shot run

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineStateManagerV2Impl.java
ignore pipeline not found exception during updatePipelineState
https://issues.apache.org/jira/browse/HDDS-5356
Manual test
=> HDDS-5356. [SCM-HA] SCM start failed with PipelineNotFoundException

hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneClient.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmKeyInfo.java, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
Added EcReplicationConfig in KeyInfo and KeyArgs proto structures.
https://issues.apache.org/jira/browse/HDDS-5343
Tested by writing with ECReplicationConfig based key
=> HDDS-5343 : EC: Add ECReplicationConfig into KeyInfo proto.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/fs/AbstractSpaceUsageSource.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/fs/DedicatedDiskSpaceUsage.java
Get more accurate space info for DedicatedDiskSpaceUsage.
https://issues.apache.org/jira/browse/HDDS-5380
manual test.
=> HDDS-5380. Get more accurate space info for DedicatedDiskSpaceUsage.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeConfiguration.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/StorageVolumeChecker.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestPeriodicVolumeChecker.java
Fix skipped volume check due to disk.check.min.gap.
https://issues.apache.org/jira/browse/HDDS-5394
A new ut.
=> HDDS-5394. Fix skipped volume check due to disk.check.min.gap.

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java
Remove unused method parameter "encodedToken".
https://issues.apache.org/jira/projects/HDDS/issues/HDDS-5426
No test.
=> HDDS-5426. Remove unused method parameter in XceiverClientGrpc.java

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisor.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestReplicationSupervisor.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementCapacity.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRackAware.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRandom.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeStatus.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestContainerPlacementFactory.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackAware.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/states/TestNodeStateMap.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/TestContainerReplication.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/TestHelper.java
https://issues.apache.org/jira/browse/HDDS-5296
=> HDDS-5296. Replication Manager should not sent replica command to DN which is not in IN_SERVICE opState 

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
Reverts apache/ozone#2422 for fixing commit message.
=> Revert "[HDDS-5452] Add link method to ContainerStateMachine for Ratis streaming"

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java
https://issues.apache.org/jira/browse/HDDS-5451
=> HDDS-5451. Incorrect PENDINGDELETEBLOCKCOUNT caused by resent command.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ReplicationManager.java
fail move if node is not in IN_SERVICE state
https://issues.apache.org/jira/browse/HDDS-5464
unit test
=> HDDS-5464. fail move if node is not in IN_SERVICE state

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/audit/parser/common/DatabaseHelper.java
Modify Statement to PreparementStatement, prevent SQL injection.
https://issues.apache.org/jira/browse/HDDS-5454?filter=-2
=> HDDS-5454. Modify Statement to PrepareStatement in DatabaseHelper

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/util/ShutdownHookManager.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/stream/StreamingClient.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/stream/StreamingServer.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/HttpServer2.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/HASecurityUtils.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMSnapshotProvider.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMSecurityProtocolServer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/upgrade/SCMUpgradeFinalizer.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/SafeModeWaitSubcommand.java
As described in [HDDS-5434](https://github.com/apache/ozone/pull/2413).
https://issues.apache.org/jira/projects/HDDS/issues/HDDS-5467
No need.
=> HDDS-5467. Handle potential InterruptedException in Ozone

pom.xml
JIRA: https://issues.apache.org/jira/browse/HDDS-5469
Use the recently released Ratis 2.1 instead of previous SNAPSHOT version.
Full CI
=> HDDS-5469. Bump Apache Ratis version to 2.1

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/upgrade/DataNodeUpgradeFinalizer.java
Skip check for UNHEALTHY containers for datanode finalize.
More details in the jira below.
https://issues.apache.org/jira/browse/HDDS-5514
no test
=> HDDS-5514. Skip check for UNHEALTHY containers for datanode finalize.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/BlockManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogImplV2.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/SCMBlockDeletingService.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/ScmBlockDeletingServiceMetrics.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/command/CommandStatusReportHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestDeletedBlockLog.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java
https://issues.apache.org/jira/browse/HDDS-5453
=> HDDS-5453. Add metrics in SCM block deleting service.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerStateManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/states/ContainerQueryKey.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/states/ContainerStateMap.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerStateManagerIntegration.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/genesis/BenchMarkContainerStateMap.java
Continue replacing instances of ReplicationType and Factor with Replication Config in the ContainerStateMap and other impacted classes.
https://issues.apache.org/jira/browse/HDDS-5511
Existing tests
=> HDDS-5511. ContainerStateMap should handle ecReplication config map

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/upgrade/BasicUpgradeFinalizer.java
SKip update firstUpgradeActionLayoutVersion when on-disk layout version is up-to-date.
https://issues.apache.org/jira/browse/HDDS-5515
CI
=> HDDS-5515. SKip update firstUpgradeActionLayoutVersion when on-disk layout version is up-to-date.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneAtRestEncryption.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java
Encrypt data of keys created in linked buckets when source is encrypted bucket.
https://issues.apache.org/jira/browse/HDDS-5530
Added tests.
=> HDDS-5530. Support links to encrypted buckets.

SECURITY.md
Update the supported versions as 1.1.0 released.
https://issues.apache.org/jira/browse/HDDS-5549
No need.
=> HDDS-5549. Add 1.1 to supported versions in security policy

hadoop-hdds/docs/content/security/SecuringTDE.md
Add documentation to access encrypted buckets using S3Gateway.
https://issues.apache.org/jira/browse/HDDS-5508
Doc change, no tests needed
=> HDDS-5508. Add documentation regarding access encrypted buckets from S3G

hadoop-hdds/docs/content/feature/OM-HA.zh.md, hadoop-hdds/docs/content/feature/Quota.zh.md, hadoop-hdds/docs/content/feature/Recon.zh.md, hadoop-hdds/docs/content/feature/SCM-HA.zh.md, hadoop-hdds/docs/content/feature/_index.zh.md
1. retranslation of feature/_index.md
2. minor changes to other Chinese docs under feature for compatibility
https://issues.apache.org/jira/browse/HDDS-5618
hugo server
=> HDDS-5618. feature/_index.zh.md retranslation

hadoop-hdds/docs/content/interface/Ofs.md
Update docs for Ozone FS Trash
https://issues.apache.org/jira/browse/HDDS-5533
`hugo serve ` in hdds/docs
=> HDDS-5533. Update Documentation for Trash

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
add ratis metrics for scm 
https://issues.apache.org/jira/browse/HDDS-5640
CI and local env
[
](url)
=> HDDS-5640. Add scm ratis metrics

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileCreateRequestWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequestWithFSO.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCreateRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCreateRequestWithFSO.java
Use latestVersion config for createKey/createFile.
https://issues.apache.org/jira/browse/HDDS-5393
Existing tests.  (Will add couple more tests)
=> HDDS-5393. Return latest version of key location for client on createKey/createFile

hadoop-hdds/docs/content/interface/ReconApi.md
Add docs for Recon namespace-related REST APIs
https://issues.apache.org/jira/browse/HDDS-5637
No need
[Backlog] Add `zh` doc if needed.
=> HDDS-5637. Add documentation for Recon Namespace REST APIs

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NetworkTopologyImpl.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/net/TestNetworkTopologyImpl.java
https://issues.apache.org/jira/browse/HDDS-5689
=> HDDS-5689. chooseRandom in NetworkTopology should exclude the affinity node too

hadoop-hdds/docs/themes/ozonedoc/layouts/index.html
The layout of the overview interface is different from other interfaces (the content part on the right). 
The purpose of this issue is to maintain a consistent layout.
https://issues.apache.org/jira/browse/HDDS-5667
Hugo serve pass.
=> HDDS-5667. documentation page layout

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeAdminMonitorImpl.java
https://issues.apache.org/jira/browse/HDDS-5700
=> HDDS-5700. Improve LOG message of decommission progress.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/ClosePipelineCommandHandler.java
Skip remove for already removed pipeline.
Logs in the JIRA below.
https://issues.apache.org/jira/browse/HDDS-5726
manual test.
=> HDDS-5726. Skip remove for already removed pipeline.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerSet.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CloseContainerCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerCheck.java
Add logging to show why a container was marked UNHEALTHY.
https://issues.apache.org/jira/browse/HDDS-5699
The patch was tested using CI tests.
https://github.com/aswinshakil/ozone/actions/runs/1183546512
=> HDDS-5699. Added Log to show why a container was marked UNHEALTHY.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ReplicationManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestReplicationManager.java
https://issues.apache.org/jira/browse/HDDS-5708
=> HDDS-5708. Skip sending container close command to unhealthy replica.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/SimpleContainerDownloader.java
https://issues.apache.org/jira/browse/HDDS-5696
=> HDDS-5696. Close grpcReplicationClient on exception.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/client/ScmClient.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocol.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/protocolPB/StorageContainerLocationProtocolClientSideTranslatorPB.java, hadoop-hdds/interface-admin/src/main/proto/ScmAdminProtocol.proto, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocolServerSideTranslatorPB.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ContainerBalancerStartSubcommand.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ContainerOperationClient.java, hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestContainerBalancerSubCommand.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestContainerBalancerOperations.java
add container balancer command line parameters
https://issues.apache.org/jira/browse/HDDS-5729
unit test
=> HDDS-5729. support setting maxSizeEnteringTarget and maxSizeLeavingSource in command line

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineStateMap.java
Fix unresolved compilation problems in PipelineStateMap
https://issues.apache.org/jira/browse/HDDS-5744
this is a typo (syntax error) fix.
=> HDDS-5744. Fix unresolved compilation problems in PipelineStateMap

hadoop-ozone/ozone-manager/pom.xml, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/security/S3GetSecretRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/tenant/OMAssignUserToTenantRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/security/S3GetSecretResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/tenant/OMAssignUserToTenantResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/tenant/OMTenantCreateResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/security/TestS3GetSecretRequest.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/s3/GetS3SecretHandler.java
See https://issues.apache.org/jira/browse/HDDS-5750
=> HDDS-5750. [Multi-Tenant] GetS3Secret should retrieve secret from new tables as well

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NetworkTopology.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NetworkTopologyImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRackAware.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackAware.java
https://issues.apache.org/jira/browse/HDDS-5697
=> HDDS-5697. SCMContainerPlacementRackAware should both affinity nodes before fallback

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/conf/DatanodeRatisServerConfig.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/RatisUtil.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerRatisServer.java
https://issues.apache.org/jira/browse/HDDS-5787
=> HDDS-5787. Provide capability in Ozone to enable ratis pre-vote

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
Removed null fields in Error Message from permission denial by OM.
https://issues.apache.org/jira/browse/HDDS-5863
This patch was manually tested and also with CI tests.
=> HDDS-5863. Error message having null fields on volume creation

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java, hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ECBlockOutputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockOutputStreamEntry.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MockDatanodeStorage.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MockXceiverClientFactory.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MockXceiverClientSpi.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MultiNodePipelineBlockAllocator.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java
Handled node failures. When nodes failed in write, we will get new block group and proceed to write there.
https://issues.apache.org/jira/browse/HDDS-5491
Added tests
=> Hdds 5491: EC: Write should handle node failures.

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestECKeyOutputStream.java
Integrated the codec changes with streams
https://issues.apache.org/jira/browse/HDDS-5874
Existing tests would use this copied codec now. and Tests are passing.
=> HDDS-5874 EC: Integrate the Codec changes into EC Streams.

pom.xml
bump rocksdb version to 6.25.3, which includes may bug-fixe and performance improvement
https://issues.apache.org/jira/browse/HDDS-5945
current ut
=> HDDS-5945. bump rocksdb version to 6.25.3

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerStateManagerImpl.java
ignore deletetransaction when container is not found
https://issues.apache.org/jira/browse/HDDS-5922
no need add more ut
=> HDDS-5922. ignore deletetransaction when container is not found

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestSecureOzoneRpcClient.java
Please see HDDS-5956 description for details.
=> HDDS-5956. Speed up TestOzoneRpcClientAbstract#testZReadKeyWithUnhealthyContainerReplica

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockInputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockReconstructedStripeInputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestECBlockReconstructedStripeInputStream.java
ECBlockReconstructedStripeInputStream needs to support seek like the other streams. This Jira will add it.
https://issues.apache.org/jira/browse/HDDS-5950
New unit tests
=> HDDS-5950. EC: Implement seek on ECBlockReconstructedStripeInputStream

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java
Throwing NIE for flush and cleaned-up the flow.
https://issues.apache.org/jira/browse/HDDS-5953
Added a simple test.
=> HDDS-5953: EC: Review the current flush API and clean up

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerCheck.java
https://issues.apache.org/jira/browse/HDDS-5958
=> HDDS-5958. Refine container scrub log message.

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/BucketLayout.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OzoneFSUtils.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/TrashOzoneFileSystem.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/OMClientRequest.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java
This change refactors usage of bucket types to allow addition of new bucket types later
https://issues.apache.org/jira/browse/HDDS-5981
Existing tests
=> HDDS-5981. Refactor usage of bucket type.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ratis/RatisHelper.java
Add XceiverClientRatis stream config
jira: https://issues.apache.org/jira/browse/HDDS-5987
=> HDDS-5987. [Ozone-Streaming] Add XceiverClientRatis stream config

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/MeasuredReplicator.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisor.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisorMetrics.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestMeasuredReplicator.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ReplicationManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManagerMetrics.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestReplicationManager.java
Capture few more metrics around replication.
https://issues.apache.org/jira/browse/HDDS-5848
Updated unit test.
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1368400919
=> HDDS-5848. Introduce more replication metrics

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystemWithFSO.java
https://issues.apache.org/jira/browse/HDDS-5969
To initialize the TestRootedOzoneFileSystem parameters properly.
=> HDDS-5969. TestRootedOzoneFileSystem parameterized test is not initialized properly

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/util/S3StorageType.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestAbortMultipartUpload.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestInitiateMultipartUpload.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestListParts.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestMultipartUploadComplete.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestMultipartUploadWithCopy.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectDelete.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectGet.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectHead.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectPut.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestPartUpload.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestPermissionCheck.java
Fix s3g create key error in cluster with replication one.
https://issues.apache.org/jira/browse/HDDS-6019
manual test
=> HDDS-6019. Fix s3g create key error in cluster with replication one.

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBColumnFamilyDefinition.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBStoreBuilder.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestDBStoreBuilder.java
Allow to add ColumnFamilyOptions to tables.
https://issues.apache.org/jira/browse/HDDS-5920
a new ut.
=> HDDS-5920. [Merge rocksdb in datanode] Allow to add ColumnFamilyOptions to tables.

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/Freon.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/SCMThroughputBenchmark.java
SCM remote benchmark tool for throughput
3 kinds of test for now:
- allocate block
- allocate container
- process reports
https://issues.apache.org/jira/browse/HDDS-5702
manual test.
=> HDDS-5702. SCM remote benchmark tool.

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManagerStarter.java
As described in [HDDS-5524](https://github.com/apache/ozone/pull/2481).
https://issues.apache.org/jira/projects/HDDS/issues/HDDS-6054
No need.
=> HDDS-6054. Fix resource leak due to OzoneManager.createOm

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManagerUtils.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/OMKeyRequestFactory.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMDirectoryCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMAllocateBlockRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyDeleteRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRenameRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMPathsPurgeRequestWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyAclRequestWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyAddAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyAddAclRequestWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyRemoveAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyRemoveAclRequestWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeySetAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeySetAclRequestWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3InitiateMultipartUploadRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadAbortRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCommitPartRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyAclRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyAclRequestWithFSO.java
This task is to refactor the om request instantiation based on #isFileSystemOptimized() check in OzoneManagerUtils class
https://issues.apache.org/jira/browse/HDDS-6055
Existing test cases
=> HDDS-6055. Refactor isFileSystemOptimized usage in OzoneManagerUtils

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ECBlockOutputStream.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRackScatter.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntry.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockOutputStreamEntry.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestECKeyOutputStream.java
Implemented to handle failure nodes and added to exclude list
https://issues.apache.org/jira/browse/HDDS-5955
Added test to verify the behavior.
=> HDDS-5955: EC: Track the failed servers to add into the excludeList when invoking allocateBlock

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/CloseContainerEventHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ReplicationManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMContext.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestDeadNodeHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStorageContainerManagerFacade.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconPipelineManager.java
Change the sequence of steps during pipeline close to,
1. Close containers
2. Close pipelines
https://issues.apache.org/jira/browse/HDDS-5973
This patch was tested using Unit test and CI tests. 
https://github.com/aswinshakil/ozone/actions/runs/1470167230
=> HDDS-5973. Changed sequence of steps during pipeline close.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/CloseContainerEventHandler.java
Change the cannot close container log message to debug from warn.
[## What is the link to the Apache JIRA]
https://issues.apache.org/jira/browse/HDDS-6059
N/A
=> HDDS-6059. Change Cannot close container log message from WARN to DEBUG

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/DefaultReplicationConfig.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmBucketArgs.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketSetPropertyRequest.java
Added the default replication setting flexibility via SetBucketPropertyRequest. I will raise separate issue to expose this option via CLI.
https://issues.apache.org/jira/browse/HDDS-6020
Added tests.
=> HDDS-6020: EC: Provide set replicationConfig option to bucket

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/RandomKeyGenerator.java
Multi-threaded validator for freon RandomKeyGenerator.
The thread pool size defaults to 1, so it does not change the default behavior, but we could have multiple validator threads if needed.
https://issues.apache.org/jira/browse/HDDS-6046
manual test
We could see that multi-threaded version saves time in validation and do little harm to writes when we have enough system resources.
Single-threaded:
./bin/ozone freon rk --keySize=20971520 --numOfBuckets=1 --numOfVolumes=1 --numOfKeys=10000 --replicationType=RATIS --factor=THREE --numOfThreads=20 --validateWrites
***************************************************
Status: Failed
Git Base Revision: a3b9c37a397ad4188041dd80621bdeefc46885f2
Number of Volumes created: 1
Number of Buckets created: 1
Number of Keys added: 9995
Ratis replication …
=> HDDS-6046. Multi-threaded validator for freon RandomKeyGenerator.

pom.xml
Update log4j to 2.15
HDDS-6085
Run unit test (locally, and with CI)
=> HDDS-6085. Update log4j to 2.15

hadoop-hdds/docs/content/start/OnPrem.md, hadoop-hdds/docs/content/start/OnPrem.zh.md
add description of datanode data dir in Ozone On Premise Installation of Gettting Started
https://issues.apache.org/jira/browse/HDDS-5912
=> HDDS-5912. Add description of hdds.datanode.dir in Getting Started

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/OzoneClientConfig.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockOutputStreamEntry.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MockBlockAllocator.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MockOmTransport.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MockXceiverClientFactory.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MultiNodePipelineBlockAllocator.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/SinglePipelineBlockAllocator.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneClient.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java
On stripe write failures, it will retry.
https://issues.apache.org/jira/browse/HDDS-6036
Added tests to verify the behavior.
=> HDDS-6036: EC: handleStripeFailure should retry

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/RepeatedOmKeyInfo.java, hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/codec/RepeatedOmKeyInfoCodec.java, hadoop-ozone/interface-storage/src/test/java/org/apache/hadoop/ozone/om/codec/TestRepeatedOmKeyInfoCodec.java
See: https://issues.apache.org/jira/browse/HDDS-6129
Existing UT
=> HDDS-6129. OM has thread unsafe issues that can cause OM shutdown.

hadoop-hdds/docs/content/security/SecureOzone.md, hadoop-hdds/docs/content/security/SecureOzone.zh.md
1. Add missing S3G settings.
2. Optimized for ZH document content translation.
https://issues.apache.org/jira/projects/HDDS/issues/HDDS-6118
Local hugo test.
=> HDDS-6118. Documentation missing settings to secure S3g with Kerberos

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ECReplicationConfig.java
Added toString in ECReplicationConfig.
https://issues.apache.org/jira/browse/HDDS-6179
=> HDDS-6179: EC: Provide toString in ECReplicationConfig

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/BackgroundPipelineCreator.java
Skipping for factor ZERO
https://issues.apache.org/jira/browse/HDDS-6180
We should not see the unnecessary log message. and verified by running the SCM.
=> HDDS-6180: EC: Pipeline creator should ignore creating pipelines for ZERO factor

hadoop-hdds/server-scm/pom.xml, hadoop-ozone/integration-test/pom.xml, hadoop-ozone/tools/pom.xml, pom.xml
The jmh-core dependency are not used. We should remove it.
https://issues.apache.org/jira/browse/HDDS-6195
NA
=> HDDS-6195. Remove unused jmh-core dependency.

hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java
Fixed the tests to use a predictable way to mark the nodes fail.
https://issues.apache.org/jira/browse/HDDS-6083
Fixed the tests to avoid flaky behaviors.
=> HDDS-6083: EC: Fix flakyness of tests around nodefailures

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAInvocationHandler.java
Removes a lot of noise from SCM and Recon logs.
https://issues.apache.org/jira/browse/HDDS-6181
No need.
=> HDDS-6181. Change SCMHAInvocationHandler#invokeRatis() logging to TRACE

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/NodeEndpoint.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/DatanodePipeline.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java
Moved away from replication factor and added ReplicationConfig in DatanodePipeline
https://issues.apache.org/jira/browse/HDDS-6272
Modified to test to consider repConfig.
=> HDDS-6272: EC: Recon UI failing because of EC replication factor

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ratis/RatisHelper.java
Add XceiverServerRatis stream config
https://issues.apache.org/jira/browse/HDDS-6298
=> HDDS-6298. Add XceiverServerRatis stream config

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ECReplicationConfig.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/RatisReplicationConfig.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ReplicationConfig.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/StandaloneReplicationConfig.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/client/TestReplicationConfig.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/NodeEndpoint.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/PipelineEndpoint.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/DatanodePipeline.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/PipelineMetadata.java, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/datanodes/datanodes.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/pipelines/pipelines.tsx, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java
Changed the repFactor from int to String
https://issues.apache.org/jira/browse/HDDS-6308
Existing test modified.
=> HDDS-6308: EC: Handle Replication Factor to consider EC Config in Recon UI

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMetrics.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketDeleteRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestOMBucketDeleteRequestWithFSO.java
Added numFSOBucketDeletes metrics to reflect the number of FSO bucket deletion requests.
https://issues.apache.org/jira/browse/HDDS-6328
Added JUnit tests.
=> HDDS-6328. Add metrics - number of FSO bucket deletes

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ECReplicationConfig.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OzoneClientKeyGenerator.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/bucket/CreateBucketHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/keys/PutKeyHandler.java
Update description strings for `--replication` and `--type`.
https://issues.apache.org/jira/browse/HDDS-6232
manual test
=> HDDS-6232. EC: Update help strings for replication config

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestRandomKeyGenerator.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/RandomKeyGenerator.java
Support writing EC keys in Freon randomKeys.
https://issues.apache.org/jira/browse/HDDS-6347
manual test and integration test.
=> HDDS-6347. EC: Freon randomKeys EC key support

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAUtils.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/InnerNodeImpl.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/upgrade/TestDefaultUpgradeFinalizationExecutor.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/AbstractFuture.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/update/client/UpdateServiceConfig.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/PKIProfiles/DefaultProfile.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerConfiguration.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMStorageConfig.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestReplicationAnnotation.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/server/TestSCMDatanodeHeartbeatDispatcher.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/cert/CertCommands.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/checksum/TestReplicatedFileChecksumHelper.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmVolumeArgs.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/web/utils/OzoneUtils.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientForAclAuditLog.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestBucketOwner.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/codec/OMDBDefinition.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/StorageContainerServiceProviderImpl.java, pom.xml
Update checkstyle to 9.3 and fix violations.
https://issues.apache.org/jira/browse/HDDS-6363
checkstyle
=> HDDS-6363. Update checkstyle version to 9.3

hadoop-ozone/dist/src/main/compose/xcompat/clients.yaml, hadoop-ozone/dist/src/main/compose/xcompat/test.sh
Test basic read/write cross-compatibility with more versions.
https://issues.apache.org/jira/browse/HDDS-6221
https://github.com/adoroszlai/hadoop-ozone/runs/4925487749?check_suite_focus=true#step:5:4518
=> HDDS-6221. Update versions covered by cross-compatibility test

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/utils/ContainerCache.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainer.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerCheck.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerMetadataInspector.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/BlockUtils.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/KeyValueContainerUtil.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/AbstractDatanodeStore.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeStore.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeStoreSchemaOneImpl.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeStoreSchemaTwoImpl.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestContainerCache.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestSchemaOneBackwardsCompatibility.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueBlockIterator.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerCheck.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
Decouple DatanodeStore impl classes from container.
https://issues.apache.org/jira/browse/HDDS-5921
existing ut.
=> HDDS-5921. [Merge rocksdb in datanode]Decouple DatanodeStore impl classes from container.

hadoop-hdds/docs/content/interface/O3fs.md, hadoop-hdds/docs/content/interface/O3fs.zh.md, hadoop-hdds/docs/content/interface/Ofs.md
Fix classpath for ofs and o3fs in docs.
https://issues.apache.org/jira/browse/HDDS-6376
No need
=> HDDS-6376. Docs: Fix classpath for ofs and o3fs

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java
Exclude pipeline upon container close instead of exclude DNs.
https://issues.apache.org/jira/browse/HDDS-6373
manula tests, see the JIRA above.
=> HDDS-6373. EC: Exclude pipeline upon container close instead of exclude DNs.

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntry.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/io/BlockStreamAccessor.java
Discard pre-allocated blocks to eliminate worthless retries.
https://issues.apache.org/jira/browse/HDDS-6364
A new ut.
=> HDDS-6364. EC: Discard pre-allocated blocks to eliminate worthless retries.

hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientUtils.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/util/S3Utils.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneBucketStub.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectPut.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestPermissionCheck.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/util/TestS3Utils.java
Handled replication config in put API.
https://issues.apache.org/jira/browse/HDDS-6185
Added tests to cover.
=> HDDS-6185: EC: EC keys can't be created via S3 interfaces

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockOutputStreamEntry.java
Fix broken future chain and cleanup unnecessary validation function.
https://issues.apache.org/jira/browse/HDDS-6368
Exisiting CI covers.
=> HDDS-6368. EC: Fix broken future chain and cleanup unnecessary validation function.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHADBTransactionBufferStub.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManagerStub.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/HddsTestUtils.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestBlockManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestDeletedBlockLog.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestCloseContainerEventHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerReportHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerStateManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestIncrementalContainerReportHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestReplicationManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestUnknownContainerReport.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestSequenceIDGenerator.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestContainerPlacement.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineDatanodesIntersection.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelinePlacementPolicy.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineStateManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestRatisPipelineProvider.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestSimplePipelineProvider.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestHealthyPipelineSafeModeRule.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestOneReplicaPipelineSafeModeRule.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestSCMSafeModeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/server/TestSCMBlockProtocolServer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerImpl.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStorageContainerManagerFacade.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/AbstractReconContainerManagerTest.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconPipelineManager.java
Refactor MockSCMHAManager and MockRatisServer class names.
https://issues.apache.org/jira/browse/HDDS-6267
Tested with CI tests
=> HDDS-6267. Recon is accessing mock classes.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerCheck.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerData.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerMetadataInspector.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/KeyValueContainerUtil.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingService.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestSchemaOneBackwardsCompatibility.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueBlockIterator.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerIntegrityChecks.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerMetadataInspector.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestContainerReader.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainer.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/MetadataKeyFilters.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManagerHelper.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestFailureHandlingByClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestValidateBCSIDOnRestart.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java
Format table key according to schema in KeyValueContainerData.
More detailed descriptions in the JIRA below.
https://issues.apache.org/jira/browse/HDDS-6404
This is an abstraction over existing code, so existing CI covers all.
=> HDDS-6404. [Merge rocksdb in datanode] Format table key according to schema in KeyValueContainerData.

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java
To make review easier, let's break down HDDS-6400 (#3151).
This is the 1st patch of the series.
https://issues.apache.org/jira/browse/HDDS-6459
Existing CI should cover.
=> HDDS-6459. EC: [Refactor-1] Check isFullCell inside handleDataWrite

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMOpenKeysDeleteRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMOpenKeysDeleteResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/OMRequestTestUtils.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMOpenKeysDeleteRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMOpenKeysDeleteResponse.java
Update usedBytes when deleting open keys.
As the continuation of #2748.
https://issues.apache.org/jira/browse/HDDS-5867
Unit tests.
=> HDDS-5867. Update quota when deleting open keys

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ratis/RatisHelper.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CreatePipelineCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCreatePipelineCommandHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/HASecurityUtils.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/RatisUtil.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisServerImpl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/RatisTestHelper.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerRatisServer.java
Move the Ratis Rpc and TLS config code to a common location.
https://issues.apache.org/jira/browse/HDDS-6482
=> HDDS-6482. Refactor Ratis Rpc and TLS config code.

hadoop-ozone/dist/src/main/compose/ozone/prometheus.yml, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/Gateway.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/BucketEndpoint.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/EndpointBase.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/RootEndpoint.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/metrics/S3GatewayMetrics.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/metrics/package-info.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/metrics/TestS3GatewayMetrics.java
Currently S3 gateway don't have a standard metrics, this ticket is to add the metrics for S3 gateway to record the successful and failed operations.
https://issues.apache.org/jira/browse/HDDS-6481
unit test
=> HDDS-6481. Add metrics for S3 gateway

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ratis/RatisHelper.java
Setup TlsConf for streaming
https://issues.apache.org/jira/browse/HDDS-5798
The feature has been tested in https://issues.apache.org/jira/browse/RATIS-1542 .  We just setup use it here.  Will see if there are easy way to add some tests.
=> HDDS-5798. [Ozone-Streaming] Setup TlsConf parameters.

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmMetrics.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneBucketStub.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestInitiateMultipartUpload.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestPermissionCheck.java
Handled the EC replication config for initiateMultipartUpload API
https://issues.apache.org/jira/browse/HDDS-6412
Added tests to cover the flow.
=> HDDS-6412: EC: Handle ECReplicationConfig in initiateMultipartUpload API

hadoop-hdds/erasurecode/src/main/java/org/apache/hadoop/io/erasurecode/rawcoder/HadoopNativeECAccessorUtil.java, hadoop-hdds/erasurecode/src/main/java/org/apache/hadoop/io/erasurecode/rawcoder/package-info.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/AbstractNativeRawDecoder.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/AbstractNativeRawEncoder.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/ErasureCodeNative.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/NativeRSRawDecoder.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/NativeRSRawEncoder.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/NativeXORRawDecoder.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/NativeXORRawEncoder.java
fix isa-l load hadoop native lib UnsatisfiedLinkError
https://issues.apache.org/jira/browse/HDDS-6478
ci
=> HDDS-6478. EC: Fix ISA-l load hadoop native lib UnsatisfiedLinkError

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/OMDBUpdatesHandler.java, pom.xml
Upgrade rocksDB to 7.0.3, which has fix for https://github.com/facebook/rocksdb/issues/8617
https://issues.apache.org/jira/browse/HDDS-6456
Tested via a manual build but is blocked on https://github.com/facebook/rocksdb/issues/9689
=> HDDS-6456 Update RocksDB Version to 7.0.4

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/AbstractDatanodeDBDefinition.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/AbstractDatanodeStore.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeSchemaOneDBDefinition.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeSchemaThreeDBDefinition.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeSchemaTwoDBDefinition.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeStore.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeStoreSchemaOneImpl.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeStoreSchemaThreeImpl.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeStoreSchemaTwoImpl.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/FixedLengthStringCodec.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/FixedLengthStringUtils.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/PrefixedStringCodec.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestFixedLengthStringUtils.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/DBDefinitionFactory.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/DBScanner.java, hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/debug/TestDBDefinitionFactory.java
Add new container schema v3 definitions.
https://issues.apache.org/jira/browse/HDDS-6486
New small UTs,
but these are only some definitions for review, utilization would be in following patches.
=> HDDS-6486. [Merge rocksdb in datanode] Add new container schema v3 definitions.

hadoop-hdds/docs/content/feature/OM-HA.md
Add documentation detailing the OM bootstrap and decommission commands and use.
https://issues.apache.org/jira/browse/HDDS-5339
Documentation update only, no test required.
=> HDDS-5339. Document OM bootstrap and decommission process

hadoop-hdds/docs/content/feature/S3-Multi-Tenancy-Access-Control.md
Update documentation around Ranger policy creation on bucket sharing.
See the PR content for details. Should be self-explanatory. :)
https://issues.apache.org/jira/browse/HDDS-6576
n/a
=> HDDS-6576. [Multi-Tenant] Update documentation around Ranger policy creation on bucket sharing

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/GrpcOmTransport.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/GrpcOzoneManagerServer.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestGrpcOzoneManagerServer.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/protocolPB/TestGrpcOmTransport.java
Commit to feature branch containing fixes to s3 feature branch from discussion feature branch merge PR - #3297.
All fixes from the discussion feature branch merge draft PR are included in this PR commit so that commits are not 'squashed', preserving commit history, during merge to master.
starting from recent tracking master merge to feature branch, `2ea9e78bf1bd041a140a18c5bf7c0110a7fcc570`
Contains commits:
` 19e73bee743baf2ee2b8e927f9cd0c7a66cffd40`
`5271cb880bcf55145f3729e869e08e0d21513c7e`
`6be5422d348303ac70d3903cf1318496a2e14011`
`49564b38cadbfb78a62f6c03c331f0cdeee6787b`
https://issues.apache.org/jira/browse/HDDS-6643
CI workflow.
=> HDDS-6643. Merge Feature Branch to Master - Fixes from Merge PR draft

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineStateMap.java
1. Fix javadoc `throws PipelineNotFoundException`.
2. Fix preconditions check `excludePipelines`.
3. Replace raw use of `Collections.EMPTY_LIST`. 
https://issues.apache.org/jira/browse/HDDS-6653
CI
=> HDDS-6653. Small fixes in PipelineStateMap

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/metrics/S3GatewayMetrics.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/metrics/TestS3GatewayMetrics.java
Added Unit Tests for Object Endpoint Metrics for S3-Gateway
https://issues.apache.org/jira/browse/HDDS-6529?filter=-1
Wrote Unit tests for existing Object Endpoint metrics
=> HDDS-6529. Adding Unit-Test cases for S3-Gateway Object-Endpoint Metrics

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/ReconstructECContainersCommand.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/protocol/commands/TestReconstructionECContainersCommands.java, hadoop-hdds/interface-server/src/main/proto/ScmServerDatanodeHeartbeatProtocol.proto
This JIRA is to add the necessary information from SCM for the reconstruction at the DN. 
https://issues.apache.org/jira/browse/HDDS-6586
Will be adding few tests .
=> HDDS-6586: EC: Implement the EC Reconstruction Command with necessary information

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainer.java
https://issues.apache.org/jira/browse/HDDS-6745
=> HDDS-6745:  [Merge rocksdb in datanode] Flush RocksDB WAL when closing container in Schema V3.

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/upgrade/AbstractLayoutVersionManager.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/endpoint/VersionEndpointTask.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/HddsVolume.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/MutableVolumeSet.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/StorageVolume.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/upgrade/DatanodeSchemaV3FinalizeAction.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/upgrade/TestDatanodeUpgradeToSchemaV3.java
https://issues.apache.org/jira/browse/HDDS-6597
=> HDDS-6597. [Merge rocksdb in datanode] Non-rolling upgrade supports container Schema V3.

hadoop-hdds/docs/content/feature/S3-Tenant-Commands.md, hadoop-ozone/dist/src/main/smoketest/security/ozone-secure-tenant.robot, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneTenantShell.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/tenant/GetUserInfoHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/tenant/TenantAssignAdminHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/tenant/TenantAssignUserAccessIdHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/tenant/TenantBucketLinkHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/tenant/TenantCreateHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/tenant/TenantDeleteHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/tenant/TenantGetSecretHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/tenant/TenantHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/tenant/TenantListHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/tenant/TenantListUsersHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/tenant/TenantRevokeAdminHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/tenant/TenantRevokeUserAccessIdHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/tenant/TenantSetSecretHandler.java
For tenant read commands, add CLI option (`--json`) to print results in JSON.
For tenant write commands, use `--verbose` parameter to optionally print JSON result if applicable.
https://issues.apache.org/jira/browse/HDDS-6340
=> HDDS-6340. [Multi-Tenant] Add tenant CLI option to print results in JSON

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/BackgroundSCMService.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestBackgroundSCMService.java
add a background  service to schedule thread to purge the expired replication ops.
https://issues.apache.org/jira/browse/HDDS-6771
UT
=> HDDS-6771. EC: ReplicationManager - make ContainerReplicaPendingOps into a SCM service

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/upgrade/TestDatanodeUpgradeToSchemaV3.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DumpFileLoader.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBSstFileLoader.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBSstFileWriter.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBTable.java, hadoop-ozone/dist/src/main/compose/compatibility/test.sh
https://issues.apache.org/jira/browse/HDDS-6792 
Sonar reported issues:
https://sonarcloud.io/project/issues?resolved=false&types=BUG&branch=HDDS-3630&sinceLeakPeriod=true&severities=BLOCKER%2CCRITICAL%2CMAJOR%2CMINOR&id=hadoop-ozone
=> HDDS-6792: [Merge RocksDB in Datanode] Fix issues reportd by sonar.

hadoop-hdds/docs/content/design/dn-merge-rocksdb.md, hadoop-hdds/docs/content/feature/dn-merge-rocksdb.md
https://issues.apache.org/jira/browse/HDDS-6790
=> HDDS-6790: Add document for Merge RocksDB in datanode feature.

pom.xml
There are a bunch of bug fixes since 7.0.4, see https://github.com/facebook/rocksdb/releases
https://issues.apache.org/jira/browse/HDDS-6817
- Existing tests should pass.
=> HDDS-6817. Bump rocksdbjni to 7.2.2

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyAddAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyRemoveAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeySetAclRequest.java
Add post finalization validators to handle ACL requests on keys present in buckets with non-LEGACY layouts.
https://issues.apache.org/jira/browse/HDDS-6820
=> HDDS-6820. Bucket Layout Post-Finalization Validators for ACL Requests.

hadoop-hdds/client/src/test/java/org/apache/hadoop/ozone/client/io/TestBlockInputStreamFactoryImpl.java, hadoop-hdds/client/src/test/java/org/apache/hadoop/ozone/client/io/TestECBlockInputStream.java, hadoop-hdds/client/src/test/java/org/apache/hadoop/ozone/client/io/TestECBlockInputStreamProxy.java, hadoop-hdds/client/src/test/java/org/apache/hadoop/ozone/client/io/TestECBlockReconstructedInputStream.java, hadoop-hdds/client/src/test/java/org/apache/hadoop/ozone/client/io/TestECBlockReconstructedStripeInputStream.java
Migrate tests in `hdds-client` to JUnit5.
HDDS-6839
CI
=> HDDS-6839. Migrate tests in hdds-client to JUnit5

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/lock/OzoneManagerLock.java
Refactor the `OMLockMetrics` code collection in `OzoneManagerLock` class to make it more readable.
https://issues.apache.org/jira/browse/HDDS-6799
Existing UTs
=> HDDS-6799. Refactor OMLockMetrics code in OzoneManagerLock

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ECReplicationConfig.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/RatisReplicationConfig.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ReplicationConfig.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ReplicationConfigValidator.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/StandaloneReplicationConfig.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/client/TestReplicationConfigValidator.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
To validate server-side replication configuration `ozone.server.default.replication`  and `ozone.server.default.replication.type` during Ozone Manager startup.
https://issues.apache.org/jira/browse/HDDS-6841
This patch was tested manually and using Unit tests.
=> HDDS-6841. EC: Validate the server default configuration on Ozone manager startup

hadoop-ozone/ozone-manager/pom.xml, pom.xml
Move Ranger plugin version to a separate tag.
https://issues.apache.org/jira/browse/HDDS-6932
All exising tests should pass.
=> HDDS-6932. [Multi-Tenant] Move Ranger plugin version to a separate tag

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/CapacityVolumeChoosingPolicy.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestCapacityVolumeChoosingPolicy.java
Currently, the volumeChoosingPolicy is RoundRobin logic, this ticket is to add a new policy that will honor the capacity of the volumes while choosing volumes.
https://issues.apache.org/jira/browse/HDDS-6891
unit test.
=> HDDS-6891. Add CapacityVolumeChoosingPolicy

hadoop-hdds/common/src/main/resources/ozone-default.xml
….replication
Changing Description of the config
https://issues.apache.org/jira/browse/HDDS-6835
Description changes.
=> HDDS-6835. EC: Provide correct example for EC in ozone.server.default.replication

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerMetrics.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancer.java
Fix move timeout in latest iteration metric
https://issues.apache.org/jira/browse/HDDS-6959
Added a basic unit test
=> HDDS-6959. Fix move timeout in latest iteration metric

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECContainerOperationClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestContainerCommandsEC.java
This adds a test to make sure we are cleaning the recovering container on failure.
https://issues.apache.org/jira/browse/HDDS-6989
This is a test
=> HDDS-6989. EC: Add Test for RECOVERING container cleanup when failure.

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientManager.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ReplicationConfig.java
Add missing spaces in ReplicationConfig error message
https://issues.apache.org/jira/browse/HDDS-7007
No need.
=> HDDS-7007. Missing spaces in error messages

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinatorTask.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/DeleteContainerCommand.java, hadoop-hdds/interface-server/src/main/proto/ScmServerDatanodeHeartbeatProtocol.proto, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerReplica.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECOverReplicationHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/OverReplicatedProcessor.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestOverReplicatedProcessor.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/TestECContainerRecovery.java
Implemented the processing logic of OverReplicated containers of EC. The logic is very similar to UnderReplicated containers processing. 
https://issues.apache.org/jira/browse/HDDS-7016
Added test
=> HDDS-7016. EC: Implement the Over replication Processor

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/AbstractBlockChecksumComputer.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/ReplicatedBlockChecksumComputer.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/ReplicatedFileChecksumHelper.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/checksum/TestReplicatedBlockChecksumComputer.java
support block composite-crc checksum, both for CRC32 and CRC32C
https://issues.apache.org/jira/browse/HDDS-6980
unit test
=> HDDS-6980. support block composite-crc checksum

hadoop-hdds/docs/content/feature/Topology.md
Minor Doc fixing of the  XML code under the Dynamic List section in hadoop-hdds/docs/content/feature/Topology.md 
https://issues.apache.org/jira/browse/HDDS-7052
This patch was tested using a real cluster.
=> HDDS-7052. Topology Dynamic List document issue

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java
Fix Logging for removing warning while online reconstruction
https://issues.apache.org/jira/browse/HDDS-6899
No unit test required. Only Logging changes
=> HDDS-6899. EC: remove warnings and errors from console during online reconstruction of data.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMBlockProtocolServer.java
Fix up incomplete audit log for KeyBlockToDelete
https://issues.apache.org/jira/browse/HDDS-7073
UT
=> HDDS-7073. Incomplete audit log for KeyBlockToDelete

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
Close SCMLayoutVersionManager in stopping stage.
https://issues.apache.org/jira/browse/HDDS-7109
Existing UT
=> HDDS-7109. SCM should close LayoutVersionManager in stopping stage

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OmRPCLoadGenerator.java
Add the ability to generate echo RPC requests with multiple RPCClient/connections. 
This is required as there's a limit of how many requests a connection can generate.
Standard PR CI.
=> HDDS-7148. Add the ability to generate echo RPC requests with multiple RPCClient/connections

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/DefaultReplicationConfig.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ECReplicationConfig.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/OzoneQuota.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/QuotaList.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ReplicationConfig.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ReplicationConfigValidator.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/client/TestECReplicationConfig.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/client/TestReplicationConfig.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/client/TestReplicationConfigValidator.java
This PR fixes code issues reported by sonar in org.apache.hadoop.hdds.client package.
src/main - https://sonarcloud.io/code?id=hadoop-ozone&selected=hadoop-ozone%3Ahadoop-hdds%2Fcommon%2Fsrc%2Fmain%2Fjava%2Forg%2Fapache%2Fhadoop%2Fhdds%2Fclient
src/test - https://sonarcloud.io/code?id=hadoop-ozone&selected=hadoop-ozone%3Ahadoop-hdds%2Fcommon%2Fsrc%2Ftest%2Fjava%2Forg%2Fapache%2Fhadoop%2Fhdds%2Fclient
https://issues.apache.org/jira/browse/HDDS-7154
As I am unable to run sonar cloud on my ozone fork, I ran sonarlint checks locally
=> HDDS-7154. Fixed issues in org.apache.hadoop.hdds.client

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java
Rather than eating up the exception & returning NULL for GetFileStatus, throw the exception.
https://issues.apache.org/jira/browse/HDDS-7132
Added a UnitTest
=> HDDS-7132. GetFileStatus returns NULL for some paths.

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/container/InfoSubcommand.java, hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/container/TestInfoSubCommand.java
Sort the container replica according to the replica index
https://issues.apache.org/jira/browse/HDDS-7176
UT
=> HDDS-7176. Sort the container replica according to the replica index

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/utils/HddsVolumeUtil.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/HddsVolume.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/upgrade/DatanodeSchemaV3FinalizeAction.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/utils/TestHddsVolumeUtil.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/container/ContainerCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/container/ExportSubcommand.java
https://issues.apache.org/jira/browse/HDDS-7163
=> HDDS-7163. Ozone debug container CLI supports container export.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeConfiguration.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/AbstractDatanodeStore.java
https://issues.apache.org/jira/browse/HDDS-7186 
Tested in local one node cluster.
=> HDDS-7186. Add support for Rocksdb user info LOG configure.

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/pipelines/pipelines.tsx
I fixed  Scrolling left to right in Pipeline Change. Pipleline ID is also Fixed as per New Comment.
https://issues.apache.org/jira/browse/HDDS-7143
Manually Tested UI and working fine.
=> HDDS-7143. Recon: Fix left to right scrolling on Pipelines page

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OmRPCLoadGenerator.java
Fixed typo "layload" in om-echo command description as payload
https://issues.apache.org/jira/browse/HDDS-7207
=> HDDS-7207. Fixed typo "layload" in om-echo command description as payload

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/protocol/DatanodeDetails.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java
Currently ECUnderReplicationHandler did not handle the policy placement checks. This is the Jira to add that.
https://issues.apache.org/jira/browse/HDDS-7039
Unit Tests
=> HDDS-7039. EC: Handle the placement policy check in ECUnderReplicationHandler

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/BucketManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
I did the following:
- added proper javadoc to the BucketManagerImpl
- removed redundant javadocs (they duplicate javadocs in parent classes)
- removed unused class members
- removed unused constructors
https://issues.apache.org/jira/browse/HDDS-7330
unit tests
=> HDDS-7330. Cleanup of BucketManagerImpl

pom.xml
bump jetty version to 9.4.49.v20220914.
there are some security problem has been fixed
https://www.eclipse.org/jetty/security_reports.php
https://issues.apache.org/jira/browse/HDDS-7424
CI
=> HDDS-7424. bump jetty version to 9.4.49.v20220914

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/CertificateClientTestImpl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainerWithTLS.java
https://issues.apache.org/jira/browse/HDDS-1157
=> HDDS-1157. TestOzoneContainerWithTLS is failing with SSLHandshakeException

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ContainerOperationClient.java
I did some ContainerOperationClient cleanup:
* removed unused methods
* removed duplicated javadoc comments
https://issues.apache.org/jira/browse/HDDS-7435
unit tests
=> HDDS-7435. ContainerOperationClient cleanup

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
we need to check more states for EC container and delete empty closed EC container.
https://issues.apache.org/jira/browse/HDDS-7090
Unit test
=> HDDS-7090. EC: delete empty closed EC container

hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancerTask.java
Add a unit test case validating size.leaving.source.max configuration for working
https://issues.apache.org/jira/browse/HDDS-6757
Running the unit test and validating normal scenario
=> HDDS-6757. Test "size.leaving.source.max" limit in ContainerBalancer

hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/spi/impl/TestOzoneManagerServiceProviderImpl.java
1. Add UT of SyncDataFromOM for SequenceNumberNotFoundException
2. Improve some code usage
https://issues.apache.org/jira/browse/HDDS-7451
UT
=> HDDS-7451. Add UT of SyncDataFromOM for SequenceNumberNotFoundException

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerReplicaPendingOps.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/OverReplicatedProcessor.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManagerMetrics.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnderReplicatedProcessor.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestContainerReplicaPendingOps.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestOverReplicatedProcessor.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManagerMetrics.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestUnderReplicatedProcessor.java
To add relevant EC metrics to the Replication Manager.
https://issues.apache.org/jira/browse/HDDS-6896
The patch was tested with added unit tests.
=> HDDS-6896. EC: ReplicationManager - Add relevant metrics to the various ReplicationManager classes

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/db.json, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/routes.json, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/missingContainers/missingContainers.tsx
Refractoring of Code for Missing Container End Point and changes suggested in JIRA.
https://issues.apache.org/jira/browse/HDDS-7408
Manually Tested
=> HDDS-7408. Recon: Refactor container status page

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/missingContainers/missingContainers.tsx
To make Container ID Column as searchable.
https://issues.apache.org/jira/browse/HDDS-4385
Manually
=> HDDS-4385. Search function using container ID on Recon Missing Container

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/ContainerUtils.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerLayoutVersion.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/interfaces/Handler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingService.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java
Cleanup possibly onDisk unreferenced blocks in BlockDeletingService
https://issues.apache.org/jira/browse/HDDS-7446
CI. Will test in POC
=> HDDS-7446. Cleanup possibly onDisk unreferenced blocks

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/metadata/SCMMetadataStoreImpl.java
fix metaTable error
https://issues.apache.org/jira/browse/HDDS-7490
no need, this is a trivial bug fix
=> HDDS-7490. fix metaTable error

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/components/autoReloadPanel/autoReloadPanel.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/overview/overview.tsx
After Clicking Button IT should trigger om Sync and disable button show message in tool tip.
https://issues.apache.org/jira/browse/HDDS-7245
Manually
=> HDDS-7245. Recon: Add button to trigger OM DB Sync (Frontend)

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/db.json, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/missingContainers/missingContainers.tsx
To add total count in each tab of container page.
https://issues.apache.org/jira/browse/HDDS-7474
Manually
=> HDDS-7474. Recon: Add count to containers page tab label

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketSetPropertyRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestOMBucketSetPropertyRequest.java
add validation for namespace and space quota
https://issues.apache.org/jira/browse/HDDS-7481
Tested using manual test and UT
=> HDDS-7481. Set quota with reduced size than actual used do not fail

hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestKeyDeletingService.java
Fix flaky ut
https://issues.apache.org/jira/browse/HDDS-7534
Locally run successfully 100 times
=> HDDS-7534. Intermittent failure in TestKeyDeletingService#checkDeletionForEmptyKey

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java
Removed unused code around MD5 digest
https://issues.apache.org/jira/browse/HDDS-7538
CI/CD tests in GitHub should pass.
=> HDDS-7538. Remove unused OmUtils#getMD5Digest

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsConfigKeys.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/x509/SecurityConfig.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/ssl/KeyStoresFactory.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/ssl/MonitoringTimerTask.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/ssl/PemFileBasedKeyStoresFactory.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/ssl/ReloadingX509KeyManager.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/ssl/ReloadingX509TrustManager.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/ssl/package-info.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/CertificateClient.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/ssl/TestPemFileBasedKeyStoresFactory.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/ssl/TestReloadingX509KeyManager.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/ssl/TestReloadingX509TrustManager.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/CertificateClientTest.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/authority/TestDefaultCAServer.java
https://issues.apache.org/jira/browse/HDDS-7486
=> HDDS-7486. Support KeyStoreFactory which supports keyManager and trustManager reload

NOTICE.txt
Bump copyright year in NOTICE.
https://issues.apache.org/jira/browse/HDDS-7568
No need.
=> HDDS-7568. Bump copyright year in NOTICE

pom.xml
https://issues.apache.org/jira/browse/HDDS-7555
=> HDDS-7555. Upgrade ratis to 2.4.2-8b8bdda-SNAPSHOT.

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/ObjectStore.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OzoneManagerProtocol.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/snapshot/SnapshotDiffReport.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/snapshot/package-info.java, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffReport.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/ClientProtocolStub.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/snapshot/SnapshotCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/snapshot/SnapshotDiffHandler.java
This jira adds SnapshotDiff client code and the server side handling of snapshotDiff RPC call.
HDDS-7466
Manual testing and unit test.
=> HDDS-7466. SnapshotDiff Client Code.

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/ssl/MonitoringTimerTask.java
https://issues.apache.org/jira/browse/HDDS-7615
=> HDDS-7615. Import from direct dependecy instead of transitive dependency.

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/db.json, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/overview/overview.tsx
Display number of open containers on the Overviews page.
https://issues.apache.org/jira/browse/HDDS-7502
=> HDDS-7502. Recon: Show number of open containers on the Overview page

hadoop-ozone/ozone-manager/src/main/resources/webapps/ozoneManager/om-overview.html
There is no OmId in OM's UI, this ticket is to add the OmId for easier distinguish among OMs.
https://issues.apache.org/jira/browse/HDDS-7595
=> HDDS-7595. Add OmId in OM's UI

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
iterator creation moved to try-with-resource block
https://issues.apache.org/jira/browse/HDDS-7643
E2E cases tested and this warning log is not observed in OM
=> HDDS-7643. rocksdb iterator is not closed properly

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/ClosedWithMismatchedReplicasHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/ClosedWithUnhealthyReplicasHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/ClosingContainerHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/DeletingContainerHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/ECReplicationCheckHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/EmptyContainerHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/OpenContainerHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/QuasiClosedContainerHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/RatisReplicationCheckHandler.java
Added some debug logs across the new RM check handlers to make it easier to debug issues which come up.
https://issues.apache.org/jira/browse/HDDS-7642
Only log messages added. No functionality change.
=> HDDS-7642. EC: Add debug logging to the Replication Manager check handlers

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/ssl/KeyStoresFactory.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/ssl/MonitoringTimerTask.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/ssl/PemFileBasedKeyStoresFactory.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/ssl/ReloadingX509KeyManager.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/ssl/ReloadingX509TrustManager.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/keys/SecurityUtil.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/ssl/TestPemFileBasedKeyStoresFactory.java
https://issues.apache.org/jira/browse/HDDS-7636
=> HDDS-7636. Remove hadoop security dependency in org.apache.hadoop.hdds.security.ssl package

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/PlacementPolicy.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/SCMCommonPlacementPolicy.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRackScatter.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECMisReplicationHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/MisReplicationHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/TestSCMCommonPlacementPolicy.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestContainerPlacementFactory.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECMisReplicationHandler.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/fsck/TestContainerHealthTask.java
Misreplication Handler post the placement policy interface changes
https://issues.apache.org/jira/browse/HDDS-7521
Unit Tests
=> HDDS-7521. EC: Misreplication Handler changes for Placement Policy interface changes

hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmMetadataManager.java
=> Revert "HDDS-7647. [snapshot] Add unit-testcases for Ozone Snapshot List API"

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/RatisDropwizardExports.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
Integration with ratis for additional cleanup of registeration after ratis provided feature
https://issues.apache.org/jira/browse/HDDS-7473
Integration test is verified for impact. And with debug, its verified for cleanup using debug in ratis.
=> HDDS-7473. Ratis integration for support of remove registeration

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/MisReplicationHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisMisReplicationHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECMisReplicationHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestMisReplicationHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisMisReplicationHandler.java
Add Ratis Misreplication Handler to solve misreplication for ratis based replicated containers.
https://issues.apache.org/jira/browse/HDDS-7661
Unit Tests
=> HDDS-7661. Ratis Misreplication Handler

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/keys/GetKeyHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/keys/PutKeyHandler.java
Modifing using strong hashing algorithms for security-sensitive
https://issues.apache.org/jira/browse/HDDS-7525
=> HDDS-7525. Migrate key digest from MD5 to SHA256 in Ozone shell

hadoop-hdds/docs/content/interface/Ofs.md, hadoop-hdds/docs/content/interface/S3.zh.md, hadoop-hdds/docs/content/security/SecuringTDE.md, hadoop-hdds/docs/content/security/SecurityAcls.md, hadoop-hdds/docs/content/security/SecurityAcls.zh.md, hadoop-hdds/docs/content/security/SecurityWithRanger.md, hadoop-hdds/docs/content/security/SecurityWithRanger.zh.md
1. Update md files contents such as fixing typos and optimizing formats.
2. Improve SecurityAcls.md to be more accurate.
https://issues.apache.org/jira/browse/HDDS-7409
=> HDDS-7409. [DOC] Update documents for better presentation

hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java
This is an addendum to #4119 to address the comments posted after its merge.
https://issues.apache.org/jira/browse/HDDS-7690
n/a
=> HDDS-7690. Addendum: [Snapshot] Use SST file list output from compaction DAG as SnapshotDiff input

hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
Mark all new proto message fields as optional before snapshot feature branch is merged to master branch.
Context: https://github.com/apache/ozone/pull/3985/files#r1041505724
https://issues.apache.org/jira/browse/HDDS-7600
- Existing tests should pass.
=> HDDS-7600. [Snapshot] Mark all new proto message fields as optional

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/db.json, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/diskUsage/diskUsage.tsx
Additional Namespace Summary EndPoint Changes and Basic Information.
https://issues.apache.org/jira/browse/HDDS-7770
Manually
=> HDDS-7770. Recon namespace summary endpoint to carry basic entity information as well

hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java, hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/rocksdiff/TestRocksDBCheckpointDiffer.java
This change is to proactively remove the unnecessary SST files from the backup directory which are not needed to generate diff using compaction DAG.
These files are the one which get compacted to new files at each level. For example in the below graph, "000015", "000013", "000011", "000009" get compacted to "000018",  "000016", "000017". 
We don't need "000018",  "000016", "000017" to generate diff because these are compaction of previous level .
https://issues.apache.org/jira/browse/HDDS-7873
* Unit tests
=> HDDS-7873. [Snapshot] Prune backup SST files that can be expanded periodically

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/HddsVersionInfo.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/VersionInfo.java, hadoop-hdds/common/src/main/resources/hdds-version-info.properties, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/util/OzoneVersionInfo.java, hadoop-ozone/common/src/main/resources/ozone-version-info.properties
https://issues.apache.org/jira/browse/HDDS-7783
=> HDDS-7783. Add compile platform info in 'ozone version' command output

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestRatisPipelineLeader.java
Failure is due to the pipeline healthy check. It is possible to get a ```allocated``` pipeline which is not **healthy**.
We should find the **healthy** pipeline before the test logic
https://issues.apache.org/jira/browse/HDDS-7904
Locally repeated run 20 times.
=> HDDS-3265. Intermittent timeout in TestRatisPipelineLeader

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeConfiguration.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/HddsVolume.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/AbstractDatanodeStore.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeSchemaThreeDBDefinition.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeStore.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeStoreSchemaThreeImpl.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java
https://issues.apache.org/jira/browse/HDDS-7321
=> HDDS-7321. Auto rocksDB small sst files compaction.

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/S3Batcher.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/S3SecretCache.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/S3SecretFunction.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/S3SecretLockedManager.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/S3SecretManager.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/S3SecretStore.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestSecureOzoneRpcClient.java, hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/S3SecretManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/security/OMSetSecretRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/security/S3GetSecretRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/security/S3RevokeSecretRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/tenant/OMTenantAssignUserAccessIdRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/tenant/OMTenantRevokeUserAccessIdRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/security/OMSetSecretResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/security/S3GetSecretResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/security/S3RevokeSecretResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/tenant/OMTenantAssignUserAccessIdResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/tenant/OMTenantRevokeUserAccessIdResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/OzoneDelegationTokenSecretManager.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/security/TestS3GetSecretRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/S3SecretStoreMap.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/TestOzoneDelegationTokenSecretManager.java
Extract interfaces of S3 secret management. This changes required to HDDS-7814. 
No new functionality introducing, only code refactoring and encapsulation. 
https://issues.apache.org/jira/browse/HDDS-7815
Existed test passed.
=> HDDS-7815. Extract S3 secret layer

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ratis/RatisHelper.java, hadoop-hdds/interface-client/src/main/proto/hdds.proto, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/audit/OMAction.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OzoneManagerProtocol.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java, hadoop-ozone/dist/src/main/smoketest/omha/testOMHA.robot, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestTransferLeadershipShell.java, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/OMAdmin.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/TransferOmLeaderSubCommand.java
Support OM transfer Ratis leadership.
Split From https://issues.apache.org/jira/browse/HDDS-5686
https://issues.apache.org/jira/browse/HDDS-7687
UT and manual test.
=> HDDS-7687. Support OM transfer Ratis leadership

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/utils/db/DatanodeDBProfile.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java, hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
Fix CME in RocksDBCheckpointDiffer#filterRelevantSstFiles .
https://issues.apache.org/jira/browse/HDDS-7866
Tested manually , existing UTS.
=> HDDS-7866. [Snapshot] Fix ConcurrentModificationException in snapdiff API.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/conf/DatanodeRatisServerConfig.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java
https://issues.apache.org/jira/browse/HDDS-7964
=> HDDS-7964. Enable ratis pre-vote in Ozone by default.

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneVolume.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/ObjectStoreStub.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneBucketStub.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneVolumeStub.java
Optimize the construction method of OzoneVolume and OzoneBucket.
https://issues.apache.org/jira/browse/HDDS-4223
=> HDDS-4223. Optimize the construction method of OzoneVolume and OzoneBucket.

hadoop-hdds/docs/content/feature/ErasureCoding.zh.md
[https://issues.apache.org/jira/browse/HDDS-7556](https://issues.apache.org/jira/browse/HDDS-7556)
local hugo server
=> HDDS-7556. Translate Erasure Coding doc into Mandarin Chinese

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/MismatchedReplicasHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestMismatchedReplicasHandler.java
QUASI_CLOSED replicas of a CLOSED container should be force closed if their BCSIDs match.
https://issues.apache.org/jira/browse/HDDS-7980
Added a unit test
=> HDDS-7980. Force Close QUASI_CLOSED replicas of CLOSED containers in RM

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/tracing/TracingUtil.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneFsShell.java
Currently `OzoneFsShell` creates unrelated spans, e.g. `ozone fs -mkdir ofs://om/vol1` results in 3 separate spans:
This PR adds a main span in `OzoneFsShell` to encompass spans created by inner method calls, similar to how `OzoneShell`, `OzoneAdmin` etc. do it.
https://issues.apache.org/jira/browse/HDDS-7976
```
cd hadoop-ozone/dist/target/ozone-1.4.0-SNAPSHOT/compose/ozone
export COMPOSE_FILE=docker-compose.yaml:monitoring.yaml
./run.sh -d
sleep 60
docker-compose exec scm ozone fs -mkdir ofs://om/vol1
open http://localhost:16686
```
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4186458710
=> HDDS-7976. FsShell creates unrelated trace spans

hadoop-ozone/dist/src/main/license/bin/LICENSE.txt, hadoop-ozone/dist/src/main/license/jar-report.txt, hadoop-ozone/s3gateway/pom.xml, pom.xml
Upgrading weld to 3.1.9.Final
https://issues.apache.org/jira/browse/HDDS-7839
Ran S3 tests locally.
https://github.com/rohit-kb/ozone/actions/runs/4242665829
=> HDDS-7839. Upgrade Weld to 3.1.9

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisMisReplicationHandler.java
Updating RatisMisReplicationHandler with the new changes from [HDDS-7847](https://issues.apache.org/jira/browse/HDDS-7847).
https://issues.apache.org/jira/browse/HDDS-7973
=> HDDS-7973. Let RatisMisReplicationHandler use the new RatisContainerReplicaCount constructor

hadoop-ozone/httpfsgateway/src/main/java/org/apache/ozone/fs/http/server/FSOperations.java, hadoop-ozone/httpfsgateway/src/main/java/org/apache/ozone/fs/http/server/HttpFSServer.java
I removed the support for satisfyStoragePolicy operation. 
https://issues.apache.org/jira/browse/HDDS-8023
Built the project successfully, green CI on my fork: https://github.com/dombizita/ozone/actions/runs/4258119003
=> HDDS-8023. [HTTPFSGW] Remove support for satisfyStoragePolicy operation

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/components/autoReloadPanel/autoReloadPanel.tsx
Change label from OM DB to DB Sync on UI of Recon.
https://issues.apache.org/jira/browse/HDDS-7505
- Manually
=> HDDS-7505. Recon: Rename OM DB Sync to DB SYNC on UI

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/RocksDBStoreMBean.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java
https://issues.apache.org/jira/browse/HDDS-7183
=> HDDS-7183. Expose RocksDB critical properties.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
=> Revert "HDDS-8006. [snapshot] Add unit test cases for snapshot delete"

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java
Addendum to #4249 to address [comment](https://github.com/apache/ozone/pull/4249#discussion_r1113303598) received after PR merge.
https://issues.apache.org/jira/browse/HDDS-7906
UT
=> HDDS-7906. Addendum: [Snapshot] Wait for checkpoint creation if snapshot in cache and not committed to DB

hadoop-hdds/docs/content/feature/Reconfigurability.md, hadoop-hdds/docs/content/feature/Reconfigurability.zh.md, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/protocol/ReconfigureProtocol.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/protocolPB/ReconfigureProtocolClientSideTranslatorPB.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/protocolPB/ReconfigureProtocolServerSideTranslatorPB.java, hadoop-hdds/interface-client/src/main/proto/ReconfigureProtocol.proto, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/reconfig/TestScmReconfigure.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/reconfig/ReconfigurePropertiesSubcommand.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/reconfig/ReconfigureStartSubcommand.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/reconfig/ReconfigureStatusSubcommand.java
SCM conf `ozone.administrators` support configurable.
https://issues.apache.org/jira/browse/HDDS-8032
=> HDDS-8032. SCM support reconfigurable dynamically

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneManagerSnapshotAcl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/package-info.java
Added native ACL integration tests for Snapshotting.
https://issues.apache.org/jira/browse/HDDS-8014
Integration tests.
=> HDDS-8014. [Snapshot] Implement Native Acl Integration tests for Snapshotting

hadoop-ozone/dist/src/main/compose/ozonesecure/test.sh, hadoop-ozone/dist/src/main/smoketest/snapshot/snapshot-acls.robot
Add smoketest for Snapshot with ACLs.
https://issues.apache.org/jira/browse/HDDS-8038
Smoketest.
=> HDDS-8038. [Snapshot] Add a smoketest for Snapshot with ACLs

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
We missed adding the RatisMisReplicationHandler into the ReplicationManager.processUnderReplicatedContainer() method. This means that RatisMisReplication is never handled.
https://issues.apache.org/jira/browse/HDDS-8111
There are currently no tests for this. Testing it in the existing TestReplicationManager class is too difficult.
It is our intention to build full integration tests using mini-cluster for ReplicationManager which will test this and the full RM full more completely.
=> HDDS-8111. ReplicationManager: Add RatisMisReplicationHandler into rm.processUnderReplicatedContainer

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java
In a scenario where an EC container has two copies of the same replica index:
1. A maintenance replica index, where the maintenance node is dead
2. A copy which is decommissioning
The replicate commands to resolve the decommissioning index can get sent to the dead maintenance node repeatedly, and then the decommission becomes stuck.
This is because the replicas which were filtered previously are not passed into the method used to resolve the decommission and maintenance indexes.
https://issues.apache.org/jira/browse/HDDS-8171
Test added to reproduce the issue before making the code change.
=> HDDS-8171. Replicate commands can be sent to dead maintenance modes if the same index is being decommissioned

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmBucketInfo.java
Fix OmBucketInfo#equals Comparative condition
see defaultReplicationConfig Comparative condition.
https://issues.apache.org/jira/browse/HDDS-8217
=> HDDS-8217. Fix OmBucketInfo#equals Comparative condition

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneKey.java
HDDS-8221. OzoneKey code comment content error
https://issues.apache.org/jira/browse/HDDS-8221
=> HDDS-8221. OzoneKey code comment content error

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/EndpointBase.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/metrics/TestS3GatewayMetrics.java
EndpointBase#getBucket Exception capture content error
https://issues.apache.org/jira/browse/HDDS-8222
=> HDDS-8222. EndpointBase#getBucket should handle BUCKET_NOT_FOUND

hadoop-hdds/rocks-native/pom.xml, hadoop-hdds/rocks-native/src/main/patches/rocks-native.patch
Changing variable in rocksdb patch to fix shadow error.
https://issues.apache.org/jira/browse/HDDS-8176
Build passed & tested manually
=> HDDS-8176. [Snapshot] Rename variables to fix shadow declaration warning with gcc

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/BlockManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/SCMBlockDeletingService.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
SCM delete block service shoud run wait for safemode to exit.
https://issues.apache.org/jira/browse/HDDS-8223
=> HDDS-8223. SCM delete block service shoud run wait for safemode to exit.

.github/ci.md
Update CI docs to reflect changes done for HDDS-7540.
:eyes:
=> HDDS-7540. Document separate scheduled CI

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/handlers/LegacyBucketHandler.java
Close `RocksIterator` in `LegacyBucketHandler`.
https://issues.apache.org/jira/browse/HDDS-8257
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4509913479
=> HDDS-8257. RocksIterator not closed properly in LegacyBucketHandler

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMetrics.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequestWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/OpenKeyCleanupService.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestOpenKeyCleanupService.java
Add metrics for numKeyHSyncs, numOpenKeysHSyncCleaned and numOpenKeysCleaned.
https://issues.apache.org/jira/browse/HDDS-7855
Will add new unit tests.
=> HDDS-7855. Add hsync metrics in OM.

hadoop-hdds/docs/content/feature/Topology.md
Update documentation by removing DNS configuration from Topology table static mapping file.
https://issues.apache.org/jira/browse/HDDS-8293
Checked in preview in IDE. Later will verify in edge(Master).
=> HDDS-8293. In Network Topology documentation remove DNS configuration from Topology table mapping file.

hadoop-hdds/docs/content/feature/Quota.md, hadoop-hdds/docs/content/feature/Quota.zh.md
…ge[Storage Space level quota]
Update documentation by remove "PB (p), etc." from Client Usage[Storage Space level quota]
https://issues.apache.org/jira/browse/HDDS-8311
UT
=> HDDS-8311. In Quota documentation remove PB (p), etc. from Client Usage[Storage Space level quota]

hadoop-hdds/docs/content/security/GDPR.md, hadoop-hdds/docs/content/security/GDPR.zh.md, hadoop-hdds/docs/content/security/SecuringDatanodes.zh.md, hadoop-hdds/docs/content/security/SecuringS3.zh.md, hadoop-hdds/docs/content/security/SecuringTDE.zh.md, hadoop-hdds/docs/content/security/SecurityWithRanger.zh.md
https://issues.apache.org/jira/browse/HDDS-8330
=> HDDS-8330. [Doc] Fix misplaced doc for GDPR.zh.md

hadoop-hdds/hadoop-dependency-client/pom.xml, hadoop-hdds/hadoop-dependency-server/pom.xml, pom.xml
Upgrade Hadoop version to 3.3.5.
https://issues.apache.org/jira/browse/HDDS-8291
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4533321279
=> HDDS-8291. Upgrade to Hadoop 3.3.5

hadoop-ozone/pom.xml
Upgrading Spring Framework to 5.3.26
https://issues.apache.org/jira/browse/HDDS-8394
https://github.com/rohit-kb/ozone/actions/runs/4637324218
=> HDDS-8394. Upgrade Spring Framework to 5.3.26 due to CVE-2023-20861

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/OMVolumeSetQuotaRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/OMRequestTestUtils.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/volume/TestOMVolumeSetQuotaRequest.java
- validation for namespace quota for bucket count when setQuota for volume for namespace quota
https://issues.apache.org/jira/browse/HDDS-8367
Unit test cases
=> HDDS-8367. setquota should have a check on usedNamespace [NameSpacequota]

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SnapshotChainManager.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/snapshot/TestOMSnapshotDeleteResponse.java
Complete the test case `TestOMSnapshotDeleteResponse#testAddToDBBatch`
https://issues.apache.org/jira/browse/HDDS-7862
- The test case itself.
=> HDDS-7862. [Snapshot] Wrap up TestOMSnapshotDeleteResponse

hadoop-hdds/docs/content/concept/Recon.md, hadoop-hdds/docs/content/concept/Recon.zh.md
https://issues.apache.org/jira/browse/HDDS-7758
=> HDDS-7758. Update Recon.zh.md doc for ozone.recon.task.safemode.wait.threshold configuration

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemWithLinks.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientUtils.java
For link bucket as orphan, fix the failure of volume not found or bucket not found.
https://issues.apache.org/jira/browse/HDDS-7884
Integration test added for the orphan link bucket deletion
=> HDDS-7884. ofs: Recursive delete of path of symlink with empty source fails

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
Fix empty bucket can not  be deleted
https://issues.apache.org/jira/browse/HDDS-7412
unit test
=> HDDS-7412. Failed to delete an empty bucket with "BUCKET_NOT_EMPTY Bucket is not empty"

hadoop-hdds/framework/src/main/resources/webapps/static/ozone.css, hadoop-hdds/server-scm/src/main/resources/webapps/scm/scm-overview.html
1. Sorting Symbol wrt each column
2. toggling reverse flag
https://issues.apache.org/jira/browse/HDDS-8465
Manually with JMX Response
Screenshot Attached:
=> HDDS-8465. Data Rendering code on SCM UI

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequestWithFSO.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCommitRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCommitRequestWithFSO.java
while commit, only additional datasize is updated comparing previous commit keyInfo datasize.
https://issues.apache.org/jira/browse/HDDS-7965
Tested using UT
=> HDDS-7965. Quota needs to be updated correctly for Hsync

hadoop-ozone/pom.xml
https://issues.apache.org/jira/browse/HDDS-8512
https://github.com/rohit-kb/ozone/actions/runs/4849780695
=> HDDS-8512. Bump Spring Framework to 5.3.27

CONTRIBUTING.md, README.md
Update README to include GitHub Discussions.
https://issues.apache.org/jira/browse/HDDS-8515
Rendered views 
- https://github.com/apache/ozone/blob/feaab2bdd7a064bac6f8ca9168750e6aac84277d/CONTRIBUTING.md
- https://github.com/apache/ozone/blob/feaab2bdd7a064bac6f8ca9168750e6aac84277d/README.md
=> HDDS-8515. Update README to include GitHub Discussions.

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/CodecRegistry.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBStoreBuilder.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/TestRDBSnapshotProvider.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStore.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBTableStore.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestTypedRDBTableStore.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestSnapshotDiffCleanupService.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestRocksDbPersistentList.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestRocksDbPersistentMap.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestRocksDbPersistentSet.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/recovery/ReconOmMetadataManagerImpl.java
Add a builder for `CodecRegistry` and make it immutable.
HDDS-8541
By existing unit tests.
=> HDDS-8541. CodecRegistry is not thread safe.

hadoop-hdds/erasurecode/src/test/java/org/apache/ozone/erasurecode/TestCodecRegistry.java, hadoop-hdds/erasurecode/src/test/java/org/apache/ozone/erasurecode/TestCoderBase.java, hadoop-hdds/erasurecode/src/test/java/org/apache/ozone/erasurecode/rawcoder/TestCodecRawCoderMapping.java, hadoop-hdds/erasurecode/src/test/java/org/apache/ozone/erasurecode/rawcoder/TestDummyRawCoder.java, hadoop-hdds/erasurecode/src/test/java/org/apache/ozone/erasurecode/rawcoder/TestNativeRSRawCoder.java, hadoop-hdds/erasurecode/src/test/java/org/apache/ozone/erasurecode/rawcoder/TestNativeXORRawCoder.java, hadoop-hdds/erasurecode/src/test/java/org/apache/ozone/erasurecode/rawcoder/TestRSRawCoder.java, hadoop-hdds/erasurecode/src/test/java/org/apache/ozone/erasurecode/rawcoder/TestRSRawCoderBase.java, hadoop-hdds/erasurecode/src/test/java/org/apache/ozone/erasurecode/rawcoder/TestRawCoderBase.java, hadoop-hdds/erasurecode/src/test/java/org/apache/ozone/erasurecode/rawcoder/TestRawErasureCoderBenchmark.java, hadoop-hdds/erasurecode/src/test/java/org/apache/ozone/erasurecode/rawcoder/TestXORRawCoderBase.java
Migrate tests in hdds-erasurecode to JUnit5
https://issues.apache.org/jira/browse/HDDS-8548
https://github.com/kaijchen/ozone/actions/runs/4890971504/jobs/8730925367#step:6:754
=> HDDS-8548. Migrate tests in hdds-erasurecode to JUnit5

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/multitenant/TestMultiTenantVolume.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/tenant/OMTenantCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/OMVolumeCreateRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOMTenantCreateRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/volume/TestOMVolumeCreateRequest.java
Allow ozone user to create volume name which contains non-s3-naming-convention character (e.g. underscore)
https://issues.apache.org/jira/browse/HDDS-8484
unit tests
=> HDDS-8484. Allow Ozone volume name to have special characters

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/upgrade/HDDSLayoutVersionManager.java
Fix intermittent `IllegalStateException: zip file closed` by creating a single instance of `Reflections` for `HDDSLayoutVersionManager`.  This avoids repeated (concurrent) scanning of the classpath.
https://issues.apache.org/jira/browse/HDDS-6049
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4900659031
=> HDDS-6049. IllegalStateException: zip file closed in HDDSLayoutVersionManager

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/CodecBuffer.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBBatchOperation.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBTable.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestCodec.java
Similar to HDDS-8542, we will add a putWithBatch method using RocksDB ByteBuffer APIs.
HDDS-8552
=> HDDS-8552. Support putWithBatch with ByteBuffer.

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
Restore client-side validation of bucket names
https://issues.apache.org/jira/browse/HDDS-8549
Unit tests.
=> HDDS-8549. Restore client-side validation of bucket names

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
Delete duplicate getBucketInfo in OMKeyCommitRequest
https://issues.apache.org/jira/browse/HDDS-8623
=> HDDS-8623. Delete duplicate getBucketInfo in OMKeyCommitRequest

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/utils/db/DatanodeDBProfile.java
`DatanodeDBProfile` may leak `ManagedColumnFamilyOptions` and its related objects:
```
[Finalizer] WARN  managed.ManagedRocksObjectUtils (ManagedRocksObjectUtils.java:assertClosed(54)) - ManagedLRUCache is not closed properly
[Finalizer] WARN  managed.ManagedRocksObjectUtils (ManagedRocksObjectUtils.java:assertClosed(54)) - ManagedBloomFilter is not closed properly
[Finalizer] WARN  managed.ManagedRocksObjectUtils (ManagedRocksObjectUtils.java:assertClosed(54)) - ManagedColumnFamilyOptions is not closed properly
```
`AtomicReference#updateAndGet` requires the update function to be free of side-effects, since it is applied in a loop and may be executed multiple times until `compareAndSet` succeeds.  However, `op -> op != null ? op : createColumnFamilyOptions(config))` has side-effect: the …
=> HDDS-8476. ManagedColumnFamilyOptions is not closed properly in DatanodeDBProfile

hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestBucketManagerImpl.java
Swap the names of two test cases to make them more appropriate for the content.
[HDDS-8107](https://issues.apache.org/jira/browse/HDDS-8107)
unit test
=> HDDS-8107. Swap test cases name in TestBucketManagerImpl

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java
Do not log zero byte object creation
https://issues.apache.org/jira/browse/HDDS-8656
=> HDDS-8656. Do not log zero byte object creation

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/ICopyObject.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/ICopyObjectInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmDirectoryInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneListStatusHelper.java
Remove Clone and make use of copyObject in OmDirectoryInfo and OmKeyInfo to have better maintainability.
https://issues.apache.org/jira/browse/HDDS-8657
Built locally and tested as same steps in HDDS-8292
=> HDDS-8657. Remove Clone and make use of copyObject in OmDirectoryInfo and OmKeyInfo.

hadoop-hdds/docs/content/design/secure-s3.md
While attempting to get Ozone to production, we found several security flaws regarding S3 auth.
Some of them we have already done ([HDDS-7191](https://issues.apache.org/jira/browse/HDDS-7191), [HDDS-7815](https://issues.apache.org/jira/browse/HDDS-7815)), some of them are in progress ([HDDS-8050](https://issues.apache.org/jira/browse/HDDS-8050),[HDDS-7814](https://issues.apache.org/jira/browse/HDDS-7814)), and some are to be implemented.
This document shares our vision of improving Ozone S3 security, the current and the upcoming work.
https://issues.apache.org/jira/browse/HDDS-8132
```
cd hadoop-hdds/docs
hugo serve
firefox http://localhost:1313
```
=> HDDS-8132. [Design] Secure S3 keys management

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/reconfig/TestOmReconfigure.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataReader.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
Support OM dynamic changes ozone.readonly.administrators.
https://issues.apache.org/jira/projects/HDDS/issues/HDDS-8654
ut
=> HDDS-8654. Support dynamic changes ozone.readonly.administrators(OM)

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/db.json, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/routes.json, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/insights/insights.less, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/insights/insights.tsx
Recon has an API endpoint to get container size distribution in Ozone. Add visualisation in Recon UI for this using histograms.
We will have to add another box that will display the percentages
Example
```
{      
"containerSize": 1024,       
"count": 2     
},
{
"containerSize": 16384,
"count": 3
},
{
"containerSize": 2097152,
"count": 4
},
{
"containerSize": 11270,
"count": 5
}
```
Total Count ➖ 2+3+4+5 = *14 Total Containers*
Percentage of Containers having upperbound 1024 = 2/14 *100 = 14.28%
Percentage of Containers having upperbound 16384 = 3/14 *100 = 21.42%
Percentage of Containers having upperbound 2097152 = 4/14 *100 = 28.5%
Percentage of Containers having upperbound 11270 = 5/14 *100 = 35.7%
https://issues.apache.org/jira/browse/HDDS-7812
Manually
For Empty Response …
=> HDDS-7812. Recon UI: Add visualization for container size distribution.

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/ContainerKeyPrefix.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/ContainerKeyPrefixImpl.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/KeyPrefixContainer.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/ContainerKeyPrefixCodec.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/KeyPrefixContainerCodec.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/ReconContainerMetadataManagerImpl.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/ContainerKeyMapperTask.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/TestReconCodecs.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/spi/impl/TestReconContainerMetadataManagerImpl.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestContainerKeyMapperTask.java
ContainerKeyPrefix and KeyPrefixContainer are two very similar classes.  We should combine them to one class.
HDDS-8733
=> HDDS-8733. Combine ContainerKeyPrefix and KeyPrefixContainer.

hadoop-ozone/dist/src/main/compose/README.md
Improve `hadoop-ozone/dist/src/main/compose/README.md` by describing the concepts in a bit more detail.  Include mention of test scripts with custom configs being introduced in #4750.
https://issues.apache.org/jira/browse/HDDS-8669
:eyes:
=> HDDS-8669. Update compose README

hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/heatmap/HeatMapProviderDataResource.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/heatmap/TestHeatMapInfo.java
This PR is to fix NPE in Junit test when heatmap provider output generates empty output.
https://issues.apache.org/jira/browse/HDDS-8747
Junit test now not throwing NPE
=> HDDS-8747. Recon - Fix HeatMap test case.

hadoop-hdds/docs/content/interface/ReconApi.md
Updated Recon API documentation for newly added APIs
https://issues.apache.org/jira/browse/HDDS-8481
Tested by previewing "`ReconApi.md`" in editor.
=> HDDS-8481. API Documentation for OM Key Level Info and Container Mismatch and SCM DB Insights Info.

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/OMClientRequest.java
Remove redundant checks in OMClientRequest#checkACLsWithFSO
https://issues.apache.org/jira/browse/HDDS-8717
ci：
https://github.com/whbing/ozone/actions/runs/5122110056
=> HDDS-8717. Optimize checkACLsWithFSO to reduce redundant checks

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/SnapshotDeletingService.java
When getting the previous snapshot, we need to get only the active snapshot. This patch address this issue.
https://issues.apache.org/jira/browse/HDDS-8684
=> HDDS-8684. [Snapshot] Skip non-active snapshots while walking snapshot chain for deletion processing

hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/rocksdb/util/TestManagedSstFileReader.java
https://issues.apache.org/jira/browse/HDDS-8834
=> HDDS-8834. Ignore TestManagedSstFileReader#testGetKeyStreamWithTombstone

hadoop-hdds/rocksdb-checkpoint-differ/pom.xml
Removed duplicate declaration of `mockito-core` in `rocksdb-checkpoint-differ`
https://issues.apache.org/jira/browse/HDDS-8816
=> HDDS-8816. Removed duplicate declaration of mockito-core in rocksdb-checkpoint-differ

pom.xml
https://issues.apache.org/jira/browse/HDDS-8849
https://github.com/rohit-kb/ozone/actions/runs/5264432709
=> HDDS-8849. Upgrade commons-text to 1.10.0

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/BucketLayoutAwareOMKeyRequestFactory.java
Modify the BucketLayoutAwareOMKeyRequestFactory#createRequest annotation
https://issues.apache.org/jira/browse/HDDS-8847
=> HDDS-8847. Fix javadoc of BucketLayoutAwareOMKeyRequestFactory#createRequest

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SnapshotChainManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotCreateRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestSnapshotChain.java
This change is to add snapshot to snapshot chain if it gets added to snapshot cache successfully and removes it from snapshot chain if fails. More details in: https://issues.apache.org/jira/browse/HDDS-8832?focusedCommentId=17732758&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17732758
https://issues.apache.org/jira/browse/HDDS-8832
Existing unit tests as of now. Will look into fault injection to reproduce the issue through unit test. That will be separate PR.
=> HDDS-8832. [Snapshot] Synchronized add snapshotInfo to snapshot chain and snapshot cache

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmMetrics.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotDeleteRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotDeleteRequest.java
Increment `NumSnapshotDeleted` and `NumSnapshotListFails` metrics for success in snapshot deletion and failure in list snapshot requests respectivel. 
* https://issues.apache.org/jira/browse/HDDS-8798
* https://issues.apache.org/jira/browse/HDDS-8799
Updated unit and integration tests to verify the changes.
=> HDDS-8798. Increment NumSnapshotDeleted and NumSnapshotListFails metrics appropriately

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java
Fix a memory leak where datanodes re-registering with different address were left in the `dnsToUuidMap`.  This was caused by trying to remove `dnsName` instead of `uuid` from the value `Set<String>` of `dnsToUuidMap`.  The bug is revealed by changing `Set<String>` to `Set<UUID>` (being done in HDDS-8854).
Reproduced by adding assertion in existing test:
```
TestSCMNodeManager.testScmRegisterNodeWithUpdatedIpAndHostname  Time elapsed: 3.104 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <[]> but was: <[4cea4603-f41f-4008-9ec5-6862bf56737b(host2/2.3.4.5)]>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
at …
```
=> HDDS-8867. Datanode re-registration memory leak

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockDataStreamOutput.java
Ozone Stream init unused token
https://issues.apache.org/jira/browse/HDDS-8884
=> HDDS-8884. [Ozone-Streaming] Ozone Stream init unused token

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/components/navBar/navBar.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/heatMap/heatMapConfiguration.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/heatMap/heatmap.less, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/heatMap/heatmap.tsx
After Doing Testing in CDPD Cluster Found Below Issues
1) Heatmap refresh was not working once we get no Data acvailable.
2) Space Issue for Smaller Blocks
3) Absolute Path was not working.
4) Empty input was going through api.
https://issues.apache.org/jira/browse/HDDS-8851
Manually
=> HDDS-8851. Recon Heatmap UI - User cannot navigate back from No Data

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsSnapshot.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientAdapter.java
To implement delete snapshot file system commands.
https://issues.apache.org/jira/browse/HDDS-8408
New unit test.
=> HDDS-8408. [Snapshot] Implement 'ozone fs' command for deleting snapshots

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NetUtils.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NetworkTopologyImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/SCMCommonPlacementPolicy.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRackScatter.java
Replace or simplify some streams in `SCMContainerPlacementRackScatter` and related code.
https://issues.apache.org/jira/browse/HDDS-8936
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5402308009
=> HDDS-8936. Eliminate unnecessary streams in SCMContainerPlacementRackScatter

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
Integration test to simulate staggered snapshot creation and deletion
https://issues.apache.org/jira/browse/HDDS-8378
Integration test.
=> HDDS-8378. [Snapshot] Integration test to simulate staggered snapshot creation and deletion

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
Fix for a flaky test.
https://issues.apache.org/jira/browse/HDDS-8089
Github Actions Workflow has been defined according to an [example](https://cwiki.apache.org/confluence/display/OZONE/Github+Actions+tips+and+tricks) in order to run single test class multiple times.
=> HDDS-8089. Intermittent failure in TestOmSnapshot.checkKey

pom.xml
https://issues.apache.org/jira/browse/HDDS-9034
https://github.com/rohit-kb/ozone/actions/runs/5552010000
=> HDDS-9034. Upgrade netty to 4.1.94.Final

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/metadata/Replicate.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/CertificateStore.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAInvocationHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/security/RootCARotationHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestReplicationAnnotation.java
This PR aims to support different methods to make Ratis call using Replicate annotation.
Make a direct call to RatisServer
Make call to RatisServer using RatisClient
[HDDS-9009](https://issues.apache.org/jira/browse/HDDS-9009)
Unit Tests
=> HDDS-9009. Introduce InvocationType for Replicate annotation in SCM.

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/OmTableInsightTask.java
While analyzing recent acceptance test runs, it has been observed that there is an issue with the new OM DB insights in Recon. The logs are flooded with messages like the following during tests such as acceptance HA and acceptance compat:
```
recon_1  | 2023-07-13 10:09:48,563 [pool-27-thread-1] INFO impl.OzoneManagerServiceProviderImpl: Number of updates received from OM : 10, SequenceNumber diff: 30, SequenceNumber Lag from OM 0.
recon_1  | 2023-07-13 10:09:48,563 [pool-27-thread-1] INFO impl.OzoneManagerServiceProviderImpl: Delta updates received from OM : 1 loops, 30 records
recon_1  | 2023-07-13 10:09:48,636 [pool-49-thread-1] WARN tasks.OmTableInsightTask: Update event does not have the old Key Info for #TRANSACTIONINFO.
recon_1  | 2023-07-13 10:09:48,636 [pool-49-thread-1] WARN …
```
=> HDDS-9052. The logs in Recon are flooded with excessive warning messages, resulting in log overload

hadoop-hdds/docs/content/interface/Cli.md
New delete commands are added recently which supports recursive volume, bucket delete. Also for FSO it supports trash while running from sh command as well. These changes are documented in this PR
https://issues.apache.org/jira/browse/HDDS-8916
Verified locally.
=> HDDS-8916. Update documentation for ozone sh delete commands.

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DefaultCertificateClient.java
A detailed description of the problem can be found in the JIRA ticket.
The TLDR:
the deadlock happens because SCM startup calls the listCA method on the SCM's cert client, which is synchronized, but it connects to the leader SCM to get data, and waits until the leader comes out of safe mode because of how the SCM Security protocol server is implemented. Also it waits infinitely.
In the meantime, as the SCM's security protocol server is already started, two other service filed a request already and the server uses the SCM's cert client to get the data requested by the other services, but the request processing can not be finished, as it can not get into the also synchronized method within the certificate client.
The proposed solution is to separate the two locks.
ListCA, and the related …
=> HDDS-9061. Possible dead-lock in SCM initialization due to certificate operations.

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/heatmap/HeatMapServiceImpl.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/heatmap/HeatMapUtil.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/heatmap/TestHeatMapInfo.java
Code refactoring which will have better manageability as well as Bucket level access count fix.
https://issues.apache.org/jira/browse/HDDS-9087
Tested using existing test cases in TestHeatMapInfo
=> HDDS-9087. Ozone Recon Heatmap code refactoring and Bucket level access count fix

hadoop-hdds/docs/content/design/symmetric-token-signatures.md
Update Ozone document for symmetric block token
https://issues.apache.org/jira/browse/HDDS-8631
=> HDDS-8631. Update Ozone document for symmetric block token

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequest.java
Remove the redundant getBucketInfo call in OMKeyCreateRequest
The getBucketInfo method is called twice in OMKeyCreateRequest, so far it seems like it only needs to be called once, and although getBucketInfo is a relatively lightweight read from FullTableCache, it's still a good idea to remove the redundancy
https://issues.apache.org/jira/browse/HDDS-8996
=> HDDS-8996. Remove the redundant getBucketInfo call in OMKeyCreateRequest

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/SnapshotInfo.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmSnapshotInfo.java, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SstFilteringService.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestSnapshotInfo.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestSstFilteringService.java
Added sstFiltered Flag in snapshot info table.
https://issues.apache.org/jira/browse/HDDS-9129
Existing Unit test changes
=> HDDS-9129. Add SSTFiltered flag in SnapshotInfo table.

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketSetPropertyRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/OMVolumeSetQuotaRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/volume/TestOMVolumeSetQuotaRequest.java
skip linked bucket for space quota check when setting volume quota
https://issues.apache.org/jira/browse/HDDS-9139
UT cases added
=> HDDS-9139. Can't set volume space quota on volume if volume has linked bucket

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
Part of HDDS-7240 (#3770) unfortunately got lost during a previous conflict resolution.
https://issues.apache.org/jira/browse/HDDS-9152
- All existing tests should pass.
=> HDDS-9152. Part of HDDS-7240 is missing due to incorrect conflict resolution

hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestOmDBInsightEndPoint.java
This is a patch for [HDDS-8964](https://issues.apache.org/jira/browse/HDDS-8964) with addition to resolve compile issue with [HDDS-9101](https://issues.apache.org/jira/browse/HDDS-9101) ([failed CI](https://github.com/apache/ozone/actions/runs/5853773657/job/15868438276) on master after merge)
https://issues.apache.org/jira/browse/HDDS-8964
CI on my fork: https://github.com/dombizita/ozone/actions/runs/5854746261
=> HDDS-8964. Create a separate endpoint for summary for various SCM Insights and OM Insights - addendum: fix compile error

hadoop-hdds/docs/content/concept/OzoneManager.md
Fixing the alignment of deleted table info in OzoneManager.md
https://issues.apache.org/jira/browse/HDDS-8937
Ran hugo serve in hadoop-hdds/ozone
=> HDDS-8937. Fixing the documentation layout of persisted state of OM

.github/workflows/ci.yml, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/security/RootCARotationHandlerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/security/RootCARotationManager.java, hadoop-ozone/dist/src/main/compose/ozonesecure-ha/root-ca-rotation.yaml, hadoop-ozone/dist/src/main/compose/ozonesecure/root-ca-rotation.yaml
https://issues.apache.org/jira/browse/HDDS-9156
=> HDDS-9156. cert-rotation acceptance test is failing randomly

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/BlockID.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ContainerBlockID.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/storage/ContainerProtocolCalls.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestFailureHandlingByClient.java
Add assertions to BlockOutputStream for verifying request order.
https://issues.apache.org/jira/browse/HDDS-9243
=> HDDS-9243. Add assertions to BlockOutputStream.

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/exceptions/OMException.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerClientProtocol.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAMetadataOnly.java, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/OMClientRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketSetPropertyRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotDeleteRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/upgrade/OMCancelPrepareRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/upgrade/OMFinalizeUpgradeRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/OMRequestTestUtils.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/upgrade/TestOMCancelPrepareRequest.java
Set S3 credentials for the thread to flush stripes (EC output stream)
https://issues.apache.org/jira/browse/HDDS-9196
manually, the test case is described in the Jira ticket
=> HDDS-9196. Fix ECKeyOutputStream for secure S3

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java
The change for #5191 seems to be causing locking and timeout issues. This PR reverts that commit so we can rethink the approach.
https://issues.apache.org/jira/browse/HDDS-9151
Existing tests cover this.
=> Revert "HDDS-9151. Close EC Pipeline when container transitions to closing (#5191)"

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMPerformanceMetrics.java
Sort Datanodes metric in OM getKeyInfo.
https://issues.apache.org/jira/browse/HDDS-9271
Standard CI.
=> HDDS-9271. SortDatanodes metric in OM getKeyInfo

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestSnapshotDeletingService.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotPurgeRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotCache.java
Invalidate snapshot cache once snapshot gets purged
https://issues.apache.org/jira/browse/HDDS-9173
Integration test
=> HDDS-9173. Invalidate snapshot cache once snapshot gets purged

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/db.json, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/routes.json, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/components/overviewCard/overviewCard.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/insights/om/om.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/overview/overview.tsx
1) Take user to Key Deletion page on click of "Overview" pending deletion card.
2) Take user to Pending Open Keys page on click of "Overview" pending open keys.
3) API param "prevKey" of deletePending keys and open keys seems not passing value.
4) First Time in API Call no need to call prevKey as we sending empty.
5) Pending Key Deletion from Overview Page need to delete.
https://issues.apache.org/jira/browse/HDDS-9076
Manually
[1.webm](https://github.com/apache/ozone/assets/112169209/45cc847a-3168-451f-9d16-c19c9fc6eeaf)
=> HDDS-9076. Recon UI OMDB Insights Changes and Improvements

hadoop-hdds/rocks-native/src/main/java/org/apache/hadoop/hdds/utils/db/managed/package-info.java, hadoop-hdds/rocks-native/src/main/java/org/apache/hadoop/hdds/utils/package-info.java
Fixing the package info of the rocks native packages
https://issues.apache.org/jira/browse/HDDS-8815
=> HDDS-8815. Fixing the package info of rocks native packages

hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/security/TestRootCARotationManager.java
https://issues.apache.org/jira/browse/HDDS-9249
Test the TestRootCARotationManager in personal repo with 10 * 10 iteration. 
https://github.com/ChenSammi/ozone/actions/runs/6147386344/job/16678776945
=> HDDS-9249. Intermittent failure in TestRootCARotationManager#testProcessingCheck

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestReplicationSupervisor.java
https://issues.apache.org/jira/browse/HDDS-9240
=> HDDS-9240. Test container schema V2 and V3 replica mutual import

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileRequest.java
Improving the builder usage of OmKeyInfo and OmDirectoryInfo
https://issues.apache.org/jira/browse/HDDS-8648
Unit tests
=> HDDS-8648. Improving OmKeyInfo.Builder and OmDirectoryInfo.Builder usage

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/SimpleContainerDownloader.java
LOG improvement when downloading container fails from DN
https://issues.apache.org/jira/browse/HDDS-9289
github CI pipeline
=> HDDS-9289. LOG improvement when downloading container fails from DN

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/DatanodeLayoutStorage.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/endpoint/VersionEndpointTask.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestDatanodeStateMachine.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/container/common/TestEndPoint.java
Correct setting of clusterId in the dnlayoutversion/version file.
https://issues.apache.org/jira/browse/HDDS-5560
Unit test
=> HDDS-5560. Update clusterId to correct value.

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyDeleteRequest.java
OMKeyDeleteRequest Remove redundant code
https://issues.apache.org/jira/browse/HDDS-9336
existing UT
=> HDDS-9336. OMKeyDeleteRequest Remove redundant code

hadoop-ozone/insight/src/main/java/org/apache/hadoop/ozone/insight/scm/ReplicaManagerInsight.java
Adding ReplicationManagerMetrics to ReplicaManagerInsight
https://issues.apache.org/jira/browse/HDDS-6155
CLI ozone insight metrics scm.replica-manager
`sh-4.2$ ozone insight metrics scm.replica-manager
Metrics for `scm.replica-manager` (SCM closed container replication manager)
ReplicationManager Container Metrics
Open Containers: 1
Closing Containers: 0
Quasi-closed Containers: 0
Closed Containers: 0
Deleting Containers: 0
Deleted Containers: 0
Recovering Containers: 0
UnderReplicated Containers: 0
MisReplicated Containers: 0
OverReplicated Containers: 0
Missing Containers: 0
Unhealthy Containers: 0
Empty Containers: 0
Open Unhealthy Containers: 0
Stuck QuasiClosed Containers: 0
ReplicationManager EC Metrics
EcReplicationCmdsSentTotal: 0
EcDeletionCmdsSentTotal: 0 …
=> HDDS-6155. Adding ReplicationManagerMetrics to ReplicaManagerInsight

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/RangeKeysGenerator.java
To address the current limitation in RangeKeysGenerator, which restricts object creation to a maximum size of 2 GB by utilizing [ContentGenerator](https://github.com/apache/ozone/blob/master/hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/ContentGenerator.java). 
This approach involves writing random keys from a finite buffer, rather than using the existing RandomUtils#nextBytes method, consequently resolving the issue of accommodating long values for objectSizeInBytes.
https://issues.apache.org/jira/browse/HDDS-9374
- Existing robot tests should cover the code changes.
- Green CI/CD checks: https://github.com/tanvipenumudy/ozone/actions/runs/6391542021
- Tested the changes manually with 4 GB object size:
```
$ ozone sh volume create voltest
$ ozone sh bucket create …
```
=> HDDS-9374. RangeKeysGenerator freon tool should support objects creation >2GB

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/components/navBar/navBar.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/heatMap/heatmap.tsx
Hetamap can be accessed after disabling config flag. so addressed this bug with this PR.
https://issues.apache.org/jira/browse/HDDS-9231
Manually
=> HDDS-9231. Recon: Heatmap Page can be directly accessed even after disable config

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/ContainerTestUtils.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestHddsDispatcher.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/interfaces/TestHandler.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCloseContainerCommandHandler.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCreatePipelineCommandHandler.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestDeleteBlocksCommandHandler.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestStorageVolumeChecker.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueHandler.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainer.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/container/common/TestEndPoint.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/metrics/TestContainerMetrics.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainerWithTLS.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestSecureOzoneContainer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/server/TestContainerServer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/server/TestSecureContainerServer.java
Reduce the duplicate create Container/Context code for test code
https://issues.apache.org/jira/browse/HDDS-9421
Existing test
=> HDDS-9421. Reduce the duplicate create Container/Context code for test code

hadoop-ozone/dist/src/main/compose/ozonesecure-ha/test.sh
scmha/scm-leader-transfer.robot is not run in any test suite currently.
Aim is to execute this test for atleast one of the suite.
[HDDS-9453](https://issues.apache.org/jira/browse/HDDS-9453)
CI
=> HDDS-9453. scm-leader-transfer.robot not part of any acceptance test

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/OzoneSecretManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/GrpcOzoneManagerServer.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SstFilteringService.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/TrashPolicyOzone.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerDoubleBuffer.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerStateMachine.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/AbstractKeyDeletingService.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/MultipartUploadCleanupService.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/OMRangerBGSyncService.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/OpenKeyCleanupService.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/SnapshotDiffCleanupService.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/OzoneDelegationTokenSecretManager.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestGrpcOzoneManagerServer.java
Add the ability to specify a prefix for threads created for the OM service in recon, the test has been implemented for the background services of OM will be adding more after discussion.
https://issues.apache.org/jira/browse/HDDS-9334
=> HDDS-8721. Improve thread names in OM.

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockInputStream.java
Add extra messages to log the pipeline and block id to help troubleshoot the problem in the future.
https://issues.apache.org/jira/browse/HDDS-9326
Log only change.
=> HDDS-9326. HBase HMaster unable to start due to IllegalArgumentException: NO_REPLICA_FOUND.

hadoop-hdds/docs/content/feature/Decommission.md
SCM Decommissioning doc is updated with a note to delete the private key as part of decommissioning. This has to be done until we have certificate revocation support.
[HDDS-9409](https://issues.apache.org/jira/browse/HDDS-9409)
Doc change. This doesn't need any testing.
=> HDDS-9409. Update SCM decommissioning documentation.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMServiceManager.java
(Please fill in changes proposed in this fix
1. **Title:** Fix log message in SCMServiceManager#start
2. **Description:** Corrected log message for SCMServiceManager#start  
(https://issues.apache.org/jira/browse/HDDS-9469)
Only log message modified
=> HDDS-9469. Fix log message in SCMServiceManager#start

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotCreateRequest.java
As part of the change [#5262](https://github.com/apache/ozone/pull/5262) for fixing of [HDDS-9199](https://issues.apache.org/jira/browse/HDDS-9199), exceptions in snapshot chain creation were changed ISE and same is [thrown back from OMSnapshotCreateRequest](https://github.com/apache/ozone/blob/master/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotCreateRequest.java#L282)
Because of this, if snapshot creation fails due to snapshot chain corruption, `OMSnapshotCreateRequest` throws `IllegalStateException` which is not handled by the state machine.
This change is to handle `IllegalStateException` in `OMSnapshotCreateRequest` so that state machine can handle it properly.
https://issues.apache.org/jira/browse/HDDS-9685
=> HDDS-9685. Handle IllegalStateException in OMSnapshotCreateRequest

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/AbstractKeyDeletingService.java
Add a handle delete with non-ratis
Currently, deleting directory data will not be deleted in non ratis mode
https://issues.apache.org/jira/browse/HDDS-9687
=> HDDS-9687. Handle key deletion with OM Ratis disabled

hadoop-hdds/docs/content/feature/Snapshot.md
Update list of snapshot apis to include info details
```
bash-4.2$ ozone sh snapshot info --help
Usage: ozone sh snapshot info [-hV] <value> <snapshotName>
returns information about an existing snapshot
```
https://issues.apache.org/jira/browse/HDDS-9891
NA
=> HDDS-9891. [snapshot] Update list of snapshot apis to include info details

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/SCMCommonPlacementPolicy.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineProvider.java
Changing the log message to warn level instead of error.
https://issues.apache.org/jira/browse/HDDS-9756
=> HDDS-9756. Verbose log messages regarding pipeline creation failure

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CommandDispatcher.java
There are some redundant comments in CommandDispatcher, and the purpose of this PR is to delete them.
Details: HDDS-9643
https://issues.apache.org/jira/browse/HDDS-9643
This PR is mainly related to documentation and does not require too much testing.
=> HDDS-9643. Remove duplicate (and outdated) comment in CommandDispatcher

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMStorage.java
Elaborating OM VERSION file mismatch message to include what could be the possible reasons for mismatch and how to overcome it.
https://issues.apache.org/jira/browse/HDDS-9880
Tested on a cluster.
=> HDDS-9880. Elaborate OM VERSION file mismatch message.

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestContainerImporter.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestWritableECContainerProvider.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/server/TestSCMBlockProtocolServer.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/upgrade/TestOMVersionManager.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/upgrade/TestOmVersionManagerRequestFactory.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/acl/TestParentAcl.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/ReconTestInjector.java, pom.xml
There are some leftover JUnit4 imports in modules already migrated.
It looks like ban of JUnit4 import did not catch these, due to two problems:
1. `org.junit.*` does not match sub-packages (`org.junit.rules.*` etc.)
2. basic analysis of `TestKeyValueContainer` does not find `org.junit.Assume`, have to enable full parsing
https://issues.apache.org/jira/browse/HDDS-9935
Verified that the build catches the following banned imports:
```
[ERROR] 	in file: org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java
[ERROR] 		org.junit.Assume 	(Line: 62, Matched by: org.junit.**)
[ERROR] 	in file: org/apache/hadoop/ozone/container/replication/TestContainerImporter.java
[ERROR] 		org.junit.rules.TemporaryFolder 	(Line: 47, Matched by: org.junit.**)
[ERROR] 	in file: …
```
=> HDDS-9935. Remove leftover JUnit4 imports from modules already migrated

hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/TestOzoneClientProducer.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/TestVirtualHostStyleFilter.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestEndpointBase.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectHead.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectPut.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/metrics/TestS3GatewayMetrics.java
Improve assertTrue/assertFalse assertions in hadoop-ozone/s3gateway
(see parent task [HDDS-9951](https://issues.apache.org/jira/browse/HDDS-9951) for details)
[HDDS-10032](https://issues.apache.org/jira/browse/HDDS-10032)
https://github.com/wzhallright/ozone/actions/runs/7382866944
=> HDDS-10032. Improve assertTrue assertions in ozone-s3gateway

hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/TestOmUtils.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/TestOzoneAcls.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/client/io/TestSelectorOutputStream.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/lock/TestKeyPathLock.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/lock/TestOzoneManagerLock.java
Improve `assertTrue`/`assertFalse` assertions in `hadoop-ozone/common`.
https://issues.apache.org/jira/browse/HDDS-10030
CI:
https://github.com/adoroszlai/ozone/actions/runs/7379165208
=> HDDS-10030. Improve assertTrue assertions in ozone-common

hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestContainerEndpoint.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestFeaturesEndPoint.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestOmDBInsightEndPoint.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/filters/TestAdminFilter.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/fsck/TestContainerHealthTask.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/heatmap/TestHeatMapInfo.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconContainerManager.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconNodeManager.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconPipelineManager.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestContainerKeyMapperTask.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestOmUpdateEventValidator.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestReconTaskControllerImpl.java
Improve assertTrue/assertFalse assertions in hadoop-ozone/recon
(see parent task [HDDS-9951](https://issues.apache.org/jira/browse/HDDS-9951) for details)
[HDDS-10034](https://issues.apache.org/jira/browse/HDDS-10034)
https://github.com/wzhallright/ozone/actions/runs/7444762108
=> HDDS-10034. Improve assertTrue assertions in ozone-recon

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
There are some error messages in StorageContainerManager, the purpose of this PR is to fix them.
Details: HDDS-10082
https://issues.apache.org/jira/browse/HDDS-10082
It is necessary to ensure that the unit test can pass smoothly.
=> HDDS-10082. Fix some wrong prompts in StorageContainerManager

hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/checksum/TestReplicatedFileChecksumHelper.java
Improve assertTrue/assertFalse assertions in hadoop-ozone/client
(see parent task [HDDS-9951](https://issues.apache.org/jira/browse/HDDS-9951) for details)
[HDDS-10031](https://issues.apache.org/jira/browse/HDDS-10031?filter=-1)
https://github.com/wzhallright/ozone/actions/runs/7457343156
=> HDDS-10031. Improve assertTrue assertions in ozone-client

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeDecommissionManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestNodeDecommissionManager.java
There are some obsolete codes in NodeDecommissionManager, and the purpose of this PR is to clean them up.
https://issues.apache.org/jira/browse/HDDS-10087
Need to ensure that unit tests pass.
=> HDDS-10087. Clean up code in NodeDecommissionManager

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/AbstractTestECKeyOutputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/Test2WayCommitInRatis.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBCSID.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockDataStreamOutput.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStreamWithFailures.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestCloseContainerHandlingByClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerReplicationEndToEnd.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachine.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineFailures.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestDeleteWithInAdequateDN.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestDiscardPreallocatedBlocks.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestFailureHandlingByClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestFailureHandlingByClientFlushDelay.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestHybridPipelineOnDatanode.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestMultiBlockWritesWithDnFailures.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneAtRestEncryption.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientMultipartUploadWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientRetriesOnExceptionFlushDelay.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientRetriesOnExceptions.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientForAclAuditLog.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestValidateBCSIDOnRestart.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestWatchForCommit.java
Improve assertTrue assertions in hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client
(see parent task [9551](https://issues.apache.org/jira/browse/HDDS-9551) for details)
[HDDS-10092](https://issues.apache.org/jira/browse/HDDS-10092)
https://github.com/wzhallright/ozone/actions/runs/7470034758
=> HDDS-10092. improve assertTrue assertions in client integration tests

hadoop-hdds/docs/content/feature/Topology.zh.md
Translate the "Topology awareness" doc into Mandarin Chinese
Translated the "Topology awareness" part into Mandarin Chinese.
https://issues.apache.org/jira/browse/HDDS-7558
Verified by loading "hadoop-hdds/docs/target/classes/docs/zh/feature/topology.html" in a local browser.
=> HDDS-7558. Translate "Topology awareness" doc into Mandarin Chinese

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
Add test for putting key with ECReplicationConfig by shell.
https://issues.apache.org/jira/browse/HDDS-10159
Unit tests.
=> HDDS-10159. Add test for putting key with ECReplicationConfig by shell.

hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestBufferPool.java, hadoop-hdds/client/src/test/java/org/apache/hadoop/ozone/client/io/TestECBlockReconstructedStripeInputStream.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerPersistence.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestContainerReader.java, hadoop-hdds/erasurecode/src/test/java/org/apache/ozone/erasurecode/TestCodecRegistry.java, hadoop-hdds/erasurecode/src/test/java/org/apache/ozone/erasurecode/rawcoder/TestRawCoderBase.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStore.java, hadoop-hdds/rocks-native/src/test/java/org/apache/hadoop/hdds/utils/db/managed/TestManagedSSTDumpIterator.java, hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/rocksdiff/TestRocksDBCheckpointDiffer.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestDatanodeAdminMonitor.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestNodeDecommissionMetrics.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestSCMSafeModeManager.java, hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestUsageInfoSubcommand.java
Improve assertTrue assertions in remaining hdds modules
[HDDS-9981](https://issues.apache.org/jira/browse/HDDS-9981)
https://github.com/wzhallright/ozone/actions/runs/7652157636
=> HDDS-9981. Improve assertTrue assertions in remaining hdds modules

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestFailoverWithSCMHA.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestGetCommittedBlockLengthAndPutKey.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestRatisPipelineLeader.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMDbCheckpointServlet.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMInstallSnapshotWithHA.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMMXBean.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMNodeManagerMXBean.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMSnapshot.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSecretKeySnapshot.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSecretKeysApi.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestStorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestXceiverClientGrpc.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestXceiverClientManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerStateManagerIntegration.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/node/TestDecommissionAndMaintenance.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestMultiRaftSetup.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestNode2PipelineMap.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineClose.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestSCMPipelineMetrics.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestCommitWatcher.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestContainerCommandsEC.java
Improve assertTrue assertions in hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm
[HDDS-10096](https://issues.apache.org/jira/browse/HDDS-10096)
https://github.com/wzhallright/ozone/actions/runs/7662998974
=> HDDS-10096. Improve assertTrue assertions in SCM integration tests

hadoop-hdds/docs/content/feature/OM-HA.md
There are a few documentation typos/grammatical errors which need to be addressed under OM High Availability section.
Details are mentioned in JIRA
https://issues.apache.org/jira/browse/HDDS-10260
This is a documentation change and doesn't require testing.
=> HDDS-10260. Fix typos in OM HA documentation

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneManagerSnapshotAcl.java
This change adds an integration test to verify that prefix ACLs work properly with snapshots.
HDDS-8793
Ran newly added test locally and fork branch.
=> HDDS-8793. Added integration test to confirm prefix Acls work properly with snapshots

hadoop-hdds/docs/content/concept/Datanodes.md, hadoop-hdds/docs/content/concept/OzoneManager.md, hadoop-hdds/docs/content/concept/Recon.md, hadoop-hdds/docs/content/concept/StorageContainerManager.md, hadoop-hdds/docs/content/feature/OM-HA.md
There are a few documentation typos/grammatical errors which need to be addressed under Architecture section.
Details are mentioned in JIRA
https://issues.apache.org/jira/browse/HDDS-10261
This is a documentation change and doesn't require testing.
=> HDDS-10261. Fix typos in Architecture Documentation

hadoop-ozone/dist/src/main/compose/ozone/prometheus.yml
https://issues.apache.org/jira/browse/HDDS-10433
Follow steps outlined in https://github.com/apache/ozone/blob/master/hadoop-ozone/dist/src/main/compose/ozone/README.md#add-ons
and inspect the endpoints (I used 5 Datanodes in all).
=> HDDS-10433. Fix Datanode prometheus endpoint in docker setup.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ContainerImporter.java
There are some duplicate logs in ContainerImporter, the purpose of this PR is to simplify them.
https://issues.apache.org/jira/browse/HDDS-10444
Ensure existing unit tests pass.
=> HDDS-10444. Reduce string concatenation in ContainerImporter#importContainer

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestStorageContainerManager.java
HDDS-10090.Clean up TestStorageContainerManager
Several goals in this jira have been achieved:
* Disabled test cases related to non-HA to HA change. This used to be not supported scenario, but was recently implemented in [HDDS-9897](https://issues.apache.org/jira/browse/HDDS-9897). Since that task also added a new test case, testSCMReinitializationWithHAEnabled and testSCMReinitializationWithHAUpgrade can be removed now.
* Thread.currentThread().sleep() can be replaced with Thread.sleep().
* Replace usage of GenericTestUtils.getTempPath with `@TempDir`.
The below items are not fixed yet, I will post some uncertain parts to the PR discussion.
* Test cases can now use MiniOzoneCluster wrapped in try-with-resources blocks to ensure the cluster is shut down …
=> HDDS-10090. Clean up TestStorageContainerManager

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/ContainerScannerConfiguration.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestContainerScannerConfiguration.java
enable container scanner by default. 
https://issues.apache.org/jira/browse/HDDS-10485
existing unit tests
=> HDDS-10485. Enable container scanner by default.

hadoop-hdds/docs/content/interface/ReconApi.zh.md
Update Chinese translation to Recon Architecture to match English . The updated filename is ReconApi.zh.md. 
https://issues.apache.org/jira/browse/HDDS-10492
It‘s only Markdown file, don't test.
=> HDDS-10492. [Doc] Update zh translation to Recon Architecture

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/BaseFreonGenerator.java
Fix spelling mistake in Freon error message
https://issues.apache.org/jira/browse/HDDS-10549
NA
=> HDDS-10549. Fix spelling mistake in Freon error message

hadoop-hdds/docs/content/security/SecuringOzoneHTTP.zh.md
HDDS-5570. security/SecuringOzoneHTTP.md translation
Translated security/SecuringOzoneHTTP.md page into Chinese
https://issues.apache.org/jira/browse/HDDS-5570
hugo serve
=> HDDS-5570. security/SecuringOzoneHTTP.md translation

hadoop-hdds/docs/content/tools/Admin.zh.md
HDDS-5571. tools/Admin.md translation
Translated tools/Admin.md page into Chinese
https://issues.apache.org/jira/browse/HDDS-5571
hugo serve
=> HDDS-5571. tools/Admin.md translation

pom.xml
https://issues.apache.org/jira/browse/HDDS-10792
=> HDDS-10792. Bump netty to 4.1.109.Final

pom.xml
https://issues.apache.org/jira/browse/HDDS-10815
https://github.com/rohit-kb/ozone/actions/runs/8964476874
=> HDDS-10815. Upgrade Spring Framework to 5.3.34

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientRatis.java
Merge [HDDS-10780](https://issues.apache.org/jira/browse/HDDS-10780) into HDDS-7593 branch.
https://issues.apache.org/jira/browse/HDDS-10700
Verified in cluster
=> HDDS-10700. Merge HDDS-10780 into HBase feature branch.

hadoop-hdds/docs/content/start/OnPrem.md
This was discussed during a talk in Community Over Code EU
https://issues.apache.org/jira/browse/HDDS-10976
NA
=> HDDS-10976. Fix outdated reference to Ozone Datanode running within HDFS

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/heatMap/heatmap.tsx
Recon Heatmap - Not allowing user to select timerange if no data available
Recon Heatmap - Not allowing user to select timerange if no data available. If in last 24H, if no data available, it doesn't allow user to select different time range. HeatMap page continue to show "No Data Available".
https://issues.apache.org/jira/browse/HDDS-10852
Manually
Before this PR
After this PR
=> HDDS-10852. Recon Heatmap - Not allowing user to select timerange if no data available

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java
There is some redundant code in the XceiverServerRatis class, and we should simplify it.
https://issues.apache.org/jira/browse/HDDS-11062
It is necessary to ensure that the unit test passes smoothly.
=> HDDS-11062. Code cleanup in the XceiverServerRatis class

hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - DeleteKey Metrics.json
Created a new dashboard and added visualisations for all the required delete key Metrics.
https://issues.apache.org/jira/browse/HDDS-10561
The patch has been tested over a Grafana.
Here are some snaphots :
=> HDDS-10561. Dashboard for delete key metrics

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java
There are some redundant codes in DatanodeStateMachine, and the purpose of this PR is to optimize them.
https://issues.apache.org/jira/browse/HDDS-11082
We need to ensure that the unit tests pass normally.
=> HDDS-11082. Code cleanup in the DatanodeStateMachine class

hadoop-ozone/dist/src/shell/conf/om-audit-log4j2.properties, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/audit/OMSystemAction.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
system audit log framework is added for OM. This is added with having log for startup of OM. This can be used further to added logs for below operation:
- internal request like open file cleanup, purge directory, ...
- other operation critical for debugging
https://issues.apache.org/jira/browse/HDDS-11306
- verified logs over docker and below is the result,
=> HDDS-11306. OM support system audit log

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java
Some unused code was introduced in DatanodeStateMachine. The purpose of this PR is to clean it up.
https://issues.apache.org/jira/browse/HDDS-11401
https://github.com/jianghuazhu/ozone/actions/runs/10655796465
=> HDDS-11401. Code cleanup in DatanodeStateMachine

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java
Removed some unused constants from OzoneConsts.
https://issues.apache.org/jira/browse/HDDS-11464
unit tests
=> HDDS-11464. Removed unused constants from OzoneConsts.

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/cache/NoTableCache.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/cache/TableCache.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/cache/TestTableCache.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmBucketInfo.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneManagerHASnapshot.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneTenantShell.java, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/lock/FSOPrefixLocking.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/lock/KeyLocking.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/lock/OmLockOpr.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/lock/OmRequestLockUtils.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/execution/BucketQuotaResource.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/execution/FollowerRequestExecutor.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/execution/LeaderRequestExecutor.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/execution/OMBasicStateMachine.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/execution/OMGateway.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/execution/OmBucketInfoQuotaTracker.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/execution/PoolExecutor.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/OMClientRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/OMPersistDbRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/upgrade/OMPrepareRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerProtocolServerSideTranslatorPB.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestDirectoryDeletingService.java
Changes it consists of:
1. Granular locking
2. removal cache
2. NO_Cache Table (but currently disabled for test case verification)
4. bucket quota no-cache
5. upgrade prepare support
6. parallel execution via RPC thread
Pending:
- new optimized flow
- test cases and cleanup
- further optmization and benchmark
https://issues.apache.org/jira/browse/HDDS-11455
- Existing test cases
=> HDDS-11403. granular lock and cache

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAUtils.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java
Rename snapshot dir constant in OzoneConsts
https://issues.apache.org/jira/browse/HDDS-11578
unit tests
=> HDDS-11578. Rename snapshot dir constant in OzoneConsts

hadoop-hdds/docs/content/tools/Debug.md, hadoop-hdds/docs/content/tools/Debug.zh.md
Many filtering options were introduced recently for `ozone debug ldb` command. The usage of these commands and it's options is documented so that users can find it easy to  understand the format of using the commands.
Many samples of the various options are included.
https://issues.apache.org/jira/browse/HDDS-11584
Checked using `hugo serve`:
Tools page:
Debug page:
=> HDDS-11584. Document ozone debug ldb command

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/OzoneClientConfig.java, hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/DomainPeer.java, hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/DomainSocketFactory.java
Implemented a factory to create DomainSocket.
https://issues.apache.org/jira/browse/HDDS-11622 
It will be tested in next patch.
=> HDDS-11622. Support domain socket creation

hadoop-hdds/docs/content/feature/SCM-HA.md
There are some errors in SCM-HA.md. It needs to be changed from 'ozone scm --daemon start' to 'ozone --daemon start scm'. I have fixed it.
https://issues.apache.org/jira/browse/HDDS-11652
It doesn't need testing because it's only documentation.
=> HDDS-11652. Fix SCM start command in SCM-HA doc

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/AbstractKeyDeletingService.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/DirectoryDeletingService.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/OMRangerBGSyncService.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestDirectoryDeletingService.java
Backport some deletion bug fixes commits from master to ozone-1.4.
https://github.com/xichen01/ozone/actions/runs/11749045124
=> Backport some deletion bug fixes commits from master to ozone-1.4

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/navBar/navBar.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/plots/heatmapPlot.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/constants/heatmap.constants.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/pages/heatmap/heatmap.less, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/pages/heatmap/heatmap.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/routes-v2.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/types/heatmap.types.ts
HDDS-11163. Improve Heatmap page UI
* This PR adds new Heatmap Page with improved designs.
* It also makes the heatmap plot a bit more compact and improves subtle text cues like bolding of tooltip information
* In this implementation we double check if heatmap is enabled in case someone directly access the Heatmap page via the url and provide appropriate error message in such a scenario
https://issues.apache.org/jira/browse/HDDS-11163
=> HDDS-11163. Improve Heatmap page UI

.asf.yaml
Update "About" description for Ozone in GitHub.  Copy tagline from new website:
https://github.com/apache/ozone-site/blob/52c086dbc5c3a1960527e3a67ce461c3a2669677/docusaurus.config.js#L32
https://issues.apache.org/jira/browse/HDDS-11890
n/a
=> HDDS-11890. Update project description in GitHub

hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestQuotaRepairTask.java
Tweak TestQuotaRepairTask to work with OM Ratis enabled, and fix the tests.
https://issues.apache.org/jira/browse/HDDS-11868
CI: 
https://github.com/chungen0126/ozone/actions/runs/12394456554
=> HDDS-11868. Enable OM Ratis in TestQuotaRepairTask

hadoop-ozone/dev-support/checks/_mvn_unit_report.sh
HDDS-11551 added summary for integration check in CI workflow, listing failed, crashed and leaking tests ([example](https://github.com/apache/ozone/actions/runs/12317391929#summary-34380288338)).  It should also list fork timeouts.
https://issues.apache.org/jira/browse/HDDS-11941
CI:
https://github.com/adoroszlai/ozone/actions/runs/12349473449
=> HDDS-11941. Include fork timeout in integration check summary

hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java
As titled, please take a look, thanks!
[HDDS-11986](https://issues.apache.org/jira/browse/HDDS-11986)
It can be tested by CI, if the unit tests are passed or not.
=> HDDS-11986. Enable SCM Ratis in TestSCMNodeManager

hadoop-ozone/httpfsgateway/pom.xml, hadoop-ozone/ozone-manager/pom.xml
Enable sortpom in ozone-manager and httpfsgateway
HDDS-12105
(https://github.com/nandakumar131/ozone/actions/runs/12850918505)
=> HDDS-12105. Enable sortpom in ozone-manager and httpfsgateway.

hadoop-ozone/fault-injection-test/mini-chaos-tests/pom.xml, hadoop-ozone/fault-injection-test/network-tests/pom.xml, hadoop-ozone/fault-injection-test/pom.xml, hadoop-ozone/integration-test/pom.xml
Enable sortpom in integration-test and fault-injection-test.
HDDS-12106
CI Run: https://github.com/nandakumar131/ozone/actions/runs/12903012669
=> HDDS-12106. Enable sortpom in integration-test and fault-injection-test.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/ContainerSafeModeRule.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/DataNodeSafeModeRule.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/HealthyPipelineSafeModeRule.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/OneReplicaPipelineSafeModeRule.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/SafeModeRuleFactory.java
Move SafeModeRule names to respective rules.
HDDS-11798
CI Run: https://github.com/nandakumar131/ozone/actions/runs/12941471100
=> HDDS-11798. Move SafeModeRule names to respective rules.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeConfiguration.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/AbstractOverReplicationHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerReplicaOp.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerReplicaPendingOps.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyReplicationManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisOverReplicationHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestMoveManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestContainerReplicaPendingOps.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECContainerReplicaCount.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisOverReplicationHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java
Backporting important RM fixes from master to the 1.4 branch. This PR is to test the CI before merging from the CLI.
=> HDDS-12127. [DO NOT MERGE] Backport Recent Replication Manager fixes to the 1.4 branch

hadoop-hdds/docs/content/design/short-circuit-read.md, hadoop-hdds/docs/content/feature/Short-Circuit-Read.md, hadoop-hdds/docs/content/feature/Short-Circuit-Read.zh.md
Document the precondition and configuration of short-circuit local read feature
https://issues.apache.org/jira/browse/HDDS-11626
1. previewed in intellij
2. passed " ./hadoop-ozone/dev-support/checks/docs.sh"
=> HDDS-11626. Document short-circuit read feature

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/TestContainerStateMachine.java
This PR removes duplicate license header
https://issues.apache.org/jira/browse/HDDS-12543
CI: https://github.com/ptlrs/ozone/actions/runs/13778946230
=> HDDS-12543. Remove duplicate license information

hadoop-hdds/interface-admin/src/main/resources/proto.lock, hadoop-hdds/interface-client/src/main/resources/proto.lock, hadoop-hdds/interface-server/src/main/resources/proto.lock, hadoop-ozone/interface-client/src/main/resources/proto.lock
HDDS-12576. [Ozone 2.0] Update proto.lock files
* Follow the release instructions to update proto.lock files https://ozone-site-v2.staged.apache.org/docs/developer-guide/project/release-guide/
https://issues.apache.org/jira/browse/HDDS-12576
No production code change.
=> HDDS-12576. [Ozone 2.0] Update proto.lock files

hadoop-hdds/docs/content/design/s3-object-lifecycle-management.md
Design proposal for S3 Object LifeCycle Management feature. Design document is shared in the link.
https://issues.apache.org/jira/browse/HDDS-8342
NA
=> HDDS-8342. S3 Object LifeCycle Management design doc.

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestStorageVolumeChecker.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestVolumeSetDiskChecks.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerMarkUnhealthy.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/TestHddsServerUtils.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/fsck/TestContainerMapper.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmInit.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneTenantShell.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestGrpcOzoneManagerServer.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/protocolPB/TestGrpcOmTransport.java
Fix `UnusedPrivateField` violations in tests.
https://issues.apache.org/jira/browse/HDDS-12921
https://github.com/adoroszlai/ozone/actions/runs/14712065574
=> HDDS-12921. UnusedPrivateField violations in tests

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmLCAction.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmLCExpiration.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmLCFilter.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmLCRule.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmLifecycleConfiguration.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmLifecycleRuleAndOperator.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmLCExpiration.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmLCFilter.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmLCRule.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmLifeCycleConfiguration.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmLifecycleRuleAndOperator.java, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/codec/OMDBDefinition.java
Introduce Lifecycle-related proto message definitions and logic for converting proto objects to java objects.
This PR include https://github.com/apache/ozone/pull/8275, the current code is used for review. Please merge the current code after merge https://github.com/apache/ozone/pull/8275
https://issues.apache.org/jira/browse/HDDS-12781
Unit test 
https://github.com/xichen01/ozone/actions/runs/14431257574
=> HDDS-12781. Implement LifecycleConfiguration proto

hadoop-ozone/dist/src/main/compose/ozonesecure-ha/docker-compose.yaml, hadoop-ozone/dist/src/main/compose/ozonesecure-ha/s3g-virtual-host.yaml, hadoop-ozone/dist/src/main/compose/ozonesecure-ha/scm-decommission.yaml
Backport HDDS-12974. to fix failed dicker tests
[HDDS-12792](https://issues.apache.org/jira/browse/HDDS-12792)
https://github.com/xichen01/ozone/actions/runs/15398569871
=> HDDS-12974. Docker could not parse extra host IP (#8397)

hadoop-hdds/docs/content/security/SecurityWithRanger.md
Update and fix documentation of Apache Ranger.
https://issues.apache.org/jira/browse/HDDS-13206
UI preview
=> HDDS-13206. [Docs] Update documentation for Apache Ranger

pom.xml
Bump Ratis and related dependencies.
https://issues.apache.org/jira/browse/HDDS-12070
https://github.com/adoroszlai/ozone/actions/runs/15856535858
=> HDDS-12070. Bump Ratis to 3.2.0

hadoop-ozone/dist/src/main/smoketest/ozone-fi/README.md
HDDS-13251. Update Byteman usage README license
* Just updating the README for Byteman Usage
HDDS-13251
N/A
=> HDDS-13251. Update Byteman usage README license

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/SCMSafeModeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMMXBean.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
Remove unused forceExitSafeMode field and related methods from SCMSafeModeManager and SCMMXBean.
https://issues.apache.org/jira/browse/HDDS-12957
Pass all existing tests.
https://github.com/erichung9060/ozone/actions/runs/15967444840
=> HDDS-12957. Remove unused SafeModeStatus#forceExitSafeMode field

hadoop-hdds/docs/content/interface/CyberDuckOzoneS3.md, hadoop-hdds/docs/content/interface/S3.md
HDDS-13359. [Docs] Accessing Ozone using Cyberduck.
* Add user tutorial for accessing Ozone S3 using Cyberduck, a popular S3 client.
* Generated-by: ChatGPT o4-mini. Prompt: 
> Write a user tutorial for accessing Ozone S3 using Cyberduck.
>
https://issues.apache.org/jira/browse/HDDS-13359
The steps were drafted by ChatGPT, and then manually verified.
=> HDDS-13359. [Docs] Accessing Ozone using Cyberduck.

hadoop-hdds/docs/content/feature/Trash.md
HDDS-13368. [Docs] Add user doc for Ozone Trash.
* Added a user doc for Ozone Trash under Features section.
* Generated-by: Google Gemini Cli, Gemini 2.5 Pro. Prompt:
> Read jira https://issues.apache.org/jira/browse/HDDS-13368 and implement it.
https://issues.apache.org/jira/browse/HDDS-13368
Draft prepared by Gemini Cli; Reviewed and updated manually.
=> HDDS-13368. [Docs] Add user doc for Ozone Trash.

hadoop-hdds/docs/content/concept/Comparison.md
HDDS-13372. [Docs] Compare Ozone to other storage technologies
* Generated-by: ChatGPT 4o, reviewed by Google Gemini Code Assistant.
https://issues.apache.org/jira/browse/HDDS-13372
=> HDDS-13372. [Docs] Compare Ozone to other storage technologies

hadoop-hdds/docs/content/interface/Ofs.md
HDDS-13421. [Docs] Ofs migration guide
* Assisted by Gemini and ChatGPT, I reviewed every single OFS, FileSystem API, DistributedFileSystem API, and cross referenced every single NameNode audit logs to produce this migration guide.
* Generated-by: Google Gemini 2.5 Pro + Gemini Cli, ChatGPT 4o.
https://issues.apache.org/jira/browse/HDDS-13421
=> HDDS-13421. [Docs] Ofs migration guide

hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/repair/ldb/TestLdbRepair.java
Added a unit test for `ozone repair ldb compact` command
https://issues.apache.org/jira/browse/HDDS-13121
Green CI on my fork: https://github.com/Tejaskriya/ozone/actions/runs/16291736112/job/46003994269#step:13:4603
=> HDDS-13121. Add unit test for ldb repair command

pom.xml
https://issues.apache.org/jira/browse/HDDS-13529
https://github.com/rohit-kb/ozone/actions/runs/16645738992
=> HDDS-13529. Upgrade commons-lang3 to 3.18.0

hadoop-hdds/docs/content/tools/Repair.md
Added a document for ozone repair commands.
This lists the usage of all the commands and subcommands under repair.
[HDDS-12196](https://issues.apache.org/jira/browse/HDDS-12196)
Verified the html page on a local browser.
=> HDDS-12196. Document ozone repair cli

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/interfaces/Handler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/utils/HddsVolumeUtil.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/AvailableSpaceFilter.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/CapacityVolumeChoosingPolicy.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/RoundRobinVolumeChoosingPolicy.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/StorageVolume.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeChoosingPolicyFactory.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/diskbalancer/DiskBalancerService.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/diskbalancer/DiskBalancerServiceMetrics.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/diskbalancer/policy/DefaultContainerChoosingPolicy.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/diskbalancer/policy/DefaultVolumeChoosingPolicy.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/diskbalancer/policy/DiskBalancerVolumeChoosingPolicy.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainer.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/ContainerController.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/diskbalancer/TestDiskBalancerService.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/diskbalancer/TestDiskBalancerTask.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/node/TestVolumeChoosingPolicy.java
1. reserve committed space in volume choosing policy
2. read lock source container before move the container
https://issues.apache.org/jira/browse/HDDS-12439
new and existing unit test
=> HDDS-12439. [DiskBalancer] Reserve committed space during volume choosing process

hadoop-hdds/docs/content/feature/om-bootstrapping-with-snapshots.md
Adding the google doc attached on the jira as a markdown in the design docs section.
https://issues.apache.org/jira/browse/HDDS-13543
=> HDDS-13543. [Docs] Design doc for OM bootstrapping process with snapshots.

pom.xml
https://issues.apache.org/jira/browse/HDDS-13527
https://github.com/rohit-kb/ozone/actions/runs/16768324182
=> HDDS-13527. Upgrade nimbus-jose-jwt to 10.4 and gson to 2.13.1

hadoop-ozone/dist/src/main/license/bin/LICENSE.txt, hadoop-ozone/dist/src/main/license/jar-report.txt, pom.xml
https://issues.apache.org/jira/browse/HDDS-13610
https://github.com/rohit-kb/ozone/actions/runs/17150374273/job/48660652035
=> HDDS-13610. Upgrade guava to 33.4.8-jre

hadoop-ozone/common/dev-support/findbugsExcludeFile.xml, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/util/TestRadixTree.java
Fix spotbugs warnings in TestRadixTree
https://issues.apache.org/jira/browse/HDDS-12379
Existing unit and integration tests
=> HDDS-12379. Fix spotbugs warnings in TestRadixTree

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotCache.java
It appears that in presence of a lot of snapshots these warnings are flooding the OM logs. The change here is to rate limit the logs once per minute.
https://issues.apache.org/jira/browse/HDDS-13685
=> HDDS-13658. Limit Snapshot Cache size warning logs.

hadoop-hdds/docs/content/start/FromSource.md
HDDS-13691. [Docs] Add additional information regarding issues encountered on Apple Silicon builds
* Added additional steps to address issues when building on Apple Silicon Macs.  See Jira for the error messages.
https://issues.apache.org/jira/browse/HDDS-13691
Please create an issue in ASF JIRA before opening a pull request, and you need to set the title of the pull
request which starts with the corresponding JIRA issue number. (e.g. HDDS-XXXX. Fix a typo in YYY.)
Tested documentation steps on local dev machine
=> HDDS-13691. [Docs] Add additional information regarding issues encountered on Apple Silicon builds
