apache/ozone

dev-support/annotations/src/main/java/org/apache/ozone/annotations/package-info.java
hadoop-ozone/dev-support/checks/rat.sh

* Collect rat failures from the new `dev-support/annotations` directory, too.
* Add missing license header.
* Reduce duplication by looping over the dirs to be checked.
https://issues.apache.org/jira/browse/HDDS-6606
Verified that the check properly fails due to license violation:
```
$ ./hadoop-ozone/dev-support/checks/rat.sh
...
dev-support/annotations/target/rat.txt: !????? src/main/java/org/apache/ozone/annotations/package-info.java
```
Then added the missing header and re-ran the check:
```
$ ./hadoop-ozone/dev-support/checks/rat.sh
...
$ echo $?
0
```
https://github.com/adoroszlai/hadoop-ozone/runs/6081893903

HDDS-6606. Rat check failure ignored for ozone-annotation-processing

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestDirectoryDeletingServiceWithFSO.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedDDSWithFSO.java

`TestDirectoryDeletingServiceWithFSO` was intermittently timing out at `assertSubPathsCount`.  This method has a `waitFor`, but the condition cannot change, since it compares two fixed long values.  It can only pass if wait is not necessary and the condition is true at the time of the call.
The fix is to get the actual value for each check during the wait.
https://issues.apache.org/jira/browse/HDDS-6189
100x passed:
https://github.com/adoroszlai/hadoop-ozone/runs/6107144162
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2200070046

HDDS-6189. Intermittent failure in TestDirectoryDeletingServiceWithFSO

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerLayoutVersion.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/ChunkUtils.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/FilePerBlockStrategy.java

EC: Fix Datanode block file INCONSISTENCY during heavy load.
Problem descriptions and analysis in the JIRA below.
In brief, we should get the file size by using the fileChannel instead of the file.
https://issues.apache.org/jira/browse/HDDS-6614
Manual test with experiment programs, seen in the JIRA above.

HDDS-6614. EC: Fix Datanode block file INCONSISTENCY during heavy load.

---

dev-support/ci/selective_ci_checks.bats
dev-support/ci/selective_ci_checks.sh

_rat_ check may fail if license is missing from non-root README files.  Thus it should be triggered for such changes in PRs.
(found during review of #3132)
https://issues.apache.org/jira/browse/HDDS-6405
Changed expected outcome in unit test.
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/1924479431

HDDS-6405. Selective checks: run rat for readme change

---

.github/workflows/post-commit.yml
dev-support/ci/selective_ci_checks.bats
dev-support/ci/selective_ci_checks.sh

Separate build and compile checks: _compile_ is run only for Java and related changes.  _build_ is also needed to get the binary tarball for running acceptance tests.
https://issues.apache.org/jira/browse/HDDS-6617
Updated test cases in `selective_ci_checks.bats`.
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2196208880

HDDS-6617. Skip compile(11) for non-java changes

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAMetadataOnly.java

Remove flaky tag for TestOzoneManagerHAMetadataOnly#testOMProxyProviderFailoverOnConnectionFailure.
https://issues.apache.org/jira/browse/HDDS-6639
1000x TestOzoneManagerHAMetadataOnly#testOMProxyProviderFailoverOnConnectionFailure:  https://github.com/kaijchen/ozone/actions/runs/2216059091
Regular CI: https://github.com/kaijchen/ozone/actions/runs/2217457986

HDDS-6639. Remove flaky tag for testOMProxyProviderFailoverOnConnectionFailure

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHA.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAWithData.java

Fix integration test `TestOzoneManagerHAWithData#testTwoOMNodesDown()`.
https://issues.apache.org/jira/browse/HDDS-6522
100x testTwoOMNodesDown (before): https://github.com/kaijchen/ozone/actions/runs/2215651435
100x testTwoOMNodesDown (after): https://github.com/kaijchen/ozone/actions/runs/2215651878
Regular CI: https://github.com/kaijchen/ozone/actions/runs/2215934619

HDDS-6522. Fix TestOzoneManagerHAWithData#testTwoOMNodesDown

---

hadoop-hdds/docs/pom.xml
hadoop-ozone/dev-support/checks/build.sh

Install Hugo if necessary during build.  Advantages:
* one fewer dependency to manually install
* improve stability by using fixed Hugo version, newer ones might break compatibility
Reuse existing `docs.sh` (run in CI by _basic (docs)_ check) for this purpose.
Allow skipping the execution of `docs.sh` via the new `skipDocs` property.  This is set by `build.sh`, so that other checks do not fail in case of doc validation problems, which should be caught by the _basic (docs)_ check.
https://issues.apache.org/jira/browse/HDDS-6512
```
$ rm -fr .dev-tools/hugo
$ which hugo
/usr/local/bin/hugo
$ mvn -am -pl :hdds-docs clean compile
...
[INFO] --- exec-maven-plugin:1.3.1:exec (default) @ hdds-docs ---
Skip installing hugo, as it's already available on PATH.
Start building sites …
| EN | ZH …
```

HDDS-6512. Install Hugo during build if needed

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerMetrics.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancer.java

The scenario is as follows:
1. ContainerBalancer trying to move the following containers:
1. container 1, took 20 minutes
1. container 2, took 40 minutes
1. container 3, took 60 minutes
2. When checking if a move finishes, the timeout is set to 30minutes.
3. When ContainerBalancer waited 20 minutes, it records container1 as finished.
4. Then Containerbalancer will wait another 30 minutes for container 2. Although container 2 took 40 minutes, ContainerBalancer will still record container 2 as a finished move.
5. The same issue happens when checking move result for container 3.
https://issues.apache.org/jira/browse/HDDS-6553
unit test.

HDDS-6553. Incorrect timeout when checking balancer iteration result.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAMetadataOnly.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/acl/TestParentAcl.java

Added flaky tag to some tests.
1. HDDS-6335. TestParentAcl#testKeyAcl
https://github.com/apache/ozone/runs/6168965490?check_suite_focus=true#step:5:1859
2. HDDS-5819, HDDS-6451. TestRootedOzoneFileSystem#testRenameToTrashEnabled
https://github.com/kaijchen/ozone/runs/6151453278?check_suite_focus=true#step:4:3038
3. HDDS-6477, HDDS-6642. TestOzoneManagerHAMetadataOnly#testListVolumes:
https://github.com/kaijchen/ozone/runs/6150362670?check_suite_focus=true#step:4:3142
4. HDDS-6644. TestOzoneManagerHAMetadataOnly#testReadRequest:
https://github.com/kaijchen/ozone/runs/6150362734?check_suite_focus=true#step:4:3558
5. HDDS-6645. TestOzoneFileSystem#testTrash
https://github.com/kaijchen/ozone/runs/6150521370?check_suite_focus=true#step:4:2934
6. HDDS-6646. …

HDDS-6647. Tag some known flaky tests

---

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/container/InfoSubcommand.java
hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/container/TestInfoSubCommand.java

[HDDS-6579](https://issues.apache.org/jira/browse/HDDS-6579) added a flag to hide newly added information in the `ozone admin container info` command for compatibility reasons. However the flag is not necessary, as the changes are not incompatible. It is also not desirable to have a new command flag for every piece of new information that is to be added to every command. It will result in commands with many flags that have to be passed all the time to get the full set of information.
There is a community discussion about compatibility where the consensus is that we provide compatibility for these admin commands via the JSON output, and that the formatting and output of the "human readable" formats can change over time:
https://lists.apache.org/thread/5gqnbstv1pznwmcvx7txspj1qrksy7gl
For …

HDDS-6636. Revert "HDDS-6579. Add commandline argument for Container Info command. (#3306)"

---

hadoop-ozone/ozonefs-shaded/pom.xml

Shaded Ozone FS jars currently include Hadoop Thirdparty libs:
```
$ cd hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/share/ozone/lib
$ unzip -t ozone-filesystem-hadoop3-1.3.0-SNAPSHOT.jar | grep 'org.apache.hadoop.thirdparty.*class' | sort | head
testing: org/apache/hadoop/thirdparty/protobuf/AbstractMessage$Builder.class   OK
testing: org/apache/hadoop/thirdparty/protobuf/AbstractMessage$BuilderParent.class   OK
testing: org/apache/hadoop/thirdparty/protobuf/AbstractMessage.class   OK
testing: org/apache/hadoop/thirdparty/protobuf/AbstractMessageLite$Builder$LimitedInputStream.class   OK
testing: org/apache/hadoop/thirdparty/protobuf/AbstractMessageLite$Builder.class   OK
testing: org/apache/hadoop/thirdparty/protobuf/AbstractMessageLite.class   OK
testing: …
```

HDDS-6626. Exclude Hadoop Thirdparty from shaded Ozone FS jars

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/container/ReplicationManagerReport.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/container/TestReplicationManagerReport.java

If the client attempts to de-serialize a ReplicationManagerReport object from protobuf, and there is a metric passed from the server to the client which the client does not know about (eg the server and client are at different versions), the client will throw in IllegalArgumentException currently. Instead if should just ignore any metrics it does not know about.
https://issues.apache.org/jira/browse/HDDS-6632
New unit test to reproduce the issue and confirm it is fixed.

HDDS-6632. ReplicationManagerReport should handle unknown metric in protobuf

---

hadoop-ozone/integration-test/pom.xml
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java

Config keys from `ozone-s3gateway` are no longer tested by `TestOzoneConfigurationFields` due to a dependency change.  This PR restores that check.
https://issues.apache.org/jira/browse/HDDS-6651
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2227536590

HDDS-6651. Restore S3 Gateway config key check in TestOzoneConfigurationFields

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/BackgroundPipelineScrubber.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestBackgroundPipelineScrubber.java

```
TestBackgroundPipelineScrubber.testRun() fails intermittently for me locally, with this trace:
2022-04-27 17:20:44,888 [main] INFO  pipeline.BackgroundPipelineScrubber (BackgroundPipelineScrubber.java:start(123)) - Starting Pipeline Scrubber Service.
2022-04-27 17:20:44,890 [main] INFO  pipeline.BackgroundPipelineScrubber (BackgroundPipelineScrubber.java:notifyStatusChanged(85)) - Service BackgroundPipelineScrubber transitions to RUNNING.
2022-04-27 17:20:47,905 [main] INFO  pipeline.BackgroundPipelineScrubber (BackgroundPipelineScrubber.java:stop(140)) - Stopping Pipeline Scrubber Service.
2022-04-27 17:20:47,905 [PipelineScrubberThread] WARN  pipeline.BackgroundPipelineScrubber (BackgroundPipelineScrubber.java:run(158)) - PipelineScrubberThread is interrupted, exit
Wanted but not …
```

HDDS-6661. TestBackgroundPipelineScrubber.testRun() fails intermittently

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/BackgroundPipelineCreator.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/BackgroundPipelineScrubber.java

On my laptop, TestSCMSafeModeManager.testSafeModePipelineExitRule() always takes just over 200 seconds. Checking a few PR runs, it does not seem to be slow on PRs, just locally.
Debugging the code, it seems to hang in the BackgroundPipelineCreator.stop() method, where it is waiting for the tread to join:
```
public void stop() {
if (!running.compareAndSet(true, false)) {
LOG.warn("{} is not running, just ignore.", THREAD_NAME);
return;
}
LOG.info("Stopping {}.", THREAD_NAME);
// in case RatisPipelineUtilsThread is sleeping
synchronized (monitor) {
monitor.notifyAll();
}
try {
thread.join();  //  ----> Hangs here
} catch (InterruptedException e) {
LOG.warn("Interrupted during join {}.", THREAD_NAME);
Thread.currentThread().interrupt();
}
}
```
It is clearly hanging as the background thread …

HDDS-6658. BackgroundPipelineCreator does not always stop quickly

---

hadoop-hdds/tools/pom.xml
hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/UsageInfoSubcommand.java
hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestUsageInfoSubcommand.java

Add the option for the command `ozone admin datanode usageinfo` to output as JSON/
https://issues.apache.org/jira/browse/HDDS-6641
New unit tests. Also verified the JSON out using a docker-compose cluster:
```
bash-4.2$ ozone admin datanode usageinfo -m --json
[ {
"datanodeDetails" : {
"level" : 0,
"cost" : 0,
"uuid" : "cf92907e-ed4d-49e5-9e4e-0283f8815e80",
"uuidString" : "cf92907e-ed4d-49e5-9e4e-0283f8815e80",
"ipAddress" : "172.23.0.7",
"hostName" : "ozone_datanode_1.ozone_default",
"ports" : [ {
"name" : "REPLICATION",
"value" : 9886
}, {
"name" : "RATIS",
"value" : 9858
}, {
"name" : "RATIS_ADMIN",
"value" : 9857
}, {
"name" : "RATIS_SERVER",
"value" : 9856
}, {
"name" : "STANDALONE",
"value" : 9859
} ],
"setupTime" : 0,
"persistedOpState" : "IN_SERVICE", …
```

HDDS-6641. datanode usageinfo CLI should provide JSON output option

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/endpoint/HeartbeatEndpointTask.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/states/endpoint/TestHeartbeatEndpointTask.java
hadoop-hdds/interface-server/src/main/proto/ScmServerDatanodeHeartbeatProtocol.proto
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/events/SCMEvents.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/CommandQueueReportHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeInfo.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeMetrics.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeHeartbeatDispatcher.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/SimpleMockNodeManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestCommandQueueReportHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/server/TestSCMDatanodeHeartbeatDispatcher.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/container/testutils/ReplicationNodeManagerMock.java

[HDDS-6554](https://issues.apache.org/jira/browse/HDDS-6554) added the current command counts for all commands queued on a Datanode to the datanode heartbeat. This Jira will process that information on SCM and store it inside the DatanodeInfo object so other parts of SCM can reference it.
https://issues.apache.org/jira/browse/HDDS-6567
New Unit Tests

HDDS-6567. Store datanode command queue counts from heartbeat in DatanodeInfo in SCM

---

hadoop-hdds/client/src/test/java/org/apache/hadoop/ozone/client/io/ECStreamTestUtil.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/ozone/client/io/TestBlockInputStreamFactoryImpl.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/ozone/client/io/TestECBlockInputStream.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/ozone/client/io/TestECBlockInputStreamProxy.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/ozone/client/io/TestECBlockReconstructedInputStream.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/ozone/client/io/TestECBlockReconstructedStripeInputStream.java
hadoop-ozone/client/pom.xml
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/io/TestKeyInputStreamEC.java
hadoop-ozone/pom.xml

Some new EC tests are in `integration-test`, but are real unit tests.  This PR moves them out to `hdds-client` and `ozone-client`, depending on where the classes being tested are.
https://issues.apache.org/jira/browse/HDDS-6684
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2254570634

HDDS-6684. Move unit tests out of integration

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java
hadoop-ozone/dist/src/main/compose/ozonesecure/docker-config
hadoop-ozone/dist/src/main/compose/upgrade/compose/ha/docker-config
hadoop-ozone/dist/src/main/compose/upgrade/compose/non-ha/docker-config
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/container/metrics/TestSCMContainerManagerMetrics.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestMultiRaftSetup.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/upgrade/TestHDDSUpgrade.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecureOzoneCluster.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManager.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBCSID.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachine.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineFailures.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineFlushDelay.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/ratis/TestDnRatisLogParser.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManagerHA.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/node/TestDecommissionAndMaintenance.java

Revert #2637.  The PR was merged regardless of my [concern](https://github.com/apache/ozone/pull/2637#discussion_r778629887) about changing the default setting without providing seamless upgrade path.
It turns out that enabling Ratis by default is indeed causing problems during upgrade. SCM fails to start with:
```
Configuration ozone.scm.ratis.enable cannot be used until SCM upgrade has been finalized
```
https://issues.apache.org/jira/browse/HDDS-5740
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2237408109

Revert "HDDS-5740. Enable ratis by default for SCM."

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerDoubleBuffer.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerStateMachine.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerDoubleBufferWithOMResponse.java

https://issues.apache.org/jira/browse/HDDS-6685

HDDS-6685. Follower OM crashed when validating S3 auth info.

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/InnerNodeImpl.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NetUtils.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NetworkTopologyImpl.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/Node.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NodeImpl.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/net/TestNetworkTopologyImpl.java

In NodeImpl, the relation of ancestor is decided as follows:
```
@Override
public boolean isAncestor(Node node) {
return this.getNetworkFullPath().equals(PATH_SEPARATOR_STR) ||
node.getNetworkLocation().startsWith(this.getNetworkFullPath()) ||
node.getNetworkFullPath().equalsIgnoreCase(this.getNetworkFullPath()); 
```
The corner case is as follows:
```
Node n1: "/rc"
Node n2: "/rc1/dc/1.1.1.1"
```
The result of n1.isAncestor(n2) is false, while in fact n1 is not n2's ancestor.
https://issues.apache.org/jira/browse/HDDS-6640
unit test

HDDS-6640. Node.isAncestor might return incorrect result

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java

The code related to checking heartbeat is as follows.
```
L1    while (context.getState() != DatanodeStates.SHUTDOWN) {
L2      try {
L3        LOG.debug("Executing cycle Number : {}", context.getExecutionCount());
L4        long heartbeatFrequency = context.getHeartbeatFrequency();
L5        nextHB.set(Time.monotonicNow() + heartbeatFrequency);
L6        context.execute(executorService, heartbeatFrequency,
L7            TimeUnit.MILLISECONDS);
L8      } catch (InterruptedException e) {
L9        // Someone has sent interrupt signal, this could be because
L10      // 1. Trigger heartbeat immediately
L11      // 2. Shutdown has be initiated.
L12      Thread.currentThread().interrupt();
L13    } catch (Exception e) {
L14      LOG.error("Unable to finish the execution.", e);
L15    } …
```

HDDS-6377.  Redundant loop while doing triggerHeartbeat in DatanodeStateMachine.

---

hadoop-ozone/dist/src/main/compose/ozone/test.sh
hadoop-ozone/dist/src/main/compose/ozonesecure/test.sh

`ozonefs.robot` test has two parameters: FS type (ofs, o3fs) and bucket type (normal, link).  `ozone` environment (unsecure) tests only 2 combinations, based on the assumption that the parameters are independent, i.e. bucket type-specific behavior is not at the FS level.  But `ozonesecure` tests all 2x2 combinations.  We could save a few minutes by running only 2 combinations there as well.  To be on the safe side, run the other 2 combinations.  So all combinations are still covered together by the two environments.
https://issues.apache.org/jira/browse/HDDS-6673
Verified that only `ozonefs-ofs-bucket` and `ozonefs-o3fs-link` combinations are run in `ozonesecure`:
https://github.com/adoroszlai/hadoop-ozone/runs/6235762566#step:5:307

HDDS-6673. Reduce OzoneFS test combinations in ozonesecure

---

hadoop-ozone/dist/src/main/compose/ozonescripts/test.sh
hadoop-ozone/dist/src/main/smoketest/basic/single_node.robot

HDDS-4556 added smoketest for `start-ozone.sh` and `stop-ozone.sh`.  However, OM is not exercised by pipeline operations, only DN and SCM.  Thus the test passes even if OM is not started successfully.  This can be reproduced by temporarily changing `start.sh` to not start OM by commenting lines:
https://github.com/apache/ozone/blob/81b6bbad14141ddbfad0aa1ff97044490dc9aa79/hadoop-ozone/dist/src/main/compose/ozonescripts/start.sh#L25-L26
```
$ cd hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/ozonescripts
$ ./test.sh
...
Pipeline :: Test ozone admin pipeline command                         | PASS |
7 tests, 7 passed, 0 failed
...
$ echo $?
0
```
This change adds another test case that verifies OM, too.
https://issues.apache.org/jira/browse/HDDS-6669
Verified that the test fails with …

HDDS-6669. Exercise OM in ozonescripts environment

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/BackgroundPipelineCreator.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/BackgroundPipelineScrubber.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestBlockManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestCloseContainerEventHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestBackgroundPipelineScrubber.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestHealthyPipelineSafeModeRule.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestOneReplicaPipelineSafeModeRule.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestSCMSafeModeManager.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconPipelineManager.java

There are a couple of places in the new scrubber code and the existing scrubber code in PipelineManagerImpl, where it uses Time.monotonicNow() to decide if the Safemode interval has passed, or if a pipeline has been Closed long enough etc. The unit tests do not correctly test these scenarios, as we just set the time to zero so there is no delay, otherwise the tests would need sleep calls, which will make them slow.
In ReplicationManager, we addressed this problem by injecting a Clock dependency. See MonotonicClock - if we inject this as a dependency to the scrubber code, then we can inject a MonotonicClock for runtime, but inject TestClock for tests. Then you can properly test the safemode delay by advancing the clock between check calls. Same for pipelines - we can check ALLOCATED ones …

HDDS-6655. Use injected clocks in PipelineManagerImp and BackgroundPipelineScrubber to ease testing

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainer.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerCheck.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerData.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerMetadataInspector.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/BlockUtils.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/KeyValueContainerLocationUtil.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/KeyValueContainerUtil.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeStoreSchemaThreeImpl.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeTable.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/ContainerTestUtils.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestKeyValueContainerData.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestSchemaOneBackwardsCompatibility.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerPersistence.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/ContainerTestVersionInfo.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueBlockIterator.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerCheck.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerIntegrityChecks.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerMetadataInspector.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestTarContainerPacker.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/impl/TestBlockManagerImpl.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestContainerReader.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainer.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBTable.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/Table.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java

KeyValueContainer operation adaptation for schema v3 containers, includes:
- create & load
- close
- delete
Not includes the following since they are in some dedicated standalone services:
- block deletion
- import & export
https://issues.apache.org/jira/browse/HDDS-6542
Extending all container schema related UTs.

HDDS-6542. [Merge rocksdb in datanode] KeyValueContainer operation adaptation for schema v3 containers.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileCreateRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMAllocateBlockRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMAllocateBlockRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCommitPartRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/file/OMFileCreateResponseWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMAllocateBlockResponse.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMAllocateBlockResponseWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyCreateResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMAllocateBlockResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMAllocateBlockResponseWithFSO.java

As we disscussed in https://issues.apache.org/jira/browse/HDDS-5867.
The quota we are currently implementing have a bug. When allocate block, we add usedBytes. If the key fails to write, the Clean Open Key Service subtracts the usedBytes. But the bucket may no longer exist when the open key is being deleted, or may have been deleted and re-created with the same name. This causes usedBytes update error.
We can only update the usedByte when commit key. In this way, failed keys are not counted in the usedByte（we‘ll add service in the background to delete them). This is reasonable for the user. This is garbage data and belongs to the Ozone system. And the Ozone system itself cleans this data.
https://issues.apache.org/jira/browse/HDDS-6556
existing UT, also add new UT.

HDDS-6556. Check quota while allocate and update usedBytes when commit.

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/BlockUtils.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingService.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeStoreSchemaThreeImpl.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeStoreSchemaTwoImpl.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DeleteTransactionStore.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java

BlockDeletingService adaptation for schema v3 containers.
https://issues.apache.org/jira/browse/HDDS-6543
turned on previously ignored UT for schema v3.

HDDS-6543. [Merge rocksdb in datanode] BlockDeletingService adaptation for schema v3 containers.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerPrepare.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

HDDS-6685 changed install snapshot logic in OM, restarting various OM components during the process.  However, it does not wait for OM RPC server to stop, leading to intermittent `BindException` a bit later during start.
```
2022-05-05 13:41:05,653 [pool-2368-thread-1] ERROR om.OzoneManager (ExitUtils.java:terminate(133)) - Terminating with exit status 1: Failed to start RPC Server.
java.net.BindException: Problem binding to [localhost:39581] java.net.BindException: Address already in use; For more details see:  http://wiki.apache.org/hadoop/BindException
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Delegati …
```

HDDS-6703. Disable failing testPrepareDownedOM until Ratis upgrade

---

hadoop-ozone/dist/src/main/compose/ozone/test.sh
hadoop-ozone/dist/src/main/compose/ozonesecure/test.sh
hadoop-ozone/dist/src/main/smoketest/s3/bucketcreate.robot
hadoop-ozone/dist/src/main/smoketest/s3/bucketdelete.robot
hadoop-ozone/dist/src/main/smoketest/s3/buckethead.robot
hadoop-ozone/dist/src/main/smoketest/s3/webui.robot

Some S3 tests are independent of the bucket type parameter.  Currently these are run for regular bucket, link, encrypted bucket and EC bucket.  Save some time by running only once per environment (secure/unsecure).
https://issues.apache.org/jira/browse/HDDS-6675
Verified that tagged tests are run only once, e.g.:
https://github.com/adoroszlai/hadoop-ozone/runs/6236210729#step:5:344
https://github.com/adoroszlai/hadoop-ozone/runs/6236210729#step:5:463

HDDS-6675. Avoid repeating some S3 tests for different bucket types

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ECBlockOutputStream.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockOutputStreamEntry.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MockDatanodeStorage.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java

Sending the current block group length on putblock call
https://issues.apache.org/jira/browse/HDDS-6659
Added test to verify.

HDDS-6659: EC: Add BlockGroupLen info as part of PutBlock in EC Writes for helping in recovery.

---

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/FollowerAppendLogEntryGenerator.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/LeaderAppendLogEntryGenerator.java

RATIS-1560 removed the `RaftProperties(boolean)` constructor (while cleaning up XML-related code for security).
This PR prepares for upgrade to upcoming Ratis 2.3.0.
https://issues.apache.org/jira/browse/HDDS-6716
Compiled Ozone.
https://github.com/adoroszlai/hadoop-ozone/runs/6354676594

HDDS-6716. Adopt RATIS-1560

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestRatisPipelineLeader.java

RATIS-1497 moved `GrpcClientProtocolService` to a different package and made its `LOG` private.  This breaks `TestRatisPipelineLeader`.  HDDS-6461 addressed this while upgrading to a Ratis snapshot (on feature branch).
This PR only cherry-picks the compatibility change without the version bump.
(cherry-picks commit eaef7eabc7df6e9e0ff0f7acefd4afcdc73918e3)
Note: I think this should be merged manually using Git CLI, to preserve author information.
https://issues.apache.org/jira/browse/HDDS-6715
```
$ mvn -DfailIfNoTests=false -Dtest=TestRatisPipelineLeader clean test
...
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 72.781 s - in org.apache.hadoop.hdds.scm.TestRatisPipelineLeader
```

HDDS-6715. Avoid using GrpcClientProtocolService.LOG

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java

If Bucket versioning is set to true, the key should be able to keep multiple versions. And the keyToDelete in OMKeyCommitRequest will not be deleted. At this time the keyToDelete's usedBytes also should not detracted.
https://issues.apache.org/jira/browse/HDDS-6709
UT has added.

HDDS-6709. Fix bucket usedBytes while versioning is true.

---

dev-support/annotations/pom.xml
hadoop-hdds/container-service/pom.xml
hadoop-hdds/server-scm/pom.xml
hadoop-ozone/insight/pom.xml
hadoop-ozone/ozone-manager/pom.xml
hadoop-ozone/ozonefs-common/pom.xml
hadoop-ozone/recon/pom.xml
hadoop-ozone/s3gateway/pom.xml
hadoop-ozone/tools/pom.xml
pom.xml

Remove unnecessary dependency `spotbugs`.  Only `spotbugs-annotations` are needed.
Depending on `spotbugs` allows using classes from `commons-lang` instead of `commons-lang3`.  Code compiles fine, but dependency is not available at runtime, resulting in `NoClassDefFoundError`.
```
\- com.github.spotbugs:spotbugs:jar:3.1.12:provided
...
+- commons-lang:commons-lang:jar:2.6:provided
```
https://issues.apache.org/jira/browse/HDDS-6507
Temporarily added offending import:
```diff
diff --git hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java
index 863b1b08c..373c80f8a 100644
--- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoi …
```

HDDS-6507. Spotbugs transitive dependencies may result in NoClassDefFound error

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRenameRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyRenameRequestWithFSO.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java

Path normalization missed in o3fs#renameKeyWithFSO, which will result in extra "/" in OM operations especially checkACLs logic.
Fix: Convert #pathToKey() on ozone client and perform #validateAndNormalizeKey() at OM RenameRequest.
https://issues.apache.org/jira/browse/HDDS-6708
Added UT.

HDDS-6708. [FSO] Make normalize keyPath on key rename request

---

.github/workflows/post-commit.yml
pom.xml

Currently integration tests are the slowest part of CI.  Increasing parallel runs can reduce wall-clock time required for the complete workflow.  There are two limiting factors: 1. constant overhead of compilation, 2. keeping split definitions manageable.
https://issues.apache.org/jira/browse/HDDS-6679
CI finished in 1.5 hours instead of 2 hours:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2253586336

HDDS-6679. Further splits integration tests

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ReplicationFactor.java
hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/pipeline/ListPipelinesSubcommand.java
hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/pipeline/TestListPipelinesSubCommand.java

The following command, which used to work before 8776430812, fails with current `master`, because `-t RATIS` is now also required for `--filterByFactor THREE` to be accepted:
```
$ ozone admin pipeline list -ffc THREE
ReplicationType cannot be null if replication is passed
```
To be backward compatible, it should accept factor without explicit replication type, and assume `RATIS`, similar to `ozone freon`.
https://issues.apache.org/jira/browse/HDDS-6734
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2309650310

HDDS-6734. ozone admin pipeline list CLI is not backward compatible

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ECContainerReplicaCount.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/states/TestECContainerReplicaCount.java

This change adds a class and tests intended to be used for checking if an EC container is over or under replicated, while also considering decommission and maintenance. Given the container details and replicas, there are a series of methods used to check for over and under replication. There are also methods to return the under or over replicated indexes. The intention of this class, is to be used by Replication manager and any other parts of the code that need to make decisions based on the replicated state of EC containers.
https://issues.apache.org/jira/browse/HDDS-6704
New unit tests

HDDS-6704. EC: ReplicationManager - create version of ContainerReplicaCounts applicable to EC

---

hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - Overall Metrics.json
hadoop-ozone/dist/src/main/compose/ozone/README.md
hadoop-ozone/dist/src/main/compose/ozone/prometheus.yml

New Grafana dashboard template.
1.  Support more Envs. Need to have the ```component``` label.
2. More dimensions of metrics.
3. Support HA situation. 
https://issues.apache.org/jira/browse/HDDS-6560
manual test

HDDS-6560. add general Grafana dashboard

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/SCMCommonPlacementPolicy.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/TestSCMCommonPlacementPolicy.java

In `SCMCommonPlacementPolicy.getResultSet()`, the abstract method of "chooseNode" will be invoked each time to get a valid node, the method declarition is as follows:
```
/**
* Choose a datanode according to the policy, this function is implemented
* by the actual policy class.
*
* @param healthyNodes - Set of healthy nodes we can choose from.
* @return DatanodeDetails
*/
public abstract DatanodeDetails chooseNode(
List<DatanodeDetails> healthyNodes); 
```
For this method, all current implementations of subclasses will remove the chosen node from healthyNodes, but seems this side effect is not explicitly clarified. 
For users trying to implement their own subclasses, they might forget this removal, which might return incorrect values. …

HDDS-6630. Explicitly remove node after being chosen

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
hadoop-ozone/dist/src/main/smoketest/security/ozone-secure-tenant.robot
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

This is a follow-up jira to [HDDS-6574](https://issues.apache.org/jira/browse/HDDS-6574) in the multi-tenancy branch.
See https://github.com/apache/ozone/pull/3298#discussion_r848659291 for the context.
https://issues.apache.org/jira/browse/HDDS-6625

HDDS-6625. [Multi-Tenant] Follow-up: Set owner of buckets created via S3 Gateway to actual user

---

hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/container/TestInfoSubCommand.java
hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/container/TestReportSubCommand.java
hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestContainerBalancerSubCommand.java
hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestDecommissionSubCommand.java
hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestListInfoSubcommand.java
hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestMaintenanceSubCommand.java
hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestRecommissionSubCommand.java
hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestUsageInfoSubcommand.java
hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/pipeline/TestListPipelinesSubCommand.java

Migrate tests in hdds-tools to JUnit5.
1. Substitute JUnit4 api with JUnit5 api.
2. ~~Replace static imports of assertions.~~
3. Do some minor cleanup (such as replacing `assertTrue` with `assertEquals` when possible).
Tests migrated:
```
./hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/pipeline/TestListPipelinesSubCommand.java
./hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestContainerBalancerSubCommand.java
./hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestRecommissionSubCommand.java
./hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestUsageInfoSubcommand.java
./hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestDecommissionSubCommand.java …
```

HDDS-6730. Migrate tests in hdds-tools to JUnit5

---

hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/scm/exceptions/TestSCMExceptionResultCodes.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/token/TestOzoneBlockTokenIdentifier.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/token/TokenVerifierTests.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/TestDefaultCertificateClient.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/keys/TestHDDSKeyGenerator.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/TestJsonUtils.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/events/TestEventQueue.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/events/TestEventQueueChain.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/events/TestEventWatcher.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/http/TestBaseHttpServer.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/http/TestHtmlQuoting.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/http/TestHttpRequestLog.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/http/TestHttpRequestLogAppender.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/http/TestHttpServer2.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/http/TestProfileServlet.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/http/TestPrometheusMetricsSink.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/http/TestRatisDropwizardExports.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStoreIterator.java

Migrate simple tests in hdds-server-framework to JUnit5, "simple" means without `@Rule` and `@Parameter`.
Also included some minor cleanups such as the parameter order in `assertEquals(expected, actual)`.
Tests migrated:
```
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/scm/exceptions/TestSCMExceptionResultCodes.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/token/TestOzoneBlockTokenIdentifier.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/token/TokenVerifierTests.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/TestDefaultCertificateClient.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/keys/TestHDDSKeyGenerator.java …
```

HDDS-6731. Migrate simple tests in hdds-server-framework to JUnit5

---

hadoop-hdds/client/src/test/java/org/apache/hadoop/ozone/client/io/TestECBlockReconstructedInputStream.java

Use fixed read buffer size instead of random one, which could even be 0.  Too small buffer leads to long execution times and intermittent timeouts.
(We can restore randomness, if desired, by enforcing minimum size.)
https://issues.apache.org/jira/browse/HDDS-6748
Repeated successfully 100x:
https://github.com/adoroszlai/hadoop-ozone/runs/6434203328
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/runs/6430180619#step:5:3562

HDDS-6748. Intermittent timeout in TestECBlockReconstructedInputStream#testReadDataWithUnbuffer

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMBlockProtocolServer.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

Fix some audit log calls where read/write category does not match the actual operation.
* add SCM, activate/deactivate pipeline are write ops
* get, list, lookup are read ops
https://issues.apache.org/jira/browse/HDDS-6742
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2315729409

HDDS-6742. Audit operation category mismatch

---

hadoop-hdds/docs/content/security/SecurityWithRanger.md
hadoop-hdds/docs/content/security/SecurityWithRanger.zh.md

Modified the Ozone integration Ranger documentation to indicate that the OZONE_CLASSPATH environment variable needs to be configured during the Ozone integration of Ranger to avoid the following errors:
```
[main] INFO org.apache.hadoop.ozone.security.OzoneDelegationTokenSecretManager: Loading token state into token manager.
[main] ERROR org.apache.hadoop.ozone.om.OzoneManagerStarter: OM start failed with exception
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.ranger.authorization.ozone.authorizer.RangerOzoneAuthorizer not found
at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2699)
at org.apache.hadoop.ozone.om.OzoneManager.getACLAuthorizerInstance(OzoneManager.java:716)
at …
```

HDDS-6657. Improve Ozone integrated Ranger configuration instructions

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAUtils.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/TestSCMHAUtils.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMBlockLocationFailoverProxyProvider.java

SCM during start sends `addSCM` request to its peers.  It tries to exclude itself from the target list:
https://github.com/apache/ozone/blob/40461504478182af509db7098d4e173011d27e5a/hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HAUtils.java#L119-L121
but `removeSelfId` does not work.  The bug is that it sets the generic `ozone.scm.nodes` property, leaving the SCM service-specific config key `ozone.scm.nodes.<service>` unchanged with 3 nodes.
https://issues.apache.org/jira/browse/HDDS-6749
Also added log message to show list of peers the fail-over proxy is created with.  From HA acceptance test:
```
scm2_1      | 2022-05-13 22:49:10,532 [main] INFO proxy.SCMBlockLocationFailoverProxyProvider: Created block location fail-over proxy with 2 nodes: …
```

HDDS-6749. SCM includes itself as peer in addSCM request

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/ReconstructECContainersCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCommandInfo.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinatorTask.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionSupervisor.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/package-info.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/ReconstructECContainersCommand.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ec/reconstruction/TestECReconstructionSupervisor.java

Added necessary classes at DN for reconstruction.
https://issues.apache.org/jira/browse/HDDS-6660
Will adding tests.

HDDS-6660: EC: Add the DN side Reconstruction Handler class.

---

hadoop-hdds/framework/pom.xml
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/TestCertificateClientInit.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/http/TestRatisNameRewrite.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/cache/TestTableCache.java

Tests migrated
```
./hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/TestCertificateClientInit.java
./hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/http/TestRatisNameRewrite.java
./hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/cache/TestTableCache.java
```
https://issues.apache.org/jira/browse/HDDS-6737
CI

HDDS-6737. Migrate parameterized tests in hdds-server-framework to JUnit5

---

hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/docs/content/feature/S3-Multi-Tenancy-Setup.md
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/exceptions/OMException.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
hadoop-ozone/dist/src/main/compose/ozonesecure/docker-config
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/multitenant/TestMultiTenantVolume.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneTenantShell.java
hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMultiTenantManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMultiTenantManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneAclUtils.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/tenant/OMTenantAssignAdminRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/tenant/OMTenantAssignUserAccessIdRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/tenant/OMTenantCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/tenant/OMTenantDeleteRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/tenant/OMTenantRevokeAdminRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/tenant/OMTenantRevokeUserAccessIdRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOMMultiTenantManager.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/OMRequestTestUtils.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/security/TestS3GetSecretRequest.java

Add a config key to enable or disable S3 Multi-Tenancy feature globally. When disabled, all S3 Multi-Tenancy read/write requests will be rejected, and multi-tenancy classes in OM will not be initialized.
Also adds config validation logic in OM, if one of the requirements are not met, S3 Multi-Tenancy will be automatically disabled despite the config key is enabled.
https://issues.apache.org/jira/browse/HDDS-6612

HDDS-6612. [Multi-Tenant] Add a config key to enable or disable S3 Multi-Tenancy feature

---

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestSchemaTwoBackwardsCompatibility.java

Add compatibility test between schema v3 & v2.
We have a compatibility UT for schema v2 & v1, and also v3 & v1, so it is better to have a similar one between v3 & v2.
https://issues.apache.org/jira/browse/HDDS-6754
This is just a new UT.

HDDS-6754. [Merge rocksdb in datanode] Add compatibility test between schema v3 & v2.

---

hadoop-ozone/dist/src/main/smoketest/s3/MultipartUpload.robot
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartUploadCompleteRequest.java

S3MultipartUpload hasn't support usedNamespace. Currently when we upload key, only usedBytes will be updated.
https://issues.apache.org/jira/browse/HDDS-6650
Add new test case.

HDDS-6650. S3MultipartUpload support update bucket usedNamespace.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManagerImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerReplicaOp.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerReplicaPendingOps.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestBlockManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestCloseContainerEventHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerManagerImpl.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestContainerReplicaPendingOps.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestContainerPlacement.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconContainerManager.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStorageContainerManagerFacade.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/AbstractReconContainerManagerTest.java

The legacy replication manager internally keeps a list of all pending replications and deletes. Each time a container is checked, it check this list and removes any replications that have been completed or expired. Then it gets the list of remaining pending operations to help decide if container is healthy or not.
Rather than the ReplicationManager removing the completed and expired replications, we could have a standalone ContainerReplicaPendingOps monitor, that works as follows:
1. Replication Manager adds pending replications and deletes to it.
2. Replication Manager queries it for anything pending for the current container and gets a list of PendingActions back.
3. The ContainerReplicaPendingOps has its own internal thread that checks for expired replications and removes them.
4. …

HDDS-6744. EC: ReplicationManager - create ContainerReplicaPendingOps class and integrate with ContainerManager

---

pom.xml

JUnit 5.8.2 was released in November 28, 2021.
It brings useful changes to `@TempDir` for replacing `TemporaryFolder` in JUnit4.
Release notes:
* https://junit.org/junit5/docs/5.8.0/release-notes/index.html
* https://junit.org/junit5/docs/5.8.2/release-notes/index.html
https://issues.apache.org/jira/browse/HDDS-6777
Verified by existing CI: https://github.com/kaijchen/ozone/actions/runs/2356547743

HDDS-6777. Upgrade to JUnit 5.8.2

---

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/Gateway.java

The current registration of prometheus sink is before the initialization of s3gateway MetricsImpl.
The symptom is the s3g prom page doesn't show detail metrics. Although the current prom page (http://s3g:9878/prom) does show the metrics, it's because of the patch of [HADOOP-17081](https://issues.apache.org/jira/browse/HADOOP-17081). But in our production cluster, the S3g still got some performance issue, seems related to the MetricsSink's half-blocking attribute of SinkQueue.
https://issues.apache.org/jira/browse/HDDS-6779
N.A.

HDDS-6779. Register metricSink after initialization

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SequenceIdGenerator.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java

There are two places where the RocksDB table iterators aren't properly closed. Inspired by https://github.com/apache/ozone/pull/3131#discussion_r878296430
https://issues.apache.org/jira/browse/HDDS-6784
- All existing tests should pass.

HDDS-6784. Missing close() for two RocksDB table iterators

---

pom.xml

Bump Guava to 31.1, which is the latest release currently.
https://issues.apache.org/jira/browse/HDDS-6778
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2356568893

HDDS-6778. Bump Guava to 31.1

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java

Fix:
```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 15.107 s <<< FAILURE! - in org.apache.hadoop.ozone.container.common.transport.server.ratis.TestCSMMetrics
[ERROR] org.apache.hadoop.ozone.container.common.transport.server.ratis.TestCSMMetrics.testContainerStateMachineMetrics  Time elapsed: 15.033 s  <<< FAILURE!
java.lang.AssertionError: Bad value for metric NumBytesCommittedCount expected:<1024> but was:<0>
...
at org.apache.hadoop.test.MetricsAsserts.assertCounter(MetricsAsserts.java:230)
at org.apache.hadoop.ozone.container.common.transport.server.ratis.TestCSMMetrics.runContainerStateMachineMetrics(TestCSMMetrics.java:156)
at org.apache.hadoop.ozone.container.common.transport.server.ratis.TestCSMMetrics.testContainerStateMachineMetrics(TestCSMMetrics.java …
```

HDDS-6786. Bad value for metric NumBytesCommittedCount in testContainerStateMachineMetrics

---

.github/workflows/post-commit.yml
hadoop-ozone/dist/src/main/compose/compatibility/test.sh
hadoop-ozone/dist/src/main/compose/upgrade/test.sh
hadoop-ozone/dist/src/main/compose/xcompat/test.sh

Extract compatibility-related acceptance tests from `misc` into a separate suite.  This reduces time needed to repeat in case of failure.
https://issues.apache.org/jira/browse/HDDS-6674
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2247936865

HDDS-6674. Create compat acceptance split

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/lock/OMLockMetrics.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/lock/TestOzoneManagerLock.java

To get the snapshot of the write `OMLockMetrics` for exposing `writeLockWaitingTimeMsStat`, `writeLockHeldTimeMsStat` over JMX.
To add the following lines to the `OMLockMetrics.getMetrics()` method:
```
writeLockHeldTimeMsStat.snapshot(builder, all);
writeLockWaitingTimeMsStat.snapshot(builder, all);
```
https://issues.apache.org/jira/browse/HDDS-6765
NA

HDDS-6765. Get snapshot of write OMLockMetrics

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMOpenKeysDeleteRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMOpenKeysDeleteResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMOpenKeysDeleteRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMOpenKeysDeleteResponse.java

Support FSO bucket in OMOpenKeysDeleteRequest and Response.
1. Migrate to the new `OpenKeyBucket` proto changed in [HDDS-6491](https://issues.apache.org/jira/browse/HDDS-6491).
2. Change `OMOpenKeysDeleteRequest/Response` to support deleting keys in OpenFileTable.
https://issues.apache.org/jira/browse/HDDS-6476
Unit tests.

HDDS-6476. Support FSO in OMOpenKeysDeleteRequest and Response

---

.github/workflows/post-commit.yml
dev-support/ci/selective_ci_checks.bats
dev-support/ci/selective_ci_checks.sh

Change _compile_ check to work against source tarball created by _build_ check to ensure the contents of the tarball can be compiled.  The goal is to catch changes that become a problem only at release time.
https://issues.apache.org/jira/browse/HDDS-6719
Regular CI:
1. _build_ check uploaded source tarball: https://github.com/adoroszlai/hadoop-ozone/runs/6355813051#step:8:19
2. _compile_ check used it instead of git repo: https://github.com/adoroszlai/hadoop-ozone/runs/6356144283#step:3:1
3. checks using binary tarball still work fine: https://github.com/adoroszlai/hadoop-ozone/runs/6356144521

HDDS-6719. Verify build from source release tarball in CI

---

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBBatchOperation.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBCheckpointManager.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBTable.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/StringCodec.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TableConfig.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBTableStore.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/OzoneManagerServiceProviderImpl.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/spi/impl/TestOzoneManagerServiceProviderImpl.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestOMDBUpdatesHandler.java

Ensure that the RocksObjects are closed properly.
https://issues.apache.org/jira/browse/HDDS-6323

HDDS-6323. Close RocksObject(s).

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestListStatus.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneListStatusHelper.java

With FSO buckets, S3 list keys output is not sorted.
Amazon S3 list Objects returning the output sorted.
https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html
Since listKeys relies on listStatus for FSO buckets, this jira proposes to make listStatus output sorted
https://issues.apache.org/jira/browse/HDDS-6788
Added a new test to check for sorted output

HDDS-6788. Sort Ozone list Status output for FSO buckets.

---

hadoop-ozone/dev-support/checks/build.sh
hadoop-ozone/dev-support/checks/checkstyle.sh
hadoop-ozone/dev-support/checks/findbugs.sh
hadoop-ozone/dev-support/checks/junit.sh
hadoop-ozone/dev-support/checks/rat.sh

Without Maven cache hit build output is flooded with downloading/downloaded messages:
```
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/kr/motd/maven/os-maven-plugin/1.5.0.Final/os-maven-plugin-1.5.0.Final.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/kr/motd/maven/os-maven-plugin/1.5.0.Final/os-maven-plugin-1.5.0.Final.pom (6.4 kB at 10 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom (6.6 kB at 97 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-api/3.2.1/maven-plugin-api-3.2.1.pom
[INFO] …
```

HDDS-6789. Omit download progress in builds

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRackScatter.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackScatter.java

SCMContainerPlacementRackScatter should use original required node num to validate placement policy.
when no datanodes which can met the placement policy are selected , an exception should be thrown out
https://issues.apache.org/jira/browse/HDDS-6816
UT

HDDS-6816. SCMContainerPlacementRackScatter should use original required node num to validate placement policy

---

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/package.json
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/pnpm-lock.yaml

Bump axios to fix https://github.com/advisories/GHSA-cph5-m8f7-6c5x.
Lock file is updated using `pnpm install --lockfile-only`.
https://issues.apache.org/jira/browse/HDDS-6780
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2357473598

HDDS-6780. Bump axios to 0.21.4

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MockDatanodeStorage.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MockXceiverClientFactory.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MockXceiverClientSpi.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java

We should call HddsClientUtils.checkForException before calling checkIfContainerToExclude.
This bug was introduced in HDDS-6400 (#3372).
https://issues.apache.org/jira/browse/HDDS-6808
* With the patch: https://github.com/kaijchen/ozone/runs/6650562194?check_suite_focus=true
* Without the patch: https://github.com/kaijchen/ozone/runs/6650731778?check_suite_focus=true#step:5:1649

HDDS-6808. EC: Fix datanode exclusion check in client

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystemWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java

List status is done as a batch process. In `liststatusFSO`, it goes through the cache, and if the cache size is greater than the batch size we return just the cache. The problem is that the cache has gaps and the keys that are within these gaps are ignored. List status continues the listing from the last element (which is a sorted cache) of the batch so we do not iterate over the keys in the gaps again. 
https://issues.apache.org/jira/browse/HDDS-6474
This patch was tested on a cluster.

HDDS-6474. Fixed File System Optimized(FSO) bucket list status.

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestListKeysWithFSO.java

This is a follow-up task to [HDDS-4683](https://issues.apache.org/jira/browse/HDDS-4683).  Say, we have below is the Ozone FS tree. 
```
buck-1
|
a
|
---------------------------------------
|           |                           |
b1          b2                          b3
-----       -----------------          ----------
|    |      |    |           |        |    |     |
c1   c2     d1   d2           d3       e1   e2   e3
------                 |
|      |                |
d21.txt  d22.txt        e11.txt
```
`ozoneBuck#listKeys("a/", "a/b2/d2/d21.txt"); `should do back and forth search in FileTable and DirTable.
Output list should be something like -> d22.txt, d3, b3, e1, e11.txt, e2, e3
https://issues.apache.org/jira/browse/HDDS-4859
Added test cases

HDDS-4859. [FSO]ListKeys: seek all the files/dirs from startKey to keyPrefix

---

hadoop-hdds/docs/content/feature/PrefixFSO.md
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/bucket/CreateBucketHandler.java

This task is to add `LEGACY` to `AllowedBucketLayouts` in the `CreateBucketHandler` class.
[CreateBucketHandler.java#L65](https://github.com/apache/ozone/blob/master/hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/bucket/CreateBucketHandler.java#L65)
```
enum AllowedBucketLayouts {
FILE_SYSTEM_OPTIMIZED("FILE_SYSTEM_OPTIMIZED"),
OBJECT_STORE("OBJECT_STORE"),
LEGACY("LEGACY")
```
While executing the `ozone sh bucket create` command and passing an `INVALID` bucket layout, we currently get the following error message:
```
Invalid value for option '--layout': expected one of [FILE_SYSTEM_OPTIMIZED, OBJECT_STORE, DEFAULT, ] (case-sensitive) but was 'INVALID'
```
After the changes, this would be modified to:
```
Invalid value for option '--layout': expected one of …
```

HDDS-6819. Add LEGACY to AllowedBucketLayouts in CreateBucketHandler

---

hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java

Fix intermittent failure in TestOzoneECClient#testExcludeOnDNMixed.
https://github.com/apache/ozone/runs/6701276416?check_suite_focus=true
HDDS-6823
Tested manually by repeating the test 100x in `for` loop.
And also tested with all other tests in TestOzoneECClient.

HDDS-6823. Intermittent failure in TestOzoneECClient#testExcludeOnDNMixed

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/storage/ContainerProtocolCalls.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/container/ContainerTestHelper.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerSet.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/interfaces/Handler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainer.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java
hadoop-hdds/interface-client/src/main/proto/DatanodeClientProtocol.proto
hadoop-hdds/interface-client/src/main/proto/hdds.proto
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/server/TestSCMContainerMetrics.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestContainerCommandsEC.java

This PR proposes to add the createREcoveringContainer API in ContainerProtocolCalls, which can be used to store reconstruction in progress containers.
https://issues.apache.org/jira/browse/HDDS-6764
Added tests to verify.

HDDS-6764: EC: DN ability to create RECOVERING containers for EC reconstruction.

---

pom.xml

Revert the upgrade of RocksDB across a major version bump
This is to avoid memory leaks due to lack of close for
RocksObject inherited objects.
The upgrade should be done only once the leaks have been fixed.
Without the leak fix, the newer version of RocksDB makes it impossible
to run any long-running load.
https://issues.apache.org/jira/browse/HDDS-6828
This is the older release train. I ran a basic build and waiting for CI run.

HDDS-6828 Revert RockDB version pending leak fixes

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OzoneFSUtils.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OzoneManagerProtocol.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestListStatus.java
hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneListStatusHelper.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/fs/OzoneManagerFS.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java

This change adds a proto field which is used to trigger listStatus in listKeysmode to allow partial prefixes
https://issues.apache.org/jira/browse/HDDS-6810
Added a new test

HDDS-6810. Add a optional flag to trigger listStatus as part of listKeys for FSO buckets.

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java

The `ozone sh bucket create` command throws an `INFO` message with Storage Type/Encryption and a few other details.
```
[root@quasar-wzsrji-4 ~]# ozone sh bucket create test/obs --layout=OBJECT_STORE
22/05/25 19:02:21 INFO rpc.RpcClient: Creating Bucket: test/obs, with om as owner and Versioning false and Storage Type set to DISK and Encryption set to false
```
It is good to have the bucket layout information as well in the `INFO` message.
https://issues.apache.org/jira/browse/HDDS-6811
NA

HDDS-6811. Bucket create message with layout type

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java
hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
hadoop-ozone/interface-client/src/main/resources/proto.lock

Revert changes made in proto.lock by HDDS-6768
HDDS-6824

HDDS-6824. Revert changes made in proto.lock by HDDS-6768.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestDirectoryDeletingServiceWithFSO.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestDataUtil.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMStartupWithBucketLayout.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestObjectStoreWithFSO.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHAWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketCreateRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestOMBucketCreateRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestOMBucketCreateRequestWithFSO.java

After the post finalization, user should be able to create LEGACY, FSO, OBS layouts.
The proposal is to modify the behavior on the server-side to only use the ozone.default.bucket.layout config if the client has not specified any bucket layout in the protobuf message.
If the client sends LEGACY bucket layout type then OM server will not override it with ozone.default.bucket.layout config value. This way a client has the flexibility to create a LEGACY bucket explicitly.
Hint: We can use the `bucketInfo.hasBucketLayout()` Protobuf method to check if the field is set by the user.
Reference: [Discussion here](https://github.com/apache/ozone/pull/3411#issuecomment-1126550908)
https://issues.apache.org/jira/browse/HDDS-6683
Added unit and integration tests.

HDDS-6683. Refactor OM server bucket layout configuration usage

---

hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MockDatanodeStorage.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MockXceiverClientSpi.java

Added listblock API in MockDatanodeStorage
https://issues.apache.org/jira/browse/HDDS-6759
This is mock class. So, this is helpful for tests.

HDDS-6759: Add listblock API in MockDatanodeStorage

---

hadoop-hdds/container-service/src/main/resources/webapps/hddsDatanode/dn-overview.html
hadoop-hdds/container-service/src/main/resources/webapps/hddsDatanode/dn.js

After the patch [https://github.com/apache/ozone/pull/3430](url) got merged, I have decided to display some of the newly added metrics on to the DataNode web UI, in the form of a table. 
https://issues.apache.org/jira/browse/HDDS-6706
After opening the DataNode UI the correct Storage related information of the various volumes associated to the DataNode were displaced

HDDS-6706 Exposing Volume Information Metrics to the DataNode UI

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/BaseFileChecksumHelper.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/checksum/TestReplicatedFileChecksumHelper.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OzoneFileStatus.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/RepeatedOmKeyInfo.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/protocolPB/OMPBHelper.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmKeyInfo.java
hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
hadoop-ozone/interface-storage/src/test/java/org/apache/hadoop/ozone/om/codec/TestOmKeyInfoCodec.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java

Persist file checksum in OM rocksdb.
[HDDS-6091](https://issues.apache.org/jira/browse/HDDS-6091)

HDDS-6091. Add file checksum to OmKeyInfo

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OzoneFSUtils.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestListKeysWithFSO.java

StartKey can be a non-existed key in the keyManager#listStatus}} API. Needs special handling to search the path in FileTable and in DirTable.
For Example, OM has namespace like:
/a/a
/a/c
/a/d
If given startKey: "/a/b", here should return ["/a/c", "/a/d"]
[Reference comment](https://github.com/apache/hadoop-ozone/pull/1503#discussion_r506857023)
https://issues.apache.org/jira/browse/HDDS-4364
Added test cases.

HDDS-4364: [FSO]List FileStatus : startKey can be a non-existed path

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OMAdminProtocolServerSideImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OMInterServiceProtocolServerSideImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerProtocolServerSideTranslatorPB.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/OzoneDelegationTokenSecretManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/S3SecurityUtil.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/TestOzoneDelegationTokenSecretManager.java

https://issues.apache.org/jira/browse/HDDS-6686

HDDS-6686. Do Leadship check before SASL token verification.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestBucketLayoutWithOlderClient.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketCreateRequest.java

Presently, older clients can create bucket other than LEGACY bucket layout if admin sets ozone.default.bucket.layout default value to FSO or OBS.
For example, ozone.default.bucket.layout = FILE_SYSTEM_OPTIMIZED in OM server.
Say, Older Client creates a bucket, OM will use the default value and creates an FSO bucket.
Now, older client can't perform any key operations to this bucket as older client's operations not supported on FSO/OBS buckets layout types.
https://issues.apache.org/jira/browse/HDDS-6838
Added test case

HDDS-6838. [FSO] Sets OM default to LEGACY for an older client's bucket create request

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/conf/OzoneConfiguration.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ratis/RatisHelper.java
hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigurationSource.java
hadoop-hdds/config/src/test/java/org/apache/hadoop/hdds/conf/ConfigurationSourceTest.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/HttpServer2.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerRatisServer.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStorageContainerManagerFacade.java

Currently, there is no mechanism in place to configure additional headers to be set for the various Http endpoints hosted by Ozone including S3G.
This change adds
1. `ozone.http.header.<HEADER>` as a configuration key that can point to the value to be returned for a header. 
2. Adds the ability for configuration to do a prefix match.
https://issues.apache.org/jira/browse/HDDS-6836

HDDS-6836. Fix Ozone http header configuration

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ReplicationConfig.java
hadoop-ozone/dist/src/main/smoketest/ec/basic.robot
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java

See https://issues.apache.org/jira/browse/HDDS-6827
Integration test and acceptance test.
Manual test:
```console
$ ./ozone sh bucket create /vol/bkt --type=RATIS --replication=rs-3-2-1024k
rs-3-2-1024k is not supported for RATIS replication type
$ ./ozone sh key put /vol/bkt/key ~/.bashrc --type=RATIS --replication=rs-3-2-1024k
rs-3-2-1024k is not supported for RATIS replication type
```

HDDS-6827. Need proper error message when "RATIS" replication-type is passed with EC codec

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/BaseFileChecksumHelper.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/ReplicatedFileChecksumHelper.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientUtils.java
hadoop-ozone/ozonefs-common/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneClientUtils.java

GetFileChecksum is implemented only for Ratis based file layout. For EC files layout, we have no implementation ready yet. This JIRA is to return null for EC files until we have the implementation ready. Otherwise, we will get the wrong CRC unknowingly for EC files.
https://issues.apache.org/jira/browse/HDDS-6815
Added a UT.

HDDS-6815: EC: getFileCheckSum should return null EC files until ECFileChecksum implemented.

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientRatis.java

See https://issues.apache.org/jira/browse/HDDS-6844

HDDS-6844. Reduce the number of watch requests in XceiverClientRatis.

---

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/ReconContainerMetadataManager.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/ReconNamespaceSummaryManager.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/ReconContainerMetadataManagerImpl.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/ReconNamespaceSummaryManagerImpl.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/ContainerKeyMapperTask.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/FileSizeCountTask.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/NSSummaryTask.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/TableCountTask.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/spi/impl/TestReconContainerMetadataManagerImpl.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/spi/impl/TestReconNamespaceSummaryManagerImpl.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestNSSummaryTask.java

Each Recon task after processing the recent events committed the changes one by one into their databases. We want to have Recon to be resilient against failure between updates to OM copy DB and post processing task. To handle this problem, at first I changed that each task commits the changes in one batch, so we either have all the changes committed or none. After this change I will be able to have the last committed sequence number for each task and I can resend the events again in case of a failure. 
Two tasks are writing into RocksDB (ContainerKeyMapperTask and NSSummaryTask), in those cases I write every change in one batch. The other two tasks (FileSizeCountTask and TableCountTask) are using jOOQ generated DAO classes to handle their databases. With that I didn't find upsert query or …

HDDS-6783. Recon tasks should write in batches to their databases

---

pom.xml

Bumping kotlin-stdlib to 1.6.21.
[CVE-2022-24329](https://nvd.nist.gov/vuln/detail/CVE-2022-24329)
1.6.21 seems to be the latest stable version [as of now](https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib).
https://issues.apache.org/jira/browse/HDDS-6850
- Should be good as long as the existing test suites all pass.

HDDS-6850. Bump kotlin-stdlib to 1.6.21 due to CVE-2022-24329

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/AbstractDataStreamOutput.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/StreamCommitWatcher.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OzoneClientKeyGenerator.java

See https://issues.apache.org/jira/browse/HDDS-6842

HDDS-6842. [Ozone-Streaming] Reduce the number of watch requests in StreamCommitWatcher.

---

hadoop-ozone/common/pom.xml
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyArgs.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmKeyArgs.java

`OmKeyArgs` has a flag to indicate if the request is a "head" operation (e.g. existence check, metadata request) or if data is needed as well.  We can skip a few resource-intensive tasks for "head".
This flag is ignored for link buckets because it is lost during `OmKeyArgs -> Builder -> OmKeyArgs` conversion:
https://github.com/apache/ozone/blob/7847e663c45adfc3566679959936da3125474d80/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ResolvedBucket.java#L70-L75
which is called in some `OzoneManager` read ops, e.g.:
https://github.com/apache/ozone/blob/7847e663c45adfc3566679959936da3125474d80/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java#L2810
https://github.com/apache/ozone/blob/7847e663c45adfc3566679959936da3125474d80/hadoop-ozone …

HDDS-6846. HeadOp ignored for link bucket

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/HttpServer2.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/NoCacheFilter.java

When processing response headers, always update if the header is present instead of adding headers to the response.
https://issues.apache.org/jira/browse/HDDS-6837
```
➜  ~ curl --insecure -I https://ritesh718-1.ritesh718.root.hwx.site:9879/static/
HTTP/1.1 200 OK
Date: Thu, 09 Jun 2022 23:42:15 GMT
Content-Type: text/html
Strict-Transport-Security: max-age=63072000; includeSubDomains;
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-FRAME-OPTIONS: SAMEORIGIN
Last-Modified: Wed, 01 Jun 2022 17:23:28 GMT
Accept-Ranges: bytes
Content-Length: 3106
```

HDDS-6837. Fix duplicate headers returned in response.

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/upgrade/OMCancelPrepareRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/upgrade/OMFinalizeUpgradeRequest.java

When checking for admin privileges in the OM Upgrade path, the check is
only run against the short name representation of the UGI. The check
should be done against variations of the user name. Ideally, the check
should be against UGI Objects but the admin list created also takes in a
string representation of the user name via config.
https://issues.apache.org/jira/browse/HDDS-6869
Local secure cluster with an upgrade finalization test.

HDDS-6869. Use UGI when checking Upgrade priv

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/tracing/TracingUtil.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/tracing/TestTracingUtil.java

When clients wraps OzoneClient with Tracing.span, Ozone will try to export the context using StringCodec, but the clients' tracer don't know the StringCodec Ozone is using, the exception of UnsupportedFormatException would be thrown.
https://issues.apache.org/jira/browse/HDDS-6878
unit test.

HDDS-6878. Only export span if Ozone tracer init

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRackScatter.java

Attempt to fix mismatch in count of nodes selected by `SCMContainerPlacementRackScatter`:
```
SCMException: Nodes size= 5, replication factor= 6 do not match
at org.apache.hadoop.hdds.scm.pipeline.PipelineFactory.checkPipeline(PipelineFactory.java:106)
at org.apache.hadoop.hdds.scm.pipeline.PipelineFactory.create(PipelineFactory.java:90)
at org.apache.hadoop.hdds.scm.pipeline.PipelineManagerImpl.createPipeline(PipelineManagerImpl.java:195)
at org.apache.hadoop.hdds.scm.pipeline.WritableECContainerProvider.allocateContainer(WritableECContainerProvider.java:172)
at org.apache.hadoop.hdds.scm.pipeline.WritableECContainerProvider.getContainer(WritableECContainerProvider.java:155)
at org.apache.hadoop.hdds.scm.pipeline.WritableECContainerProvider.getContainer(WritableECContainerProvider.java:51 …
```

HDDS-6830. EC: SCMContainerPlacementRackScatter may choose fewer nodes than required

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ECContainerReplicaCount.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerHealthCheck.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerHealthResult.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECContainerHealthCheck.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECContainerHealthCheck.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/states/TestECContainerReplicaCount.java

This PR defines a ContainerHealthCheckInterface, with the following definition:
```
ContainerHealthResult checkHealth(
ContainerInfo container, Set<ContainerReplica> replicas,
List<Pair<Integer, DatanodeDetails>> indexesPendingAdd,
List<Pair<Integer, DatanodeDetails>> indexesPendingDelete,
int remainingRedundancyForMaintenance);
}
```
And also an implementation for EC containers that can determine if an EC container is over or under replicated. The interface will return a ContainerHealthResult object that contains information about the health state. Eg for under replicated, it will contain details about the remaining redundancy, whether its due to decommission etc.
For now this class is standalone and unused. It will be integrated with ReplicationManager soon via a new Jira. …

HDDS-6697. EC: ReplicationManager - create class to detect EC container health issues

---

hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/signature/TestAuthorizationV4QueryParser.java

TestAuthorizationV4QueryParser.testWithAWSExample cannot be passed without internet connection. 
It requires the internet because the test passes "examplebucket.s3.amazonaws.com" to an HTTP header. This hostname is attempted to be resolved during the test.
Such tests make creating a CI pipeline in a restricted infrastructure difficult.
https://issues.apache.org/jira/browse/HDDS-6872
Units tests passed

HDDS-6872. TestAuthorizationV4QueryParser should pass offline

---

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/upgrade/TestDatanodeUpgradeToSchemaV3.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/keys/PutKeyHandler.java

Put EC key should not using streaming.
In the EC write test, writing a small file (less than 4MB) was successful, but writing 100MB failed. Cause 100MB EC key should not be written using Streaming.
https://issues.apache.org/jira/browse/HDDS-6867
Existing test in acceptance-unsecure.

HDDS-6867.  [Ozone-Streaming] PutKeyHandler should not use streaming to put EC key.

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMultiTenantManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerStateMachine.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/upgrade/OMFinalizeUpgradeRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerStateMachine.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyRequest.java

Avoid duplication of dealing with short and full names that are part of UGI. 
https://issues.apache.org/jira/browse/HDDS-6870
Existing tests run by CI

HDDS-6870. Clean up isTenantAdmin to use UGI

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/fs/CachingSpaceUsageSource.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerData.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/StorageVolume.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeInfo.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeUsage.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingService.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/AbstractDatanodeStore.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestKeyValueContainerData.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBProfile.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestRefreshVolumeUsageHandler.java

- Setting the `MaxTotalWalSize` for DN containers to `2MB`. RocksDB by default pre-allocates `141MB` WAL file for every container and it only uses less than `2MB` of it. 
- Updating the cached used space with chunk write and block delete. `CachingSpaceUsageSource` periodically refreshed the used space of a Volume. (`hdds.datanode.du.refresh.period=1h` for `DU` and `hdds.datanode.df.refresh.period=5m` for `DedicatedDiskSpaceUsage`). During the interval used space  is not updated, Hence the volume usage goes beyond the reserved space(`hdds.datanode.dir.du.reserved`)
https://issues.apache.org/jira/browse/HDDS-6577
This patch was tested manually using the docker cluster.

HDDS-6577. Configurations to reserve HDDS volume space.

---

hadoop-ozone/dist/src/main/compose/upgrade/compose/ha/docker-config
hadoop-ozone/dist/src/main/smoketest/upgrade/finalize.robot

After HDDS-6760, SCM finalization was intermittently timing out during the acceptance test. This happened because containers were put in a CLOSING state since finalization happened before datanode leader election, but the replication manager was not running to close the containers until 5 minutes after safemode exit. The pipeline scrubber also had a large wait time and pipeline timeout that prevented it from force closing these pipelines during the duration of the test.
This Jira modifies the acceptance test configurations to speed up moving containers to a CLOSED state so finalization can proceed. It also increases the test timeout.
HDDS-6898
50 successful runs on my fork: https://github.com/errose28/hadoop-ozone/runs/6905140700?check_suite_focus=true

HDDS-6898. [SCM HA finalization] Modify acceptance test configuration to speed up test finalization

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/InflightType.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManagerMetrics.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManagerMetrics.java

See https://issues.apache.org/jira/browse/HDDS-6829

HDDS-6829. Limit the no of inflight replication tasks in SCM.

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientManager.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ECBlockOutputStream.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/storage/ContainerProtocolCalls.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/ReconstructECContainersCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECContainerOperationClient.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinator.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinatorTask.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionSupervisor.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ec/reconstruction/TestECReconstructionSupervisor.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestContainerCommandsEC.java

This patch implements the EC REconstruction coordinator functionality. With this patch, DN would be capable of reconstructing given missing indexes to given targets.
https://issues.apache.org/jira/browse/HDDS-6806
Added tests.

HDDS-6806. EC: Implement the EC Reconstruction coordinator.

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockInputStream.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/ozone/client/io/TestECBlockInputStream.java

Co-authored-by: Uma Maheswara Rao G <umagangumalla@cloudera.com>
Fix potential wrong replica read with over-replicated container.
The problem is due to that an EC pipeline with multiple DNs is returned and used with the first DN picked while refreshing pipeline on read error(Read error is due to concurrent redundant EC container replica deletion, e.g. EC 10+4 with 18 replicas),
but the right behavior should be pick the DN with the same replicaIndex and build a standalone pipeline for retry.
https://issues.apache.org/jira/browse/HDDS-6890
To be verified manually.

HDDS-6890. EC: Fix potential wrong replica read with over-replicated container.

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/cli/GenericCli.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/server/TestStorageContainerManagerStarter.java
hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/cli/OzoneAdmin.java
hadoop-ozone/dist/src/main/smoketest/basic/ozone-shell-lib.robot
hadoop-ozone/dist/src/main/smoketest/basic/ozone-shell.robot
hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/OzoneChaosCluster.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerStarter.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/Freon.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/segmentparser/RatisLogParser.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/OzoneShell.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/s3/S3Shell.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/tenant/TenantShell.java

Command-line tools don't take exit-code from `picocli` and set the exit-code accordingly. That makes exit-codes for cases like invalid argument be always 0.
This change fixes that by replacing the use of the deprecated `parseWithHandler` method with the `execute` method that returns correct exit-code for parsing/invalid input cases. 
https://issues.apache.org/jira/browse/HDDS-6882
Regression is checked by unit test.
Manually tests to verify the expected status code for error-cases.
```
ozone sh bucket create /vol1/bucket1 -l 123
Invalid value for option '--layout': expected one of [FILE_SYSTEM_OPTIMIZED, OBJECT_STORE, LEGACY] (case-sensitive) but was '123'
Usage: ozone sh bucket create [-ghV] [-k=<bekName>] [-l=<allowedBucketLayout>]
[--namespace-quota=<quotaInNamespace>] …
```

HDDS-6882. Correct exit code for invalid arguments passed to command-line tools.

---

hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMDbCheckpointServlet.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMiniOzoneOMHACluster.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmInit.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestSecureOzoneManager.java
hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
hadoop-ozone/ozone-manager/pom.xml
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OpenKeyCleanupService.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOpenKeyCleanupService.java

~~WIP: this PR depends on #3233 and #3226.~~
This pull request completes the open key cleanup service outlined in the parent Jira HDDS-4120. It implements the `OpenKeyCleanupService` class, and starts and stops the service in `KeyManagerImpl`. The following configurations have been defined to specify the service's behavior:
1. ozone.open.key.cleanup.service.interval (default value 24 hours)
2. ozone.open.key.expire.threshold (default value 1 week)
3. ozone.open.key.cleanup.limit.per.task (default value 1000 keys)
See `ozone-defaults.xml` for their corresponding descriptions.
https://issues.apache.org/jira/browse/HDDS-4123
Integration test `TestOpenKeyCleanupService`

HDDS-4123. Integrate OM Open Key Cleanup Service Into Existing Code

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockInputStreamProxy.java

Exception stacktrace put in debug level instead of warn or error level. 
https://issues.apache.org/jira/browse/HDDS-6899
Logging Changes, no change in logic.

HDDS-6899. [EC] Remove warnings and errors from console during online reconstruction of data.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestObjectStoreWithLegacyFS.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequestWithFSO.java

OBS bucket keys should create flat key-value structure and intermediate directories shouldn't be created even if the OZONE_OM_ENABLE_FILESYSTEM_PATHS flag is TRUE.
https://issues.apache.org/jira/browse/HDDS-6924
Added test case

HDDS-6924. OBJECT_STORE isn't flat namespaced

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerProtocolServerSideTranslatorPB.java

For operations that are not read only we should
set the thread local S3 Auth.
https://issues.apache.org/jira/browse/HDDS-6868
Before patch.
This was manually tested, we need to improve our secure S3 testing and will file a separate jira to improve our test cases. This is an urgent fix that needs to get in.
```
mc: <ERROR> Failed to copy `/etc/hosts`. Insufficient permissions to access this file `https://localhost:9879/bucket/key`
```
After patch the object could be uploaded to S3.

HDDS-6868. Add S3Auth information to thread local

---

hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/conf/TestOzoneConfiguration.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/net/TestNodeSchemaManager.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/common/TestStateMachine.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/lease/TestLeaseManager.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/upgrade/TestAbstractLayoutVersionManager.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/upgrade/TestUpgradeFinalizerActions.java

Migrate following tests to JUnit 5:
```
hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/conf/TestOzoneConfiguration.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/net/TestNodeSchemaManager.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/common/TestStateMachine.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/lease/TestLeaseManager.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/upgrade/TestAbstractLayoutVersionManager.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/upgrade/TestUpgradeFinalizerActions.java
```
https://issues.apache.org/jira/browse/HDDS-6876
Full CI: https://github.com/kaijchen/ozone/actions/runs/2539608584

HDDS-6876. Migrate test with rules in hdds-common to JUnit5

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineFailures.java

Add `@Flaky` annotation to this test due to unrelated failures described in HDDS-6935.
HDDS-6936
N/A, this patch is only skipping a test.

HDDS-6936. Mark TestContainerStateMachineFailures#testApplyTransactionFailure as flaky.

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinator.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/TokenHelper.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/token/OzoneBlockTokenSecretManager.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/token/TestOzoneBlockTokenSecretManager.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestContainerCommandsEC.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestSecureOzoneRpcClient.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainerWithTLS.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/server/TestSecureContainerServer.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/OmTestManagers.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyRequest.java

Support secure cluster by using block/container tokens in `ECReconstructionCoordinator`.
https://issues.apache.org/jira/browse/HDDS-6873
Changed existing integration test to require tokens.
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2544654342

HDDS-6873. EC: Add block token support for ECReconstructionCoordinator

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRackScatter.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/WritableECContainerProvider.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/ScmBlockLocationProtocolServerSideTranslatorPB.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestWritableECContainerProvider.java

When `allocateBlock()` fails, It throws a generic SCMException `Allocated 0 blocks. Requested 1 blocks`. Here the block allocation failed because there weren't enough DataNodes for EC replication. Proposing to throw an exception when `allocateContainer()` fails and propagate back the actual Exception. 
https://issues.apache.org/jira/browse/HDDS-6812
This patch was tested manually with docker and Unit test. Now the error message is,
```
INTERNAL_ERROR No enough datanodes to choose. TotalNode = 3 AvailableNode = 3 RequiredNode = 5 ExcludedNode = 0
```

HDDS-6812. Fix INTERNAL_ERROR message on failed write.

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketSetPropertyRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestOMBucketSetPropertyRequest.java

A member of our dev ops team discovered that setting a quota on a non legacy bucket will convert it to a legacy bucket, making the data there inaccessible.
You can reproduce the problem like so:
```
ozone sh volume create testgbj
ozone sh bucket create -l FILE_SYSTEM_OPTIMIZED testgbj/fsobucket4
ozone sh bucket info testgbj/fsobucket4
{
"volumeName" : "testgbj",
"name" : "fsobucket4",
"creationTime" : "2022-06-23T21:26:47.091Z",
"modificationTime" : "2022-06-23T21:26:47.091Z",
"bucketLayout" : "FILE_SYSTEM_OPTIMIZED",
"owner" : "root",
"link" : false
}
ozone sh bucket setquota --namespace-quota=20 testgbj/fsobucket4
ozone sh bucket info …
```

HDDS-6941. Setting Bucket Property can corrupt bucket layout.

---

hadoop-ozone/dist/pom.xml
hadoop-ozone/dist/src/main/compose/ozonesecure-ha/docker-config
hadoop-ozone/dist/src/main/compose/ozonesecure-mr/docker-config
hadoop-ozone/dist/src/main/compose/ozonesecure/docker-config

AUTH_TO_LOCAL setting for Kerberos is incorrect.
This issue needs https://issues.apache.org/jira/browse/HDDS-6929 to be merged in and be picked up by smoke tests.
https://issues.apache.org/jira/browse/HDDS-6906
Tested with a dev build of https://issues.apache.org/jira/browse/HDDS-6929
~~Encrypted tests are still failing and this PR is not yet ready to merge.~~

HDDS-6906. Fix kerberos config for secure smoke tests.

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/endpoint/HeartbeatEndpointTask.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/states/endpoint/TestHeartbeatEndpointTask.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeProtocolServer.java

Commands of type `reconstructECContainersCommand` should be sent from SCM and handled by datanode via heartbeat.
https://issues.apache.org/jira/browse/HDDS-6944
Added unit test case in `TestHeartbeatEndpointTask`.
https://github.com/adoroszlai/hadoop-ozone/runs/7044249170#step:5:1021

HDDS-6944. EC: Handle reconstructECContainersCommand in heartbeat

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CloseContainerCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/ClosePipelineCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CommandDispatcher.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CreatePipelineCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/FinalizeNewLayoutVersionCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/ReconstructECContainersCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/RefreshVolumeUsageCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/SetNodeOperationalStateCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinatorTask.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionSupervisor.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ec/reconstruction/TestECReconstructionSupervisor.java

This JIRA addresses the issue regarding DN reconstruction command queues reporting. Now with this changes, when reconstruction command received by DN, while executing the task, counter will be incremented and after execution of the coordinator task counter will be reduced. 
https://issues.apache.org/jira/browse/HDDS-6945
added test.

HDDS-6945. EC: EC Reconstruction Command count queues should be included in DN heartbeat

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/multitenant/MultiTenantAccessAuthorizerRangerPlugin.java

Check whether return policy is null. If so, we should log and exit instead of still trying to delete the policy.
https://issues.apache.org/jira/browse/HDDS-6948
N/A

HDDS-6948. MultiTenantAccessAuthorizerRangerPlugin#deletePolicyByName should log and exit if getAccessPolicyByName returns null

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancer.java

ContainerBalancer has `balancingThread.join()` being called in ContainerBalancer#stopBalancingThread. Callers of this method acquire but don't release the only lock in this class when calling this method. If at this time another thread is trying to acquire the lock, we have a deadlock.
For example, SCMClientProtocolServer#stopContainerBalancer() will lead to the calling thread wait for the balancing thread to join in ContainerBalancer#stopBalancingThread. If the balancing thread now checks for `isBalancerRunning()` in ContainerBalancer#balance, the two threads will get into a deadlock. The balancing thread is disabled and waiting to acquire the lock, while the other thread is waiting for balancing thread to finish.
Changes: Release lock in callers of ContainerBalancer#stopBalancingThread …

HDDS-6928. ozone container balancer CLI went in hung state due to deadlock

---

hadoop-ozone/dist/src/main/smoketest/security/ozone-secure-tenant.robot
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/security/S3SecretRequestHelper.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/security/TestS3GetSecretRequest.java

We are unable to get secret even though we kinit with the same user for which we want to retrieve the secret. This PR aims to fix this by getting short user principal and not the full prinicipal.
https://issues.apache.org/jira/browse/HDDS-6968
The patch was tested manually in a cluster and also using CI tests.
```
bash-4.2$ klist
Ticket cache: FILE:/tmp/krb5cc_0
Default principal: systest@ROOT.HWX.SITE
bash-4.2$ ozone tenant user getsecret 'tenant$systest' --om-service-id=ozone1
export AWS_ACCESS_KEY_ID='tenant$systest'
export AWS_SECRET_ACCESS_KEY='e264d0460c146624d381d058677b4102f8deaaa7302ad589d85adc1c3fdd7d16'
```

HDDS-6968. [Multi-Tenant] Fix USER_MISMATCH error even on correct user.

---

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java

See https://issues.apache.org/jira/browse/HDDS-6973

HDDS-6973. Refactor ObjectEndpoint.

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java

As per a recent change to add Bucket Layout information while creating bucket: [HDDS-6811](https://issues.apache.org/jira/browse/HDDS-6811) (PR [#3479](https://github.com/apache/ozone/pull/3479)), the information is displayed as expected when we pass a parameter for `--layout` but is displayed as `null` when we don't pass any.
It should rather print the default bucket layout type and should not rely on the user params.
```
root@st-ozone-sq1qpy-p9xm2:/ansible# /opt/cloudera/parcels/CDH/bin/ozone sh bucket create o3://ozone1/vol-1/buck-1
2022-06-13 17:37:30,582 [main] INFO  rpc.RpcClient (RpcClient.java:createBucket(666))       - Creating Bucket: vol-1/buck-1, with the Bucket Layout null, hrt_qa as owner, Versioning false, Storage Type set to DISK and Encryption set to false
22/06/13 …
```

HDDS-6879. Bucket layout as null on default layout type

---

hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBTableStore.java

This is a follow-up task of #3415.
`rdbStore` is already initialized in `@BeforeEach setUp()`, and closed in `@AfterEach tearDown()`.
Reuse them in `testIsExist()` and `testGetIfExist()`.
https://issues.apache.org/jira/browse/HDDS-6773
CI: https://github.com/kaijchen/ozone/actions/runs/2353514330

HDDS-6773. Cleanup TestRDBTableStore

---

hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/states/TestECContainerReplicaCount.java

There are some unneeded references in TestECContainerReplicaCount to instances of ContainerReplicaPendingOps. We should remove them to reduce the dependencies on the test class.
https://issues.apache.org/jira/browse/HDDS-6977
Just unit test changes.

HDDS-6977. EC: Remove references to ContainerReplicaPendingOps in TestECContainerReplicaCount

---

hadoop-ozone/dist/src/main/smoketest/README.md

The current README in smoketest reference compose directory like a sub-directory.
It was quite confusing at first glance.
This patch adds link to compose directory, and changes the path in the command example.
https://issues.apache.org/jira/browse/HDDS-6969
Rendered version: https://github.com/kaijchen/ozone/blob/HDDS-6969/hadoop-ozone/dist/src/main/smoketest/README.md

HDDS-6969. [Docs] Add link to compose directory in smoketest README

---

.github/workflows/post-commit.yml

_basic (unit)_ check takes 45+ minutes, and sometimes even times out after 60 minutes.  It looks like Github runners have variable performance.  Since we have more tests now, I think it is reasonable to increase the timeout.
https://issues.apache.org/jira/browse/HDDS-6965
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/runs/7087566467
_basic (unit)_ check succeeded in 1h 1m 44s, so it would have failed prior to this change.

HDDS-6965. Increase timeout for basic check

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBSstFileWriter.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileRequest.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/ListTables.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/RocksDBUtils.java

Change-Id: I5e2f906508d92c1c21555aa51d9b5c97744f26cd
(cherry picked from commit c1cda1d8e99555282b991f174d0bf597c0deb950)
Close RocksDB objects when they are not used.
https://issues.apache.org/jira/browse/HDDS-6723
This is tested in an internal branch, ran a few workloads.
The RocksDB jar was replaced with a custom build which prints memory leak in stdout. This is the code: https://github.com/jojochuang/rocksdb/commits/debug_memory_leak
With this change, most of the leaks are now gone, except during OM initialization when load DB. Didn't care much about them as they account for very little memory usage.

HDDS-6723. Close Rocks objects properly in OzoneManager

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerHealthResult.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java

After the under / over replicated containers are collect in [HDDS-6699](https://issues.apache.org/jira/browse/HDDS-6699), they need to be priortised and placed on a queue for the next stage of RM to pick up and process.
This change adds a priority queue for the under replicated containers, where they are priortised by the remaining redundancy and made available for processing by the next stage of the replication process.
https://issues.apache.org/jira/browse/HDDS-6957
New unit tests

HDDS-6957. EC: ReplicationManager - priortise under replicated containers

---

pom.xml

Dependencies from `org.codehaus.plexus` are defined in `dependencyManagement`, but never actually used, so can be removed.
https://issues.apache.org/jira/browse/HDDS-6979
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2600537869

HDDS-6979. Remove unused plexus dependency declaration

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/AbstractOverReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerReplicaCount.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECContainerHealthCheck.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECContainerReplicaCount.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECOverReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnhealthyReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeAdminMonitorImpl.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationTestUtil.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestContainerReplicaCount.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECContainerReplicaCount.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECOverReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisContainerReplicaCount.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestDatanodeAdminMonitor.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/node/TestDecommissionAndMaintenance.java

Implement the Over-replication Handler
https://issues.apache.org/jira/browse/HDDS-6960
unit test

HDDS-6960. EC: Implement the Over-replication Handler

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/security/S3SecretRequestHelper.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/security/TestS3GetSecretRequest.java

This is an addendum to #3566
Fix the Short Principle and Full Principle check for `GetS3SecretHandler` and `TenantGetSecretHandler`
CI run: https://github.com/aswinshakil/ozone/actions/runs/2599527648

HDDS-6968. Addendum: [Multi-Tenant] Fix USER_MISMATCH error even on correct user.

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECContainerOperationClient.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinator.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java

Coordinator created recovering containers would be deleted if there is failure.
https://issues.apache.org/jira/browse/HDDS-6982
Will be adding tests.

HDDS-6982. EC: Attempt to cleanup the RECOVERING container when reconstruction failed at coordinator.

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/ContainerReader.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestContainerReader.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/container/ContainerCommands.java

Cleanup RECOVERING container on DN restarts in containerReader
https://issues.apache.org/jira/browse/HDDS-6978

HDDS-6978. EC: Cleanup RECOVERING container on DN restarts

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigurationSource.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeInfo.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeUsage.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestReservedVolumeSpace.java

Currently, We can reserve space on a volume using `hdds.datanode.dir.du.reserved`, which is key-value pair where we specify the volume and the space that should be reserved in that volume (i.e data1:5000MB). If there are multiple volumes we have put a key-value pair of volume:reserved for each volume. This PR aims to create a configuration that sets the percentage of volume reserved for all the volumes in the Datanode.
https://issues.apache.org/jira/browse/HDDS-6901
Patch was tested manually using docker and unit tests.

HDDS-6901. Configure HDDS volume reserved as percentage of the volume space.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerStateManagerImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SequenceIdGenerator.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineStateManagerImpl.java

Found and fixed some `TableIterator` objects in `hdds-server-scm` that were not closed after use.
https://issues.apache.org/jira/browse/HDDS-6725
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2557552003

HDDS-6725. Close Rocks objects properly in StorageContainerManager

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ReplicationConfig.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/keys/PutKeyHandler.java

Cluster-level replication for EC was introduced in HDDS-6294.
When client side and bucket level replication config are both missing,
client will pass `null` as replication config to let OM decide.
The first problem is NPE in createStreamKey() if replication config is `null`.
The second problem is, since streaming is not compatible for writing EC keys,
we cannot determine when to use streaming just by key size and client side replication config.
In this PR, I have added a explicit `--stream` flag in ozone shell key handler.
In stream mode, replication config will fallback to client side defaults when missing.
And it will be checked to ensure not using streaming to write an EC key.
https://issues.apache.org/jira/browse/HDDS-6955
Manual test
```bash
ozone sh --verbose key put --stream …
```

HDDS-6955. [Ozone-streaming] Add explicit stream flag in ozone shell

---

hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/TestReconCodecs.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestTaskStatusService.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/filters/TestAdminFilter.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/fsck/TestContainerHealthStatus.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/fsck/TestContainerHealthTask.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/fsck/TestContainerHealthTaskRecordGenerator.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/persistence/AbstractReconSqlDBTest.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/persistence/TestReconInternalSchemaDefinition.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/persistence/TestSqlSchemaSetup.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/persistence/TestStatsSchemaDefinition.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/persistence/TestUtilizationSchemaDefinition.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/AbstractReconContainerManagerTest.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconContainerManager.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconIncrementalContainerReportHandler.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconPipelineReportHandler.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/spi/impl/TestStorageContainerServiceProviderImpl.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestFileSizeCountTask.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestReconTaskControllerImpl.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestTableCountTask.java

Migrate simple tests in ozone-recon to JUnit5.
https://issues.apache.org/jira/browse/HDDS-6954
https://github.com/kaijchen/ozone/actions/runs/2568738472

HDDS-6954. Migrate simple tests in ozone-recon to JUnit5

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OzoneFSUtils.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestListKeysWithFSO.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestObjectStoreWithFSO.java

https://issues.apache.org/jira/browse/HDDS-6992
Say, Files & Dirs in the namespace:
/a1/b1/c1/c1.tx;
/a110.tx
/a111.tx
/x/y/z/z1.tx
/dir1/dir2/dir3/d11.tx
Expected List:
[a1/, a1/b1/, a1/b1/c1/, a1/b1/c1/c1.tx, a110.tx, a111.tx, dir1/, dir1/dir2/, dir1/dir2/dir3/, dir1/dir2/dir3/d11.tx, x/, x/y/, x/y/z/, x/y/z/z1.tx]
Added tests

HDDS-6992. ListKeys : SubPaths with a mixture of files and dirs breaks sorted order

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ReplicationConfigValidator.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestSecureOzoneRpcClient.java

Validate keys while putting a key 
https://issues.apache.org/jira/browse/HDDS-6889
Unit test, Integration Test

HDDS-6889. EC: put key command with EC replication can use ReplicationConfig validator

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/BlockDeletingServiceMetrics.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingService.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java

Currently we only have metrics of block deleting service on SCM, this ticket is to add the metrics on datanode side.
https://issues.apache.org/jira/browse/HDDS-6981
unit test

HDDS-6981. Add metrics for BlockDeletingService on Datanode

---

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OmBucketGenerator.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OmBucketRemover.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OmKeyGenerator.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OzoneClientKeyGenerator.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OzoneClientKeyRemover.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OzoneClientKeyValidator.java

While executing any of the following `ozone freon` commands:
```
ozone freon ockg --help
ozone freon ockv --help
ozone freon ockr --help
ozone freon ombg --help
ozone freon omkg --help
ozone freon ombr --help
```
the `-v, --volume` description reads “Name of the `bucket`…” instead of `volume`:
```
-v, --volume=<volumeName>
Name of the bucket which contains the test data. Will
be created if missing.
Default: vol1
```
https://issues.apache.org/jira/browse/HDDS-6999
NA

HDDS-6999. Correct volume parameter description for freon test tools

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerSelectionCriteria.java

Excluding EC containers from balancing by removing them from the set of Candidate containers selected in `ContainerBalancerSelectionCriteria`.
https://issues.apache.org/jira/browse/HDDS-6940
Existing UTs.

HDDS-6940. EC: Skip the EC container for balancer

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMOpenKeysDeleteRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMOpenKeysDeleteRequest.java

Ignore keys with higher updateID in OpenKeyDeleteRequest, see:
https://issues.apache.org/jira/browse/HDDS-6998
`TestOMOpenKeysDeleteRequest#testDeleteKeyWithHigherUpdateID()`

HDDS-6998. Ignore keys with higher updateID in OpenKeyDeleteRequest

---

CONTRIBUTING.md
hadoop-ozone/fault-injection-test/network-tests/src/test/blockade/README.md

* Maven 3.6 required for frontend-maven-plugin 1.12.0
* Omit blockade as requirement, move link to blockade-specific README
* Robot and Hugo are installed by test scripts on-demand (HDDS-4969, HDDS-6512), no need to manually install
* Remove duplicate docker-compose requirement
* Avoid `mvn install` (installing Ozone into local repo may hide build errors)
* Prefer `run.sh` over `docker-compose` command in `ozone` compose environment
* Improve contribution workflow (some more detailed steps)
* Remove mention of advanced docker-related Maven profiles
* Describe check scripts
* Document bad class file problem encountered in IDEA
https://issues.apache.org/jira/browse/HDDS-6994
:eyes:

HDDS-6994. Update Contributing guide

---

hadoop-ozone/dist/src/main/compose/upgrade/compose/ha/docker-config

Recon previously showed zero datanodes at the Overview and Datanodes pages in the `./compose/upgrade/compose/ha/` environment. I added the recon address (recon:9891) in the docker-config file, which fixed it.
https://issues.apache.org/jira/browse/HDDS-6588
I created a cluster in the `./compose/upgrade/compose/ha/` directory, checked the Recon page at http://localhost:9888/ and the datanode number was correct, I was able to see each datanode.

HDDS-6588. Recon shows zero datanodes with `./compose/upgrade/compose/ha/`

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/ReconstructECContainersCommand.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/ReplicateContainerCommand.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/states/endpoint/TestHeartbeatEndpointTask.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/protocol/commands/TestReconstructionECContainersCommands.java
hadoop-hdds/interface-server/src/main/proto/ScmServerDatanodeHeartbeatProtocol.proto
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnderReplicatedProcessor.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnhealthyReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationTestUtil.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestUnderReplicatedProcessor.java

We need some sort of thread which picks work from the under / over replicated queue and assigns the work to DNs with capacity. The DNs will pick the work up on each heartbeat.
This initial change does not consider DN capacity or any limits. It will process all under replicated EC containers and assign them to the DN.
https://issues.apache.org/jira/browse/HDDS-6895
New unit tests added

HDDS-6895. EC: ReplicationManager - Logic to process the under replicated queue and assign work to DNs

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/audit/AuditLogger.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/audit/AuditMarker.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/audit/TestOzoneAuditLogger.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/BucketEndpoint.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/EndpointBase.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/signature/AWSSignatureProcessor.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/signature/AuthOperation.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/signature/AuthorizationV2HeaderParser.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/signature/AuthorizationV4HeaderParser.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/signature/AuthorizationV4QueryParser.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/signature/Credential.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/signature/MalformedResourceException.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/signature/SignatureParser.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/util/AuditUtils.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/TestOzoneClientProducer.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/signature/TestAuthorizationV2HeaderParser.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/signature/TestAuthorizationV4HeaderParser.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/signature/TestStringToSignProducer.java

Customer related events, including validation errors, should be logged in Audi logs only. The goal is to avoid a bad client to over load the s3g log and keep s3g log purely for internal issues.
https://issues.apache.org/jira/browse/HDDS-6904
Manual test.

HDDS-6904. Cleanup customer related events in S3G logs

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerHealthResult.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationTestUtil.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestUnderReplicatedProcessor.java

When processing containers, we should skip the open containers until they are closed.
https://issues.apache.org/jira/browse/HDDS-7020
New unit tests

HDDS-7020. EC: ReplicationManager - skip processing open containers

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancer.java

In some cases, balancer displays size of data moved as 0GB even after scheduling some moves and successfully completing an iteration. Check the [Jira](https://issues.apache.org/jira/browse/HDDS-6976) for one such example. This happens even though containers have actually been moved, implying that the problem is in calculating the size. 
The cause could be division of two long values causing a truncation of the fractional part in `ContainerBalancer#moveContainer()`: 
```
metrics.incrementDataSizeMovedGBInLatestIteration(
containerInfo.getUsedBytes() / OzoneConsts.GB);
```
If container sizes are less than a GB, the result would be 0.
This PR sets this metric at the end of the iteration instead of incrementing it after every move. Result is logged as a double value. …

HDDS-6976. 0GB data moved by container balancer after successful iteration

---

hadoop-ozone/common/pom.xml
hadoop-ozone/dist/src/main/license/jar-report.txt
hadoop-ozone/ozone-manager/pom.xml
pom.xml

Removed the tcnative property from dependencies at it is already included in netty.
Here is the link: [HDDS-6807](https://issues.apache.org/jira/browse/HDDS-6807)
All unit/integration tests were run in the forked repository's pipeline as well as local deployment to see if the application still runs.

HDDS-6807. Remove tcnative.version property

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NetworkTopologyImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/SCMCommonPlacementPolicy.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementCapacity.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRackAware.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRackScatter.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRandom.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelinePlacementPolicy.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementCapacity.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackAware.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackScatter.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationTestUtil.java

When the object of the Class DataNodeDetails is built from protobuf only UUID of the datanode is added which is used for the hashcode. Thus not passing any information about the topology. While excluding datanodes the object is built from protobuf. NetworkTopology removes all nodes from the list which does not fall under the scope while selecting a random node. Default scope value is "/default-rack/" which won't match the required scope. Thus pass the proper object of DatanodeDetails while trying to get the random node from NetworkTopology should fix this.
https://issues.apache.org/jira/browse/HDDS-7015
Stage Test. Writing a unit test would be flaky.

HDDS-7015. Ensure excluded nodes have network location when used in placement policies

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerDoubleBuffer.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/metrics/OzoneManagerDoubleBufferMetrics.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerDoubleBufferWithDummyResponse.java

Though there're already metrics for double buffer in OM, none of them capture the current queue size.
This PR adds the metrics.
https://issues.apache.org/jira/browse/HDDS-7024
Unit test, and also manual test to verify that the expected metric can be seen in Prometheus.

HDDS-7024. Add queue size metric for OM double buffer

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java

Block files are not closed in `PutBlock`, because client does not set `size` in `BlockData` (it is calculated by the DN, so we could use that, though).  Let's use the list of chunks to decide if `finishWriteChunks` should be called or not.
https://issues.apache.org/jira/browse/HDDS-7034
```
$ sudo yum install -y lsof
...
Installed:
lsof.x86_64 0:4.87-6.el7
$ ozone freon ockg -n100 -s10
...
Successful executions: 100
$ lsof -u hadoop | grep '/chunks/' | wc -l
0
```
Existing tests cover functionality.
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2717806549

HDDS-7034. File handle leak on datanode in PutBlock

---

hadoop-ozone/dist/src/main/compose/ozone/monitoring.conf

Enable RocksDB statistics in the sample `ozone` docker-compose environment's [monitoring extension](https://github.com/apache/ozone/blob/master/hadoop-ozone/dist/src/main/compose/ozone/README.md#monitoring).
https://issues.apache.org/jira/browse/HDDS-7036
```
cd hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/ozone
export COMPOSE_FILE=docker-compose.yaml:monitoring.yaml
OZONE_REPLICATION_FACTOR=3 ./run.sh -d
sleep 60
docker-compose exec -T scm ozone freon ockg -n1 -t1
```
Verified that JMX endpoint shows RocksDB stats:
```
$ curl -LSs http://localhost:9874/jmx
...
}, {
"name" : "Hadoop:service=Ozone,name=RocksDbStore,dbName=om.db",
...
"NUMBER_KEYS_WRITTEN" : 14,
"NUMBER_KEYS_READ" : 7,
...
```
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2719241954

HDDS-7036. Enable RocksDB stats in monitoring sample config

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/multitenant/OMRangerBGSyncService.java

Fix the warning message. It was incomplete in HDDS-6909.
Background: Ozone S3 Multi-Tenancy currently requires Ranger admin privilege to work because currently Ranger Admin Server doesn't support Ranger non-admin to getPolicyVersion, create/update/delete Ranger role. The message should be revised once Ranger implemented these features.
https://issues.apache.org/jira/browse/HDDS-7021
- All existing tests should pass.

HDDS-7021. [Multi-Tenant] Fix warning message when OM BG Sync is unable to get Ozone service policy version from Ranger

---

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/NodeEndpoint.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/DatanodeMetadata.java
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/datanodes/datanodes.tsx

Currently the network location information is not shown in Recon's Datanode page, this information would be quite useful when networktopology is in use.
https://issues.apache.org/jira/browse/HDDS-6767

HDDS-6767. Add network location in Recon's datanode page

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/RepeatedOmKeyInfo.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java

The error is causing OM's crash. Should be caused by concurrent change on RepeatedOmKeyInfo's omKeyInfo list.
```
2022-07-22 15:20:39,215 [OMDoubleBufferFlushThread] ERROR org.apache.hadoop.ozone.om.ratis.OzoneManagerDoubleBuffer: Terminating with exit status 2: OMDoubleBuffer flush threadOMDoubleBufferFlushThreadencountered Throwable error
java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
at java.util.ArrayList$Itr.next(ArrayList.java:859)
at org.apache.hadoop.ozone.om.helpers.RepeatedOmKeyInfo.getProto(RepeatedOmKeyInfo.java:70)
at org.apache.hadoop.ozone.om.codec.RepeatedOmKeyInfoCodec.toPersistedFormat(RepeatedOmKeyInfoCodec.java:50)
at org.apache.hadoop.ozone.om.codec.RepeatedOmKeyInfoCodec.toPersistedFormat(RepeatedOmKeyIn …
```

HDDS-7041. Avoid ConcurrentModificationException in RepeatedOmKeyInfo

---

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/datanodes/datanodes.tsx

[A patch earlier](https://github.com/apache/ozone/pull/3429) unintentionally changed the leader count's dataIndex from `leaderCount` to `leader Count` in the datanodes.tsx, I changed it back. 
https://issues.apache.org/jira/browse/HDDS-7046
I tested it in docker-compose environment and the leader count is visible again.

HDDS-7046. Leader count missing in Recon

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMultiTenantManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/multitenant/CachedTenantState.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOMMultiTenantManagerImpl.java

On startup, the tenant cache is built from the DB by iterating the access ID table. If the tenant does not have any users, there will be no corresponding entries in the access ID table and the cache will not contain an entry for that tenant, even though there is info for that tenant in the DB's tenant state table. This leads to incorrect behavior while the OM is running.
HDDS-7042
Unit test added.

HDDS-7042. Rebuilding tenant cache omits empty tenants

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

Reposition the initialization of `ozoneLockProvider`: 
`ozoneLockProvider = new OzoneLockProvider(getKeyPathLockEnabled(), getEnableFileSystemPaths())`
currently present at [OzoneManager.java#L1545](https://github.com/apache/ozone/blob/master/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java#L1545) below `metadataManager.start(configuration)` at [OzoneManager.java#L1468](https://github.com/apache/ozone/blob/master/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java#L1468).
https://issues.apache.org/jira/browse/HDDS-6956
Existing UTs.

HDDS-6956. Reposition ozoneLockProvider initialization in OzoneManager

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisServerImpl.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestStorageContainerManagerHA.java

The current logic to decide the LEADER of SCM is to check if the RaftPeer is local, https://github.com/apache/ozone/blob/master/hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisServerImpl.java#L268
I assuem this is because the "scm roles" requests are forwarded to the LEADER SCM, so the invoker is always the leader, thus "isLocal" is used to decide which SCM is LEADER.
But in SCM UI, the "SCM HA (roles)" information are retrived by invoking "getRatisRoles" by each SCM, not forwarded to the LEADER SCM, thus each SCM will consider itself as the LEADER in UI.
https://issues.apache.org/jira/browse/HDDS-6728
unit test.

HDDS-6728. SCM UI not showing correct HA roles

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECOverReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECOverReplicationHandler.java

ContainerReplicaPendingOps needs to track the replica index of any pending replicas. In ECOverReplicationHandler we missed setting the repIndex of the replica in the delete command.
https://issues.apache.org/jira/browse/HDDS-7057
Modified a unit test

HDDS-7057. EC: ReplicationManager - Over replication handler should set repIndex on delete cmds

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerData.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestKeyValueContainerData.java

When an EC container is replicated (not reconstructed) the replica index gets lost when it is imported. We need to ensure the index is copied from the source container data to the new container data.
https://issues.apache.org/jira/browse/HDDS-7056
New unit test added and manually verified.

HDDS-7056. EC: Ensure replica index is maintained when replicating a container

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/TokenHelper.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/TestHddsDatanodeService.java

Fix the exception:
```
ERROR org.apache.hadoop.ozone.HddsDatanodeService: Exception in HddsDatanodeService.
at org.apache.hadoop.ozone.container.ec.reconstruction.TokenHelper.<init>(TokenHelper.java:68)
at org.apache.hadoop.ozone.container.ec.reconstruction.ECReconstructionCoordinator.<init>(ECReconstructionCoordinator.java:119)
at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.<init>(DatanodeStateMachine.java:185)
at org.apache.hadoop.ozone.HddsDatanodeService.start(HddsDatanodeService.java:279)
```
triggered by such config:
```xml
<property>
<name>hdds.block.token.enabled</name>
<value>true</value>
</property>
<property>
<name>hdds.container.token.enabled</name>
<value>true</value>
</property>
<property> …
```

HDDS-7055. NPE in ec.reconstruction.TokenHelper

---

hadoop-hdds/docs/content/interface/ReconApi.md
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/ContainerEndpoint.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestContainerEndpoint.java

Recon's `/missing` endpoint didn't have a limit set (it was set to `Integer.MAX_VALUE`), which caused Recon to be unresponsive. I added a query parameter called limit and set it 1000 as default.
https://issues.apache.org/jira/browse/HDDS-7050
https://github.com/dombizita/ozone/actions/runs/2732085430

HDDS-7050. Recon "/missing" endpoint return limit too high

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneKeyDetails.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneBucketStub.java

Remove the additional lookupKeys calls in getObject API.
https://issues.apache.org/jira/browse/HDDS-7059
Unit, rotbot.

HDDS-7059. S3G should not call lookup twice for Get Object

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinator.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinatorTask.java

Wrongly re throwing the exception before fully finishing the cleanup loop.
https://issues.apache.org/jira/browse/HDDS-7068
Depending existing tests.

HDDS-7068. EC: Prematurely re-throwed the exception in reconstruction cleanup loop.

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockReconstructedStripeInputStream.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java

Adding debug Logs for EC Stripe Write Failures
https://issues.apache.org/jira/browse/HDDS-7048
Logging Changes

HDDS-7048. EC: Add debug logging with exception info when stripe write failed

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationTestUtil.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java

If a container has a missing replica, and some decommission replicas, then it will have both a reconstruction and replication command scheduled when it is processed for under replication.
However, the target node picked for the reconstruction is not excluded when picking nodes for the replication, so it would be possible for both commands to target the same node with different indexes.
We need to track all nodes selected when processing under replication to ensure they are not used twice.
https://issues.apache.org/jira/browse/HDDS-7069
New unit test

HDDS-7069. EC: ReplicationManager - Track nodes already used when handing under replication

---

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OmBucketReadWriteKeyOps.java

Replace `bucket.listKeys()` with the `bucket.listStatus()` method for simulating synthetic read operation workload in `OmBucketReadWriteKeyOps` Freon class since `bucket.listStatus()` uses the `OzoneManagerLock.acquireReadLock()` method which would hence serve more useful for the sake of benchmarking the lock performance.
https://issues.apache.org/jira/browse/HDDS-6951
Existing integration tests.

HDDS-6951. Replace bucket.listKeys() with bucket.listStatus() in OmBucketReadWriteKeyOps

---

dev-support/ci/selective_ci_checks.bats
dev-support/ci/selective_ci_checks.sh

Avoid triggering all tests:
* for workflows except `post-commit.yml`: they are not exercised by any jobs in the `post-commit.yml` (`build-branch`) workflow, so running those jobs is useless
* for `pr_title_check.*`: these are covered by specific checks (_rat_ for license, and _bats_ for bash unit tests)
https://issues.apache.org/jira/browse/HDDS-7044
Added test case in `selective_ci_checks.bats`.  Also checked output for the commit (96009ab20) for HDDS-7043 locally:
```
$ bash dev-support/ci/selective_ci_checks.sh 96009ab20
...
All 2 changed files are known to be handled by specific checks.
needs-basic-checks=true
basic-checks=["rat","bats"]
needs-build=false
needs-compile=false
needs-compose-tests=false
needs-dependency-check=false
needs-integration-tests=false …
```

HDDS-7044. Ignore pr_title_check for selective checks

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/SnapshotInfo.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmSnapshotInfo.java
hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java
hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/codec/OmDBSnapshotInfoCodec.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/codec/OMDBDefinition.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestSnapshotInfo.java

Adding support for snapshot metadata in ozone manager.  Snapshot metadata is to be stored in the ozone manager RocksDB database as an additional `SnapshotInfo` column family.  Metadata for each snapshot created is captured in a `SnapshotInfo` entry (schema as defined in `CheckpointBasedDesign` doc) and inserted into the RocksDB snapshot table.
Included in this is the schema `SnapshotInfo` entry builder, protobuf definition, `OmMetadataManager` integration and unit tests testing `SnapshotInfo` entry accessors, and `RocksDB` table creation, Snapshot entry additions and deletions.
https://issues.apache.org/jira/browse/HDDS-6849
Unit tests:
i.) testing `SnapshotInfo` metadata data structure holding state info for object store snapshots. - `TestOmSnapshotInfo`
ii.) testing `SnapshotInfo` …

HDDS-6849. OM changes for tracking Snapshot Metadata

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingService.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java

EC Block is never deleted due to BlockDeletingService#isDeletionAllowed() throwing Exception.
```
2022-08-02 10:53:47,890 [BlockDeletingService#3] WARN  background.BlockDeletingService (BlockDeletingService.java:getTasks(171)) - Unexpected error occurs during deleting blocks.
java.lang.IllegalArgumentException: Invalid UUID string: 
at java.util.UUID.fromString(UUID.java:194)
at org.apache.hadoop.ozone.container.keyvalue.statemachine.background.BlockDeletingService.isDeletionAllowed(BlockDeletingService.java:200)
```
This patch is a workaround for now, and requires redesign in the future.
https://issues.apache.org/jira/browse/HDDS-7077
Integration test `TestBlockDeletion#testBlockDeletion()`.

HDDS-7077. EC: Fix block deletion not allowed due to missing pipelineID

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/OverReplicatedProcessor.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnderReplicatedProcessor.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/BackgroundSCMService.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java

When there are two replicas online with the same index, eg due to decommission, over-replication or maintenance, and the container is under replicated due to another missing index, an illegal argument exception can be thrown when collecting the source indexes:
```
2022-08-02 10:54:26,939 WARN org.apache.hadoop.hdds.scm.container.replication.ECUnderReplicationHandler: Exception while processing for creating the EC reconstruction container commands for #2.
java.lang.IllegalStateException: Duplicate key 3 (attempted merging values ContainerReplica{containerID=#2, state=CLOSED, datanodeDetails=fb63a3c8-2e5b-432e-be63-274c41aab79f{ip: 172.27.124.131, host: quasar-onjdpu-5.quasar-onjdpu.root.hwx.site, ports: [REPLICATION=9886, RATIS=9858, RATIS_ADMIN=9857, RATIS_SERVER=9856, STANDALONE=9859], …
```

HDDS-7081. EC: ReplicationManager - UnderRep handler should handle duplicate indexes

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestECKeyOutputStream.java

Fix offset Condition in ECKeyOutputStream
Condition checking with offset+writtenLen !< length if offset is not zero.
https://issues.apache.org/jira/browse/HDDS-7051
Current flows all have offset =0.

HDDS-7051. Fix offset Condition in ECKeyOutputStream

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/metrics/TestContainerMetrics.java

Increase createContainer metric when writing chunk to a datanode if there is no current container in datanode yet
https://issues.apache.org/jira/browse/HDDS-7063
Manual tests on developer's laptop

HDDS-7063. Increment createContainer metric when container is created while writing chunk

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/ChunkUtils.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/helpers/TestChunkUtils.java

Replace the spinlock in ChunkUtils with exponentially backoff timed wait.
https://issues.apache.org/jira/browse/HDDS-4970
The patch is applied and verified to work in a 20-node test cluster running Impala TPC-DS workload.

HDDS-4970. Significant overhead when DataNode is over-subscribed

---

pom.xml

Upgrade gRPC dependency used for S3-OM gRPC communication to 1.48.1.
Datanode-side gRPC will be upgraded later via new Ratis release.
https://issues.apache.org/jira/browse/HDDS-7085
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2808890973

HDDS-7085. Update gRPC to 1.48.1 to address OOM bug

---

dev-support/ci/pr_title_check.bats
dev-support/ci/pr_title_check.sh

When opening a PR on Github, title is filled from commit message. If it is too long, an ellipsis (…) is added, and the rest of the message is moved to the PR description. The partial PR title could then end up in the final commit message if not corrected during merge. We should avoid such titles.
https://issues.apache.org/jira/browse/HDDS-7043
Added test case in `pr_title_check.bats`.
https://github.com/adoroszlai/hadoop-ozone/runs/7651057967?check_suite_focus=true#step:5:41

HDDS-7043. Disallow trailing ellipsis in PR title

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/TestECContainerRecovery.java

When a DN is Shutdown, SCM closes the pipeline and the containers associated with the DN. The `NodeManager` sends `closePipeline` and `closeContainer` commands to the DNs when it comes back as a response to DN heartbeat. In the event the commands on the NodeManager are gone (eg: SCM restart). The EC Container is left OPEN forever. This patch aims to close these OPEN containers. 
https://issues.apache.org/jira/browse/HDDS-7022
This patch was manually tested on a cluster and also using integration test.

HDDS-7022. EC: Open EC container are not closed when SCM container was already closed.

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/utils/db/DatanodeDBProfile.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/AbstractDatanodeStore.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBProfile.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBStoreBuilder.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TableConfig.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedBlockBasedTableConfig.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedColumnFamilyOptions.java
pom.xml

DBProfile and its related RocksDB settings components creates a number of RocksObjects which are left unclosed.
This PR is a result of hunting those RocksObjects and ensure they're closed before GC.
Key changes:
- In RocksDatabase, many `TableConfig` objects is created and then filtered (org.apache.hadoop.hdds.utils.db.RocksDatabase#open). Each [TableConfig](https://github.com/duongnguyen0/ozone/blob/a43b3da2ab8c9e5684436e7c89adb228712068e7/hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TableConfig.java#L35-L35) object encloses a ColumnFamilyOptions instance. The pattern of creating before filtering needs to be inverse.
- ColumnFamilyOptions itself is RocksObject but also consists of a hierarchy of other RocksObjects which are not closed automatically by …

HDDS-7116. Avoid leaking RocksObject from DBProfile

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/BaseFileChecksumHelper.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/ReplicatedFileChecksumHelper.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/checksum/TestReplicatedFileChecksumHelper.java

Support both CRC32 an CRC32C for Ozone to make it possible to replicate files between HDFS and Ozone.
https://issues.apache.org/jira/browse/HDDS-6127
Unit tests.

HDDS-6127. file checksum to support both CRC32 and CRC32C.

---

hadoop-ozone/dist/src/main/license/bin/LICENSE.txt
hadoop-ozone/dist/src/main/license/jar-report.txt
hadoop-ozone/ozone-manager/pom.xml

Exclude:
```
com.amazonaws:aws-java-sdk-bundle
org.apache.hive:hive-storage-api
org.apache.kafka:kafka-clients
org.apache.solr:solr-solrj
```
https://issues.apache.org/jira/browse/HDDS-7102

HDDS-7102. Exclude unnecessary RangerClient dependencies

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/AvailableSpaceFilter.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/CapacityVolumeChoosingPolicy.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/RoundRobinVolumeChoosingPolicy.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeChoosingUtil.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestCapacityVolumeChoosingPolicy.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestRoundRobinVolumeChoosingPolicy.java

Added new log messages:
* If `VolumeChoosingPolicy` finds no volumes which have enough available space for a new container, it logs an info level message, showing space for all volumes.
* Otherwise, any volumes with not enough available space are logged at debug level.
Both messages include actual free space and committed space (reserved for existing open containers).
https://issues.apache.org/jira/browse/HDDS-7033
Verified log messages in updated unit test.
Also tested on docker-compose cluster, by creating empty containers (size set to 10GB in config) until it failed.  Checked datanode log:
```
2022-07-28 10:23:35,663 [ChunkReader-5] INFO volume.RoundRobinVolumeChoosingPolicy: No volumes have enough space for a new container.  Most available space: 5682657280 bytes; required space: …
```

HDDS-7033. Include committed space in log for disk out of space

---

hadoop-hdds/docs/content/security/SecuringTDE.md
hadoop-hdds/docs/content/security/SecuringTDE.zh.md

The following docs issues are fixed:
* hadoop.security.key.provider.path must be set up via core-site.xml, not hdfs-site.xml
* encKey" is invalid name for hadoop kms key. Uppercase characters are not supported for keys
https://issues.apache.org/jira/browse/HDDS-7127
Unit tests are passed. No additional testing needed for documentation change.

HDDS-7127. Fix Transparent Data Encryption documentation

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/EndpointStateMachine.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/EndpointStateMachineMBean.java

Add a new MBean interface to export the type of end point.
https://issues.apache.org/jira/browse/HDDS-7074
This is the new EndpointStateMachineMBean output:
```
{
"name": "Hadoop:service=HddsDatanode,name=SCMConnectionManager",
"modelerType": "org.apache.hadoop.ozone.container.common.statemachine.SCMConnectionManager",
"SCMServers": [
{
"addressString": "localhost/127.0.0.1:9891",
"lastSuccessfulHeartbeat": 1659536391,
"missedCount": 0,
"state": "HEARTBEAT",
"type": "Reconn",
"versionNumber": 0
},
{
"addressString": "localhost/127.0.0.1:9861",
"lastSuccessfulHeartbeat": 0,
"missedCount": 0,
"state": "REGISTER",
"type": "SCM",
"versionNumber": 1
}
]
}
```

HDDS-7074. DN EndpointStateMachineMBean to add getType()

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/HddsVolume.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeIOStats.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestVolumeIOStatsWithPrometheusSink.java

Prometheus can't distinguish between different volumes when getting data about VolumeIOStats. It's due to a MetricTag missing that would separate the volumes. Adding an additional tag fixes this issue.
[HDDS-7120](https://issues.apache.org/jira/browse/HDDS-7120)
Added unit test for multiple VolumeIOStats.
Also deployed locally via a local docker container, different VolumeIOStats did show up.

HDDS-7120. Fix Prometheus reporting only 1 VolumeIOStat

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/recon/ReconConfigKeys.java
hadoop-hdds/docs/content/concept/Recon.md
hadoop-hdds/docs/content/concept/Recon.zh.md
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/PipelineEndpoint.java
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/pipelines/pipelines.tsx

The Last Leader Election and No. of Elections columns in the Pipelines page had incorrect or no data previously. This issue is caused by a few small things. These columns only have data, if any metrics service providers like Prometheus is configured, which is assumable from a [comment](https://github.com/apache/ozone/blob/64032cc223d314ac1e93558dc538663cec4a1a92/hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/PipelineEndpoint.java#L108) in the code. I added a tooltip to these columns with this information and if no metrics service provider is configured in the cluster, the columns will show NA.
If you configured Prometheus the No. of Elections had data, but the Last Leader Election didn't. This happened, because the Last Leader Election's metric name was incorrect. …

HDDS-7045. Election info is out of date in Recon

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainer.java

Add container file path to error message when writing to container encounters an error
[HDDS-7076](https://issues.apache.org/jira/browse/HDDS-7076)
Reproduce the error on a local cluster via taking away the write permission on container data by making its folder read only.

HDDS-7076. Log container file path when container cannot be written.

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/multitenant/RangerClientMultiTenantAccessController.java

`RangerClientMultiTenantAccessController#decodeRSEStatusCodes` assumes the provided RangerServiceException will have a non-null status. However, Looking at the [constructors for the class](https://github.com/apache/ranger/blob/master/intg/src/main/java/org/apache/ranger/RangerServiceException.java) this may not always be true, and we have seen exceptions will null statuses during testing.
HDDS-7134
N/A

HDDS-7134. NPE when Ranger client throws RangerServiceException without Status.

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java

`DirectoryDeletingService` is supposed to run every 60s by default for FSO buckets. Due to a wrong conversion, Instead of 60s it runs every 60000s~=16hours.
https://issues.apache.org/jira/browse/HDDS-7147
The patch was tested manually on a real cluster.

HDDS-7147. DirectoryDeletingService doesn't run in the expected interval for FSO

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ChunkInputStream.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestChunkInputStream.java

Release buffers when ChunkInputStream is closed.
https://issues.apache.org/jira/browse/HDDS-7136
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2880737539

HDDS-7136. Memory leak due to ChunkInputStream.close() not releasing buffer

---

hadoop-ozone/dist/src/main/smoketest/s3/objectputget.robot
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/BucketEndpoint.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/EndpointBase.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java

Providing wrong signature (authentication) for S3 request should result in access denied (403), but currently it results in server error (500) instead:
```
$ kinit -kt /etc/security/keytabs/scm.keytab scm/scm@EXAMPLE.COM
$ ozone sh bucket create /s3v/bucket
$ ozone sh key put /s3v/bucket/passwd /etc/passwd
$ curl -i -X GET 'http://s3g:9878/bucket/passwd' -H 'Authorization: AWS scm/scm@EXAMPLE.COM:asdfqwerty'
HTTP/1.1 500 Server Error
...
```
Server-side log:
```
s3g_1       | 2022-08-18 17:58:41,466 [qtp1178587240-20] WARN server.HttpChannelState: unhandled due to prior sendError
s3g_1       | javax.servlet.ServletException: javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: INVALID_TOKEN org.apache.hadoop.ozone.om.exceptions.OMException: User …
```

HDDS-7139. INVALID_TOKEN is handled as internal error in S3G

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/contract/AbstractContractUnbufferTest.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java
hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java
hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java

https://issues.apache.org/jira/browse/HDDS-7135
Make sure that OFS returns an input stream that is wrapped by CapableOzoneFSInputStream when it is shaded with Hadoop3 dependency. CapableOzoneFSInputStream support StreamCapabilities API.
The StreamCapabilities API is added only in Hadoop3, so the Hadoop2-based filesystem jar returns the input stream wrapped by OzoneFSInputStream.
A simple assertion is added to validate the StreamCapabilities in the file system contrast test.

HDDS-7135. ofs file input stream should support StreamCapabilities interface

---

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/BaseFreonGenerator.java

Currently if turned on the fail-at-end option and the freon tasks have failures, `shotdown()` will be processed. It waits for the progress bar to be completed, while the progress bar will not naturally finish as there are failures. Thus the freon gets stuck.
```
if (failureCounter.get() > 0 && !failAtEnd) {
progressBar.terminate();
} else {
progressBar.shutdown();
}
```
We shall simply remove the flag check here,  when Freon goes into ```shutdown```, it has processed all tasks in     waitForCompletion().
https://issues.apache.org/jira/browse/HDDS-7150
Manual test on the cluster

HDDS-7150. Freon fail-at-end option caused not shutdown

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ReplicationConfigValidator.java

Based on replication type, ReplicationConfigValidator returns different error messages
This is a patch for jira https://issues.apache.org/jira/browse/HDDS-7108
CI tests

HDDS-7108. Make ReplicationConfig validation error message type-specific

---

.github/workflows/close-pending.yaml
.github/workflows/comments.yaml
.github/workflows/post-commit.yml

Github [has deprecated the Ubuntu 18.04 runner image](https://github.com/actions/runner-images/issues/6002).  While 18.04 will be unsupported only after 11/30/2022, there will be periodic "brownout" periods when builds using 18.04 will fail.
This PR upgrades to 20.04.
https://issues.apache.org/jira/browse/HDDS-7159
`build-branch` workflow:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2904661184
(Not completely finished yet, but each check (integration, acceptance, etc.) has at least one finished run.)
The other two workflows are not tested, but unlikely to have anything version-specific.

HDDS-7159. Upgrade ubuntu version from 18.04 to 20.04

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingService.java

Currently, if a runtime error happened and `LOG.isDebugEnabled() == false`, there are no logs recorded in the DN,  which lead to inconvenience when checking certain error.
So, log the error msg explicitly in BlockDeletingService
https://issues.apache.org/jira/browse/HDDS-7157
/

HDDS-7157. Log the error msg explicitly in BlockDeletingService

---

.github/workflows/post-commit.yml

Follow-up to #3707: run integration tests on Java 8.  `TestSecureOzoneCluster` is failing on Java 11.
https://issues.apache.org/jira/browse/HDDS-7159
https://github.com/adoroszlai/hadoop-ozone/runs/7957021440?check_suite_focus=true

HDDS-7159. Run integration tests on Java 8

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/report/ReportManager.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/report/ReportPublisher.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/report/ReportPublisherFactory.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/StateContext.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/endpoint/HeartbeatEndpointTask.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/CommandForDatanode.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/SCMCommand.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/report/TestReportPublisher.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/TestStateContext.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/CodecRegistry.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/StatefulService.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/io/CodecFactory.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/io/EnumCodec.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/io/GeneratedMessageCodec.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/io/ListCodec.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeHeartbeatDispatcher.java

`GeneratedMessage` is Protobuf implementation detail and should not be used by non-generated code.  Replace with usage of the `Message` interface.  This is in preparation of Protobuf upgrade, since Protobuf 3 generates `GeneratedMessageV3` instead.
https://issues.apache.org/jira/browse/HDDS-7151
https://github.com/adoroszlai/hadoop-ozone/actions/runs/2889775897

HDDS-7151. Avoid using GeneratedMessage in non-generated code

---

hadoop-ozone/dist/src/main/smoketest/s3/commonawslib.robot

AWS CLI is pre-installed in ozone-runner docker image since HDDS-4881.  The problem is that HDDS-6264 changed it to install `awscli` via `pip`, not `yum`.  Thus `yum` installs another instance of the tool during test setup:
```
Running command 'sudo -E yum install -y awscli'
...
Installing:
awscli                       noarch 1.23.2-1.el7_9.1             updates 2.3 M
Installing for dependencies:
PyYAML                       x86_64 3.10-11.el7                  base    153 k
jbigkit-libs                 x86_64 2.0-11.el7                   base     46 k
libtiff                      x86_64 4.0.3-35.el7                 base    172 k
libwebp                      x86_64 0.3.0-10.el7_9               updates 170 k
libyaml                      x86_64 0.1.4-11.el7_0               base     55 k
make …
```

HDDS-7164. Skip installing awscli if already present

---

pom.xml

This change was reverted by [HDDS-6828](https://issues.apache.org/jira/browse/HDDS-6828).
I'm checking it back in as memory leak has been fixed as per HDDS-6722
https://issues.apache.org/jira/browse/HDDS-6456
Standard CI. https://github.com/duongnguyen0/ozone/actions/runs/2879138807
Also ran different workloads on my local cluster and verify no leaks were generated.

HDDS-6456. Update RocksDB Version to 7.x

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/Checksum.java

Remove expensive heap memory copy; replace with zero copy wrapper.
https://issues.apache.org/jira/browse/HDDS-7161
Covered by existing UT.

HDDS-7161. Make Checksum.int2ByteString() zero-copy

---

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/recovery/ReconOmMetadataManagerImpl.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/recovery/TestReconOmMetadataManagerImpl.java

Found this when baking RocksDB changes in our internal test cluster.
When updating the database object for a new checkpoint, the existing DB is replaced without closing. 
https://issues.apache.org/jira/browse/HDDS-7166
Unit test, standard CI.

HDDS-7166. Memory leak in Recon when replacing DB for new checkpoint

---

hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/recovery/TestReconOmMetadataManagerImpl.java

Followup HDDS-7166 (#3713), UT is failling because Exception happened when creating new DBStore, which leads to DBStore not replaced.
```
2022-08-25 15:10:45,751 [main] ERROR recovery.ReconOmMetadataManagerImpl (ReconOmMetadataManagerImpl.java:initializeNewRdbStore(94)) - Unable to initialize Recon OM DB snapshot store.
java.io.IOException: Failed init RocksDB, db path : /var/folders/4k/0pm7c7vs4ds216sc45nft3l40000gn/T/junit4663311154991749567/junit8976120310500205625/db.checkpoints/om.db_checkpoint_1661411444529, exception :org.rocksdb.RocksDBException lock hold by current process, acquire time 1661411445 acquiring thread 13095075840: /var/folders/4k/0pm7c7vs4ds216sc45nft3l40000gn/T/junit4663311154991749567/junit8976120310500205625/db.checkpoints/om.db_checkpoint_1661411444529/LOCK: No …
```

HDDS-7173. Fix TestReconOmMetadataManagerImpl#testUpdateOmDB

---

hadoop-ozone/dist/src/main/smoketest/admincli/pipeline.robot

`Close pipeline` test case fails intermittently like this:
```
INFO Running command 'ozone admin pipeline close "028eec27-0d46-45d5-b682-74c543a13bcd"
INFO ${rc} = 0
...
INFO Running command 'ozone admin pipeline list | grep "028eec27-0d46-45d5-b682-74c543a13bcd"
INFO ${rc} = 1
```
The problem is that the pipeline may be removed between the `close` and `list` commands by the background `BackgroundPipelineScrubber` thread:
```
scm1.org_1   | 2022-08-24 10:46:49,350 [IPC Server handler 0 on default port 9860] INFO pipeline.PipelineManagerImpl: Pipeline Pipeline[ Id: 028eec27-0d46-45d5-b682-74c543a13bcd, ...] moved to CLOSED state
scm1.org_1   | 2022-08-24 10:46:50,353 [BackgroundPipelineScrubberThread] INFO pipeline.PipelineManagerImpl: Scrubbing pipeline: id: …
```

HDDS-7172. Intermittent failure in Close pipeline smoketest

---

hadoop-ozone/interface-storage/src/test/java/org/apache/hadoop/ozone/om/codec/TestOmKeyInfoCodec.java

The following usage in TestOmKeyInfoCodec isn't perfect. Can use some help.
} catch (IOException e) {
fail("Should success");
}
Suggest to let the exception to be thrown directly; remove the catch statement.
https://issues.apache.org/jira/browse/HDDS-6493
The existing test cases ran successfully

HDDS-6493. Improve TestOmKeyInfoCodec error handling.

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/recon/ReconConfigKeys.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/OzoneAdmins.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/BaseHttpServer.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/DBCheckpointServlet.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDBCheckpointServlet.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMDbCheckpointServlet.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMDbCheckpointServlet.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMDBCheckpointServlet.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/acl/OzoneNativeAuthorizer.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/acl/TestOzoneAdministrators.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/acl/TestOzoneNativeAuthorizer.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/acl/TestParentAcl.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/acl/TestVolumeOwner.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/filters/ReconAdminFilter.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/filters/TestAdminFilter.java

Two new properties have been added to support admin groups:
- "ozone.administrators.groups" 
- "ozone.recon.administrators.groups"
These properties are somewhat similar to existing "ozone.administrators" and  "ozone.recon.administrators" (hence the naming) but specify groups the user is directly or indirectly a part of.
https://issues.apache.org/jira/browse/HDDS-2954
unit tests and manual testing

HDDS-2954. Support admin groups

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeSchemaThreeDBDefinition.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedSlice.java
hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/GenericTestUtils.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestLDBCli.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmLDBCli.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/DBDefinitionFactory.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/DBScanner.java

https://issues.apache.org/jira/browse/HDDS-7158

HDDS-7158. ldb cli command supports to scan container V3.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerReplica.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestDataUtil.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/node/TestDecommissionAndMaintenance.java

For Ratis, the number of replicas which must be available when a node goes into maintenance is a simple integer defaulting to 2 in hdds.scm.replication.maintenance.replica.minimum.
This means that for a Ratis container, one out of the 3 nodes can be offline without any replication happening. This can be set to 1, letting two go offline or 3 ensuring full redundancy and hence replication when any node is taken offline.
It could be argued that 1 would be a better default here. With the default placement of 2 replicas on one rack and 1 on another rack, that should allow for a full rack to be taken offline without replication.
For EC, its a little more tricky. Aside from Ratis 1 containers, which are rarely used in practice, EC can tolerate 2 offline (for 3-2), 3 (for 6-3) or 4 (for 10-4).
If …

HDDS-6975. EC: Define the value of Maintenance Redundancy for EC containers

---

hadoop-ozone/dev-support/checks/_mvn_unit_report.sh

Timed out tests are now missing from CI bundles:
* HDDS-3078 added timed out tests to CI check bundles
* SUREFIRE-1728 [changed the output](https://github.com/apache/maven-surefire/commit/706346f0b293a2ab834fcb71ff09e70d24799251#diff-bf7f174589af8f08638da17d6aefbe897133b7b77ff363a1e12439c37ea8683eL283) of Surefire plugin
* Ozone upgraded to the version with changed output in HDDS-6095
Example [timeout](https://github.com/apache/ozone/runs/8006028747?check_suite_focus=true#step:6:3118) missing from [summary](https://github.com/apache/ozone/runs/8006028747?check_suite_focus=true#step:7:1).
This PR tweaks the search string used to check for timeouts in output.
https://issues.apache.org/jira/browse/HDDS-7175
Old Surefire version:
```
$ curl -LOSs …
```

HDDS-7175. Timed out tests missing from bundle

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfig.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogStateManagerImpl.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestDeletedBlockLog.java

Currently, we find that the deleted block txns in SCM RDB are not updated anymore.
For the unhealthy container(no healthy replica and not enough replicas), SCM will not commit the txn and remove it from RDB until all desired replicas commit it. SCM will add the committed replica to the map `dnsWithTransactionCommitted` before all replicas commit the txn.
In the process of `getTransactions`, SCM will read the txn out from RDB and try to add it to the result, but if the txn existed in the `dnsWithTransactionCommitted`, SCM will ignore it. No matter whether ignoring the txn, the numBlocksDeletion is still counting this, which will lead to nonsense running, and actually returning empty txns when the cluster has a certain amount of unhealthy containers.
1. use the real num of blocks as the …

HDDS-7125. Inaccurate numBlocksDeletion when getTransactions

---

hadoop-hdds/annotations/src/main/java/org/apache/ozone/annotations/ReplicateAnnotationProcessor.java
hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigFileGenerator.java

Get rid of the warning:
```
[INFO] --- aspectj-maven-plugin:1.14.0:compile (default) @ ozone-manager ---
[INFO] Showing AJC message detail for messages of types: [error, warning, fail]
[WARNING] No SupportedSourceVersion annotation found on org.apache.hadoop.hdds.conf.ConfigFileGenerator, returning RELEASE_6.
<unknown source file>:<no line information>
[WARNING] No SupportedSourceVersion annotation found on org.apache.ozone.annotations.ReplicateAnnotationProcessor, returning RELEASE_6.
<unknown source file>:<no line information>
```
https://issues.apache.org/jira/browse/HDDS-7171
Built locally, verified no warnings:
```
[INFO] --- aspectj-maven-plugin:1.14.0:compile (default) @ ozone-manager ---
[INFO] Showing AJC message detail for messages of types: [error, warning, fail]
[INFO] 
``` …

HDDS-7171. Add SupportedSourceVersion in annotation processors

---

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectGet.java

will get the content in a range( add such as: "Range: bytes=123-" at request header), The backend service needs to return this range of data, and the returned status code should be [206](https://www.rfc-editor.org/rfc/rfc7233#section-4.1)
current Ozone s3 gateway will return 200 instead of 206, this pr will be fixed it.
https://issues.apache.org/jira/browse/HDDS-7200
Send a get request requesting range data, the return status should be 206.

HDDS-7200. Fixed inaccurate get request status code

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/AbstractDatanodeStore.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBStoreBuilder.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java

https://issues.apache.org/jira/browse/HDDS-7197
It uses rocksdb directory name as the jmx bean name.   For Schema V2,  every rocksdb directory like this, 
999998-dn-container.db
999999-dn-container.db
While in Schema V3, all rocksdb has the same directory name "container.db".  Collision happens when rocksdb per disk volume come to  register its metrics to jmx with failure "already exists!" metrics exception.  
This patch add the disk storage UUID as prefix of bean name. So now the bean name for each Schema V3 rocksdb instance will be storageUUID-container.db, here is an example,
DS-d26aea2d-cc3b-42e4-b574-b4644227fa8-ccontainer.db

HDDS-7197. Schema V3 RocksDB instance statitics register as metrics collision

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/node/TestDecommissionAndMaintenance.java

Since changes in [HDDS-6975](https://issues.apache.org/jira/browse/HDDS-6975) the test testContainerIsReplicatedWhenAllNodesGotoMaintenance is failing frequently. This PR is to fix the issues with that test.
https://issues.apache.org/jira/browse/HDDS-7201
Ran test several times locally to ensure it always passes.

HDDS-7201. testContainerIsReplicatedWhenAllNodesGotoMaintenance is failing frequently

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneConfigUtil.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/security/S3SecretRequestHelper.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOzoneConfigUtil.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/security/TestS3GetSecretRequest.java

1. Created new props `ozone.s3.administrators` and `ozone.s3.administrators.groups`
2. In case when at least one of these props is defined all s3 shell operation can be executed only by one of defined user as admin. Each user still should have permission to generate keys for itself.
3. In case when these properties are empty admins should be taken from `ozone.administrators` or `ozone.administrators.groups`
https://issues.apache.org/jira/browse/HDDS-7191
Manual testing and new unit tests

HDDS-7191. Separate prop for s3 admin

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/HddsVolume.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeInfoMetrics.java
hadoop-hdds/container-service/src/main/resources/webapps/hddsDatanode/dn-overview.html

In this change I added the volume state to the VolumeInfoMetrics so it will be exposed to the JMX of the datanodes and added a volume state column to the Volume Information's table on the Datanode WebUI. I modified that if a volume fail it will still have a VolumeInfoMetrics with the information added that it is failed.
https://issues.apache.org/jira/browse/HDDS-7086
Tested locally on a cluster that the volume state have been exposed to the datanode's JMX (`jmx?qry=Hadoop:service=HddsDatanode,name=VolumeInfoMetrics*`) and I can also see it on the WebUI.
```
{
"beans" : [ {
"name" : "Hadoop:service=HddsDatanode,name=VolumeInfoMetrics-/data/hdds",
"modelerType" : "VolumeInfoMetrics-/data/hdds",
"tag.Context" : "ozone",
"tag.VolumeState" : "NORMAL",
"tag.VolumeType" : "DATA_VOLUME", …
```

HDDS-7086. DataNode UI to show failed volumes too

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMDbCheckpointServlet.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMSnapshot.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/container/metrics/TestSCMContainerManagerMetrics.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestMultiRaftSetup.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestNode2PipelineMap.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestNodeFailure.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestSCMRestart.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestSCMSafeModeWithPipelineRules.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestAllocateContainer.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestCloseContainer.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestContainerSmallFile.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestGetCommittedBlockLengthAndPutKey.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestSCMMXBean.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestSCMNodeManagerMXBean.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestXceiverClientGrpc.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestXceiverClientManager.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestXceiverClientMetrics.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/node/TestDecommissionAndMaintenance.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/node/TestQueryNode.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/pipeline/TestPipelineManagerMXBean.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/pipeline/TestSCMPipelineBytesWrittenMetrics.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/pipeline/TestSCMPipelineMetrics.java

Migrate tests under following directories to JUnit 5.
* `hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/`
* `hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/`
https://issues.apache.org/jira/browse/HDDS-7174
https://github.com/kaijchen/ozone/actions/runs/2932207457

HDDS-7174. Migrate SCM integration tests to JUnit 5

---

pom.xml

Upgrade Jersey 2.33 to 2.34 due to CVE-2021-28168.
https://issues.apache.org/jira/browse/HDDS-7209
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3024130363

HDDS-7209. Bump Jersey2 to 2.34

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java
hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DatanodeCommands.java
hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DiskBalancerCommands.java
hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DiskBalancerReportSubcommand.java
hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DiskBalancerStartSubcommand.java
hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DiskBalancerStatusSubcommand.java
hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DiskBalancerStopSubcommand.java
hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DiskBalancerUpdateSubcommand.java
hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestDiskBalancerSubCommand.java

This ticket is to add CLI for DiskBalancer.
https://issues.apache.org/jira/browse/HDDS-7205
unit test.

HDDS-7205. DiskBalancer CLI

---

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/datanodes/datanodes.tsx

I fixed  changes to allow user to filter by HEALTHY or other State; same for Operational State and make only HostName as fixed and float the State and Operational State.
https://issues.apache.org/jira/browse/HDDS-7144
I tested manually  in Localhost 3000 and showed changes to Zita also.

HDDS-7144. Recon: Make only hostname fixed in Datanodes page.

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/RatisReplicationConfig.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestClosedWithMismatchedReplicasHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestOpenContainerHandler.java

The HealthCheck handlers OpenContainerHandler and ClosedWithMismatchedReplicasHandler currently don't have tests for Ratis. I've added tests that use `RatisReplicationConfig`. 
https://issues.apache.org/jira/browse/HDDS-7225

HDDS-7225. Add Ratis tests for HealthCheck handlers of Replication Manager

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerCheckRequest.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationQueue.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/ECReplicationCheckHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestECReplicationCheckHandler.java

We should consider if we should encapsulate the under and over replicated queues into a single object. We may want to have queues with different priorities or more queues going forward, so bring these together into a single object would make things more flexible in the future.
https://issues.apache.org/jira/browse/HDDS-7221
Existing tests cover the changes.

HDDS-7221. EC: ReplicationManager - Encapsulate the under and over rep queues into a queue object

---

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/signature/StringToSignProducer.java

The asterisk not encoded when building CanonicalRequest, which will cause the error when validating signatures.
https://issues.apache.org/jira/browse/HDDS-7185
Test using the following commands:
aws s3api --endpoint http://s3g:9878 list-objects --bucket bucket --prefix "dir1/*"

HDDS-7185. Encode asterisk for parsing signature

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/ClosingContainerHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestClosingContainerHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/package-info.java

If a container is CLOSING, some replicas can be OPEN or CLOSING. Close container commands need to be sent to the datanodes having these replicas. This Jira aims to create a new handler class for this scenario.
https://issues.apache.org/jira/browse/HDDS-7239

HDDS-7239. EC: Add a Handler for CLOSING containers in Replication Manager

---

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DiskBalancerCommands.java
hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DiskBalancerCommonOptions.java
hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DiskBalancerStartSubcommand.java
hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DiskBalancerStatusSubcommand.java
hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DiskBalancerStopSubcommand.java
hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DiskBalancerUpdateSubcommand.java

This ticket is to add a common option for DiskBalancer CLI.
https://issues.apache.org/jira/browse/HDDS-7234
original unit test.

HDDS-7234. Add a common option for DiskBalancer commands

---

hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

Previously the list all volume operation only went through the ACL check if the list all volume was disabled. Because of this the audit logging wasn't triggered. I removed the if condition checking the `ozone.om.volume.listall.allowed`'s value, so the ACL check gets triggered in every case (if the ACL is enabled). I also updated the `ozone.om.volume.listall.allowed`'s description in `ozone-default.xml`.
OzoneNativeAuthorizer wouldn't be affected by this change, because of [this](https://github.com/apache/ozone/pull/1395) change, the allowListAllVolumes is set [here](https://github.com/apache/ozone/blob/master/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java#L762) on the authorizer side.  
https://issues.apache.org/jira/browse/HDDS-7240
Run related …

HDDS-7240. List all volume operation should go through ACL check as well in order to trigger audit logging

---

hadoop-hdds/client/pom.xml
hadoop-hdds/common/pom.xml
hadoop-hdds/container-service/pom.xml
hadoop-hdds/framework/pom.xml
hadoop-hdds/hadoop-dependency-client/pom.xml
hadoop-hdds/hadoop-dependency-server/pom.xml
hadoop-hdds/test-utils/pom.xml
hadoop-hdds/tools/pom.xml
hadoop-ozone/client/pom.xml
hadoop-ozone/common/pom.xml
hadoop-ozone/csi/pom.xml
hadoop-ozone/dist/src/main/license/bin/LICENSE.txt
hadoop-ozone/dist/src/main/license/bin/NOTICE.txt
hadoop-ozone/dist/src/main/license/jar-report.txt
hadoop-ozone/integration-test/pom.xml
hadoop-ozone/ozonefs-common/pom.xml
hadoop-ozone/ozonefs-hadoop2/pom.xml
hadoop-ozone/ozonefs-hadoop3/pom.xml
hadoop-ozone/ozonefs-shaded/pom.xml
hadoop-ozone/ozonefs/pom.xml
hadoop-ozone/s3gateway/pom.xml
pom.xml

Log4j 1.x is EOL.  This PR proposes to replace it with Reload4j, which is a drop-in replacement with security updates.
https://issues.apache.org/jira/browse/HDDS-7251
Built locally.  Only Log4j 2 present in distribution:
```
$ ls -1 hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/share/ozone/lib/*log4j*
hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/share/ozone/lib/log4j-api-2.17.1.jar
hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/share/ozone/lib/log4j-core-2.17.1.jar
```
Verified no Log4j or Reload4j classes are present in shaded FS jars.
Full CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3103286435

HDDS-7251. Replace Log4j 1.x with Reload4j

---

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/db.json
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/routes.json
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/components/autoReloadPanel/autoReloadPanel.tsx
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/overview/overview.tsx

Display ToolTip to show OM last updated Delta and Full timestamp.
https://issues.apache.org/jira/browse/HDDS-7145
Manually Tested and reviewed by siyog and corrected review changes suggested by siyog.

HDDS-7145. Recon: Show last OM DB sync time on Overview page

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerMetrics.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancer.java

A metric is added for move container failed due to exception occurred in execution - numContainerMovesFailed. This does not include metrics for replication know failure.
https://issues.apache.org/jira/browse/HDDS-6492
Patch is tested with unit test, here multiple type of exception is thrown using mock of replication manager - checkIterationResultException

HDDS-6492. Add metric for failed container moves

---

pom.xml

Bump snakeyaml to latest, 1.32.
https://issues.apache.org/jira/browse/HDDS-7257
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3108064849

HDDS-7257. Bump snakeyaml to 1.32

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMXBean.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerRatisServer.java
hadoop-ozone/ozone-manager/src/main/resources/webapps/ozoneManager/om-overview.html
hadoop-ozone/ozone-manager/src/main/resources/webapps/ozoneManager/ozoneManager.js

Add Group-Id, Current-Node Role, Election Count, Leader Election Elapsed time & the Ratis-Ring information for OM UI.
https://issues.apache.org/jira/browse/HDDS-6863?filter=-1
Tested on docker OM ha env
For a single node cluster it will print STANDALONE

HDDS-6863. Add Group-Id & Ratis-Roles Information for OM UI.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerStateManagerImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/states/ContainerAttribute.java
pom.xml

ContainerStateManagerImpl - Changes done in this file for reducing global level read write locks and use resource level (ContainerId) lock wherever necessary to reduce thread lock contention and thread starvation.
By using container level locks in events handling of Container Reports by SCM and Recon will minimize the thread lock contention and starvation issue. Currently it.is global read write lock in ContainerStateManagerImpl class.
https://issues.apache.org/jira/browse/HDDS-7232
This patch was tested by running 3 node cluster and simulated the increased events for ICR and FCR processed by SCM and Recon. No impact in existing functionality. This container level lock design and implementation was proposed based on Recon and SCM server crash because of memory overflow due to event queue …

HDDS-7232. Introduce container-level lock while handling container report events by SCM and Recon

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/QuasiClosedContainerHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationTestUtil.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestQuasiClosedContainerHandler.java

Added a handler for Quasi Closed containers to Replication Manager. This handler takes care of only Ratis containers. Most of the core logic has been picked up from the legacy RM.
https://issues.apache.org/jira/browse/HDDS-7263

HDDS-7263. Add a handler for Quasi Closed containers to RM

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocol.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/protocolPB/StorageContainerLocationProtocolClientSideTranslatorPB.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ScmClient.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/OmTestManagers.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestScmClient.java

Introduce container location cache in ScmClient.
https://issues.apache.org/jira/browse/HDDS-7229
Also, this is done without DatanodeDetails normalization. Just did an experiment to confirm the cache size on top of the changes in this PR and the results are documented as per [HDDS-7249](https://issues.apache.org/jira/browse/HDDS-7249). In summary, 10K containers take 35mb heap and that number linearly grows with the number of containers.  
Standard CI with added unit test to cover new ScmClient interfaces: https://github.com/duongkame/ozone/actions/runs/3099408939

HDDS-7229. Introduce container location cache in ScmClient

---

hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestClosedWithMismatchedReplicasHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestClosingContainerHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestOpenContainerHandler.java

Some tests such as TestClosedWithMismatchedReplicasHandler#testClosedHealthyRatisContainerReturnsFalse specify the Replica Index field for Ratis container replicas. This field is only meaningful for EC and should be removed.
```
Set<ContainerReplica> containerReplicas =
ReplicationTestUtil.createReplicas(containerInfo.containerID(),
ContainerReplicaProto.State.CLOSED, 1, 2, 3);
```
https://issues.apache.org/jira/browse/HDDS-7268

HDDS-7268. EC: Fix tests for HealthCheck handlers of RM that use Replica Indexes for Ratis Containers

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteContainerCommandHandler.java

The thread count won't be growing for ThreadPoolExecutor in two cases of our current codebase.
The reason can be tracked here: https://stackoverflow.com/a/15485841/5365979
https://issues.apache.org/jira/browse/HDDS-7283
By checking the thread count in the thread dump.

HDDS-7283. Set coreSize equal to maxSize for threadPoolExecutor

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java

After [HDDS-7283](https://issues.apache.org/jira/browse/HDDS-7283), the mark for the delete process will be handled concurrently.
The current implementation has a concurrent issue which will lead to the following exception.
```
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 4
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:192)
at org.apache.hadoop.ozone.container.common.statemachine.commandhandler.DeleteBlocksCommandHandler.lambda$processCmd$0(DeleteBlocksCommandHandler.java:301)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.apache.hadoop.ozone.container.common.statemachine.commandhandler.DeleteBlocksCommandHandler.processCmd(DeleteBlocksCommandHandler.java:299)
at …
```

HDDS-7285. Fix concurrent issue in DeleteBlocksCommandHandler

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyRequest.java

This PR removes dead code from omKeyManagerImpl class. The most significant part of the removed code is helper methods of listStatusFSO(), which is unreachable and has been removed.
https://issues.apache.org/jira/browse/HDDS-7211
Existing unit and integration tests

HDDS-7211. remove dead code from org.apache.hadoop.ozone.omKeyManagerImpl

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestDataUtil.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/FileStatusAdapter.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientUtils.java
hadoop-ozone/ozonefs-hadoop2/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java

Hadoop FileStatus accepts flags for erasure coding and encryption on creation. Impala relies on FileStatus.isErasureCoded. Ozone doesn't use this signature, so isErasureCoded and isEncrypted always return false.
https://issues.apache.org/jira/browse/HDDS-7208
Changing Getter Setters

HDDS-7208. Erasure coding and encryption are not flagged on FileStatus

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingService.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java

If the block info is null, then blocksDeleted is not increased and the numPendingDeletionBlocks then will not be decreased.
During ```chooseContainerForBlockDeletion```, all containers with such inexistent blocks will still be chosen but no actual deletion happens, and normal block deletion will be blocked.
TODO:
Besides this, if deletion of certain block retries exceeds a certain number of times, the service should skip deleting it, otherwise invalid numPendingDeletionBlocks could accumulate beyond the limit and the following deletion will also stop. We should add this as a protection mechianism.
https://issues.apache.org/jira/browse/HDDS-7259
Manual test

HDDS-7259. Fix uncounted blocksDeleted in BlockDeletingService

---

pom.xml

Bump Jackson2 to 2.13.4 for https://github.com/FasterXML/jackson-databind/commit/063183589218fec19a9293ed2f17ec53ea80ba88.
https://issues.apache.org/jira/browse/HDDS-7293
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3200004358

HDDS-7293. Bump jackson2 to 2.13.4

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManagerImpl.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerManagerImpl.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerStateManagerIntegration.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestContainerCommandsEC.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconAsPassiveScm.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconTasks.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconContainerManager.java

Clean up of org.apache.hadoop.hdds.scm.container.ContainerManager and its descendants. Removed various code smells such as 
- using deprecated methods
- missing javadocs
- using methods annotated VisibleForTesting in production code
https://issues.apache.org/jira/browse/HDDS-7286
Unit tests

HDDS-7286. Clean up ContainerManager

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingService.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java

After the patch of [HDDS-7259](https://issues.apache.org/jira/browse/HDDS-7259),  the number of empty containers is accumulating and they are not deleted.  The reason is due to the incorrect block count. 
The block count is increased each time of puttingBlock, so it should not decrease the missing block number.
While the pending deletion block number is increased by counting the blocks in the TXN(missing blocks included), so missing block number should be reduced.
https://issues.apache.org/jira/browse/HDDS-7302
UT . See supplement of UT

HDDS-7302. Fix inaccurate container block count caused by missing block

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogImpl.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestDeletedBlockLog.java

This ticket is to fix two related errors on transactionToRetryCountMap.
* SCM sends a request to dn, the retry count of the message is currently read from DB, but the DB value won't be changed until exceeding the max retry times, so it will always be 0 before exceeding the max value.
* Reset retry count didn't reset the value of transactionToRetryCountMap.
https://issues.apache.org/jira/browse/HDDS-7287
unit test.

HDDS-7287. Send deleteBlocksRequest with correct retry count

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/TrashOzoneFileSystem.java

Fix the following exception being thrown during FileSystem.close()
Exception in thread "Trash Emptier" java.lang.UnsupportedOperationException: fs.getUri() not implemented in TrashOzoneFileSystem
https://issues.apache.org/jira/browse/HDDS-6664
Ran relevant checks scripts locally and build-branch was successful with  this change. https://github.com/pratapchandu/ozone/actions/runs/3172304615

HDDS-6664. Implements getUri in TrashOzoneFileSystem

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockReconstructedStripeInputStream.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/ozone/client/io/TestECBlockReconstructedStripeInputStream.java

he EC client establishes an ElasticByteBufferPool, so that byte buffers can be assigned / freed and reused without allocating and freeing memory over and over. The buffer returned by the elastic buffer can be larger than the size requested, and if that is the case we can get an error on EC decode, such as:
```
java.lang.IllegalArgumentException: Invalid buffer [3], not of length 1048576
at org.apache.ozone.erasurecode.rawcoder.ByteBufferDecodingState.checkInputBuffers(ByteBufferDecodingState.java:106)
at org.apache.ozone.erasurecode.rawcoder.ByteBufferDecodingState.<init>(ByteBufferDecodingState.java:44)
at org.apache.ozone.erasurecode.rawcoder.RawErasureDecoder.decode(RawErasureDecoder.java:84)
at org.apache.hadoop.ozone.client.io.ECBlockReconstructedStripeInputStream.decodeStripe(ECBlock …
```

HDDS-7304. EC: EC Decode can fail when byteBuffer from elastic pool is larger than chunksize

---

hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServerConfigKeys.java

Enable Recon SCM DB bootstrap by default. `ozone.recon.scm.snapshot.enabled` was set to`false`, until other [tasks](https://issues.apache.org/jira/browse/HDDS-2852) were completed. 
https://issues.apache.org/jira/browse/HDDS-7236
Using existing Unit and Integration tests for Recon which was added as part of the previous changes.

HDDS-7236. Enable Recon SCM DB bootstrap by default.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java

scmMetaStore to be close at last in sequence, as other service like metric may be using this to access tables.
https://issues.apache.org/jira/browse/HDDS-7315
Running Unit test and integration test for the impact.

HDDS-7315. SCM order of close of dbstore and other services

---

hadoop-hdds/docs/content/feature/OM-HA.md
hadoop-hdds/docs/content/feature/OM-HA.zh.md

Removed serviceIds 'cluster2' from ozone.om.service.ids configuration since it's not being used and creating confusion/doubts.
ozone.om.service.ids : cluster1,cluster2
https://issues.apache.org/jira/browse/HDDS-7308

HDDS-7308. Updated Doc for OM HA Setup

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java

Fixing bug on existing healthy node selection in ECUnderReplicationHandler.  
https://issues.apache.org/jira/browse/HDDS-7270
Fixing Unit Test cases.

HDDS-7270. Fix bug in checking healthy replica placement policy check in EC underReplication handler

---

hadoop-ozone/dist/src/main/license/bin/LICENSE.txt
pom.xml

hsqldb and jettison seem to be leftover dependencies from Hadoop and can be removed.
https://issues.apache.org/jira/browse/HDDS-7322
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3241229595

HDDS-7322. Remove unused dependencies hsqldb and jettison

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerStateManagerImpl.java

Fair locking was suggested to be always as "true" in HDDS-7232 under comments and being asked to handle as separate jira item.
https://issues.apache.org/jira/browse/HDDS-7269
Tested locally in docker cluster with manual test.

HDDS-7269. Remove fair lock configuration for container state management flows.

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockReconstructedStripeInputStream.java

In ECBlockReconstructedStripeInputStream, when an exception occurs reading a block, the code calls the `init()` method to setup the missing indexes and buffers.
If an InsufficientLocations exception is thrown part way through that method, the class ends up partly re-initialized. If something then ignores / handles the InsufficientLocations and tries to call read again, it can cause strange results. In one case, we get an illegalArgumentException, which I think is related to the above:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
at org.apache.hadoop.ozone.client.io.ECBlockReconstructedStripeInputStream.assignBuffers(ECBlockReconstructedStripeInputStream.java:289)
at org.apache.hadoop.ozone.client.io.ECBlockReconstructedStripeInputStream.read(ECBlockReconstructedStripeInputStr …
```

HDDS-7303. EC: ECBlockReconstructedStripeInputStream should set initialized false on re-init

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/util/CacheMetrics.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMPerformanceMetrics.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmCacheMetrics.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ScmClient.java

Add container location cache metrics.
https://issues.apache.org/jira/browse/HDDS-7261
Standard CI.
Metrics are verified locally in Prometheus.

HDDS-7261. Add container location cache metrics.

---

dev-support/ci/lib/_initialization.sh

`set-output` has been deprecated by Github, to be replaced by redirection to `$GITHUB_OUTPUT` file.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
https://issues.apache.org/jira/browse/HDDS-7337
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3254979226

HDDS-7337. Replace set-output in Github Actions workflow

---

hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java

I removed logging exceptions in ozone client getFileStatus() methods. This issue was introduced in https://github.com/apache/ozone/pull/3687
https://issues.apache.org/jira/browse/HDDS-7343
manual test: I built Ozone from a branch, deployed Hadoop cluster, deployed Ozone in this Hadoop cluster, and checked those exceptions were gone.

HDDS-7343. Do not log exception on file not found in getFileStatus()

---

pom.xml

Bump `jackson2-databind` to 2.13.4.2 due to CVE-2022-42003.
https://issues.apache.org/jira/browse/HDDS-7340
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3263801866

HDDS-7340. Bump jackson-databind to 2.13.4.2

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/DeleteContainerCommand.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/EmptyContainerHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationTestUtil.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestEmptyContainerHandler.java

Created a handler for empty containers. This mostly contains the same logic as the legacy RM for checking if a container is closed and empty, deleting its replicas, and moving it to DELETING state. Also introduced a new method in RM for sending a delete command to a DN and adding it to `ContainerReplicaPendingOps`. 
We should not add this handler to the chain of handlers in RM until the DELETING container handler has been added. This is because the DELETING container handler will take care of resending delete commands to replicas of a DELETING container.
https://issues.apache.org/jira/browse/HDDS-6893
`TestEmptyContainerHandler`

HDDS-6893. EC: ReplicationManager - move the empty container handling into RM from Legacy

---

hadoop-hdds/docs/content/feature/SCM-HA.md

Currently SCM HA is supported only for fresh installations. SCM HA must be enabled when starting the Ozone service in the beginning.  After a SCM is started in non-HA mode, it cannot be easily changed to HA mode. We should document this clearly.
https://issues.apache.org/jira/browse/HDDS-7254
NA

HDDS-7254. Document that moving SCM from non-HA to HA is currently unsupported.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMStateMachine.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestValidateBCSIDOnRestart.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestSCMInstallSnapshotWithHA.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerStateMachine.java
pom.xml

We should update  Ratis to 2.4.0  to fix [gRPC memleak](https://github.com/grpc/grpc-java/pull/9415). 
After we update ratis to 2.4.0, we will  start release ozone 1.3.0.
https://issues.apache.org/jira/browse/HDDS-7149
UT had been update.

HDDS-7149. Update ratis version to 2.4.0 and thirdparty version to 1.0.2.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerImpl.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java

A datanode is stopped and before the stale node handler is triggered, SCM is restarted. When SCM restarts its loads all the only pipelines and nodes from RocksDB, and then all the nodes will register again.
In the case of EC pipelines, there is nothing to trigger the close of a pipeline (and the containers on it) except:
1. The Container getting full and the DN triggering the close
2. The stale / dead node handlers noticing a node on it has gone dead.
In the case above, the EC pipeline will sit forever in an Open state, but any attempt to write to it will likely result in errors on the client due to one of the nodes not being available. These errors still will not trigger it to close.
A solution to this problem, is to add logic to the pipeline scrubber to close any pipelines that have …

HDDS-7341. EC: Close pipelines with unregistered nodes

---

hadoop-hdds/framework/pom.xml
hadoop-hdds/hadoop-dependency-server/pom.xml
hadoop-hdds/server-scm/pom.xml
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerImpl.java
hadoop-ozone/dist/src/main/license/jar-report.txt

* Replace one import from Hadoop's shaded Guava.
* Add direct dependencies for various Apache Commons libs instead of relying on getting them transitively via Hadoop.
Different Hadoop versions may not depend on all these libraries (or shade different Guava version), so using transitive dependency explicitly (via import) risks breaking with some version of Hadoop.
https://issues.apache.org/jira/browse/HDDS-7305
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3228775529

HDDS-7305. Fix Hadoop imports

---

pom.xml

Simplify dependency management for Jackson2 artifacts by importing `com.fasterxml.jackson:jackson-bom`.
https://issues.apache.org/jira/browse/HDDS-7351
Verified jackson version in dependency tree, e.g.
```
[INFO] org.apache.ozone:ozone-client:jar:1.3.0-SNAPSHOT
[INFO] \- org.apache.ozone:hdds-common:test-jar:tests:1.3.0-SNAPSHOT:test
[INFO]    +- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.4:compile
[INFO]    \- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.4:compile
[INFO]       +- com.fasterxml.jackson.core:jackson-core:jar:2.13.4:compile
[INFO]       \- com.fasterxml.jackson.core:jackson-databind:jar:2.13.4.2:compile
```
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3275722116

HDDS-7351. Use jackson-bom to ensure consistent Jackson version

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingService.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java

If using SchemaV3, the blocks are deleted on disk but the blockData is not deleted accordingly due to the misuse of the key in deleteViaTransactionStore. 
Keep using the unified key format as V2 and V3 both delete blocks via TXN.
https://issues.apache.org/jira/browse/HDDS-7354
UT

HDDS-7354. SchemaV3 blockData not deleted in table

---

hadoop-hdds/docs/content/feature/SCM-HA.zh.md

Update SCM-HA.zh.md, mainly on SCM-HA security.
Followup #3846.
https://issues.apache.org/jira/browse/HDDS-7356
No need.

HDDS-7356. Update SCM-HA.zh.md to match the English version

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java

when converting a unsecure cluster to a secure one, we need to reinit the primordial SCM to generate the root ca and a sub ca to itself.  then , we need to bootstrap the other two scm to get a signed cert and sub ca from primordial SCM.
current code has a bug in `initializeSecurityIfNeeded` which will lead the bootstrapped scm to get a self signed cert from itself, not the root signed cert from primordial SCM.
https://issues.apache.org/jira/browse/HDDS-7355
manually test in my inner cluster

HDDS-7355. non-primordial scm fail to get signed cert from primordial SCM when converting an unsecure cluster to secure

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientMetrics.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockInputStreamProxy.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinator.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionMetrics.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ec/reconstruction/TestECReconstructionSupervisor.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestContainerCommandsEC.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmMetrics.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMetrics.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequest.java

To add EC metrics for OM, DN, and Client side.
https://issues.apache.org/jira/browse/HDDS-6210
Unit tests and Integration tests.

HDDS-6210. EC: Add EC metrics

---

hadoop-hdds/docs/content/feature/Nonrolling-Upgrade.md

Found the following typos in Nonrolling-Upgrade.md:
**ozone --daemon scm start
ozone --daemon datanode start
ozone --daemon om start --upgrade**
https://issues.apache.org/jira/browse/HDDS-7369

HDDS-7369. Fix wrong order of command arguments in Nonrolling-Upgrade.md

---

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/index.less
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/diskUsage/diskUsage.less
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/diskUsage/diskUsage.tsx

1) Make the DU page's texts the same font and color as on the other pages in Recon.
2) The chart description (which color stands for which volume/bucket/key) could be a bit bigger
3) If we click into the chart parts we go into that bucket and change the pie chart accordingly. If we click on the last key there is no pie chart showing up, we could change this to show a pie chart with 100% of the key.
4) There is a button on the right side that says Show Metadata for Current Path. If we click on it there is a page popping up on the right side with information about the current path. We could fix this page on the right side as we have plenty of space to do that. We can remove the button in this case and we don't need to make the left side of the page (the chart) grey. …

HDDS-7141. Recon: Improve Disk Usage Page

---

README.md

Improve Ozone Security feature documentation. Ozone integrates with Kerberos for authentication and supports native and Ranger Acls.
https://issues.apache.org/jira/browse/HDDS-7403

HDDS-7403. README Security Improvement

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/tenant/OMTenantCreateRequest.java

For tenant create request, if the volume already exists it creates empty default Ranger policies as the check happens in validateAndUpdateCache. Even though Ranger Background sync thread deletes these policies later, it would be better to avoid creating these policies.
https://issues.apache.org/jira/browse/HDDS-7368
Existing Unit Tests.

HDDS-7368. [Multi-Tenant] Add Volume Existence check in preExecute for OMTenantCreateRequest.

---

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestSchemaOneBackwardsCompatibility.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/metadata/SCMMetadataStore.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBTable.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/Table.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogStateManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogStateManagerImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/metadata/SCMMetadataStoreImpl.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestObjectStoreWithLegacyFS.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAKeyDeletion.java
hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/ReconContainerMetadataManagerImpl.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestTableCountTask.java

Added check for close of DB before db access, And a counter if any operation in progress
This counter is used for close to make sure operation is closed, and max wait for 5 sec for force close as strategy.
https://issues.apache.org/jira/browse/HDDS-7284
A test is performed to check if IO Exception after close is comming, as earlier it was causing Java crash,

HDDS-7284. JVM crash for rocksdb for read/write after close

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeConfiguration.java

https://issues.apache.org/jira/browse/HDDS-7182

HDDS-7182. Add property to control RocksDB max open files

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java

Fix exception when '/' in key name
https://issues.apache.org/jira/browse/HDDS-7253
How to reproduce the bug
- First put a key that containing '/'
```bash
[root@Linux /root/ozone]% bin/ozone sh key put s3v/testbucket/dir1/dir2/key1 ~/testfile
[root@Linux /root/ozone]% bin/ozone sh key ls s3v/testbucket/ | grep name
"name" : "dir1/dir2/key1"
```
- Execute command
`ls` command for keys containing '/'
before this commit
```bash
[root@Linux /root/ozone]% bin/ozone fs -ls ofs://localhost/s3v/testbucket/
Found 1 items
drwxrwxrwx   - root root          0 2022-09-19 14:11 ofs://localhost/s3v/testbucket/dir1
[root@Linux /root/ozone]% bin/ozone fs -ls ofs://localhost/s3v/testbucket/dir1
ls: `ofs://localhost/s3v/testbucket/dir1': No such file or directory
```
after this commit
```bash
[root@Linux …
```

HDDS-7253. Fix exception when '/' in key name

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/VolumeManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/VolumeManagerImpl.java

I removed unused constructor arguments and cleanup javadoc comments (mostly removed duplicated ones)
https://issues.apache.org/jira/browse/HDDS-7381
unit tests

HDDS-7381. Cleanup of VolumeManagerImpl

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyCommitResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCommitRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestKeyDeletingService.java

We found that the blocks the client committed may not be equal to the allocated(when EC stripe fails), and the uncommitted blocks would remain forever as orphan blocks as no key maps to them anymore. 
Here I use a tricky solution that considers these blocks as repeated/ overwritten key blocks, and thus they would be deleted in the existing deletion path.
------ 
https://docs.google.com/document/d/1Oi1zPKdmvA7DFwIcUWz6zw_p-pY3D1L76gyV37jQT94/edit#
The prototype of the design.
https://issues.apache.org/jira/browse/HDDS-7258
UT and Manual test in the test environment.

HDDS-7258. Cleanup the allocated but uncommitted blocks

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/ClosingContainerHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestClosingContainerHandler.java

Force close non-RATIS containers in ReplicationManager.
https://github.com/apache/ozone/blob/965d31cde91ba7c9973beb9e082f7c0e492e18a8/hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CloseContainerCommandHandler.java#L106-L113
https://issues.apache.org/jira/browse/HDDS-7396
TestClosingContainerHandler#testOpenOrClosingReplicasAreClosed

HDDS-7396. Force close non-RATIS containers in ReplicationManager

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/MultipartCryptoKeyInputStream.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/OzoneCryptoInputStream.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java

Refactor MultipartCryptoKeyInputStream to extract encryption-related boundary calculation to a more relevant OzoneCryptoInputStream class
https://issues.apache.org/jira/browse/HDDS-7342
No code added or removed, just moved from one class to another. Tested with existing unit tests

HDDS-7342. Move encryption-related code to OzoneCryptoInputStream

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/RatisDropwizardExports.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

1. Additional RatisDropwizardExports old by DNs after its closed
2. register of RatisDropwizardExports even its already present with name in ratisMetricsMap
https://issues.apache.org/jira/browse/HDDS-7349
Tested with flaky and taking heapdump for objects of RatisDropwizardExports referred by DNs ratisMetricsMap.

HDDS-7349. Flaky integration test have memory leak for RatisDropwizardExports

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/WritableECContainerProvider.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestWritableECContainerProvider.java

In [HDDS-6452](https://issues.apache.org/jira/browse/HDDS-6452), we have discussed the unit of EC block allocation.
In each container replica, the minimum allocation unit should be scmBlockSize
instead of scmBlockSize / dataNum.
For each key, the minimum allocation unit should be scmBlockSize * dataNum,
instead of scmBlockSize.
So the allocation logic in TestWritableECContainerProvider should be updated.
https://issues.apache.org/jira/browse/HDDS-7407
TestWritableECContainerProvider#testNewContainerAllocatedAndPipelinesClosedIfNoSpaceInExisting is updated.

HDDS-7407. EC: Block allocation should not be stripped across the EC group

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/CommandQueueReportHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeInfo.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeHeartbeatDispatcher.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/SimpleMockNodeManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestCommandQueueReportHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/container/testutils/ReplicationNodeManagerMock.java

In [HDDS-6567](https://issues.apache.org/jira/browse/HDDS-6567), we stored the datanode queued command counts into DatanodeInfo on each heartbeat. However, we did not consider the commands that were queued to goto the Datanode on that heartbeat. The real count, is the count queued on the DNs, plus the commands queued in SCM we are about to send to the DN over the heartbeat being processed.
This Jira adds the "commands ready to send" count to the stored counts to give a better reflection on the current queued count on the DN.
https://issues.apache.org/jira/browse/HDDS-7370
Adapted existing tests

HDDS-7370. Add pending commands in SCM to Datanode command count

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestDirectoryDeletingServiceWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/DirectoryDeletingService.java

Currently, the deleting speed of paths in the FSO bucket is too slow.
Every time the DirectoryDeletingService executes(every 1m by default),  it chooses only one path from DeletedDirectroyTable and tries adding its sub-files and sub-dirs into the PurgeDirectories Request. The real deletion happens in OMKeyDeleteResponseWithFSO, which moved all sub-dirs into DeletedDirectroyTable.  Then these sub-dirs will be chosen by the future execution of DirectoryDeletingService. 
In the real production environment, such deletion speed is not applicable. There could be lots of dirs deleted without sub-dirs or sub-files. The dir deletion speed would lag behind the dir creation speed.
In this PR,  I propose to optimize the logic of the DirectoryDeletingService, we could consume all the quota …

HDDS-7328. Improve Deletion of FSO Paths

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/KeyDeletingService.java

1. Remove unused the exception
2. Improve debug log in KeyDeletingService
3. Fix the copyright format
4. Expand the parameter to erase the Raw use warning
https://issues.apache.org/jira/browse/HDDS-7406
/

HDDS-7406. Remove unused the exception & improve debug log in KeyDeletingService

---

hadoop-hdds/framework/pom.xml
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedObject.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedRocksObjectUtils.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStoreIterator.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/ReconContainerMetadataManagerImpl.java

Add logging to identify location/trace of unclosed RocksObjects .
https://issues.apache.org/jira/browse/HDDS-7316
Tested on docker with debug logs enabled , identified an instance and fixed in this PR
```
[34mrecon_1     |[0m 2022-10-12 13:56:51 WARN  ManagedRocksObjectUtils:49 - RocksIterator is not closed properly
[34mrecon_1     |[0m 2022-10-12 13:56:51 DEBUG ManagedRocksObjectUtils:52 - StackTrace for unclosed instance: org.apache.hadoop.hdds.utils.db.managed.ManagedObject.<init>(ManagedObject.java:34)
[34mrecon_1     |[0m org.apache.hadoop.hdds.utils.db.managed.ManagedRocksIterator.<init>(ManagedRocksIterator.java:28)
[34mrecon_1     |[0m org.apache.hadoop.hdds.utils.db.managed.ManagedRocksIterator.managed(ManagedRocksIterator.java:32)
[34mrecon_1     |[0m …
```

HDDS-7316. Print stacktrace to identify the location of RocksObject leaks.

---

hadoop-ozone/dist/src/main/license/jar-report.txt
hadoop-ozone/pom.xml

Bump Spring framework from 5.2.20 to 5.3.23.
https://issues.apache.org/jira/browse/HDDS-7420
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3335701458

HDDS-7420. Bump Spring framework from 5.2.20 to 5.3.23

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestDatanodeStateMachine.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/upgrade/TestDatanodeUpgradeToSchemaV3.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/container/common/TestEndPoint.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneCluster.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMiniOzoneCluster.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/server/TestSecureContainerServer.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/ClientProtocolStub.java

Since Ozone DataStream is a new feature, we disable it by default.
Also, we propose to rename the following conf properties
- ozone.fs.datastream.enable
- dfs.container.ratis.datastream.enable
to
- ozone.fs.datastream.enabled
- dfs.container.ratis.datastream.enabled
in order to be consistent with the existing conf properties.
https://issues.apache.org/jira/browse/HDDS-7431
By existing unit tests.

HDDS-7431. [Ozone-Streaming] Disable data steam by default.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/CommandQueue.java

In [HDDS-7402](https://issues.apache.org/jira/browse/HDDS-7402) it was suggested to move the CommandSummary tracking into the Commands inner class. This Jira is to make that small change.
https://issues.apache.org/jira/browse/HDDS-7432
Existing test added in [HDDS-7402](https://issues.apache.org/jira/browse/HDDS-7402) covers this.

HDDS-7432. Move command summary into Commands object in CommandQueue

---

hadoop-hdds/container-service/pom.xml
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeQueueMetrics.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/StateContext.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/metrics/TestDatanodeQueueMetrics.java

This ticket is to add a general metrics class for the following queues in Datanodes
* StateContextCommandQueue
* CommandDispatcherQueue
* IncrementalReportQueue
* ContainerActionQueue
* PipelineActionQueue
https://issues.apache.org/jira/browse/HDDS-7361
unit test.

HDDS-7361. Add general metrics for queues in Datanode

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/DeletingContainerHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/EmptyContainerHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestDeletingContainerHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestEmptyContainerHandler.java

implement deleting container handler
https://issues.apache.org/jira/browse/HDDS-7384
unit test

HDDS-7384. EC: ReplicationManager - implement deleting container handler

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockInputStream.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ChunkInputStream.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestBlockInputStream.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneManagerVersion.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MockOmTransport.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OzoneManagerProtocol.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestKeyInputStream.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmContainerLocationCache.java

This is a part of the container location cache implementation(HDDS-7223), specified in [Client Interaction](https://docs.google.com/document/d/1-hVdA7mRBFiFOqr0J0Pg6-Ie5SOZaT7Z/edit#heading=h.4d34og8) design.
This PR includes the changes to integrate the GetKeyInfo API to key read flows, keeping client code backward compatible with previous OM versions.
https://issues.apache.org/jira/browse/HDDS-7231
**Before:**
1. Client calls lookupKey.
2. Client calls getBlock and readChunk. They when there's an exception in either calls:
- If it's a security problems, fail without retry.
- If StorageContainerException (threw when Datanode returns any stattus code than), recall lookupKey to get latest block location info.
- If it a conectivity issues (all datanodes are not reachable), or any …

HDDS-7231. Integrate the GetKeyInfo API to key read flows

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java

Added unit-testcases for Ozone snapshot feature HDDS-6517
[HDDS-7427](https://issues.apache.org/jira/browse/HDDS-7427)
Added testcases in file - hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
`mvn -Dtest=TestOmSnapshot test`
[INFO] Running org.apache.hadoop.ozone.om.TestOmSnapshot
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 159.773 s - in org.apache.hadoop.ozone.om.TestOmSnapshot
[INFO] 
[INFO] 
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0
[INFO]

HDDS-7427. [Snapshot] Add unit-testcases for Ozone snapshot feature.

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientWithRatis.java

```java
//OzoneBucket
public OzoneDataStreamOutput createStreamKey(String key, long size)
throws IOException {
...
}
```
We propose to add the above method to `OzoneBucket` since there is a similar `createKey` in `OzoneBucket`.
https://issues.apache.org/jira/browse/HDDS-7438
Added a new unit test.

HDDS-7438. Add a createStreamKey method to OzoneBucket.

---

hadoop-ozone/dist/src/shell/ozone/ozone
hadoop-ozone/dist/src/shell/ozone/ozone-functions.sh

To make changes to the Ozone CLI for validating if each of the jars as listed in the Ozone classpath files are present in the indicated location or not. 
To introduce a `--validate` flag in the Ozone CLI:
```
The --validate flag validates if all jars as indicated in the corresponding OZONE_RUN_ARTIFACT_NAME classpath file are present
Usage I: ozone --validate classpath <ARTIFACTNAME>
Usage II: ozone --validate [OPTIONS] --daemon start|status|stop csi|datanode|om|recon|s3g|scm
OPTIONS is none or any of:
continue        command execution shall continue even if validation fails
```
https://issues.apache.org/jira/browse/HDDS-7363
Follow-up Task (to introduce Robot acceptance tests): https://issues.apache.org/jira/browse/HDDS-7373

HDDS-7363. Changes to Ozone CLI to validate if the jars in classpath files are present on an install

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/metadata/SCMMetadataStoreMetrics.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/metadata/TestSCMMetadataStoreImpl.java

In SCMMetadataStoreMetrics, we introduced a "Tag" which has all the estimated sizes as a String for a better summary.
But it's causing the Prometheus metrics page adding duplicated metrics, seems we can only have identical values in "Tag" of metrics under this constriant.
https://issues.apache.org/jira/browse/HDDS-7429
unit test.

HDDS-7429. Remove Tag from SCMMetadataStoreMetrics

---

hadoop-ozone/dev-support/intellij/log4j.properties
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/DirectoryDeletingService.java

Found this Iterator leak when working on another problem. TableIterator is not closed, introduce from [this change](https://github.com/apache/ozone/pull/3844/files#diff-7ec30412dac9f4304cc72760eec9efe605e901ec3a7d379551da7c6ab67ea7eaR148).
https://issues.apache.org/jira/browse/HDDS-7447
Standard CI.
Manual verify the no leaks is introduced from running DirectoryDeletingService.

HDDS-7447. Leak of TableIterator in DirectoryDeletingService.

---

hadoop-ozone/dist/pom.xml
hadoop-ozone/dist/src/main/license/jar-report.txt
hadoop-ozone/ozonefs-hadoop-client/pom.xml
hadoop-ozone/ozonefs-hadoop3-client/pom.xml
hadoop-ozone/pom.xml

Hadoop distributes two versions of their hdfs client:
hadoop-client-api-3.3.1.jar and hadoop-common-3.3.4.jar
The first uses shaded protobufs, eg: org.apache.hadoop.shaded.com.google.protobuf.Message
The second unshaded protobufs, eg: com.google.protobuf.Message
Currently, Ozone only supports unshaded protobufs, (with ozone-filesystem-hadoop3-1.3.0-SNAPSHOT.jar)
But projects like spark use shaded protobufs, (through hadoop-client-api-3.3.1.jar).
This PR adds the ozone-filesystem-hadoop3-client-1.3.0-SNAPSHOT.jar which is identical to the ozone-filesystem-hadoop3-1.3.0-SNAPSHOT.jar, except that it uses the shaded protobufs, (so as to work with spark and other systems distributed with the hadoop-client jars.
https://issues.apache.org/jira/browse/HDDS-6926
I installed spark and confirmed …

HDDS-6926. Add support for shaded protobufs used by hadoop-client/spark.

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/TableCacheMetrics.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/Table.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/cache/CacheStats.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/cache/CacheStatsRecorder.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/cache/FullTableCache.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/cache/PartialTableCache.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/cache/TableCache.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/cache/TestTableCache.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java

Create table cache metrics. Initially, only the cache size is included.
https://issues.apache.org/jira/browse/HDDS-7025
Standard CI.
Also local test to ensure expected metrics are emitted to Prometheus.

HDDS-7025. Add table cache metrics in OM.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestLDBCli.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/DBScanner.java

The current RocksDB scanner command allows only a simple length parameter to limit the number of records to scan in a specific col family. In the case of a huge table like keyTable or containers, while we are looking for a specific entry, the search is needlessly large and explorative (since we do not know the 'index' of the key)
A startKey param would be useful.
ozone debug ldb --db=<> scan --column_family=<> --length=<> --startKey=<>
https://issues.apache.org/jira/browse/HDDS-7423

HDDS-7423. DB Scanner should allow iteration from specific key

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/TrashPolicyOzone.java

When moving a file/dir to trash, the destination path is different for ofs and o3fs.  The change here is to make it same for both.
```
o3fs -> /<vol>/<buck>/.Trash/<user>/Current/..<dir if any>..
ofs -> /<vol>/<buck>/.Trash/<user>/Current/<vol>/<buck>/..<dir if any>..
```
Omitting volume and bucket for ofs key since its redundant info as for a particular ozone key already volume and bucket is known.
Most of the code for moveToTrash is duplicated from the  [hadoop client code](https://github.com/apache/hadoop/blob/616cea2e8068e990d24057d2b0d6090f35e21371/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/TrashPolicyDefault.java#L123 ) and only the below if condition is a modification to the method.  
If this part is not duplicated and the path is trimmed of volume and …

HDDS-5866. Discrepancy in Trash directory in ofs vs o3fs.

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/ObjectStore.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneKey.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/ClientProtocolStub.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestPermissionCheck.java

HDDS-7230 implements the GetKeyInfo with the ability to assume S3 volume context by OM. That releases S3G from having to call `getS3VolumeContext` prior to calling `lookupKey`, as it does today.
Changes include:
- S3G Get Key API to call GetKeyInfo via RpcClient with `assumeS3Context=true`, and without a proper `volumeName`. S3G doesn't need to call GetS3VolumeContext prior to GetKeyInfo. 
- RpcClient once it sees an S3 context in the GetKeyInfo response, takes the user principal, and sets it to the [S3LocalAuthContext](https://github.com/apache/ozone/blob/master/hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java#L923-L923).
That code change reduces once roundtrip between S3G and OM for every S3 Object Get/Head request. …

HDDS-7324. S3G: Avoid calling getS3VolumeContext by using GetKeyInfo

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OzoneManagerProtocol.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java
hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java

The target of this task is to deprecate the `LookupFile` interface and use `GetKeyInfo` for the OFS use case.
The gap between OFS and object storage use cases (like S3) is that due to a file system nature, OFS has to answer the file read requests from its client. A file read input is a file path and OFS needs to be able to decide if the given path is a valid file. To be specific, if the given path is not a file (but a directory), OFS should return an error. Reading empty files is a valid use case.
```
// throws IOException if the given path is not a file.
FileSystem.open(path)
```
The `lookupKey` API returns the same content for an empty file and directory. 
Today, this is solved in Ozone by the separated `lookupFile` API, detecting if the given key is a directory and throwing an error on …

HDDS-7419. Integrate the GetKeyInfo API to OFS

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/utils/db/DatanodeDBProfile.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TableConfig.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedColumnFamilyOptions.java

This PR brings back the mechanism to share LRU cache between RocksDB in datanodes
https://issues.apache.org/jira/browse/HDDS-7362
Standard CI.

HDDS-7362. Bring back the mechanism to share LRU cache between RocksDB in datanodes

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelinePlacementPolicy.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestRatisPipelineCreateAndDestroy.java

Fix and enable test cases in TestRatisPipelineCreateAndDestroy. Throw exception when available healthy nodes are not sufficient 
https://issues.apache.org/jira/browse/HDDS-3419
All tests in TestRatisPipelineCreateAndDestroy were running successfully with the fix on developers machine. 
build-branch was successful with the changes https://github.com/pratapchandu/ozone/actions/runs/3264534699
https://github.com/pratapchandu/ozone/actions/runs/3384457500

HDDS-3419. Throw exception with correct code when available data nodes are not sufficient

---

pom.xml

Upgrade snakeyaml to 1.33, which fixes an [issue](https://bitbucket.org/snakeyaml/snakeyaml/issues/553/loaderoptionssetcodepointlimit-not-honored) with `loadAll()`.
No call to `loadAll()` in Ozone currently (hence not needed for 1.3), but let's upgrade to avoid issues with potential future uses.
https://issues.apache.org/jira/browse/HDDS-7460
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3392744185

HDDS-7460. Bump snakeyaml from 1.32 to 1.33

---

pom.xml

RocksDB 7.7.3 includes a important bug fix.
https://github.com/facebook/rocksdb/issues/9423
The minimum version includes this fix is 7.5.3, but CI is OK with RocksDB 7.7.3.
I wish this fix can be included in the 1.3.0 release.
https://issues.apache.org/jira/browse/HDDS-7448
https://github.com/kaijchen/ozone/actions/runs/3369331676

HDDS-7448. Upgrade RocksDB to 7.7.3

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/TestECContainerRecovery.java

Changing **hdds.scm.replication.thread.interval** to run Replication Manager more frequently which defaults to 300s should fix intermittency of the tests under class.
https://issues.apache.org/jira/browse/HDDS-7326
UT changes

HDDS-7326. Intermittent timeout in TestECContainerRecovery.testContainerRecoveryOverReplicationProcessing

---

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/db.json
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/insights/insights.tsx

When there is only one volume present in the cluster, the buckets dropdown does not list is getting displayed.
https://issues.apache.org/jira/browse/HDDS-5112
Manually

HDDS-5112. Recon Insights page does not list buckets when only one volume is present.

---

hadoop-hdds/docs/content/feature/Streaming-Write-Pipeline.md

This is to document the new Streaming Pipeline feature ([HDDS-4454](https://issues.apache.org/jira/browse/HDDS-4454)).
https://issues.apache.org/jira/browse/HDDS-7425
NA

HDDS-7425. Add documentation for the new Streaming Pipeline feature.

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsConfigKeys.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/x509/SecurityConfig.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/StorageInfo.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/TestHddsSecureDatanodeInit.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/CertificateClient.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/CommonCertificateClient.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DefaultCertificateClient.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/SCMCertificateClient.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/TestCertificateClientInit.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/TestDefaultCertificateClient.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/HASecurityUtils.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestSecureOzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMStorage.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServer.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStorageConfig.java

In this PR I would like to add a check to the security initialization code, that check if a certificate is about to be expire soon, and if yes, then it will remove the certificate materials of the service, re-initializes the certificate client in a state where there are no keys and certificates anymore, and with that forces the new instance to get a new certificate as it does during the basic security initialization.
This would help to renew certificates with a restart instead of a tedious manual process that involves a restart and removing the files by hand.
For Ozone Manager the code would run when the OM is started with the --init option, as that code is responsible to initialize certificates also when security gets enabled.
For DataNode and for Recon it works during regular startup as …

HDDS-7453. Check certificate expiration at service startup, renew if necessary.

---

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServer.java

JVM crash is observed in ozone integration test. The cause for this,
Rocks DB is closed
Operation in other thread accessing rocks db for read and write
As solution, need to perform graceful shutdown in order, closing other threads and then rocksdb handle at last.
https://issues.apache.org/jira/browse/HDDS-7314
This patch was tested manually by running integration tests. All integration tests are passing now and no rocksDB crash exception observed in any of the integration tests which was otherwise observed as per log attached in JIRA.

HDDS-7314. Recon graceful shutdown while closing RocksDB handle.

---

hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java

https://issues.apache.org/jira/browse/HDDS-7360
Manually Tested "org.apache.hadoop.fs.ozone.TestRootedOzoneFileSystem" test cases which were failing in following boundary conditions of "listingPageSize":
1. If I give value at client less than equal to 1, it hung.
2. If I give value more than 1 upto 3, then it doesn't hung any of the test case of TestRootedOzone file, but "listStatusCheckHelper" method makes assertion fail for 2-3 test cases.
3. If give value more than 3, all test cases passed.

HDDS-7360. Investigate TestRootedOzoneFileSystem test cases.

---

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/datanodes/datanodes.tsx
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/pipelines/pipelines.tsx

To show last refreshed at Pipeline and Datanodes Page.
https://issues.apache.org/jira/browse/HDDS-7456
Manually

HDDS-7456. Recon: Refreshed at not working on Pipeline and DataNode page

---

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/datanodes/datanodes.tsx

To add Tooltip for open Containers column
https://issues.apache.org/jira/browse/HDDS-7469
Manually

HDDS-7469. Recon: Add more information to Open Containers column on on the Datanodes page.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/DatanodeCommandCountUpdatedHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/events/SCMEvents.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestDatanodeCommandCountUpdatedHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java

When a datanode heartbeat is processed, it updates the queued command counts on the datanodes. Replication is going to use this information when assigning work to datanodes, and if a datanode exceeds the load limit it will be excluded until it has more capacity.
To allow RM to remove nodes from any exclude lists, we should fire a SCM event when the counts are updated, as this will avoid RM polling frequently.
For now, the notification in RM does not do anything - we will add code which uses it in future changes as we build out the load aware under / over replication processing.
https://issues.apache.org/jira/browse/HDDS-7471
New unit tests

HDDS-7471. EC: Notify ReplicationManager when a heartbeat updates datanode command counts

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemWithStreaming.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java

Fix the following NPE
```java
at org.apache.hadoop.hdds.client.ReplicationConfig.adjustReplication(ReplicationConfig.java:138)
at org.apache.hadoop.fs.ozone.BasicOzoneClientAdapterImpl.createStreamFile(BasicOzoneClientAdapterImpl.java:280)
at org.apache.hadoop.fs.ozone.BasicOzoneFileSystem.createOutputStream(BasicOzoneFileSystem.java:278)
at org.apache.hadoop.fs.ozone.BasicOzoneFileSystem.create(BasicOzoneFileSystem.java:254)
at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1195)
at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1175)
at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1064)
```
https://issues.apache.org/jira/browse/HDDS-7478
A new unit test.

HDDS-7478. [Ozone-Streaming] NPE in when creating a file with o3fs.

---

pom.xml

Some transitive dependencies via Hadoop are declared explicitly, dating back to the time when Ozone was split from Hadoop project.  Since then Hadoop has moved on with these dependencies, and we have updated Hadoop version in Ozone, but retained the old versions of these transitive dependencies.
https://issues.apache.org/jira/browse/HDDS-7475
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3439905879
Dependency tree diff:
```
@@ -107,7 +107,7 @@
|  |  \- org.apache.kerby:kerby-pkix:jar:1.0.1:compile
|  |     +- org.apache.kerby:kerby-asn1:jar:1.0.1:compile
|  |     \- org.apache.kerby:kerby-util:jar:1.0.1:compile
-|  +- org.codehaus.woodstox:stax2-api:jar:3.1.4:compile
+|  +- org.codehaus.woodstox:stax2-api:jar:4.2.1:compile
|  +- …
```

HDDS-7475. Remove outdated Hadoop dependencies stax2-api, nimbus-jose-jwt, json-smart

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java

Added unit testcase for create snapshot validation -  `TestOmSnapshot / testNonExistentBucket`
https://issues.apache.org/jira/browse/HDDS-7452
Added testcases in file - hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
`mvn -Dtest=TestOmSnapshot test`
[INFO] Running org.apache.hadoop.ozone.om.TestOmSnapshot
[INFO] Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 156.251 s - in org.apache.hadoop.ozone.om.TestOmSnapshot
[ERROR] Exception in thread "Thread-1021" Exception in thread "Thread-2642" Exception in thread "Thread-2926" Exception in thread "Thread-4261" Exception in thread …

HDDS-7452. [snapshot] Add unit-testcases for snapshot create validation.

---

pom.xml

Bump commons-codec to latest 1.15 due to [CODEC-134](https://issues.apache.org/jira/browse/CODEC-134).
https://issues.apache.org/jira/browse/HDDS-7485
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3456719263

HDDS-7485. Bump commons-codec to 1.15

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/events/EventExecutor.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/events/FixedThreadPoolWithAffinityExecutor.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/events/IEventInfo.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/events/TestEventQueue.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ScmUtils.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeHeartbeatDispatcher.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManager.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStorageContainerManagerFacade.java

Added metrics for
- FCR/ICR report waiting in queue crosses threshold
- FCR/ICR End to End execution time crosses threshold
https://issues.apache.org/jira/browse/HDDS-7255
Tested using Unit case and count is verified

HDDS-7255. Add metrics for container reports events

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerCheckRequest.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECContainerReplicaCount.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/ClosedWithUnhealthyReplicasHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/ECReplicationCheckHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECContainerReplicaCount.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestClosedWithUnhealthyReplicasHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestECReplicationCheckHandler.java

If the DN scrubber marks a container as UNHEALTHY, the EC Replication Manager logic needs to be able to deal with it. It needs to remove the unhealthy one, and create a new copy using EC Reconstruction.
This PR proposes considering UNHEALTHY replicas when checking for under and over replication in `ECReplicationCheckHandler`. 
The newly introduced handler `ClosedWithUnhealthyReplicasHandler` will handle closed EC containers with unhealthy replicas but no under, over or mis replication.
For example, consider a closed EC 3-2 container with the following replicas:
Replica Index 1: Closed
Replica Index 2: Closed
Replica Index 3: Closed, Unhealthy (2 replicas for this index)
Replica Index 4: Unhealthy
Replica Index 5: Closed
This is a case of under replication because index 4 is unavailable. …

HDDS-7101. EC: ReplicationManager - handle UNHEALTHY replicas

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/ObjectStore.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsSnapshot.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientAdapter.java

This change is to implement create snapshot for ozone file system commands.
https://issues.apache.org/jira/browse/HDDS-7375
Using CLI and running following commands:
```
bash-4.2$ ozone fs -createSnapshot /vol1/bucket1 snap
Created snapshot ofs://om/vol1/bucket1/.snapshot/snap
bash-4.2$ ozone fs -createSnapshot /vol1/bucket1 snap
createSnapshot: Snapshot already exists
bash-4.2$ ozone fs -ls /vol1/bucket1/.snapshot/snap
Found 1 items
-rw-rw-rw-   3 hadoop hadoop       3811 2022-11-01 06:09 /vol1/bucket1/.snapshot/snap/key1
```

HDDS-7375. [Snapshot] Implement `ozone fs` command for creating snapshot

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/DefaultCAServer.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificates/utils/SelfSignedCertificate.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/utils/TestCRLCodec.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/utils/TestCertificateCodec.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificates/TestRootCertificate.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/CertificateClientTestImpl.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainerWithTLS.java

https://issues.apache.org/jira/browse/HDDS-7487

HDDS-7487. Support fine grained certificate lifetime for efficient test.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerHealthResult.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECOverReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationQueue.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/ECReplicationCheckHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/RatisReplicationCheckHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECOverReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestLegacyReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestECReplicationCheckHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestRatisReplicationCheckHandler.java

While looking into mis-replicated handling for EC, we found the code is much simplified if we handle mis-replicated containers only when they are not also over or under replicated.
With that in mind, we should have a separate unhealthy state for mis-replication, rather than making it part of under-replication.
This change adds that new state, adds mis-replication logic to the ECReplicationCheckHandler and amends the RatisReplicationCheckHandler to match it.
For now, a mis-replicated queue has been added, but this may change later, as we need to look into the queues and see if they need more work to separate out EC and Ratis or not.
https://issues.apache.org/jira/browse/HDDS-7488
New and modified unit tests

HDDS-7488. EC: ReplicationManager: Move Mis-Replicated into a separate unhealthy state

---

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/db.json
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/routes.json
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/overview/overview.tsx

Remove missingContainer Endpoint and use missingCounter from ClusterState End Point.
On a cluster with million containers, it was observed that the Recon dashboard page does not load even when most of the information has been returned by the backend through the /clusterState API, but the /missing containers API is still blocked.
https://issues.apache.org/jira/browse/HDDS-4402
Manually Tested

HDDS-4402. Recon dashboard page does not load until missing containers API returns data.

---

hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/SnapshotInfo.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmSnapshotInfo.java

> It turns out in HDDS-7281 I forgot to add the serialization and deserialization logic for dbTxSequenceNumber in SnapshotInfo. As a result, dbTxSequenceNumber is always zero when deserialized. This is a simple fix to address that issue.
https://issues.apache.org/jira/browse/HDDS-7494
- This is manually tested on a deployed cluster.

HDDS-7494. [Snapshot] Fix SnapshotInfo#dbTxSequenceNumber (de)serialization

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/tenant/OMTenantAssignUserAccessIdRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestOMBucketCreateRequest.java

Avoid IllegalArgumentException in validateAndUpdateCache() which is called during applyTransaction
1. return OMException with QUOTA_EXCEEDED
2. OMTenantAssignUserAccessIdRequest also return IllegalArgumentException in similar case, returned OMException
https://issues.apache.org/jira/browse/HDDS-7470
Test scenario for create bucket crossing the size quota

HDDS-7470. [Quota] bucket is created crossing quota makes OM crash and unable to start

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmBucketArgs.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmBucketArgs.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketSetPropertyRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestOMBucketSetPropertyRequest.java

When updating bucket arguments from the CLI, eg:
```
ozone sh bucket set-replication-config o3://ozone1/testquota/ec-bucket5 --type EC --replication rs-3-2-1024k
```
A quota related error occurs:
```
QUOTA_ERROR Can not clear bucket spaceQuota because volume spaceQuota is not cleared.
```
This is because the OMBucketArgs object defaults the quota related values to "-1" which means "clear the quota". As these values are "long" types, they cannot have a null value, so this default is always passed, making it impossible to know if the bucketArgs are trying to reset the quota, or just passed by default.
This change adds a getter to OmBucketArgs called `hasQuotaInBytes` and `hasQuotaInNamespace` to align with the protobuf fields which tell you if a value has been passed or not. That way, we …

HDDS-7346. Cannot set bucket args when the bucket has quota set

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerListVolumes.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

Change the authorization check when listing volumes visible to another user.
https://issues.apache.org/jira/browse/HDDS-7498
unit tests

HDDS-7498. Add permission check when `--user` is specified in `ozone sh volume list`

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMDirectoriesPurgeRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMDirectoriesPurgeResponseWithFSO.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMDirectoriesPurgeRequestAndResponse.java

While delete keys in background service for recursive cleanup, cleanup of key's space and its namespace is added in purge of keys.
https://issues.apache.org/jira/browse/HDDS-4565
1. single file remove with delete folder hierarchy
2. multiple files in different level with delete folder hierarchy
3. multiple files in same level with delete folder hierarchy

HDDS-4565. [FSO]Delete : quotaReleased on directory deletion should consider all sub paths

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/x509/SecurityConfig.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/hdds/datanode/metadata/CRLDBDefinition.java

In a secure cluster, if `ozone.metadata.dirs` are not specified then SCM will fallback to `hdds.datanode.dir` and will end up storing its certificates under the datanode path. It's preferable to let the system crash, rather than storing  scm data under the datanode disk. Also, the datanodes crash if `ozone.metadata.dirs` aren't specified, so it makes sense to not have a fallback.
from `master` under `compose/ozonesecure`, edit `docker-config`
```
OZONE-SITE.XML_ozone.om.ratis.storage.dir=/data/om/ratis
OZONE-SITE.XML_ozone.om.db.dirs=/data/om/db
OZONE-SITE.XML_ozone.om.ratis.snapshot.dir=/data/om/ratis-snap
OZONE-SITE.XML_ozone.scm.ha.ratis.storage.dir=/data/scm/ratis
OZONE-SITE.XML_ozone.scm.db.dirs=/data/scm/db
OZONE-SITE.XML_ozone.recon.db.dir=/data/recon/db …
```

HDDS-7476. SCM root CA stored under hdds.datanode.dir if ozone.metadata.dirs is not specified

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/AbstractFindTargetGreedy.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerSelectionCriteria.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerTask.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/FindSourceGreedy.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/FindSourceStrategy.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/FindTargetGreedyByNetworkTopology.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/FindTargetGreedyByUsageInfo.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/FindTargetStrategy.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancerTask.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestFindTargetStrategy.java

Currently, we stop an iteration of balancer if we are one datanode or 5GB away from the limits "datanodes.involved.max.percentage.per.iteration" and "size.moved.max.per.iteration" respectively. This is a pre-emptive check. 
This PR changes this by trying to dynamically adapt to these limits if possible instead of breaking out of the loop right away. If we're nearing the limits - that is, we're one DN away - then we restrict potential source datanodes to the ones that have already been selected. If we've reached the limits, then we restrict potential sources and targets both to datanodes that have already been selected. The iteration can continue because we aren't involving any new datanodes (Changes made in `ContainerBalancerTask`, `FindSourceStrategy` and `FindTargetStrategy`). We adapt …

HDDS-5526. ContainerBalancer#checkConditionsForBalancing pre-emptively checks iteration limits.

---

hadoop-ozone/dist/src/main/compose/ozonesecure/test.sh
hadoop-ozone/dist/src/main/smoketest/ec/ozonefs.robot
hadoop-ozone/dist/src/main/smoketest/ozonefs/ozonefs.robot

Fix intermittent failure in ozonesecure replication test
(I increased the number of test datanodes from 3 to 5 nodes in [acceptance test (secure)](https://github.com/apache/ozone/pull/3810/files#diff-d9e95f2a5878015411d6da9c74f5ade773b2e9ffac6ff7345929635281e3beb8R30) for EC file's disk usage test,
which caused intermittent failure in ozonesecure replication test.
This PR is to move the EC-specific tests to hadoop-ozone/dist/src/main/smoketest/ec, which is executed only in ozone environment with 5 datanodes, and revert ozonesecure test back to 3 datanodes.)
https://issues.apache.org/jira/browse/HDDS-7518
CI's robot test

HDDS-7518. Fix intermittent failure in ozonesecure replication test

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerSet.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeConfiguration.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECContainerOperationClient.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinator.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/StaleRecoveringContainerScrubbingService.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestStaleRecoveringContainerScrubbingService.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/CloseContainerEventHandler.java
hadoop-hdds/test-utils/pom.xml
hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/GenericTestUtils.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/TestECContainerRecovery.java

EC Reconstruction(with Write Chunk Operation) recreates open with replica Index 0 when StaleRecoveringContainerScrubbingService deletes the recovering container. Thus an invalid container with replica 0 is created. This could potentially cause SCM failure when container is reported with heartbeat & also partial reconstructed container when a new block is written simultaneously with recovering container being deleted.
Marking the recovering container as unhealthy should fix the issue. Handling the failure to delete unhealthy container should fix the issue from Reconstruction Coordinater will cleanup the stale container. 
https://issues.apache.org/jira/browse/HDDS-7462
Unit & Integration Test

HDDS-7462. EC: Fix Reconstruction Issue with StaleRecoveringContainerScrubbingService

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECOverReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECOverReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java

On a small cluster, if an EC container is both over replicated and under replicated, there might be no free nodes to place a new replica on. In this case, we need to remove over-replicated replicas first, freeing up nodes to put the new replicas onto.
We always attempt to process under replication first and a container is only ever in one "bad" state (over, under or mis replicated), so the case of both under and over replication will fall into the under replication handler.
This PR solves this problem by catching "not enough nodes" exceptions in the under-replication handler - it then checks to see if the container is also over-replicated and if it is, passes control to the over-rep handler instead.
The under-replication repair will be reattempted on the next pass, hopefully after the …

HDDS-7092. EC: Offline Recovery with simultaneous Over Replication & Under Replication

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/OverReplicatedProcessor.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManagerMetrics.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnderReplicatedProcessor.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestOverReplicatedProcessor.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestUnderReplicatedProcessor.java

The logic to send datanode commands, such as replicate, reconstruct, delete and close container happens in a few different places in the RM classes. It would make sense to centralise this in some common code, as it will make it more re-usable. There is some logic in the balancer which could re-use these new central methods to send replicate and delete commands too.
https://issues.apache.org/jira/browse/HDDS-7528
Some tests modified and some new ones added to cover the new logic.

HDDS-7528. EC: ReplicationManager - refactor logic to send datanode commands into a central place

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/ECXceiverClientGrpc.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestHddsDispatcher.java

When WriteChunk or PutBlock fails when writing a stripe, the client should retry the operation before rewriting this stripe to a new block. So that the block files on the disk will be as large as possible. 
This patch addresses a way to configure `ECXceiverClientGrpc` to retry failed requests based on GRPC Status Code `DEADLINE_EXCEEDED` 
https://issues.apache.org/jira/browse/HDDS-7187
Manual testing and Unit tests.

HDDS-7187. EC: Retry failed writes before rewrite to a new block group

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketSetPropertyRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestOMBucketSetPropertyRequest.java

If EC or quotas are set on an existing encrypted bucket, the encryption bucket property gets overwritten. Any keys created on the updated bucket are not encrypted. 
```
sh-4.2$ ozone sh bucket create -k key1 o3://om/vol1/saketa-ec1bucket
sh-4.2$ ozone sh bucket info o3://om/vol1/saketa-ec1bucket
{
"name" : "saketa-ec1bucket",
"creationTime" : "2022-11-22T17:32:37.501Z",
"modificationTime" : "2022-11-22T17:32:37.501Z",
"encryptionKeyName" : "key1",
"bucketLayout" : "LEGACY",
"owner" : "testuser",
"link" : false
}
sh-4.2$ ozone sh bucket set-replication-config o3://om/vol1/saketa-ec1bucket --type EC --replication …
```

HDDS-7449. Avoid overwriting bucket encryption properties when quota/replication config are set on an existing bucket

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestLegacyReplicationManager.java

`ReplicationManager` and `LegacyReplicationManager` both define some of the same configuration keys in their own `ReplicationManagerConfiguration` class.  This results in duplicate items in the generated config:
```
$ grep '<name>hdds.scm.replication' hadoop-hdds/server-scm/target/classes/ozone-default-generated.xml | sort | uniq -c
1     <name>hdds.scm.replication.container.inflight.deletion.limit</name>
1     <name>hdds.scm.replication.container.inflight.replication.limit</name>
2     <name>hdds.scm.replication.event.timeout</name>
1     <name>hdds.scm.replication.maintenance.remaining.redundancy</name>
2     <name>hdds.scm.replication.maintenance.replica.minimum</name>
1     <name>hdds.scm.replication.over.replicated.interval</name>
2 …
```

HDDS-7535. Eliminate duplicated config in LegacyReplicationManager

---

pom.xml

* Bump protobuf-java from 3.19.2 to 3.19.6
* Upgrade Ratis to 2.4.1, Ratis Thirdparty to 1.0.3
* Increase max. heap size for integration tests (required due to RATIS-1717)
https://issues.apache.org/jira/browse/HDDS-7289
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3555369297

HDDS-7289. Bump protobuf-java from 3.19.2 to 3.19.6

---

pom.xml

Some dependency declarations in Ozone root POM's `dependencyManagement` are leftover from Hadoop, unused, and can be removed.
https://issues.apache.org/jira/browse/HDDS-7536
No added or removed dependencies, verified by _dependency_ check in CI.
Also verified that dependency tree has not changed.  The only difference between Maven's output from `master` and the patch is in the Reactor Summary (time required to build each sub-module):
```
$ git checkout master
$ mvn -Dorg.slf4j.simpleLogger.showDateTime=false -B --no-transfer-progress dependency:tree > dep.master
$ git checkout HDDS-7536
$ mvn -Dorg.slf4j.simpleLogger.showDateTime=false -B --no-transfer-progress dependency:tree > dep.HDDS-7536
$ diff -uw dep.master dep.HDDS-7536
--- dep.master	2022-11-25 18:14:37.836905281 +0100
+++ …
```

HDDS-7536. Remove unused dependency declarations

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerDoubleBuffer.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerDoubleBuffer.java

The OmRequest double buffer flush thread flushes the entire buffer as a batch.  Since follower OM's will flush batches with different contents, snapshots can't stay consistent between the leader and the followers.
This change is to flush double buffer snapshot aware and flush all the transactions before snapshot create request.
https://issues.apache.org/jira/browse/HDDS-7279
- Added unit test.
- Tested it by preventing the flush thread from waking up when a key commit request occurs as described by George in [jira](https://issues.apache.org/jira/browse/HDDS-7279)

HDDS-7279. Snapshot Create requires Double Buffer Flush thread to split the commit batch.

---

hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServerConfigKeys.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/NSSummaryTask.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/NSSummaryTaskDbEventHandler.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/NSSummaryTaskWithFSO.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/NSSummaryTaskWithLegacy.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestNSSummaryEndpointWithFSO.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestNSSummaryTaskWithFSO.java

Issue:
we are keep on iterating that iterator using while loop and "handlePutDirEvent" method keep pushing the keys and value objects (NSSummary) in `nsSummaryMap` and that hashmap is retaining lot of objects worth of 16 GB and then eventually goes OOM. At the end of while loop down the code in this method, we push the data to NSSummaryTable in recon SQL DB.
Solution:
As per heap dump provided, further analysed recon code which runs NSSummary task, the code which is adding these objects "NSSummary" in hashmap. "NSSummary" object is used for storing metadata summary of dir/keys using few data structures and all internal data structures are using primitive types for storing this metadata which are already optimized. As per heapdump analysis, it is being observed that this each metadata …

HDDS-7500. Ozone recon server Memory Optimization.

---

.github/workflows/ci.yml
.github/workflows/scheduled_ci.yml

`build-branch` workflow is disabled by default in new contributors' forks because it has a scheduled run.  We may be able to improve new contributor experience by separating scheduled runs from regular CI workflow.
This is achieved by moving the workflow steps into `ci.yml`, which is defined as a reusable workflow.  It is called by existing `build-branch` workflow (`post-commit.yml`) on `push`/`pull_request` events, and by new `scheduled_ci.yml` on `schedule`.
It also saves resources, because the scheduled run can be kept disabled in forks.
https://issues.apache.org/jira/browse/HDDS-7540
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3543655506

HDDS-7540. Separate scheduled CI from push/PR workflows

---

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/pipelines/pipelines.tsx

Recon UI should show `DORMANT` in pipeline status filter.
https://issues.apache.org/jira/browse/HDDS-7554
- Manually

HDDS-7554. Recon UI should show DORMANT in pipeline status filter

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/OzoneClientConfig.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestECKeyOutputStream.java

Introduced a new flush thread in ECKeyOutputStream, pipelining the encode stage and flush stage.
The producer thread does the buffering and encoding, and the consumer thread does the flushing.
They are connected by a `ArrayBlockingQueue`, whose size is `"ec.stripe.queue.size"`, which defaults to 2.
Necessary refactors has been done to seperate the two stages.
`EOFDummyStripe` is used to denote the end of the key, `CheckpointDummyStripe` is used for syncing in tests.
Synchronization was added in tests.
~~NOTE: Currently the exception handling needs another look. If exception were thrown in the flush thread,
the main thread will not get it until calling `Future.get()` in `close()`.~~ This has been fixed in d710aff.
https://issues.apache.org/jira/browse/HDDS-6615
It's covered by existing …

HDDS-6615. EC: Improve write performance by pipelining encode and flush

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/bucket/ClearQuotaHandler.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/bucket/SetQuotaHandler.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/volume/ClearQuotaHandler.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/volume/SetQuotaHandler.java

CLI usages included one of the mandatory parameter for setquota and clrquota in both volume and bucket case.
https://issues.apache.org/jira/browse/HDDS-7561
1. UT cases are added
2. command option is verified for showing usages of quota parameter for atleast one of quota

HDDS-7561. Improve setquota, clrquota CLI usage

---

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/ClusterStateEndpoint.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/ClusterStateResponse.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestTotalOpenContainerCount.java

We need to:
(1) Add field openContainers to "/clusterState" which gives us the details about all the open containers across the cluster!
https://issues.apache.org/jira/browse/HDDS-7510
Tested using Unit-Tests

HDDS-7510. Recon: Return number of open containers in `/clusterState` endpoint

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/PrometheusMetricsSink.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/DecayRpcSchedulerUtil.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/TestDecayRpcSchedulerUtil.java

On the Prometheus endpoint for the OM, in the DecayRpcScheduler summary for users, the username is exposed in the metric name. It makes almost impossible to monitor these values as every time a new user shows up we need to register a new metrics name. 
The metric name from `org_apache_hadoop_ipc_decay_rpc_scheduler_volume` becomes `org_apache_hadoop_ipc_decay_rpc_scheduler_caller_hadoop_volume` for a user with `hadoop` username.
The proposed solution is to filter the logs and remove the username from the metric and add it in a username tag. 
This metric comes from `hadoop-common-3.3.4.jar/DecayRpcScheduler` and more specifically
```
Metrics2Util.NameValuePair entry = (Metrics2Util.NameValuePair)topNCallers.poll();
String topCaller = "Caller(" + entry.getName() + ")";
String …
```

HDDS-7394. OM RPC FairCallQueue decay decision metrics list caller username in the metric

---

.github/workflows/post-commit.yml
.github/workflows/scheduled_ci.yml

Minor addendum for #4004: the reusable workflow does not get the caller's secrets by default, so the _coverage_ check is running into error.
```
SONAR_TOKEN environment variable should be set
```
https://github.com/apache/ozone/actions/runs/3574181477/jobs/6010427884#step:8:19
The _coverage_ check is run only in Apache repo for `push` events, so it was not flagged in my fork, nor the PR.
Reference:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit
https://issues.apache.org/jira/browse/HDDS-7540
It will be tested when the PR is merged.

HDDS-7540. Let reusable workflow inherit secrets

---

hadoop-ozone/dist/src/main/compose/ozone/docker-config
hadoop-ozone/dist/src/main/compose/ozonesecure/docker-config
hadoop-ozone/dist/src/main/smoketest/ozonefs/ozonefs.robot
pom.xml

Add a new acceptance test for Streaming Pipeline.  This supersedes #3991
https://issues.apache.org/jira/browse/HDDS-7426
NA

HDDS-7426. Add a new acceptance test for Streaming Pipeline.

---

hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotCreateRequest.java

Added unit-testcases for Ozone Snapshot create API name validation - `TestOMSnapshotCreateRequest / testPreExecuteNameOnlyNumbers` and `TestOMSnapshotCreateRequest / testPreExecuteNameLength`
https://issues.apache.org/jira/browse/HDDS-7571
Added testcases in file - `hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotCreateRequest.java`
```
$ mvn -Dtest=TestOMSnapshotCreateRequest test
[INFO] Running org.apache.hadoop.ozone.om.request.snapshot.TestOMSnapshotCreateRequest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.623 s - in …
```

HDDS-7571. [snapshot] Add unit-testcases for Ozone Snapshot create API name validation.

---

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/utils/themeIcons.tsx

This bug in introduced in [HDDS-6308](https://issues.apache.org/jira/browse/HDDS-6308), which updates the type of "replicationFactor" from "number" to "string".
https://issues.apache.org/jira/browse/HDDS-7575

HDDS-7575. Correct showing of RATIS-THREE icon in Recon UI

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMDirectoryCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMDirectoryCreateRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/file/OMDirectoryCreateResponse.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/file/OMDirectoryCreateResponseWithFSO.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/file/TestOMDirectoryCreateRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/file/TestOMDirectoryCreateRequestWithFSO.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/file/TestOMDirectoryCreateResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/file/TestOMDirectoryCreateResponseWithFSO.java

Fix `Ozone` fs `mkdir` does not update bucket's `usedNamespace`
https://issues.apache.org/jira/browse/HDDS-7497
Before this PR: 
Bucket property `usedNamespace` will become negative after delete a directory, because the `mkdir` will not increase the `usedNamespace` of bucket but `rmdir` will decrease `usedNamespace`.
```java
"usedNamespace" can be updated when `mkdir`
[root@Linux /root/ozone]% ozone sh bucket create s3v/bucket1
[root@Linux /root/ozone]% ozone fs -mkdir ofs://localhost/s3v/bucket1/dir1
[root@Linux /root/ozone]% ozone sh bucket info s3v/bucket1
{
"volumeName" : "s3v",
"name" : "bucket1",
"creationTime" : "2022-11-16T11:17:26.512Z",
"modificationTime" : …
```

HDDS-7497. Fix mkdir does not update bucket's usedNamespace

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisUnderReplicationHandler.java

The new RM needs a handler that can process under replicated Ratis containers and create replication commands. Legacy RM does this in the `handleUnderReplicatedContainer` method. The new handler `RatisUnderReplicationHandler` mostly has the same logic as legacy with one notable difference - we don't need to handle mis replication (failure to meet placement policy) because that's a separate case now and should get its own handler.
https://issues.apache.org/jira/browse/HDDS-7563
`TestRatisUnderReplicationHandler`

HDDS-7563. Add a handler for under replicated Ratis containers in RM

---

hadoop-ozone/dist/pom.xml
pom.xml

Suppress warning about long filenames output by `maven-assembly-plugin` when creating source tarball:
```
[INFO] --- maven-assembly-plugin:2.4:single (src-dist) @ ozone-dist ---
[INFO] Reading assembly descriptor: /home/adoroszlai/src/apache/ozone/hadoop-ozone/dist/src/main/assemblies/ozone-src.xml
[INFO] Building tar: /home/adoroszlai/src/apache/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT-src.tar.gz
[WARNING] Entry: ozone-1.3.0-SNAPSHOT-src/dev-support/annotations/target/maven-status/maven-compiler-plugin/compile/default-compile/ longer than 100 characters.
[WARNING] Resulting tar file can only be processed successfully by GNU compatible tar commands
[WARNING] Entry: ozone-1.3.0-SNAPSHOT-src/dev-support/annotations/target/classes/META-INF/services/javax.annotation.processing.Proce …
```

HDDS-7562. Suppress warning about long filenames in tar

---

pom.xml

Ratis uses Netty 4.1.77.  The same version is recommended for gRPC 1.48.1 which Ozone uses.  This PR proposes to move from Netty 4.1.79 to Netty 4.1.77 for consistency.
https://issues.apache.org/jira/browse/HDDS-7579
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3600140354

HDDS-7579. Use Netty 4.1.77 for consistency

---

hadoop-ozone/dist/src/main/license/update-jar-report.sh

Pattern matching for jar version numbers in `update-jar-report.sh` does not correctly work for `ratis-*-2.4.2-8b8bdda-SNAPSHOT`.
Expected:
```
share/ozone/lib/ratis-client.jar
share/ozone/lib/ratis-common.jar
share/ozone/lib/ratis-grpc.jar
share/ozone/lib/ratis-metrics.jar
share/ozone/lib/ratis-netty.jar
share/ozone/lib/ratis-proto.jar
share/ozone/lib/ratis-server-api.jar
share/ozone/lib/ratis-server.jar
```
Actual:
```
share/ozone/lib/ratis-clientbdda-SNAPSHOT.jar
share/ozone/lib/ratis-commonbdda-SNAPSHOT.jar
share/ozone/lib/ratis-grpcbdda-SNAPSHOT.jar
share/ozone/lib/ratis-metricsbdda-SNAPSHOT.jar
share/ozone/lib/ratis-nettybdda-SNAPSHOT.jar
share/ozone/lib/ratis-protobdda-SNAPSHOT.jar
share/ozone/lib/ratis-server-apibdda-SNAPSHOT.jar
share/ozone/lib/ratis-serverbdda-SNAPSHOT.jar
``` …

HDDS-7581. Fix update-jar-report for snapshot versions

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestDirectoryDeletingServiceWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/DirectoryDeletingService.java

In DirectoryDeletingService, added sub-directory also for deletion including its sub-file and sub-dir. This will be handled automatically by PurgeDiretoriesRequest.
https://issues.apache.org/jira/browse/HDDS-7541
1. Tested E2E with recursive deletion of directory
2. UT is updated for the change verifying same

HDDS-7541. FSO recursive delete directory with hierarchy takes much time for cleanup

---

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/Shell.java

Updated the URI syntax description so that it contains examples of serviceId and port usage.
[Improve the description of Ozone URI in Ozone Shell help message](https://issues.apache.org/jira/browse/HDDS-5704)
Running on a local docker cluster I've reproduced the message and also experimented on separate ways how the URIs can be used.

HDDS-5704. Ozone URI syntax description in help content needs to mention about ozone service id

---

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/handlers/BucketHandler.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/handlers/FSOBucketHandler.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/handlers/KeyEntityHandler.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/handlers/LegacyBucketHandler.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/OMMetadataManagerTestUtils.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestNSSummaryEndpointWithFSO.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestNSSummaryEndpointWithLegacy.java

EC: Fix the NSSummaryEndpoint#getDiskUsage should be fixed for EC keys
https://issues.apache.org/jira/browse/HDDS-7472
CI's unit tests.

HDDS-7472. EC: Fix NSSummaryEndpoint#getDiskUsage for EC keys

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmMetadataManager.java

1. Fix list snapshot API. Let it list the correct snapshot when there are more than one buckets.
2. Throw an exception when listing a non-existent bucket.
3. Add a assertion in `testListSnapshot` for listing a non-existent bucket.
https://issues.apache.org/jira/browse/HDDS-7512
The following is a manual test on docker for listing correct snapshot:
The following is a manual test on docker for listing a non-existent bucket:
The following is the unit test:

HDDS-7512. [snapshot] List Snapshot returns an empty list for a non-existent bucket

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/BooleanTriFunction.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBProfile.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java
hadoop-hdds/rocksdb-checkpoint-differ/pom.xml
hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java
hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDiffUtils.java
hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/rocksdiff/TestRocksDBCheckpointDiffer.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestOMSnapshotDAG.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SstFilteringService.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestKeyDeletingService.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestSstFilteringService.java
pom.xml

This PR introduces a background service `SSTFilteringService` to delete irrelevant SST files of a snapshot, It makes use of RocksDB#deleteFile
API to do so which only permits the deletion of [last level of SST files](https://github.com/facebook/rocksdb/blob/de34e7196fdfc7d361404f5a69c6302c03b5090d/db/db_impl/db_impl.cc#L4212) ie if there are n levels of SST's at a given point , the service will delete only nth level SST's. This is still beneficial as the last level SST's are the bulkiest and deletion of these can help save space. On successful deletion , it will update a marker file `filtered-snapshots` and write the snapshot ID of the processed Snapshot to it. Only the` keyTable`, `fileTable` & `directoryTable` keys are deleted as they can grow very large compared to other tables. …

HDDS-6962. [Snapshot] Background Service to delete irrelevant SST files in a snapshot.

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmBucketArgs.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmBucketArgs.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketSetPropertyRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestOMBucketSetPropertyRequest.java

Setting Quotas on an existing bucket overwrites the replication config to RATIS ONE. These are the first options for ReplicationType & ReplicationFactor enums in [hdds.proto](https://github.com/apache/ozone/blob/master/hadoop-hdds/interface-client/src/main/proto/hdds.proto#L267-L279) which are picked up by default. 
Proposed change is similar to [#3975 ](https://github.com/apache/ozone/pull/3975). Add `hasDefaultReplicationConfig` in OmBucketArgs.java to indicate if Replication Config is passed by the client. If not, avoid setting replication config in protobuf fields.
if replication config is not explicitly passed, retain replication config of existing bucket when setting bucket properties in OMBucketSetPropertyRequest.java 
```
22/11/29 22:52:06 INFO rpc.RpcClient: Creating Volume: …
```

HDDS-7526. Avoid overwriting replication config on existing bucket when quota is set

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManager.java

Change error message when user does not have SCM superuser priviledge.
[HDDS-7597](https://issues.apache.org/jira/browse/HDDS-7597)
Manual test.
1. `mvn clean install -DskipTests -DskipShade`
2. `cd hadoop-ozone/dist/target/ozone-*/compose/ozonesecure`
3. `docker-compose up -d --scale datanode=3 `
4. `docker exec -it ozonesecure_om_1 /bin/bash`
a. `kinit -k testuser/om@EXAMPLE.COM -t /etc/security/keytabs/testuser.keytab` 
b. `ozone admin container report`

HDDS-7597. Improve ambiguous messages

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestLDBCli.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/DBScanner.java

Add option to show key count in DBScanner.
https://issues.apache.org/jira/browse/HDDS-7580
`bash-4.2$ ozone debug ldb --db=/data/metadata/om.db scan --column_family=keyTable -count`
Tested on docker , added unit tests.

HDDS-7580. Add option to show key count in DBScanner.

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteContainerCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/ReconstructECContainersCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/ReplicateContainerCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/endpoint/HeartbeatEndpointTask.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCommandInfo.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinatorTask.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionSupervisor.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisor.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisorMetrics.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationTask.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/SCMCommand.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestDeleteContainerCommandHandler.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ec/reconstruction/TestECReconstructionSupervisor.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisorScheduling.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestReplicationSupervisor.java
hadoop-hdds/interface-server/src/main/proto/ScmServerDatanodeHeartbeatProtocol.proto
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeProtocolServer.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMDatanodeProtocolServer.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/ClosedContainerReplicator.java

The new and old replication manager sends commands to the datanodes. If the command has not processed on the datanodes within the replicationManager event.timeout, RM assumes the command has failed for some reason, and may send another one to the same or a different host.
It makes sense to drop any command not processed on the datanode slightly before ReplicationManager gives up on it. Especially with delete container commands, we don't want to have two or more deletes pending in the system for the same container, when RM thinks there is only 1.
To facilitate dropping the commands, we can add a deadline to all commands. Only for commands we want to enforce a deadline on, we can set the deadline in SCM and check for it on the DN side. The deadline is the epoch time that the command should …

HDDS-7618. Replication Commands should timeout if not processed on datanodes in time

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/AbstractOverReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisOverReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisOverReplicationHandler.java

Added `RatisOverReplicationHandler` to create delete commands for replicas of over replicated ratis containers. The logic is similar to `LegacyReplicationManager#handleOverReplicatedContainer`.
https://issues.apache.org/jira/browse/HDDS-7591
`TestRatisOverReplicationHandler`

HDDS-7591. Add a handler for over replicated Ratis containers to RM

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/StateContext.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/TestStateContext.java

Update datanode's record of "SCM leader term" as soon as command is added to the queue to help drop obsolete commands sooner.
https://issues.apache.org/jira/browse/HDDS-7619
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3677335765

HDDS-7619. Update SCM term in datanode when command is received

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java

Adding config to only support Snapshot based on the max number of Snapshot history count
https://issues.apache.org/jira/browse/HDDS-7583
Only Config changes. No unit test cases required

HDDS-7583. Support efficient Snapdiff only until configured Snapshot History

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/parser/TestOzoneHARatisLogParser.java

Convert `TestOzoneHARatisLogParser` to JUnit5 and mark it as `@Flaky`.
https://issues.apache.org/jira/browse/HDDS-7008
Verified that `TestOzoneHARatisLogParser` is run as part of _integration (flaky)_:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3688403684/jobs/6243167414#step:6:3148

HDDS-7008. Mark TestOzoneHARatisLogParser as flaky

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/ClosedWithMismatchedReplicasHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestClosedWithMismatchedReplicasHandler.java

Scenario :
In a cluster(13 datanodes) having bucket of EC replication RS-3-2-1024K, for a container of a key which is in CLOSED state, 2 of the replicas in the cluster are made UNHEALTHY.
```
Replica Index 1: Closed
Replica Index 2: Unhealthy
Replica Index 3: Closed
Replica Index 4: Unhealthy
Replica Index 5: Closed
```
Expected behaviour - The container should be identified as under replicated due to the unhealthy containers. Once is it fully replicated, the unhealthy containers should be removed.
Observed behaviour - The UNHEALTHY replicas are still in the container after 12 hours and the under replication is not identified or fixed.
The reason is that the container is handled in ClosedWithMismatchedReplicasHandler as all replica states does not match the the container state (CLOSED …

HDDS-7640. EC: UNHEALTHY replicas not replaced by healthy replicas from a CLOSED container by RM

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java

ECUnderReplicationHandler finds new target datanodes where replicas of an under replicated container can be added. However, it does not exclude datanodes that are pending addition of a replica of that container from the list of targets. This pull request ensures that datanodes pending ADD are excluded.
https://issues.apache.org/jira/browse/HDDS-7582
Added UT

HDDS-7582. ECUnderReplicationHandler does not consider pending adds when finding targets

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/ContainerPlacementStatusDefault.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestContainerPlacementStatusDefault.java

Currently the calculation of misreplication count for max replicas per rack is done wrong, the signs have been swapped thus reporting negative value as the misreplication count.
https://issues.apache.org/jira/browse/HDDS-7627
Unit Tests

HDDS-7627. EC: Bug fix for calculating Misreplication Count

---

hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMDirectoriesPurgeResponseWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyDeleteResponseWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeysDeleteResponseWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/DirectoryDeletingService.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeysDeleteResponseWithFSO.java

Adding additional suffix "objectId" in deletedTable key to make it unique in case of frequent add and delete directory.
https://issues.apache.org/jira/browse/HDDS-7592
Impacted UTs are verified and CI will cover other impact cases for cleanup.
From E2E perspective, its verified that cleanup of all directory and related keys are deleted. table entry also have unique value,
```
sumitagrawal@sumitagrawal-MBP16 bin % ./ozone debug ldb --db /tmp/metadata/om.db scan --with-keys --column_family=deletedDirectoryTable | grep d1
"/-9223372036853886720/-9223372036853885696/-9223372036853885696/d1/-9223372036853877503" -> {
"keyName": "d1",
"fileName": "d1",
"/-9223372036853886720/-9223372036853885696/-9223372036853885696/d1/-9223372036853878527" -> {
"keyName": "d1",
"fileName": "d1",
```

HDDS-7592. Recursive delete of directory multiple time impacts some directory not removed

---

hadoop-hdds/common/pom.xml
hadoop-hdds/test-utils/pom.xml
hadoop-ozone/dev-support/checks/coverage.sh
hadoop-ozone/dist/pom.xml
hadoop-ozone/ozone-manager/pom.xml
hadoop-ozone/ozonefs-common/pom.xml
hadoop-ozone/ozonefs-hadoop2/pom.xml
hadoop-ozone/recon-codegen/pom.xml
hadoop-ozone/recon/pom.xml
hadoop-ozone/s3gateway/pom.xml
pom.xml

Move all dependency version definition to properties in root POM.  This allows overriding the dependency's version for each build.
https://issues.apache.org/jira/browse/HDDS-7371
Verified that all dependency versions are defined via properties, only enforcer rules have non-property-based `<version>` tags:
```
$ rg '<version>' | grep -Fv -e '1.3.0-SNAPSHOT' -e '<version>${'
pom.xml:                <version>[3.0.2,)</version>
pom.xml:                <version>[1.8,)</version>
```
Verified that dependency tree is same as for `master`:
```
$ git checkout master
$ mvn -Dorg.slf4j.simpleLogger.showDateTime=false -B --no-transfer-progress dependency:tree > dep.master
$ git checkout HDDS-7371
$ mvn -Dorg.slf4j.simpleLogger.showDateTime=false -B --no-transfer-progress dependency:tree > …
```

HDDS-7371. Create properties for all dependency versions

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/OverReplicatedProcessor.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnderReplicatedProcessor.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnhealthyReplicationProcessor.java

Lot of code reused. Over replicated Processor & Under replicated processor could be refactored before adding Mis replicated Processor.
https://issues.apache.org/jira/browse/HDDS-7616
Existing Unit testing should be sufficient. Contains only refactoring changes.

HDDS-7616. EC: Refactor Unhealthy Replicated Processor

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/AbstractFindTargetGreedy.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/FindSourceGreedy.java

Improve logging in `AbstractFindTargetGreedy` and `FindSourceGreedy`.
https://issues.apache.org/jira/browse/HDDS-7605

HDDS-7605. Improve logging in Container Balancer

---

hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmMetadataManager.java

Added unit-testcases for Snapshot List API - `TestOmMetadataManager / testListSnapshotDoesNotListOtherBucketSnapshots`
https://issues.apache.org/jira/browse/HDDS-7647
Added testcases in file - `hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmMetadataManager.java`
mvn -Dtest=TestOmMetadataManager test
```[INFO] -------------------------------------------------------
[INFO] Running org.apache.hadoop.ozone.om.TestOmMetadataManager
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 25.162 s - in org.apache.hadoop.ozone.om.TestOmMetadataManager
[INFO]
[INFO]
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0```

HDDS-7647. [snapshot] Add unit-testcases for Ozone Snapshot List API

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java

Revert "HDDS-7583. Support efficient Snapdiff only until configured Snapshot History"

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsConfigKeys.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/x509/SecurityConfig.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/DefaultCAServer.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/keys/KeyCodec.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/authority/TestDefaultCAServer.java

During SCM startup an external root CA can now be specified to use instead of generating a self signed CA.
[HDDS-7399](https://issues.apache.org/jira/browse/HDDS-7399)

HDDS-7399. Enable specifying external root ca

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientMultipartUploadWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java

Fix for size calculation for EC case in complete flow when old version file is for removal
https://issues.apache.org/jira/browse/HDDS-7649
Tested using UT cases and added for EC

HDDS-7649. S3 multipart upload EC release space quota wrong for old version

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/StateContext.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/endpoint/HeartbeatEndpointTask.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/states/endpoint/TestHeartbeatEndpointTask.java
hadoop-hdds/interface-server/src/main/proto/ScmServerDatanodeHeartbeatProtocol.proto
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeProtocolServer.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconDatanodeProtocolServer.java

If the DN does not receive any commands, then it will not receive the new term and drop any queued commands.  This change adds the term to the top-level heartbeat response and updates datanode's record of the SCM term.
https://issues.apache.org/jira/browse/HDDS-7621
Checked SCM audit logs for heartbeat response, they have `term`:
```
| INFO  | SCMAudit | user=hadoop | ip=172.23.0.2 | op=SEND_HEARTBEAT {datanodeUUID=eebacd7d-1ba4-4341-8871-4e663f6fcfdb, term=2, command=[]} | ret=SUCCESS |  
| INFO  | SCMAudit | user=hadoop | ip=172.23.0.5 | op=SEND_HEARTBEAT {datanodeUUID=cac3df6f-4877-4abb-ada0-d412240fbf7b, term=2, command=[]} | ret=SUCCESS |  
| INFO  | SCMAudit | user=hadoop | ip=172.23.0.7 | op=SEND_HEARTBEAT {datanodeUUID=a3c96822-b7e6-4c91-833d-908d05f0e891, term=2, command=[]} | …
```

HDDS-7621. Update SCM term in datanode from heartbeat without any commands

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerHealthResult.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationQueue.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestECReplicationCheckHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestRatisReplicationCheckHandler.java

Mis Replication is another form of under replication, but with a lower priority. Therefore it would make sense that mis-replicated containers are queued in the same queue as under-replicated. Ideally, we would not spend resources fixing mis-replicated until all the under replicated containers are handled, so having them in separate queues doesn't add any value.
Mis-Replicated containers are queued with a priority lower than decommissioning containers in this PR, so they do not block decommission from completing if they are ahead of it in the queue.
https://issues.apache.org/jira/browse/HDDS-7654
Added a unit test to prove the mis-rep container queues with a lower priority than decommission. Small changes to existing tests cover most of the rest of the changes.
Ideally we should have a …

HDDS-7654. EC: ReplicationManager - merge mis-rep queue into under replicated queue

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmMetrics.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMAllocateBlockRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java

To update failure metric `numBlockAllocationFails` when allocate block fails in preExecute
https://issues.apache.org/jira/browse/HDDS-7635
Unit test and manual test in docker.

HDDS-7635. Update failure metrics when allocate block fails in preExecute.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java

If an EC container is under-replicated somehow, and also has some maintenance indexes that do not need replicated, the logic calls the placement policy requesting zero nodes. The policy then throws an exception as it expects to have greater than zero nodes requested.
https://issues.apache.org/jira/browse/HDDS-7683
Unit test used to reproduce the issue and then a code change to fix the test.

HDDS-7683. EC: ReplicationManager - UnderRep maintenance handler should not request nodes if none needed

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestBlockManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestHealthyPipelineSafeModeRule.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestSCMSafeModeManager.java

While creating pipeline we are using time from java.util time package. During pipeline scrub we should use same java.util time package for correct comparison. So that pipeline which is in allocated state for long time can be removed.
https://issues.apache.org/jira/browse/HDDS-7463
Code has been built locally and manually tested.

HDDS-7463. SCM Pipeline scrubber never able to cleanup allocated pipeline.

---

hadoop-hdds/interface-admin/src/main/resources/proto.lock
hadoop-hdds/interface-client/src/main/resources/proto.lock
hadoop-hdds/interface-server/src/main/resources/proto.lock
hadoop-ozone/interface-client/src/main/resources/proto.lock

Ozone 1.3.0 had Announced Release.
[Just as what we did after 1.2 release](https://github.com/apache/ozone/pull/2865). We also need cherry-pick proto.lock form ozone-1.3 branch to master.
https://issues.apache.org/jira/browse/HDDS-7686
Normal build process which runs the proto-backwards-compatability check.

HDDS-7686. Cherry-pick proto.lock files change from ozone-1.3 release branch to master

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java

Change error message when DiskSpace quota of bucket is exceeded.
https://issues.apache.org/jira/browse/HDDS-7631
Manual test.
1. `mvn clean install -DskipTests -DskipShade`
2. `cd hadoop-ozone/dist/target/ozone-*/compose/ozone`
3. `docker-compose up -d --scale datanode=3`
4. `docker exec -it ozone_om_1 /bin/bash`
a. `ozone sh volume create /vol`
b. `ozone sh bucket create /vol/buc`
c. `ozone sh bucket setquota --space-quota 610929 /vol/buc`
d. `ozone fs -put README.md ofs://om/vol/buc/readme.md`

HDDS-7631. Log format error on quotas when exceeding the space quota

---

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/fsck/ContainerHealthTask.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/PipelineSyncTask.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconDeadNodeHandler.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStaleNodeHandler.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStorageContainerManagerFacade.java

Currently, the ContainerHealthTask runs in periodic intervals to check if a container is under replicated or missing. A small improvement by triggering a run of this task when a DN goes STALE or DEAD can help identify under replicated containers quicker.
Since StaleNodeHandler don't update container state or remove container replica from Recon cache on which ContainerHelathTask is dependent on identifying missing or unhealthy containers, so we should trigger PipelineSyncTask on StaleNodeHandler and ContainerHealthTask on DeadNodeHandler.
https://issues.apache.org/jira/browse/HDDS-5331
Existing test cases will cover the above scenario. So tested manually.

HDDS-5331. Recon: Trigger PipelineSyncTask when DN becomes stale and ContainerHealthTask when DN becomes dead.

---

hadoop-hdds/docs/themes/ozonedoc/layouts/partials/header.html

To help understand our users, I propose to embed Mamoto tracking code into Ozone web page. More details can be found at https://privacy.apache.org/matomo/
https://issues.apache.org/jira/browse/HDDS-7684
Manually verifies the rendered page issues request to the Matomo javascript resources. However, I am yet to see results on analytics.apache.org

HDDS-7684. Embed Matomo Web Analytics tracking code in docs.

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/PrometheusMetricsSink.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/http/TestPrometheusMetricsIntegration.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/http/TestPrometheusMetricsSink.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/server/http/TestPrometheusMetrics.java

For Prometheus, if a metric is unregistered and not pushed to the sink any more it will still exist in the map in `PrometheusMetricsSink` and it will be presented to the user. In this PR, we are storing all the metrics pushed to the sink to a second map which will be cleared every time we call `flush()`. This way, if a metric is stale and not pushed to the sink, it will not be presented to the user. This implementation is the same that was followed for hadoop in [this PR](https://github.com/apache/hadoop/pull/3369). The other issues described in the hadoop PR seem to have been previously resolved for ozone. 
This problem was uncovered and discussed here: https://github.com/apache/ozone/pull/3781#issuecomment-1306594864
https://issues.apache.org/jira/browse/HDDS-7576
This patch was tested …

HDDS-7576. Prometheus metrics do not remove stale metrics until restart

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/container/common/helpers/ExcludeList.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerSet.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisorScheduling.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestBlockManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestContainerPlacement.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockOutputStreamEntryPool.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconPipelineManager.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStorageContainerManagerFacade.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/AbstractReconContainerManagerTest.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/ClosedContainerReplicator.java

From the jira:
> Similar to [HDDS-7463](https://issues.apache.org/jira/browse/HDDS-7463), we are seeing that commands sent from SCM to the datanodes are being expired when they should not be. This is because we are getting the command deadline from MonotonicClock and then comparing that with the current time, also gotten from MonotonicClock on the datanodes.
As we discovered in [HDDS-7463](https://issues.apache.org/jira/browse/HDDS-7463), the "Time" monotonic clock uses is not system time, but some arbitrary reference point in the JVM. We cannot use the time from monotonic clock to compare times across JVM restarts, or in different JVMs.
For that reason, I believe it would be safer to replace any usages of Monotonic clock with java.util.SystemClock.
This PR replaces usages of …

HDDS-7692. Remove usage of MonotonicClock as default Clock used

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMDirectoryCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMDirectoryCreateRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileCreateRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/file/OMFileCreateResponseWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyCreateResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/OMRequestTestUtils.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/file/TestOMDirectoryCreateRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/file/TestOMDirectoryCreateRequestWithFSO.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/file/TestOMFileCreateRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/file/TestOMFileCreateRequestWithFSO.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCreateRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCreateRequestWithFSO.java

1. missing validation for namespace added
2. missing increment of namespace added where parent directory created (as missing)
3. Cache update for directory done after validation of quota
https://issues.apache.org/jira/browse/HDDS-7641
E2E perspective for additional scenario, this is tested

HDDS-7641. Namespace quota validation is not present in multiple places

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientMultipartUploadWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3InitiateMultipartUploadRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3InitiateMultipartUploadResponseWithFSO.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartUploadCompleteRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartUploadCompleteRequestWithFSO.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3MultipartResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3MultipartUploadAbortResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3MultipartUploadAbortResponseWithFSO.java

S3 multipart upload for FSO type creates a directory if missing for a parent. But the corresponding namespace addition is not recorded.
Validation and namespace quota updated for missing parent directory that got created.
https://issues.apache.org/jira/browse/HDDS-7644
Tested using unit test for namespace quota

HDDS-7644. S3 multipart upload does not update quota namespace for missing parents

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

When we add a new OM node right after decommissioning, the OM process on the new node gets terminated immediately on the restart. The new OM node is unable to join the ratis ring. 
This is because OM applies all the previous transactions which also includes the transaction to decommission(removal of a node from peer list) which causes termination of the newly added OM process node.
The assumption here is that the OM node id of the newly added node is the same as that of the decommissioned node.
https://issues.apache.org/jira/browse/HDDS-7584
Tested Manually

HDDS-7584. Addition of new OM node expels itself from the Ratis ring after restart

---

.github/workflows/ci.yml
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java

Fix error when compiling Ozone for target Java version 11:
```
$ mvn -Djavac.version=11 -DskipTests clean package
...
[ERROR] hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java:[74,19] package com.sun.jmx.mbeanserver is not visible
[ERROR]   (package com.sun.jmx.mbeanserver is declared in module java.management, which does not export it)
```
Change _compile_ CI check so that it, in addition to using JDK of the specified version, also targets the same Java version.  This way we can catch such errors in CI.
https://issues.apache.org/jira/browse/HDDS-7633
```
$ mvn -Djavac.version=11 -DskipTests clean package
...
[INFO] BUILD SUCCESS
```
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3687864892/jobs/6242414957

HDDS-7633. Compile error with Java 11: package com.sun.jmx.mbeanserver is not visible

---

hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/audit/AuditLogTestUtils.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmAcls.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/utils/AuditLogUtils.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

adding log entries to OM audit log in case a request is prohibited by ACL policies. Also, a way of testing audit logs is added along with integration tests (see AuditLogUtils.class).
https://issues.apache.org/jira/browse/HDDS-7716
* local unit tests run, 
* integration tests were added,
* deployed modified jars to dev server to ensure that log entries have been added

HDDS-7716. Add ACL errors to OM audit logs for read requests

---

hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdb/util/RdbUtil.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyLocationInfoGroup.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/snapshot/SnapshotDiffReport.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmKeyInfo.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java

Fix issue which shows key as modified
```java
bash-4.2$ ozone sh volume create vol1
bash-4.2$ ozone sh bucket create vol1/buck1
bash-4.2$ ozone sh key put vol1/buck1/key1
bash-4.2$ ozone sh snapshot create vol1/buck1 snap1
bash-4.2$ ozone sh snapshot create vol1/buck1 snap2
bash-4.2$ ozone sh snapshot snapshotDiff vol1/buck1 snap1 snap2
Difference between snapshot snap1 and snapshot snap2:
M key1
```
Also fixed snapdiff for FSO buckets
https://issues.apache.org/jira/browse/HDDS-7607
Added Basic Snapdiff unit tests

HDDS-7607. [Snapshot] SnapshotDiff command lists unmodified file as modified

---

hadoop-ozone/dist/src/main/compose/ozone-om-ha/docker-compose.yaml

`ozone-om-ha` uses a temporary Docker image based on top of the regular `ozone-runner` images.
HDDS-6293 added support for custom `ozone-runner` image, but the change had a bug: `OZONE_RUNNER_IMAGE` variable was not passed to the Docker build context in `ozone-om-ha`.  This was not noticed as this test is disabled due to flakiness.
Compare to `ozonescripts` environment, which also uses its own derived image.
https://issues.apache.org/jira/browse/HDDS-7714
```
$ cd hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/ozone-om-ha
$ docker-compose up -d
Building datanode
Sending build context to Docker daemon  29.18kB
Step 1/23 : ARG OZONE_RUNNER_IMAGE
Step 2/23 : ARG OZONE_RUNNER_VERSION
Step 3/23 : FROM ${OZONE_RUNNER_IMAGE}:${OZONE_RUNNER_VERSION}
---> 2f81b649e1b7
Step 4/23 : RUN sudo …
```

HDDS-7714. Docker cluster ozone-om-ha fails during docker-compose up

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/MisReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisMisReplicationHandler.java

MisReplicationHandler#filterSources gets a Set of replicas that can be used to fix mis replication. It selects CLOSED replicas:
```
private Set<ContainerReplica> filterSources(Set<ContainerReplica> replicas) {
return replicas.stream().filter(r -> r
.getState() == StorageContainerDatanodeProtocolProtos
.ContainerReplicaProto.State.CLOSED)
.filter(r -> ReplicationManager
.getNodeStatus(r.getDatanodeDetails(), nodeManager)
.isHealthy())
.filter(r -> r.getDatanodeDetails().getPersistedOpState()
== HddsProtos.NodeOperationalState.IN_SERVICE)
.collect(Collectors.toSet());
}
```
When thinking about Ratis Containers, QUASI_CLOSED replicas can also be mis replicated. They're also allowed to be replicated to datanodes so we should allow them as sources too. …

HDDS-7696. MisReplicationHandler does not consider QUASI_CLOSED replicas as sources

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerHealthResult.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerReplicaCount.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECContainerReplicaCount.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisContainerReplicaCount.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/ECReplicationCheckHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeAdminMonitorImpl.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECContainerReplicaCount.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestECReplicationCheckHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/DatanodeAdminMonitorTestUtil.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestDatanodeAdminMonitor.java

In EC, a container is considered missing and under replicated if it has lost enough replicas that offline reconstruction is not possible. If any of the remaining replicas for this container are on a datanode that is being decommissioned, the decommissioning will not proceed. All the containers on that node must be restored to proper replication for it to finish decommissioning, but the code will not copy the replica of the missing container to a different node.
There are 3 parts to fixing this problem:
In DatanodeAdminMonitorImpl, inside the method checkContainersReplicatedOnNode, we use a call to ECContainerReplicaCount.isSufficientlyReplicated() to decide if the container is replicated ok or not. Even if we address 1 and 2 above, this is still a problem, as the container is …

HDDS-7666. EC: Unrecoverable EC containers with some remaining replicas may block decommissioning

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java

Register `DatanodeCommandCountUpdatedHandler` for `DATANODE_COMMAND_COUNT_UPDATED` events.
https://issues.apache.org/jira/browse/HDDS-7727
`No event handler registered for event ... 'Datanode_Command_Queue_Updated'` no longer appears in logs.
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3848900393

HDDS-7727. EC: SCM unregistered event handler for DatanodeCommandCountUpdated

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineStateMap.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java

SCM should allow adding a container to a CLOSED pipeline as a pipeline state can be changed while the container creating transaction is waiting to be processed by SCM.
https://issues.apache.org/jira/browse/HDDS-7738
Unit tests.
Standard CI: https://github.com/duongkame/ozone/actions/runs/3857497185/jobs/6574962174

HDDS-7738. SCM terminates when adding container to a closed pipeline

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECContainerReplicaCount.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECContainerReplicaCount.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestECReplicationCheckHandler.java

In ECContainerReplicaCount, we intentionally ignore UNHEALTHY replicas so that when we check for over or under replication, it is if the replicas are not there.
However if there is a pending delete for an unhealthy replica, due to ignoring the unhealthy replicas, the pending delete decrements the healthy count and makes the container appear under replicated when it is not.
When processing pending deletes, we need also ignore any that are removing the ignored unhealthy replicas.
https://issues.apache.org/jira/browse/HDDS-7729
Unit test added to reproduce the issue and confirm it is fixed after the fix.

HDDS-7729. EC: ECContainerReplicaCount should handle pending delete of unhealthy replicas

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerReplicaPendingOps.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManagerMetrics.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestContainerReplicaPendingOps.java

```
"EcReplicationCmdsSentTotal" : 0,
"EcDeletionCmdsSentTotal" : 259,
"EcReplicationCmdsCompletedTotal" : 51,
"EcDeletionCmdsCompletedTotal" : 51,
"EcReconstructionCmdsSentTotal" : 571,
"EcReplicationCmdsTimeoutTotal" : 765,
"EcDeletionCmdsTimeoutTotal" : 204
```
Total replication commands sent are 0, while timed out are 765.
I think the code is working as intended, but it is confusing.
We have a metric for "EcReplicationCmdsSentTotal" and EcReconstructionCmdsSentTotal. However on completion or timeout we only have a metric EcReplicationCmdsCompletedTotal and EcReplicationCmdsTimeoutTotal - we don't have a reconstruction completed / timeout. This is because we track completion in ContainerReplicaPendingOps, and all it sees is a replica that has been scheduled to be created. It doesn't …

HDDS-7695. EC metrics related to replication commands don't add up

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/protocol/DatanodeDetails.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/CloseContainerCommand.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/DeleteContainerCommand.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/ReconstructECContainersCommand.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/ReplicateContainerCommand.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java

Replication Manager writes an info log each time it sends a command to a datanode, but aside from the command name, it doesn't contain any further information about the command. This change is to log more details about the command being sent which may aid debugging issues in the future.
Example new messages after this change:
```
2023-01-06 17:23:06,080 [main] INFO  replication.ReplicationManager (ReplicationManager.java:sendDatanodeCommand(426)) - Sending command [replicateContainerCommand: containerId: 1, replicaIndex: 1, sourceNodes: [localhost-143.110.182.62/143.110.182.62, localhost-243.150.55.19/243.150.55.19]] for container ContainerInfo{id=#1, state=CLOSED, pipelineID=PipelineID=bdd96da4-f447-45d4-9331-62480e7bf224, stateEnterTime=1970-01-01T00:00:00Z, owner=Ozone} to …
```

HDDS-7739. EC: Increase the information in the RM sending command log message

---

hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java

This is a follow-up to [HDDS-7466](https://issues.apache.org/jira/browse/HDDS-7466).
Currently [HDDS-7466](https://issues.apache.org/jira/browse/HDDS-7466) is not being passed in the "filtered" SST list result from compaction DAG output.
The original jira HDDS-7466 does not have UTs. Some test are being added in [HDDS-7607](https://issues.apache.org/jira/browse/HDDS-7607). More tests to come in [HDDS-7467](https://issues.apache.org/jira/browse/HDDS-7467).
https://issues.apache.org/jira/browse/HDDS-7690

HDDS-7690. [Snapshot] Use SST file list output from compaction DAG as SnapshotDiff input

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/PlacementPolicy.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/SCMCommonPlacementPolicy.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/TestSCMCommonPlacementPolicy.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestContainerPlacementFactory.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/fsck/TestContainerHealthTask.java

Placement Policy Interface changes to handle Overreplication changes
https://issues.apache.org/jira/browse/HDDS-7560
Unit test

HDDS-7560. Placement Policy Interface changes to handle Overreplication

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerDoubleBuffer.java

When OzoneManagerDoubleBuffer fails due to exception, it's better to have detailed information of the OMResponse for debugging.
https://issues.apache.org/jira/browse/HDDS-7630
no test.
Some example outputs:
* Create bucket
```
cmdType: CreateBucket
traceID: ""
success: true
status: OK
createBucketResponse {
}
```
* Create key
```
cmdType: CreateKey
traceID: ""
success: true
status: OK
createKeyResponse {
keyInfo {
volumeName: "vol1"
bucketName: "bucket1"
keyName: "key1"
dataSize: 3879
type: RATIS
factor: THREE
keyLocationList {
version: 0
keyLocations {
blockID {
containerBlockID {
containerID: 1
localID: 109611004723200001
}
blockCommitSequenceId: 0
}
offset: 0
length: 268435456
createVersion: 0
pipeline {
members {
uuid: "c6d47952-d622-4723-b28b-a6ff48fc1fe0"
ipAddress: "172.21.0.8" …
```

HDDS-7630. Show detailed OMResponse when OzoneManagerDoubleBuffer terminates

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OMAdminProtocolPB.java

Replaced OMAdminProtocolPB protocolName with a proper class name. The existing one does not exist and leads to "Unknown protocol" error, which does not allow to add a new OM to the existing cluster.
https://issues.apache.org/jira/browse/HDDS-7705
Manually tested, with the fix a new OM is able to join the existing cluster.

HDDS-7705. Fix OM Bootstrap request

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/protocol/DatanodeDetails.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCommandInfo.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/ReconstructECContainersCommand.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/ReplicateContainerCommand.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java

`DatanodeDetails#toString` outputs too much detail for it to be usable in each and every log message related to datanodes.  Thus log statements currently have to build their own output (e.g. for list of hosts, etc.), leading to duplication.
This PR replaces `toString` with less verbose implementation, but keeps the current one for occasional usage as `toDebugString`.
https://issues.apache.org/jira/browse/HDDS-7753
Checked for log messages in `TestECContainerRecovery` output.
```
... [Under Replicated Processor] INFO  replication.ReplicationManager (ReplicationManager.java:sendDatanodeCommand(426)) - Sending command [reconstructECContainersCommand: containerID: 1, replicationConfig: EC/ECReplicationConfig{data=3, parity=2, ecChunkSize=1024, codec=rs}, sources: …
```

HDDS-7753. Simplify DatanodeDetails#toString to improve log messages

---

hadoop-ozone/dist/pom.xml
hadoop-ozone/dist/src/main/compose/ozone-ha/docker-compose.yaml
hadoop-ozone/dist/src/main/compose/ozone-ha/test.sh
hadoop-ozone/dist/src/main/compose/ozone/docker-compose.yaml
hadoop-ozone/dist/src/main/compose/ozone/test.sh
hadoop-ozone/dist/src/main/compose/ozonesecure-ha/docker-compose.yaml
hadoop-ozone/dist/src/main/compose/ozonesecure-ha/docker-config
hadoop-ozone/dist/src/main/compose/ozonesecure-ha/test.sh
hadoop-ozone/dist/src/main/compose/ozonesecure/docker-compose.yaml
hadoop-ozone/dist/src/main/compose/ozonesecure/docker-config
hadoop-ozone/dist/src/main/compose/ozonesecure/test.sh
hadoop-ozone/dist/src/main/smoketest/httpfs/operations_tests.robot

In this change I fixed the Kerberos setup for the HttpFS tests in secure environment and also added them back to the `test.sh`, as after the master merge there were some changes that broke them. I added the new ozone-runner image to the `ozone-dist/pom.xml`, which has `httpfs` as a user and group. 
https://issues.apache.org/jira/browse/HDDS-7719
Run the tests locally
Also waited the CI on my fork: https://github.com/dombizita/ozone/actions/runs/3854740738/jobs/6569223329 (only the flaky integration tests failed, not relevant with my change)

HDDS-7719. [HTTPFSGW] Fix secure integration tests for the HttpFS module

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerConfiguration.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMStorage.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOMStorage.java

OM uses its NodeID to generate the RaftPeerId. As such, the OM NodeId should be immutable. This Jira proposes to add the OM NodeId to its VERSION file. On restarts, the OM NodeID should be compared with the nodeId in the VERSION file to verify that it has not been updated.
https://issues.apache.org/jira/browse/HDDS-5934
Added unit test

HDDS-5934. Add OM NodeID to VERSION file.

---

hadoop-ozone/dist/src/main/smoketest/createbucketenv.robot
hadoop-ozone/dist/src/main/smoketest/createmrenv.robot
hadoop-ozone/dist/src/main/smoketest/debug/ozone-debug-tests.robot
hadoop-ozone/dist/src/main/smoketest/gdpr/gdpr.robot
hadoop-ozone/dist/src/main/smoketest/ozonefs/setup.robot
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketSetPropertyRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/OMVolumeSetQuotaRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestOMBucketCreateRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestOMBucketSetPropertyRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/file/TestOMFileCreateRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMAllocateBlockRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCommitRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCreateRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/volume/TestOMVolumeSetQuotaRequest.java

1. Revert changes HDDS-7652 as its mandatory that all bucket space quota is set if volume quota is set
2. Added check for volume when have set space quota, all bucket must have set space quota
3. Also check when bucket is created, its space quota must be present when volume space quota set
[HDDS-7751](https://issues.apache.org/jira/browse/HDDS-7751)
Patch is tested with UT and E2E scenario

HDDS-7751. Volume quota must have all bucket quota set

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/ClosedWithUnhealthyReplicasHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/DeletingContainerHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/EmptyContainerHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestClosedWithUnhealthyReplicasHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestDeletingContainerHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestEmptyContainerHandler.java

An unhealthy non empty replica won't be deleted from a datanode unless the force flag is set. We need to force delete unhealthy replicas of an EC container when it's sufficiently replicated. This PR sets the force flag in `ClosedWithUnhealthyReplicasHandler`.
https://issues.apache.org/jira/browse/HDDS-7775
Changed existing UTs.
Passed CI run in my fork: https://github.com/siddhantsangwan/ozone/actions/runs/3902132448

HDDS-7775. EC: Exception encountered while deleting UNHEALTHY replica in Datanode

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/AbstractOverReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECOverReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationTestUtil.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECOverReplicationHandler.java

In HDDS-7560, we added the method `placementPolicy.replicasToRemoveToFixOverreplication()` to select replicas to remove when a container is over replicated. This PR is to change the EC Over replication Handler to use that new method, and remove the existing logic from the handler class.
https://issues.apache.org/jira/browse/HDDS-7761
Added new unit tests and modified some existing tests

HDDS-7761. EC: ReplicationManager - Use placementPolicy.replicasToRemoveToFixOverreplication in EC Over replication handler

---

hadoop-hdds/docs/content/design/trash.md

Update outdated trash documentation.
[HDDS-3982. Disable moveToTrash in o3fs and ofs temporarily](https://github.com/apache/ozone/pull/1215) introduced the modified content, [HDDS-4307.Start Trash Emptier in Ozone Manager #1507](https://github.com/apache/ozone/pull/1507) supported this function, but did not update the document, it is easy to misunderstand new users.
https://issues.apache.org/jira/browse/HDDS-7774
no need test

HDDS-7774. Update outdated trash documentation

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequestWithFSO.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCommitRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCommitRequestWithFSO.java

Fix incorrect use of openKeyTable/openFileTable, where key/file name, instead of open key/file name is used.
[HDDS-7722](https://issues.apache.org/jira/browse/HDDS-7722)

HDDS-7722. FSO buckets fail to invalidate open file table cache when committing a key

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerCheck.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerData.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerMetadataInspector.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/KeyValueContainerUtil.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingService.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestSchemaOneBackwardsCompatibility.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestSchemaTwoBackwardsCompatibility.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerIntegrityChecks.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerMetadataInspector.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestContainerReader.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainer.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManagerHelper.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestFailureHandlingByClient.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestValidateBCSIDOnRestart.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java

The current function names to get metadata keys in KeyValueContainerData might be confusing to users, this ticket is to update the names for better readability.
https://issues.apache.org/jira/browse/HDDS-7441
Only update function names, no need to add tests.

HDDS-7441. Rename function names of retrieving metadata keys

---

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/OMDBUpdatesHandler.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestOMDBUpdatesHandler.java

This JIRA is a bug in code while updating OM DB snapshots in Recon where framework for applying DB updates assumes storing OM DB updates in a event map with table keyType as "String" and while doing codec deserializing and type casting for DTOKENTABLE, it throws ClassCastException because for DTOKENTABLE, table key type is of "OzoneTokenIdentifier" class instead of String. 
**_Patch Fix:_**
This patch is fixed by skipping any updates or syncing of table DTOKENTABLE in Recon because Recon don't use this table for any use case as of now. If in future , DTOKENTABLE table data is needed, all events for this table updates will be saved using Object as key and new task will also retrieve using Object as key.
https://issues.apache.org/jira/browse/HDDS-7455
This patch was tested manually by …

HDDS-7455. ClassCastException: OzoneTokenIdentifier cannot be cast to String

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/GrpcReplicationClient.java

HDDS-7572 changed `ReplicationServer` (among others) to respect `hdds.grpc.tls.enabled`, but `GrpcReplicationClient` was left unchanged.  Thus protocol mismatch prevents replication when the following config is set:
* `ozone.security.enabled=true`
* `hdds.grpc.tls.enabled=false`
```
ERROR org.apache.hadoop.ozone.container.replication.GrpcReplicationClient: Download of container 1 was unsuccessful
org.apache.ratis.thirdparty.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
at org.apache.ratis.thirdparty.io.grpc.Status.asRuntimeException(Status.java:535)
...
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: …
```

HDDS-7754. Download of container is failing with SSL/TLS error during re-replication

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/ECFileChecksumHelper.java

When calculating a checksum for an EC file with Rack Topology enabled, you can get the following error intermittently:
```
ERROR : Failed with exception null
java.lang.IndexOutOfBoundsException
at java.nio.ByteBuffer.wrap(ByteBuffer.java:375)
at org.apache.hadoop.ozone.client.checksum.ECBlockChecksumComputer.computeCompositeCrc(ECBlockChecksumComputer.java:163)
at org.apache.hadoop.ozone.client.checksum.ECBlockChecksumComputer.compute(ECBlockChecksumComputer.java:65)
at org.apache.hadoop.ozone.client.checksum.ECFileChecksumHelper.getBlockChecksumFromChunkChecksums(ECFileChecksumHelper.java:148)
at org.apache.hadoop.ozone.client.checksum.ECFileChecksumHelper.checksumBlock(ECFileChecksumHelper.java:106)
at org.apache.hadoop.ozone.client.checksum.ECFileChecksumHelper.checksumBlocks(ECFileChec …
```

HDDS-7787. GetChecksum for EC files can fail intermittently with IndexOutOfBounds exception

---

pom.xml

Upgrade Netty to 4.1.86 and gRPC to 1.51.1 (same as in RATIS-1760).
https://issues.apache.org/jira/browse/HDDS-7718
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3828414627

HDDS-7718. Bump Netty to 4.1.86 and gRPC to 1.51.1

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisOverReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisOverReplicationHandler.java

As a stale DN is more than likely dead, in the RatisOverReplicationHandler we should exclude stale replicas before checking for over-replication. That way, we will not allow stale replicas to count toward over-replication. If we continue consider a stale replica as "present" for over-replication, we may remove another replica and then the stale one could go dead and get removed too, resulting in under replication.
https://issues.apache.org/jira/browse/HDDS-7788
New unit test added.

HDDS-7788. Ratis OverReplicationHandler should exclude stale replicas

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsSnapshot.java

Add UTs for fs createSnapshot - `TestOzoneFsSnapshot`
Testcases :
```
- testCreateSnapshotDuplicateName
- testCreateSnapshotInvalidName
- testCreateSnapshotOnlyNumericName
- testCreateSnapshotInvalidURI
- testCreateSnapshotNameLength
- testCreateSnapshotParameterMissing
```
https://issues.apache.org/jira/browse/HDDS-7702 
Testcase file - `hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsSnapshot.java`
```
mvn -Dtest=TestOzoneFsSnapshot test
[INFO] Running org.apache.hadoop.fs.ozone.TestOzoneFsSnapshot
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 42.015 s - in …
```

HDDS-7702. [snapshot] Add unit-testcases for Ozone fs createSnapshot

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3InitiateMultipartUploadResponseWithFSO.java

Rename `addToOpenFileTable()` to `addToOpenFileTableForMultipart`.
https://issues.apache.org/jira/browse/HDDS-7748
No new test needed.

HDDS-7748. Rename OMFileRequest.addToOpenFileTable() to avoid misuse.

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/IOmMetadataReader.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMetrics.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataReader.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataReaderMetrics.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshot.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotMetrics.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/recovery/ReconOmMetadataManagerImpl.java

Merge from master was incomplete in that it did not move the new getKeyInfo() method from OzoneManager to the OmMetadataReader,( and OmMetadataReaderMetrics).
This PR rectifies that.
It also modifies the OmMetadataManagerImpl to not use the unneeded tableCacheMetrics on snapshots.  (These metrics were added by the merge and are not used by snapshots.)
https://issues.apache.org/jira/browse/HDDS-7765
Tested against the acceptance test for this PR: https://github.com/apache/ozone/pull/4134

HDDS-7765. [Snapshot] Handle OzoneManager#getKeyInfo with OmMetadataReader.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyRatisContainerReplicaCount.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisContainerReplicaCount.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisContainerReplicaCount.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisOverReplicationHandler.java

- Replicas with UNHEALTHY state will not count toward sufficient replication.
- A new constructor in RatisContainerReplicaCount that takes a list of ContainerReplicaOp. This is needed to ignore pending deletes on UNHEALTHY replicas.
- Ensure Legacy RM is not affected.
- New UTs.
- This breaks the ratis flow in the new RM, which is still WIP. Disabled a UT for now. It will be fixed when the rest of the tasks are in: https://issues.apache.org/jira/browse/HDDS-7785
- There is a discrepancy in the meaning of healthy replicas bw RatisContainerReplicaCount#isHealthy and getHealthyReplicaCount. This should be clear when the rest of the jiras are in.
Check the jira for a detailed description.
https://issues.apache.org/jira/browse/HDDS-7785
New UTs
CI run in my fork: …

HDDS-7804. UNHEALTHY replicas will not contribute to sufficient replication in RatisContainerReplicaCount

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneListStatusHelper.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/lock/OBSKeyPathLockStrategy.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/lock/RegularBucketLockStrategy.java

There occur some possibilities that acquired locks are not released due to exceptions. This change corrects them so that locks are always released theoretically.  
https://issues.apache.org/jira/browse/HDDS-7755
Standard CI. https://github.com/duongkame/ozone/actions/runs/3954812858

HDDS-7755. Ensure that acquired locks are always released.

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/TarContainerPacker.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestTarContainerPacker.java
hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/SpyInputStream.java
hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/SpyOutputStream.java

`TarContainerPacker` closes the underlying `GrpcOutputStream` multiple times:
```
datanode_1  | java.lang.IllegalStateException: call already closed
datanode_1  | 	at org.apache.ratis.thirdparty.com.google.common.base.Preconditions.checkState(Preconditions.java:502)
datanode_1  | 	at org.apache.ratis.thirdparty.io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:218)
datanode_1  | 	at org.apache.ratis.thirdparty.io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:211)
datanode_1  | 	at org.apache.ratis.thirdparty.io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:395)
datanode_1  | 	at org.apache.hadoop.ozone.container.replication.GrpcOutputStream.close(GrpcOutputStream.java:106)
datanode_1  | 	at …
```

HDDS-7807. TarContainerPacker closes streams multiple times

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmMetrics.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMetrics.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotCreateRequest.java

This PR is adding more snapshot metrics in `OMMetrics` to keep track of the count of each snapshot status. 
Right now there is no implementation for snapshot delete or reclaim and therefore these metrics are not getting a value anywhere in the code. 
We are going over the snapshot table on OM `start()`, `restart()` and `reloadOMState()` and get a count for every snapshot status. Also we are incrementing the number of active snapshots during every create request. In the future we might want to decrement the number of active when incrementing the number of delete and similarly decrement number of delete when incrementing number of reclaimed.
I've checked the snapshot metrics from HDFS and couldn't find something applicable here that's missing.
https://issues.apache.org/jira/browse/HDDS-7506 …

HDDS-7506. [Snapshot] Expose more snapshot metrics under OMMetrics

---

hadoop-ozone/dist/src/main/smoketest/security/ozone-secure-tenant.robot
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

This is a regression from the GetKeyInfo implementation ([HDDS-7230](https://issues.apache.org/jira/browse/HDDS-7230)). When called in the context of tenant volume, OM fails to resolve the correct tenant volume and instead uses the default `s3v` volume. This result in a "Bucket not found" error.
https://issues.apache.org/jira/browse/HDDS-7801
Robot test.

HDDS-7801. Bucket not found when calling getKeyInfo with tenant context

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java

Add UTs for SnapshotDiff - `TestOmSnapshot`
```
- testSnapDiffNoSnapshot
- testSnapDiffNonExistentUrl
- testSnapDiffMissingMandatoryParams
```
https://issues.apache.org/jira/browse/HDDS-7704
Testcase file - `hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java`
```
mvn -Dtest=TestOmSnapshot#testSnapDiff* test
[INFO] Running org.apache.hadoop.ozone.om.TestOmSnapshot
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 168.426 s - in org.apache.hadoop.ozone.om.TestOmSnapshot
[INFO]
[INFO]
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0
[INFO]
```

HDDS-7779. [snapshot] Add unit-testcases for Ozone SnapshotDiff

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/MismatchedReplicasHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestMismatchedReplicasHandler.java

Mismatched replicas are replicas which don't match the container state. Such as CLOSING or OPEN replicas for CLOSED or QUASI_CLOSED containers. UNHEALTHY replicas also don't match the container's state, but the distinction is that we cannot close these replicas today. Hence these are uniquely considered as unhealthy replicas.
ClosedWithMismatchedReplicasHandler already handles CLOSED containers. This jira proposes handling QUASI_CLOSED along with CLOSED in that handler.
https://issues.apache.org/jira/browse/HDDS-7813
Added a new UT

HDDS-7813. Handle Mismatched Replicas (OPEN or CLOSING) of QUASI-CLOSED containers in RM

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainer.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerCheck.java

1. Add log for the exception object when container corruption happens to better identify the failure.
2. Remove the stack trace of the call to KeyValueContainer#markContainerUnhealthy (not very useful).
https://issues.apache.org/jira/browse/HDDS-7097
Manually test in local cluster to verify the log message.
Example message format:
`ERROR keyvalue.KeyValueContainerCheck: Marking Container [{containerID}] UNHEALTHY as it failed metadata check. Exception: {exception stack trace}`

HDDS-7097. Container scanner log output lacks useful information

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/TarContainerPacker.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestTarContainerPacker.java

`DownloadAndImportReplicator` extracts container descriptor (`container.yaml`) as a first step when importing the container.
> A tar file isn't really indexed, and it doesn't have a "directory listing" section to list the files in it, it skips from one file header to the next seeking down the file. So if this file is always at the end, it must check all other file headers in the archive first.
Currently the descriptor is stored at the end of the tarball, so the import process needs to read the entire tarball twice.
This change moves the descriptor to the start of the archive.
https://issues.apache.org/jira/browse/HDDS-7820
Added an assertion about position of the descriptor.
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3988198928

HDDS-7820. Store container descriptor at start of tar archive

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java

Normalize logStreamError so that EC write errors are logged at WARN level all the time, not just when logging at DEBUG level.

HDDS-7825. Warn when EC write exception occurs

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/ReplicateContainerCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinatorTask.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/AbstractReplicationTask.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/DownloadAndImportReplicator.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/MeasuredReplicator.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/PushReplicator.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisor.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisorMetrics.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationTask.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisorScheduling.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestMeasuredReplicator.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestReplicationSupervisor.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/ClosedContainerReplicator.java

A refactor or the existing ReplicationSupervisor so we can have the same supervisor (and threadpool) manage both Replication and EC Reconstruction tasks.
This change does not include moving the EC tasks into the ReplicationSupervisor - that will be done in another PR as this one is already large enough with this change.
This change makes ReplicationSupervisor accept AbstractReplicationTask's rather than a ReplicationTask, so we can have a version for EC Reconstruction and Ratis.
This results in the ReplicationTask having a `runTask()` method so it contains the knowledge of how to run itself and the supervisor can simply check the state. The choice of Replicator (push or download) is decided in the ReplicateContainerCommandHandler and a reference to the correct replicator is stored in the …

HDDS-7833. EC: Refactor ReplicationSupervisor to allow Replication and ECReconstruction tasks

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/AbstractOverReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECOverReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/MisReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/OverReplicatedProcessor.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisOverReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnderReplicatedProcessor.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnhealthyReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnhealthyReplicationProcessor.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECOverReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestMisReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestOverReplicatedProcessor.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisOverReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestUnderReplicatedProcessor.java

`RatisUnderReplicationHandler` needs to create more than one command per datanode for push replication if there are fewer sources than targets (e.g. if only one out of three replicas is available).
This PR changes the `UnhealthyReplicationHandler` interface to allow this.
https://issues.apache.org/jira/browse/HDDS-7822
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3996840932

HDDS-7822. Allow multiple commands per datanode in UnhealthyReplicationHandler

---

hadoop-hdds/client/src/test/java/org/apache/hadoop/ozone/client/io/ECStreamTestUtil.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECContainerReplicaCount.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyReplicationManager.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java

Streams are overkill for simple list/set conversion, when no filtering/transformation is applied.  These can be replaced with a simple constructor call.
https://issues.apache.org/jira/browse/HDDS-7834
No functional change, so existing tests cover it.
https://github.com/adoroszlai/hadoop-ozone/actions/runs/3999006508

HDDS-7834. Remove unnecessary streams

---

hadoop-ozone/dist/src/main/license/jar-report.txt
hadoop-ozone/httpfsgateway/pom.xml

Cleaning up dependencies that were added previously and are not used by the HttpFS module. 
https://issues.apache.org/jira/browse/HDDS-7737
Built it successfully locally, also run the `dependency.sh` and the HttpFS related robot tests.

HDDS-7737. [HTTPFSGW] Clean up dependencies

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneSnapshotRestore.java

Add UTs for Snapshot Restore - `TestOzoneSnapshotRestore`
```
- testRestoreSnapshot
- testRestoreSnapshotDifferentBucket
- testRestoreSnapshotDifferentBucketLayout
```
https://issues.apache.org/jira/browse/HDDS-7704
Testcase file - `hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneSnapshotRestore.java`
```
mvn -Dtest=TestOzoneSnapshotRestore test
[INFO] Running org.apache.hadoop.ozone.om.snapshot.TestOzoneSnapshotRestore
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 265.872 s - in org.apache.hadoop.ozone.om.snapshot.TestOzoneSnapshotRestore
[INFO]
[INFO]
[INFO] Tests …
```

HDDS-7704. [snapshot] Add unit-testcases for snapshot restore

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsSnapshot.java

Add unit-testcases for fs delete of bucket havng snapshots - `TestOzoneFsSnapshot#testDeleteBucketWithSnapshot`
https://issues.apache.org/jira/browse/HDDS-7819
Testcase file - `hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsSnapshot.java`
```
mvn -Dtest=TestOzoneFsSnapshot#testDeleteBucketWithSnapshot test
[INFO] Running org.apache.hadoop.fs.ozone.TestOzoneFsSnapshot
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 54.886 s - in org.apache.hadoop.fs.ozone.TestOzoneFsSnapshot
[INFO]
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
```

HDDS-7819. [snapshot] Add unit-testcases for fs delete of bucket havng snapshots

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java

Fix intermittent failure in `TestReplicationManager#testUnderReplicationQueuePopulated`.  Unexpected results were caused by concurrent processing of the replication queue in background threads.  The unit test assumes deterministic results after explicit `processAll` calls.  The patch disables those threads for the unit test.
https://issues.apache.org/jira/browse/HDDS-7808
Reproduced the problem without the fix in 5 out of 1000 repetitions:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4016532071/jobs/6899876966#step:5:750
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4016532071/jobs/6899875959#step:5:750
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4016532071/jobs/6899876132#step:5:750
With the fix, the failure has not happened in any of the 1000 …

HDDS-7808. Intermittent failure in TestReplicationManager#testUnderReplicationQueuePopulated

---

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestPushReplicator.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestSendContainerOutputStream.java

Add unit test for `SendContainerOutputStream` and `PushReplicator`.
https://issues.apache.org/jira/browse/HDDS-7806
```
[INFO] Running org.apache.hadoop.ozone.container.replication.TestSendContainerOutputStream
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.324 s - in org.apache.hadoop.ozone.container.replication.TestSendContainerOutputStream
[INFO] Running org.apache.hadoop.ozone.container.replication.TestPushReplicator
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.346 s - in org.apache.hadoop.ozone.container.replication.TestPushReplicator
```

HDDS-7806. Add unit tests for push replication

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/IOUtils.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/MeasuredReplicator.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/PushReplicator.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestMeasuredReplicator.java

Reuse existing `MeasuredReplicator` wrapper to register metrics for push replication, too.
https://issues.apache.org/jira/browse/HDDS-7778
Ran replication test (copied from `ozonesecure`) in `ozone` compose environment:
```
start_docker_env 3
execute_robot_test scm basic/basic.robot
execute_robot_test scm admincli/container.robot
docker-compose up -d --scale datanode=2
execute_robot_test scm -v container:1 -v count:2 replication/wait.robot
docker-compose up -d --scale datanode=3
execute_robot_test scm -v container:1 -v count:3 replication/wait.robot
```
Datanode log:
```
[ContainerReplicationThread-0] INFO replication.GrpcOutputStream: Sent 30208 bytes for container 1
```
Verified metrics via JMX:
```
{
"name" : "Hadoop:service=HddsDatanode,name=ContainerReplicator/push",
"modelerType" : …
```

HDDS-7778. Add metrics for push replication

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/AbstractReplicationTask.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisor.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationTask.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/ReplicateContainerCommand.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestReplicationSupervisor.java
hadoop-hdds/interface-server/src/main/proto/ScmServerDatanodeHeartbeatProtocol.proto

In order to allow replication commands intended to fix under and mis-replication to run with higher priority that replication commands related to the balancer, we will change the replication supervisor to be a priority queue, ordered by priority, enqueue time.
Commands sent from the balancer will have a low priority, other commands will a normal priority. The default will be NORMAL. This means that balancer commands will not run while there are other replication commands present in the queue.
This means it is not important if the balancer adds a lot of replication commands to the queue and then some nodes go down in the cluster. The replication commands related to the down nodes will automatically get to the front of the queue.
Note that LOW priority tasks are not counted in the command …

HDDS-7844. EC: Add normal and low priority to replication supervisor and commands

---

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestPushReplicator.java

Fix timeout in `TestPushReplicator`:
```
"main" 
java.lang.Thread.State: WAITING
at sun.misc.Unsafe.park(Native Method)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1707)
at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1742)
at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
at org.apache.hadoop.ozone.container.replication.PushReplicator.replicate(PushReplicator.java:62)
at org.apache.hadoop.ozone.container.replication.TestPushReplicator.uploadCompletesNormally(TestPushReplicator.java:61)
```
The problem is that `PushReplicator` now (after HDDS-7778) wraps the …

HDDS-7856. Fix timeout in TestPushReplicator

---

hadoop-hdds/framework/pom.xml
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBCheckpointManager.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java
hadoop-ozone/dist/src/main/license/bin/LICENSE.txt
hadoop-ozone/dist/src/main/license/jar-report.txt
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneSnapshotRestore.java
pom.xml

This change is to add the wait of 10 secs for checkpoint directory creation with 100 millis interval poll. We can't not use [wait()](https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#wait()) and [notify()](https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#notify()) because checkpointing directory creation happens inside RocksDB and RocksDB doesn't provide any [listen](https://javadoc.io/static/org.rocksdb/rocksdbjni/7.4.5/org/rocksdb/EventListener.html) which can be overloaded to notify.
Hence we are using `awaitility` polling mechanism to check if checkpoint directory gets created in 10 secs.
https://issues.apache.org/jira/browse/HDDS-7845

HDDS-7845. [Snapshot] Wait for RocksDB checkpoint directory creation

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/ObjectStore.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/audit/OMAction.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OzoneManagerProtocol.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMetrics.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotDeleteRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotCreateResponse.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotDeleteResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/OMRequestTestUtils.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotCreateRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotDeleteRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/snapshot/TestOMSnapshotDeleteResponse.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/ClientProtocolStub.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/snapshot/CreateSnapshotHandler.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/snapshot/DeleteSnapshotHandler.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/snapshot/ListSnapshotHandler.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/snapshot/SnapshotCommands.java

- Implement CLI `ozone sh snapshot delete`.
- Implement Ratis Tx `OMSnapshotDeleteRequest`.
- Improve CLI output for UX.
https://issues.apache.org/jira/browse/HDDS-6857
```bash
$ ozone fs -mkdir -p ofs://om/vol1/buck1/dir1/
$ ozone fs -put README.md ofs://om/vol1/buck1/dir1/
$ ozone sh snapshot create /vol1/buck1 snap1
$ ozone sh snapshot delete /vol1/buck1 snap1
$ ozone sh snapshot delete /vol1/buck1 snap1
FILE_NOT_FOUND Snapshot exists but no longer active
$ ozone sh snapshot list /vol1/buck1
[ {
"bucketName" : "buck1",
"name" : "snap1",
"creationTime" : 1673583279047,
"snapshotStatus" : "SNAPSHOT_DELETED",
"snapshotID" : "08f640e3-95db-4596-9d5f-a47cb7272329",
"snapshotPath" : "vol1/buck1",
"checkpointDir" : "-08f640e3-95db-4596-9d5f-a47cb7272329"
} ]
```

HDDS-6857. [Snapshot] Implement Snapshot Delete CLI and API

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneSnapshotRestore.java

Snapshot [restore integration test](https://github.com/apache/ozone/blob/HDDS-6517-Snapshot/hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneSnapshotRestore.java#L236) fails when restoring form bucket1's snapshot to bucket2 for legacy bucket type.
This change is to delete keys from the source bucket. This is temporary fix to make sure that test passes all the time.
If we don't delete keys from the source bucket, copy command will fail. In copy command, there is a check to make sure that key doesn't exist in the destination bucket.
Problem is that RocksDB's seek operation doesn't 100% guarantee that item key is available. Tho we believe that it is. When we seek if there is a directory for the key name, sometime it returns non-null response but in …

HDDS-7861. [Snapshot] Delete keys from the source bucket to fix the flakiness of snapshot restore tests

---

hadoop-ozone/integration-test/src/test/resources/contract/ozone.xml
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/CapableOzoneFSOutputStream.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneFSOutputStream.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneStreamCapabilities.java
hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java
hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java
hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java
hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java

Add StreamCapability interface to Ozone outputstream.
https://issues.apache.org/jira/browse/HDDS-7826
Unit tests

HDDS-7826. Add support for application to probe output stream capability

---

pom.xml

the system info of my macbook is as follow:
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T23:06:16+08:00)
Maven home: /Library/apache-maven-3.6.2
Java version: 1.8.0_362, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk@8/1.8.0+362/libexec/openjdk.jdk/Contents/Home/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "12.6", arch: "x86_64", family: "mac"
when building the project on my macbook, this error comes out.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (depcheck) on project ozone-manager: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
the reason is :
```
[INFO] — maven-enforcer-plugin:3.0.0-M1:enforce …
```

HDDS-7850. bump maven-enforcer-plugin.version to 3.2.1

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStream.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStreamFlushDelay.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestFailureHandlingByClient.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestAddRemoveOzoneManager.java

Mark some test methods flaky in `TestAddRemoveOzoneManager`, `TestBlockOutputStreamFlushDelay` and `TestFailureHandlingByClient`.  (`TestBlockOutputStreamFlushDelay` had to be converted to JUnit5 for this.)
HDDS-7875
HDDS-7877
HDDS-7878
HDDS-7880
Verified that the tests flagged are now executed in the _integration (flaky)_ check.

HDDS-5626. Mark parts of TestAddRemoveOzoneManager, TestBlockOutputStreamFlushDelay and TestFailureHandlingByClient as flaky

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/RatisBlockOutputStream.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntryPool.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/audit/OMAction.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OzoneManagerProtocol.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
hadoop-ozone/integration-test/src/test/resources/contract/ozone.xml
hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyCommitResponse.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyCommitResponseWithFSO.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeyCommitResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeyCommitResponseWithFSO.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/CapableOzoneFSOutputStream.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneStreamCapabilities.java

1. Repurpose CommitKey request handler to support hsync.
2. Make sure client hsync() updates SCM.
3. add StreamCapability interface to output stream.
https://issues.apache.org/jira/browse/HDDS-7688
Unit tests

HDDS-7688. Ozone Manager change to support HSync.

---

hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/audit/AuditLogTestUtils.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmAcls.java

Fix intermittent failure in `TestOmAcls` where audit log did not have the expected content.
I think this is caused by audit log being written asynchronously (to reduce delay of Ozone operations).  Thus we have to wait for the content to be written.
Also added removal of the `audit.log` file, which was leftover after the test finished.
https://issues.apache.org/jira/browse/HDDS-7868
Repeated 100 times successfully:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4072040018/jobs/7014405350
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4073118127

HDDS-7868. Intermittent failure in TestOmAcls

---

hadoop-ozone/dist/src/main/smoketest/basic/ozone-shell-single.robot
hadoop-ozone/dist/src/main/smoketest/basic/ozone-shell.robot

In some test runs each operation takes a bit longer, leading to intermittent timeouts in `ozone-shell` and `ozone-shell-single` tests.  The change increases timeout from 5 to 10 minutes.
https://issues.apache.org/jira/browse/HDDS-7881
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4076435810/jobs/7026141074
Two of the tests with increased timeout would have failed with the original limit (`Test ozone shell` and `RpcClient with port`) as they took just a few seconds more than 5 minutes:
```
2023-02-02T18:13:44.1486984Z Basic.Ozone-Shell-Single :: Test ozone shell CLI usage                        
2023-02-02T18:13:44.1487687Z ==============================================================================
2023-02-02T18:18:49.6730281Z Test ozone shell …
```

HDDS-7881. Intermittent timeout in basic acceptance test

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DatanodeDeletedBlockTransactions.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/SCMBlockDeletingService.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeProtocolServer.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java

Currently the delete block transaction retry count is increased when SCM sends command to each datanode, which means for one transaction, SCM is to send to 3 datanodes, the retry count will be increased 3 times, but in fact, it should only be increased once.
This ticket is to fix the above issue.
https://issues.apache.org/jira/browse/HDDS-7306
Added log checks in integration test.

HDDS-7306. DeleteBlock retry count increased at incorrect place

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/RandomContainerDeletionChoosingPolicy.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/TopNOrderedContainerDeletionChoosingPolicy.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingService.java

Previously, containers with zero pending deletion blocks will also be sent to check container chosing policy, which is unnecessary. We can filter them out before passing to any policy.
https://issues.apache.org/jira/browse/HDDS-7091
Manual tested with debug log added.
Before:
```
2022-08-04 14:14:23,725 [BlockDeletingService#8] INFO org.apache.hadoop.ozone.container.keyvalue.statemachine.background.BlockDeletingService: Found 57 candidates for bl
ock deletion
2022-08-04 14:14:23,725 [BlockDeletingService#8] INFO org.apache.hadoop.ozone.container.common.impl.TopNOrderedContainerDeletionChoosingPolicy: Container 128 has 0 pendi
ng deletion blocks
2022-08-04 14:14:23,725 [BlockDeletingService#8] INFO org.apache.hadoop.ozone.container.common.impl.TopNOrderedContainerDeletionChoosingPolicy: …
```

HDDS-7091. Filter containers with pending deletion blocks before checking policy

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAUtils.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMInstallSnapshot.java

The configuration of "OZONE_SCM_HA_RATIS_SNAPSHOT_DIR" is not correctly used as the directory of ratis snapshot.
https://issues.apache.org/jira/browse/HDDS-7578
unit test.

HDDS-7578. Wrong directory config used for SCM HA Ratis Snapshot

---

hadoop-hdds/docs/content/tools/LogsInOzone.md
hadoop-ozone/dist/src/shell/conf/dn-audit-log4j2.properties
hadoop-ozone/dist/src/shell/conf/om-audit-log4j2.properties
hadoop-ozone/dist/src/shell/conf/s3g-audit-log4j2.properties
hadoop-ozone/dist/src/shell/conf/scm-audit-log4j2.properties

This ticket is to add delete action to log4j to delete our of date audit logs.
https://issues.apache.org/jira/browse/HDDS-7082
Test in cluster.

HDDS-7082. Delete out of date audit logs

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerUnit.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmMetadataManager.java

When a key is created by OMKeyCreateRequest, its creation time is set by Time.now(), which is local time.
When OpenKeyCleanupService checks for expired open keys (OmMetadataManagerImpl.getExpiredOpenKeys()) it uses Instant.now() as the current time, which is UTC time.
They should use the same time zone.
https://issues.apache.org/jira/browse/HDDS-7764
Updated existing unit tests.

HDDS-7764. Potential discrepancy of key creation time may cause premature open key clean up.

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/server/JsonUtils.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/DatanodeSimulationState.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/DatanodeSimulator.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/Freon.java

This PR contains a new Freon tool to simulate a number of datanodes and coordinate with SCM to create a number of containers on the said datanodes.
Example usage: The following command simluates 5K datanodes with 40K containers per datanode (total 200M containers replication ~ 1exabytes of raw usage).
```
ozone freon simulate-datanode -t 20 -n 5000 -c 40000
```
https://issues.apache.org/jira/browse/HDDS-7489
The tool is tested manually in docker cluster and read cluster. We were able to simulate 5K datanoes and 100M containers with just 20 threads and an insignificant CPU consumption.

HDDS-7489. Create a Freon tool to simulate datanodes

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ExtendedInputStream.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/BadDataLocationException.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockInputStream.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockInputStreamProxy.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/ozone/client/io/TestECBlockInputStream.java

In ECBlockInputStream, it is possible to have multiple locations for a single replicaIndex, if, say one replica is decommissioned but still online and there is also an IN_SERVICE replica.
Similar for Maintenance - there can be maintenance and in_service replicas, or just over replicated replicas.
As things stand, if a read to an index fails, it causes a failover to reconstruction read, but there are occassions where it would be possible to read from the spare replica and no need to fall back to reconstruction.
This PR allows spare replicas to be tried before giving up with an error.
https://issues.apache.org/jira/browse/HDDS-7917
Added a new unit test.

HDDS-7917. EC: ECBlockInputStream should try spare replicas on error

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerImpl.java

HDDS-7871 (#4236) needs to add a JUnit 5 test to TestKeyManagerImpl.
Better to do the migration first.
https://issues.apache.org/jira/browse/HDDS-7921
Full CI: https://github.com/kaijchen/ozone/actions/runs/4120563700

HDDS-7921. Migrate TestKeyManagerImpl to JUnit5

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManager.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/ContainerEndpoint.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestContainerEndpoint.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconContainerManager.java

**Problem :** 
- The problem is that currently we are iterating through the OM-DB Snapshot using the ReconContainerMetadataManagerto provide data to these endpoints. Which is not very Reliable and UpToDate for container metadata. On the other hand we know for a fact that SCM DB snapshots are also fetched by recon which have a more reliable and upToDate information about the containters. Hence, recon should use its SCM metadata to give out information through the Container Endpoint. 
**Solution:**
- Its sugested that SCM Snapshots have a better upTodate information about the containers, To get the required data from these snapshots, we will fetch data from `ReconContainerManager` Class which interacts with the SCM snapshots and use its methods to populate the results of `ContainerEndpoint` …

HDDS-6056. Recon /containers endpoint should return SCM container data instead of OM container data.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java

`RocksIterator#seek()` may position at the first key in the source that at or **past target**,
which results false positive in KeyManagerImpl#createFakeDirIfShould().
https://issues.apache.org/jira/browse/HDDS-7871
TestKeyManagerImpl#testGetFileStatusWithFakeDirs()

HDDS-7871. Fix false positive in KeyManagerImpl#createFakeDirIfShould()

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestLegacyReplicationManager.java

LegacyReplicationManager#closeReplicasIfPossible tries to close replicas. 
```
private int closeReplicasIfPossible(ContainerInfo container,
List<ContainerReplica> replicas) {
// This method should not be used on open containers.
if (container.getState() == LifeCycleState.OPEN) {
return 0;
}
int numCloseCmdsSent = 0;
Iterator<ContainerReplica> iterator = replicas.iterator();
while (iterator.hasNext()) {
final ContainerReplica replica = iterator.next();
final State state = replica.getState();
if (state == State.OPEN || state == State.CLOSING) {
sendCloseCommand(container, replica.getDatanodeDetails(), false);
numCloseCmdsSent++;
iterator.remove();
} else if (state == State.QUASI_CLOSED) {
// Send force close command if the BCSID matches
if (container.getSequenceId() == …
```

HDDS-7915. Force close QUASI_CLOSED replicas only when the container is CLOSED in Legacy RM

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ECBlockOutputStream.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestContainerCommandsEC.java

Handled the case when chunk list null, but getChunks internal method returning empty list. In this case, we have made wrong assumption and access array elements. This fixed the issue and added the necessary checks.
https://issues.apache.org/jira/browse/HDDS-7923
Added the test.

HDDS-7923. [EC] Reconstruction is failing with IndexOutOfBoundsException

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerReplicaOp.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerReplicaPendingOps.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestContainerReplicaPendingOps.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/node/TestDecommissionAndMaintenance.java

In order to facilitate a "Move Manager" for the balancer, we need to schedule pending ops on the datanodes with different deadlines.
For example, as replica scheduled due to replication would have a timeout of 10 minutes.
However the balancer schedules large batches of work each hour, so replicas scheduled by the balancer probably need a timeout of 60 minutes.
To facilitate this, we need to change containerReplicaPending ops to store the deadline rather than the scheduled time. This also fixes another issue, in that the ContainerReplicaPendingOps "expiry thread" had its own setting for the timeout for all pending ops, and it is not related to the replication manager settings.
As part of this change, some APIs into RM has been changed a little to allow the move manager to schedule …

HDDS-7928. EC: Change ContainerReplicaPendingOps to store deadline rather than scheduled time

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerListVolumes.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

This PR is to fix the issue that users without Admin permission got PERMISSION_DENIED when listing their volume.
```
>> kinit -kt compose/_keytabs/testuser.keytab testuser/om@EXAMPLE.COM
>> ozone sh volume list 
PERMISSION_DENIED User testuser/om@EXAMPLE.COM doesn't have LIST permission to access volume Volume:/
```
Please see details and analysis in the related JIRA.
https://issues.apache.org/jira/browse/HDDS-7920
Tested manually in docker with `testuser/om@EXAMPLE.COM` (not an admin) in  `testuser.keytab`.
```
sh-4.2$ kinit -kt compose/_keytabs/testuser.keytab testuser/om@EXAMPLE.COM
sh-4.2$ ozone sh volume list
[ ]
sh-4.2$
```
I couldn't find any existing security test-suit to add this test to.

HDDS-7920. User cannot list their own volumes without access to root volume

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/TestECContainerRecovery.java

Fix intermittent timeout in TestECContainerRecovery.
Remove `running` and use `isrunning()` , because I think it is not `running` but `isrunning()` representing the Replication Monitor thread.
https://issues.apache.org/jira/browse/HDDS-7617
Run `TestECContainerRecovery` for many times.

HDDS-7617. Intermittent timeout in TestECContainerRecovery

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerHealthResult.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyRatisContainerReplicaCount.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisContainerReplicaCount.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisOverReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/RatisReplicationCheckHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/RatisUnhealthyReplicationCheckHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationTestUtil.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisContainerReplicaCount.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisOverReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestRatisReplicationCheckHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestRatisUnhealthyReplicationCheckHandler.java

Check the jira for a description of the task: https://issues.apache.org/jira/browse/HDDS-7847
Legacy RM calls mismatched and UNHEALTHY replicas unhealthy. New RM calls only UNHEALTHY replicas unhealthy.
Some notes about the changes proposed here:
1. Legacy RM tries to close all replicas, even UNHEALTHY ones. We don’t do this in RM - No need?
2. Legacy RM currently does not handle mis replication when ALL replicas are unhealthy. New RM will not either.
3. Legacy tries to close a quasi closed replica of a closed container, while new RM doesn't. We need to add this to MismatchedReplicasHandler but this is not done in this pr.
4. Legacy tries to close a quasi closed replica of a quasi closed container in some cases. This is probably a bug and is not done in new RM.
5. If a container is over …

HDDS-7847. Handle Replication of Unhealthy Replicas in RM

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/audit/S3GAction.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/S3GatewayConfigKeys.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/exception/S3ErrorTable.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectPut.java

Instead of creating 0 byte file, directory is going to be created.
https://issues.apache.org/jira/browse/HDDS-7594
* unit tests
* manual tests

HDDS-7594. [FSO] Folders created through S3G are created on file system as "files".

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerReplica.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeStatus.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/ECPipelineProvider.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerReplica.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestNodeStatus.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestECPipelineProvider.java

Sort datanodes of EC read pipeline by health and state, omit dead datanodes.
https://issues.apache.org/jira/browse/HDDS-7919
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4177372996

HDDS-7919. EC: ECPipelineProvider.createForRead should filter out dead replicas and sort replicas

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotFileSystem.java

Add Unit test for getFilestatus and readFile from snapshot paths.
https://issues.apache.org/jira/browse/HDDS-7865

HDDS-7865. [Snapshot] Add test for getFileStatus and readFile from snapshot paths.

---

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/FileSizeCountTask.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestFileSizeCountTask.java

In order to display the sizes of files stored in FSO (File Storage Optimised) buckets on the user interface, you will need to update the code that retrieves and displays the file information to also include files stored in FSO buckets. 
https://issues.apache.org/jira/browse/HDDS-7832?filter=-1
- Modified the existing UT's to check support for FSO
- Checked the UI by manually creating a Legacy, FSO and OBS bucket - 
```
ozone sh bucket create --layout FILE_SYSTEM_OPTIMIZED /s3v/fso-bucket
ozone sh key put s3v/fso-bucket/key1-fso NOTICE.txt
ozone sh key put s3v/fso-bucket/key2-fso NOTICE.txt
ozone sh bucket create --layout OBJECT_STORE /s3v/obs-bucket
ozone sh key put s3v/obs-bucket/key1-obs NOTICE.txt
ozone sh key put s3v/obs-bucket/key2-obs NOTICE.txt
ozone sh key put …
```

HDDS-7832. Support FSO buckets for FileSizeCountTask.

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/Table.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/cache/CacheValue.java
hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMDirectoryCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMDirectoryCreateRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileCreateRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3InitiateMultipartUploadRequestWithFSO.java

```java
//CacheValue.java
private Optional<VALUE> value;
```
It should be store simply as a VALUE.
https://issues.apache.org/jira/browse/HDDS-7969
This is a code refactoring.  No new tests added.

HDDS-7969. CacheValue should not store value as an Optional.

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/utils/CertificateCodec.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/CAType.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/CertificateServer.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/DefaultCAServer.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/CertificateClient.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DNCertificateClient.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DefaultCertificateClient.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/ReconCertificateClient.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/SCMCertificateClient.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/crl/CRLCodec.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/CertificateClientTest.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/authority/TestDefaultCAServer.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/TestDefaultCertificateClient.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/utils/TestCRLCodec.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/utils/TestCertificateCodec.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/utils/TestRootCertificate.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/HASecurityUtils.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMSecurityProtocolServer.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/cert/InfoSubcommand.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecureOzoneCluster.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/CertificateClientTestImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/OMCertificateClient.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/TestOzoneDelegationTokenSecretManager.java

Instead of using the sole certificate the whole cert bundle is used now.
In this new version, certificates are stored along with their entire certificate path up to the root CA. When getting these certificates, the whole chain is read back instead. In protocol messages the chain is converted into a String, so in reality `SCMGetCertResponseProto.x509Certificate` is now a pem encoded full certification chain.
Some minor refactors in CertificateCodec and removing some dead code is also included.
[HDDS-7379](https://issues.apache.org/jira/browse/HDDS-7379)
Some local tests were added as well as a sanity check of running a local cluster with security enabled and inserting a key.

HDDS-7379. Use certificate bundles instead of the sole certificate

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3MultipartUploadCompleteResponse.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3MultipartUploadCompleteResponseWithFSO.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3MultipartResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3MultipartUploadCompleteResponseWithFSO.java

When `keyToDelete.getDataSize()` returns zero and a request for FSO-enable bucket, a `CompleteMultipartUpload` request will crash with NullPointerException by attempting to read a bucketInfo that is assigned as null at this line [^1]. This patch proposes to prevent crash that changes not to read bucketInfo in the request handler.
```
2022-12-02 20:48:24,809 [OMDoubleBufferFlushThread] ERROR org.apache.hadoop.ozone.om.ratis.OzoneManagerDoubleBuffer: Terminating with exit status 2: OMDoubleBuffer flush thread OMDoubleBufferFlushThread encountered Throwable error
java.lang.NullPointerException: Cannot invoke "org.apache.hadoop.ozone.om.helpers.OmBucketInfo.getObjectID()" because the return value of "org.apache.hadoop.ozone.om.response.s3.multipart.S3MultipartUploadCompleteResponseWithFSO.getO …
```

HDDS-7596. Fix OM crash due to a corner case for FSO-enabled bucket

---

hadoop-ozone/dist/src/main/compose/ozones3-haproxy/test.sh
hadoop-ozone/dist/src/main/smoketest/s3/webui.robot

HDDS-1972 added a docker-compose example for HA Proxy in front of multiple S3 Gateways.  The example only runs basic, non-S3 tests.  This change replaces it with S3 tests, to verify S3 Gateway works with such setup.
https://issues.apache.org/jira/browse/HDDS-7988
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4205557222/jobs/7298351301#step:5:849

HDDS-7988. Run S3 tests with HA Proxy

---

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/commontypes/EncodingTypeObject.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/commontypes/KeyMetadata.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/commontypes/ObjectKeyNameAdapter.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/BucketEndpoint.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ListObjectResponse.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/commontypes/TestObjectKeyNameAdapter.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestBucketList.java

Support AWS s3 ListObjects API's encodingType request parameter
refer:
https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#AmazonS3-ListObjectsV2-response-EncodingType
current Ozone will encode `key` and `prefix` in the `ListObjects` response in the default, however, the AWS s3 has a request parameter of `encoding-type` that can control whether to encode fields such as key in the response 
The Ozone default encoding key can cause some bugs
For example, when using go-SDK `ListObjectsV2`, the encoded key is returned instead of the original character.
this is the example code:
you can put some keys that contain special characters in the key name (such as `=`), execute this code and check the return value(`=` will become `%3d`), you will find that special characters are …

HDDS-7710. Support AWS s3 ListObjects API's encodingType request parameter

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestObjectStoreWithLegacyFS.java

>  Quoted from javadoc of testFlatKeyStructureWithOBS():
>
> Test verifies that OBS bucket keys should create flat key-value
> structure and intermediate directories shouldn't be created even
> if the OZONE_OM_ENABLE_FILESYSTEM_PATHS flag is TRUE.
It turns out that the previous fix #4040 was not correct, in term of matching the original intention of this test.
I have reverted c119557241967679b1f8754e65cbe54a5d71fb6f on master.
This PR is a 2nd attempt to fix the flaky test `TestObjectStoreWithLegacyFS#testFlatKeyStructureWithOBS`,
without changing the original intention (so it matches with the javadoc).
https://issues.apache.org/jira/browse/HDDS-7588
Full CI: https://github.com/kaijchen/ozone/actions/runs/4221363513
Repeat 1000x: https://github.com/kaijchen/ozone/actions/runs/4221392332

HDDS-7588. Intermittent failure in TestObjectStoreWithLegacyFS#testFlatKeyStructureWithOBS

---

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/TracingFilter.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java

This fix excludes closing `StreamingOutput` related operations' spans in `TracingFilter` and only closing them after `StreamingOutput` callback (i.e. `GetBlock` and `ReadChunk`) has finished and the data has been written to the destination
https://issues.apache.org/jira/browse/HDDS-7064
Manual test in the docker-compose environment (with tracing enabled) and submitting AWS get-object request to S3G endpoint.

HDDS-7064. S3 get-object response emits tracing spans outside ObjectEndpoint#get

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnhealthyReplicationProcessor.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestOverReplicatedProcessor.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestUnderReplicatedProcessor.java

`UnhealthyReplicationProcessor#processAll` requeues any failed task.  Such tasks are attempted in the same `processAll` call, before exiting the loop.  This can flood SCM logs until the cause of the error is resolved.
This causes Github's environment to [run out of disk space](https://github.com/adoroszlai/hadoop-ozone/actions/runs/4205417969/jobs/7297733162#step:5:1527) in just a few minutes after testing EC reconstruction read (test being added in HDDS-7982).
This PR proposes to collect failed container health results and requeue them only after exiting the loop.
https://issues.apache.org/jira/browse/HDDS-7989
Also verified together with HDDS-7982 (which uncovered the problem without this fix):
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4207471575/jobs/73025 …

HDDS-7989. UnhealthyReplicationProcessor retries failure without delay

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsSnapshot.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotCreateRequest.java

Add unit testcase to handle snapshot name minimum-length -
- TestOzoneFsSnapshot#testCreateSnapshotSuccess,testCreateSnapshotFailure
- TestOMSnapshotCreateRequest#testPreExecuteNameLength
https://issues.apache.org/jira/browse/HDDS-7993
Testcase files - 
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotCreateRequest.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsSnapshot.java

HDDS-7993. [snapshot] Add testcase to handle snapshot name minimum-length

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineStream.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java

- setDataStreamMinPacketSize to 1 MB in the tests
https://issues.apache.org/jira/browse/HDDS-7983
Fixing existing tests.

HDDS-7983. Intermittent OutOfMemoryError in TestOzoneRpcClientWithRatis#testUploadWithStreamAndMemoryMappedBuffer.

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/ExpiredOpenKeys.java
hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/OpenKeyCleanupService.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmMetadataManager.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestOpenKeyCleanupService.java

When an OPEN file is abandoned by the original client up to the lease hard limit (7 days by default):
- If the file is not hsync’ed, delete it. (same as today)
- If the file is hsync’ed, close it at the last hsync’ed length.
https://issues.apache.org/jira/browse/HDDS-7782
Modified existing tests and new tests

HDDS-7782. OM lease recovery for hsync'ed files.

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

Patch #4140 added OM HA metrics, with some logic in OM to unregister if leader is unknown. However, unregistration happens in the wrong if branch, should be done if leader is null, not its id (which is required to be non-null).
Related discussion: https://github.com/apache/ozone/pull/4140#discussion_r1114254142
https://issues.apache.org/jira/browse/HDDS-8009
This patch was tested manually in docker clusters under 
`/hadoop-ozone/dist/target/ozone-1.4.0-SNAPSHOT/compose/ozone-ha`
and
`/hadoop-ozone/dist/target/ozone-1.4.0-SNAPSHOT/compose/ozone`.
Also, after taking another look in method `OzoneManager.updatePeerList()` under which we register `OMHAMetrics`, I can see that this method is only called after electing a leader. Under any scenario that there is no leader, this method won't even …

HDDS-8009. OM HA metrics should be unregistered if leader is not known

---

hadoop-ozone/dist/src/main/smoketest/basic/links.robot

Robot test for bucket links creates a loop of links, and verifies it is detected, i.e. infinite loop is avoided when trying to read from the link.  This PR adds cleanup to remove the loop after the test, to avoid errors in OM log:
```
om_1        | 2023-02-22 14:29:00,002 [Trash Emptier] ERROR om.TrashOzoneFileSystem: Couldn't perform fs operation fs.listStatus()/fs.exists()
om_1        | DETECTED_LOOP_IN_BUCKET_LINKS org.apache.hadoop.ozone.om.exceptions.OMException: Detected loop in bucket links. Bucket name: loop1, Volume name: 15904-target
om_1        | 	at org.apache.hadoop.ozone.om.OzoneManagerUtils.getBucketLayout(OzoneManagerUtils.java:110)
om_1        | 	at org.apache.hadoop.ozone.om.OzoneManagerUtils.getBucketLayout(OzoneManagerUtils.java:127)
om_1        | 	at …
```

HDDS-8012. Clean up after link loop test

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/RandomContainerDeletionChoosingPolicy.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/TopNOrderedContainerDeletionChoosingPolicy.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/interfaces/ContainerDeletionChoosingPolicyTemplate.java

This patch refactor `ContainerDeletionChoosingPolicy` by creating an abstract base class that acts as the template (`ContainerDeletionChoosingPolicyTemplate`) which abstracts out the general container deletion choosing process. `chooseContainerForBlockDeletion` acts as the template method. The concrete classes (e.g. `RandomContainerDeletionChoosingPolicy` and `TopNOrderedContainerDeletionChoosingPolicy`) only need to implement the ordering method (`orderByDescendingPriority`).
Notable changes and considerations:
- There are some additional logging `RandomContainerDeletionChoosingPolicy` regarding the number chosen blocks / total blocks, but it doesn't exist in `TopNOrderedContainerDeletionChoosingPolicy`. I decided to include it in the template class. 
- …

HDDS-7890. Refactor ContainerDeletionChoosingPolicy implementations

---

hadoop-ozone/httpfsgateway/src/main/java/org/apache/ozone/lib/servlet/ServerWebApp.java

Changed `VisibleForTesting` import to `com.google.common.annotations.VisibleForTesting`.
https://issues.apache.org/jira/browse/HDDS-7979
Built the project successfully, green CI on my fork: https://github.com/dombizita/ozone/actions/runs/4258016809

HDDS-7979. Replace import from shaded Guava

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/ECFileChecksumHelper.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/ReplicatedFileChecksumHelper.java

Let file checksum helper release client in case of success to prevent memleak.
(It seems logic for releasing client was copied from `BlockInputStream`, which has been fixed in HDDS-7931 since then.)
https://issues.apache.org/jira/browse/HDDS-8020
```
mvn clean test -am -pl :ozone-integration-test -Dtest='TestOzoneFileChecksum'
```
Verified no warning about `ManagedChannelImpl was not shutdown properly` appears in test log.
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4257319915

HDDS-8020. File checksum helper leaking client

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/ECReplicationCheckHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/RatisReplicationCheckHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestECReplicationCheckHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestRatisReplicationCheckHandler.java

If a container is missing, then the new Replication Manager currently counts 1 in the report for under replicated and 1 for missing, meaning the container is double counted.
It makes more sense if we only count under-replicated OR missing. Technically a missing container is also under-replicated, but it makes the report confusing when the container is in two states.
https://issues.apache.org/jira/browse/HDDS-8025
Modified some existing tests.

HDDS-8025. ReplicationManager: Count a container once for missing, under, mis or over replicated

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/XceiverServerGrpc.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/RatisPipelineProvider.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/TestSCMCommonPlacementPolicy.java
pom.xml

Directly use Guava classes instead of the shaded ones from `ratis-thirdparty`.
https://issues.apache.org/jira/browse/HDDS-8026
```
$ rg --glob '*.java' org.apache.ratis.thirdparty.com.google.common | wc -l
0
```
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4262730397

HDDS-8026. Replace import from shaded Guava

---

pom.xml

I added `okio` as a dependency to the root pom (it was already present in the project transitively by another dependency, but without this the version wasn't defined, so different dependencies could bring in different versions of it)
https://issues.apache.org/jira/browse/HDDS-8022
Built the project successfully, green CI on my fork: https://github.com/dombizita/ozone/actions/runs/4257898815

HDDS-8022. Add okio as dependency to the root pom

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManagerImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerStateManagerImpl.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerReportHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerStateManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestIncrementalContainerReportHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestLegacyReplicationManager.java

As things stand, ContainerManagerImpl holds a reference to ContainerReplicaPendingOps. As new replicas are received or deleted from the DNs, the replicas are updated in ContainerStateManager under a lock, and then pending ops is updated. This leave the possibility of a race condition where the replicas have been updated but pending ops has not.
To avoid this, we should move the pendingOps update into the StateManager so it is updated along with the replicas under the same lock.
https://issues.apache.org/jira/browse/HDDS-8008
Existing tests cover this.

HDDS-8008. Move pendingOps into ContainerStateManagerImpl to ensure consistent state

---

hadoop-ozone/dist/src/main/compose/ozone-ha/docker-compose.yaml
hadoop-ozone/dist/src/main/compose/ozone/docker-compose.yaml
hadoop-ozone/dist/src/main/compose/ozonesecure-ha/docker-compose.yaml
hadoop-ozone/dist/src/main/compose/ozonesecure/docker-compose.yaml
hadoop-ozone/httpfsgateway/pom.xml

I changed the `ozone-runtime` dependency scope to runtime in the HttpFS module and as a result of in the docker environments with HttpFS I could remove the `ozone-filesystem-hadoop3` jar from the classpath.
https://issues.apache.org/jira/browse/HDDS-7997
Built the project successfully, also manually tested the docker environments locally.
green CI on my fork: https://github.com/dombizita/ozone/actions/runs/4257933078

HDDS-7997. [HTTPFSGW] Change ozone-filesystem to a runtime dependency for HttpFS

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/MoveManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestMoveManager.java

`MoveManager#move` already checks if a container has any in-flight (pending) Adds or Deletes before scheduling a move. However, there is some time between the replication thread checking the health of a container and queuing it and the `UnhealthyReplicationProcessor` thread picking containers from the queue and scheduling Adds and Deletes. To be safe, we should also check the container's health in `MoveManager` before scheduling move.
https://issues.apache.org/jira/browse/HDDS-8034
Added UT.

HDDS-8034. Check container replication health before scheduling move in MoveManager

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/CloseContainerEventHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/IncrementalContainerReportHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestCloseContainerEventHandler.java

There are many NotLeaderException stack trace printed in follower SCM.  We change them to a single line messages here.
https://issues.apache.org/jira/browse/HDDS-6241
Just changing some log messages.  No new tests added.

HDDS-6241. Follower SCM node repeatedly sending requests to Ratis server.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHADBTransactionBufferImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHADBTransactionBufferStub.java

Found by  https://issues.apache.org/jira/browse/HDDS-8031?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel
The issue is found due to the lack of lock protection.
The **addToBuffer/removeFromBuffer** may be concurrently called with **flush**, which may add KV into a closed batch and cause the JVM crash.
https://issues.apache.org/jira/browse/HDDS-8036
Original Error test:
https://github.com/Xushaohong/ozone/actions/runs/4280636237/jobs/7452661792
POC fix test:
https://github.com/Xushaohong/ozone/actions/runs/4281772162/jobs/7455208505

HDDS-8036. Unprotected flush in SCMHADBTransactionBuffer

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/GrpcReplicationService.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestGrpcReplicationService.java

`GrpcOutputStream` is created for replicating container between datanodes.  It is passed into `TarContainerPacker`, which closes it after writing files of the container:
https://github.com/apache/ozone/blob/25ad1f2a4fc944cff098c22edaea1bd9e08344ba/hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/TarContainerPacker.java#L160
If an exception happens before `TarContainerPacker#pack` is called (e.g. container not found), `GrpcOutputStream` is left open.
This patch ensures the stream is closed even in such cases.  This applies to pull replication.  Push replication already has such logic:
https://github.com/apache/ozone/blob/25ad1f2a4fc944cff098c22edaea1bd9e08344ba/hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/Pus …

HDDS-8044. Ensure GrpcOutputStream is closed

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java

Add unit-testcases for snapshot delete - `TestOmSnapshot`
- testCreateSnapshotMissingMandatoryParams
- testDeleteSnapshotTwice
- testDeleteSnapshotFailure
- testDeleteSnapshotMissingMandatoryParams
https://issues.apache.org/jira/browse/HDDS-8006
Testcase files - `hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java`

HDDS-8006. [snapshot] Add unit test cases for snapshot delete

---

hadoop-hdds/docs/content/tools/_index.md
hadoop-hdds/docs/content/tools/_index.zh.md
hadoop-ozone/dist/src/shell/ozone/ozone

`ozone jmxget` has never been implemented, but `jmxget` is still listed as a possible subcommand.
```
$ ozone jmxget
ERROR: jmxget is not COMMAND nor fully qualified CLASSNAME.
...
Admin Commands:
daemonlog     get/set the log level for each daemon
jmxget        get JMX exported values from NameNode or DataNode.
...
```
This PR proposes to remove `jmxget` as an `ozone` subcommand.
https://issues.apache.org/jira/browse/HDDS-534
```
$ ozone jmxget
ERROR: jmxget is not COMMAND nor fully qualified CLASSNAME.
...
Admin Commands:
daemonlog     get/set the log level for each daemon
Client Commands:
...
```
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4286535294

HDDS-534. Remove unsupported jmxget subcommand

---

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/FileSizeCountTask.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/NSSummaryTaskWithLegacy.java

The Recon server is encountering an issue while processing a key in the file system, leading to an unexpected exception. The error message cites a "ClassCastException," indicating that the Recon server is attempting to cast an object of type `org.apache.hadoop.ozone.om.helpers.RepeatedOmKeyInfo` as an object of type `org.apache.hadoop.ozone.om.helpers.OmKeyInfo`. As a result, the server is unable to properly process the key and accurately display the number of files/keys.
So I have made changes to the fileSizeCountTask which will handle both RepeatedOmKeyInfo and OmKeyInfo objects.
https://issues.apache.org/jira/browse/HDDS-7926
UT's ran successfully

HDDS-7926. [hsync] Recon throws ClassCastException.

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/StringUtils.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/conf/OzoneConfiguration.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/TestHddsUtils.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManagerStarter.java
hadoop-ozone/csi/src/main/java/org/apache/hadoop/ozone/csi/CsiServer.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManagerStarter.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServer.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/Gateway.java

Added a `conf` field in `STARTUP_MSG` for all Ozone roles with configs relevant to the role. 
https://issues.apache.org/jira/browse/HDDS-7869
Manual test
```
OM : 
/************************************************************
2023-02-12 20:11:34 STARTUP_MSG: Starting OzoneManager
...
2023-02-12 20:11:34 STARTUP_MSG:   java = 11.0.17
2023-02-12 20:11:34 STARTUP_MSG:   conf = {hadoop.hdds.db.rocksdb.logging.level=INFO, ozone.om.enable.ofs.shared.tmp.dir=false, ozone.om.ratis.log.appender.queue.num-elements=1024, hadoop.hdds.db.rocksdb.logging.enabled=false, ozone.om.snapshot.provider.socket.timeout=5000s, ozone.scm.info.wait.duration=10m, ozone.om.http.auth.type=kerberos, ozone.om.multitenancy.enabled=true, ozone.om.https-bind-host=0.0.0.0, ozone.om.ratis.server.request.timeout=3s, …
```

HDDS-7869. Log configuration on component startup.

---

hadoop-ozone/dist/src/main/license/bin/LICENSE.txt
hadoop-ozone/dist/src/main/license/jar-report.txt
hadoop-ozone/httpfsgateway/pom.xml
pom.xml

After merge from `master` we'll have dependency convergence error for Zookeeper.
This change prepares for that by upgrading Curator on the feature branch.
https://issues.apache.org/jira/browse/HDDS-8045
```
git merge --no-edit origin/master
mvn -DskipTests clean package
hadoop-ozone/dev-support/checks/dependency.sh
```
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4294938025

HDDS-8045. Dependency convergence error for zookeeper

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/GrpcXceiverService.java

Avoid calling response observer's `onCompleted()` after `onError()`.
Steps to reproduce:
1. Change `BlockManagerImpl.persistPutBlock` to throw some NPE
2. Start cluster with 5 nodes
3. Create EC key: `ozone freon ockg -n1 -t1 --replication-type EC --replication rs-3-2-1024k -s100`
Result in datanode log:
```
2023-03-01 17:54:22,957 [ChunkReader-1] ERROR server.GrpcXceiverService: Got exception when processing ContainerCommandRequestProto cmdType: PutBlock
traceID: ""
containerID: 1
datanodeUuid: "1c284e9e-d128-4c95-bded-7a1d75eecd30"
putBlock {
blockData {
blockID {
containerID: 1
localID: 111677748019200001
blockCommitSequenceId: 0
replicaIndex: 2
}
metadata {
key: "TYPE"
value: "KEY"
}
metadata {
key: "blockGroupLen"
value: "100"
}
}
eof: true
}
java.lang.NullPointerException: testing …
```

HDDS-8019. IllegalStateException: call already closed at GrpcXceiverService.onCompleted

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestRandomKeyGenerator.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/RandomKeyGenerator.java

Resolve NullPointerException caused by `RandomKeyGenerator`
https://issues.apache.org/jira/browse/HDDS-7934
This patch was tested by executing `ozone freon randomkeys --numOfVolumes=3 --numOfBuckets 10 --numOfKeys 30`, and the following is result.
***************************************************
Status: Success
Git Base Revision: a585a73c3e02ac62350c136643a5e7f6095a3dbb
Number of Volumes created: 3
Number of Buckets created: 30
Number of Keys added: 900
Replication: THREE
Replication type: RATIS
Average Time spent in volume creation: 00:00:00,010
Average Time spent in bucket creation: 00:00:00,058
Average Time spent in key creation: 00:00:07,202
Average Time spent in key write: 00:00:00,331
Total bytes written: 9216000
Total Execution time: 00:00:38,263 …

HDDS-7934. NPE in RandomKeyGenerator's shutdown hook

---

hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/BaseHttpServer.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/TestStorageContainerManagerHttpServer.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHttpServer.java

A lot of customers were facing issues Ozone service-related WebUI not opening with a 404 error. The issue can be fixed by restarting, but during the restart, a `jetty-0_0_0_0-*/webapp` folder is created, and the customer noticed that such a folder does not exist on the host with access issues. The customer performed manual restarts on each node and observed that the problem was resolved by creating a new `jetty-0_0_0_0-*/webapp` folder. 
After investigating we can confirm that the ozone code is not responsible for the deletion of the contents in the tmp directory. It appears that an external program is responsible for the deletion.
The main culprit for deletion is the Linux program called `systemd-tmpfiles-clean.timer` . This program is designed to clean up temporary files that are …

HDDS-6176. Ozone service WebUI is not accessible with 404 error.

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/DBCheckpointMetrics.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMetrics.java

https://issues.apache.org/jira/browse/HDDS-8070
It's tested by [TestOzoneManagerListVolumesSecure.java](https://github.com/apache/ozone/pull/2466/files#diff-98e0e9e15effe6120b4dcae2999f826e671701b9e8d5ca2bb09d6bdb9fe867fe)

HDDS-8070. DBCheckpointMetrics is not unregistered during OM stop.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/CapableOzoneFSOutputStream.java

StreamCapabilities.hasCapability(HSYNC) does not return true for encrypted buckets.
https://issues.apache.org/jira/browse/HDDS-8029
Unit test + Manually tested on a HBase cluster

HDDS-8029. [hsync] Outputstream in encrypted buckets do not return the correct stream capabilities.

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinatorTask.java

ECReconstructionCoordinatorTask.runTask() catches IOException, but any RuntimeExceptions fall threw the handler and are not logged correctly.
The handler should catch Exception to ensure any Runtime Exception caused by precondition checks are caught and handled too.
https://issues.apache.org/jira/browse/HDDS-8075
No tests added.

HDDS-8075. ECReconstructionCoordinatorTask.runTask should catch Exception instead of IOException

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/pipeline/Pipeline.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/storage/ContainerProtocolCalls.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestXceiverClientGrpc.java

When failing read chunk from a datanode, exclude it and retry other datanodes.
https://issues.apache.org/jira/browse/HDDS-8024
Updated TestHSync

HDDS-8024. When readChunk from a datanode fails, retry other datanodes.

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueHandlerWithUnhealthyContainer.java

`KeyValueHandler` in general does not handle unchecked exceptions.  The exception reaches gRPC, which closes the connection abruptly.  As a result, client only gets some generic exception (`StatusRuntimeException: UNKNOWN`).
Steps to reproduce:
1. Change `BlockManagerImpl.persistPutBlock` to throw some NPE
2. Start cluster with 5 nodes
3. Create EC key: `ozone freon ockg -n1 -t1 --replication-type EC --replication rs-3-2-1024k -s100`
Result in datanode log:
```
2023-03-01 17:54:22,957 [ChunkReader-1] ERROR server.GrpcXceiverService: Got exception when processing ContainerCommandRequestProto cmdType: PutBlock
traceID: ""
containerID: 1
datanodeUuid: "1c284e9e-d128-4c95-bded-7a1d75eecd30"
putBlock {
blockData {
blockID {
containerID: 1
localID: 111677748019200001
blockCommitSequenceId: 0 …
```

HDDS-8057. Handle unchecked exception in KeyValueHandler more gracefully

---

hadoop-hdds/common/src/main/resources/ozone-default.xml

Some config properties have embedded newlines, which breaks any output where they are included (e.g. https://github.com/apache/ozone/pull/4271#issuecomment-1447706645).
This patch removes such newlines.
https://issues.apache.org/jira/browse/HDDS-8046
Full CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4292591337

HDDS-8046. Eliminate embedded newlines from config properties

---

dev-support/ci/pr_title_check.bats
dev-support/ci/pr_title_check.sh

Allow PR title starting with `Revert "` to pass the PR CI title check.
Support the default title generated by Github's built-in revert PR feature.
https://issues.apache.org/jira/browse/HDDS-8078
- Apache CI
- Added test cases
- CI run on a fork with `Revert "` in PR title has passed:
- https://github.com/smengcl/hadoop-ozone/actions/runs/4329335098/jobs/7559813493

HDDS-8078. Github CI: Allow PR title starting with Revert

---

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/pipeline/ListPipelinesSubcommand.java

Currently the Pipeline list SubCommand provides a list of pipelines on the console, but it does not provide a JSON output option. We should allow for JSON output to ensure compatibility and so the output can be consumed programmatically.
https://issues.apache.org/jira/browse/HDDS-6802
This patch was tested using docker-compose. Here is the output -
```
bash-4.2$ ozone admin pipeline list --json | more
[ {
"id" : {
"id" : "ec954f5b-355d-477c-9905-09718d77da9c"
},
"replicationFactor" : "ONE",
"requiredNodes" : 1,
},
"nodesInOrder" : [ {
"level" : 0,
"cost" : 0,
"uuid" : "955f219c-e422-415b-9f83-0431588552b4",
"uuidString" : "955f219c-e422-415b-9f83-0431588552b4",
"ipAddress" : "172.18.0.11",
"hostName" : "ozone_datanode_6.ozone_default", …
```

HDDS-6802. Pipeline list SubCommand should provide a JSON output option

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeManagerMXBean.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java
hadoop-hdds/server-scm/src/main/resources/webapps/scm/scm-overview.html
hadoop-hdds/server-scm/src/main/resources/webapps/scm/scm.js
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/SimpleMockNodeManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/container/testutils/ReplicationNodeManagerMock.java

commit id : 74b79146fcdb288a29e583e0af9270dc983e3d48
This Includes Sorting, Searching & Pagination on SCM UI where page deafult size is 10. we can also set this to 20 or 50 or 'All' records per page as well.
Page slicing & Record Slicing both have been implemented along wth sort & search.
Backend Changes ::
JMX API developed & the response from API is
"NodeStatusInfo" : [ {
"key" : "ozone_datanode_1.ozone_default",
"value" : [ "HEALTHY", "IN_SERVICE" ]
}, {
"key" : "ozone_datanode_3.ozone_default",
"value" : [ "HEALTHY", "IN_SERVICE" ]
}, {
"key" : "ozone_datanode_2.ozone_default",
"value" : [ "HEALTHY", "IN_SERVICE" ]
} ]
Note: HDDS 7816 JIRA includes both UI & Backend changes . …

HDDS-7816. Add DataNode list to the SCM WebUI

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/GrpcContainerUploader.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/GrpcReplicationClient.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/SendContainerOutputStream.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/SimpleContainerDownloader.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestGrpcContainerUploader.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestSendContainerOutputStream.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestSimpleContainerDownloader.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/replication/TestContainerReplication.java

Ensure `GrpcReplicationClient` is closed to fix leak.
HDDS-8108  (but reported as early as HDDS-1615)
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4364237406

HDDS-8108. gRPC channel created for replication client not shutdown properly

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java

`DatanodeStateMachine` creates `ECReconstructionCoordinator`, but never closes it.
https://issues.apache.org/jira/browse/HDDS-8112
Trivial fix.  Existing tests (for regression):
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4366169736

HDDS-8112. ECReconstructionCoordinator is not closed

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NodeSchemaLoader.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/server/YamlUtils.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/DatanodeIdYaml.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerDataYaml.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/helpers/TestContainerUtils.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/helpers/TestDatanodeIdYaml.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMiniOzoneCluster.java
pom.xml

* Upgrade SnakeYaml to 2.0,
* which disabled global tags by default for security, so we need to explicitly allow HDDS/Ozone classes.  The logic is centralized in `YamlUtils`.
* Add unit test for `DatanodeIdYaml`, because previously serialization problem was found only in acceptance/integration tests.
* Move related test case from `TestMiniOzoneCluster` to `TestContainerUtils`, as it is a unit test, not integration one.
Thanks @rohit-kb for the initial patch.
https://issues.apache.org/jira/browse/HDDS-8086
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4342661934

HDDS-8086. Bump snakeyaml from 1.33 to 2.0

---

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/TestHddsDatanodeService.java

`TestHddsDatanodeService` intermittently exits with:
```
[Datanode State Machine Task Thread - 0] ERROR datanode.InitDatanodeState (InitDatanodeState.java:call(84)) - Failed to get SCM addresses: ozone.scm.names need to be a set of valid DNS names or IP addresses. Empty address list found.
[Datanode State Machine Daemon Thread] ERROR statemachine.StateContext (StateContext.java:execute(675)) - Critical error occurred in StateMachine, setting shutDownMachine
[Datanode State Machine Daemon Thread] ERROR statemachine.DatanodeStateMachine (DatanodeStateMachine.java:startStateMachineThread(334)) - DatanodeStateMachine Shutdown due to an critical error
[Datanode State Machine Daemon Thread] INFO  util.ExitUtil (ExitUtil.java:terminate(210)) - Exiting with status 1: ExitException
```
Since the …

HDDS-8087. Intermittent crash in TestHddsDatanodeService

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/AbstractReplicationTask.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisor.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationTask.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestReplicationSupervisor.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/AllSourcesOverloadedException.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECMisReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/MisReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisMisReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECMisReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestMisReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisMisReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java

Create a configuration on Replication Manager that sets the limit of inflight replicate container commands to 20. The intention is to revisit this limit later to make it more dynamic, but this is a starting point.
Then create a method on ReplicationManager createThrottledReplicateContainerCommand, which create the replicateContainerCommands and take into consideration the pending commands on the target datanode. If not targets for the command have capacity, it will throw an exception.
Adjust the various places in ReplicationManager which send the replicateContainer commands to use the new method.
Additionally switch the default replication mode to Push (rather than download) and ensure the LegacyReplicationManager continues to use download as before. …

HDDS-8110. ReplicationManager: Introduce basic limits on ReplicateContainer commands

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SstFilteringService.java

Close rocksDB connection after SstFilteringTask finishes.
https://issues.apache.org/jira/browse/HDDS-8120
Tested in dev cluster.

HDDS-8120. [Snapshot] Close rocksDB connection after SstFilteringTask finishes

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/GrpcContainerUploader.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/SendContainerOutputStream.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestSendContainerOutputStream.java

Minor refactoring to simplify closing of `GrpcReplicationClient`.
https://issues.apache.org/jira/browse/HDDS-8119
Existing unit/integration tests.
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4368446905

HDDS-8119. Remove loosely related AutoCloseable from SendContainerOutputStream

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java

Add a new `TaskQueueMap` with `synchronized` submit(..) and removeIfEmpty(..) methods.
https://issues.apache.org/jira/browse/HDDS-8129
Using https://github.com/apache/ozone/compare/ozone-1.3...szetszwo:ozone:multipartUpload (may include the test here or in a separated JRIA.)

HDDS-8129. ContainerStateMachine allows two different tasks with the same container id running in parallel.

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/ContainerMetrics.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestDeleteContainerHandler.java

Similar to https://issues.apache.org/jira/browse/HDDS-8118 add a check for Block Table.
If there are blocks in the blocks DB then do no delete the container.
https://issues.apache.org/jira/browse/HDDS-8142
Integration tests included.

HDDS-8142. Check if no entries in Block DB for a container on container delete

---

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/keys/ChecksumKeyHandler.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/keys/KeyCommands.java
hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/shell/keys/TestChecksumKeyHandler.java
hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/shell/keys/package-info.java

Some earlier Jiras added the feature to retrieve the checksum of an Ozone key either as COMPOSITE_CRC or MD5 or the chunk checksum MD5s.
This checksum is only accessible via the Hadoop API.
This Jira adds a CLI command to Ozone to retrieve the same information.
https://issues.apache.org/jira/browse/HDDS-8133
New unit test and manually in docker cluster:
```
bash-4.2$ ozone sh key checksum /vol1/bucket/512    
{
"bucketName" : "bucket",
"name" : "512",
"dataSize" : 512,
"algorithm" : "COMPOSITE-CRC32",
"checksum" : "5A4FA397"
}
```

HDDS-8133. Create ozone sh key checksum command

---

hadoop-hdds/config/src/test/java/org/apache/hadoop/hdds/conf/TestConfigurationSource.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/rpc/TestRpcClient.java

Rename `RpcClientTest` and `ConfigurationSourceTest` to include them in CI runs.
https://issues.apache.org/jira/browse/HDDS-8150
Locally ran these tests, as well as checkstyle.

HDDS-8150. RpcClientTest and ConfigurationSourceTest not run due to naming convention

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DefaultCertificateClient.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/CertificateClientTestImpl.java

In my local environment the TestDefaultCertificateClient#testTimeBeforeExpiryGracePeriod() test started to fail, as we are approaching DST, and with that the return value of DefaultCertificateClient#timeBeforeExpiryGracePeriod(X509Certificate) is off by an hour.
This is because the test sets a 28 days expiration to the certificate, but due to switch to DST, at 3am in one of the mornings we switch to 2am, therefore the certificate expiration is 28days and 1 hour away instead of the expected 0.
https://issues.apache.org/jira/browse/HDDS-8144
After the change the named test runs fine in my local env.

HDDS-8144. TestDefaultCertificateClient#testTimeBeforeExpiryGracePeriod fails as we approach DST.

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/conf/OzoneConfiguration.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/conf/HddsConfServlet.java

Make the implementation of HDDS-8091 (#4359) compatible with Hadoop 3.1.  Both `addTags(Properties)` and `HADOOP_TAGS_CUSTOM` were only introduced in Hadoop 3.2.
https://issues.apache.org/jira/browse/HDDS-8091
Verified SCM web UI still can be used to browse Ozone config by tags.

HDDS-8091. [addendum] Generate list of config tags from ConfigTag enum - Hadoop 3.1 compatibility fix

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ScmClient.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerUnit.java

Use container cache in Key listing API to improve Key/file listing performance.
https://issues.apache.org/jira/browse/HDDS-8076
Unit test.

HDDS-8076. Use container cache in Key listing API.

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockInputStream.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockInputStreamFactory.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockInputStreamFactoryImpl.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockInputStream.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockInputStreamFactory.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockInputStreamFactoryImpl.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockInputStreamProxy.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockReconstructedStripeInputStream.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/DummyBlockInputStream.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/DummyBlockInputStreamWithRetry.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestBlockInputStream.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/ozone/client/io/ECStreamTestUtil.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/ozone/client/io/TestECBlockInputStream.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/ozone/client/io/TestECBlockInputStreamProxy.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyInputStream.java

Update the retry function to not only update pipeline, but also updating block token.
https://issues.apache.org/jira/browse/HDDS-7930
Unit tests

HDDS-7930. input stream does not refresh expired block token.

---

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/pipeline/ListPipelinesSubcommand.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/TransferOmLeaderSubCommand.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/scm/GetFailedDeletedBlocksTxnSubcommand.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/scm/TransferScmLeaderSubCommand.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/DBScanner.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/ReadReplicas.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/segmentparser/BaseLogParser.java

Add lower case hyphen arg names for those that only has camel case long option
https://issues.apache.org/jira/browse/HDDS-8065
local test

HDDS-8065. Provide GNU long options

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SstFilteringService.java

Use try-with-resources to ensure close rockdb connection in SstFilteringService
https://issues.apache.org/jira/browse/HDDS-8163
current CI unit tests

HDDS-8163. Use try-with-resources to ensure close rockdb connection in SstFilteringService

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockInputStream.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ChunkInputStream.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/storage/ContainerProtocolCalls.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestXceiverClientGrpc.java

Similar to [HDDS-8024](https://issues.apache.org/jira/browse/HDDS-8024), the client should retry other datanodes if it has failed to getBlock from a datanode.
https://issues.apache.org/jira/browse/HDDS-8090
This is to fix TestHSync

HDDS-8090. When getBlock from a datanode fails, retry other datanodes.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerConfiguration.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerTask.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/MoveManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancer.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancerTask.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestMoveManager.java

Currently ContainerBalancer uses ReplicationManager#move which internally uses LegacyReplicationManager. This jira proposes integrating MoveManager with ContainerBalancer such that it uses MoveManager#move if "hdds.scm.replication.enable.legacy" is false and ReplicationManager#move if it's true.
https://issues.apache.org/jira/browse/HDDS-8153
Added a UT and modified existing ones

HDDS-8153. Integrate ContainerBalancer with MoveManager

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCommandInfo.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinatorTask.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/AbstractReplicationTask.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/GrpcContainerUploader.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/GrpcOutputStream.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/GrpcReplicationService.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/PushReplicator.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisor.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationTask.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/SendContainerRequestHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/ReplicateContainerCommand.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/GrpcOutputStreamTest.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnhealthyReplicationProcessor.java
hadoop-ozone/dist/src/main/compose/ozonesecure/docker-config

* Change some verbose messages to debug level.
* Change some error messages to warn (replication failures are "expected").
* Add some missing info level logs.
* Improve content of some messages.
* Only log containers processed if there were any (in `UnhealthyReplicationProcessor`)
* Disable legacy replication manager in `ozonesecure` env. to exercise push replication 
* Avoid duplicate execution of `close()` in `GrpcOutputStream` (mostly to prevent confusing duplicate log messages)
https://issues.apache.org/jira/browse/HDDS-7867
Checked logs of replication in `ozonesecure`.
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4414527872

HDDS-7867. Clean up replication logs

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestLDBCli.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/DBScanner.java

Make unlimited(-1) length the default in ozone debug ldb.
https://issues.apache.org/jira/browse/HDDS-8099
Built locally and verified using docker-compose by creating more than 100 keys and run ldb command to see if it returns all data by default without giving "-l -1" option while running command.

HDDS-8099. Make unlimited length the default in ozone debug ldb.

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBStoreBuilder.java
hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedRocksDB.java
hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/GenericTestUtils.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/snapshot/SnapshotDiffReport.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/PersistentList.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/PersistentMap.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/RocksDbPersistentList.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/RocksDbPersistentMap.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/RocksDbPersistentSet.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestRocksDbPersistentList.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestRocksDbPersistentMap.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestRocksDbPersistentSet.java

This change is to return partial snap diff response along with some optimization to remove unnecessary serialization and 
de-serialization while persisting information to RocksDB.
For snap diff jobs and reports persistent, two table `snap-diff-job-table` and `snap-diff-report-table` have been added to snapshot Diff RocksDB instance (As of now, later can be moved to OM RocksDB instance). `snap-diff-job-table` table contains the information about the snap diff job to early return if similar job exists. `snap-diff-report-table` table is global table and is used to persist the snapdiff report and return the response in paginated fashion with client continuation token.
To remove unnecessary serialization and de-serialization, intermediate table and report table's type have been changed to byte …

HDDS-7548. [Snapshot] SnapDiff pagination and partial diff report implementation

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java
hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/rocksdiff/TestRocksDBCheckpointDiffer.java

Problem: As part of jira-[HDDS-7873](https://issues.apache.org/jira/browse/HDDS-7873), we added an optimization to early prune out SST files that won't be needed for compaction DAG base snap diff. More details in [PR-4235](https://github.com/apache/ozone/pull/4235).
Files are removed from back dir but compaction logs don't get updated because those are needed for DAG traversal based diffing. On OM restart, we count number of keys in the file present in compaction log. It is possible that file has been deleted due to above optimization which is causing OM crash.
This change is to log the exception instead throwing exception on OM restart. It will not affect Compaction DAG based snap diff because If file is not present during diff, it will throw the `FileNotFoundException`. …

HDDS-8069. [Snapshot] Compaction DAG reconstruction logic potentially crashing OM on startup

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECOverReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/MisReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/OverReplicatedProcessor.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisOverReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnderReplicatedProcessor.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnhealthyReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnhealthyReplicationProcessor.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationTestUtil.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECMisReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECOverReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestMisReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestOverReplicatedProcessor.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisMisReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisOverReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestUnderReplicatedProcessor.java

To allow better throttling control all the unhealthy handlers should send the command directly using the RM API, rather than gathering up a list of commands and returning them.
This change involves a change to the UnhealthyReplicationHandler interface, which previously returned the commands, but now returns just the count of commands sent instead.
https://issues.apache.org/jira/browse/HDDS-8158
Various existing tests modified.

HDDS-8158. Replication Manager: Make all handlers send commands immediately instead of returning commands

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerTask.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/MoveManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancer.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancerTask.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestMoveManager.java

Right now, `MoveManager` is instantiated in `ContainerBalancer` and it does not register with `ContainerReplicaPendingOps` as a subscriber. In this PR, we instantiate it inside StorageContainerManager and register it as a subscriber to `ContainerReplicaPendingOps`. Also removed the `running` state inside `MoveManager` and restricted `MoveManager#move` to its package.
https://issues.apache.org/jira/browse/HDDS-8167

HDDS-8167. Inject MoveManager into ContainerBalancer

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBStoreBuilder.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestDBStoreBuilder.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SstFilteringService.java

1) We need to make sure that Snapshot RocksDB instance are opened with configuration option that turns of the auto-compaction.
2) We open rocksDB for snapshot in RW for file filtering service. This is to delete some irrelevant SST files from the snapshot rocksDB manifest. We need to make sure that one of the configuration option in rocksDB option turns of Auto compaction.
https://issues.apache.org/jira/browse/HDDS-8102
https://issues.apache.org/jira/browse/HDDS-8122
Unit Tests & Integration Tests

HDDS-8122. [Snapshot] Disable RocksDB column family auto compaction in SstFilteringService

---

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/commontypes/EncodingTypeObject.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/BucketEndpoint.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestBucketList.java

This patch handles an edge case in `BucketEndpoint#get` where delimiter is an empty string. Some S3 client (e.g. Minio S3 Client) passes empty delimiter for recursive list.
https://issues.apache.org/jira/browse/HDDS-8183
Unit test and Manual test.
Empty delimiter is able to return the correct response:

HDDS-8183. Fix edge case where delimiter is empty string in BucketEndpoint#get

---

hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java

While working on [HDDS-8069](https://issues.apache.org/jira/browse/HDDS-8069) and going through the logs for it, we saw that there were some compaction entries in which input and output compaction files were exactly same. Which causes the loop in the DAG and make it non-DAG.
This change is to skip the compaction entry from being written to compaction log and file nodes get added to DAG, if input and output files are exactly the same.
https://issues.apache.org/jira/browse/HDDS-8160
Existing Unit tests and Acceptance tests.

HDDS-8160. [Snapshot] Skip the compaction entry from log and DAG if compaction input and output files are exactly same

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java

In order to keep a consistent count of the number of pending replicate and delete commands, ReplicationManager should send commands to the datanode via the nodeManager.addDatanodeCommand() method rather than publishing them to the event queue.
At the moment, the commands goto the event queue, where they are picked up by NodeManager and added to the datanode command queue. As we are using the counts in the command queue to determine how many commands are pending, the indirection provided by the event queue makes it difficult to keep a consistent count without excessive effort.
There is also no further processing done on the commands in the event queue, they simply go RM -> Event Queue -> Node Manager -> Command Queue.
This change makes RM send the commands to nodeManager directly. …

HDDS-8187. ReplicationManager: Datanode commands should be sent to nodeManager directly

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/DbVolume.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/HddsVolume.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/MutableVolumeSet.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/StorageVolume.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeInfoMetrics.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestHddsVolume.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestReservedVolumeSpace.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestVolumeSet.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMiniOzoneCluster.java

In case of failed volume, VolumeInfo object is assigned with null. While using VolumeInfo object we need to validate before accessing it.
https://issues.apache.org/jira/browse/HDDS-8054
https://issues.apache.org/jira/browse/HDDS-8051
https://issues.apache.org/jira/browse/HDDS-8052
https://issues.apache.org/jira/browse/HDDS-8053
Code has been built locally and manually tested.

HDDS-8054. NullPointerException: MethodMetric, Error invoking method getReserved.

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java

Remove the check for "delete transactionId" to be in order and skip any transaction coming out of order
https://issues.apache.org/jira/browse/HDDS-8139
This is tested for impact using E2E setup and observing frequency of logs for out-of-order or retry of deleteTransactionId comming again. 
Result: Its observed only once when had many blocks, but its not coming repeated always. So no impact is observed.

HDDS-8139. Datanodes should not drop block delete transactions based on transaction ID

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerRatisServer.java

While getting RatisRoles, In some cases when there is an exception we don't get leaderID. In this case we should return error to the caller.
https://issues.apache.org/jira/browse/HDDS-8068
Code has been built locally and manually tested.

HDDS-8068. Exception: JMXJsonServlet, getting attribute RatisRoles of Hadoop:service=OzoneManager.

---

hadoop-hdds/interface-client/src/main/proto/hdds.proto
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerConfiguration.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerTask.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/MoveManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancer.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancerTask.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestMoveManager.java

MoveManager currently has a hardcoded deadline of 60 minutes. We should make this configurable, and that configuration should be present in ContainerBalancerConfiguration.
Move is replication + deletion. Replication involves copying between two datanodes so it's generally more expensive than deletion. So we probably need to have an additional configuration for deciding how much time out of the total move deadline is allowed for replication. The rest will be allowed for deletion. Move deadline's configuration is "hdds.container.balancer.move.timeout".
Changes introduced:
1. Added a new configuration "hdds.container.balancer.move.replication.timeout". Made MoveManager use this configuration.
2. Added validations for this configuration in ContainerBalancer.
3. Added this configuration to …

HDDS-8168. Make deadlines inside MoveManager for move commands configurable

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECContainerReplicaCount.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECContainerReplicaCount.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java

For an EC container which has 2 replicas for the same index, with one decommissioning and one in_maintenance, the decommission logic in ECUnderReplicationHandler can send a command for the replica, and then the maintenance logic can send another replication command for the same container to a different target. If they both succeed it will likely result in over replication.
To solve this, we probably need to adjust the pending ops between each stage of the processing, so as then the maintenance logic would be "fixed by pending" and avoid sending the second command.
https://issues.apache.org/jira/browse/HDDS-8172
Existing tests modified.

HDDS-8172. ECUnderReplicationHandler should consider commands already sent when processing the container

---

hadoop-ozone/dist/src/main/smoketest/s3/bucketlist.robot
hadoop-ozone/dist/src/main/smoketest/s3/commonawslib.robot

Define "S3 tests set up" variable to indicate whether the common setup was done already.  Previously it relied on Ozone RPC calls, which can take a few seconds.  Also avoids repeatedly getting S3 secret to configure aws client.
https://issues.apache.org/jira/browse/HDDS-8152
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4406584085
Compare time elapsed in "Setup S3 tests", the first step in each S3 test:

HDDS-8152. Reduce S3 acceptance test setup time

---

.github/workflows/ci.yml
hadoop-ozone/dist/src/main/compose/ozone-ha/docker-config
hadoop-ozone/dist/src/main/compose/ozone-ha/test.sh
hadoop-ozone/dist/src/main/compose/ozone/test.sh
hadoop-ozone/dist/src/main/compose/ozonesecure-ha/docker-config
hadoop-ozone/dist/src/main/compose/ozonesecure-ha/test.sh
hadoop-ozone/dist/src/main/compose/ozonesecure/test.sh

1. Split HA acceptance tests into `HA-secure` and `HA-unsecure` (for `ozonesecure-ha` and `ozone-ha` environments, respectively).
2. Move some FS and S3 tests from `ozone` and `ozonesecure` to these HA environments.
The goal is to reduce time required for the longest split (currently `ozonesecure`) for faster overall CI runs.
https://issues.apache.org/jira/browse/HDDS-7975
Full CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4468991145

HDDS-7975. Rebalance acceptance tests

---

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerPersistence.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBTable.java

Currently container entry doesn't get removed from RocksDB after container gets deleted because in `RDBTable#deleteBatchWithPrefix`, `deleteWithBatch` gets called with iterator's `value` instead of the `key`. 
This change is to fix the bug by using correct parameter `key` to call `deleteWithBatch`.
https://issues.apache.org/jira/browse/HDDS-8173
* Unit test.

HDDS-8173. Fix to remove entries from RocksDB after container gets deleted.

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/KeyValueStreamDataChannel.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/StreamDataChannelBase.java

KeyValueStreamDataChannel add write data exception handling
https://issues.apache.org/jira/browse/HDDS-8220

HDDS-8220. [Ozone-Streaming] Trigger volume check on IOException in StreamDataChannelBase

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/CommandTargetOverloadedException.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECOverReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/MisReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisOverReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationTestUtil.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECMisReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECOverReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestMisReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisMisReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisOverReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java

Similar to ReplicateContainerCommands, we should limit the number of delete commands queued on a given datanode at any time. This PR will enforce the limit with a static config variable with a view to making this more dynamic later.
This change does not limit any delete container commands sent from the health check chain in RM. It only affects deletes for the Ratis and EC Over Replication Handlers, which should drive the bulk of the deletes.
Note that delete container replicas from the balancer are not throttled. The balancer issues moves in a controlled way, and its deletes are triggered when a replication completes. Therefore its deletes are naturally throttled by the rate of completion of the replicated commands. It will not flood the cluster with deletes like could happen when a …

HDDS-8233. ReplicationManager: Throttle delete container commands from over-replication handlers

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/KeyDeletingService.java

The directory deleting service has an info log that displays a summary of the run when some amount data is deleted. The key deleting service only logs this at the debug level. It should have an info log that prints a summary of the number of keys deleted if it is nonzero.
For reference, the corresponding line in directory deleting service is [here](https://github.com/apache/ozone/blob/5eead92666b374c4bb912f332488acb23f9a81df/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/DirectoryDeletingService.java#L208)
HDDS-8245
No tests added since this is a simple logging change.

HDDS-8245. Info log for keyDeletingService when nonzero number of keys are deleted.

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/AWSV4AuthValidator.java

Due to the high cost of creating and initializing Mac instances, S3 token validation can be a bottleneck in OM latencies for S3 use cases.
```
Mac mac = Mac.getInstance(HMAC_SHA256_ALGORITHM);
mac.init(signingKey); 
```
Caching Mac instances in ThreadLocal (as they are stateful) and reusing them eliminates the need to create and initialize these objects from scratch, mitigating the high cost of S3 token validation and significantly reducing overhead while improving overall performance.
https://issues.apache.org/jira/browse/HDDS-8154
Existing UTs

HDDS-8154. Perf: Reuse Mac instances in S3 token validation

---

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/cert/ListSubcommand.java
hadoop-ozone/dist/src/main/smoketest/security/admin-cert.robot

https://issues.apache.org/jira/browse/HDDS-8042
Output before patch
```
bash-4.2$ ozone admin cert list 
Total 11 valid certificates: 
SerialNumber      Valid From                     Expiry                         Subject                                                                                                       
1                 Mon Mar 20 06:20:20 UTC 2023   Thu Apr 27 06:20:20 UTC 2028   CN=scm@scm1.org,OU=d2a1c17f-34cb-4a0e-af0f-4d28353f1a6c,O=CID-148b1564-3abc-462b-8389-2a7b6ac6c733            
87303630914       Mon Mar 20 06:20:21 UTC 2023   Thu Apr 27 06:20:21 UTC 2028   CN=scm-sub@scm1.org,OU=d2a1c17f-34cb-4a0e-af0f-4d28353f1a6c,O=CID-148b1564-3abc-462b-8389-2a7b6ac6c733        
109107860257      Mon Mar 20 06:20:43 UTC 2023   Thu Apr 27 06:20:43 UTC 2028 …
```

HDDS-8042. Display certificate issuer in cert list command.

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/RemoveSCMRequest.java
hadoop-hdds/interface-client/src/main/proto/hdds.proto
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManagerImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManagerStub.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisServer.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisServerImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/SCMHAManagerImplTest.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestReplicationAnnotation.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestSCMHAManagerImpl.java

This change introduces support for `removeSCM` in `SCMRatisServer`.
As part of SCM decommissioning, the Ratis set configuration should be executed with a new peer list to remove the decommissioning SCM node from the Raft Ring.
`SCMRatisServer` should expose the method to perform remove node which should call Ratis set configuration with a new peer list.
`notifyConfigurationChanged` on `SCMStateMachine` should be idempotent as this can be called during SCM restart while applying the Raft log.
HDDS-7853
Unit tests added

HDDS-7853. Add support for RemoveSCM in SCMRatisServer.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelinePlacementPolicy.java

Log improvement adding excludedNodes for pipeline creation
https://issues.apache.org/jira/browse/HDDS-8148
E2E test with debug creating similar scenario and checked logs.

HDDS-8148. Improve log for Pipeline creation failure

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLog.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/SCMBlockDeletingService.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DeadNodeHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestDeletedBlockLog.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestDeadNodeHandler.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/TestECContainerRecovery.java

1. Filter of transactions belonging to healthy and In-Service DN, and previous delete transaction command already handled in heartbeat
2. Removal of commands in command queue for the DN which is dead
https://issues.apache.org/jira/browse/HDDS-8155
Unit test is added for the cases, integration test for success and E2E test observing the behavior for DN down case for retry

HDDS-8155. SCM Block deleting service add transaction blocks for stale/dead/decommissioning DNs

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestLDBCli.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/DBScanner.java

Change default schema to V3 for ozone debug ldb container db. For V2 containers need to give option "-d=V2" while running tool.
https://issues.apache.org/jira/browse/HDDS-8098
Patch tested using TestLDBCli test cases for both testDNDBSchemaV3() and testDNDBSchemaV2() as well as built locally and tested using docker compose by running ldb commands.

HDDS-8098. Make Schema V3 as default in ozone debug ldb for container db.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/MoveManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestMoveManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/MiniOzoneChaosCluster.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java

Right now, "hdds.scm.replication.command.deadline.factor" is a fraction. For long durations such as 60 minutes, the difference between SCM deadline and Datanode deadline will be 60 - 60 * 0.9, which is 6 minutes. This is a significant difference, so perhaps this configuration should be a duration instead, like 30 seconds.
Currently the APIs provided by RM expose the DN deadline as a parameter. We could remove this and just let the RM decide a deadline for commands in the DN.
This PR removes the parameter hdds.scm.replication.command.deadline.factor and also passing the datanodeDeadline via the various methods. Instead we now have hdds.scm.replication.event.timeout.datanode.offset, defaulting to 30s, which is the amount of time we subtract from event.timeout (SCM deadline) to get the …

HDDS-8230. Let ReplicationManager decide the timeout for commands in Datanodes

---

hadoop-ozone/dist/src/main/compose/ozonesecure-ha/docker-config
hadoop-ozone/dist/src/main/compose/ozonesecure-mr/docker-config

Get rid of unnecessary 5 seconds sleep at container startup in `ozonesecure-ha` and `ozonesecure-mr` environments, which also caused the following warning:
```
ozone.scm.client.address should be set in ozone-site.xml or with the --scm option
```
See [details](https://issues.apache.org/jira/browse/HDDS-8255?focusedCommentId=17703983&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17703983) in Jira.
https://issues.apache.org/jira/browse/HDDS-8255
Tested locally:
```
$ cd hadoop-ozone/dist/target/ozone-1.4.0-SNAPSHOT/compose/ozonesecure-ha
$ SCM=scm1.org
$ docker-compose up -d ${SCM}; for i in {1..5}; do docker-compose exec ${SCM} grep scm.service /etc/hadoop/ozone-site.xml; sleep 1; done
Starting ozonesecure-ha_scm1.org_1 ... done …
```

HDDS-8255. Remove unnecessary sleep at secure container startup

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/util/ClosableIterator.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SnapshotChainManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/PersistentList.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/RocksDbPersistentList.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/RocksDbPersistentSet.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestRocksDbPersistentList.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestRocksDbPersistentSet.java

RocksObject leaks in snapshot.
```
2023-03-23 09:44:20,288 [Finalizer] WARN  managed.ManagedRocksObjectUtils (ManagedRocksObjectUtils.java:assertClosed(54)) - RocksIterator is not closed properly
StackTrace for unclosed instance: org.apache.hadoop.hdds.utils.db.managed.ManagedObject.<init>(ManagedObject.java:35)
org.apache.hadoop.hdds.utils.db.managed.ManagedRocksIterator.<init>(ManagedRocksIterator.java:28)
org.apache.hadoop.hdds.utils.db.managed.ManagedRocksIterator.managed(ManagedRocksIterator.java:32)
org.apache.hadoop.hdds.utils.db.RocksDatabase.newIterator(RocksDatabase.java:757)
org.apache.hadoop.hdds.utils.db.RDBTable.iterator(RDBTable.java:167)
org.apache.hadoop.hdds.utils.db.TypedTable.iterator(TypedTable.java:286)
org.apache.hadoop.ozone.om.SnapshotChainManager.loadFromSnapshotI …
```

HDDS-8251. RocksIterator is not closed properly in snapshot

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestOMSnapshotDAG.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotCreateResponse.java

Snapshot DAG tracking RocksDB listener optimization 1 of 2.
Only track active DB compaction when there is at least one snapshot in OM DB.
https://issues.apache.org/jira/browse/HDDS-7559
- Added new test case.
- Existing test cases where compactions are tracked and utilized should pass.

HDDS-7559. [Snapshot] Skip compaction tracking when no Ozone snapshot exists

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ECReplicationConfig.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ReplicationConfigValidator.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/client/TestReplicationConfig.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/client/TestReplicationConfigValidator.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneClient.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestContainerCommandsEC.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestECKeyOutputStream.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/TestECContainerRecovery.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java

Limit EC chunk size to a few sensible options between 512KB and 4MB by default, but allow admins to override it in config.
Change EC replication string to display chunk size in KBs.
https://issues.apache.org/jira/browse/HDDS-7122
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4503959940

HDDS-7122. Add validation for EC chunk size

---

.github/workflows/ci.yml
hadoop-ozone/dist/src/main/license/bin/LICENSE.txt
hadoop-ozone/dist/src/main/license/bin/NOTICE.txt
hadoop-ozone/dist/src/main/license/jar-report.txt
hadoop-ozone/recon-codegen/pom.xml
pom.xml

In order to support compilation of Ozone under JDK 17, the following changes are required:
- Bump maven-shade-plugin to 3.4.1
- Bump guice to 5.1.0
- Remove guice-multibindings (no longer exists [since guice 4.2](https://github.com/google/guice/wiki/Multibindings))
https://issues.apache.org/jira/browse/HDDS-8263
- Compilation passed with JDK 17 on CI on my fork's [other test branch](https://github.com/smengcl/hadoop-ozone/commits/HDDS-8248-jdk17-compile)
- https://github.com/smengcl/hadoop-ozone/actions/runs/4497681697/jobs/7913886545
- Compilation passed locally with Zulu JDK 1.8.0_362 aarch64
- Compilation should pass in this PR CI with JDK 11 (unchanged)

HDDS-8263. [JDK17] Bump guice to 5.1.0, maven-shade-plugin to 3.4.1, remove guice-multibindings

---

hadoop-hdds/rocks-native/pom.xml
hadoop-hdds/rocks-native/src/CMakeLists.txt

Currently RocksDB lib and tools JNI is building with `DEBUG_LEVEL=1` (the default).
Explicitly set it to `DEBUG_LEVEL=0` and make appropriate CMakeLists changes.
https://issues.apache.org/jira/browse/HDDS-8279
- Compilation passed locally:
```
$ mvn clean install -DskipTests -e -Dmaven.javadoc.skip=true -DskipShade -Drocks_tools_native
...
[INFO] --- antrun:1.3:run (build-rocksjava) @ hdds-rocks-native ---
[INFO] Executing tasks
[exec] $DEBUG_LEVEL is 0
[exec] $DEBUG_LEVEL is 0
[exec]   CC       db_stress_tool/db_stress.o
[exec]   CC       tools/block_cache_analyzer/block_cache_trace_analyzer.o
[exec]   CC       tools/trace_analyzer_tool.o
...
[INFO] Apache Ozone HDDS RocksDB Tools .................... SUCCESS [01:23 min]
[INFO] Apache Ozone ....................................... SUCCESS …
```

HDDS-8279. [Snapshot] Switch RocksDB Tools JNI to release build

---

dev-support/ci/selective_ci_checks.bats
dev-support/ci/selective_ci_checks.sh

Selective CI should not skip _integration_ and _unit_ tests for changes to `junit.sh`, which is a common implementation of these two checks, like it did in [this run](https://github.com/apache/ozone/actions/runs/4490859276?pr=4449).
https://issues.apache.org/jira/browse/HDDS-8244
Added test case in bats test.
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4491964343/jobs/7901188422#step:6:25

HDDS-8244. Selective checks: handle change in junit.sh

---

.github/workflows/ci.yml
hadoop-ozone/dev-support/checks/build.sh
hadoop-ozone/dev-support/checks/findbugs.sh
hadoop-ozone/dev-support/checks/junit.sh
hadoop-ozone/dist/src/main/compose/test-all.sh

Coverage check is executed only for commits in `apache/ozone`, i.e. neither for pull requests in `apache/ozone`, nor for any event in forks (HDDS-4801).  However, coverage data is still collected during test runs, which (1) uses space unnecessarily in result bundles, and (2) takes a tiny bit of time to execute.  This PR disables JaCoCo for the cases when its output is ignored.
https://issues.apache.org/jira/browse/HDDS-8240
JaCoCo is executed in CI simulating commit on `apache/ozone` repo:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4489193839/jobs/7897102199#step:5:3513
but skipped in fork:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4489001536/jobs/7897164734#step:5:3560
`jacoco*.exec` files are not present in the artifacts produced by the latter.

HDDS-8240. Disable JaCoCo for PRs and in forks

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBBatchOperation.java

OM rocksdb uses a lot of space.
This PR adds a cache in RDBBatchOperation for caching the put ops.  When there are multiple ops with the same key, it will overwrite the previous op in the cache so the previous op won't be written into RocksDB.  In a test, the cache can reduce the disk usage in OM rocksdb of a single upload with 1000 parts from 755MB to 23MB.
https://issues.apache.org/jira/browse/HDDS-8128
The is an optimization.  The existing test already has covered.  Also have tested this with https://github.com/apache/ozone/compare/ozone-1.3...szetszwo:ozone:multipartUpload manually.

HDDS-8128. Deduplicate the ops in RDBBatchOperation.

---

CONTRIBUTING.md

We have included an IntelliJ code style export since HDDS-3674 (thanks @captainzmc).
Prompted by https://github.com/apache/ozone/pull/4376/files#r1145395241, we should include a few lines of instructions in the markdown doc as well.
https://issues.apache.org/jira/browse/HDDS-8281
n/a

HDDS-8281. Add IntelliJ code style scheme import recommendation in CONTRIBUTING.md

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneAclUtils.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketSetPropertyRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/acl/OzoneNativeAuthorizer.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/acl/TestParentAcl.java

1. Volume permission changed to READ for multiple operation (towards Ranger permission similarity)
2. quota set and clear can be done only by admin and owner for Native ACL
https://issues.apache.org/jira/browse/HDDS-7697
UT cases and E2E case is verified

HDDS-7697. Restrict change of bucket properties to owner and admins in NativeACL

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/HASecurityUtils.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/InterSCMGrpcClient.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/InterSCMGrpcProtocolService.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerRatisServer.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java

After [Use keyManager and trustManager provided ...](https://issues.apache.org/jira/browse/HDDS-7590) couple of places remained that used keys/certificates for communication. This should be changed to use key/trustmanagers instead. This comes with the advantage of allowing certificate bundles to be used during the communication.
[HDDS-7573](https://issues.apache.org/jira/browse/HDDS-7573)
Existing tests cover communication, and a simple sanity check was done on a local cluster to see basic functionality still working.
Additional testing will be performed in: [HDDS-8266](https://issues.apache.org/jira/browse/HDDS-8266)

HDDS-7573. Use keyManager and trustManager provided by keyStoreFactory in Ratis group

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java

Close `BlockIterator` in `KeyValueHandler#logBlocksIfNonZero`.
https://issues.apache.org/jira/browse/HDDS-8258
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4509916244

HDDS-8258. RocksIterator not closed properly in KeyValueHandler.logBlocksIfNonZero

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHADBTransactionBufferImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHADBTransactionBufferStub.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManagerImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManagerStub.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java

* Close `DBTransactionBuffer` in `SCMHAManagerImpl`
* Close `SCMHAManager` even if SCM is not started, since it needs to close the eagerly created `DBTransactionBuffer`
* Similarly, `ReplicationManager` is eagerly started, so it needs to be stopped even if SCM is not started
* Close previous `BatchOperation` in `SCMHADBTransactionBufferImpl`, as new one is created when snapshot is installed
* Close `ManagedWriteBatch` in `SCMHADBTransactionBufferStub` (used for tests and Recon) even if `DBStore` is not created
https://issues.apache.org/jira/browse/HDDS-8275
`TestSCMInstallSnapshot` and `TestSCMInstallSnapshotWithHA` do not log not properly closed `ManagedWriteBatch`.
```
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 120.839 s - in …
```

HDDS-8275. ManagedWriteBatch is not closed properly in SCMHADBTransactionBuffer

---

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/pnpm-lock.yaml

Upgrade moment.js to 2.29.4 due to the CVEs
https://issues.apache.org/jira/browse/HDDS-8288
https://github.com/rohit-kb/ozone/actions/runs/4500928021
Recon UI also seems okay upon thorough exploration.

HDDS-8288. Upgrade moment.js to 2.29.4

---

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStorageContainerManagerFacade.java

Warning about not closed object can be seen in `TestReconScmSnapshot` and/or `TestReconScmHASnapshot`
Close previous `DBStore` when being replaced in `ReconStorageContainerManagerFacade`.
https://issues.apache.org/jira/browse/HDDS-8272
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4510251505

HDDS-8272. DBStore not closed properly in ReconStorageContainerManagerFacade

---

hadoop-ozone/dist/src/main/smoketest/createmrenv.robot

Increase timeout for the setup required for MapReduce test to prevent intermittent failure.
https://issues.apache.org/jira/browse/HDDS-8274
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4515003631

HDDS-8274. Intermittent timeout in acceptance-MR test setup

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/StaleRecoveringContainerScrubbingService.java

Check whether container exists or not before making RECOVERING container unhealthy .
https://issues.apache.org/jira/browse/HDDS-7842
Verified in testScrubbingStaleRecoveringContainers
1.Create few containers in RECOVERING state and store in containerSet.
2.Remove one container using containerSet.removeContainer(containerId)
3.Run StaleRecoveringContainerScrubbingService task.
4.Before fix, since container was already deleted before StaleRecoveringContainerScrubbingService task execution, containerSet.getContainer returns null and throw NPE. After fix it will ignore if container is already removed.

HDDS-7842. NPE in StaleRecoveringContainerScrubbingService

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzonePathCapabilities.java
hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java
hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java
hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java
hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java

Implemented PathCapabilities interface APIs in ofs/o3fs.
Three existing capabilities are added: FS_ACLS, FS_CHECKSUMS and FS_SNAPSHOTS. This is implemented following the utility class DfsPathCapabilities in Hadoop HDFS.
The lease recovery and safemode capabilities are not yet included. Will add in a future jira.
https://issues.apache.org/jira/browse/HDDS-8193
Unit tests

HDDS-8193. Ozone file systems to support Hadoop's PathCapabilities interface

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmKeyInfo.java
hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto

Add a isHsync field in OmKeyInfo. This field is not persisted in RocksDB but rather is inferred from the metadata if it has HSYNC_CLIENT_ID field.
https://issues.apache.org/jira/browse/HDDS-7781
Unit tests

HDDS-7781. Change Get Key Info to return HSync info

---

hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdb/util/RdbUtil.java
hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java
hadoop-ozone/dist/src/main/smoketest/snapshot/snapshot-sh.robot
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/PersistentMap.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/RocksDbPersistentList.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/RocksDbPersistentMap.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffJob.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotUtils.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestRocksDbPersistentList.java

This change is to offload the snapshot diff process to the background processor and release the request thread. This is needed to make sure that client request doesn't timeout in case diff is huge and takes more than max request timeout.
A fixed size thread pool executor is added to offload the snapDiff processing. Snapdiff jobs are submitted to the executor and request thread is release with a wait time along with job status in response. Client will retry after the wait time in case job status is In_Progress, Rejected or Failed.
Flow of the state machine is as in the following diagram.
On OM restarts, we load all the `IN_PROGRESS` jobs, which were in progress before OM went down, and send them to executor. We don't need to load `QUEUED` jobs because responses for queued jobs were never …

HDDS-7952. [Snapshot] Server side changes to add job status and wait time to mimic the async behaviour for snapshot diff API.

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBStore.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBStoreBuilder.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBUpdatesWrapper.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStore.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBTableStore.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestTypedRDBTableStore.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/DBUpdates.java
hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/OzoneManagerServiceProviderImpl.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/spi/impl/TestOzoneManagerServiceProviderImpl.java

Observations about below code in `org.apache.hadoop.hdds.utils.db.RDBStore#getUpdatesSince(long, long)`
```
dbUpdatesWrapper.addWriteBatch(result.writeBatch().data(),
result.sequenceNumber());
```
Above code is in while loop for all log files getting iterated and each log file batch allocates a byte[] array which results in accumulating the data in dbUpdatesWrapper in the form of dataList. This will increase JVM heap due to dataList growing with each allocated byte[] array getting added in dataList for dbUpdatesWrapper object and may further fail to allocate any byte[] array in the log iterator loop on calling "result.writeBatch().data()" code. If Recon has limited heap memory, this may fail frequently and may even fall into worse situation where a first call to …

HDDS-8195. RDBStore.getUpdatesSince() throws RocksDBException: Requested array size exceeds VM limit

---

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/ClusterStateEndpoint.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/ClusterStateResponse.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/OMMetadataManagerTestUtils.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java

- When a key is deleted, it is not immediately removed from the metadata but marked for deletion and moved to the DeletedTable. The KeyDeletingService sends requests to delete the corresponding data blocks associated with the keys. Once Recon detects the deletion, it updates its metadata store to reflect the change and retains a record of the deleted key in the DeletedTable for administrators to query.
- This information can be useful for auditing, compliance, and troubleshooting purposes. **_Hence in short the main purpose is to get a quick idea of the deletion progress._**
- This information will be displayed on the overview page of recon which gets populated with the information provided by the `ClusterStateEndpoint` 
- The Jira is coming out of the following discussion :- …

HDDS-7994. Expose information via the ClusterState endpoint on keys and Directories marked for deletion

---

hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotMoveDeletedKeysRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotMoveDeletedKeysResponse.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/SnapshotDeletingService.java

To move entries from the current snapshot's `snapshotRenamedKeyTable` to the next snapshot's `snapshotRenamedKeyTable` inside `SnapshotDeletingService`
https://issues.apache.org/jira/browse/HDDS-8290
The patch was tested with existing tests.

HDDS-8290. [Snapshot] Merge entries from snapshotRenamedKeyTable to next snapshot.

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/ECFileChecksumHelper.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/ReplicatedFileChecksumHelper.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileChecksum.java

`ECFileChecksumHelper#getChunkInfos` copies the original EC pipeline and limits nodes to specific replicas.  However, the list of "nodes in order", used for topology-aware read, still contains all original nodes.  Thus it may happen that read is attempted from the wrong node.
This patch updates "nodes in order" in the copy to reflect the same set of nodes as the unordered one.
Also remove a stray placeholder from the error message:
`Fail to get block checksum for ... checksum combine mode : {}COMPOSITE_CRC`
https://issues.apache.org/jira/browse/HDDS-8276
Updated the integration test `TestOzoneFileChecksum` to cover both topology-aware and regular read.
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4553955626

HDDS-8276. EC file checksum calculation fails with topology-aware read enabled

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java

Close `RocksDBCheckpointDiffer`, ignore compaction events in closed state.
Move some statements which I don't think need protection out of the `synchronized` blocks.
https://issues.apache.org/jira/browse/HDDS-8282
No crash in 10x10 runs with the fix (but had failures due to HDDS-8035):
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4551460230
Had 18 crashes in 17 of the 100 runs without the fix:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4545915739
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4551404963

HDDS-8282. [Snapshot] Intermittent DB crash in RocksDBCheckpointDiffer

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/TestHddsSecureDatanodeInit.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/token/TestOzoneBlockTokenSecretManager.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/authority/TestDefaultCAServer.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/TestDefaultCertificateClient.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/TestDnCertificateClientInit.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/HASecurityUtils.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecureOzoneCluster.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/server/TestContainerServer.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestSecureOzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerRatisServer.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/TestOmCertificateClientInit.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/TestOzoneDelegationTokenSecretManager.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServer.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/StorageContainerServiceProviderImpl.java

[HDDS-7874](https://issues.apache.org/jira/browse/HDDS-7874) revealed that the Certificate client instances in the system are not closed properly.
This PR adds the close() call for all CertificateClient instances that are created either in tests or during normal operations, to ensure that the internal certificate lifetime monitor task executor thread is shut down correctly once the client is not used anymore.
https://issues.apache.org/jira/browse/HDDS-8134
Existing tests should cover.
Added an additional test to check on the bg thread creation and closing the CertClient
Also I ran the TestHddsSecureDatanodeInit.testCertificateRotation test 300 times without failure locally, before patch, from 100 runs I was able to see 4 failures.

HDDS-8134. Certificate clients are not correctly closed.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/SimpleMockNodeManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationTestUtil.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/container/testutils/ReplicationNodeManagerMock.java

EC Reconstruction commands should be throttled in a similar way to replicate container commands, so that a limited number of commands can be sent to any given node.
As reconstruction and replication share the same queue on the datanode, the datanode could be filled with a combination of replication and reconstruction commands, so the sendThrottledReplicationCommand method will also need adjusted to consider the number of reconstructions commands queue when checking the limit.
To allow both reconstruction and replication commands to share the same queue, the reconstruction command count is multiplied by a weighting factor to reflect its extra expense of processing. In this PR each reconstruction command has a weighting of 3.
https://issues.apache.org/jira/browse/HDDS-8309
New tests added

HDDS-8309. ReplicationManager: Throttle EC Reconstruction commands

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBStoreBuilder.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDBConfiguration.java

https://issues.apache.org/jira/browse/HDDS-8313
Use docker-compose do the test manually
1. start a docker-compose ozone cluster
2. open the latest OPTION file of rocksdb of every service, verify WAL_ttl_seconds is 1200 and WAL_size_limit_MB 0 
3. stop ozone cluster
4. add following  properties in docker-config file
hadoop.hdds.db.rocksdb.WAL_size_limit_MB 100MB
hadoop.hdds.db.rocksdb.WAL_ttl_seconds   1800 
5. start the ozone cluste again
6. open the latest OPTION file of rocksdb of every service, verify WAL_ttl_seconds is 1800 and WAL_size_limit_MB 104857600(100MB)

HDDS-8313. Support rocksdb WAL ttl and size limit configuration
