apache/ozone

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java

Improve DB related handle closure by calling cancelAllBackgroundWork() and explicitly closing all compaction listeners.
Adding snapshot label to this because the DB compaction listener is introduced with Ozone snapshot feature.
Context: https://github.com/apache/ozone/pull/4492#issuecomment-1489502614
It should be safe to call `cancelAllBackgroundWork()`. From RocksDB [wiki](https://github.com/facebook/rocksdb/wiki/RocksDB-FAQ):
> Q: Is it safe to close RocksDB while another thread is issuing read, write or manual compaction requests?
> A: No. The users of RocksDB need to make sure all functions have finished before they close RocksDB. You can speed up the waiting by calling CancelAllBackgroundWork().
I presume any cancelled background work would be picked back up when the DB is loaded …

HDDS-8323. [Snapshot] cancelAllBackgroundWork and close listeners in RDBStore#close

---

hadoop-ozone/dist/src/main/license/jar-report.txt
hadoop-ozone/ozone-manager/pom.xml
pom.xml

Ranger depends on jackson version 1.9.13. Please check https://github.com/apache/ozone/pull/4497
https://issues.apache.org/jira/browse/HDDS-8320
Ozone Internal tests

HDDS-8320. Fix ranger jackson version conflict

---

hadoop-ozone/dist/src/main/smoketest/ec/basic.robot
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFSInputStream.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientMultipartUploadWithFSO.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmMetrics.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneConfigUtil.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileCreateRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3InitiateMultipartUploadRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3InitiateMultipartUploadRequestWithFSO.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOzoneConfigUtil.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerDoubleBufferWithOMResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/OMRequestTestUtils.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/TestOMClientRequestWithUserInfo.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestBucketRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestOMBucketCreateRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestOMBucketCreateRequestWithFSO.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCreateRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyRequest.java

Validate the replication config provided by client, at the server-side.
https://issues.apache.org/jira/browse/HDDS-8273
Added unit test and acceptance test.
CI (before acceptance test):
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4572695466
CI (with acceptance test, in progress):
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4573559120

HDDS-8273. EC: Validate replication config at server-side

---

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/ListInfoSubcommand.java
hadoop-ozone/dist/src/main/smoketest/admincli/datanode.robot

Json formatting option added for `ozone admin datanode list` command 
```
bash-4.2$ ozone admin datanode list --help
Usage: ozone admin datanode list [-hV] [--json] [-id=<scmServiceId>]
[--id=<uuid>] [--ip=<ipaddress>]
[--node-state=<nodeState>]
[--operational-state=<nodeOperationalState>]
[--scm=<scm>]
List info of datanodes
-h, --help             Show this help message and exit.
-id, --service-id=<scmServiceId>
ServiceId of SCM HA Cluster
--id=<uuid>        Show info by datanode UUID.
--ip=<ipaddress>   Show info by ip address.
--json             Show info in json format
--node-state=<nodeState>
Show info by datanode NodeState( HEALTHY, STALE, DEAD)
--operational-state=<nodeOperationalState>
Show info by datanode NodeOperationalState(IN_SERVICE,
DECOMMISSIONING, DECOMMISSIONED, …
```

HDDS-8185. ozone admin datanode list should have a json option for output

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java

When sending throttled replication / reconstruction commands, we know if the target node is at the replication task limit. If it is, we should add it to an exclude list in replicationManager.
When the DN heartbeats, it triggers a callback to RM, which lets it check if the node should be removed from the exclude list.
The exclude list can then be fed into the node selection for reconstruction tasks, so it can avoid picking nodes which are already overloaded as targets, but that will be another Jira.
https://issues.apache.org/jira/browse/HDDS-8334
New unit tests added.

HDDS-8334. ReplicationManager: Add nodes to exclude list if they are overloaded

---

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestListParts.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectGet.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestPermissionCheck.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/metrics/TestS3GatewayMetrics.java

Make `ObjectEndpoint#get` not accept an HTTP request body so that we no longer see the following WARNING.
```
ozone-s3g-6bd9d99555-lgmsl: WARNING: The following warnings have been detected: WARNING: A HTTP GET method, public javax.ws.rs.core.Response org.apache.hadoop.ozone.s3.endpoint.ObjectEndpoint.get(java.lang.String,java.lang.String,java.lang.String,int,java.lang.String,java.io.InputStream) throws java.io.IOException,org.apache.hadoop.ozone.s3.exception.OS3Exception, should not consume any entity. 
```
https://issues.apache.org/jira/browse/HDDS-8354
I verified we never observe the warning the master branch with this patch.

HDDS-8354. Avoid WARNING about ObjectEndpoint#get

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/pipeline/Pipeline.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/ECFileChecksumHelper.java
hadoop-ozone/dist/src/main/smoketest/debug/ozone-debug.robot

Due to same root cause as HDDS-8276, `ozone debug read-replicas` may give wrong results with topology-aware read enabled.  It creates a single-node copy of the original pipeline for each replica, but only updates `nodes`, not `nodesInOrder`.  If the replica is stale (offline but not yet dead), read is attempted and fails, and the client checks if there are any fallback nodes.  There should be none left (single-node pipeline), but with topology-aware read enabled the other two nodes are still present in the list.
This PR moves the fix that was originally added for EC file checksum to the pipeline copy builder, so that all usages get fixed (currently only these two cases change nodes in the copy pipeline).
https://issues.apache.org/jira/browse/HDDS-8364
Updated relevant smoketest to enable …

HDDS-8364. ReadReplicas may give wrong results with topology-aware read enabled

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DefaultCertificateClient.java

The intent of the renewLock in the DefaultCertificateClient is to ensure no more than one thread changes the on disk certificate material at a given time. The problem is that the lock is belonging to an instance of the CertificateClient implementation, and with that there might be multiple instances from the lock.
As we do not use any of the properties of a ReentrantLock, I simply think we should synchronize the renewal and the on disk operations on the class.
In the meantime, I switched to shutdownNow instead of shutDown in the executor, after HDDS-8134 we do not have multiple executors running at the same time, but the service after close should not schedule any new runs but should finish the current run. This is not a foolproof implementation, but a good enough one for now. We are …

HDDS-8135. Incorrect synchronization during certificate renewal in DefaultCertificateClient.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java

`getContainerReplicationHealth()` in `ReplicationManager` does not set `pendingOps` and `maintenanceRedundancy` when building `ContainerCheckRequest`. This leads to errors such as:
```
scm_1         | java.lang.NullPointerException
scm_1         | 	at java.base/java.util.Collections$UnmodifiableCollection.<init>(Collections.java:1030)
scm_1         | 	at java.base/java.util.Collections$UnmodifiableList.<init>(Collections.java:1303)
scm_1         | 	at java.base/java.util.Collections.unmodifiableList(Collections.java:1290)
scm_1         | 	at org.apache.hadoop.hdds.scm.container.replication.ContainerCheckRequest.<init>(ContainerCheckRequest.java:45)
scm_1         | 	at org.apache.hadoop.hdds.scm.container.replication.ContainerCheckRequest.<init>(ContainerCheckRequest.java:31)
scm_1 …
```

HDDS-8359. ReplicationManager: Fix getContainerReplicationHealth() so that it builds ContainerCheckRequest correctly

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerSelectionCriteria.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancerTask.java

`ContainerBalancerSelectionCriteria` has a Comparator `orderContainersByUsedBytes` which is used for comparing containers on the basis of used space. This comparator calls `isContainerMoreUsed`, which does not have consistent behaviour when used space for two containers is equal.
This bug was exposed when fixing the setup of `TestContainerBalancerTask`.
`createReplicasForContainers()` in `TestContainerBalancerTask` creates additional container replicas but does not add them to `datanodeToContainersMap`, the map being used to track these. This PR intends to fix the bug and the test setup.
https://issues.apache.org/jira/browse/HDDS-8358

HDDS-8358. Fix the space usage comparator in ContainerBalancerSelectionCriteria

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java

`ReplicationManager` creates `ContainerReplicaOp` in `adjustPendingOpsAndMetrics`. For replicate command, the target datanode in the `op` should be the datanode that reports back addition of a replica. However currently the target datanode is being set as the datanode that the command is being sent to. This PR fixes this.
https://issues.apache.org/jira/browse/HDDS-8368
Added UT.
Draft because I'm waiting for CI in my fork: https://github.com/siddhantsangwan/ozone/actions/runs/4607466302

HDDS-8368. ReplicationManager: Create ContainerReplicaOp with correct target Datanode

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestOMSnapshotDAG.java

- `#testSkipTrackingWithZeroSnapshot` fails occasionally presumably because the compaction log directory isn't created yet.
e.g. https://github.com/apache/ozone/actions/runs/4540058938/jobs/8001489891?pr=3980
```
Error:  Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 52.179 s <<< FAILURE! - in org.apache.hadoop.ozone.freon.TestOMSnapshotDAG
Error:  org.apache.hadoop.ozone.freon.TestOMSnapshotDAG.testSkipTrackingWithZeroSnapshot  Time elapsed: 11.135 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: not <null>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
at org.junit.jupiter.api.Assertions.fail(Assertions.java:134)
at org.junit.jupiter.api.AssertNotNull.failNull(AssertNotNull.java:47)
at …
```

HDDS-8304. [Snapshot] Reduce flakiness in testSkipTrackingWithZeroSnapshot

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerSet.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/MutableVolumeSet.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerMetadataInspector.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/ContainerController.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/ContainerTestVersionInfo.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerIntegrityChecks.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerMetadataInspector.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/container/ContainerCommands.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/container/InspectSubcommand.java

The KeyValueContainerMetadataInspector currently can be run by the option
`-Dozone.datanode.container.metadata.inspector=inspect` on datanode startup.
In this JIRA, we will allow to run with the `ozone debug` command.
https://issues.apache.org/jira/browse/HDDS-8039
Will add some new tests.

HDDS-8039. Allow container inspector to run from ozone debug.

---

hadoop-ozone/dist/src/main/compose/upgrade/README.md

Minor typos in the test doc were flagged in #4456. This is to fix them since that change was already merged.
HDDS-8375
N/A. Developer doc change only.

HDDS-8375. Fix typos in upgrade acceptance test README.

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java

openKey need not setKeyArgs two twice, `setKeyArgs` duplicated with line 693
https://issues.apache.org/jira/browse/HDDS-8397

HDDS-8397. openKey need not setKeyArgs twice

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerSelectionCriteria.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerTask.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/MoveManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancerTask.java

This PR enables balancing EC containers in `ContainerBalancer`. Since `MoveManager` has been integrated with ContainerBalancer now, we can support balancing EC containers.
Changes include:
1. Exclude EC containers from balancing in `ContainerBalancerSelectionCriteria` only if Legacy RM is enabled.
2. Add some `DEBUG` logs in `MoveManager`.
3. Fix a small bug in `ContainerBalancer` where it was logging a `Duration` instead of the long value of a config.
4. Update the setup in `TestContainerBalancerTask` to also create EC containers along with the RATIS containers it was already creating. Change some tests accordingly.
5. Disable Legacy RM in `TestContainerBalancerTask`, except in specific tests where we're testing both Legacy RM and `MoveManager`. …

HDDS-8170. Let ContainerBalancer consider EC containers for balancing

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java

Use the exclude list added in HDDS-8334 when getting the target nodes from the placement policy for EC Reconstruction commands in the ECUnderReplicationHandler.
https://issues.apache.org/jira/browse/HDDS-8351
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4595979508

HDDS-8351. ReplicationManager: Use RM exclude list when getting target nodes for reconstruction

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/MisReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/InsufficientDatanodesException.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECMisReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestMisReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisMisReplicationHandler.java

`MisReplicationHandler` execution may result in fewer than expected (but more than 0) commands to be sent.  It should throw an exception to let `ReplicationManager` requeue the task for retry later.
https://issues.apache.org/jira/browse/HDDS-8337
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4610104612

HDDS-8337. MisReplicationHandler should throw an exception if partially successful

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/BlockDeletingServiceMetrics.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java

- metrics added to count out of order delete transactions received from scm
https://issues.apache.org/jira/browse/HDDS-8228
Patch is verified with E2E to check metrics reporting

HDDS-8228. Add metric for out of order/retried delete transactions

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java

- while set userInfo in create request in pre-execute, getUserIfNotExist() method is used to populate process userName for non-rpc call for HSync feature, where it can be triggered during OpenKeyCleanupService additionally.
https://issues.apache.org/jira/browse/HDDS-8352
verified impact of existing test cases in integration test.

HDDS-8352. OM crash with NPE in OMKeyCommitRequest due to missing user info

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/OzoneContract.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/rooted/RootedOzoneContract.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/CapableOzoneFSOutputStream.java
hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java
hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java
hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java
hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java

Hsync is under development, not yet stable. Disable it by default to avoid interfering with existing applications.
https://issues.apache.org/jira/browse/HDDS-8302
unit test

HDDS-8302. Add a flag to disable hsync by default

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerSelectionCriteria.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancerTask.java

Currently, Container Balancer checks if a container is CLOSED, but does not check whether the replica being moved is also CLOSED. This should be checked to be consistent with ReplicationManager and avoid moving any un CLOSED replicas.
Change made: When selecting candidate containers (eligible for being moved because they satisfy selection criteria) from a source DN, filter out containers whose replica on that source is non CLOSED.
https://issues.apache.org/jira/browse/HDDS-8346
Added UT. 
Draft while waiting for CI in my fork: https://github.com/siddhantsangwan/ozone/actions/runs/4678046422

HDDS-8346. ContainerBalancer should move only CLOSED replicas

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/audit/OMAction.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/exceptions/OMException.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OzoneManagerProtocol.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestLeaseRecovery.java
hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMetrics.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMRecoverLeaseRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/file/OMRecoverLeaseResponse.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/upgrade/OMLayoutFeature.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/file/TestOMRecoverLeaseRequest.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java

Implement recoverLease() API that is similar to HDFS's one, which allows a client to forcefully close an open file. 
https://issues.apache.org/jira/browse/HDDS-7769
Unit tests

HDDS-7769. Implement client initiated lease recovery

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/MisReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationTestUtil.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisUnderReplicationHandler.java

In RatisUnderReplicationHandler, if the container is under-replicated by more than 1 replica, then we need to select 2 or more new copies. In the code getTargets():
```
private List<DatanodeDetails> getTargets(
RatisContainerReplicaCount replicaCount,
List<ContainerReplicaOp> pendingOps) throws IOException {
// DNs that already have replicas cannot be targets and should be excluded
final List<DatanodeDetails> excludeList =
replicaCount.getReplicas().stream()
.map(ContainerReplica::getDatanodeDetails)
.collect(Collectors.toList());
// DNs that are already waiting to receive replicas cannot be targets
final List<DatanodeDetails> pendingReplication =
pendingOps.stream()
.filter(containerReplicaOp -> containerReplicaOp.getOpType() ==
ContainerReplicaOp.PendingOpType.ADD) …
```

HDDS-8336. ReplicationManager: RatisUnderReplicationHandler should partially recover the container if not enough nodes

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBMetrics.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java

https://issues.apache.org/jira/browse/HDDS-8406
Run freon rk command to generate the OM updates during the test.  From the metrics data, we can see that the average size of rocksdb tx in OM is about 466 bytes(data size/sequence count). 
Initial metrics after om start
metrics after recon fetch DB update from om

HDDS-8406. Add OM DB update data size and sequence metrics

---

hadoop-ozone/dist/src/main/license/bin/LICENSE.txt
hadoop-ozone/dist/src/main/license/jar-report.txt
hadoop-ozone/recon-codegen/pom.xml
hadoop-ozone/recon/pom.xml

Exclude `spring-jcl` so as to suppress the following log.
```
ozone-recon-0: 2023-04-02 14:47:27,640 [main] WARN http.HttpRequestLog: Jetty request log can only be enabled using Log4j 
```
This issue happens because `spring-jcl` introduces [another implementation of LogFactory](https://github.com/spring-projects/spring-framework/blob/v5.3.23/spring-jcl/src/main/java/org/apache/commons/logging/LogFactory.java) and the implementation of `spring-jcl` can be loaded.
This PR takes the approach to exclude `spring-jcl` following [the instruction](https://github.com/spring-projects/spring-framework/blob/v5.3.23/spring-jcl/src/main/java/org/apache/commons/logging/package-info.java).
There would be other approaches.
- Fix [HttpRequestLog](https://github.com/apache/ozone/blob/53d8fe0e57f644989da927b6 …

HDDS-8357. Exclude spring-jcl to avoid dependency conflict

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestDirectoryDeletingServiceWithFSO.java
hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMDirectoriesPurgeRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotMoveDeletedKeysRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMDirectoriesPurgeResponseWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotMoveDeletedKeysResponse.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/AbstractKeyDeletingService.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/DirectoryDeletingService.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/SnapshotDeletingService.java

Clean up `deletedDirTable` of the snapshot in `SnapshotDeletingService`
- Move common functions between `SnapshotDeletingService` and `DirectoryDeletingService` to `AbstractKeyDeletingService`
- Add support for snapshots in `OMDirectoriesPurgeResponseWithFSO` and `OMDirectoriesPurgeRequestWithFSO`.
- Added support to move directories from the current snapshot to the next snapshot in `OMSnapshotMoveDeletedKeysRequest` and `OMSnapshotMoveDeletedKeysResponse`
https://issues.apache.org/jira/browse/HDDS-8317
Existing unit tests and CI

HDDS-8317. [Snapshot] DirectoryDeletingService should clean up Snapshot's deletedDirTable.

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmDirectoryInfo.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneListStatusHelper.java

ListStatus should use local cache copy. It should not use and update main cache which is used for DB updation.
https://issues.apache.org/jira/browse/HDDS-8292
Tested using below steps
1. Create file
2. Commit key
3. Rename file (cache value updated in OM memory, still value to be updated in Rocksdb which in this case happened at step  5)
4. List status is called, which reads from cache as well as updating cache value to full path(which it should not mean to do))-->At this step keyName is becoming wrong.
If X number of times, List status is called before commit to DB, X number of times keys are appended.
5. Write to DB(commit to DB for rename file operation) -->Since memory value is corrupted it inserts repeated keyName to DB.
After the fix, it works in local cache and doesn't impact …

HDDS-8292. Inconsistent key name handling for FSO bucket files.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java

`testListStatusWithIntermediateDir` intermittently fails because it finds two entries in the root directory instead of one:
```
AssertionError: expected:<1> but was:<2>
...
at org.apache.hadoop.fs.ozone.TestOzoneFileSystem.testListStatusWithIntermediateDir(TestOzoneFileSystem.java:645)
```
Including the file status list in the assertion message reveals that the unexpected extra entry is `.Trash`:
```
AssertionFailedError: Found [
FileStatus{path=o3fs://bucket40939.volume15180/.Trash; isDirectory=true; modification_time=1680592792546; access_time=1680592792546; owner=runner; group=runner; permission=rwxrwxrwx; isSymlink=false; hasAcl=false; isEncrypted=false; isErasureCoded=false},
FileStatus{path=o3fs://bucket40939.volume15180/object-dir; isDirectory=true; modification_time=1680592792548; …
```

HDDS-8370. Intermittent failure in TestOzoneFileSystem#testListStatusWithIntermediateDir

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java

Allow multiple trash checkpoints to account for items deleted for other test cases.
https://issues.apache.org/jira/browse/HDDS-8407
No failures of `testTrash` in 100 runs (only `testListStatusWithIntermediateDir` failed once, being fixed in HDDS-8370):
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4691530928
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4692326817

HDDS-8407. Intermittent failure in TestOzoneFileSystem#testTrash

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAMetrics.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMStateMachine.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestSCMHAMetrics.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/package-info.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestStorageContainerManagerHA.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/package-info.java

Add SCM HA metrics to `/jmx` and `/prom` endpoints.
```
{
"name": "Hadoop:service=StorageContainerManager,name=SCMHAMetrics",
"modelerType": "SCMHAMetrics",
"tag.NodeId": "3c8c82f5-524a-41f4-beea-8dcd868fbf91",
"tag.Hostname": "bca1fb37b8aa",
"SCMHALeaderState": 1
}
```
```
scmha_metrics_scmha_leader_state{nodeid="3c8c82f5-524a-41f4-beea-8dcd868fbf91",hostname="bca1fb37b8aa"} 1
```
Similar PR: https://github.com/apache/ozone/pull/4140.
https://issues.apache.org/jira/browse/HDDS-8363
- unit
- integration
- manual
Steps for manual test:
- start Docker cluster for HA environment `ozone-ha` and wait for it to be ready
- check if SCM HA metrics are initialized correctly
- stop SCM leader node and wait for new leader to be elected
- check if SCM HA metrics are updated correctly

HDDS-8363. Make SCM Ratis roles available in /prom endpoint

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/MisReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManagerUtil.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java

If an EC container is missing multiple indexes, and there are not enough nodes to recover all indexes, the process currently fails. It could be possible to recover some of the indexes and it will reduce the chances of data loss.
Therefore, if we cannot select enough nodes to recover all indexes, we should try to select enough nodes to recover N - 1 indexes, or N - 2, as recovering some of them is better than nothing.
https://issues.apache.org/jira/browse/HDDS-8333
New unit tests added and some existing tests modified to handle the change in behavior of throwing an exception on partial success.

HDDS-8333. ReplicationManager: Allow partial EC reconstruction if insufficient nodes available

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/RocksDBStoreMetrics.java

https://issues.apache.org/jira/browse/HDDS-8400
captured metrics from service /jmx endpoint

HDDS-8400. Expose rocksdb last sequence number through metrics

---

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/Gateway.java

Currently s3Gateway fails to come up if "ozone.http.basedir" is not defined.
https://issues.apache.org/jira/browse/HDDS-8253

HDDS-8253. Set ozone.metadata.dirs to temporary dir if not defined in S3 Gateway

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECMisReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/MisReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisMisReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECMisReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestMisReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisMisReplicationHandler.java

Push down the `sendReplicateCommands` from `MisReplicationHandler` into subclasses so that we can have different implementations for Ratis and EC.
Change implementation for Ratis to allow using all sources.
https://issues.apache.org/jira/browse/HDDS-8109
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4718760757

HDDS-8109. Seperate Ratis and EC MisReplication Handling

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/util/MetricUtil.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMPerformanceMetrics.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataReader.java

Introducing a new OM performance metric for capturing the latency of the `checkAccess` method in the `OmMetadataReader` class. This metric shall be crucial in measuring the time it takes for the security providers that extend support for Ozone ACLs to verify the access permissions granted for a given Ozone object.
This metric could potentially serve as a valuable tool in identifying any performance bottlenecks and improving efficiency.
https://issues.apache.org/jira/browse/HDDS-8270
The patch has been tested over a cluster that has the Ozone services running to see what the metric looks like. A sample screenshot of the Prometheus UI has been attached (for reference) capturing `om_performance_metrics_check_access_latency_ns_avg_time` (in nanoseconds):

HDDS-8270. Measure checkAccess latency for Ozone objects

---

hadoop-ozone/dist/src/main/smoketest/s3/commonawslib.robot
hadoop-ozone/dist/src/main/smoketest/s3/objecthead.robot
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java

Legacy buckets returned 404 for HEAD request via S3G for paths (which equates to directory objects if filesystem paths are enabled).
This restores the behavior
http://issues.apache.org/jira/browse/HDDS-8424
Tested manually, upstream code does not default filesystem paths to be enabled. Will create a separate set of tests for legacy buckets in a separate jira.

HDDS-8424. Restore legacy bucket behavior for directory objects.

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/TarContainerPacker.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestTarContainerPacker.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMDBCheckpointServlet.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconUtils.java

Fix OM HA RatisSnapshot creation to support large group ID's
https://issues.apache.org/jira/browse/HDDS-8385
Reproduced the problem by setting the group id of one of the snapshot files like so:
```
chgrp 1301600003 omNode-1/db.snapshots/checkpointState/om.db-c3e20908-b7ea-4650-a538-352c832ceeaa/000051.sst
```
Then confirmed the problem no longer occurs after the fix

HDDS-8385. Ozone can't process snapshot when service UID > 2097151.

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java

Use proper class for typecast while reading from cache. Added OmDirectoryInfo for reading directory info cache value to determine whether bucket is empty or not.
https://issues.apache.org/jira/browse/HDDS-8440
Create/Delete directory and FSO bucket and adding some delay in rocks db insertion so that values are read from cache.

HDDS-8440. Ozone Manager crashed when failed to delete FSO bucket.

---

dev-support/ci/selective_ci_checks.bats
dev-support/ci/selective_ci_checks.sh

CI should run all checks if `ci.yaml` is modified.
https://issues.apache.org/jira/browse/HDDS-8446
Added test case in _bats_ test suite.
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4735076871/jobs/8404851947

HDDS-8446. Selective checks: handle change in ci.yaml

---

.github/workflows/ci.yml

_build_ check in CI is frequently timing out in forks due to Maven cache miss (but not in `apache/ozone`).  Dependent checks (e.g. acceptance, kubernetes) can only be run after re-try.  To avoid wasting time, I propose increasing time limit for _build_ check from 30 to 45 minutes.
https://issues.apache.org/jira/browse/HDDS-8444
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4734224440/jobs/8402851285
_build_ check succeeded in 36m 6s, i.e. would have failed without this change.

HDDS-8444. Increase timeout of CI build

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java

This test was flaky because one thread trys to read the log output from another thread before the log has been generated.
I confirmed this by hitting a breakpoint on the assertion failure, then looking at the log and seeing that it had subsequently been updated by another thread.
The fix is to poll the log for a few seconds until it is updated to the expected contents.
https://issues.apache.org/jira/browse/HDDS-8355
Without the fix, I was able to reproduce the problem by running the test class 5 times repeatedly in intellij.
With the fix, I was unable to reproduce the problem after running it in intellij 50 times.
I also ran the CI 25 times without this failing.

HDDS-8355. Intermittent failure in TestOMRatisSnapshots#testInstallSnapshot

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECMisReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationTestUtil.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECMisReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestMisReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisUnderReplicationHandler.java

Both ECUnderReplicationHandler and ECMisReplicationHandler could hit a CommandTargetOverloaded exception when attempting to replicate a specific index from source to destination. When that happens, instead of failing immediately, it should attempt to replicate any other pending index it has, and then re-throw the last exception so the container is re-queued.
https://issues.apache.org/jira/browse/HDDS-8335
New unit tests added

HDDS-8335. ReplicationManager: EC Mis and Under replication handlers should handle overloaded exceptions

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/OzoneAdmins.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataReader.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneConfigUtil.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/acl/OzoneNativeAuthorizer.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/acl/TestOzoneAdministrators.java

Currently, there are admin users in the zone, which is a list of super read and super write users. As an administrator list, sometimes a only super read user list is also required
https://issues.apache.org/jira/browse/HDDS-8413
- unit test
Existing test classes.
- Functional test
etc: ozone-site.xml (add)
```
<property>
<name>ozone.super.read.usernames</name>
<value>bigdata_qa</value>
</property>
```
```
[hadoop@presto-test-006 ~]$ export HADOOP_USER_NAME=test
[hadoop@presto-test-006 ~]$ om-current/bin/ozone sh key getacl vol-test/bucket-test/key-hosts-test8
PERMISSION_DENIED User test doesn't have READ permission to access volume Volume:vol-test Bucket:bucket-test Key:key-hosts-test8
[hadoop@presto-test-006 ~]$ export HADOOP_USER_NAME=bigdata_qa
[hadoop@presto-test-006 ~]$ …
```

HDDS-8455. Om supports read only administrators.

---

pom.xml

Upgrade Jetty to latest 9.4.
https://issues.apache.org/jira/browse/HDDS-8461
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4746027424

HDDS-8461. Bump jetty to 9.4.51.v20230217

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisUnderReplicationHandler.java

In the RatisUnderReplicationHander, the sources are sorted by BSCIS, intending that the highest ID is used as the source for the replication.
However, the list is later sorted by the source command count pending for push replication, or shuffled for pull replication, so the sort is not having the intended effect.
We should remove the sort here, and instead filter out all sources except those with the highest BCSID.
https://issues.apache.org/jira/browse/HDDS-8416
New unit test added

HDDS-8416. ReplicationManager: RatisUnderReplication handler should filter sources by highest BCSID

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineFailures.java

Relase client in `TestContainerStateMachineFailures` after use.
https://issues.apache.org/jira/browse/HDDS-8474
Ran `TestContainerStateMachineFailures` locally, searched for gRPC's log:
```
grep 'was not shutdown' hadoop-ozone/integration-test/target/surefire-reports/org.apache.hadoop.ozone.client.rpc.TestContainerStateMachineFailures-output.txt
```

HDDS-8474. XceiverClient not closed properly in TestContainerStateMachineFailures

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/ChunkUtils.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/FilePerBlockStrategy.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/helpers/TestChunkUtils.java

In the `FilePerBlockStrategy#writeChunk` will generate twice IO process.
- The first is to check whether the write operation is an overwrite, will check whether the chunk file is exist (`ChunkUtils#verifyChunkFileExists`).
- The second is write Chunk, will open file and write file.
Those two IO operation can merge to once. just need to check whether is overwrite after open file and before write Chunk
https://issues.apache.org/jira/browse/HDDS-8421
unit test

HDDS-8421. Reduce DN IO times when writeChunk (FilePerBlockStrategy)

---

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/fsck/ContainerMapper.java

Close DB after use in `ContainerMapper` to fix:
```
2023-04-22 04:44:53,929 [Finalizer] WARN  managed.ManagedRocksObjectUtils (ManagedRocksObjectUtils.java:assertClosed(54)) - Checkpoint is not closed properly
StackTrace for unclosed instance: org.apache.hadoop.hdds.utils.db.managed.ManagedObject.<init>(ManagedObject.java:35)
...
org.apache.hadoop.hdds.utils.db.RDBStore.<init>(RDBStore.java:174)
org.apache.hadoop.hdds.utils.db.DBStoreBuilder.build(DBStoreBuilder.java:229)
org.apache.hadoop.ozone.om.OmMetadataManagerImpl.loadDB(OmMetadataManagerImpl.java:554)
org.apache.hadoop.ozone.om.OmMetadataManagerImpl.loadDB(OmMetadataManagerImpl.java:522)
org.apache.hadoop.ozone.om.OmMetadataManagerImpl.start(OmMetadataManagerImpl.java:512) …
```

HDDS-8480. DB not closed properly in ContainerMapper

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java

Synchronize every public interface of KeyOutputStream.
https://issues.apache.org/jira/browse/HDDS-7907
Unit test. Will also verify using HBase workloads too.

HDDS-7907. [hsync] KeyOutputStream is not thread safe.

---

hadoop-hdds/rocks-native/pom.xml

Currently native header file compilation fails for jdk11 & jdk 17. 
https://issues.apache.org/jira/browse/HDDS-8468
Local testing

HDDS-8468. Fix Native JDK 11, 17 compile

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestLegacyReplicationManager.java
hadoop-ozone/dist/src/main/compose/ozonesecure/docker-config
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManager.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/node/TestDecommissionAndMaintenance.java

* Enable the new ReplicationManager by default
* Except in:
* `TestLegacyReplicationManager`, since it tests `LegacyReplicationManager`
* `TestDecommissionAndMaintenance`, which will be fixed for new RM by HDDS-8459
* Fix `TestStorageContainerManager#testCloseContainerCommandOnRestart` for the new RM flow
https://issues.apache.org/jira/browse/HDDS-8466
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4755806209 (before `TestDecommissionAndMaintenance` change)
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4763910111 (final patch)

HDDS-8466. Disable LegacyReplicationManager by default

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerHealthResult.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisContainerReplicaCount.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/ECReplicationCheckHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/RatisReplicationCheckHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestMoveManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisContainerReplicaCount.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestRatisReplicationCheckHandler.java

The scenario is described in the jira: https://issues.apache.org/jira/browse/HDDS-8459.
The fix here is using the correct `RatisContainerReplicaCount` object in `RatisUnderReplicationHandler`. And also to consider `UNHEALTHY` replicas when checking for over replication in `RatisReplicationCheckHandler` to fix the subsequent over replication.
Added and modified unit tests. Also tested manually using docker compose.
Draft only because CI is still running in my fork: https://github.com/siddhantsangwan/ozone/actions/runs/4798311173/jobs/8536433251

HDDS-8459. Ratis under replication handling in a rack aware environment doesn't work

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java

In OM GetKeyInfo API, unexpected IOExceptions are returned as KEY_NOT_FOUND and the original error is swallowed.
https://issues.apache.org/jira/browse/HDDS-8475
Standard CI.

HDDS-8475. Unexpected IOException should be returned as INTERNAL_ERROR.

---

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/OzoneAddress.java
hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneAddressClientCreation.java

Ozone cli support multiple ozone.om.service.ids
https://issues.apache.org/jira/browse/HDDS-8482
manual tests passed.
without pr:
```bash
$ ozone sh vol ls o3://ozone1
Following ServiceID's [ozone1, ozone2] are defined in the configuration. Use the method getRpcClient which takes serviceID and configuration as param
```
with pr:
```bash
$ ozone sh vol ls o3://ozone1
[ {
"metadata" : { }...
]
$ ozone sh vol ls o3://ozone2
[ {
"metadata" : { }...
]
ozone sh vol ls
Service ID or host name must not be omitted when multiple ozone.om.service.ids is defined  
```

HDDS-8482. Let Ozone shell support multiple OM services

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneManagerSnapshotAcl.java

Fix for a flaky test. Instead of `RandomStringUtils.randomNumeric(5)`, `RandomStringUtils.randomNumeric(32)` is used and unecessary `cleanup()` method is removed. 
https://issues.apache.org/jira/browse/HDDS-8433
[GitHub action](https://github.com/mladjan-gadzic/ozone/actions/workflows/HDDS-8433.yml?page=2) was created that executed one test multiple times. Since #37 run GitHub action was running on latest changes without an intermittent failure. Prior to that it was running on old codebase and it was confirmed that test was flaky.

HDDS-8433. Intermittent failure in TestOzoneManagerSnapshotAcl

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeConfiguration.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/StateContext.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteContainerCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/ReconstructECContainersCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/ReplicateContainerCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisor.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/TestStateContext.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestDeleteContainerCommandHandler.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisorScheduling.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestReplicationSupervisor.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/ClosedContainerReplicator.java

- Block Delete Command queue cap to 5
- Other queue is capped to 5000
https://issues.apache.org/jira/browse/HDDS-8417
Impact is tested using existing UT and integration test

HDDS-8417. Cap on queue of commands at DN

---

hadoop-ozone/dist/src/main/smoketest/security/ozone-secure-token.robot
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/token/GetTokenHandler.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/token/TokenOption.java

The CLI command: `ozone sh token get` does a few things wrong:
1. Writes to `/tmp/ozone.token` and the permissions allow another user to read it.
2. A second user cannot run the command as the `/tmp` folder does not allow another user to delete the file.
We will require a fix that would:
1. Require the user to enter the path to which the token will be written.
2. Set the permission for the file to be readable by only the user who owns the file.
https://issues.apache.org/jira/browse/HDDS-8495
- Existing Robot tests. 
- The patch has also been tested over a cluster with the basic Ozone services running.
- Green Git CI/CD: https://github.com/tanvipenumudy/ozone/actions/runs/4817911817/

HDDS-8495. Fix permissions and path handling for ozone sh token get command

---

.github/workflows/ci.yml
dev-support/ci/selective_ci_checks.sh
hadoop-hdds/pom.xml
hadoop-ozone/dev-support/checks/build.sh
hadoop-ozone/dev-support/checks/native_check.sh
hadoop-ozone/pom.xml
pom.xml

Enable Selective CI native building & testing based on the change in hdds-rocks-native module. In this PR we check if the git version for the module directory can be found in the maven repository & if the version is different we would do a full native build. Otherwise we would just override hdds-rocks-native dependent version.
The solution is well explained in @smengcl PR #4466 
https://issues.apache.org/jira/browse/HDDS-8269
Local fork run [link](https://github.com/swamirishi/ozone/actions/runs/4750932163/jobs/8439558970#:~:text=Checking%20Maven%20repo%20contains%20hdds%2Drocks%2Dnative%20of%20version%201.4.0%2DSNAPSHOT.df27c89).

HDDS-8269. [Snapshot] Enable CI native building and testing

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java

Thread sleep replaced with waiting for DN container to Closed
https://issues.apache.org/jira/browse/HDDS-8458
Flaky test fix, test case running multiple time

HDDS-8458. Intermittent timeout in TestBlockDeletion#testBlockDeletion

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/symmetric/DefaultSecretKeyVerifierClient.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/symmetric/SecretKeyVerifierClient.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/token/ShortLivedTokenVerifier.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/token/TokenVerifierTests.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyInputStream.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestBlockTokens.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecretKeysApi.java

E2E integration test cases for block tokens:
- Basic functionality working.
- Basic functionality working around rotation.
- Client using expired secret key (retry successful).
- Client using invalid token:
- wrong password.
- invalid secret key id.
https://issues.apache.org/jira/browse/HDDS-8003
CI run. https://github.com/duongkame/ozone/actions/runs/4631999605

HDDS-8003. E2E integration test cases for block tokens

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/OverReplicatedProcessor.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationQueue.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnderReplicatedProcessor.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnhealthyReplicationProcessor.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestOverReplicatedProcessor.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestUnderReplicatedProcessor.java

Make over/under-replicated processors use a single instance of `ReplicationQueue` for each iteration, even if `ReplicationManager` replaces it with a new queue concurrently.
https://issues.apache.org/jira/browse/HDDS-8471
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4821912584

HDDS-8471. Ensure replication processors use a single queue for each iteration

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
hadoop-ozone/integration-test/src/test/resources/ozone-site.xml
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java

Frequent timeout of `TestRootedOzoneFileSystem` (fork is killed after 20 minutes) is caused by increased snapshot diff wait time (1 minute instead of 1 second, changed in #4511).
```
[INFO] Running org.apache.hadoop.fs.ozone.TestRootedOzoneFileSystem
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project ozone-integration-test: There was a timeout in the fork -> [Help 1]
```
Thread dump excerpt:
```
"Time-limited test" 
java.lang.Thread.State: TIMED_WAITING
at java.lang.Thread.sleep(Native Method)
at org.apache.hadoop.fs.ozone.BasicRootedOzoneClientAdapterImpl.getSnapshotDiffReportOnceComplete(BasicRootedOzoneClientAdapterImpl.java:1351)
at org.apache.hadoop.fs.ozone.BasicRootedOzoneClientAdapterImpl.getSnapshotDiffReport(B …
```

HDDS-8510. Intermittent timeout in TestRootedOzoneFileSystem#testSnapshotDiff

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMRecoverLeaseRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/file/TestOMRecoverLeaseRequest.java

preExecute() to fill in userInfo to avoid NPE in follower OM.
https://issues.apache.org/jira/browse/HDDS-8506
Unit test is updated to enable ACL (fails in ACL check code) and verify preExecute() does fill in userInfo properly.

HDDS-8506. LeaseRecovery failing with NullPointer exception.

---

hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/codec/OMDBDefinition.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyRenameResponse.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyRenameResponseWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeysRenameResponse.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotCreateResponse.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotMoveDeletedKeysResponse.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/SnapshotDeletingService.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotCreateRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeyRenameResponse.java

When directories are renamed, this information is not tracked. It is required by the`SnapshotDeletingService` to check the previous snapshot's `directoryTable` and check if the renamed key is present.
https://issues.apache.org/jira/browse/HDDS-8435

HDDS-8435. [Snapshot] Handle Directory renames for FSO Buckets.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/OverReplicatedProcessor.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnderReplicatedProcessor.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnhealthyReplicationProcessor.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestOverReplicatedProcessor.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestUnderReplicatedProcessor.java

We should make it possible to configure a global replication limit, limiting the number of inflight containers pending creation. A larger cluster would be capable of having more inflight replication than a smaller cluster, so the limit should be a function of the number of datanodes on the cluster, and the limit of the number of commands which can be queued per datanode and some weighting factor.
For example, if each datanode can queue 20 replication commands, and there are 100 nodes in the cluster, then the natural limit is 20 * 100. However, that assumes that commands are queued evenly across all datanodes, which is unlikely. With a global limit we would prefer that all datanodes are not fully loaded with replication commands simultaneously, so we may want to impose a limit of half that …

HDDS-8505. ReplicationManager: Add configurable global replication limit

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerInfo.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerSelectionCriteria.java

Problem: Container Balancer gets a reference to a Container's `ContainerInfo` from `ContainerManager` in several places throughout the balancer package. We need to investigate if there are possible race conditions with other parts of SCM changing the replicas of a container etc.
In the investigation it was found that in most places, the `ContainerInfo` object's `usedBytes` field is being read through the getter `ContainerInfo#getUsedBytes`. `usedBytes` is written in `AbstractContainerReportHandler#updateContainerUsedAndKeys` when a container report is processed. Since `usedBytes` is a long primitive type and read/write to a long are not atomic, there's a race condition between the balancer thread reading this value and the report handling thread writing to it. This PR proposes making …

HDDS-8347. Investigate possible race conditions on ContainerInfo in ContainerBalancer

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/protocol/DatanodeDetails.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/SetNodeOperationalStateCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisor.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisorScheduling.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestReplicationSupervisor.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/ClosedContainerReplicator.java

When a datanode switches to a decommissioning state, it will adjust the size of the replication supervisor thread pool higher, and if the node returns to the In Service state, it will return to the lower thread pool limit.
Similarly when scheduling commands, SCM can allocate more commands to the decommissioning host, as it should process them more quickly due to the lower load and increased threadpool.
* Scale the size of executor thread pool and command queue for replication in datanode if state changes between in-service and out-of-service
* Similarly scale the limit of pending replication commands at SCM
* Simplify `TestReplicationSupervisor#testMaxQueueSize` to avoid the use of thread pool (possible source of intermittent failures recently …

HDDS-8494. Adjust replication queue limits for out-of-service nodes

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneAtRestEncryption.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/AbstractOMKeyDeleteResponse.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMDirectoriesPurgeResponseWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyCommitResponse.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyCommitResponseWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyDeleteResponseWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeysDeleteResponseWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMTrashRecoverResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/OMRequestTestUtils.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCommitRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeyCommitResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeyCommitResponseWithFSO.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeyDeleteResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMOpenKeysDeleteResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestKeyDeletingService.java

1. delete key is appended with objectId to make it unique
2. Removed caching of deleteTable as its not used again due to uniqueness
and removed getting from deleteTable for old key (old key will not be present as delete key is unique)
3. This is to add repeated info and overwrite the same key again in deleteTable, which can cause missing cleanup of latest block appended as there KeyDeletingService has already run in parallel.
Uniqueness for multiple flows:
openKey cleanup: openKey appended with objectId
key commit(unused block and old version): openKey appended with objectId
delete key/keys: dbKey appended with objectId
directoryPurge: key appended with objectId
https://issues.apache.org/jira/browse/HDDS-8462
Unit test and integration test for delete behavior impact

HDDS-8462. Key in deleteTable uniqueness

---

hadoop-ozone/recon/pom.xml
hadoop-ozone/recon/src/main/resources/webapps/recon/WEB-INF/web.xml
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/package.json
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/pnpm-lock.yaml
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/public/index.html
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/public/static/media/LICENSE
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/index.tsx

The direct link for the Google Roboto font has been replaced with the use of the Fontsource module. 
https://issues.apache.org/jira/browse/HDDS-8393
Manual testing

HDDS-8393. [Recon] Include Roboto font using fontsource instead

---

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/db.json
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/overview/overview.tsx

This information will be displayed on the overview page of recon which gets populated with the information provided by the ClusterStateEndpoint
https://issues.apache.org/jira/browse/HDDS-8340
Manually

HDDS-8340. [Recon] Show the number of deleted containers in UI

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestRecursiveAclWithFSO.java

* Convert `TestRecursiveAclWithFSO` to JUnit5 (requirement for `@Flaky` tag)
* Mark as flaky
* Fix some issues:
* Properly close `OzoneClient`
* Remove unused variables, fix dangling javadoc
https://issues.apache.org/jira/browse/HDDS-8092
Verified `TestRecursiveAclWithFSO` is executed in _integration (flaky)_:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4881430130/jobs/8710329587#step:6:3657

HDDS-8092. Mark TestRecursiveAclWithFSO#testKeyDeleteAndRenameWithoutPermission as flaky

---

hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdb/util/ManagedSstFileReader.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java

This change is to throw exception if estimated keys changed in snapdiff job is more than 10 million.
[HDDS-7546](https://issues.apache.org/jira/browse/HDDS-7546)
Existing unit tests for now.

HDDS-7546. [Snapshot] Throw exception if the SnapshotDiff size is huge

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerReplicaPendingOps.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestContainerReplicaPendingOps.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java

ContainerReplicaPendingOps contains a record of all the pending replications which are waiting to complete across the cluster. When SCM steps down as a leader, and a new one takes over, the pending commands on the datanodes are dropped as they check the leader term before they are processed.
This means the contents of ContainerReplicaPendingOps is not needed if the SCM fails back to the original node. Therefore, if the SCM becomes active again, we should clear the pending ops when RM is transitioning to the RUNNING state.
https://issues.apache.org/jira/browse/HDDS-8473
New unit tests added.

HDDS-8473. ReplicationManager: Clear ContainerReplicaPendingOps when RM goes to running state

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerDoubleBuffer.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerStateMachine.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerDoubleBuffer.java

In order to support bootstrapping followers, the om snapshot subsystem needs to make consistent copies snapshot, including the deleted keys table which can be updated at any time.
This means that the background processes modifying the deletedKeys tables need to be halted, and then the bootstrapping process needs to wait for the double buffer to be flushed, (so that any remaining mods to the deletedKeys table is up to date.)
This PR adds the mechanism to allow a thread to wait until the double buffer has been flushed.
It is implmented by adding a set of countdown latches one for each thread that is waiting.
The latches are initialized to 2, one for each of the buffers in the "double" buffer.
Each time a buffer is cleared the latches are decremented once, so that when both have been …

HDDS-8499. Add mechanism to notify threads when OM double buffer flushed.

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisor.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestReplicationSupervisor.java

https://github.com/apache/ozone/blob/a455597815a4a12ded9479f334780a83116a2123/hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisor.java#L164-L165
The above code works when increasing thread pool size, but fails when decreasing it, because maximum cannot be set to less than core.  Seen in `TestDecommissionAndMaintenance` logs:
```
java.lang.IllegalArgumentException
at java.util.concurrent.ThreadPoolExecutor.setMaximumPoolSize(ThreadPoolExecutor.java:1680)
at org.apache.hadoop.ozone.container.replication.ReplicationSupervisor$Builder.lambda$build$1(ReplicationSupervisor.java:164)
at org.apache.hadoop.ozone.container.replication.ReplicationSupervisor.nodeStateUpdated(ReplicationSupervisor.java:294)
```
Core pool size needs to be …

HDDS-8554. Thread pool size needs to be decreased in different order in ReplicationSupervisor

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/StringUtils.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/Codec.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/CodecBuffer.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/ByteArrayCodec.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/IntegerCodec.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/LongCodec.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBTable.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/StringCodec.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/TestRDBSnapshotProvider.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestCodec.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStore.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestTypedRDBTableStore.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java

- Add a put method to use RocksDB ByteBuffer APIs.
- Support ByteBuffer methods in Codec and some of the implementations.  (Will work on other implementations in other JIRAs.)
HDDS-8542
Add new tests to test the codec implementations.

HDDS-8542. In RDBTable, add a put method using RocksDB ByteBuffer APIs.

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HAUtils.java

OzoneManager and OzoneDatanode check the count of SCM certificates and the number of configured SCM in the cluster, this count will mismatch after decommissioning. This count mismatch has to be handled.
HDDS-8521

HDDS-8521. Fix SCM certificate count check during OM & Datanode startup.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/node/TestDecommissionAndMaintenance.java

3e0cb27632d increased the number of datanodes in the mini cluster of `TestDecommissionAndMaintenance` from 6 to 7.  However, `testSCMHandlesRestartForMaintenanceNode` still expects 5 in-service datanodes after shutting down one, as originally introduced in 42d53bce288.
This change simply makes the same increase in the expected number of nodes (5 to 6).
https://issues.apache.org/jira/browse/HDDS-8493
Ran locally:
```
$ mvn -am -pl :ozone-integration-test -Dtest='TestDecommissionAndMaintenance#testSCMHandlesRestartForMaintenanceNode' clean test
...
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 43.132 s - in org.apache.hadoop.ozone.scm.node.TestDecommissionAndMaintenance
```

HDDS-8493. Intermittent timeout in TestDecommissionAndMaintenance#testSCMHandlesRestartForMaintenanceNode

---

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/cert/ListSubcommand.java

Add a warning to the user when the list subcommand lists too few certificates that they should increase the batch size.
[HDDS-8514](https://issues.apache.org/jira/browse/HDDS-8514)
Github actions show no test failures and tried out the command on a local cluster.

HDDS-8514. Improve ozone admin cert list subcommand count limits

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/Codec.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/CodecBuffer.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/ByteStringCodec.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/CodecRegistry.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestCodecRegistry.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/metadata/ByteStringCodec.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/metadata/SCMDBDefinition.java

Do not get codec from super classes and interfaces.
HDDS-8551

HDDS-8551. Fix the generic type of CodecRegistry.getCodec

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/OzoneTestUtils.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestCloseContainer.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneDebugShell.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/ChunkKeyHandler.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/OzoneDebug.java

Fix ozone debug chunkinfo command to work on keys that are present in closed containers, The issue was that the xceiverclient was trying to acquire the original pipeline from the keylocation which gets closed on container/pipeline close. 
1. The fix is to use the separate standalone pipeline instance for read.
```java  ContainerProtos.ContainerDataProto containerData =
containerOperationClient.readContainer(
- keyLocation.getContainerID(), keyLocation.getPipeline());
+ keyLocation.getContainerID(), pipeline);
```
2. Also closed client instances by enclosing in try with resources to prevent any leaks.
3. Added TestOzoneDebugShell to test this
https://issues.apache.org/jira/browse/HDDS-8546
Added a unit test

HDDS-8546. Ozone debug chunkinfo command throws GroupMismatchException for closed container

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneListStatusHelper.java

When listing keys in FSO, there is no need to seek first if the prefix is provided.
Constructor for RDB Store seeks first if the prefix is not set. ListKeys calls in FSO should forward the prefix to the constructor to avoid wastefully seeks.
```
public RDBStoreIterator(ManagedRocksIterator iterator, RDBTable table,
byte[] prefix) {
this.rocksDBIterator = iterator;
this.rocksDBTable = table;
if (prefix != null) {
this.prefix = Arrays.copyOf(prefix, prefix.length);
}
seekToFirst();
}
```
This is related to https://issues.apache.org/jira/browse/HDDS-8289 but not be sufficient to improve the entire performance issue but should help.
https://issues.apache.org/jira/browse/HDDS-8289

HDDS-8289. Speed up FSO ListKeys, skip skipToFirst

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/utils/DatanodeStoreCache.java
hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/MiniOzoneChaosCluster.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneHAClusterImpl.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/volume/TestDatanodeHddsVolumeFailureDetection.java

Surefire fork intermittently times out in `TestDecommissionAndMaintenance`.
Container DB is added to the cache:
```
2023-05-03 08:18:26,909 [EndpointStateMachine task thread for /0.0.0.0:43723 - 0 ] INFO  utils.DatanodeStoreCache (DatanodeStoreCache.java:addDB(58)) - Added db /home/runner/work/ozone/ozone/hadoop-ozone/integration-test/target/test-dir/MiniOzoneClusterImpl-ff176d5b-bea5-4cbe-a997-8236a6853a89/datanode-0/data-0/containers/hdds/ff176d5b-bea5-4cbe-a997-8236a6853a89/DS-4328e108-8c1a-4a6f-8bff-6f686dd50b24/container.db to cache
```
but then not found and tried to open again, which fails since RocksDB is already open and protected by OS-level lock (`lock hold by current process`):
```
2023-05-03 08:18:57,086 [Command processor thread] ERROR utils.DatanodeStoreCache …
```

HDDS-8539. Container DB open, but not found in DatanodeStoreCache

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/AbstractContainerReportHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerReportHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestIncrementalContainerReportHandler.java

One possible scenario where this could happen is analysed here - https://issues.apache.org/jira/browse/HDDS-8179?focusedCommentId=17719799&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17719799
This PR changes the `AbstractContainerReportHandler` to only update an EC container's state if the replica is the first index or one of the parity indexes.
https://issues.apache.org/jira/browse/HDDS-8179

HDDS-8179. Datanode decommissioning blocked due to non-empty replica of deleting container

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java

ensure double buffer flush as cache is removed and this may be cause for intermittent failure
https://issues.apache.org/jira/browse/HDDS-8550
test fix

HDDS-8550. Intermittent failure in testOverWriteKeyWithAndWithOutVersioning

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingService.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachine.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineFailures.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestValidateBCSIDOnRestart.java
hadoop-ozone/integration-test/src/test/java/org/apache/ratis/statemachine/impl/StatemachineImplTestUtil.java
pom.xml

Upgrade Ratis to 2.5.1.
Fix for compilation error in tests due to interface change was provided by @szetszwo.  When merging this, please keep the following detail in the commit message:
```
Co-authored-by: Tsz-Wo Nicholas Sze <szetszwo@apache.org>
```
https://issues.apache.org/jira/browse/HDDS-8382
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4891132333

HDDS-8382. Upgrade Ratis to 2.5.1

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMSecurityProtocolFailoverProxyProvider.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SingleSCMSecurityProtocolProxyProvider.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/symmetric/SecretKeyManager.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/symmetric/SecretKeyState.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/symmetric/SecretKeyStateImpl.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManagerImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManagerStub.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMStateMachine.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMInstallSnapshot.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneHAClusterImpl.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestSCMInstallSnapshotWithHA.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestSecretKeySnapshot.java

Integrate secret keys to SCM snapshot. The taken approach is during snapshot installation, the follower makes a separate call to get secrets from SCM leader.
Protocol description of a new node joining an existing SCM (ratis) ring:
1. The new node connects to the current leader, and the leader decides if the new node needs to download a snapshot.
2. The new node download the snapshot from the leader, also make a separate call to download (latest) secret keys. These states are apply to the new node state.
3. The new node then joins the ring.
4. The new node receives ratis logs (after the index of the downloaded snapshot). The logs may contain secret keys sync. If it does, the latest secret keys will overwrite the current secret keys state.
https://issues.apache.org/jira/browse/HDDS-7945 …

HDDS-7945. Integrate secret keys to SCM snapshot

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationServer.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisor.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestReplicationConfig.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java

HDDS-8494 doubled the replication thread pool and queue size of decommissioning/maintenance nodes.  This PR makes the factor configurable.  The same config applies to both datanodes and SCM.
https://issues.apache.org/jira/browse/HDDS-8532
https://github.com/adoroszlai/hadoop-ozone/actions/runs/4907548631

HDDS-8532. Add config for factor of scaling up replication queue/threads in decommissioning nodes

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java

Remove the Flaky tag from TestHSync since it no longer fails; see https://github.com/szetszwo/ozone/actions/runs/4928119390
HDDS-8146
NA

HDDS-8146. TestHSync is no longer flaky

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/exceptions/OMException.java
hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRenameRequestWithFSO.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyRenameRequestWithFSO.java

Renaming open files is unsupported. It creates unfortunate behavior where inconsistent copies of files appears in the namespace. So let's stop allowing this.
https://issues.apache.org/jira/browse/HDDS-8545
Unit test; Ran HBase integration test to verify it actually function as expected.

HDDS-8545. [hsync] reject renaming open file

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java
hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java

This change is to close RocksDB instance if RDBStore creations fails after [RocksDB's instance creation](https://github.com/apache/ozone/blob/75f5a28f376516e7252e750e86a10c2f9d874d5a/hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java#L112).
It also includes proper closing of `OmMetadataManagerImpl` in its construct and while loading snapshot cache due to any failure.
https://issues.apache.org/jira/browse/HDDS-8576
1. Existing tests.
2. Before the change, integration tests I added as part of [HDDS-8389](https://issues.apache.org/jira/browse/HDDS-8389), were failing most of the time.
Failed run example#1: https://github.com/hemantk-12/ozone/actions/runs/4929699855/jobs/8812911004
Failed run example#2: …

HDDS-8576. Close RocksDB instance in RDBStore if RDBStore's initialization fails after RocksDB instance creation

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/MisReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManagerUtil.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationTestUtil.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManagerUtil.java

With [HDDS-7226](https://issues.apache.org/jira/browse/HDDS-7226) merged, the RackAwarePlacementPolicy now supports passing used nodes and excluded nodes separately. This allows it to select the racks correctly when there are one or two used nodes.
We need to change the Ratis under and mis-replication handlers to pass the used nodes and excluded nodes as two separate lists now.
Also the EC under-replication handler should be fixed to pass used nodes separately too.
https://issues.apache.org/jira/browse/HDDS-8504
New unit and changed tests

HDDS-8504. ReplicationManager: Pass used and excluded node separately for Under and Mis-Replication

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsHAURLs.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneCluster.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterProvider.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneHAClusterImpl.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/OzoneTestUtils.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmContainerLocationCache.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerConfiguration.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/node/TestDecommissionAndMaintenance.java

`TestDecommissionAndMaintenance` uses `MiniOzoneClusterProvider` to provision clusters in the background.  Tests intermittently fail due to port conflict.
```
Tests run: 7, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 348.139 s <<< FAILURE! - in org.apache.hadoop.ozone.scm.node.TestDecommissionAndMaintenance
org.apache.hadoop.ozone.scm.node.TestDecommissionAndMaintenance.testNodeWithOpenPipelineCanBeDecommissionedAndRecommissioned  Time elapsed: 159.55 s  <<< ERROR!
java.util.concurrent.TimeoutException: 
...
at org.apache.hadoop.ozone.MiniOzoneClusterImpl.waitForClusterToBeReady(MiniOzoneClusterImpl.java:218)
at org.apache.hadoop.ozone.MiniOzoneClusterImpl.restartHddsDatanode(MiniOzoneClusterImpl.java:431)
at org.apache.hadoop.ozone.scm.node.TestDecommissionAndMaintenance.testNodeWit …
```

HDDS-8581. Avoid random ports in integration tests

---

hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java

Add a unit test to validate that an unrecoverable (missing) EC container that is also empty, is handled as an empty container.
https://issues.apache.org/jira/browse/HDDS-7732
Unit test added

HDDS-7732. EC: Verify unrecoverable EC containers which are empty transition to deleting

---

hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneFSDataStreamOutput.java

Hadoop client write slowly when stream enabled
code stack
```
at org.apache.hadoop.hdds.scm.storage.BlockDataStreamOutput.doFlushIfNeeded(BlockDataStreamOutput.java:321)
at org.apache.hadoop.hdds.scm.storage.BlockDataStreamOutput.write(BlockDataStreamOutput.java:260)
at org.apache.hadoop.ozone.client.io.BlockDataStreamOutputEntry.write(BlockDataStreamOutputEntry.java:108)
at org.apache.hadoop.ozone.client.io.KeyDataStreamOutput.writeToDataStreamOutput(KeyDataStreamOutput.java:201)
at org.apache.hadoop.ozone.client.io.KeyDataStreamOutput.handleWrite(KeyDataStreamOutput.java:179)
at org.apache.hadoop.ozone.client.io.KeyDataStreamOutput.write(KeyDataStreamOutput.java:159)
at org.apache.hadoop.hdds.scm.storage.ByteBufferStreamOutput.write(ByteBufferStreamOutput.java:37)
at …
```

HDDS-8584. Hadoop client write slowly when stream enabled

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/AbstractOMKeyDeleteResponse.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMDirectoriesPurgeResponseWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3MultipartUploadAbortResponse.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3MultipartUploadCommitPartResponse.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3MultipartUploadCompleteResponse.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3MultipartUploadCompleteResponseWithFSO.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/OMRequestTestUtils.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartUploadCompleteRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartUploadCompleteRequestWithFSO.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeyCommitResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3MultipartResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3MultipartUploadAbortResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3MultipartUploadCommitPartResponseWithFSO.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3MultipartUploadCompleteResponseWithFSO.java

for multipart, delete key is multi-part + objectId, where multi-part format is /volumeName/bucketName/keyname/uploadId
https://issues.apache.org/jira/browse/HDDS-8463
Tested with UT and integration cased present

HDDS-8463. S3 key uniqueness in deletedTable

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/IOUtils.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisServer.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisServerImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMMXBean.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneCluster.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneHAClusterImpl.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMiniOzoneCluster.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestStorageContainerManagerHA.java

- Remove `throws IOException` from `SCMRatisServer.getRatisRoles()` and the related method.
- Add `getName()` and `getBaseDir()` to `MiniOzoneCluster`.
- Update `TestMiniOzoneCluster` to junit 5.
HDDS-8621
Add new asserts.

HDDS-8621. IOException is never thrown in SCMRatisServer.getRatisRoles().

---

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/ClusterStateEndpoint.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/ClusterStateResponse.java
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/db.json
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/overview/overview.tsx
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java

This information will be displayed on the overview page of recon which gets populated with the information provided by the ClusterStateEndpoint This information can be useful for auditing, compliance, and troubleshooting purposes. Hence in short the main purpose is to get a quick idea of the deletion progress.
https://issues.apache.org/jira/browse/HDDS-8339
Manually

HDDS-8339. Recon Show the number of keys marked for Deletion in Recon UI.

---

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/ChunkKeyHandler.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/ChunkType.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/ContainerChunkInfo.java

The output of `ozone debug chunkinfo` now shows the type of chunks in an EC block
https://issues.apache.org/jira/browse/HDDS-8615
Manually. Now the output of  `ozone debug chunkinfo` looks as follows:
```
...
{
"Datanode-HostName": "ozone-datanode-7.ozone_default",
"Datanode-IP": "172.27.0.13",
"Container-ID": 1,
"Block-ID": 111677748019200001,
"Locations": {
"files": [
"/data/hdds/hdds/CID-5fc1a1ae-41c9-436f-81c7-fbd53389ddc4/current/containerDir0/1/chunks/111677748019200001.block"
],
"pipelineID": "413af33b-2975-49b1-a850-b8f8378ffc0b",
"chunkType": "PARITY"
}
}
...
```

HDDS-8615. Explicitly show EC block type in 'ozone debug chunkinfo'

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsConfigKeys.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/AvailableSpaceFilter.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeInfo.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeUsage.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestHddsDispatcher.java
hadoop-hdds/container-service/src/test/resources/ozone-site.xml
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java

Close containers when volume reaches utilisation threshold, If volume is configured with a reserved space, the softlimit would hit when `(capacity-reserved) - used  <= minFreeSpaceOnVolume.`
By default the value is 5GB.
https://issues.apache.org/jira/browse/HDDS-8254
Unit tests

HDDS-8254. Close containers when volume reaches utilisation threshold

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisContainerReplicaCount.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/RatisReplicationCheckHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/RatisUnhealthyReplicationCheckHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisContainerReplicaCount.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestRatisReplicationCheckHandler.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/node/TestDecommissionAndMaintenance.java

`TestDecommissionAndMaintenance#testContainerIsReplicatedWhenAllNodesGotoMaintenance` fails with the new replication manager (i.e. if legacy is disabled).  If all replicas are starting maintenance, underreplication is not fixed.  `RatisReplicationCheckHandler` skips because there are no healthy replicas, and `RatisUnhealthyReplicationCheckHandler` skips because neither are there any unhealthy ones.  Decommissioning and maintenance replicas are counted separately, and we lose the information regarding their health.
This change fixes the problem by counting healthy/unhealthy decom/maint replicas separately, and including them in total healthy/unhealthy counts (`getHealthyReplicaCount()` and `getUnhealthyReplicaCount()`).
It also includes some refactoring as separate commits, reducing code …

HDDS-8616. Underreplication not fixed if all replicas start decommissioning

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationServer.java

A separate thread pool is used for processing replication server grpc requests. If no thread pool is set, the default thread pool is used, which is now also used by raft GRPC in ratis
https://issues.apache.org/jira/browse/HDDS-8626

HDDS-8626. Config thread pool in ReplicationServer

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinator.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinatorTask.java

* Log at info-level when EC reconstruction is started.  Update existing messages on completion/failure to be similar.
* Add debug-level message for container create/close commands.
https://issues.apache.org/jira/browse/HDDS-7080
Ran `TestECContainerRecovery` locally, checked output.
```
2023-05-16 11:45:57,038 [ContainerReplicationThread-0] INFO  reconstruction.ECReconstructionCoordinatorTask (ECReconstructionCoordinatorTask.java:runTask(65)) - IN_PROGRESS reconstructECContainersCommand: containerID=1, replication=rs-3-2-1024k, missingIndexes=[1], sources={2=4f8c1ee8-843d-4e20-a85d-84a8bafed0a1(localhost/127.0.0.1), 3=ef236338-4845-41a8-aac7-e4a6b965d1de(localhost/127.0.0.1), 4=954c0e80-343e-491f-8fd9-01a4f3fbc54a(localhost/127.0.0.1), …
```

HDDS-7080. EC: Offline reconstruction needs better logging

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBStoreBuilder.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SstFilteringService.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java

By default, [DBStore object gets created with compaction DAG enabled](https://github.com/apache/ozone/blob/b5ad73aaa8a3a419fdb9cb27d54ea6ee54f71cf0/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java#L560). There is no need for compaction DAG when loading metadata for snapshots.
This change is add `enableCompationDag` to [loadDB()](https://github.com/apache/ozone/blob/master/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java#L545) use it to create DBStore object.
Also change the variable name from `enableCompationLog` to `enableCompationDag` because someone can get confused if it is to enable/disable RocksDB compaction.
https://issues.apache.org/jira/browse/HDDS-8577
Added test for it.

HDDS-8577. [Snapshot] Disable compaction log when loading metadata for snapshot

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinator.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestContainerCommandsEC.java

In case of EC reconstruction of containers when orphan blocks are present in some of the replicas. The reconstruction could fail as orphan blocks may be present in some of the replicas & absent in some of the replicas due to which reconstruction for this particular block would fail & the whole reconstruction of container could fail and this reconstruction would continuously keep on failing.
https://issues.apache.org/jira/browse/HDDS-7241
Integration test added to reproduce the issue and confirm the fix.

HDDS-7241. EC: Reconstruction could fail with orphan blocks.

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/lease/LeaseManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestCloseContainerEventHandler.java

LeaseManager have concurrency issue that, when new event is added just before monitor thread go for wait, then notification will be missed and object remains in queue indefinitely till further new event comes and notify.
- changed the logic using blocking queue for event notification.
- test case change to validate lease acquire and wait with GenericTestUtils.waitFor
https://issues.apache.org/jira/browse/HDDS-8575
running testcase multiple time

HDDS-8575. Intermittent failure in TestCloseContainerEventHandler.testCloseContainerWithDelayByLeaseManager

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/SnapshotInfo.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHASnapshot.java
hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SnapshotChainManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotDeleteRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotManager.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/OMRequestTestUtils.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotDeleteRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/snapshot/TestOMSnapshotCreateResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/snapshot/TestOMSnapshotDeleteResponse.java

OM was crashing on the restart because snapshot chain was getting corrupted. On the deep dive, it is found that it is because creation time of snapshots are not unique among snapshots and causing the failure. Mode details are in jira: https://issues.apache.org/jira/browse/HDDS-8530.
This change is to pass the creation time through [preExecute](https://github.com/apache/ozone/blob/master/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotCreateRequest.java#L92) instead of each OM node using current time as creation time. Creation time is passed similar to `snapshotId`.
This change also includes some logging changes in `SnapshotChainManager` to log more information to debug in future.
https://issues.apache.org/jira/browse/HDDS-8530
Added …

HDDS-8530. [Snapshot] Fix for OM crash on restart due to snapshot chain manager corruption

---

hadoop-ozone/dist/src/main/smoketest/basic/links.robot
hadoop-ozone/dist/src/main/smoketest/basic/ozone-shell-lib.robot
hadoop-ozone/dist/src/main/smoketest/basic/ozone-shell.robot
hadoop-ozone/dist/src/main/smoketest/security/ozone-secure-fs.robot
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/keys/DeleteKeyHandler.java

When trash is enabled and user runs ozone sh key delete, the key should be moved inside trash instead of permanent delete immediately.
Currently using fs command when trash is enabled and user deletes the file for FSO bucket it goes inside Trash.
https://issues.apache.org/jira/browse/HDDS-8547
Added new integration and robot test.

HDDS-8547. Support Trash for FSO bucket using ozone sh command.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestContainerCommandsEC.java

`ECReconstructionCoordinator` should be closed to avoid:
```
SEVERE: *~*~*~ Previous channel ManagedChannelImpl{logId=1375, target=10.1.1.154:15058} was not shutdown properly!!! ~*~*~*
Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
...
at org.apache.hadoop.hdds.scm.XceiverClientGrpc.connectToDatanode(XceiverClientGrpc.java:188)
...
at org.apache.hadoop.hdds.scm.XceiverClientManager.getClient(XceiverClientManager.java:224)
at org.apache.hadoop.hdds.scm.XceiverClientManager.acquireClient(XceiverClientManager.java:168)
at org.apache.hadoop.hdds.scm.XceiverClientManager.acquireClient(XceiverClientManager.java:141)
at org.apache.hadoop.ozone.container.ec.reconstruction.ECContainerOperationClie …
```

HDDS-8642. TestContainerCommandsEC should close ECReconstructionCoordinator

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyDataStreamOutput.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/OzoneOutputStream.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyArgs.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/security/GDPRSymmetricKey.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/security/TestGDPRSymmetricKey.java

- Check the parameters (null, class) in OzoneOutputStream constructors and don't have check it again in the code.
- Remove unused feInfo from KeyDataStreamOutput.
- Remove duplicated replicationConfig parameter from RpcClient.createDataStreamOutput(..).
- Add addAllMetadataGdpr to OmKeyArgs.Builder to take care GDPR_FLAG.
- Refactor GDPRSymmetricKey related code.
https://issues.apache.org/jira/browse/HDDS-8639
Modified TestGDPRSymmetricKey

HDDS-8639. Clean up OzoneOutputStream and the related code.

---

hadoop-hdds/rocks-native/pom.xml
hadoop-hdds/rocks-native/src/main/java/org/apache/hadoop/hdds/utils/NativeLibraryLoader.java
hadoop-hdds/rocks-native/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedSSTDumpIterator.java
hadoop-hdds/rocks-native/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedSSTDumpTool.java
hadoop-hdds/rocks-native/src/main/java/org/apache/hadoop/hdds/utils/db/managed/PipeInputStream.java
hadoop-hdds/rocks-native/src/main/native/SSTDumpTool.cpp
hadoop-hdds/rocks-native/src/main/patches/rocks-native.patch
hadoop-hdds/rocks-native/src/test/java/org/apache/hadoop/hdds/utils/db/managed/Native.java
hadoop-hdds/rocks-native/src/test/java/org/apache/hadoop/hdds/utils/db/managed/TestManagedSSTDumpIterator.java
hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdb/util/ManagedSstFileReader.java

Adding unit tests for SST Dump Tool. The test cases depends on #4470.
SSTDumpToolIterator was failing in the case key or value contain '\0' character, since prinf in c++ limits the string formatting till the first occurance null character. This PR also contains changes to send raw bytes of key, value over the pipe from the native sst file reader & corresponding changes to deserialize the raw bytes from the stream.
https://issues.apache.org/jira/browse/HDDS-8306
Unit Tests

HDDS-8306. [Snapshot] Fix SSTDumptool to allow null character & add tests for SST dump tool

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMDirectoriesPurgeResponseWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/DirectoryDeletingService.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/KeyDeletingService.java

During snapshot creation, access to `deletedTable` and `deletedDirectoryTable` would need to be synchronized with `KeyDeletingTask` and `DirDeletingTask` to avoid out-of-order access (read/write) messing up either table.
Here are the code logics that justify the locks:
1. Acquire `getTableLock(deletedDirectoryTable)` write lock, then acquire`getTableLock(deletedTable)` write lock
2. In `deletedTable`, remove all keys with prefix matching snapshot scope path (bucket)
3. In `deletedDirectoryTable`, remove all keys with prefix matching snapshot scope path (bucket)
4. Release `getTableLock(deletedTable)` write lock, then release`getTableLock(deletedDirectoryTable)` write lock
1. Acquire `getTableLock(deletedTable)` write lock
2. `getPendingDeletionKeys()`: (currently) retrieves a number of …

HDDS-8067. [Snapshot] Revisit locks on deletedTable and deletedDirTable

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/ContainerMetrics.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/CSMMetrics.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/TestCSMMetrics.java

Some of the metrics in CMSMetrics are in milliseconds, some are in nanoseconds, and here they are standardized to milliseconds
https://issues.apache.org/jira/browse/HDDS-8428

HDDS-8428. Add MS or NS time unit suffix for CSMMetrics

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineID.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/LongCodec.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/UuidCodec.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/hdds/datanode/metadata/CRLDBDefinition.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/CodecRegistry.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestCodec.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestDBStoreBuilder.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/metadata/SCMDBDefinition.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/metadata/OldPipelineIDCodecForTesting.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/metadata/TestPipelineIDCodec.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/codec/OMDBDefinition.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/codec/NSSummaryCodec.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/ReconDBDefinition.java

PipelineID only has a UUID field. We will add a UuidCodec and then use DelegatedCodec to support CodecBuffer for PipelineID codec.
https://issues.apache.org/jira/browse/HDDS-8643
Add new tests.

HDDS-8643. Support CodecBuffer for PipelineID codec.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotDeleteRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotCreateRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotDeleteRequest.java

This change is to increment activeSnapshot count metric only if snapshot creation succeeds. Current it gets incremented even if creation fails due to any reason.
https://issues.apache.org/jira/browse/HDDS-8360
* Added a test and ran locally.

HDDS-8360. [Snapshot] Increment activeSnapshot count metric only if snapshot creation succeeds

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneSnapshotRestore.java

The issue was that `TestOzoneSnapshotRestore::keyCopy` method was not finished copying keys when assertion for return value of `TestOzoneSnapshotRestore::keyCount` method was executed. It is proposed to use `GenericTestUtils::waitFor` to wait for `TestOzoneSnapshotRestore::keyCount` to return expected number of keys. For more info check comment section under linked Jira ticket.
https://issues.apache.org/jira/browse/HDDS-7889
* unit tests

HDDS-7889. Intermittent failure in TestOzoneSnapshotRestore

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

OM snapshot installing fails with:
```
2023-05-18 09:35:39,485 ERROR org.apache.hadoop.ozone.om.OzoneManager: Terminating with exit status 1: Failed to reload OM state and instantiate services.
org.apache.hadoop.metrics2.MetricsException: Metrics source OMPerformanceMetrics already exists!
at org.apache.hadoop.metrics2.lib.DefaultMetricsSystem.newSourceName(DefaultMetricsSystem.java:152)
at org.apache.hadoop.metrics2.lib.DefaultMetricsSystem.sourceName(DefaultMetricsSystem.java:125)
at org.apache.hadoop.metrics2.impl.MetricsSystemImpl.register(MetricsSystemImpl.java:229)
at org.apache.hadoop.ozone.om.OMPerformanceMetrics.register(OMPerformanceMetrics.java:33)
at org.apache.hadoop.ozone.om.OzoneManager.instantiateServices(OzoneManager.java:779)
at …
```

HDDS-8647. Fix problem with performance metric preventing OM taking snapshot.

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

Reverts apache/ozone#4734
I missed checking the checks for commits, the jira ID is missing from the commit.

Revert "HDDS-8647. Fix problem with performance metric preventing OM taking snapshot."

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRenameRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRenameRequestWithFSO.java

Fix OMKeyRenameRequest rename key failed infomation
When I tested, I found the following problems
```
2023-05-18 11:59:52,725 [IPC Server handler 63 on 9862] WARN org.apache.hadoop.ozone.om.OzoneManager: User test doesn't have DELETE permission to access key Volume:vol-rm-test Bucket:blk-rm-test Key:dirS/
2023-05-18 11:59:52,725 [IPC Server handler 63 on 9862] ERROR org.apache.hadoop.ozone.om.request.key.OMKeyRenameRequest: Rename key failed for volume:vol-rm-test bucket:blk-rm-test fromKey:dirS/ toKey:.Trash/test/Current/vol-rm-test/blk-rm-test/dirS1684382392673/. Key: dirS/ not found.
```
This error is not because the key does not found，but user doesn't have DELETE permission.
So I think exception information should be added.
https://issues.apache.org/jira/projects/HDDS/issues/HDDS-8644

HDDS-8644. Fix OMKeyRenameRequest rename key failed infomation.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerHealthResult.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisContainerReplicaCount.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/ECReplicationCheckHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeStatus.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestLegacyReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisContainerReplicaCount.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestClosedWithUnhealthyReplicasHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestDeletingContainerHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestECReplicationCheckHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestRatisReplicationCheckHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestRatisUnhealthyReplicationCheckHandler.java

According to the following javadoc, both decommission and maintenance replicas should be deprioritised:
https://github.com/apache/ozone/blob/6d9002201e58dc995dc133941acaef2af03cb9d2/hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerHealthResult.java#L145-L164
but `dueToDecommission=true` is set only based on decommission replicas, ignoring maintenance replicas (`maintenanceCount`):
https://github.com/apache/ozone/blob/6d9002201e58dc995dc133941acaef2af03cb9d2/hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisContainerReplicaCount.java#L520-L533
This PR:
* changes the method to consider the sum of decommission and maintenance replicas,
* renames the method and related code to refer to out-of-service …

HDDS-8617. Ratis underreplication due to maintenance is not deprioritised

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHASnapshot.java

`TestOzoneManagerHASnapshot` intermittently fails because DB is getting closed due to Ratis's consistence state. 
```
Error:  org.apache.hadoop.ozone.om.TestOzoneManagerHASnapshot.testSnapshotNameConsistency  Time elapsed: 3.094 s  <<< ERROR!
java.lang.RuntimeException: java.io.IOException: Rocks Database is closed
at org.apache.hadoop.ozone.om.TestOzoneManagerHASnapshot.lambda$testSnapshotNameConsistency$0(TestOzoneManagerHASnapshot.java:76)
at org.awaitility.core.CallableCondition$ConditionEvaluationWrapper.eval(CallableCondition.java:99)
at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at …
```

HDDS-8645. Change TestOzoneManagerHASnapshot to not subclass TestOzoneManagerHA

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestLegacyReplicationManager.java

In Replication Manager, a deadline is set on commands sent to a datanode. If the command has not completed within the timeout, RM assumes it is lost and will schedule a new command to another random node.
Right now the default is set to 30 minutes as the legacy RM scheduled a lot of work onto the DNs and it could take a long time to complete. The new RM throttles the work sent, so a large queue on the DNs should not be possible.
We should change the default event timeout to 10 minutes instead of 30.
https://issues.apache.org/jira/browse/HDDS-8658
Existing tests. This is a simple config default change.

HDDS-8658. ReplicationManager: Change default command timeout to 10 minutes

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainer.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerData.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerMetadataInspector.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/TarContainerPacker.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/BlockUtils.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/KeyValueContainerLocationUtil.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/KeyValueContainerUtil.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingService.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerPersistence.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/ContainerTestVersionInfo.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java

> @k5342 found a `NullPointerException` while replicating V1 containers in Ozone 1.3.0.  V1 containers do not have the `schemaVersion` field in the `.container` file
The NPE is fixed by adding and using a comparison function that considers `null` and `V1` to be equal.
https://issues.apache.org/jira/browse/HDDS-8636
Tested in real cluster:
https://github.com/apache/ozone/pull/4723#issuecomment-1554645068
Updated parameterized unit tests that exercise different schema versions to also test `null` value.
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5032201568

HDDS-8636. Containers in schema V1 fail for replication after the 1.3.0 upgrade

---

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/ContainerEndpoint.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/ContainersResponse.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestContainerEndpoint.java

The `getContainers()` method in the container Endpoint has been modified to exclude the container specified by the `prevKey` parameter from the list of containers in the `ContainerResponse`. 
The getContainers() method changes ensure that:
1. **Skipping the container with the same ID as prevKey**: The container stream is filtered to exclude the container matching prevKey, ensuring it is not included in the results.
2. **To increase the prevKey by 1**: We simply add 1 to the current value of prevKey. This is because the container IDs are arranged in ascending order. By doing this, we remove the first container from the list, which corresponds to the container with a Container ID equal to prevKey. As a result, this prevents that particular container from appearing in the API response.
3. …

HDDS-8502. Recon - getContainers API is not giving expected response with prevKey.

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/AbstractDataStreamOutput.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ByteBufferStreamOutput.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/ByteArrayStreamOutput.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/ByteBufferOutputStream.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyDataStreamOutput.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/OzoneDataStreamOutput.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/OzoneOutputStream.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
hadoop-ozone/dist/src/main/smoketest/gdpr/gdpr.robot
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneAtRestEncryption.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneFSDataStreamOutput.java

Currently, ClientProtocol.createStreamKey returns OzoneDataStreamOutput which is not an OutputStream. Therefore, it does not support CryptoOutputStream and CipherOutputStream since they requires OutputStream.
https://issues.apache.org/jira/browse/HDDS-8638
Added new tests.

HDDS-8638. Support CryptoOutputStream and CipherOutputStream in createStreamKey

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMDirectoriesPurgeResponseWithFSO.java

quota fix for snapshot updating active db when quota is released for keys/files/directory removal
https://issues.apache.org/jira/browse/HDDS-7598
Testcase is pending to be handled as part of snapshot deleting service https://issues.apache.org/jira/browse/HDDS-8207 for quota verification.

HDDS-7598. Quota for snapshot handling

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/WritableContainerFactory.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/WritableECContainerProvider.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/SimpleMockNodeManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestWritableECContainerProvider.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/container/testutils/ReplicationNodeManagerMock.java

Currently EC pipelines are limited to 5 per EC scheme, which does not scale with the size of the cluster.
As a simple first step for scaling EC pipeline/container count, `WritableECContainerProvider` should dynamically adjust the limit based on the number of healthy data volumes available in the cluster.
To retain behavior in smaller clusters, the existing `pipeline.minimum` config is used if it is greater than the calculated value.
https://issues.apache.org/jira/browse/HDDS-8674
Added test case in `TestWritableECContainerProvider`.
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5054873935

HDDS-8674. Allow more EC pipelines based on number of volumes

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineStateMap.java

In the WriteableECContainerProvider, we need to get the list of open pipelines on each block allocation request.
Open pipelines for a replication config can be retrieved efficiently from the PipelineStateMap.query2OpenPipelines variable.
However the list then needs to be filtered to remove excluded datanodes or pipelines. In the common case, these exclusions will be empty, so we can optimize this by skipping the iterator if there is nothing to filter out.
https://issues.apache.org/jira/browse/HDDS-8680

HDDS-8680. Optimize getting open pipelines from pipelineManager

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/recon/ReconConfigKeys.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/server/ServerUtils.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/TestServerUtils.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java

The recommendation to set the permissions for the Apache Ozone DN, OM, SCM, Reccon metadata storage directories to 750 or tighter means that only the owner of the directory (in this case, the Hadoop user) and members of the Hadoop group should have access to the directory. By setting the permissions to 750, non-root users will not be able to read or write to the storage directories, which is important for protecting sensitive data.
The table represents the permissions configuration associated with each configuration property :- 
| Configuration Property               | Permissions |
|--------------------------------------|-------------|
| ozone.recon.db.dirs.permissions      | 750         |
| ozone.scm.db.dirs.permissions        | 750         |
| ozone.om.db.dirs.permissions         | 750 …

HDDS-8573. Verify default setting for DN root dir to restrict non-admin access

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECContainerReplicaCount.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java

With EC containers, if there is a small cluster of say 6 nodes with EC-3-2, a container will require 5 nodes. If 2 containers become unhealthy, reconstruction will be required to recover the 2 containers, but there is only 1 spare node.
This means one will get recovered, and we will have 4 "good" containers and 2 `UNHEALTHY` and the container will remain stuck like this because `UNHEALTHY` containers are only removed once the container has no over or under replication.
A similar problem was resolved previously where an EC container with both over and under replication can meet the same problem, where under replication cannot proceed due to insufficient spare nodes. In that case, the solution was to check for this case, and call the over-replication handler to clear up the excess replicas. …

HDDS-8535. ReplicationManager: Unhealthy containers could block EC recovery in small clusters

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/PipelineChoosePolicy.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/WritableECContainerProvider.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/choose/algorithms/HealthyPipelineChoosePolicy.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/choose/algorithms/RandomPipelineChoosePolicy.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestWritableECContainerProvider.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/choose/algorithms/TestPipelineChoosePolicyFactory.java

When iterating over the pipeline list, if a pipeline is not valid for selection, we call Array.remove(element) to remove it from the list before selecting another random element.
If the pipeline selection policy could return the array index of the selected pipeline rather than the actual pipeline, then we can use the more efficient Array.remove(index). Even this is still O(n) as the array has to shuffle the elements down the internal array, but it is better than Array.remove(element) as it avoids searching for the element.
https://issues.apache.org/jira/browse/HDDS-8682

HDDS-8682. EC: Avoid O(n) array.remove(element) when filtering pipelines in WritableECContainerProvider

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/hdds/datanode/metadata/CRLDBDefinition.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeSchemaOneDBDefinition.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeSchemaThreeDBDefinition.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeSchemaTwoDBDefinition.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/SchemaOneChunkInfoListCodec.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/SchemaOneKeyCodec.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/ByteArrayCodec.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/CodecRegistry.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/FixedLengthStringCodec.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/IntegerCodec.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/ShortCodec.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/StringCodec.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestCodec.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestDBStoreBuilder.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/metadata/BigIntegerCodec.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/metadata/SCMDBDefinition.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/metadata/X509CertificateCodec.java
hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/codec/TokenIdentifierCodec.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/codec/OMDBDefinition.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffJob.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestSnapshotDiffCleanupService.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/TestOzoneTokenIdentifier.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/codec/NSSummaryCodec.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/ContainerKeyPrefixCodec.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/KeyPrefixContainerCodec.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/ReconDBDefinition.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/TestReconCodecs.java

DB codec implementations can be singletons, as they are stateless.  Some classes already are, this PR changes the rest.
https://issues.apache.org/jira/browse/HDDS-8559
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5078351190

HDDS-8559. Codec implementations should be singleton

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerTask.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancer.java

Container balancer may fail to interrupt the current balancing thread.  We've seen various test execution times from 1 second to 10 minutes.
This change is a workaround to reduce test execution time.
1. Reduce node report interval from 1 minute to 2 seconds, safe mode wait time from 5 minutes to 5 seconds.
2. Fix mismatch between sleep time being logged and actual sleep duration.
3. Add a unique ID to balancer thread name so we can distinguish between runs.
https://issues.apache.org/jira/browse/HDDS-8676
1000x runs passed in CI, each batch of 100 runs in ~1 hour.
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5077320448
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5079590645

HDDS-8676. Speed up TestContainerBalancer

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerSet.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/BackgroundContainerMetadataScanner.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/ContainerController.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/upgrade/DataNodeUpgradeFinalizer.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestStaleRecoveringContainerScrubbingService.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerSet.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestContainerScannersAbstract.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/upgrade/TestHddsUpgradeUtils.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/container/InspectSubcommand.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/container/ListSubcommand.java

Use the iterator() method (and the Iterable interface) instead.
https://issues.apache.org/jira/browse/HDDS-8706
Modifying existing tests.

HDDS-8706. Remove ContainerSet.getContainerIterator().

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/client/io/SelectorOutputStream.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/client/io/TestSelectorOutputStream.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemWithStreaming.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneFSInputStream.java
hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java
hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java
hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java
hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java

We may buffer user data in OzoneFSOutputStream.
- If user closes the file and the file size is within a certain limit, use the createKey API to send the data.
* We may use PutSmallFile to further optimize it in the future.
- If user keeps writing and the bytes written is larger than the limit, use createStreamKey.
https://issues.apache.org/jira/browse/HDDS-8635
New unit tests.

HDDS-8635. Automatically select createKey and createStreamKey in OzoneFileSystem.

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/CodecBuffer.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/Proto2Codec.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBTable.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBTableStore.java
hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedRocksDB.java

Currently we use byte[] to get from RocksDB.  We should use RocksDB ByteBuffer APIs to reduce the number of buffer copying operations when the codec support `CodecBuffer`.
https://issues.apache.org/jira/browse/HDDS-8571
Added `testGetByteBuffer`.

HDDS-8571. Support get using RocksDB ByteBuffer APIs.

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBMetrics.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBTable.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBTableStore.java

- RocksDatabase.keyMayExist should be removed since it should always use keyMayExistHolder.
- We actually will rename keyMayExistHolder back to keyMayExist
- In RDBTable.isExist, it should not check value.length > 0 since it incorrectly excludes the zero size byte array case.
https://issues.apache.org/jira/browse/HDDS-8713
Modified an existing test.

HDDS-8713. Remove RocksDatabase.keyMayExist and the value.length check.

---

hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/container/ContainerTestHelper.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/ContainerTestUtils.java

Fix intermittent failure in `TestContainerPersistence`:
```
StorageContainerException: Container creation failed because ContainerFile already exists
at org.apache.hadoop.ozone.container.keyvalue.KeyValueContainer.create(KeyValueContainer.java:191)
at org.apache.hadoop.ozone.container.common.impl.TestContainerPersistence.addContainer(TestContainerPersistence.java:200)
at org.apache.hadoop.ozone.container.common.impl.TestContainerPersistence.testGetContainerReports(TestContainerPersistence.java:311)
```
Since "test container ID" was simply current time, next container could have the same ID.
https://issues.apache.org/jira/browse/HDDS-7457
10x100 repetitions:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5097065042
Regular CI: …

HDDS-7457. Intermittent failure in TestContainerPersistence

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java

When forming the InsufficientNodesException, we pass missingIndexes.size() as the expected node count. However if there are insufficient nodes, the expected list gets trimmed, so this count is incorrect. We should pass expectedNodes instead, which is the original list length.
```
2023-05-30 07:17:30,597 [Under Replicated Processor] ERROR org.apache.hadoop.hdds.scm.container.replication.UnhealthyReplicationProcessor: Error processing Health result of class: class org.apache.hadoop.hdds.scm.container.replication.ContainerHealthResult$UnderReplicatedHealthResult for container ContainerInfo{id=#54, state=CLOSED, pipelineID=PipelineID=d795e5a1-5eb9-4833-9c03-2b1342683b99, stateEnterTime=2023-05-30T06:50:10.331Z, owner=om1}
org.apache.hadoop.hdds.scm.pipeline.InsufficientDatanodesException: Not …
```

HDDS-8728. Incorrect expectedNodes passed to InsufficientNodesException

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/CodecBuffer.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBTable.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java
pom.xml

Use RocksDB ByteBuffer API: 
https://javadoc.io/static/org.rocksdb/rocksdbjni/7.7.3/org/rocksdb/RocksDB.html#keyMayExist-org.rocksdb.ColumnFamilyHandle-java.nio.ByteBuffer-java.nio.ByteBuffer-
https://issues.apache.org/jira/browse/HDDS-8725

HDDS-8725. Support keyMayExist with ByteBuffer.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequestWithFSO.java

Do not remove uncommitted blocks if hsync.
OM HSync handler leverages existing key commit logic. However, uncommitted blocks (meaning the block that is allocated but not used) is supposed to be removed upon key commit, because key is immutable after commit. But for hsync, key may still be written afterwards so it is not desirable to remove the uncommitted blocks.
https://issues.apache.org/jira/browse/HDDS-8259
Added one unit test to ensure the sequence of create-hsync-write-hsync-close is successful.

HDDS-8259. [hsync] OMKeyRequest: Detect allocated but uncommitted blocks

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/audit/OMAction.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OzoneManagerProtocol.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java
hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMetrics.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/BucketLayoutAwareOMKeyRequestFactory.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeySetTimesRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeySetTimesRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyAclRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeySetTimesResponse.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeySetTimesResponseWithFSO.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/TestBucketLayoutAwareOMKeyFactory.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMSetTimesRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMSetTimesRequestWithFSO.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientAdapter.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/Statistic.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/ClientProtocolStub.java

Support FileSystem.setTimes() API
https://issues.apache.org/jira/browse/HDDS-8278
Unit tests and file system integration tests.

HDDS-8278. O3fs/ofs to support setTimes() API

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java

Add a test to verify hsync file cannot be overtaken by another client.
https://issues.apache.org/jira/browse/HDDS-7947
Unit tests.

HDDS-7947. Disallow overwriting a hsync'ed key

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRackScatter.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackScatter.java

The usedNode count is missing in some log messages in the SCMContainerPlacementRackScatter placement policy.
Also, it checks at the start to see if there are enough available nodes, and the usedNodes need to be removed from the available nodes for the check to work correctly.
https://issues.apache.org/jira/browse/HDDS-8736
Added a unit test to validate the limit check

HDDS-8736. Add usedNodes to limit check and log messages in SCMContainerPlacementRackScatter

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/spi/impl/TestOzoneManagerServiceProviderImpl.java

When a cache metrics being registered for any OM DB table, it should check if cache metrics already registered or not. If it is already registered, then we should unregister first and allow registration. 
https://issues.apache.org/jira/browse/HDDS-8734
This patch was tested using existing unit test cases including initialisation of  new snapshot OM DB in Recon and do registration of cache metrics tables.

HDDS-8734. OM DB cache metrics creation should be idempotent

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/InsufficientDatanodesException.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/SimplePipelineProvider.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java

EC offline reconstruction has two properties that may be in conflict:
* tries to exclude from targets any datanodes that are currently overloaded with replication commands
* attempts partial reconstruction if full reconstruction is not possible due to lack of enough targets
This may result in multiple subsequent partial reconstructions, wasting resources.
This change lets SCM defer reconstruction if:
* only partial reconstruction is currently possible AND
* full reconstruction would be possible using overloaded nodes AND
* at least one more replica may be lost before the container becomes unrecoverable (i.e. recovery is not yet critical)
The improvement applies to EC(6,3) and EC(10,4) only, because EC(3,2) can only have 1 or 2 replicas missing before becoming unrecoverable: with 1 missing …

HDDS-8727. Defer non-critical partial EC reconstruction

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/OzoneAdmins.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneConfigUtil.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

There have some duplicate Method, such as `getOzoneAdminsFromConfig` , `getOzoneAdminsGroupsFromConfig` and `isAdmin` etc, This PR will move them to the class `OzoneAdmin`
https://issues.apache.org/jira/browse/HDDS-8737
The Existing tests

HDDS-8737. Organize Ozone admin related Methods into Class OzoneAdmin

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ratis/RatisHelper.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServer.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/Gateway.java

* Replace Hadoop's `JvmPauseMonitor` with the one from Ratis in OM and SCM for non-HA.  (With HA, Ratis automatically starts `JvmPauseMonitor`.)
* Remove Hadoop's `JvmPauseMonitor` from datanode (which also has the one from Ratis).
* Add `JvmPauseMonitor` in Recon and S3 Gateway.
* HttpFS is unchanged, as it uses `JvmPauseMonitor` with the Hadoop metrics.
https://issues.apache.org/jira/browse/HDDS-8731
Temporarily changed config in `ozone` compose environment to disable Ratis in OM and SCM:
```
OZONE-SITE.XML_ozone.scm.ratis.enable=false
OZONE-SITE.XML_ozone.om.ratis.enable=false
```
Checked logs for `JvmPauseMonitor` output:
```
scm_1       | 2023-06-01 07:08:27,260 [JvmPauseMonitor0] INFO util.JvmPauseMonitor: JvmPauseMonitor-53e975e9-f056-4c13-9ed0-1fd833e12de6: Started
om_1        | …
```

HDDS-8731. Standardize JVM pause monitor

---

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/EntityReadAccessHeatMapResponse.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/heatmap/HeatMapServiceImpl.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/heatmap/TestHeatMapInfo.java

This PR is to add "path" attribute in "`api/v1/heatmap/readaccess`" API response at each node level including  bucket and volume.
https://issues.apache.org/jira/browse/HDDS-8414
This patch is tested functionally using Junit test case assertion as well as verifying response of API through POSTMAN client where a new attribute "`path`" being added:
```
{
"label": "root",
"children": [
{
"label": "hivevolTest1",
"children": [
{
"label": "hivebucketTest1",
"children": [
{
"label": "enc_path/hive_tpcds/store_sales/test1.dat",
"size": 1026,
"path": "/hivevolTest1/hivebucketTest1/enc_path/hive_tpcds/store_sales/test1.dat",
"accessCount": 155074,
"color": 1
},
{
"label": "enc_path/hive_tpcds/catalog_sales/test2",
"size": 20,
"path": "/hivevolTest1/hivebucketTest1/enc_path/hive_tpcds/catalog_sales/t …
```

HDDS-8414. Recon: Heatmap Absolute Path in Response at end node level on HyperLink End Point Response.

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisor.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisorMetrics.java

To give added visibility into the Replication Queue on a datanode, this Jira adds some extra metrics to give visibility into the count of "normal priority" Replication and Reconstruction tasks, along with the current maxStreams setting, which is automatically adjusted when the node moves into decommission.
https://issues.apache.org/jira/browse/HDDS-8746
This was tested manually in Docker compose by sampling the JMX output. Sample output:
```
"name" : "Hadoop:service=HddsDatanode,name=ReplicationSupervisorMetrics",
"modelerType" : "ReplicationSupervisorMetrics",
"tag.Hostname" : "b297306fcf0f",
"numInFlightReplications" : 5,
"numQueuedReplications" : 4,
"numRequestedReplications" : 1,
"numTimeoutReplications" : 0,
"numSkippedReplications" : 0,
"maxReplicationStreams" : 1, ** newly added …
```

HDDS-8746. Add metrics to ReplicationSupervisor for task count and max streams

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/CodecBuffer.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java

For getting a value from DB, the value size is unknown when allocating a buffer.  Currently, we set the exact capacity in buffer allocation and, if the capacity is too small, reallocate a new buffer.  We should use an adjustable buffer and try to adjust the capacity if it is too small.
https://issues.apache.org/jira/browse/HDDS-8741
By existing `TestRDBTableStore.testGetByteBuffer()`: Before this change, it will show some "increaseBufferSize" messages.   After this change, the messages are gone since it will adjust the capacity instead of the allocating new buffers.

HDDS-8741. Use adjustable capacity CodecBuffer to get from DB.

---

hadoop-ozone/dist/src/main/compose/ozone/README.md
hadoop-ozone/dist/src/main/compose/ozone/run.sh

`run.sh` uses `$OZONE_REPLICATION_FACTOR` both to set the default replication factor and to decide how many datanodes to start.  This limits the number of datanodes to 1 or 3.  While datanodes can be scaled afterwards, it would be nice to be able to start the cluster with e.g. 5 datanodes in the first place.
https://issues.apache.org/jira/browse/HDDS-8726
Old usage (still works):
```
$ ./run.sh -d
$ OZONE_REPLICATION_FACTOR=3 ./run.sh -d
```
New usage:
```
$ OZONE_DATANODES=5 ./run.sh -d
```
(Also tested various combinations of the two parameters.)

HDDS-8726. Let run.sh start more than 3 datanodes

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataReader.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/acl/OzoneNativeAuthorizer.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/acl/TestOzoneNativeAuthorizer.java

`OzoneAdmins` instances owned by `OzoneManager` are passed around to other objects, which only need access to the `isAdmin` function.  This change refactors `OzoneNativeAuthorizer` to use a `Predicate` instead of a full `OzoneAdmins` object.
https://issues.apache.org/jira/browse/HDDS-8710
Refactoring, covered by existing tests:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5098439977

HDDS-8710. Expose read-only interface of OzoneAdmins to OzoneNativeAuthorizer

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/DefaultCAServer.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DefaultCertificateClient.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/utils/CertificateSignRequest.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/utils/SelfSignedCertificate.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/authority/TestDefaultCAServer.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/utils/TestRootCertificate.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecureOzoneCluster.java

TestSecureOzoneCluster#testOMGrpcServerCertificateRenew fails on some machines when run locally because the subject material and ips/dns configs are not properly created when generating the certificate for the test. This adds the configuration found in DefaultCertificateClient to fix this problem.
This issue was found during [Support multiple root ca certificates in trust stores](https://issues.apache.org/jira/browse/HDDS-8589) and the fix is provided in this pull request.
[HDDS-8738](https://issues.apache.org/jira/browse/HDDS-8738)
The test runs locally on @fapifta and my machine after these changes.
The actions on my fork are still running:
https://github.com/Galsza/ozone/actions/runs/5134337627
, but here is a run that …

HDDS-8738. Fix TestSecureOzoneCluster#testOMGrpcServerCertificateRenew local failures

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/WritableECContainerProvider.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestWritableECContainerProvider.java

Currently, if the pipeline limit is not reached, when a new block is requested, a new pipeline is allocated and returned to the client.
If the pipeline limit is reached, we attempt to return a pipeline from the existing set.
If none of those pipelines meet the criteria, then we fall back to creating another pipeline. This could result in unbounded pipeline growth if a client is having problems.
We should therefore limit the pipelines that can be created via this exceptional case.
For example, if we close some pipelines when searching the existing list (due to them being full), we know we have freed up some capacity to create a new pipeline.
https://issues.apache.org/jira/browse/HDDS-8698
Modified existing tests

HDDS-8698. EC: Avoid unbounded pipeline creation if all existing pipelines don't meet criteria

---

hadoop-hdds/config/pom.xml
hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/Config.java
hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigType.java
hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigurationReflectionUtil.java
hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigurationSource.java
hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ReconfigurableConfig.java
hadoop-hdds/config/src/test/java/org/apache/hadoop/hdds/conf/ConfigurationExample.java
hadoop-hdds/config/src/test/java/org/apache/hadoop/hdds/conf/TestConfigurationReflectionUtil.java
hadoop-hdds/config/src/test/java/org/apache/hadoop/hdds/conf/TestConfigurationSource.java
hadoop-hdds/config/src/test/java/org/apache/hadoop/hdds/conf/TestReconfigurableConfig.java
hadoop-hdds/config/src/test/resources/log4j.properties

* allow `@Config` properties to be marked as `reconfigurable`
* implement reconfiguration of annotated config object from `ConfigurationSource`
* create base class `ReconfigurableConfig` to help with keeping track of reconfigurable properties and handling updates
This is not tied into reconfiguration handling in OM/SCM/etc., will be done in follow-up.
https://issues.apache.org/jira/browse/HDDS-8668
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5073256233

HDDS-8668. Allow reconfiguration of annotated config object

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerSet.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestStorageVolumeChecker.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestVolumeSetDiskChecks.java

Currently when volume fail happens, DN just marks container UNHEALTHY and later when SCM receives this information, SCM tries to delete those containers , but since the volume has failed, delete container fails in DN.
In this change when there is volume fail, In DN we can remove those containers from container set and immediately send FCR to SCM.
SCM will get information about container is missing in particular DN so that SCM will replicate to other place.
https://issues.apache.org/jira/browse/HDDS-8448
Added test case.

HDDS-8448. Send FCR to SCM on volume failure.

---

hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/TestDefaultCertificateClient.java

In preparation for root CA cert rotation, the cert clients need to be able to store more than one root CA certificate. This functionality is already possible, but never actually used. The certs are just saved with the ROOT_CA prefix and their ID. Since the ID is unique, it won't cause collisions.
[HDDS-8587](https://issues.apache.org/jira/browse/HDDS-8587)
Only added testing, which run properly on my work:
https://github.com/Galsza/ozone/actions/runs/4977850423

HDDS-8587. Prepare CertificateClient to store more than one rootCA certificate

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/utils/CertificateCodec.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/Codec.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/CodecBuffer.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/StringCodecBase.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/io/LengthOutputStream.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/io/package-info.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/utils/db/CodecTestUtil.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestCodec.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/metadata/X509CertificateCodec.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/metadata/OldX509CertificateCodecForTesting.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/metadata/TestPipelineIDCodec.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/metadata/TestX509CertificateCodec.java

Support CodecBuffer for X509CertificateCodec so it can use the RocksDB ByteBuffer API.
https://issues.apache.org/jira/browse/HDDS-8761
New tests

HDDS-8761. Support CodecBuffer for X509CertificateCodec.

---

dev-support/ci/selective_ci_checks.bats
dev-support/ci/selective_ci_checks.sh

HDDS-8669 only updated README.md.  [PR acceptance check](https://github.com/apache/ozone/actions/runs/5154144097) is unnecessary for such changes.
https://issues.apache.org/jira/browse/HDDS-8751
Added test case in bats tests.

HDDS-8751. Selective checks: skip tests for doc changes in compose or k8s

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BufferPool.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestBufferPool.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChunkBufferImplWithByteBuffer.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinator.java

Avoid unnecessary `BufferPool` creation for EC reconstruction flow:
```
// TODO: Let's avoid unnecessary bufferPool creation. This pool actually
//  not used in EC flows, but there are some dependencies on buffer pool.
```
Use an empty singleton `BufferPool` for that.
Also, convert some validation checks to real preconditions in `BufferPool` (i.e. perform the check before changing state, not afterwards).
https://issues.apache.org/jira/browse/HDDS-8766
Existing tests:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5186666728

HDDS-8766. Use empty BufferPool for EC reconstruction

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnhealthyReplicationProcessor.java

When processing the unhealthy container queues, we would expect quite a large number of containers to have processing deferred due to load on the datanodes. At the moment, these are logged at ERROR level, which is probably too verbose and also the messages are expected, so ERROR will likely worry administrators.
This change moves that to debug level, and also adds a counter so we can print a summary of how many containers were deferred due to load after each iteration.
https://issues.apache.org/jira/browse/HDDS-8776
No tests added or changed. This is just a logging change.

HDDS-8776. ReplicationManager: Log overloaded commands at debug rather than error level

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/HASecurityUtils.java

ManagedChannel leak. This is not caught in master because there's no integration test with secure MiniOzoneHAClusterImpl. 
```
Jun 07, 2023 4:29:35 PM org.apache.ratis.thirdparty.io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Previous channel ManagedChannelImpl{logId=538, target=localhost:65138} was not shutdown properly!!! ~*~*~*
Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
at org.apache.ratis.thirdparty.io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:100)
at org.apache.ratis.thirdparty.io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:60)
at …
```

HDDS-8780. Leak of ManagedChannel in HASecurityUtils

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/BlockDeletingServiceMetrics.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingService.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java

Add a Metrics to monitor the `Pending Block` Count.
`block_deleting_service_metrics_total_pending_block_count{context="dfs",hostname="centos"} 0`
```
[root@centos ~/root/ozone]$ curl -s http://127.0.0.1:9882/prom  | grep block_deleting_service_metrics | grep -v '#'
block_deleting_service_metrics_failure_count{context="dfs",hostname="centos"} 0
block_deleting_service_metrics_out_of_order_delete_block_transaction_count{context="dfs",hostname="centos"} 0
block_deleting_service_metrics_success_bytes{context="dfs",hostname="-centos"} 0
block_deleting_service_metrics_success_count{context="dfs",hostname="centos"} 0
block_deleting_service_metrics_total_pending_block_count{context="dfs",hostname="centos"} 0
[root@centos ~/root/ozone]$ 
```
https://issues.apache.org/jira/browse/HDDS-8729
manual …

HDDS-8729. Add metrics for count of pending Block on DN

---

hadoop-ozone/dist/src/main/smoketest/admincli/datanode.robot
hadoop-ozone/dist/src/main/smoketest/basic/ozone-shell-lib.robot

Minor refactoring of some robot tests to reduce the number of identical `ozone sh` calls.
https://issues.apache.org/jira/browse/HDDS-8787
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5208905246

HDDS-8787. Reduce ozone sh calls in robot tests

---

.github/workflows/ci.yml
hadoop-ozone/dist/src/main/compose/ozone/test-ec.sh

Extract EC-related tests into a separate acceptance check split.
Add unique name for the two repeated `read.robot` executions.
https://issues.apache.org/jira/browse/HDDS-8790
Ran `test-ec.sh` locally.
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5209512124/jobs/9399896144

HDDS-8790. Split EC acceptance tests

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/OzoneQuota.java
hadoop-hdds/docs/content/feature/Quota.md
hadoop-hdds/docs/content/feature/Quota.zh.md

Added a note in quota documentation for below 2 conditions
- In setquota [Volume & Bucker level ] doesn't accepts decimals 
- Minimum Storage quota should be default block size * replication factor 
[HDDS-8373](https://issues.apache.org/jira/browse/HDDS-8373)
[HDDS-8372](https://issues.apache.org/jira/browse/HDDS-8372)
UT

HDDS-8373. Document that setquota doesn't accept decimals

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/ObjectStore.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OzoneManagerProtocol.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmMetrics.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmMetadataManager.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/ClientProtocolStub.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/snapshot/ListSnapshotHandler.java

(cherry picked from commit 9f84c77)
The original PR (#4065) targeted the snapshot feature branch. Unfortunately, I merged that PR after feature branch's merge to master (didn't check the PR target branch at the time of merge). So it is missing from master branch. Thanks @hemantk-12 for catching this.
And because this backport requires more than just simple conflict resolution. I have posted this as a new PR for formality.
- Cherry-picked 9f84c77613c66f5b0c24bb6b41eb13c29ecf8fcc to `master` branch
- Resolved two minor conflicts
- Fixed usage in `listStatusBucketSnapshot` and a test because of the API change: d6d23cbd39226bcfe220abe00d315577adfb3ce3
- `getNextListOfSnapshots()` now throws IOException directly, rather than wrapping it in another `RuntimeException`: …

HDDS-7507. [Snapshot] Implement List Snapshot API Pagination (#4065)

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManagerMetrics.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java

Adding a metric for the number of containers where we fail to send a delete, replication or reconstruction due to the throttling. This will give some visibility into how often throttling is occurring.
New metrics are:
```
ecReconstructionCmdsDeferredTotal
deleteContainerCmdsDeferredTotal
replicateContainerCmdsDeferredTotal
```
https://issues.apache.org/jira/browse/HDDS-8801
Adapted tests to check metric is getting incremented

HDDS-8801. ReplicationManager: Add metric to count how often replication is throttled

---

hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/TestDefaultCertificateClient.java

Pull request opened for master from feature branch PR, because the feature branch is going to be abandoned:
https://github.com/apache/ozone/pull/4717
For root CA cert rotation, it's necessary to enable the cert client to store multiple root CA certificates. This functionality already exists, here I'm just adding testing just to be sure. 
[HDDS-8587](https://issues.apache.org/jira/browse/HDDS-8587)
CI runs on both my fork and on feature branch this was merged. Only testing functionality has been updated.

HDDS-8587. Test that CertificateClient can store multiple rootCA certificates

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBBatchOperation.java

`TestScmHAFinalization` intermittently reports `Found 2 leaked objects` (`CodecBuffer` instances).
```
2023-06-08 19:50:12,664 [Finalizer] WARN  db.CodecBuffer (CodecBuffer.java:finalize(129)) - LEAK 1: org.apache.hadoop.hdds.utils.db.CodecBuffer@292f4cc4, refCnt=1, capacity=3 allocation:
org.apache.hadoop.hdds.utils.db.CodecBuffer.allocate(CodecBuffer.java:74)
...
org.apache.hadoop.hdds.utils.db.TypedTable.putWithBatch(TypedTable.java:172)
```
`CodecBuffer`s created for batch operations are released on commit.  They are leaked if the batch is closed without commit.
https://github.com/apache/ozone/blob/b479a384e854b6eb62c429801ec3ce2acfa3c160/hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBBatchOperation.java#L333-L339
This PR fixes the leak by clearing the batch's …

HDDS-8803. Release CodecBuffers when batch operation is closed

---

hadoop-ozone/dist/src/main/compose/xcompat/clients.yaml
hadoop-ozone/dist/src/main/compose/xcompat/test.sh

Run cross-compatibility test for both 1.3.0 (already released) and 1.4.0 (built from source).
https://issues.apache.org/jira/browse/HDDS-8768
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5191899874

HDDS-8768. Update cross-compatibility test for 1.3.0 release

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestBlockTokens.java

TestBlockTokens uses methods that are removed in Hadoop 3.3. This prevents ozone to build with later versions of Hadoop. 
```
INFO    : [ERROR] /grid/0/jenkins/workspace/workspaceSOURCES/ozone/hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestBlockTokens.java:[243,14] cannot find symbol
INFO    :   symbol:   method setID(byte[])
INFO    :   location: variable token of type org.apache.hadoop.security.token.Token<org.apache.hadoop.hdds.security.token.OzoneBlockTokenIdentifier>
INFO    : [ERROR] /grid/0/jenkins/workspace/workspace/SOURCES/ozone/hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestBlockTokens.java:[262,14] cannot find symbol
INFO    :   symbol:   method setPassword(byte[])
INFO    :   location: variable token of type …
```

HDDS-8828. Adapt TestBlockTokens to build with Hadoop 3.3

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/OverReplicatedProcessor.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnderReplicatedProcessor.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnhealthyReplicationProcessor.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestOverReplicatedProcessor.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestUnderReplicatedProcessor.java

Refactor `ReplicationManager` and related classes to prepare for dynamic reconfigurability.  Avoid storing config in member variables.
https://issues.apache.org/jira/browse/HDDS-8813
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5235703783

HDDS-8813. Prepare for dynamic config in ReplicationManager

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/CertificateClient.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DefaultCertificateClient.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/CertificateClientTestImpl.java

Reorganize the loadAllCertificates code in the DefaultCertificateClient, to make it more easy to understand what is actually happening.
Reduce visibility of getCACertPath method which is used only within the DefaultCertificateClient.
https://issues.apache.org/jira/browse/HDDS-8755
Existing JUnit tests.

HDDS-8755. Cleanup loadAllCertificates code in DefaultCertificateClient.

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/StorageVolume.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/BackgroundContainerDataScanner.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/BackgroundContainerMetadataScanner.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OnDemandContainerDataScanner.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/ContainerTestUtils.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueHandlerWithUnhealthyContainer.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestBackgroundContainerDataScanner.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestBackgroundContainerMetadataScanner.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestContainerScannersAbstract.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOnDemandContainerDataScanner.java

- Background container data scanner threads should terminate when their volume is marked unhealthy.
- When a container fails a scan, a volume scan should be done before marking it unhealthy to determine whether the problem is specific to the container or the volume.
HDDS-7365
Unit tests added.

HDDS-7365. Integrate container and volume scanners.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java

Fix `UnsupportedOperationException` thrown by `SCMCommonPlacementPolicy` due to trying to modify an `ImmutableList` passed from `ECUnderReplicationHandler`.
```
java.lang.UnsupportedOperationException
at com.google.common.collect.ImmutableList.set(ImmutableList.java:528)
at org.apache.hadoop.hdds.scm.SCMCommonPlacementPolicy.validateDatanodes(SCMCommonPlacementPolicy.java:162)
at org.apache.hadoop.hdds.scm.SCMCommonPlacementPolicy.chooseDatanodes(SCMCommonPlacementPolicy.java:208)
at org.apache.hadoop.hdds.scm.container.replication.ReplicationManagerUtil.getTargetDatanodes(ReplicationManagerUtil.java:83)
at org.apache.hadoop.hdds.scm.container.replication.ECUnderReplicationHandler.getTargetDatanodes(ECUnderReplicationHandler.java:396)
at …
```

HDDS-8831. UnsupportedOperationException when there are more replication tasks than limit

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/LocalStream.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/KeyValueStreamDataChannel.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/StreamDataChannelBase.java

Clean up datanode memory in case of an ozone stream write error
https://issues.apache.org/jira/browse/HDDS-8848

HDDS-8848. Clean up datanode memory in case of an ozone stream write error

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/SCMCommonPlacementPolicy.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerReportHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/IncrementalContainerReportHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DeadNodeHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/HealthyReadOnlyNodeHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerImpl.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestContainerPlacementFactory.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementCapacity.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackAware.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackScatter.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRandom.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconIncrementalContainerReportHandler.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconNodeManager.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconIncrementalContainerReportHandler.java

Add `getNodeByUuid(UUID)` to avoid `UUID.fromString` conversion when looking up datanodes.
https://issues.apache.org/jira/browse/HDDS-8826
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5268395265

HDDS-8826. Avoid String to UUID conversion in SCMNodeManager

---

hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzonePathCapabilities.java

Add Path capability for FS snapshots to prevent this exception.
https://issues.apache.org/jira/browse/HDDS-8857

HDDS-8857. [snapshot] UnsupportedOperationException for snapshot distcp operation.

---

hadoop-ozone/dist/src/main/smoketest/snapshot/snapshot-sh.robot
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/snapshot/SnapshotDiffHandler.java

`ozone sh snapshot snapshotDiff` would be more user-friendly simply as `ozone sh snapshot diff`.  Hierarchical sub-commands help establish context, no need for repeating "snapshot".
https://issues.apache.org/jira/browse/HDDS-8789
Updated acceptance test.
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5230130623/jobs/9444144097#step:5:953

HDDS-8789. Simplify snapshot diff command name

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/CpuMetrics.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java
hadoop-ozone/integration-test/dev-support/findbugsExcludeFile.xml
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestCpuMetrics.java

Expose CPU load (process & system) and available processors metrics to Prometheus
https://issues.apache.org/jira/browse/HDDS-8836
new integration test that's located in  hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestCpuMetrics.java

HDDS-8836. Expose cpu load and available processors metrics

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/utils/CertificateSignRequest.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/utils/SelfSignedCertificate.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/RatisNameRewriteSampleBuilder.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHANodeDetails.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/S3SecretManagerImpl.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/DecommissionOMSubcommand.java

Replace usage of org.apache.logging.log4j.util.Strings  with org.apache.commons.lang3.StringUtils
https://issues.apache.org/jira/browse/HDDS-8861
Verified the logic of isBlank/isNotEmpty/join methods are same across both versions.

HDDS-8861. Replace usage of log4j2 Strings class.

---

hadoop-ozone/dist/src/main/compose/ozone/test-ec.sh

Test EC container reconstruction, by waiting for replica count to reach 5 after 2 nodes were shutdown (for online reconstruction test) and restarted.
https://issues.apache.org/jira/browse/HDDS-8791
New test.  Also checked the logs:
```
datanode_4  | 2023-06-14 18:01:32,007 [ContainerReplicationThread-0] INFO reconstruction.ECReconstructionCoordinatorTask: IN_PROGRESS reconstructECContainersCommand: containerID=1, replication=rs-3-2-1024k, missingIndexes=[2, 3], sources={1=493f541b-c7f3-4b67-8f6d-8d341b56bf6c(ozone_datanode_1.ozone_default/172.18.0.8), 4=4a76fdb2-a7c7-4f03-93cc-59392b2b01fb(ozone_datanode_2.ozone_default/172.18.0.7), 5=957afea6-7c0d-4fbe-9f0c-4873208ae6f7(ozone_datanode_3.ozone_default/172.18.0.10)}, targets={2=fba614af-5325-4851-82e7-01fd06c6e8a4(ozone_datanode_4.ozone_def …
```

HDDS-8791. Create acceptance test for offline recovery

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBTable.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java

When the codec support CodecBuffer, use RocksDB ByteBuffer delete API.
HDDS-8762

HDDS-8762. Support RocksDB delete with ByteBuffer.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/MisReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManagerMetrics.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/UnhealthyReplicationProcessor.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECMisReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestMisReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestUnderReplicatedProcessor.java

Add additional metrics to ReplicationManagerMetrics:
* PendingReplicationClusterLimitReached - incremented if the cluster wide limit has been reached.
* Partial Reconstruction metrics to indicate when EC reconstruction is not able to recover all the indexes, only some of them.
* Partial replication metrics for EC decommission / maintenance replicas and Ratis replication.
https://issues.apache.org/jira/browse/HDDS-8850
Tests modified to check the new metrics.

HDDS-8850. ReplicationManager: Add metrics for partial replication / reconstruction and cluster limit

---

hadoop-ozone/csi/pom.xml
pom.xml

Bump Guava to `32.0.0-jre`.
Fix dependency convergence error:
```
Dependency convergence error for com.google.j2objc:j2objc-annotations:jar:1.3 paths to dependency are:
+-org.apache.ozone:ozone-integration-test:jar:1.4.0-SNAPSHOT
+-org.apache.ozone:ozone-csi:jar:1.4.0-SNAPSHOT:compile
+-com.google.protobuf:protobuf-java-util:jar:3.19.6:compile
+-com.google.j2objc:j2objc-annotations:jar:1.3:compile
and
+-org.apache.ozone:ozone-integration-test:jar:1.4.0-SNAPSHOT
+-org.apache.ozone:ozone-csi:jar:1.4.0-SNAPSHOT:compile
+-com.google.guava:guava:jar:32.0.0-jre:compile
+-com.google.j2objc:j2objc-annotations:jar:2.8:compile
```
https://issues.apache.org/jira/browse/HDDS-8853
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5276513789

HDDS-8853. Bump Guava to 32.0.0-jre

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/BlockDeletingServiceMetrics.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/DeletedContainerBlocksSummary.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingService.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java

Add more BlockDeletingServiceMetrics to Monitor the Datanode
```bash
block_deleting_service_metrics_failure_count{context="dfs",hostname="VM-8-3-centos"} 0
block_deleting_service_metrics_marked_block_count{context="dfs",hostname="VM-8-3-centos"} 5210
block_deleting_service_metrics_out_of_order_delete_block_transaction_count{context="dfs",hostname="VM-8-3-centos"} 1
block_deleting_service_metrics_received_block_count{context="dfs",hostname="VM-8-3-centos"} 5210
block_deleting_service_metrics_received_container_count{context="dfs",hostname="VM-8-3-centos"} 20
block_deleting_service_metrics_received_retry_transaction_count{context="dfs",hostname="VM-8-3-centos"} 0
block_deleting_service_metrics_received_transaction_count{context="dfs",hostname="VM-8-3-centos"} 28 …
```

HDDS-8881. Add more BlockDeletingServiceMetrics to Monitor the Datanode

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/ListOptions.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/volume/ListVolumeHandler.java

Currently ListOptions provide -l option to override number of results return. 
In this PR providing a way to return all results by providing --all option applicable for command which is using ListOptions like ListVolume, ListBucket, ListKeys.
- Using --all option for listKeys
`ozone sh key list --all o3://localhost:9862/vol11/bucket1
`
[ {
"volumeName" : "vol11",
"bucketName" : "bucket1",
"name" : "key1",
"dataSize" : 0,
"creationTime" : "2023-06-19T11:04:46.584Z",
"modificationTime" : "2023-06-19T11:04:46.640Z",
},
"metadata" : { }
}, {
"volumeName" : "vol11",
"bucketName" : "bucket1",
"name" : "key2",
"dataSize" : 0,
"creationTime" : "2023-06-19T11:04:50.748Z",
"modificationTime" : …

HDDS-8887. Support --all option in ListOptions.

---

hadoop-ozone/ozone-manager/null/snapDiff/_README.txt
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconConstants.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/ContainerEndpoint.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestContainerEndpoint.java

In the modified code, the pagination and filtering logic is applied to : `getContainerMisMatchInsights()`
**For the notSCMContainers list (OM containers not in SCM):**
- If prevKey is greater than 0, the method finds the index of the next container after prevKey and retrieves the sublist from that index up to the specified limit.
- If prevKey is negative, we return `NOT_ACCEPTABLE`
**For the nonOMContainers list (SCM containers not in OM):**
- Similar to the previous section, the pagination logic is applied to retrieve the sublist of containers based on the prevKey and limit.
**Filter Parameter:** 
- The `missingIn` filter parameter is used in the `getContainerMisMatchInsights` method to specify whether the returned container discrepancies should be based on containers missing in the …

HDDS-8701. Recon - Improve Mismatched container info API (containers/v1/mismatch).

---

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/bucket/ListBucketHandler.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/keys/ListKeyHandler.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/snapshot/ListSnapshotHandler.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/volume/ListVolumeHandler.java

We should avoid mixing JSON output with hints, which can lead to jq parse failure.
In this PR, In code where hints are printed with stdout is replaced by stderr.
https://issues.apache.org/jira/browse/HDDS-8858
Verified in local cluster to see json/err redirection
`$$ozone sh key list -l 1 o3://localhost:9862/vol11/ > a.txt`
`Listing first 1 entries of the result. Use --length (-l) to override max returned keys.`
```
$$cat a.txt 
[ {
"volumeName" : "vol11",
"bucketName" : "bucket1",
"name" : "key1",
"dataSize" : 0,
"creationTime" : "2023-06-19T11:04:46.584Z",
"modificationTime" : "2023-06-19T11:04:46.640Z",
},
"metadata" : { }
} ]
```

HDDS-8858. Do not mix JSON output with hints.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMSecurityProtocolServer.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/server/TestSCMClientProtocolServer.java

Scm supports read only administrators.
https://issues.apache.org/jira/browse/HDDS-8456
ut

HDDS-8456. Support read-only administrators in SCM

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/CommandHandlerMetrics.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CloseContainerCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/ClosePipelineCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CommandDispatcher.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CreatePipelineCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteContainerCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/FinalizeNewLayoutVersionCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/ReconstructECContainersCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/RefreshVolumeUsageCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/ReplicateContainerCommandHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/SetNodeOperationalStateCommandHandler.java

Add CommandHandler Metrics
```
command_handler_metrics_command_received_count{context="CommandHandlerMetrics",command="closeContainerCommand",hostname="VM-8-3-centos"} 8
command_handler_metrics_command_received_count{context="CommandHandlerMetrics",command="closePipelineCommand",hostname="VM-8-3-centos"} 6
command_handler_metrics_command_received_count{context="CommandHandlerMetrics",command="createPipelineCommand",hostname="VM-8-3-centos"} 2
command_handler_metrics_command_received_count{context="CommandHandlerMetrics",command="deleteBlocksCommand",hostname="VM-8-3-centos"} 1
command_handler_metrics_command_received_count{context="CommandHandlerMetrics",command="deleteContainerCommand",hostname="VM-8-3-centos"} 0
command_handler_metrics_command_received_count{context="CommandHandlerMetric …
```

HDDS-8868. Support CommandHandler Metrics

---

hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBStoreBuilder.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SstFilteringService.java

By default rocks db opens all sst files by default thereby increasing the total number of sst files.
Limit number of open files for each snapshot db loaded into the snapshot cache.
Make this number a configurable value for the snapshot dbs.
https://issues.apache.org/jira/browse/HDDS-8842
Unit tests pass which were earlier failing because of too many open files.

HDDS-8842. [Snapshot] Limit number of open files for each snapshot RocksDB instance

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestAddRemoveOzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

When we decommission an OM node and then try to bootstrap a new OM node then ratis try to apply previous transactions and the call goes to "addOMNodeToPeers()" of OzoneManager.java which results in throwing off an exception as it's not able to find the details of the decommissioned node in the conf which is correct as node doesn’t exist as an OM now. So, we are changing the exception to a warning message so that process flow shouldn't stop and newly bootstrapped OM doesn’t get shut down.
https://issues.apache.org/jira/browse/HDDS-8872

HDDS-8872. New bootstrapped OM shouldn’t shutdown if ratis applies previous transactions

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/SnapshotDeletingService.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/RocksDbPersistentMap.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffObject.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDiffManager.java

This change is to return correct snapshot diff when key is renamed and overridden.
Currently it return rename diff entry only.
```
R    ./key -> ./key_renamed
```
After the change it would be rename and modify
```
R    ./key -> ./key_renamed
M    ./key
```
https://issues.apache.org/jira/browse/HDDS-8841
Updated integration tests.

HDDS-8841. [Snapshot] Fix to return correct snapshotDiff when key is renamed and overridden.

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotManager.java

Checkpoint creation should be idempotent in the case of log replays.
https://issues.apache.org/jira/browse/HDDS-8685
Existing UT and New UT.

HDDS-8685. [SNAPSHOT] CreateCheckpoint needs to be idempotent.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestSecretKeySnapshot.java

Intermittent happens because it may take time for secret keys to be replicated to followers. 
https://issues.apache.org/jira/browse/HDDS-8839
Standard CI: https://github.com/duongkame/ozone/actions/runs/5340376630

HDDS-8839. Intermittent failure in TestSecretKeySnapshot.testInstallSnapshot

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java

`datanode.replication.limit < datanode.reconstruction.weight` should not be allowed in configuration, otherwise EC reconstruction will never be scheduled.
https://issues.apache.org/jira/browse/HDDS-8898
Tested by setting replication limit to 2:
```
scm_1       | [main] ERROR server.StorageContainerManagerStarter: SCM start failed with exception
scm_1       | java.lang.IllegalArgumentException: replicationLimit should be >= reconstruction weight 3, but was set to 2
scm_1       | 	at org.apache.hadoop.hdds.scm.container.replication.ReplicationManager$ReplicationManagerConfiguration.validate(ReplicationManager.java:1340)
scm_1       | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
scm_1       | 	at …
```

HDDS-8898. Replication limit should not be less than reconstruction weight

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/StringUtils.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/CodecBuffer.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/PutToByteBuffer.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/StringCodecBase.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/AutoCloseSupplier.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStoreAbstractIterator.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStoreByteArrayIterator.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStoreCodecBufferIterator.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBTable.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RawKeyValue.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/Table.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStoreByteArrayIterator.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStoreCodecBufferIterator.java

Use RocksDB's ByteBuffer API to implement `Table.KeyValueIterator`.
HDDS-8763
Added new tests.

HDDS-8763. Support RocksDB iterator with ByteBuffer.

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeConfiguration.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainer.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/KeyValueContainerUtil.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestDeleteContainerHandler.java

Currently we are checking both rocks db as well as disk to determine whether container is really empty or not. There are certain scenario where blocks remains on disk and causing container delete fail forever.
More details is in the Jira.
In this PR we are changing default value of hdds.datanode.check.empty.container.on-disk.on.delete to false, which will make container empty check just depends on rocksdb by default.
https://issues.apache.org/jira/browse/HDDS-8838
Verified using new integration test and with existing test.

HDDS-8838. Update default datanode check empty containter on disk to false

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/SnapshotInfo.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmSnapshotInfo.java
hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotMoveDeletedKeysRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotPurgeRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyPurgeResponse.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotPurgeResponse.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/AbstractKeyDeletingService.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/KeyDeletingService.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/SnapshotDeletingService.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotUtils.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotPurgeRequestAndResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestKeyDeletingService.java

This change allows the `KeyDeletingService` to reclaim those trapped keys from the snapshot's `deletedTable`. Every snapshot is deep cleaned once they are created, after that snapshots are only deep cleaned if the previous snapshot is deleted. 
https://issues.apache.org/jira/browse/HDDS-7968
Existing and New UTs.

HDDS-7968. [Snapshot] Improve KeyDeletingService to reclaim eligible key blocks in snapshot's deletedTable

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDiffManager.java

This change is to add unit tests for `SnapshotDiffManager`.
https://issues.apache.org/jira/browse/HDDS-8315
Ran newly added test locally.

HDDS-8315. [Snapshot] Added unit tests for SnapshotDiffManager

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeStateManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java

Add `getNode(UUID)` in `NodeStateManager` so that callers with only `UUID` can avoid creation of temporary `DatanodeDetails`.
Change `dnsToUuidMap` in `SCMNodeManager` to store `UUID` instead of `String`.
https://issues.apache.org/jira/browse/HDDS-8854
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5298453058

HDDS-8854. Avoid unnecessary DatanodeDetails creation for NodeStateManager lookup

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/SCMPipelineMetrics.java

Reduce the amount of work done by `PipelineManagerImpl` while holding its global write lock.  Move out:
* `pipelineID` conversion
* metrics update
* some log statements
https://issues.apache.org/jira/browse/HDDS-8905
Refactoring, covered by existing tests.
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5345235126

HDDS-8905. PipelineManager metrics should not be synchronized

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeInfo.java

Failed volume count should be calculated when storage report is updated, instead of on each call to `DatanodeInfo#getFailedVolumeCount`.
https://issues.apache.org/jira/browse/HDDS-8907
Refactoring, covered by existing tests.
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5344930453

HDDS-8907. Store volume count when storage report is updated

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeStateManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/states/NodeStateMap.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/states/TestNodeStateMap.java

Try to avoid the stream created for `NodeStateManager#getNodes(IN_SERVICE, HEALTHY)` (invoked by `totalHealthyVolumeCount`).
https://issues.apache.org/jira/browse/HDDS-8906
Refactoring, covered by existing tests.
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5346100498

HDDS-8906. Avoid stream when getting in-service healthy nodes

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineStateManagerImpl.java

There are a few places where protobuf conversion is perform under a lock in PipelineStateManagerImpl. We should move these outside of the lock.
There are also some log messages issued under the lock, which I also moved out.
https://issues.apache.org/jira/browse/HDDS-8917

HDDS-8917. Move protobuf conversion out of the lock in PipelineStateManagerImpl

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerStateManagerImpl.java

`ContainerStateManagerImpl` uses `LockManager` for maintaining a set of locks to be used per container ID.  Similar to HDDS-8765, it should be replaced with `Striped` locks.
https://issues.apache.org/jira/browse/HDDS-8910
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5346927967

HDDS-8910. Replace LockManager with striped lock in ContainerStateManager

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/RepeatedOmKeyInfo.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/OMDBInsightEndpoint.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/OmTableInsightTask.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/OMMetadataManagerTestUtils.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestOmDBInsightEndPoint.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestOmTableInsightTask.java

We generate the keysSummary for `keys/deletePending` endpoint of the `ODBInsightEndpoint` class. Similar to how it was done for `keys/open` endpoint of the same class. 
```
{
"keysSummary": {
"totalUnreplicatedDataSize": 17289,
"totalReplicatedDataSize": 51867,
"totalDeletedKeys": 1
},
"lastKey": "/volume/bucket/key/-9223372036854774527",
"replicatedDataSize": 51867,
"unreplicatedDataSize": 17289,
"deletedKeyInfo": [
{
"omKeyInfoList": [
{
<Key Metadata>
}
],
"totalSize": {
"51867": 17289
}
}
],
"status": "OK"
}
```
https://issues.apache.org/jira/browse/HDDS-8586
Manual Testing and Unit Testing

HDDS-8586 Recon. - API for Count of deletePending keys and amount of data mapped to such keys.

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockInputStream.java

The XceiverClient cache is often expired when using ec reads
I am currently using ec for large concurrent reads and found that on the client side, a large number of XceiverClient cache remove logs .
Now each read builds a new pipeline, I think we can use the datanode id, as the pipeline id, so that we can take the client's XceiverClient cache.
https://issues.apache.org/jira/browse/HDDS-8922
Existing test

HDDS-8922. Random EC pipeline ID causes XceiverClient cache churn

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/QuotaRepairTask.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestQuotaRepairTask.java

- reset of quota value "-2" to "-1" as to disable warning to support quota after re-calculation
https://issues.apache.org/jira/browse/HDDS-8885
UT case is added

HDDS-8885. Quota repair count enable quota feature for old bucket/volume

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/interfaces/Container.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainer.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/BackgroundContainerMetadataScanner.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/ContainerTestUtils.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestBackgroundContainerDataScanner.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestBackgroundContainerMetadataScanner.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestContainerScannersAbstract.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOnDemandContainerDataScanner.java

Fix container metadata scanner to not scan unhealthy containers. Add tests for all scanners that they do not scan unhealthy containers. 
HDDS-8927
Unit tests added.

HDDS-8927. Metadata scanner should not scan unhealthy containers.

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/DbVolume.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/MutableVolumeSet.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/StorageVolume.java

If failures happen during volume initialization, the volume object is abandoned, and a failed volume created instead.  The original object should be cleaned up.
1. `StorageVolume#initialize` may throw `IOException`.  By this time it may have started background thread for disk usage check.  `HddsVolume` also created and registered metrics objects.
2. `MutableVolumeSet#initializeVolumeSet` also may throw `IOException` if storage directory does not exist and cannot be created.
To reproduce, simply add `/root` as an additional data or DB directory (assuming non-root user runs datanode):
```
OZONE-SITE.XML_hdds.datanode.dir=/root,/data/hdds
OZONE-SITE.XML_hdds.datanode.container.db.dir=/root,/data/metadata/db
```
Failed data volume results in datanode stopping during startup:
```
datanode_1  | …
```

HDDS-8914. Datanode may fail to start due to duplicate VolumeInfoMetrics

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/InterSCMGrpcProtocolService.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestInterSCMGrpcProtocolService.java

Currently the InterSCMGrpcProtocol service endpoint on SCM does not require client authentication. This change is about adding the requirement, and verify with a test that mTLS is working, and set.
The newly added test fails without the change in the InterSCMGrpcProtocolService class.
https://issues.apache.org/jira/browse/HDDS-8901
Added JUnit test to verify client and service certificates are properly sent for the configured trust managers for checking if the client/server is trusted.

HDDS-8901. Enable mTLS for InterSCMGrpcProtocol.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerImpl.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/MockPipelineManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java

As it stands, the method:
```
PipelineManager.createPipeline(ReplicationConfig replicationConfig,
List<DatanodeDetails> excludedNodes, List<DatanodeDetails> favoredNodes)
```
Is used to create a new pipeline and add it to the Pipeline manager. This creation and adding is all performed under a single lock The somewhat expensive node selection process from the placement policy is performed under the lock.
For Ratis pipelines, this could be important, as pipelines are created and limited based on the number of existing pipelines on the nodes.
EC pipelines do not have such a limitation, and they also need to be created much more frequently due to their short lived nature.
This PR changes the pipeline manager to have a buildPipeline Method, which calls the placement policy and creates the new …

HDDS-8919. Allow EC pipelines to be created and then added to PipelineManager in two steps

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestRandomKeyGenerator.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/BaseFreonGenerator.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/FollowerAppendLogEntryGenerator.java

Fix edge case in `BaseFreonGenerator` which happens if there are tasks in progress when `ProgressBar` shutdown/termination is initiated AND one or more of these in-progress tasks fail.
Repro:
```
$ docker-compose exec -T s3g ozone freon s3kg -n 1 -t 10 -b no-such-bucket
...
2023-06-25 13:30:46,493 [main] INFO freon.BaseFreonGenerator: Executing test with prefix p0l2uvfgg7 and number-of-tests 1
2023-06-25 13:30:46,507 [Thread-3] INFO freon.ProgressBar: Progress: 0.00 % (0 out of 1)
2023-06-25 13:30:46,792 [pool-2-thread-1] ERROR freon.BaseFreonGenerator: Error on executing task 0
com.amazonaws.SdkClientException: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))
at …
```

HDDS-8925. BaseFreonGenerator may not complete if last attempts fail

---

hadoop-ozone/dist/src/main/smoketest/s3/s3_getsecret.robot
hadoop-ozone/dist/src/main/smoketest/s3/s3_serviceId.robot
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/OzoneAddress.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/s3/S3Handler.java

For ozone S3 commands, instead of having --om-service-id as a mandatory option, use the serviceID from the config file as the default if there is only one. Otherwise, Make the option a compulsory one.
The usage for non-HA clusters and HA clusters with one service ID:
`ozone s3 getsecret`
And usage for HA clusters with multiple service IDs:
`ozone s3 getsecret --om-service-id=<omServiceID>`
https://issues.apache.org/jira/browse/HDDS-6814
Added a Robot test for the change.

HDDS-6814. ozone s3 getsecret default --om-service-id

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/reconfig/TestScmReconfiguration.java

Support dynamic changes ozone.readonly.administrators(SCM)
https://issues.apache.org/jira/browse/HDDS-8895
ut

HDDS-8895. Support dynamic changes ozone.readonly.administrators(SCM).

---

hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDiffManager.java

This patch contains following changes:
1. Currently `snapDiff` job fails if it can't get the delta files using `RocksDBCheckpointDiffer`. This change is to fallback to full diff if `RocksDBCheckpointDiffer#getSSTDiffListWithFullPath` fails.
2. We fall back to full diff if fromSnapshot and toSnapshot are same. Which is wrong and unnecessary. With change, it will throw an exception if form and to snapshots are same.
3. Added more info logs when SST files are removed by compaction DAG and SST file pruning jobs to debug an issue.
https://issues.apache.org/jira/browse/HDDS-8935
Added unit and integration tests.

HDDS-8935. [Snapshot] Fallback to full diff if getDetlaFiles from compaction DAG fails

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerID.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/CollectionUtils.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/TestCollectionUtils.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManagerImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/states/ContainerAttribute.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/states/ContainerStateMap.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerManagerImpl.java

1. `ContainerManagerImpl` lock is intended only for write operations (see [comment](https://github.com/apache/ozone/blob/3211547ed21b7683720ca57282e13a4edb9fdce2/hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManagerImpl.java#L68-L71) on `lock`).  `ContainerStateManagerImpl` has its own read/write lock.  Earlier `ConcurrentModificationException` (HDDS-6314) happened because `ContainerStateManagerImpl` returns an unmodifiable view of its internal sets.  These are not thread-safe, only protect against changing the set.  Replaced these with `ImmutableSet.copyOf`.
2. Replace stream with iteration.
3. Remove ineligible items from the list being sorted before sorting it.
4. Only filter items if request is not for all items (as indicated by the smallest …

HDDS-8913. ContainerManagerImpl: reduce processing while locked

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientManager.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/util/CacheMetrics.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/io/TestECBlockOutputStreamEntry.java

Enable recording of statistics for `XceiverClientManager#clientCache`, and expose them as metrics.
https://issues.apache.org/jira/browse/HDDS-8923
Checked cache metrics in Prometheus after triggering EC reconstruction by scaling datanodes down and up.
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5376304587

HDDS-8923. Expose XceiverClient cache stats as metrics

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffObject.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDiffManager.java

As part of [HDDS-8841](https://issues.apache.org/jira/browse/HDDS-8841), we added a check if block location is same for key object. Somehow isBlockLocationSame function is getting called for non-OmKeyInfo object. We should skip this check is object are not OmKeyInfo. In the case it is a directory we should check if the directory acls are the same otherwise we should return a modify entry for the directory.
https://issues.apache.org/jira/browse/HDDS-8939
Unit Tests.

HDDS-8939. [Snapshot] isBlockLocationSame check should be skipped if object is not OmKeyInfo.

---

hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/ObjectStore.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/SnapshotDiffJob.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OzoneManagerProtocol.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/snapshot/CancelSnapshotDiffResponse.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/snapshot/SnapshotDiffResponse.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHASnapshot.java
hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDiffManager.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/ClientProtocolStub.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/snapshot/SnapshotDiffHandler.java

This patch contains following changes.
1. First change is to return job failure reason to client if it is available otherwise return "unknown reason".
1. As part of [HDDS-8490](https://issues.apache.org/jira/browse/HDDS-8490) and [PR-4819](https://github.com/apache/ozone/pull/4819), support to cancel snapshot job was added. In [PR-4819](https://github.com/apache/ozone/pull/4819), snapshot diff job creation API was altered to cancel the snap diff job as well. It kinda convoluted snapshot diff code path. In this patch, separate API was created to cancel snapshot diff job to simplify the snapshot diff job creation and cancellation flow. Shell command is kept the same.
1. Reduced the snapshot diff cleanup service time interval to 1 min from 1 hour. …

HDDS-8859. [Snapshot] Return failure message to client for a failed snapshot diff jobs

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotDisabledRestart.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotManager.java

This is a follow-up to HDDS-8166.
As a safety measure, if snapshot feature flag is disabled (`ozone.filesystem.snapshot.enabled == false`), block OM from starting up if there are still snapshots in the system (i.e. `snapshotInfoTable` is not empty).
This implies any deleted but not reclaimed snapshots will also block OM start up in this case, by design.
This should prevent issues with OM HA where some OM has `ozone.filesystem.snapshot.enabled` set to `false` but some still have it set to `true`. (e.g. if leader has it set to `true` but a follower has it set to `false`, when a snapshot request comes in, the follower OM would fail the Tx because the feature is disabled)
Related thought: do we have any OM configuration consistency check when an OM joins a quorum? …

HDDS-8555. [Snapshot] When snapshot feature is disabled, block OM startup if there are still snapshots in the system

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/SCMCommonPlacementPolicy.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelinePlacementPolicy.java

Fix NPE in `validateContainerPlacement` which can happen when trying to get placement group for dead node.
Strictly speaking the fix is only this part:
```
-            .collect(Collectors.groupingBy(this::getPlacementGroup,
+        .map(this::getPlacementGroup)
+        .filter(Objects::nonNull)
+        .collect(Collectors.groupingBy(
+            Function.identity(),
```
https://issues.apache.org/jira/browse/HDDS-8950
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5400935177

HDDS-8950. NPE in SCMCommonPlacementPolicy#validateContainerPlacement

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerMetrics.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerTask.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancerTask.java

Added metrics for number of moves that were scheduled in the latest iteration and in total. Included all `MoveResult` failure cases under existing metric for failures, `numContainerMovesFailed`. Except `REPLICATION_FAIL_TIME_OUT` and `DELETION_FAIL_TIME_OUT`, which are considered time outs and counted in `numContainerMovesTimeout`.
https://issues.apache.org/jira/browse/HDDS-8840
Added assertions to an existing unit test.

HDDS-8840. Add metrics to Container Balancer

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/BackgroundPipelineCreator.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineReportHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/WritableECContainerProvider.java

Move the logging of create / open pipelines to the caller so the log message is not performed under a lock. Flame charts show logging to be a significant factor when creating EC pipelines under a synchronized block.
https://issues.apache.org/jira/browse/HDDS-8957
Logging only change to existing tests should cover.

HDDS-8957. Move info level log messages for create / open pipelines outside of locks

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/endpoint/RegisterEndpointTask.java

During the upgrade process, the datanode has an error exception message.
datanode log:
```
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: DataNode has higher Software Layout Version than SCM.
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:192)
at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.computeNextContainerState(RunningDatanodeState.java:199)
at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:239)
at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:50)
at …
```

HDDS-8948. Clarify Datanode upgrade error message (mention Recon, include endpoint address)

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/DBCheckpointServlet.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMDbCheckpointServlet.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMDbCheckpointServlet.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMDBCheckpointServlet.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotCreateResponse.java

This intermittent failure is caused by a race condition with the om double-buffer flush-thread.
the bootstrap lock here should have been preventing this problem from happening: https://github.com/apache/ozone/blob/2fbed633e87ba455e7635e75356df3ce2dd906ac/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMDBCheckpointServlet.java#L395
The reason it wasn't was because I was taking the lock after the checkpoint was created instead before, so I moved it to before and that fixed the problem.
https://issues.apache.org/jira/browse/HDDS-8681
Without this fix, I can make this failure happen consistently by inserting a thread sleep in the double buffer thread here:  https://github.com/GeorgeJahad/ozone/blob/15d451742a/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozon …

HDDS-8681. [SNAPSHOT] Intermittent failure in TestOMDbCheckpointServlet#testWriteDbDataToStream

---

hadoop-ozone/httpfsgateway/pom.xml

Get rid of:
```
httpfs_1    | SEVERE: Implementation of JAXB-API has not been found on module path or classpath.
httpfs_1    | javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
httpfs_1    |  - with linked exception:
httpfs_1    | [java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
...
httpfs_1    | 	at org.apache.hadoop.http.HttpServer2.start(HttpServer2.java:1301)
```
https://issues.apache.org/jira/browse/HDDS-8955
Ran `httpfs` acceptance tests locally, verified exception is gone.
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5411417691

HDDS-8955. Add JAXB runtime to HttpFS classpath

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerRatisRequest.java
hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerRatisServer.java

Replace `TestUnknownCommand` with a real catch-all type: `UnknownCommand = 0`.
Protobuf guide [recommends](https://protobuf.dev/programming-guides/dos-donts/#do-include-an-unspecified-value-in-an-enum):
> Enums should include a default FOO_UNSPECIFIED value as the first value in the declaration.
Rationale:
> When new values are added to a proto2 enum, old clients will see the field as unset and the getter will return the default value or the first-declared value if no default exists.
https://issues.apache.org/jira/browse/HDDS-8966
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5421634940

HDDS-8966. Replace test-specific unknown value with real one

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotUtils.java

Add error message in case snapshot info not found.
https://issues.apache.org/jira/browse/HDDS-7794
Existing Unit test

HDDS-7794. [snapshot] SnapshotDiff should throw better error messages for exception handling

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java

This patch fixes issues with three methods running under `TestOMRatisSnapshots`. This class was 30% of the time resulting in a timeout due to the configuration setup.
The issue comes from the config key `ozone.om.ratis.snapshot.auto.trigger.threshold` which is referring to the number of unappended logs before triggering a snapshot installation. All tests under this class depend on frequent Ratis snapshot installations. 
#4770 Increased the number of writes performed by `testInstallSnapshot()` which in combination with the frequent Ratis snapshot installations led 30% of runs to a system freeze that caused a timeout. To fix the issue, only `testInstallSnapshot()` runs configured with a higher threshold number.
Furthermore, `testInstallIncrementalSnapshot` and …

HDDS-8880. Intermittent fork timeout in TestOMRatisSnapshots

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OzoneManagerProtocol.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestLeaseRecovery.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemWithFSO.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystemWithFSO.java
hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/LeaseRecoverable.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/SafeMode.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/SafeModeAction.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientAdapter.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientUtils.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/Statistic.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/package-info.java
hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java
hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java
hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java
hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java

Implement new Hadoop file system APIs to support HBase.
https://issues.apache.org/jira/browse/HDDS-8436 Support setSafeMode(), isFileClosed() FileSystem API
Unit tests

HDDS-8436. Support setSafeMode(), isFileClosed() FileSystem API

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/snapshot/SnapshotDiffReportOzone.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDiffManager.java

Snapshot diff currently returns absolute path which breaks distcp on snapdiff changes. Thus should return path relative to bucket root.
https://issues.apache.org/jira/browse/HDDS-8970
Existing UT changes

HDDS-8970. Snapshot Diff should return path relative to bucket root

---

hadoop-ozone/dist/src/main/k8s/examples/testlib.sh

Use `kubectl apply -k` instead of `-f` to get rid of error:
```
error: error validating "kustomization.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
```
(with `--validate=false` some other similar error is shown...)
https://github.com/apache/ozone/actions/runs/5463225307/jobs/9944167392#step:5:126
https://issues.apache.org/jira/browse/HDDS-8979
Verified output no longer shows this error:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5465403252/jobs/9949414579#step:5:111

HDDS-8979. error validating kustomization.yaml

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsConfigKeys.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/SecurityConfig.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/RootCaRotationPoller.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/utils/TestRootCaRotationPoller.java

After the SCMs finished their part of root ca rotation the clients also need to get the new root CA certificate. This is done through a simple polling mechanism that asks the SCMs for the root CAs and once it observes a change it invokes a consumer from the clients to notify them. Integrating this change is going to be done in later items.
[HDDS-8591](https://issues.apache.org/jira/browse/HDDS-8591)
Added unit tests. Functional change is not yet observed in this patch as the polling is not actually integrated into anything yet.

HDDS-8591. Create scheduler to check for new root ca certificates

---

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/TestHddsSecureDatanodeInit.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DNCertificateClient.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DefaultCertificateClient.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/SCMCertificateClient.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/TestDefaultCertificateClient.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/OMCertificateClient.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/security/ReconCertificateClient.java

This is a redone version of an approved draft pr: https://github.com/apache/ozone/pull/5000 
The reason for the redo is to clean up the commit history and make sure that the rebase process was done cleanly.
Unfortunately I lost the original changes in that pull request due to a personal error and had to use changes saved in 
https://github.com/apache/ozone/pull/5001 
But during the process of taking commits from that pull request I realized that the conflicts and the number of commits makes it more complicated than rewriting it from scratch. Sorry for the inconvenience.
Orig description:
After the SCMs finished their part of root ca rotation the clients also need to get the new root CA certificate. This is done through a simple polling …

HDDS-8592. Fetch and save all root certificates during service's certificate rotation.

---

hadoop-ozone/dist/src/main/k8s/examples/getting-started/test.sh
hadoop-ozone/dist/src/main/k8s/examples/minikube/test.sh
hadoop-ozone/dist/src/main/k8s/examples/ozone-dev/test.sh
hadoop-ozone/dist/src/main/k8s/examples/ozone/test.sh
hadoop-ozone/dist/src/main/k8s/examples/testlib.sh

Kubernetes check currently proceeds to execute tests even if cluster is not able to start up.  It should exit without trying to run the tests.
```
**** Waiting until the k8s cluster is running ****
...
4 pods are running out from the 5
100 'all_pods_are_running' is failed...
**** Executing robot tests scm-0 ****
Defaulted container "scm" out of: scm, init (init)
Unable to use a TTY - input is not a terminal or the right kind of file
error: unable to upgrade connection: container not found ("scm")
```
This change skips the tests if cluster fails to start up.
Also:
* Fix `-1 pods are running` message (due to hard-coded subtraction intended to account for the header row of `kubectl get pod`'s output)
* Allow custom number of retry attempts (for easier testing)
* Reduce code duplication in …

HDDS-7645. Kubernetes check should fail fast if cluster cannot start

---

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/TestHddsSecureDatanodeInit.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DefaultCertificateClient.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/SCMCertificateClient.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/CertificateClientTestImpl.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/TestDefaultCertificateClient.java
hadoop-ozone/dist/src/main/compose/ozonesecure/root-ca-rotation.yaml
hadoop-ozone/dist/src/main/compose/ozonesecure/test-root-ca-rotation.sh

After all preparation has been made for the root ca rotation poller, it can be started in DefaultCertificateClient. SCMCertificateClient should be ommited from this since SCM will get Root CA rotation done separately.
Note: these are the same changes created in https://github.com/apache/ozone/pull/5001 but due to the rebasing complexity I found it easier to recreate the pull request from scratch
https://issues.apache.org/jira/browse/HDDS-8593
https://github.com/Galsza/ozone/actions/runs/5478158390
unit/integration tests, more extended docker based testing will be created in a separate jira

HDDS-8593. Add RootCARotationPoller to CertClient

---

hadoop-ozone/dist/src/main/compose/testlib.sh

Try to avoid intermittent timeout in HA secure tests by improving `wait_for_safemode_exit`:
* wait for SCM (and KDC in secure cluster) to be up, then
* use `safemode wait` instead of repeated `safemode status`
This reduces the number of SCM client connections and KDC requests, and accounts for the time until SCM is started.
https://issues.apache.org/jira/browse/HDDS-8985
Tested cluster startup locally in a few environments.
Full CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5484345000

HDDS-8985. Intermittent timeout exiting safe mode in HA secure tests

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCommitPartRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartRequest.java

Changing checkKeyAcls() to checkKeyAclsInOpenKeyTable() in S3MultipartUploadCommitPartRequest as for Acl type "WRITE", the key can only be found in OpenKeyTable.
https://issues.apache.org/jira/browse/HDDS-7750
Tested Manually

HDDS-7750. Incorrect WRITE ACL check

---

hadoop-ozone/dist/src/main/compose/ozonesecure-ha/test-root-ca-rotation.sh
hadoop-ozone/dist/src/main/compose/ozonesecure-ha/test.sh

Increase time allowed for datanode4 to become available, to prevent frequent failure due to timeout.
https://issues.apache.org/jira/browse/HDDS-8990
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5506570548

HDDS-8990. Intermittent timeout waiting on datanode4 9856 to become available

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneAclUtils.java

It is unnecessary to call `checkAcls()` twice when caller is volume owner in `OzoneAclUtils#checkAllAcls`.
Because the reason we had to split that into two calls in [HDDS-5903](https://issues.apache.org/jira/browse/HDDS-5903) is because Ranger only has one `{OWNER}` tag, and that we want `{OWNER}` tag used in bucket/key level policies to be filled in with the **bucket** owner during ACL check **when the caller is NOT the volume owner**.
In the case where the caller is the Ozone volume owner, this hierarchical check is already enforced by the authorizer (`OzoneNativeAuthorizer` or `RangerOzoneAuthorizer`) internally. Thus it is unnecessary.
Note: This has the potential side effect of having different number of audit log entries in different cases. i.e. There will be 1 audit log entry when …

HDDS-8864. Remove redundant checkAcls() when caller is volume owner during key or prefix access

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/RocksDBStoreMetrics.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBStore.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/recovery/ReconOmMetadataManagerImpl.java

HDDS-7284 added a check in (almost) all methods of `RocksDatabase` to avoid operating on closed RocksDB.  This PR adds `assertClose()` calls in methods introduced without such check since then (in HDDS-6962, HDDS-7321, HDDS-7851).
https://issues.apache.org/jira/browse/HDDS-8980
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5487024333

HDDS-8980. RocksDB crash in RocksDBStoreMetrics.computeSstFileStat

---

hadoop-ozone/dist/pom.xml

Upgrade `ozone-runner` to latest `20230615-1`, contains changes for HDDS-8628 and HDDS-8843.
https://issues.apache.org/jira/browse/HDDS-8972
```
20230615-1: Pulling from apache/ozone-runner
Digest: sha256:46c59e4f69c94a8f886d621c9f1898fda8cc4d5de59059c6c74175ffa4718474
Status: Downloaded newer image for apache/ozone-runner:20230615-1
```
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5438295046

HDDS-8972. Bump ozone-runner to 20230615-1

---

hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/RDBSnapshotProvider.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMDbCheckpointServlet.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMDBCheckpointServlet.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/OmSnapshotUtils.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotManager.java

The incremental checkpointing PR I created here: https://github.com/apache/ozone/pull/4770 allows multiple increments of data if the initial tarball took too long to download.
This is needed for om snapshots but is not completely sufficient, because the first increment can grow quite large, as it includes all sst files that exist at the time it is created.  (Each subsequent increment only includes the sst files created after the first tarball was created.)
This means there is no limit to the size of the initial tarball.  
In order to alleviate that, this PR adds the "max sst size" config flag: **OZONE_OM_RATIS_SNAPSHOT_MAX_TOTAL_SST_SIZE_KEY**.  
The tarball creation process  has been modified to close the tarball once it reaches that size of sst files.  If that leaves the tarball …

HDDS-8943. [Snapshot] Limit the total size of sst files in bootstrapping tarball.

---

hadoop-ozone/dist/src/main/compose/testlib.sh

Test results for `test-root-ca-rotation.sh` failure (see HDDS-8983) are missing, because `rebot` encountered error processing one of the files (hence no combined XML is available), but then the script deleted individual XMLs.
This PR changes the acceptance test lib to only delete separate Robot XMLs if combination (`rebot ...`) is successful.  This ensures we have some test output in both cases.
https://issues.apache.org/jira/browse/HDDS-8984
Not yet, need repro of HA-secure test failure.

HDDS-8984. Keep separate Robot XMLs if rebot fails to combine them

---

hadoop-hdds/interface-client/pom.xml
hadoop-hdds/interface-server/pom.xml
hadoop-hdds/rocks-native/pom.xml
hadoop-ozone/httpfsgateway/pom.xml
hadoop-ozone/interface-client/pom.xml
pom.xml

Hitting this error during maven build on my end with the latest master branch:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:3.1.0:run (default) on project hdds-interface-client: You are using 'tasks' which has been removed from the maven-antrun-plugin. Please use 'target' and refer to the >>Major Version Upgrade to version 3.0.0<< on the plugin site. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:3.1.0:run (default) on project hdds-interface-client: You are using 'tasks' which has been removed from the maven-antrun-plugin. Please use 'target' and refer to the >>Major Version Upgrade to version 3.0.0<< on the plugin site.
```
Then I realized `maven-antrun-plugin` …

HDDS-8993. Pin maven-antrun-plugin version to 3.1.0

---

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/scm/DecommissionScmSubcommand.java
hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/scm/TestDecommissionScmSubcommand.java

SCM Decommissioning command currently prints the error message on failure, but the exit code is 0. The decommissioning command should exit with non-zero code on failure.
[HDDS-8928](https://issues.apache.org/jira/browse/HDDS-8928)
Modified and verified the existing unit test

HDDS-8928. SCM Decommissioning command should exit with non-zero code on failure.

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DefaultCertificateClient.java

The PR proposes a change in how the RootCaRotationPoller is being instantiated, as the shared rootCaCertificates set from the DefaultCertificateClient is causing a problem.
The problem was found as part of the testing done for HDDS-8605, it is causing a problem in the case of the following events in order:
- rootCA certificates are being rotated
- OM certificate is being renewed with the new CA certs
- RootCaRotationPoller is running after the certificate renewal
The cause it the shared rootCaCertificates set, which is updated by the certificate renewal process within the DefaultCertificateClient, so that the poller once it gets to poll the new certificates, it does not recognize that there is an unkown certificate (as it already knows it via the change in the data structure during …

HDDS-8998. Shared mutable state causes rootca poller to miss updates.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/security/RootCARotationManager.java

https://issues.apache.org/jira/browse/HDDS-8983

HDDS-8983. Intermittent failure in test-root-ca-rotation.sh due to null certId

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java

When key is deleted, it firsts inserts into cache as deleted and later flush to db which deletes entry from db. In case of Bucket empty check we first check in cache and then check in table whether any entry exist for the prefix. But during this iteration there is chance that cache gets flushed into db and when we read cache it returns NULL and at this point we assume that table has entry but cache don't have. This shows that bucket is not empty at this point.
So to fix this in this case we should check in table whether really table entry is removed.
Similar problem is for Volume empty check. Making volume empty check also follow above criteria to ensure it is empty or not.
https://issues.apache.org/jira/browse/HDDS-8526
Before Fix: Test fails Intermittently in latest master for …

HDDS-8526. Intermittent failure: Directory is not empty

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsConfigKeys.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/SecurityConfig.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DefaultCertificateClient.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMSecurityProtocolServer.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-ozone/dist/src/main/compose/ozonesecure-ha/root-ca-rotation.yaml
hadoop-ozone/dist/src/main/compose/ozonesecure/root-ca-rotation.yaml

https://issues.apache.org/jira/browse/HDDS-8959 
Manual test:
1. start a docker based cluster, remote ssh to one SCM,  verify 
```
bash-4.2$ jstack 7 | grep RootCARotationManager
"RootCARotationManager-Inactive" #381 daemon prio=5 os_prio=0 cpu=0.34ms elapsed=21.62s tid=0x0000ffff9a084800 nid=0x2d2 waiting on condition  [0x0000ffff3ade4000]
```
2. stop the cluster, add following configuration
OZONE-SITE.XML_hdds.x509.ca.rotation.enabled=false
4. start a docker based cluster again, run the same command, 
```
bash-4.2$ jstack 7 | grep RootCARotationManager
bash-4.2$ 
```

HDDS-8959. Add the ability to turn off automated CA rotation

---

.github/workflows/ci.yml
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneCluster.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/debug/TestLDBCli.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestScmSafeMode.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestSnapshotDeletingService.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestContainerReportWithKeys.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestSecretKeysApi.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestStorageContainerManager.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestStorageContainerManagerHelper.java
pom.xml

Try to reduce overall integration test time by moving out some tests from the longest-running splits.
1. Create 2 new integration test splits:
* `contract` (extracted from `filesystem`): FS contract tests
* `shell` (extracted from `ozone`): CLI-related tests
2. Move some tests to more appropriate packages.
https://issues.apache.org/jira/browse/HDDS-8986
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5488447421

HDDS-8986. Rebalance integration tests

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/TenantArgs.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmTenantArgs.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneTenantShell.java
hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/tenant/OMTenantCreateRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/tenant/OMTenantCreateResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOMMultiTenantManager.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOMTenantCreateRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/OMRequestTestUtils.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/tenant/TenantCreateHandler.java

Add `--force` option to tenant create CLI that allows a tenant to be created even when the volume exists. Note this option does NOT override any other failures, e.g. Ranger failures
https://issues.apache.org/jira/browse/HDDS-8994

HDDS-8994. [Multi-Tenant] Add CLI option to allow tenant creation on top of existing volumes

---

hadoop-ozone/dist/src/main/smoketest/admincli/scmrole.robot
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/scm/GetScmRatisRolesSubcommand.java

Add the option for the command `ozone admin scm roles` to output as JSON
https://issues.apache.org/jira/browse/HDDS-6668
New robot test. Also verified the JSON out using a docker-compose cluster:
```
bash-4.2$ ozone admin scm roles --json
{
"scm2" : {
"address" : "scm2:9894",
"raftPeerRole" : "FOLLOWER",
"ID" : "3a52e9ff-77e2-488b-b1e8-539f5cf9a313",
"InetAddress" : "172.18.0.6"
},
"scm1" : {
"address" : "scm1:9894",
"raftPeerRole" : "LEADER",
"ID" : "808fae81-dcd4-4bcd-9a82-eab25b939530",
"InetAddress" : "172.18.0.10"
},
"scm3" : {
"address" : "scm3:9894",
"raftPeerRole" : "FOLLOWER",
"ID" : "07b07cf8-a1e5-4f70-b4bd-53feed2a4255",
"InetAddress" : "172.18.0.4"
}
}
```

HDDS-6668. scm roles CLI should provide JSON output option

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/container/common/helpers/ExcludeList.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/WritableECContainerProvider.java

Log more information, including the exclude list, if EC block allocation fails due to max. open pipeline limit.
https://issues.apache.org/jira/browse/HDDS-9012
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5547145701
Example output from unit test:
```
WARN  pipeline.WritableECContainerProvider (WritableECContainerProvider.java:getContainer(170)) - Unable to allocate a container after trying 5 existing ones; requested size=1, replication=EC{rs-3-2-1024k}, owner=SCM, ExcludeList {datanodes = [], containerIds = [#2381628560543191, #2381628561553557, #2381628561265675, #2381628560940851, #2381628561836869], pipelineIds = []}
java.io.IOException: Pipeline limit (5) reached (5), none closed
at org.apache.hadoop.hdds.scm.pipeline.WritableECContainerProvider.getContainer(WritableECCo …
```

HDDS-9012. Log more information about failed EC block allocation

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataReader.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshot.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

External access authorizer can be shared in same service. In case of ranger we can see we initialize multiple times in same service which eventually does refresh policies internally inside ranger plugin. Any request at this point doesn't work as policy check returns null. Which can be avoided by initialize only once during OM startup. 
https://issues.apache.org/jira/browse/HDDS-8997
Run existing tests.

HDDS-8997. Fix RangerOzoneAuthorizer initialization issue.

---

hadoop-ozone/recon/pom.xml

It is noticed that because the pnpm build during Recon compilation doesn't put the files under `./target`, they are not removed by `mvn clean` by default. This PR aims to address that.
Note this will slightly increase build time for devs who regularly uses `mvn clean install` when building Ozone, since now Recon build and node_modules dirs would first be deleted in `clean` phase. If Recon is not the component you currently work on, consider appending `-DskipRecon` to your maven build command.
https://issues.apache.org/jira/browse/HDDS-8294

HDDS-8294. mvn clean should remove frontend build artifacts stored in Recon src

---

hadoop-ozone/dist/src/main/license/jar-report.txt
pom.xml

Bump okio from 2.8.0 to 3.4.0.
https://issues.apache.org/jira/browse/HDDS-9014
https://github.com/apache/ozone/actions/runs/5545884911?pr=5059

HDDS-9014. Bump okio to 3.4.0

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/DBCheckpointServlet.java
hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMDbCheckpointServlet.java

Currently it is possible that RocksDB compaction adds the newer log entry to the compaction log while tarball creation is in progress because it is unaware of tarball creation. This lead to the situation when compaction log has new log entries after checkpoint was created for the follower. And when follower construct the DAG based on the compaction log, new entries nodes will become dangling nodes and will never be reached by snap diff or removed from the DAG unless OM is restarted or another bootstrap kicks in.
In this change, it is proposed to wait for tarball completion before appending new log entries to the compaction log. This way follower will never get new entries. Whenever OM gets tarball request, it increases the tarball request count in the `RocksDBCheckpointDiffer` and once …

HDDS-9004. [Snapshot] Pause the compaction log append if tarball creation is in progress

---

hadoop-ozone/dist/src/main/compose/upgrade/testlib.sh

Upgrade acceptance test uses v2 `docker compose` to determine SCM node, cannot be run with v1.
```
Using docker cluster defined in compose/ha/docker-compose.yaml
unknown flag: --project-directory
See 'docker --help'.
```
https://issues.apache.org/jira/browse/HDDS-9025
Ran `upgrade` acceptance test locally.
```
$ docker-compose --version
docker-compose version 1.29.2, build unknown
$ cd hadoop-ozone/dist/target/ozone-1.4.0-SNAPSHOT/compose/upgrade
$ ./test.sh
...
```
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5566833396

HDDS-9025. Upgrade acceptance test cannot be run with docker-compose v1

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/symmetric/DefaultSecretKeySignerClient.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/symmetric/SecretKeySignerClient.java

When a datanode/OM starts up while SCM has not finished initializing secret keys yet, the startup fails because Datanode/OM needs to prefetch the current active secret keys.
```
2023-07-13 16:06:22,369 [main] ERROR org.apache.hadoop.ozone.HddsDatanodeService: Exception in HddsDatanodeService.
java.lang.RuntimeException: Can't start the HDDS datanode plugin
at org.apache.hadoop.ozone.HddsDatanodeService.start(HddsDatanodeService.java:361)
at org.apache.hadoop.ozone.HddsDatanodeService.start(HddsDatanodeService.java:235)
at org.apache.hadoop.ozone.HddsDatanodeService.call(HddsDatanodeService.java:203)
at org.apache.hadoop.ozone.HddsDatanodeService.call(HddsDatanodeService.java:93)
at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
at …
```

HDDS-9020. Datanodes fails to start up when secret key has not yet been initialized in SCM.

---

hadoop-ozone/dev-support/checks/dependency.sh
hadoop-ozone/dist/src/main/license/update-jar-report.sh

Dependency check instructs developers to update `jar-report.txt` using `update-jar-report.sh`.  However, its output varies due to different `sort` implementations.  This can cause unnecessarily reordered lines, which makes it more difficult to see actual changes.  (This is similar to reordering imports unneccessarily in a PR.)
This change proposes updating the instructions: developers should edit `jar-report.txt` manually, based on the diff shown in the check's output.  License needs to be edited manually anyway, so it's only a minor change in the workflow.
Benefits:
* simpler diffs of `jar-report.txt` in PRs
* developers may build with `-DskipShade` locally and can still update `jar-report.txt`
https://issues.apache.org/jira/browse/HDDS-9024
```
$ …
```

HDDS-9024. Update instructions in dependency check

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java

`ECUnderReplicationHandler` checks if current available source datanodes + potential replica datanodes satisfy placement policy. If they don't, the targets are rejected and recovery fails. While this check makes some sense, it can block container recovery. Since under replication is more serious than mis replication, we should let a new replica be reconstructed even if it doesn't satisfy placement policy. 
Also, we should rely on the policy to suggest a node that satisfies the policy - if there is none, the policy will fallback and try to suggest a node on a rack where the container is already present. 
Changes:
Allow recovery even if placement policy is not satisfied. Also added some logs.
https://issues.apache.org/jira/browse/HDDS-9019
Modified existing UT according to the new …

HDDS-9019. ECUnderReplicationHandler rejects a potential target if it doesn't satisfy placement policy

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DefaultCertificateClient.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/RootCaRotationPoller.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/utils/TestRootCaRotationPoller.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecureOzoneCluster.java

Polling when a new root ca certificate is available doesn't pick up if the certificate sign request (or anything during certificate rotation) went wrong and never tries again even if the client didn't store its certs successfully.
[HDDS-9010](https://issues.apache.org/jira/browse/HDDS-9010)

HDDS-9010. Fix RootCaRotationPoller not toggling rotation if previous rotation failed

---

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/cert/ListSubcommand.java
hadoop-ozone/dist/src/main/smoketest/admincli/cert.robot

Add the option for the command `ozone admin cert list` to output as JSON
https://issues.apache.org/jira/browse/HDDS-8256
Added new Robot test. Also verified the JSON out using a docker-compose cluster:
```
bash-4.2$ ozone admin cert list --json | more
Certificate list:(Type=VALID, BatchSize=20, CertCount=8)
[ {
"serialNumber" : 554359750626,
"validFrom" : "Thu Jul 13 07:32:58 UTC 2023",
"expiry" : "Sun Aug 20 07:32:58 UTC 2028",
"subjectDN" : {
"CN" : "scm-sub-554314287126@scm",
"OU" : "899b84a5-3c9a-4245-a2c4-f3b74158c512",
"O" : "CID-94fd40c6-5fe3-466c-8b72-06e8f93b6e55"
},
"issuerDN" : {
"CN" : "scm-1@scm",
"OU" : "899b84a5-3c9a-4245-a2c4-f3b74158c512",
"O" : "CID-94fd40c6-5fe3-466c-8b72-06e8f93b6e55"
}
}, {
"serialNumber" : 571775840717,
--More--
```

HDDS-8256. ozone admin cert list should provide JSON output option

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/cache/CacheKey.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/cache/CacheResult.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/cache/FullTableCache.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/cache/PartialTableCache.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/cache/TableCache.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/cache/TestTableCache.java

Fix warnings in `TableCache` and related code caused by raw usage of `CacheKey` and `CacheValue`.
https://issues.apache.org/jira/browse/HDDS-9008
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5540872425

HDDS-9008. Fix unchecked warnings in TableCache

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneAtRestEncryption.java

Convert `TestOzoneAtRestEncryption` to JUnit5.
Mark streaming test cases as flaky (see HDDS-8947).
https://issues.apache.org/jira/browse/HDDS-9028
Ran `TestOzoneAtRestEncryption` locally:
```
[INFO] Tests run: 31, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 41.388 s - in org.apache.hadoop.ozone.client.rpc.TestOzoneAtRestEncryption
```
Previously:
```
[INFO] Tests run: 22, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 71.226 s - in org.apache.hadoop.ozone.client.rpc.TestOzoneAtRestEncryption
```
(Increase in number of tests is due to also testing `LEGACY` bucket layout.)
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5572230188

HDDS-9028. Migrate TestOzoneAtRestEncryption to JUnit5

---

hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/ObjectStore.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OzoneManagerProtocol.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/ClientProtocolStub.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/CompactionLogDagPrinter.java

This change addresses few of the concerns raised in PR #5061. 
* Added check to allow only Ozone admin user to call print compaction dag API.
* Update the response message stating the file name, parent dir's absolute path and the OM leader node info.
Note: This PR doesn't addressed `Having a network call that generates a file on the server is strange.` because of following reason.
As we talked in [here](https://github.com/apache/ozone/pull/5061#issuecomment-1638972143), it is better to be have it as a OM request to get the in-memory picture of the DAG. It can be solved in following two ways.
1. Return graph POJO to client and generate the image on client side. But it comes with a problem of graph size and might need pagination.
2. Stream the generated image to the client. But we don't …

HDDS-8961. [Snapshot] Added check to allow only Ozone admin user to call print compaction dag

---

hadoop-ozone/dist/src/main/compose/testlib.sh

Save docker container logs into separate files, instead of a single mixed file.
https://issues.apache.org/jira/browse/HDDS-8946
Verified content of some acceptance check bundles:
```
$ unzip -q acceptance-misc.zip
$ find * -type f -name 'docker*' | sort | xargs ls -1hs
32K ozone-csi/docker-ozone-csi_csi_1.log
116K ozone-csi/docker-ozone-csi_datanode_1.log
120K ozone-csi/docker-ozone-csi_datanode_2.log
116K ozone-csi/docker-ozone-csi_datanode_3.log
96K ozone-csi/docker-ozone-csi_om_1.log
140K ozone-csi/docker-ozone-csi_scm_1.log
116K ozone-om-prepare/docker-ozone-om-prepare_dn1_1.log
120K ozone-om-prepare/docker-ozone-om-prepare_dn2_1.log
120K ozone-om-prepare/docker-ozone-om-prepare_dn3_1.log
76K ozone-om-prepare/docker-ozone-om-prepare_om1_1.log
72K …
```

HDDS-8946. Add dedicated log file for each service in docker test

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/WritableContainerFactory.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/WritableECContainerProvider.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/reconfig/TestScmReconfiguration.java

Allow dynamic reconfiguration of `WritableECContainerProvider` config.
https://issues.apache.org/jira/browse/HDDS-9038
Updated integration test.
Tested in `ozone` compose example:
```
$ ozone freon ockg -n10 -t10 --type EC --replication rs-3-2-1024k
...
$ ozone admin container list | jq -r '.containerID' | wc -l
5
$ ozone admin reconfig --address scm:9860 start
SCM: Started reconfiguration task on node [scm:9860].
$ ozone admin reconfig --address scm:9860 status
SCM: Reconfiguring status for node [scm:9860]: started at Tue Jul 18 19:28:06 UTC 2023 and finished at Tue Jul 18 19:28:06 UTC 2023.
SUCCESS: Changed property ozone.scm.ec.pipeline.minimum
From: "5"
To: "10"
$ ozone freon ockg -n10 -t10 --type EC --replication rs-3-2-1024k
...
$ ozone admin container list | jq -r '.containerID' | …
```

HDDS-9038. Enable dynamic reconfiguration of EC container provider properties

---

hadoop-ozone/dist/src/shell/ozone/ozone

Revert [HDDS-3812](https://issues.apache.org/jira/browse/HDDS-3812).
Forcing datanode to disable the Netty leak detector is premature optimization. This prevents efforts to debug memory leaks in Ozone.
The default netty leak detection level is SIMPLE, meaning it doesn't create any stacktrace and hurt performance. Ref: https://netty.io/wiki/reference-counted-objects.html#wiki-h3-11
https://issues.apache.org/jira/browse/HDDS-9047

HDDS-9047. Ozone not to disable netty resource leak detector in datanode

---

.github/workflows/ci.yml
hadoop-ozone/dist/src/main/compose/ozonesecure-ha/test-root-ca-rotation.sh
hadoop-ozone/dist/src/main/compose/ozonesecure/test-certificate-rotation.sh
hadoop-ozone/dist/src/main/compose/ozonesecure/test-root-ca-rotation.sh

`Test execution of ozonesecure-ha/test-root-ca-rotation.sh` failed 23 times recently (on `master`, not counting PRs).  Also, `acceptance (HA-secure)` now takes ~1.5 hours.  Both problems could be less severe if we executed cert. rotation in its own split.
https://issues.apache.org/jira/browse/HDDS-9036
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5589130892

HDDS-9036. Create separate acceptance split for cert rotation

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/SendContainerRequestHandler.java

This patch is to fix NullPointerException due to null path when trying to delete tar ball during container replication if any RuntimeException occurred.  Below is the exception trace:
`Jul 20, 2023 1:24:56 PM org.apache.ratis.thirdparty.io.grpc.internal.SerializingExecutor run SEVERE: Exception while executing runnable org.apache.ratis.thirdparty.io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed@60a1ee40 java.lang.NullPointerException at java.base/java.nio.file.Files.provider(Files.java:101) at java.base/java.nio.file.Files.deleteIfExists(Files.java:1181) at org.apache.hadoop.ozone.container.replication.SendContainerRequestHandler.deleteTarball(SendContainerRequestHandler`
https://issues.apache.org/jira/browse/HDDS-9062
This patch was tested manually with …

HDDS-9059. NPE in SendContainerRequestHandler.deleteTarball

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/OzoneAddress.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/bucket/DeleteBucketHandler.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/volume/DeleteVolumeHandler.java

OM ServiceId can be fetched from address and can be used to form Ozone address for fs URI. This can avoid giving service ID explicitly in option while running recursive delete volume command. Already this has been done for delete bucket command handler. Refactored getting serviceId from common place. 
https://issues.apache.org/jira/browse/HDDS-9049
Update existing integration test and verify.

HDDS-9049. Use OM service ID from Ozone address for recursive delete

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/DefaultApprover.java

Please see the JIRA description and comments for more information on the failure being addressed here.
We do not know the reason of the failure, and could not reproduce the issue after finding it a few times.
This change adds some logging around the place where we add extensions to certificates, as this is where we have seen the NPE. I believe knowing what is in the CSR, and what we have in the supported extensions map should be sufficient to further deduct things about the failure, and I do not see more places where we can add anything useful to further debug the problem, but I am open to any ideas.
https://issues.apache.org/jira/browse/HDDS-9050
No additional testing was done.

HDDS-9050. Added exploratory logging to gather further information.

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotPurgeResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotPurgeRequestAndResponse.java

There is a copy-paste /typo error [OMSnapshotPurgeResponse](https://github.com/apache/ozone/blob/9b782054e6d4e237c02bf3ae7ce3a4d512e2eb24/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotPurgeResponse.java#L174) while cleaning up the snapshot chain.
It is supposed to be `nextGlobalSnapInfo.setGlobalPreviousSnapshotId(snapInfo.getGlobalPreviousSnapshotId());` but it is `nextGlobalSnapInfo.setGlobalPreviousSnapshotId(snapInfo.getPathPreviousSnapshotId());`.
This change is fixes the typo and adds the tests for it.
https://issues.apache.org/jira/browse/HDDS-9073
Added new test which validates the change.

HDDS-9073. Fixed the typo while cleaning up snapshot chain in OMSnapshotPurgeResponse

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsSnapshot.java

Add UTs for fs deleteSnapshot - `TestOzoneFsSnapshot#testSnapshotDeleteFailure`
https://issues.apache.org/jira/browse/HDDS-9060
Testcase file - `hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsSnapshot.java`
```
mvn -l testlog.out -Dtest=TestOzoneFsSnapshot#testSnapshotDeleteFailure test
[INFO] Running org.apache.hadoop.fs.ozone.TestOzoneFsSnapshot
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 21.999 s - in org.apache.hadoop.fs.ozone.TestOzoneFsSnapshot
[INFO]
[INFO]
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
```

HDDS-9060. [snapshot] Add unit-testcase for snapshot fs -deleteSnapshot

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerStateMachine.java

Currently in case of IOException also OzoneManager terminates and not able to recover. In this PR handling IOException in runCommand in OzoneManagerStateMachine so that ozone manager runs normally. 
Detail mentioned in below "patch tested" step when this can happen.
https://issues.apache.org/jira/browse/HDDS-9074
Verified locally using below steps:
1. Create bucket bucket1
2. Delete bucket bucket1 (Before Apply transaction) 
3. Create key key1 inside bucket1 (Pre execute) 
4. Delete bucket bucket1 (Apply transaction)
5. Key1 create(During apply transaction)
Calls `OzoneManagerRatisUtils.createClientRequest` which uses [getBucketLayout](https://github.com/apache/ozone/blob/e374aae82db1f39e666325d47fcd09a0392d0b70/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/Bu …

HDDS-9074. Ozone Manager terminated in CreateKey request due to bucket not found

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMDBCheckpointServlet.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotManager.java

Recon is unable to load data from the OM because the DB sync is failing due to path issues:
```
2023-07-20 23:44:50,686 ERROR [pool-27-thread-1]-org.apache.hadoop.ozone.recon.spi.impl.OzoneManagerServiceProviderImpl: Unable to obtain Ozone Manager DB Snapshot.
java.io.FileNotFoundException: /var/lib/hadoop-ozone/recon/om/data/om.snapshot.db_1689896689992/ints/om.db_checkpoint_1689896690655/000103.sst (No such file or directory)
at java.io.FileOutputStream.open0(Native Method)
at java.io.FileOutputStream.open(FileOutputStream.java:270)
at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
at org.apache.hadoop.ozone.recon.ReconUtils.untarCheckpointFile(ReconUtils.java:198)
``` …

HDDS-9063. OM - Recon unable to obtain Ozone Manager DB Snapshot

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/SecurityConfig.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/security/TestRootCARotationManager.java

https://issues.apache.org/jira/browse/HDDS-9068

HDDS-9068. rootCA configs should not be checked when RootCA is disabled.

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/CertificateClient.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/CommonCertificateClient.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DefaultCertificateClient.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/SCMCertificateClient.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/TestDefaultCertificateClient.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServer.java

In this patch I propose to remove parts of HDDS-7453. Earlier we have added a check and some logic to renew the certificate of a service at startup. As we progressed with the development, there is a new background service thread that checks for the certificate's expiration date periodically, and also does the check at startup. This background service sufficiently replaces the previous functionality, and as it turned out during testing, in some cases these two solutions are competing in a race which leads to multiplying certificates, or sometimes miss the renewal.
The parts that are to be removed, are all related to the REINIT InitCase in DefaultCertificateClient together with the REINIT InitCase itself. The rest is related to configuration and other elements we still use in the code, so a …

HDDS-9066. Remove the renew logic added by HDDS-7453.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/WritableECContainerProvider.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestWritableECContainerProvider.java

HDDS-8698 introduced a hard limit on EC pipeline count.  This may be too restrictive, since a few bad nodes could spoil all pipelines.
The problem can happen in the time period between datanode failure and SCM marking it as dead, closing its related pipelines.  In this case client trying to write to a failed datanode detects the failure sooner than SCM does.  It requests a new block, excluding the failed datanode.  If all existing pipelines are excluded due to such failure, client encounters block allocation failure, then gives up.
This PR proposes to turn the limit into a soft one, increasing the limit for the final attempt (after searching through all existing pipelines) to the number of datanodes.  (This only affects small clusters with few disks per node.  The problem may exist in …

HDDS-9033. Increase EC pipeline limit for final allocation attempt

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/protocol/DatanodeDetails.java

- volatile keyword is added to fields persistedOpState and persistedOpStateExpiryEpochSec as its observed that DN on HB always sends IN_SERVICE state but SetNodeOperationalStateCommandHandler changes to DECOMMISSIONING. So seems after update also, this state is not returned.
https://issues.apache.org/jira/browse/HDDS-9055
- current Integration test cover impact test
- This is random failure, will be observed if occurs again

HDDS-9055. Datanode decommission Failed, Follower never received the command

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHA.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java

As part of change #3912 and #4448, `isFile` parameter was added to `OmKeyInfo` and `OzoneKey` but it was not set when new create file gets created it doesn't exist [here](https://github.com/apache/ozone/blob/f2ef43b638e2df94af2a8e30fcef3849697195dc/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java#L689).
This change is to set `isFile` on createFile code path so that it can properly identify if key is file or dir.
https://issues.apache.org/jira/browse/HDDS-9072

HDDS-9072. Set isFile when creating OmKeyInfo for createFile code path

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java

`ECUnderReplicationHandler` is initialized before initializing `ReplicationManagerMetrics`, So whenever any ReplicationManagerMetrics is used, it throws NPE. The behavior is same for all these other classes and will throw NPEs,
`ECOverReplicationHandler, ECMisReplicationHandler, RatisUnderReplicationHandler, RatisMisReplicationHandler`
```
ECUnderReplicationHandler(final PlacementPolicy containerPlacement,
final ConfigurationSource conf, ReplicationManager replicationManager) {
this.containerPlacement = containerPlacement;
this.currentContainerSize = (long) conf
.getStorageSize(ScmConfigKeys.OZONE_SCM_CONTAINER_SIZE,
ScmConfigKeys.OZONE_SCM_CONTAINER_SIZE_DEFAULT, StorageUnit.BYTES);
this.replicationManager = replicationManager;
this.metrics = replicationManager.getMetrics(); --> still …
```

HDDS-9090. NullPointerException thrown by ReplicationManagerMetrics because of the order of initialization

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisContainerReplicaCount.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisOverReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationTestUtil.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestLegacyReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisContainerReplicaCount.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisOverReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestRatisReplicationCheckHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestRatisUnhealthyReplicationCheckHandler.java

When a Container is in CLOSED state with one of its replicas in QUASI_CLOSED state and has incorrect sequenceID, that replica should be deleted by SCM as it's inconsistent replica.
[HDDS-9075](https://issues.apache.org/jira/browse/HDDS-9075)
Added unit test to verify if SCM is re-replicating the container when there is an inconsistent quasi_closed container and then deleting the inconsistent replica when the container is in CLOSED state.

HDDS-9075. QUASI_CLOSED Replica with incorrect sequenceID should be deleted by SCM.

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/CopyContainerResponseStream.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/GrpcContainerUploader.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/GrpcOutputStream.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/GrpcReplicationService.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationServer.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisor.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/SendContainerOutputStream.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/GrpcOutputStreamTest.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestGrpcContainerUploader.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestGrpcReplicationService.java

Replication sends messages faster than the network/receiver can consume. This results in many messages being queued by Netty and the amount allocated memory surges and results in OOME. 
The change in this PR eliminates messages backlog and memory surge for both pull and push, thus allowing multiple concurrent replications.
It can be optimized to fully utilize manual control to avoid unnecessary delay (or sleep), following these [examples](https://github.com/grpc/grpc-java/tree/v1.30.2/examples/src/main/java/io/grpc/examples/manualflowcontrol). I don't have data to say if it's worth it yet.
https://issues.apache.org/jira/browse/HDDS-9081
Tested locally and verified it eliminates direct memory surges during replication.

HDDS-9081. Handling Netty back pressure when streaming containers for replication.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRackScatter.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackScatter.java

Simply put, the problem here is that EC under replication handling is blocked in cases where the Rack Scatter policy cannot return new Datanodes because they don't satisfy the policy.
Please check the jira for one such scenario, and this [document](https://docs.google.com/document/d/1ebuSwJZkw4wMWWCHinDvRCfNbeFD4kcHMyIN6Q6wD9g/edit?usp=sharing) for a detailed (but roughly documented) reproduction of some cases.
Changes proposed: Allow the rack scatter policy to fallback and return the required number of datanodes even if the policy can't be satisfied. But still try to follow the policy as well as possible. Because `fallback` is true by default, the policy will now try to return nodes if possible in situations it'd throw an `SCMException` previously. The invariant that this policy tries to …

HDDS-9011. EC: Unhealthy replica not replaced with a healthy replica in a rack-scatter environment

---

hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDiffUtils.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SstFilteringService.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestSstFilteringService.java

In [PR-5008](https://github.com/apache/ozone/pull/5008/files#diff-b9ad374a12f870c302a0cca808071a5da620f87b42595246e9e604633b228dacR221), tailing slash was appended in `filterPrefix` and `filterPrefixFSO` so that we don't delete wrong SST files.
For example, SST filtering service is running for a snapshot taken on vol1/bucket, if tailing slash is not appended, it might delete the SST files belongs to vol1/bucket1, vol1/bucket2 or anything with `bucket` prefix.
The above change caused a regression, because prefix had tailing `/` but [firstBucketKey](https://github.com/apache/ozone/blob/7a19afa71401e356cd86a99648e94278ea2850c8/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SstFilteringService.java#L94) and [lastBucketKey](https://github.com/apache/ozone/blob/7a19afa71401e …

HDDS-9093. Appended tailing slash while constructing the bucket key for SSTFilteringService

---

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/OmTableInsightTask.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestOmDBInsightEndPoint.java

After upgrading Ozone to a newer version, Recon faces compatibility issues while reading data from the `GlobalStats` table, that keeps a count of total records in every OM table and Size related metrics for certain OM tables. 
The problem lies in the transformation of data values stored in the GlobalStats table between the old and new versions. The previous data format used a suffix "**Count**" for key strings, while the current format employs the suffix "**TableCount**." As a result, Recon is unable to interpret the data properly.
A simple fix for this would be to either add a handler that gets triggered upon recon starting, or just change the prefix back to "Count".
https://issues.apache.org/jira/browse/HDDS-9101?filter=-1
Ran Existing UT's and also added new ones

HDDS-9101. Recon - Overview Page shows incorrect count of keys and buckets.

---

hadoop-ozone/dist/src/main/compose/testlib.sh

Creation of stack dump fails for `test-s3-haproxy.sh`, because `haproxy` image doesn't have `bash`.  Artifact upload then fails due to invalid character in filename.
```
2023-07-16T11:06:13.0454641Z jstack 6 > /home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.4.0-SNAPSHOT/compose/ozone/result/ozone_s3g1_1_Gateway.stack
2023-07-16T11:06:14.0932388Z jstack 7 > /home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.4.0-SNAPSHOT/compose/ozone/result/ozone_s3g2_1_Gateway.stack
2023-07-16T11:06:15.2248031Z jstack 6 > /home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.4.0-SNAPSHOT/compose/ozone/result/ozone_s3g3_1_Gateway.stack
2023-07-16T11:06:15.9927006Z jstack OCI > /home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.4.0-SNAPSHOT/compose/ozone/result …
```

HDDS-9027. Error creating stack dump in S3 HA environment

---

dev-support/ci/selective_ci_checks.bats
dev-support/ci/selective_ci_checks.sh

Skip acceptance and kubernetes checks for PRs that only change license-related files.
https://issues.apache.org/jira/browse/HDDS-9026
Added test cases in `selective_checks.bats`.
https://github.com/adoroszlai/hadoop-ozone/actions/runs/5567020982/jobs/10168620378#step:6:50

HDDS-9026. Skip acceptance/kubernetes for license changes

---

hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBCheckpointUtils.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotUtils.java

Currently snapshot dir wait poll max timeout value is a constant value. Adding a config for the same.
Snapshot listing currently throws FileNotFound exception if the directory exists check times out. This should throw a timeout error code instead of file not found.
https://issues.apache.org/jira/browse/HDDS-9112
Adding a configuration. No testing required.

HDDS-9112. Make snapshot dir wait poll max timeout configurable

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

Compaction DAG pruning service/s are not getting started after bootstrapping. It is because `RocksDBCheckpointDiffer` is singleton class. On the metadataManager.stop() path we stop the executor and on restart we just used [the cached object](https://github.com/apache/ozone/blob/7a19afa71401e356cd86a99648e94278ea2850c8/hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java#L1523) where executor is not running and don't restart Compaction DAG pruning service/s.
In this change, `invalidateCacheEntry()` is added in `RocksDBCheckpointDifferHolder` to close cached instance of `RocksDBCheckpointDiffer` and create new when `getInstance()` is called for the same metedata dir..
Note: Ideally there is no need to have …

HDDS-9118. Added an invalidateCacheEntry() in RocksDBCheckpointDifferHolder to close cached instance of RocksDBCheckpointDiffer

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsConfigKeys.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/SecurityConfig.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/security/x509/CertificateTestUtils.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/authority/CertificateStore.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/authority/MockCAStore.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/security/RootCARotationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMCertStore.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/security/TestRootCARotationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/server/TestSCMCertStore.java
hadoop-ozone/dist/src/main/compose/ozonesecure/root-ca-rotation.yaml
hadoop-ozone/dist/src/main/compose/ozonesecure/test-root-ca-rotation.sh
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecureOzoneCluster.java

Periodically remove expired certificates from scm rocksdb just as housekeeping
[HDDS-7380](https://issues.apache.org/jira/browse/HDDS-7380)
Added unit test and robot test and also observed it in a local cluster

HDDS-7380. Remove expired certificates from SCM DB

---

hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestSstFilteringService.java

As part of [HDDS-9093](https://issues.apache.org/jira/browse/HDDS-9093), simple unit test was added to validate the change. In this change, we are testing data correctness after `SstFilteringService` finishes the run. The test fails if [this change](https://github.com/apache/ozone/pull/5127/files#diff-66bf1299030e3a5f6bef620f42109ee991f9e9fbe732b3b011d607d951d51795R69) is reverted.
https://issues.apache.org/jira/browse/HDDS-9094
Ran newly added test/s locally.

HDDS-9094. [Snapshot] Added data integrity integration test for SST filtering service

---

hadoop-ozone/dist/src/main/smoketest/omha/om-roles.robot
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/GetServiceRolesSubcommand.java

Add the option for the command `ozone admin om roles` to output as JSON
https://issues.apache.org/jira/browse/HDDS-9080
Added new Robot test. Also verified the JSON out using a docker-compose cluster:
```
ozone admin om roles --service-id=omservice --json
[ {
"om1" : {
"serverRole" : "FOLLOWER",
"hostname" : "om1"
}
}, {
"om2" : {
"serverRole" : "FOLLOWER",
"hostname" : "om2"
}
}, {
"om3" : {
"serverRole" : "LEADER",
"hostname" : "om3"
}
} ]
```

HDDS-9080. om roles CLI should provide Json output option

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMOpenKeysDeleteResponse.java

OMOpenKeysDeleteResponse deletes both from openKeyTable and openFileTable depending on the bucketLayout. This patch adds openFileTable as the list of cleanupTables.
https://issues.apache.org/jira/browse/HDDS-9097
Existing CI.

HDDS-9097. Add openFileTable in CleanupTableInfo of OMOpenKeysDeleteResponse

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SstFilteringService.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/SnapshotDeletingService.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestSstFilteringService.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOmSnapshotUtils.java

SstFilteringService throws Exception while processing deleted snapshots. 
1. The fix here is to catch the exception occurred while loading a deleted snapshot, check  if it is actually deleted and mark it as filtered.
2. Also added a condition in SnapshotDeletingService to perform gc only if the snapshots are filtering complete
https://issues.apache.org/jira/browse/HDDS-9126
Unit tests

HDDS-9126. [Snapshot] SstFilteringService throws Exception while processing deleted snapshots.

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/GrpcContainerUploader.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/GrpcOutputStream.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketSetPropertyRequest.java

1. Wrapped Request Stream observer, with setting observer as error and returning isReady() true, so that it will fail while operating
2. timeout provided with 1 minute even if stream is not ready
https://issues.apache.org/jira/browse/HDDS-9134
Test with debug to verify exit of replication at DN

HDDS-9134. GRPC based replication can get stuck forever if the receiver is not available

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/OzoneOutputStream.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestLeaseRecovery.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/debug/TestLeaseRecoverer.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCommitRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestOpenKeyCleanupService.java

1. OM rejects hsync request if ozone.fs.hsync.enabled is false (which is the default value).
2. Client hsync() actually calls flush() if ozone.fs.hsync.enabled is false. This is the original behavior prior to the hsync implementation.
https://issues.apache.org/jira/browse/HDDS-9148
Unit tests in client and OM side.

HDDS-9148. OM to reject hsync if ozone.fs.hsync.enabled is false

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java

Checks if the stream container command is read only or not.
Now there is no problem, because streamInit and streamWrite happen to be non-read-only (the default).But we'd better specify the value.
https://issues.apache.org/jira/browse/HDDS-9105

HDDS-9105. [Ozone-Streaming] Checks if the stream container command is read only or not

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/KeyValueStreamDataChannel.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/StreamDataChannelBase.java

We are not currently recording the metrics of write chunks on the datanode using stream.
https://issues.apache.org/jira/browse/HDDS-9149

HDDS-9149. [Ozone-Streaming] Add Streaming Write Chunk Metrics to datanode

---

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/OMDBInsightEndpoint.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/KeyInsightInfoResponse.java
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/routes.json
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/overview/overview.tsx
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestOmDBInsightEndPoint.java

In summary, this patch introduces separate API endpoints for retrieving summarized information about open keys and deleted keys in Hadoop Ozone Recon. These summaries provide aggregated statistics and high-level information about the keys' status and data sizes.
Changes made :- 
- `OMDBInsightEndpoint.java` : This file adds two new API endpoints: `/open/summary` and `/deletePending/summary`. These endpoints retrieve summaries of open keys and deleted keys, providing aggregated information like total key count, replicated data size, and unreplicated data size.
- `KeyInsightInfoResponse.java` : This Response class no longer includes the `keysSummary` field, as the keys' summary information is now included directly in the response body of the API endpoints. …

HDDS-8964. Create a separate endpoint for summary for various SCM Insights and OM Insights.

---

hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestListKeys.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/S3GatewayConfigKeys.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/BucketEndpoint.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneBucketStub.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestBucketList.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestPermissionCheck.java

[S3G] Improve list performance in LEGACY/OBS bucket when listing delimited by '/'
https://issues.apache.org/jira/browse/HDDS-8822
- Manual test
keys info:
```bash
hadoop fs -count ofs://om/s3v/buk-lg/*
6        54712             109424 ofs://om/s3v/buk-lg/s3put
1            1                238 ofs://om/s3v/buk-lg/test1
61        30489              30489 ofs://om/s3v/buk-lg/test2
21       100000             100000 ofs://om/s3v/buk-lg/test3
hadoop fs -count ofs://om/s3v/buk-lg/test3/*
1         5000               5000 ofs://om/s3v/buk-lg/test3/dir0_47640
1         5000               5000 ofs://om/s3v/buk-lg/test3/dir10_19047
1         5000               5000 ofs://om/s3v/buk-lg/test3/dir11_99507
1         5000               5000 ofs://om/s3v/buk-lg/test3/dir12_43926
1         5000 …
```

HDDS-8822. [S3G] Improve list performance in LEGACY/OBS bucket

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientMultipartUploadWithFSO.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java

Make S3G MPU invalid part Exception Reporting More detailed, For MPU, the Part number must be an integer between 1 and 10000, refer to: https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html
Before
```bash
[root@VM-8-3-centos ~]$ aws s3api upload-part --bucket pony-bucket1 --key my-large-file --part-number 0 --body /root/1M.img --upload-id adf5534e-a2c2-430c-b07d-e659f63adbdc-110831976767881217 --endpoint-url http://localhost:9878
An error occurred (500) when calling the UploadPart operation (reached max retries: 2): Internal Server Error
[root@VM-8-3-centos ~]$ aws s3api upload-part --bucket pony-bucket1 --key my-large-file --part-number 10001 --body /root/1M.img --upload-id adf5534e-a2c2-430c-b07d-e659f63adbdc-110831976767881217 --endpoint-url http://localhost:9878
An error …
```

HDDS-9123. Make S3G MPU invalid part Exception Reporting More detailed

---

hadoop-ozone/dist/src/main/smoketest/freon/read-write-key.robot
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/Freon.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OzoneClientKeyReadWriteListOps.java

Enhance the read/write tool (ockrw) to include list operation support. Users can specify the percentage of read, write, and list tasks for generating the mixed workload. This should help in benchmarking the performance of the listKeys operation.
The below command runs 50% of read-key tasks, 40% list-key tasks and 10% of write-key tasks from pre-generated keys:
`ozone freon ockrw --percentage-read 50 --percentage-list 40 -r 100 -v voltest -b buckettest -p performanceTest`
https://issues.apache.org/jira/browse/HDDS-9128
- Added robot tests.
- Green CI/CD: https://github.com/tanvipenumudy/ozone/actions/runs/5787028346/job/15698237642
- The updated freon tool has been tested over a cluster for capturing the metric: `om_performance_metrics_list_keys_latency_ns_avg_time` (in nanoseconds) - PR: …

HDDS-9128. Ozone freon tool extension for benchmarking listKeys operation

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMPerformanceMetrics.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataReader.java

Introduce a new OM performance metric for capturing the latency of the listKeys operation. 
This metric should help in benchmarking the listKeys performance and in identifying performance bottlenecks (if any).
https://issues.apache.org/jira/browse/HDDS-9096
The patch has been tested over a cluster that has Ozone services running to see what the metric looks like. 
A sample screenshot of the Prometheus UI has been attached (for reference) capturing `om_performance_metrics_list_keys_latency_ns_avg_time` (in nanoseconds):

HDDS-9096. Add OM performance metrics for listKeys operation

---

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/EndpointBase.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/exception/S3ErrorTable.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestEndpointBase.java

Replacing the IllegalArgumentException thrown with a new OS3Exception for MetadataTooLarge.
https://issues.apache.org/jira/browse/HDDS-8011
Manually tested in Docker set-up using an API development tool to send a request to s3g.
cURL form of the request used to test: https://gist.github.com/Tejaskriya/7a8740cb2152ba7704030835ae8b85f1
Output seen:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>MetadataTooLarge</Code>
<Message>Your metadata headers exceed the maximum allowed metadata size.</Message>
<Resource>x-amz-meta-b</Resource>
<RequestId>2f65ae49-bf28-4947-9504-dddca6fc0452</RequestId>
</Error>
```
Also tested using a test case in TestEndpointBase.java.

HDDS-8011. IllegalArgumentException logged for invalid user-defined metadata

---

hadoop-hdds/rocks-native/pom.xml

Currently zlip url points to https://zlib.net/zlib-*.tar.gz which is not stable because older version get migrated to https://zlib.net/fossils/zlib-*.tar.gz. https://zlib.net/fossils/zlib-*.tar.gz is more stable URL to download zlib.
This change is to update the URL to https://zlib.net/fossils/zlib-*.tar.gz.
https://issues.apache.org/jira/browse/HDDS-9193
Built it on local machine and verified docker comes up properly.

HDDS-9193. Updated the zlib download URL to stable URL

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OzoneFSUtils.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsSnapshot.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotCreateRequest.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java
hadoop-ozone/ozonefs-common/src/test/java/org/apache/hadoop/fs/ozone/TestBasicOzoneFileSystems.java

- Correctly print snapshot path when subdirectories are specified during snapshot creation with `fs -createSnapshot`.
cc @hemantk-12 
https://issues.apache.org/jira/browse/HDDS-9157
- Added new test case in `TestOzoneFsSnapshot`.

HDDS-9157. [Snapshot] Print correct snapshot path in `fs -createSnapshot`

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManagerImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerImpl.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java

In testing we have found an issues in the ECWritableContainerProvider.
For EC a pipeline is used for only one container, when the container gets closed, the pipeline also gets closed. At the moment, the only place in the code which closes the EC piplines which no longer have an open container is inside the ECWritableContainerProvider. It first gets the list of open piplines and enforces the pipeline limit, then for all open pipelines, it tries top find one the client can use.
If the client has had problems writing to the pipelines (eg it was given a container/pipeline and then the write failed as the container was closed on the DN), the pipelines get added to the exclude list. Then we can get into a situation where many pipelines need to be closed on the write path, slowing down block …

HDDS-9151. Close EC Pipeline when container transitions to closing

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/SnapshotInfo.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SnapshotChainManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotPurgeRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotPurgeResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotPurgeRequestAndResponse.java

Issue is that at final stage of snapshot purge we update the [snapshot chain and next global & path level snapshots in DB](https://github.com/apache/ozone/blob/master/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotPurgeResponse.java#L112). When we update next global and path level snapshots in DB, it doesn’t not [update the cache](https://github.com/apache/ozone/blob/master/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotPurgeResponse.java#L144). SnapshotInfo [read happens from the cache](https://github.com/apache/ozone/blob/master/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotPurgeResponse.java#L149). When causes that test failures mentioned …

HDDS-8665. Implemented CopyObject for SnapshotInfo and moved out snapshot chain update form OMSnapshotPurgeResponse

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/AbstractContainerReportHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestIncrementalContainerReportHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/MockPipelineManager.java

Currently when a datanode's replica moves from open to unhealthy, it will send an ICR to SCM. This is processed on the next run of the SCM replication manager, which could be up to 5 minutes by default. In the mean time, SCM will continue to send writes to this open container, which will fail at the datanode. 
The unhealthy replica could be handled quicker if the container is closed when the unhealthy ICR is processed in [AbstractContainerReportHandler#updateState](https://github.com/apache/ozone/blob/0fcfe212e18efc620260f733b14db43e63e2ea08/hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/AbstractContainerReportHandler.java#L262)
https://issues.apache.org/jira/browse/HDDS-8902
New unit test added.

HDDS-8902. Close open container immediately on ICR of unhealthy replica

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerHealthResult.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECContainerReplicaCount.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/ClosedWithUnhealthyReplicasHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/ECReplicationCheckHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/RatisUnhealthyReplicationCheckHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECContainerReplicaCount.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestClosedWithUnhealthyReplicasHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestECReplicationCheckHandler.java

An EC container should only be marked as unhealthy if:
1) Is not missing (has at least dataNum replica indexs online)
2) Has at least dataNum Healthy indexes online.
For a 3-2 container, this means that:
Healthy, Healthy -> This is missing
Unhealthy, Unhealthy -> This is missing as it doesn't matter that the replicas are unhealthy, as we could not read it anyway as we need at least 3 replicas.
Healthy, Healthy, Unhealthy (indexes 1, 2, 3) -> This is unhealthy as technically much of the data can still be read, but it is the unhealthy container which is causing the problem and making it unrecoverable.
Healthy, Healthy, Healthy, Unhealthy -> This is under replicated, as we can recover using the 3 healthy.
https://issues.apache.org/jira/browse/HDDS-9197
Some tests modified and new tests …

HDDS-9197. EC: Mark EC containers unhealthy when not missing but unrecoverable

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java

Assertion that times out (compaction backup files pruning) during workflow run is commented out. This is only a temporary solution, because compaction backup files pruning is just a part of larger set of snapshot background services tests which are important. Jira [HDDS-9209](https://issues.apache.org/jira/browse/HDDS-9209) is created to fix this.
https://issues.apache.org/jira/browse/HDDS-9206

HDDS-9206. testSnapshotBackgroundServices is failing most of the time in workflow run

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java

I accidentally merged this findbugs error into master:
M D DLS: Dead store to numberOfSstFiles in org.apache.hadoop.ozone.om.TestOMRatisSnapshots.testSnapshotBackgroundServices() At TestOMRatisSnapshots.java:[line 1245]
https://issues.apache.org/jira/browse/HDDS-9213
findbugs

HDDS-9213. Findbugs error in TestOMRatisSnapshots.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/MisReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/ClosedWithUnhealthyReplicasHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/ECMisReplicationCheckHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/ECReplicationCheckHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestECMisReplicationCheckHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestECReplicationCheckHandler.java

UNHEALTHY replicas are considered when checking for mis replication in `ECReplicationCheckHandler`, but not when checking for under/over replication.
When this mis replicated container is picked from queue, mis replication handling isn't correct because that assumes the container is not over/under replicated.
The solution here is to take care of the excess UNHEALTHY replica before checking for mis replication. This PR splits the mis replication check from `ECReplicationCheckHandler` into its own handler. This new handler, called `ECMisReplicationCheckHandler`, is added to the command chain after the unhealthy handler. This means any excess UNHEALTHY replicas will be removed (or at least scheduled for delete) first. Then mis replication will be checked in this new handler in the next …

HDDS-9177. A mis replicated EC container with UNHEALTHY replicas may not get resolved

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelinePlacementPolicy.java

Under normal circumstances, a log like this is seen frequently in the SCM log:
```
2023-08-23 10:41:06,087 [main] WARN  pipeline.PipelinePlacementPolicy (PipelinePlacementPolicy.java:filterViableNodes(166)) - Pipeline creation failed due to no sufficient healthy datanodes. Required 3. Found 2. Excluded 14.
```
This happens regularly, as the background pipeline creator thread attempts to fill all datanodes with pipelines. When all the limits have been reached the above scenario legitimately happens and prints the warning to the logs.
We should move this message to debug along with a few others similar to it, as they are not warnings, but normal occurrences.
https://issues.apache.org/jira/browse/HDDS-9204
Logging only change. Ran the TestPipelineManagerImpl tests before and after and …

HDDS-9204. Reduce log level of PipelinePlacementPolicy failed to create pipeline message

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/DatanodeCommandCountUpdatedHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java

Whenever a `DATANODE_COMMAND_COUNT_UPDATED` event is processed in the SCM, these log messages are printed in DEBUG mode:
```
LOG.debug("DatanodeCommandCountUpdatedHandler called with datanode {}",
datanodeDetails);
```
and 
```
LOG.debug("Received a notification that the DN command count " +
"has been updated for {}", datanode);
```
In a busy cluster this can happen quite frequently. This PR moves them to TRACE level.
https://issues.apache.org/jira/browse/HDDS-9179

HDDS-9179. Datanode Command Count Updated related DEBUG logging is too frequent

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java

There could be possible issue of getting wrong key listStatus if a key is created, deleted and flushed to DB, but then again before cache gets  flushed, same key is created, current cache map get overwritten with DB.
https://issues.apache.org/jira/browse/HDDS-9195
This patch is tested by running existing test cases in multiple counts of Job runs.

HDDS-9195. TestOzoneFileSystem - Handle inconsistency in Create, Delete operations of same key before cache flush.

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAUtils.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/RatisUtil.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/parser/TestOzoneHARatisLogParser.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

Currently, we don't support om service id change but if someone changes om service id then we throw a warning message which results in the creation of a new raft group directory with respect to the new om service id and finally leads to iIllegalStateException. This PR aims to prevent the om service id change by throwing an exception, with this PR we also prevent the existence of SCM and OM ratis storage directory at the same path.
https://issues.apache.org/jira/browse/HDDS-7553

HDDS-7553. Ozone OM stopped with iIllegalStateException.

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DefaultCertificateClient.java

https://issues.apache.org/jira/browse/HDDS-9217

HDDS-9217. Refine certificate renewer service to avoid it scheduled ahead of time

---

hadoop-hdds/docs/content/feature/Decommission.md
hadoop-hdds/docs/content/feature/OM-HA.md

This PR provides the documentation for decommissioning of OM, SCM and Datanode.
https://issues.apache.org/jira/browse/HDDS-9037

HDDS-9037. Provide documentation for Decommissioning in Ozone

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/IncrementalContainerReportHandler.java

Not leader log was changed in [HDDS-6241](https://issues.apache.org/jira/browse/HDDS-6241) when there is exception during ICR. But in [HDDS-8934](https://issues.apache.org/jira/browse/HDDS-8934) not leader exception is wrapped inside SCMException. Now it is not getting caught in `NotLeaderException`. In this PR updating the log for SCM_NOT_LEADER exception.
https://issues.apache.org/jira/browse/HDDS-9216
Just logging changed, no test impact.

HDDS-9216. Update log in exception while processing ICR for container.

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockReconstructedStripeInputStream.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinator.java

We have seen some issues where ec recontruction fails to complete due to what looks like bad data in the blocks in some of the replicas. When this happens, it is very difficult to debug the problem as the logs only container an error.
To help with future debugging of these problems this change will log out details of the block group, the replica details and chunks and chunk lengths. Having this information along with the error should allow us to find the root cause of the failures we have seen.
https://issues.apache.org/jira/browse/HDDS-9211
Logging only change. Existing tests should cover this.

HDDS-9211. Log EC Replica details if a block cannot be read during reconstruction

---

hadoop-hdds/docs/content/feature/ErasureCoding.md
hadoop-ozone/dist/src/shell/ozone/ozone
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/checknative/CheckNative.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/checknative/package-info.java
hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/checknative/TestCheckNative.java

Added CLI command for checking if native libraries (libhadoop and isa-l) are accessible
https://issues.apache.org/jira/browse/HDDS-9230
added a unit test for a case where native libs are not provided. Other cases are tricky to mock so I did manual testing:
Native libs not provided:
```
$ ozone checknative
Native library checking:
hadoop:  false
ISA-L:   false
```
Only hadooplib is provided:
```
$ ozone checknative
Native library checking:
hadoop:  true /root/lib/libhadoop.so
ISA-L:   false Loading ISA-L failed: Failed to load libisal.so.2 (libisal.so.2: cannot open shared object file: No such file or directory)
```
Hadooplib and isa-l are provided:
```
$ ozone checknative
Native library checking:
hadoop:  true /root/lib/libhadoop.so
ISA-L:   true /lib64/libisal.so.2
```

HDDS-9230. Add CLI command for checking native libs

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMDBCheckpointServlet.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotManager.java

The tarball creation code was incorrectly assuming that two sst files with the same name, (but different directories,) were hard linked to each other.
See the jira ticket for an example of when this isn't correct: https://issues.apache.org/jira/browse/HDDS-9207
To remedy this, the tarball creation process must check the INodes of each file to confirm they are equal before linking them together.  That is the purpose of this PR.
The exclude list is a list of sst files the follower generates and sends to the leader when requesting a tarball.  It includes all the sst files already received by the follower so that the leader doesn't need to resend them.
The leader also uses this list to decide what hard links to create.  Prior to adding the inode check described above, the filename was all …

HDDS-9207. [Snapshot] Snapshot Bootstrap creates incorrect hard links.

---

hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestSnapshotBackgroundServices.java

- Introduced suspend/resume mechanism and necessary checks for it for backup compaction files pruning. By default pruning is not suspended.
- Fixed and re-enabled test check for backup compaction files pruning.
- Snapshot background services were moved to its own class.
https://issues.apache.org/jira/browse/HDDS-9209
Integration tests

HDDS-9209. Re-enable check for backup compaction files pruning

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/SCMCommonPlacementPolicy.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRackAware.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRackScatter.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelinePlacementPolicy.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/TestSCMCommonPlacementPolicy.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackScatter.java

The situation is well documented under the heading 'Situation 4' in https://docs.google.com/document/d/1ebuSwJZkw4wMWWCHinDvRCfNbeFD4kcHMyIN6Q6wD9g/edit?usp=sharing. This happens because of limitations in rack scatter policy + replication manager flow. 
An example (summary) of this situation:
Suppose there are 5 racks and 6 DNs, such that any one rack will have 2 DNs. 5 replicas of an EC container are scattered across each of the 5 racks (so that there's only 1 replica on each rack). Now, if any of the Datanodes from any rack where there's only 1 DN on that rack is decommissioned, under replication handling will be blocked.
In this PR, if a rack has only excluded nodes, we reduce the cluster rack count by 1 for each rack in this case. So if we have a 5 rack clusters, and have replicas …

HDDS-9125. Decommissioning blocked because of under replicated EC containers

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestSCMSafeModeWithPipelineRules.java

The changes that fix the test :
1. Setting `OZONE_DATANODE_PIPELINE_LIMIT` to 1 , earlier set to 50 . With Multi-Raft enabled by default, each DN was participating in multiple pipelines which caused failures in some assertions that asserted pipeline count. This test was written prior to multi raft. 
2.  Outdated waiting logic : When pipeline scrubber creates pipelines , SCM persists its info in its RocksDB. After a cluster/SCM restart, SCM loads back the persisted pipelines in its memory . pipelineManager.getPipelines() returns this info. 
This is independent of how many dataNodes are up or down as it is purely loading it from SCM DB. Removed such redundant checks.
https://issues.apache.org/jira/browse/HDDS-3420
Unit test fix
Ran the test for 100 iterations : …

HDDS-3420. Enable TestSCMSafeModeWithPipelineRules test cases

---

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/AccessHeatMapEndpoint.java

This PR is to avoid calling heatmap API if client explicitly calls HeatMap UI page or API through postman.
https://issues.apache.org/jira/browse/HDDS-9212
This patch was tested using PostMan calling heatmap after disabling heatmap feature flag `ozone.recon.heatmap.enable`

HDDS-9212. HeatMap UI doesn't load On Disabling & Enable Recon HeatMap using Feature Flag.

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3InitiateMultipartUploadRequest.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/util/OMMultipartUploadUtils.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmMetadataManager.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/OMRequestTestUtils.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestOpenKeyCleanupService.java

Currently OpenKeyCleanupService deletes all the open keys in the openKeyTable regardless whether the open keys are MPU-related or not. This might cause orphan MPU in MultipartInfoTable, since to abort the MultipartInfo, we need to check openKeyTable for MPU-related open keys, which will fail if the open keys are already deleted. 
We need to exclude the incomplete MPU open keys in getExpiredOpenKeys so they are not deleted. We can use `isMultipartKey` flag set in the incomplete MPU open key info and exclude them from being deleted. However, prior to HDDS-9017, `isMultipartKey` flag is always set to false, so we need to handle this case. Here are the cases considered:
1. For MPU open keys with `isMultipartKey` flag set to true
- We can skip it straight, without further checks
2. For MPU …

HDDS-9098. Exclude the cleanup of incomplete MPU open keys in getExpiredOpenKeys

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManagerUtil.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisUnderReplicationHandler.java

This PR changes the flow so that if RM cannot find a spare node to replicate to, it will check look for quasi_closed or unhealthy replicas.
Provided there are at least 3 replicas available AND there are no pending deletes on the container AND there is at least one CLOSED replica it will:
1. Try to delete a single quasi_closed replica. If there is more than 1, it will delete the one with the lowest seqID.
2. If there are no quasi-closed, it will delete an unhealthy one
3. If there are no unhealthy or quasi-closed, it will do nothing (same functionality as before).
The container will then be requeued to be processed again later when the delete has hopefully completed OK.
https://issues.apache.org/jira/browse/HDDS-8536
New unit tests added to test the new flow and all scenarios.

HDDS-8536. ReplicationManager: Unhealthy replicas could block Ratis containers being replicated

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestDirectoryDeletingServiceWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/AbstractKeyDeletingService.java

KeyDeletingService currently processes deleted keys in FSO buckets that are present (held by) in snapshots which should not happen.
The fix here is to use getFileName() for FSO key instead of getKeyName(). For detailed explanation see [this](https://issues.apache.org/jira/browse/HDDS-8453?focusedCommentId=17763222&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17763222)
https://issues.apache.org/jira/browse/HDDS-8453
Unit test
Ran the test for 100 iterations here : https://github.com/sadanand48/hadoop-ozone/actions/runs/6144131795

HDDS-8453. [Snapshot] KeyDeleting service should not reclaim snapshot keys.

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/SimpleStriped.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/utils/SimpleStripedTest.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/utils/TestSimpleStriped.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/lock/OzoneManagerLock.java

[HDDS-8765](https://issues.apache.org/jira/browse/HDDS-8765) uses Guava's [Striped](https://guava.dev/releases/19.0/api/docs/com/google/common/util/concurrent/Striped.html) to implement striped locks in OM. For now, Striped doesn't allow creating striped locks with a custom fairness order. Details are in #4885.
There's a [open issue](https://github.com/google/guava/issues/2514) and a [PR](https://github.com/google/guava/pull/2515) in Guava to address that, but looks like they're not reviewed by Guava devs for a long time.
This PR implements a factory of `com.google.common.util.concurrent.Striped` which uses reflection to create Striped locks with fair order policy.
https://issues.apache.org/jira/browse/HDDS-9237
Unit-tested.

HDDS-9237. Enable lock order fairness for striped locks.

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/TrashPolicyOzone.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java

moveToTrash is not checking for return value of rename API. When rename fails due to various reasons, still moveToTrash assume it as success. This leads to inconsistent behaviour, one which is mentioned in Jira description(HDDS-9136).
In this PR, If there is failure in rename operation, we are throwing exception to know moveToTrash has failed. 
https://issues.apache.org/jira/browse/HDDS-9136

HDDS-9136. Throw exception when rename fails during moveToTrash.

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

As of now if certificate durations are invalid for example, if "hdds.x509.max.duration" is set with a negative value then OM goes into a retry mode as OM tries to communicate with SCM which is already down so in this case after 600 seconds(by default) OM shuts down. In this jira, we will try to check the validity of the certificate duration in the init process and shut down the OM immediately if the durations are invalid.
https://issues.apache.org/jira/browse/HDDS-9234

HDDS-9234. OM should shutdown immediately if certificate durations are invalid

---

hadoop-hdds/docs/content/feature/Snapshot.md

Update list of snapshot apis to include lsDiff details
```
Usage: ozone sh snapshot listDiff [-ahV] [-s=<jobStatus>] <value>
List snapshotDiff jobs for a bucket.
```
https://issues.apache.org/jira/browse/HDDS-9268
NA

HDDS-9268. [snapshot] Update list of snapshot apis to include lsDiff details

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationServer.java

Add queue limit in ReplicationServer
https://issues.apache.org/jira/browse/HDDS-9208

HDDS-9208. Add queue limit in ReplicationServer.

---

.github/workflows/ci.yml
dev-support/ci/acceptance_suites.sh

When adding a new acceptance test split, we need to make two changes:
* set `suite` in some test script(s)
* add the new `suite` in `ci.yml`
To simplify this and avoid possible typos, this PR makes `ci.yml` execute a script to find all existing suites.
https://issues.apache.org/jira/browse/HDDS-9270
```
$ dev-support/ci/acceptance_suites.sh                   
suites=["cert-rotation","compat","EC","HA-secure","HA-unsecure","misc","MR","secure","unsecure"]
```
CI (same suites as on `master`):
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6161699404

HDDS-9270. Create a script to list all acceptance test splits

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/BlockDeletingService.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeConfiguration.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingTask.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java

Reduce the granularity of Container locks for BlockDeletingService, Reduces the amount of time the BlockDeletingService holds a `Container` lock to reduce affect to others threads who need acquire the `Container`  lock
https://issues.apache.org/jira/browse/HDDS-9107
existing test

HDDS-9107. Reduce the granularity of Container locks for BlockDeletingService

---

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/utils/columnSearch.tsx

There are values present in the column, but the search does not filter them out. so Now search Functionality is working on Array and Objects
https://issues.apache.org/jira/browse/HDDS-9161
Manually
[pieplines.webm](https://github.com/apache/ozone/assets/112169209/6c9923a3-83fe-4f23-b65d-8717e05290fc)
From UID Search

HDDS-9161. Recon Pipelines datanode columns search does not work

---

hadoop-ozone/dist/src/main/compose/common/ec-test.sh
hadoop-ozone/dist/src/main/compose/ozonesecure/docker-config
hadoop-ozone/dist/src/main/compose/ozonesecure/test-ec.sh
hadoop-ozone/dist/src/main/smoketest/ec/lib.resource

EC acceptance tests are executed only in unsecure environment.  They should be also run in secure environment (to catch bugs like HDDS-9196).
https://issues.apache.org/jira/browse/HDDS-9264
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6157599390/job/16711249803#step:5:995

HDDS-9264. Execute EC acceptance test in secure environment

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestLegacyReplicationManager.java

In [HDDS-9257](https://issues.apache.org/jira/browse/HDDS-9257) we added logic to remove an excess unhealthy replica if a spare node could not be found to fix under replication. The delete command sent to the datanode needs to have force=true to allow it to delete a non-empty containers.
This change is to send the delete command with force = true.
https://issues.apache.org/jira/browse/HDDS-9275
Modified a unit test to ensure the force flag is true.

HDDS-9275. LegacyReplicationManager: Delete excess unhealthy with force=true

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/client/HddsClientUtils.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestHddsClientUtils.java

Ozone was unintentionally supporting Unicode non-ascii alphabetic characters (like Æ, ｚ, etc.) for volume and bucket names as Character.lowercase method is unicode aware. The check is now done using regex to avoid this behaviour.
https://issues.apache.org/jira/browse/HDDS-8920
Added a unit test in TestHddsClientUtils. Also tested manually in docker set-up:
```
bash-4.2$ LC_ALL="en_US.UTF-8" ozone sh volume create "ãñð"
INVALID_VOLUME_NAME Bucket or Volume name has an unsupported character : ã
bash-4.2$ LC_ALL="POSIX" ozone sh volume create Áaa
INVALID_VOLUME_NAME Bucket or Volume name has an unsupported character : ?
```

HDDS-8920. Ozone is supporting unicode volume and bucket names, unintentionally

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedDDSWithFSO.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystemWithFSO.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/rooted/ITestRootedOzoneContractRootDir.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java

Recursive volume list/delete doesn't work for OBS buckets using fs command which leads to abnormal behaviour. To handle this we are now already supporting both OBS and FSO bucket for list/delete using new sh command. Document for the change attached in [HDDS-6610](https://issues.apache.org/jira/browse/HDDS-6610).
In this Jira we are removing support for fs list/delete command.
https://issues.apache.org/jira/browse/HDDS-9262
Updated existing test.

HDDS-9262. Remove support for recursive volume list/delete using ozone fs command.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestAddRemoveOzoneManager.java

Removed the `@Flaky` annotation from TestAddRemoveOzoneManager because the failures can not be reproduced by repeated execution of the tests in CI.
[HDDS-6077](https://issues.apache.org/jira/browse/HDDS-6077)
By repeated execution of the tests in CI to check if failures can  be reproduced but all the tests has passed.
Link for one of the test jobs result:  https://github.com/HD372000/ozone/actions/runs/6164026361/job/16728851792#step:4:8309

HDDS-6077. Remove flaky tag from TestAddRemoveOzoneManager

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerStateManagerIntegration.java

Removed the `@Flaky` annotation from TestContainerStateManagerIntegration.testGetMatchingContainerMultipleThreads because the failure can not be reproduced by repeated execution of the tests in CI.
[HDDS-1159](https://issues.apache.org/jira/browse/HDDS-1159)
By repeated execution of the tests in CI to check if failure can be reproduced but all the tests has passed.
Link for one of the test jobs result:  https://github.com/HD372000/ozone/actions/runs/6165606906/job/16733664079#step:4:3794

HDDS-1159. Remove flaky tag from TestContainerStateManagerIntegration

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDiffManager.java

Currently snapdiff checks only key versions to check if a key has been modified. We have to check if other fields have also changed like (Acl changes, replication config changes etc.)
https://issues.apache.org/jira/browse/HDDS-9236
Integration tests

HDDS-9236. Fix snapdiff output for key modification

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java

Added unit-testcase for Snapshot Quota handling - `TestOmSnapshot#testSnapshotQuotaHandling
`
https://issues.apache.org/jira/browse/HDDS-9269
Testcase file - `hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java`
```
mvn -l testlog.out -Dtest=TestOmSnapshot#testSnapshotQuotaHandling test
[INFO] Running org.apache.hadoop.ozone.om.TestOmSnapshot
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 493.689 s - in org.apache.hadoop.ozone.om.TestOmSnapshot
[INFO]
[INFO]
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
[INFO]
```

HDDS-9269. [snapshot] Add unit-testcase for Snapshot Quota handling

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java

Add more negative unit-testcases coverage for volume/bucket quota - `TestOzoneShellHA#testShQuota`
https://issues.apache.org/jira/browse/HDDS-9277
Testcase file - `hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java`
```
mvn -l testlog.out -Dtest=TestOzoneShellHA#testShQuota test
[INFO] Running org.apache.hadoop.ozone.shell.TestOzoneShellHA
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 769.384 s - in org.apache.hadoop.ozone.shell.TestOzoneShellHA
[INFO]
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

HDDS-9277. [Quota] Add more negative unit-testcases coverage for volume/bucket quota

---

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/heatMap/heatMapConfiguration.tsx
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/heatMap/heatmap.tsx

Few HeatMap issues:
1) Not able to enter "/s3v/cloudera-health-monitoring-ozone-basic-canary-bucket/cloudera-health-monitoring-ozone-basic-canary-key" in path box.
2) Tooltip always show FileName label irrespective of entity type selected. It should display label as Key Name, if selected bucket entity type, tool tip should have label Bucket Name and if volume, the should be Volume Name.
**Yes it will need backend Changes also as not able to differentiate between Volume,Bucket, Directories, Sub Directories and keys byseeing name only. Currently did changes as Entity Name so it will be consistent across all levels**.
https://issues.apache.org/jira/browse/HDDS-9224
Manually
Regular Expression for - working

HDDS-9224. Recon HeatMap UI issues

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecureOzoneCluster.java

* Upgrade `TestSecureOzoneCluster` to JUnit5.
* Mark `testDelegationTokenRenewCrossCertificateRenew` as flaky.
https://issues.apache.org/jira/browse/HDDS-9286
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6186500594/job/16794302198#step:5:3790
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6186500594/job/16794304438#step:6:3780

HDDS-9286. Migrate TestSecureOzoneCluster to JUnit5

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAWithData.java

`TestOzoneManagerHAWithData` passed in 200/200 runs, I think we can remove the flaky annotation.
https://issues.apache.org/jira/browse/HDDS-6074
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6197108608
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6197659648

HDDS-6074. Remove flaky tag from TestOzoneManagerHAWithData

---

hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/ReconTestInjector.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestNSSummaryTask.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestNSSummaryTaskWithFSO.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestNSSummaryTaskWithLegacy.java

`TestNSSummaryTask` and related tests are implemented as nested classes.  If we run the nested test class directly (either explictly, or via some selector, e.g. package name), these nested classes run into exceptions, because JUnit does not execute the `@BeforeClass` setup code in the outer class.
This change converts these tests to JUnit5, which handles nested class setup properly.
https://issues.apache.org/jira/browse/HDDS-9252
```
$ mvn -am -pl :ozone-recon -Dtest='TestNSSummaryTaskWithLegacy$TestProcess' clean test
...
[INFO] Running org.apache.hadoop.ozone.recon.tasks.TestNSSummaryTaskWithLegacy
[INFO] Running …
```

HDDS-9252. NPE in TestNSSummaryTask

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestOpenKeyCleanupService.java

After further thinking, in MPU abort request handling, we only clean up the "open MPU key" and not the "open MPU part key". However since we set isMultipartKey in the "open MPU part key" (https://github.com/apache/ozone/pull/5072) and open key clean up service will exclude them (https://github.com/apache/ozone/pull/5214), both Open Key cleanup service and MPU abort will not clean the "open MPU part key", this might cause these open keys to be in the openKeyTable forever.
Let's treat the "open MPU part key" as normal open key by not setting the isMultipartKey flag to true so that it can be cleaned by Open Key cleanup service.
To summarize:
- Open MPU key: Cleaned during MPU abort request (and MPU cleanup service to be implemented in https://issues.apache.org/jira/browse/HDDS-9194)
- Open …

HDDS-9285. Revert set isMultipartKey for Open MPU part keys

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java

Avoid creating Managed objects per getKeyInfo request to avoid the finalizer cost. 
https://issues.apache.org/jira/browse/HDDS-9294
Standard CI.

HDDS-9294. Avoid creating Managed objects per getKeyInfo request.

---

hadoop-ozone/dist/src/main/smoketest/freon/read-write-key.robot
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/KeyGeneratorUtil.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OzoneClientKeyReadWriteListOps.java

ozone freon ockrw is a useful command to generate a fixed name key range and generate workload against a working set of keys. Currently the keys are generated only randomly. It would be useful to have a mode where the keys are generated .
https://issues.apache.org/jira/browse/HDDS-8693
robot test added.

HDDS-8693. Generate linear keys for freon ockrw

---

hadoop-hdds/interface-client/src/main/proto/hdds.proto
hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/compaction/log/CompactionFileInfo.java
hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/compaction/log/CompactionLogEntry.java
hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/compaction/log/package-info.java
hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java
hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/compaction/log/TestCompactionFileInfo.java
hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/compaction/log/TestCompactionLogEntry.java
hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/codec/OMDBDefinition.java

In this change, a new columnFamily: `compactionLogTable` is added to keep the compaction log entries. Currently simple text file is used to keep compaction entries which has following problems:
* There is no proper way to serialize and deserialize the compaction entry. It is based on different token ` `,  `,` and `:`. Which makes it backward incompatible whenever a new parameter gets added to logs. e.g. 1). when dbSequence number was added to the log in [HDDS-8652](https://issues.apache.org/jira/browse/HDDS-8652), 2). when it is needed to add SST file details to fix [HDDS-8940](https://issues.apache.org/jira/browse/HDDS-8940). After migrating to column family, Protobuf's serialization will be used to store it in RocksDB column family. It will be easier to add new parameter with protobuf. …

HDDS-7601. Added new columnFamily: compactionLogTable to store compaction entries

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainer.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java

The reported issue had a datanode with 2 disks:
```
/dev/nvme2n1    985G  935G     0 100% /ozone-data
/dev/nvme4n1    985G  453G  482G  49% /ozone-data1
```
One disk is full, but the create container call still failed with this stack:
```
2020-02-13 10:58:01,097 ERROR org.apache.hadoop.ozone.container.keyvalue.helpers.KeyValueContainerUtil: Unable to create directory for metadata storage. Path: /ozone-data/hdds/cf793a84-8529-4897-8bf9-f18ec79e8ad6/current/containerDir1/536/metadata
2020-02-13 10:58:01,097 INFO org.apache.hadoop.ozone.container.keyvalue.KeyValueHandler: Operation: CreateContainer , Trace ID:  , Message: Container creation failed. Unable to create directory for metadata storage. Path: /ozone-data/hdds/cf793a84-8529-4897-8bf9-f18ec79e8ad6/current/containerDir1/536/metadata , …
```

HDDS-3009. Create Container should retry other volumes if writes fail

---

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestReplicationSupervisor.java

https://issues.apache.org/jira/browse/HDDS-9240

HDDS-9240. Test container schema V2 and V3 replica mutual import

---

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OzoneClientKeyReadWriteListOps.java

This command requires specifying the percentage of reads and list operations. This makes the CLI invocation long when one wants to create a few keys. This issue is to track making the reads and list to default to 0 and the command to run a pure create workload unless specified to do reads and or list keys.
https://issues.apache.org/jira/browse/HDDS-9306
Existing robot tests

HDDS-9306. Default reads/lists to 0 (freon ockrw)

---

hadoop-ozone/dist/src/main/smoketest/s3/bucketcreate.robot
hadoop-ozone/dist/src/main/smoketest/upgrade/generate.robot
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/EndpointBase.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/exception/S3ErrorTable.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestBucketPut.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/metrics/TestS3GatewayMetrics.java

AWS s3 returns with an exit code of 255 if a create-bucket on an existing bucket is done but ozone was returning the location of the bucket each time instead. In order to match the behaviours, S3G now throws a new error BUCKET_ALREADY_EXISTS if we try to create-bucket on an existing bucket.
https://issues.apache.org/jira/browse/HDDS-9314
Added test in TestBucketPut. Also tested manually using docker:
```
$ aws s3api --endpoint http://localhost:9878 create-bucket --bucket bucket1
{
"Location": "http://localhost:9878/bucket1"
}
$ aws s3api --endpoint http://localhost:9878 create-bucket --bucket bucket1 
An error occurred (BucketAlreadyExists) when calling the CreateBucket operation: The requested bucket name is not available as it already exists.
```

HDDS-9314. create-bucket on an existing bucket should fail

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/CodecBuffer.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/utils/db/CodecTestUtil.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/utils/db/TestLeakDetector.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/TestRDBSnapshotProvider.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestCodec.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStore.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStoreCodecBufferIterator.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestTypedRDBTableStore.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java

CodecBuffer overrides the finalize() method for leak detection. It turns out causing a much longer GC time. (Thanks
@duongkame for finding it out.)
This JIRA is to change CodecBuffer not to override finalize(). In the test, we will create a subclass to override CodecBuffer for leak detection.
HDDS-9295
Added a new test.

HDDS-9295. Avoid overriding finalize() in CodecBuffer.

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/OzoneQuota.java
hadoop-ozone/dist/src/main/smoketest/basic/ozone-shell-lib.robot
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java

Return proper error message thrown when text/decimal is supplied as a parameter for namespace-quota
Issue observed -
```
For input string: "test"
For input string: "test"
For input string: "test"
For input string: "test" 
For input string: "1.5" 
```
Solution provided -
```
bash-4.2$ ozone sh volume create vol1 --namespace-quota test
test is invalid. The quota value should be a positive integer between 1 and Long.MAX_VALUE
bash-4.2$ ozone sh volume create vol1 --space-quota test
test is invalid. The quota value should be a positive integer between 1 and Long.MAX_VALUEwith byte numeration(B, KB, MB, GB and TB)
bash-4.2$ ozone sh volume create vol1 --space-quota 1.5GB
1.5GB is invalid. The quota value should be a positive integer between 1 and Long.MAX_VALUEwith byte numeration(B, KB, MB, …
```

HDDS-9278. Return proper error message thrown when text/decimal is supplied as a parameter for namespace-quota

---

hadoop-ozone/dist/src/main/smoketest/omha/om-roles.robot
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/GetServiceRolesSubcommand.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/OMAdmin.java

Currently, for ozone admin om roles command, we need to specify the om service ID as its a mandatory parameter.
```
bash-4.2$ ozone admin om roles
Missing required option: '--service-id=<omServiceId>'
Usage: ozone admin om roles [-hV] [--json] -id=<omServiceId>
List all OMs and their respective Ratis server roles
-id, --service-id=<omServiceId>
OM Service ID
--json      Format output as JSON
-V, --version   Print version information and exit.
```
Even if the omServiceId is null, its handled properly [here](https://github.com/apache/ozone/blob/4b43f158b8b5f9e0d1a58ffe81d3411729337c66/hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/OMAdmin.java#L113) 
[HDDS-9305](https://issues.apache.org/jira/browse/HDDS-9305)
Modified …

HDDS-9305. Make OM service ID optional for `ozone admin om roles` if only one is defined in config

---

hadoop-ozone/dist/src/main/compose/common/ec-test.sh
hadoop-ozone/dist/src/main/compose/ozone-ha/test.sh
hadoop-ozone/dist/src/main/compose/ozone/disabled-test-s3-haproxy.sh
hadoop-ozone/dist/src/main/compose/ozonesecure-ha/s3g-virtual-host.yaml
hadoop-ozone/dist/src/main/compose/ozonesecure-ha/test-s3g-virtual-host.sh
hadoop-ozone/dist/src/main/compose/ozonesecure-ha/test.sh
hadoop-ozone/dist/src/main/compose/ozonesecure/test-vault.sh
hadoop-ozone/dist/src/main/smoketest/s3/awss3virtualhost.robot
hadoop-ozone/dist/src/main/smoketest/s3/commonawslib.robot
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/AuthorizationFilter.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/ClientIpFilter.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/HeaderPreprocessor.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/OzoneClientProducer.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/VirtualHostStyleFilter.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/EndpointBase.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/signature/AWSSignatureProcessor.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/signature/SignatureInfo.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/signature/StringToSignProducer.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/util/S3Consts.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/TestAuthorizationFilter.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/TestOzoneClientProducer.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/TestVirtualHostStyleFilter.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/signature/TestAuthorizationV4QueryParser.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/signature/TestStringToSignProducer.java

When using Virtual-Host Style addressing using AWS CLI the client uses `/` as the canonical URI when generating the S3 request. At the server side, `VirtualHostStyleFilter.java` extracts bucket name from the host value and appends it to the URI. This causes the signature validation to fail because the canonical URI used to generating string to sign is `/bucketname`. But, this is also necessary to resource match the request to the correct endpoint.
Proposed change introduces an 
- `AuthorizationFilter.java` and moves the string to sign generation function from `OzoneClientProducer.java` to `AuthorizationFilter.java`.  The filter runs before the `VirtualHostStyleFilter.java` where the URI is changed.
- Repurposes `SignatureInfo` object to store String to Sign information.
- Fixed a bug in …

HDDS-7035. Generate strToSign before applying virtual host style filter.

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeChoosingPolicyFactory.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ContainerImporter.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestCapacityVolumeChoosingPolicy.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueHandler.java

Current default is round robin which won't take into account the space on the volume while creating/replicating containers which can cause allocate block failures (although they would be retried) or lead to small containers.  It is better to make  CapacityVolumeChoosingPolicy as default.
https://issues.apache.org/jira/browse/HDDS-9273
Unit test

HDDS-9273. Set CapacityVolumeChoosingPolicy as default VolumeChoosingPolicy.

---

hadoop-ozone/dist/src/main/compose/ozonesecure-ha/test.sh
hadoop-ozone/dist/src/main/smoketest/omha/om-fetch-key.robot
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/FetchKeySubCommand.java

Currently, for ozone admin om fetch-key command, we need to specify the om service ID as its a mandatory parameter.
```
ozone admin om fetch-key
Missing required option: '--service-id=<omServiceId>'
Usage: ozone admin om fetch-key [-hV] -id=<omServiceId>
CLI command to force OM to fetch the latest secret key from SCM.
-id, --service-id=<omServiceId>
Ozone Manager Service ID
-V, --version   Print version information and exit. 
```
Even if the omServiceId is null, its handled properly [here](https://github.com/apache/ozone/blob/4b43f158b8b5f9e0d1a58ffe81d3411729337c66/hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/OMAdmin.java#L113)
[HDDS-9313](https://issues.apache.org/jira/browse/HDDS-9313)
Manually tested + Added Robot …

HDDS-9313. Make OM service ID optional for `ozone admin om fetch-key` if only one is defined in config

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/endpoint/HeartbeatEndpointTask.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeHeartbeatDispatcher.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestStorageContainerManager.java

Change endpoint state to GetVersion in case of Re-Register to prevent cases where older version with older cluster ID of datanode registers back.
To add more context : 
Datanode has an EndpointStateMachine which undergoes various states in sequence - {GETVERSION,REGISTER,HEARTBEAT,SHUTDOWN}
When DN is started it first gets version from SCM and creates its storage dirs (adds version files etc) and then registers with SCM. Now that it is registered, it will keep sending HeartBeats and EndpointState = HEARTBEAT. If during this time, SCM is re-initialised i.e all prev storage dirs are deleted and SCM is inited with new cluster ID then DN still keeps sending Heartbeats and re-registers . In this case if version is not checked an old DN can register to  a new SCM and cause issues which is why …

HDDS-6634. Incorrect datanode state drop after lose connection to SCM server

---

hadoop-ozone/dist/src/main/compose/testlib.sh

In rare occasions there is a race condition between closing a docker container and that container leaving the network. When the container is still connected to the network but the network is being shut down it will cause an error that makes the acceptance tests fail.
This pr adds a retry mechanism for docker-compose down as well as ignoring the possible error coming from it, since it's irrelevant to the result of the test itself.
[HDDS-7531](https://issues.apache.org/jira/browse/HDDS-7531)
The error is hard to reproduce directly. I observed that the CI still runs. Locally I've also changed the docker-comose.yaml while running an acceptance test thus creating an orphan container that can't be removed. When the test shut down it was retried and the test was still successful in result.
Green …

HDDS-7531. Intermittent error while removing docker network

---

hadoop-ozone/dist/src/main/compose/ozone-ha/test.sh
hadoop-ozone/dist/src/main/compose/ozonesecure-ha/test.sh
hadoop-ozone/dist/src/main/smoketest/omha/om-roles.robot

The om-roles.robot test added in [HDDS-9305](https://issues.apache.org/jira/browse/HDDS-9305) is not executed in any of the acceptance test. Aim is to add it in ozone-ha and ozonesecure-ha environments.
[HDDS-9341](https://issues.apache.org/jira/browse/HDDS-9341)
Acceptance test CI, passing in local fork.
ha-secure: https://github.com/LZD-PratyushBhatt/ozone/actions/runs/6277586606/job/17050342303
```
Om-Roles :: Smoke test for listing om roles.                                  
List om roles with OM service ID passed                               | PASS |
List om roles without OM service ID passed                            | PASS | …
```

HDDS-9341. om-roles.robot is not part of any test runs

---

hadoop-hdds/docs/content/security/SecurityWithRanger.md
hadoop-hdds/docs/content/security/SecurityWithRanger.zh.md

The doc should ask admins to configure `RangerOzoneAuthorizer` classpath using `OZONE_MANAGER_CLASSPATH` instead of `OZONE_CLASSPATH` so as to narrow down the effective scope of it to OMs only.
https://issues.apache.org/jira/browse/HDDS-9300
- CDP is already using `OZONE_MANAGER_CLASSPATH`.

HDDS-9300. Instruct admins to use `OZONE_MANAGER_CLASSPATH` for `RangerOzoneAuthorizer`

---

hadoop-ozone/dist/src/main/compose/testlib.sh

Acceptance test scripts run locally with `KEEP_RUNNING=true` exit with an error at the end:
```
$ KEEP_RUNNING=true ./test.sh
...
Failed to remove all docker containers in  attempts.
$ echo $?
1
```
https://issues.apache.org/jira/browse/HDDS-7531
Ran (a shortened version of) `ozone/test.sh`:
```
$ cd hadoop-ozone/dist/target/ozone-1.4.0-SNAPSHOT/compose/ozone
$ KEEP_RUNNING=true ./test.sh
$ echo $?
0
```
Verified no error message is printed, and the script exits with success (0).

HDDS-7531. (addendum) Intermittent error while removing docker network

---

hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestSCMSafeModeManager.java

The test already got fixed in HDDS-4133 with having a try-catch around createPipeline call. This test stops the background pipeline creator which is followed in another tests in this class. This way there won't be a race b/ w manual and bg process.
https://issues.apache.org/jira/browse/HDDS-4113
Test passed 100X10= 1000 times prior to this change itself  : https://github.com/sadanand48/hadoop-ozone/actions/runs/6296446016

HDDS-4113. Intermittent failure in TestSCMSafeModeManager#testPipelinesNotCreatedUntilPreCheckPasses.

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/AbstractKeyDeletingService.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/DirectoryDeletingService.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/SnapshotDeletingService.java

`SnapshotDeletingService` should use `omSnaphot`'s `KeyManager` and not activeDb's `KeyManager`.
https://issues.apache.org/jira/browse/HDDS-9333
Existing Tests.

HDDS-9333. Snapshot should use snapshot's keyManager in optimizeDirDeletesAndSubmitRequest

---

.github/workflows/ci.yml
dev-support/ci/categorize_basic_checks.sh
dev-support/ci/selective_ci_checks.sh

If neither unit, nor native check is required, PR check is successful, but email notification says "PR run failed", which is confusing.  [PR run](https://github.com/apache/ozone/actions/runs/6249526071) is annotated with:
```
Error when evaluating 'strategy' for job 'unit'. apache/ozone/.github/workflows/ci.yml@d74a8a98c243d5b0a9a82f5b3c21525cfea89933 (Line: 231, Col: 16): Matrix vector 'check' does not contain any values
```
https://issues.apache.org/jira/browse/HDDS-9332
Tested the case when no unit check is required:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6251667755
Full CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6251652835

HDDS-9332. Handle empty unit check

---

.github/workflows/ci.yml
hadoop-ozone/dev-support/checks/_summary.sh

Ozone's CI check scripts (`integration.sh`, etc.) have 2 main conventions:
* exit with non-zero code if there are failed tests
* list failures in `summary.txt` or similar
Most CI jobs have a _Summary of failures_ step, which provides a quick overview by showing the contents of `summary.txt`.
Github automatically expands the failed step, which according to these conventions is the main _Execute tests_ step.  The problem is that this can have very long output.
It would be better to exit with failure in the _Summary of failures_ step, thus focusing the developer's attention on the quick overview, keeping the long output collapsed by default.
https://issues.apache.org/jira/browse/HDDS-9301
Triggered failure in some checks.
checkstye: …

HDDS-9301. Fail checks in Summary step instead of Test

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestLegacyReplicationManager.java

LRM needs to save UNHEALTHY replicas that have unique Origin IDs when deleting excess UNHEALTHY replicas of a QUASI_CLOSED container. This is because replicas with unique origins are used to decide whether such a container can be closed. If we can close UNHEALTHY replicas in the future, these replicas can be used to make this decision.
Currently, LRM considers all replicas in the algorithm for finding out which replicas need to be saved and which should be deleted:
```
// Gather the origin node IDs of replicas which are not candidates for
// deletion.
Set<UUID> existingOriginNodeIDs = allReplicas.stream()
.filter(r -> !deleteCandidates.contains(r))
.map(ContainerReplica::getOriginDatanodeId)
.collect(Collectors.toSet());
```
We need to remove any DNs that are not in-service and healthy …

HDDS-9352. LegacyReplicationManager: Ignore any Datanodes that are not in-service and healthy when finding unique origins

---

hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/upgrade/QuotaRepairUpgradeAction.java

The default value in `QuotaRepairUpgradeAction` class is not the same in `ozone-site.xml`, which is confusing. 
In fact, `QuotaRepairTask` will be very time consuming during upgrading om, the time taken is as follows:
```java
// test 1
2023-07-05 16:15:36,432 [pool-37-thread-1] INFO org.apache.hadoop.ozone.om.service.QuotaRepairTask: Recalculate Key usages completed, count 259337075 time 1873737ms
// test 2
2023-08-13 17:35:45,622 [pool-37-thread-2] INFO org.apache.hadoop.ozone.om.service.QuotaRepairTask: Recalculate File usages completed, count 19752234 time 440393ms
```
I prefer that `ozone.om.upgrade.quota.recalculate.enabled` default to false.
https://issues.apache.org/jira/browse/HDDS-9166

HDDS-9166. Fix OZONE_OM_UPGRADE_QUOTA_RECALCULATE_ENABLE default value

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/CloseContainerCommand.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestLegacyReplicationManager.java

Legacy Replication Manager currently doesn't handle a CLOSING container when all its replicas are UNHEALTHY. RM needs to make decisions for such a container so it can move to one of the terminal states and be eligible for replication. This PR moves such a container to the QUASI_CLOSED state. This jira will fix the LegacyReplicationManager only.
https://issues.apache.org/jira/browse/HDDS-9327

HDDS-9327. LegacyReplicationManager: Handle all UNHEALTHY replicas of a CLOSING container

---

hadoop-ozone/dist/src/main/compose/ozonesecure/vault.yaml
hadoop-ozone/dist/src/shell/ozone/ozone-functions.sh
hadoop-ozone/dist/src/shell/shellprofile.d/hadoop-ozone-manager.sh

HDDS-2310 added support for OM-specific extra classpath. Currently it accepts only a single item (which can be a wildcard, though). However, it does not allow adding two or more specific jars given in a classpath-like string (e.g. `x.jar:y.jar:z.jar`).
This PR adds support for adding 2+ extra jars to OM classpath.
https://issues.apache.org/jira/browse/HDDS-9344
Change is verified by `test-vault.sh` in `ozonesecure` acceptance test, where two jars are added to OM classpath.
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6285129998/job/17067585858

HDDS-9344. Allow multiple classpath items in OZONE_MANAGER_CLASSPATH

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/pipeline/Pipeline.java
hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/container/InfoSubcommand.java

In case of all datanodes being down, various methods in Pipeline.java were throwing an IOException. This was causing `ozone admin container info <id> --json` to fail. The fix proposed is to create another class in InfoSubcommand.java to store all pipeline information not dependent on the existence of datanodes in case there are no datanodes up..
https://issues.apache.org/jira/browse/HDDS-9239
Manually tested using docker
```
sh-4.2$ ozone admin container info 4
Container id: 4
Pipeline id: ac51ee38-c755-4f66-a2c2-16806f7a5974
Container State: CLOSING
Datanodes: []
Replicas: []
sh-4.2$ ozone admin container info 4 --json
{
"containerInfo" : {
"state" : "CLOSING",
"stateEnterTime" : "2023-09-27T04:44:27.592Z", …
```

HDDS-9239. Ozone cli command to get container info should deal with empty values for --json

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisContainerReplicaCount.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestLegacyReplicationManager.java

QUASI_CLOSED containers may have some UNHEALTHY replicas that have the highest sequence ID while all healthy replicas have a smaller sequence ID. In such cases, RM should try to keep one copy of such UNHEALTHY replicas.
Changes:
1. RatisContainerReplicaCount: A new API to get UNHEALTHY replicas that need to be replicated to other DNs. These replicas will be on decommissioning or maintenance nodes.
2. LegacyReplicationManager: Uses the above API to get UNHEALTHY replicas and sends replicate commands for them.
Additionally, this PR already contains the changes from #5365. We should get that one merged first.
https://issues.apache.org/jira/browse/HDDS-9321
Green CI in my fork: https://github.com/siddhantsangwan/ozone/actions/runs/6317121316/job/17153215650.

HDDS-9321. LegacyReplicationManager: Save UNHEALTHY replicas with highest BCSID for a QUASI_CLOSED container

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/ClosingContainerHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestClosingContainerHandler.java

Replication Manager currently doesn't handle a CLOSING container when all its replicas are UNHEALTHY. RM needs to make decisions for such a container so it can move to one of the terminal states and be eligible for replication. This PR moves such a container to the QUASI_CLOSED state.
This is the equivalent of #5348 for the new replication manager.
https://issues.apache.org/jira/browse/HDDS-9340
New unit test added

HDDS-9340. ReplicationManager: Handle all UNHEALTHY replicas of a CLOSING Ratis container

---

.github/workflows/ci.yml

HDDS-6618 extracted a new `unit` check from `basic`.  Artifacts for this new check are missing, because `upload` step was not copied.  This PR adds it.
https://issues.apache.org/jira/browse/HDDS-9364
Regular CI:
```
Artifact has been finalized. All files have been successfully uploaded!
```
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6342725953/job/17229534601#step:7:20

HDDS-9364. Upload artifacts of unit/native check

---

.github/workflows/intermittent-test-check.yml

HDDS-9357 introduced a new workflow to easily run some intermittent test in multiple iterations.  Currently it has the default `fail-fast: true` behavior for the matrix check, but `FAIL_FAST=false` for iterations within a split.  This PR adds a new parameter to the workflow to ensure these two are consistent.  This will allow running all splits to completion, which helps estimate the rate of failure.
https://issues.apache.org/jira/browse/HDDS-9359
fail-fast=true:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6336826095
fail-fast=false:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6336793682

HDDS-9359. Parameter for fail-fast behavior in flaky-test-check

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestLeaseRecovery.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemWithFSO.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystemWithFSO.java

1. Add a missing `close` call for a `FileSystem` instance
2. Close output stream in `testLeaseRecoverable()`, ignoring `KEY_NOT_FOUND` (see HDDS-9358).  Also in two other test classes that had the same pattern (although I haven't yet seen `ManagedChannel` warning from those).
https://issues.apache.org/jira/browse/HDDS-9351
`TestRootedOzoneFileSystemWithFSO` had no `not shutdown properly` warnings in 10x10 runs:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6335324968
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6335857380

HDDS-9351. ManagedChannel not shutdown properly in TestRootedOzoneFileSystemWithFSO

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/metrics/SCMNodeMetric.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/container/placement/TestDatanodeMetrics.java

`SCMContainerPlacementCapacity#chooseNode` select less used space node through the following code:
```java
datanodeDetails = ! firstNodeMetric.isGreater(secondNodeMetric.get()) ? firstNodeDetails : secondNodeDetails; 
```
More used node should be return in `SCMNodeMetric#isGreater`, rather than more remaining  node.
https://issues.apache.org/jira/browse/HDDS-9315
TestDatanodeMetrics passed

HDDS-9315. Fix comparison logic for SCMContainerPlacementCapacity.

---

.github/workflows/ci.yml
hadoop-ozone/dist/src/main/compose/compatibility/docker-config
hadoop-ozone/dist/src/main/compose/ozone-csi/docker-config
hadoop-ozone/dist/src/main/compose/ozone-ha/docker-config
hadoop-ozone/dist/src/main/compose/ozone-om-ha/docker-config
hadoop-ozone/dist/src/main/compose/ozone-om-prepare/docker-config
hadoop-ozone/dist/src/main/compose/ozone-topology/docker-config
hadoop-ozone/dist/src/main/compose/ozone/docker-config
hadoop-ozone/dist/src/main/compose/ozoneblockade/docker-config
hadoop-ozone/dist/src/main/compose/ozonescripts/docker-config
hadoop-ozone/dist/src/main/compose/ozonesecure-ha/docker-config
hadoop-ozone/dist/src/main/compose/ozonesecure-mr/docker-config
hadoop-ozone/dist/src/main/compose/ozonesecure/docker-config
hadoop-ozone/dist/src/main/compose/restart/docker-config
hadoop-ozone/dist/src/main/compose/upgrade/compose/ha/docker-config
hadoop-ozone/dist/src/main/compose/upgrade/compose/non-ha/docker-config
hadoop-ozone/dist/src/main/compose/upgrade/compose/om-ha/docker-config
hadoop-ozone/dist/src/main/compose/xcompat/docker-config

Acceptance test started failing recently due to `DISK_OUT_OF_SPACE` error from datanodes.  It turns out 5GB is still left, so container (1GB) could have been created, but datanode wanted to preserve free space.  This change reduces the minimum free remaining space which is required when creating containers to 100MB from default 5GB.
Also, remove Ozone binary tarball (~350MB) after extraction to really free up some space.
https://issues.apache.org/jira/browse/HDDS-9362
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6344084423

HDDS-9362. Intermittent failure in acceptance test due to `DISK_OUT_OF_SPACE`

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmMetrics.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMetrics.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotDeleteRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDiffManager.java

In this change, 
1. Metric `numSnapshotReclaimed` metric counter is removed because *Reclaimed* is not a used snapshot status and will be removed completely as part of [HDDS-9214](https://issues.apache.org/jira/browse/HDDS-9214). 
2. Added missing getter for some metrics.
3. Added snapshotDiffJob count and failure metrics.
4. Updated existing tests to validate metrics are getting populated properly. 
https://issues.apache.org/jira/browse/HDDS-8641

HDDS-8641. Removed numSnapshotReclaimed metric and added missing getter for snapshot metrics.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMDbCheckpointServlet.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMDBCheckpointServlet.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/OmSnapshotUtils.java

When OM bootstrap process generates last snapshot checkpoint it creates tmp file that contains hard links data and adds it to the tarball. Currently, created tmp file is not deleted after it is used. Idea of the this PR is to delete that tmp file when it is no longer needed.
https://issues.apache.org/jira/browse/HDDS-9337
Modified existing OM integration test to check whether tmp file is deleted.

HDDS-9337. Tmp files are not deleted after OM bootstrapping

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/BucketManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManagerUtils.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ResolvedBucket.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestBucketManagerImpl.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/PrefixParser.java

Before these changes single and multipart uploads via S3G to an EC bucket resulted in keys created with RATIS/3 replication. 
Now linked buckets inherit the original bucket's replication type
https://issues.apache.org/jira/browse/HDDS-9117
Unit tests, manual tests

HDDS-9117. Source bucket replication type is ignored for links

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/TrashOzoneFileSystem.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/TrashPolicyOzone.java

1. Modify the check in the test  after the key moves to trash to to assert that the key is either in the Current or the checkpoint directory as the checkpoint could immediately happen in some cases.
2. Make Trash FS Ozone Listing Iterator use omMetadataManager#listKeys instead of iterating the Raw key table directly as it won't account for keys in Cache. This solves cases where if Cache is not flushed after rename to trash  or delete from trash.
3. One of the main fixes for this is to fix createFakeDirIfShould to avoid race condition b/w cache flush and opening an older KeyTable Iterator reference solved by #5252 
https://issues.apache.org/jira/browse/HDDS-6645
Unit test
Ran the test successfully for 15x10 = 150 times here : https://github.com/sadanand48/hadoop-ozone/actions/runs/630496696 …

HDDS-6645. Intermittent timeout in TestOzoneFileSystem#testTrash.

---

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/cli/OzoneAdmin.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneFsShell.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/OzoneShell.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/s3/S3Shell.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/tenant/TenantShell.java

Using the entire shell command as root span instead of main
https://issues.apache.org/jira/browse/HDDS-7978 
docker-compose env with jaegar tracing enabled.

HDDS-7978. Using shell command name as root span name instead of main

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java
hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/rocksdiff/TestRocksDBCheckpointDiffer.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestSnapshotBackgroundServices.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java

In Jira: [HDDS-7601](https://issues.apache.org/jira/browse/HDDS-7601) and [PR#5303](https://github.com/apache/ozone/pull/5303/), a new column family: `compactionLogTable` was added to RocksDB to store compaction information but it was not used.
This change is to actually use `compactionLogTable` column family to store compaction information in RocksDB. And make sure code is backward and forward compatibility.
1. `RocksDB` and `ColumnFamliy` are directly used to access the `compactionLogTable` instead of using [Table](https://github.com/apache/ozone/blob/master/hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/Table.java)/[RDBTable](https://github.com/apache/ozone/blob/master/hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBTable.java). Reason being, …

HDDS-9311. Use compationLogTable to store compaction information

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/BooleanCodec.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/Codec.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/CodecBuffer.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/DelegatedCodec.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/IntegerCodec.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/LongCodec.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/Proto2Codec.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/Proto3Codec.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/ShortCodec.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/StringCodecBase.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/UuidCodec.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/utils/db/CodecTestUtil.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/ByteStringCodec.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestCodec.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestCodecRegistry.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManagerStub.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/metadata/SCMDBDefinition.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/metadata/X509CertificateCodec.java

In `ByteStringCodec`, we may wrap the ByteString instead of copying it in the `toCodecBuffer(..)` method.
HDDS-9370
Added new tests.

HDDS-9370. Avoid copying ByteString in ByteStringCodec.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHASnapshot.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SnapshotChainManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotCreateRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestSnapshotChain.java

Currently, OM restart fails and leaves the OM in unstable (which can't be stabilized without manual effort) if there is any kind of failure in snapshot chain reconstruction. Previous issues ([HDDS-7689](https://issues.apache.org/jira/browse/HDDS-7689), [HDDS-8530](https://issues.apache.org/jira/browse/HDDS-8530), [HDDS-8832](https://issues.apache.org/jira/browse/HDDS-8832) and [HDDS-9073](https://issues.apache.org/jira/browse/HDDS-9073)) where OM restart failed and left it in unstable state.
In this change, it is proposed to keep the snapshot chain state and let the OM start without any snapshot/chain related issues. Snapshot chain corrupted state is used to block all the snapshot's write operations like create, delete and purge snapshot if snapshot chain is corrupted.
A new parameter, …

HDDS-9199. Snapshot chain corruption should not fail OM restart

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/StorageVolume.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeInfo.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeUsage.java

Reduce the number of system calls when DN writes a key
To execute `HddsDispatcher.sendCloseContainerActionIfNeeded` once, need to call `getCapacity()` 3 times and `getAvailable()` 2 times.
The `getCapacity()` and `getAvailable()` are System call, we need reduce the System calls.
In this PR, reduces the number of `getCapacity()` and `getAvailable()` calls to once each.
After this PR
https://issues.apache.org/jira/browse/HDDS-9380
Existing Test

HDDS-9380. Reduce the number of system calls when DN writes a key

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMiniOzoneCluster.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStreamWithFailures.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineFailureOnRead.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestFailureHandlingByClient.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCloseContainerByPipeline.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestRandomKeyGenerator.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAMetadataOnly.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestRecursiveAclWithFSO.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestSCMContainerPlacementPolicyMetrics.java

Remove the `@Flaky` annotations from the test cases that have been successfully fixed and are no longer experiencing flakiness.
https://issues.apache.org/jira/browse/HDDS-9381
I ran the Test class 300 times for each test class and ensured that there were no intermittent failures.
Class Name | CI Runs
-- | -- 
TestSCMContainerPlacementPolicyMetrics HDDS-2961 | https://github.com/ArafatKhan2198/ozone/actions/runs/6398416895 https://github.com/ArafatKhan2198/ozone/actions/runs/6398418026 https://github.com/ArafatKhan2198/ozone/actions/runs/6398419702
TestOzoneManagerHAMetadataOnly HDDS-6644 |  https://github.com/ArafatKhan2198/ozone/actions/runs/6235727447 https://github.com/ArafatKhan2198/ozone/actions/runs/6235729232 
TestOzoneManagerHAMetadataOnly HDDS-6642 | …

HDDS-9381. Remove `@Flaky` annotations from now-stable test cases.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerReplicaCount.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECContainerReplicaCount.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyRatisContainerReplicaCount.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisContainerReplicaCount.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeAdminMonitorImpl.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECContainerReplicaCount.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestDatanodeAdminMonitor.java

Mix of quasi-closed and unhealthy replicas blocks decommission even if sufficiently replicated.
a. Caused when only some of the replicas hit the error during write.
b. Can be fixed by removing this check:
```
if (!replicaSet.isHealthy()) {
if (LOG.isDebugEnabled()) {
unhealthyIDs.add(cid);
}
if (unhealthy < CONTAINER_DETAILS_LOGGING_LIMIT
```
However, simply removing that check is not a complete solution. We need to try and preserve any UNHEALTHY replicas that have the greatest Sequence ID. https://issues.apache.org/jira/browse/HDDS-9321 takes care of the Legacy Replication Manager side of things to preserve such UNHEALTHY replicas. This jira focuses on the decommissioning side.
Changes:
1. Implemented `isSufficientlyReplicatedForOffline` in `LegacyRatisContainerReplicaCount`. The …

HDDS-9354. LegacyReplicationManager: Unhealthy replicas of a sufficiently replicated container can block decommissioning

---

hadoop-ozone/dev-support/intellij/ozone-site.xml

Change default bucket layout to FILE_SYSTEM_OPTIMIZED for standalone run using Intellij.
https://issues.apache.org/jira/browse/HDDS-9391
Verified manually, Started ozone using Intellij and create volume/bucket.

HDDS-9391. Change default bucket layout to FSO in standalone run using Intellij.

---

.github/workflows/ci.yml

_unit_ check runtime varies around 70-85 minutes, but occasionally times out after 90 minutes (e.g. [here](https://github.com/apache/ozone/actions/runs/6421657632/job/17436882342#step:5:3145)).  I think we should increase the timeout to avoid unnecessarily failed CI runs.  While we should strive to reduce test runtime, the set of tests is also incrementally growing.
Also:
* _basic_ check timeout can be reduced after HDDS-6618 (long running parts were extracted to separate check)
* increase timeout of _build_, which occasionally times out in forks due to cache miss
https://issues.apache.org/jira/browse/HDDS-9402
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6429432639

HDDS-9402. Increase timeout of unit check

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

HDDS-9232 added a new test case in `TestOzoneManagerHAKeyDeletion`, now the only other test case started failing.
```
org.apache.hadoop.ozone.om.TestOzoneManagerHAKeyDeletion.testKeyDeletion  Time elapsed: 5.575 s  <<< ERROR!
at org.apache.hadoop.ozone.om.TestOzoneManagerHAKeyDeletion.lambda$testKeyDeletion$0(TestOzoneManagerHAKeyDeletion.java:84)
at org.apache.ozone.test.GenericTestUtils.waitFor(GenericTestUtils.java:221)
at org.apache.hadoop.ozone.om.TestOzoneManagerHAKeyDeletion.testKeyDeletion(TestOzoneManagerHAKeyDeletion.java:83)
```
The root cause is that `TestOzoneManagerHA` restarts OMs after each test, but `restart()` does not start `KeyManager`.  The latter creates `KeyDeletingService` only upon start.
Also fix `TestOmSnapshot`, which stops …

HDDS-9412. NPE in TestOzoneManagerHAKeyDeletion#testKeyDeletion

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMBlockProtocolServer.java

isAdmin check is added in multiple flows in [HDDS-1796](https://issues.apache.org/jira/browse/HDDS-1796). By default SCM process admin is just SCM user. In secure cluster, when request comes from OM to SCM for `allocateBlock` and  `deleteKeyBlocks` isAdmin check fails as request user is OM and OM is not admin for SCM process by default. 
In this PR removing the isAdmin check for `allocateBlock` and `deleteKeyBlocks` and keeping the behaviour same as before.
https://issues.apache.org/jira/browse/HDDS-9376
Verified manually in cluster

HDDS-9376. Revert isAdmin check from allocate and delete block flow.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java

Restore log appender wait time to 10ms for `TestOMRatisSnapshots`.
https://issues.apache.org/jira/browse/HDDS-9416
Ran `TestOMRatisSnapshots` 100x, no fork timeout (but reproduced HDDS-8876 a few times):
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6458193918

HDDS-9416. Intermittent fork timeout in TestOMRatisSnapshots

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/storage/ContainerProtocolCalls.java
hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ContainerOperationClient.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneDebugShell.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/ChunkKeyHandler.java

The block file path is incorrect for some nodes sometimes. All paths are the same (in the same data disks) in all the nodes, but in actuality, some of the nodes have the block path in different data disks. The problem is due to readContainer reading from the first node of the pipeline. If paths(storage dir) are different for different DN, then the tool needs to query every DN instead of just the first node similar to getBlockFromAllNodes.
So, we are querying every data node present in the pipeline to get the block information to display correct block paths.
https://issues.apache.org/jira/browse/HDDS-9356

HDDS-9356. Ozone debug chunkinfo shows incorrect block path for some nodes

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogImpl.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestDeletedBlockLog.java
hadoop-ozone/integration-test/dev-support/findbugsExcludeFile.xml
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestDeleteWithInAdequateDN.java

SCM deleting service should avoid sending delete transactions for under-replicated containers. It currently tracks all the transactions in memory until all the replicas receive the transaction. A lot of transactions for under-replicated containers could slow down the deletion as these will remain pending until the container reaches the desired replication. The service has a limit on pending transactions.
https://issues.apache.org/jira/browse/HDDS-4368

HDDS-4368. SCM should avoid sending delete transactions for under-replicated containers

---

hadoop-hdds/common/pom.xml
hadoop-hdds/common/src/main/java/org/apache/hadoop/util/UUIDUtil.java
hadoop-ozone/dist/src/main/license/bin/LICENSE.txt
hadoop-ozone/dist/src/main/license/jar-report.txt
hadoop-ozone/ozone-manager/pom.xml
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManagerServiceGrpc.java
pom.xml

The OM's org.apache.hadoop.ozone.om.OzoneManagerServiceGrpc#submitRequest method uses UUID.randomUUID() (through org.apache.hadoop.ipc.ClientId#getClientId) to set the clientId for an omRequest. The latter has a synchronized block inside that leads to high lock contention in case of a big amount of tiny files (1K) read requests (we were testing a read of 15mln 1KiB files from 3 clients in 50 threads, 150 threads in total). Hence, the clientId generator should be thread-local
https://issues.apache.org/jira/browse/HDDS-9379
Manual test of reading of 15mln 1KiB files

HDDS-9379. thread local client ID generator for omRequest

---

hadoop-ozone/dist/src/main/compose/ozone/test.sh
hadoop-ozone/dist/src/main/compose/testlib.sh

[HDDS-9255](https://issues.apache.org/jira/browse/HDDS-9255) introduced robot tests for lease Recovery, but the tests were never executed.
Aim is to add these tests in atleast one test suite.
[HDDS-9415](https://issues.apache.org/jira/browse/HDDS-9415)
CI: 
Working in fork CI : https://github.com/LZD-PratyushBhatt/ozone/actions/runs/6452398832/job/17514936342?pr=7

HDDS-9415. ozone-debug-lease-recovery.robot not part of acceptance tests

---

hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientUtils.java

During snapshotDiff call, if toSnapshot or fromSnapshot is empty we take temporary snapshots to represent current state of Object store. These temp snapshots are later discarded after returning snapDiff. If there is a failure to delete these snapshots, they must be logged so that user can manually delete them later. Having a separate service to delete this doesn't make sense as failed deletes are not a common scenario.
https://issues.apache.org/jira/browse/HDDS-8483

HDDS-8483. Log failed temp snapshot deletes.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/debug/TestLDBCli.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/DBScanner.java

Improving parsing speed of DB Scanner
```bash
ozone debug ldb --db=/tmp/metadata/om.db/ scan --column_family=keyTable -l 1000000 -o /dev/null
```
Before:
Take about 300s
After:
Take about 5s
**Performance improvement of about 50 ~ 60 times**
- Multi-threaded Json parsing, separate thread to read RocksDB, separate thread for output
- Replacing the Json parsing tool from Gson to Jackson
https://issues.apache.org/jira/browse/HDDS-9348
Existing Test

HDDS-9348. Improving parsing speed of DB Scanner

---

hadoop-ozone/dist/src/main/smoketest/admincli/pipeline.robot

Add robot test for pipeline list subcommands json output i.e.
`ozone admin pipeline list --json `
[HDDS-9427](https://issues.apache.org/jira/browse/HDDS-9427)
Added a robot test.
Result:
```
Create pipeline                                                       | PASS |
List pipelines                                                        | PASS |
List pipeline with json option                                        | PASS |
List pipelines with explicit host …
```

HDDS-9427. Robot test for JSON output option in Pipeline list subcommand

---

.github/workflows/intermittent-test-check.yml

Improve flaky-test-check job name to include input arguments for better usability and identification of the run.
https://issues.apache.org/jira/browse/HDDS-9445
Sample Run : https://github.com/sadanand48/hadoop-ozone/actions/runs/6486056047

HDDS-9445. Improve flaky-test-check job name.

---

hadoop-ozone/dist/src/main/compose/ozonesecure-ha/test-scm-decommission.sh
hadoop-ozone/dist/src/main/smoketest/scmha/scm-decommission.robot

The robot test currently was decommissioning the scm node that we were running the tests from. Hence the tests were abruptly stopping without any Pass/Fail message.
Changing the exec container to s3g to prevent this.
[HDDS-9437](https://issues.apache.org/jira/browse/HDDS-9437)
Passed CI: https://github.com/LZD-PratyushBhatt/ozone/actions/runs/6505325429/job/17669363810?pr=8

HDDS-9437. Intermittent failure in test-scm-decommission

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java
hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedRocksObjectUtils.java

Fix java.lang.UnsatisfiedLinkError: 'long org.rocksdb.ReadOptions.newReadOptions()' 
```bash
> docker exec -it ozone-om-1 bash
bash-4.2$ ozone debug ldb --db=/data/metadata/om.db ls
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'long org.rocksdb.ReadOptions.newReadOptions()'
at org.rocksdb.ReadOptions.newReadOptions(Native Method)
at org.rocksdb.ReadOptions.<init>(ReadOptions.java:16)
at org.apache.hadoop.hdds.utils.db.managed.ManagedReadOptions.<init>(ManagedReadOptions.java:28)
at org.apache.hadoop.hdds.utils.db.RocksDatabase.<clinit>(RocksDatabase.java:83)
at org.apache.hadoop.ozone.debug.ListTables.call(ListTables.java:47)
at org.apache.hadoop.ozone.debug.ListTables.call(ListTables.java:34)
at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
at …
```

HDDS-9419. java.lang.UnsatisfiedLinkError when trying to read RocksDB with ozone debug ldb

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/OzoneProtocolMessageDispatcher.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/ProtocolMessageMetrics.java

This metric shows how many threads are really working in an RPC server. 
https://issues.apache.org/jira/browse/HDDS-9424
Tested locally.

HDDS-9424. Add a metric to indicate how many concurrent requests an RPC Server (OM, SCM) is handling

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBTableStore.java

When the db is closed before calling `iterate(prefix)`, the `prefix` buffer is not released.
HDDS-9454
New unit tests.

HDDS-9454. TypedTable prefix iterator may leak CodecBuffer.

---

.github/pull_request_template.md
CONTRIBUTING.md

In the part, we have been in a situation when there is not much context provided behind the change. Also Jira doesn't have proper description as well other than a one-liner. This change is to add jira creation guideline and update PR template to preserve the context behind the change.
For more details, check [Ozone_Jira_and_PR_guidelines.pdf](https://issues.apache.org/jira/secure/attachment/13063247/13063247_Ozone_Jira_and_PR_guidelines.pdf) discussion.
https://issues.apache.org/jira/browse/HDDS-9363
No testing. Just documentation change.

HDDS-9363. Added jira guideline and updated Pull request template

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRackAware.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackAware.java

When used and favoured nodes are on same rack then there is possibility that all replicas will place into one rack. 
In this PR we are ensuring that if multiple racks are available then replicas will be placed in at least two racks, even though favoured node is on same rack as used node.
https://issues.apache.org/jira/browse/HDDS-8503
New Unit test.

HDDS-8503. Exclude nodes are not well considered in SCMContainerPlacementRackAware#chooseNodes

---

.github/workflows/intermittent-test-check.yml
hadoop-hdds/rocks-native/src/test/java/org/apache/hadoop/hdds/utils/db/managed/TestManagedSSTDumpIterator.java
hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/rocksdb/util/TestManagedSstFileReader.java
hadoop-ozone/dev-support/checks/native.sh
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileInterfaces.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileInterfacesWithFSO.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemWithFSO.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystemWithFSO.java
pom.xml

The new `flaky-test-check` workflow should skip `@Unhealthy` tests (these were `@Ignore` or `@Disabled` previously).
Also, convert a few leftover `@Disabled` instances to `@Unhealthy`.
https://issues.apache.org/jira/browse/HDDS-9443
Triggered run for `TestSecureOzoneCluster`, confirmed 2 unhealthy tests (of 16 total) were [excluded](https://github.com/adoroszlai/hadoop-ozone/actions/runs/6498802347):
```
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 139.993 s - in org.apache.hadoop.ozone.TestSecureOzoneCluster
```
Regular CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6498802347

HDDS-9443. Skip unhealthy tests in repeated runs workflow

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestSecureOzoneRpcClient.java

Remove the test case `testKeyOpFailureWithoutBlockToken` from `TestSecureOzoneRpcClient`.  It was disabled in HDDS-1119, and has never worked.  The same functionality is being tested in `TestBlockTokens` and `TestSecureOzoneContainer`.
https://issues.apache.org/jira/browse/HDDS-3429
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6523940629

HDDS-3429. Remove testKeyOpFailureWithoutBlockToken from TestSecureOzoneRpcClient

---

hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/SlowTest.java
hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/UnhealthyTest.java
hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/tag/Flaky.java
hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/tag/Native.java
hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/tag/Slow.java
hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/tag/Unhealthy.java
hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/tag/package-info.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
pom.xml

`TestOmSnapshot` requires 1000-1200 seconds in CI.  Single slowest test case is testDayWeekMonthSnapshotCreationAndExpiration (added in HDDS-8378), takes 130s in each 4 parameterized runs.  I propose marking `testDayWeekMonthSnapshotCreationAndExpiration` as slow.  Slow tests are skipped in regular CI, but still can be executed manually or in scheduled runs.
`@Slow` only applies to JUnit5 tests, so this PR also adds a matching `@Category` for JUnit4.
Also:
* improve javadoc comments on these tags/categories to clarify how they can be used
* fix package name mismatch in `package-info.java`
https://issues.apache.org/jira/browse/HDDS-9299
Before:
```
Tests run: 160, Failures: 0, Errors: 0, Skipped: 5, Time elapsed: 1,066.519 s - in org.apache.hadoop.ozone.om.TestOmSnapshot
```
After:
``` …
```

HDDS-9299. Mark TestOmSnapshot#testDayWeekMonthSnapshotCreationAndExpiration as slow

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestSecretKeysApi.java

Merge two test cases in `TestSecretKeysApi` to save some cluster setup time.
https://issues.apache.org/jira/browse/HDDS-9463
Before:
```
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 232.86 s - in org.apache.hadoop.ozone.scm.TestSecretKeysApi
```
After:
```
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 196.522 s - in org.apache.hadoop.ozone.scm.TestSecretKeysApi
```

HDDS-9463. Speed up TestSecretKeysApi

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneSnapshotRestore.java

Launch a single cluster for all tests in `TestOzoneSnapshotRestore` instead of one per test.
https://issues.apache.org/jira/browse/HDDS-9471
Before:
```
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 154.597 s - in org.apache.hadoop.ozone.om.snapshot.TestOzoneSnapshotRestore
```
After:
```
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 41.952 s - in org.apache.hadoop.ozone.om.snapshot.TestOzoneSnapshotRestore
```
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6537079445

HDDS-9471. Speed up TestOzoneSnapshotRestore

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeDecommissionManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/SimpleMockNodeManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestNodeDecommissionManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/container/testutils/ReplicationNodeManagerMock.java

If a datanode is registered to SCM on the cluster, and then it is stopped and the data disks cleared and then it is restarted, it will reconnect to SCM as a new node with a new UUID.
When this happens, the old datanode details are kept in SCM as a dead node and the mapping table which maps DNs running on a host to their UUIDs will contain two entries, leaving the decommission command unable to decide which entry is to be decommissioned, giving this error:
```
2023-10-03 08:05:50,279 ERROR [IPC Server handler 25 on 9860]-org.apache.hadoop.hdds.scm.server.SCMClientProtocolServer: Failed to decommission nodes
org.apache.hadoop.hdds.scm.node.InvalidHostStringException: Host host1.acme.org is running multiple datanodes registered with SCM, but no port numbers match. Please check the port …
```

HDDS-9481. A reformatted datanode node cannot be decommissioned

---

hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - JVM Metrics.json

Created a new dashboard and added visualisations for all the required JVM Metrics
https://issues.apache.org/jira/browse/HDDS-9308
The patch has been tested over a cluster. After ploting and configuring all mentioned JVM Metrics on Grafana, the dashboard looks like :

HDDS-9308. Dashboard for JVM metrics needs to be tracked across the cluster.

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/ThrowableFunction.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/snapshot/TestOMSnapshotCreateResponse.java

Currently rocksDb sst file becomes corrupt in case of delete range function while creating snapshot. Speculating the corruption could be because of delete range function. When a snapshot for a bucket is created, all keys corresponding to the bucket in the deletedTable & deletedDirTable are removed from active object store after creating the rocksdb checkpoint.
https://issues.apache.org/jira/browse/HDDS-9432
Existing unit tests. Issue is not reproducible

HDDS-9432. Perform individual delete key instead of delete range function

---

hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/FlakyTest.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestStorageContainerManager.java
pom.xml

`@Flaky` tag only applies to JUnit5 tests.  This change implements a similar feature for JUnit4 tests.  Now JUnit4 tests can be annotated with `@Category(FlakyTest.class)` to execute them in _integration (flaky)_ (with few repetitions if necessary) instead of their regular _integration_ split.
Also mark `TestStorageContainerManager#testContainerReportQueueTakingMoreTime` as flaky (see HDDS-8470).
https://issues.apache.org/jira/browse/HDDS-9466
Test marked as `@Category(FlakyTest.class)` was executed in _integration (flaky)_:
```
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.737 s - in org.apache.hadoop.ozone.scm.TestStorageContainerManager
```
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6544313982/job/17771626430#step:6:3824
Other tests in same class …

HDDS-9466. Introduce FlakyTest category for flaky JUnit4 tests

---

.github/workflows/ci.yml
hadoop-ozone/dev-support/checks/junit.sh

Let _integration_ check reuse Ozone jars created in _build_ check, instead of building everything from scratch.  These jars are not part of the cached Maven repo, so we need to upload/download them separately.
If there is a problem downloading the artifact (e.g. it has expired), `integration.sh` falls back to previous behavior.
To reduce code duplication, flaky/other executions are merged into the same code block.
https://issues.apache.org/jira/browse/HDDS-9485
Time for [_integration_ check's splits](https://github.com/adoroszlai/hadoop-ozone/actions/runs/6556786545) decreased by 10-20 minutes each compared to latest [run on `master`](https://github.com/apache/ozone/actions/runs/6556346778).

HDDS-9485. Let integration check reuse Ozone jars from build check

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataReader.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

Redundant ACL checks in getKeyInfo for S3 use case. See details in the JIRA. 
https://issues.apache.org/jira/browse/HDDS-9447
Should be covered by the existing tests in CI.

HDDS-9447. Redundant ACL checks in getKeyInfo for S3 use case

---

hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/TestMiniChaosOzoneCluster.java

This PR removes the `UnhealthyTest` category annotation from `TestMiniChaosOzoneCluster`, as it no longer times out.
https://issues.apache.org/jira/browse/HDDS-3131
This patch is tested using flaky-test-check workflow [CI run](https://github.com/devmadhuu/ozone/actions/runs/6559767946/job/17817681781) and no failures or timeout in 200 iterations.

HDDS-3131. Enable TestMiniChaosOzoneCluster

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/util/MetricUtil.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMPerformanceMetrics.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerRatisServer.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerProtocolServerSideTranslatorPB.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java

These added metrics expose the details of where write operators spend time one.
- On RPC server:
- Request validation
- PreExecute
- Convert OM request to Ratis format
- Ratis invocation
- Convert ratis response to OM response.
- On ratis execution:
- applyTransaction local latency.  
https://issues.apache.org/jira/browse/HDDS-9425
Local test.

HDDS-9425. Breakdown metrics for OM writes

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/BackgroundSCMService.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMStateMachine.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeDecommissionManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeStateManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/BackgroundPipelineCreator.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/security/RootCARotationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/security/SecretKeyManagerService.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/upgrade/FinalizationManagerImpl.java

Improve thread names in SCM by adding instance-specific prefix to make it easier to distinguish log messages from different instances.
https://issues.apache.org/jira/browse/HDDS-8720
Ran integration test with SCM HA (e.g. `TestSecretKeysApi`), checked thread names in log messages.
```
[scmNode-1-BackgroundPipelineScrubber]
[scmNode-1-ExpiredContainerReplicaOpScrubber]
[scmNode-1-ReplicationMonitor]
[scmNode-1-SCMHATransactionMonitor]
[scmNode-1-SecretKeyManagerService]
```
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6532064840

HDDS-8720. Improve thread names in SCM

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerStateMachine.java

**Root Cause** - The Jira ticket suggests that the issue is related to the order of operations. It appears that the ozoneManagerDoubleBuffer is created before the threadPrefix is set, and this might be the reason why the thread name is being set incorrectly.
**Resolution** - Reordered the initialization of `threadPrefix` to precede the creation of the `ozoneManagerDoubleBuffer`
https://issues.apache.org/jira/browse/HDDS-9518
I ran the `TestTrashService` class and verified the logs, which clearly display the `om node` prefix before the thread name `ozoneManagerDoubleBuffer`.
```
2023-10-23 11:58:21,931 [om1@group-C5BA1605619E-StateMachineUpdater] INFO  ratis.OzoneManagerDoubleBuffer (OzoneManagerDoubleBuffer.java:stopDaemon(559)) - Stopping OMDoubleBuffer flush thread
2023-10-23 …
```

HDDS-9518. Fix OM double buffer thread name.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeDecommissionManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestNodeDecommissionManager.java

When decommission command is executed and if port or hostname is wrong and doesn't present in SCM, in that case command retries for 300 times which is unnecessary. 
In this PR we are fixing below:
If hoststring or port is wrong, instead of throwing exception we are returning DataNodeAdmin error which will avoid retry and will be normal exit.
If there are multiple hosts passed in the command, hosts which are invalid we add into error list and continue decommissioning for the proper host.
https://issues.apache.org/jira/browse/HDDS-9511
Update existing tests and verify

HDDS-9511. Handle DataNode decommissioning error for hoststring and port.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneHAClusterImpl.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHA.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAMetadataOnly.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAMetrics.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerPrepare.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManagerStarter.java

Fix intermittent error in `testAllVolumeOperations`: `OMNotLeaderException: OM:omNode-1 is not the leader. Suggested leader is OM:omNode-2[localhost/127.0.0.1].`
`TestOzoneManagerHA` subclasses use a single cluster for all tests, and all OM instances are restarted after each test case.
The patch makes 3 main changes:
1. add "wait for OM leader election" before each test case
2. mark all OMs as active when restarting them (HA mini cluster keeps track of active and inactive OMs.  OM stopped via `stopOzoneManager()` is marked as inactive.  Before this change `restartOzoneManager()` still starts all OMs, even inactive ones.  But `getLeaderOM()` only considers active ones, thus we may not find the actual leader if it is left as "inactive".)
3. wait for OM RPC server to really stop (call …

HDDS-9429. Intermittent error in TestOzoneManagerHAMetadataOnly#testAllVolumeOperations

---

.github/workflows/intermittent-test-check.yml
hadoop-ozone/dev-support/checks/junit.sh

* Add a new job in `flaky-test-check` to sum up failures across all splits
* Fix `junit.sh` to stop on first failure if `FAIL_FAST=true`
* Improve _run name_ to include number of splits and iterations
https://issues.apache.org/jira/browse/HDDS-9509
Run with `Stop after first failure: false` (i.e. run all tests and collect results):
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6595397183/job/17920692241
Run with `Stop after first failure: true`:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6589388300/job/17903770249

HDDS-9509. Count total number of failures in flaky-test-check

---

hadoop-ozone/dist/src/main/compose/ozonesecure-ha/test-leadership.sh
hadoop-ozone/dist/src/main/compose/ozonesecure-ha/test-scm-decommission.sh
hadoop-ozone/dist/src/main/compose/ozonesecure-ha/test.sh
hadoop-ozone/dist/src/main/compose/ozonesecure/test-vault.sh

_acceptance (HA-secure)_ and _acceptance (secure)_ take quite a bit longer than all other checks.  This PR proposes to rebalance the tests in order to reduce wall-clock time for the complete CI run.
1. Create a new acceptance test split (`leadership`) to cover admin CLI, SCM/OM leader transfer, decomissioning.
2. Move some tests to `misc` split
3. Drop second run of `admincli` (with SCM=scm2.org) -- it affects only very few test cases since we have moved execution from `${SCM}` to `s3g`
4. Drop execution of `httpfs` tests in secure HA environment
https://issues.apache.org/jira/browse/HDDS-9508
CI:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6576844317
Total CI duration is now closer to 1.5 hours, and all acceptance check splits are within 1 hour.

HDDS-9508. Rebalance acceptance tests

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/grpc/metrics/GrpcMetrics.java

Fix some bugs about quantiles in GrpcMetrics.
https://issues.apache.org/jira/browse/HDDS-9513
Test locally.
When config is like:
```
<property>   
<name>ozone.grpc.metrics.percentiles.intervals</name>
<value>57</value>
</property
```
The result will be:

HDDS-9513. Fix gRPC queue time metrics

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestLegacyReplicationManager.java

`ozone admin container report` will count nodes as over-replicated if we are saving unhealthy replicas because they have unique origin IDs while still having sufficient quasi-closed replicas. For now we consider this a stable state, so these containers should not be flagged in the container report.
HDDS-9489
Unit test added

HDDS-9489. LegacyReplicationManager: Do not count unique origin nodes as over-replicated.

---

hadoop-ozone/insight/src/main/java/org/apache/hadoop/ozone/insight/scm/NodeManagerInsight.java

Updating the NodeManagerInsight to reflect the correct node metrics
https://issues.apache.org/jira/browse/HDDS-6154
Docker-compose environment with command ozone insight metrics scm.node-manager
`sh-4.2$ ozone insight metrics scm.node-manager
Metrics for `scm.node-manager` (SCM Datanode management related information.)
Node counters
in_service healthy Nodes: 3
in_service stale Nodes: 0
in_service dead Nodes: 0
decommissioning healthy Nodes: 0
decommissioning stale Nodes: 0
decommissioning dead Nodes: 0
decommissioned healthy Nodes: 0
decommissioned stale Nodes: 0
decommissioned dead Nodes: 0
entering_maintenance healthy Nodes: 0
entering_maintenance stale Nodes: 0
entering_maintenance dead Nodes: 0
in_maintenance healthy Nodes: 0
in_maintenance stale Nodes: 0
in_maintenance dead Nodes: 0 …

HDDS-6154. Update NodeManagerInsight with the correct node metrics

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/DirectoryDeletingService.java

Various OM background services can encounter NPE after shutdown:
```
[omNode-3-KeyDeletingService#0] WARN  utils.BackgroundService (BackgroundService.java:lambda$run$0(145)) - Background task execution failed
at org.apache.hadoop.ozone.om.OzoneManager.isLeaderReady(OzoneManager.java:4068)
at org.apache.hadoop.ozone.om.service.DirectoryDeletingService.shouldRun(DirectoryDeletingService.java:110)
at org.apache.hadoop.ozone.om.service.DirectoryDeletingService.access$0(DirectoryDeletingService.java:105)
at org.apache.hadoop.ozone.om.service.DirectoryDeletingService$DirDeletingTask.call(DirectoryDeletingService.java:145)
at org.apache.hadoop.hdds.utils.BackgroundService$PeriodicalTask.lambda$run$0(BackgroundService.java:140)
```
This happens mostly in integration …

HDDS-9519. NPE in OM background services during restart

---

.github/pull_request_template.md

In PR https://github.com/apache/ozone/pull/5372, pull request template was updated to provide more context in PRs description. But it created confusion and title is duplicated in PR description as well.
This change is to update the template so that title is not duplicated in description and only added to the PR title field.
https://issues.apache.org/jira/browse/HDDS-9363
No testing. Just documentation change.

HDDS-9363. Updated pull request template to remove PR title confusion

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/DeletedContainerBlocksSummary.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java

DeleteBlocksCommandHandler should not print TXID at info level.
Basically, the DeleteBlocksCommandHandler was logging all the delete block transaction IDs at info level, and thus flooding the datanode log.
Now, the transaction IDs are logged only if the Debug node is enabled, otherwise only the number of transactions are logged at info level.
This is done so that user is not overwhelmed with unimportant information, rather have cleaner and more relevant information.
[HDDS-9462](https://issues.apache.org/jira/browse/HDDS-9462) 
As it is only a logging change, no new test cases were added. But the existing tests for this module were run successfully.

HDDS-9462. DeleteBlocksCommandHandler should not print TXID at info level

---

hadoop-ozone/s3-secret-store/src/main/java/org/apache/hadoop/ozone/s3/remote/vault/VaultS3SecretStore.java
hadoop-ozone/s3-secret-store/src/test/java/org/apache/hadoop/ozone/s3/remote/vault/VaultS3SecretStoreTest.java

Fix authentication check for Vault S3 secret store. 
Its possible that Vault authentication token expire between authentication check call and required operation call.
https://issues.apache.org/jira/browse/HDDS-9529
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this.)

HDDS-9529. Reauth to Vault after failed request

---

hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestOpenKeyCleanupService.java

Fix intermittent failure in `TestOpenKeyCleanupService`.
There were several small items that contributed to the failures:
1. The test waited until `runCount` was incremented, then made some assertions.  However, `runCount` is incremented at the start of the cleanup task, so the other changes may have not been done when the test checked.  It needs to wait for `submittedKeyCount` to reach the expected value, since this counter is increased as the last step of the task.
2. `OpenKeyCleanupService` performs two tasks per run (processes different bucket layouts separately).  Tests use a combination of keys in the two layouts, hence it needs to wait until `runCount` is increased by both tasks.
3. OM is stopped after each test case.  We need to wait (`join()`) for it to finish stopping.
4. …

HDDS-8871. Intermittent failure in TestOpenKeyCleanupService

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneSnapshotRestore.java

Fix intermittent failure in the test by waiting so that create/delete operations are finished properly before key count is done
https://issues.apache.org/jira/browse/HDDS-9436
Ran test multiple times
```
[INFO] Running org.apache.hadoop.ozone.om.snapshot.TestOzoneSnapshotRestore
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 62.567 s - in org.apache.hadoop.ozone.om.snapshot.TestOzoneSnapshotRestore
[INFO]
[INFO]
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0
```

HDDS-9436. Intermittent failure in TestOzoneSnapshotRestore#testUnorderedDeletion

---

.github/workflows/ci.yml
.github/workflows/intermittent-test-check.yml
.gitignore
.mvn/extensions.xml
.mvn/gradle-enterprise.xml

It was nice meeting some of you at the Gradle booth last week at Community over Code. We discussed Develocity with some of you, and this would be the PR that enables it.
This PR publishes a build scan for every CI build and for every local build from an authenticated Apache committer. The build will not fail if publishing fails.
The build scans of the Apache Ozone project are published to the Develocity instance at [ge.apache.org](https://ge.apache.org/), hosted by the Apache Software Foundation and run in partnership between the ASF and Gradle. This Develocity instance has all features and extensions enabled and is freely available for use by the Apache Ozone project and all other Apache projects.
On this Develocity instance, Apache Ozone will have access not only to all of the published …

HDDS-9515. Capture build scans on ge.apache.org to benefit from deep build insights

---

hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestHddsClientUtils.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneClient.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/checksum/TestReplicatedBlockChecksumComputer.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/checksum/TestReplicatedFileChecksumHelper.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/io/TestECBlockOutputStreamEntry.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/io/TestKeyInputStreamEC.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneKMSUtil.java

Migrate the few of test classes to JUnit5
Migrate the following test classes to JUnit5. See parent task for details.
- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestHddsClientUtils.java
- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneClient.java
- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java
- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/checksum/TestReplicatedBlockChecksumComputer.java
- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/checksum/TestReplicatedFileChecksumHelper.java
- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/io/TestECBlockOutputStreamEntry.java
- …

HDDS-9500. Migrate simple tests in ozone-client to JUnit5

---

hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/TestOmUtils.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/TestOzoneAcls.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/exceptions/TestResultCodes.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/ha/TestOMFailoverProxyProvider.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmBucketArgs.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmBucketInfo.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmKeyInfo.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmKeyLocationInfoGroup.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmMultipartKeyInfo.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmMultipartUpload.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmSnapshotInfo.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmVolumeArgs.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOzoneAclUtil.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOzoneFsUtils.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestQuotaUtil.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/lock/TestKeyPathLock.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/lock/TestOzoneManagerLock.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/protocolPB/TestS3GrpcOmTransport.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/security/TestGDPRSymmetricKey.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/security/TestOzoneDelegationTokenSelector.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/security/acl/TestOzoneObjInfo.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/util/TestRadixTree.java

HDDS-9493. Migrating tests in ozone-common to JUnit5
Migrating all the tests under ozone-common to Junit5 and making sure that Junit4 is not used in any of the tests
Tested that using **grep -rlE "org.junit.[A-Z]" . --include '*.java'** command in hadoop-ozone/common folder
https://issues.apache.org/jira/browse/HDDS-9493 
Full CI run- https://github.com/VarshaRaviCV/ozone/actions/runs/6663851768

HDDS-9493. Migrating tests in ozone-common to JUnit5

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java
hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/compaction/log/CompactionFileInfo.java
hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/compaction/log/CompactionLogEntry.java
hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/CompactionNode.java
hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java
hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDiffUtils.java
hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/rocksdiff/TestRocksDBCheckpointDiffer.java
hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/rocksdiff/TestRocksDiffUtils.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestOMSnapshotDAG.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SstFilteringService.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotUtils.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestSstFilteringService.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/snapshot/TestOMSnapshotCreateResponse.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDiffManager.java

**Problem**:
The problem is that [SSTFilteringService](https://github.com/apache/ozone/blob/master/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SstFilteringService.java) and [SST pruning service](https://github.com/apache/ozone/blob/master/hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java#L1483) work independently and try to optimize the space by deleting unnecessary SST files. SSTFilteringService deletes some files which don't belongs to the snapshotted bucket and SST prune service deletes the file which are not required for diff calculations. On the other hand compaction DAG is global at Ozone level and is kind a not aware of the above two clean ups. Problem arises when calculating the delta files for two …

HDDS-8940. Fix for missing SST files on optimized snapDiff code path

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/OzoneDelegationTokenSecretManager.java

Fix deadlock during shutdown in `OzoneDelegationTokenSecretManager`:
```
"nullExpiredTokenRemover" 
java.lang.Thread.State: BLOCKED
at org.apache.hadoop.ozone.security.OzoneDelegationTokenSecretManager.removeExpiredToken(OzoneDelegationTokenSecretManager.java:612)
at org.apache.hadoop.ozone.security.OzoneDelegationTokenSecretManager.access$4(OzoneDelegationTokenSecretManager.java:610)
at org.apache.hadoop.ozone.security.OzoneDelegationTokenSecretManager$ExpiredTokenRemover.run(OzoneDelegationTokenSecretManager.java:647)
at java.lang.Thread.run(Thread.java:750)
"main" 
java.lang.Thread.State: WAITING
at java.lang.Object.wait(Native Method)
at java.lang.Thread.join(Thread.java:1257)
at java.lang.Thread.join(Thread.java:1331)
at org.apache.hadoop.ozone.security.OzoneDelegationTokenSecretManag …
```

HDDS-9546. Fix possible deadlock during shutdown in OzoneDelegationTokenSecretManager

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/SCMCommonPlacementPolicy.java

When we get placement policy problems, potentially caused by full or non-writable nodes, it is not possible to see why nodes were rejected without enabling debug logging.
This change adjusts the log added in [HDDS-9167](https://issues.apache.org/jira/browse/HDDS-9167) to be info level, as this should only be logged when nodes are not valid for space or non-writable reasons.
https://issues.apache.org/jira/browse/HDDS-9558
Log level change. No tests modified.

HDDS-9558. Log reason for not using a node at info level in SCMCommonPlacementPolicy

---

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/insights/insights.tsx

[Recon][UI] On File Size Insights Page
Bucket Drop down filter is not getting disabled when more than 1 volume is selected
As discussed, bucket drop down filter works only for 1 volume and can't be used if more than 1 volume are present.
When 2 volumes are selected the Bucket list drop down is not getting disabled, whereas on selecting 3 volumes it is getting disabled.
https://issues.apache.org/jira/browse/HDDS-9556
Manually
Before this Change Bucket  dropdown is not disabled.
After this PR change Bucket Drop Down is Disabled

HDDS-9556. Recon UI : Bucket Drop down filter is not getting disabled when more than 1 volume is selected

---

hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedReadOptions.java
hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedRocksObjectUtils.java
hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedSlice.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/DBScanner.java

`TestLDBCli` intermittently fails due to:
```
2023-09-14 01:01:32,542 [Finalizer] WARN  managed.ManagedRocksObjectUtils (ManagedRocksObjectUtils.java:assertClosed(64)) - ManagedReadOptions is not closed properly
2023-09-14 01:01:32,542 [Finalizer] WARN  managed.ManagedRocksObjectUtils (ManagedSlice.java:finalize(42)) - ManagedSlice is not closed properly
```
This change attempts to fix it by closing `ManagedReadOptions` and `ManagedSlice` instance in `DBScanner`.
Also, add allocation stack trace to `ManagedReadOptions` and `ManagedSlice` to help debug any further leak.
https://issues.apache.org/jira/browse/HDDS-9283
`TestLDBCli` passed:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/6678993900/job/18157010772#step:6:113
(Even without the fix I could not intentionally reproduce …

HDDS-9283. ManagedReadOptions/ManagedSlice not closed properly in DBScanner

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeAdminMonitorImpl.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestDatanodeAdminMonitor.java

When decommissioning a node, if there are replicas for a container which are marked as deleting in SCM, decommission should not wait on them, as they are going to be removed anyway.
We have also seen some cases where the container is deleting and has some unhealthy replicas which can cause decommission to hang unnecessarily.
This change will have decommission check for deleting containers and ignore them for the purposes of allowing decommission to complete.
https://issues.apache.org/jira/browse/HDDS-9555
New unit test added.

HDDS-9555. Decommission should not wait on deleting containers

---

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/NSSummaryTask.java

This item's jira: [Improve NSSummaryTask thread name](https://issues.apache.org/jira/browse/HDDS-9560)
Change NSSummaryTask thread name missing from https://github.com/apache/ozone/pull/5456
Sometimes in tests it's hard to follow which thread was created where, adding these prefixes help clarifying these. More can be found in the parent jira: [Improve thread names](https://issues.apache.org/jira/browse/HDDS-8719).
Running the test locally and observing that the threadnames changed and starting a CI run on my fork: https://github.com/Galsza/ozone/actions/runs/6696071994

HDDS-9560. Improve NSSummaryTask thread name

---

.github/workflows/ci.yml
dev-support/ci/selective_ci_checks.bats
dev-support/ci/selective_ci_checks.sh

Draft PRs usually skip most checks.  However, if CI code is changed, all checks are run.  This is unnecessary, because marking the PR ready for review will trigger a new run anyway.
Also minor addendum for HDDS-6618: wait for successful _basic_ check before starting _compile_ check (which tests compilation with Java 11 and 17).
https://issues.apache.org/jira/browse/HDDS-9406
Added bats test case.  Also tested by creating this PR as draft.
Draft CI:
https://github.com/apache/ozone/actions/runs/6453841050?pr=5406
Regular CI:
https://github.com/apache/ozone/actions/runs/6453854455?pr=5406

HDDS-9406. Do not run all checks for draft PR touching CI files

---

hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java

Set HadoopRPC as the default transport between S3 and Ozone. Details in JIRA.
https://issues.apache.org/jira/browse/HDDS-9446
Tested locally to verify HadoopRPC is used for the traffic S3->OM.

HDDS-9446. Set HadoopRPC as the default transport between S3 and Ozone.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestStorageContainerManager.java

Speed up `TestStorageContainerManager` by about 10% by reusing an existing cluster within `testRpcPermission`.
Also remove creation of `container3`, which had no difference at all from `container2`.
https://issues.apache.org/jira/browse/HDDS-9464
Before:
```
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 245.604 s - in org.apache.hadoop.ozone.scm.TestStorageContainerManager
```
After:
```
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 218.325 s - in org.apache.hadoop.ozone.scm.TestStorageContainerManager
```

HDDS-9464. Speed up TestStorageContainerManager

---

hadoop-ozone/dist/src/main/smoketest/s3/objectcopys3a.robot
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/BucketEndpoint.java

`BucketEndPoint` returns keys without considering `"/" ` for FSO bucket, So it matches `dir1/` with `dir123` also, and return back the result. Because of this it leads to incorrect behaviour for FSO bucket keys.
To fix this issue in this PR we are ensuring exact prefix match so that for FSO bucket result from `BucketEndPoint` is proper.
https://issues.apache.org/jira/browse/HDDS-9229
Manually tested using dfs s3a for FSO bucket.

HDDS-9229. Fix S3A compatibility - dfs -put for FSO bucket.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/EmptyContainerHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestEmptyContainerHandler.java

If a container appears empty to SCM (ie key count is zero in the containerInfo) and there are no replicas, it could be a container which failed to be created on the datanodes, and no replicas will ever be reported.
However there isn't enough information to know if the container can be safely deleted or not, as the DN could have gone offline or missed some heartbeats etc.
As things stand, such as container will appear as missing in the container report. In this PR, we change that to leave the container as CLOSED but count it as EMPTY without triggering the delete process.
That means if replicas later appear, it will be OK. 
However if the replicas never appear, the container will be stuck in this state forever. Additionally, if there **should** be replicas, as the client successfully wrote …

HDDS-9550. Container report shows missing containers when they actually appear empty

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestLegacyReplicationManager.java

This change mirrors #5523 for the legacy RM.
If a container appears empty to SCM (ie key count is zero in the containerInfo) and there are no replicas, it could be a container which failed to be created on the datanodes, and no replicas will ever be reported.
However there isn't enough information to know if the container can be safely deleted or not, as the DN could have gone offline or missed some heartbeats etc.
As things stand, such as container will appear as missing in the container report. In this PR, we change that to leave the container as CLOSED but count it as EMPTY without triggering the delete process.
That means if replicas later appear, it will be OK.
However if the replicas never appear, the container will be stuck in this state forever. Additionally, if there should be …

HDDS-9602. Backport HDDS-9550 to legacy RM (missing containers which are empty)

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/utils/BufferUtils.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/FilePerBlockStrategy.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/FilePerChunkStrategy.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/interfaces/BlockManager.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/interfaces/ChunkManager.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/helpers/TestChunkUtils.java

defaultReadBufferCapacity was changed from long to int in this PR. 
This change was made because although defaultReadBufferCapacity was long in BlockManagerImpl/FilePerBlockStrategy/FilePerChunkStrategy, it was casted to int when it is used as shown below.
```
//BufferUtils.assignByteBuffers
for (int i = 0; i < numBuffers - 1; i++) {
dataBuffers[i] = ByteBuffer.allocate((int) bufferCapacity);
buffersAllocated += bufferCapacity;
}
```
Using long as buffer capacity does NOT work for Java array, Java ByteBuffer, Protobuf ByteString and Netty ByteBuf. Moreover, if we set ozone.chunk.read.buffer.default.size to "2GB", `((int) bufferCapacity) == -2147483648 ` would throw an IllegalArgumentException from ByteBuffer.allocate(..).
https://issues.apache.org/jira/browse/HDDS-9549
Existing tests in …

HDDS-9549. defaultReadBufferCapacity should be int instead of long

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/interfaces/BlockManager.java

There were some inconsistent API definitions in BlockManager and BlockManagerImpl for putBlock(), getBlock(), getCommittedBlockLength(), deleteBlock() and listBlock().
This PR makes all the definitions consistent between the BlockManager interface and BlockManagerImpl class. 
https://issues.apache.org/jira/browse/HDDS-9540
As it is only a JavaDoc change, No tests were performed

HDDS-9540. Inconsistent API definitions in BlockManager

---

.github/workflows/ci.yml

SonarCloud will no longer accept scans created with Java 11 ([announcement](https://community.sonarsource.com/t/java-11-is-deprecated-as-a-runtime-env-to-scan-your-projects/96597)), so we should upgrade _coverage_ check to Java 17.
Also: checkout the project with history, to eliminate a [warning](https://github.com/apache/ozone/actions/runs/6712269060/job/18244181507#step:8:5788) printed for each source file.
https://issues.apache.org/jira/browse/HDDS-9605
CI (in `apache/ozone` instead of my fork, because forks and PRs skip coverage check):
https://github.com/apache/ozone/actions/runs/6724730333
Verified that analysis was uploaded to SonarCloud:
https://sonarcloud.io/summary/overall?id=hadoop-ozone&branch=HDDS-9605

HDDS-9605. Upgrade coverage check to Java 17

---

hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java

Enable multipart upload cleanup service by default by setting `ozone.om.open.mpu.parts.cleanup.limit.per.task` to 1000.
Set to the same value as open key clean up service. 
https://issues.apache.org/jira/browse/HDDS-9625
Only configuration change. Unit tests already enable the clean up service.

HDDS-9625. Enable multipart upload cleanup service by default

---

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/utils/columnSearch.tsx

Need to Highlight Search Functionality Icon across all pages so it will be helpful in debugging.
https://issues.apache.org/jira/browse/HDDS-9599
Manually
Before this PR
After this PR Change

HDDS-9599. Recon : Highlight the search icon on the containers page of Recon UI

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/Checksum.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChunkBufferImplWithByteBuffer.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChunkBufferImplWithByteBufferList.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/utils/BufferUtils.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/ChunkUtils.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/FilePerBlockStrategy.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/FilePerChunkStrategy.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/interfaces/ChunkManager.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerPersistence.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/helpers/TestChunkUtils.java

In KeyValueHandler.validateChunkChecksumData(..), it converts ChunkBuffer to ByteString, which will be converted back to ChunkBuffer.
Also includes code cleanup:
- avoid passing buffer capacity as `long`;
- check for integer overflow
All the changes were discovered in HDDS-9536.
HDDS-9611

HDDS-9611. Avoid unnecessary buffer conversion.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerImpl.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmMetrics.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataReader.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ResolvedBucket.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerUnit.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestBucketRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/file/TestOMDirectoryCreateRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/file/TestOMDirectoryCreateRequestWithFSO.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/TestCleanupTableInfo.java

OM's getKeyInfo API internally does the following steps:
1. Resolve bucket link: confirms that bucket/volume exists, resolve the bucket's real name if the bucket param points to a soft link.
2. ACL check: check if the user has access to the requested resource.
3. Read key metadata from rocks db.
4. Get block container location cache/SCM.
5. Generate block token for read.
Although during (1), bucket/volume info is already retrieved from db/cache, step (2) and (3) still re-read the same information to extract different sub-attribute. e.g. (2) needs to read bucket/volume to get bucket/volume owner name, (3) needs to get bucket layout.
Those redundant reads unnecessarily add a significant cost to API, given that each read involves locking, encoding/decoding results... …

HDDS-9297. getKeyInfo re-read bucket/volume info multiple times

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java

There are some irregular document descriptions in OzoneConfigKeys, one of which is the description of DFS_CONTAINER_IPC_PORT_DEFAULT. The purpose of this PR is to improve some documentation.
Also, there is one description here that needs to be updated.
When set to false (default), the container port will be specified as {@link #DFS_CONTAINER_IPC_PORT} and the default value will be specified as {@link #DFS_CONTAINER_IPC_PORT_DEFAULT}.
https://issues.apache.org/jira/browse/HDDS-9628
This PR is mainly related to documentation and does not require too much testing.

HDDS-9628. Link in OzoneConfigKeys javadoc from DFS_CONTAINER_IPC_RANDOM_PORT to DFS_CONTAINER_IPC_PORT

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisUnderReplicationHandler.java

Even though: 
1. The new RM will send close commands to QUASI_CLOSED replicas of CLOSED containers with matching sequence IDs (MismatchedReplicasHandler), and 
2. It'll only replicate replicas that match the container's sequence ID (RatisUnderReplicationHandler)
there's a chance that RM ends up replicating a QUASI_CLOSED replica of a CLOSED container when other CLOSED replicas are available. This is a problem, since we want to replicate CLOSED replicas when possible.
This PR fixes the bug by only picking CLOSED replicas as sources if they're available. If they aren't available, or if the container is QUASI_CLOSED, then QUASI_CLOSED replicas are also allowed as sources.
https://issues.apache.org/jira/browse/HDDS-9591

HDDS-9591. Replication Manager could incorrectly use QUASI_CLOSED replicas as replication sources for CLOSED containers

---

.github/workflows/repeat-acceptance.yml
hadoop-ozone/dist/src/main/compose/testlib.sh

HDDS-9357 added a workflow for running some integration test repeatedly.  This change implements similar feature for acceptance tests.
Acceptance tests can already be limited by suite or filter pattern.  One of these should be provided to the workflow.  If both of them are provided, suite is given precedence.  If both of them are empty, all acceptance tests are run, which will take quite some time.
Iterations within the same split are not implemented, so repetitions are only controlled by number of splits.  They are run concurrently (with some limit imposed by GitHub).  It also makes it a bit easier to interpret results (count failures).
https://issues.apache.org/jira/browse/HDDS-9629
Triggered for existing test with filter:
https://github.com/adoroszlai/hadoop-ozone/actions/runs/675444924 …

HDDS-9629. Create workflow for running acceptance test repeatedly

---

hadoop-hdds/rocks-native/pom.xml

Make native build thread count configurable. Build should set system.numCores property to the cpu count of the build machine if the property is not passed by the user during the maven build.
E.g. mvn -X clean install -DskipTests -pl :hdds-rocks-native -Drocks_tools_native -Dsystem.numCores=5
https://issues.apache.org/jira/browse/HDDS-9584
Native build succeeded in local.

HDDS-9584. Make native build thread count configurable

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ECReplicationConfig.java

There is some missing documentation and comments in ECReplicationConfig, the purpose of this PR is to improve here.
Details: HDDS-9630
https://issues.apache.org/jira/browse/HDDS-9630
This PR is mainly related to documentation and does not require too much testing.

HDDS-9630. Add missing javadoc description for ECReplicationConfig constructor param

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/utils/HddsVolumeUtil.java

Currently the rocksdb that loads schema v3 uses sequential loading and is slow to load, the purpose of this PR is to speed up the loading of the rocksdb using parallel loading.
This is my test data:
1. datanode 35 disks * 8TB Wrote about 50% of the capacity
2. after restarting the datanode, it took 5 minutes to load the checksdb.
After using this feature:
```
2023-11-07 16:25:06,699 [main] INFO org.apache.hadoop.ozone.container.ozoneimpl.OzoneContainer: Load 35 volumes DbStore cost: 1532ms 
```
https://issues.apache.org/jira/browse/HDDS-9641

HDDS-9641. Parallel loading datanode volume db store

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java

When uploading a file with the same name using a slice overwrite, if the number of previous copies is not the same as the current one, the meta information is updated incorrectly.
Example:
1. a file with the name `A` is uploaded the first time it is ratis 3 factor
2. the second time a file with the same name `A` is uploaded using multipart upload it is ec-3-2-512k
3. the replication config in the meta-information is recorded as ratis 3 factor, but it should actually be ec-3-2-512k.
```
$ ozone sh bucket create --layout=OBJECT_STORE  --replication=rs-3-2-512k --replication-type=EC s3v/testbucket
$ ozone sh bucket info s3v/testbucket
{
"volumeName" : "s3v",
"name" : "testbucket", …
```

HDDS-9607. Overwrite file by multipart upload, saving wrong ReplicationConfig in KeyInfo

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestDelegationToken.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecureOzoneCluster.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

Hadoop use property "hadoop.security.token.service.use_ip" to control when the IP or the host name will be used as  service name in delegation token. 
If hadoop.security.token.service.use_ip is true(default).  then IP address will be used to construct the Token service field, otherwise, then use host name. 
Currently in Ozone, service name in delegation token always use host name.
https://issues.apache.org/jira/browse/HDDS-9523
Tested by the enhanced existing unit test.

HDDS-9523. Ozone manager doesn't honor property 'hadoop.security.token.service.use_ip'

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/StorageContainerNodeProtocol.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconNodeManager.java

`Last Heartbeat` in the Datanodes section in Recon's UI, is always showing NA because the `datanodeHeartbeatMap` in `ReconNodeManager` doesn't get updated. 
PR #4341, modified the `processHeartbeat()` method to also process the queue report as part of the heartbeat, by adding a `CommandQueueReport` parameter.
[SCMDatanodeHeartbeatDispatcher.dispatch()](https://github.com/apache/ozone/blob/master/hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeHeartbeatDispatcher.java#L133-L134) is the only place where `processHeartbeat()` is used but it's only calling the overloaded method with the 3 parameters. Recon overrides the 2 parameter method and as a result, Recon's `processHeartbeat()` never gets called. 
The 2 parameter method is only used in tests and for that …

HDDS-9609. Recon doesn't display 'Last Heartbeat' for datanodes

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestListKeysWithFSO.java

Option **--delimiter '/'**  in ListObjectsV2  Is a commonly used option. Common scenarios are as follows:
- simple aws s3 cmd like `aws s3 --endpoint http://<ip>:9878 ls buk/dir/`
- aws s3api cmd like `aws s3api --endpoint http://<ip>:9878 list-objects-v2 --bucket buk1-ln --prefix '' --delimiter '/'`
- fuse mount s3 bucket and ls cmd
Only listing immediate children node of prefix is needed in the above scenario.
In the current implementation of FSO bucket, the object is listed by Depth-First-Search algorithm, and then filtered by delimiter, which greatly reduces the performance.
It was reduced from tens of seconds to 3 seconds in my test environment after optimization.
https://issues.apache.org/jira/browse/HDDS-8773
- Unit test
- CLI commands in ozone cluster environment as follow
info : …

HDDS-8773. [S3G] Improve list performance in FSO bucket

---

.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/dependabot-ci.yml
hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/package.json

HDDS-9171. Added a dependabot.yml file to control the PRs that are being raised by dependabot for auto-upgrade of versions.
* The Ozone upstream repo has dependabot upgrades enabled to maintain versions for JS libraries, however right now dependabot only updates the `pnpm-lock.yaml` file which is an incorrect behaviour and would cause build failures.
* This PR adds a dependabot.yml file to set the rules on which folders to scan for possible upgrades, defining the proper package manager to use, and setup general dependabot behaviour.
* This also adds a few github actions, which would be triggered on a dependabot raised PR.
* Why the actions are required?
Even after we properly define the dependabot behaviour, it would properly update the versions on the …

HDDS-9171. Resolve dependabot build issues when updating npm packages

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockDataStreamOutputEntryPool.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntryPool.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyDataStreamOutput.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/OzoneDataStreamOutput.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/OzoneOutputStream.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneClient.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/EndpointBase.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpointStreaming.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/ClientProtocolStub.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneBucketStub.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneOutputStreamStub.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestMultipartUploadWithCopy.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectPut.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestPartUpload.java

To fix the problem of abnormal dirty data overwriting normal data when S3G writes data. Make Ozone S3 puts atomic writes, all successes total or failures
The main implementation is to check whether the data of the key is complete or not when committing, if the data written by the key is different from the expected size, the key is considered incomplete, and the commit operation is not executed.
```java
@Override
public synchronized void close() throws IOException {
//...
try {
//...
if (requiresAtomicWrite) {
long expectedSize = blockOutputStreamEntryPool.getDataSize();
Preconditions.checkArgument(expectedSize == offset,
String.format("Expected: %d and actual %d write sizes do not match",
expectedSize, offset));
}
blockOutputStreamEntryPool.commitKey(offset);
} finally { …
```

HDDS-9526. Two S3G instances writing the same key may cause data loss in case of an exception.

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshot.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/FSODirectoryPathResolver.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/ObjectPathResolver.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestFSODirectoryPathResolver.java

FSO bucket Snapdiff fails in the case a key is renamed into a directory that would be eventually deleted. The path resolution for the parent directory fails since the directory doesn't come as part of the tree walk of the target snapdiff dir table.
Making changes in DirPathResolver to ignore exception for unreachable dirObjectIds for target snapshots directory path resolution and adding delete entry in the snapshot diff report instead.
https://issues.apache.org/jira/browse/HDDS-9597
Adding integration test

HDDS-9597. Snapdiff fails in case of key renames to deleted directories

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CloseContainerCommandHandler.java

When a datanode which is not the followed received a closed container command, if the pipeline is still active and the datanode is not the pipeline leader, the close fails with a NotLeaderException.
If the container is failing to close for some reason (eg [HDDS-3509](https://issues.apache.org/jira/browse/HDDS-3509)) then there are no clues in the DN log that it is failing to close the container.
We should log this at INFO level rather than debug.
https://issues.apache.org/jira/browse/HDDS-9557
Logging only change - no tests modified.

HDDS-9557. Datanode should log Follower cannot close container at info level

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotMetrics.java

Snapshot's snap diff acceptance test failed with an exception `Metrics source OmSnapshotMetrics already exists!`. Based on exception and message looks like `OmSnapshotMetrics` is getting initialized more than once. Even though it is singleton class, it is not synchronized. So it is possible that two or more threads can try to register `OmSnapshotMetrics` metric at the same time and fail except the first one.
This change is to put `register` inside a `synchronized` block and added double check to make sure that it is registered only once.
https://issues.apache.org/jira/browse/HDDS-9559
Existing unit test.

HDDS-9559. Synchronized OmSnapshotMetrics initialization

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DefaultCertificateClient.java

Resolve the backward compatibility issue introduced in HDDS-8588. 
The root cause is that the listCA() call during SCM, will try to call SCM's SCMSecurityProtocolServer API, but this SCMSecurityProtocolServer is not ready at that time. The call has a max retry policy. So SCM will stuck in the retry and cannot startup. 
The fix avoids the remote API call, use local on disk info to build the TrustChain.
https://issues.apache.org/jira/browse/HDDS-9420
Tested it manually. Here is the step 
1. enable ozone security,  ozone.security.enabled
2. enable grpc security, hdds.grpc.tls.enabled
3. Install a 1.3.0 OM cluster with above properties, do "scm --init", start scm, and then stop scm
4. upgrade the cluster to master branch, start scm, scm hang with following stack, stop scm
```
"main" #1 prio=5 …
```

HDDS-9420. [Compatibility]Enabling GRPC encryption causes SCM startup failure

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ratis/RatisHelper.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestTransferLeadershipShell.java

Currently, Ratis transfer leadership uses priority as a way for the previous leader to yield its leadership to the target peer with higher priority.
The implementation in Ozone uses setConfiguration API to set the target peer's priority to 2 (higher priority) while the rest is set to 1 (neutral priority).
However, we need to reset the priorities back to the same priorities (1 in this case) after transfer leadership (regardless of the transfer leadership result) to avoid cases where the same Raft peer will always be favored to be the leader (even if the peer is slow).
https://issues.apache.org/jira/browse/HDDS-9627
Integration testing. Add Raft peers priority assertions to `TestTransferLeadershipShell` after transfer leadership is finished.
Clean CI run: …

HDDS-9627. Reset RaftPeer priorities after transfer leadership

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMDbCheckpointServlet.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMDBCheckpointServlet.java

When ratis is disabled, a null pointer exception is reported, so I tried to fix it.
I am setting ozone.om.ratis.enable in ozone.xml as :
//ozone-site.xml
```
<property>
<name>ozone.om.ratis.enable</name>
<value>false</value>
</property> 
```
When I using http://my.om.address:9874/dbCheckpoint
This is the error:
```
2023-10-25 20:17:09,444 [qtp1013364696-226] ERROR org.apache.hadoop.hdds.utils.DBCheckpointServlet: Unable to process metadata snapshot request. 
        at org.apache.hadoop.ozone.om.OMDBCheckpointServlet$Lock.lock(OMDBCheckpointServlet.java:672)
        at org.apache.hadoop.hdds.utils.DBCheckpointServlet.generateSnapshotCheckpoint(DBCheckpointServlet.java:197)
        at org.apache.hadoop.hdds.utils.DBCheckpointServlet.doGet(DBCheckpointServlet.j …
```

HDDS-9541. NPE in OMDBCheckpointServlet.Lock#lock with OM Ratis disabled

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/debug/TestLDBCli.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/DBScanner.java

Fix for an exception which occurs during serialization of nodesInOrder when using ldb scan for scm.db and pipelines column family.
[https://issues.apache.org/jira/browse/HDDS-9587](https://issues.apache.org/jira/browse/HDDS-9587)
Manual tests

HDDS-9587. `No serializer found for class ThreadLocal` in DBSCanner for pipelines in scm.db

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/metadata/SCMMetadataStoreImpl.java

When SCMMetadataStoreImpl#start() is called, SCMDBDefinition instances will be created repeatedly, which will add more system overhead.
https://issues.apache.org/jira/browse/HDDS-9677
Just make sure that the existing unit tests pass.

HDDS-9677. Reuse SCMDBDefinition instance in SCMMetadataStoreImpl#start()

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java

TestOMRatisSnapshots is still failing after marking it [flaky](https://github.com/apache/ozone/commit/87958e61e9b40ef94d0cde61ced9cea1ac502db4) to run repeatedly. This change is to disable TestOMRatisSnapshots test for now.
https://issues.apache.org/jira/browse/HDDS-8876

HDDS-8876. Marked TestOMRatisSnapshots unhealthy

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMBlockProtocolServer.java

SCM's audit log entry for sort datanodes request does not have information about the request (client, node list).  This change adds them.
https://issues.apache.org/jira/browse/HDDS-9676
Checked audit log entry, example:
```
2023-11-13 08:41:13,856 | INFO  | SCMAudit | user=hadoop | ip=10.5.0.70 | op=SORT_DATANODE {client=10.5.0.71, nodes=[6a9a42ad-9ecd-4e96-bf45-5255f6be66bf, a12806c3-6e7f-479a-be63-20cb3ecb0eb4, cfac92e5-cdce-471d-a995-e6f4dc22ea6f]} | ret=SUCCESS |  
```
CI:
https://github.com/adoroszlai/ozone/actions/runs/6847145541

HDDS-9676. SORT_DATANODE audit log should include request details

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/protocol/DatanodeDetails.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NetworkTopologyImpl.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/server/TestSCMBlockProtocolServer.java

When datanode registers, SCM adds the `DatanodeDetails` object to:
* `NetworkTopologyImpl`, which sets `level` in `DatanodeDetails`
* `NodeStateMap` (via `NodeStateManager`), which copies it as a `DatanodeInfo` object (`extends DatanodeDetails`)
The problem is that `level` is lost during this copy.  These `DatanodeInfo` objects are retrieved from `NodeStateMap` and passed to `NetworkTopologyImpl` by `sortDatanodes`.  Since all datanodes have the same level, distance calculation still works, but this is accidental.  Searching for a `Node` object that has the proper level set would yield wrong results.
This change ensures `level` is copied to the wrapper `DatanodeInfo`.
https://issues.apache.org/jira/browse/HDDS-9678
Added unit test case to verify datanodes assigned to two racks are sorted …

HDDS-9678. Topology level is not set in datanode object for distance calculation

---

hadoop-ozone/recon/pom.xml
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestBlocksEndPoint.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestContainerEndpoint.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestContainerStateCounts.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestFeaturesEndPoint.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestNSSummaryEndpointWithFSO.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestNSSummaryEndpointWithLegacy.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestOmDBInsightEndPoint.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestOpenContainerCount.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestTriggerDBSyncEndpoint.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/heatmap/TestHeatMapInfo.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/persistence/AbstractReconSqlDBTest.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/persistence/TestReconWithDifferentSqlDBs.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/recovery/TestReconOmMetadataManagerImpl.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconNodeManager.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconPipelineManager.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/spi/impl/TestReconContainerMetadataManagerImpl.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/spi/impl/TestReconDBProvider.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/spi/impl/TestReconNamespaceSummaryManagerImpl.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestContainerKeyMapperTask.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestOMDBUpdatesHandler.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestOmTableInsightTask.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestOmUpdateEventValidator.java

Migrate the following test classes to JUnit5.
Migrate the following test classes to JUnit5. See parent task for details.
- As a first batch modified following files.
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/TestReconUtils.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestBlocksEndPoint.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestContainerEndpoint.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestFeaturesEndPoint.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestNSSummaryEndpointWithFSO.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestNSSummaryEndpointWithLegacy.java …

HDDS-9498. Migrate tests with TemporaryFolder in ozone-recon to JUnit5

---

.github/workflows/ci.yml

Coverage check is skipped in forks and for PRs.  However, dependabot pushes dependency version bumps to the main repo instead of its own fork.  The check is failing, because secrets required for this step are not available for the bot.  We should also skip coverage check for dependabot's branches.
https://issues.apache.org/jira/browse/HDDS-9682
`coverage` check was skipped when pushed to branch `dependabot-HDDS-9682` in `apache/ozone`:
https://github.com/apache/ozone/actions/runs/6854896922/job/18642348015

HDDS-9682. Skip coverage check for dependabot

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestDataUtil.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotFileSystem.java

This change is to migrate TestOmSnapshotFileSystem tests from JUnit-4 to JUnit-5. Changed the cluster setup to only once at class level as suggested in https://github.com/apache/ozone/pull/4740.
https://issues.apache.org/jira/browse/HDDS-8201
Ran the unit test locally and workflow run. Test run time after the change around 80 secs.
```
[INFO] Running org.apache.hadoop.ozone.om.TestOmSnapshotFileSystem
[INFO] Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 80.806 s - in org.apache.hadoop.ozone.om.TestOmSnapshotFileSystem
```

HDDS-8201. Migrated TestOmSnapshotFileSystem tests to JUnit5.

---

hadoop-ozone/dist/src/main/compose/common/hadoop-secure.yaml
hadoop-ozone/dist/src/main/compose/common/hadoop-security.conf
hadoop-ozone/dist/src/main/compose/common/hadoop-test.sh
hadoop-ozone/dist/src/main/compose/common/hadoop.conf
hadoop-ozone/dist/src/main/compose/ozonesecure-mr/.env
hadoop-ozone/dist/src/main/compose/ozonesecure-mr/docker-compose.yaml
hadoop-ozone/dist/src/main/compose/ozonesecure-mr/docker-config
hadoop-ozone/dist/src/main/compose/ozonesecure-mr/test.sh

Hadoop compatibility tests are run for versions [2.7, 3.1, 3.2, 3.3](https://github.com/apache/ozone/blob/0b377f7620b4795031a517a7d5a48c5995210d35/hadoop-ozone/dist/src/main/compose/common/hadoop-test.sh#L36) in [unsecure environment](https://github.com/apache/ozone/blob/0b377f7620b4795031a517a7d5a48c5995210d35/hadoop-ozone/dist/src/main/compose/ozone/test-hadoop.sh#L26), and for [3.3 in secure one](https://github.com/apache/ozone/blob/0b377f7620b4795031a517a7d5a48c5995210d35/hadoop-ozone/dist/src/main/compose/ozonesecure-mr/.env#L19).  However, part of the version-specific code is related to security.  Therefore, we should also test secure environment with all supported Hadoop versions.
This PR changes `ozonesecure-mr` to execute the tests using all 4 versions.
Note that with Hadoop …

HDDS-9583. Test Hadoop compatibility in secure environment with all supported versions

---

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockOutputStreamEntry.java
hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MockXceiverClientFactory.java

Fix intermittent failures in `testPartialStripeWithPartialChunkRetry`:
```
IndexOutOfBoundsException: Index: -1
at java.util.Collections$EmptyList.get(Collections.java:4456)
at java.util.Collections$UnmodifiableList.get(Collections.java:1311)
at org.apache.hadoop.ozone.client.io.ECBlockOutputStreamEntry.calculateChecksum(ECBlockOutputStreamEntry.java:416)
at org.apache.hadoop.ozone.client.io.ECKeyOutputStream.commitStripeWrite(ECKeyOutputStream.java:266)
at org.apache.hadoop.ozone.client.io.ECKeyOutputStream.flushStripeToDatanodes(ECKeyOutputStream.java:585)
at org.apache.hadoop.ozone.client.io.ECKeyOutputStream.flushStripeFromQueue(ECKeyOutputStream.java:567)
```
and
```
NullPointerException
at org.apache.hadoop.ozone.client.io.ECBlockOutputStreamEntry.calculateChecksum(ECBlockOutputStrea …
```

HDDS-9659. Intermittent failure in TestOzoneECClient#testPartialStripeWithPartialChunkRetry

---

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/ContainerTestUtils.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCreatePipelineCommandHandler.java

* This test used `PowerMockRunner` from junit4 making it harder to migrate.
* As part of a larger effort to migrate tests to JUnit5, and due to some test cases being harder than other this pr aims at migrating one such test case from the container-service module to JUnit5. 
[HDDS-9495. Migrate TestCreatePipelineCommandHandler to JUnit5](https://issues.apache.org/jira/browse/HDDS-9495)
Run locally and there is a green CI run here:
https://github.com/Galsza/ozone/actions/runs/6866136015

HDDS-9495. Migrate TestCreatePipelineCommandHandler to JUnit5

---

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/TestHddsSecureDatanodeInit.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestContainerCache.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestDatanodeStoreCache.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestSchemaTwoBackwardsCompatibility.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/helpers/TestBlockData.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/helpers/TestDatanodeVersionFile.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/interfaces/TestHandler.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/report/TestReportPublisherFactory.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCreatePipelineCommandHandler.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestDeleteContainerCommandHandler.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/utils/TestDiskCheckUtil.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/utils/TestHddsVolumeUtil.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/utils/TestStorageVolumeUtil.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestDbVolume.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestHddsVolume.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestPeriodicVolumeChecker.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestReservedVolumeSpace.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestVolumeSet.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestVolumeSetDiskChecks.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/ContainerLayoutTestInfo.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerIntegrityChecks.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/impl/TestKeyValueStreamDataChannel.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestSimpleContainerDownloader.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/upgrade/TestDataNodeStartupSlvLessThanMlv.java

As part of a larger process, tests are migrated from JUnit 4 to JUnit 5. In this pull request I'm migrating the simpler test cases. The remainder of the cases will be covered in later pull requests.
[HDDS-8988 Migrate simple tests in hdds-container-service to JUnit5](https://issues.apache.org/jira/browse/HDDS-8988)
Run all tests locally as well as seeing a green CI run here:
https://github.com/Galsza/ozone/actions/runs/6866863226

HDDS-8988. Migrate simple tests in hdds-container-service to JUnit5

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/endpoint/HeartbeatEndpointTask.java

When a heartbeat request occurs on the datanode, some redundant symbols are found in the log. The purpose of this PR is to optimize it.
`
2023-11-15 12:57:37,450 [EndpointStateMachine task thread for xxxx.xxxx.xxxx.xxxx/xxx.xxx.xxx.xxx:9861 - 0 ] DEBUG org.apache.hadoop.ozone.container.common.states.endpoint.HeartbeatEndpointTask: Sending heartbeat message :: datanodeDetails {
`
Details: HDDS-9694
https://issues.apache.org/jira/browse/HDDS-9694
Just make sure that the existing unit tests are normal.

HDDS-9694. Delete redundant symbols in the datanode heartbeat report log

---

.github/workflows/ci.yml
.github/workflows/post-commit.yml

dependabot pushes dependency version bumps to the main repo instead of its own fork.  It then creates a pull request without waiting for the `push` workflow to succeed.  Thus both workflows test the same state of code, which is unnecessary.
I propose completely skipping `push` build for dependabot's changes to save CI resources.
https://issues.apache.org/jira/browse/HDDS-9698
Build skipped in branch `dependabot-HDDS-9698` in my fork:
https://github.com/adoroszlai/ozone/actions/runs/6876171772
but ran normally in branch `HDDS-9698`:
https://github.com/adoroszlai/ozone/actions/runs/6876180867
as well as for PR created from branch `dependabot-HDDS-9698`:
https://github.com/adoroszlai/ozone/actions/runs/6876212003

HDDS-9698. Skip push build for dependabot

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/RootCaRotationPoller.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/TestRootCaRotationPoller.java

Fix the failure in TestRootCaRotationPoller arising from multi threaded execution
Sometimes the test cases were failing because `CompletableFuture.supplyAsync()` wasn't finishing before assertions were made for its results. Now 2 test cases avoid using the future at all, the third one is refactored so that it can wait for its result.
There is also a small refactor regarding pollRootCas, its visibility is changed so that it can be called directly from the test instead of relying on the run method that would introduce another point of possible sync issue via the executorService scheduling.
And finally pollRootCas now returns weather it found new certificates. Also added some logging in the success scenario.
The error `Exception in thread …

HDDS-9548. Intermittent failures in TestRootCaRotationPoller

---

hadoop-ozone/common/pom.xml
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/GrpcOmTransport.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/grpc/ClientAddressClientInterceptor.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/grpc/ClientAddressServerInterceptor.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/grpc/GrpcClientConstants.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/grpc/package-info.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/protocolPB/grpc/TestClientAddressClientInterceptor.java
hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/protocolPB/grpc/TestClientAddressServerInterceptor.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/GrpcOzoneManagerServer.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataReader.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/OMClientRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOMMetadataReader.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/OMRequestTestUtils.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/TestOMClientRequestWithUserInfo.java

A lot of code pieces in OM proto method handlers use OMClientRequest.preExecute method to define/detect userInfo for consequent ACLs checks. But if the provided client hostname is null (in case of GRPC transport) the user will be replaced by an 'om' one and the consequent ACLs check through a custom authorizer (e.g. Ranger) will fail due to non-existent permission policies for the 'om' user.
So, the PR introduces a new client&server interceptor to send/receive header with the client IP and hostname and uses it in GrpcOmTransport
https://issues.apache.org/jira/browse/HDDS-9663
1 unit test to check that userInfo has hostname and IP in case of GRPC transport (ozone-manager)
2 unit tests to check that client and server interceptors set and read client IP and hostname to/from the GRPC request …

HDDS-9663. Allow OM to detect client address when using gRPC

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java

To reproduce, run `TestSecureContainerServer.testClientServerRatisGrpc()` (although it will pass) and then search NPE in the log.
```java
Caused by: java.lang.NullPointerException
at org.apache.hadoop.ozone.container.common.transport.server.ratis.XceiverServerRatis.triggerPipelineClose(XceiverServerRatis.java:715)
at org.apache.hadoop.ozone.container.common.transport.server.ratis.XceiverServerRatis.handleApplyTransactionFailure(XceiverServerRatis.java:842)
at org.apache.hadoop.ozone.container.common.transport.server.ratis.ContainerStateMachine.lambda$applyTransaction$11(ContainerStateMachine.java:968)
at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
```
HDDS-9720
Run `TestSecureContainerServer.testClientServerRatisGrpc()` and search NPE.

HDDS-9720. XceiverServerRatis.triggerPipelineClose throws NPE.

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeConfiguration.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/TestDatanodeConfiguration.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestDeleteBlocksCommandHandler.java

When DeleteCmdWorker is running, it will execute the delete command every 2 seconds. Currently, this time is fixed. The interval here should be changeable, which is good for system scalability.
Details: HDDS-9696
https://issues.apache.org/jira/browse/HDDS-9696
If you specify a new interval, it must take effect.

HDDS-9696. Add configuration for wait time after checking queue in DeleteCmdWorker

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/DispatcherContext.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/ChunkManagerDummyImpl.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/FilePerChunkStrategy.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/ContainerTestUtils.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerPersistence.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestHddsDispatcher.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/server/TestSecureContainerServer.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/ChunkManagerDiskWrite.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/containergenerator/GeneratorDatanode.java

In ContainerStateMachine, the startTransaction(..) method has already validated the token. The applyTransaction(..) should not validate the same token again.
A problem is that the token may expire later on. Then, a server may not be able to re-apply the same transaction when replaying the RaftLog after server restart.
HDDS-9697
New unit test.

HDDS-9697. ContainerStateMachine.applyTransaction(..) should not validate token again.

---

hadoop-ozone/dist/src/shell/ozone/ozone

**What changes were proposed in this pull request?**
Reverting the change for now.
**What is the link to the Apache JIRA**
https://issues.apache.org/jira/browse/HDDS-9078

Revert "HDDS-9078. Set ratis.thirdparty.io.netty.native.workdir as OZONE home temp directory"

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotFileSystem.java

There are two tasks asked in [HDDS-8201](https://issues.apache.org/jira/browse/HDDS-8201). In #5518, TestOmSnapshotFileSystem tests were migrated to JUnit-5. This change is to address the second task and make some remaining tasks Snapshot delete aware. 
https://issues.apache.org/jira/browse/HDDS-8201
Workflow run on fork: https://github.com/hemantk-12/ozone/actions/runs/6872953402/job/18692239021

HDDS-8201. Added snapshot delete in all tests of TestOmSnapshotFileSystem

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/AbstractKeyDeletingService.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/KeyDeletingService.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestKeyDeletingService.java

When KeyDeletingService is running, the logs recorded are not enough. The purpose of this PR is to be as complete as possible. This is useful for understanding what happened when the key/file was deleted, and can provide some clues as to when the failure occurred.
Here are some logs from the run:
`
2023-11-18 23:26:35,908 [om1-KeyDeletingService#0] DEBUG utils.BackgroundService (AbstractKeyDeletingService.java:processKeyDeletes(108)) - Keys sent to SCM: [BlockGroup[groupID='/volume91iZP/bucketNsfJE/keyy3kmt/-9223372036854772480', blockIDs=[conID: 638262276 locID: 638262276 bcsId: 0]], BlockGroup[groupID='/volumeDK8cR/bucketE4OTF/keyzb2Ty/-9223372036854763264', blockIDs=[conID: 638262316 locID: 638262316 bcsId: 0]], BlockGroup[groupID='/volumeWCaz8/bucketSAWVY/keyrUoAc/-9223372036854764800' …

HDDS-9722. Add some logging when KeyDeletingService is running

---

hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedBloomFilter.java
hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedCheckpoint.java
hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedColumnFamilyOptions.java
hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedCompactRangeOptions.java
hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedDBOptions.java
hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedEnvOptions.java
hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedFlushOptions.java
hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedIngestExternalFileOptions.java
hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedLRUCache.java
hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedObject.java
hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedOptions.java
hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedReadOptions.java
hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedRocksDB.java
hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedRocksObjectUtils.java
hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedSlice.java
hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedSstFileWriter.java
hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedStatistics.java
hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedWriteBatch.java
hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedWriteOptions.java

Managed RocksDB objects have optional leak detection (enabled in integration tests).  Objects that extend `ManagedObject` report leak with stack trace, but most other types lack this detail, making it more difficult to find the source of the leak:
```
[Finalizer] WARN  managed.ManagedRocksObjectUtils (ManagedRocksObjectUtils.java:reportLeak(71)) - ManagedWriteBatch is not closed properly
```
This change improves it by adding stack trace information for these objects.
https://issues.apache.org/jira/browse/HDDS-9724
Applied the patch on top of https://github.com/devmadhuu/ozone/commit/81fb066918893cea15e4f49bb1af71d7d971cde6, which was not closing `RDBBatchOperation`.  Ran `TestReconTasks`, checked log for stack trace:
```
[Finalizer] WARN  managed.ManagedRocksObjectUtils …
```

HDDS-9724. Provide stack trace for RocksObject allocation

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/CodecBuffer.java

Fix `Return value of ... ignored, but method has no side effect` warnings in `CodecBuffer`.
Examples:
https://github.com/vtutrinov/ozone/actions/runs/6655766005/job/18086771096#step:7:11
https://github.com/xichen01/ozone/actions/runs/6925852588/job/18837148517#step:7:11
The methods being called do have side effects, they return the same buffer only for convenience.  `CodecBuffer.buf` is `final`, we cannot update it to the buffer returned even if it's another instance.
`assertSame` call is added to make use of the return value, and also to alert if the implementation is changed to return any other instance.
https://issues.apache.org/jira/browse/HDDS-9731
* Checked out https://github.com/xichen01/ozone/commit/1589e17d0ab64d12064050c73a75bfba52b62132
* Ran `findbugs.sh` locally to reproduce …

HDDS-9731. Fix false positive findbugs warnings in CodecBuffer

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineClose.java

Replace Thread.sleep in TestPipelineClose#testPipelineCloseWithPipelineAction with a conditional wait.
HDDS-9713
This is a unit test change

HDDS-9713. Replace Thread.sleep in TestPipelineClose.

---

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/container/InfoSubcommand.java
hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/container/TestInfoSubCommand.java

For closed containers, the pipeline ID keeps on changing on every request, it's randomly generating everytime we execute the container info command. To address this issue we directly fetch the pipeline ID from scm client via container info and display it in the implementation of container info command instead of displaying the random pipeline ID assigned during the creation of pipeline when container are closed.
https://issues.apache.org/jira/browse/HDDS-9544
Output:
When the container is open,
``` bash
[root@ozone-ozone-1 ~]# ozone admin container info 2003
Container id: 2003
Pipeline id: 063c7d82-dba0-4cf6-95ed-b40fa84196fa
Write PipelineId: 063c7d82-dba0-4cf6-95ed-b40fa84196fa
Write Pipeline State: OPEN
Container State: OPEN
Datanodes: …
```

HDDS-9544. Incorrect pipeline ID and state for closed container.

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SnapshotChainManager.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotCreateRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestSnapshotChain.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotPurgeRequestAndResponse.java

As fix of HDDS-9199, exceptions in snapshot chain creation were changed IllegalStateException. We have seen couple of issues with this as in HDDS-9685 and HDDS-9745.
This change is to change unchecked `IllegalStateException` to checked `IOException` so that OM state machine can handle the exception properly and doesn't crash the system.
[HDDS-9745](https://issues.apache.org/jira/browse/HDDS-9745)
Updated unit and integration tests.

HDDS-9745. Change IllegalStateException to IOException in SnapshotChainManager

---

pom.xml

After HDDS-9741 upgraded Surefire from 3.0.0-M5 to 3.2.2, trying to run specific tests by setting `-Dtest` in the CLI fails with `No tests matching pattern "..." were executed`.
Example:
```
$ mvn -am -pl :hdds-server-scm -Dtest='TestBlockManager' clean test
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.2:test (default-test) on project hdds-annotation-processing: No tests matching pattern "TestBlockManager" were executed! (Set -Dsurefire.failIfNoSpecifiedTests=false to ignore this error.) 
```
The problem is that the default value of [`failIfNoSpecifiedTests`](https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#failIfNoSpecifiedTests) was changed to `true` in 3.0.0-M6 by [SUREFIRE-1910](https://issues.apache.org/jira/browse/SUREFIR …

HDDS-9757. Cannot run specific test due to failIfNoSpecifiedTests=true

---

hadoop-ozone/ozonefs-common/pom.xml
hadoop-ozone/ozonefs-common/src/test/java/org/apache/hadoop/fs/ozone/TestBasicOzoneFileSystems.java
hadoop-ozone/ozonefs-common/src/test/java/org/apache/hadoop/fs/ozone/TestOFSPath.java
hadoop-ozone/ozonefs-common/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneClientUtils.java
hadoop-ozone/ozonefs-common/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFSInputStream.java
hadoop-ozone/ozonefs-common/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsShell.java

HDDS-9502. Migrate tests in ozonefs-common to JUnit5
Migrating all the tests under ozonefs-common to Junit5 and making sure that Junit4 is not used in any of the tests. This PR also migrates the parametrized tests under ozonefs-common to junit5.
Tested that using grep -rlE "org.junit.[A-Z]" . --include '*.java' command in hadoop-ozone/ozonefs-common folder
https://issues.apache.org/jira/browse/HDDS-9502
This PR was tested by running the full CI - https://github.com/VarshaRaviCV/ozone/actions/runs/6942165040

HDDS-9502. Migrate tests in ozonefs-common to JUnit5

---

hadoop-hdds/server-scm/src/main/resources/webapps/scm/scm-overview.html
hadoop-hdds/server-scm/src/main/resources/webapps/scm/scm.js

If there are both HTTP and HTTPS port present in the NodeStatusInfo object in the JMX of SCM, then the JS code should select the port that belongs the protocol via which the SCM webUI is being rendered. Currently the selection relies on the order of the keys in a structure that most likely contains both ports, and is completely ad-hoc.
So in order to provide a functionality with the least astonishment, the new logic follows these guidelines:
- if SCM webUI is rendered over https, then it should display http links to DNs, while if it is rendered over https it should display https links to DNs.
- if SCM webUID is rendered http, but DN has only https port defined or vice versa then fallback to the available protocol.
- In case the DN does not expose neither HTTP nor HTTPS port (which would …

HDDS-9732. SCM WebUI incorrectly renders DN links

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAWithAllRunning.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAWithStoppedNodes.java

This PR addresses the timing/sync issue between two separate indexes:
```
lastAppliedTermIndex -- committed index where apply transaction is completed
Ratis snapshot index for OM -  its from DB which represent last index present in DB, and when snapshot is taken, it takes this DB one
```
Both indexes are mostly same however due to DoubleBuffer, these 2 indexes may give different values sometimes with fraction of time difference when these two called upon.
https://issues.apache.org/jira/browse/HDDS-9706
This patch is tested by running multiple splits and iterations. Here is the green CI [link](https://github.com/devmadhuu/ozone/actions/runs/6931437125/job/18876158682) with 3 job runs repeatedly on the patch in different test branch.

HDDS-9706. Intermittent failure in TestOzoneManagerHAWithStoppedNodes#testOMRatisSnapshot.

---

hadoop-ozone/dist/src/main/compose/common/hadoop-test.sh
pom.xml

* Upgrade Ozone's Hadoop2 dependency to 2.10.2.
* Use `apache/hadoop` docker image for testing this version (no `flokkr/hadoop` image available).
* Drop 3.2.2 from versions being tested.
Related discussion on mailing list:
https://lists.apache.org/thread/q99x4f93yk20z6m8wsqpvwms1vqw030l
https://issues.apache.org/jira/browse/HDDS-9699
CI:
https://github.com/adoroszlai/ozone/actions/runs/6878591140/job/18712121667#step:5:151

HDDS-9699. Upgrade Hadoop2 to latest 2.10.2

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmStartupSlvLessThanMlv.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerListVolumesSecure.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerRatisRequest.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/service/TestRangerBGSyncService.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconAsPassiveScm.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconTasks.java

Migrated following integration tests with TemporaryFolder to JUnit5.
```
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmStartupSlvLessThanMlv.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerListVolumesSecure.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerRatisRequest.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/service/TestRangerBGSyncService.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconAsPassiveScm.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconTasks.java
```
https://issues.apache.org/jira/browse/HDDS-9505
CI/CD run on fork: …

HDDS-9505. Migrated integration tests with TemporaryFolder to JUnit5

---

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconUtils.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/ContainerSizeCountTask.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/TestReconUtils.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestContainerSizeCountTask.java

Fix the following method which does not work for 
- negative number (infinite loop), and
- positive power of two (incorrect value).
```java
//ReconUtils
private static int nextClosestPowerIndexOfTwo(long dataSize) {
int index = 0;
while (dataSize != 0) {
dataSize >>= 1;
index += 1;
}
return index;
}
```
HDDS-9749
Added a new test.

HDDS-9749. Infinite loop in ReconUtils.nextClosestPowerIndexOfTwo().

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisOverReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisUnderReplicationHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManagerUtil.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestLegacyReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisOverReplicationHandler.java

https://issues.apache.org/jira/browse/HDDS-9352 makes changes in the algorithm used for saving `UNHEALTHY` replicas with unique origins for a `QUASI_CLOSED` container in Legacy Replication Manager. This PR makes similar changes to `RatisOverReplicationHandler` for the new RM. Basically, any Datanodes not in-service, healthy should not be considered when finding replicas with unique origin datanode id, because these datanodes are likely going away soon or gone already. 
Also refactored duplicated logic to one place and added some logs.
https://issues.apache.org/jira/browse/HDDS-9353
Modified unit tests.

HDDS-9353. ReplicationManager: Ignore any Datanodes that are not in-service and healthy when finding unique origins

---

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/container/InfoSubcommand.java
hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/container/TestInfoSubCommand.java

Currently the command:
ozone admin container info 1234
Only accepts a single container ID. If you need to list the details from many containers, then the JVM startup overhead makes the command very slow.
This Jira changes the behavior so you can pass multiple containers at the same time, eg:
```
ozone admin container info 1 2 456 789
```
Additionally, you can pass the container list over stdin, with 1 containerID per line. To do that, you pass the container id as a dash character:
```
ozone admin container info - < containerList
```
When passing multiple containers, if a container is not found or is an invalid ID, and error is printed to stdout and the command will continue with the next ID in the list.
If containers are being read from stdin, or multiple IDs are specified on the command …

HDDS-9700. Allow ozone admin container info to list multiple containers

---

hadoop-hdds/server-scm/src/main/resources/webapps/scm/scm-overview.html
hadoop-hdds/server-scm/src/main/resources/webapps/scm/scm.js

If there are hundreds of Datanodes, it is difficult to browse the situation and view the number of Datanodes.
In the SCM UI, I need to check how many datanodes there are, so here I need to display the number of records of the datanodes and be able to jump to the specified page during pagination.
https://issues.apache.org/jira/browse/HDDS-9726
Only all unit test.
https://github.com/aierate/ozone/actions/runs/6938742317
Here is UI screenshot.

HDDS-9726. Add page jump function and entity count display to the Node Status section of the SCM UI.

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockInputStream.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ChunkInputStream.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/DummyBlockInputStream.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/DummyBlockInputStreamWithRetry.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/DummyChunkInputStream.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestBlockInputStream.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestChunkInputStream.java

`BlockInputStream` updates block token if it experiences an exception reading a chunk (implemented in HDDS-7930).  However, `ChunkInputStream` keeps using the initial token, so read still fails.
This PR changes it to use the latest token fetched by `BlockInputStream`.
Both this PR and #5655 are changing `TestChunkInputStream`.  To avoid conflicts, this PR includes @hemantk-12's change for this single test as a separate commit.
https://issues.apache.org/jira/browse/HDDS-9734
Added assertion in existing unit test.
CI:
https://github.com/adoroszlai/ozone/actions/runs/6961769568

HDDS-9734. ChunkInputStream should use new token after pipeline refresh

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java

Currently `TestOMRatisSnapshots` is disabled, because it cannot completely pass even with retries, even after increasing timeouts.
After testing various methods separately, it seems only `testInstallIncrementalSnapshotWithFailure` is flaky, and even in that method, only metrics-related assertions.
So this PR:
* enables `TestOMRatisSnapshots`
* increases timeout of all `waitFor` checks
* disables 3 metrics-related checks in `testInstallIncrementalSnapshotWithFailure`
https://issues.apache.org/jira/browse/HDDS-8876
Passed 10x10 for commit https://github.com/adoroszlai/ozone/commits/163958ae0ea2c2df46136d404bfbd5939c9532b6:
https://github.com/adoroszlai/ozone/actions/runs/6994739107
which has the same content as this PR:
https://github.com/adoroszlai/ozone/compare/163958ae0ea2c2df46136d404bfb …

HDDS-8876. Enable TestOMRatisSnapshots, increase timeouts, disable flaky assertions

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/RatisReplicationCheckHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestRatisReplicationCheckHandler.java

If a quasi closed container has replicas that are hosted by nodes with unique origins, then don't count them as over replicated because they're all needed.
This change is replicating the change to the Legacy Replication Manager made in [HDDS-9489](https://issues.apache.org/jira/browse/HDDS-9489)
https://issues.apache.org/jira/browse/HDDS-9593
New unit tests added

HDDS-9593. Replication Manager: Do not count unique origin nodes as over-replicated

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyRatisContainerReplicaCount.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestLegacyReplicationManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestDatanodeAdminMonitor.java

The initial problem was that `LegacyReplicationManager` was not considering that `UNHEALTHY` replicas could be decommissioning or entering maintenance. So, its logic for determining whether a container with all `UNHEALTHY` replicas is under replicated was flawed. This was fixed in [HDDS-9652](https://issues.apache.org/jira/browse/HDDS-9652). The fix simply used existing logic in `RatisContainerReplicaCount` that is able to account for decommissioning `UNHEALTHY` replicas. However this didn't completely fix the problem because `DatanodeAdminMonitorImpl` also needs to be updated. The reason it needs to be updated is that `RatisContainerReplicaCount` (extended by `LegacyRatisContainerReplicaCount`, exclusively used by the legacy replication manager) is the interface between the replication …

HDDS-9737. Legacy Replication Manager should consider that UNHEALTHY replicas might be decommissioning

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileInterfaces.java

This PR is just to enable `TestOzoneFileInterfaces.testOzoneManagerLocatedFileStatusBlockOffsetsWithMultiBlockFile`  by removing `@Unhealthy` annotation, as this is not reproducible and would like to see if it fails in recent master branch code. This flaky test JIRA is quite old and may have been fixed already.
https://issues.apache.org/jira/browse/HDDS-3506
This patch was tested by running repeated CI run for `TestOzoneFileInterfaces.testOzoneManagerLocatedFileStatusBlockOffsetsWithMultiBlockFile` using flaky workflow. Here is the green CI [link](https://github.com/devmadhuu/ozone/actions/runs/7000915449)

HDDS-3506. Enable TestOzoneFileInterfaces#testOzoneManagerLocatedFileStatusBlockOffsetsWithMultiBlockFile

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/server/TestContainerServer.java

This PR is to allow running test cases of `TestContainerServer` class, as they were marked `slow` and some `unhealthy`.  In earlier written test case, some of the inputs to `testClientServerWithContainerDispatcher` like volumeSet and config like `hdds.datanode.dir` were not set correctly due to which the test was failing and it was failing after running and retrying for more than 2 mins. This PR has improved that corrected the test case.
https://issues.apache.org/jira/browse/HDDS-3438
Since this PR is to allow and enable running of test cases of `TestContainerServer` class, the test class has been tested using running multiple times and it passed successfully without any significant delay.

HDDS-3438. Fix and enable TestContainerServer#testClientServerWithContainerDispatcher

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotFileSystemFso.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotFileSystemLegacy.java

[HDDS-8201](https://issues.apache.org/jira/browse/HDDS-8201) migrated parameterized JUnit4 TestOmSnapshotFileSystem to JUnit5 by creating two subclasses. These are not executed, unless explicitly specified by -Dtest.
This change is to convert the nested subclasses TestOmSnapshotFileSystemFso and TestOmSnapshotFileSystemLegacy to top-level so that they run in CI workflow.
Note: I thought about creating buckets in @BeforeAll but FileSystem is setup based on bucket name. If create bucket in @BeforeAll we have to create and clean up two FileSystem clients. I think having subclasses is cleaner approach so implemented that.
https://issues.apache.org/jira/browse/HDDS-9773
Verified that TestOmSnapshotFileSystemFso and TestOmSnapshotFileSystemLegacy ran in forkCI run: …

HDDS-9773. Fix to run TestOmSnapshotFileSystem in CI workflow

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/upgrade/AbstractLayoutVersionManager.java
hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/upgrade/TestAbstractLayoutVersionManager.java

If there is a restart during or immediately after SCM upgrade finalization, the `FinalizationStateManager#finalizeLayoutFeature` Ratis call will be re-executed while Raft log is re-applied during restart.
This will cause the SCM to crash if `FinalizationStateManager#finalizeLayoutFeature` call is not idempotent.
This PR modifies the behaviour of `AbstractLayoutVersionManager` to make `finalizeLayoutFeature` call idempotent.
HDDS-9769
Modified the existing unit test to verify the new behavior.

HDDS-9769. SCM's FinalizationStateManager#finalizeLayoutFeature Ratis call should be idempotent.

---

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/OzoneManagerServiceProviderImpl.java

Since Recon will fallback to full OM DB snapshot update in case failed to get incremental updates, but we don't need this below full trace rather a brief message with some important details is enough.
```
2023-10-18 23:09:01,152 WARN [pool-28-thread-1]-org.apache.hadoop.ozone.recon.spi.impl.OzoneManagerServiceProviderImpl: Unable to get and apply delta updates from OM.
INTERNAL_ERROR org.apache.hadoop.ozone.om.exceptions.OMException: Unable to read full data from RocksDB wal to get delta updates. It may have partially been flushed to SSTs. Requested sequence number is 69523 and first available sequence number is 224239 in wal.
at org.apache.hadoop.ozone.om.protocolPB.OzoneManagerProtocolClientSideTranslatorPB.handleError(OzoneManagerProtocolClientSideTranslatorPB.java:728)
at …
```

HDDS-9702. Improve logging when Recon gets a full update from OM

---

hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/upgrade/TestAbstractLayoutVersionManager.java

We should unregister MBean after test execution in `TestAbstractLayoutVersionManager`.
Not unregistering causes exception in the next test execution
```
2023-11-28 12:09:32,486 [main] INFO  upgrade.AbstractLayoutVersionManager (AbstractLayoutVersionManager.java:init(83)) - Initializing Layout version manager with metadata layout = org.apache.hadoop.ozone.upgrade.TestAbstractLayoutVersionManager$1@1e097d59 (version = 2), software layout = org.apache.hadoop.ozone.upgrade.TestAbstractLayoutVersionManager$1@1e097d59 (version = 2)
2023-11-28 12:09:32,487 [main] WARN  util.MBeans (MBeans.java:getMBeanName(167)) - Error creating MBean object name: Hadoop:service=LayoutVersionManager,name=AbstractLayoutVersionManager$MockitoMock$718765086
org.apache.hadoop.metrics2.MetricsException: …
```

HDDS-9783. Unregister MBean after test execution in TestAbstractLayoutVersionManager.

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/recovery/ReconOmMetadataManagerImpl.java

Cache should be disabled for Snapshot rocksdb. Since no writes happen on snapshots and can be read from the rocksdb.
Enable partial cache for all tables for snapshot rocksDB
https://issues.apache.org/jira/browse/HDDS-9778

HDDS-9778. Disable rocksDB cache for snapshot

---

hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerDoubleBuffer.java

Since the background thread, `doubleBufferFlush`, flushes the double buffer every **1 second**, when we create a user, it would immediately flush the user to the double buffer, preventing us from verifying the values in the doubleBuffer and cache accurately. Therefore, we have added a trigger to stop it.
Earlier the following error was being thrown by the Test as an Intermittent failure :- 
https://github.com/adoroszlai/ozone-build-results/blob/master/2023/11/27/27054/unit/hadoop-ozone/ozone-manager/org.apache.hadoop.ozone.om.ratis.TestOzoneManagerDoubleBuffer.txt
```
Tests run: 8, Failures: 6, Errors: 0, Skipped: 0, Time elapsed: 10.18 s <<< FAILURE! -- in org.apache.hadoop.ozone.om.ratis.TestOzoneManagerDoubleBuffer
TestOzoneManagerDoubleBuffer.testS3SecretCacheSizePostDoubleBufferFlush …
```

HDDS-9780. Intermittent failure in testS3SecretCacheSizePostDoubleBufferFlush.

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/pipeline/Pipeline.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DeadNodeHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/HealthyReadOnlyNodeHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/StaleNodeHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/StartDatanodeAdminHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineActionHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManager.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerImpl.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/MockPipelineManager.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineActionHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestNode2PipelineMap.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineClose.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachine.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineFailures.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineFlushDelay.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientRetriesOnExceptionFlushDelay.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientRetriesOnExceptions.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestWatchForCommit.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconAsPassiveScm.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/node/TestDecommissionAndMaintenance.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/pipeline/TestSCMPipelineMetrics.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconPipelineManager.java

Whenever we close a pipeline, we have an option to give some grace time for the container to get closed, the grace time is configured using `ozone.scm.pipeline.destroy.timeout`.
We wait for the timeout to happen before we go ahead and delete the pipeline. This will give enough time for the datanodes to close the container gracefully.
It will prevent the containers from moving to the `QUASI_CLOSED` state.
This functionality is broken and we don't wait for the timeout to happen before we delete the Pipeline. This creates a lot of `QUASI_CLOSED` containers in the cluster when a node goes stale or when a datanode is getting decommissioned.
This has to be fixed and we should wait for the configured amount of time before we delete the Pipeline, this will give datanodes enough time to `CLOSE` …

HDDS-9479. Pipeline close doesn't wait for containers to be closed.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisOverReplicationHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisOverReplicationHandler.java

```
if (allUnhealthy) {
// prefer deleting replicas with lower sequence IDs
return replicas.stream()
.sorted(Comparator.comparingLong(ContainerReplica::getSequenceId)
.reversed())
.collect(Collectors.toList());
}
```
This should actually be the opposite, allowing lower sequence IDs to be deleted first. If all sequence IDs are the same, we should have a secondary sort based on the containerReplica hashCode, which is already used for healthy replicas.
https://issues.apache.org/jira/browse/HDDS-9747
New unit tests added to reproduce the issue and validate the fix.

HDDS-9747. Incorrect sorting order for all unhealthy replicas in RatisOverReplicationHandler

---

hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/upgrade/TestAbstractLayoutVersionManager.java
hadoop-ozone/insight/pom.xml
hadoop-ozone/insight/src/test/java/org/apache/hadoop/ozone/insight/TestBaseInsightPoint.java
hadoop-ozone/insight/src/test/java/org/apache/hadoop/ozone/insight/TestConfigurationSubCommand.java
hadoop-ozone/insight/src/test/java/org/apache/hadoop/ozone/insight/TestLogSubcommand.java
hadoop-ozone/interface-storage/pom.xml
hadoop-ozone/interface-storage/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmKeyInfoCodec.java
hadoop-ozone/interface-storage/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmMultipartKeyInfoCodec.java
hadoop-ozone/interface-storage/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmPrefixInfo.java
hadoop-ozone/interface-storage/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmPrefixInfoCodec.java
hadoop-ozone/interface-storage/src/test/java/org/apache/hadoop/ozone/om/helpers/TestRepeatedOmKeyInfoCodec.java
hadoop-ozone/interface-storage/src/test/java/org/apache/hadoop/ozone/om/helpers/TestS3SecretValueCodec.java
hadoop-ozone/interface-storage/src/test/java/org/apache/hadoop/ozone/om/helpers/TestTransactionInfoCodec.java

Migrate the following test classes to JUnit5. See parent task for details.
hadoop-ozone/insight/src/test/java/org/apache/hadoop/ozone/insight/TestBaseInsightPoint.java
hadoop-ozone/insight/src/test/java/org/apache/hadoop/ozone/insight/TestConfigurationSubCommand.java
hadoop-ozone/insight/src/test/java/org/apache/hadoop/ozone/insight/TestLogSubcommand.java
hadoop-ozone/interface-storage/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmKeyInfoCodec.java
hadoop-ozone/interface-storage/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmMultipartKeyInfoCodec.java
hadoop-ozone/interface-storage/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmPrefixInfo.java
hadoop-ozone/interface-storage/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmPrefixInfoCodec.java …

HDDS-9501. Migrate misc. tests in hadoop-ozone to JUnit5

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOmSnapshot.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOmSnapshotFsoWithNativeLib.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOmSnapshotFsoWithoutNativeLib.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOmSnapshotLegacy.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOmSnapshotObjectStore.java

This change is to migrate TestOmSnapshot to Junit5. Currently we use Junit4 parameterize test and initialized cluster based on the bucket layout and some other parameter.
To migrate TestOmSnapshot to Junit5, we are using inheritance. Cluster setup and tests are defined in abstract class `TestOmSnapshot` and sub-classes initialize the super class with necessary parameters.
https://issues.apache.org/jira/browse/HDDS-9779
Verified that all the sub-classes ([TestOmSnapshotFsoWithoutNativeLib](https://github.com/hemantk-12/ozone/actions/runs/7023339913/job/19110596541#step:6:161), [TestOmSnapshotFsoWithoutNativeLib](https://github.com/hemantk-12/ozone/actions/runs/7023339913/job/19110596541#step:6:163), [TestOmSnapshotObjectStore](https://github.com/hemantk-12/ozone/actions/runs/7023339913/job/ …

HDDS-9779. Migrated TestOmSnapshot to Junit5

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineClose.java

The`TestPipelineClose#testPipelineCloseWithPipelineAction` only waits for 5 seconds before it timeout and fails. 
The `ozone.scm.pipeline.destroy.timeout` is set to 5 seconds in the test. So, SCM will send close pipeline command to Datanode only after 5 seconds and the datanode is not getting enough time to remove the pipeline.
It's good to increase the max wait time in test to at least 10 seconds.
HDDS-9801
Executed the test multiple times in local to make sure that the test consistently passes.

HDDS-9801. Increase the timeout in TestPipelineClose#testPipelineCloseWithPipelineAction.

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NetworkTopology.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NetworkTopologyImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMBlockProtocolServer.java

Currently `SCMBlockProtocolServer#sortDatanodes` has to create a new list just to cast all items (defined as `Node`) to `DatanodeDetails` (which implements `Node`).  This is necessary because `NetworkTopology` defines its return type too loosely.  We can fix that by using method-local type definition.
https://issues.apache.org/jira/browse/HDDS-9675
Refactoring, covered by existing build/test.
https://github.com/adoroszlai/ozone/actions/runs/7020414682

HDDS-9675. Eliminate unnecessary stream in SCMBlockProtocolServer#sortDatanodes

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestCommitWatcher.java

As provided the following exceptions have been thrown :- `AlreadyClosedException`, `ExecutionException`, `RaftRetryFailureException`, `NotLeaderException`. 
```
org.apache.hadoop.hdds.scm.storage.TestCommitWatcher.testReleaseBuffersOnException -- Time elapsed: 28.88 s <<< ERROR!
java.util.concurrent.ExecutionException: org.apache.ratis.protocol.exceptions.AlreadyClosedException: SlidingWindow$Client:client-2D6A59F17A72->RAFT is closed.
at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
at org.apache.hadoop.hdds.scm.storage.TestCommitWatcher.testReleaseBuffersOnException(TestCommitWatcher.java:301)
...
Caused by: org.apache.ratis.protocol.exceptions.AlreadyClosedException: …
```

HDDS-9766. Intermittent AlreadyClosedException in TestCommitWatcher.testReleaseBuffersOnException

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/snapshot/SnapshotDiffReportOzone.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOmSnapshot.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDiffManager.java

Currently, we print empty line if snapshot diff entry list is empty because continuation token more than the total diff entries. This change is to throw an IOException if continuation token for snapshot diff is more than the total diff entries. Also updated the response printing if DiffEntryList is empty.
https://issues.apache.org/jira/browse/HDDS-9360
Updated integ tests and also checked the response on docker.
```
sh-4.2$ ozone sh volume create vol1
sh-4.2$ ozone sh bucket create vol1/bucket1
sh-4.2$ ozone sh key put vol1/bucket1/key1 README.md
sh-4.2$ ozone sh snapshot create vol1/bucket1 snap1
sh-4.2$ ozone sh key put vol1/bucket1/key2 README.md
sh-4.2$ ozone sh key put vol1/bucket1/key3 README.md
sh-4.2$ ozone sh key put vol1/bucket1/key4 README.md
sh-4.2$ ozone sh key put …
```

HDDS-9360. Throw an IOException if continuation token for snapshot diff is more than the total diff entries

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/protocolPB/ScmBlockLocationProtocolClientSideTranslatorPB.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMBlockLocationFailoverProxyProvider.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/BlockManagerImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/SCMBlockDeletingService.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java

`XceiverServerRatis` creates `DatanodeRatisServerConfig` repeatedly for accessing individual properties.  It should create it only once and reuse.
Some other similar usage patterns are also fixed.
Ideally we should strive to pass these objects from fewer places, but that change would affect many classes, and cause conflict in other tasks in-progress.  Hence this change is limited in scope.
https://issues.apache.org/jira/browse/HDDS-9772
CI:
https://github.com/adoroszlai/ozone/actions/runs/7019067260

HDDS-9772. Avoid recreating typesafe config objects unnecessarily

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFSBucketLayout.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneCluster.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientWithKeyLatestVersion.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestReadRetries.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestChunkInputStream.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestInputStreamBase.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestKeyInputStream.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/TestContainerReplication.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainerWithTLS.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestSecureOzoneContainer.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/scanner/TestBackgroundContainerDataScannerIntegration.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/scanner/TestBackgroundContainerMetadataScannerIntegration.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/scanner/TestContainerScannerIntegrationAbstract.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/scanner/TestOnDemandContainerDataScannerIntegration.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/volume/TestDatanodeHddsVolumeFailureDetection.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestBucket.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMBucketLayoutUpgrade.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMUpgradeFinalization.java

Migrate the following test classes to JUnit5.
```
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFSBucketLayout.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientWithKeyLatestVersion.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestReadRetries.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestChunkInputStream.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestKeyInputStream.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/TestContainerReplication.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneCont …
```

HDDS-9504. Migrate some parameterized integration tests to JUnit5

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeAdminMonitorImpl.java

Currently only 5 under-replicated containers are logged on each pass of the DatanodeAdminMonitor. This impacts debugging, as multiple debugging iterations are needed to resolve all the problems.
This PR changes the default log limit to 1000, and also makes it configurable so it can be turned up or down as needed.
https://issues.apache.org/jira/browse/HDDS-9594
Manually inspected in a docker cluster.

HDDS-9594. Make the number of containers logged configurable in DatanodeAdminMonitorImpl

---

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/OMDBUpdatesHandler.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestOMDBUpdatesHandler.java

This PR fixes by omitting the event to be handled by Recon where a value in a table could be null for a key. Ideally this should not happen in Raft log sequence of events so this PR is trying to skip such event and log with WARNING and details of event like table, event key etc. This will address 2 issues along with update to javadoc for `processEvent` method code in`OMDBUpdatesHandler.java`
1. NPE will not be thrown while processing event (PUT, UPDATE, DELETE) in Recon task handler, if a event is having null value for a key.
2. Any inconsistency or issue identified later using above log message will be deeply analyzed why and on which table such key occurrence can happen on OM DB side.
https://issues.apache.org/jira/browse/HDDS-9530
This patch was tested using existing Junit tests as …

HDDS-9530. Recon - NPE in handling deleteKey event in NSSummaryFSO task.

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineActionHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineActionHandler.java

While processing `PipelineAction`, the `PipelineActionHandler` logs error message with exception trace if the current SCM is not leader.
Getting `NotLeaderException` is expected behaviour, `PipelineActionHandler` should not log error message or the exception trace in this case.
HDDS-9811
Additional unit test added

HDDS-9811. Follower SCM should not process Pipeline Action

---

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/TestDatanodeConfiguration.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/conf/DatanodeRatisServerConfig.java

Fix performance issues with DN
Detail:
https://issues.apache.org/jira/browse/HDDS-9784
https://issues.apache.org/jira/browse/HDDS-9784
existing test

HDDS-9784. Reduce default log.appender.wait-time.min to 0us in Datanode

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/ozone/audit/AuditLogger.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/ozone/audit/AuditMessage.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/BucketEndpoint.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/EndpointBase.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java

Implementation of lazy audit log message building by the `MessageSupplier`, which performs audit log building only when the log will be output.
```java
public void logWriteSuccess(AuditMessage.Builder msg) {
if (shouldLogAtDebug(msg)) {
this.logger.logIfEnabled(
FQCN, Level.DEBUG, WRITE_MARKER, msg::build, null);
} else {
this.logger.logIfEnabled(
FQCN, Level.INFO, WRITE_MARKER, msg::build, null);
}
}
```
`logIfEnabled`: 
```java
public interface ExtendedLogger extends L
ogger {
//...
/**
* Logs a message which is only to be constructed if the specified level is active.
*
* @param fqcn The fully qualified class name of the logger entry point, used to determine the caller class and
*            method when location information needs to be logged.
* @param level The logging Level to check. …
```

HDDS-9822. Format audit log message lazily

---

hadoop-ozone/dist/src/main/compose/upgrade/upgrades/non-rolling-upgrade/callbacks/1.3.0/callback.sh
hadoop-ozone/dist/src/main/compose/upgrade/upgrades/non-rolling-upgrade/callbacks/1.4.0/callback.sh
hadoop-ozone/dist/src/main/compose/upgrade/upgrades/non-rolling-upgrade/callbacks/common/callback.sh
hadoop-ozone/dist/src/main/compose/upgrade/upgrades/non-rolling-upgrade/driver.sh

Upgrade acceptance test runs the same Robot test files on different Ozone versions and in different states of the cluster. Robot test statistics (log.html) show the same suite name for each of these.
This change adds cluster state / version information to make these steps easier to understand.
https://issues.apache.org/jira/browse/HDDS-9744
Ran upgrade acceptance tests.  Robot test log.html attached to HDDS-9744 [before](https://issues.apache.org/jira/secure/attachment/13064868/before.html)/[after](https://issues.apache.org/jira/secure/attachment/13064867/after.html) the change.
CI:
https://github.com/adoroszlai/ozone/actions/runs/7051917960

HDDS-9744. Set descriptive title for upgrade Robot tests

---

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChunkBuffer.java
hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChunkBufferImplWithByteBufferList.java
hadoop-hdds/common/src/main/resources/ozone-default.xml
hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/common/TestChunkBufferImplWithByteBufferList.java
hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigurationSource.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/ChunkUtils.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/FilePerBlockStrategy.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/FilePerChunkStrategy.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/interfaces/BlockManager.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/helpers/TestChunkUtils.java

From @jojochuang 
> Running Impala TPC-DS which stresses Ozone DN read path.
> BufferUtils#assignByteBuffers stands out as one of the offender.
> We can experiment with MappedByteBuffer and see if it makes performance better.
HDDS-7117
New unit test.

HDDS-7117. Consider reading chunk files using MappedByteBuffer.

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManager.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/OzoneManagerServiceProviderImpl.java

This PR fixes the `isDBUpdateSuccess` flag being set at OzoneManger's `org.apache.hadoop.ozone.om.OzoneManager#getDBUpdates` API. This flag was being set at server side, but was not set at client layer in `org.apache.hadoop.ozone.om.protocolPB.OzoneManagerProtocolClientSideTranslatorPB#getDBUpdates`. Because of this, Recon didn't knkow about any DB updates failure at OM side and Recon was not able to recover by falling back on full snapshot OM DB update. 
One of the prominent use case found for OM DB update failure is the mis-match in sequence number between Recon OM
snapshot DB and OzoneManager OM active DB.
Since Recon sync with OM DB every 5-10 mins based on configured interval and if Recon OM snapshot DB  has higher sequence number than OM active DB last sequence number, then OM DB …

HDDS-9830. Propagate DBUpdateSuccess flag from OM response to client

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestListKeysWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileRequest.java

When `prefix` is passed with trailing slash in `getOMKeyInfoIfExists` still we are querying in `fileTable` and returning back the result. Instead this `prefix` is assumed to be checked only in directory table in this case. 
https://issues.apache.org/jira/browse/HDDS-9825
New integration test added.

HDDS-9825. Fix ListKeys trailing slash prefix issue.

---

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/HadoopFsGenerator.java

Add check to prevent invalid --path parameter in ozone freon dfsg command.
* It's a trivial change but took me several hours to troubleshoot so thought it's worth fixing.
https://issues.apache.org/jira/browse/HDDS-9804
Manually tested on a cluster.

HDDS-9804. ozone freon dfsg does not work with relative --path

---

hadoop-hdds/common/pom.xml
hadoop-hdds/common/src/main/java/org/apache/hadoop/util/UUIDUtil.java
hadoop-ozone/dist/src/main/license/bin/LICENSE.txt
hadoop-ozone/dist/src/main/license/jar-report.txt
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManagerServiceGrpc.java
pom.xml

Provide a method to get generated UUID as a bytes array and get rid of the fasterxml:java-uuid-generator dependency
* a new method was written to provide a generate UUID as a bytes array - org.apache.hadoop.util.UUIDUtil#randomUUIDBytes
* the org.apache.hadoop.util.UUIDUtil#randomUUID method was rewritten to use the method described above and a couple of private methods to compute the most and the least significant bits
https://issues.apache.org/jira/browse/HDDS-9849
manually

HDDS-9849. Improve UUID generator and get rid of java-uuid-generator dependency

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsHAURLs.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockDataStreamOutput.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStream.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStreamFlushDelay.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStreamWithFailures.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStreamWithFailuresFlushDelay.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestCloseContainerHandlingByClient.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientRetriesOnExceptionFlushDelay.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientRetriesOnExceptions.java

The following tests seem to create too many datanode and pipelines. We can change it to 5 datanodes and 3 pipelines. This will reduce the setup time and with fewer `datanodes` and `pipelines`, there's less likelihood of encountering resource contention and timing issues. Such issues can often lead to intermittent failures that are hard to reproduce and diagnose.
1. TestOzoneClientRetriesOnExceptions.java
2. TestBlockOutputStream.java
3. TestCloseContainerHandlingByClient.java
4. TestBlockOutputStreamFlushDelay.java
5. TestBlockDataStreamOutput.java
6. TestOzoneClientRetriesOnExceptionFlushDelay.java
7. TestBlockOutputStreamWithFailures.java
8. TestBlockOutputStreamWithFailuresFlushDelay.java
9. TestOzoneFsHAURLs.java
https://issues.apache.org/jira/browse/HDDS-9805
All the tests ran …

HDDS-9805. Reduce cluster size in integration tests.

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/HttpServer2.java
hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/Gateway.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/Freon.java

Specify a default temporary directory for HttpServer2 for 'ozone freon --server' command.
Essentially copy-pasted from HDDS-8253
https://issues.apache.org/jira/browse/HDDS-9483
Manually tested on a cluster.

HDDS-9483. ozone freon --server is broken by HDDS-6176.

---

hadoop-ozone/dist/src/main/compose/testlib.sh

Sometimes acceptance tests fail due to docker not being able to remove the network during teardown.  HDDS-7531 added retry, but it looks like it may fail on repeated attempts, too.
To find out why some container cannot be stopped, let's create stack dump of such containers if `docker-compose down` fails.
```
Removing network xcompat_default
error while removing network: network xcompat_default id 81e9a46c74c2487fbfe428b07f25da18f053e8410562334d2dc7a013e254cd33 has active endpoints
...
Failed to remove all docker containers in 3 attempts.
ERROR: Test execution of xcompat/test.sh is FAILED!!!!
```
https://issues.apache.org/jira/browse/HDDS-9875
Regular CI:
https://github.com/adoroszlai/ozone/actions/runs/7129082081
Tried to reproduce the original problem in 10 runs, but it did not happen: …

HDDS-9875. Create stack dump if cannot remove docker network

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java

Fix compile error caused by HDDS-9816 and HDDS-9303.
https://issues.apache.org/jira/browse/HDDS-9816
Compiled locally.

HDDS-9816. Addendum: fix compile error due to conflict with HDDS-9303

---

hadoop-ozone/dev-support/intellij/ozone-style.xml

As the [HDDS-3583](https://issues.apache.org/jira/browse/HDDS-3583) resolved, we should update the RIGHT_MARGIN to 120 for intellij meanwhile.
https://issues.apache.org/jira/browse/HDDS-9899
Intellij import this config file and open an editor to verify the right margin.

HDDS-9899. Update RIGHT_MARGIN to 120 for IntelliJ

---

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java
hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestTypedRDBTableStore.java

`TypedTable#iterator` will throw `NullPointerException` in any error scenario, which will hide the actual exception and make it hard to debug.
This PR changes the behavior of `TypedTable#iterator` to throw the real exception.
HDDS-9900
An additional unit test is added to cover the new behavior.

HDDS-9900. TypedTable#iterator throws NPE on any error if prefix is null

---

hadoop-hdds/client/pom.xml
hadoop-hdds/config/pom.xml
hadoop-hdds/container-service/pom.xml
hadoop-hdds/framework/pom.xml
hadoop-ozone/client/pom.xml
hadoop-ozone/common/pom.xml
hadoop-ozone/ozone-manager/pom.xml
hadoop-ozone/ozonefs-common/pom.xml
pom.xml

Bump JUnit5 and related dependencies to current latest version.
Switch to `junit-bom` to ensure consistent versions for all JUnit5 artifacts.
https://issues.apache.org/jira/browse/HDDS-9853
CI:
https://github.com/adoroszlai/ozone/actions/runs/7118343498

HDDS-9853. Bump JUnit5 to 5.10.1

---

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ContainerImporter.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestReplicationSupervisor.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/ClosedContainerReplicator.java

We are seeing NPE when replicating closed container using freon 
```
at org.apache.hadoop.ozone.container.replication.ContainerImporter.chooseNextVolume(ContainerImporter.java:146)
at org.apache.hadoop.ozone.container.replication.DownloadAndImportReplicator.replicate(DownloadAndImportReplicator.java:77)
at org.apache.hadoop.ozone.container.replication.ReplicationTask.runTask(ReplicationTask.java:122)
at org.apache.hadoop.ozone.container.replication.ReplicationSupervisor$TaskRunner.run(ReplicationSupervisor.java:359)
at org.apache.hadoop.ozone.freon.ClosedContainerReplicator.lambda$replicateContainer$1(ClosedContainerReplicator.java:224)
at com.codahale.metrics.Timer.time(Timer.java:101)
at org.apache.hadoop.ozone.freon.ClosedContainerReplicator.replicateConta …
```

HDDS-9896. Fix for NullPointerException when replicating closed container using freon

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/CloseContainerEventHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/IncrementalContainerReportHandler.java

HDDS-9888. Reduce log level for "not leader" log entries.
Reduced log level from warning to info for the messages logged on non-leader nodes to reduce the number of warning messages.
https://issues.apache.org/jira/browse/HDDS-9888
Manually checked log files.

HDDS-9888. Reduce log level for "not leader" log entries

---

pom.xml

* Bump `okhttp` to 4.12.0, `okio` to 3.6.0, `kotlin` to 1.9.21
* Use `kotlin-bom` to ensure consistent versions of various `org.jetbrains.kotlin` artifacts (they are also transitive dependency of `okhttp`)
https://issues.apache.org/jira/browse/HDDS-9850
CI:
https://github.com/adoroszlai/ozone/actions/runs/7112934454

HDDS-9850. Bump okhttp to 4.12.0, okio to 3.6.0, kotlin to 1.9.21

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotCache.java

When accessing the snapshot cache, Multiple threads fall into a deadlock between ConcurrentHashMap(`dbMap`) and SynchronizedSet(`pendingEvictionList`).
1. `dbMap.compute()` holds the ConcurrentHashMap lock while trying to hold the lock for `pendingEvictionList` Set.
2. `cleanup()` method holds the lock for `pendingEvictionList` Set while trying to hold the lock for the ConcurrentHashMap (`dbMap`).
```
"snapshot-diff-job-thread-id-8":
waiting to lock monitor 0x00007fa7964788d8 (object 0x00000006d658eed0, a java.util.Collections$SynchronizedSet),
which is held by "KeyDeletingService#0"
"KeyDeletingService#0":
waiting to lock monitor 0x0000000000e99e68 (object 0x00000006db6bcba8, a java.util.concurrent.ConcurrentHashMap$Node),
which is held by "SstFilteringService#0"
"SstFilteringService#0": …
```

HDDS-9871. [Snapshot] Fix Deadlock in SnapshotCache.

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java

In OmMetadataManagerImpl, there are some wrong symbols, the purpose of this PR is to fix them.
Details: HDDS-9890
https://issues.apache.org/jira/browse/HDDS-9890
This is a change related to documentation and does not require too much testing. Just keep the unit tests passing.

HDDS-9890. Fix comment typo in OmMetadataManagerImpl

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ListIterator.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneListStatusHelper.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmMetadataManager.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/OMRequestTestUtils.java

Snapshot list might be missing entries in the return list. Currently the list happens in a paginated fashion getting few snapshots at a time. Thus every page updates the previous value as the last entry in the previous page, helping the api to seek to the next snapshot directly. The problem is we form the listing by getting the first few entries from the cache and then the remaining entries from the table and return the concatenated list.
Consider the case:
TableCache has snap100...snap125
RocksDB Table has snap0...snap99
Now we want to list all snapshots from snap50 with maxPageSize of 30:
The expected list should be:
snap50 to snap80
But the current output is snap50 to snap54 ... snap100 to snap125 which is wrong. The next page would start from snap125, thus missing the snapshot 55 to …

HDDS-9710. Missing snapshot entries list Snapshot under a bucket API

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerHealthResult.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/ECReplicationCheckHandler.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeAdminMonitorImpl.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeDecommissionMetrics.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestECReplicationCheckHandler.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/DatanodeAdminMonitorTestUtil.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestDatanodeAdminMonitor.java
hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestNodeDecommissionMetrics.java

The logic in ReplicationManager is increasingly complex due to various edge cases around unhealthy and quasi-closed containers, and the differences between EC and Ratis.
It therefore makes sense for DatanodeAdminMonitor to call the new API replicationManager.checkContainerState and then check the report for under-replicated, rather than using the ReplicaCount objects. This means all the logic to decide about under-replication is confined to the replication manager.
In making this change, I needed to make a change in the EC under-replication handling where the container is unhealthy / unrecoverable but also has decommissioning indexes, as it was not being reported as under-replicated previously.
I also refactored the decommission monitor slightly to remove references to containers as …

HDDS-9902. Decommission: Admin monitor should call RM.checkContainerState to check for under-replication

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/TrashOzoneFileSystem.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/TrashPolicyOzone.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java

Improving hdfs perf by eliminating redundant config reads, and replacing them with a single one when the fs is initialized.
https://issues.apache.org/jira/browse/HDDS-9910
Current tests still apply.
Rename perf under spark improved by a factor of 5:
```
spark-shell --master local --conf spark.kerberos.access.hadoopFileSystems=ofs://vol1 --conf spark.ui.enabled=false --conf spark.port.maxRetries=64
// The following commands are all run from within the sparkshell
// init the fs
import org.apache.hadoop.fs.Path
val ozone_fs = org.apache.hadoop.fs.FileSystem.get(new java.net.URI("ofs://vol1/bdpe/squirrelfso"), sc.hadoopConfiguration)
ozone_fs.delete(new Path(s"ofs://vol1/bdpe/squirrelfso/file1/part10001"))
ozone_fs.copyFromLocalFile(new Path(s"/etc/hosts"), new …
```

HDDS-9910. Slow ozone hdfs performance when lots of config files.

---

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/snapshot/ListSnapshotHandler.java

List snapshot was implemented in HDDS-7507 but ListSnapshotHandler was not passing snapshot prefix and continuation token. Which was making list snapshot ozone shell to be non-paginated.
This change is to add `ListOptions` to `ListSnapshotHandler` and pass snapshot prefix and continuation token properly.
HDDS-9832
Tested it in docker.
After the change:
```
sh-4.2$ ozone sh snapshot ls --help
Usage: ozone sh snapshot list [-hV] [-p=<prefix>] [-s=<startItem>]
[[-l=<limit>] | [-a]] <value>
List snapshots for the buckets.
<value>               URI of the volume/bucket.
Ozone URI could either be a full URI or short URI.
Full URI should start with o3://, in case of non-HA
clusters it should be followed by the host name and
optionally the port number. In case of HA clusters
the service id should …
```

HDDS-9832. Updated ListSnapshotHandler to pass snapshot prefix and continuation token

---

.asf.yaml

Enable Github to Jira [autolink feature](https://cwiki.apache.org/confluence/pages/viewpage.action?spaceKey=INFRA&title=git+-+.asf.yaml+features#Git.asf.yamlfeatures-AutolinksforJira) for Hadoop and Ratis issues.  These projects are closely related, automatic linking makes references in PR descriptions easier.
https://issues.apache.org/jira/browse/HDDS-9917
Not tested, syntax taken from ASF doc and the `.asf.yaml` [file](https://github.com/apache/ozone-site/blob/177c30e0989032a6241caff2ed556c99599758f4/.asf.yaml#L24-L25) in `ozone-site` repo.

HDDS-9917. Autolink Hadoop and Ratis issues

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientManager.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestXceiverClientManager.java

clientCache in XceiverClientManager hold the client created in XceiverClientManager. Client in clientCache will be invalidated by two ways,
one is the explicitly call XceiverClientManager#releaseClient for this client,
another is when the client in clientCache is not accessed for a predefined period of time.
When XceiverClientManager#releaseClient is called, it will invalidate the client based on the constructed cache key, where it doesn't match the key constructed when client is put into clientCache when security is enabled.
https://issues.apache.org/jira/browse/HDDS-9893
unit test

HDDS-9893. Client in clientCache is not properly invalidated with security enabled

---

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMDirectoryCreateRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/file/TestOMDirectoryCreateRequest.java

Currently `ozone fs -mkdir` command doesn't throw an error message is key path starts with `.snapshot` and create `.snapshot` dir. `.snapshot` dir under bucket is reserved for snapshot and should not be allowed to be created using `ozone fs -mkdir` and `ozone sh`.
`ozone sh` throws an exception is key starts with `.snapshot` dir but `ozone fs` doesn't because it doesn't share the same code path to create key and file and dir can be create independently.
This change is to check dir name similar to key and file creation.
HDDS-9422
1. Added unit test.
2. Tested it on docker E2E.
```
sh-4.2$ ozone fs -mkdir -p ofs://om/vol1/bucket1/.snapshot/key1
mkdir: Cannot create key under path reserved for snapshot: .snapshot/
sh-4.2$
```

HDDS-9422. Return error response when trying to create a directory under .snapshot path

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileInterfaces.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemWithFSO.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystemWithFSO.java

Replace `Assert.assert...` with static import + `assert...` in the following files:
```
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileInterfaces.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileInterfacesWithFSO.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemWithFSO.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystemWithFSO.java
```
No other changes (e.g. no upgrade to JUnit5; no refactoring of assertions which could be …

HDDS-9920. Add static import for assertions in parameterized FS integration tests

---

.github/workflows/ci.yml

`hadoop-maven-plugins` has a [bug](https://issues.apache.org/jira/browse/HADOOP-19011) that causes intermittent `ConcurrentModificationException` in the `version-info` goal:
```
[INFO] --- hadoop-maven-plugins:3.3.6:version-info (version-info) @ hdds-common ---
[WARNING] [git, branch] failed with error code 128
[INFO] SCM: NONE
[INFO] Computed MD5: f7acef9f5512e5cf4e753b29d1490
...
[INFO] --- hadoop-maven-plugins:3.3.6:version-info (version-info) @ ozone-common ---
[WARNING] [git, branch] failed with error code 128
...
[INFO] BUILD FAILURE
...
[ERROR] Failed to execute goal org.apache.hadoop:hadoop-maven-plugins:3.3.6:version-info (version-info) on project ozone-common: java.util.ConcurrentModificationException
```
The problem can happen if the command returns with error.  In our case …

HDDS-9873. Intermittent failure at hadoop-maven-plugins in compile check

---

CONTRIBUTING.md

Line length limit was increased to 120 chars in PR #921 . So update CONTRIBUTING.md to reflect that.
https://issues.apache.org/jira/browse/HDDS-9923
Did a change in CONTRIBUTING.md and manually verified it

HDDS-9923. Update line length limit in CONTRIBUTING.md

---

hadoop-hdds/container-service/pom.xml
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestKeyValueContainerData.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestSchemaOneBackwardsCompatibility.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestStaleRecoveringContainerScrubbingService.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerDataYaml.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerDeletionChoosingPolicy.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerPersistence.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerSet.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestHddsDispatcher.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCloseContainerCommandHandler.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestDeleteBlocksCommandHandler.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestStorageVolumeChecker.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueBlockIterator.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerCheck.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerIntegrityChecks.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerMarkUnhealthy.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerMetadataInspector.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueHandler.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestTarContainerPacker.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/impl/TestBlockManagerImpl.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestContainerReader.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainer.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestReplicationSupervisor.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/upgrade/TestDatanodeUpgradeToSchemaV3.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/upgrade/TestDatanodeUpgradeToScmHA.java

Migrate parameterized tests in hdds-container-service to JUnit5. With this all container-service tests have been migrated to Junit5.
There is an ongoing effort to migrate all tests to JUnit5 in this ticket I'm migrating the parameterized tests in container-service. After this there shouldn't be any more JUnit4 tests remaining in the module.
[HDDS-9494](https://issues.apache.org/jira/browse/HDDS-9494)
Run each test locally after the fix was finished as well as getting a green CI run here:
https://github.com/Galsza/ozone/actions/runs/7214752431

HDDS-9494. Migrate parameterized tests in hdds-container-service to JUnit5

---

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/ContainerSafeModeRule.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/HealthyPipelineSafeModeRule.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/OneReplicaPipelineSafeModeRule.java
hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/SafeModeExitRule.java

Add details of sample containers/pipelines that do not satisfy safemode criteria in order to continue further debugging/investigation
https://issues.apache.org/jira/browse/HDDS-9478
Manually
Tried bringing down a DN that hosts a container with RF=1, hence pipelineSafemode will not be satisfied i.e atleast one replica of the pipeline is not reported
```bash
bash-4.2$ ozone admin safemode status --verbose
SCM is in safe mode.
validated:true, DataNodeSafeModeRule, registered datanodes (=1) >= required datanodes (=1)
validated:false, HealthyPipelineSafeModeRule, healthy Ratis/THREE pipelines (=0) >= healthyPipelineThresholdCount (=1)
Sample pipelines not satisfying the criteria : [PipelineID=a96f5a77-8d04-41b5-8532-18d0043ffbf3]
validated:true, ContainerSafeModeRule, % of containers with at …
```

HDDS-9478. Add more details to Safemode verbose output.

---

hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/protocol/MockDatanodeDetails.java
hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/GenericTestUtils.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneCluster.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneHAClusterImpl.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/server/TestSecureContainerServer.java

`TestSecureContainerServer` uses random ports and intermittently runs into the following binding error.
The initial thought of why we might be getting the binding error is because of the datanodes of a pipeline might be having similar port numbers due to which it is failing. To fix this we will use the `PortAllocator` method present in `MiniOzoneCluster` that replaces random ports with a simple incremental allocation starting at 15000. It applies to all MiniOzoneCluster-based tests. 
We have also shifted this `PortAllocator` to the `GenericUtils` class so as to be used by all the tests.
```
org.apache.ratis.util.ExitUtils$ExitException: Failed to start Grpc server
at org.apache.ratis.util.ExitUtils.terminate(ExitUtils.java:141)
at …
```

HDDS-9881. Intermittent address already in use in TestSecureContainerServer.

---

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/OzoneClientConfig.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/StreamBufferArgs.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ECBlockOutputStream.java
hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/RatisBlockOutputStream.java
hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestBlockOutputStreamCorrectness.java
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinator.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntry.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntryPool.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockOutputStreamEntry.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockOutputStreamEntryPool.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java
hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneOutputStreamStub.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OmMetadataGenerator.java

Improving EC perf by eliminating redundant config reads.
The `conf.getObject(OzoneClientConfig.class)` is an expensive operation, because the for in `injectConfigurationToObject` may need to be looped many times and there will be a lot of configuration parsing operations.
https://github.com/apache/ozone/blob/8b25c554cbb7a74120f6cf6390ea127bb23f64e2/hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigurationReflectionUtil.java#L89-L99
- There may be other places in Ozone where there are similar performance issues, because `getObject` is used heavily.
- Maybe this can be solved by caching the computed configurations
https://issues.apache.org/jira/browse/HDDS-9913
existing test
Performance testing result
https://issues.apache.org/jira/browse/HDDS-9911

HDDS-9913. Reduce number of times configuration is loaded in Ozone client

---

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestKeyValueContainerData.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestStaleRecoveringContainerScrubbingService.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerPersistence.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestDeleteBlocksCommandHandler.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/ContainerTestVersionInfo.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerCheck.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerIntegrityChecks.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerMetadataInspector.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/impl/TestBlockManagerImpl.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestContainerReader.java
hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainer.java

`ContainerTestVersionInfo` is used in several classes to parameterize test methods.  The goal of this change is to reduce code duplication by defining a [composite annotation](https://junit.org/junit5/docs/current/user-guide/#writing-tests-meta-annotation).
(Will create follow-up tasks for other similar common parameter types.)
https://issues.apache.org/jira/browse/HDDS-9932
Tests changed by this PR were executed normally (no change in test count, etc.).
Before:
```
Tests run: 136, Failures: 0, Errors: 0, Skipped: 8, Time elapsed: 13.51 s -- in org.apache.hadoop.ozone.container.common.impl.TestContainerPersistence
Tests run: 32, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.915 s -- in org.apache.hadoop.ozone.container.common.statemachine.commandhandler.TestDeleteBlocksCommandHandler …
```

HDDS-9932. Compose annotation for tests parameterized with ContainerTestVersionInfo

---

hadoop-hdds/test-utils/pom.xml
hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/TimedOutTestsListener.java
hadoop-hdds/test-utils/src/main/resources/META-INF/services/org.junit.platform.launcher.TestExecutionListener
pom.xml

Let `TimedOutTestsListener` implement JUnit5's `TestExecutionListener` to print thread dump in case tests time out.
https://issues.apache.org/jira/browse/HDDS-9938
Added a test in `hadoop-hdds/config/src/test/java/org/apache/hadoop/hdds/conf/TestConfigFileGenerator.java` which always times out:
```java
@Test
@Timeout(1)
void timeoutTest() throws Exception {
Thread.sleep(2000);
}
```
ran the test:
```
mvn -am -pl :hdds-config -Dtest=TestConfigFileGenerator clean test
```
and verified the output file created for the test:
```
====> timeoutTest() TIMED OUT. PRINTING THREAD DUMP. <====
Timestamp: 2023-12-16 04:04:27,669
...
"main"  prio=5 tid=1 runnable
java.lang.Thread.State: RUNNABLE
at java.lang.Thread.dumpThreads(Native Method)
at java.lang.Thread.getAllStackTraces(Thread.java:1615)
at …
```

HDDS-9938. Migrate TimedOutTestsListener to JUnit5

---

hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneDelegationTokenRenewer.java
hadoop-ozone/ozonefs-hadoop3/src/main/resources/META-INF/services/org.apache.hadoop.security.token.TokenRenewer
hadoop-ozone/ozonefs/src/main/resources/META-INF/services/org.apache.hadoop.security.token.TokenRenewer

Ozone's `TokenRenewer` implementations do not close `OzoneClient` after use.
Both O3FS and OFS define their own `TokenRenewer` implementation.
Hadoop finds implementations via `ServiceLoader`, and uses the first one that handles the kind of token being used:
https://github.com/apache/hadoop/blob/7db9895000860605a66dd6403005b0c61a6ed744/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/token/Token.java#L454-L470
The two implementations are the same (not FileSystem-specific), kind is the same for both, so we can remove the duplicate one.
https://issues.apache.org/jira/browse/HDDS-9943
Ran `ozonesecure-mr/test.sh`, checked OM audit log for delegation token operations:
```
...  | OMAudit | user=hadoop/rm@EXAMPLE.COM | ip=172.31.0.11 | op=GET_DELEGATION_TOKEN …
```

HDDS-9943. TokenRenewer should close OzoneClient after use

---

hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmMetadataManager.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerDoubleBuffer.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/TestReconCodecs.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestBlocksEndPoint.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestFeaturesEndPoint.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/common/CommonUtils.java
hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/fsck/TestContainerHealthStatus.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestPermissionCheck.java
hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/util/TestRangeHeaderParserUtil.java

Assertions in the form:
```
assertTrue(<x> == <y>)
assertEquals(null, <x>) or assertTrue(<x> == null)
assertTrue(<x> != null)
assertEquals(<boolean>, <x>)
```
can be simplified to:
```
assertEquals(<x>, <y>)
assertNull(<x>)
assertNotNull(<x>)
assertTrue/assertFalse(<x>)
```
Not only are these simpler, some of them also provide more information in case of failure.
This PR updates such assertions in `hadoop-ozone` (except integration tests).
https://issues.apache.org/jira/browse/HDDS-9954
CI:
https://github.com/adoroszlai/ozone/actions/runs/7250386337

HDDS-9954. Simplify assertions in hadoop-ozone unit tests

---

hadoop-ozone/integration-test/dev-support/findbugsExcludeFile.xml
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/AbstractOzoneFileSystemTest.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/AbstractOzoneFileSystemTestWithFSO.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestO3FS.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestO3FSWithFSO.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestO3FSWithFSOAndOMRatis.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestO3FSWithFSPaths.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestO3FSWithFSPathsAndOMRatis.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestO3FSWithOMRatis.java

Migrate `TestOzoneFileSystem` and its subclass `TestOzoneFileSystemWithFSO` to JUnit5.
https://issues.apache.org/jira/browse/HDDS-6152
CI:
https://github.com/adoroszlai/ozone/actions/runs/7213522269/job/19654186050

HDDS-6152. Migrate TestOzoneFileSystem to JUnit5

---

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyDeleteRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/file/TestOMFileCreateRequest.java
hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyDeleteRequest.java
hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/keys/DeleteKeyHandler.java

Snapshots are readable only and don't support deletion of key from snapshots. Currently exception is thrown but exception message is not clear. It says `Key not found .snapshot/snap1` for ozone shell and `Unable to get file status: volume: vol1 bucket: buck1 key: .snapshot/snap1` for ozone fs command.
This change is to correct exception message and properly return it to client.
HDDS-9423
1. Added/updated unit tests.
1. Tested in docker:
```
sh-4.2$ ozone sh key delete vol1/bucket1/.snapshot/snap1
Operation not permitted Cannot delete key under path reserved for snapshot: .snapshot/ 
sh-4.2$ ozone sh key delete vol1/bucket1/.snapshot/snap1/key1
Operation not permitted Cannot delete key under path reserved for snapshot: .snapshot/ 
sh-4.2$ ozone sh key delete …
```

HDDS-9423. Throw appropriate error messages when deleting a file in .snapshot path

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMDatanodeProtocolServer.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMInstallSnapshot.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerStateManagerIntegration.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestLeaderChoosePolicy.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineClose.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestRatisPipelineCreateAndDestroy.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestContainerCommandsEC.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/upgrade/TestHDDSUpgrade.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/upgrade/TestHddsUpgradeUtils.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/OzoneTestUtils.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestDelegationToken.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineFailures.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestFailureHandlingByClient.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientWithRatis.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestWatchForCommit.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/TestHelper.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCloseContainerByPipeline.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainer.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/server/TestContainerServer.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestRandomKeyGenerator.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestAddRemoveOzoneManager.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMDbCheckpointServlet.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconInsightsForDeletedDirectories.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestFailoverWithSCMHA.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestSCMContainerPlacementPolicyMetrics.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestSCMInstallSnapshotWithHA.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java

Migrate assertions in the following test classes to JUnit5:
```
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerStateManagerIntegration.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/sim/pipeline/TestLeaderChoosePolicy.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineClose.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestRatisPipelineCreateAndDestroy.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestContainerCommandsEC.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMDatanodePro …
```

HDDS-9809. Migrate assertions in integration tests to JUnit5

---

hadoop-hdds/rocksdb-checkpoint-differ/pom.xml

`version-info` is executed in `hdds-common` and `ozone-common` to get some values substituted into `hdds-version-info.properties` and `ozone-version-info.properties`, respectively.
`hadoop-hdds/rocksdb-checkpoint-differ` also runs `version-info`, but it's useless, the properties are not used anywhere.
https://issues.apache.org/jira/browse/HDDS-9916
CI:
https://github.com/adoroszlai/ozone/actions/runs/7195602829

HDDS-9916. Useless execution of version-info in rocksdb-checkpoint-differ

---

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/TestOzoneClientFactory.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/AbstractTestECKeyOutputStream.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/Test2WayCommitInRatis.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBCSID.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockDataStreamOutput.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestCloseContainerHandlingByClient.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerReplicationEndToEnd.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachine.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineFailures.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineFlushDelay.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineStream.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestDeleteWithInAdequateDN.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestDiscardPreallocatedBlocks.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestECKeyOutputStream.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestECKeyOutputStreamWithZeroCopy.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestFailureHandlingByClient.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestFailureHandlingByClientFlushDelay.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestHybridPipelineOnDatanode.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestMultiBlockWritesWithDnFailures.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientMultipartUploadWithFSO.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientRetriesOnExceptionFlushDelay.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientRetriesOnExceptions.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientForAclAuditLog.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientWithRatis.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestValidateBCSIDOnRestart.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestWatchForCommit.java

Migrating all the tests under integration-test/ozone/client to Junit5 and making sure that Junit4 is not used in any of the tests
Tested that using grep -rlE "org.junit.[A-Z]" . --include '*.java' command in hadoop-ozone/integration-test/
https://issues.apache.org/jira/browse/HDDS-9776
Full CI run: https://github.com/VarshaRaviCV/ozone/actions/runs/7248042617

HDDS-9776. Migrate simple client integration tests to JUnit5
