- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/ratis/TestServerNotLeaderExceptionMessageParsing.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/container/common/helpers/TestExcludeList.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/utils/TestResourceCache.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/common/TestChecksumImplsComputeSameValues.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/TestHddsSecureDatanodeInit.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestDatanodeStoreCache.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestStaleRecoveringContainerScrubbingService.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerPersistence.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/states/endpoint/TestHeartbeatEndpointTask.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/impl/TestBlockManagerImpl.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBTableStore.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancer.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackAware.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestNodeReportHandler.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/server/TestSCMBlockProtocolServer.java
Assertions in the form:
```
assertTrue(<x> == <y>)
assertEquals(null, <x>) or assertTrue(<x> == null)
assertTrue(<x> != null)
assertEquals(<boolean>, <x>)
```
can be simplified to:
```
assertEquals(<x>, <y>)
assertNull(<x>)
assertNotNull(<x>)
assertTrue/assertFalse(<x>)
```
Not only are these simpler, some of them also provide more information in case of failure.
This PR updates such assertions in `hadoop-hdds`.
https://issues.apache.org/jira/browse/HDDS-9953
CI:
https://github.com/adoroszlai/ozone/actions/runs/7250200952
> HDDS-9953. Simplify assertions in hadoop-hdds

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineClose.java
This PR fixes the  Intermittent failure in `TestPipelineClose#testPipelineCloseWithLogFailure`. Test case was earlier verifying if `org.apache.hadoop.hdds.scm.pipeline.PipelineActionHandler#onMessage` gets called immediately with timeout f 100 ms after calling `org.apache.hadoop.ozone.container.common.transport.server.ratis.XceiverServerRatis#handleNodeLogFailure` , this was failing intermittently as the number of times `PipelineActionHandler#onMessage`  get called may vary due to timing issue from all 3 DNs, so this PR fixes this problem by changing the calling count at least once for `PipelineActionHandler#onMessage` method.
https://issues.apache.org/jira/browse/HDDS-5604
This patch was tested using existing integration test by running using flaky workflow. Here is the green CI …
> HDDS-5604. Intermittent failure in TestPipelineClose.

- hadoop-ozone/dev-support/checks/checkstyle.sh
_basic (checkstyle)_ is shown as passing if it fails with config error, not a checkstyle violation.
https://issues.apache.org/jira/browse/HDDS-9885
Verified that the check fails with https://github.com/apache/ozone/pull/921/commits/9b16de3fc1524cc263c5a14576559bec2722e7dd checked out (which had the config error):
```
$ hadoop-ozone/dev-support/checks/checkstyle.sh > /dev/null
$ hadoop-ozone/dev-support/checks/_summary.sh target/checkstyle/summary.txt
13:58:11,624 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:check (default-cli) on project ozone-main: Failed during checkstyle configuration: cannot initialize module TreeWalker - TreeWalker is not allowed as a parent of LineLength Please review 'Parent Module' section for this Check in web …
```
> HDDS-9885. Checkstyle check passing despite config error

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerHealthResult.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyRatisContainerReplicaCount.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/LegacyReplicationManager.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/MisReplicationHandler.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisContainerReplicaCount.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisUnderReplicationHandler.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManagerUtil.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/VulnerableUnhealthyReplicasHandler.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeAdminMonitorImpl.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisUnderReplicationHandler.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManagerUtil.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestVulnerableUnhealthyReplicasHandler.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/DatanodeAdminMonitorTestUtil.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestDatanodeAdminMonitor.java
A `QUASI_CLOSED` container may have some `UNHEALTHY` replicas with the same sequence id as the container, while there are no healthy replicas with the correct sequence id. Such `UNHEALTHY` replicas cannot be deleted and must be kept around.
If the DN hosting such an `UNHEALTHY` replica is put in decommission, then decommission will stay blocked because the `UNHEALTHY` cannot be lost, but at the same time RM currently does nothing about it. We try to do something about these vulnerable `UNHEALTHY` replicas in this PR so that decommission can be successful.
Changes introduced:
1. A new handler, `VulnerableUnhealthyReplicasHandler`, leverages the existing `replicaCount.getVulnerableUnhealthyReplicas` API to find such `UNHEALTHY` replicas. If found, the container is marked as under replicated …
> HDDS-9592. Replication Manager: Save UNHEALTHY replicas with highest BCSID for a QUASI_CLOSED container

- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/helpers/TestChunkUtils.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/symmetric/TestLocalKeyStore.java
- hadoop-hdds/rocks-native/src/test/java/org/apache/hadoop/hdds/utils/TestNativeLibraryLoader.java
- hadoop-hdds/rocks-native/src/test/java/org/apache/hadoop/hdds/utils/db/managed/TestManagedSSTDumpIterator.java
- hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/rocksdb/util/TestManagedSstFileReader.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestInterSCMGrpcProtocolService.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsSnapshot.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMDbCheckpointServlet.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMDbCheckpointServlet.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerRatisRequest.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/service/TestRangerBGSyncService.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDiffManager.java
Replace `createTempFile` and `createTempDir` usage in tests with `@TempDir`.
Only one usage in Recon unit tests is left, which requires a bigger refactoring.
https://issues.apache.org/jira/browse/HDDS-9828
CI:
https://github.com/adoroszlai/ozone/actions/runs/7252513711
> HDDS-9828. Do not use Files.createTempFile in tests

- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerDataYaml.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerDeletionChoosingPolicy.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerSet.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestHddsDispatcher.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCloseContainerCommandHandler.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/ContainerLayoutTestInfo.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerMarkUnhealthy.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueHandler.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestReplicationSupervisor.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestChunkInputStream.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestKeyInputStream.java
ContainerLayoutVersion is used in several classes to parameterize test methods.
- replace repeated @ParameterizedTest and @MethodSource
- delete the local method used as source in the test class    
https://issues.apache.org/jira/browse/HDDS-9948
CI: https://github.com/wzhallright/ozone/actions/runs/7274471363
> HDDS-9948. Compose annotation for tests parameterized with ContainerLayoutVersion

- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/protocolPB/ScmBlockLocationProtocolClientSideTranslatorPB.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMBlockProtocolServer.java
@xichen01 found NPE when running `SCMThroughputBenchmark`
There were also excessive WARN logs from `SCMNodeManager#getNodesByAddress` when the `clientMachine` is empty.
This patch will the resolve the above issues.
https://issues.apache.org/jira/browse/HDDS-9971
> HDDS-9971. Fix issues in allocateBlock when clientMachine is null

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
When doing a `listStatus` on a volume, we are setting the volume owner as the resource owner. Therefore, `ozone fs -ls` is resulting in displaying the volume owner as the owner of every bucket. 
Check the jira description for a test-case for manually reproducing it. 
https://issues.apache.org/jira/browse/HDDS-9950
A new test was added under `TestRootedOzoneFileSystem`. The patch was also tested manually in ozone docker dev env like so
```
> pwd
/projects/ozone/hadoop-ozone/dist/target/ozone-1.5.0-SNAPSHOT/compose/ozone
// Start docker env
> docker-compose up --scale datanode=5 -d
// Create volume with the default user, hadoop
> docker-compose exec om ozone sh volume create /vol1
// Create bucket and set the owner as testuser
> docker-compose exec om ozone sh bucket create /vol1/bucket1 …
```
> HDDS-9950. 'ozone fs -ls' on volume shows the volume owner as the bucket owner

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileInterfaces.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystemWithFSO.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestLeaderChoosePolicy.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineClose.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientForAclAuditLog.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmBlockVersioning.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerListVolumesSecure.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestScmSafeMode.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestSnapshotDeletingService.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestContainerReportWithKeys.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestFailoverWithSCMHA.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestSCMMXBean.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestStorageContainerManager.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestXceiverClientManager.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/pipeline/TestSCMPipelineMetrics.java
Assertions in the form:  
``` 
assertTrue(<x> == <y>)   
assertEquals(null, <x>) or assertTrue(<x> == null)
assertTrue(<x> != null)
assertEquals(<boolean>, <x>)
```
can be simplified to:   
```
assertEquals(<x>, <y>)
assertNotNull(<x>)
assertTrue/assertFalse(<x>)
assertNull(<x>)
```
Not only are these simpler, some of them also provide more information in case of failure.
This PR updates such assertions in hadoop-ozone/integration-test.
https://issues.apache.org/jira/browse/HDDS-9955
https://github.com/wzhallright/ozone/actions/runs/7284783456
> HDDS-9955. Simplify assertions in integration tests

- hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestChunkInputStream.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/helpers/TestDatanodeVersionFile.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerDataYaml.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerSet.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCloseContainerCommandHandler.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueBlockIterator.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueHandler.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/impl/CommonChunkManagerTestCases.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/upgrade/TestDataNodeStartupSlvLessThanMlv.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestSCMSafeModeManager.java
- hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/GenericTestUtils.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/AbstractOzoneFileSystemTest.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestRootedOzoneFileSystem.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestBlockTokens.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecureOzoneCluster.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientMultipartUploadWithFSO.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerConfiguration.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHA.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAWithAllRunning.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerRestart.java
- hadoop-ozone/interface-storage/pom.xml
- hadoop-ozone/interface-storage/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmMultipartKeyInfoCodec.java
- hadoop-ozone/interface-storage/src/test/java/org/apache/hadoop/ozone/om/helpers/TestTransactionInfoCodec.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/failover/TestOMFailovers.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/volume/TestOMVolumeCreateRequest.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/TestVirtualHostStyleFilter.java
This change is to deprecate and remove GenericTestUtils#assertExceptionContains and use AssertJ#assertThat. 
AssertJ is already a dependency of ozone and is preferred to use to exception message comparison. More details are in HDDS-9951 and HDDS-9170. 
HDDS-9170
Ran test locally and fork branch.
> HDDS-9170. Replace GenericTestUtils#assertExceptionContains with AssertJ#assertThat

- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotCache.java
This change is to log failure if there is any problem in closing RocksDB instance to investigate to memory leak like
```
2023-12-18 19:21:06,485 WARN [Finalizer]-org.apache.hadoop.hdds.utils.db.managed.ManagedRocksObjectUtils: Checkpoint is not closed properly
2023-12-18 19:21:06,486 WARN [Finalizer]-org.apache.hadoop.ozone.om.OmSnapshot: org.apache.hadoop.hdds.utils.db.RDBStore@4e5ac786 is not closed properly. snapshotName: snap-5griw
```
HDDS-9986
> HDDS-9986. Log if there is a failure in closing RocksDB

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestDataValidate.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestDataValidateWithDummyContainers.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestDataValidateWithSafeByteOperations.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestDataValidateWithUnsafeByteOperations.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestFreonWithDatanodeFastRestart.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestFreonWithPipelineDestroy.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestHadoopDirTreeGenerator.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestHadoopNestedDirGenerator.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestOmBucketReadWriteFileOps.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestOmBucketReadWriteKeyOps.java
Migrated the following classes to JUnit5 as per the task of the parent jira HDDS-6729
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestDataValidate.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestDataValidateWithDummyContainers.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestFreonWithDatanodeFastRestart.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestFreonWithPipelineDestroy.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestHadoopDirTreeGenerator.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestHadoopNestedDirGenerator.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/f …
> HDDS-9834. Migrate simple freon integration tests to JUnit5

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientMultipartUploadWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMRecoverLeaseRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMAllocateBlockRequestWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequestWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCommitPartRequestWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/util/OMMultipartUploadUtils.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartUploadCompleteRequestWithFSO.java
Move pathComponents calculation to OMFileRequest#getParentID
* PathComponets comes from key and always used with OMFileRequest#getParentID so we can Move pathComponents calculation to OMFileRequest#getParentID. 
HDDS-9946. Move pathComponents calculation to OMFileRequest#getParentID
CI test
https://github.com/TaiJuWu/ozone/actions/runs/7307373311
> HDDS-9946. Move pathComponents calculation to OMFileRequest#getParentID

- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/TestOmUtils.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/client/io/TestSelectorOutputStream.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/exceptions/TestResultCodes.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/ha/TestOMFailoverProxyProvider.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmBucketArgs.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmBucketInfo.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmKeyInfo.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmKeyLocationInfoGroup.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmMultipartUpload.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmSnapshotInfo.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmVolumeArgs.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOzoneAclUtil.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOzoneFsUtils.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOzoneIdentityProvider.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestQuotaUtil.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/lock/TestKeyPathLock.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/lock/TestOzoneManagerLock.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/protocolPB/TestS3GrpcOmTransport.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/protocolPB/grpc/TestClientAddressClientInterceptor.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/protocolPB/grpc/TestClientAddressServerInterceptor.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/security/TestGDPRSymmetricKey.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/security/TestOzoneDelegationTokenSelector.java
Add static import for assertions and mocks in hadoop-ozone/common.
The goal of this task is to add import static for all assertions and interactions with mocks.
HDDS-9989
CI test:
https://github.com/TaiJuWu/ozone/actions/runs/7313708292
> HDDS-9989. Add static import for assertions and mocks in ozone-common

- hadoop-hdds/pom.xml
- hadoop-hdds/server-scm/dev-support/findbugsExcludeFile.xml
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationTestUtil.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManagerScenarios.java
- hadoop-hdds/server-scm/src/test/resources/replicationManagerTests/basic.json
- hadoop-hdds/server-scm/src/test/resources/replicationManagerTests/mismatched_replicas.json
- hadoop-hdds/server-scm/src/test/resources/replicationManagerTests/simple_decommission.json
- hadoop-hdds/server-scm/src/test/resources/replicationManagerTests/simple_maintenance.json
This change added a new test class called TestReplicationManagerScenarios. It work via test definitions in JSON, such as:
```
{ "description": "Perfect Replication Ratis", "containerState": "CLOSED", "replicationConfig": "RATIS:THREE", "sequenceId": 12,
"replicas": [
{ "state": "CLOSED", "index": 0, "datanode": "d1", "sequenceId": 0, "isEmpty": false, "origin": "o1"},
{ "state": "CLOSED", "index": 0, "datanode": "d2", "sequenceId": 0, "isEmpty": false, "origin": "o2"},
{ "state": "CLOSED", "index": 0, "datanode": "d3", "sequenceId": 0, "isEmpty": false, "origin": "o3"}
],
"expectation": {},
"commands": []
}
```
Which defines the container state and the replica states, along with expected commands and outputs from processing the container.
For each scenario, it runs through the Replication …
> HDDS-9877. ReplicationManager: Create a data driven test framework to cover similar test scenarios

- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/TestAuthorizationFilter.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/TestVirtualHostStyleFilter.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestAbortMultipartUpload.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestBucketAcl.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestInitiateMultipartUpload.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestListParts.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestMultipartUploadComplete.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestMultipartUploadWithCopy.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectDelete.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectGet.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectPut.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestPartUpload.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestPartUploadWithStream.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestPermissionCheck.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestUploadWithStream.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/metrics/TestS3GatewayMetrics.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/signature/TestStringToSignProducer.java
```
```
and
```
```
and
```
// also:
```
makes the code more readable (shorter lines, less wrapping).
[HDDS-9992](https://issues.apache.org/jira/browse/HDDS-9992)
https://github.com/wzhallright/ozone/actions/runs/7318668302
> HDDS-9992. Add static import for assertions and mocks in ozone-s3gateway

- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/conf/TestHddsConfServlet.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/ssl/TestPemFileBasedKeyStoresFactory.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/ssl/TestReloadingX509KeyManager.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/symmetric/TestSecretKeyManager.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/authority/TestDefaultCAServer.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/TestDefaultCertificateClient.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/TestRootCaRotationPoller.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/utils/TestCRLCodec.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/keys/TestKeyCodec.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/TestJsonUtils.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/events/TestEventQueue.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/events/TestEventWatcher.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/http/TestPrometheusMetricsIntegration.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/http/TestRatisDropwizardExports.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/TestRDBSnapshotProvider.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestCodec.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestDBStoreBuilder.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStore.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStoreByteArrayIterator.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStoreCodecBufferIterator.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBTableStore.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestTypedRDBTableStore.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/ozone/audit/TestOzoneAuditLogger.java
Improve assertTrue assertions in hadoop-hdds/framework
Assertions in the form:
```
assertTrue(<string>.contains(...))
```
do not provide any information about the actual value, if the assertion fails.
```
AssertionFailedError: expected: <true> but was: <false>
```
This can be improved by replacing them with:
```
import static org.assertj.core.api.Assertions.assertThat;
assertThat(<string>).contains(...)
```
which gives us more info in the form:
```
AssertionError: 
Expecting:
<"actual string">
to contain:
<"part"> 
```
Similarly, assertions about inequality relations, e.g.:
```
assertTrue(<x> > <y>)
```
can be replaced with:
```
assertThat(<x>).isGreaterThan(<y>);
```
The goal of this task is to find and replace such assertTrue assertions. …
> HDDS-9982. Improve assertTrue assertions in hdds-server-framework

- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/TestReconCodecs.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestBlocksEndPoint.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestContainerStateCounts.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestFeaturesEndPoint.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestOmDBInsightEndPoint.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestOpenContainerCount.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestTaskStatusService.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestTriggerDBSyncEndpoint.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/filters/TestAdminFilter.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/fsck/TestContainerHealthStatus.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/fsck/TestContainerHealthTask.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/fsck/TestContainerHealthTaskRecordGenerator.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/heatmap/TestHeatMapInfo.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/persistence/AbstractReconSqlDBTest.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/persistence/TestStatsSchemaDefinition.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconIncrementalContainerReportHandler.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconPipelineManager.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/spi/impl/TestReconNamespaceSummaryManagerImpl.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/spi/impl/TestStorageContainerServiceProviderImpl.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestFileSizeCountTask.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestOmUpdateEventValidator.java
Add static import for assertions and mocks in hadoop-ozone/recon
```
```
and
```
```
and
```
// also:
```
makes the code more readable (shorter lines, less wrapping).
[HDDS-9996](https://issues.apache.org/jira/browse/HDDS-9996)
https://github.com/wzhallright/ozone/actions/runs/7321501158
> HDDS-9996. Add static import for assertions and mocks in ozone-recon

- dev-support/ci/selective_ci_checks.bats
- dev-support/ci/selective_ci_checks.sh
Tests can be skipped for changes in IntelliJ configuration (e.g. HDDS-9899), since these are not covered by any tests.
https://issues.apache.org/jira/browse/HDDS-9901
Added bats test case.
CI:
https://github.com/adoroszlai/ozone/actions/runs/7171239020
> HDDS-9901. Selective checks: skip tests for IntelliJ config change

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientWithRatis.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerStateMachine.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/metrics/OzoneManagerStateMachineMetrics.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/DummyOMClientResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/TestCleanupTableInfo.java
In the current OM statemachine implementation, if the write request fails before request's validateAndUpdateCache call, this request will have no OMClientResponse in the doublebuffer, which leads to this request cannot be confirmed as completed(even with failure), so this request txIndex will be left in OM statemachine applyTransactionMap forever.  It will cause a lot of consequences, refer to HDDS-9342 for detail issues observed. 
To solve this problem, a DummyOMClientResponse is introduced for all these failed requests, to go through the doubleBuffer flush cycle, so that they will be treated as completed and their txIndex will be removed from applyTransactionMap. 
https://issues.apache.org/jira/browse/HDDS-9876
Test with newly added unit test.
> HDDS-9876. OM state machine should add response for every write request to the double-buffer

- hadoop-ozone/integration-test/dev-support/findbugsExcludeFile.xml
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/AbstractRootedOzoneFileSystemTest.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/AbstractRootedOzoneFileSystemTestWithFSO.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOFS.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOFSWithCacheOnly.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOFSWithFSO.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOFSWithFSOAndCacheOnly.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOFSWithFSOAndOMRatis.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOFSWithFSOAndOMRatisAndCacheOnly.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOFSWithFSPaths.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOFSWithFSPathsAndOMRatis.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOFSWithFSPathsAndOMRatisAndACL.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOFSWithFSPathsAndOMRatisAndCacheOnly.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOFSWithOMRatis.java
Migrate `TestRootedOzoneFileSystem` and its subclass `TestRootedOzoneFileSystemWithFSO` to JUnit5.
https://issues.apache.org/jira/browse/HDDS-9921
CI:
https://github.com/adoroszlai/ozone/actions/runs/7331919110/job/19965565932
> HDDS-9921. Migrate TestRootedOzoneFileSystem to JUnit5

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/conf/DefaultConfigManager.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/upgrade/AbstractLayoutVersionManager.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/upgrade/LayoutVersionManager.java
- hadoop-hdds/docs/content/feature/SCM-HA.md
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHANodeDetails.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestSCMHAConfiguration.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/upgrade/TestSCMHAUnfinalizedStateValidationAction.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestStorageContainerManager.java
Currently, we don't have any steps/ways to enable SCM HA on a Non-HA setup. This is because `ozone.scm.ratis.enable` cannot be modified once the cluster is initialized ([HDDS-6695](https://issues.apache.org/jira/browse/HDDS-6695)).
We have to initialize Ratis (once the upgrade is finalized) as part of `scm --init` command to support enabling of SCM HA in a Non-HA cluster.
After this change, once the cluster is upgraded running `scm --init` will enable and initialize Ratis in a Non-HA (non Ratis) setup.
[HDDS-9879
](https://issues.apache.org/jira/browse/HDDS-9897)
An additional unit test is added to verify the new behavior.
> HDDS-9897. Option to enable Ratis in SCM.

- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/lock/TestOzoneManagerLock.java
testLockViolations should fail if it does not catch RuntimeException
* Insert Assertions.fail() to next line.
HDDS-10023.
CI:  https://github.com/TaiJuWu/ozone/actions/runs/7347807688
> HDDS-10023. testLockViolations should fail if it does not catch RuntimeException

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
In ContainerStateMachine, some wrong symbols will be recorded to the log file. The purpose of this PR is to fix it.
https://issues.apache.org/jira/browse/HDDS-10024
For testing, there’s not much pressure.
> HDDS-10024. Fix typo in ContainerStateMachine log message

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/SCMBlockDeletingService.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java
Fix unstable integration tests.
Multiple tests have uncovered a number of things that can cause `TestBlockDeletion` to fail
1. `hdds.datanode.block.delete.queue.limit` defaults to 5, which may cause tasks to be discarded if they can't be added to the queue, thus causing the test to time out.  (fix by https://github.com/apache/ozone/pull/5845)
2. `restartHddsDatanode` in `TestBlockDeletion.testBlockDeletion` can sometimes cause the DN to be restarted before sending the `DeleteBlockTransactionResult` to the SCM.
https://github.com/apache/ozone/blob/4eca52b6b76b0737bfb2d6ed94097969a0737a45/hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java#L299-L310
3. `SCMBlockDeletingService#notifyStatusChanged` in …
> HDDS-9962. Intermittent timeout in TestBlockDeletion.testBlockDeletion

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/HddsVolume.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestHddsVolume.java
Fix NPE in `HddsVolume.getCommitted()`, which can happen for failed volumes.
https://issues.apache.org/jira/browse/HDDS-10027
Added assertion unit test.
CI:
https://github.com/adoroszlai/ozone/actions/runs/7355440841
> HDDS-10027. NPE in VolumeInfoMetrics.getCommitted()

- dev-support/ci/selective_ci_checks.bats
- hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdb/util/SstFileSetReader.java
- hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/rocksdb/util/TestSstFileSetReader.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDiffManager.java
Rename `ManagedSstFileReader` in `rocksdb-checkpoint-differ` to avoid confusion with the "real" `ManagedSstFileReader` from `hdds-managed-rocksdb`.
https://github.com/apache/ozone/blob/f9167a359e7ff6f54eafc8a7b1c3fd165050160f/hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedSstFileReader.java#L23-L26
https://github.com/apache/ozone/blob/f9167a359e7ff6f54eafc8a7b1c3fd165050160f/hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdb/util/ManagedSstFileReader.java#L48-L52
I think `SstFileSetReader` would be a better name.
https://issues.apache.org/jira/browse/HDDS-10007
CI:
https://github.com/adoroszlai/ozone/actions/runs/7309005071
> HDDS-10007. Rename ManagedSstFileReader in rocksdb-checkpoint-differ

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestStorageContainerManager.java
This PR fixes the Intermittent failure in TestStorageContainerManager#testContainerReportQueueTakingMoreTime. Intermittent failure was detected in below assertion:
Assert.assertTrue(containerReportExecutors.longWaitInQueueEvents() >= 1);
This assertion statement asserts that number of container reports, waiting in event queue more than queueWaitThreshold is greater than 1. This metric of longWaitInQueue is incremented if report is waiting in event queue longer than wait threshold value of 1s set by test case. Due to timing issue, assertion use to fail intermittently and this PR fixes that with usage of semaphore. This PR also improves the test case by reducing the time needed to finish the test case.
https://issues.apache.org/jira/browse/HDDS-8470
This patch is tested by running all test …
> HDDS-8470. Intermittent failure in TestStorageContainerManager#testContainerReportQueueTakingMoreTime.

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneHAClusterImpl.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestAddRemoveOzoneManager.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAWithAllRunning.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAWithStoppedNodes.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerPrepare.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestTransferLeadershipShell.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerRatisServer.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerStateMachine.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/upgrade/OMPrepareRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerProtocolServerSideTranslatorPB.java
`OzoneManagerRatisServer` has a specific raftGroup. The `getServer()` method should return the division specific to that group. Otherwise, callers have to get groupId and then get the division with try-catch.
HDDS-10036
> HDDS-10036. OzoneManagerRatisServer.getServer() should return Division.

- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneClient.java
- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java
- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/checksum/TestReplicatedFileChecksumHelper.java
- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/io/TestKeyInputStreamEC.java
- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/rpc/TestRpcClient.java
Add static import for assertions and mocks in hadoop-ozone/client.
The goal of this task is to add import static for all assertions and interactions with mocks.
HDDS-9990
CI test: https://github.com/TaiJuWu/ozone/actions/runs/7377357085
> HDDS-9990. Add static import for assertions and mocks in ozone-client

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/io/ByteBufferInputStream.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OMRatisHelper.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerRatisServer.java
In `OMRatisHelper`, the helper methods uses a `byte[]` to do the conversion.  It can be improved by using `ByteBuffer` for reducing the number of buffer copying.
HDDS-10037
> HDDS-10037. Reduce the number of buffer copying in OMRatisHelper.

- hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/rocksdiff/TestRocksDBCheckpointDiffer.java
Clean up artifacts in hadoop-hdds/rocksdb-checkpoint-differ directory.
Add a list to record cp directory and we can delete these directories when clean up.
HDDS-10002.
CI test: https://github.com/TaiJuWu/ozone/actions/runs/7376016275
> HDDS-10002. TestRocksDBCheckpointDiffer leaves artifacts in project root dir

- .github/workflows/ci.yml
* `license` check should use Maven cache for dependencies.
* Use explicit `cache/restore` in all checks except `build`.  This avoids the need for separate cache keys in concurrent checks, since only `build` will save cache.
* Specify `path` exception to avoid the need to explicitly delete Ozone artifacts before cache upload.
https://issues.apache.org/jira/browse/HDDS-10028
CI:
https://github.com/adoroszlai/ozone/actions/runs/7355754873
> HDDS-10028. Simplify Maven cache for dependencies in CI

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconScmHASnapshot.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconScmSnapshot.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManagerFSO.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManagerHA.java
HDDS-9836. Migrate simple recon integration tests to JUnit5
- Updated test annotations `@Before`, `@After`, `@BeforeClass`, `@AfterClass`, `@Timeout` with JUnit 5 equivalents.
- Replaced JUnit 4 assert methods and Timeout rule with JUnit 5 equivalents.
- Modified imported classes for JUnit 5 compatibility.
- Affected files:
- TestReconScmHASnapshot.java
- TestReconScmSnapshot.java
- TestReconWithOzoneManagerFSO.java
- TestReconWithOzoneManagerHA.java
- According to the description in https://issues.apache.org/jira/browse/HDDS-9836, one more class TestReconWithOzoneManager.java is also needed to change, but it is already migrated to JUnit 5, so it is skipped in this PR. 
- These changes ensure compatibility with JUnit 5 and leverage its updated testing features. …
> HDDS-9836. Migrate simple recon integration tests to JUnit5

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeMetrics.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/scm/node/TestSCMNodeMetrics.java
I added three new metrics to the `SCMNodeMetrics`:
- Number of datanodes
- Total cluster installed capacity
- Total current Ozone utilization
With this change these metrics will be available in the SCM's JMX endpoint. This is an addition to the already existing SCMNodeMetrics, which will be useful when we want to gather information about the overall state of the cluster.
https://issues.apache.org/jira/browse/HDDS-10047
I added the new metrics to the already existing tests, green CI: https://github.com/dombizita/ozone/actions/runs/7387348419
> HDDS-10047. Add number of datanodes, total capacity/used space to SCMNodeMetrics

- hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdb/util/SstFileSetReader.java
- hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java
- hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDiffUtils.java
Close some RocksDB objects that were left open in `rocksdb-checkpoint-differ` module.
https://issues.apache.org/jira/browse/HDDS-10001
CI:
https://github.com/adoroszlai/ozone/actions/runs/7359160284
> HDDS-10001. Options not closed properly in rocksdb-checkpoint-differ

- hadoop-hdds/annotations/pom.xml
- hadoop-hdds/docs/pom.xml
- hadoop-hdds/hadoop-dependency-client/pom.xml
- hadoop-hdds/hadoop-dependency-server/pom.xml
- hadoop-hdds/hadoop-dependency-test/pom.xml
- hadoop-hdds/interface-admin/pom.xml
- hadoop-hdds/interface-client/pom.xml
- hadoop-hdds/interface-server/pom.xml
- hadoop-hdds/managed-rocksdb/pom.xml
- hadoop-ozone/dev-support/checks/junit.sh
HDDS-10013 removed dependency on `junit` from modules which do not have tests.  Now `unit` check finishes with success in 1 minute instead of running unit tests:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.2:test (default-test) on project hdds-annotation-processing: groups/excludedGroups require TestNG, JUnit48+ or JUnit 5 (a specific engine required on classpath) on project test classpath -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.2:test (default-test) on project hdds-hadoop-dependency-client: groups/excludedGroups …
```
> HDDS-10056. Silent failure in unit check

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManager.java
This PR fixes the failure of `org.apache.hadoop.ozone.recon.TestReconWithOzoneManager#testOmDBSyncWithSeqNumberMismatch` when run it individually. Failure happens due to the assertion of hardcoded OM DB sequence number and Recon OM snapshot DB sequence number  with the assumption that always whole test class will run and since test case shares the common MiniOzoneCluster with `testOmDBSyncing` test case, these hardcoded values of sequence numbers may not be consistent always if test runs individually. So the fix is needed to allow test cases to be able to run individually and pass successfully.
https://issues.apache.org/jira/browse/HDDS-9970
This patch is tested by running both the individual test cases of `org.apache.hadoop.ozone.recon.TestReconWithOzoneManager` class.
> HDDS-9970. Recon - Fix failure of TestReconWithOzoneManager test case testOmDBSyncWithSeqNumberMismatch.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/recon/ReconConfigKeys.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/ContainerReportQueue.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeHeartbeatDispatcher.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServerConfigKeys.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconUtils.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconContainerManager.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconContainerReportQueue.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconIncrementalContainerReportHandler.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStorageContainerManagerFacade.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconIncrementalContainerReportHandler.java
There is a difference between SCM's  IncrementalContainerReportHandler and Recon's IncrementalContainerReportHandler , Recon always connects to SCM and verify each container before adding new container to its own containerStateManager cache. This could be a bottle neck if SCM may respond slow and frequent ICR requests may pile up in queue. So as of now, this PR will improve below multiple things:
-     Recon to verify containers in batches from SCM on receive of ICR request from DNs.
-     Reduce the scmClient configs for Recon before connecting to SCM:
- `hdds.scmclient.rpc.timeout` - 1 min (Default value is 15 mins)
- `hdds.scmclient.failover.max.retry` - 3 (Default value is dynamic and computed, but based on default values, computed value is 15)
Above 2 SCM client configs will be …
> HDDS-9883. Recon - Improve the performance of processing IncrementalContainerReport from DN

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/LeakDetector.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/LeakTracker.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/resource/TestLeakDetector.java
- hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedBloomFilter.java
- hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedColumnFamilyOptions.java
- hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedCompactRangeOptions.java
- hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedDBOptions.java
- hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedEnvOptions.java
- hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedFlushOptions.java
- hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedIngestExternalFileOptions.java
- hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedLRUCache.java
- hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedObject.java
- hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedOptions.java
- hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedReadOptions.java
- hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedRocksObjectUtils.java
- hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedSlice.java
- hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedSstFileWriter.java
- hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedStatistics.java
- hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedWriteBatch.java
- hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedWriteOptions.java
* Let `LeakTracker` implement `UncheckedAutoCloseable` and change methods that return it to use the interface.  Tracked objects should not call other methods exposed due to `LeakTracker extends WeakReference`.
* Distinguish detectors with the same name by appending a unique integer.
* Split two test cases in `TestLeakDetector`.
https://issues.apache.org/jira/browse/HDDS-10000
CI:
https://github.com/adoroszlai/ozone/actions/runs/7401596618
> HDDS-10000. Improve LeakDetector

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java
The test goes through these steps
* Start with an inactive follower
* Write keys
* Start the inactive follower, which downloads a ratis snapshot
* Write more keys
* The follower now downloads an incremental snapshot
* Delete some sst files from the follower's candidate dir
* The follower tries to install an incremental snapshot, which fails
* The follower installs a new snapshot
* Check the metrics to verify the above steps 
The metrics part was commented out by https://github.com/apache/ozone/pull/5673.
The metrics depend on downloading the 3rd snapshot. During the failures, the corruption in the candidate dir isn’t picked up and the Ratis GrpcLogAppender actually returns SUCCESS and the snapshot installation isn’t repeated. 
The issue is with the code deleting the sst files. The steps …
> HDDS-10004. Fix TestOMRatisSnapshots#testInstallIncrementalSnapshotWithFailure

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/fs/SpaceUsageSource.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/fs/MockSpaceUsageSource.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/StorageVolume.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeInfo.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeUsage.java
`PrecomputedVolumeSpace`, added in HDDS-9380, is structurally very similar to the `Fixed` implementation of `SpaceUsageSource`.  The latter is currently only used for testing.  We can reduce duplication by moving `Fixed` from tests to production code and replacing `PrecomputedVolumeSpace` with it.
https://issues.apache.org/jira/browse/HDDS-10046
Refactoring, covered by existing tests:
https://github.com/adoroszlai/ozone/actions/runs/7385534327
> HDDS-10046. Replace PrecomputedVolumeSpace with SpaceUsageSource.Fixed

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/PipelineRequestInformation.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/WritableRatisContainerProvider.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestWritableRatisContainerProvider.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestSafeMode.java
Change `WritableRatisContainerProvider.getContainer` logic from:
* infinite loop until container is found
* look up open pipelines
* select one pipeline
* find matching container
to:
* look up open pipelines
* iterate pipelines until container is found
* select one pipeline
* find matching container
The original logic may keep finding the same pipeline until it is closed.
https://issues.apache.org/jira/browse/HDDS-8982
Added unit and integration test.
CI:
https://github.com/adoroszlai/ozone/actions/runs/7391181618
> HDDS-8982. Prevent infinite loop in WritableRatisContainerProvider if pipeline's nodes are not found

- hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/client/TestHddsClientUtils.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/utils/db/Proto2CodecTestBase.java
- hadoop-hdds/config/src/test/java/org/apache/hadoop/hdds/conf/TestConfigFileAppender.java
- hadoop-hdds/config/src/test/java/org/apache/hadoop/hdds/conf/TestConfigFileGenerator.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerPersistence.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/report/TestReportPublisherFactory.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestStorageVolumeChecker.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestVolumeSetDiskChecks.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerMarkUnhealthy.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/ssl/TestReloadingX509TrustManager.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/token/TestOzoneBlockTokenSecretManager.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/token/TokenVerifierTests.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/TestDefaultCertificateClient.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/ozone/audit/TestOzoneAuditLogger.java
- hadoop-hdds/hadoop-dependency-test/pom.xml
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackScatter.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestInterSCMGrpcProtocolService.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestWritableECContainerProvider.java
- hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/cert/TestCleanExpiredCertsSubcommand.java
- hadoop-ozone/dist/src/main/license/bin/LICENSE.txt
- hadoop-ozone/integration-test/pom.xml
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFSBucketLayout.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsHAURLs.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/scanner/TestContainerScannerIntegrationAbstract.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOmSnapshot.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOMStorage.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestServiceInfoProvider.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/upgrade/TestOMUpgradeFinalizer.java
- pom.xml
Replace Hamcrest `assertThat` and matchers with JUnit or AssertJ assertions, to reduce the number of test dependencies a bit.
https://issues.apache.org/jira/browse/HDDS-10058
CI:
https://github.com/adoroszlai/ozone/actions/runs/7409626572
> HDDS-10058. Replace Hamcrest assertions

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
This PR fixes intermittent failure in `TestSecureOzoneRpcClient.testValidateBlockLengthWithCommitKey` test case.
This test case validates the committed block length for committed key on OM side, but this test case generates the key content randomly using `RandomStringUtils.random(RandomUtils.nextInt(0, 1024))` and this caused the intermittent failure as sometimes seed value of 0 being used to generate key content due to which empty block gets written in key. This PR fixed the issue by changing the range (1, 1024) so that empty key block never gets committed.
https://issues.apache.org/jira/browse/HDDS-9758
This patch is tested by running repeated CI runs of multiple iterations (100 iterations in CI flaky workflow). Here is the green CI …
> HDDS-9758. Intermittent failure in testValidateBlockLengthWithCommitKey.

- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestWritableRatisContainerProvider.java
Fix intermittent failure in `TestWritableRatisContainerProvider#skipsPipelineWithoutContainer`.
One of the pipelines has a container (stubbing for `getMatchingContainer`), the other doesn't.  Mocks return `null` for calls without stubbing, and the test relies on that for the pipeline without container.  The problem is that Mockito is also strict by default.  When it sees the non-stubbed pipeline, it reports this error.  Pipelines are returned by `getPipelines` in the right order (one without container first), but the order in which they are actually checked depends on `PipelineChoosePolicy`.
The problem can be reproduced by changing the test case to `@RepeatedTest(100)`.
The fix sets lenient mode for Mockito in the test class to be able to rely on the default.
This also exposed another …
> HDDS-10070. Intermittent failure in TestWritableRatisContainerProvider

- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/TestHddsUtils.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/fs/TestDU.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/fs/TestDedicatedDiskSpaceUsage.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/fs/TestSpaceUsageFactory.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/protocol/TestDatanodeDetails.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/TestSCMHAUtils.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/container/TestReplicationManagerReport.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/net/TestNetworkTopologyImpl.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/net/TestNodeSchemaManager.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/net/TestYamlSchemaLoader.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/utils/db/TestLeakDetector.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/lock/TestLockManager.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/upgrade/TestLayoutVersionInstanceFactory.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/upgrade/TestUpgradeFinalizerActions.java
Replace some `assertTrue`/`assertFalse` with `assertThat`, which can provide details about the failure, in `hadoop-hdds/common`.
https://issues.apache.org/jira/browse/HDDS-9980
CI:
https://github.com/adoroszlai/ozone/actions/runs/7390928267
> HDDS-9980. Improve assertTrue assertions in hdds-common

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsSnapshot.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
Currently when we do `ozone fs -ls` on `.snapshot` hidden dir of a bucket, it throws an error message if bucket contains deleted snapshot which are not be garbage collected as mentioned in HDDS-10057.
In this change, snapshot active check is added to make sure it lists only active snapshots and their content.
HDDS-10057
Updated the unit test and tested it out on local cluster by increasing the run time of SnapshotDeletingService.
> HDDS-10057. [Snapshot] 'ozone fs -ls' on '.snapshot' dir of a bucket should list only active snapshots

- hadoop-ozone/ozonefs-common/src/test/java/org/apache/hadoop/fs/ozone/TestBasicOzoneFileSystems.java
- hadoop-ozone/ozonefs-common/src/test/java/org/apache/hadoop/fs/ozone/TestOFSPath.java
- hadoop-ozone/ozonefs-common/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneClientUtils.java
- hadoop-ozone/ozonefs-common/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsShell.java
and
...
and
// also:
https://issues.apache.org/jira/browse/HDDS-9999
Ran unit tests
> HDDS-9999. Add static import for assertions and mocks in ozonefs-common

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/keys/ListKeyHandler.java
Ozone List keys CLI should co-ordinate between max limit and listCache Size. 
The client should only ask the OM the user requested amount of keys (if maxLimit is set) however currently even though user requests say 10 keys (maxLimit=10), OM will give out 1000 keys (as maxCacheLimit=1000) and then while printing we only print the 10 keys. We can reduce this small performance overhead by only requesting maxLimit from OM which this PR intends to do.
https://issues.apache.org/jira/browse/HDDS-9927
Manual
> HDDS-9927. Ozone List keys CLI should co-ordinate between max limit and listCache Size.

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestDataUtil.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmMetrics.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMDirectoriesPurgeRequestWithFSO.java
Directory and file count is included in the OM NumKeys metric. When a directory is deleted from OM, its subdirectories and files are not subtracted from the current key count held by the NumKeys metric. We can decrement this metric in the OMDirectoriesPurgeRequestWithFSO sent out by the leader's directory deleting service so that the metric is updated asynchronously on the leader and all followers.
HDDS-10063
New integration test for directory related metrics added to the existing test class for OM Metrics.
> HDDS-10063. NumKeys metric not decremented on FSO directory delete.

- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/TestHelper.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerImpl.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestObjectStoreWithFSO.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerRestart.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestFailoverWithSCMHA.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestSCMNodeManagerMXBean.java
Assertions in the form:
```
assertTrue(<x> == <y>)
assertEquals(null, <x>) or assertTrue(<x> == null)
assertTrue(<x> != null)
assertEquals(<boolean>, <x>)
```
can be simplified to:
```
assertEquals(<x>, <y>)
assertNull(<x>)
assertNotNull(<x>)
assertTrue/assertFalse(<x>)
```
Not only are these simpler, some of them also provide more information in case of failure.
This PR updates such assertions missed by previous tasks (except `TestSecureOzoneCluster` is done in #5906).
https://issues.apache.org/jira/browse/HDDS-10075
CI:
https://github.com/adoroszlai/ozone/actions/runs/7427315061
> HDDS-10075. Simplify leftover assertions

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestDataUtil.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmMetrics.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneDebugShell.java
Replace hard-coded `BucketLayout.LEGACY` with the configured default bucket layout:
https://github.com/apache/ozone/blob/48ea0bb94b22cb9584de3c2b1d6757d1d1f64969/hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestDataUtil.java#L142-L145
and similarly here:
https://github.com/apache/ozone/blob/48ea0bb94b22cb9584de3c2b1d6757d1d1f64969/hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestDataUtil.java#L52-L55
Keep using `LEGACY` in two tests that fail with the default `FILE_SYSTEM_OPTIMIZED` layout.
https://issues.apache.org/jira/browse/HDDS-10084
CI:
https://github.com/adoroszlai/ozone/actions/runs/7440054515
> HDDS-10084. Replace LEGACY in integration test with default layout from config

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/AbstractBackgroundContainerScanner.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/scanner/TestBackgroundContainerDataScannerIntegration.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/scanner/TestContainerScannerIntegrationAbstract.java
`TestBackgroundContainerDataScannerIntegration` may fail intermittently.
Example:
```
TestBackgroundContainerDataScannerIntegration.testCorruptionDetected(ContainerCorruptions)[1] -- Time elapsed: 13.31 s <<< FAILURE!
Expected: a string containing "MISSING_CHUNKS_DIR"
but: was "ID=1 | Index=0 | BCSID=4 | State=UNHEALTHY | MISSING_CHUNK_FILE for file /home/runner/work/ozone/ozone/hadoop-ozone/integration-test/target/test-dir/MiniOzoneClusterImpl-7b4415b0-8a9a-489f-9f19-6b15e56f000b/datanode-0/data-0/containers/hdds/7b4415b0-8a9a-489f-9f19-6b15e56f000b/current/containerDir0/1/chunks/111677748019200001.block. Message: /home/runner/work/ozone/ozone/hadoop-ozone/integration-test/target/test-dir/MiniOzoneClusterImpl-7b4415b0-8a9a-489f-9f19-6b15e56f000b/datanode-0/data-0/containers/hdds/7b4415b0- …
```
> HDDS-9852. Intermittent timeout in testCorruptionDetected waiting for container to become unhealthy

- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/exceptions/OMException.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OzoneManagerProtocol.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
- hadoop-ozone/dist/src/main/smoketest/debug/ozone-debug-lease-recovery.robot
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestLeaseRecovery.java
- hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMRecoverLeaseRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMAllocateBlockRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMAllocateBlockRequestWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequestWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/file/OMRecoverLeaseResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyCommitResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyCommitResponseWithFSO.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/OMRequestTestUtils.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/file/TestOMRecoverLeaseRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeyCommitResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeyCommitResponseWithFSO.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientAdapter.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/Statistic.java
- hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java
- hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java
- hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java
- hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java
Implement file recovery support in OM. 
https://issues.apache.org/jira/browse/HDDS-9638
new unit tests and existing tests.
> HDDS-9638. [hsync] File recovery support in OM

- hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/loadgenerators/LoadBucket.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/OzoneFileSystemTests.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/OzoneContract.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/rooted/RootedOzoneContract.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMultipartObjectGet.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecureOzoneCluster.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientWithRatis.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/OMUpgradeTestUtils.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmContainerLocationCache.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerRocksDBLogging.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestStorageContainerManager.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestStorageContainerManagerHelper.java
Migrate integration tests not covered by HDDS-9835 to JUnit5.
https://issues.apache.org/jira/browse/HDDS-10049
CI:
https://github.com/adoroszlai/ozone/actions/runs/7389637226
> HDDS-10049. Migrate remaining integration tests to JUnit5

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/TestOzoneClientFactory.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/AbstractTestECKeyOutputStream.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/Test2WayCommitInRatis.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBCSID.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockDataStreamOutput.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestCloseContainerHandlingByClient.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerReplicationEndToEnd.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachine.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineFailureOnRead.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineFlushDelay.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineStream.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestDeleteWithInAdequateDN.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestDiscardPreallocatedBlocks.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestFailureHandlingByClientFlushDelay.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestHybridPipelineOnDatanode.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestMultiBlockWritesWithDnFailures.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneAtRestEncryption.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientMultipartUploadWithFSO.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientRetriesOnExceptionFlushDelay.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientRetriesOnExceptions.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientForAclAuditLog.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestValidateBCSIDOnRestart.java
…gration tests
Add static import for assertions and mocks in client integration tests
```
```
and
```
```
and
```
// also:
```
makes the code more readable (shorter lines, less wrapping).
[HDDS-10069](https://issues.apache.org/jira/browse/HDDS-10069)
https://github.com/wzhallright/ozone/actions/runs/7456359981
> HDDS-10069. Add static import for assertions and mocks in client integration tests

- pom.xml
Upgrade Ratis from 3.0.0 to 3.0.1.
https://issues.apache.org/jira/browse/HDDS-10035
Tested in CI (for `master` branch) while validating the Ratis release candidate:
https://github.com/adoroszlai/ozone/actions/runs/7424798081
https://github.com/adoroszlai/ozone/actions/runs/7355126097
CI in fork is in progress:
https://github.com/adoroszlai/ozone/actions/runs/7460198373
> HDDS-10035. Bump Ratis to 3.0.1

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/interfaces/Container.java
`Container` extends the `RwLock` interface from Hadoop, probably only for convenience.  Hadoop 3.4 adds two new methods in `RwLock` (HDFS-16434) without default implementation.  We need to
1. either implement these new methods,
2. or inline the methods used into `Container`.
No code in Ozone makes use of the `RwLock` abstraction, so I think we can go with (2).
Q: should we keep methods implemented but not used in Ozone? (`readLockInterruptibly`, `writeLockInterruptibly`, `hasReadLock`)
https://issues.apache.org/jira/browse/HDDS-10072
CI:
https://github.com/adoroszlai/ozone/actions/runs/7426301421
> HDDS-10072. Update Container interface for named RwLock operations

- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/conf/HddsConfServlet.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/HttpServer2.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/conf/TestHddsConfServlet.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/NSSummaryAdmin.java
[HDDS-2950](https://issues.apache.org/jira/browse/HDDS-2950) forked HttpServer2 from Hadoop. There are a few leftover places where Hadoop's version of HttpServer2 is used. We should replace these with [the one from Ozone](https://github.com/apache/ozone/blob/master/hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/HttpServer2.java):
Files modified for the import replacement:
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/conf/HddsConfServlet.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/HttpServer2.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/NSSummaryAdmin.java
- …
> HDDS-9847. Replace usage of org.apache.hadoop.http.HttpServer2

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestSafeMode.java
HDDS-8982 added a new assertion in `TestSafeMode` and set timeout of 1 minute for the test case.  Encountered the following problem in a recent run:
```
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 103.8 s <<< FAILURE! -- in org.apache.hadoop.fs.ozone.TestSafeMode
org.apache.hadoop.fs.ozone.TestSafeMode.o3fs -- Time elapsed: 72.90 s <<< ERROR!
java.util.concurrent.TimeoutException: o3fs() timed out after 60 seconds
```
Initial `selectContainer` has correctly found none:
```
2024-01-08 10:08:41,553 [main] WARN  container.ContainerManagerImpl (ContainerManagerImpl.java:getMatchingContainer(344)) - Container allocation failed on pipeline=Pipeline[ Id: 30c296b9-71b9-4744-8977-9b77b35a0eb3, Nodes: e6c09ac7-730a-4058-a1a8-e64ffc2fb789(fv-az1117-812.frmogvfxo1lepnjzqgguis2xib.c …
```
> HDDS-10086. Intermittent timeout in TestSafeMode

- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/conf/TestHddsConfServlet.java
- pom.xml
TestHddsConfServlet has an unnecessary dependency on hadoop-thirdparty.
```
...
import org.apache.hadoop.http.HttpServer2;
import org.apache.hadoop.thirdparty.com.google.common.base.Strings;
import org.apache.hadoop.util.XMLUtils;
...
```
Ozone code is supposed to use guava directly and from hadoop-thirdparty.
https://issues.apache.org/jira/browse/HDDS-10099
CI.
> HDDS-10099. TestHddsConfServlet unnecessarily depends on hadoop-thirdparty

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerImpl.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMDbCheckpointServlet.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMStartupWithBucketLayout.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmConf.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmContainerLocationCache.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmInit.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmMetrics.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotDisabled.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotDisabledRestart.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAWithAllRunning.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAWithStoppedNodes.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerListVolumes.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestScmSafeMode.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestSnapshotBackgroundServices.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerRatisRequest.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/service/TestRangerBGSyncService.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneManagerSnapshotAcl.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneSnapshotRestore.java
Add static import for assertions and mocks in client integration tests
```
```
and
```
```
and
```
// also:
```
makes the code more readable (shorter lines, less wrapping).
[HDDS-10068](https://issues.apache.org/jira/browse/HDDS-10068)
https://github.com/wzhallright/ozone/actions/runs/7460449894
> HDDS-10068. Add static import for assertions and mocks in OM integration tests

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerDoubleBuffer.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerDoubleBuffer.java
In `FlushNotifier`, it add a new latch to the `flushLatches` set for each `await()` call.
We may reduce the number of objects by using `CompletableFuture`. Then, the `await()` calls waiting for the same flush will use for the same future.
HDDS-10039
> HDDS-10039. Remove the flushLatches set from FlushNotifier.

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CloseContainerCommandHandler.java
Currently CloseContainerCommandHandler reports error in log when its ContainerController.getContainer() returns null. This was probably a container that never got created as documented in [HDDS-9550](https://issues.apache.org/jira/browse/HDDS-9550)/[HDDS-9600](https://issues.apache.org/jira/browse/HDDS-9600). Thus we'd like to change [this log message](https://github.com/apache/ozone/blob/52236b152ba4529cf3050d2baee4d50c6722d73b/hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CloseContainerCommandHandler.java#L105) to info with a note that the container may not have been created. (currently the error log stands out when it is probably not a real issue.) We could revisit this log later when issue …
> HDDS-9958. Improve log for container not found in CloseContainerCommandHandler

- hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - ListKey Metrics.json
Created a new dashboard and added visualisations for all the required listKeys Metrics
https://issues.apache.org/jira/browse/HDDS-9309
The patch has been tested over a cluster. After ploting and configuring all mentioned listKeys Metrics on Grafana, the dashboard looks like :
> HDDS-9309. Dashboard for list key operations.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/upgrade/HDDSLayoutFeature.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/HddsVolume.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/AbstractDatanodeDBDefinition.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/AbstractDatanodeStore.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeSchemaOneDBDefinition.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeSchemaThreeDBDefinition.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeSchemaTwoDBDefinition.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeStore.java
Skeleton code for supporting incremental chunk list in PutBlock. See HDDS-8047 for the problem description and design doc.
* Add a new rocksdb table lastChunkInfoTable to store the last, in-progress, partial chunk of blocks. (Question: does adding a new table require a new schema version v4? do we need additional code to support upgrade?)
* Add a Client configuration switch incremental.chunk.list for clients to send incremental chunk list in PutBlock.
* Add a new client version INCREMENTAL_CHUNK_LIST_SUPPORT (this version change may not be required)
https://issues.apache.org/jira/browse/HDDS-9750
Skeleton code. No functional change.
> HDDS-9750. [hsync] Make Putblock performance acceptable - Skeleton code

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCloseContainerHandler.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestDeleteContainerHandler.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestRefreshVolumeUsageHandler.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/TestCSMMetrics.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/metrics/TestContainerMetrics.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/metrics/TestDatanodeQueueMetrics.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/server/TestSecureContainerServer.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/ratis/TestDnRatisLogParser.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/volume/TestDatanodeHddsVolumeFailureToleration.java
=> Migrate Junit4 to Junit5
=> Migrated the following test classes to JUnit5
++++
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCloseContainerHandler.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestDeleteContainerHandler.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestRefreshVolumeUsageHandler.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/TestCSMMetrics.java
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/metrics/TestContainerMetrics.java …
> HDDS-9835. Migrate simple datanode integration tests to JUnit5

- hadoop-ozone/integration-test/pom.xml
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHASnapshot.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOmSnapshot.java
- hadoop-ozone/ozone-manager/pom.xml
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestSstFilteringService.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDiffManager.java
- pom.xml
Awaitility (third-party library) is used 7 times in 4 test classes.
Alternatives:
* `GenericTestUtils.waitFor`, used by 268 callers.
* `LambdaTestUtils.await`, used by 19 callers.
* `JavaUtils.attempt` (prod. utility in Ratis)
This PR replaces most `Awaitility.await` calls with `LambdaTestUtils.await` (which most resembles Awaitility of the three alternatives), and one call (where a void assertion is used) with `attempt`.
We can then remove this dependency (and need to add `hamcrest`, which is also required by other tests, and was a transitive dependency of Awaitility).
https://issues.apache.org/jira/browse/HDDS-10102
CI:
https://github.com/adoroszlai/ozone/actions/runs/7478683757
> HDDS-10102. Replace Awaitility with existing utils

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisContainerReplicaCount.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/VulnerableUnhealthyReplicasHandler.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisUnderReplicationHandler.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestVulnerableUnhealthyReplicasHandler.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestDatanodeAdminMonitor.java
A `QUASI_CLOSED` container may have `UNHEALTHY` replicas with the correct sequence ID which have unique origin Datanodes. If any of these `UNHEALTHY` replicas is being taken offline, then it needs to be replicated to another DN for decommission to progress. Currently, decommission will simply proceed without replication, and such an `UNHEALTHY` replica will be lost.
We try to save such `UNHEALTHY` replicas because in the future HDDS may have the ability to restore these replicas to a healthy state. Then, these replicas can be used to achieve quorum and close the `QUASI_CLOSED` container.
This PR makes some changes in `VulnerableUnhealthyReplicasHandler`. Previously, it was only queueing the container if the healthy ones didn't have the correct sequence ID. Now, it checks if:
1. …
> HDDS-10113. UNHEALTHY replicas of QUASI_CLOSED container with unique origins should be handled during decommission

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/token/ContainerTokenIdentifier.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/token/OzoneBlockTokenIdentifier.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/token/ShortLivedTokenIdentifier.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/token/ShortLivedTokenVerifier.java
Remove unnecessary heap allocation associated with block token verification in DataNode.
Rewrite part of token verification code to use the underlying byte array directly. Avoid certain input/output stream objects that internally allocates sizable heap (4KB) each.
(I wanted to get rid of or optimize Token.decodeFromUrlString too, because BaseNCodec.ensureBufferSize allocates a 8192 byte buffer, which is overkill for this use case. This is another 1.x% overhead but I haven't find a way to remove it)
https://issues.apache.org/jira/browse/HDDS-10054
Ran with freon hsync workload and verified the change does remove heap allocation using profiler.
> HDDS-10054. Reduce DataNode token verification heap allocation cost.

- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/http/TestRatisDropwizardExports.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/ha/GrpcOMFailoverProxyProvider.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/ha/OMFailoverProxyProviderBase.java
- pom.xml
Mockito has been upgraded to 3.x,  but the `pom.xml` tag still named mockito2.version. Maybe it should be renamed to mockito3.version.And fixed some typos in this PR.
[HDDS-10116](https://issues.apache.org/jira/browse/HDDS-10116)
https://github.com/wzhallright/ozone/actions/runs/7497056961
> HDDS-10116. Rename mockito2.version to mockito.version in pom.xml and fix typos

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockDataStreamOutput.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ECBlockOutputStream.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/storage/ContainerProtocolCalls.java
Block token is serialized for every output stream client request. Cache it to avoid the waste.
The profiler report found that a noticeable amount of heap allocation is attributed to block token serialization. Because the block token is never updated, we can cache the serialized block token once and it use it repeatedly.
The change is applicable in both WriteChunk and PutBlock request.
https://issues.apache.org/jira/browse/HDDS-10003
Verified on a real cluster that the heap allocation is removed.
> HDDS-10003. [hsync] Cache serialized block token in output stream to reduce heap consumption

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/conf/OzoneConfiguration.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/conf/TestOzoneConfiguration.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMBlockProtocolServer.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeProtocolServer.java
The SCM service contains multiple RPC types, they are: SCMClientProtocolServer, SCMBlockProtocolServer, SCMDatanodeProtocolServer.
When initializing these RPCs, the same configuration is used to define the number of handlers.
"ozone.scm.handler.count.key"
Different configurations should be used in different environments, which will be more friendly.
for example:
"ozone.scm.client.handler.count.key"
"ozone.scm.block.handler.count.key"
"ozone.scm.datanode.handler.count.key"
https://issues.apache.org/jira/browse/HDDS-10088
It is necessary to ensure that the unit test passes successfully.
> HDDS-10088. Refine the number of handlers for each RPC of SCM

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeConfiguration.java
`hdds.datanode` is a default prefix. Repeated declarations lead to duplicate. 
https://issues.apache.org/jira/browse/HDDS-10105
no need
> HDDS-10105. Remove duplicate hdds.datanode. prefix from check.empty.container.dir.on.delete

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerSelectionCriteria.java
Renamed the following method to `isECContainerAndLegacyRMEnabled`. `isECContainer` was misleading, because Container Balancer supports balancing EC containers. This PR only changes the method names and updates java doc. No logic change.
```
private boolean isECContainer(ContainerInfo container) {
return container.getReplicationType().equals(HddsProtos.ReplicationType.EC)
&& replicationManager.getConfig().isLegacyEnabled();
}
```
https://issues.apache.org/jira/browse/HDDS-10085
Ran existing tests.
> HDDS-10085. Improve Method Name in ContainerBalancerSelectionCriteria

- hadoop-ozone/dev-support/checks/junit.sh
- hadoop-ozone/dist/src/shell/ozone/ozone
- hadoop-ozone/dist/src/shell/ozone/ozone-functions.sh
- pom.xml
Several tests fail when run with Java 17 due to:
```
java.lang.ExceptionInInitializerError
at org.apache.hadoop.ozone.common.TestChecksumImplsComputeSameValues.testCRC32CImplsMatch(TestChecksumImplsComputeSameValues.java:66)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field boolean java.nio.ByteBuffer.isReadOnly accessible: module java.base does not "opens java.nio" to unnamed module @75eeccf5
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java …
```
> HDDS-10123. InaccessibleObjectException in tests using ChecksumByteBufferImpl with Java 17

- hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigFileGenerator.java
Check fields annotated with `@Config` in classes with `@ConfigGroup` such that the `Config#key` field does not begin with the `ConfigGroup#prefix`.
https://issues.apache.org/jira/browse/HDDS-10125
Verified that build fails without the fix for HDDS-10105:
```
[INFO] --- maven-compiler-plugin:3.9.0:compile (default-compile) @ hdds-container-service ---
...
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeConfiguration.java:[551,19] @Config(key = "hdds.datanode.check.empty.container.dir.on.delete") should not duplicate prefix from @ConfigGroup("hdds.datanode") …
```
> HDDS-10125. Verify config key does not duplicate prefix

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientFactory.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientManager.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/IOUtils.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/replication/TestContainerReplication.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/ChunkKeyHandler.java
`ChunkKeyHandler` may not release `xceiverClient` (and thus close `ManagedChannel`) if exception is encountered.
This can be reproduced by running `TestOzoneDebugShell` with Java 17 with the fix for HDDS-10123.  `ChunkKeyHandler` throws exception due to GSON not being able to set some fields via reflection (HDDS-10122).  `xceiverClient` is not released, and test log shows:
```
SEVERE: *~*~*~ Previous channel ManagedChannelImpl{logId=209, target=127.0.0.1:15011} was not shutdown properly!!! ~*~*~*
Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
at org.apache.ratis.thirdparty.io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:102)
at …
```
> HDDS-10117. ChunkKeyHandler does not close XceiverClient in case of exception

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/StringCodecBase.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOMDBDefinition.java
`RocksDatabase` already has a non-static `columnFamilies` which has `ColumnFamilyHandle`. The static `dbNameToCfHandleMap` should be removed for better performance and cleaner code.
HDDS-10107
> HDDS-10107. Remove the static dbNameToCfHandleMap from RocksDatabase.

- hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/GenericTestUtils.java
- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneClient.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneAtRestEncryption.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestSecureOzoneRpcClient.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestStorageContainerManagerHA.java
Several client tests that compare volume/bucket creation time to `Instant.now()` as of the start of the test failed because `now()` may include a nanosecond component, while creation time is recorded with millisecond precision only.
https://github.com/apache/ozone/blob/02bfa7f91d9442381503ec001f28c2de19c2897b/hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java#L171
This is fixed by using `Instant.ofEpochMillis` to record test start time, too.
https://issues.apache.org/jira/browse/HDDS-10119
Tested locally with Java 17:
```
$ JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 \
./hadoop-ozone/dev-support/checks/junit.sh -am -pl :ozone-integration-test -DexcludedGroups=unhealthy \
-Dtest="TestOzoneAtRestEncryption,TestOzoneClient,TestOzoneRpcClient,TestOzoneRpcClientW …
```
> HDDS-10119. Assertions on object creationTime fail with Java 17

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFSInputStream.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemPrefixParser.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemWithStreaming.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsSnapshot.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/upgrade/TestScmHAFinalization.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/OzoneTestUtils.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestBlockTokensCLI.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestContainerOperations.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestContainerStateMachineIdempotency.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMiniOzoneOMHACluster.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMultipartObjectGet.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/debug/TestLDBCli.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestDataValidate.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestFreonWithDatanodeFastRestart.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestFreonWithPipelineDestroy.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestHadoopDirTreeGenerator.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestHadoopNestedDirGenerator.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestOMSnapshotDAG.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestOmBucketReadWriteKeyOps.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/parser/TestOzoneHARatisLogParser.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconInsightsForDeletedDirectories.java
Add static import for assertions and mocks in hadoop-hdds (only after all other subtasks for specific hadoop-hdds submodules are done).
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFSInputStream.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemPrefixParser.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemWithStreaming.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsSnapshot.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/upgrade/TestScmHAFinalization.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/OzoneTestUtils.java
- …
> HDDS-9997. Add static import for assertions and mocks in misc. integration tests

- hadoop-ozone/integration-test/dev-support/findbugsExcludeFile.xml
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestSecureOzoneManager.java
Fix `TestSecureOzoneManager` failure when run with Java 17 (see HADOOP-17910 for similar issue):
```
AssertionFailedError: expected: <Can't get SCM signed certificate. omRpcAdd: om-unknown:9862> but was: <Can't get SCM signed certificate. omRpcAdd: om-unknown/<unresolved>:9862>
```
Additionally, some cleanup (as separate commits).
https://issues.apache.org/jira/browse/HDDS-10130
```
$ JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 \
./hadoop-ozone/dev-support/checks/junit.sh -DexcludedGroups=unhealthy \
-am -pl :ozone-integration-test -Dtest='TestSecureOzoneManager'
...
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.891 s -- in org.apache.hadoop.ozone.om.TestSecureOzoneManager
```
CI (still with Java 8):
https://github.com/adoroszlai/ozone/actions/runs/7538490881
> HDDS-10130. TestSecureOzoneManager.testSecureOmInitFailure fails with Java 17

- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestTarContainerPacker.java
Fix `TestTarContainerPacker` for Java 17:
```
FileNotFoundException: target/test/data/packer-source-dir/111/metadata/db/../db_file (No such file or directory)
at java.base/java.io.FileOutputStream.open0(Native Method)
...
at org.apache.hadoop.ozone.container.keyvalue.TestTarContainerPacker.writeSingleFile(TestTarContainerPacker.java:388)
at org.apache.hadoop.ozone.container.keyvalue.TestTarContainerPacker.writeDbFile(TestTarContainerPacker.java:379)
at org.apache.hadoop.ozone.container.keyvalue.TestTarContainerPacker.unpackContainerDataWithInvalidRelativeDbFilePath(TestTarContainerPacker.java:319)
```
https://issues.apache.org/jira/browse/HDDS-10131
```
$ JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 \
./hadoop-ozone/dev-support/checks/junit.sh -DexcludedGroups=unhealthy \
-am -pl …
```
> HDDS-10131. TestTarContainerPacker fails with Java 17

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ListIterator.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
This PR fixes the Intermittent failure in `TestOzoneRpcClientAbstract.testListSnapshot`.
`TestOzoneRpcClientAbstract.testListSnapshot` creates 20 snapshots using `createSnapshot` API and asserts the count of same using `listSnapshot` API. This assertion of count fails intermittently.
`listSnapshot` API uses the `org.apache.hadoop.ozone.om.ListIterator.MinHeapIterator` which internally uses both CacheIterator and DBIterator and DBIterator had the logic of checking if rocks DB key is present in cache in `org.apache.hadoop.ozone.om.ListIterator.DbTableIter#getNextKey`, this checks the cache from table cache which may be intermittently flushed which makes the addition of duplicate entry in `org.apache.hadoop.ozone.om.ListIterator.MinHeapIterator`.  So to fix this, we should use the pre-loaded …
> HDDS-9967. Intermittent failure in TestOzoneRpcClientAbstract.testListSnapshot.

- hadoop-hdds/rocks-native/pom.xml
- hadoop-ozone/dev-support/checks/native.sh
Download of `zlib` fails with `403 Forbidden` in CI:
```
Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.7.1:wget (zlib source download) on project hdds-rocks-native: Download failed with code 403: Forbidden
```
The same goal works locally:
```
mvn -N com.googlecode.maven-download-plugin:download-maven-plugin:1.7.1:wget \
-Ddownload.url=https://zlib.net/fossils/zlib-1.2.13.tar.gz \
-Ddownload.outputDirectory=. \
-Ddownload.outputFileName=zlib-1.2.13.tar.gz
```
The patch allows overriding the official URL by setting `-Dzlib.url`, and does so in `native.sh`, which is run in `unit (native)` check in CI.
https://issues.apache.org/jira/browse/HDDS-10157
CI (native only):
https://github.com/adoroszlai/ozone/actions/runs/7568517329/job/20609886518
Regular CI …
> HDDS-10157. Download zlib fails with 403 Forbidden in CI

- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestSCMSafeModeManager.java
Add unit tests to  show rule status of scm safemode.
https://issues.apache.org/jira/browse/HDDS-3849
> HDDS-3849. Add tests to show rule status of scm safemode.

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
This is a minor clean up, the logic for calculating paths is reimplemented in many places. Using HDDS-10153 as an umbrella Jira to clean up the instances. 
https://issues.apache.org/jira/browse/HDDS-10155
Existing tests
> HDDS-10155. Use getOzoneKey when calculating the paths for keys

- hadoop-hdds/docs/content/tools/Admin.md
- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MockOmTransport.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/ListOpenFilesResult.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OpenKeySession.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OzoneManagerProtocol.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
- hadoop-ozone/dist/src/main/compose/ozone/docker-config
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmMetrics.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHAWithFSO.java
- hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
- hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/audit/OMAction.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMetrics.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmMetadataManager.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/ListOpenFilesSubCommand.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/OMAdmin.java
Add Ozone Admin CLI `listopenfiles` as a debug command for admins and devs. e.g.
```bash
$ ozone admin om lof --service-id=om-service-test1 --length=3 --prefix=/volumelof/buck1
5 total open files (est.). Showing 3 open files (limit 3) under path prefix:
/volume-lof/buck1
Client ID		Creation time	Hsync'ed	Open File Path
111726338148007937	1704808626523	No		/volume-lof/buck1/-9223372036854774527/key0
111726338151415810	1704808626578	No		/volume-lof/buck1/-9223372036854774527/key1
111726338152071171	1704808626588	No		/volume-lof/buck1/-9223372036854774527/key2
To get the next batch of open keys, run:
ozone admin om lof -id=om-service-test1 --length=3 --prefix=/volume-lof/buck1 --start=/-9223372036854775552/-9223372036854775040/-9223372036854774527/key2/111726338152071171
```
JSON output: …
> HDDS-8830. Add admin CLI to list open files

- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMDBCheckpointServlet.java
Fix NPE on OMDBCheckpointServlet caused by possible null SstFilteringService. The null SstFilteringService is due to configuration ozone.filesystem.snapshot.enabled=false or ozone.snapshot.filtering.service.interval=-1. 
When NPE is thrown in the call of OMDBCheckpointServlet.Lock, this cause the subsequent call to OMDBCheckpointServlet.Lock.lock to block indefinitely since the previous call that triggered the NPE did not release the lock held on keyDeletingService.
The current solution is a simple nullity check. There might be better solution to prevent the NPE than just a nullity check.
https://issues.apache.org/jira/browse/HDDS-10138
Manual test.
Clean CI: https://github.com/ivandika3/ozone/actions/runs/7550769000
> HDDS-10138. NPE for SstFilteringService in OMDBCheckpointServlet.Lock

- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/DiskUsageSubCommand.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/FileSizeDistSubCommand.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/NSSummaryAdmin.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/QuotaUsageSubCommand.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/SummarySubCommand.java
This PR fixes the Ozone Client connection leak by closing all opened client connections in NSSummaryAdmin.java
NSSummaryAdmin commands leaves the Ozone client connections open which is not a good practice and may consume resources. So. this PR fixes that by closing all opened Ozone client connections.
https://issues.apache.org/jira/browse/HDDS-9944
This patch was tested using existing integration test `org.apache.hadoop.ozone.shell.TestNSSummaryAdmin`
> HDDS-9944. NSSummary commands should close OzoneClient.

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
isKeyPresentInTable should use the constructor with prefix. 
The table iterator implemented over rocksDB can seek to the prefix if provided at the time to construction. This can avoid wasteful seekToFirst behavior that is part of the construction of the iterator.
https://issues.apache.org/jira/browse/HDDS-10154
Existing tests
> HDDS-10154. isKeyPresentInTable should use the constructor with prefix

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMPerformanceMetrics.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
Correct two metric names within OMPerformanceMetrics:
- `createOmResoonseLatencyNs` -> `createOmResponseLatencyNs`
- `validateAndUpdateCacneLatencyNs` -> `validateAndUpdateCacheLatencyNs`
https://issues.apache.org/jira/browse/HDDS-10162
No need
> HDDS-10162. Correct the metric names within OMPerformanceMetrics

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerDoubleBuffer.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerStateMachine.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerProtocolServerSideTranslatorPB.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerDoubleBuffer.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerDoubleBufferWithDummyResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerDoubleBufferWithOMResponse.java
https://github.com/apache/ozone/blob/6f6ec580743208ba4c09e9b55b94f68cfefd2d5d/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerDoubleBuffer.java#L195-L201
The OzoneManagerDoubleBuffer constructor above has many parameter.  We may reduce it by passing the Builder.
We will also clean up the code, add javadoc and fix typos.
HDDS-10171
> HDDS-10171. Fix checkstyle:parameternumber in OzoneManagerDoubleBuffer.

- hadoop-ozone/dist/src/main/compose/upgrade/test.sh
- hadoop-ozone/dist/src/main/compose/xcompat/clients.yaml
- hadoop-ozone/dist/src/main/compose/xcompat/test.sh
Add 1.4.0 to `xcompat` test matrix.
Change `upgrade` test to start from 1.4.0 instead of 1.3.0.
https://issues.apache.org/jira/browse/HDDS-10168
```
OZONE_ACCEPTANCE_SUITE=compat ./hadoop-ozone/dev-support/checks/acceptance.sh
open target/acceptance/log.html
```
CI:
https://github.com/adoroszlai/ozone/actions/runs/7593375483
> HDDS-10168. Add Ozone 1.4.0 to compatibility acceptance tests

- hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestBlockInputStream.java
- hadoop-hdds/client/src/test/java/org/apache/hadoop/ozone/client/io/TestECBlockReconstructedStripeInputStream.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/common/TestChecksumByteBuffer.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/server/http/TestHttpServer2Metrics.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestDeletedBlockLog.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackAware.java
- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/checksum/TestReplicatedBlockChecksumComputer.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/contract/AbstractContractSeekTest.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/AbstractRootedOzoneFileSystemTest.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestLeaderChoosePolicy.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMultipartObjectGet.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestWatchForCommit.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestDeletedBlocksTxnShell.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/TestReconUtils.java
HDDS-10151: Replace single-use Random objects with RandomUtils in test classes
Replace single-use Random objects by RandomUtils or similar. This is a code optimization task aimed at improving the efficiency of the codebase.
https://issues.apache.org/jira/browse/HDDS-10151
Each test class are manually tested using 
`mvn test -Dtest=ClassName`
All the tests passed after the code change.
For the Abstract classes, tests passed for the sub-classes that inherit from the superclasses after code change, for example:
**TestOzoneContractLegacy** extends AbstractOzoneContractTest extends AbstractContractSeekTest
**TestOFSWithOMRatis** extends AbstractRootedOzoneFileSystemTest
**RandomUtils** cannot directly set a seed. 
In the below test classes …
> HDDS-10151. Replace single-use Random objects with RandomUtils in test classes

- hadoop-ozone/dev-support/checks/junit.sh
Repeated tests in `junit.sh` should fail fast if no tests are executed in the first iteration.  The goal is to indicate if the wrong test filter was used (e.g. abstract test class).
https://issues.apache.org/jira/browse/HDDS-10080
Non-existent class:
```
$ ITERATIONS=3 OZONE_REPO_CACHED=true \
./hadoop-ozone/dev-support/checks/junit.sh \
-am -pl :hdds-config -Dtest='NoSuchTest'
...
[INFO] BUILD SUCCESS
...
Iteration 1 exit code: 1
$ cat target/unit/iteration1/summary.txt 
No tests were run
```
Non-existent method in existing class:
```
$ ITERATIONS=3 OZONE_REPO_CACHED=true \
./hadoop-ozone/dev-support/checks/junit.sh \
-am -pl :hdds-config -Dtest='TestConfigFileAppender#noSuchTest'
...
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
...
[INFO] BUILD SUCCESS
...
Iteration 1 exit …
```
> HDDS-10080. Let junit.sh fail if no tests were matched in repeated run

- .github/workflows/ci.yml
- pom.xml
* Use `plexus-archiver` 4.2.2 for `maven-dependency-plugin`.  4.2.3+ has broken behavior on case-insensitive filesystem (e.g. macOS).  https://github.com/codehaus-plexus/plexus-archiver/commit/efd980ddaf3d98ebb19e06805258f9f978c9ebc1
* Add compilation on macOS to the test matrix.
https://issues.apache.org/jira/browse/HDDS-10178
Compile on macOS failed without the fix:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.6.1:unpack (include-dependencies) on project ozone-filesystem-hadoop2: Error unpacking file: /Users/runner/work/ozone/ozone/hadoop-ozone/ozonefs-shaded/target/ozone-filesystem-shaded-1.5.0-SNAPSHOT.jar to: /Users/runner/work/ozone/ozone/hadoop-ozone/ozonefs-hadoop2/target/classes: Error while expanding …
```
> HDDS-10178. Shaded Jar build failure in case-insensitive filesystem

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/TrashOzoneFileSystem.java
HDDS-6796. Extract method for building OMRequest in TrashOzoneFileSystem
- Declare the createOMRequest Throws IOException
- In the calling method:
```
omRequest = createOMRequest(OzoneManagerProtocolProtos.Type.RenameKey)
.setRenameKeyRequest(renameKeyRequest)
.build();
```
https://issues.apache.org/jira/browse/HDDS-6796
Locally build successfully by:
mvn clean install -DskipTests -DskipShade
CI passed on the fork git repo.)
> HDDS-6796. Extract method for building OMRequest in TrashOzoneFileSystem

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestSnapshotDeletingService.java
After #5986, pendingEvictionList has been removed and assertion on pendingEvictionList has been removed as well which was causing Intermittent test failure. This change is to remove flaky tag from the test.
https://issues.apache.org/jira/browse/HDDS-9288
Ran the test on local repo 10X10 times: https://github.com/hemantk-12/ozone/actions/runs/7563200213
> HDDS-9288. Intermittent failure in TestSnapshotDeletingService#testMultipleSnapshotKeyReclaim

- hadoop-hdds/docs/content/feature/Decommission.zh.md
Translated the documentation for Decommissioning in Ozone to Mandarin Chinese
https://issues.apache.org/jira/browse/HDDS-9181
> HDDS-9181. Provide documentation for Decommissioning in Mandarin Chinese

- hadoop-hdds/docs/content/feature/dn-merge-rocksdb.zh.md
Translated "Merge Container RocksDB in DN" doc into Mandarin Chinese.
https://issues.apache.org/jira/browse/HDDS-7557
Verified by lanching the Chinese version in local browser.
> HDDS-7557. Translate "Merge Container RocksDB in DN" doc to Mandarin Chinese

- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisUnderReplicationHandler.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/TestCSMMetrics.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/metrics/TestContainerMetrics.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/metrics/TestDatanodeQueueMetrics.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainerWithTLS.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/server/TestContainerServer.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/server/TestSecureContainerServer.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/ratis/TestDnRatisLogParser.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/volume/TestDatanodeHddsVolumeFailureToleration.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestOmBucketReadWriteFileOps.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestDeletedBlocksTxnShell.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneContainerUpgradeShell.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneDebugShell.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestTransferLeadershipShell.java
- hadoop-ozone/interface-storage/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmMultipartKeyInfoCodec.java
- hadoop-ozone/interface-storage/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmPrefixInfo.java
Add static import for assertions and mocks in all classes missed by other subtasks.
https://issues.apache.org/jira/browse/HDDS-10186
CI:
https://github.com/adoroszlai/ozone/actions/runs/7617089021
> HDDS-10186. Add missing static import for assertions and mocks

- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/AbstractDatanodeDBDefinition.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeStore.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeStoreSchemaThreeImpl.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeStoreSchemaTwoImpl.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeStoreWithIncrementalChunkList.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/impl/TestBlockManagerImpl.java
- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MockDatanodeStorage.java
- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MockXceiverClientSpi.java
Implement DataNode side change for HDDS-8047 incremental chunk list for PutBlock. See HDDS-8047 for the problem description and design doc.
* This PR depends on HDDS-9750 / #5661 
* Test code and supporting mock classes. Tests are enabled if schema is v3.
* Implementation details 
[PutBlock metadata optimization.pdf](https://github.com/apache/ozone/files/13443985/PutBlock.metadata.optimization.pdf)
https://issues.apache.org/jira/browse/HDDS-9751
* New unit tests in TestBlockManagerImpl
* Full cluster HBase ycsb workload test
> HDDS-9751. [hsync] Make Putblock performance acceptable - DataNode side

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOmSnapshot.java
`TestOmSnapshot.testSnapDiffWithMultipleSSTs` was failing all the time because snapshot diff is an async API and when a job is submitted for the first time, it always returns empty diff list with IN_PROGRESS status. User is supposed to make second call to fetch the results, once job is DONE. TestOmSnapshot.testSnapDiffWithMultipleSSTs was only making one call which only submits the request and returned empty diff response as mentioned above.
This change is to call snap diff after job to DONE to fetch complete diff report.
HDDS-8005
* Ran the test locally and on fork: https://github.com/hemantk-12/ozone/actions/runs/7620429542
* Flaky-test-check workflow run: https://github.com/hemantk-12/ozone/actions/runs/7630045775
> HDDS-8005. Fixed intermittent failure in TestOmSnapshot.testSnapDiffWithMultipleSSTs

- hadoop-hdds/interface-client/src/main/resources/proto.lock
- hadoop-ozone/csi/src/main/resources/proto.lock
Some `proto.lock` files were not updated for the 1.4.0 release.  This happened because the new v0.17.0 version of `protolock` introduced a new check, which is failing for `DatanodeClientProtocol.proto` and `csi.proto`:
```
CONFLICT: "data" was moved into oneof "responseData" [DatanodeClientProtocol.proto]
CONFLICT: "dataBuffers" was moved into oneof "responseData" [DatanodeClientProtocol.proto]
CONFLICT: "block" was moved into oneof "access_type" [csi.proto]
CONFLICT: "mount" was moved into oneof "access_type" [csi.proto]
CONFLICT: "rpc" was moved into oneof "type" [csi.proto]
CONFLICT: "rpc" was moved into oneof "type" [csi.proto]
CONFLICT: "service" was moved into oneof "type" [csi.proto]
CONFLICT: "snapshot" was moved into oneof "type" [csi.proto]
CONFLICT: "volume" was moved into …
```
> HDDS-10187. Update hdds-interface-client proto.lock for 1.4

- .github/workflows/intermittent-test-check.yml
Build Ozone in a separate job, and reuse in all parallel test splits of flaky-test-check.  Skip building some parts not necessary for tests (Recon frontend, shaded jars).
Previously all parallel splits spent time building Ozone before running the tests.
This reduces:
* total workflow time (sum of job run times)
* wall-clock time (elapsed time from start to end)
* output size (~4000 lines less per parallel run)
Reducing output also makes checking for test failures in Github UI easier (not having to scroll through those ~4000 lines).
https://issues.apache.org/jira/browse/HDDS-10175
https://github.com/adoroszlai/ozone/actions/runs/7596924232
> HDDS-10175. Pre-build Ozone in flaky-test-check

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmBucketArgs.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHAWithFSO.java
- hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/common/BekInfoUtils.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketCreateRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketSetPropertyRequest.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/ClientProtocolStub.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/bucket/BucketCommands.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/bucket/SetEncryptionKey.java
Due to a known bug: '[HDDS-7449](https://issues.apache.org/jira/browse/HDDS-7449). Avoid overwriting bucket encryption properties when quota/replication config are set on an existing bucket', there can be consumers on a previous version of Ozone who could possibly run into this issue of losing bucket encryption properties when they (re)set quota or bucket replication configurations - which is a critical issue.
Through this patch, we can reset the BEK (bucket encryption key) of buckets affected by this bug through Ozone shell (`ozone sh bucket set-encryption-key -k <enckey> <vol>/<buck>`).
It does not change any other properties of the bucket or the properties of existing keys in the given bucket. 
- The properties of the older keys in the bucket remain as is.
- If any keys are added to …
> HDDS-10142. Add hidden command to set bucket encryption key to fix HDDS-7449

- pom.xml
Ozone build configures 20 minutes fork timeout:
https://github.com/apache/ozone/blob/73e6f90aae4dc22a265361b9a63ccb25a5e6919a/pom.xml#L286
but it's not applied, because the facility to check the fork is disabled by default:
> Since 3.0.0-M4 the process checkers are disabled ([source](https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#enableProcessChecker))
So instead of killing the fork after 20 minutes, any runaway test is caught only by the Github job timeout, 2.5 hours for integration tests.  The problem is even worse for the `flaky-test-check`, which gives more time (6 hours) to jobs.
This change enables the process checkers.
However, current version of Surefire doesn't seem to kill the fork after timeout even with process checkers enabled.  Thus we need to …
> HDDS-10174. Enable Surefire process checker

- .github/workflows/intermittent-test-check.yml
If `flaky-test-check` is triggered for a specific method, it checks if the method exists in the test class.  This does not work for test methods inherited from parent class.
```
Test method testValidateBlockLengthWithCommitKey does not exist in TestSecureOzoneRpcClient.java.Stopping!
```
https://github.com/adoroszlai/ozone/actions/runs/7431424440/job/20222159860#step:3:33
However, the same test method is accepted for the parent class, which cannot be run, since it's abstract.
I propose removing this safety check.  If the specified method cannot be run, build output will show `Tests run: 0`.
https://issues.apache.org/jira/browse/HDDS-10079
https://github.com/adoroszlai/ozone/actions/runs/7431422827
> HDDS-10079. Remove validation of test method in flaky-test-check

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/AbstractDatanodeStore.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBStoreBuilder.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStore.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/utils/db/managed/TestRocksObjectLeakDetector.java
When config set: 
```xml
<property>
<name>ozone.metastore.rocksdb.statistics</name>
<value>ALL</value>
</property> 
```
ManagedStatistics not closed properly in OM and DN:
```java
2024-01-22 18:34:22,137 [LeakDetector-ManagedRocksObject0] WARN org.apache.hadoop.hdds.utils.db.managed.ManagedRocksObjectUtils: ManagedStatistics is not closed properly
StackTrace for unclosed instance: org.apache.hadoop.hdds.utils.db.managed.ManagedStatistics.<init>(ManagedStatistics.java:30)
org.apache.hadoop.hdds.utils.db.DBStoreBuilder.getDefaultDBOptions(DBStoreBuilder.java:418)
org.apache.hadoop.hdds.utils.db.DBStoreBuilder.build(DBStoreBuilder.java:209)
org.apache.hadoop.ozone.om.OmMetadataManagerImpl.loadDB(OmMetadataManagerImpl.java:607)
org.apache.hadoop.ozone.om.OmMetadataManagerImpl.loadDB(OmMetadata …
```
> HDDS-10184. Fix ManagedStatistics not closed properly

- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancerTask.java
- Enabled the test method `TestContainerBalancerTask` with a fix.
- The small change fixes the testDelayedStart of TestContainerBalancerTask method timing out, the reason why its timing out is because of the fact that sometimes it takes more than 20millisecond to go into waiting state.
So by increasing the waiting time to 40 seconds, I was able to run the test successfully 600 times.
https://issues.apache.org/jira/browse/HDDS-8941
I was able to run the test successfully 600 times.
https://github.com/ArafatKhan2198/ozone/actions/runs/7617671268
https://github.com/ArafatKhan2198/ozone/actions/runs/7617674689
https://github.com/ArafatKhan2198/ozone/actions/runs/7617675944
> HDDS-8941. Intermittent timeout in TestContainerBalancerTask

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/AbstractFindTargetGreedy.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/FindTargetGreedyByNetworkTopology.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/FindTargetGreedyByUsageInfo.java
Simple DEBUG level logging improvement for Container Balancer.
This jira is to improve logging around a Datanode being removed from the collection of potential targets in ContainerBalancer. This can help us understand why a particular Datanode wasn't chosen as a target for container move when we think it's the optimal choice.
A Datanode may not be selected in multiple situations - it has already had enough size moved into it and has reached the limit, doesn't follow placement policy, already has the container's replica etc. I saw a situation in which a particular Datanode was the best choice when considering network distance and was also a potential target, but balancer did not choose it. I want to debug why this happened and more logging will help with this. …
> HDDS-10198. Improve Logging in AbstractFindTargetGreedy

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/S3InMemoryCache.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/S3SecretValue.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestSecureOzoneRpcClient.java
- hadoop-ozone/interface-storage/src/test/java/org/apache/hadoop/ozone/om/helpers/TestS3SecretValueCodec.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/S3SecretManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/security/OMSetSecretRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/security/S3GetSecretRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/tenant/OMTenantAssignUserAccessIdRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/TestOzoneDelegationTokenSecretManager.java
- hadoop-ozone/s3-secret-store/src/main/java/org/apache/hadoop/ozone/s3/remote/vault/VaultS3SecretStore.java
- hadoop-ozone/s3-secret-store/src/test/java/org/apache/hadoop/ozone/s3/remote/vault/TestVaultS3SecretStore.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/ClientProtocolStub.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3secret/TestSecretGenerate.java
Revoked S3 secret is stored in the cache as `S3SecretValue` with `null` secret value.  Since the object is mutable, other thread could access the same instance before revocation, and might encounter NPE while trying to convert to protobuf.
```
2024-01-24 09:49:09,063 [om1-OMDoubleBufferFlushThread] ERROR ratis.OzoneManagerDoubleBuffer (ExitUtils.java:terminate(133)) - Terminating with exit status 2: During flush to DB encountered error in OMDoubleBuffer flush thread om1-OMDoubleBufferFlushThread
org.apache.ratis.util.ExitUtils$ExitException: During flush to DB encountered error in OMDoubleBuffer flush thread om1-OMDoubleBufferFlushThread when handling OMRequest: cmdType: SetS3Secret
traceID: ""
success: true
status: OK
SetS3SecretResponse {
accessId: "testUser1accessId1"
secretKey: …
```
> HDDS-10200. OM may terminate due to NPE in `S3SecretValue` proto conversion

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
Avoid `OmMetadataManagerImpl` creating new instance of `S3Batcher` for each S3 secret operation.
https://issues.apache.org/jira/browse/HDDS-10202
CI:
https://github.com/adoroszlai/ozone/actions/runs/7643348101
> HDDS-10202. OmMetadataManagerImpl creates new S3Batcher for each operation

- hadoop-ozone/dist/src/main/license/bin/LICENSE.txt
`hadoop-ozone/dist/src/main/license/bin/LICENSE.txt` has some packages under the wrong license (CDDL instead of EPL):
* [Jersey](https://github.com/eclipse-ee4j/jersey/blob/2.x/README.md#licensing-and-governance)
* [HK2](https://github.com/eclipse-ee4j/glassfish-hk2?tab=License-1-ov-file#readme)
Also, there are duplicate sections for "EPL 2.0" and "CDDL".
https://issues.apache.org/jira/browse/HDDS-10191
> HDDS-10191. Fix some mismatches in LICENSE

- .github/workflows/ci.yml
- .github/workflows/close-pending.yaml
- .github/workflows/comments.yaml
- .github/workflows/dependabot-ci.yml
- .github/workflows/intermittent-test-check.yml
- .github/workflows/pull-request.yml
- .github/workflows/repeat-acceptance.yml
Upgrade all GitHub actions to `v4` (which happens to be the version using Node.js 20 for all of them):
* https://github.com/actions/cache/releases/tag/v4.0.0
* https://github.com/actions/checkout/releases/tag/v4.0.0
* https://github.com/actions/download-artifact/releases/tag/v4.0.0
* https://github.com/actions/setup-java/releases/tag/v4.0.0
* https://github.com/actions/setup-node/releases/tag/v4.0.0
* https://github.com/actions/upload-artifact/releases/tag/v4.0.0
https://issues.apache.org/jira/browse/HDDS-10199
CI run completed normally, artifacts are available.
https://github.com/adoroszlai/ozone/actions/runs/7641885304
> HDDS-10199. Node.js 16 actions are deprecated

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneHAClusterImpl.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestAddRemoveOzoneManager.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHA.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHASnapshot.java
MiniOzoneHAClusterImpl:
getOMLeader() returns current OM leader.
getOMLeader(boolean) optionally waits until OM leader is elected
There are some tests that implement the same "wait for leader OM" logic using the non-waiting getOMLeader(). 
```
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestAddRemoveOzoneManager.java
209:    GenericTestUtils.waitFor(() -> cluster.getOMLeader() != null, 500, 30000);
437:    GenericTestUtils.waitFor(() -> cluster.getOMLeader() != null, 500, 30000);
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHA.java
466:        getCluster().getOMLeader() != null, 500, timeout);
hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHASnapshot.java
126:    await(120_000, …
```
> HDDS-9524. Clean up wait for leader OM in integration tests

- .github/workflows/ci.yml
Increase timeout for `compile` check, which seems to take a lot more time on MacOS, and may intermittently run a bit over 30 minutes.  
Mac: https://github.com/apache/ozone/actions/runs/7631717145/job/20790957028
Linux: https://github.com/apache/ozone/actions/runs/7631717145/job/20790956625
https://issues.apache.org/jira/browse/HDDS-10197
CI:
https://github.com/adoroszlai/ozone/actions/runs/7638587571/job/20811157503
> HDDS-10197. Increase timeout for compile check

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/StateContext.java
While tracing the block deletion logic, I found a possible problem regarding command status update logic.
The cmdStatusMap in StateContext is a ConcurrentHashMap
Currently the update logic for command status is as follows:
```java
public boolean updateCommandStatus(Long cmdId,
Consumer<CommandStatus> cmdStatusUpdater) {
if (cmdStatusMap.containsKey(cmdId)) {
cmdStatusUpdater.accept(cmdStatusMap.get(cmdId));
return true;
}
return false;
}
```
It does not seem correct. Although the get containsKey and get is protected by the ConcurrentHashMap, the CommandStatus retrieved is mutated directly using the cmdStatusUpdater and not protected by the ConcurrentHashMap (Please correct me if I'm mistaken). This might trigger race condition.
We should use atomic operation like computeIfPresent.
Note: …
> HDDS-10210. Ensure atomic update in StateContext#updateCommandStatus

- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java
`TypedTable.putWithBatch` defers closing `CodecBuffer` until the batch is committed.  If value conversion (or `putWithBatch` itself) throws, the buffers are not added to the batch, so they need to be released eagerly.
Example value conversion error:
```
NullPointerException
at org.apache.hadoop.ozone.protocol.proto.OzoneManagerProtocolProtos$S3Secret$Builder.setAwsSecret(OzoneManagerProtocolProtos.java)
at org.apache.hadoop.ozone.om.helpers.S3SecretValue.getProtobuf(S3SecretValue.java:100)
at org.apache.hadoop.hdds.utils.db.DelegatedCodec.toCodecBuffer(DelegatedCodec.java:85)
at org.apache.hadoop.hdds.utils.db.Codec.toDirectCodecBuffer(Codec.java:73)
at org.apache.hadoop.hdds.utils.db.TypedTable.putWithBatch(TypedTable.java:171)
at …
```
> HDDS-10204. TypedTable.putWithBatch may leak if conversion of value throws

- .github/dependabot.yml
Attempt to configure dependabot to have only one PR open for all Recon dependencies at the same time ([docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/customizing-dependency-updates#grouping-dependabot-version-updates-into-one-pull-request)).
Also drop the prefix for Java package updates.  The prefix for Recon is used in the `dependabot-ci` [workflow](https://github.com/apache/ozone/blob/51a7eaec39b7bc61f280bd5512bc184774e2254b/.github/workflows/dependabot-ci.yml#L24), but the one for Java is unnecessary, causing too long titles.
https://issues.apache.org/jira/browse/HDDS-10196
Not yet.
> HDDS-10196. Group dependabot PRs for frontend dependencies

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestLeaseRecovery.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMRecoverLeaseRequest.java
- hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java
- hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java
- hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java
- hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java
Handle lease recovery for the file which don't have any blocks. Once after file is created and hsync is called the lease recovery can be called before any block allocation after the soft limit period. In this case recovery should work and file should get closed.
https://issues.apache.org/jira/browse/HDDS-10190
Unit test
> HDDS-10190. [hsync] Handle lease recovery for file without blocks.

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
- hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyDeleteRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyDeleteRequestWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeysDeleteRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OmKeysDeleteRequestWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyDeleteResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyDeleteResponseWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeysDeleteResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeysDeleteResponseWithFSO.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeyDeleteResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeyDeleteResponseWithFSO.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeysDeleteResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeysDeleteResponseWithFSO.java
In order to fix the undesired behavior of keys reappearing in the namespace when they are deleted after first being hsync()'ed (see HDDS-9930 description for an example), we need to remove open keys when keys are deleted from `KeyTable` so that they cannot be hsync()'ed again. This is achieved by checking OmKeyInfo's hsync metadata upon key deletion.
Note as a natural consequence of this change, the first client that does the initial `hsync()` can get OMException `KEY_NOT_FOUND` when trying to close/commit the file.
https://issues.apache.org/jira/browse/HDDS-9930
> HDDS-9930. Remove open keys as well when keys are deleted from KeyTable

- hadoop-ozone/dev-support/checks/sonar.sh
`sonar.sh` copies the combined coverage report to all submodules:
https://github.com/apache/ozone/blob/2ae531b0f6a069db5a46bd486bb50225a168485d/hadoop-ozone/dev-support/checks/sonar.sh#L26-L31
We can avoid the need for this hack by setting `sonar.coverage.jacoco.xmlReportPaths`.
https://issues.apache.org/jira/browse/HDDS-10101
After [CI run](https://github.com/apache/ozone/actions/runs/7466669266) in `apache/ozone` repo, [coverage for the branch](https://sonarcloud.io/component_measures?metric=coverage&view=list&branch=HDDS-10101&id=hadoop-ozone) is available in SonarCloud.
> HDDS-10101. Set sonar.coverage.jacoco.xmlReportPaths

- hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHA.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestSnapshotBackgroundServices.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMDBCheckpointServlet.java
There is a deadlock between checkpointing creation for Bootstrapping and RocksDBCheckpointDiffer#pruneSstFiles.
Bootstrapping takes the BootstrapStateHandler#lock before checkpointing creation and then takes lock on RocksDBCheckpointDiffer instance to unpause the compaction thread/s. On the other hand RocksDBCheckpointDiffer#pruneSstFiles is synchronized function which first takes lock on RocksDBCheckpointDiffer instance and takes BootstrapStateHandler#lock before removing any files.
Hence both threads, checkpointing creation for Bootstrapping and pruneSstFiles background task, are blocking each other.
~~In this change, synchronized block to notify RocksDBCheckpointDiffer to unpause the compaction has been removed. Now heckpointing creation for Bootstrapping and pruneSstFiles background …
> HDDS-9486. Fix deadlock causing intermittent fork timeout in TestSnapshotBackgroundServices

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerImpl.java
- hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/helpers/OmPrefixInfo.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/PrefixManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/prefix/OMPrefixAclRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/util/ObjectParser.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/OMRequestTestUtils.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMPrefixAclRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/acl/prefix/TestOMPrefixAclResponse.java
- output.log
While working on Prefix ACL, it's found that there are very few tests on Prefix ACL OM HA request and response flow. We need to add more tests for prefix ACL.
There are also identified possible bugs that might have be a problem in the future. They are:
- It's found that OmPrefixInfo and PersistedPrefixInfo do not store and load the updateID and the objectID from DB correctly
- We need to add the object ID and updateID in the prefix codec process.
- UpdateID stored in the OmPrefixInfo on the in-memory prefix tree are not updated
- In OMPrefixAclRequest, the setUpdateId is called after the we apply the ACL operation to the prefix tree (through PrefixManager), this causes OmPrefixInfo update ID to be different than the one in the OM DB
- We need set the update ID to OmPrefixInfo before we …
> HDDS-10066. Consolidate and test the Ratis write path for prefix ACL

- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/cache/CacheValue.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMultiTenantManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMultiTenantManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3ExpiredMultipartUploadsAbortRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/security/S3SecretRequestHelper.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/tenant/OMTenantAssignAdminRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/tenant/OMTenantRevokeAdminRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/tenant/OMTenantRevokeUserAccessIdRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOMMultiTenantManagerImpl.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3ExpiredMultipartUploadsAbortRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/security/TestS3GetSecretRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/security/TestOMGetDelegationTokenRequest.java
Replace Guava Optional with Java Optional, except two unnecessary usages where it's completely removed:
* deprecated `CacheValue` constructor
* `Optional<Long>` in `TestOMGetDelegationTokenRequest`
https://issues.apache.org/jira/browse/HDDS-9985
CI:
https://github.com/adoroszlai/ozone/actions/runs/7680017854
> HDDS-9985. Do not use Guava Optional

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconAndAdminContainerCLI.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconEndpointUtil.java
`TestReconAndAdminContainerCLI` intermittently fails (in 8/100 [runs](https://github.com/adoroszlai/ozone/actions/runs/7680318420)) with timeout at:
```
at org.apache.ozone.test.GenericTestUtils.waitFor(GenericTestUtils.java:204)
at org.apache.hadoop.ozone.recon.TestReconAndAdminContainerCLI.compareRMReportToReconResponse(TestReconAndAdminContainerCLI.java:335)
```
The test gets reports from SCM and Recon, and then waits for the values to be equal.  The problem is that the report values are "fixed", updates are done at the server-side.  The operation repeated by `waitFor` should include getting the reports, too.
Some additional cleanup in separate commits.
https://issues.apache.org/jira/browse/HDDS-10227
Passed in 100 runs:
https://github.com/adoroszlai/ozone/actions/runs/7684474778 …
> HDDS-10227. Intermittent timeout in TestReconAndAdminContainerCLI

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationServer.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/reconfig/TestDatanodeReconfiguration.java
Dynamic reconfiguration replication stream limit.
Control the replication load while the datanode is running.
https://issues.apache.org/jira/browse/HDDS-10183
UT
> HDDS-10183. Dynamic reconfiguration replication stream limit

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestLeaseRecovery.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMRecoverLeaseRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequestWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/util/OmKeyHSyncUtil.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyCommitResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyCommitResponseWithFSO.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCommitRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeyCommitResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeyCommitResponseWithFSO.java
Currently, only those keys in `KeyTable` would have metadata `HSYNC_CLIENT_ID` when those keys have been hsync'ed (and not closed/committed yet). One problem with this is that it makes `getExpiredOpenKeys()` and `listOpenKeys()` (HDDS-8830) inefficient by forcing them to look up `KeyTable` while they could have just used `OpenKeyTable` solely to determine whether an open key is hsync'ed or not.
1. During key `hsync()`, persist metadata `HSYNC_CLIENT_ID` to `OmKeyInfo` in `OpenKeyTable` as well, in addition to `KeyTable`. Only write when the client ID changes so it doesn't lead to excessive writes. Ideally, only the first hsync() would lead to a `OpenKeyTable` write of that key.
2. During key `close()`, remove `HSYNC_CLIENT_ID` from OpenKeyTable if any, so that `HSYNC_CLIENT_ID` isn't …
> HDDS-10077. Add hsync metadata to hsync'ed keys in OpenKeyTable as well

- hadoop-hdds/common/pom.xml
- hadoop-hdds/framework/pom.xml
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/utils/TestCertificateSignRequest.java
- hadoop-hdds/server-scm/pom.xml
- hadoop-ozone/dist/src/main/license/bin/LICENSE.txt
- hadoop-ozone/dist/src/main/license/bin/NOTICE.txt
- hadoop-ozone/dist/src/main/license/jar-report.txt
- hadoop-ozone/ozone-manager/pom.xml
- pom.xml
Upgrade Bouncy Castle to 1.77 (current latest release).  Dependabot would not upgrade it due to a packaging change in 1.71.
1.74 fixes CVE-2023-33201, which does not affect Ozone since we don't use LDAP.
https://bouncycastle.org/latest_releases.html
https://issues.apache.org/jira/browse/HDDS-10194
CI:
https://github.com/adoroszlai/ozone/actions/runs/7630191546
> HDDS-10194. Upgrade Bouncy Castle to 1.77

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/AbstractFindTargetGreedy.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerSelectionCriteria.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerTask.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/FindTargetStrategy.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java
[HDDS-10160](https://issues.apache.org/jira/browse/HDDS-10160). Cache sort results in ContainerBalancerSelectionCriteria
The sort of all the containers is very time consuming, this patch is to cache the sort result and improve the balancer speed.
https://issues.apache.org/jira/browse/HDDS-10160
Original balancer tests running successfully would be enough.
> HDDS-10160. Cache sort results in ContainerBalancerSelectionCriteria

- hadoop-hdds/rocks-native/pom.xml
- hadoop-ozone/dev-support/checks/native.sh
Fix intermittent failure downloading `bzip2` due to `Network is unreachable`.
The fix is similar to HDDS-10157: download from GitHub in CI.  The tarballs from these two sources are a bit different: contents are in `bzip2-bzip2-1.0.8/` in the one from GitHub, `bzip2-1.0.8/` in the original one.  So an additional `move` Ant task renames the GitHub-specific dir to the original one.  `failonerror=false` ensures it passes with the original tarball, too.
https://issues.apache.org/jira/browse/HDDS-10228
Tested locally for the original URL:
```
$ mvn -DskipTests -am -pl :hdds-rocks-native clean install
...
$ mvn -Drocks_tools_native -pl :hdds-rocks-native clean generate-sources
...
[INFO] BUILD SUCCESS
$ ls -1 hadoop-hdds/rocks-native/target/bzip2
bzip2-1.0.8
bzip2-v1.0.8.tar.gz
```
CI (with the …
> HDDS-10228. Intermittent failure downloading bzip2 from sourceware.org

- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestSCMHAManagerImpl.java
`TestSCMHAManagerImpl` has three test cases, each starting new leader SCM from scratch:
* add SCM
* remove SCM
* invalid scenarios
```
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 47.041 s - in org.apache.hadoop.hdds.scm.ha.TestSCMHAManagerImpl
```
This change reduces test execution time by starting a single leader SCM.
1. Testing removal of peer requires adding it first, so `testRemoveSCM` already depends on "add SCM" functionality working correctly.  The patch deletes "add SCM" setup from `testRemoveSCM`, now it relies on the state left by `testAddSCM`.
2. Testing invalid scenarios does not need a fresh SCM leader, requests being tested are invalid either way.
Also, some additional code cleanup, performed in separate commits for easier review. …
> HDDS-10225. Speed up TestSCMHAManagerImpl

- hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/rocksdiff/TestRocksDBCheckpointDiffer.java
Reduce "sleep" time in `TestRocksDBCheckpointDiffer`.  This code path is used in two parameterized tests, executed 14 times in total.
```
[INFO] Tests run: 58, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 74.812 s - in org.apache.ozone.rocksdiff.TestRocksDBCheckpointDiffer
```
https://issues.apache.org/jira/browse/HDDS-10224
```
[INFO] Tests run: 58, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.81 s - in org.apache.ozone.rocksdiff.TestRocksDBCheckpointDiffer
```
https://github.com/adoroszlai/ozone/actions/runs/7677809640
Tested in 10x50 runs to confirm that the change does not introduce flakiness:
https://github.com/adoroszlai/ozone/actions/runs/7678240439
> HDDS-10224. Speed up TestRocksDBCheckpointDiffer

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/container/ReplicationManagerReport.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/scm/container/TestReplicationManagerReport.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerStateManagerImpl.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/OpenContainerHandler.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestOpenContainerHandler.java
If there is an OPEN container without any pipeline, that container has to be moved to CLOSING state and CLOSE container command has to be sent to the datanodes.
Currently, this is done while SCM is initialized. Since Ratis is not set up completely (mostly no leader is elected at this point), the state update is done locally (not via Ratis).
Doing this on SCM start-up is error-prone.
The container state update has to be done only via Ratis. If not, there are chances of container state getting diverged between SCMs.
This PR changes the logic and moves it to ReplicationManager's `OpenContainerHandler`, where we check if the OPEN Container has a healthy Pipeline, if not the container is closed.
HDDS-10231
Added new unit test to cover the scenario.
> HDDS-10231. ContainerStateManager should not finalize the OPEN containers without a Pipeline.

- hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/NamedTestsBase.java
- hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/OzoneTestBase.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/OmTestManagers.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestBucketManagerImpl.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerUnit.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotManager.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestSstFilteringService.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestTrashService.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestMultipartUploadCleanupService.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestOpenKeyCleanupService.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/acl/TestParentAcl.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/acl/TestVolumeOwner.java
Some of the slowest unit tests use `OmTestManagers` to launch OM.  It takes ~10 seconds to initialize (half of that is Ratis leader election).  The test cases are pretty quick after that.
```
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 148.9 s -- in org.apache.hadoop.ozone.om.service.TestOpenKeyCleanupService
[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 133.0 s -- in org.apache.hadoop.ozone.om.TestBucketManagerImpl
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 108.3 s -- in org.apache.hadoop.ozone.om.TestKeyManagerUnit
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 83.42 s -- in org.apache.hadoop.ozone.om.TestOmSnapshotManager
```
This change speeds up four of these tests, mostly by …
> HDDS-10215. Speed up some tests that use OmTestManagers

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/SCMDeletedBlockTransactionStatusManager.java
Improved logs for `SCMDeletedBlockTransactionStatusManager`.
`SCMDeletedBlockTransactionStatusManager` sometimes outputs some redundant WARN logs or unclear logs.
https://issues.apache.org/jira/browse/HDDS-10029
Existing Test
> HDDS-10029. Improved logs for SCMDeletedBlockTransactionStatusManager

- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestKeyDeletingService.java
Fix intermittent failure in `TestKeyDeletingService`.  `KeyDeletingService` may complete deleting all keys in 1 run.
https://issues.apache.org/jira/browse/HDDS-10251
Tested with 100x repeated CI runs.
Before HDDS-10215: 100/100 pass
https://github.com/adoroszlai/ozone/actions/runs/7716648128
HDDS-10215 seems to have introduced the flakiness: 100/100 failed (although the same test passed in the PR and in fork run)
https://github.com/adoroszlai/ozone/actions/runs/7716644638
With this fix: 100/100 pass
https://github.com/adoroszlai/ozone/actions/runs/7716856421
Regular CI:
https://github.com/adoroszlai/ozone/actions/runs/7716815030
> HDDS-10251. Intermittent failure in TestKeyDeletingService

- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/OMDBInsightEndpoint.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestOmDBInsightEndPoint.java
The current response of Deleted-Directories Insights has the following parameters :- 
```
"key":"/-9223372036854775552/-9223372036854775040/-9223372036854775040/dir1/-9223372036854774527",
"path": "dir1",
```
As we can see its confusing and not very intuitive for the user. 
We want the final response parameters to be like this :- 
```
"key": "dir1", 
"path": "volume/bucket1/dir1/dir2/dir3",
```
Here we will have to construct the path of the directory with their actual names rather than printing out the object ID's.
And we will also have to make a few changes to the frontend to accommodate this new info accordingly.
https://issues.apache.org/jira/browse/HDDS-10241
Manual Testing & Unit Testing
> HDDS-10241. Improve the response for the Deleted Directories Insight Endpoint.

- hadoop-ozone/dist/src/main/smoketest/freon/metadata-generate.robot
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OmMetadataGenerator.java
Add more function for freon OmMetadataGenerator
- CREATE_STREAM_FILE
- CREATE_STREAM_KEY
- LIST_KEYS_LIGHT
- LIST_STATUS_LIGHT
Such as:
```bash
[root@VM-7-9-centos ~/root/]$ ozone freon ommg --operation LIST_KEYS_LIGHT -t 10 --duration 30 --bucket bucket-obs
46.67% |████████████████                  |  14/30 Time: 0:00:14|   LIST_KEYS_LIGHT: rate 913 max 913
```
https://issues.apache.org/jira/browse/HDDS-10025
manually test.
> HDDS-10025. Add more function for freon OmMetadataGenerator

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestFinalizeBlock.java
Migrate TestFinalizeBlock test class to use JUnit5.
https://issues.apache.org/jira/browse/HDDS-10147
Existing test.
> HDDS-10147. Migrate TestFinalizeBlock to JUnit5.

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/endpoint/VersionEndpointTask.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/ContainerReader.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestContainerReader.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainer.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineFailures.java
volume is not fully initialized when ContainerReader is performing verify and cleanup container data. So causing NPE for temp directory and container deleted path.
while reading volume, temp dir and deleted container dir is initialized before reading container with working dir (as one used for reading container data at same co-location).
https://issues.apache.org/jira/browse/HDDS-9658
- test case updated to cover same scenario
> HDDS-9658. NPE while cleanup deleted container data

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/client/HddsClientUtils.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockDataStreamOutput.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockInputStream.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/RatisBlockOutputStream.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockInputStream.java
- hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/client/TestHddsClientUtils.java
- hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestBlockInputStream.java
- hadoop-hdds/client/src/test/java/org/apache/hadoop/ozone/client/io/ECStreamTestUtil.java
- hadoop-hdds/client/src/test/java/org/apache/hadoop/ozone/client/io/TestECBlockInputStreamProxy.java
Removing dead code from hdds-client module. Dead code besides that it is not used can be harmful, if someone starts to use it, as it was not used it might not have been updated either along with similar functionality, so it is better to get rid of it.
The PR is, removing unused code from hdds-client module.
https://issues.apache.org/jira/browse/HDDS-10248
Functionality should not be changing, if the code compiles, and existing tests are running fine, that pretty much proves that we did not needed these methods.
On the other hand, due to potential reflective access it is hard to prove that complete methods are not called, therefore I ran a search for the method name in the codebase and checked for that manually.
> HDDS-10248. Remove unused, dead code in hdds-client module

- hadoop-ozone/dist/src/main/smoketest/freon/metadata-generate.robot
Fix:
```
NoSuchFileException: There are not enough files for testing you should use CREATE_FILE to create at least batch-size * threads = 1000
```
which happens because only `n=100` items are created, but `List` test requires 1000 items (`batch-size = 100`, `threads = 10`).
Reduce `threads` to 1.
https://issues.apache.org/jira/browse/HDDS-10263
Ran `freon/metadata-generate.robot` locally 10x:
```
Metadata-Generate :: Test freon ommg command                                  
[Setup] Create Volume and Buckets                                     | PASS |
[Read] Bucket Information                                             | PASS | …
```
> HDDS-10263. Intermittent failure in freon/metadata-generate robot test

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java
As described in HDDS-10146, all of the ChunkReader threads are blocked in the `KeyValueHandler#checkContainerIsHealthy` method, waiting for the `KeyValueContainer#readLock`. 
Remove readLock from KeyValueHandler.checkContainerIsHealthy to improve performance
https://issues.apache.org/jira/browse/HDDS-10246
- No new test and pass exist unit tests
- Works well in our cluster
> HDDS-10246. Remove KeyValueHandler.checkContainerIsHealthy to improve read performance

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestSnapshotDeletingService.java
Wrong test was updated in PR #5344. This change is to correctly remove flaky tag from  TestSnapshotDeletingService.testMultipleSnapshotKeyReclaim test.
After https://github.com/apache/ozone/pull/5986, pendingEvictionList has been removed and assertion on pendingEvictionList has been removed as well which was causing Intermittent test failure. 
HDDS-9288
Ran the test 10x10 times: https://github.com/hemantk-12/ozone/actions/runs/7733801856
> HDDS-9288. Remove flaky tag from TestSnapshotDeletingService.testMultipleSnapshotKeyReclaim

- hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/client/TestHddsClientUtils.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestSchemaOneBackwardsCompatibility.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerPersistence.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/impl/TestFilePerBlockStrategy.java
- hadoop-hdds/erasurecode/src/test/java/org/apache/ozone/erasurecode/rawcoder/TestRawCoderBase.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/conf/TestHddsConfServlet.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/authority/TestDefaultCAServer.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/utils/TestCertificateSignRequest.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/utils/TestRootCertificate.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStoreByteArrayIterator.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStoreCodecBufferIterator.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackAware.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackScatter.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECOverReplicationHandler.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisOverReplicationHandler.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestReplicationAnnotation.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelinePlacementPolicy.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineStateManagerImpl.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestRatisPipelineProvider.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/security/TestRootCARotationManager.java
- hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestDecommissionSubCommand.java
- hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestMaintenanceSubCommand.java
- hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestRecommissionSubCommand.java
Simplify tests using assertThrows in hadoop-hdds
[HDDS-10208](https://issues.apache.org/jira/browse/HDDS-10208)
https://github.com/wzhallright/ozone/actions/runs/7737861963
> HDDS-10208. Simplify tests using assertThrows in hadoop-hdds

- hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestBlockOutputStreamCorrectness.java
_Background: Spotbugs 4 finds more problems than Spotbugs 3, which we currently use.  Upgrade to Spotbugs 4 is required for migration to Java 11+.  This PR fixes a warning which is new to Spotbugs 4._
Refactor `TestBlockOutputStreamCorrectness` to avoid the need for `new Random`.
Also parameterize the test, to exercise both single-byte and array write path.
https://issues.apache.org/jira/browse/HDDS-10173
Tested with Spotbugs 4:
```
$ ./hadoop-ozone/dev-support/checks/findbugs.sh -Dspotbugs.version=4.8.3.0 -am -pl :hdds-client
...
$ grep -c TestBlockOutputStreamCorrectness target/findbugs/summary.txt
0
```
CI:
https://github.com/adoroszlai/ozone/actions/runs/7716000984/job/21032183070#step:5:999
> HDDS-10173. findbugs: Random object used only once in TestBlockOutputStreamCorrectness

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMDirectoryCreateRequest.java
In OMDirectoryCreateRequest#getAllParentInfo, there is an unnecessary call to add cache entry for the missing parent directory info.
```java
omMetadataManager.getKeyTable(BucketLayout.DEFAULT).addCacheEntry(
omMetadataManager.getOzoneKey(
volumeName, bucketName, parentKeyInfo.getKeyName()),
parentKeyInfo, trxnLogIndex); 
```
Although it is already added later in OMFileRequest#addKeyToTableCacheEntries
As the method name suggest, getAllParentInfo should just return the missing parent info without doing any table operation.
https://issues.apache.org/jira/browse/HDDS-10269
Clean CI: https://github.com/ivandika3/ozone/actions/runs/7737930007
> HDDS-10269. Remove duplicate addCacheEntry in OMDirectoryCreateRequest#getAllParentInfo

- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestSCMSafeModeManager.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestListKeysWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneListStatusHelper.java
Fix  cases when the keyPrefix pertains to a particular file/dir  . For more details on the problem check jira description.
https://issues.apache.org/jira/browse/HDDS-9065
Unit tests.
> HDDS-9065. [FSO]ListKeys: Incorrect result when keyPrefix matching multiple exist keys.

- hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigurationTarget.java
- hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/TimeDurationUtil.java
Removing dead code from hdds-config module. Dead code besides that it is not used can be harmful, if someone starts to use it, as it was not used it might not have been updated either along with similar functionality, so it is better to get rid of it.
The PR is, removing unused code from hdds-config module.
https://issues.apache.org/jira/browse/HDDS-10248
Functionality should not be changing, if the code compiles, and existing tests are running fine, that pretty much proves that we did not needed these methods.
On the other hand, due to potential reflective access it is hard to prove that complete methods are not called, therefore I ran a search for the method name in the codebase and checked for that manually.
> HDDS-10279. Remove unused, dead code in hdds-config module.

- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DefaultCertificateClient.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerStateManagerImpl.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
- We are already logging all the config properties during start-up, in addition to that the container balancer config is also logged. We can avoid logging container balancer config during startup.
- We don't have to print the complete certificate information at the info level. Printing SerialId should be enough.
- Fix incorrect log message in ContainerStateManager#initialize
HDDS-10271
NA
> HDDS-10271. Fixing SCM start-up logs.

- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestKeyDeletingService.java
Speed up `TestKeyDeletingService`:
```
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 162.082 s - in org.apache.hadoop.ozone.om.service.TestKeyDeletingService
```
1. Start OM in per-class setup methods instead of per-test.  Tests are moved into two nested classes, because some of them test normal operations, others simulate failing block delete requests.  Most assertions had to be changed to not assume "empty" OM DB, similarly to #6107.
2. Reduce some service intervals.
3. Extract some helper methods.
https://issues.apache.org/jira/browse/HDDS-10217
Total time is reduced to 40-45 seconds:
```
[INFO] Running org.apache.hadoop.ozone.om.service.TestKeyDeletingService
[INFO] Running org.apache.hadoop.ozone.om.service.TestKeyDeletingService$Failing
[INFO] Tests run: 3, …
```
> HDDS-10217. Speed up TestKeyDeletingService

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMiniOzoneCluster.java
Remove unnecessary sleep in `TestMiniOzoneCluster`. Saves 20s in the split.
https://issues.apache.org/jira/browse/HDDS-10285
> HDDS-10285. Remove unnecessary sleep in TestMiniOzoneCluster

- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/container/ReportSubcommand.java
- hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/container/TestReportSubCommand.java
After SCM is started or after a failover, all the numbers in the replication manager report will be zero, which can lead to confusion.
While it may be an idea to throw an error if the report isn't ready yet, that could be an incompatible change, as some monitoring tools to QA scripts could depend on the output to some extent.
Therefore it makes sense to print a warning to stderr indicating the report has zero values until replication manager runs for the first time. Same output after this PR:
```
bash-4.2$ ozone admin container report
The Container Report is not available until Replication Manager completes its first run after startup or fail over. All values will be zero until that time.
Container Summary Report generated at 1970-01-01T00:00:00Z …
```
> HDDS-10272. Container Report admin command displays incorrect value immediately after SCM restart

- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/GenericTestUtils.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestStorageContainerManager.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneCluster.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java
`MiniOzoneCluster` has a setting to enable trace level logging, but it is never set to `true`.  Setting trace level logging globally is also useless, would result in too verbose logs.  Setting level for specific loggers as needed is more helpful.
This PR proposes to remove `enableTrace` and related code.
Config key `ozone.trace.enabled` can also be removed, since it is not used elsewhere.  (The description says it is useful for debugging the REST protocol.  Which was removed in favor of S3 Gateway years ago: HDDS-738.)
https://issues.apache.org/jira/browse/HDDS-10287
CI:
https://github.com/adoroszlai/ozone/actions/runs/7768321799
> HDDS-10287. Remove unused `ozone.trace.enabled` config and related code

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/RatisTestHelper.java
`RatisTestSuite` is unused, can be removed.
https://issues.apache.org/jira/browse/HDDS-10286
CI:
https://github.com/adoroszlai/ozone/actions/runs/7767145925
> HDDS-10286. Remove unused RatisTestSuite

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinator.java
Create and store `OzoneClientConfig` instance via `ConfigurationSource#getObject` to ensure actual config values (coming from `ozone-site.xml`) are injected into the object.  Creating `new OzoneClientConfig()` initializes it with the default values, defined in the class.
(There are similar bugs in some integration tests.  Those will be fixed as part of HDDS-10292, to make it easier to backport the fix for prod code.)
https://issues.apache.org/jira/browse/HDDS-10294
CI:
https://github.com/adoroszlai/ozone/actions/runs/7778426128
> HDDS-10294. Actual client configuration ignored in ECReconstructionCoordinator

- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DiskBalancerReportSubcommand.java
Currently the disk balancer status command requires passing -c / --count to list any nodes as the default value of "count" is zero. If you omit the -c no results are returned.
The default should allow the report to be produced. I propose setting the default to 25.
https://issues.apache.org/jira/browse/HDDS-10297
Manually via docker-compose. After this change the output looks like:
```
bash-4.2$ ozone admin datanode diskbalancer report
Report result:
Datanode                                           VolumeDensity
ozone_datanode_1.ozone_default                     0.0
```
Before, no results would have been returned unless a positive value was passed for -c
> HDDS-10297. [Disk Balancer] Report command should default to 25 nodes

- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/SCMTestUtils.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestDatanodeStateMachine.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/TestSCMCommonPlacementPolicy.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestBlockManager.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerManagerImpl.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerReportHandler.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestUnknownContainerReport.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECMisReplicationHandler.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECOverReplicationHandler.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestLegacyReplicationManager.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestMisReplicationHandler.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisMisReplicationHandler.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisUnderReplicationHandler.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestSequenceIDGenerator.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineDatanodesIntersection.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelinePlacementPolicy.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineStateManagerImpl.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestSimplePipelineProvider.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/server/TestSCMClientProtocolServer.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/container/common/TestEndPoint.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMiniOzoneCluster.java
`SCMTestUtils` cannot use `@TempDir` directly, since its lifecycle is not managed by JUnit.  The goal of this task is to refactor tests that use `SCMTestUtils`: they can pass their own `@TempDir`.
https://issues.apache.org/jira/browse/HDDS-10243
CI:
https://github.com/adoroszlai/ozone/actions/runs/7760146658
> HDDS-10243. Replace GenericTestUtils temp dir in SCMTestUtils

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocolServerSideTranslatorPB.java
- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DiskBalancerStatusSubcommand.java
The current status command only shows nodes where the disk balancer is RUNNING. The different states can be filtered via the -s switch (RUNNING, STOPPED, UNKNOWN). The current CLI gives no way to list "all nodes".
It would be better to just output all the states by default and then allow them to be filtered with the -s switch. That way, we can list all nodes, or filter down by a specific status.
This change also simplifies the code in the CLI command a little by using an enum for the status state value, rather than a string, which can result in better errors if a wrong value is given.
https://issues.apache.org/jira/browse/HDDS-10299
Manually via docker compose. Now the output by default looks like:
```
sodonnell@sodonnell-MBP16 ozone % docker exec -it ozone_scm_1 /bin/bash
bash-4.2$ ozone …
```
> HDDS-10299. [DiskBalancer] Status command should output all statuses by default

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/DiskBalancerCommand.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DiskBalancerManager.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocolServerSideTranslatorPB.java
Fix various problems with the disk balancer start command:
1. When using -a for all datanodes, the hosts appear as an empty list due to the way the protobuf is deserialized, resulting in no hosts getting processed.
2. All the config values appear at zero, as if the proto value is not set for a double, it returns 0.0, so we need to check for has<field> and set an optional or empty
3. The isHealthy check needed negated, as it was excluding healthy nodes rather than unhealthy ones resulting in no nodes getting processed.
I also added a log message or two so we can have a record in the SCM log of the command being sent.
https://issues.apache.org/jira/browse/HDDS-10304
Manually using docker compose. Prior to these changes the command would fail silently, but now SCM sends the command to the …
> HDDS-10304. [DiskBalancer] Start command - Fix nodes not being processed and incorrect config values

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/OzoneClientConfig.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockInputStream.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeStoreWithIncrementalChunkList.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/impl/TestBlockManagerImpl.java
- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MockOmTransport.java
- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestBlockOutputStreamIncrementalPutBlock.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
Implement Client side change for HDDS-8047 incremental chunk list for PutBlock. See HDDS-8047 for the problem description and design doc.
* This PR depends on HDDS-9750 / #5661 and HDDS-9751 / #5662
* Updates BlockOutputStream WriteChunk and PutBlock to product the incremental chunk list. See 
[PutBlock metadata optimization.pdf](https://github.com/apache/ozone/files/13444017/PutBlock.metadata.optimization.pdf) for implementation details.
* New test cases TestBlockOutputStreamIncrementalPutBlock
https://issues.apache.org/jira/browse/HDDS-9752
* New unit tests TestBlockOutputStreamIncrementalPutBlock
* Full cluster HBase ycsb workload test
> HDDS-9752. [hsync] Make Putblock performance acceptable - Client side

- hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - JVM Metrics.json
- hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - ListKey Metrics.json
- hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - Object Metrics.json
There are some fixes needed for various dashboards published.
Details are in the linked jira.
https://issues.apache.org/jira/browse/HDDS-10229
Dashboard was imported to my dev cluster and validated against load generation.
> HDDS-10229. Fixes for dashboards

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestSnapshotDeletingService.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequestWithFSO.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCommitRequest.java
for key overwrite case, objectId is same. for deleted key, its suffixed with objectId to be unique. So for continuous create and delete same key, there is a possibility of overwrite deletedTable entry causing missing cleanup of blocks of previous key.
Also snapshot content remain orphan in case of overwrite in active db.
As fix for overwrite, a unique id is appended to key in deleted table to make it unique.
https://issues.apache.org/jira/browse/HDDS-10296
- updated existing unit test case
> HDDS-10296. orphan blocks during overwrite of key

- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java
Add a default value "*" for the configuration property ozone.om.kerberos.principal.pattern to support accessing Ozone cluster in other Kerberos realms.
* Follow what was done in HDFS-7546.
* Currently we simply workaround the issue by adding the property to the command line. Adding it to the default makes Ozone more user friendly. E.g. 
`hdfs dfs -Dozone.om.kerberos.principal.pattern=* -ls ofs://ozone1707264383/vol1/bucket1/`
https://issues.apache.org/jira/browse/HDDS-10328
> HDDS-10328. Support cross realm Kerberos out of box.

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/VolumeArgs.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/AbstractRootedOzoneFileSystemTest.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneManagerSnapshotAcl.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/ObjectStoreStub.java
Fix findbugs warnings by making `VolumeArgs` immutable.
```
M V EI: org.apache.hadoop.ozone.client.VolumeArgs.getAcls() may expose internal representation by returning VolumeArgs.acls  At VolumeArgs.java:[line 107]
M V EI: org.apache.hadoop.ozone.client.VolumeArgs.getMetadata() may expose internal representation by returning VolumeArgs.metadata  At VolumeArgs.java:[line 103]
M V EI2: org.apache.hadoop.ozone.client.VolumeArgs$Builder.setAcls(List) may expose internal representation by storing an externally mutable object into VolumeArgs$Builder.listOfAcls  At VolumeArgs.java:[line 165]
```
Findbugs complains about `get...` method even if the corresponding field is initialized using `Collections.unmodifiable...`.  Two possible ways to solve the problem:
1. wrap in `unmodifiable...` in …
> HDDS-10322. Make VolumeArgs immutable

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DiskBalancerCommandHandler.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeProtocolServer.java
When the datanode receives a disk balancer command, it logs an error indicating the command is not registered:
```
2024-02-06 13:57:20,690 [IPC Server handler 1 on default port 9861] WARN ipc.Server: IPC Server handler 1 on default port 9861, call Call#6 Retry#0 org.apache.hadoop.ozone.protocol.StorageContainerDatanodeProtocol.submitRequest from ozone_datanode_1.ozone_default:34310 / 192.168.48.4:34310
java.lang.IllegalArgumentException: Scm command diskBalancerCommand is not implemented
at org.apache.hadoop.hdds.scm.server.SCMDatanodeProtocolServer.getCommandResponse(SCMDatanodeProtocolServer.java:413)
at org.apache.hadoop.hdds.scm.server.SCMDatanodeProtocolServer.sendHeartbeat(SCMDatanodeProtocolServer.java:283)
at org.apache.hadoop.ozone.protocolPB.StorageContainerDatanodeProtocolServer …
```
> HDDS-10305. [DiskBalancer] Disk balancer command is not registered on datanode

- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBStoreBuilder.java
- hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedLogger.java
`DBStoreBuilder` uses unmanaged RocksDB `Logger`, and does not close it.
https://issues.apache.org/jira/browse/HDDS-10333
Added temporary log in `LeakTracker#close`, verified instance for `ManagedLogger` is invoked.
CI:
https://github.com/adoroszlai/ozone/actions/runs/7830648761
> HDDS-10333. RocksDB logger not closed

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BufferPool.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/CodecBuffer.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChunkBuffer.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChunkBufferImplWithByteBuffer.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/IncrementalChunkBuffer.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/common/TestChunkBuffer.java
- hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/container/upgrade/TestUpgradeManager.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestCommitWatcher.java
Ozone client allocates large chunks of heap memory when writing keys (BlockOutputStream, BufferPool).
Extract client-related buffer improvement from #5497.
https://issues.apache.org/jira/browse/HDDS-9843
CI: https://github.com/duongkame/ozone/actions/runs/7759444701
> HDDS-9843. Ozone client high memory (heap) utilization

- dev-support/ci/selective_ci_checks.bats
- dev-support/ci/selective_ci_checks.sh
Currently there are no test for dashboard changes but the PRs still run the entire CI workflow.
Skip the CI if only the dashboards have been updated.
https://issues.apache.org/jira/browse/HDDS-10340
Pushed this change and a dashboard change to https://github.com/kerneltime/ozone/commits/HDDS-10339-skip-ci/
> HDDS-10340. Skip ci on dashboard updates

- hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - ListKey Metrics.json
To be brought in after merging PR: https://github.com/apache/ozone/pull/6120.
Add a visualization to the Ozone - ListKey Metrics Dashboard to indicate how many concurrent requests an RPC server (OM) is handling (metric to be added: `om_client_protocol_concurrency`).
https://issues.apache.org/jira/browse/HDDS-10318
The patch has been tested out manually on a docker-compose cluster with the monitoring add-ons.
> HDDS-10318. Add OM client protocol metrics to Ozone - ListKey Metrics dashboard

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/LeaseKeyInfo.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OzoneManagerProtocol.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestLeaseRecovery.java
- hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMRecoverLeaseRequest.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientAdapter.java
- hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java
- hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java
- hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java
- hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java
During leaseRecovery if final block doesn't exist in datanode(when data still not yet flushed to datanode for the last block) but exist in openFileTable. In this case recovery client should finalize the penultimate block and the lease recovery should succeed with the penultimate block length.
https://issues.apache.org/jira/browse/HDDS-10242
New integration test.
> HDDS-10242. [hsync] Handle penultimate block finalization.

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/endpoint/HeartbeatEndpointTask.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/diskbalancer/DiskBalancerInfo.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/states/endpoint/TestHeartbeatEndpointTask.java
All the pieces are in place to allow the DNs to relay their disk balancer status to SCM, but the disk balancer report is not yet added to the heartbeat message in HeartbeatEndpointTask. This results in the SCM details never getting updated and the status command always shows UNKNOWN as the status.
This change simply adds the report into the heartbeat message.
https://issues.apache.org/jira/browse/HDDS-10332
Manually tested via docker proving the current status is update in SCM after a DN heartbeat.
> HDDS-10332. [Diskbalancer] Include Disk Balancer Report in the heartbeat message

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/RatisTestHelper.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestSstFilteringService.java
Changes are done to improve the test run speed to 33.23 s as compare to 59.43 s earlier.
- The setup method modified to be initialize one time for all methods.
- Introduced the method orderer
- Declared one counter to track the number of snapshots been generated in all the methods to assert the count according.
- Separated the methods for creation of volume and bucket which was combine and there were repeated calls to it.
- Changed one assert statement to assert that because the .sst file from the bucket created in first method was not consistent to available in second method.
https://issues.apache.org/jira/browse/HDDS-10218
Tested on local system and in CI-CD integration.
> HDDS-10218. Speed up TestSstFilteringService

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/BucketArgs.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OzoneAcl.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/AbstractRootedOzoneFileSystemTest.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
Fix findbugs warnings by making `BucketArgs` immutable.  See #6193 for similar change in `VolumeArgs`.
```
M V EI: org.apache.hadoop.ozone.client.BucketArgs.getAcls() may expose internal representation by returning BucketArgs.acls  At BucketArgs.java:[line 130]
M V EI: org.apache.hadoop.ozone.client.BucketArgs.getMetadata() may expose internal representation by returning BucketArgs.metadata  At BucketArgs.java:[line 139]
M V EI2: org.apache.hadoop.ozone.client.BucketArgs$Builder.setAcls(List) may expose internal representation by storing an externally mutable object into BucketArgs$Builder.acls  At BucketArgs.java:[line 239]
```
Also eliminate `@SuppressWarnings("parameternumber")` by passing the builder to the constructor, instead of individual properties.
Create new constructor in …
> HDDS-10325. Make BucketArgs immutable

- .github/dependabot.yml
By default Dependabot performs its duties (check for updates and open pull requests) on Monday.  We could better distribute CI workflow runs by shifting Dependabot schedule to the weekend, when fewer PRs are created by developers.
https://issues.apache.org/jira/browse/HDDS-10344
Not tested.
Reference:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleday
> HDDS-10344. Schedule dependabot for weekend

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/client/ScmClient.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocol.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/protocolPB/StorageContainerLocationProtocolClientSideTranslatorPB.java
- hadoop-hdds/interface-admin/src/main/proto/ScmAdminProtocol.proto
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/FetchMetrics.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/FetchMetrics.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocolServerSideTranslatorPB.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestFetchMetrics.java
- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ContainerOperationClient.java
- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DecommissionStatusSubCommand.java
- hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestDecommissionStatusSubCommand.java
In order to track the progress of the decommissioning of a datanode, the number of pipelines associated to the datanode and the number of containers on the datanode blocking the decommissioning (i.e., unhealthy and under-replicated containers) is necessary to be shown as a part of the decommission status command.
These counts, along with the time at which decommission was started for the datanode are stored as a part of metrics in NodeDecommissionMetrics. In this PR, a class similar to JMXJsonServerlet (from hadoop-common) is introduced in scm-server, which can accept a request for metrics from a specific class. The response is parsed to display the counts and start-time for each node currently in DECOMMISSIONING.
https://issues.apache.org/jira/browse/HDDS-9738
Updated tests in …
> HDDS-9738. Display startTime, pipeline and container counts for decommissioning datanode

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/volume/DeleteVolumeHandler.java
In recursive volume delete if volume contains OBS bucket, then the delete happens successfully but the exception is shown in CLI. As after deleting OBS bucket it goes into default case and throws exception.
https://issues.apache.org/jira/browse/HDDS-10359
Integration test
> HDDS-10359. Recursively deleting volume with OBS bucket shows error despite success

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/AbstractRootedOzoneFileSystemTest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeySetTimesRequest.java
Set Times API doesn't work with linked buckets, This PR fixes it by adding resolution for the linked bucket.
https://issues.apache.org/jira/browse/HDDS-10369
Unit test
> HDDS-10369. Set Times API doesn't work with linked buckets.

- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/db.json
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/datanodes/datanodes.tsx
We are displaying only first 3 PipelinesID's and remaining pipelinesId's we displaying in popup after over on text
... and N more pipelines
###Please describe your PR in detail:
As discussed in APAC community sync:
Suggested one improvement on Recon UI, fold the pipeline info for a DN  on Datanode page. When a Datanode has more than 10 pipelines, it will  display all the pipelines by default, which is not necessary most of the  time. 
https://issues.apache.org/jira/browse/HDDS-10301
Manually
Before this PR
With this PR
> HDDS-10301. Recon - Fold the pipeline info for a DN on Datanode page.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChecksumByteBufferImpl.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/common/TestChecksumByteBuffer.java
While we accept Java 8 as the minimum supported JVM, most Ozone production clusters are running on a newer platform like JDK11.
We can leverage Java 9+ interface using reflection to checksum direct buffers directly in native memory.
https://issues.apache.org/jira/browse/HDDS-10288
Added unit test. Ran it in JDK 11 to ensure same checksum output between on-heap and off-heap. 
Perf test is done with [HDDS-9843](https://issues.apache.org/jira/browse/HDDS-9843).
> HDDS-10288. Checksum to support direct buffers

- hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - S3 Dashboard.json
Adds latency, API rate, failure tracking, data transfer metrics for S3 Gateway 
https://issues.apache.org/jira/browse/HDDS-10339
Attached gif and used steps outline in https://github.com/apache/ozone/blob/master/hadoop-ozone/dist/src/main/compose/ozone/README.md#add-ons and used a real cluster deployment as well.
https://github.com/apache/ozone/assets/774455/8d4faa34-09ed-4fee-aa5b-d3ee00604d92
> HDDS-10339. Add S3 API level dashboard

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntry.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntryPool.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockOutputStreamEntry.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockOutputStreamEntryPool.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java
- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/io/TestECBlockOutputStreamEntry.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneOutputStreamStub.java
We fix the @SuppressWarnings({"parameternumber", "squid:S00107"}) in
- KeyOutputStream
- BlockOutputStreamEntry
- BlockOutputStreamEntryPool
- ECBlockOutputStreamEntry
- ECBlockOutputStreamEntryPool
HDDS-10387
By the existing tests.
> HDDS-10387. Fix parameter number warning in KeyOutputStream and the related classes

- hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/MiniOzoneChaosCluster.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneCluster.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneHAClusterImpl.java
Reduce code duplication in MiniOzoneCluster builders by extracting some common methods.  Also some trivial code cleanup (see separate commits).
https://issues.apache.org/jira/browse/HDDS-10342
CI:
https://github.com/adoroszlai/ozone/actions/runs/7845724482
> HDDS-10342. Reduce code duplication in MiniOzoneCluster builders

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/RatisPipelineProvider.java
`RatisPipelineProvider` is used to create a new Ratis pipeline when SCM is asked to provide one and existing pipelines can't be used. Both `WritableRatisContainerProvider` and `BackgroundPipelineCreator` create pipelines this way, dynamically and in the background, respectively.
As part of new pipeline creation, Datanodes are excluded if they're already engaged in "ozone.scm.datanode.pipeline.limit" number of pipelines:
```
private List<DatanodeDetails> filterPipelineEngagement() {
List<DatanodeDetails> healthyNodes =
getNodeManager().getNodes(NodeStatus.inServiceHealthy());
List<DatanodeDetails> excluded = healthyNodes.stream()
.map(d ->
new DnWithPipelines(d,
PipelinePlacementPolicy
.currentRatisThreePipelineCount(getNodeManager(),
getPipelineStateManager(), d)))
.filter(d -> …
```
> HDDS-10345. Sorting isn't needed when excluding Datanodes during Ratis Pipeline Creation

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/OMClientRequest.java
Instance object is having thread local object, which can have memory leak as thread local is not explicitly released. Further there do not seems any usecase having thread local definition for OmLockDetails.
So removed thread local definition.
https://issues.apache.org/jira/browse/HDDS-10385
Existing test case to cover impact
> HDDS-10385. Memory leak for thread local usages in OMClientRequest

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/AbstractDatanodeDBDefinition.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/AbstractDatanodeStore.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeSchemaOneDBDefinition.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeSchemaThreeDBDefinition.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeSchemaTwoDBDefinition.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeStoreSchemaOneImpl.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeStoreSchemaThreeImpl.java
deleted_blocks table is only used in container schema V1. It's replaced with delete_txns table in schema V2 and V3. But currently deleted_blocks table is still defined and kept in DatanodeSchemaThreeDBDefinition and DatanodeSchemaTwoDBDefinition, which will confuse the code readers who don't know this background.
This task removes the deleted_blocks table definition and reference in schema V2 and V3.
https://issues.apache.org/jira/browse/HDDS-10398
> HDDS-10398. Remove deleted_blocks table in container schema V2 and V3 definition

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/keys/DeleteKeyHandler.java
When enableFileSystemPath is true and bucket layout is legacy, during key delete operation in normalizekey(prexecute) it removes trailing slash, but in DB key is present with trailing slash. And because of this KEY_NOT_FOUND error comes.
But fixing legacy bucket directory deletion using sh can lead to other issues. In this PR we are restricting legacy bucket directory deletion using sh command.
More discussion in [PR](https://github.com/apache/ozone/pull/6218).
https://issues.apache.org/jira/browse/HDDS-10397
New Integration test.
> HDDS-10397. Restrict legacy bucket directory deletion through sh command.

- hadoop-ozone/recon-codegen/src/main/java/org/hadoop/ozone/recon/schema/ContainerSchemaDefinition.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/UnhealthyContainersResponse.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/fsck/ContainerHealthTask.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/ContainerSizeCountTask.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/fsck/TestContainerHealthTask.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestContainerSizeCountTask.java
Encounterd an error in recon log `IllegalArgumentExpection`: containerSize Negative" :-
```
2024-02-01 19:50:21,727 ERROR [ContainerSizeCountTask]-org.apache.hadoop.ozone.recon.tasks.ContainerSizeCountTask: FIXME: Failed to process ContainerInfo{id=#3979, state=DELETED, stateEnterTime=2024-02-01T02:45:43.506025Z, pipelineID=PipelineID=0ea98cdd-adf9-4ffa-b7f8-15a3052b155a, owner=om1546336125}
java.lang.IllegalArgumentException: containerSize = -63 < 0
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:204)
at org.apache.hadoop.ozone.recon.ReconUtils.getContainerSizeBinIndex(ReconUtils.java:329)
at org.apache.hadoop.ozone.recon.ReconUtils.getContainerSizeUpperBound(ReconUtils.java:309)
at org.apache.hadoop.ozone.recon.tasks.ContainerSizeCountTask.getContainerSizeCountKe …
```
> HDDS-10293. IllegalArgumentException: containerSize Negative

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotPurgeRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotUtils.java
When a previous snapshot purge request has already purged the snapshot. There will be a race condition between `SnapshotDeletingService` and `OMSnapshotPurgeRequest` where we resend the same request which causes a NPE when getting the `snapshotInfo` from the `snapshotInfoTable`. We can ignore this request as this snapshot is already purged.
https://issues.apache.org/jira/browse/HDDS-10408
> HDDS-10408. NPE causes OM crash in Snapshot Purge request.

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneVolume.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmBucketArgs.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmBucketInfo.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmDirectoryInfo.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmMultipartKeyInfo.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmVolumeArgs.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/WithMetadata.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/WithObjectID.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/WithParentObjectId.java
- hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/helpers/OmPrefixInfo.java
Eliminate `@SuppressWarnings("visibilitymodifier")` in `WithMetadata` and similar subclasses.
https://issues.apache.org/jira/browse/HDDS-10396
CI:
https://github.com/adoroszlai/ozone/actions/runs/7972059774
> HDDS-10396. Encapsulate fields in WithMetadata and subclasses

- hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/MiniOzoneChaosCluster.java
- hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/TestMiniChaosOzoneCluster.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/upgrade/TestHDDSUpgrade.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/upgrade/TestScmHAFinalization.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneCluster.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMiniOzoneCluster.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/UniformDatanodesFactory.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/volume/TestDatanodeHddsVolumeFailureDetection.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/volume/TestDatanodeHddsVolumeFailureToleration.java
Currently MiniOzoneCluster creates almost identical datanodes, based on global config and few datanode-specific properties:
* `numDataVolumes`
* `datanodeReservedSpace`
* `dnLayoutVersion`
This change introduces a factory to create datanodes for `MiniOzoneCluster`, further cleaning up the global `MiniOzoneCluster.Builder` interface.
Other implementations can be added in the future to customize each datanode (e.g. different number of volumes, different amount of reserved space, etc.).
https://issues.apache.org/jira/browse/HDDS-10320
CI:
https://github.com/adoroszlai/ozone/actions/runs/7979189177
> HDDS-10320. Introduce factory to configure MiniOzoneCluster's datanodes

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerLayoutVersion.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerCheck.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/KeyValueContainerUtil.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/FilePerBlockStrategy.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/FilePerChunkStrategy.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerCheck.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/impl/CommonChunkManagerTestCases.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/impl/TestFilePerChunkStrategy.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/ChunkKeyHandler.java
In the container-service code, it often creates a `ChunkInfo` object from a proto in order to get length/name. It should get length/name directly from the proto.
HDDS-10410
> HDDS-10410. Avoid creating ChunkInfo.

- hadoop-ozone/dist/src/main/smoketest/s3/MultipartUpload.robot
- hadoop-ozone/dist/src/main/smoketest/s3/objectcopy.robot
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpointStreaming.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneBucketStub.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectPut.java
Currently copyObject does not seem to support eTag based on key's content. It uses a random UUID in CopyObjectResponse.
We need to change this to be the eTag based on the key content instead.
https://issues.apache.org/jira/browse/HDDS-10403
Unit tests, acceptance test, and manual tests.
Compatibilities
- If the source key does not contain eTag field, the copied destination key will have an eTag field
Clean CI run: https://github.com/ivandika3/ozone/actions/runs/8001415597
> HDDS-10403. CopyObject should set ETag based on the key content

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsConfigKeys.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneSecurityUtil.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeClientProtocolServer.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsPolicyProvider.java
- hadoop-hdds/docs/content/feature/Reconfigurability.md
- hadoop-hdds/docs/content/feature/Reconfigurability.zh.md
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/protocolPB/ReconfigureProtocolClientSideTranslatorPB.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/protocolPB/ReconfigureProtocolDatanodePB.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/protocolPB/ReconfigureProtocolOmPB.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/protocolPB/ReconfigureProtocolPB.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/protocolPB/ReconfigureProtocolServerSideTranslatorPB.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMPolicyProvider.java
- hadoop-ozone/dist/src/main/compose/ozonesecure-ha/docker-config
- hadoop-ozone/dist/src/main/compose/ozonesecure-ha/test-leadership.sh
- hadoop-ozone/dist/src/main/compose/ozonesecure/docker-config
- hadoop-ozone/dist/src/main/smoketest/admincli/reconfigure.robot
- hadoop-ozone/dist/src/shell/ozone/ozone
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestReconfigShell.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/reconfig/AbstractReconfigureSubCommand.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/reconfig/ReconfigureCommands.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/reconfig/ReconfigurePropertiesSubcommand.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/reconfig/ReconfigureStartSubcommand.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/reconfig/ReconfigureStatusSubcommand.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/reconfig/ReconfigureSubCommandUtil.java
Fix the issue that "ozone admin reconfig" CLI fails in a secure cluster.
Before the patch, reconfig will fail. Please go to the JIRA page to find the detail failure stack. 
After the patch,  rconfig will succeed. Here is the command output 
```
bash-4.2$ ozone admin reconfig --address=om:9862 --service=OM start
OM: Started reconfiguration task on node [om:9862].
bash-4.2$ ozone admin reconfig --address=scm:9860 --service=SCM start
SCM: Started reconfiguration task on node [scm:9860].
bash-4.2$ ozone admin reconfig --address=datanode:19864 --service=DATANODE start
DN: Started reconfiguration task on node [datanode:19864].
```
https://issues.apache.org/jira/browse/HDDS-10404
new robot test
> HDDS-10404. Ozone admin reconfig command fails with security enabled

- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/cli/OzoneAdmin.java
- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ReplicationManagerStartSubcommand.java
- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ReplicationManagerStatusSubcommand.java
- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ReplicationManagerStopSubcommand.java
- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/SafeModeCheckSubcommand.java
- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/SafeModeExitSubcommand.java
- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/SafeModeWaitSubcommand.java
- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/cert/CleanExpiredCertsSubcommand.java
- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/cert/InfoSubcommand.java
- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/cert/ListSubcommand.java
- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/cert/ScmCertSubcommand.java
- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/container/CreateSubcommand.java
- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/container/InfoSubcommand.java
- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/container/ListSubcommand.java
- hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/container/TestInfoSubCommand.java
`ozone admin` commands use loggers to print to standard output.  They ignore logging configuration due to hard-coded info level.  Log output also lack details like timestamp, thread name, etc. to mimic regular output.
This change replaces `LOG.info` with printing to `System.out`, `LOG.error` with printing to `System.err`.  Log messages from other parts of the code can now be displayed if needed.
`LOG` messages are kept in `UpgradeManager` and `UpgradeTask` (container layout v2 to v3 upgrade tool, introduced recently), which have more complex output.  I think they can benefit from using regular logging.
https://issues.apache.org/jira/browse/HDDS-10405
Tested few commands manually in `ozone` compose environment.
Tested debug level logging with …
> HDDS-10405. ozone admin has hard-coded info loglevel

- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/conf/OzoneManagersCommandHandler.java
Changed the description for `ozone getconf -ozonemanagers` from "gets list of ozone storage container manager nodes in the cluster" to "gets list of Ozone ozone-manager nodes in the cluster" in "OzoneManagersCommandHandler.class"
https://issues.apache.org/jira/browse/HDDS-10365
> HDDS-10365. Fix description for `ozone getconf ozonemanagers`

- SECURITY.md
Currently Security.md only contains Ozone version up to 1.1
This patches include version up to 1.4.
It is also a good idea to add information to the Ozone wiki release guide to update the security.md during the release process.
https://issues.apache.org/jira/browse/HDDS-10214
NA
> HDDS-10214. Update supported versions in security policy up to 1.4.0

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/AbstractCommitWatcher.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinator.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneAtRestEncryption.java
RPC clients reuse thread resources instead of creating a new thread for each Block.
Detail https://github.com/apache/ozone/pull/5791
https://issues.apache.org/jira/browse/HDDS-10384
Existing Test
> HDDS-10384. RPC client Reusing thread resources.

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/BasicOmKeyInfo.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmBucketArgs.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmBucketInfo.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyArgs.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmMultipartKeyInfo.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/SnapshotInfo.java
Refactor some constructors in `package org.apache.hadoop.ozone.om.helpers` to eliminate `@SuppressWarnings("parameternumber")`.
(`OmVolumeArgs` and `SnapshotDiffJob` still have suppression, those require more change, should be done separately.)
https://issues.apache.org/jira/browse/HDDS-10394
CI:
https://github.com/adoroszlai/ozone/actions/runs/8033013820
> HDDS-10394. Fix parameter number warning in om.helpers

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java
A small update to HDDS-9752 such that it works for direct buffers too.
HDDS-9752 assumed the byte buffer is heap buffer which has a backing byte array. It's no longer the case after HDDS-9843 which uses direct buffer, so we need to adapt the code to support that.
https://issues.apache.org/jira/browse/HDDS-10361
Unit tests
> HDDS-10361. [hsync] Output stream should support direct byte buffer.

- hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/TestOzoneClientConfig.java
- hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigType.java
Missing size suffix in some config properties can prevent Datanode from starting up:
```
[main] ERROR ozone.HddsDatanodeService: Exception in HddsDatanodeService.
org.apache.hadoop.hdds.conf.ConfigurationException: Failed to inject configuration to OzoneClientConfig.bytesPerChecksum
at org.apache.hadoop.hdds.conf.ConfigurationReflectionUtil.setField(ConfigurationReflectionUtil.java:146)
at org.apache.hadoop.hdds.conf.ConfigurationReflectionUtil.injectConfigurationToObject(ConfigurationReflectionUtil.java:103)
at org.apache.hadoop.hdds.conf.ConfigurationReflectionUtil.injectConfiguration(ConfigurationReflectionUtil.java:73)
at org.apache.hadoop.hdds.conf.ConfigurationSource.getObject(ConfigurationSource.java:177)
at org.apache.hadoop.ozone.container.ec.reconstruction.ECReconstructionCoordin …
```
> HDDS-10423. Datanode fails to start with checksum size setting without suffix

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/AbstractCommitWatcher.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinator.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneAtRestEncryption.java
This reverts commit 84c6e4d861d907d1ac39e252aa97e8a512ef247b, because it introduced flakiness in the write path.
Checked repeated test runs before HDDS-10384, with HDDS-10384 and after reverting it.  Write tests like `TestFreonWithPipelineDestroy`, `TestSecureOzoneRpcClient#testPutKeyRatisThreeNodesParallel` etc. fail frequently with HDDS-10384, pass before that and after revert.
HDDS-10384 failing: https://github.com/adoroszlai/ozone/actions/runs/8050504234
revert passing: https://github.com/adoroszlai/ozone/actions/runs/8052736373
> Revert "HDDS-10384. RPC client Reusing thread resources. (#6270)"

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/OzoneClientConfig.java
- hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/TestOzoneClientConfig.java
fix the issue that OzoneClientConfig#validate doesn't get called. 
https://issues.apache.org/jira/browse/HDDS-10428
improved unit test
> HDDS-10428. OzoneClientConfig#validate doesn't get called

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/util/S3StorageType.java
In a single-node deployment, no files could be written to Ozone via the S3G as it attempts to use a replication factor of 3 by default. The result of trying to write a file was as below:
```
$ aws s3api put-object --bucket bb1 --key k01 --endpoint http://localhost:9878 --body ~/temp1  
An error occurred (500) when calling the PutObject operation (reached max retries: 4): Internal Server Error
```
This was due to the way replication factor was being resolved on the client side. When ozone.replication config isn't set, storageType was defaulting to "STANDARD" which was leading to a replication factor of 3. 
In this PR, a check is added to return null instead, leaving the resolving of replication factor to the server. This method is what is being followed when a key is written through `ozone …
> HDDS-10327. S3G does not work in a single-node deployment

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeHeartbeatDispatcher.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/TestReconUtils.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconIncrementalContainerReportHandler.java
This PR fixes the UnsupportedOperationException while merging Incremental Container Reports.
Recon processes the Incremental Container Reports (ICRs) being sent from datanodes and to improve performance and process multiple ICRs in a heartbeat,  [HDDS-9883](https://issues.apache.org/jira/browse/HDDS-9883) merged multiple ICRs from datanodes into a single report before sending to Recon ICR handler (`ReconIncrementalContainerReportHandler`) where it handles such merged container reports , but merge operation was throwing `UnsupportedOperationException` while merging ICRs. This PR fixes the issue and handles the merge operation correctly.
https://issues.apache.org/jira/browse/HDDS-10413
This patch was tested manually by adding new `org.apache.hadoop.ozone.recon.scm.TestReconIncrementalContain …
> HDDS-10413. Recon - UnsupportedOperationException while merging Incremental Container Reports.

- hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/ByteBufferOutputStream.java
See [HDDS-10432](https://issues.apache.org/jira/browse/HDDS-10432).  Currently `write(byte[], int, int)` is inherited from OutputStream and thus write byte by byte.
https://issues.apache.org/jira/browse/HDDS-10432
CI
> HDDS-10432. Hadoop FS client write(byte[], int, int) is very slow in streaming

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconTasks.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/ContainerEndpoint.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/fsck/ContainerHealthTask.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/persistence/ContainerHealthSchemaManager.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/fsck/TestContainerHealthTask.java
This PR addresses the corner case when a Recon has earlier identified some MISSING (UNHEALTHY) containers, but they all were EMPTY (No keys mapped), so Recon should filter out such existing MISSING (UNHEALTHY) containers.
In a running cluster, Recon may have identified some MISSING (UNHEALTHY) containers before the [HDDS-9695](https://issues.apache.org/jira/browse/HDDS-9695) was applied. After the fix is applied, in a running cluster, existing MISSING (UNHEALTHY) containers which were actually EMPTY were still shown as MISSING, so this PR change is to filter out such existing MISSING (UNHEALTHY) containers which were actually EMPTY.
https://issues.apache.org/jira/browse/HDDS-10370
Existing Junit integration test `org.apache.hadoop.ozone.recon.TestReconTasks#testEmptyMissingContainerDownNod …
> HDDS-10370. Recon - Handle the pre-existing missing empty containers in clusters.

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerTask.java
Container balancer tries to interrupt current balancing thread upon being stopped. This may fail when the interrupt is before the thread even starts i.e., it hasn't been picked up by the scheduler. As a result, the balancer stop is delayed by the interval for which the thread goes to sleep next, which may be 5m by default for delayStart.
In this PR, a check is added in run() to check whether the containerBalancer is running on the scm. If it is running, only then it goes to sleep for delayStart. Otherwise the sleep is skipped.
https://issues.apache.org/jira/browse/HDDS-8683
Existing tests. No regression is caused by the refactoring in this PR. 
Successful CI run on my fork: https://github.com/Tejaskriya/ozone/actions/runs/7796903702
> HDDS-8683. Container balancer thread interrupt may not work

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMEpochForNonRatis.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
ObjectIDs duplicate when non-Ratis OM start from an existing Ratis transactionInfoTable.
Transaction index should increase incrementally based on the existing transactionInfoTable for non-Ratis rather than from 0.
This approach will facilitate the migration from Ratis to non-Ratis scenarios seamlessly.
https://issues.apache.org/jira/browse/HDDS-10425
**manual tests.**
For origin ratis transactionInfoTable
```bash
bin/ozone debug ldb --db=/home/hadoop/cluster-data/ozonedata/om/db/om.db scan --cf=transactionInfoTable
{ "#TRANSACTIONINFO": {
"term" : 1,
"transactionIndex" : 9
}
```
**(1) without pr**
migrate to non-ratis
```bash
bin/ozone debug ldb --db=/home/hadoop/cluster-data/ozonedata/om/db/om.db scan --cf=transactionInfoTable
{ "#TRANSACTIONINFO": {
"term" : -1,
"transactionIndex" : 3
} …
```
> HDDS-10425. Increase OM transaction index for non-Ratis based on existing Ratis transactionInfoTable

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestListKeysWithFSO.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestListKeysWithFSO.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestListStatus.java
Fix possible NullPointerException which can occur in some cases while invoking listKeysLight from OzoneManagerProtocolClientSideTranslatorPB. 
https://issues.apache.org/jira/browse/HDDS-10367
This patch is test manually. 
Separate epic created to cover testing of hdfs client with S3A protocol: https://issues.apache.org/jira/browse/HDDS-10381
> HDDS-10367. Fix possible NullPointerException in listKeysLight method

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeAdminMonitor.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeAdminMonitorImpl.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeDecommissionManager.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestDatanodeAdminMonitor.java
- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DecommissionStatusSubCommand.java
- hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestDecommissionStatusSubCommand.java
DatanodeAdminMonitor#getContainersReplicatedOnNode() is renamed to something more appropriate i.e., getContainersPendingReplication() as the method only returns a list of under-replicated and unclosed containers, and not all containers like the current name would suggest. Some other minor improvements are also done for the output of `ozone admin datanode status decommission` command to make output match up with the design doc attached the the parent Jira HDDS-9324
https://issues.apache.org/jira/browse/HDDS-10437
As it is minor code refactoring, existing tests cover the cases.
> HDDS-10437. Rename method to getContainersPendingReplication

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsHAURLs.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestFailoverWithSCMHA.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMInstallSnapshotWithHA.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSecretKeySnapshot.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSecretKeysApi.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestStorageContainerManagerHA.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/upgrade/TestHDDSUpgrade.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/upgrade/TestScmHAFinalization.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneHAClusterImpl.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestBlockTokens.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestBlockTokensCLI.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMultipartObjectGet.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/metrics/TestDatanodeQueueMetrics.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestAddRemoveOzoneManager.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMBucketLayoutUpgrade.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMUpgradeFinalization.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotDisabled.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotDisabledRestart.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHA.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHASnapshot.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestSnapshotBackgroundServices.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneManagerSnapshotProvider.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneSnapshotRestore.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/parser/TestOzoneHARatisLogParser.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManagerHA.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestDeletedBlocksTxnShell.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneTenantShell.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestTransferLeadershipShell.java
Make `MiniOzoneHAClusterImpl.Builder.build()` return `MiniOzoneHAClusterImpl`, so that tests do not need to cast the return value.
https://issues.apache.org/jira/browse/HDDS-6713
CI:
https://github.com/adoroszlai/ozone/actions/runs/8083218045
> HDDS-6713. Avoid the need to cast to MiniOzoneHAClusterImpl

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerDoubleBuffer.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerStateMachine.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerProtocolServerSideTranslatorPB.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/RequestHandler.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOMMultiTenantManager.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerDoubleBuffer.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerDoubleBufferWithDummyResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerDoubleBufferWithOMResponse.java
It is generally a bad practice to start a thread inside a constructor; see https://stackoverflow.com/questions/11834173/why-shouldnt-i-use-thread-start-in-the-constructor-of-my-class
Also, quite a few tests (such as `TestOzoneManagerDoubleBuffer`) has to stop the daemon in order to eliminate the race condition in the very beginning.
HDDS-10041
> HDDS-10041. Do not start the daemon inside the OzoneManagerDoubleBuffer constructor.

- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/acl/OzoneNativeAclTestUtil.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/acl/TestOzoneNativeAuthorizer.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/acl/TestParentAcl.java
`TestOzoneNativeAuthorizer` and `TestParentAcl` has some duplicated code that can be extracted into a helper class.
https://issues.apache.org/jira/browse/HDDS-10447
CI:
https://github.com/adoroszlai/ozone/actions/runs/8109661988
> HDDS-10447. Extract helper methods from Ozone native ACL unit tests

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockInputStream.java
- hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestBlockInputStream.java
Currently when read fails from DN, client retries without waiting. In this PR, client will wait based on retry policy before reading again.
https://issues.apache.org/jira/browse/HDDS-10427
Update existing test
> HDDS-10427. Retry read wait based on policy.

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/OzoneClientConfig.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/containergenerator/GeneratorDatanode.java
Enable ozone.fs.hsync.enabled, ozone.chunk.list.incremental, ozone.client.incremental.chunk.list by default.
* Let's enable these features in HDDS-7593 branch.
* If DataNode has not completed upgrade, fall back to full chunk list mode.
https://issues.apache.org/jira/browse/HDDS-10252
Unit test
> HDDS-10252. [hsync] Revisit configuration keys for incremental chunk list after HDDS-9884

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneCluster.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestAddRemoveOzoneManager.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotDisabled.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotDisabledRestart.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneManagerSnapshotAcl.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneSnapshotRestore.java
Do not expose method to set config on `MiniOzoneCluster` after it is already created.
https://issues.apache.org/jira/browse/HDDS-10439
CI:
https://github.com/adoroszlai/ozone/actions/runs/8132769261
> HDDS-10439. Remove setConf from MiniOzoneCluster public interface

- hadoop-hdds/hadoop-dependency-client/pom.xml
- hadoop-hdds/hadoop-dependency-server/pom.xml
- pom.xml
Resolve the CVEs:
https://nvd.nist.gov/vuln/detail/CVE-2023-34453
https://nvd.nist.gov/vuln/detail/CVE-2023-34454
https://nvd.nist.gov/vuln/detail/CVE-2023-34455
An old version of snappy-java lib was replaced with a new one
https://issues.apache.org/jira/browse/HDDS-10459
repo's robot tests
> HDDS-10459. Bump snappy-java to 1.1.10.5 for hadoop-common (CVE fix)

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsSnapshot.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOmSnapshot.java
Adding unit-test for recreating snapshots with deleted snapshot names - `TestOmSnapshot#testSnapshotReuseSnapName`, 
`TestOzoneFsSnapshot#testSnapshotReuseSnapName`
https://issues.apache.org/jira/browse/HDDS-10329
Tested using mvn for **TestOzoneFsSnapshot** and **TestOmSnapshot** inherited files - **TestOmSnapshotLegacy, TestOmSnapshotFsoWithNativeLib, TestOmSnapshotFsoWithoutNativeLib, TestOmSnapshotObjectStore**
> HDDS-10329. [snapshot] Add unit-test for recreating snapshots with deleted snapshot names

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/container/common/helpers/AllocatedBlock.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/pipeline/Pipeline.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMBlockProtocolServer.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestXceiverClientGrpc.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
Make `Pipeline#nodesInOrder` immutable to avoid race condition.
https://issues.apache.org/jira/browse/HDDS-10430
https://github.com/adoroszlai/ozone/actions/runs/8121255974
> HDDS-10430. Race condition around Pipeline#nodesInOrder

- hadoop-hdds/docs/content/feature/Decommission.md
- hadoop-hdds/docs/content/feature/Decommission.zh.md
The command to view status of decommissioning datanodes: `ozone admin datanode status decommission` that was added recently as a part of HDDS-9324 should be mentioned in ozone documents so users are aware of it and can utilise it when necessary.
https://issues.apache.org/jira/browse/HDDS-10458
Checked the rendering with `hugo serve` :
> HDDS-10458. Mention datanode status decommission command in decommission feature docs

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/security/acl/OzoneObjInfo.java
- hadoop-ozone/dist/src/main/smoketest/basic/links.robot
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHA.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAWithAllRunning.java
- hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/BucketManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataReader.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/PrefixManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ResolvedBucket.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/prefix/OMPrefixAclRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/prefix/OMPrefixAddAclRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/prefix/OMPrefixRemoveAclRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/prefix/OMPrefixSetAclRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCreateRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMPrefixAclRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/acl/prefix/TestOMPrefixAclResponse.java
Following up on [HDDS-4715](https://issues.apache.org/jira/browse/HDDS-4715), we also need to resolve the bucket link for prefix ACL.
Here are the changes included in this patch:
-  Include prefix resource type to be `BucketManagerImpl`  so that prefix access under a bucket link will be resolved to the source bucket
- Prefix ACL read: `PrefixManagerImpl#getAcl` will resolve the bucket to get the ACL
- Prefix ACL write: `OMPrefixAclRequest#validateAndUpdateCache` will resolve the bucket before writing the ACL
- This requires passing the resolved prefix `OzoneObj` to the request hooks (`onComplete`, `apply`) so that the request implementation can use the resolved object and not the link object
- Fixed `PrefixManagerImpl#setAcl` so that default ACL is inherited only when the prefix does not …
> HDDS-10412. Prefix ACL check needs to resolve the bucket link

- hadoop-hdds/common/pom.xml
- hadoop-ozone/dist/src/main/license/bin/LICENSE.txt
- hadoop-ozone/dist/src/main/license/jar-report.txt
- hadoop-ozone/ozonefs-shaded/pom.xml
- pom.xml
Remove dependency `commons-pool2`, which seems to be unused.
https://issues.apache.org/jira/browse/HDDS-10457
CI:
https://github.com/adoroszlai/ozone/actions/runs/8124160811
> HDDS-10457. Remove dependency commons-pool2

- .github/labeler.yml
- .github/workflows/label-pr.yml
Automatically label PRs targeting the container reconciliation feature branch.
HDDS-10450
The workflow will not run until merged. There is a similar workflow running successfully for the ozone-site repo . See the [config](https://github.com/apache/ozone-site/blob/HDDS-9225-website-v2/.github/labeler.yml) and [workflow](https://github.com/apache/ozone-site/blob/HDDS-9225-website-v2/.github/workflows/label-pr.yml) there for reference.
> HDDS-10450. Add GitHub actions labeler for the reconciliation feature branch.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmBucketArgs.java
We should refine audit logging for operations modifying bucket properties.
**How can this be useful?**
- Critical for consumers on earlier versions of Ozone who could potentially run into known bugs: [HDDS-7449](https://issues.apache.org/jira/browse/HDDS-7449) and [HDDS-7526](https://issues.apache.org/jira/browse/HDDS-7526).
- Losing bucket replication properties/bucket encryption properties when one (re)sets quota/bucket replication configurations poses significant risks.
- It is difficult for diagnosing the root cause when one runs into such issues just by looking at the audit logs.
- Currently, the audit logs do not provide much insight into what properties have been modified while performing bucket config re(set) operations.
As of today, we are only capturing basic information such as …
> HDDS-10460. Refine audit logging for bucket property updation operations

- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MockDatanodeStorage.java
Fix a memory corruption in test utility caused by (potentially unsafe) memory manipulation.
Found in  HDDS-10431 (#6286). For some reason it only fails for Linux not Mac.
https://issues.apache.org/jira/browse/HDDS-10471
Unit test.
> HDDS-10471. [hsync] MockDatanodeStorage.writeChunk should make a copy of byte string.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ECReplicationConfig.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/RequestAuditor.java
Audit log for key creation is missing information about EC replication (see `replicationFactor=ZERO`).
```
2024-03-05 18:53:20,425 | INFO  | OMAudit | user=hadoop | ip=172.18.0.5 | op=COMMIT_KEY {volume=smxvvmay, bucket=cgszxdst, key=PUTFILE2.txt._COPYING_, dataSize=17289, replicationType=EC, replicationFactor=ZERO} | ret=SUCCESS |  
```
https://issues.apache.org/jira/browse/HDDS-10472
Verified OM audit log for EC key creation in acceptance tests:
```
2024-03-06 10:31:50,226 | INFO  | OMAudit | user=dlfknslnfslf | ip=172.18.0.2 | op=ALLOCATE_KEY {volume=s3v, bucket=erasure, key=testfile, dataSize=29, replicationType=EC, replicationConfig=rs-3-2-1048576} | ret=SUCCESS |  
2024-03-06 10:31:51,434 | INFO  | OMAudit | user=dlfknslnfslf | ip=172.18.0.2 | op=COMMIT_KEY {volume=s3v, …
```
> HDDS-10472. Audit log should include EC replication config

- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmMetadataManager.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/OMRequestTestUtils.java
Set mod time in `OMRequestTestUtils.createOmKeyInfo` to fix the regression in test util that caused test failure in a feature branch. See jira description for more backgrounds.
https://issues.apache.org/jira/browse/HDDS-10482
- Added assertion to prevent such regression from happening on the master branch again.
> HDDS-10482. OMRequestTestUtils.createOmKeyInfo should set key modification time

- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDiffManager.java
Fix intermittent crash in `TestSnapshotDiffManager`:
- Avoid recreating `SnapshotDiffManager` without closing the previous instance.  Actually the new one seems to be unnecessary, as original one is created `@BeforeEach`.
- Close `SnapshotDiffManager` before closing RocksDB objects.
https://issues.apache.org/jira/browse/HDDS-10487
No crash in 500 runs (but had 5 failures due to NPE, reported in HDDS-10490):
https://github.com/adoroszlai/ozone/actions/runs/8191095498
Regular CI:
https://github.com/adoroszlai/ozone/actions/runs/8191527914
> HDDS-10487. Intermittent crash in TestSnapshotDiffManager

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerCheck.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisResponse.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/ECBlockChecksumComputer.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/ReplicatedBlockChecksumComputer.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/DatanodeChunkValidator.java
Some proto2 `ByteString.toByteArray()` calls can be removed in order to avoid buffer copying.
HDDS-10480
> HDDS-10480. Avoid proto2 ByteString.toByteArray() calls.

- .github/workflows/ci.yml
- .github/workflows/intermittent-test-check.yml
- .github/workflows/populate-cache.yml
- .github/workflows/repeat-acceptance.yml
Create a separate CI workflow to populate the cache for Maven dependencies from scratch.  This prevents cache inflation that can happen if existing cache is updated with new dependencies: obsolete dependencies are never removed.
The workflow runs on `master` and `ozone-1.4` branches whenever `pom.xml` files are changed.  It also runs on a schedule to avoid cache miss due to expiry.
Existing workflows are updated to only restore the cache, do not create/update it.
https://issues.apache.org/jira/browse/HDDS-10470
Tested in fork:
- initial commit: https://github.com/adoroszlai/ozone/actions/runs/8170279080/job/22336101638
- no pom change: https://github.com/adoroszlai/ozone/actions/runs/8170585645/job/22337004185
- pom change: https://github.com/adoroszlai/ozone/actions/runs/8170893673/job/22 …
> HDDS-10470. Populate Maven dependency cache in separate workflow

- hadoop-ozone/ozone-manager/pom.xml
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/TestOMClientRequestWithUserInfo.java
- pom.xml
HDDS-10495. Removed JMockit dependency
There's the only unit test left that uses JMockit. I rewrote the test to use Mockito instead and removed JMockit dependency.
https://issues.apache.org/jira/browse/HDDS-10495
unit tests
> HDDS-10495. Removed JMockit dependency

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeInfo.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeUsage.java
`VolumeInfo#configuredCapacity` is unused, can be removed.
Also: let `VolumeUsage` not implement `SpaceUsageSource`.  Long term goal is to access all space usage properties of `VolumeUsage`  via a single call to `snapshot()`.  Removing `implements` is a first step to removing individual methods like `getAvailable()`.
https://issues.apache.org/jira/browse/HDDS-10504
CI:
https://github.com/adoroszlai/ozone/actions/runs/8231787063
> HDDS-10504. Remove unused VolumeInfo#configuredCapacity

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/IOUtils.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ListIterator.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDiffManager.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/ReadReplicas.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/DatanodeSimulator.java
Improve `IOUtils.close` to be able to call it with a collection of any type that implements `AutoCloseable`.
https://issues.apache.org/jira/browse/HDDS-10502
CI:
https://github.com/adoroszlai/ozone/actions/runs/8230153156
> HDDS-10502. Improve generic type of IOUtils.close

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmBucketInfo.java
As part of a [review comment](https://github.com/apache/ozone/pull/6329#pullrequestreview-1918970353) over [HDDS-10460](https://issues.apache.org/jira/browse/HDDS-10460) (PR: [#6329](https://github.com/apache/ozone/pull/6329)), it has been observed that the audit logs pertaining to the bucket creation operation do not capture the bucket quota, owner and replication-related properties. 
Capturing these details is important for improving debugging capabilities.
https://issues.apache.org/jira/browse/HDDS-10475
- Green Git CI: https://github.com/tanvipenumudy/ozone/actions/runs/8243755358/
- The patch has been tested manually on a docker-compose cluster.
**Before changes:**
```
bash-4.2$ ozone sh bucket create voltest/bucktest2 --type=RATIS --replication=THREE --space-quota=1GB …
```
> HDDS-10475. Refine audit logging for bucket creation operation

- hadoop-ozone/dist/src/main/smoketest/recon/recon-api.robot
- hadoop-ozone/dist/src/main/smoketest/topology/cli.robot
Recon Acceptance test is failing for the robot test :-
```
hadoop-ozone/dist/src/main/smoketest/recon/recon-api.robot
```
The discrepancy arises because, in local Docker setups, DataNodes are named using hyphens, such as `datanode-1`, whereas in the upstream (CI) environment, DataNodes utilize underscores, like `datanode_1`. This variation in naming conventions leads to inconsistencies across different environments.
https://issues.apache.org/jira/browse/HDDS-10414
The acceptance test passed locally :- 
```
Check if Recon picks up DN heartbeats                                 | PASS |
Check if Recon Web UI is up …
```
> HDDS-10414. Some acceptance tests fail with Docker Compose V2

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/storage/ContainerProtocolCalls.java
If the block token expires, request an up-to-date token immediately. Prior to this PR, the client would try each DN in the pipeline before it refreshes block token. In this case, trying every DN doesn't help so it better refresh immediately.
https://issues.apache.org/jira/browse/HDDS-10497
> HDDS-10497. [hsync] Refresh block token immediately if block token expires.

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
- As part of a [review comment](https://github.com/apache/ozone/pull/5391#discussion_r1513498047) on PR: [#5391](https://github.com/apache/ozone/pull/5391), it has been observed that since `KeyManager` is dependent on `ScmTopologyClient`, we should start the client before the `KeyManager` in `OzoneManager`.
- Cleanup unused code.
- `KeyManager` is already being stopped prior to the client.
https://issues.apache.org/jira/browse/HDDS-10512
Existing tests should cover the changes, Green Git CI: https://github.com/tanvipenumudy/ozone/actions/runs/8261507655/
> HDDS-10512. Refactor initialization of ScmTopologyClient in OM

- dev-support/rat/rat-exclusions.txt
- hadoop-hdds/docs/pom.xml
- hadoop-hdds/pom.xml
- hadoop-ozone/dev-support/checks/rat.sh
- hadoop-ozone/httpfsgateway/pom.xml
- hadoop-ozone/pom.xml
- pom.xml
To improve Apache Rat configuration and Ozone maven config, I have done:
* Added Rat plugin to the root module (ozone-main) to cover all files in a repo.
* Removed Rat plugin declarations from other modules to make maven and rat configs more readable.
* Moved exclusions to a separate file to make the Maven config more maintainable.
https://issues.apache.org/jira/browse/HDDS-10498
1. I did a manual test by adding a "file.txt" without a license inside to hadoop-hdds-client project and running apache-rat:check goal. The output of the build:
<pre>
[INFO] --- apache-rat:0.16.1:check (default-cli) @ hdds-client ---
[INFO] Rat check: Summary over all files. Unapproved: 1, unknown: 1, generated: 0, approved: 68 licenses.
[WARNING] Files with unapproved licenses: …
> HDDS-10498. Improved configuration for license compliance

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/ContainerMetrics.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java
add metrics for chunk read from internal ratis. 
Currently, there are following metrics on every datanode for chunk reads.
"numReadChunk" : 136237,
"bytesReadChunk" : 1395066880,
"LatencyReadChunkNumOps" : 136237,
"LatencyReadChunkAvgTime" : 1.0, 
The chunk read requests come from both remote user client and internal ratis if the datanode is the leader of the ratis group. Currently, we cannot tell how much data is read by user client, and how much data is read by ratis leader itself. So this task is to introduce a new set of following metrics for read by ratis, 
numReadStateMachine // the request counts from ratis
bytesReadStateMachine // the total bytes read by ratis
So the final goal is we want to know how much data is read by user client. So for read from user client,
bytesReadChunk - …
> HDDS-10516. Add metrics for chunk read from internal ratis

- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java
A user encountered this error when it tries to download a key using the AWS S3 Java SDK (version 1.11.415).
```
ERROR FileOperationServiceImpl - s3Client.getObject invoke error, objectKey:<redacted>. (FileOperationServiceImpl.java:438)
java.lang.ArrayIndexOutOfBoundsException: 110
at com.amazonaws.util.Base16Codec.pos(Base16Codec.java:96)
at com.amazonaws.util.Base16Codec.decode(Base16Codec.java:87)
at com.amazonaws.util.Base16Lower.decode(Base16Lower.java:53)
at com.amazonaws.util.BinaryUtils.fromHex(BinaryUtils.java:48)
at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1456)
...
```
Although the key was able to be downloaded using AWS s3api
```
aws s3api --endpoint <redacted> get-object --bucket <redacted> --key <redacted> download.txt
{
"AcceptRanges": "bytes", …
```
> HDDS-10521. ETag field should not be returned during GetObject if the key does not contain ETag field

- hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/MiniOzoneChaosCluster.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestSafeMode.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/node/TestDecommissionAndMaintenance.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/upgrade/TestHDDSUpgrade.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneCluster.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterProvider.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneHAClusterImpl.java
`MiniOzoneCluster.Builder` allows creating multiple cluster instances from the same builder.  To avoid conflict, users (currently only `MiniOzoneClusterProvider`) need to set new cluster ID and a copy of the configuration.  The goal of this change is to automatically set the cluster ID and config whenever `build()` is called.
https://issues.apache.org/jira/browse/HDDS-10440
CI:
https://github.com/adoroszlai/ozone/actions/runs/8139597150
> HDDS-10440. Set new cluster ID and config instance in `MiniOzoneCluster#build()`

- .github/workflows/populate-cache.yml
- hadoop-ozone/ozonefs-hadoop2/pom.xml
- hadoop-ozone/ozonefs-hadoop3-client/pom.xml
- hadoop-ozone/ozonefs-hadoop3/pom.xml
- hadoop-ozone/ozonefs-shaded/pom.xml
- hadoop-ozone/pom.xml
- pom.xml
`maven-dependency-plugin` seems to ignore exclusions of transitive dependencies ([MDEP-844](https://issues.apache.org/jira/browse/MDEP-844)), resulting in larger than necessary Maven cache (including a 250MB jar for `aws-java-sdk-bundle` via Ranger).
This PR changes the `populate-cache` workflow to run a regular build for creating the cache (suggested in [MDEP-904](https://issues.apache.org/jira/browse/MDEP-904)).  This reduces cache size from 750MB to 360MB.
Shading is skipped to speed up the build.  A new property `maven.shade.skip` is added to only skip actual shading while still building (some) `ozonefs` modules.  Only `ozonefs-hadoop2` is included, not the ones for Hadoop 3.  The latter are unnecessary, since we already get the same dependencies by using the same version of Hadoop …
> HDDS-10496. Fetch dependencies using actual build

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFSInputStream.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ByteBufferPositionedReadable.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/CapableOzoneFSInputStream.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneFSInputStream.java
Support ByteBufferPositionedReadable in OzoneFSInputStream. 
This will benefit HBase read.
https://issues.apache.org/jira/browse/HDDS-10511
New integration test
> HDDS-10511. Support ByteBufferPositionedReadable in OzoneFSInputStream.

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestStorageContainerManager.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecureOzoneCluster.java
Avoid `BindException` in two integration tests when run with Java 17.
```
at org.apache.hadoop.ozone.om.OzoneManager.startRpcServer(OzoneManager.java:1273)
at org.apache.hadoop.ozone.om.OzoneManager.getRpcServer(OzoneManager.java:1247)
at org.apache.hadoop.ozone.om.OzoneManager.<init>(OzoneManager.java:702)
at org.apache.hadoop.ozone.om.OzoneManager.createOm(OzoneManager.java:768)
at org.apache.hadoop.ozone.TestSecureOzoneCluster.testSecureOmReInit(TestSecureOzoneCluster.java:887)
```
```
at org.apache.hadoop.hdds.scm.server.StorageContainerManager.startRpcServer(StorageContainerManager.java:1126)
at org.apache.hadoop.hdds.scm.server.SCMDatanodeProtocolServer.<init>(SCMDatanodeProtocolServer.java:173)
at org.apache.hadoop.hdds.scm.server.StorageContainerManager.<init>(StorageContainerManag …
```
> HDDS-10120. BindException in integration tests with Java 17

- pom.xml
The com.objenesis:objenesis:1.0 dependency is not used anywhere in the project, so it has bee removed.
https://issues.apache.org/jira/browse/HDDS-10534
CI verifications
> HDDS-10534. Removed objenesis dependency

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/fs/SpaceUsageSource.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/fs/MockSpaceUsageSource.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/StorageVolume.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeInfo.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeUsage.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestHddsDispatcher.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestReservedVolumeSpace.java
Keeping track of reserved space is split between `VolumeInfo` and `VolumeUsage`.  The goal of this change is to make it a responsibility of `VolumeUsage` only.
https://issues.apache.org/jira/browse/HDDS-10505
CI:
https://github.com/adoroszlai/ozone/actions/runs/8252722437
> HDDS-10505. Move space reservation logic to VolumeUsage

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerStateMachine.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerStateMachine.java
OM is not getting stopped even after Leader is elected but Leader is not ready. This is an impact of HDDS-10026.
As solution, need update lastAppliedTransactionId with notifiedIndex if that is in sequence. So that Ratis can also get latest sequenceId as updated.
https://issues.apache.org/jira/browse/HDDS-10546
- Unit test covers the update of appliedTransaction
- Impacted area by Integration test
> HDDS-10546. OM startup failure as leader is not getting ready

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/SnapshotInfo.java
- hadoop-ozone/dist/src/shell/ozone/ozone
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/OzoneRepair.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/RDBRepair.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/om/SnapshotRepair.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/om/package-info.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/package-info.java
In the past, we have seen many instances (HDDS-8530, HDDS-8832, and recently HDDS-10524) when SnapshotChain corruption was causing OM to get stuck on restart. Lots of bugs related to snapshot chain corruption have been fixed but we still issue some occurrences here and there (HDDS-10524 is a very recent one).
This change is to implement a tool that can be used to repair the snapshot chain corruption once a corrupted entry is identified. 
The idea for this tool is from HDDS-8100. This change also provides a base setup for HDDS-8100 and can be extended to provide support for other cases HDDS-8101, HDDS-8824, HDDS-10295, etc.
HDDS-9802
Tested it on the docker.
> HDDS-9802. Tool to fix corrupted snapshot chain

- hadoop-hdds/common/pom.xml
- hadoop-hdds/hadoop-dependency-test/pom.xml
- hadoop-ozone/fault-injection-test/mini-chaos-tests/pom.xml
- hadoop-ozone/integration-test/pom.xml
- pom.xml
Workaround for [SUREFIRE-1815](https://issues.apache.org/jira/browse/SUREFIRE-1815), which affects 3.0.0-M5, by downgrading to M4.  Cannot upgrade to M6 or newer, because forks are not killed correctly ([SUREFIRE-1722](https://issues.apache.org/jira/browse/SUREFIRE-1722), HDDS-10174) as of 3.2.5.
SUREFIRE-1815 causes intermittent fork timeout due to not being able to interrupt e.g. container scanner thread:
```
"main" 
java.lang.Thread.State: WAITING
at java.lang.Object.wait(Native Method)
at java.lang.Thread.join(Thread.java:1257)
at java.lang.Thread.join(Thread.java:1331)
at org.apache.hadoop.ozone.container.ozoneimpl.AbstractBackgroundContainerScanner.shutdown(AbstractBackgroundContainerScanner.java:149)
at org.apache.hadoop.ozone.container.ozoneimpl.BackgroundContainerDataScanner.shutd …
```
> HDDS-10552. Downgrade Surefire to 3.0.0-M4

- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/db.json
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/routes.json
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/insights/om/om.tsx
New Enhancement on Recon Directories Pending for Deletion Inside OMDB Insight to display the count of deletePending directories and the corresponding data size.
limit (optional)
Only returns the limited number of results. The default limit is 1000.
Returns
Returns set of directories pending for deletion.
https://issues.apache.org/jira/browse/HDDS-9085
{
"lastKey": "/-4611686018427388160/-9223372036854775552/-9223372036854767358/240122081700/-9223372036854767357",
"replicatedDataSize": 0,
"unreplicatedDataSize": 103734,
"deletedDirInfo": [
{
"**key": "/-4611686018427388160/-9223372036854775552/-9223372036854767358/240122081700/-9223372036854767357"**,
"**path": ".Trash/hadoop/240122081700**",
"inStateSince": 1705911362730,
"size": 103734,
"replicatedSize": 0,
"replicationInfo": { …
> HDDS-9085. Recon Directories Pending for Deletion Inside OMDB Insight

- pom.xml
Upgrade Zookeeper to 3.8.4 due to ZOOKEEPER-4799.
https://issues.apache.org/jira/browse/HDDS-10554
```
$ ls -1 hadoop-ozone/dist/target/ozone-1.5.0-SNAPSHOT/share/ozone/lib/zookeeper-*
hadoop-ozone/dist/target/ozone-1.5.0-SNAPSHOT/share/ozone/lib/zookeeper-3.8.4.jar
hadoop-ozone/dist/target/ozone-1.5.0-SNAPSHOT/share/ozone/lib/zookeeper-jute-3.8.4.jar
```
CI:
https://github.com/adoroszlai/ozone/actions/runs/8346528435
> HDDS-10554. Bump Zookeeper to 3.8.4

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmMetrics.java
- Start/Stop cluster in `@BeforeAll`,`@AfterAll`, aim to only start one cluster for all tests
- change assertCounter to assertEqual to assert the "current value" with "initial value" + "expected increment value" , the "initial value" is fetched at the beginning of each subtest. 
- modified some resource names between subtests to ensure no conflict in the same cluster.
This PR isn't finished yet and I face a problem, I would like to solve this and commit again.
Problem:
Some tests likely cannot use the same cluster, if I comment out all the startCluster() and shutdown(), the below OM dummyException happens:
```
[ERROR]   TestOmMetrics.testAclOperations:663 » OM dummyException
663   client.getObjectStore().createVolume("volumeacl");
[ERROR]   TestOmMetrics.testAclOperationsHA:691 » OM …
```
> HDDS-10311. Speed up TestOmMetrics

- hadoop-hdds/framework/pom.xml
LMAX Disruptor is required by Log4j2 async loggers, used by audit logging in Ozone.  The goal of this change is to mark it as a runtime dependency for clarification.
https://issues.apache.org/jira/browse/HDDS-10544
`dependency` check verifies the jar is still included in `share/ozone/lib`.
CI:
https://github.com/adoroszlai/ozone/actions/runs/8322480289
> HDDS-10544. Move LMAX Disruptor to runtime scope

- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DecommissionStatusSubCommand.java
Added --json option for json formatted output to `ozone admin datanode status decommission` command.
https://issues.apache.org/jira/browse/HDDS-10436
Tested the format of the output using a docker cluster.
> HDDS-10436. datanode status decommission command should have json output option

- hadoop-hdds/docs/content/interface/HttpFS.md
ListStatus Iterative is currently a unsupported operation, but in the docs it is shown as supported. 
Mark this as unsupported in the docs as well.
Mark ListStatus Iterative as an unsupported operation.
https://issues.apache.org/jira/browse/HDDS-10551
Build the project, checked the generated httpfs.html files.
> HDDS-10551. Improve HTTPFS Documentation for Iterative Liststatus Functionality

- hadoop-hdds/rocks-native/pom.xml
- hadoop-hdds/rocks-native/src/CMakeLists.txt
While building rocksdb tools lib, makefile of rocksdb adds native optmization gcc flags when compiling rocksdb code. This makes the built code incompatible with other chipsets, where it fails with illegal instruction when loading the native lib on ozone manager jvm.
Setting PORTABLE=1 while building rocksdb tools will fix this particular issue, and also adding -O0 flag while compiling jni on ozone will prevent the same on ozone jnilib side.
https://github.com/facebook/rocksdb/blob/v7.7.3/INSTALL.md#:~:text=By%20default%20the,make%20static_lib.
https://issues.apache.org/jira/browse/HDDS-10477
Successful build and checking the native lib manually on various instance
> HDDS-10477. Make Rocksdb tools native lib compatible with all chipset with the same arch

- hadoop-hdds/rocks-native/pom.xml
Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.0.2:copy-dependencies (copy-jars) on project hdds-rocks-native: Artifact has not been packaged yet. When used on reactor artifact, copy should be executed after packaging: see MDEP-187.
I found the file names mismatch in the the referred directory
https://issues.apache.org/jira/browse/HDDS-10118
Tested with command line 
alias mvn11="JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home && mvn"
mvn11 clean install -DskipTests -e -DskipShade -X -Drocks_tools_native
> HDDS-10118. hdds-rocks-native fails to build with Java11+

- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/ChunkKeyHandler.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/ContainerChunkInfo.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/ReadReplicas.java
This update addresses compatibility concerns with Java 17 by transitioning from GSON to Jackson in the `Debug-Shell` module. This change simplifies dependencies and ensures smooth operation across different Java versions.
Parent Jira Issue: [HDDS-10538](https://issues.apache.org/jira/browse/HDDS-10538)
This patch streamlines our Debug-Shell Implementation.
Affected Classes:
```
- ChunkKeyHandler.java
- ReadReplicas.java
- ContainerChunkInfo.java
```
https://issues.apache.org/jira/browse/HDDS-10541
To test out the changes we have to run :- `TestOzoneDebugShell` Integration test.
The forked CI also ran successfully.
> HDDS-10541. Replace GSON with Jackson in debug commands

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/server/JsonUtils.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManager.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/DiskUsageSubCommand.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/FileSizeDistSubCommand.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/NSSummaryCLIUtils.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/QuotaUsageSubCommand.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/SummarySubCommand.java
This update addresses compatibility concerns with Java 17 by transitioning from GSON to Jackson in the `NSSummary` code. This change simplifies dependencies and ensures smooth operation across different Java versions.
Parent Jira Issue: [HDDS-10538](https://issues.apache.org/jira/browse/HDDS-10538)
This patch streamlines our Subcommands Implementation.
Affected NSSummary-Subcommands Classes:
```
- FileSizeDistSubCommand.java
- DiskUsageSubCommand.java
- NSSummaryCLIUtils.java
- QuotaUsageSubCommand.java
- SummarySubCommand.java
- TestReconWithOzoneManager.java
```
https://issues.apache.org/jira/browse/HDDS-10540
The existing UT's passed successfully. 
And the forked CI passed successfully as well.
> HDDS-10540. Replace GSON with Jackson in nssummary.

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientWithRatis.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerProtocolServerSideTranslatorPB.java
Fix testParallelDeleteBucketAndCreateKey
The root cause is the `preExecute#resolveBucketAndCheckKeyAcls` of `CreateKey` may execute after `deleteBucket`, then the `CreateKey#preExecute` will throw an exception, so the test will fail.  For fix this, we just need to add the waiting time.
https://issues.apache.org/jira/browse/HDDS-10143
Before, lots of failures.
https://github.com/xichen01/ozone/actions/runs/8158284595
After, All successful
https://github.com/xichen01/ozone/actions/runs/8158363756
> HDDS-10143. Fix intermittent failure in testParallelDeleteBucketAndCreateKey

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
When a volume has more than "1024" buckets, the command of "ozone fs -ls /volume" will reach endless loop.
It's caused by incorrect parameter passing in `listStatus`.
https://issues.apache.org/jira/browse/HDDS-10562
unit test.
> HDDS-10562. Fix endless loop in ozone fs -ls

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
HDDS-10564. Make Outputstream writeExecutor daemon threads.
[HDDS-10383](https://issues.apache.org/jira/browse/HDDS-10383) added new thread pools in the output stream. They should be made daemon threads so that processes don't wait for them when exiting. (The bug is in the command line which does not close FileSystem object. Nonetheless, it would still be a good idea to make these thread pools daemon)
https://issues.apache.org/jira/browse/HDDS-10564
Deployed on a real cluster, with HBase on Ozone, repeated the same command to verify that the command no longer hangs.
> HDDS-10564. Make Outputstream writeExecutor daemon threads.

- pom.xml
HDDS-10579. Remove org.ow2.asm dependency
The org.ow2.asm:asm:5.0.4 dependency is not used anywhere in the project and can be safely removed.
https://issues.apache.org/jira/browse/HDDS-10579
Existing tests
> HDDS-10579. Remove org.ow2.asm dependency

- hadoop-hdds/docs/content/feature/ErasureCoding.md
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/AbstractOzoneFileSystemTest.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/AbstractRootedOzoneFileSystemTest.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/OzoneFileSystemTests.java
ofs/o3fs is able to write keys/files with EC replication config, but there is no unit test and doc to explain how to do it. So this pr makes it.
https://issues.apache.org/jira/browse/HDDS-10553
1) Unit Test
2) Tested locally.
hadoop client write:
key info:
> HDDS-10553. Add test case for creating file with EC replication config

- hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - ListKey Metrics.json
The patch fixes minor orientation issues with the visualisations over the Ozone - List Keys Metrics Dashboard. 
Please find more details over the [Jira ticket](https://issues.apache.org/jira/browse/HDDS-10448).
https://issues.apache.org/jira/browse/HDDS-10448
The patch was tested manually on an Ozone docker-compose cluster with the monitoring add-ons.
> HDDS-10448. Orientation fixes for Ozone - List Keys Metrics Dashboard

- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/DiskUsageSubCommand.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/SummarySubCommand.java
- This issue arose from direct calls to methods like `.asInt()` and `.asText()` on potentially null `JsonNode` objects returned by `.get(String)` when the expected keys were missing in the JSON response.
```
Cannot invoke "com.fasterxml.jackson.databind.JsonNode.asInt()" because the return value of
"com.fasterxml.jackson.databind.JsonNode.get(String)" is null
```
- To resolve this, we employed the `.path(String)` method followed by `.asInt(defaultValue)` or `.asText(defaultValue)` to safely access and convert JSON fields. The `.path(String)` method ensures a null-safe way to access JSON fields, returning a "missing node" instead of null for absent keys, thereby preventing NPEs. Furthermore, by specifying default values for `.asInt(defaultValue)` and `.asText(defaultValue)`, we ensured …
> HDDS-10581. NPE in SummarySubCommand & DiskUsageSubCommand.

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisor.java
`ReplicationSupervisor#Builder#threadNamePrefix` is never called, prefix is null:
```
2024-03-24 12:17:18,388 [nullContainerReplicationThread-0] INFO reconstruction.ECReconstructionCoordinatorTask: IN_PROGRESS reconstructECContainersCommand ...
```
Fix it by using `threadNamePrefix` from `StateContext`, remove unnecessary variable from `ReplicationSupervisor#Builder`.
https://issues.apache.org/jira/browse/HDDS-10583
```
$ mvn clean test -Dtest='TestECContainerRecovery,TestReconAndAdminContainerCLI'
...
$ grep -m1 ContainerReplicationThread hadoop-ozone/integration-test/target/surefire-reports/*txt
hadoop-ozone/integration-test/target/surefire-reports/org.apache.hadoop.ozone.recon.TestReconAndAdminContainerCLI-output.txt
2024-03-24 13:39:15,367 …
```
> HDDS-10583. Thread name prefix in ReplicationSupervisor is null

- hadoop-ozone/dev-support/checks/coverage.sh
Exclude Protobuf v3 generated code from coverage calculation.
Other minor improvements:
- Combine `find` commands.
- Use version from `pom.xml` for `maven-dependency-plugin`.
https://issues.apache.org/jira/browse/HDDS-10584
Temporarily enabled coverage for fork build, compared results:
https://github.com/adoroszlai/ozone/actions/runs/8409710921 (without fix)
vs.
https://github.com/adoroszlai/ozone/actions/runs/8409713572 (with fix)
> HDDS-10584. Exclude proto3 classes from coverage

- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/client/ScmTopologyClient.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
- After the change implemented in: [#5391](https://github.com/apache/ozone/pull/5391), the network topology layer schema file is now loaded for every key-level read operation, flooding the OM logs (please find the below logs for reference).
- This is because a new `NetworkTopologyImpl` object is being instantiated for each read. As part of this instantiation, `NodeSchemaManager` is initialized each time resulting in the loading of the schema file each time.
- To optimize this process, a new `NetworkTopologyImpl` object is now generated only when the fetched network topology cluster tree differs from the current cluster tree.
- This object generation is now bound by the rate specified by the `ozone.om.network.topology.refresh.duration` configuration which defaults to 1 hour.
- This ensures …
> HDDS-10586. Avoid loading network topology layer schema file for every read

- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ContainerBalancerStopSubcommand.java
- hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestContainerBalancerSubCommand.java
`ozone admin containerbalancer stop` command seems stuck and does not return anything while it is in STOPPING state waiting for the current iteration to complete. 
Print progress message to improve the logs for containerbalancer CLI.
https://issues.apache.org/jira/browse/HDDS-10510
Manually tested this patch using a docker cluster. Also got a clean CI run.
> HDDS-10510. Improve user experience with containerbalancer CLI

- hadoop-ozone/s3gateway/pom.xml
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectPut.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestPartUpload.java
Currently, the MessageDigest instance is a thread local variable (one per S3G Jetty thread). MessageDigest requires the call to either `MessageDigest#digest` or `MessageDigest#reset` to reset the digest.
In normal ObjectEndpoint#put flow, MessageDigest#digest is called after the data has been written to the datanodes, before the key is committed. However, **if an IOException happens (e.g. EOFException due to client cancelling during the write), the digest will not be reset and remains in the inconsistent state.** This will affect the subsequent request that uses the same thread and therefore the ETag generated will be completely different from the md5 hash of the object causing AWS S3 SDK to detect inconsistent hash when downloading the object.
The issue can be replicated using an S3G …
> HDDS-10587. Reset the thread-local MessageDigest instance during exception

- hadoop-hdds/hadoop-dependency-client/pom.xml
- hadoop-hdds/hadoop-dependency-server/pom.xml
- hadoop-ozone/ozonefs-hadoop3/pom.xml
- pom.xml
The current hadoop-shaded-guava (1.1.1) depends/built on guava-30.1.1 that has a CVE - https://nvd.nist.gov/vuln/detail/CVE-2023-2976. Upgrading the hadoop-shaded-guava up to 1.2.0 resolves the issue (depends on guava-32.0.1)
https://issues.apache.org/jira/browse/HDDS-10588
Existing hadoop related robot tests
> HDDS-10588. Bump hadoop-shaded-guava to 1.2.0

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/protocolPB/ContainerCommandResponseBuilders.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/storage/ContainerProtocolCalls.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/audit/DNAction.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java
- hadoop-hdds/interface-client/src/main/proto/DatanodeClientProtocol.proto
- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ContainerOperationClient.java
- hadoop-ozone/dist/src/main/smoketest/freon/echoRPCLoad.robot
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestContainerSmallFile.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestDNRPCLoadGenerator.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/DNRPCLoadGenerator.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/Freon.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OmRPCLoadGenerator.java
Add a new freon tool similar to `ozone freon om-echo` that can be used to benchmark client to DataNode route-trip latency.
Usage:
`ozone freon dn-echo --container-id=1 -n 100000 -t 32 --payload-req=0 --payload-resp=1024`
This tool requires SCM superuser privilege.
It sends an echo request and receives the response to DataNodes associated with container specified with `--containerID`, repeat `100000` times, using `32` threads. The request has a `0`KB payload and the response has `1024`KB payload.
https://issues.apache.org/jira/browse/HDDS-10442
Two unit tests, also tested in a real cluster.
> HDDS-10442. [hsync] Add a Freon tool to measure client to DataNode round-trip latency

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/SnapshotInfo.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SnapshotChainManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotPurgeRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotPurgeResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotPurgeRequestAndResponse.java
Currently when snapshot is purged, it is not removed from the snapshotInfoTable cache. Because of which it is possible that a purged snapshot is added by `SnapshotSetProperty` API.
`KeyDeletingService` and `SnapshotDeletingService` are two background service which run in parallel.
1). KeyDeletingService updates deep clean flag and exclusive size for a snapshot.
2). SnapshotDeletingService purges a deleted snapshot.
KeyDeletionService will try to mark a snapshot deep clean here: [code](https://github.com/apache/ozone/blob/2f2234c7b61714404399ada8f31b3fb4772b613a/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/KeyDeletingService.java#L475)
Since it is in a loop, it is possible when KeyDeletingService is going over all the snapshot. Meanwhile user deletes the …
> HDDS-10524. [Snapshot] Invalidate the cache entry from snapshotInfoTable cache in OMSnapshotPurgeRequest

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneAtRestEncryption.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java
fix the issue that a overwrite file's encryption info is not properly set. 
https://issues.apache.org/jira/browse/HDDS-10594
new unit test logic
> HDDS-10594. File encryption info is not properly set when overwrite a file

- hadoop-ozone/dist/src/main/smoketest/admincli/container.robot
- hadoop-ozone/dist/src/main/smoketest/admincli/datanode.robot
HDDS-9764. Add Robot test for JSON output where missing
- Added robot test for:
`ozone admin container info "${CONTAINER}" --json`
`ozone admin container report --json`
`ozone admin datanode usageinfo -m --json`
- Added missing JSON keys in incomplete command `ozone admin container`
https://issues.apache.org/jira/browse/HDDS-9764
CI/acceptance workflow run on the fork git repo
Test Incomplete command:
https://github.com/will-sh/ozone/actions/runs/8447788465/job/23139219880#step:5:733
Test List containers as JSON:
https://github.com/will-sh/ozone/actions/runs/8447788465/job/23139219880#step:5:727
Test Report containers as JSON :
https://github.com/will-sh/ozone/actions/runs/8447788465/job/23139219880#step:5:729
Get usage info as JSON: …
> HDDS-9764. Add Robot test for JSON output where missing

- hadoop-hdds/hadoop-dependency-client/pom.xml
- hadoop-hdds/hadoop-dependency-server/pom.xml
- pom.xml
It's a continuation of the discussion started here - https://github.com/apache/ozone/pull/6441
hdds-hadoop-dependency-(client|server) modules depend on hadoop-common, the latter depends on com.nimbusds:nimbus-jose-jwt:9.8.1 (through org.apache.hadoop:hadoop-auth).
The 9.8.1th version of the com.nimbusds:nimbus-jose-jwt library contains a shaded version of the net.minidev:json-smart:1.3.2 (https://bitbucket.org/connect2id/nimbus-jose-jwt/src/815b98228df7be7b918ae368ea003a034768f769/pom.xml#lines-59) that has a CVE - https://nvd.nist.gov/vuln/detail/CVE-2021-31684.
Upgrading the nimbus-jose-jwt up to 9.24 will resolve the issue - there the json-smart was replaced with google-gson library
https://issues.apache.org/jira/browse/HDDS-10600
Existing hadoop-related robot tests
> HDDS-10600. Bump nimbus-jose-jwt to 9.37.2

- hadoop-ozone/dist/src/main/compose/ozone-ha/test.sh
- hadoop-ozone/dist/src/main/smoketest/s3/commonawslib.robot
- hadoop-ozone/dist/src/main/smoketest/s3/objecthead.robot
- hadoop-ozone/dist/src/main/smoketest/s3/objectputget.robot
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectPut.java
Fix a bug where attempting to create empty file in FSO bucket via S3 Gateway results in creation of a directory.
```
$ ozone sh bucket create --layout FILE_SYSTEM_OPTIMIZED /s3v/fso-bucket
$ hdfs dfs -touch s3a://fso-bucket/empty.s3a
$ ozone sh key info /s3v/fso-bucket/empty.s3a
{
"name" : "empty.s3a/",
"dataSize" : 0,
...
"ozoneKeyLocations" : [ ],
"file" : false
}
```
The same works OK in `OBJECT_STORE` and `LEGACY` buckets.
It was broken by HDDS-7594, which fixed a bug where attempt to create directory through S3G created files instead.  In other words, prior behavior was also wrong, just the other way around.
https://issues.apache.org/jira/browse/HDDS-10570
Added test case in unit test (`TestObjectPut`).
Changed acceptance tests to run tests on all three bucket layout types.
Also …
> HDDS-10570. S3A: `fs -touch` creates directory instead of empty file in FSO bucket

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NetworkTopologyImpl.java
1. The changes introduced in PR: [#5391](https://github.com/apache/ozone/pull/5391) involve reconstructing the hierarchical cluster tree object (that represents the network topology) on the Ozone Manager side.
2. Under the `NetworkTopology` class, various operations employ the **`==`/`!=`** operator for comparison.
3. However, this comparator needs to be modified to utilize the `InnerNode#equals` method instead. This adjustment is required as certain use cases, as described in **`1`**., involve object reconstruction necessitating custom equality comparisons based on individual object attributes.
https://issues.apache.org/jira/browse/HDDS-10507
Existing tests should cover the changes, Green Git CI: https://github.com/tanvipenumudy/ozone/actions/runs/8433408560
> HDDS-10507. Use equals() instead of == for nodes in NetworkTopology

- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/ContainerEndpoint.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestContainerEndpoint.java
This PR is to address a bug in filtering the EMPTY_MISSING containers in ContainerEndPoint API `"api/v1/unhealthy/{state}"`
ContainerEndPoint API `"api/v1/unhealthy/{state}"` is not filtering the EMPTY_MISSING containers as expected.
https://issues.apache.org/jira/browse/HDDS-10636
Tested with adding Junit manual test cases. Here is green CI [link](https://github.com/devmadhuu/ozone/actions/runs/8524543190).
> HDDS-10636. Ozone Recon - Filter EMPTY MISSING Containers in UnHealthy State Containers API

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
- hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyDeleteRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyDeleteRequestWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeysDeleteRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OmKeysDeleteRequestWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyDeleteResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyDeleteResponseWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeysDeleteResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeysDeleteResponseWithFSO.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeyDeleteResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeyDeleteResponseWithFSO.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeysDeleteResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/TestOMKeysDeleteResponseWithFSO.java
This aims to backport fix HDDS-9930 from feature branch (HDDS-7593) to master branch. Minor conflicts in import and constructor.
```
HDDS-9930. Remove open keys as well when keys are deleted from KeyTable (#6079)
(cherry picked from commit 2651d4c20851f78d5059a7145edc4e17a0b52608)
Conflicts:
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OmKeysDeleteRequestWithFSO.java
hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeysDeleteResponseWithFSO.java
```
https://issues.apache.org/jira/browse/HDDS-9930
- Existing tests should pass.
> HDDS-9930. Remove open keys as well when keys are deleted from KeyTable (cherry pick to master)

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMetrics.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotPurgeRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotSetPropertyRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotPurgeRequestAndResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotSetPropertyRequestAndResponse.java
For snapshot purge and set snapshot property, there is no OM log or audit log. Without logs, it is hard to debug an issue like Snapshot chain corruption (e.g. HDDS-10524).
This change is to add logs so that, there is a way to know which snapshot is updated by which request. It also adds metrics for `SnapshotPurgeRequest` and `SetSnapshotPropertyRequest` APIs for monitoring purposes.
HDDS-9200
Updated existing unit tests to validate that metrics are populated correctly.
> HDDS-9200. [Snapshot] Added logs and metrics for snapshot purge and set property APIs

- hadoop-hdds/docs/content/interface/Cli.zh.md
- hadoop-hdds/docs/content/interface/_index.zh.md
HDDS-5567. interface/Cli.md translate to Chinese.
Translated interface/Cli.md to Chinese.
Corrected a parent title from "编程接口" to "客户端接口" to better align with the English expression "Client Interfaces"
[HDDS-5567](https://issues.apache.org/jira/browse/HDDS-5567)
hugo serve
> HDDS-5567. interface/Cli.md translation

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockInputStream.java
HDDS-10591. [hsync] improve block token refresh message.
Usually an expired block token received by a DataNode is refreshed properly. However the relevant log messages look scary and confusing.
* Some of the logs should tone down. Instead of ERROR, it should be a WARN, because the exception will be retried.
* The log messages surrounding block token refresh should be more clear.
https://issues.apache.org/jira/browse/HDDS-10591
Log message only. Existing unit tests should suffice.
> HDDS-10591. [hsync] improve block token refresh message.

- pom.xml
The cglib:cglib:3.3.0 dependency is not used anywhere in the project and can be safely removed.
https://issues.apache.org/jira/browse/HDDS-10659
Existing tests
> HDDS-10659. Remove cglib dependency

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMStateMachine.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
Currently during normal SCM stop it's going into deadlock situation, detail is in Jira.
During normal SCM stop we should not terminate SCM through statemachine when called by ratis. Instead SCM should stop all the worker threads and shutdown gracefully.
https://issues.apache.org/jira/browse/HDDS-10643
Verified in the cluster for graceful exit
> HDDS-10643. Avoid terminating SCM by statemachine during normal SCM stop.

- hadoop-ozone/dist/src/main/smoketest/s3/objectcopy.robot
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/util/S3Consts.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectPut.java
Need to support x-amz-metadata-directive: specifies whether the metadata is copied from the source object or replaced with metadata that's provided in the request. When copying an object, you can preserve all metadata (the default) or specify new metadata. If this header isn’t specified, COPY is the default behavior.
Valid Values: COPY | REPLACE
See: https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html#API_CopyObject_RequestSyntax
https://issues.apache.org/jira/browse/HDDS-10645
Unit test and acceptance test.
Clean CI run: https://github.com/ivandika3/ozone/actions/runs/8589734492
> HDDS-10645. Support x-amz-metadata-directive in CopyObject

- hadoop-hdds/docs/content/interface/Ofs.zh.md
HDDS-5568. interface/Ofs.md translation to Chinese
https://issues.apache.org/jira/browse/HDDS-5568
hugo serve
> HDDS-5568. interface/Ofs.md translation

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/ContainerClientMetrics.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/storage/ContainerProtocolCalls.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/tracing/TracingUtil.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneFSInputStream.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneFSOutputStream.java
- hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java
Add client side trace spans to ofs file system APIs and input/output stream APIs.
Select screenshots:
input stream read()
outputstream hsyc
file system contentSummary API
file system create file API
https://issues.apache.org/jira/browse/HDDS-10268
Tested in a dev cluster.
> HDDS-10268. [hsync] Add OpenTracing traces to client side read path

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequestWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3MultipartUploadCompleteResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3MultipartUploadCompleteResponseWithFSO.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/s3/multipart/TestS3MultipartResponse.java
S3a provides multiple mapreduce [committers](https://hadoop.apache.org/docs/current/hadoop-aws/tools/hadoop-aws/committers.html). When using the directory staging committer `fs.s3a.committer.name=directory` with replace conflict mode `fs.s3a.committer.staging.conflict-mode=replace` and writing to FSO buckets, the job fails with the following errors.
This is because the logic to add back missing parent directories and missing output prefix directories similar to Initiate MPU request ([S3InitiateMultipartUploadRequestWithFSO.java](https://github.com/apache/ozone/blob/83d75861b0266160b219acde72d769eb0f9d5ac4/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3InitiateMultipartUploadRequestWithFSO.java#L192-L207), …
> HDDS-10630. Add missing parent directories deleted between initiate and complete MPU

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinator.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestContainerCommandsEC.java
Given a small EC block:
*  <= 2MB for EC-3-2
*  <= 5MB for EC-6-3
*  <= 9MB for EC-10-4
So that it is less than a full stripe and does not use all the datanodes.
When reconstruction happens to replace a replica which is not used in the stripe, the unused containers are not issued with the put block to store the details of the empty block within the container. Note that the container replica will likely have other blocks, so it will still get reconstructed, but it will not be given a reference to this empty block.
All containers are checked for the presence of all blocks during reconstruction. If any of the containers do not have a reference to the block, it is considered an orphan block / abandoned stripe and will not be reconstructed.
Therefore if one replica has no entry for the block, …
> HDDS-10681. EC Reconstruction does not issue put block to data index if it is unused

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinator.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestContainerCommandsEC.java
Given an EC block that is larger than 1 full stripe, but the last stripe is partial so that it does not use all the index.
If one of the replicas is reconstructed that does not have any data in that final position, an empty chunk is written to the end of the block's chunk list.
While this does no cause any immediate problem, it can prevent further reconstructions that attempt to use this block, and they will fail with an error like:
```
2024-04-09 01:06:21,855 ERROR [ec-reconstruct-reader-TID-4]-org.apache.hadoop.hdds.scm.XceiverClientGrpc: Failed to execute command GetBlock on the pipeline Pipeline[ Id: 7f6f1fc9-ed26-4e19-86b6-47435b027f6a, Nodes: 7f6f1fc9-ed26-4e19-86b6-47435b027f6a(ccycloud-4.quasar-jyswng.root.comops.site/10.140.150.0), ReplicationConfig: STANDALONE/ONE, State:CLOSED, …
```
> HDDS-10682. EC Reconstruction creates empty chunks at the end of blocks with partial stripes

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
Removed non-used properties:
* hdds.rest.netty.high.watermark
* hdds.rest.netty.low.watermark
https://issues.apache.org/jira/browse/HDDS-10625
Existing tests
> HDDS-10625. Remove unused netty-related config options from SCM

- .github/workflows/ci.yml
- dev-support/ci/categorize_basic_checks.sh
- hadoop-ozone/dev-support/checks/native.sh
_unit_ check used to be part of _basic_.  HDDS-6618 extracted it and combined it with top-level _native_ check, under the name _unit_, these two became items in the matrix strategy.  HDDS-9242 merged _unit_ into _integration_ (not as a matrix item, rather by removing module-level filtering from `integration.sh`).  Now _unit_ check has only one item: _native_.
The goal of this change is to:
* rename _unit_ check to _native_
* remove matrix strategy
Logic related to `*-checks` list is cleaned up to remove code duplication.
https://issues.apache.org/jira/browse/HDDS-10598
CI:
https://github.com/adoroszlai/ozone/actions/runs/8661440172/job/23751686695
> HDDS-10598. Rename unit check to native

- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigTag.java
Create a configuration option that is going to be later used by issues under [Regulatory compliance for used cryptography](https://issues.apache.org/jira/browse/HDDS-10234). This ticket just aims at creating this configuration option, the usage for it comes in a later issue.
[HDDS-10605](https://issues.apache.org/jira/browse/HDDS-10605)
green ci with unrelated failure: https://github.com/Galsza/ozone/actions/runs/8515349639/job/23323384841
> HDDS-10605. Add a configuration option for compliance mode

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMStateMachine.java
Currently the check leader ready logic is bounded inside "EventApi.
notifyTermIndexUpdated", since Ratis now provide an separate "notifyLeaderReady", it should be better to use the new API now.
https://issues.apache.org/jira/browse/HDDS-10690
> HDDS-10690. SCMStateMachine Override LeaderEventApi.notifyLeaderReady

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/client/ScmClient.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocol.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/protocolPB/StorageContainerLocationProtocolClientSideTranslatorPB.java
- hadoop-hdds/interface-admin/src/main/proto/ScmAdminProtocol.proto
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeDecommissionManager.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocolServerSideTranslatorPB.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestNodeDecommissionManager.java
- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ContainerOperationClient.java
- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/MaintenanceSubCommand.java
- hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestMaintenanceSubCommand.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/node/TestDecommissionAndMaintenance.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconAndAdminContainerCLI.java
Many users test out Ozone in small clusters of 15 Datanodes or less. If a 15 DN cluster has some EC 10-4 containers, for example, then it's not possible to put more than 2 datanodes into maintenance (`maintenance.remaining.redundancy` = 1 by default), because EC 10-4 requires at least (10+4-1) = 13 Datanodes. If someone tries to move 3 Datanodes to maintenance, the maintenance process is designed such that it will keep looping and checking every 30 seconds whether it's possible to take the two DNs offline. It will never fail, even though it's clearly not possible to take the Datanodes offline.
In this PR, the maintenance is failed early if sufficient datanodes are not available based on the maximum replication factor of containers present in the cluster, and the configs …
> HDDS-10463. Fail Datanode Maintenance early

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/BasicOmKeyInfo.java
- hadoop-ozone/dist/src/main/compose/common/s3a-test.sh
- hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/RequestAuditor.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/BucketEndpoint.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java
Fix test failures related to in S3A contract test.  The problem is that some parts of the code use "modification time" instead of content hash as ETag.
```
Tests run: 11, Failures: 0, Errors: 3, Skipped: 1, Time elapsed: 2.998 s <<< FAILURE! - in org.apache.hadoop.fs.contract.s3a.ITestS3AContractRename
testRenamePopulatesFileAncestors2(org.apache.hadoop.fs.contract.s3a.ITestS3AContractRename)  Time elapsed: 1.04 s  <<< ERROR!
org.apache.hadoop.fs.s3a.RemoteFileChangedException: copy `s3a://obs-bucket/test/testRenamePopulatesFileAncestors2/src/dir1/dir2/dir3/fileA': ETag change detected on client during copy. Expected 2024-03-29T18:34:05.086Z got f41ee8006d26bd7fc73828b0a0b350a8
testRenameWithNonEmptySubDir(org.apache.hadoop.fs.contract.s3a.ITestS3AContractRename)  Time elapsed: 0.281 s …
```
> HDDS-10615. ETag change detected in S3A contract test

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/util/PayloadUtils.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/util/TestPayloadUtils.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/util/OMEchoRPCWriteRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OmRPCLoadGenerator.java
"freon om-echo" command generates a wrong payload response size. 
The parameter `--payload-resp` (in KB) is converted to bytes before sent to OM, but OM interprets the number as in KB. This makes the actual generated response payload 1024x larger than expected.
Also, this PR optimizes the response payload generation to maintain the tool purpose: to evaluate RPC performance only.
https://issues.apache.org/jira/browse/HDDS-10671
CI.
> HDDS-10671. Wrong size of response data in om-echo.

- .github/dependabot.yml
1. Upgrade npm dependencies only for security fixes.
2. Disable major version upgrades for Maven dependencies.
https://issues.apache.org/jira/browse/HDDS-10686
N/A
> HDDS-10686. Bump npm packages only for security

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
Currently, there is no check for snapshot diff operations. Similar to [HDFS](https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-hdfs/HdfsSnapshots.html#Get_Snapshots_Difference_Report), we should check if a user has read permission on the bucket.
HDDS-10434
> HDDS-10434. Added permission check for snapshotDiff related operations

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/S3SecretValue.java
- hadoop-ozone/dist/src/main/smoketest/security/S3-secret.robot
`ozone s3 getsecret` prints some additional items since HDDS-9444.
```
awsAccessKey=...
awsSecret=...
isDeleted=false
transactionLogIndex=0
```
The last two lines are internal details, should be omitted.
https://issues.apache.org/jira/browse/HDDS-10692
Added assertion in robot test.
CI:
https://github.com/adoroszlai/ozone/actions/runs/8693821050
> HDDS-10692. ozone s3 getsecret prints some internal details

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/AbstractKeyDeletingService.java
Fix the condition that causes duplicate command sent to SCM. 
Please find the detail analysis in JIRA description. The issue caused SCM frequent crash in user's environment. 
https://issues.apache.org/jira/browse/HDDS-10680
Verified in user's cluster.
> HDDS-10680. Duplicate delete key blocks sent to SCM

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockInputStream.java
Due to [HDDS-10682](https://issues.apache.org/jira/browse/HDDS-10682) some EC blocks in a cluster could have an empty final chunk. These blocks will fail to read and could cause data to become unavailable, even though it is still present on disk.
If the last chunk is empty, this should not stop the block from being read.
https://issues.apache.org/jira/browse/HDDS-10704
Adding a unit test for this issue is not easy within a sensible time.
I tested this manually in a Docker cluster.
First, I created a block with the problem in a build without the fix for HDDS-10682
Then attempted to read the block in a docker-compose cluster and validated the log message was produced:
```
bash-4.2$ dd if=/dev/random of=4mb bs=1024 count=4096
4096+0 records in
4096+0 records out
4194304 bytes (4.2 MB) …
```
> HDDS-10704. Do not fail read of EC block if the last chunk is empty

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDeletingService.java
- hadoop-ozone/recon/pom.xml
Speed up TestSnapshotDeletingService
The time span is improved to 250.118 seconds from 321.147 seconds earlier.
https://github.com/raju-balpande/apache_ozone/actions/runs/8339044173/job/22820842037
We have managed the cluster creation part to be executed once.
https://issues.apache.org/jira/browse/HDDS-10309?
Tested each method independently and in sequence locally and Tested the sequence in Ci
I recreated this pull request to solve some of conflicts that the original file got replaced to a package and wasn't allowing to fix the conflicts. I recreated the branch and cherry-picked my changes. the earlier pull request was https://github.com/apache/ozone/pull/6403
> HDDS-10309. Speed up TestSnapshotDeletingService

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockInputStream.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinator.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestContainerCommandsEC.java
Backport recent EC reconstruction fixes to branch 1.4
https://issues.apache.org/jira/browse/HDDS-10681
https://issues.apache.org/jira/browse/HDDS-10682
https://issues.apache.org/jira/browse/HDDS-10704
Unit tests were added for the changes, so a green build on the branch checks them.
> HDDS-10681. Backport Recent EC fixes to branch ozone-1.4

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ECBlockOutputStream.java
- hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestBlockOutputStreamCorrectness.java
In this scenario, EC reconstruction is failing in the new Ozone version for EC data written in the old version because the `stripeChecksum` field in the `ChunkInfo` proto breaks compatibility between the two versions.
Please check the Jira for a description and analysis of the problem. In this pull request, I changed the code so that reconstruction doesn't fail if `stripeChecksum` is missing. Also added some logging.
https://issues.apache.org/jira/browse/HDDS-10652
Added a unit test.
> HDDS-10652. EC Reconstruction fails with "IOException: None of the block data have checksum" after upgrade

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/fs/CachingSpaceUsageSource.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/fs/TestCachingSpaceUsageSource.java
The root cause seems to be an error during the refresh operation of the `CachingSpaceUsageSource`. Specifically, the underlying `SpaceUsageSource` (likely an instance of DU, which uses the Unix du command to calculate disk usage) is failing due to a permission issue when trying to read the /data3/lost+found directory. This failure might cause the `getUsedSpace()` method to return an incorrect value (possibly zero), which, when decremented, results in a negative value. Here are the steps that are likely leading to the issue:
This PR introduces error handling and validation in the `CachingSpaceUsageSource` class to ensure data integrity. Specifically, it prevents negative values for used space by validating new values before updating the cache and handles exceptions, including …
> HDDS-10614. Recon fails to start with used space cannot be negative.

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestDeleteBlocksCommandHandler.java
DeleteBlockCommands can be sent out of order, so even DeleteBlockCommand's tx is smaller than container's deleteTransactionId, we cannot tell it's duplicate or not. But if the DeleteBlockCommand's tx is equal to container's current deleteTransactionId, then it's duplicate no doubt. Tx ID is unique ID. There will be no Tx with same ID but different pending deleting blocks. 
It's observed that large duplicate DeleteBlockCommands are received on DN and persist into DB in user's cluster. This task is going to skip the persist to avoid unnecessary DN resources used on these duplicate commands handling. 
https://issues.apache.org/jira/browse/HDDS-10705
new UT
> HDDS-10705. Avoid persist duplicate DeleteBlockCommands on DN

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java
It is found that the Ratis WriteLog retry is "0/0" which means the WriteLog will not retry at all, and the datanode will trigger a pipeline failure to close the pipeline. This might cause a lot of pipeline close events sent by the datanodes during high IO events. Our cluster encountered this issue which caused pipeline thrashing issues (pipeline kept getting closed and created continuously).
The issue was due to `nodeFailureTimeoutMs` initialized AFTER `newRaftProperties` and `setStateMachineDataConfigurations` which causes an issue. HDDS-9821 removed the overwritten configuration, but at the same time exposed the bug.
Need to fix the ordering so that it's the `syncTimeoutRetry` is calculated correctly (default 30 times).
https://issues.apache.org/jira/browse/HDDS-10717
Clean CI: …
> HDDS-10717. nodeFailureTimeoutMs should be initialized before syncTimeoutRetry

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/BasicOmKeyInfo.java
- hadoop-ozone/dist/src/main/smoketest/basic/ozone-shell-lib.robot
Avoid introducing empty `ETag` in response for keys created outside of S3 Gateway (e.g. via Ozone CLI).
https://issues.apache.org/jira/browse/HDDS-10719
Added assertion in existing Robot test.
CI:
https://github.com/adoroszlai/ozone/actions/runs/8758764190
> HDDS-10719. Empty ETag for key created outside of S3

- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java
skipTrash option is not applicable for `ozone sh` commands. We can remove from suggestion message while deleting volume recursively.
https://issues.apache.org/jira/browse/HDDS-10716
Manually verified in cluster
> HDDS-10716. Remove skipTrash option from IOException message in recursive volume delete.

- hadoop-hdds/hadoop-dependency-test/pom.xml
- hadoop-hdds/rocks-native/pom.xml
- hadoop-ozone/common/pom.xml
- hadoop-ozone/s3gateway/pom.xml
Fix test failure with Java 17:
```
[ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.323 s <<< FAILURE! - in org.apache.hadoop.ozone.freon.TestContentGenerator
[ERROR] org.apache.hadoop.ozone.freon.TestContentGenerator.writeWithHsync  Time elapsed: 0.294 s  <<< ERROR!
java.lang.NullPointerException: Cannot read the array length because "this.buf" is null
at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:97)
at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:130)
at org.apache.hadoop.ozone.freon.ContentGenerator.write(ContentGenerator.java:98)
at org.apache.hadoop.ozone.freon.TestContentGenerator.writeWithHsync(TestContentGenerator.java:113)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at …
```
> HDDS-10725. TestContentGenerator#writeWithHsync fails with Java 17

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
- hadoop-ozone/dist/src/main/smoketest/s3/MultipartUpload.robot
- hadoop-ozone/dist/src/main/smoketest/s3/objectputget.robot
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3InitiateMultipartUploadRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3InitiateMultipartUploadRequestWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/OMRequestTestUtils.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3InitiateMultipartUploadRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3InitiateMultipartUploadRequestWithFSO.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartUploadCompleteRequest.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/EndpointBase.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/ClientProtocolStub.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneBucketStub.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestMultipartUploadComplete.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestPermissionCheck.java
[HDDS-6440](https://issues.apache.org/jira/browse/HDDS-6440) added support for custom metadata for normal object creation.
We should also support custom metadata creation for multipart upload key.
The metadata should be set during the multipart upload initiation request, which will be committed during the multipart upload complete request.
See: https://docs.aws.amazon.com/cli/latest/reference/s3api/create-multipart-upload.html 
Should be tested using unit tests and acceptance tests.
https://issues.apache.org/jira/browse/HDDS-10653
Unit, integration, and acceptance tests.
Clean CI: https://github.com/ivandika3/ozone/actions/runs/8581916553
> HDDS-10653. Support custom metadata for MPU key

- hadoop-ozone/dev-support/checks/junit.sh
HDDS-10080 added a sanity check in `junit.sh` to stop iterations if no tests were run.  However, it is also triggered if tests are run, but do not complete "normally", e.g. Surefire fork times out or crashes.
Example (each split stopped right after the first crash): https://github.com/adoroszlai/ozone/actions/runs/8191098889/job/22400265006#step:6:11998
This patch slightly tweaks the pattern.
https://issues.apache.org/jira/browse/HDDS-10545
Valid test class, iterations continue:
```
$ ITERATIONS=3 OZONE_REPO_CACHED=true \
./hadoop-ozone/dev-support/checks/junit.sh \
-am -pl :hdds-config -Dtest='TestConfigFileAppender'
...
$ cat target/unit/summary.txt                                                                                                                   
Iteration 1 exit code: 0 …
```
> HDDS-10545. Repeated tests stop if fork does not return

- hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/audit/parser/TestAuditParser.java
Fix test failure with Java 11+:
```
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.31 s <<< FAILURE! - in org.apache.hadoop.ozone.audit.parser.TestAuditParser
[ERROR] org.apache.hadoop.ozone.audit.parser.TestAuditParser.testLoadCommand  Time elapsed: 0.01 s  <<< FAILURE!
java.lang.AssertionError: 
Expecting:
<"Error while calling command (org.apache.hadoop.ozone.audit.parser.handler.LoadCommandHandler@266374ef): java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5">
to contain:
<": 5"> 
at org.apache.hadoop.ozone.audit.parser.TestAuditParser.testLoadCommand(TestAuditParser.java:195)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at …
```
> HDDS-10726. TestAuditParser.testLoadCommand fails with Java 11+

- .github/workflows/repeat-acceptance.yml
The `repeat-acceptance-test` workflow does not use the `ref` input parameter in the build step. The build will always default to the tip of the branch the workflow is run from (based on the `Use workflow from`) dropdown, according to the [docs](https://github.com/actions/checkout?tab=readme-ov-file#usage).
I first noticed this on [this workflow run](https://github.com/errose28/ozone/actions/runs/8762099500) where I was testing changes on my reconciliation feature branch. We can see from the title that I input `HDDS-10372-reconcile-cli` as the branch to test changes from, and I selected to use the workflow from `master` as shown in the top of that page because the workflow file had not changed on my branch at that time.
- Expected: The workflow file from `master` should have built and …
> HDDS-10735. `repeat-acceptance-test` workflow always builds Ozone with the branch the workflow is run from.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/protocolPB/ContainerCommandResponseBuilders.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/storage/ContainerProtocolCalls.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/audit/DNAction.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java
- hadoop-hdds/interface-client/src/main/proto/DatanodeClientProtocol.proto
- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ContainerOperationClient.java
- hadoop-ozone/dist/src/main/smoketest/freon/echoRPCLoad.robot
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestContainerSmallFile.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestDNRPCLoadGenerator.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/DNRPCLoadGenerator.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/Freon.java
(cherry picked from commit 509c970054886c15cd7dd425104be9d0e4e59723)
HDDS-10442. [hsync] Add a Freon tool to measure client to DataNode round-trip latency (#6297)
* Cherrypick HDDS-10442 from feature branch HDDS-7593 to master.
https://issues.apache.org/jira/browse/HDDS-10442
Unit tests, Freon integration tests.
> HDDS-10442. [hsync] Add a Freon tool to measure client to DataNode round-trip latency (#6297)

- hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Datanode Chunk Read_Write Dashboard.json
Adding a dashboard that tracks number of operations and total data transferred for chunks across datanodes and across each volume.
https://issues.apache.org/jira/browse/HDDS-10712
Spun it up locally.
> HDDS-10712. Add a dashboard for chunks & volume IO.

- .github/workflows/ci.yml
Bump Java version to 17 in `integration` check.
https://issues.apache.org/jira/browse/HDDS-10713
CI:
https://github.com/adoroszlai/ozone/actions/runs/8788103037
> HDDS-10713. Run JUnit tests with Java 17

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/SCMSafeModeManager.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMMXBean.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
- hadoop-hdds/server-scm/src/main/resources/webapps/scm/scm-overview.html
Safe mode rules are not calculated/updated after a safemode force exit, If a user looks at the SCM web UI after a force exit , it would give an impression that SCM is in safemode by looking at the rules not being satisfied.
Displaying if safe mode was forcefully exited will be helpful in  this case.
https://issues.apache.org/jira/browse/HDDS-10628
Manually
> HDDS-10628. Display if safemode exit was via force exit command.

- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java
For crypto compliance mode the cryptography related configuration options need to be whitelisted in some way. After some deliberate consideration, the CRYPTO_COMPLIANCE tag is used and in [HDDS-10604](https://issues.apache.org/jira/browse/HDDS-10604) the whitelisting will be added for these options.
In this PR the CRYPTO_COMPLIANCE tag is added to all already existing configuration options.
`hdds.key.algo` and `hdds.security.provider` are also exposed to the ozone-default.xml, these properties were missing before.
[HDDS-10691](https://issues.apache.org/jira/browse/HDDS-10691)
green CI:
https://github.com/Galsza/ozone/actions/runs/8702230425
> HDDS-10691. CRYPTO_COMPLIANCE tag for cryptography parameters

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmBucketInfo.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmMultipartKeyInfo.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmMultipartKeyInfo.java
- hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/helpers/OmPrefixInfo.java
@xichen01  pointed out in https://github.com/apache/ozone/discussions/6518#discussioncomment-9192008 that OmBucketInfo did not implement CopyObject.
Also found that OmMultipartKeyInfo/OmPrefixInfo should implement CopyObject.
HDDS-10752
> HDDS-10752. OmBucketInfo/OmMultipartKeyInfo/OmPrefixInfo should implement CopyObject.

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmBucketInfo.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmVolumeArgs.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/WithMetadata.java
- hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/helpers/OmPrefixInfo.java
@xichen01  pointed out in https://github.com/apache/ozone/discussions/6518#discussioncomment-9192008 that OMKeyInfo#copyObject is just a shallow copy. It is not thread safe since OmKeyInfo#acls is just an ArrayList.
Similarly, WithMetadata#metadata is also not thread safe.
In this PR, we replace `ArrayList` and `HashMap` and with `CopyOnWriteArrayList` and `ConcurrentHashMap`, respectively.
HDDS-10753
> HDDS-10753. OmKeyInfo#acls and WithMetadata#metadata are not thread safe.

- hadoop-hdds/common/src/main/java/com/google/protobuf/Proto2Utils.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCommandInfo.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/ReconstructECContainersCommand.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/states/endpoint/TestHeartbeatEndpointTask.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestReplicationSupervisor.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/protocol/commands/TestReconstructionECContainersCommands.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/io/BigIntegerCodec.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/io/BooleanCodec.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/io/EnumCodec.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/io/IntegerCodec.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/io/LongCodec.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/io/ManagedSecretKeyCodec.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/io/StringCodec.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/io/X509CertificateCodec.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECUnderReplicationHandler.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/io/TestX509CertificateCodec.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/util/PayloadUtils.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/util/OMEchoRPCWriteRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/DNRPCLoadGenerator.java
As the name implied, `ByteString#copyFrom(byte[])` creates a ByteString by copying the given byte array. In some cases (e.g. the byte array is already copied), the copying can be avoided by using `Proto2Utils.unsafeByteString(byte[])`.
HDDS-10756
> HDDS-10756. Avoid proto2 ByteString#copyFrom(byte[]).

- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerRatisServer.java
OM crash as the following logs:
```java
2024-04-26 13:29:26,517 [JvmPauseMonitor0] ERROR org.apache.ratis.server.RaftServer: om2: JVM pause detected 145.979s longer than the close-threshold 60s, shutting down ... 
```
This pr makes the close-threshold value configurable from the OM side.
https://issues.apache.org/jira/browse/HDDS-10761
manual tests: debug ratis and trace the value.
> HDDS-10761. Add raft close threshold config to OM RaftProperties

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/OzoneClientConfig.java
I added the CRYPTO_COMPLIANCE tag to the `ozone.client.checksum.type` and `ozone.client.bytes.per.checksum` config options. 
https://issues.apache.org/jira/browse/HDDS-10732
https://github.com/dombizita/ozone/actions/runs/8874650538
> HDDS-10732. Add CRYPTO_COMPLIANCE tag to client checksum type and bytes per checksum configs

- .github/workflows/ci.yml
HDDS-9242 changed `integration` check to run JUnit tests from all modules.  Thus it no longer needs Ozone to be present in local Maven repo.
https://issues.apache.org/jira/browse/HDDS-10769
CI:
https://github.com/adoroszlai/ozone/actions/runs/8866379733
> HDDS-10769. Integration check no longer needs Ozone repo

- hadoop-hdds/docs/content/design/overwrite-key-only-if-unchanged.md
Design doc - see content in the PR.
For any key, but especially a large key, it can take significant time to read and write it. There are scenarios where it would be desirable to replace a key in Ozone, but only if the key has not changed since it was read. This design outlines a minimal change to allow this feature in the Ozone API.
https://issues.apache.org/jira/browse/HDDS-10657
> HDDS-10657. Design Doc for overwriting a key if it has not changed

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeStoreSchemaThreeImpl.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/RocksDBStoreMetrics.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java
- hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdb/util/RdbUtil.java
- hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/rocksdiff/TestRocksDBCheckpointDiffer.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOmSnapshot.java
LiveFileMetaData class in RocksDB has three methods that are returning a byte[] which we convert to String after any call.
These methods are:
- columnFamilyName()
- smallestKey()
- largestKey()
We use 3 different conversion to String for the returned byte arrays.
For largestKey and smallestKey we use FixedLengthStringCodec.bytes2String and new String(byte[], UTF_8)
For columnFamilyName we use org.apache.hadoop.hdds.StringUtils.bytes2String, new String(byte[], UTF_8), and org.bouncycastle.util.Strings.fromByteArray.
From these methods, FixedLengthStringCodec throws an exception if the conversion can not be done, and it uses ISO_8859_1 as the charset for the conversion, while the rest uses UTF_8 charset for the conversion, and replaces the characters that UTF-8 can not represent.
Based on …
> HDDS-10744. Standardize byte array conversion to String for LiveFileMetaData in RocksDB.

- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/FindMissingPadding.java
Create a CLI tool to find EC keys whose blocks are missing from some of the replicas due to having been reconstructed before HDDS-10681 was fixed.
The tool prints keys affected in a tab-separated list, showing key name, size, replication.  This information can be used to recreate the keys (if enough replicas are still available) using existing tools (`ozone sh key get/put`).
https://issues.apache.org/jira/browse/HDDS-10751
Configured Ozone's `restart` Docker Compose environment with some additional datanodes.  Set 8MB block size, so EC 3-2 would use 1 block on each datanode hosting the EC container for each 24MB of total key size.
Created a set of EC keys spread out in 4 containers:
- container 1 had a key of 1MB, 25MB, 49MB, 73MB each (thus 2 padding blocks)
- container 2 had a key of …
> HDDS-10751. Detect missing EC padding blocks

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerRatisServer.java
Simplify OM RaftProperties formatting for more readability.
https://issues.apache.org/jira/browse/HDDS-10773
no need new test.
> HDDS-10773. Simplify OM RaftProperties formatting

- hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java
[SstFileReaderIterator](https://github.com/apache/ozone/blob/78a7e7ae1a18469befa764d3176c0a7e8c07454a/hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java#L1582) is not getting closed in RocksDBCheckpointDiffer that could potentially leave the file descriptor open even after RocksDB compaction deletes the file. This change is to close the SstFileReaderIterator after the use.
HDDS-10783
> HDDS-10783. Close SstFileReaderIterator in RocksDBCheckpointDiffer

- hadoop-ozone/dist/src/main/compose/ozonesecure/docker-config
- hadoop-ozone/dist/src/main/compose/ozonesecure/test.sh
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java
Fix exception:
```
ClassCastException: class org.apache.hadoop.crypto.CryptoOutputStream cannot be cast to class org.apache.hadoop.ozone.client.io.KeyMetadataAware ...
at org.apache.hadoop.ozone.s3.endpoint.ObjectEndpoint.createMultipartKey(ObjectEndpoint.java:1003)
at org.apache.hadoop.ozone.s3.endpoint.ObjectEndpoint.put(ObjectEndpoint.java:239)
```
Steps to reproduce:
0. Start cluster with Ratis streaming disabled (default setting)
1. Create encrypted bucket in S3 volume
2. Upload key via multipart upload to encrypted bucket
https://issues.apache.org/jira/browse/HDDS-10784
Added acceptance test coverage for S3 with Ratis streaming disabled in encrypted bucket in `ozonesecure` environment.  `ozonesecure-ha` covers the same with Ratis streaming enabled.
CI: …
> HDDS-10784. Multipart upload to encrypted bucket fails with ClassCastException

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAWithStoppedNodes.java
Resolved Intermittent failure in TestOzoneManagerHAWithStoppedNodes due to OMLeaderNotReadyException
There was mandatory pause of 8seconds, which I replaced by getCluster().waitForLeaderOM(). This will also reduce the time required to completed the test execution.
https://issues.apache.org/jira/browse/HDDS-9761
Tested the behavior in CI build https://github.com/raju-balpande/apache_ozone/actions/runs/8921923082, or https://github.com/raju-balpande/apache_ozone/actions/runs/8924750049/job/24511920360
> HDDS-9761. Intermittent failure in TestOzoneManagerHAWithStoppedNodes due to OMLeaderNotReadyException

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/node/TestDecommissionAndMaintenance.java
[HDDS-10462](https://issues.apache.org/jira/browse/HDDS-10462) added fail early conditions for datanode decommission. And [HDDS-10463](https://issues.apache.org/jira/browse/HDDS-10463) added fail early conditions for datanode maintenance. This PR adds few integration tests in TestDecommissionAndMaintenance for the same.
https://issues.apache.org/jira/browse/HDDS-10464
Green CI on my fork: https://github.com/Tejaskriya/ozone/actions/runs/8733823330
```
[INFO] Running org.apache.hadoop.hdds.scm.node.TestDecommissionAndMaintenance
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 299.794 s - in org.apache.hadoop.hdds.scm.node.TestDecommissionAndMaintenance
```
> HDDS-10464. Add integration tests for fail-early

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeUsage.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestCapacityVolumeChoosingPolicy.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestReservedVolumeSpace.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestRoundRobinVolumeChoosingPolicy.java
Currently there are two ways to reserve space in datanode volumes:
1. `hdds.datanode.dir.du.reserved.percent` allows specifying a percentage of the volume's space to be unused. It applies to all volumes
2. `hdds.datanode.dir.du.reserved` allows specifying a map of volume name to bytes reserved. Since it depends on a volume path, it cannot have a default value.
By default Ozone should not allow datanode volumes to get 100% full. This can cause the drive to "lock up" because some operations like block delete that would free up space still need extra disk space before they can complete because they must append to the RocksDB WAL. Once encountered, such issues are difficult to resolve. Add a default value for `hdds.datanode.dir.du.reserved.percent` to prevent this from happening.
A default …
> HDDS-10720. Datanode volume DU reserved percent should have a non-zero default value.

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneOutputStreamStub.java
`OzoneOutputStreamStub.getKeyOutputStream()` returns a dummy `KeyOutputStream`, which has no relation to the underlying stream (the one passed to parent `OzoneOutputStream` class).
This PR eliminates the need for the dummy `KeyOutputStream`.  The only caller (`ObjectEndpoint`) can access it via `OzoneOutputStream`, so the stub's custom logic is not bypassed.
https://issues.apache.org/jira/browse/HDDS-10796
CI:
https://github.com/adoroszlai/ozone/actions/runs/8928970232
> HDDS-10796. Avoid dummy KeyOutputStream in OzoneOutputStreamStub

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestHddsDispatcher.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/token/CompositeTokenVerifier.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/token/NoopTokenVerifier.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/token/ShortLivedTokenVerifier.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/token/TokenVerifier.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/token/TestOzoneBlockTokenSecretManager.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/token/TokenVerifierTests.java
HDDS-10797. Remove unused UserGroupInformation object in DataNode token verifier.
freon dn-echo tool examines the baseline client to DataNode communication performance. The flamegraph shows token verifier at DataNode instantiates current user UGI, which is meaningless for DataNode. Furthermore, it is unused at all.
https://issues.apache.org/jira/browse/HDDS-10797
Patched the jars in a real cluster. Flamegraph after the change confimred UGI is no longer seen.
> HDDS-10797. Remove unused UserGroupInformation object in DataNode token verifier.

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientRatis.java
See [HDDS-10780](https://issues.apache.org/jira/browse/HDDS-10780).
We have NPE for the following scenarios. Let's say a pipeline `p1` with dn1, dn2 and dn3.
Some chunks are written to `p1` -> flush 1 -> watchCommit 1 timed out because dn3 hasn't caught up to the latest index. -> dn3 is [removed](https://github.com/apache/ozone/blob/master/hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientRatis.java#L303-L303) from `commitInfoMap`.
Some other chunks are written to ratis -> flush 2 -> watchCommit 2  -> latest index has been committed to all dn1, dn2 and dn3 -> NPE because dn3 has been removed from `commitInfoMap`. 
https://issues.apache.org/jira/browse/HDDS-10780
CI.
> HDDS-10780. NullPointerException in watchForCommit

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerStateMachine.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/ratis/TestOzoneManagerStateMachine.java
when ratis index is updated from doubleBuffer to OM StateMachine, its not updating the lastNotifiedTransaction as due to error in check `lastApplied.getIndex() >= lastSkippedIndex` fails, This is fixed using `newTermIndex.getIndex() >= lastSkippedIndex`
https://issues.apache.org/jira/browse/HDDS-10798
- Unit Test added for the scenario
> HDDS-10798. OMLeaderNotReadyException exception on switch leader

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestWatchForCommit.java
Ensure `XceiverClientSpi` is released in `TestWatchForCommit` even if any of the test assertions fail.
(Most of the patch is just indentation change due to wrapping in `try-finally` block.  Check it by using `git diff --ignore-space-change` locally.)
https://issues.apache.org/jira/browse/HDDS-10097
10x10 runs [passed](https://github.com/adoroszlai/ozone/commit/3a364d8a8b58d03ad74900eee5550f24cc0780f4) with a "small" [change](https://github.com/adoroszlai/ozone/commit/3a364d8a8b58d03ad74900eee5550f24cc0780f4) to ignore actual test failures.  So iterations would have been marked as failure only if log postprocessing indicated some problem, e.g. the channel being leaked.  This tweak was necessary to avoid failures reported for known issue HDDS-10788.
Regular CI: …
> HDDS-10097. Intermittent ManagedChannel not shutdown properly in TestWatchForCommit

- hadoop-hdds/hadoop-dependency-server/pom.xml
- hadoop-ozone/dist/src/main/compose/ozonesecure/docker-config
- hadoop-ozone/dist/src/main/license/jar-report.txt
- pom.xml
Fix:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/kerby/kerberos/kerb/keytab/Keytab
at org.apache.hadoop.security.authentication.util.KerberosUtil.getPrincipalNames(KerberosUtil.java:238)
at org.apache.hadoop.security.authentication.util.KerberosUtil.getPrincipalNames(KerberosUtil.java:257)
at org.apache.hadoop.security.authentication.server.KerberosAuthenticationHandler.init(KerberosAuthenticationHandler.java:163)
at org.apache.hadoop.security.authentication.server.AuthenticationFilter.initializeAuthHandler(AuthenticationFilter.java:194)
at org.apache.hadoop.security.authentication.server.AuthenticationFilter.init(AuthenticationFilter.java:180)
...
at org.apache.hadoop.hdds.server.http.HttpServer2.start(HttpServer2.java:1184)
at …
```
> HDDS-10803. HttpServer fails to start with wildcard principal

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/OzoneDelegationTokenSecretManager.java
When one encounters a 'Tampered/Invalid token' exception, it may occur due to 
OzoneDelegationTokenSecretManager#verifySignature failing in any one of the following scenarios:
1. Failure when obtaining the signer's certificate (CertificateClient#getCertificate call).
2. In case the signer's certificate returned from this code is simply null.
3. In case of an expired certificate or a certificate not yet valid.
4. Failure during CertificateClient#verifySignature (with the signer's certificate).
Related code snippet [link](https://github.com/apache/ozone/blob/master/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/OzoneDelegationTokenSecretManager.java#L437-L466).
While we are already logging an error for the latter two cases, this patch introduces additional logging …
> HDDS-10802. Improve logging for signature verification

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/SCMBlockDeletingService.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java
Backport the following fixes from master to ozone-1.4 for 1.4.1:
HDDS-9962. Intermittent timeout in TestBlockDeletion.testBlockDeletion (#5886) - (to fix the problem described in https://issues.apache.org/jira/browse/HDDS-10799)
https://github.com/vtutrinov/ozone/actions/runs/8967491544
> [DO NOT MERGE] Backport some fixes from master to ozone-1.4

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMRatisServerImpl.java
Failure in adding scm during setup for SCM-HA is logged with a big stack in scm logs trace even though the addSCM call is successful eventually due to the retry logic.
Log level is reduced to warn. And the stackTrace is printed as a debug log.
https://issues.apache.org/jira/browse/HDDS-10814
As it is log change, no intensive testing is required.
> HDDS-10814. Log addSCM failure as warn, not error

- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/CompleteMultipartUploadRequestUnmarshaller.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/MultiDeleteRequestUnmarshaller.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/PutBucketAclRequestUnmarshaller.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestCompleteMultipartUploadRequestUnmarshaller.java
An exception occurs occasionally when the business uses s3 gateway to perform Complete Multipart Upload or Delete Objects.
It was analyzed as a result of concurrent requests; See details: https://issues.apache.org/jira/browse/HDDS-10777
https://issues.apache.org/jira/browse/HDDS-10777
UT
passed ci: https://github.com/guohao-rosicky/ozone/actions/runs/8890601157
> HDDS-10777. S3 gateway error when parsing xml in concurrent execution

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/storage/ContainerProtocolCalls.java
- hadoop-hdds/interface-client/src/main/proto/DatanodeClientProtocol.proto
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestContainerSmallFile.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestDNRPCLoadGenerator.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/DNRPCLoadGenerator.java
HDDS-10820. Freon tool DN-Echo to support GRPC and Ratis read/write mode
[HDDS-10442](https://issues.apache.org/jira/browse/HDDS-10442) added a freon tool dn-echo to microbenchmark the performance of client to DN communication.
This PR aims to enhance the tool by testing client/DataNode in different transport/modes:
(1) Ratis write mode (CLI parameters: --ratis)
(2) Ratis read mode (CLI parameters: --ratis --read-only)
(3) Grpc mode (default)
https://issues.apache.org/jira/browse/HDDS-10820
Freon mini cluster test, also manually tested on a real cluster.
> HDDS-10820. Freon tool DN-Echo to support GRPC and Ratis read/write mode

- hadoop-hdds/docs/content/tools/Admin.md
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/ListOpenFilesSubCommand.java
ListOpenFile currently displays all the keys present in openFile/Key table. In some cases when hsync keys are deleted but those keys may still present in openFileTable for some duration before openKeyCleanupService deletes them permanently. To show those deleted keys in this PR we are adding one extra column in CLI to display deleted information.
https://issues.apache.org/jira/browse/HDDS-10774
Integration test
> HDDS-10774. Show deleted hsync keys in ListOpenFile CLI.

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/snapshot/SnapshotDiffReportOzone.java
This [change](https://github.com/apache/ozone/pull/5697/files#diff-ba1235c3cb249eb15a22d8be137eca2b98f47edc1a1f4842da2e701d5204cc9cR104-R113) potentially breaks the backward compatibility of the snapshot diff CLI command if the output of the CLI is used directly. Because SnapDiff doesn't support JSON output format as of now, we are reverting this change.
In the future, we will add JSON output support for SnapDiff (Jira: HDDS-10833) so that this type of change can be done without any backward compatibility issues. More details about JSON backward compatibility support: https://lists.apache.org/thread/5gqnbstv1pznwmcvx7txspj1qrksy7gl
HDDS-10834
> HDDS-10834. Revert snapshot diff output change added in HDDS-9360

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/KeyValueStreamDataChannel.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/StreamDataChannelBase.java
Not every channel write generated io, but only added to the Buffers object, and in the close channel will be in the Buffers object has not been written to the disk data, the part also need to record metrics.
For the detailed see jira.
https://issues.apache.org/jira/browse/HDDS-10772
> HDDS-10772. [Ozone-Streaming] Stream write metric is wrong

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestAddRemoveOzoneManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMDBCheckpointServlet.java
After applying RATIS-2045, we saw lots of integration test failures as described in the HDDS-10696.
It is because of how MiniOzoneHACluster is set up. It doesn't set value for config `ozone.om.db.dirs` which OMDBCheckpointServlet is trying to access [here](https://github.com/apache/ozone/blob/ff78dc83a7640bf1dbed409bc6e79b3a0f231483/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMDBCheckpointServlet.java#L320).
So when `ozone.om.db.dirs` is not set, [ServerUtils#getDBPath](https://github.com/apache/ozone/blob/ff78dc83a7640bf1dbed409bc6e79b3a0f231483/hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/server/ServerUtils.java#L292) returns `ozone.metadata.dirs`. Because of that **snapshotDir path**: is getting evaluated …
> HDDS-10696. Fix test failure caused by empty snapshot installation

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeStateManager.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/states/NodeStateMap.java
There is a class [NodeStateMap](https://github.com/apache/ozone/blob/master/hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/states/NodeStateMap.java#L47) with 3 fields:
1. `ConcurrentHashMap<UUID, DatanodeInfo> nodeMap`
2. `ConcurrentHashMap<UUID, Set<ContainerID>> nodeToContainer`
3. `private final ReadWriteLock lock`
Both `read` and `write` operations in `NodeStateMap` are protected by `lock`.
1. Replace `ConcurrentHashMap` with pure `HashMap` to avoid extra lock operations.
2. Create `private NodeStateMap::getNodeInfoUnsafe` method without `lock.readLock.lock()` to use it when `lock.writeLock.lock()` has already acquired:
-  `NodeStateMap::updateNodeHealthState`
- `NodeStateMap::updateNodeOperationalState`
https://issues.apache.org/jira/browse/HDDS-10830
Use …
> HDDS-10830. Replace ConcurrentHashMap with HashMap protected by ReadWriteLock in NodeStateMap

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/client/ClientTrustManager.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OmTransportFactory.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainerWithTLS.java
Changed the log level of the extra log lines from INFO to DEBUG. 
https://issues.apache.org/jira/browse/HDDS-10829
This patch was tested by running the ozone shell commands on docker. 
(disabled the function `ozone_suppress_shell_log` for testing purpose)
Before suppressing the logs:
After suppressing the logs:
> HDDS-10829. Suppress extra INFO log lines from ozone shell commands output

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/AbstractOzoneFileSystemTest.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/AbstractOzoneFileSystemTestWithFSO.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneClientUtils.java
In BasicOzoneClientAdapterImpl#isFileClosed we use OFSPath to check if the path was a key, but it Utility class for OFS not O3FS. That is to say, the pathStr doen't include volume and bucket but the OFSPath still setting the first two levels of directories or key as volume and bucket. If the path was less than two level it comes out an error.
https://github.com/apache/ozone/blob/HDDS-7593/hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java#L774
https://issues.apache.org/jira/browse/HDDS-10781
There are some existing lease recovery tests.
> HDDS-10781. Do not use OFSPath in O3FS BasicOzoneClientAdapterImpl

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStream.java
Fix test failure:
```
Error:  org.apache.hadoop.ozone.client.rpc.TestBlockOutputStream.testWriteExactlyFlushSize(boolean)[2]  Time elapsed: 0.06 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <2> but was: <1>
at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:166)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:161)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:632)
at org.apache.hadoop.ozone.client.rpc.TestBlockOutputStream.testWriteExactlyFlushSize(TestBlockOu …
```
> HDDS-10557. TestBlockOutputStream#testWriteExactlyFlushSize is flaky

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/server/JsonUtils.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/JsonTestUtils.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/container/common/helpers/DeletedBlocksTransactionInfoWrapper.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManager.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/heatmap/TestHeatMapInfo.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/scm/ResetDeletedBlockRetryCountSubcommand.java
This pull request introduces a migration from Gson to Jackson for the remaining classes of the `hadoop-ozone` module, specifically focusing on replacing Gson's JsonParser with Jackson's ObjectMapper. It involves using ObjectMapper's `readValue()` method to deserialise JSON strings into Java objects. Additionally, the code utilises Jackson's JsonNode to navigate and extract data from JSON structures.
https://issues.apache.org/jira/browse/HDDS-10801
Ran the UT's and the forked CI
> HDDS-10801. Replace GSON with Jackson in hadoop-ozone classes.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/protocol/DatanodeDetails.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NetConstants.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NodeImpl.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/util/StringWithByteString.java
Reduce `com/google/protobuf/ByteString.copyFromUtf8` when encode a protobuf Object.
- For a String type protobuf field, if you use the `setXXX` method (such as `builder.setHostName`), the protobuf will call `ByteString.copyFromUtf8` convert UTF8 String to `ByteString`. 
- For some UTF8 String with fixed content, we can cache its `ByteString` value, and use `setXXXBytes` to avoid calling `ByteString.copyFromUtf8`
Before
https://issues.apache.org/jira/secure/attachment/13068731/om-create-key-alloc-profiler-setxxxString.html
After
The `com/google/protobuf/ByteString.copyFromUtf8` in the `DatanodeDetail` disappear.
https://issues.apache.org/jira/secure/attachment/13068732/om-create-key-alloc-profiler-setxxbytes.html
https://issues.apache.org/jira/browse/HDDS-10811
Existing Test.
> HDDS-10811. Reduce UTF8 string encoding by caching encoding result

- hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMDbCheckpointServlet.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMDBCheckpointServlet.java
As part of the change https://github.com/apache/ozone/pull/4680#issuecomment-1553512855, it was asked to add sequence number to compaction logs (HDDS-8652) and later pause in the RocksDB compaction when tarball creation is in progress (HDDS-9004 and HDDS-9064). These changes were valid when a text file was used to store compaction log entries.
After HDDS-9311, compaction logs were migrated to the RocksDB column family. Now we can simply rely on RocksDB's synchronization. Either the compaction entry will be present in the compactionLog columnFamily or not in the snapshot of the ActiveFS depending on the order of compaction entry append and checkpoint creation.
This change is to remove the wait and notify logic between RocksDB's compaction and tarball creation.
HDDS-9039
Updated existing …
> HDDS-9039. Removed the pause and wait in RocksDB compaction when tarball creation is in progress

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/ListOpenFilesSubCommand.java
When a hsync key is overwritten, it will have the overwrittenHsyncKey metadata. This task will support to show or hide this metadata in ListOpenFile CLI.
https://issues.apache.org/jira/browse/HDDS-10835
new Unit test
> HDDS-10835. Show overwritten hsync keys in ListOpenFile CLI

- .github/workflows/populate-cache.yml
- dev-support/ci/populate-cache.sh
- hadoop-ozone/recon/pom.xml
- pom.xml
Download from `nodejs.org` seems to be unreliable.
This PR fixes intermittent failures in:
- `compile (8, macos-12)`, which previously had to download Node.js for each run, since the binary tarball is platform-specific, and we only cached the one for Linux
- various [checks](https://github.com/apache/ozone/actions/runs/9013830936) in the rare case that `populate-cache` runs into [download problem](https://github.com/apache/ozone/actions/runs/8968724893/job/24628735903#step:5:3429)
Changes:
1. Download both Linux and Mac versions of Node.js.  Use `curl`, with retry enabled.
2. Indicate partially built cache by creating a marker file, which is deleted if all downloads succeed.
3. Log cache contents even in case of cache hit, making it easier to check contents.
4. Allow triggering …
> HDDS-10273. Intermittent build failure while downloading nodejs

- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/BaseFreonGenerator.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OmMetadataGenerator.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OzoneClientKeyReadWriteListOps.java
BaseFreonGenerator allows an empty prefix instead of enforcing a random prefix when no prefix is specified.
https://issues.apache.org/jira/browse/HDDS-10845
manual tests.
without pr:
```java
$ ozone freon ockrw -r 1000 -t 10 --linear --contiguous --percentage-read 50 -m=true --size=0 --duration 10s -v vol1 -b freon2
2024-05-12 16:54:45,789 [pool-2-thread-9] ERROR freon.OzoneClientKeyReadWriteListOps: Key:o7h00eovbs/9 not found
2024-05-12 16:54:45,789 [pool-2-thread-2] ERROR freon.OzoneClientKeyReadWriteListOps: Key:o7h00eovbs/5 not found
2024-05-12 16:54:45,789 [pool-2-thread-1] ERROR freon.OzoneClientKeyReadWriteListOps: Key:o7h00eovbs/7 not found
2024-05-12 16:54:45,789 [pool-2-thread-5] ERROR freon.OzoneClientKeyReadWriteListOps: Key:o7h00eovbs/0 not found
2024-05-12 16:54:45,791 …
```
> HDDS-10845. BaseFreonGenerator allows an empty prefix

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneAclUtils.java
- Avoid NPE in `OzoneAclUtils.isOwner` (and simplify condition)
- Call `isOwner` lazily
https://issues.apache.org/jira/browse/HDDS-10371
CI:
https://github.com/adoroszlai/ozone/actions/runs/9076402412
> HDDS-10371. NPE in OzoneAclUtils.isOwner

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3ExpiredMultipartUploadsAbortRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3InitiateMultipartUploadRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3InitiateMultipartUploadRequestWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadAbortRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCommitPartRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java
Multipart UploadID is not written to S3 MPU requests. Since, the same multipart key can be created with multiple uploadIDs added the multipart UploadID info to the audits.
https://issues.apache.org/jira/browse/HDDS-9679
Manually tested multipart commands using `aws s3api`
```
2024-05-14 00:33:50,810 | INFO  | S3GAudit | user=unsecure | ip=172.19.0.3 | op=INIT_MULTIPART_UPLOAD {bucket=[testbucket], path=[large_test_file1], uploads=[]} | ret=SUCCESS |  
2024-05-14 00:34:36,473 | INFO  | S3GAudit | user=unsecure | ip=172.19.0.3 | op=CREATE_MULTIPART_KEY {bucket=[testbucket], path=[large_test_file1], uploadId=[57bc370c-e8c5-4a24-b7ec-2a1e4b3a240f-112436630703439875], partNumber=[1]} | ret=SUCCESS | perf={streamMode=true, metaLatencyMs=29, sizeByte=5242880, opLatencyMs=793} |  
2024-05-14 …
```
> HDDS-9679. Added Multipart Upload ID to S3MultiPart audit logs.

- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/OzoneRepair.java
- hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/repair/TestOzoneRepair.java
We added a repair tool for snapshot chain fix as part of PR: https://github.com/apache/ozone/pull/6386
This check was missed in the original PR. This task is to add a check or warning to make sure that the repair tool is run as system user (default to hdfs)
https://issues.apache.org/jira/browse/HDDS-10559
Unit test
> HDDS-10559. Add a warning or a check to run repair tool as System user

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeDecommissionManager.java
The current error message if decommission or maintenance fails early is not detailed enough:
`Error: AllHosts: Sufficient nodes are not available.`
The message must be self-explanatory and mention the reason of failure.
In this PR, the error messages have been changed to show the number of nodes trying to be decommissioned/put into maintenance and how many nodes are needed to maintain required replication.
https://issues.apache.org/jira/browse/HDDS-10859
Tested locally in docker cluster with 5 nodes, max replication factor of keys was RATIS-THREE:
```
bash-4.2$ ozone admin datanode decommission ozone-datanode-1 ozone-datanode-2 ozone-datanode-3
Started decommissioning datanode(s):
ozone-datanode-1
ozone-datanode-2
ozone-datanode-3
Error: AllHosts: Insufficient nodes. Tried to decommission …
```
> HDDS-10859. Improve error messages when decommission and maintenance fail-early

- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/OzoneAddress.java
- hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneAddressClientCreation.java
Ozone cli supports default ozone.om.service.id.
https://issues.apache.org/jira/browse/HDDS-10861
Unit tests.
> HDDS-10861. Ozone cli supports default ozone.om.service.id

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerTask.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/MockedSCM.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancerDatanodeNodeLimit.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancerTask.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestableCluster.java
In [PR for HDDS-9889](https://github.com/apache/ozone/pull/5758) we [discussed](https://github.com/apache/ozone/pull/5758#pullrequestreview-1963251436) with [Siddhant Sangwan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siddhant) that tests form `org.apache.hadoop.hdds.scm.container.balancer.TestContainerBalancerTask` could be refactored using `MockedSCM` class (introduced in [HDDS-9889](https://issues.apache.org/jira/browse/HDDS-9889))
1. Refactor some tests from `org.apache.hadoop.hdds.scm.container.balancer.TestContainerBalancerTask` 
2. Made some cleanups in `org.apache.hadoop.hdds.scm.container.balancer.ContainerBalancerTask` related to changes in refactored test
https://issues.apache.org/jira/browse/HDDS-10699
Use standalone tests
> HDDS-10699. Refactor ContainerBalancerTask and tests in TestContainerBalancerTask

- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneManagerVersion.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
Reject `rewriteKey` call at client if OM does not support it.
https://issues.apache.org/jira/browse/HDDS-10865
Created command `ozone sh key rewrite` to call the new API, toggling replication between RATIS/3 and EC/3,2.
Tested the command in `ozone` environment to verify it works:
```
$ cd hadoop-ozone/dist/target/ozone-1.5.0-SNAPSHOT/compose/ozone
$ OZONE_DATANODES=5 ./run.sh -d
$ docker-compose exec scm bash
bash-4.2$ ozone freon ockg -n1 -t1 # create volume and bucket
...
bash-4.2$ ozone sh key put /vol1/bucket1/rocksdbjni-7.7.3.jar share/ozone/lib/rocksdbjni-7.7.3.jar
bash-4.2$ ozone sh key list /vol1/bucket1 -p=rocksdbjni-7.7.3.jar 
[ {
"creationTime" : "2024-05-16T18:33:10.860Z",
"modificationTime" : "2024-05-16T18:33:12.277Z", …
```
> HDDS-10865. Check OM version before making rewrite key request

- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/TestOzoneDelegationTokenSecretManager.java
TestOzoneDelegationTokenSecretManager#testRenewTokenFailureRenewalTime fails intermittently
There is 'OzoneDelegationTokenSecretManager.run()' check every five seconds(or lesser if value is configured) for the expired tokens to be removed from the cache and in rare scenario if our thread doesn't get control before it, the expired token may get out of cache and hence will have to consider this as a valid scenario. I have modified the code to accommodate that condition. We are testing the exceptions to be thrown as part of this test method.
https://issues.apache.org/jira/browse/HDDS-2643
Tested the modified code with 500 runs having 25 splits and 20 iterations, it is working 100% fine https://github.com/raju-balpande/apache_ozone/actions/runs/9114752214
> HDDS-2643. TestOzoneDelegationTokenSecretManager#testRenewTokenFailureRenewalTime fails intermittently

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMInstallSnapshot.java
No intermittent failures in testInstallCheckPoint method of TestSCMInstallSnapshot, so removed `@Flaky` tag.
https://issues.apache.org/jira/browse/HDDS-6116
https://github.com/muskan1012/ozone/actions/runs/9093526472
> HDDS-6116. Remove flaky tag from TestSCMInstallSnapshot

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ratis/RatisHelper.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/ClosePipelineCommandHandler.java
From the https://issues.apache.org/jira/browse/HDDS-10750?focusedCommentId=17847435&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17847435 in [HDDS-10750](https://issues.apache.org/jira/browse/HDDS-10750), it's found `GroupMismatchException` are thrown during the `ClosePipelineCommandHandler`.
This is because `XceiverRatisServer#removeGroup` is called before `XceiverRatisServer#getRaftPeersInPipeline`, which causes `XceiverRatisServer#getRaftPeersInPipeline` to throw `GroupMismatchException` when it's trying to get the `RaftServerProxy#getDivision` since the group has been removed.
Therefore, we need to first call the `XceiverRatisServer#getRaftPeersInPipeline` before calling `XceiverRatisServer#removeGroup`. 
This patch also catch the …
> HDDS-10875. XceiverRatisServer#getRaftPeersInPipeline should be called before XceiverRatisServer#removeGroup

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
No intermittent failure in testOverWriteKeyWithAndWithOutVersioning method of TestOzoneRpcClient, removing `@Unhealthy` tag.
https://issues.apache.org/jira/browse/HDDS-8752
https://github.com/muskan1012/ozone/actions/runs/9094898957
> HDDS-8752. Enable TestOzoneRpcClientAbstract#testOverWriteKeyWithAndWithOutVersioning

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyArgs.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
- hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmKeyInfo.java
- hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/RequestAuditor.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCommitRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCreateRequest.java
Rename rewriteGeneration to expectedDataGeneration.
This future proofs the name, so we can potentially have expectedMetaGeneration in the future.
It also better describes what the field is for - when passed, it indicates the existing key is "expected" to have a Data Generation of the given value, whether it is for read, write (potential future use cases) or re-write (the current use case).
https://issues.apache.org/jira/browse/HDDS-10857
Just a name change so existing tests cover this.
> HDDS-10857. Rename rewriteGeneration to expectedDataGeneration in the protobuf and builders

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
The "owner" field is only set at the OM server side when a new key is created. In the case a key is overwritten, the owner is never retrieved from the keyargs and hence overwriting the owner when overwriting a key is not possible. This is the case, both prior to the atomic key overwrite feature and when the traditional key overwrite where a new version is allocated.
Therefore this change should simply remove the owner details from being passed in the rewrite key and the owner will continue to be inherited as it is now.
https://issues.apache.org/jira/browse/HDDS-10840
Existing test modified to check the owner before and after are the same.
> HDDS-10840. Do not pass owner in keyargs when rewriting a key

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientWithRatis.java
Current client workflow:
1. chooses regular or streaming write API (by calling `createKey` or `createStreamKey`, or similar methods)
2. opens key by making a call to OM
3. sets up hierarchy of output streams based on chosen write API
4. uses output streams to write
Streaming write is supported only for Ratis-based replication.  However, actual replication may be decided by OM based on its own config, if there aren't any more specific settings (coming from client, or configured at bucket level).
If client chooses streaming write and OM ends up creating an EC key, client may run into errors when trying to use output streams in step 4.
```
ClassCastException: class ECXceiverClientGrpc cannot be cast to class XceiverClientRatis 
at org.apache.hadoop.hdds.scm.storage.BlockDataStreamOutput.<init …
```
> HDDS-10832. Client should switch to streaming based on OpenKeySession replication

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
HDDS-10890. [hsync] Increase default value for hdds.container.ratis.log.appender.queue.num-elements.
Using Freon DN Echo tool, I found that increasing hdds.container.ratis.log.appender.queue.num-elements value drastically improve DN Echo throughput and latency.
Set it to 1024 to be consistent with OM and SCM.
ozone.om.ratis.log.appender.queue.num-elements
ozone.scm.ha.ratis.log.appender.queue.num-elements
https://issues.apache.org/jira/browse/HDDS-10890
Benchmarked on a real cluster
> HDDS-10890. [hsync] Increase default value for hdds.container.ratis.log.appender.queue.num-elements.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/lease/Lease.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/lease/LeaseCallbackExecutor.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/lease/LeaseManager.java
Do not expose mutable `Lease#callbacks`.  Also, normally [only zero or one callbacks are present](https://github.com/apache/ozone/pull/6351#discussion_r1605881549), so we can avoid using `List`.
Extracted from #6351.  Most of this change is from review suggestion by @szetszwo.
https://issues.apache.org/jira/browse/HDDS-10899
CI:
https://github.com/adoroszlai/ozone/actions/runs/9190676417
> HDDS-10899. Refactor Lease callbacks

- hadoop-ozone/dist/src/shell/ozone/ozone-functions.sh
Ozone's services startup scripts (e.g. ozone-functions.sh) require the log4j.properties config file to be in $OZONE_CONF_DIR. If the config file isn't there the **OZONE_CONF_DIR** env variable will be overridden as $OZONE_HOME/etc/hadoop (but all of the required and properly filled configuration files are in the previous location).
The PR suggests changing the requirement from **log4j.properties** to **ozone-site.xml** configuration file (at least SCM can't start without some mandatory conf properties inside, but all of the ozone's services can work without logger config (we won't see any log message, but the service will work anyway)
https://issues.apache.org/jira/browse/HDDS-10898
manually (mvn build and docker-compose up, + number of commands to deal with ozone cluster: create bucket, …
> HDDS-10898. Validate OZONE_CONF_DIR by presence of ozone-site.xml, not log4.properties

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/FaultInjector.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestLeaseRecovery.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/utils/FaultInjectorImpl.java
Fault injector is been updated by different thread call which leads to intermittent behaviour. In this PR we are protecting injector to get updated correctly and used by different threads.
https://issues.apache.org/jira/browse/HDDS-10860
Flaky test run 10X10
https://github.com/ashishkumar50/ozone/actions/runs/9124256970/workflow
> HDDS-10860. Fix Intermittent failure in TestLeaseRecovery.testFinalizeBlockFailure

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/AbstractOzoneFileSystemTest.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/AbstractRootedOzoneFileSystemTest.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java
FileSystem.getHomeDirectory() sometimes returns the current process' user name even if the process has securely impersonated another use using [UserGroupInformation.doAs()](https://hadoop.apache.org/docs/r1.2.1/Secure_Impersonation.html).
Implementation getHomeDirectory() in BasicRootedOzoneFileSystem and BasicOzoneFileSystem to return the securely impersonated user's home directory like in other FileSystem implementations like HDFS. 
https://issues.apache.org/jira/browse/HDDS-10905
Added an integration test and tested manually with Oozie workflows
> HDDS-10905. Override getHomeDirectory() in Ozone FileSystem implementations

- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconConstants.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconResponseUtils.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconUtils.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/NSSummaryEndpoint.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/OMDBInsightEndpoint.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/handlers/EntityHandler.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/handlers/FSOBucketHandler.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/KeyEntityInfo.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/ListKeysResponse.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/ParamInfo.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/OMMetadataManagerTestUtils.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestOmDBInsightEndPoint.java
This PR adds a new API in Recon for listing keys for OBS buckets, Legacy buckets and FSO buckets with filters and recursively in a flat structure for OBS, LEGACY and FSO buckets.
New API:
api/v1/keys/listKeys?startPrefix=/volume1/obs-bucket/&limit=105
Default values of API parameters if not provided:
1.  `replicationType` - empty string and filter will not be applied, so list out all keys irrespective of replication type.
2. `creationTime` - empty string and filter will not be applied, so list out keys irrespective of age, else list out keys which got created on or after provided creationTime
3. `keySize` - 0 bytes, which means all keys greater than zero bytes will be listed, effectively all.
4. `startPrefix` - /
5.  `prevKey` - ""
6. `limit` - 1000
Behavior of API:
For OBS bucket - list …
> HDDS-10634. Recon - listKeys API for listing keys with optional filters

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
In the previous code, the metric was updated synchronously when OM started. There should be changed to asynchronous to reduce time consumption.
https://issues.apache.org/jira/browse/HDDS-10862
exist UT.
> HDDS-10862. Reduce time spent on initializing metrics during OM start

- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/fsck/ContainerHealthTask.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/PipelineSyncTask.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/ContainerKeyMapperTask.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/ContainerSizeCountTask.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/FileSizeCountTask.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/NSSummaryTask.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/NSSummaryTaskWithFSO.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/NSSummaryTaskWithLegacy.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/NSSummaryTaskWithOBS.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/OmTableInsightTask.java
Set the log levels of various background tasks in Recon to debug. These tasks were previously filling the Recon logs unnecessarily, as they are only needed for debugging in rare cases. Now, they will not flood the Recon logs after every delta update sync as they did before.
https://issues.apache.org/jira/browse/HDDS-10867
Verified the logs manually.
> HDDS-10867. Clean Up Unnecessary Logs in Recon.

- hadoop-hdds/common/src/main/resources/ozone-default.xml
I changed the `ozone.security.crypto.compliance.mode` configuration default value to `unrestricted`. Its default value is already "unrestricted" in the OzoneConfigKeys class.
https://issues.apache.org/jira/browse/HDDS-10919
No testing needed.
> HDDS-10919. Change ozone.security.crypto.compliance.mode default value in ozone-default.xml

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
Add test cases for atomic rewrite.  Also slightly reword one of the error messages.
https://issues.apache.org/jira/browse/HDDS-10839
CI:
https://github.com/adoroszlai/ozone/actions/runs/9267804529
> HDDS-10839. Add end to end tests for atomic rewrite for OBS buckets.

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequestWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequestWithFSO.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCommitRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCommitRequestWithFSO.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCreateRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyCreateRequestWithFSO.java
Extend the atomic commit support to FSO buckets. This will follow the same pattern for OBS buckets, ensuring that a key exists at the given path, and still existings upon commit with the same expected generation.
https://issues.apache.org/jira/browse/HDDS-10921
The tests added for OBS buckets have been enabled for FSO buckets too. Previously they were disabled for FSO, as the feature was not implemented there. Some changes were needed to the tests to handle FSO buckets.
> HDDS-10921. Enable Atomic Rewrite in FSO buckets

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
HDDS-9918. [hsync] Remove block token from Ratis log once verified
After [HDDS-9697](https://issues.apache.org/jira/browse/HDDS-9697), block token is not useful after leader DN verifies it, and does not need to be recorded in Ratis log.
https://issues.apache.org/jira/browse/HDDS-9918
Stand up a docker compose cluster, verified that secure DataNode does not preserve encodedToken in Ratis log.
Unit tests passed
> HDDS-9918. [hsync] Remove block token from Ratis log once verified.

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStream.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStreamWithFailures.java
HDDS-10925. [hsync] Parameterize TestBlockOutputStream on ozone.client.stream.putblock.piggybacking
Improve BlockOutputStream test coverage for both ozone.client.stream.putblock.piggybacking = true and false. 
https://issues.apache.org/jira/browse/HDDS-10925
This is a test only PR.
> HDDS-10925. [hsync] Parameterize TestBlockOutputStream on ozone.client.stream.putblock.piggybacking

- .github/workflows/intermittent-test-check.yml
Fix the bug that `flaky-test-check`'s `count-failures` job does not list failed iterations:
```
Total failures: 5
Failed runs:
Error: Process completed with exit code 1.
```
This was caused by HDDS-10264, which removed `split` from the artifact name.
Also swap `run_id` and `run_number` in the artifact name, because `run_number` is a smaller number.  This makes it easier to extract a specific artifact zip after downloading several of them.
https://issues.apache.org/jira/browse/HDDS-10938
Triggered run for `TestOzoneManagerPrepare`, verified failures are [listed](https://github.com/adoroszlai/ozone/actions/runs/9285132172/job/25550868993#step:3:21):
```
Total failures: 7
Failed runs:
split 1 Iteration 10
split 3 Iteration 8
split 3 Iteration 10
split 9 Iteration 3
split 9 Iteration 5
split …
```
> HDDS-10938. flaky-test-check does not list failed iterations

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/ObjectStore.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OzoneManagerProtocol.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/snapshot/ListSnapshotResponse.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
- hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
- hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmMetadataManager.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/ClientProtocolStub.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/snapshot/ListSnapshotHandler.java
Currently, the last element from the current page's response is used as a continuation token for the list snapshot API. Because of that, every time a client has to make an extra call to know if there are more entries. This change is to return the continuation token from the server and the next page will be fetched after the provided token. 
HDDS-9983
Updated existing unit tests.
> HDDS-9983. Changed snapshot list API to return continuation token rather than using last element from the previous page's response.

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/snapshot/CancelSnapshotDiffResponse.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/snapshot/SnapshotDiffReportOzone.java
- hadoop-ozone/dist/src/main/smoketest/snapshot/snapshot-sh.robot
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/snapshot/SnapshotDiffHandler.java
As per HDDS-6637 and [discussion](https://lists.apache.org/thread/5gqnbstv1pznwmcvx7txspj1qrksy7gl), Ozone CLI is supposed to support JSON output format. And currently, SnapshotDiff CLI doesn't support that.
This change is to add the support of JSON format along with the existing format so that issues like HDDS-10834 can be avoided.
HDDS-9317
Locally on docker.
> HDDS-9317. Provide an option for displaying Ozone snapshot diff output as JSON

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManagerImpl.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMStateMachine.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestSCMHAManagerImpl.java
Tweak `TestSCMHAManagerImpl` to let it pass with Ratis 3.1.0.
https://issues.apache.org/jira/browse/HDDS-10924
Ozone CI with Ratis 3.1.0 RC0:
https://github.com/adoroszlai/ozone/actions/runs/9306740993
Regular CI:
https://github.com/adoroszlai/ozone/actions/runs/9306735813
> HDDS-10924. TestSCMHAManagerImpl#testAddSCM fails on ratis master

- hadoop-ozone/dist/src/main/compose/common/ec-test.sh
- hadoop-ozone/dist/src/main/smoketest/ec/rewrite.robot
- hadoop-ozone/dist/src/main/smoketest/lib/os.robot
- hadoop-ozone/dist/src/main/smoketest/ozone-lib/shell.robot
- hadoop-ozone/dist/src/main/smoketest/ozone-lib/shell_tests.robot
- hadoop-ozone/dist/src/main/smoketest/s3/MultipartUpload.robot
- hadoop-ozone/dist/src/main/smoketest/s3/commonawslib.robot
This PR adds coverage for rewrite of key created via multipart upload.  The test can be expanded later for other cases, but atomic key rewrite is already (mostly) covered by integration tests for regular keys.
Most of this change is making some custom robot test keywords available for tests outside S3 tests.
https://issues.apache.org/jira/browse/HDDS-10947
CI:
https://github.com/adoroszlai/ozone/actions/runs/9317350415/job/25648077188#step:5:366
Verified that the key was originally created via multipart upload:
```
2024-05-31 16:26:22,635 | INFO  | OMAudit | user=dlfknslnfslf | ip=192.168.96.9 | op=INITIATE_MULTIPART_UPLOAD {volume=s3v, bucket=bucket-bcqjqldpje, key=multipart.key, dataSize=0} | ret=SUCCESS |  
2024-05-31 16:26:23,441 | INFO  | OMAudit | user=dlfknslnfslf | ip=192.168.96.9 …
```
> HDDS-10947. Add robot test for rewrite of multipart key

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconScmNonHASnapshot.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconContext.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServer.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStorageContainerManagerFacade.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/StorageContainerServiceProviderImpl.java
This PR handles Recon startup failure due to unexpected runtime error and shuts down silently without logging the actual cause of error.
Ozone Recon - Handle startup failure and log reasons as error due to SCM non-HA scenario
While ReconServer.start() method is called, if any runtime errors being thrown, those are not being logged and Recon startup fails silently without logging any reason of failure. E.g. In case of non-HA SCM case, few configurations made Recon fails to start. This scenario or any runtime exception  needs to be handled for proper logging.
In non-HA SCM case, while trying to fetch SCM DB snapshot, SCM peer roles are not being returned correctly, so the logic needs to handle.
https://issues.apache.org/jira/browse/HDDS-10937
Tested manually and added additional integration …
> HDDS-10937. Ozone Recon - Handle startup failure and log reasons as error due to SCM non-HA scenario

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ratis/conf/RatisClientConfig.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/conf/DatanodeRatisServerConfig.java
Reduce the default duration of Ratis server watch timeout hdds.ratis.raft.server.watch.timeout to reduce the amount of time client needs to wait during two-way commit (i.e. one DN is not reachable).
The watch timeout configuration affects the upper bound of how long the watch request will wait during a block write, let's set it to 10s as a good starting point.
See the related tickets for context.
https://issues.apache.org/jira/browse/HDDS-10972
Existing tests (thanks for @smengcl for validating the CI earlier). Clean CI: https://github.com/ivandika3/ozone/actions/runs/9365515025
Tested with ozone-ha docker-compose environment with one DN down (using "docker container pause")
Without watch timeout configuration change -> client needs to wait for 3 minutes (the default …
> HDDS-10972. Reduce the default watch timeout configuration in DatanodeRatisServerConfig

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerSelectionCriteria.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerTask.java
SelectionCriteria.setSelectedContainers copy a set, which can be very memory intensive when the set is very large.
https://issues.apache.org/jira/browse/HDDS-10871
> HDDS-10871. ContainerBalancerSelectionCriteria memory occupancy optimization

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerStateManagerIntegration.java
Corrected the misleading assert message in TestContainerStateManagerIntegration.testGetMatchingContainerMultipleThreads
TestContainerStateManagerIntegration has assert Statement having misleading message
[INFO] Running org.apache.hadoop.hdds.scm.container.TestContainerStateManagerIntegration
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 22.117 s <<< FAILURE! - in org.apache.hadoop.hdds.scm.container.TestContainerStateManagerIntegration
Error:  org.apache.hadoop.hdds.scm.container.TestContainerStateManagerIntegration.testGetMatchingContainerMultipleThreads  Time elapsed: 22.05 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <2> but was: <3>
**Expectation:**
The correct message shall the expected actual which is 3. …
> HDDS-10973. TestContainerStateManagerIntegration has assert Statement having misleading message

- hadoop-ozone/dist/dev-support/bin/dist-layout-stitching
- pom.xml
Create and publish Software Bill of Materials (SBOM) for Ozone.
https://cwiki.apache.org/confluence/display/SECURITY/Software+Bill+of+Materials+SBOM
SBOM is created using `cyclonedx-maven-plugin` at build time, when using `dist` profile.
Both aggregate and module-level BOM is created.  Aggregate SBOM is included in the binary tarball, submodule BOMs are attached to JARs published to Maven repo.
https://issues.apache.org/jira/browse/HDDS-10986
```
$ mvn -DskipShade -DskipTests -Pdist clean install
...
$ ls -1hs hadoop-ozone/dist/target/ozone-1.5.0-SNAPSHOT/bom*
640K hadoop-ozone/dist/target/ozone-1.5.0-SNAPSHOT/bom.json
572K hadoop-ozone/dist/target/ozone-1.5.0-SNAPSHOT/bom.xml
...
$ ls ~/.m2/repository/org/apache/ozone/hdds-config/1.5.0-SNAPSHOT/*cyclonedx.* …
```
> HDDS-10986. Publish SBOM artifacts

- hadoop-hdds/hadoop-dependency-server/pom.xml
Ozone server components use code from `hadoop-auth`, e.g. `org.apache.hadoop.security.authentication.client.AuthenticationException`.  However, dependency on `hadoop-auth` is only transitive via `hadoop-common`.  We should add explicit dependency.
https://issues.apache.org/jira/browse/HDDS-10987
CI:
https://github.com/adoroszlai/ozone/actions/runs/9421451719
> HDDS-10987. Add explicit dependency for hadoop-auth

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/OzoneQuota.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/client/TestOzoneQuota.java
`RawQuotaInBytes.valueOf(0)` creates an object with unit of `EB`.  This PR changes that to use `B` (byte) as unit.
https://issues.apache.org/jira/browse/HDDS-10988
CI:
https://github.com/adoroszlai/ozone/actions/runs/9420841951
> HDDS-10988. Let zero OzoneQuota use byte as unit

- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/ClusterStateEndpoint.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/ClusterStateResponse.java
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/db.json
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/components/overviewCard/overviewCard.tsx
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/overview/overview.tsx
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestClusterStateEndpoint.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java
Add a data block with SCM and OM service IDs if the cluster is in HA mode
https://issues.apache.org/jira/browse/HDDS-10975
A new unit-test to check required field values in a response of cluster state endpoint, manually check the Recon UI Overview page
> HDDS-10975. Recon Show SCM and OM services IDs in overview page

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerTask.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerMoveSelection.java
moveSelectionToFutureMap cleanup when future complete
https://issues.apache.org/jira/browse/HDDS-10870
> HDDS-10870. moveSelectionToFutureMap cleanup when future complete

- hadoop-hdds/rocks-native/src/main/patches/rocks-native.patch
Changing the patch file in native lib to clear ParsedInternalKey object.
https://issues.apache.org/jira/browse/HDDS-10990
> HDDS-10990. Fix memory leak in native lib

- hadoop-hdds/common/pom.xml
- pom.xml
HDDS/Ozone Client depends (via `hdds-common`) on Ratis Server, which is unnecessary after the separation of Ratis Server API.
https://issues.apache.org/jira/browse/HDDS-10999
CI:
https://github.com/adoroszlai/ozone/actions/runs/9450260526
> HDDS-10999. Remove dependency on ratis-server from Ozone Client

- .github/workflows/build-ratis.yml
- .github/workflows/populate-cache.yml
- dev-support/ci/download-nodejs.sh
- hadoop-hdds/docs/dev-support/bin/generate-site.sh
- hadoop-ozone/dev-support/checks/acceptance.sh
- hadoop-ozone/dev-support/checks/blockade.sh
- hadoop-ozone/dev-support/checks/coverage.sh
- hadoop-ozone/dev-support/checks/junit.sh
- hadoop-ozone/dev-support/checks/kubernetes.sh
- hadoop-ozone/dist/src/main/k8s/examples/testlib.sh
- hadoop-ozone/dist/src/main/keytabs/update-keytabs.sh
- hadoop-ozone/dist/src/main/license/update-jar-report.sh
Skip publication of build scans for helper Maven commands:
* read dependency versions (`help:evaluate`)
* merge Jacoco files (`jacoco:merge`)
* set version in POMs (`versions:set`)
to reduce noise in Develocity.
https://issues.apache.org/jira/browse/HDDS-10997
CI run in `apache/ozone`:
https://github.com/apache/ozone/actions/runs/9429335669
Verified that the run published no scans for helper tasks:
https://ge.apache.org/scans?search.rootProjectNames=Apache%20Ozone%20Main&search.startTimeMax=1717883999999&search.startTimeMin=1717855200000&search.tags=HDDS-10997&search.timeZoneId=Europe%2FVienna
> HDDS-10997. Avoid publishing build scan for helper Maven commands

- .github/workflows/ci.yml
- .github/workflows/intermittent-test-check.yml
- .github/workflows/repeat-acceptance.yml
- .gitignore
- .mvn/develocity.xml
- .mvn/extensions.xml
Starting with version 1.21, the Gradle Enterprise extension is available under the “Develocity” brand.  This change [migrates](https://docs.gradle.com/develocity/maven-extension/legacy/#develocity_migration) configuration to allow future version bumps.
https://issues.apache.org/jira/browse/HDDS-10994
CI build in `apache/ozone`:
https://github.com/apache/ozone/actions/runs/9428877644/job/25974666271
Build scan published:
https://ge.apache.org/s/ez5vddmvqgzdm
CI run in fork:
https://github.com/adoroszlai/ozone/actions/runs/9429126848
> HDDS-10994. Migrate from Gradle Enterprise to Develocity

- hadoop-ozone/dist/src/main/smoketest/s3/MultipartUpload.robot
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMultipartObjectGet.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/util/S3Consts.java
Support the `x-amz-mp-parts-count` for MPU key. This value is returned if the object is uploaded as a multipart upload. The response is displayed in the get and head object aws commands as `PartsCount`.
https://issues.apache.org/jira/browse/HDDS-10640
Tested the patch locally on a docker cluster and verified the output.
sarvekshayr@Sarvekshas-MacBook-Pro ozonesecure % aws s3api head-object --bucket multipart-30oct-rat --endpoint http://localhost:9878 --key my_1GB_file
```
{
"LastModified": "2024-06-10T05:07:19+00:00",
"ContentLength": 1048576000,
"ETag": "\"9866ed9e49f7808c22243d26910dd99d-2\"",
"CacheControl": "no-cache",
"ContentType": "binary/octet-stream",
"Expires": "2024-06-10T05:07:37+00:00",
"Metadata": {},
"PartsCount": 2
}
```
sarvekshayr@Sarvekshas-MacBook-Pro ozonesecure % aws …
> HDDS-10640. Support x-amz-mp-parts-count for MPU key

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
Add assertions about `OmKeyInfo` and `OzoneKey` attributes for tests covering rewrite.
https://issues.apache.org/jira/browse/HDDS-10843
CI:
https://github.com/adoroszlai/ozone/actions/runs/9448431396
> HDDS-10843. Enhance rewrite test to cover all key attributes

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/ContainerClientMetrics.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/util/MetricUtil.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntry.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntryPool.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java
Create hsync metrics to measure client side latency with microsecond precision.
The PR adds two metrics, one for the Hsync RPC round-trip latency to Ozone Manager, another one for the round-trip latency to DataNode.
https://issues.apache.org/jira/browse/HDDS-9987
Tested against a real cluster.
> HDDS-9987. [hsync] Client side metrics.

- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconContainerManager.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconPipelineManager.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconPipelineReportHandler.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconPipelineManager.java
This pull request proposes changes to handle the scenario where a duplicate pipeline ID is detected in Recon. The modifications ensure that when a pipeline with a duplicate ID is encountered, the system logs a warning and skips the addition, instead of throwing an exception.
1. Modified the `addPipeline` method in the `ReconPipelineManager` class to check if the pipeline already exists before attempting to add it.
2. If a duplicate pipeline ID is detected, the system logs a warning and skips the addition.
3. Implemented a test case to verify that no exception is thrown when attempting to add a duplicate pipeline.
https://issues.apache.org/jira/browse/HDDS-10880
A new test case was added to `TestReconPipelineManager` to verify that no exception is thrown when a duplicate pipeline is added. …
> HDDS-10880. Duplicate Pipeline ID Detected in ReconContainerManager.

- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/container/common/TestEndPoint.java
After running the testRegisterRpcTimeout through the flaky workflow: https://github.com/Tejaskriya/ozone/actions/runs/9476838761 , the test seems to fail each time.
Even when the single test case is run multiple times locally, failures are observed on the first run, and the remaining runs are successful. 
By seeing the logs, It seems like the steps after timeout interruption takes place could take 700-800ms when the test is run individually.
In this PR, the test is refactored to measure only the required latency of endpointTask.call(), and not the remaining steps.
https://issues.apache.org/jira/browse/HDDS-11005
Tested flaky workflow: https://github.com/Tejaskriya/ozone/actions/runs/9494208563
> HDDS-11005. TestEndPoint#testRegisterRpcTimeout fails when run in itself

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/LeaseKeyInfo.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestLeaseRecovery.java
- hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMRecoverLeaseRequest.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/LeaseRecoveryClientDNHandler.java
- hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java
- hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java
- hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java
- hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java
In this PR, In some cases we are considering last two block to get the actual length from DN and update OM fileTable during lease recovery.
This is done as there may be some corner case when hsync is not called on last block and lease recover is called and also penultimate block is not completely filled because of various reason like CLOSE container. In this case penultimate block length is not correct in openFileTable as well as fileTable.
https://issues.apache.org/jira/browse/HDDS-10632
New integration test
> HDDS-10632. Handle inconsistent read issue for hsync keys after lease recovery.

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestNSSummaryAdmin.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/DiskUsageSubCommand.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/NSSummaryAdmin.java
When running `namespace du` command with root `/` or volume name `/volume` ofs paths, ofs path validation errors `INVALID_VOLUME_NAME` and `INVALID_BUCKET_NAME` are like below printed on the output. This is invalid because both `/` and `/volume` are valid paths.
Fixed the path validation code to skip printing errors if paths are valid.
```
ozone admin namespace du /
Connecting to Recon: https://xxx:9889/api/v1/namespace/du?path=/ ...
Bucket layout couldn't be verified for path: . Exception: INVALID_VOLUME_NAME org.apache.hadoop.ozone.om.exceptions.OMException: Bucket or Volume length is illegal, valid length is 3-63 characters
Bucket layout couldn't be verified for path: . Exception: INVALID_VOLUME_NAME org.apache.hadoop.ozone.om.exceptions.OMException: Bucket or Volume length is illegal, …
```
> HDDS-9644. Fixed incorrect validation of path with namespace du commands.

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/metrics/SCMPerformanceMetrics.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMBlockProtocolServer.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
In this PR few performance metrics are introduced in SCM Service for deleteKey operation.
In this PR following metrics are introduced in SCM service for deleteKey operation:
- deleteKeyFailure
- deleteKeySuccess
- deleteKeyFailureLatencyNs
- deleteKeySuccessLatencyNs
https://issues.apache.org/jira/browse/HDDS-10407
Tested manually on the cluster.
> HDDS-10407. Introduce metrics for deleteKey operation in SCM service.

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java
ContainerOpsLatency metric should reuse existing variable in onError.
https://issues.apache.org/jira/browse/HDDS-11003
- Existing metrics UTs would suffice.
> HDDS-11003. Eliminate code duplication in XceiverClientGrpc#sendCommandAsync

- pom.xml
Remove unused variable `release-year` from root POM.
`release-year` was used in Hadoop to show the release year in HDFS Web UI footer. Such footer is not present in Ozone Web UI and thus it is not used by Ozone anywhere.
https://issues.apache.org/jira/browse/HDDS-11019
- n/a
> HDDS-11019. Remove unused variable release-year from root POM

- hadoop-ozone/dev-support/checks/native.sh
- hadoop-ozone/dev-support/checks/unit.sh
- pom.xml
When running `integration.sh` without any arguments, some undesired tests are executed:
- tests marked as `@Native` (which require native bits from `hdds-rocks-native`)
- tests marked as `@Unhealthy` (which are expected to fail)
Changes in this PR:
- Add exclusion of `@Native` and `@Unhealthy` tests to Ozone's default configuration of Maven Surefire plugin.
- Add a new profile to not skip `@Native` tests when native bits are compiled.  The profile is activated by presence of `rocks_tools_native` property, which also triggers compilation of native bits.
- Remove `excludedGroups` from `native.sh`, since it was overriding the exclusion defined in the profile.
- Remove `excludedGroups` from `unit.sh`, since now it matches the default exclusion.
https://issues.apache.org/jira/browse/HDDS-11022 …
> HDDS-11022. Set default test exclusion

- .github/workflows/ci.yml
Changing only `junit.sh` should trigger `integration` check (which uses this script).  Output of `build-info` is correct ([`needs-integration-tests=true`](https://github.com/apache/ozone/actions/runs/9479546581/job/26118309123?pr=6807#step:4:777)), but `integration` is [skipped](https://github.com/apache/ozone/actions/runs/9479546581/job/26118347341?pr=6807) because `build` is [skipped](https://github.com/apache/ozone/actions/runs/9479546581/job/26118319979?pr=6807).  Since `integration` no longer uses artifacts from `build`, I propose to fix this by removing this dependency.
https://issues.apache.org/jira/browse/HDDS-11006
Regular CI:
https://github.com/adoroszlai/ozone/actions/runs/9480041261
> HDDS-11006. Selective checks: integration skipped when build not required

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientRatis.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ratis/conf/RatisClientConfig.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/Test2WayCommitInRatis.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestCommitInRatis.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestFailureHandlingByClient.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestWatchForCommit.java
Currently, while sending watch requests in ozone client, it sends watch requests with ratis replication level set to ALL_COMMITTED and in case it fails, it sends the request  with MAJORITY_COMMITTED semantics. The idea is to configure the replication level for watch requests so that MAJORITY_COMMITTED can be used if write performance is favored.
https://issues.apache.org/jira/browse/HDDS-2887
Existing UT.  This CI will test ALL_COMMITTED case.
This CI https://github.com/ChenSammi/ozone/actions/runs/9367491573  tested MAJORITY_COMMITTED case.
> HDDS-2887. Add config to tune replication level of watch requests in Ozone client

- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/NodeEndpoint.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java
This PR is to stop showing Decommissioned datanodes again on Recon Datanodes page after removing them explicitly.
Ozone Recon - Decommissioned datanodes shows up again after removing in Recon Datanodes page.
As part of [HDDS-10409](https://issues.apache.org/jira/browse/HDDS-10409)
Recon was allowing to remove the Decommissioned datanodes and was removing from Recon rocksDB nodes table, however Decommissioned datanodes continue to send heartbeats till they are being shutdown, so they get registered and added again in Recon memory map which makes them show up again in datanodes UI.
Solution is to allow only DEAD datanodes to be removed and skip other node status or node operational status datanodes.
https://issues.apache.org/jira/browse/HDDS-11032
This patch was tested by updating the …
> HDDS-11032. Decommissioned datanodes shows up again after removing in Recon Datanodes page.

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestAddRemoveOzoneManager.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/DecommissionOMSubcommand.java
Currently, before we decommission an OM, Ozone needs to configure with "ozone.om.decommissioned.nodes.serviceID" to vary of OM's to be decommissioned.
It would be nice to add a constant suffix-less config key support i.e. if only one serviceId is configured, "ozone.om.decommissioned.nodes" should be an acceptable config key that defaults to the only configured ID.
https://issues.apache.org/jira/browse/HDDS-10942
Tested Manually + Unit tests
> HDDS-10942. OM decommission config support for default serviceID.

- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/NSSummaryTaskDbEventHandler.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/NSSummaryTaskWithLegacy.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/NSSummaryTaskWithOBS.java
In the `NSSummaryTaskWithLegacy` class, a common issue arises when the ParentKeyInfo is null. ParentKeyInfo might be null due to deleted parents, yet-to-be-added parents, concurrency problems, or orphaned keys. Proper logging and error handling are essential to diagnose and address these issues effectively.
When ParentKeyInfo is null:
1. An IOException is thrown.
2. The error is logged with a few details.
3. The task fails, and the system attempts `to retry or reprocess the task.`
This behaviour ensures that the system does not silently ignore critical metadata inconsistencies, which could lead to larger issues later.
The desired functionality in handling the Null ParentKeyInfo error is to leave the current behaviour as is because:
Throwing exceptions on critical errors like missing …
> HDDS-10855. Handle Null ParentKeyInfo Error in Recon Namespace Summary Task.

- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/db.json
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/routes.json
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/utils/axiosRequestHelper.tsx
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/datanodes/datanodes.less
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/datanodes/datanodes.tsx
Recon datanodes listing page should have a mechanism using a button or link which will be enabled once user selects the  State is **DEAD** nodes for explicity removal from Recon memory and ask recon to stop tracking. 
**Node State= DEAD    Operation State=[Any State] ==> Allow for Removal**
Following backend API will be provided by Recon to facilitate this.
1) When totalcount is greater than 0 then we are displaying Remove button.
PUT
api/v1/datanodes/remove
JSON Body input takes UUID list of datanodes to be removed from cluster:
Input:
[
"50ca4c95-2ef3-4430-b944-97d2442c3daf"
]
Output:
Examples of well-written pull requests:
https://issues.apache.org/jira/browse/HDDS-10486
Need to get merge after  below backend  PR gets merged …
> HDDS-10486. Recon datanode UI to incorporate explicit removal of DEAD

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestXceiverClientGrpc.java
Reading data before the follower state machine hasn't finished applying log gets wrong `BlockData`.
The BlockInputStream reads data from one of the datanodes in the pipeline. If the BlockInputStream read data from follower before the statemachine finished updating, the data may be incorrect.
Therefore, I make the BlockInputStream read data from leader first.
https://issues.apache.org/jira/browse/HDDS-8942
Run `TestHSync` for 20*10 times:
https://github.com/chungen0126/ozone/actions/runs/9532695490
> HDDS-8942. Intermittent failure in ITestOzoneContractCreate#testSyncable

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
Add some tests that rename a key in both OBS and FSO buckets to sure the atomic commit works fine with renames.
https://issues.apache.org/jira/browse/HDDS-10946
https://github.com/adoroszlai/ozone/actions/runs/9546938396/job/26311575455#step:5:2174
> HDDS-10946. Test combinations of rename and rewrite

- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/FreonReplicationOptions.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/MandatoryReplicationOptions.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/ReplicationOptions.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/keys/RewriteKeyHandler.java
`ozone sh key rewrite` has a convenience feature to simply change between Ratis and EC(3,2) replication, when invoked without replication options.  The goal of this task is to remove it, and make replication options mandatory.
https://issues.apache.org/jira/browse/HDDS-11048
```
$ ozone freon ockg -n1 -t1 -p test
...
$ ozone sh key rewrite /vol1/bucket1/test/0
Missing required options: '--replication-type=<type>', '--replication=<replication>'
...
$ ozone sh key rewrite --type RATIS -r ONE /vol1/bucket1/test/0
$ ozone sh key info /vol1/bucket1/test/0
...
"replicationFactor" : "ONE",
```
Options are still not required for other commands:
```
$ ozone sh key put /vol1/bucket1/passwd /etc/passwd
$
```
CI:
https://github.com/adoroszlai/ozone/actions/runs/9616596034
> HDDS-11048. Remove dev-only toggle functionality of rewrite CLI

- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/diskUsage/diskUsage.tsx
Need to Remove tooltip from Recon Disk Usage which shows only for FSO Buckets.
Need to Remove tooltip from Recon Disk Usage which shows only for FSO Buckets.
(https://issues.apache.org/jira/browse/HDDS-11044)
Manually
Before this patch
After this patch
> HDDS-11044. Recon Disk Usage need to remove tool tip

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/recon/ReconConfigKeys.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconUtils.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/OzoneManagerServiceProviderImpl.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestTriggerDBSyncEndpoint.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/spi/impl/TestOzoneManagerServiceProviderImpl.java
**_Changes in this patch include the following :-_** 
We included checks for the presence of SST files, logging a warning if the snapshot is empty or lacks SST files, which could indicate issues such as OM leader instability or snapshot corruption.
The synchronization process between Recon and the OM database now includes logging of the last sequence number before and after each sync. 
We implemented a method to validate the permissions of the Recon DB directories against the expected configuration settings. The method logs a warning if the actual permissions do not match the expected permissions, enhancing operational awareness.
https://issues.apache.org/jira/browse/HDDS-10813
Manually Tested out the logs. The required log messages get printed :- 
1. Logging for SST Files Availability on …
> HDDS-10813. Improve Recon Debuggability for Snapshot Fetching, Sync Monitoring, and Permission Validation.

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/interfaces/Container.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainer.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/BackgroundContainerDataScanner.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/BackgroundContainerMetadataScanner.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/ContainerController.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OnDemandContainerDataScanner.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/ContainerTestUtils.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestBackgroundContainerDataScanner.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestBackgroundContainerMetadataScanner.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestContainerScannersAbstract.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOnDemandContainerDataScanner.java
Currently the container scanner skips containers which are already marked as unhealthy. Now that the we want to either repair these containers, or use parts of them to repair other containers. We need the container scanner to scan UNHEALTHY container as well. 
https://issues.apache.org/jira/browse/HDDS-10923
Existing Tests.
> HDDS-10923. Container Scanner should still scan unhealthy containers.

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ECBlockOutputStream.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/storage/ContainerProtocolCalls.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java
HDDS-11014. [hsync] Block finalization should also merge last chunk to blockDataTable.
There are two scenarios where the last chunk should be merged into blockDataTable:
(1) when block is being closed by client. In this case, an endOfBlock flag is added to WriteChunk/PutBlock combo request to tell the DataNode to merge the last chunk.
(2) if an open file is closed by recoverLease, in which case, the DataNode finalizeBlock handler must merge the last chunk too.
https://issues.apache.org/jira/browse/HDDS-11014
TBD
> HDDS-11014. [hsync] Block finalization should also merge last chunk to blockDataTable.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfig.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/choose/algorithms/RoundRobinPipelineChoosePolicy.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/choose/algorithms/TestRoundRobinPipelineChoosePolicy.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientRetriesOnExceptions.java
Implement `RoundRobinPipelineChoosePolicy` for test case `TestOzoneClientRetriesOnExceptions#testMaxRetriesByOzoneClient`, in order to make sure the test is properly run every time instead of depending on the randomness in `RandomPipelineChoosePolicy`.
`Assume.assumeFalse(containerList.contains(containerID))` was added in HDDS-4577 (#1689) to skip the test if the condition of each block being in a different container is not satisfied. That can now be guaranteed with `RoundRobinPipelineChoosePolicy` and has thus been switched to `assert`.
At this moment, `RoundRobinPipelineChoosePolicy` might only be useful for testing and debugging purposes.
https://issues.apache.org/jira/browse/HDDS-11020
- Added UT.
> HDDS-11020. Implement RoundRobinPipelineChoosePolicy

- hadoop-hdds/common/src/main/resources/ozone-default.xml
Just fixing the doc:
1. `SPNEOGO -> SPNEGO`
2. There is no such thing as "Kerberos SPNEGO". Kerberos is a one of the auth sub-mechanisms that can be used under SPNEGO (the other common one being NTLM).
https://issues.apache.org/jira/browse/HDDS-11066
- n/a
> HDDS-11066. Fix inaccurate *.http.auth.type config descriptions in ozone-default.xml

- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java
When DEBUG logging is enabled for OM, there are many un-useful messages as mentioned in the JIRA description. These messages are now in TRACE log level. 
https://issues.apache.org/jira/browse/HDDS-11059
Tested the patch on docker.
Before changing the log level:
```
2024-06-27 07:56:36 2024-06-27 02:26:36 INFO  OzoneManager:1228 - Creating RPC Server
2024-06-27 07:56:36 2024-06-27 02:26:36 DEBUG RocksDatabase:684 - get: size=-1, remaining=4096
2024-06-27 07:56:36 2024-06-27 02:26:36 INFO  RaftServer$Division:256 - om1: new RaftServerImpl for group-C5BA1605619E:[om1|om:9872] with OzoneManagerStateMachine:uninitialized
2024-06-27 07:56:36 2024-06-27 02:26:36 DEBUG LifeCycle:154 - om1: NEW
```
After changing the log level:
```
2024-06-27 08:00:29 2024-06-27 02:30:29 INFO  OzoneManager:1228 - …
```
> HDDS-11059. Reduce OM DEBUG messages

- pom.xml
- Bump Ratis to 3.1.0.
- Increase Surefire fork heap to 8GB to fix `OutOfMemoryError` in `TestRandomKeyGenerator`.
https://issues.apache.org/jira/browse/HDDS-10910
CI:
https://github.com/adoroszlai/ozone/actions/runs/9685631843
> HDDS-10910. Bump Ratis to 3.1.0

- hadoop-hdds/rocks-native/pom.xml
- hadoop-ozone/dev-support/checks/junit.sh
`native` check fails when run with Java 11 or later.
```
$ export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
$ mvn -Drocks_tools_native -Pnative clean test
...
Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.6.1:copy-dependencies (copy-jars) on project hdds-rocks-native: Artifact has not been packaged yet. When used on reactor artifact, copy should be executed after packaging: see MDEP-187
```
This was reported earlier in HDDS-10118, but mistakenly thought to be fixed, because we were trying to reproduce with `mvn clean install`.  The problem only happens if Maven goal preceding `package` is executed.
The workaround is to run tests by using `verify` goal, which is after `package` in the lifecycle.
Also, remove hard-coded compile source/target of Java 8 in the …
> HDDS-11054. native check fails with Java11+

- hadoop-hdds/docs/content/feature/Nonrolling-Upgrade.md
[The upgrade docs](https://ozone.apache.org/docs/current/feature/nonrolling-upgrade.html) have a section that lists which new features require finalization before they can be used in a new version. However, this section hasn't been updated since Ozone 1.2.0. IMO we can remove this section since new features should be documented in the release notes and the system will tell you if finalization is required when you try to use them.
HDDS-11080
Local preview of the page renders correctly.
> HDDS-11080. Remove "Features requiring finalization" section in docs.

- pom.xml
Move up to Ratis 3.1.0
https://issues.apache.org/jira/browse/HDDS-10955
CI:
https://github.com/chungen0126/ozone/actions/runs/9703602797
> HDDS-10955. [hsync] Adopt Ratis 3.1.0 when it's released

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/SnapshotDeletingService.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestSnapshotDeletingService.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOmSnapshotUtils.java
Currently, SnapshotDeletingService calls [KeyManagerImpl#isSstFilteringSvcEnabled()](https://github.com/apache/ozone/blob/f00455897e99d5fcef6e8145921117fa97cc8c01/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/SnapshotDeletingService.java#L162-L164) for each snapshot while iterating over snapshotInfoTable. It reads the config every time which is a redundant call. Since the config can not be changed after the service's startup dynamically, we can change the code to read the config once and reuse it.
HDDS-11084
Unit tests.
> HDDS-11084. Read SstFilteringService config once and reuse it in SnapshotDeletingService

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java
When the conf is not set, there is a NPE:
In `OmUtils#getAllOMHAAddresses`, if `omNodeDetails` was null, then `omNodeDetails.getNodeId()` throws NPE.
```
OMNodeDetails omNodeDetails = OMNodeDetails.getOMNodeDetailsFromConf(
conf, omServiceId, nodeId);
if (decommissionedNodeIds.contains(omNodeDetails.getNodeId())) {
omNodeDetails.setDecommissioningState();
}
```
https://issues.apache.org/jira/browse/HDDS-10508
CI:
https://github.com/chungen0126/ozone/actions/runs/9716680901
> HDDS-10508. OmUtils.getAllOMHAAddresses may throw NPE

- .github/workflows/ci-with-ratis.yml
- .github/workflows/ci.yml
HDDS-10854 added a workflow to run full Ozone CI with specific version of Ratis. It also has an input for the Ozone branch/tag/commit to test. The current version has a bug: this input is ignored, the workflow's branch (usually master) is used in all runs.
https://issues.apache.org/jira/browse/HDDS-11042
Triggered manually, verified Ozone commit being built is from the branch specified in workflow input:
https://github.com/adoroszlai/ozone/actions/runs/9600783270/job/26477933573#step:4:245
Regular CI (push build):
https://github.com/adoroszlai/ozone/actions/runs/9600910016
Created a test PR:
https://github.com/adoroszlai/ozone/pull/30
https://github.com/adoroszlai/ozone/actions/runs/9602631775?pr=30
> HDDS-11042. CI with Ratis ignores Ozone ref

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientRatis.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStream.java
We can use CommitInfoProto in NotReplicatedException introduced in [RATIS-2089](https://issues.apache.org/jira/browse/RATIS-2089) to remove the need for watch MAJORITY_COMMITTED calls if NotReplicatedException is thrown from the DN Ratis leader.
This also requires DN Ratis server watch timeout configuration change hdds.ratis.raft.server.watch.timeout to be lower than the client watch timeout hdds.ratis.raft.client.rpc.watch.request.timeout so that NotReplicatedException will be thrown instead of TimeoutException.
https://issues.apache.org/jira/browse/HDDS-10932
Existing tests. Increased the client watch RPC timeout in `TestBlockOutputStream` to be strictly larger than the server watch timeout to reflect the current default configurations.
Clean CI: …
> HDDS-10932. Reduce number of watch requests by using CommitInfoProto from NotReplicatedException

- hadoop-hdds/common/pom.xml
- hadoop-ozone/client/pom.xml
- hadoop-ozone/common/pom.xml
- pom.xml
We started using `@Immutable` from `jcip-annotations` in HDDS-10322 (and some follow-up tasks).  However, `jcip-annotations` is only a transitive dependency via `nimbus-jose-jwt`.  We should add an explicit dependency.
https://issues.apache.org/jira/browse/HDDS-11090
CI:
https://github.com/adoroszlai/ozone/actions/runs/9723714947
> HDDS-11090. Add explicit dependency for jcip-annotations

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/BackgroundService.java
Currently BackgroundService#PeriodicalTask#run will capture Exception type exception and log warning message, change it to capture Throwable to log messages for all failure cases. 
https://issues.apache.org/jira/browse/HDDS-11067
The test will be covered by existing UTs.
> HDDS-11067. Capture Throwable execption in BackgroundService#PeriodicalTask

- hadoop-ozone/dist/src/main/smoketest/s3/MultipartUpload.robot
- hadoop-ozone/dist/src/main/smoketest/s3/objectcopy.robot
- hadoop-ozone/dist/src/main/smoketest/s3/objectputget.robot
S3 Robot tests have some test cases using shell function `printf` to generate fixed length string.
```
hadoop-ozone/dist/src/main/smoketest/s3/objectcopy.robot
115:    ${custom_metadata_value} =  Execute                    printf 'v%.0s' {1..3000}
hadoop-ozone/dist/src/main/smoketest/s3/objectputget.robot
194:    ${custom_metadata_value} =  Execute                    printf 'v%.0s' {1..3000}
202:    ${long_tag_key} =           Execute                               printf 'v%.0s' {1..129}
205:    ${long_tag_value} =         Execute                               printf 'v%.0s' {1..257}
hadoop-ozone/dist/src/main/smoketest/s3/MultipartUpload.robot
161:    ${custom_metadata_value} =  Execute                               printf 'v%.0s' {1..3000}
```
This does not work on more recent bash …
> HDDS-11095. Generate fixed length string with Robot builtin

- hadoop-ozone/dist/src/main/compose/ozonesecure-ha/docker-compose.yaml
- hadoop-ozone/dist/src/main/compose/ozonesecure/docker-compose.yaml
`httpfs` container uses hard-coded `apache/ozone-runner` image.  It should use `$OZONE_RUNNER_IMAGE`, like all other Ozone containers, to allow testing new/custom runner image.
https://issues.apache.org/jira/browse/HDDS-11101
CI:
https://github.com/adoroszlai/ozone/actions/runs/9818282363
> HDDS-11101. Use `OZONE_RUNNER_IMAGE` for httpfs

- pom.xml
Building Ozone with Java 9+ (but still targeting Java 8 with `javac.version=8`) and running with Java 8 results in:
```
NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
at org.apache.hadoop.ozone.common.ChunkBufferImplWithByteBuffer.duplicate(ChunkBufferImplWithByteBuffer.java:111)
```
It can be reproduced in Hadoop compatibility tests, because Hadoop images still ship with Java 8, while Ozone images have newer Java.
CI tweak for repro:
https://github.com/adoroszlai/ozone/commit/33f7f4b2cc26e380ee7e570b990ef9962021b89c
Failure:
https://github.com/adoroszlai/ozone/actions/runs/9792172547/job/27038142506#step:6:9
Exception can be seen in `log.html` in the [test artifact](https://github.com/adoroszlai/ozone/actions/runs/9792172547/artifacts/1667509237).
Blog with great …
> HDDS-11076. NoSuchMethodError: ByteBuffer.position compiling with Java 9+, running with Java 8

- hadoop-ozone/dist/src/main/compose/testlib.sh
Acceptance test saves Docker container logs, but only for those still running at the end of the test.  It should collect logs from stopped containers, too.
https://issues.apache.org/jira/browse/HDDS-11106
Changed `ozone/test.sh` to simulate stopped container:
```
COMPOSE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
export COMPOSE_DIR
export SECURITY_ENABLED=false
export OZONE_REPLICATION_FACTOR=3
source "$COMPOSE_DIR/../testlib.sh"
start_docker_env
sleep 30
docker-compose ps
docker-compose stop httpfs recon
sleep 30
docker-compose ps
sleep 30
```
Log files after "test" finished:
```
$ ls -1sh result
total 656K
0 dn-audit-2581c25f46e7.log
0 dn-audit-71ca6309050a.log
0 dn-audit-90d141c9629a.log
116K docker-ozone-datanode-2.log
124K docker-ozone-datanode-3.log
16K …
```
> HDDS-11106. Save logs for stopped containers

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/ContainerMetrics.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/CSMMetrics.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/DispatcherContext.java
HDDS-10941. CSMMetrics to record number of started transactions
(1) 
Add a label RaftGroupId so that Prometheus can identify different CSM instances by pipeline id. Previously, only one Container State Machine metrics instance is exported, which is confusing.
Add a few metrics for ContainerStateMachine operations.
* opsQueueingDelay -- the queueing latency of ContainerOp thread pool.
* pendingApplyTransactions -- count the number of transactions between startTransaction and applyTransaction
* untilApplyTransactionNs -- measures the latency between startTransaction and applyTransaction
* startTransactionCompleteNs -- measures the time spent in startTransaction callback method.
https://issues.apache.org/jira/browse/HDDS-10941
Existing unit tests passed. …
> HDDS-10941. Add a few interesting ContainerStateMachine metrics in CSMMetrics

- hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - ReadKey Metrics.json
Created a new dashboard and added visualisations for all the required ReadKey Metrics.
https://issues.apache.org/jira/browse/HDDS-10112
The patch has been tested over a Grafana.
> HDDS-10112. Dashboard for read key metrics

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/DecommissionUtils.java
This PR is to fix the NullPointerException for datanode tag in Decommissioning Info API JSON.
https://issues.apache.org/jira/browse/HDDS-11045
Patch was tested manually with existing Junit test cases.
> HDDS-11045. Recon Decommissioning Info API throws NPE.

- .github/workflows/ci.yml
- .github/workflows/intermittent-test-check.yml
- .github/workflows/repeat-acceptance.yml
- hadoop-ozone/dev-support/checks/build.sh
Javadoc is generated only with the `dist` profile.  This is used in CI build, but Javadoc is explicitly skipped.  Thus, javadoc generation is currently exercised only when making release candidates.
This change enables Javadoc generation in the `compile` check.  Build is successful despite Javadoc problems, e.g.:
```
Warning:  .../GenericTestUtils.java:339: warning - invalid usage of tag >
```
We can enable `failOnWarning` after fixing these warnings.  The current change would help catch problems with usage of `maven-javadoc-plugin` itself (e.g. wrong version or config).
https://issues.apache.org/jira/browse/HDDS-11112
Verified `maven-javadoc-plugin` is executed in `compile` check:
https://github.com/adoroszlai/ozone/actions/runs/9828984546/job/27133798734#step:8:3488
> HDDS-11112. Verify javadoc creation in CI

- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/snapshot/SnapshotDiffHandler.java
The pagination logic is already there, so this jira only prints default value for snapshot diff cli.
The default value is 1000 according to:
https://github.com/apache/ozone/blob/4d29b6ce30019fb9b47d5f1a4a88645214cf23b9/hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java#L551-L552
And
https://github.com/apache/ozone/blob/4d29b6ce30019fb9b47d5f1a4a88645214cf23b9/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java#L201-L204
And
https://github.com/apache/ozone/blob/4d29b6ce30019fb9b47d5f1a4a88645214cf23b9/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java#L758-L760
https://issues.apache.org/jira/browse/HDDS-10841
1. Build in local docker containers
`mvn clean install -DskipTests` and …
> HDDS-10841. Snapshot diff CLI help should print default value for parameters

- hadoop-ozone/dist/src/main/compose/test-all.sh
`compose/test-all.sh` assumes it is executed with `compose` being the current directory.  This assumption is needed only for finding tests, since right after that step the script changes to its own directory.
With this trivial change, `test-all.sh` can be executed from any directory, it changes dir before finding tests.
https://issues.apache.org/jira/browse/HDDS-11110
Tweaked `test-all.sh`, so that after finding tests it prints current dir, lists tests found (would normally be executed), and then exit:
```
pwd
echo $tests
exit
```
Tested in various dirs.  Verified both current dir and list of tests are the same in each case:
```
$ cd hadoop-ozone/dist/target/ozone-1.5.0-SNAPSHOT/compose/ozone
$ ../test-all.sh 
hadoop-ozone/dist/target/ozone-1.5.0-SNAPSHOT/compose
compatibility/test.sh …
```
> HDDS-11110. Allow running test-all.sh from any directory

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/validation/RequestValidations.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/validation/ValidatorRegistry.java
1. Avoid unnecessary conversion to/from builder in `RequestValidations`.
2. Create `defaultValue` only if needed in `ValidatorRegistry`, and replace logic with `computeIfAbsent`.
3. `MethodAnnotationsScanner` is deprecated, replace as suggested in javadoc.
https://issues.apache.org/jira/browse/HDDS-11139
CI:
https://github.com/adoroszlai/ozone/actions/runs/9880192900
> HDDS-11139. Avoid unnecessary object creation in OM request validator

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneDebugShell.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/ChunkKeyHandler.java
After HDDS-10983 , it requires every getBlock request be assigned a replicaIndex in case of an EC block. The request constructed for getBlock in this tool didn't have that. This change sets the replicaIndex if key is EC in the getBlock request.
I have reconstructed the request after unpacking the existing request which could have been avoided but since the usecase is just a debug tool and it was simple change, I went with it.
https://issues.apache.org/jira/browse/HDDS-11069
Unit test
> HDDS-11069. Block location is missing in output of Ozone debug chunkinfo command for EC.

- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/RootPageDisplayFilter.java
Newer `curl` sends `Authorization: Negotiate` in initial request, so redirect from `/` to `/static/` fails with 403:
```
$ curl --negotiate -u : -vvv http://s3g:9878/
...
* Connected to s3g (172.20.0.9) port 9878 (#0)
* Server auth using Negotiate with user ''
> GET / HTTP/1.1
> Host: s3g:9878
> Authorization: Negotiate <redacted>
> User-Agent: curl/7.81.0
...
< HTTP/1.1 403 Forbidden
...
<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>InvalidRequest</Code>
<Message>Error creating s3 auth info. The request may not be signed using AWS V4 signing algorithm, or might be invalid</Message>
<Resource/>
<RequestId/>
</Error>
```
Using old `curl`:
```
$ curl --negotiate -u : -vvv http://s3g:9878/
...
* Connected to s3g (172.20.0.9) port 9878 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> …
```
> HDDS-11096. Error creating s3 auth info for request with Authorization: Negotiate

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerStateMachine.java
JIRA: HDDS-11100. OM/SCM Metrics support displaying Netty off-heap memory.
During a recent period, our cluster's DataNode (DN) exhibited high off-heap memory utilization, triggering frequent system.gc() calls. Upon reading relevant GC logs, we observed normal heap memory usage and monitored heap metrics. It became apparent that off-heap memory usage might be causing the system.gc() calls. We identified that DataNode can display off-heap memory usage, which indirectly helped us infer potential off-heap memory overflow. In [HDDS-9070](https://issues.apache.org/jira/browse/HDDS-9070), we now support displaying Netty off-heap memory usage on DataNode, facilitating off-heap memory monitoring. Similarly, we can display Netty off-heap memory usage on OM and SCM. …
> HDDS-11100. OM/SCM Metrics support displaying Netty off-heap memory.

- hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/DirectoryDeletingService.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/KeyDeletingService.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/recovery/ReconOmMetadataManagerImpl.java
As part of the investigation of HDDS-11124, it was found that change HDDS-8067 created a deadlock and caused the read/write operations to halt.
<ins>**Deadlock scenario**</ins>: Handler threads waiting for applyTransaction future -> which is waiting for DoubleBuffer which is in progress -> DoubleBuffer flush thread is stuck on processing a SnapshotCreate request -> because OmSnapshotManager is waiting for the DeletedTable lock -> which is being held by KeyDeletingService -> which is waiting for deletion to be applied by OzoneManagerStateMachine#applyTransaction.
More detailed analysis in HDDS-11124.
As part of this change, DELETED_TABLE and DELETED_DIR_TABLE locks are removed and we are relying on transaction flush which happens sequentially on both Ratis and DoubleBuffer for now. …
> HDDS-11124. Removed DELETED_TABLE and DELETED_DIR_TABLE locks

- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/package.json
HDDS-11169. Updates the package manager field for Recon package.json
* Currently dependabot uses the package.json packageManager field to identify the version and the package manager that is being used by the project.
* This field was not updated, but pnpm version was changed to v8.
* This causes dependabot to use v7 to generate the lockfile, but we are using pnpm v8 to build the project.
* Hence dependabot PRs related to JS upgrades are failing in CI builds.
* This PR will fix that issue.
https://issues.apache.org/jira/browse/HDDS-11169
This patch was tested manually in forked repo via dependabot upgrade PR request.
> HDDS-11169. Upgrade packageManager version for Recon package.json

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/debug/TestLDBCli.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/ValueSchema.java
RocksDB stores data in key-value pairs. The value itself may have some kind of key-value structure. A command is needed which shows what structure this value has and prints the same. This would help in parsing and filtering the output of `ozone debug ldb scan` command to obtain only the required details from the value.
In this PR, A command `ozone debug ldb --db=<db-path> value-schema --cf=<table-name>` has been introduced, which uses java reflections to fetch the fields of the value type of a rocksDB for all levels. `--depth` option can be used to limit the hierarchy till which it fetches the fields.
https://issues.apache.org/jira/browse/HDDS-11117
Tested manually in docker setup, also added test in TestLDBCli. Sample output:
```
sh-4.2$ ozone debug ldb --db=/data/metadata/om.db …
```
> HDDS-11117. Introduce debug CLI command to show the value schema of any rocksDB

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/AbstractCommitWatcher.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BufferPool.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/CommitWatcher.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ECBlockOutputStream.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/RatisBlockOutputStream.java
- hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestBufferPool.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChunkBufferImplWithByteBuffer.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntryPool.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestCommitWatcher.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStream.java
Make KeyOutputStream/BlockOutputStream ready for multiple threads calling hsync.
https://issues.apache.org/jira/browse/HDDS-9844
Test
> HDDS-9844. [hsync] De-synchronize write APIs

- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
Currently the max_open_files rocksdb config is -1 by default and not set anywhere via Ozone code. However in situations where the number of SST Files in the rocksdb instance becomes greater than the ulimit (open file limit of the OS), Rocksdb will not respect the OS config and try to open all files at once thereby leading to "Too many open files" error. 
Introducing a config in Ozone to set this is helpful to avoid/recover from such crashes. Default is still kept unchanged as -1 as [RocksDB recommends](https://github.com/facebook/rocksdb/wiki/Memory-usage-in-RocksDB#indexes-and-filter-blocks) -1 for best performance.
>  If you are certain that your ulimit will always be bigger than number of files in the database, we recommend setting max_open_files to -1, which means infinity. 
Setting …
> HDDS-11191. Add a config to set max_open_files for OM RocksDB.

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/StorageLocationReport.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/AvailableSpaceFilter.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeUsage.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestReservedVolumeSpace.java
HDDS-11135. [hsync] Replace expensive VolumeUsage.getMinVolumeFreeSpace()
VolumeUsage.getMinVolumeFreeSpace() has a lot of expensive ConfigurationSource lookups, which is wastes CPU cycles in one of the most critical performance bottleneck area for hsync (DataNode ContainerStateMachine.writeStateMachiine()).
The values never changes and should be cached and reused.
https://issues.apache.org/jira/browse/HDDS-11135
New UT in TestReservedVolumeSpace to cover the new code.
Async profiler confirms the CPU time is removed from flame graph.
> HDDS-11135. [hsync] Replace expensive VolumeUsage.getMinVolumeFreeSpace()

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/ContainerMetrics.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/StreamDataChannelBase.java
- hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/MetricsAsserts.java
ContainerOpsLatencies are now measured by milliseconds while most container op latencies are submilliseconds. This results in  ContainerOpsLatencies recorded as zeros. 
ContainerOpsLatencies should be captured as nanoseconds.
https://issues.apache.org/jira/browse/HDDS-11185
CI.
> HDDS-11185. Fix ContainerOpsLatencies metrics

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/client/HddsClientUtils.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/OzoneRpcClientTests.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotCreateRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotDeleteRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotRenameRequest.java
HDDS-10844. Clarify snapshot create error message
* Show the specific reason why the snapshot name is invalid by throwing the specific IllegalArgumentException using `e.getMessage()`
* Enhance HddsClientUtils.verifyResourceName to support validation for volumes, buckets, and snapshots by introducing a resType parameter. This modification allows specifying the resource type in error messages, making them more context-specific.
Usage examples:
HddsClientUtils.verifyResourceName(snapshotName, "snapshot");
HddsClientUtils.verifyResourceName(volumeName, "volume", isStrictS3);
HddsClientUtils.verifyResourceName(bucketName, "bucket", isStrictS3);
Example output:
docker exec -it ozone-om-1 sh -c "ozone sh snapshot create /s3v/bucket1 s1"
INVALID_SNAPSHOT_ERROR …
> HDDS-10844. Clarify snapshot create error message

- hadoop-ozone/dist/src/main/compose/testlib.sh
Logs for one of the containers for each run is missing from acceptance test artifacts.
For example, `docker-ozone-datanode-1.log` and `docker-ozonesecure-ha-datanode1-1.log` here:
```
$ find 2024/07/12/32233/acceptance-s3a -name 'docker*' | sort
2024/07/12/32233/acceptance-s3a/ozone/s3a/docker-ozone-datanode-2.log
2024/07/12/32233/acceptance-s3a/ozone/s3a/docker-ozone-datanode-3.log
2024/07/12/32233/acceptance-s3a/ozone/s3a/docker-ozone-httpfs-1.log
2024/07/12/32233/acceptance-s3a/ozone/s3a/docker-ozone-om-1.log
2024/07/12/32233/acceptance-s3a/ozone/s3a/docker-ozone-recon-1.log
2024/07/12/32233/acceptance-s3a/ozone/s3a/docker-ozone-s3g-1.log
2024/07/12/32233/acceptance-s3a/ozone/s3a/docker-ozone-scm-1.log
2024/07/12/32233/acceptance-s3a/ozonesecure-ha/s3a/docker-ozonesecure-ha-datanode2-1. …
```
> HDDS-11186. First container log missing from bundle

- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBConfigFromFile.java
HDDS-11179. DBConfigFromFile#readFromFile result of toIOException not thrown
* throw the toIOException
https://issues.apache.org/jira/browse/HDDS-11179
github CI test passed
> HDDS-11179. DBConfigFromFile#readFromFile result of toIOException not thrown

- hadoop-ozone/dist/src/main/smoketest/spnego/web.robot
Update existing Robot test for SPNEGO-enabled URLs to cover more endpoints (more servlets and more servers).
https://issues.apache.org/jira/browse/HDDS-11192
Run in CI:
```
Verify SPNEGO URLs without auth                                       | PASS |
Verify SPNEGO URLs with auth                                          | PASS |
```
https://github.com/adoroszlai/ozone/actions/runs/9961163803/job/27522849505#step:5:997
```
$ grep -o 'curl.*http_code.*http://[^ ]*' ozonesecure.xml | wc -l
54
$ grep -o 'curl.*http_code.*http://[^ ]*' ozonesecure.xml | head 
curl --negotiate -u : --silent -o /dev/null -w '%{http_code}' 'http://om:9874/conf'
curl --negotiate -u : --silent -o /dev/null -w '%{http_code}' …
```
> HDDS-11192. Increase SPNEGO URL test coverage

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMUpgradeFinalization.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/audit/OMAction.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/upgrade/OMCancelPrepareRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/upgrade/OMFinalizeUpgradeRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/upgrade/OMPrepareRequest.java
Audit log is added for upgrade prepare, cancel and finalize as this was missing. Since this is user request, this also needs logged.
https://issues.apache.org/jira/browse/HDDS-11194
- added testcase for audit log generation
> HDDS-11194. OM missing audit log for upgrade prepare, cancel and finalize

- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/HttpServer2.java
HDDS-11180. Simplify HttpServer2#inferMimeType return statement
The additional null check is removed. The intermediate variable mime was removed, making the return statement directly return the result of sContext.getMimeType(path).
https://issues.apache.org/jira/browse/HDDS-11180
workflow run on the fork git repo
> HDDS-11180. Simplify HttpServer2#inferMimeType return statement

- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/.vscode/extensions.json
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/.vscode/settings.json
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/tsconfig.json
HDDS-11198.  Fix Typescript configs for Ozone Recon
- Currently the tsconfig is not up to standard recommended by TypeScript. We are explicitly specifying the complete path.
- While the builds happen properly, but the editor/IDE cannot properly resolve the modules
- This PR fixes the issue by properly specify the path relative to the baseUrl
- It also adds a .vscode configuration folder to help new contributors setup their editor/environment out of the box.
https://issues.apache.org/jira/browse/HDDS-11198
The patch was tested manually by running build, as well as checking if the resolution errors go away after changing the settings
> HDDS-11198. Fix Typescript configs for Recon

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotCreateResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotManager.java
Keys from DeletedTable and DeletedDirTable of AOS should be deleted on batch operation while creating a snapshot and not directly from the table. The transactions have to be flushed to delete the keys. If the transaction is not flushed then the deleted keys wouldn't be present in the next transaction replay leading to having unreferenced blocks in the system.
Scenario:
Snapshot S1 create is fired.
create S1 transaction has not been flushed yet, but it has created the snapshot directory and deleted the entries from the table.
This OM has received a bootstrap request from another OM. The bootstrap command will only copy the OM instance and the snapshots that have been flushed to the AOS. S1 will not be a part of it.
The boostrapped OM will replay unflushed transactions(Create S1 will be a …
> HDDS-11183. Keys from DeletedTable and DeletedDirTable of Active Object Store should be deleted on batch operation while creating a snapshot

- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/components/overviewCard/overviewCard.tsx
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/utils/axiosRequestHelper.tsx
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/diskUsage/diskUsage.tsx
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/insights/insights.tsx
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/overview/overview.tsx
HDDS-11150. Shift Axios.all to Promise.allSettled and add fallback for error in failed requests
- Currently Axios.all() uses Promise.all() in the background, but this causes all further promises to reject if one request is rejected
- So we have migrated to Promise.allSettled() which allows to wait for all requests to complete instead of immediately rejecting
- Along with this new fallbacks have been added to allow data to be shown even if there is an error while fetching the data
- Scope of fallback scenario
- When the API is unreachable, say because of an API timeout or the backend is not able to respond
- When the network might go down and the call to the backend fails
- If the API returns any error (like 500, or 404 etc.) where the data is not present …
> HDDS-11150. Recon Overview page crashes due to failed API Calls

- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/OMDBUpdatesHandler.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestOMDBUpdatesHandler.java
Map Structure Change: The `omdbLatestUpdateEvents` map has been changed from `Map<Object, OMDBUpdateEvent>` to `Map<String, Map<Object, OMDBUpdateEvent>>`. This nested map structure ensures that each table's events are stored separately, avoiding key collisions between different tables.
Event Processing Logic: The `processEvent` method now uses the table name as the first-level key in the map. If a key already exists for a table, it retrieves the nested map and updates or adds the event. This change ensures that events from different tables with the same key structure are isolated and correctly processed.
This change ensures that events from different tables with the same key structure do not overwrite each other, preventing the `ClassCastException` caused by fetching incorrect event …
> HDDS-11187. Fix Event Handling in Recon OMDBUpdatesHandler to Prevent ClassCastException

- hadoop-ozone/dist/src/shell/ozone/ozone
Added `-Dorg.apache.ratis.thirdparty.io.netty.tryReflectionSetAccessible=true` to the ozone script to allow Netty unsafe memory allocation and avoid the zeroing cost for Java 9+.
https://issues.apache.org/jira/browse/HDDS-10382
Tested the patch in docker by changing the Java version.
```
recon-1     | Java version string: openjdk version "17.0.2" 2022-01-18
recon-1     | OpenJDK Runtime Environment (build 17.0.2+8-86)
recon-1     | OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
recon-1     | Java major version: 17
recon-1     | NETTY_OPTS: -Dorg.apache.ratis.thirdparty.io.netty.tryReflectionSetAccessible=true
```
> HDDS-10382. Optimize Netty memory allocation by avoiding zero assignment in Java 9+

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestDirectoryDeletingServiceWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerDoubleBuffer.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMDirectoriesPurgeRequestWithFSO.java
bucketInfo can have incorrect count, and even can go -ve value. This is as DirectoryDeletingService keeps sending purgeDirectory request till rocksdb delectedDirectoryTable is not flushed with deletion. For the fix,
- Cache is added for directoryTable and fileTable marking the key is deleted
- in directoryDeletetingService, applicable list to delete directory / files are obtained with check from cache if deleted
https://issues.apache.org/jira/browse/HDDS-11215
- Integration test covering scenario (reproduced without fix)
> HDDS-11215. Quota count can go wrong when double buffer flush takes time

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneBucket.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
- hadoop-ozone/dist/src/main/smoketest/s3/MultipartUpload.robot
- hadoop-ozone/dist/src/main/smoketest/s3/objectcopy.robot
- hadoop-ozone/dist/src/main/smoketest/s3/objectputget.robot
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientAbstract.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3InitiateMultipartUploadRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3InitiateMultipartUploadRequestWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/OMRequestTestUtils.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3InitiateMultipartUploadRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3InitiateMultipartUploadRequestWithFSO.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/multipart/TestS3MultipartUploadCompleteRequest.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/EndpointBase.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/util/S3Consts.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/ClientProtocolStub.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneBucketStub.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestMultipartUploadComplete.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectPut.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestPermissionCheck.java
Following this discussion https://github.com/apache/ozone/discussions/6639, we need to backport some improvements for custom metadata feature completeness:
- HDDS-10645. Support x-amz-metadata-directive in CopyObject
- HDDS-10653. Support custom metadata for MPU key
https://github.com/ivandika3/ozone/actions/runs/8978867164
> [DO NOT MERGE] Backport custom metadata improvements from `master` to `ozone-1.4`

- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/AccessHeatMapEndpoint.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/HealthCheckResponse.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/heatmap/HeatMapServiceImpl.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/heatmap/IHeatMapProvider.java
This PR change is only to refactor heatmap code to have better readability and maintainability.
https://issues.apache.org/jira/browse/HDDS-11228
Patch tested manually.
> HDDS-11228. Ozone Recon HeatMap refactoring of code.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChunkBufferImplWithByteBufferList.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/common/TestChunkBufferImplWithByteBufferList.java
HDDS-11223. Fix iteration over ChunkBufferImplWithByteBufferList
`ChunkBufferImplWithByteBufferList.iterate()` is broken and returns the result that violates the contract of `ChunkBuffer.iterate()`. 
As a result, with `hdds.datanode.chunk.data.validation.check=true` it's not possible to put anything into an EC bucket (see details in JIRA).
https://issues.apache.org/jira/browse/HDDS-11223
Added new unit tests.
> HDDS-11223. Fix iteration over ChunkBufferImplWithByteBufferList

- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java
A few internal calls as part of FileSystem client delete involve repeated computation of getBucket(). Instead, we may precompute the OzoneBucket object and then pass it onto other dependent calls as they again compute the same object internally.
https://issues.apache.org/jira/browse/HDDS-11238
Existing unit and integration tests should cover the changes
> HDDS-11238. Converge redundant getBucket calls for FileSystem client delete

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeManagerMXBean.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java
- hadoop-hdds/server-scm/src/main/resources/webapps/scm/scm-overview.html
- hadoop-hdds/server-scm/src/main/resources/webapps/scm/scm.js
For SCM, it is very useful to count the min, max, median, and stdev of node storage.
After adding the patch:
jmx:
ui:
https://issues.apache.org/jira/browse/HDDS-11206
It is necessary to ensure that jmx can display NodeStatics correctly.
It is necessary to ensure that the UI can display Statistical correctly.
> HDDS-11206. Statistics storage usage indicators include min, max, median, stdev

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/StringUtils.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/SignalLogger.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java
- hadoop-hdds/framework/pom.xml
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManagerStarter.java
- hadoop-ozone/csi/pom.xml
- hadoop-ozone/csi/src/main/java/org/apache/hadoop/ozone/csi/CsiServer.java
- hadoop-ozone/dist/src/main/license/bin/LICENSE.txt
- hadoop-ozone/dist/src/main/license/jar-report.txt
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManagerStarter.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServer.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/Gateway.java
- pom.xml
Revert HDDS-11076 and HDDS-11078.
HDDS-11078 causes loss of signal handling functionality.  In addition to Ozone-side fix, it also requires a fix in (and new release of) `jnr-posix`, thus we must revert the change for now.
HDDS-11076 requires HDDS-11078 (does not compile on Java 9+ with usage of `sun.misc.Signal`), so we must revert these two together.
CI:
https://github.com/adoroszlai/ozone/actions/runs/10148894587
> HDDS-11076. Revert HDDS-11076 and HDDS-11078

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmMetadataManager.java
Similar to [HDDS-7764](https://issues.apache.org/jira/browse/HDDS-7764), we need to update this to prevent expired multipart upload being cleaned up prematurely.
https://issues.apache.org/jira/browse/HDDS-11221
Update existing unit tests.
> HDDS-11221. Resolve potential time discrepancy for expired multipart upload cleanup

- hadoop-ozone/dist/src/shell/ozone/ozone
- hadoop-ozone/dist/src/shell/ozone/ozone-functions.sh
[HDDS-10382](https://issues.apache.org/jira/browse/HDDS-10382) introduced Java-version specific logic for Netty, we will move the setting of `NETTY_OPTS` to the `ozone_java_setup` function in hadoop-ozone/dist/src/shell/ozone/ozone-functions.sh.
This will centralize the configuration and ensure compatibility with the existing `RATIS_OPTS` settings.
https://issues.apache.org/jira/browse/HDDS-11236
Tested the patch locally on a docker cluster.
```
recon-1     | DEBUG: Final OZONE_OPTS: -Djava.net.preferIPv4Stack=true  -Dorg.apache.ratis.thirdparty.io.netty.allocator.useCacheForAllThreads=false -Dorg.apache.ratis.thirdparty.io.netty.tryReflectionSetAccessible=true   --add-opens java.management/com.sun.jmx.mbeanserver=ALL-UNNAMED --add-exports …
```
> HDDS-11236. Move Java version-specific NETTY_OPTS to ozone-functions.sh

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/audit/OMAction.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/tenant/OMTenantDeleteRequest.java
removal of duplicate audit logging of UPDATE_VOLUME for delete tenant case. Already DELETE_TENANT audit log is present.
https://issues.apache.org/jira/browse/HDDS-11119
- existing test cases for impact
> HDDS-11119. Unnecessary UPDATE_VOLUME audit entry for DELETE_TENANT

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconInsightsForDeletedDirectories.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/OzoneManagerServiceProviderImpl.java
This PR change is to improve Recon starts and restarts more gracefully in case of failures during start or restart. Ozone Recon component has few paths where exception handling needs improvement in order to avoid abrupt crash and shutdown of Recon.
https://issues.apache.org/jira/browse/HDDS-11231
Patch is tested manually and with existing test cases.
> HDDS-11231. Make Recon start more resilient

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotBackgroundServices.java
- hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SstFilteringService.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotPurgeResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/SnapshotDeletingService.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestSnapshotDeletingService.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSstFilteringService.java
SstFiltering service directly updates the snapshotInfo and doesn't go through DoubleBufferFlush to update the DB. This interferes with SnapshotInfo updated during SnapshotPurgeRequest.
Consider the case:
S1 <- S2(SstFiltered) <- S3 (Sst unfiltered)
At T1 if S2 is purged and submitted to OM ratis but it hasn't been flushed to the rocksDb but just present in the cache which makes the chain.
S1 <- S3 (Sst Unfiltered in cache)
S2(SstFiltered, deleted in Cache but present in table)
Suppose at T2 SstFiltering service runs on the chain and marks S3 to be SstFiltered which would be directly flushed to DB
S1 <- S3 (Sst filtered in DB)
S1 <- S2 (Present in DB but not present in cache)
Now if the OM is restarted, snapshot chain would have gotten corrupted since both S2 & S3 are pointing S1 in the …
> HDDS-11068. Move SstFiltered flag to a file in the snapshot directory

- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancerDatanodeNodeLimit.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancerTask.java
In [PR for HDDS-9889](https://github.com/apache/ozone/pull/5758) we [discussed](https://github.com/apache/ozone/pull/5758#pullrequestreview-1963251436) with [Siddhant Sangwan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siddhant) that tests form `org.apache.hadoop.hdds.scm.container.balancer.TestContainerBalancerTask` could be refactored using `MockedSCM` class (introduced in [HDDS-9889](https://issues.apache.org/jira/browse/HDDS-9889))
Some work has been already done in:
1. https://github.com/apache/ozone/pull/5758
2. https://github.com/apache/ozone/pull/6537
1. Refactor some tests from `org.apache.hadoop.hdds.scm.container.balancer.TestContainerBalancerTask` 
https://issues.apache.org/jira/browse/HDDS-10917
Use standalone tests
> HDDS-10917. Refactoring more tests from TestContainerBalancerTask

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMRecoverLeaseRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/upgrade/OMLayoutFeature.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
HDDS-11258. [hsync] Add new OM layout version.
Add a new OM layout version HBASE_SUPPORT in Ozone 1.5.0 to prevent any misuse of the APIs (hsync, recoverLease, listOpenFiles) until upgrade finalizes.
https://issues.apache.org/jira/browse/HDDS-11258
Unit tests covering OM upgrade code path.
> HDDS-11258. [hsync] Add new OM layout version.

- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/cache/FullTableCache.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/cache/TestTableCache.java
FullTable Cache eviction is used for cleanup entry in cache if its value is null and same is persisted in DB. Current logic keeps and iterate all epoch for updatation.
As Optimization having logic refactor:
- keep epochEntries only for case where key is deleted (i.e. value is null as marked for deletion)
- lock is put is required to be readonly, as protection is required while cleanup of cache entry (which is not threadsafe) wrt put logic. Its safe to have parallel put.
`1. Cleanup Policy Never uses ConcurrentSkipListMap, and its computeIfPresent is not atomic, so there can be a race condition between cleanup and requests adding to cache. (This might cause cleaning up entries which are not flushed to DB, and this can cause correctness issue)
`
Reference: …
> HDDS-11201. optimize fulltable cache eviction, scheduler and lock

- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneManagerVersion.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
- hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/ClientProtocolStub.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/ListOpenFilesSubCommand.java
HDDS-11260. [hsync] Add Ozone Manager protocol version
Add a new Ozone Manager layout version HBASE_SUPPORT and prevent clients to submit HBase related requests (hsync, listOpenFiles, recoverLease) to OM if OM isn't upgraded yet.
https://issues.apache.org/jira/browse/HDDS-11260
> HDDS-11260. [hsync] Add Ozone Manager protocol version

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ratis/conf/RatisClientConfig.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ratis/retrypolicy/RequestTypeDependentRetryPolicyCreator.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/ratis/conf/TestRatisClientConfig.java
Default max retries count is very high for ExponentialBackoffPolicy which in some cases leads to longer wait for client. Client like HBase by default timesout after 5 minutes which leads to unexpected crash. 
In this PR making retry count as configurable so that after max retry client can try on different DN and doesn't need to wait for long.
https://issues.apache.org/jira/browse/HDDS-11226
Updated existing test
> HDDS-11226. Make ExponentialBackoffPolicy maxRetries configurable

- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBStoreBuilder.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDBConfiguration.java
By default, RocksDB keeps a single log file for application logs ([Logger](https://github.com/facebook/rocksdb/wiki/Logger) and [default values](https://github.com/facebook/rocksdb/blob/main/include/rocksdb/options.h#L864)). It can eat up a lot of disk space under heavy load as mentioned in the  HDDS-11214 if logs files are not rolled over and kept to a certain number.
This change provides an option to set the maximum log file size and number of log files for RocksDB.  It will enable the auto roll logging and keep the log size to the limited value.
HDDS-11214
> HDDS-11214. Added config to set rocksDB's max log file size and num of log files

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/impl/TestBlockManagerImpl.java
- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestBlockOutputStreamIncrementalPutBlock.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
HDDS-11259. [hsync] DataNode should verify HBASE_SUPPORT layout version for every PutBlock.
The layout version check for incremental chunk list support is performed at DataNode startup only, which means that DataNode would reject any such clients until the next restart after finalization.
The check should be moved later inside PutBlocks handling.
https://issues.apache.org/jira/browse/HDDS-11259
> HDDS-11259. [hsync] DataNode should verify HBASE_SUPPORT layout version for every PutBlock.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsConfigKeys.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
[HDDS-11224](https://issues.apache.org/jira/browse/HDDS-11224). Increase hdds.datanode.handler.count
hdds.datanode.handler.count is default to 1. This property defines the number of DataNode RPC handlers. Increasing to 10 improves DN Echo throughput
https://issues.apache.org/jira/browse/HDDS-11224
Just change a configuration property value. No new tests.
The change was applied to a cluster and then benchmarked the throughput change using
`ozone freon dne --clients=32 -t 32 -n 1000000 --sleep-time-ms=0 --ratis --payload-req=0 --container-id=1 `
> HDDS-11224. Increase hdds.datanode.handler.count

- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
[HDDS-11225](https://issues.apache.org/jira/browse/HDDS-11225). Increase ipc.server.read.threadpool.size
Add a new configuration property ozone.om.read.threadpool which defaults to 10. It sets number of reader thread pool size for OM, essentially overrides Hadoop's ipc.server.read.threadpool.size default.
https://issues.apache.org/jira/browse/HDDS-11225
No functional change. Existing unit tests covers it all.
> HDDS-11225. Increase ipc.server.read.threadpool.size

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
In BasicRootedOzoneFileSystem#mkdir() method we use getBucket in all circumstances, as that call is also used to create the bucket if it does not exists.
However, this results in a GetBucketInfo RPC call every time, even when the bucket exists, and we create a key with this call. In this latter case we should not call getBucket() but use the RPCClient (ClientProtocol) directly using the bucket name to create the directory.
In order to achieve functional parity with the old approach, I have extracted the logic that handles non existent volumes and buckets in the getBucket() call, and in createDirectory I am changing the getBucket call also to directly call getBucketInfo if keyStr is not present.
The RpcClient#createDirectory change is to ensure verification of the volume and bucket name …
> HDDS-11235. Spare InfoBucket RPC call in FileSystem#mkdir() call.

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/AbstractCommitWatcher.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStream.java
TestBlockOutputStream.testWriteMoreThanFlushSize is flaky after HDDS-9844 fix.
It is due to addAckDataLength is not kept as thread safe which is causing wrong totalAckDataLength.
In this PR we are adding synchronized in AbstractCommitWatcher.addAckDataLength to make thread safe.
https://issues.apache.org/jira/browse/HDDS-11280
Verified in 10X10 run and it is green after the fix
https://github.com/ashishkumar50/ozone/actions/runs/10244918136/workflow
> HDDS-11280. Add Synchronize in AbstractCommitWatcher.addAckDataLength

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ratis/RatisHelper.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/util/MutableMinMax.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/protocol/SecretKeyProtocolDatanode.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/protocolPB/SecretKeyProtocolDatanodePB.java
- hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/compaction/log/CompactionFileInfo.java
- hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/compaction/log/CompactionLogEntry.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeDecommissionManager.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneFsDelete.java
- pom.xml
* Replace accidental usage of Hadoop's annotations and config keys.
* Add import restrictions to avoid similar future problems.
https://issues.apache.org/jira/browse/HDDS-11274
Tested import restrictions by trying to compile with only the POM change:
```
[ERROR] Rule 2: org.apache.maven.plugins.enforcer.RestrictImports failed with message:
[ERROR] 
[ERROR] Banned imports detected:
[ERROR] 
[ERROR] Reason: Use Ozone's version of the same class
[ERROR] 	in hadoop-hdds/common/src/main/java/org/apache/hadoop/util/MutableMinMax.java
[ERROR] 		org.apache.hadoop.classification.InterfaceAudience  	(Line: 20, Matched by: org.apache.hadoop.classification.InterfaceAudience)
[ERROR] 		org.apache.hadoop.classification.InterfaceStability 	(Line: 21, Matched by: …
```
> HDDS-11274. Replace Hadoop annotations/configs with Ozone-specific ones

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeInfo.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeStateManager.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java
- hadoop-hdds/server-scm/src/main/resources/webapps/scm/scm-overview.html
- hadoop-hdds/server-scm/src/main/resources/webapps/scm/scm.js
In Ozone, there is no statistical node status information, such as healthy nodes, dead nodes, decommissioning nodes, etc. The purpose of this PR is to improve these.
After adding this PR, jmx and UI will be updated.
New jmx:
New ui:
https://issues.apache.org/jira/browse/HDDS-11272
You need to ensure that JMX displays normally.
You need to ensure that the UI displays normally.
> HDDS-11272. Statistics some node status information

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/container/ContainerTestHelper.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeStoreWithIncrementalChunkList.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/impl/TestBlockManagerImpl.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/upgrade/TestDatanodeUpgradeToHBaseSupport.java
- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/MockDatanodeStorage.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestFinalizeBlock.java
HDDS-11270. [hsync] Add DN layout version (HBASE_SUPPORT/version 8) upgrade test.
This is a test-only PR built on top of HDDS-11259.
Add a test class TestDatanodeUpgradeToHBaseSupport which has two test cases
* PutBlock request with incremental chunk list
* Block finalization request 
These two requests are rejected before upgrade finalizes and accepted after upgrade.
https://issues.apache.org/jira/browse/HDDS-11270
Test only code
> HDDS-11270. [hsync] Add DN layout version (HBASE_SUPPORT/version 8) upgrade test.

- hadoop-ozone/dist/pom.xml
Bump `ozone-runner` to latest `20240729-jdk17-1`, which reduces image size.
https://issues.apache.org/jira/browse/HDDS-11249
CI:
https://github.com/adoroszlai/ozone/actions/runs/10146353761
> HDDS-11249. Bump ozone-runner to 20240729-jdk17-1

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/GrpcReplicationClient.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/InterSCMGrpcClient.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/GrpcOmTransport.java
- hadoop-ozone/integration-test/pom.xml
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/FollowerAppendLogEntryGenerator.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/LeaderAppendLogEntryGenerator.java
GRPC uses HTTP internally for its connections and due to this, if http proxy is configured for any Ozone process using grpc , it directs each call through the proxy even for grpc which is not [desirable](https://github.com/apache/ratis-thirdparty/pull/53#issuecomment-2262233350) for performance. Hence disabling proxy for grpc connections that ozone uses.
This has been fixed in RATIS via RATIS-2133. For the complete fix we need to update Ozone's ratis version to one which has the fix but that would happen whenever the next ratis update happens.
https://issues.apache.org/jira/browse/HDDS-11257
Since current Ratis version in Ozone does not have the fix, used the flaky test check with custom ratis commit to point to latest commits in apache/ratis
Tested a unit test with this [commit …
> HDDS-11257. Ozone write does not work when http proxy is set for the JVM.

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingTask.java
In this pull request, a fix was implemented to address an issue where datanodes reported negative container sizes due to duplicate block deletion requests. The root cause was identified as multiple deletion requests being sent for the same blocks, leading to incorrect updates in container metrics. The solution involved improving the block deletion logic by tracking already-deleted blocks and ignoring duplicate deletion attempts. This ensures that the container's used bytes and block count metrics remain accurate, preventing negative values. 
https://issues.apache.org/jira/browse/HDDS-11267
Manually Tested
> HDDS-11267. Datanode Reporting Negative values for Container UsedBytes and BlockCount

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/CertificateClient.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/utils/CertificateSignRequest.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DNCertificateClient.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/DefaultCertificateClient.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/client/SCMCertificateClient.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/authority/TestDefaultCAServer.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/authority/TestDefaultProfile.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/CertificateClientTestImpl.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/client/TestDefaultCertificateClient.java
- hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/security/x509/certificate/utils/TestCertificateSignRequest.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/security/RootCARotationManager.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecureOzoneCluster.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/OMCertificateClient.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/security/ReconCertificateClient.java
Within CertificateClient implementations, we use the CertificateSignRequest class to configure a BouncyCastle PKCS10CertificationRequest object. To remove this dependency, we should use our own CertificateSignRequest class throughout the whole client side, then transform it to a PEM encoded String and transfer it as is to the server side.
This way, the conversion itself can be moved later on to the crypto module, and then we can let implementors implement the conversion to a string based representation separatly, and use that from our CertificateSignRequest object later on dynamically.
This PR fully removes the usage of the BouncyCastle classes from the CertificateClient, and changes the related tests and business logic to use CertificateSignRequest instead.
Note:
On the server side, the …
> HDDS-11028. Replace PKCS10CertificationRequest usage in CertificateClient

- hadoop-hdds/docs/content/interface/ReconApi.md
The `ReconApi.md` file is missing the GET `/api/v1/utilization/containerCount` endpoint that is present in the Swagger documentation. This endpoint should be added to the ReconApi.md file to provide a complete reference for Ozone users:
`GET /api/v1/utilization/containerCount`: Returns container counts within the specified container size.
Action Items:
- Update the ReconApi.md file to include this endpoint.
- Ensure that the endpoint is fully documented, including the description, parameters, and example responses.
https://issues.apache.org/jira/browse/HDDS-11301
Built the project locally, and started ozone on docker setup and verified the docs :- 
The added doc changes are present on the following URL :- 
```
http://localhost:54553/docs/interface/reconapi.html
```
> HDDS-11301. Add Missing Utilization Endpoint in ReconApi.md for Ozone Recon Documentation.

- hadoop-ozone/dist/src/main/smoketest/basic/ozone-shell-lib.robot
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
Added tests for quota level boundary conditions
Tests added -
1. `hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java` - `testShQuota`
2. `hadoop-ozone/dist/src/main/smoketest/basic/ozone-shell-lib.robot` - `Test ozone shell errors`
https://issues.apache.org/jira/browse/HDDS-11288
```
mvn -l testlog.out -Dtest=TestOzoneShellHA#testShQuota test
[INFO] Running org.apache.hadoop.ozone.shell.TestOzoneShellHA
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 66.925 s - in org.apache.hadoop.ozone.shell.TestOzoneShellHA
[INFO]
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: …
```
> HDDS-11288. Add tests for quota level boundary conditions

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java
- hadoop-hdds/server-scm/src/main/resources/webapps/scm/scm-overview.html
- hadoop-hdds/server-scm/src/main/resources/webapps/scm/scm.js
In SCM, there are no statistics related to storage space, such as Capacity, Scmused, remaining, NonScmused. These indicators are very useful, and the purpose of this PR is to improve them.
Below is the effect after adding this patch.
jmx:
ui:
https://issues.apache.org/jira/browse/HDDS-11252
You need to ensure that JMX is displayed correctly.
You need to ensure that the UI is displayed correctly.
> HDDS-11252. Statistics of some storage space indicators

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/ChunkUtils.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/helpers/TestChunkUtils.java
The user repeatedly reads the same block, and I observed that the access time for the read chunk is too slow, which is caused by spin lock in processFileExclusive in ChunkUtils. I added the corresponding slow request log to see this issue.
see detail:  https://issues.apache.org/jira/browse/HDDS-11281
https://issues.apache.org/jira/browse/HDDS-11281
org.apache.hadoop.ozone.container.keyvalue.helpers.TestChunkUtils#concurrentReadWriteOfSameFile
> HDDS-11281. Optimize the lock of ReadChunk

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/ContainerTestUtils.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/TestCSMMetrics.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainerWithTLS.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestSecureOzoneContainer.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/server/TestContainerServer.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/server/TestSecureContainerServer.java
Currently, when RatisServer is down(mainly due to long GC which exceeds the ratis close threshold), Datanode is still running and in HEALTHY and IN_SERVICE state, which is confusing.
This tasks will shutdown the Datanode after RatisServer is down.
https://issues.apache.org/jira/browse/HDDS-10749
Manual test
> HDDS-10749. Shutdown datanode when RatisServer is down

- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestScmClient.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestKeyDeletingService.java
- pom.xml
`commons-lang` v2 is a transitive dependency via Hadoop and Ranger.  Ozone and most of its other dependencies use `commons-lang` v3.
The goal of this PR:
- Replace existing usage of `commons-lang` v2 with v3.
- Ban import of v2 classes to avoid new usage.
https://issues.apache.org/jira/browse/HDDS-11305
Tested `pom.xml` change without import changes on `master`:
```
[ERROR] Rule 6: org.apache.maven.plugins.enforcer.RestrictImports failed with message:
[ERROR] 
[ERROR] Banned imports detected in TEST code:
[ERROR] 
[ERROR] Reason: Use commons-lang v3
[ERROR] 	in hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestScmClient.java
[ERROR] 		static org.apache.commons.lang.RandomStringUtils.randomAlphabetic 	(Line: 46, Matched by: org.apache.commons.lang.**)
[ERROR] 	in …
```
> HDDS-11305. Avoid accidental usage of commons-lang v2

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsConfigKeys.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeClientProtocolServer.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMBlockProtocolServer.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeProtocolServer.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMSecurityProtocolServer.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java
Introduce newer Ozone wrapper configurations for increasing the `ipc.server.read.threadpool.size` from the default value of **1** to **10** for both SCM and Datanode RPC Servers.
https://issues.apache.org/jira/browse/HDDS-11302
Existing unit and integration tests should cover the changes (no functional change).
> HDDS-11302. Wrapper configurations to increase ipc.server.read.threadpool.size for SCM and Datanode

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSyncUpgrade.java
HDDS-11292. [hsync] Move HBASE_SUPPORT layout upgrade test into its own test.
* Test only change
* Refactor the layout upgrade test into its own test class, so that each TestHsync test case is isolated.
https://issues.apache.org/jira/browse/HDDS-11292
Test only change
> HDDS-11292. [hsync] Move HBASE_SUPPORT layout upgrade test into its own test.

- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/ScmTestMock.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/upgrade/TestDatanodeUpgradeToHBaseSupport.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/upgrade/TestDatanodeUpgradeToSchemaV3.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/upgrade/TestDatanodeUpgradeToScmHA.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/upgrade/UpgradeTestHelper.java
TestDatanodeUpgradeToScmHA was the first unit test for handling of a specific datanode layout version. It works by starting just the minimal [SCM RPC server](https://github.com/apache/ozone/blob/6ed1e58dd598e4dbc8948e1c23ae67dd1e55104c/hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/upgrade/TestDatanodeUpgradeToScmHA.java#L561) and running datanodes without their [heartbeat thread](https://github.com/apache/ozone/blob/0c47b0f3bfaf39f1625295a2631c21276c48b9f8/hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java#L331). This allows most fo the functionality that would be present in a MiniOzoneCluster integration test but runs at the speed of a unit test.
The framework has since been adopted …
> HDDS-11282. Combine test setup for datanode upgrade unit tests

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotPurgeRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotSetPropertyRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotPurgeResponse.java
In [HDDS-10590](https://issues.apache.org/jira/browse/HDDS-10590), we introduce the locks to achieve synchronization among snapshot purge, set snapshot property, and SSTFilteringService because SSTFilteringService was directly updating the snapshotInfo table and might be causing the snapshot chain corruption.
In [HDDS-11068](https://issues.apache.org/jira/browse/HDDS-11068), we found that the snapshot chain corruption issue still exists even after the locks. And the actual reason is that SSTFilteringService directly updates the DB and persists it. More details in [HDDS-11068](https://issues.apache.org/jira/browse/HDDS-11068).
In a fix #6965 for HDDS-11068, we removed the logic to persist `sstFiltered` flag in `snapshotInfoTable`. Now we create a touch file in snapshot dir which is local …
> HDDS-11137. Removed locks from SnapshotPurge and SnapshotSetProperty APIs.

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/OzoneClientConfig.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStreamSemaphore.java
- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/io/TestKeyOutputStream.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
Since HDDS-9844, writes on a single key are allowed to be interleaved outside the critical section. This PR aims to add a config to be able to restore the strictly serialized behavior before HDDS-9844 was merged as a safety measure.
```
ozone.client.key.write.concurrency
Maximum concurrent writes allowed on each key.
Defaults to 1 which matches the behavior before HDDS-9844.
For unlimited write concurrency, set this to -1 or any negative integer value.
```
https://issues.apache.org/jira/browse/HDDS-11184
- Added UT
> HDDS-11184. [hsync] Add a client config to limit write concurrency on the same key

- hadoop-ozone/client/pom.xml
- hadoop-ozone/common/pom.xml
- hadoop-ozone/csi/pom.xml
- hadoop-ozone/httpfsgateway/pom.xml
- hadoop-ozone/insight/pom.xml
- hadoop-ozone/integration-test/pom.xml
- hadoop-ozone/interface-client/pom.xml
- hadoop-ozone/interface-storage/pom.xml
- hadoop-ozone/ozone-manager/pom.xml
- hadoop-ozone/ozonefs-common/pom.xml
- hadoop-ozone/ozonefs/pom.xml
- hadoop-ozone/pom.xml
- hadoop-ozone/recon-codegen/pom.xml
- hadoop-ozone/recon/pom.xml
- hadoop-ozone/s3-secret-store/pom.xml
- hadoop-ozone/s3gateway/pom.xml
- hadoop-ozone/tools/pom.xml
- pom.xml
Similar to #7029, for `hadoop-ozone` instead of `hadoop-hdds`.
Add direct dependency for modules used in `hadoop-ozone`, instead of relying on transitive dependencies for the same.  (Except "test-only" modules `integration-test` and `mini-chaos-test`, to avoid too big patch.)
This should get rid of most items under `Used undeclared dependencies` part of dependency analysis.
Exceptions:
- Test dependencies declared in `hdds-test-utils` and `hdds-hadoop-dependency-test` for convenience.
- Hadoop dependencies declared in `hdds-hadoop-dependency-client` and `hdds-hadoop-dependency-server` for convenience.
- `commons-lang` (v2) not added, because it will be replaced with v3 (HDDS-11305).
https://issues.apache.org/jira/browse/HDDS-11279
Compared output of `mvn dependency:analyze` before/after …
> HDDS-11279. Add direct dependencies in hadoop-ozone

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/conf/RatisConfUtils.java
- hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/conf/TestRatisConfUtils.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/RatisUtil.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerRatisServer.java
Due to a bug, [RATIS-2135](https://issues.apache.org/jira/browse/RATIS-2135) requires
- raft.grpc.message.size.max
to be 1MB larger than
- raft.server.log.appender.buffer.byte-limit
We must change the OM, SCM and Datanode conf accordingly.
HDDS-11320
A new unit test.
> HDDS-11320. Update OM, SCM, Datanode conf for RATIS-2135.

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientRatis.java
I changed the log level from info to debug in XceiverClientRatis.java to this log message:
`"WatchType {}. Majority {}, ", this.watchType, this.majority)`
https://issues.apache.org/jira/browse/HDDS-11319
Trivial change
> HDDS-11319. Reduce XceiverClientRatis info log to debug

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/EndpointStateMachine.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocolPB/StorageContainerDatanodeProtocolClientSideTranslatorPB.java
EndpointStateMachine.EndPointStates.value is redundant since Java enum already has ordinal().
HDDS-11310
> HDDS-11310. Remove EndpointStateMachine.EndPointStates.value.

- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java
- hadoop-hdds/common/src/main/resources/ozone-default.xml
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
`ozone.fs.hsync.enabled` was initially added in HDDS-8302 with default value of `false`. The config is used to control whether the hsync feature (implemented for HBase support for the most part) would be enabled on both OM side and client side.
But the default was later flipped to `true` in HDDS-10252. We need to:
1. Switch the default back to `false`
2. Ensure this doesn't break any existing tests et al..
https://issues.apache.org/jira/browse/HDDS-11327
- Existing tests should all pass.
> HDDS-11327. [hsync] Revert config default ozone.fs.hsync.enabled to false

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/ozone/audit/AuditLogger.java
1. fixed the negative latency value
2. improve the WRITE_CHUNK audit log, added "offset" and "stage" information. 
https://issues.apache.org/jira/browse/HDDS-11324
Manual test, before the patch 
```
2024-08-19 14:25:20,150 | INFO  | DNAudit | user=null | ip=null | op=WRITE_CHUNK {blockData=conID: 3 locID: 113750153625600003 bcsId: 0 replicaIndex: 0, blockDataSize=4194304} | ret=null | perf={preOpLatencyMs=-533452451886676, opLatencyMs=7012417} |
2024-08-19 14:25:20,153 | INFO  | DNAudit | user=null | ip=null | op=WRITE_CHUNK {blockData=conID: 3 locID: 113750153625600003 bcsId: 0 replicaIndex: 0, blockDataSize=4194304} | ret=null | perf={preOpLatencyMs=-533452460253757, opLatencyMs=1874458} |
2024-08-19 14:25:20,157 | INFO  | DNAudit | user=null | ip=null | op=WRITE_CHUNK {blockData=conID: …
```
> HDDS-11324. Negative value preOpLatencyMs in DN audit log

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ECBlockOutputStream.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/RatisBlockOutputStream.java
- hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestBlockOutputStreamCorrectness.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntry.java
Currently, for every client side buffer flush size(32MB default), there will be a putBlock call to DN to persist the block metadata.  For a 128MB block, there will be 4 putBlock calls during the data write, and one extra putBlock at the end when this block is closed due to full.  This last putBlock will add the flag "eof" in the request to indicate that this block is completed. 
This task aims to remove this last putBlock call in case this block is a full block when block close is called. 
https://issues.apache.org/jira/browse/HDDS-11340
Existing test cases, plus manual audit log verification. Before the patch, here are the audit logs, the block size 32MB. 
```
2024-08-19 21:29:26,396 | INFO  | DNAudit | user=null | ip=null | op=WRITE_CHUNK {blockData=conID: 2001 locID: 113750153625602004 …
```
> HDDS-11340. Avoid extra PubBlock call when a full block is closed

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStream.java
HDDS-11325. Intermittent failure in TestBlockOutputStreamWithFailures#testContainerClose
The assertion assumes the buffer pool is allocated 4 buffers.
After [HDDS-9844](https://issues.apache.org/jira/browse/HDDS-9844), the block output stream buffer allocation becomes asynchronous and it's possible to allocate fewer buffers than before, because some response already come back and the associated buffer can be reused.
https://issues.apache.org/jira/browse/HDDS-11325
Unit test change only.
> HDDS-11325. Intermittent failure in TestBlockOutputStreamWithFailures#testContainerClose

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/AbstractTestECKeyOutputStream.java
`ECKeyOutputStream` extends `KeyOutputStream`, but Ozone EC does not support `hsync` (at least for now since it is not implemented) as there are known issues with that, such as HDDS-8932.
This jira prevents `hsync()` and `hflush()` from being called on `ECKeyOutputStream` by throwing `NotImplementedException`.
https://issues.apache.org/jira/browse/HDDS-11322
- Added test case to make sure that invocation of `hsync()` and `hflush()` on `ECKeyOutputStream` throws exception.
> HDDS-11322. [hsync] Block ECKeyOutputStream from calling hsync and hflush

- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBStore.java
- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java
- hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/OMQuotaRepairRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/volume/OMQuotaRepairResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/QuotaRepairTask.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/upgrade/QuotaRepairUpgradeAction.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestQuotaRepairTask.java
Changes:
1. refactor quota repair for running non-blocking
- DB checkpoint is created before starting quota usages calculation
- Diff quota usages is identified from checkpoint with original and new quota
- For diff, quota update is send via ratis to correct quota usages
- Status is added to be integrated for last run with CLI
2. while upgrade case, change handling as non-blocking
- quota repair trigger on FiNALIZE trigger for upgrade (as ratis dependency, its initialized during this phase only)
- Just trigger, but actual run will happen async
The target for this refactor is to `integrate with tool CLI` option to trigger again and verify for correctness. This is tracked with `Parent ID:` [HDDS-8824](https://issues.apache.org/jira/browse/HDDS-8824) …
> HDDS-11284. refactor quota repair non-blocking while upgrade

- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/recovery/ReconOmMetadataManagerImpl.java
HDDS-11349. Add NullPointer handling when volume/bucket tables are not initialized
* Currently if we call the /volumes API while the Volumes table is being initialized it returns a 500 error.
* This PR will add the handling of this scenario
* After this change, if we call `/volumes` or `/buckets` endpoint before the table is completely initialized, it will return
```
{
totalCount: 0,
volumes: []
}
```
```
{
buckets: []
totalCount: 0
}
```
https://issues.apache.org/jira/browse/HDDS-11349
It was tested using unit tests and also manually verifying the response is properly returned.
> HDDS-11349. Add NullPointer handling when volume/bucket tables are not initialized

- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java
Correct the prompt Ozone CLI gives when trying to recursively delete an Ozone volume.
HDDS-10716 fixed it partially by removing the invalid `-skipTrash` option but didn't fix the `-id` part.
See the JIRA description for more details.
https://issues.apache.org/jira/browse/HDDS-11346
- Verified manually.
> HDDS-11346. FS CLI gives incorrect recursive volume deletion prompt

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/StateContext.java
In some cases, Datanodes were unable to report to the SCM for a long time due to StateContext#pipelineActions being stuck. This PR is intended to try to fix this.
https://issues.apache.org/jira/browse/HDDS-11331
Need to ensure CI execution is successful.
> HDDS-11331. Fix Datanode unable to report for a long time

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/ErrorInjector.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientCreator.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientManager.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientRatis.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntry.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockOutputStreamEntryPool.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockOutputStreamEntryPool.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/ECKeyOutputStream.java
- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java
- hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/io/TestKeyOutputStream.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
When a block (or `BlockOutputStream`, I'll use them interchangeably in this description) becomes faulty (any exception happens when sending requests to the pipeline), `KeyOutputStream` will allocate a new Block (as the current block), and hand off all pending changes in the `BufferPool` to the current block. This is done by `KeyOutputStream`'s `handleException`.
Two essential changes are needed when allowing KeyOutputStream to be used by multiple threads concurrently.
1. When hsync is called concurrently, `handleException` can be called multiple times for a given block. This is different from when `KeyOutputStream` is fully synchronized.  The second `handleException` on a block call will see the block has been closed already and some assertion that is true in full synchronization is no …
> HDDS-11239. Fix KeyOutputStream's exception handling when calling hsync concurrently

- hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Datanode Chunk Read_Write Dashboard.json
- hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - CreateKey Metrics.json
Change-Id: I187a3f0b61ebd3e6ce7c36464052d3dd2e2a2d8b
Add additional metrics to create key dashboard to track total data committed, number of key commits executed.
Minor fixes to legends for Chunk Dashboard. Workaround issue https://github.com/grafana/grafana/issues/44251
Also, default to prometheus configured instead of parameterizing the source which gives errors on import.
https://issues.apache.org/jira/browse/HDDS-11316
Deployed locally.
> HDDS-11316. Improve Create Key and Chunk IO Dashboards

- hadoop-ozone/dist/src/main/compose/upgrade/test.sh
- hadoop-ozone/dist/src/main/compose/xcompat/test.sh
Replace hard-coded version number for current in upgrade and xcompat tests.
Only run EC compatibility test for current version.  Previously it was executed twice, once for both 1.3.0 and 1.4.0, but `new-cluster.yaml` ignores the version number.  EC test is to be improved in HDDS-11334 to cover multiple versions.
https://issues.apache.org/jira/browse/HDDS-11333
CI:
https://github.com/adoroszlai/ozone/actions/runs/10430533094
> HDDS-11333. Avoid hard-coded current version in upgrade/xcompat tests

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestHadoopDirTreeGenerator.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/HadoopBaseFreonGenerator.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/HadoopDirTreeGenerator.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/HadoopFsGenerator.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/HadoopFsValidator.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/HadoopNestedDirGenerator.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/HsyncGenerator.java
[HDDS-4313](https://issues.apache.org/jira/browse/HDDS-4313) uses thread-local instance of FileSystem in HadoopFsGenerator to prevent client contention due to the shared FileSystem instance. We can apply this to other FS freon tests (e.g. HadoopDirTreeGenerator)
https://issues.apache.org/jira/browse/HDDS-11081
> HDDS-11081. Use thread-local instance of FileSystem in Freon tests

- hadoop-ozone/recon-codegen/src/main/java/org/hadoop/ozone/recon/schema/ContainerSchemaDefinition.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/persistence/ContainerHealthSchemaManager.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/fsck/TestContainerHealthTask.java
During the execution of the `ContainerHealthTask`, it was discovered that the length of the `CONTAINER_STATE` column in the `UNHEALTHY_CONTAINERS` table is insufficient to store some of the enum values defined in UnHealthyContainerStates. Specifically, the `ALL_REPLICAS_UNHEALTHY` state, which has a length of 21 characters, exceeds the current `VARCHAR(16)` limit set for the `CONTAINER_STATE` column.
When attempting to insert a record with the `ALL_REPLICAS_UNHEALTHY` state into the `UNHEALTHY_CONTAINERS` table, a truncation error is thrown:
```
org.jooq.exception.DataAccessException: SQL [insert into "UNHEALTHY_CONTAINERS" ("container_id", "container_state", "in_state_since", "expected_replica_count", "actual_replica_count", "replica_delta", "reason") values ...]; A truncation error was …
```
> HDDS-11309. Increase CONTAINER_STATE Column Length in UNHEALTHY_CONTAINERS to Avoid Truncation

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/AbstractCommitWatcher.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java
- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/RatisBlockOutputStream.java
In HDDS-11174, we change XceiverClientRatis.watchForCommit to async. This JIRA is to further change RatisBlockOutputStream to use it.
HDDS-11208
> HDDS-11208. Change RatisBlockOutputStream to use HDDS-11174.

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotPurgeRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotPurgeResponse.java
Currently, we maintain two maps updatedPathPreviousAndGlobalSnapshots and updatedSnapInfos which creates an issue with batch processing because order matters. If we use one map instead of two and use that as local cache, it would solve the problem and we can still keep the batch purge operation. (More details: https://github.com/apache/ozone/pull/6491#issuecomment-2272219528)
HDDS-9198
Existing unit and integration tests.
> HDDS-9198. Maintain local cache in OMSnapshotPurgeRequest to get updated snapshotInfo and pass the same to OMSnapshotPurgeResponse

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java
- hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
This reverts commit 5a3b7986629d12b823cde7e31cc99f2db59cb6fa due to a regression reported in [HDDS-11348](https://issues.apache.org/jira/browse/HDDS-11348).
Creating directories using `fs -mkdir` should not be allowed for OBS buckets. Please refer to [HDDS-11348](https://issues.apache.org/jira/browse/HDDS-11348) for further details.
https://issues.apache.org/jira/browse/HDDS-11348
- Patch reverts a commit, existing tests should pass.
- Green CI/CD: https://github.com/tanvipenumudy/ozone/actions/runs/10572314594
> Revert "HDDS-11235. Spare InfoBucket RPC call in FileSystem#mkdir() call. (#6990)"

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/ReconstructECContainersCommand.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/protocol/commands/TestReconstructionECContainersCommands.java
Logs for EC reconstruction command lists the missing indexes as ASCII control characters like `^A ^B`.
Fix by restoring `Arrays.toString` in EC reconstruction command's `toString()`.
https://issues.apache.org/jira/browse/HDDS-11373
Added assertion in unit test.
CI:
https://github.com/adoroszlai/ozone/actions/runs/10574613444
> HDDS-11373. Log for EC reconstruction command lists the missing indexes as ASCII control characters

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStream.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockOutputStreamWithFailures.java
HDDS-11325. (addendum) Intermittent failure in TestBlockOutputStreamWithFailures#testContainerClose
1. Removed \@Flaky annotation  from TestBlockOutputStreamWithFailures#testContainerClose and TestBlockOutputStream#testWriteMoreThanMaxFlushSize
2. Relaxed the assertions in the test to match the current behavior.
3. Verified there's no longer intermittent test failures in TestBlockOutputStreamWithFailures#testContainerClose and TestBlockOutputStream#testWriteMoreThanMaxFlushSize
https://issues.apache.org/jira/browse/HDDS-11325
Flaky-test-check:
https://github.com/jojochuang/ozone/actions/runs/10532241331
TestBlockOutputStream#testWriteMoreThanMaxFlushSize[HDDS-11325-take2]-10x10 
https://github.com/jojochuang/ozone/actions/runs/10565349000 …
> HDDS-11325. (addendum) Intermittent failure in TestBlockOutputStreamWithFailures#testContainerClose

- hadoop-ozone/dist/src/main/compose/test-all.sh
- pom.xml
Fix the problem that coverage is not calculated for `org.apache.ozone` and some other packages.
https://issues.apache.org/jira/browse/HDDS-11372
Tweaked CI workflow to run `coverage` check in my fork (normally it only runs in `apache/ozone` repo).  Verified coverage > 0% for the packages affected.
> HDDS-11372. No coverage for org.apache.ozone packages

- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/package.json
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/pnpm-lock.yaml
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/vite.config.ts
Remove dependency on Babel in Vite
* Babel currently uses caniuse-lite as a transitive dependency and it cannot be included in Apache projects
* Recon is already using Vite for builds, but has Babel usage due to the plugin-react, and svgr plugins.
* This PR uses plugin-react-swc to use SWC instead of Babel for transpilation, and removed dependency on SVGR plugin as we are manually exporting SVG icons as React componets.
* There are no Babel plugins currently being used for transpilation, hence the switch from Babel to SWC is also a simple replacement
https://issues.apache.org/jira/browse/HDDS-11368
Patch was tested manually, as well as by running the initial unit tests added to verify no features are broken.
| Screenshot | Description | …
> HDDS-11368. Remove dependency on Babel in Vite

- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/conf/DatanodeRatisGrpcConfig.java
- hadoop-ozone/integration-test/src/test/resources/ozone-site.xml
HDDS-11375. DN Startup fails with "RuntimeException: Can't start the HDDS datanode plugin"
* Remove the predefined hdds.ratis.raft.grpc.message.size, because its value of 32MB is not large enough. We should simply remove it and let it be calculated as hdds.container.ratis.log.appender.queue.byte-limit + 1MB.
* Update hdds.container.ratis.log.appender.queue.byte-limit to 32MB in the integration test so that integration tests can reproduce the bug.
Note: HDDS-11320 did update hdds.ratis.raft.grpc.message.size to be hdds.container.ratis.log.appender.queue.byte-limit + 1MB, but later it got override here: https://github.com/apache/ozone/blob/master/hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/Xcei …
> HDDS-11375. DN startup fails due to illegal configuration of raft.grpc.message.size.max

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOmSnapshot.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneManagerHASnapshot.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SnapshotChainManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMDirectoriesPurgeRequestWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyPurgeRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotMoveDeletedKeysRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotPurgeRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMDirectoriesPurgeResponseWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyPurgeResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotMoveDeletedKeysResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotPurgeResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/AbstractKeyDeletingService.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/KeyDeletingService.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/SnapshotDeletingService.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/SnapshotDirectoryCleaningService.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotUtils.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyPurgeRequestAndResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDiffManager.java
Sometimes, the follower OM node may be lagging that it gets `purgeKeys` or `snapshotMoveDeletedKeys` from a Snapshot, and `purgeSnapshot` for the same Snapshot one after another.  And purgeSnapshot's validateAndUpdateCache gets executed before doubleBuffer flushes `purgeKeys`  or `snapshotMoveDeletedKeys`from that Snapshot.
This should not be a case on the leader node because SnapshotDeletingService checks that deletedTable and deletedDirectoryTable in DB don't have entries for the bucket before it sends a `purgeSnapshot` request for a snapshot.
If that happens, and we just look into the cache, the addToBatch operation fails when it tries to open the DB and purgeKeys from the Snapshot because the snapshot is already purged from the SnapshotInfoTable cache.
***PurgeKeys***:
```
2024-08-22 …
```
> HDDS-11152. OMDoubleBuffer error when handling snapshot's background operations

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java
- hadoop-ozone/dist/src/main/compose/compatibility/docker-config
- hadoop-ozone/dist/src/main/smoketest/compatibility/om.robot
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequest.java
`OzoneManagerVersion` lets client know what kind of requests OM supports.  The goal of this task is to allow disabling version-specific features in OM, even if it supports the feature according to versioning.  This is achieved by a private config (not added to `ozone-default.xml`, nor any `@Config` objects).
The config itself is just a way to indicate that the feature is to be disabled.  Actual restriction needs to be implemented for each feature where desired.  As part of this task, it is implemented for the "atomic rewrite key" feature (added in HDDS-10656).
https://issues.apache.org/jira/browse/HDDS-11378
Added acceptance test case in `compatibility`, ran locally.
CI:
https://github.com/adoroszlai/ozone/actions/runs/10593377482
> HDDS-11378. Allow disabling OM version-specific feature via config

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NetworkTopologyImpl.java
HDDS-11381. Adding logging for sortByDistanceCost in NetworkTopologyImpl to print sorted datanode list
Context: The sortDatanodes method in the KeyManagerImpl class used to include logging to print the sorted list of datanodes for topology-aware reads. However, as part of the changes introduced in [HDDS-9343](https://issues.apache.org/jira/browse/HDDS-9343), which moved the sortDatanodes logic to the OM (Ozone Manager), this logging was removed.
Action: To reinstate this functionality, add logging to the sortByDistanceCost method—called from the KeyManagerImpl class—to print the sorted list of datanodes. This will help maintain visibility into the datanode sorting process in the new implementation.
https://issues.apache.org/jira/browse/HDDS-11381
Locally …
> HDDS-11381. Adding logging for sortByDistanceCost in NetworkTopologyImpl

- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/PrometheusServlet.java
HDDS-11339. Publishing hadoop metrics immediately in Prometheus sink fills up SinkQueue quickly.
Two issues:
`PrometheusServlet` is being registered with `BaseHttpServer` when prometheus support is enabled and `PrometheusServlet` is being called every 15 secs by default as scraping interval and it publishes the hadoop metrics immediately. So if there are large number of metrics needs to be published in a very busy cluster, this makes SinkQueue gets filled up quickly and then sink cannot consume the given metrics and just dropped them outright.
A part from dropping , another issue is taking the object lock of `MetricsSystemImpl` class and before metrics actually being published, other threads keeps waiting to take the object lock. There was a recent issue came to highlight where in a busy …
> HDDS-11339. Publishing hadoop metrics immediately in Prometheus sink fills up SinkQueue quickly.

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerMXBean.java
Seen in [this run](https://github.com/errose28/ozone/actions/runs/10511037945)
Test set: org.apache.hadoop.hdds.scm.pipeline.TestPipelineManagerMXBean
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 25.984 s <<< FAILURE! - in org.apache.hadoop.hdds.scm.pipeline.TestPipelineManagerMXBean
org.apache.hadoop.hdds.scm.pipeline.TestPipelineManagerMXBean.testPipelineInfo  Time elapsed: 25.927 s  <<< ERROR!
java.util.concurrent.TimeoutException: 
Timed out waiting for condition. Thread diagnostics:
Timestamp: 2024-08-22 04:26:47,454
This previously showed up as an assertion failure until [HDDS-9537](https://issues.apache.org/jira/browse/HDDS-9537) introduced a wait for the condition. It seems the condition is still sometimes not satisfied, but the error now shows up as a timeout. …
> HDDS-11359. Intermittent timeout in TestPipelineManagerMXBean#testPipelineInfo

- hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/JavaUtils.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChecksumByteBufferImpl.java
During our internal testing we ran into an exception with Java 17 that originates in ChecksumByteBufferImpl.
The exception:
<pre>java.lang.reflect.InaccessibleObjectException: Unable to make field boolean java.nio.ByteBuffer.isReadOnly accessible: module java.base does not "opens java.nio" to unnamed module @46d56d67
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
at org.apache.hadoop.ozone.common.ChecksumByteBufferImpl.<clinit>(ChecksumByteBufferImpl.java:51)</pre>
The code has a TODO comment later on: …
> HDDS-11392. ChecksumByteBufferImpl's static initializer fails with java 17+

- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/ContentGenerator.java
Currently, there is a precautionary hsync and hflush capability check in ContentGenerator which is unnecessary. Because it should be based on feature flag and API implementation as in [OzoneOutputStream](https://github.com/apache/ozone/blob/877504aee1a5a23eeaa097e159b033018af66c86/hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/OzoneOutputStream.java#L108-L123).
This change is to remove the check and just rely on the feature flag and client.
HDDS-11390
Exiting unit tests and more in HDDS-11312
> HDDS-11390. Removed hsync and hflush capability check in ContentGenerator

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/upgrade/OMLayoutFeature.java
`OMLayoutFeature.HSYNC` was added in 1.4.0 but the HSync feature is disabled in 1.4.0. Later `OMLayoutFeature.HBASE_SUPPORT` was added for the newer HSync APIs and use cases.
Now, we have two layout flags, `OMLayoutFeature.HSync` and `OMLayoutFeature.HBASE_SUPPORT` for HSYNC which creates confusion. This change is to deprecate `OMLayoutFeature.HSync` and use `OMLayoutFeature.HBASE_SUPPORT` for all the HSync use cases.
HDDS-11407.
Existing tests and more will be added in HDDS-11312
> HDDS-11407. Use OMLayoutFeature.HBASE_SUPPORT for HSYNC

- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerTask.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/MockedSCM.java
- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancerStatusInfo.java
Please check the problem and its analysis in the Jira.
This PR adds a null check for the variables that may be null - `findTargetStrategy` and `findSourceStrategy`.
https://issues.apache.org/jira/browse/HDDS-11350
Added a unit test. The test reproduces the problem and fails without the source code changes in this PR. It passes with the changes.
**Note:** Green CI in my fork - https://github.com/siddhantsangwan/ozone/actions/runs/10682066573/job/29607054968
> HDDS-11350. NullPointerException thrown on checking container balancer status

- hadoop-ozone/dist/src/main/compose/upgrade/compose/ha/docker-config
- hadoop-ozone/dist/src/main/compose/upgrade/compose/non-ha/docker-config
- hadoop-ozone/dist/src/main/compose/upgrade/compose/om-ha/docker-config
- hadoop-ozone/dist/src/main/compose/upgrade/upgrades/non-rolling-upgrade/callbacks/1.5.0/callback.sh
- hadoop-ozone/dist/src/main/smoketest/debug/ozone-debug-lease-recovery.robot
- hadoop-ozone/dist/src/main/smoketest/freon/hsync.robot
- hadoop-ozone/dist/src/main/smoketest/hsync/upgrade-hsync-check.robot
- hadoop-ozone/dist/src/main/smoketest/ozone-lib/freon.robot
This change is to add upgrade tests and set the basic framework to add more tests for hsync. 
1. The upgrade tests added are currently using lease recovery API only. We can add other APIs `listOpenFiles`. (I tried to add listOpenFiles API as well but was facing issues when running in a non-HA environment. Will work on that as an improvement.)
2. Added HSync and HFlush tests via freon.
HDDS-11312
Green CI for acceptance tests in my forked branch: https://github.com/hemantk-12/ozone/actions/runs/10512044391
> HDDS-11312. [hsync] Added upgrade tests

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/ChunkManagerDispatcher.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/impl/AbstractTestChunkManager.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/impl/CommonChunkManagerTestCases.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
HDDS-11391. Frequent Ozone DN Crashes During OM + DN Decommission with Freon
* When in piggyback mode, check if WriteChunk/PutBlock has end of block field toggled. If so, close the corresponding block file open descriptor.
* Added unit test and integration test
TODO:
There is still one corner case not fixed yet: if client does write - hsync and then close (meaning write buffer is emptied), for some reason client doesn't toggle end of block field.
Unfortunately our BlockOutputStream implementation is becoming too complex to understand. Refactoring would be required later.
https://issues.apache.org/jira/browse/HDDS-11391
Unit tests, integration tests
> HDDS-11391. Frequent Ozone DN Crashes During OM + DN Decommission with Freon

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OzoneManagerProtocol.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneRepairShell.java
- hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/QuotaRepairTask.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/quota/QuotaRepair.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/quota/QuotaStatus.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/quota/QuotaTrigger.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/quota/package-info.java
CLI option to trigger repair and also check status:
```
ozone repair quota status [--service-host=<omHost> ] [--service-id, --om-service-id=<omServiceId>] 
ozone repair quota trigger [--buckets=<buckets>] [--service-host=<omHost>] [--service-id=<omServiceId>]
```
https://issues.apache.org/jira/browse/HDDS-11285
- Unit test case is added
```
./ozone repair quota trigger --service-host=localhost
ATTENTION: Running as user sumitagrawal. Make sure this is the same user used to run the Ozone process. Are you sure you want to continue (y/N)? y
Run as user: <supressed>
{"bucketCountDiffMap":{},"lastRunFinishedTime":"","lastRunStartTime":1725511849369,"taskId":1,"errorMsg":""}
./ozone repair quota status --service-host=localhost 
ATTENTION: Running as user sumitagrawal. Make sure this is the same …
```
> HDDS-11285. cli to trigger quota repair and status

- hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStreamSemaphore.java
Seeing these log messages in the console running freon tool
2024-08-23 23:18:37,432 [pool-2-thread-9] INFO io.KeyOutputStreamSemaphore: Initializing semaphore with maxConcurrentWritePerKey = 1
2024-08-23 23:18:37,432 [pool-2-thread-8] INFO io.KeyOutputStreamSemaphore: Initializing semaphore with maxConcurrentWritePerKey = 1
2024-08-23 23:18:37,432 [pool-2-thread-2] INFO io.KeyOutputStreamSemaphore: Initializing semaphore with maxConcurrentWritePerKey = 1
2024-08-23 23:18:37,432 [pool-2-thread-4] INFO io.KeyOutputStreamSemaphore: Initializing semaphore with maxConcurrentWritePerKey = 1
2024-08-23 23:18:37,432 [pool-2-thread-1] INFO io.KeyOutputStreamSemaphore: Initializing semaphore with maxConcurrentWritePerKey = 1
2024-08-23 23:18:37,432 [pool-2-thread-3] INFO …
> HDDS-11369. [hsync] Remove KeyOutputStreamSemaphore logs

- hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - ReadKey Metrics.json
Currently the read key dashboard does not include many OM read key related metrics. Add the break down of the read key metrics in OM. 
https://issues.apache.org/jira/browse/HDDS-11383
Local docker tests + real cluster dashboards.
> HDDS-11383. Improve read key dashboard to include add the read key related OM metrics.

- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/CancelPrepareSubCommand.java
ozone admin om cancelprepare --service-id improvement.
Currently, for ozone admin om cancelprepare command, we need to specify the om service ID as its a mandatory parameter.
```
ozone admin om cancelprepare
Missing required option: '--service-id=<omServiceId>'
Usage: ozone admin om cancelprepare [-hV] -id=<omServiceId>
Cancel prepare state in the OMs.
-id, --service-id=<omServiceId>
Ozone Manager Service ID
-V, --version   Print version information and exit. 
```
The aim is to pick the default om service ID when explicilty not specified. 
[HDDS-11145](https://issues.apache.org/jira/browse/HDDS-11145)
Tested Manually using CLI
```
ozone admin om cancelprepare
Cancel prepare succeeded, cluster can now …
```
> HDDS-11145. ozone admin om cancelprepare --service-id improvement

- NOTICE.txt
- dev-support/pom.xml
- hadoop-hdds/pom.xml
- hadoop-ozone/dist/src/main/assemblies/ozone-src.xml
- hadoop-ozone/pom.xml
- pom.xml
Backport #7120 to `ozone-1.4`.
https://issues.apache.org/jira/browse/HDDS-11365
```
$ for f in hadoop-ozone/dist/target/ozone-1.4.1/share/ozone/lib/{hdds,ozone}*jar; do
unzip -p "$f" META-INF/NOTICE.txt | head -2
done | sort -u
Apache Ozone
Copyright 2024 The Apache Software Foundation
```
CI:
https://github.com/adoroszlai/ozone/actions/runs/10580727905
> HDDS-11365. Fix the NOTICE file

- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/TriggerDBSyncEndpoint.java
- hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/filters/TestAdminFilter.java
Adding `@AdminOnly` annotation to the TriggerDBSyncEndpoint Endpoint.
https://issues.apache.org/jira/browse/HDDS-11436
Modified the existing UT's which passed successfully.
> HDDS-11436. Minor update in Recon API handling.

- hadoop-hdds/interface-client/src/main/proto/hdds.proto
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeUsageInfo.java
- hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java
- hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/UsageInfoSubcommand.java
- hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestUsageInfoSubcommand.java
We can use `ozone admin datanode usageinfo` to display the usage information of a datanode. However, this information does not include Pipeline details, which are also crucial for the datanode. It would be useful to include Pipeline information in this display.
The information is displayed as follows:
```
UUID : dd1e5cf2-dtf5-6b35-ade5-ac8589d9eaf5
IP Address : 192.168.0.1
Hostname : localhost-192.168.0.1
Capacity : 100 B (100 B)
Total Used : 20 B (20 B)
Total Used % : 20.00%
Ozone Used : 10 B (10 B)
Ozone Used % : 10.00%
Remaining : 80 B (80 B)
Remaining % : 80.00%
Pipeline(s) : 10
Container(s) : 5
Container Pre-allocated : 0 B (0 B)
Remaining Allocatable : 80 B (80 B)
Free Space To Spare : 0 B (0 B)
```
JIRA: HDDS-11357. Datanode Usageinfo Support Display Pipeline.
Junit Test & Execute …
> HDDS-11357. Datanode Usageinfo Support Display Pipelines Count.

- hadoop-ozone/dist/src/main/smoketest/ozone-lib/shell_tests.robot
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/keys/PutKeyHandler.java
Passing zero or negative `--expectedGeneration` values, `ozone sh key put` performs regular "put key" operation, not atomic rewrite.  To prevent confusion, we should reject such values.  For non-rewrite "put key" the option must be omitted.
https://issues.apache.org/jira/browse/HDDS-11441
Added Robot test case.
CI:
https://github.com/adoroszlai/ozone/actions/runs/10792841435
> HDDS-11441. ozone sh key put should only accept positive expectedGeneration

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinatorTask.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/AbstractReplicationTask.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisor.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisorMetrics.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationTask.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestReplicationSupervisor.java
When datanode executes ReplicateContainerCommand and ReconstructECContainersCommand, they are all done by ReplicationSupervisor. We should record more detailed metrics.
https://issues.apache.org/jira/browse/HDDS-11376
When we open the jmx connection of Datanode, we will see the newly added metrics.
Old jmx:
New jmx:
> HDDS-11376. Improve ReplicationSupervisor to record replication metrics

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/service/TestRangerBGSyncService.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/TrashOzoneFileSystem.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerRatisServer.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/AbstractKeyDeletingService.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/KeyDeletingService.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/MultipartUploadCleanupService.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/OMRangerBGSyncService.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/OpenKeyCleanupService.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/QuotaRepairTask.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/SnapshotDeletingService.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/SnapshotDirectoryCleaningService.java
submit ratis code refactor to avoid code duplicate. current for every internal request like cleanupOpenKey, deleteKeyService, deleteDirectoryService, ... it sends deleteOpenKey, Purge keys and Purge directory for cleanup. To handle that, below code in some or other form is written in all places,
```
if (isRatisEnabled()) {
OzoneManagerRatisServer server = getOzoneManager().getOmRatisServer();
RaftClientRequest raftClientRequest = RaftClientRequest.newBuilder()
.setClientId(clientId)
.setServerId(server.getRaftPeerId())
.setGroupId(server.getRaftGroupId())
.setCallId(getRunCount().get())
.setMessage(Message.valueOf(
OMRatisHelper.convertRequestToByteString(omRequest)))
.setType(RaftClientRequest.writeRequestType())
.build();
server.submitRequest(omRequest, raftClientRequest);
} else { …
```
> HDDS-11416. refactor ratis submit request avoid code duplicate

- hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ECBlockOutputStream.java
- hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/container/common/helpers/BlockData.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestContainerCommandsEC.java
During Ozone EC block recovery, we encountered a situation where some attempted recoveries of EC Stripe Blocks fail to reconstruct properly, resulting in the following error.
```
java.lang.IllegalArgumentException: The chunk list has 2 entries, but the checksum chunks has 3 entries. 
They should be equal in size.  
```
After carefully reviewing the EC code, We did not find any issues with the read and write operations. Upon discussion, we concluded that the closure of containers (e.g., when a container reaches its write capacity) may affect the writing of EC stripe data blocks. However, this is considered a normal occurrence, implying that occasional issues with some EC stripe data blocks are expected. 
For EC type EC-3-2-1024K: 
One of our EC stripes consists of 3 data blocks. Blocks 1 …
> HDDS-10985. EC Reconstruction failed because the size of currentChunks was not equal to checksumBlockDataChunks.

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/protocolPB/OMPBHelper.java
Connections, streams, files, and other classes that implement the Closeable interface or its super-interface, AutoCloseable, needs to be closed after use. Further, that close call must be made in a finally block otherwise an exception could keep the call from being made.
This change ensures that the DataInputBuffer and its close call is closed in a finally clause.
https://issues.apache.org/jira/browse/HDDS-11438
This is a trivial change, so no testing was deemed necessary.
> HDDS-11438. Ensure DataInputBuffer is closed in OMPBHelper#convert

- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OzoneFSUtils.java
Remove extra log which is added in [HDDS-11342](https://issues.apache.org/jira/browse/HDDS-11342) for each fs operation.
https://issues.apache.org/jira/browse/HDDS-11449
Verified using local docker cluster new log doesn't comes up for fs operation.
> HDDS-11449. Remove unnecessary log from client console.

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
There are some unclear docs in ContainerStateMachine. This PR aims to fix them if possible.
https://issues.apache.org/jira/browse/HDDS-11448
ci: 
https://github.com/jianghuazhu/ozone/actions/runs/10806940246
> HDDS-11448. Improve documentation in ContainerStateMachine

- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/TransactionInfo.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/SnapshotInfo.java
- hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMDirectoriesPurgeRequestWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyPurgeRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotCreateRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotMoveDeletedKeysRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotPurgeRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMDirectoriesPurgeResponseWithFSO.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/OMKeyPurgeResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotMoveDeletedKeysResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotUtils.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMDirectoriesPurgeRequestAndResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyPurgeRequestAndResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotCreateRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotPurgeRequestAndResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/snapshot/TestOMSnapshotCreateResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotInfo.java
Add a lastTransactionInfo field in SnapshotInfo to check for transactions in flight on the snapshot. This field can be compared against OMTransactionInfo table value to see if all transactions have been flushed to disk. We need this since all tables don't have a cache which could lead to wrong results when an iterator is initialized by a background service if all the transactions haven't been flushed to disk.
https://issues.apache.org/jira/browse/HDDS-11440
Added unit test to test serialization and deserialization and also testing the allied util functions.
> HDDS-11440. Add a lastTransactionInfo field in SnapshotInfo to check for transactions in flight on the snapshot

- .github/workflows/ci.yml
Wait for successful dependency and license checks before starting acceptance tests and other checks that also require a build (compile and kubernetes, currently).  Since dependency and license checks are quick, we can delay starting some other checks until their results are known.  This saves quite some worfkflow execution time in the rare case that these checks find any problem.
https://issues.apache.org/jira/browse/HDDS-11456
CI:
https://github.com/adoroszlai/ozone/actions/runs/10833842006
> HDDS-11456. Require successful dependency/licence checks for acceptance/compile/kubernetes

- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBCheckpointUtils.java
Currently the waitForCheckpointDirectoryExist helper method prints the log message in reversed order.
* As a part of this PR we are fixing this error message to properly reflect the fields it is logging
* Currently in the message `Checkpoint directory: {} didn't get created in {} secs` the ordering is reversed i.e Checkpoint directory `time` didn't get created in `directoryPath` seconds i.e the fields are flipped
* After this change the message will be proper
https://issues.apache.org/jira/browse/HDDS-11419
This patch was tested via Unit tests
> HDDS-11419. Fix waitForCheckpointDirectoryExist log message

- hadoop-ozone/dist/src/main/smoketest/s3/MultipartUpload.robot
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/AuthorizationFilter.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/CompleteMultipartUploadRequestUnmarshaller.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/MultiDeleteRequestUnmarshaller.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/PutBucketAclRequestUnmarshaller.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/exception/OS3Exception.java
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/util/S3Utils.java
When submitting `CompleteMultipartUpload` request without parts, `CompleteMultipartUploadRequestUnmarshaller` encounters `SAXParseException`, which it converts to error response with the default `500 Internal Server Error` code.  We can use the more specific `InvalidRequest` code instead.  Similar problem is fixed in two other unmarshallers.  Additionally, we can avoid the `SAXParseException` by checking for empty input and returning more specific error message (`You must specify at least one part`) for empty `CompleteMultipartUpload` request.
https://issues.apache.org/jira/browse/HDDS-11457
Tweaked existing robot test to verify this case.
CI:
https://github.com/adoroszlai/ozone/actions/runs/10846339715
> HDDS-11457. Internal error on S3 CompleteMultipartUpload if parts are not specified

- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/search/search.tsx
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/tables/bucketsTable.tsx
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/tables/pipelinesTable.tsx
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/tables/volumesTable.tsx
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/pages/buckets/buckets.tsx
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/pages/pipelines/pipelines.less
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/pages/pipelines/pipelines.tsx
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/pages/volumes/volumes.tsx
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/types/bucket.types.ts
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/types/pipelines.types.ts
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/types/volume.types.ts
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/utils/momentUtils.ts
Improve Pipelines page UI.
* This PR adds a new Pipelines Page with improved layout and design.
* The new page would help to eventually improve the overall look and feel for Recon
* Currently the page is disabled to the user so as to not affect any existing functionality
https://issues.apache.org/jira/browse/HDDS-11158
> HDDS-11158. Improve Pipelines page UI

- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueHandlerWithUnhealthyContainer.java
After running `
TestKeyValueHandlerWithUnhealthyContainer#testMarkContainerUnhealthyInFailedVolume`, it generate files.
It is better to move them to the `TempDir`, and make sure the project is clean after running tests.
https://issues.apache.org/jira/browse/HDDS-11473
CI:
https://github.com/chungen0126/ozone/actions/runs/10938671361
> HDDS-11473. Clean up files created after TestKeyValueHandlerWithUnhealthyContainer#testMarkContainerUnhealthyInFailedVolume

- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/components/autoReloadPanel/autoReloadPanel.tsx
HDDS-11468. Enabled DB sync button
* Currently the OM status gets initialized to empty string on component mount. This will cause the disabled status to evaluate to false. But upon clicking the button, the state gets updated and hence the disabled status evaluates to true.
* When we refresh the page, this state is again reset and the button gets enabled again.
* The backend will always provide a boolean response and we do not need to check for the empty string
* In such a scenario even after the initial load we should not disable the button and rather only check the response from backend.
* This PR makes the change by removing the disable flag allowing the user to click even after the sync.
https://issues.apache.org/jira/browse/HDDS-11468
Patch was …
> HDDS-11468. Enabled DB sync button

- hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/Table.java
- hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDeletingService.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDeletingServiceIntegrationTest.java
- hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto
- hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SnapshotChainManager.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotMoveTableKeysRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotPurgeRequest.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotMoveDeletedKeysResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotMoveTableKeysResponse.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/DirectoryDeletingService.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/KeyDeletingService.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/SnapshotDeletingService.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotUtils.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/OMRequestTestUtils.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotCreateRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotDeleteRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotMoveTableKeysRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotPurgeRequestAndResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotRenameRequest.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotSetPropertyRequestAndResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/snapshot/TestOMSnapshotMoveTableKeysResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestSnapshotDeletingService.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotChain.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotRequestAndResponse.java
On snapshot deletes, not all rename table entries are propogated to the next snapshot. This could lead to an incorrect reclamation of blocks on certain edge case scenarios.
Snapshot deletion steps:
1) Has the snapshot been flushed to disk
2) If next snapshot is not in deleted state
3) If the next snapshot is AOS, then check key deletion service is not running
4) Move all renameTableEntries/deleted/deletedDirectoryTable keys to next snapshot/AOS
5) Check all tables empty
6) Purge snapshot from the chain.
https://issues.apache.org/jira/browse/HDDS-11408
Adding unit tests
> HDDS-11408. Snapshot rename table entries are propagated incorrectly on snapshot deletes

- hadoop-hdds/docs/content/concept/Datanodes.md
- hadoop-hdds/docs/content/concept/Datanodes.zh.md
Due to the lack of configuration related descriptions on the Datanode docs new learners are unable to deploy the Datanode service quickly. Therefore, it is necessary to add some configuration descriptions of Datanodes to provide guidance for new learners.
In this patch, we've added configuration details to the DataNode documentation.
https://issues.apache.org/jira/browse/HDDS-11477
The test passed using the Hugo tool.
> HDDS-11477. [doc] Add configuration description for datanode docs

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerDoubleBuffer.java
TestOzoneManagerSnapshotAcl#testLookupKeyWithNotAllowedUserForPrefixAcl failed in [this run](https://github.com/errose28/ozone/actions/runs/10478142479/attempts/1)
Sometimes `OzoneManagerDoubleBuffer` doesn't work. Therefore, OM failed to create snapshot.
Set `isRunning` to true before starting `OzoneManagerDoubleBuffer`. 
This is necessary because, if `OzoneManagerDoubleBuffer#flushTransactions` runs while `isRunning` is false, it wil not flush any buffers, as shown below.
```
/**
* Runs in a background thread and batches the transaction in currentBuffer
* and commit to DB.
*/
@VisibleForTesting
public void flushTransactions() {
while (isRunning.get() && canFlush()) {        // it won't go into the while loop if isRunning is false
flushCurrentBuffer(); …
```
> HDDS-11354. Intermittent failure in TestOzoneManagerSnapshotAcl#testLookupKeyWithNotAllowedUserForPrefixAcl

- hadoop-ozone/dist/src/main/compose/common/s3a-test.sh
- hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/BucketEndpoint.java
Fix unexpected number of files in S3 status list, caused by including `startAfter` item in each batch (for directories).  Since the test uses page size = 2, each batch had one item from the previous, and only one new item.  This duplicated directory entries in the listing.
https://issues.apache.org/jira/browse/HDDS-10617
`ITestS3AContractGetFileStatusV1List` is now enabled and passing.
CI:
https://github.com/adoroszlai/ozone/actions/runs/10883581540
> HDDS-10617. Unexpected number of files in ITestS3AContractGetFileStatusV1List

- dev-support/ci/selective_ci_checks.bats
- dev-support/ci/selective_ci_checks.sh
Checkstyle applies some of its checks to properties files in `src/.../resources` directory.  However, checkstyle is run for PRs only if some Java files are changed (or checkstyle config itself).  Thus CI may fail to catch some checkstyle violation in properties files.
https://issues.apache.org/jira/browse/HDDS-11458
Added test case for selective checks using the following commit:
```
commit 71b8bdd8becf72d6f7d4e7986895504b8259b3e5
...
HDDS-4794. No appenders could be found for logger - in tests (#1896)
hadoop-hdds/client/src/test/resources/log4j.properties            |  2 +-
hadoop-hdds/common/src/test/resources/log4j.properties            |  2 +-
hadoop-hdds/container-service/src/test/resources/log4j.properties |  2 +-
hadoop-hdds/framework/src/test/resources/log4j.properties         | …
```
> HDDS-11458. Selective checks: trigger checkstyle for properties file changes

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECReconstructionCoordinator.java
In HDDS-10985(#7009), we worked together to improve the issue where EC blocks could not be recovered due to checksum problems. We have deployed it internally, and everything seems to be functioning normally so far.
I found a small improvement that can be optimized, as there is some redundancy in the code.
In HDDS-10985, we extracted `getBlockDataLength` into `BlockData`, allowing us to directly call the internal method in `ECReconstructionCoordinator`.
JIRA: https://issues.apache.org/jira/browse/HDDS-10985
No Need Unit Test.
> HDDS-11499. Remove Redundant Code from ECReconstructionCoordinator.

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java
In XceiverServerRatis, some logs are not clear enough. The purpose of this PR is to try to fix them.
Old log record 1:
```
2024-09-30 00:46:28,733 [973d0e1a-fd90-4d2b-991b-89a92fa7c5e1@group-6FF9AF421BCC->44fd977b-83b9-4753-ba54-52c87024523d-GrpcLogAppender-LogAppenderDaemon] ERROR org.apache.hadoop.ozone.container.common.transport.server.ratis.XceiverServerRatis: pipeline Action CLOSE on pipeline PipelineID=25293fcd-0bf2-4785-b7f8-6ff9af421bcc.Reason : 973d0e1a-fd90-4d2b-991b-89a92fa7c5e1 has not seen follower/s 44fd977b-83b9-4753-ba54-52c87024523d for 94267149ms
```
New log record 1:
```
2024-09-30 14:36:51,515 [main] ERROR ratis.XceiverServerRatis (XceiverServerRatis.java:triggerPipelineClose(777)) - pipeline Action CLOSE on pipeline …
```
> HDDS-11501. Improve logging in XceiverServerRatis

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/AbstractKeyDeletingService.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/DirectoryDeletingService.java
Client ID remains same between multiple service - KeyDeletingService, DirectoryDeletingService, SnapshotDeletingService, and SnapshotDirectoryDeletingService, as defined static.
Under rare scenario, when clientId and callId becomes same, ratis will ignore request considering replay of request, where callId is increase at same pace for the services.
So here, making clientId as unique for each service to avoid the case, by defining non-static in base class.
https://issues.apache.org/jira/browse/HDDS-11491
- Existing test cases for impact
> HDDS-11491. Avoid sharing clientId among deleting services

- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/api/db.json
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/duBreadcrumbNav/duBreadcrumbNav.tsx
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/duMetadata/duMetadata.tsx
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/duPieChart/duPieChart.tsx
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/eChart/eChart.tsx
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/fileNavbar/fileNavbar.tsx
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/pages/diskUsage/diskUsage.less
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/pages/diskUsage/diskUsage.tsx
- hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/types/diskUsage.types.ts
Improve Disk Usage page UI.
* This PR adds a new DU Page with improved layout and design.
* The new page would help to eventually improve the overall look and feel for Recon
* Currently the page is disabled to the user so as to not affect any existing functionality
https://issues.apache.org/jira/browse/HDDS-11162
> HDDS-11162. Improve Disk Usage page UI

- pom.xml
HDDS-11504. Update Ratis to 3.1.1.
* Update Ratis version from 3.1.0 to 3.1.1, which contains a lot of important bug fixes.
* IMO the most critical bug fixes for Ozone are 
1.  [RATIS-2135](https://issues.apache.org/jira/browse/RATIS-2135),
2. Revert of [RATIS-2099](https://issues.apache.org/jira/browse/RATIS-2099) and
3. Revert of [RATIS-1983](https://issues.apache.org/jira/browse/RATIS-1983).
We found Ozone were experiencing errors, slower (10%) and went out of memory under stress.
Commit diff: 
https://github.com/apache/ratis/compare/ratis-3.1.0...ratis-3.1.1
https://issues.apache.org/jira/browse/HDDS-11504
Existing unit test.
> HDDS-11504. Update Ratis to 3.1.1.

- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/BaseFreonGenerator.java
- hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OmBucketGenerator.java
When running freon, some errors will occur if -duration and -n are set at the same time. The purpose of this PR is to try to fix it.
https://issues.apache.org/jira/browse/HDDS-11494
ci: https://github.com/jianghuazhu/ozone/actions/runs/11085251713
There should be no errors when testing freon.
`
./bin/ozone freon ombg -v test3 -n 5 --duration 1m
`
Result:
```
SLF4J(W): Class path contains multiple SLF4J providers.
SLF4J(W): Found provider [org.slf4j.reload4j.Reload4jServiceProvider@5c0369c4]
SLF4J(W): Found provider [org.slf4j.simple.SimpleServiceProvider@2be94b0f]
SLF4J(W): See https://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J(I): Actual provider is of type [org.slf4j.reload4j.Reload4jServiceProvider@5c0369c4]
2024-09-28 23:54:35,812 [main] INFO …
```
> HDDS-11494. Improve the duration option of freon

- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestCommitInRatis.java
- hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestWatchForCommit.java
According to SonarCloud the new code added to this file is not covered by tests:
https://sonarcloud.io/component_measures?id=hadoop-ozone&branch=HDDS-7593&metric=new_coverage&selected=hadoop-ozone%3Ahadoop-hdds%2Fclient%2Fsrc%2Fmain%2Fjava%2Forg%2Fapache%2Fhadoop%2Fhdds%2Fscm%2FXceiverClientRatis.java
There are tests ([TestCommitInRatis.java](https://github.com/apache/ozone/blob/master/hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestCommitInRatis.java) and [TestWatchForCommit.java](https://github.com/chungen0126/ozone/blob/master/hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestWatchForCommit.java)) in `org.apache.hadoop.ozone.client.rpc` testing the 2 way and 3 way commit in Ratis. I …
> HDDS-11127. [hsync] Improve test coverage for XceiverClientRatis.java

- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/AbstractKeyDeletingService.java
- hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/DirectoryDeletingService.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestDirectoryDeletingService.java
When a directory have large number of sub-directory and that does not have any further sub-directory or sub-files, DirectoryDeletingService try to add all those sub-directory without considering deleted count. The reason is, remainCount is decremented only when have sub-directory or sub-files.
Fix is done, decrementing remainCount for directory marked for deletion also. So, remainCount will reduce for,
- parent directory getting updated
- sub-directory count getting moved / deleted
- sub-file count count getting moved / deleted
https://issues.apache.org/jira/browse/HDDS-11492
- Unit cases added
> HDDS-11492. Directory deletion get stuck having millions of directory

- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/CommandHandlerMetrics.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CloseContainerCommandHandler.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/ClosePipelineCommandHandler.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CreatePipelineCommandHandler.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteContainerCommandHandler.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/FinalizeNewLayoutVersionCommandHandler.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/ReconstructECContainersCommandHandler.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/RefreshVolumeUsageCommandHandler.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/ReplicateContainerCommandHandler.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/SetNodeOperationalStateCommandHandler.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisor.java
- hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisorMetrics.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestReconstructECContainersCommandHandler.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestReplicateContainerCommandHandler.java
- hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestReplicationSupervisor.java
This PR is an additional improvement to HDDS-11376. The goal is to make Datanode command metrics consistent across all commands.
https://issues.apache.org/jira/browse/HDDS-11444
ci:  https://github.com/jianghuazhu/ozone/actions/runs/10831917769
New jmx:
> HDDS-11444. Make Datanode Command metrics consistent across all commands

- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/volume/TestOMVolumeCreateResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/volume/TestOMVolumeDeleteResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/volume/TestOMVolumeResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/volume/TestOMVolumeSetOwnerResponse.java
- hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/volume/TestOMVolumeSetQuotaResponse.java
This PR extracts the bootstrap methods (`setup()`, `tearDown()`) used in the following OM volume response tests to reduce redundant code by allowing the tests to inherit from a superclass:
- TestOMVolumeCreateResponse
- TestOMVolumeDeleteResponse
- TestOMVolumeSetOwnerResponse
- TestOMVolumeSetQuotaResponse
[HDDS-11480. Refactor OM volume response tests](https://issues.apache.org/jira/browse/HDDS-11480)
- Pass all unit test
> HDDS-11480. Refactor OM volume response tests

- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/OMDBInsightEndpoint.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/OMDBInsightSearchEndpoint.java
- hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/KeyEntityInfo.java
The value of **`isKey`** for the **`keyEntityInfo`** is set to true by default. However, this should not be the case when using this object for deletedDirectories insights. Instead, we need to set the value to match what is present in the **`omKeyInfo`** in the RocksDB table.
https://issues.apache.org/jira/browse/HDDS-11518
Tested it out manually by creating a deleted directory record and validating in the json response.
> HDDS-11518. Recon OmDB Insights show isKey=true for directories

- .github/workflows/ci.yml
Overall code coverage decreased from 79% to 58% after changing to Java 17 for running tests
This PR adds build with Java 17 for use in `acceptance`, `kubernetes` and `coverage` checks.  This lets JaCoCo access the same binaries as the one used in tests.
Java 8 build is used in MapReduce acceptance tests because Hadoop docker image still comes with Java 8 (HDDS-11053).
https://issues.apache.org/jira/browse/HDDS-11046
Coverage in fork increased from 60% to 82%.
https://github.com/adoroszlai/ozone/actions/runs/11142498866
> HDDS-11046. Coverage decreased due to running tests with Java 17

- .github/workflows/ci.yml
After HDDS-11046, CI workflow builds Ozone with both Java 8 and 17.  Both target Java 8 (create classfiles usable in JDK 8), so there is no difference at runtime.  This PR removes the Java 8 build.
Also:
- use `TEST_JAVA_VERSION` where possible (`basic` check cannot use it, because SpotBugs 3 does not work with Java 17, while SpotBugs 4 reports many new issues)
- include Java version in "Setup java" step name
- add comment about different Java versions
https://issues.apache.org/jira/browse/HDDS-11527
CI:
https://github.com/adoroszlai/ozone/actions/runs/11175653923
> HDDS-11527. Avoid unnecessary duplicate build

- hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestSCMSafeModeManager.java
This PR refactored some tests in `TestSCMSafeModeManager` using JUnit 5's ParameterizedTest. Let us to execute a single test method multiple times with different parameters and reduce duplicate test.
[HDDS-6776. Cleanup TestSCMSafeModeManager](https://issues.apache.org/jira/browse/HDDS-6776)
- Pass all test
> HDDS-6776. Cleanup TestSCMSafeModeManager

- .github/workflows/ci.yml
`macos-12` runner is being deprecated, bump to next version: `macos-13`.
https://issues.apache.org/jira/browse/HDDS-11536
CI:
https://github.com/adoroszlai/ozone/actions/runs/11194104108
> HDDS-11536. Bump macOS runner version to macos-13
