hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocolServerSideTranslatorPB.java
Some column headers are missing from SCM roles table header:
```
$ cd hadoop-ozone/dist/target/ozone-2.0.0-SNAPSHOT/compose/ozone
$ OZONE_DATANODES=3 ./run.sh -d
$ docker-compose exec scm bash
bash-4.4$ ozone admin scm roles
f27d293bb5b5:9894:LEADER:833027d4-771b-4793-9e6d-024cc4a1bc7b:172.30.0.2
bash-4.4$ ozone admin scm roles --table
+----------------------------------------------------------------------------------+
|                         Storage Container Manager Roles                          |
+--------------+------+
|  Host Name   | Port |
+--------------+------+
| f27d293bb5b5 | 9894 | LEADER | 833027d4-771b-4793-9e6d-024cc4a1bc7b | 172.30.0.2 |
+--------------+------+--------+--------------------------------------+------------+
``` …
=> HDDS-11535. Incomplete SCM roles table header

hadoop-hdds/hadoop-dependency-test/pom.xml, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientWithRatis.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestSnapshotBackgroundServices.java, hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/OMMetadataManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SstFilteringService.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotPurgeResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/SnapshotDeletingService.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerProtocolServerSideTranslatorPB.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestSstFilteringService.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestSnapshotDeletingService.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOmSnapshotUtils.java
Fix the issue that junit5 tests were not executed in CI, backport these PR to fix this issue.
HDDS-10059. TestOMRatisSnapshots.testInstallSnapshot should only validate live files. (#6069)
HDDS-10143. Intermittent failure in TestOzoneRpcClientWithRatis.testParallelDeleteBucketAndCreateKey (#6335)
HDDS-11068. Move SstFiltered flag to a file in the snapshot directory (#6965)
HDDS-10218. Speed up TestSstFilteringService (#6196)
HDDS-11084. Read SstFilteringService config only once in SnapshotDeletingService (#6885)
HDDS-10552. Downgrade Surefire to 3.0.0-M4 (#6406)   (re-backport)
Because junit5 dependency `junit-jupiter-engine` was omitted when backporting HDDS-10552 (https://github.com/apache/ozone/pull/6553/commits/6a31ccd5011aad703473e48d7f623f9a6bcbf673). junit5 tests in the ozone-1.4 …
=> [DO NOT MERGE] Fix the issue that junit5 tests were not executed in CI

hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java
The default value of property `hdds.datanode.metadata.rocksdb.cache.size` in ozone-default.xml is corrected to 1GB as per the actual default value used in the code. 
[HDDS-11526](https://issues.apache.org/jira/browse/HDDS-11526)
Tested using TestKeyValueContainer#testContainerRocksDB.
=> HDDS-11526. hdds.datanode.metadata.rocksdb.cache.size default value description is wrong

hadoop-ozone/dist/src/main/smoketest/debug/ozone-debug-ldb.robot, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/debug/TestLDBCli.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/DBScanner.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/utils/Filter.java
A --filter option was added recently which selects records that have a given value for a particular field will make debugging easier. (as a part of https://github.com/apache/ozone/pull/7167)
Adding support for lesser/greater than operations will be useful while debugging
For example, if a value has many fields like [name, location->[address, DN, IP], version, lastUpdateTime], 
- using the option "--filter={version:equals:1}" will display records that have the value 1 for version.
- using the option "–filter={lastUpdateTime:greater:1000}" will display the record with lastUpdateTime>1000
- using the option "–filter={lastUpdateTime:lesser:1000}" will display the record with lastUpdateTime<1000
A list of fields along with the value it should be compared to is given to the command, and only …
=> HDDS-11476. Implement lesser/greater operation for --filter option of ldb scan command

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/insights/om/om.tsx
HDDS-11520. Fix Delete pending directories key mapping
* In the current code the columns for directory path and directory name are flipped for delete pending directories tab
* As a part of this PR we address that issue
https://issues.apache.org/jira/browse/HDDS-11520
=> HDDS-11520. Fix Delete pending directories key mapping

hadoop-ozone/dev-support/checks/build.sh, hadoop-ozone/dev-support/checks/junit.sh
`junit.sh` fails if `MAVEN_OPTS` is not set: the script enables `nounset` (fail on unset variables), but references `MAVEN_OPTS` without providing default value.
https://issues.apache.org/jira/browse/HDDS-11547
```
$ unset MAVEN_OPTS
$ ./hadoop-ozone/dev-support/checks/junit.sh
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 1.8.0_422, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.8.0-45-generic", arch: "amd64", family: "unix"
[INFO] Scanning for projects...
...
```
=> HDDS-11547. Make MAVEN_OPTS optional

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBDefinition.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/codec/OMDBDefinition.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerDoubleBuffer.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOMDBDefinition.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/OMDBUpdatesHandler.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestOMDBUpdatesHandler.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestOmUpdateEventValidator.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/DBDefinitionFactory.java, hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/debug/TestDBDefinitionFactory.java
HDDS-11554
By definition, OMDBDefinition won't be changed.  It should be a singleton.
=> HDDS-11554. OMDBDefinition should be singleton.

.github/workflows/ci.yml, hadoop-ozone/dev-support/checks/_mvn_unit_report.sh
Even if all tests pass, integration check may fail if it detects a leak (HDDS-8261).  Tests may also crash.
With this change, CI will list failed, crashed and leaking integration tests separately to help understand CI results ([example](https://github.com/adoroszlai/ozone/actions/runs/11261798708/attempts/1#summary-31316050194)).
https://issues.apache.org/jira/browse/HDDS-11551
Temporarily added a test with failure and enabled a test with leak.
CI:
https://github.com/adoroszlai/ozone/actions/runs/11261977076
=> HDDS-11551. Provide details about integration check failure

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/ECBlockChecksumComputer.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/ECFileChecksumHelper.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileChecksum.java
The parity checksum bytes calculation for the EC stripe checksum should be based on each stripe's first chunk's length. But right now it is calculated only on the first stripe's chunk length which results in incorrect results and, in many cases causes the byte buffer limit to become negative. Further, the checksum calculation has been simplified in this patch.
The checksum calculation for the last stripe is a little tricky, We have two cases for it.
1. If the last stripe has only one chunk at replica index 1, we can get the chunk length to calculate checksum. 
2. If the last stripe has more than one chunk, Then the last chunk will be partial. 
For EC, We store the stripe checksum for the entire stripe in replica index 1 and the parity blocks. We use this stripe checksum to calculate the …
=> HDDS-11482. EC Checksum throws IllegalArgumentException because the buffer limit is negative

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/utils/CertificateSignRequest.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsPolicyProvider.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECContainerOperationClient.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/CodecRegistry.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/DBCheckpointServlet.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerTask.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/SCMContainerPlacementRackAware.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestBlockManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestDeletedBlockLog.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestIncrementalContainerReportHandler.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestOzoneECClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
HDDS-11544. Improve work with arrays.
Some other meaningful refactoring.
This PR is designated to tackle some problems we have with converting collections into arrays. 
Like using old-style pre-sized arrays for such action or converting collection/stream into array through intermediary list which leads to significant performance degradation. 
https://issues.apache.org/jira/browse/HDDS-11544
Patch tested using existing Unit Tests. No new code was added, so no new tests are requited.
=> HDDS-11544. Improve work with arrays.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHADBTransactionBufferImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMStateMachine.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerStateMachine.java
The purpose of this PR is to add some logs to some StateMachines.
https://issues.apache.org/jira/browse/HDDS-11548
https://github.com/jianghuazhu/ozone/actions/runs/11255835628
=> HDDS-11548. Add some logging to the StateMachine

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java
Not sure how important of the NativeLibraryNotLoadedException. Keep seeing the following ERROR in the OM log. If it is important, it should throw the exception out and stop OM; otherwise, change it to WARN and consider not printing the stack trace.
```
024-09-24 23:02:20,241 ERROR [main]-org.apache.hadoop.ozone.om.snapshot.SnapshotDiffManager: Native Library for raw sst file reading loading failed.
org.apache.hadoop.hdds.utils.NativeLibraryNotLoadedException: Unable to load library ozone_rocksdb_tools from both java.library.path & resource file libozone_rocksdb_tools.so from jar.
        at org.apache.hadoop.hdds.utils.db.managed.ManagedRawSSTFileReader.loadLibrary(ManagedRawSSTFileReader.java:40)
        at org.apache.hadoop.ozone.om.snapshot.SnapshotDiffManager.initNativeLibraryForEffici …
```
=> HDDS-11486. SnapshotDiffManager prints ERROR for NativeLibraryNotLoadedException

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/InterSCMGrpcService.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/metadata/SCMDBDefinition.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/metadata/SCMMetadataStoreImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerReportHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerStateManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestIncrementalContainerReportHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestUnknownContainerReport.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestLegacyReplicationManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestStatefulServiceStateManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestContainerPlacement.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineDatanodesIntersection.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelinePlacementFactory.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelinePlacementPolicy.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineStateManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestRatisPipelineProvider.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestSimplePipelineProvider.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestWritableECContainerProvider.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMInstallSnapshot.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMInstallSnapshotWithHA.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconSCMDBDefinition.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/DBDefinitionFactory.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/containergenerator/GeneratorScm.java, hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/debug/TestDBDefinitionFactory.java
By definition, SCMDBDefinition won't be changed. It should be a singleton.
HDDS-11555
=> HDDS-11555. SCMDBDefinition should be singleton.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v1/AbstractS3SDKV1Tests.java, hadoop-ozone/integration-test/src/test/resources/log4j.properties
- Fix `OzoneClient` leak in S3G integration test:
https://github.com/apache/ozone/actions/runs/11315912516/attempts/1#summary-31467801190
- `HddsUtils#reportLeak` is supposed to print the leak's stack trace if log level is at least `DEBUG`.  However, it checks the wrong `Logger` instance: `HddsUtils`'s `LOG` instead of the argument `log`.  This method was moved from `ManagedRocksObjectUtils` by HDDS-11543, adding the new parameter, but keeping the `LOG.isDebugEnabled()` check.
- Set `OzoneClientFactory` log level to `DEBUG` in integration tests to get stack trace of `OzoneClient` leaks.
https://issues.apache.org/jira/browse/HDDS-11574
```
$ mvn -am -pl :ozone-integration-test -Dtest='TestS3SDKV1*' clean test
$ grep 'not closed properly' …
```
=> HDDS-11574. Ozone client leak in TestS3SDKV1

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
ContainerStateMachine and BaseStateMachine have the same RaftGroupId, so just keep one.
https://issues.apache.org/jira/browse/HDDS-11581
ci: https://github.com/jianghuazhu/ozone/actions/runs/11326766632
=> HDDS-11581. Remove duplicate ContainerStateMachine#RaftGroupId

hadoop-ozone/dev-support/checks/coverage.sh
JaCoCo can show java sources in the coverage report, we only need to let it know where to find the source files.
https://issues.apache.org/jira/browse/HDDS-11538
CI:
https://github.com/adoroszlai/ozone/actions/runs/11200444704
=> HDDS-11538. Let coverage report link to java sources

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/app.less, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/app.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/pages/buckets/buckets.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/pages/datanodes/datanodes.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/pages/diskUsage/diskUsage.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/pages/overview/overview.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/pages/pipelines/pipelines.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/pages/volumes/volumes.tsx
HDDS-11545. Added OM ID and SCM ID information
* We had a card displaying the OM Id and SCM id in the old UI however the new UI doesn't have this
* As a part of this PR we add a small metadata to the Overview page to display the IDs
* This is helpful in case of running commands or debugging where we can directly get the ID from Recon UI
https://issues.apache.org/jira/browse/HDDS-11545
=> HDDS-11545. [UI] Add OM and SCM ID information

hadoop-ozone/dist/src/main/smoketest/s3/MultipartUpload.robot, hadoop-ozone/dist/src/main/smoketest/s3/bucketdelete.robot, hadoop-ozone/dist/src/main/smoketest/s3/commonawslib.robot, hadoop-ozone/dist/src/main/smoketest/s3/mpu_lib.robot
Refactor `MultipartUpload.robot` by extracting reusable Robot keywords for test steps.
Also, reduce the number of temp files created for testing.
https://issues.apache.org/jira/browse/HDDS-11108
CI:
https://github.com/adoroszlai/ozone/actions/runs/11352009883
=> HDDS-11108. Extract keywords for multipart upload tests

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DatanodeDeletedBlockTransactions.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/SCMBlockDeletingService.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/ScmBlockDeletingServiceMetrics.java
> Background
During our use of deletion, I noticed that it can be very slow, especially after we switched to the EC policy.
Our Ozone01 cluster currently has about 1K machines. Initially, we chose to use a `Ratis-3Replica` strategy, but for cost 
considerations, we gradually switched to the `EC-6-3` strategy in July.
The following chart shows the deletion speed for `Ratis-3Replica` .
The following chart shows the deletion speed for `EC-6-3`.
By reviewing the code and analyzing the logs, we found that the following situation can cause deletion to be very slow. We will illustrate this with an example.
> Example
We want to delete data from an EC container with ContainerId = 1000. Since it is EC-6-3, there are 9 replicas (DN1, DN2, DN3, ... DN9).
Before deletion, we first select a batch of …
=> HDDS-11498. Improve SCM deletion efficiency.

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconSCMDBDefinition.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStorageContainerManagerFacade.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/AbstractReconContainerManagerTest.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconNodeManager.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconPipelineManager.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/DBDefinitionFactory.java, hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/debug/TestDBDefinitionFactory.java
By definition, ReconSCMDBDefinition won't be changed. It should be a singleton.
HDDS-11589
=> HDDS-11589. ReconSCMDBDefinition should be singleton.

hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/S3GatewayConfigKeys.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectPut.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestPartUpload.java
1. make s3g object read/write buffer configurable
2. change ozone.s3g.client.buffer.size default value from 4KB to 1MB
https://issues.apache.org/jira/browse/HDDS-11483
wrap get benchmark test
1. before the patch, ozone.client.bytes.per.checksum = 16KB, s3 get buffer size 8KB
```
[root@vc0616 systest]# warp get --warp-client=vc0616.halxg.cloudera.com --host=localhost:9879 --tls --autoterm --insecure --access-key=$AWS_ACCESS_KEY_ID --secret-key=$AWS_SECRET_ACCESS_KEY --obj.size=20mb --concurrent=20 --bucket=bucket-20-24 --objects 10000 --duration=5m
warp: Running benchmark on all clients... …
```
=> HDDS-11483. Make s3g object get and put operation buffer configurable

hadoop-hdds/docs/content/feature/Quota.md, hadoop-hdds/docs/content/feature/Quota.zh.md, hadoop-hdds/docs/content/security/GDPR.md, hadoop-hdds/docs/content/security/GDPR.zh.md, hadoop-hdds/docs/content/security/SecureOzone.md, hadoop-hdds/docs/content/security/SecureOzone.zh.md, hadoop-hdds/docs/content/security/SecuringDatanodes.md, hadoop-hdds/docs/content/security/SecuringDatanodes.zh.md, hadoop-hdds/docs/content/security/SecuringOzoneHTTP.md, hadoop-hdds/docs/content/security/SecuringOzoneHTTP.zh.md, hadoop-hdds/docs/content/security/SecuringS3.md, hadoop-hdds/docs/content/security/SecuringS3.zh.md, hadoop-hdds/docs/content/security/SecuringTDE.md, hadoop-hdds/docs/content/security/SecuringTDE.zh.md, hadoop-hdds/docs/content/security/SecurityAcls.md, hadoop-hdds/docs/content/security/SecurityAcls.zh.md, hadoop-hdds/docs/content/security/SecurityWithRanger.md, hadoop-hdds/docs/content/security/SecurityWithRanger.zh.md
This pull request fixes the Hadoop HDDS docs build issue encountered with Hugo v0.135.0 on an M1 Max MacBook Pro.
https://issues.apache.org/jira/browse/HDDS-11570
The issue was reproduced by building Ozone with the following command on an M1 Max MacBook Pro:
```bash
mvn clean install -DskipTests -Dos.arch=x86_64
```
The Hugo version used was v0.135:
```
hugo version
hugo v0.135.0-f30603c47f5205e30ef83c70419f57d7eb7175ab darwin/arm64 BuildDate=2024-09-27T13:17:08Z VendorInfo=gohugoio
```
The Maven build failed specifically at the hadoop-hdds-docs module with the following error:
```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.4.1:exec (default) on project hdds-docs: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
```
=> HDDS-11570. Fix HDDS Docs Build fail with Hugo v0.135.0

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMetrics.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/helpers/OMAuditLogger.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/lock/KeyLocking.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/lock/OmLockOpr.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/execution/BucketQuotaResource.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/execution/DbChangesRecorder.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/execution/LeaderCompatibleRequestExecutor.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/execution/LeaderRequestExecutor.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/execution/OMGateway.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/execution/OMGatewayMetrics.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/execution/RequestContext.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/execution/request/OMKeyCommitRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/execution/request/OMKeyCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/execution/request/OmKeyUtils.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/execution/request/OmRequestBase.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/utils/OzoneManagerRatisUtils.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/BucketLayoutAwareOMKeyRequestFactory.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerProtocolServerSideTranslatorPB.java
Performance test is done for benchmark adding metrics, configuration and code fix
NA
NA
=> HDDS-11418. leader execution flow 

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/ClientVersion.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/BlockUtils.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueHandlerWithUnhealthyContainer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestContainerCommandsEC.java
Change-Id: Ib8b9fb743492eacde1f11436eb3116e6a221ac9b
Currently backward client version compatability of Ozone RequestFeatureValidator in OM is broken, after a client version bump done as part of HDDS-10983. https://github.com/apache/ozone/pull/6932 fixes the issue on the RequestFeatureValidator side. 
This patch is a stop gap arrangement done in the interim which reverts the client version bump done in HDDS-10983.
https://issues.apache.org/jira/browse/HDDS-11132
Existing IT & unit tests
=> HDDS-11132. Revert client version bump done as part of HDDS-10983

hadoop-ozone/ozone-manager/pom.xml, pom.xml
Fix intermittent [failure](https://github.com/apache/ozone/actions/runs/11442330586/job/31839199387?pr=7340#step:10:35) in `repro` check:
```
--- /home/runner/.m2/repository/org/apache/ozone/ozone-manager/2.0.0-SNAPSHOT/ozone-manager-2.0.0-SNAPSHOT.jar
+++ hadoop-ozone/ozone-manager/target/ozone-manager-2.0.0-SNAPSHOT.jar
...
├── builddef.lst
│┄ ordering differences only
```
caused by:
> aspectj-maven-plugin generates a builddef.lst file with the detailed options passed to AspectJ and this file is embedded in the final jar. ([source](https://github.com/mojohaus/aspectj-maven-plugin/issues/52))
The contents of `builddef.lst` is non-reproducible due to:
- order of arguments may be different between runs (depends on filesystem iteration)
- arguments contain absolute paths
Since this file is …
=> HDDS-11600. Intermittent failure in repro due to ordering differences in builddef.lst

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java
If client sends unknown message to OM (e.g. new client talking to old OM), OM rejects it with error: `Message missing required fields`.  Client then retries it according to policy.  Since the message is sent unchanged, retries will not improve the situation.
Repro:
```
$ cd hadoop-ozone/dist/target/ozone-2.0.0-SNAPSHOT/compose/xcompat
$ OZONE_VERSION=1.4.0 COMPOSE_FILE=old-cluster.yaml:clients.yaml docker-compose up -d
$ COMPOSE_FILE=old-cluster.yaml:clients.yaml docker-compose exec new_client bash
bash-4.4$ kinit -kt /etc/security/keytabs/testuser.keytab testuser/scm@EXAMPLE.COM
bash-4.4$ OZONE_LOGLEVEL=DEBUG ozone repair quota status --service-host=om
...
2024-10-24 18:09:33,779 [main] INFO retry.RetryInvocationHandler: com.google.protobuf.ServiceException: …
```
=> HDDS-11608. Client should not retry invalid protobuf request

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java
Update batch put buffer debug log to print value remaining size.
https://issues.apache.org/jira/browse/HDDS-11594
Verified log in the local docker cluster
=> HDDS-11594. Update batchPut buffer log for rocksdb.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestTransferLeadershipShell.java
This PR modifies `TestTransferLeadershipShell` to create a cluster before executing all tests instead of creating a new cluster for each test execution. Since the tests in `TestTransferLeadershipShell` are validating `OM` and `SCM` independently, we can safely make this change to reduce integration test time.
[HDDS-11614. Speed up TestTransferLeadershipShell](https://issues.apache.org/jira/browse/HDDS-11614)
Pass the tests.
=> HDDS-11614. Speed up TestTransferLeadershipShell

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeDecommissionManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestNodeDecommissionManager.java
HDDS-11380. Fixing the error message of node decommission to be more comprehensive
Right now, when decommissioning fails quickly due to in-sufficient nodes, the error message says
> Insufficient nodes. Tried to decommission 1 nodes of which 1 nodes were valid. Cluster has 3 IN-SERVICE nodes, 3 of which are required for minimum replication.
This does not clearly explain, how many nodes are required for the decommission to proceed. So in this PR we will be changing the above message to clearly define how many more IN-SERVICE nodes are needed for decommissioning to proceed.
>  Insufficient nodes. Tried to decommission 2 nodes out of 4 IN-SERVICE HEALTHY and 1 UNHEALTHY nodes. Cannot decommission as a minimum of 3 IN-SERVICE HEALTHY nodes are required to …
=> HDDS-11380. Fixing the error message of node decommission to be more comprehensive

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/AbstractKeyDeletingService.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/OMRangerBGSyncService.java
HDDS-11507. Add error information to log while handling ServiceException
* Currently the log information provides a generic message with no error information when submitting purge request to Ratis fails.
* This PR adds the extra error information to the log
https://issues.apache.org/jira/browse/HDDS-11507
Patch was tested using unit tests
=> HDDS-11507. Add error information to log while handling ServiceException

hadoop-hdds/pom.xml, hadoop-hdds/rocks-native/pom.xml, hadoop-hdds/server-scm/pom.xml, hadoop-ozone/csi/pom.xml, hadoop-ozone/datanode/pom.xml, hadoop-ozone/dev-support/checks/dependency.sh, hadoop-ozone/dist/dev-support/bin/dist-layout-stitching, hadoop-ozone/dist/pom.xml, hadoop-ozone/httpfsgateway/pom.xml, hadoop-ozone/insight/pom.xml, hadoop-ozone/ozone-manager/pom.xml, hadoop-ozone/pom.xml, hadoop-ozone/recon/pom.xml, hadoop-ozone/s3gateway/pom.xml, hadoop-ozone/tools/pom.xml, pom.xml
(This PR extracts the code change common between HDDS-11450 and HDDS-11588, to make it easier to review.)
When building each Ozone component, its dependencies are listed in a classpath descriptor file, to be used at runtime.
Dependencies are copied to the `share/ozone/lib` directory only when building the `ozone-dist` module.  It depends on all other Ozone modules directly or transitively.  Since `ozone-dist` is a single module, third-party transitive dependency versions are resolved by Maven to a single version.  Only that version is copied to `share/ozone/lib`.  However, various Ozone components may depend on different versions of the same third-party module.  These different versions can end up in the classpath files, but will not be found at runtime.
The problem is mitigated by the …
=> HDDS-11591. Copy dependencies when building each module

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAWithStoppedNodes.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerRatisServer.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerProtocolServerSideTranslatorPB.java
HDDS-11558. HBase RegionServer crashes due to inconsistency caused by Ozone client failover handling
* Please see the jira for the reproduction steps.
* This PR proposes to add a check before OM preExecute() step, such that if OM (inside its Hadoop RPC handler) receives a request that has been executed before, return its cached result.
https://issues.apache.org/jira/browse/HDDS-11558
The reproduction is complex. It involves pausing multiple OMs in specific lock steps. So I'm not able to write a test. It might be possible to write Docker-based acceptance test to simulate node pause though.
I manually repeated the steps described in the jira several times to confirm the change fixed the problem.
=> HDDS-11558. Make OM client retry idempotent

hadoop-hdds/hadoop-dependency-client/pom.xml, hadoop-hdds/hadoop-dependency-server/pom.xml, pom.xml
Remove explicit dependency on `hadoop-shaded-guava`.  It is only for Hadoop, not used directly by Ozone.
https://issues.apache.org/jira/browse/HDDS-11619
CI:
https://github.com/adoroszlai/ozone/actions/runs/11577173548
=> HDDS-11619. Remove dependency on hadoop-shaded-guava

hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzFs.java, hadoop-ozone/ozonefs-hadoop2/src/main/java/org/apache/hadoop/fs/ozone/OzFs.java, hadoop-ozone/ozonefs-hadoop2/src/main/java/org/apache/hadoop/fs/ozone/RootedOzFs.java, hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/OzFs.java, hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/RootedOzFs.java, hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/OzFs.java, hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/RootedOzFs.java
HDDS-11635. Fix memory leak while using OFS connector via FileContext Hadoop API
* Leak occurs while using OFS connector via **Hadoop FileContext API**
* FileContext API does not have an explicit close interface
* ozone-filesystem client library implements FileContext API by means of **org.apache.hadoop.fs.ozone.RootedOzFs** which spawns new **RootedOzoneFileSystem** every time FileContext is used
* this internal FS object is never closed
* Propsed solution:
* close internal FS object in finalize()
https://issues.apache.org/jira/browse/HDDS-11635
Manual testing (accessing and manipulating data in Ozone over FileContext API) while monitoring memory consumption via JMX metrics. With the fix, consumption is stable
=> HDDS-11635. Memory leak while using OFS connector via FileContext Hadoop API

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/ClientVersion.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/BlockUtils.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueHandlerWithUnhealthyContainer.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/TestMiniChaosOzoneCluster.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestCommitWatcher.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestContainerCommandsEC.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestBlockTokens.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestBlockTokensCLI.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestContainerBalancerOperations.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestContainerOperations.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestContainerStateMachineIdempotency.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMiniOzoneOMHACluster.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/debug/TestLeaseRecoverer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/fsck/TestContainerMapper.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestContainerReportWithKeys.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/TestSecretKeysApi.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzFs.java, hadoop-ozone/ozonefs-hadoop2/src/main/java/org/apache/hadoop/fs/ozone/OzFs.java, hadoop-ozone/ozonefs-hadoop2/src/main/java/org/apache/hadoop/fs/ozone/RootedOzFs.java, hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/OzFs.java, hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/RootedOzFs.java, hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/OzFs.java, hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/RootedOzFs.java, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/package.json, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/pnpm-lock.yaml, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/vite.config.ts
HDDS-9503. Migrate simple misc. integration tests to JUnit5 (#5854)
HDDS-11608. Client should not retry invalid protobuf request (#7354)
HDDS-11132. Revert client version bump done as part of HDDS-10983 (#7348)
HDDS-11368. Remove dependency on Babel in Vite (#7119)
HDDS-11635. Memory leak when using Ozone FS via Hadoop FileContext API (#7382)
https://github.com/xichen01/ozone/actions/runs/11534716378
=> [DO NOT MERGE] Backport some fixes and compatibility commits from master to ozone-1.4

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/ContainerClientMetrics.java, hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java
Add detailed client-side hsync metrics, including:
1. Time to compose and send writeChunk/putBlock.
2. Time spent in the synchronize work. This is just a wrap around 1. plus any waiting time on the monitor lock.
3. Time to wait for the acshyncrhous work (writeChunk/putBlock and watchForCommit).
4. Time to wait for watchForCommit.
https://issues.apache.org/jira/browse/HDDS-11200
Standard CI.
=> HDDS-11200. Hsync client-side metrics

hadoop-ozone/dist/pom.xml, hadoop-ozone/dist/src/main/smoketest/s3/objectcopys3a.robot
Upgrade to `ozone-runner` image with Rocky Linux 9.3.
New `awscli` prints `Prefix` in the response for `list-objects`, e.g.:
```
{
"RequestCharged": null,
"Prefix": "ozone-test-6310816850/word.txt/"
}
```
So we have to tweak some assertions to look for given text only in key names, not just anywhere in the response.
https://issues.apache.org/jira/browse/HDDS-11639
Ran acceptance tests with pre-commit image:
https://github.com/adoroszlai/ozone/actions/runs/11662926001
Full CI with final image in progress:
https://github.com/adoroszlai/ozone/actions/runs/11665816501
=> HDDS-11639. Upgrade ozone-runner to Rocky Linux 9.3

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/ContainerClientMetrics.java, hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientMetrics.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/grpc/metrics/GrpcMetrics.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/util/MetricUtil.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/util/PerformanceMetrics.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/util/PerformanceMetricsInitializer.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/ContainerMetrics.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/metrics/S3GatewayMetrics.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/Freon.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/OzoneClientCreator.java
`MutableQuantiles` should be stopped when no longer needed, since its `scheduledTask` is referenced by a global `ScheduledExecutorService`.
https://issues.apache.org/jira/browse/HDDS-11642
Implemented a new Freon test (~not part of the PR~) that keeps creating and closing `RpcClient`:
```
ozone freon occ -t 1 --duration 10m
```
Confirmed on `master` that `MutableQuantiles` instance count is growing:
```
num     #instances         #bytes  class name (module)
3:        677544       32522112  org.apache.hadoop.metrics2.lib.MutableQuantiles
3:        935136       44886528  org.apache.hadoop.metrics2.lib.MutableQuantiles
3:       1095792       52598016  org.apache.hadoop.metrics2.lib.MutableQuantiles
```
while with the fix it is stable:
```
num     #instances         #bytes  class name …
```
=> HDDS-11642. MutableQuantiles should be stopped

hadoop-ozone/dev-support/checks/build.sh, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/upgrade/UpgradeActionRecon.java
Exit code in `build.sh` (used by `build` check) was accidentally omitted in HDDS-11057.  This results in "successful" build check even in case of build failure.  (`dependency` or `acceptance` checks may still catch the problem due to missing artifacts.)
This PR makes `build.sh` exit with failure result if there are any errors.
Also fix a javadoc [failure](https://github.com/apache/ozone/actions/runs/11549582108/job/32143421325#step:8:15382), which was not caught by CI earlier due to the problem above.
https://issues.apache.org/jira/browse/HDDS-11637
Ran the script after introducing some syntax error:
```
$ echo "garbage" >> hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsConfigKeys.java
$ ./hadoop-ozone/dev-support/checks/build.sh; echo $?
...
[ERROR] …
```
=> HDDS-11637. Compile failure is ignored in build check

hadoop-ozone/dist/src/main/compose/common/hadoop-test.sh
_acceptance (MR)_ test has some hard-coded information about Hadoop versions and corresponding Docker images.  The goal of this change is to allow overriding this information.  Possible use cases:
- build with Hadoop version X that does not (yet) have Docker image, and test with other Hadoop versions that do
- use custom Docker images with version of base software (Java, Robot Framework, etc.)
The implementation allows providing the list of Docker images by overriding `HADOOP_TEST_VERSIONS` environment variable.
https://issues.apache.org/jira/browse/HDDS-11641
Set custom `HADOOP_TEST_VERSIONS`:
https://github.com/adoroszlai/ozone/blob/b02daa3f62b61cd8cfe9005f53dd48875dbe02be/.github/workflows/ci.yml#L35
and verified that tests are executed for the specified versions: …
=> HDDS-11641. Allow testing Hadoop with custom docker images

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/app.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/pages/notFound/notFound.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/routes-v2.tsx
HDDS-11609. Switch to Recon v2 UI as the default UI
* Currently the default UI on visiting Recon is the V1 UI
* This PR changes the default UI to show the new v2 UI by default and enable the UI switching for users that want to use the old UI
* The heatmap page for this points to the v1 Heatmap UI even when v2 UI is enabled which would be changed to point to new heatmap page once that is prepared.
* As a part of this PR we are also adding a new improved 404 page design.
https://issues.apache.org/jira/browse/HDDS-11609
----
----
=> HDDS-11609. Switch to Recon v2 UI as the default UI

hadoop-ozone/dist/src/main/smoketest/compatibility/read.robot, hadoop-ozone/dist/src/main/smoketest/compatibility/setup.robot, hadoop-ozone/dist/src/main/smoketest/compatibility/write.robot
This change is to add a compatibility test for HSync similar to FSO (jira: HDDS-11134).
HDDS-11311
A successful run on the fork: https://github.com/hemantk-12/ozone/actions/runs/11699680411
=> HDDS-11311. Added Compatibility test for HSync

hadoop-ozone/dist/src/main/smoketest/compatibility/read.robot, hadoop-ozone/dist/src/main/smoketest/compatibility/write.robot
Address post-commit [comments](https://github.com/apache/ozone/pull/7400#pullrequestreview-2420025935) from HDDS-11311.
https://issues.apache.org/jira/browse/HDDS-11659
CI:
https://github.com/adoroszlai/ozone/actions/runs/11719155673/job/32642454294
=> HDDS-11659. Improve HSync compatibility test

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconUtils.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/OMDBInsightEndpoint.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/KeyEntityInfoProtoWrapper.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/ListKeysResponse.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/recovery/ReconOMMetadataManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/recovery/ReconOmMetadataManagerImpl.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestOmDBInsightEndPoint.java
The current ListKeysAPI implementation, pulls a batch of OMKeyInfo objects from the File / Key table and buffers them in an array.
Then it converts each item in that array to a KeyEntityInfo object, which has JSON annotations allowing the data to be serialized over HTTP.
This results in two copies of the objects buffered in memory at once.
Additionally, the OMKeyInfo object is a fairly heavyweight object, and creating it from protobuf also deserialized the block information, which is not needed for the ListKey purposes.
Further taking the protobuffer bytes from RocksDB creates a KeyInfo object (de-serialized proto) and then this object is copied into OmKeyInfo.
So for each key retrieved, we start with:
1. A deserialized proto object (KeyInfo)
2. A copy of the proto fields (OmKeyInfo)
3. A …
=> HDDS-11660. Recon List Key API: Reduce object creation and buffering memory

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java
In `OmUtils.normalizeKey()`, the code:
```
if (!keyName.equals(normalizedKeyName) && LOG.isDebugEnabled()) {
LOG.debug("Normalized key {} to {} ", keyName,
normalizedKeyName.substring(1));
}
```
Always executes the `String.equals()`, but it does not do anything unless debug is enabled.
Debug should be first in the if statement as predicates are evaluated left to right and if isDebugEnabled returns false, the more expensive string compare will not execute.
https://issues.apache.org/jira/browse/HDDS-11669
=> HDDS-11669. In OmUtils.normalizeKey isDebugEnabled should be evaluated first

.github/workflows/ci.yml
Change CI workflow to use `ozone-runner` from GitHub Container Registry to reduce rate of pull from Docker Hub.
(Ideally the version should be changed in `hadoop-ozone/dist/pom.xml`, but this image is not yet available in Docker Hub due to infra issues.)
https://issues.apache.org/jira/browse/HDDS-11583
CI:
https://github.com/adoroszlai/ozone/actions/runs/11737132627
Verified that download activity for the [image](https://github.com/apache/ozone-docker-runner/pkgs/container/ozone-runner/302390217?tag=20241108-jdk17-1) in GitHub increased (from 5 to 101) due to the CI run.
=> HDDS-11583. Use ozone-runner from GitHub in CI

.github/workflows/ci.yml, .github/workflows/intermittent-test-check.yml
Significant amount of time is spent on building Ozone FS modules in integration
check.  Any tests in these modules (currently only one) are executed only in
_integration (filesystem)_.  Thus we can skip shading in other splits.  Also
can be skipped in `flaky-test-check`.
https://issues.apache.org/jira/browse/HDDS-11683
Shaded modules were included in _integration (filesystem)_:
```
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.333 s - in org.apache.hadoop.fs.TestOmKeyInfoWithHadoop2
...
[INFO] Apache Ozone FileSystem Shaded ..................... SUCCESS [03:09 min]
[INFO] Apache Ozone FS Hadoop 2.x compatibility ........... SUCCESS [ 18.842 s]
[INFO] Apache Ozone FS Hadoop 3.x compatibility ........... SUCCESS [ 13.471 s]
[INFO] Apache Ozone FS Hadoop shaded 3.x …
```
=> HDDS-11683. Skip shade in most integration checks

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientRatis.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChunkBufferImplWithByteBuffer.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/container/common/helpers/BlockData.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyOutputStream.java
See HDDS-11665
https://issues.apache.org/jira/browse/HDDS-11665
CI.
Load test internally confirm at least 10% of improvement for hbase use-case.
=> HDDS-11665. Minor optimizations on the write path

hadoop-ozone/dev-support/checks/_lib.sh, hadoop-ozone/dev-support/checks/acceptance.sh
Avoid false negative ([failing](https://github.com/jojochuang/ozone/actions/runs/11388335221/job/31686275738#step:5:19), but reported as passing) _acceptance (s3a)_ check if Hadoop cannot be downloaded.
```
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
Abort the check in this case.
https://issues.apache.org/jira/browse/HDDS-11664
Temporarily changed Hadoop version to non-existent:
```diff
diff --git pom.xml pom.xml
index 9d48f929f6..1ad7cf2939 100644
--- pom.xml
+++ pom.xml
@@ -67,7 +67,7 @@ xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xs
<project.build.outputTimestamp>2023-01-01T00:00:00Z</project.build.outputTimestamp>
<hadoop2.version>2.10.2</hadoop2.version>
-    <hadoop.version>3.3.6</hadoop.version>
+ …
```
=> HDDS-11664. Hadoop download failure not reported as error

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/CertInfo.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/upgrade/FinalizationManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/upgrade/SCMUpgradeFinalizationContext.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/TenantArgs.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/DeleteTenantState.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmDBAccessIdInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmDBTenantState.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmDBUserPrincipalInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmRangerSyncArgs.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmTenantArgs.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/S3VolumeContext.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/NodeEndpoint.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/AclMetadata.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/ClusterStateResponse.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/DatanodeMetadata.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/NamespaceSummaryResponse.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/PipelineMetadata.java
Remove suppression of `HiddenField` checkstyle rule, currently only used for `Builder` classes.
Checkstyle is already configured to ignore `HiddenField` for "setter" methods.  However,
> [a] method is recognized as a setter if it is in the following form
> ```
> ${returnType} set${Name}(${anyType} ${name})
> ```
> where ... `${name}` is name of the variable that is being set and `${Name}` its capitalized form that appears in the method name.
> https://checkstyle.org/checks/coding/hiddenfield.html
So we need to make sure to follow naming conventions:
- parameter name must match method name
- method name must be `set...`, not `with...`
(We could also avoid the violation by renaming parameters to something like `newValue`.)
In some classes suppression was completely unnecessary. …
=> HDDS-11684. Remove suppression of HiddenField

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconUtils.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/OMDBInsightEndpoint.java
As we iterate keys in the listKeys API there is logic to resolve the FSO path to the key which is quite expensive in aggregate over many keys.
As we iterate the keys in order, it is highly likely there will be consecutive keys with the same parent folder and hence prefix.
Therefore, we should save the prefix prefix and if the current parentID is equal to the previous one, simple reuse it, avoiding all the path construction work.
https://issues.apache.org/jira/browse/HDDS-11668
Existing tests
=> HDDS-11668. Recon List Keys API: Reuse key prefix if parentID is the same

SECURITY.md
Based on the discussion in [the Ozone release rc2 email](https://lists.apache.org/thread/ncpxccgk250g8hwyy6pxhl7v87xjjs68), we should add the ozone-1.4.1 release information to `SECURITY.md` on the ozone-1.4 branch .
https://issues.apache.org/jira/browse/HDDS-11671
https://github.com/xichen01/ozone/actions/runs/11747419785
=> HDDS-11671. Refer to website for supported versions

pom.xml
Ratis 3.1.2 was just released, upgrade the version in Ozone.
https://issues.apache.org/jira/browse/HDDS-11653
CI:
https://github.com/adoroszlai/ozone/actions/runs/11813605274
=> HDDS-11653. Bump Ratis to 3.1.2

.github/workflows/populate-cache.yml, .github/workflows/scheduled-cache-update.yml
Workflows with schedules are disabled by GitHub in new forks.  `populate-cache` has a schedule, but is also triggered by commits changing POM files.  This PR extracts the scheduled part, so that new forks can start out with `populate-cache` enabled (only the schedule will be disabled by default).  Hopefully.
https://issues.apache.org/jira/browse/HDDS-11689
Pushed to `master` in my fork, `populate-cache` workflow was triggered correctly:
https://github.com/adoroszlai/ozone/actions/runs/11814012303
scheduled run was also triggered (with modified schedule, to avoid having to wait a day):
https://github.com/adoroszlai/ozone/actions/runs/11815697729
=> HDDS-11689. Extract scheduled workflow for populate-cache

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMDirectoryCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/file/OMFileCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCommitRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRenameRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/file/TestOMDirectoryCreateRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/file/TestOMDirectoryCreateRequestWithFSO.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyRequest.java
There is some identical processing logic in OMFileCreateRequest, OMKeyCommitRequest, OMKeyCreateRequest, and OMKeyRenameRequest, and the purpose of this PR is to simplify them.
Details: HDDS-10133
https://issues.apache.org/jira/browse/HDDS-10133
Ensure that unit tests pass successfully.
=> HDDS-10133. Add a method to check key name in OMKeyRequest

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineReportHandler.java
SCM follower should not log NotLeaderException during Pipeline Report processing.
While processing Pipeline Report, SCM follower might log `NotLeaderException` when the follower tries to move the Pipeline from ALLOCATED state to OPEN state.
This exception can be ignored as this is expected to happen in follower SCM.
We can optionally add `scmContext.isLeader()` check before calling `pipelineManager.openPipeline(pipelineID)` this will avoid the exception in the first place.
But, we can still end up with `NotLeaderException` as leader can change after `scmContext.isLeader()` check is done.
`scmContext.isLeader()` is an optimization which is not required here.
HDDS-11695.
This is logging change and doesn't affect any functionality.
The code refactoring is tested with existing unit test.
=> HDDS-11695. SCM follower should not log NotLeaderException during Pipeline Report processing.

hadoop-hdds/interface-admin/pom.xml, hadoop-hdds/interface-client/pom.xml, hadoop-hdds/interface-server/pom.xml, hadoop-ozone/interface-client/pom.xml
SpotBugs spends quite some time (~2.5 minutes) analyzing protobuf generated classes in _basic (findbugs)_ check ([example](https://github.com/apache/ozone/actions/runs/11812304304/job/32907294585#step:7:494)):
```
2024-11-13T07:07:13.4457877Z [INFO] --- spotbugs-maven-plugin:3.1.12.2:spotbugs (default-cli) @ hdds-interface-client ---
2024-11-13T07:07:14.2753914Z [INFO] Fork Value is true
2024-11-13T07:07:44.5920143Z [INFO] Done SpotBugs Analysis....
...
2024-11-13T07:07:48.7132408Z [INFO] --- spotbugs-maven-plugin:3.1.12.2:spotbugs (default-cli) @ hdds-interface-admin ---
2024-11-13T07:07:48.7224599Z [INFO] Fork Value is true
2024-11-13T07:08:07.8785130Z [INFO] Done SpotBugs Analysis....
...
2024-11-13T07:08:11.9305598Z [INFO] --- spotbugs-maven-plugin:3.1.12.2:spotbugs (default-cli) @ …
```
=> HDDS-11692. Skip spotbugs for modules with only generated code

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
Fix ACL check on bucket resolution while reading from a snapshot
https://issues.apache.org/jira/browse/HDDS-11732
Existing integration test & unit tests should be sufficient.
=> HDDS-11732. Skip ACL check on bucket resolution while reading from snapshot

.github/workflows/ci.yml, hadoop-ozone/dist/src/main/compose/common/hadoop-secure.yaml, hadoop-ozone/dist/src/main/compose/common/hadoop-test.sh, hadoop-ozone/dist/src/main/compose/common/hadoop.yaml, hadoop-ozone/dist/src/main/compose/ozonesecure-ha/.env, hadoop-ozone/dist/src/main/compose/ozonesecure-ha/docker-compose.yaml, hadoop-ozone/dist/src/main/compose/ozonesecure-mr/.env, hadoop-ozone/dist/src/main/compose/ozonesecure-mr/docker-compose.yaml, hadoop-ozone/dist/src/main/compose/ozonesecure/.env, hadoop-ozone/dist/src/main/compose/ozonesecure/docker-compose.yaml, hadoop-ozone/dist/src/main/compose/upgrade/compose/ha/.env, hadoop-ozone/dist/src/main/compose/upgrade/compose/ha/docker-compose.yaml, hadoop-ozone/dist/src/main/compose/xcompat/.env, hadoop-ozone/dist/src/main/compose/xcompat/new-cluster.yaml, hadoop-ozone/dist/src/main/compose/xcompat/old-cluster.yaml
Starting with Hadoop 3.3.6, Docker image is available from GitHub Container Registry.  Use it in CI to reduce intermittent failures like:
```
Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
https://github.com/apache/ozone/actions/runs/11823273130/job/32942963396#step:5:147
and
```
Error response from daemon: Head "https://registry-1.docker.io/v2/apache/hadoop/manifests/3.3.6": Get "https://auth.docker.io/...": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```
https://github.com/apache/ozone/actions/runs/11823273130/job/32942963396#step:5:147
Acceptance check uses Hadoop image for two purposes:
1. KMS in all secure …
=> HDDS-11698. Use hadoop image from GitHub in CI

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/OzoneVolume.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v1/AbstractS3SDKV1Tests.java
Fix:
```
java.lang.UnsupportedOperationException: null
at com.google.common.collect.ImmutableCollection.add(ImmutableCollection.java:268) ~[guava-32.1.3-jre.jar:?]
at org.apache.hadoop.ozone.client.OzoneVolume.addAcl(OzoneVolume.java:220) ~[classes/:?]
at org.apache.hadoop.ozone.s3.endpoint.BucketEndpoint.putAcl(BucketEndpoint.java:632) ~[classes/:?]
at org.apache.hadoop.ozone.s3.endpoint.BucketEndpoint.put(BucketEndpoint.java:304) ~[classes/:?]
```
which happens when trying to update bucket ACL via S3 Gateway.
https://issues.apache.org/jira/browse/HDDS-11737
Updated S3 integration test to exercise this code path.
CI:
https://github.com/adoroszlai/ozone/actions/runs/11878215107
=> HDDS-11737. UnsupportedOperationException in S3 setBucketAcl

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
Seems OMLayoutVersionManager is never closed, unlike layout version manager in SCM and DN. This cause metrics to not be cleaned.
https://issues.apache.org/jira/browse/HDDS-11644
https://github.com/ivandika3/ozone/actions/runs/11867693678
=> HDDS-11644. Close OMLayoutVersionManager

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconUtils.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/OMDBInsightEndpoint.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/ServiceNotReadyException.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestContainerEndpoint.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestNSSummaryEndpointWithFSO.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestOmDBInsightEndPoint.java
This PR addresses the issue when NSSummary tree is still building and initialising while listKeys API got request. 
This PR addresses the issue when NSSummary tree is still building and initialising while listKeys API got request. In this scenario, listKeys API should not return empty response , rather it should return proper Http Status code: `503 (Service Unavailable).`
https://issues.apache.org/jira/browse/HDDS-11708
Tested by running existing Junit test cases and wrote a new test case to test `503:Service Unavailable` scenario.
=> HDDS-11708. Recon ListKeys API should return a proper http response status code if NSSummary rebuild is in progress.

hadoop-ozone/dist/src/main/smoketest/debug/ozone-debug-tests.robot, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/VersionDebug.java
Implement debug subcommand to show Ozone internal component versions like:
```
$ ozone debug version
{
"client" : {
"name" : "BUCKET_LAYOUT_SUPPORT",
"protoValue" : 3
},
"datanode" : {
"name" : "COMBINED_PUTBLOCK_WRITECHUNK_RPC",
"protoValue" : 2
},
"om" : {
"name" : "S3_OBJECT_TAGGING_API",
"protoValue" : 9
}
}
```
It can be used in compatibility tests to help validate not only releases, but any specific commit.  (Of course this will require further changes in the tests.)
https://issues.apache.org/jira/browse/HDDS-11740
Added basic test case to exercise the command in acceptance tests.
CI:
https://github.com/adoroszlai/ozone/actions/runs/11881652506
=> HDDS-11740. Add debug command to show internal component versions

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/BucketEndpoint.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/CompleteMultipartUploadRequestUnmarshaller.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/MessageUnmarshaller.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/MultiDeleteRequestUnmarshaller.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/PutBucketAclRequestUnmarshaller.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/PutTaggingUnmarshaller.java
Reduce code duplication among:
- `CompleteMultipartUploadRequestUnmarshaller`
- `MultiDeleteRequestUnmarshaller`
- `PutBucketAclRequestUnmarshaller`
- `PutTaggingUnmarshaller`
by extracting generic parent class.
https://issues.apache.org/jira/browse/HDDS-11739
Refactoring, covered by existing tests.
CI:
https://github.com/adoroszlai/ozone/actions/runs/11880414364
=> HDDS-11739. Extract generic unmarshaller for S3 requests

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogStateManagerImpl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestDeletedBlocksTxnShell.java
While getting failed transaction based on start value, in this case currently we are iterating table till we reach to the start of the input transaction and then do the business logic. Instead of iterating here we can use help of seek to reach the input start transaction.
https://issues.apache.org/jira/browse/HDDS-11713
New integration test
=> HDDS-11713. Use seek to reach the start transaction.

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java
- **DataNode Registration Delays**: Each DataNode requires approximately 30 seconds to register with the leader SCM due to the heartbeat interval.
- **SCM Restart and Leadership Retention**: In scenarios where the restarted SCM retains leadership after an election, the SCM loses its in-memory state. DataNodes and pipelines must re-register, leading to delays in exiting safe mode.
- **Dependency on HealthyPipelineSafeModeRule**: This rule requires DataNodes to report pipeline health, which can be delayed due to slow DataNode registration, network latency, or the time needed for pipelines to stabilize.
- These factors combined caused the SCM to take slightly over a minute to exit safe mode, impacting write operations during this transition.
- The `handleSubmitRequestAndSCMSafeModeRetry` …
=> HDDS-11780. Increase client write retry when SCM is in safe mode

hadoop-hdds/docs/content/feature/dn-merge-rocksdb.md, hadoop-hdds/docs/content/feature/dn-merge-rocksdb.zh.md
[HDDS-7320](https://issues.apache.org/jira/browse/HDDS-7320) updated the default to be schemaV3. But it is not mentioned in the docs "Merge Container RocksDB in DN". It is updated in this PR.
https://issues.apache.org/jira/browse/HDDS-11796
Tested manually with `hugo serve`
=> HDDS-11796. Update documentation to mention that container schemaV3 is default

hadoop-ozone/dist/src/main/compose/testlib.sh
Hadoop's containers are left running if Hadoop test fails.
Steps to reproduce (by simulating failure):
```bash
cd hadoop-ozone/dist/target/ozone-2.0.0-SNAPSHOT/compose
sed -i -e 's/execute_command_in_container rm hadoop version/exit 1/' common/hadoop-test.sh
cd ozone
./test-hadoop.sh
docker ps
```
Result:
```
CONTAINER ID   IMAGE                  COMMAND                  CREATED         STATUS         PORTS                                                                      NAMES
983d0cd0fe79   apache/hadoop:2.10.2   "/usr/local/bin/dumb…"   8 seconds ago   Up 7 seconds   0.0.0.0:8088->8088/tcp, :::8088->8088/tcp                                  ozone-rm-1
89b8ddc1c331   apache/hadoop:2.10.2   "/usr/local/bin/dumb…"   8 seconds ago   Up 7 seconds …
```
=> HDDS-11704. Hadoop test leaves running containers in case of failure

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestHsyncGenerator.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/HsyncGenerator.java
See https://issues.apache.org/jira/browse/HDDS-11723.
https://issues.apache.org/jira/browse/HDDS-11723
CI.
=> HDDS-11723. Tool to better micro benchmark hbase performance in Ozone

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/OzoneClientConfig.java, hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/Checksum.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChecksumCache.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/common/TestChecksum.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/common/TestChecksumCache.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java, hadoop-ozone/client/src/test/java/org/apache/hadoop/ozone/client/TestBlockOutputStreamIncrementalPutBlock.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
Currently by default, each 4 MB block chunk is further divided into 16 KB chunks (down from 1 MB, changed in HDDS-10465) for checksum calculation.
The problem is, even with the smaller checksum chunk, clients still calculate the checksum for the whole 4 MB block chunk **from the beginning** every single time:
https://github.com/apache/ozone/blob/e57370124a36315d2be5791753912901f836ccd8/hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/Checksum.java#L171-L177
This PR aims to implement a checksum cache to reduce the CPU time spent in critical section for checksum calculation, in hope of greatly improving client hsync throughput when checksum is enabled.
There are much more improvements that can be done on optimizing checksum, such as:
1. Even finer-grained incremental checksum …
=> HDDS-10411. Support incremental ChunkBuffer checksum calculation

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ECReplicationConfig.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/RatisReplicationConfig.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/ReplicationConfig.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/client/StandaloneReplicationConfig.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerReportHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/events/SCMEvents.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/ContainerSafeModeRule.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/SCMSafeModeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/SafeModeMetrics.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeHeartbeatDispatcher.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeProtocolServer.java, hadoop-hdds/server-scm/src/main/resources/webapps/scm/scm-overview.html, hadoop-hdds/server-scm/src/main/resources/webapps/scm/scm.js, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/HddsTestUtils.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestSCMSafeModeManager.java
We aim for SCM to immediately switch to leader once it exits safe mode. Currently, due to certain issues, we need to wait for at least one full container report from a DataNode before proceeding with the switch.
Currently, SCM SafeMode has the following issues:
> Issue1
`DataNodeSafeModeRule` cannot effectively verify the registration status of DataNodes. In most cases, as long as there are more than one DataNode, this rule passes. Therefore, we need to strengthen this rule.
> Issue2
`ContainerSafeModeRule` does not support verification of EC (Erasure Coding) Containers. `EC` Containers differ significantly from `RATIS/THREE` Containers because EC Containers require determining how many replicas are needed based on the EC type. For instance, for `EC-6-3-1024K`, we need to ensure that the …
=> HDDS-11243. SCM SafeModeRule Support EC.

.github/workflows/ci.yml, hadoop-ozone/dev-support/checks/_post_process.sh, hadoop-ozone/dev-support/checks/acceptance.sh, hadoop-ozone/dev-support/checks/author.sh, hadoop-ozone/dev-support/checks/bats.sh, hadoop-ozone/dev-support/checks/checkstyle.sh, hadoop-ozone/dev-support/checks/docs.sh, hadoop-ozone/dev-support/checks/findbugs.sh, hadoop-ozone/dev-support/checks/junit.sh, hadoop-ozone/dev-support/checks/kubernetes.sh, hadoop-ozone/dev-support/checks/license.sh, hadoop-ozone/dev-support/checks/rat.sh, hadoop-ozone/dev-support/checks/repro.sh, hadoop-ozone/dist/src/main/k8s/definitions/ozone/config.yaml, hadoop-ozone/dist/src/main/k8s/examples/getting-started/config-configmap.yaml, hadoop-ozone/dist/src/main/k8s/examples/minikube/config-configmap.yaml, hadoop-ozone/dist/src/main/k8s/examples/ozone-dev/config-configmap.yaml, hadoop-ozone/dist/src/main/k8s/examples/ozone-ha/config-configmap.yaml, hadoop-ozone/dist/src/main/k8s/examples/ozone/config-configmap.yaml
Background:
- CI checks collect problems that caused the failure into a report file (usually `summary.txt`).  This file is shown in the jobs' `Summary of failures` step.
- Checks are marked as failed if the report file is not empty.
- There may be failures that affect the check, but are not specific to its validation.  E.g. findbugs may fail due to compile error.  This is not reflected in the report file, so the check may be passing despite compile errors.
On current `master`, SCM cannot exit safe mode in Kubernetes check:
```
100 'grep_log scm-0 SCM exiting safe mode.' is failed...
```
due to datanode startup failure:
```
RuntimeException: Failed to set directory permissions for /data: /data: Operation not permitted
at org.apache.hadoop.hdds.server.ServerUtils.getDirectoryFromConfig(Serve …
```
=> HDDS-11718. Some CI checks passing despite error

hadoop-hdds/common/src/main/resources/ozone-default.xml
HDDS-11773. Bump hdds.ratis.snapshot.threshold and hdds.container.ratis.statemachine.max.pending.apply-transactions to 100k
* DataNode is configured to snapshot every 10k transactions, which is too frequent for HBase workloads where DataNode can do thousands and eventually 10s of thousands of transactions per second. 
* Bump hdds.ratis.snapshot.threshold to 100k for now. Update hdds.container.ratis.statemachine.max.pending.apply-transactions to make it consistent.
* We have to revisit and make it 1M eventually.
https://issues.apache.org/jira/browse/HDDS-11773
Applied the change to a HBase cluster. Previously it was snapshotting every 4-5 seconds, and now it is doing it about every minute.
=> HDDS-11773. Prevent frequent DataNode Ratis snapshotting.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
HDDS-11785. DataNode aborts state machine because ContainerStateMachine does not know follower's next index
* When waitOnAllFollowers is enabled (hdds.datanode.wait.on.all.followers), the leader may not have the follower's information, and will throw a RuntimeException that closes the state machine.
* Add a fix to return 0 in that case.
https://issues.apache.org/jira/browse/HDDS-11785
=> HDDS-11785. DataNode aborts ContainerStateMachine if it does not know any follower next index

hadoop-ozone/dist/src/main/compose/upgrade/test.sh, hadoop-ozone/dist/src/main/compose/xcompat/clients.yaml, hadoop-ozone/dist/src/main/compose/xcompat/test.sh
Update compatibility acceptance tests to 1.4.1
https://issues.apache.org/jira/browse/HDDS-11265
https://github.com/xichen01/ozone/actions/runs/12066964771
=> HDDS-11265. Add Ozone 1.4.1 to compatibility acceptance tests

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/OzoneShell.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/bucket/BucketCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/keys/KeyCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/prefix/PrefixCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/snapshot/SnapshotCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/tenant/TenantUserCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/token/TokenCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/volume/VolumeCommands.java
`OzoneShell` subcommands are currently added via `ServiceLoader` (by implementing `SubcommandWithParent`).  Since this is a well-defined set of commands, we can register them in the parent command directly (`subcommands = { ... }`).
https://issues.apache.org/jira/browse/HDDS-11822
CI:
https://github.com/adoroszlai/ozone/actions/runs/12096565592
=> HDDS-11822. Register subcommands in OzoneShell

hadoop-ozone/dist/pom.xml, hadoop-ozone/dist/src/main/compose/common/init-kdc.sh
Test user principals are currently defined in the `apache/ozone-docker-testkrb5` repository.  Whenever a new principal is needed for tests, we need to:
- commit updated `init.sh` in `apache/ozone-docker-testkrb5`
- bump `ozone-testkrb5` image version in `apache/ozone`
- update keytabs in `apache/ozone` (this steps is removed in HDDS-11810)
This can be improved by creating principals just-in-time, right before exporting keytabs.
Benefits:
- simplifies the process of adding new principals
- avoid mismatch in list of principals added and exported
This PR updates `ozone-testkrb5` image to the latest version, which does not include any test principals.  It also adds logic to create the principals at test run time.
After this change we can simply add new principals in `init-kdc.sh` without …
=> HDDS-11820. Create test principals at test run time

hadoop-ozone/dist/src/main/smoketest/s3/bucketcreate.robot
Robot warning: replace "is not" with "!=" for S3 bucket create test.
HDDS-11687
Verified with local robot test run.
=> HDDS-11687. Robot warning: replace "is not" with "!="

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/debug/TestLDBCli.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/DBScanner.java
When executing the ldb command, specify the maximum number of records to print for each file.
https://issues.apache.org/jira/browse/HDDS-10568
ci : 
https://github.com/jianghuazhu/ozone/actions/runs/11955271018
Test command:
`
./bin/ozone debug ldb --db=/home/hadoop/jhz/test/om.db scan --column_family=bucketTable --out=/data12/test/tmp_file1 --max-records-per-file=300
`
`--max-records-per-file` specifies the maximum number of records to print per file. It is used together with `--out`.
result:
```
-rw-rw-r-- 1 hadoop hadoop 140538 Nov 21 22:02 0
-rw-rw-r-- 1 hadoop hadoop 136737 Nov 21 22:02 1
-rw-rw-r-- 1 hadoop hadoop 136741 Nov 21 22:02 2
-rw-rw-r-- 1 hadoop hadoop 139301 Nov 21 22:02 3
-rw-rw-r-- 1 hadoop hadoop 130741 Nov 21 22:02 4
-rw-rw-r-- 1 hadoop hadoop 130737 Nov 21 22:02 5 …
```
=> HDDS-10568. When the ldb command is executed, it is output by line

hadoop-ozone/dist/src/main/k8s/examples/getting-started/config-configmap.yaml, hadoop-ozone/dist/src/main/k8s/examples/getting-started/httpfs-public-service.yaml, hadoop-ozone/dist/src/main/k8s/examples/getting-started/httpfs-service.yaml, hadoop-ozone/dist/src/main/k8s/examples/getting-started/httpfs-statefulset.yaml, hadoop-ozone/dist/src/main/k8s/examples/getting-started/recon-public-service.yaml, hadoop-ozone/dist/src/main/k8s/examples/getting-started/recon-service.yaml, hadoop-ozone/dist/src/main/k8s/examples/getting-started/recon-statefulset.yaml
HttpFS k8s example files are added in the getting-started directory
https://issues.apache.org/jira/browse/HDDS-11806
By manual test, I have deployed getting-started in my own k8s cluster. It has been successfully deployed and I have checked the functionalities by integrating hue with httpfs gw.
=> HDDS-11806. Add HttpFS and Recon in getting-started k8s example

hadoop-hdds/interface-client/src/main/resources/proto.lock, hadoop-hdds/interface-server/src/main/resources/proto.lock, hadoop-ozone/interface-client/src/main/resources/proto.lock
Add `proto.lock` files from ozone-1.4.1 release branch to master.
https://issues.apache.org/jira/browse/HDDS-11266
https://github.com/xichen01/ozone/actions/runs/12066950982
=> HDDS-11266. Update proto.lock for Ozone 1.4.1

hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerConfigBuilder.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/MockedSCM.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancerDatanodeNodeLimit.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancerTask.java
In [PR for HDDS-9889](https://github.com/apache/ozone/pull/5758) we [discussed](https://github.com/apache/ozone/pull/5758#pullrequestreview-1963251436) with [Siddhant Sangwan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siddhant) that tests form `org.apache.hadoop.hdds.scm.container.balancer.TestContainerBalancerTask` could be refactored using `MockedSCM` class (introduced in [HDDS-9889](https://issues.apache.org/jira/browse/HDDS-9889))
Some work has been already done in:
1. https://github.com/apache/ozone/pull/5758
2. https://github.com/apache/ozone/pull/6537
3. https://github.com/apache/ozone/pull/6734
1. Refactor some tests from `org.apache.hadoop.hdds.scm.container.balancer.TestContainerBalancerTask` 
https://issues.apache.org/jira/browse/HDDS-11410
Use standalone …
=> HDDS-11410. Refactoring more tests from TestContainerBalancerTask

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMMXBean.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMXBean.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
We implemented the display of the DN HostName information on the DN page in [HDDS-11462](https://issues.apache.org/jira/browse/HDDS-11462) #7206 . I think we should display similar information in OM and SCM as well. This is a small change.
HDDS-11794. Display HostName in OM / SCM Overview. 
> OM
> SCM 
Manual test.
=> HDDS-11794. Display HostName in OM / SCM Overview.

hadoop-hdds/hadoop-dependency-client/pom.xml, hadoop-ozone/ozonefs-common/pom.xml, hadoop-ozone/ozonefs-common/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsShell.java
`ozonefs-common` depends on some server-side components with `test` scope, but doesn't actually use any of those.  It shouldn't need them, since it's a client-side component.
`OzoneFsShell` requires `commons-cli` due to the parent class from Hadoop.  It gets the dependency accidentally, because `ozone fs` uses the `ozone-tools` classpath, which has it:
https://github.com/apache/ozone/blob/dd22dbef8958311c2ec5e99822269405d59f8eba/hadoop-ozone/dist/src/shell/ozone/ozone#L191-L194
Similarly, `TestOzoneFsShell` gets the dependency transitively via the server-side components.  It started failing after removing the test-scoped dependencies:
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.153 s <<< FAILURE! - in org.apache.hadoop.fs.ozone.TestOzoneFsShell …
```
=> HDDS-11719. Remove dependency on server components from ozonefs-common

hadoop-ozone/dist/src/main/smoketest/recon/recon-api.robot, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/KeyEntityInfoProtoWrapper.java
Please check the jira for a description of the problem. The solution proposed here is to change `isKey()` to `getIsKey()` in `KeyEntityInfoProtoWrapper`.
https://issues.apache.org/jira/browse/HDDS-11848
Tested manually. 
Before the fix, calling the listKeys endpoint resulted in the described bug:
```
http://localhost:9888/api/v1/keys/listKeys?startPrefix=/vol1/bucket2&limit=1000
Conflicting/ambiguous property name definitions (implicit name 'key'): found multiple explicit names: [key, isKey], but also implicit accessor: [method org.apache.hadoop.ozone.recon.api.types.KeyEntityInfoProtoWrapper#setKey(java.lang.String)][visible=true,ignore=false,explicitName=false] (through reference chain: org.apache.hadoop.ozone.recon.api.types.ListKeysResponse["keys"])
```
After the fix, it works as …
=> HDDS-11848. Serialisation bug in Recon's listKeys API

hadoop-hdds/docs/content/interface/CSI.md, hadoop-hdds/docs/content/interface/S3.md, hadoop-hdds/docs/content/interface/S3.zh.md
Fuse support for Ozone via S3 is still experimental and not tested. This is explicitly called out in the CSI page, but not so in the S3 page. Remove the mention of fuse in the S3 page since it duplicates information from the CSI page.
HDDS-11859
Checked locally with `hugo serve`
=> HDDS-11859. Remove mention of fuse from s3 interface docs page

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestMultipartObjectGet.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v1/AbstractS3SDKV1Tests.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/audit/S3GAction.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/metrics/S3GatewayMetrics.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestListParts.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestMultipartUploadComplete.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestMultipartUploadWithCopy.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectGet.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectPut.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectTaggingDelete.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectTaggingGet.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectTaggingPut.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestPartUpload.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestPartUploadWithStream.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestPermissionCheck.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestUploadWithStream.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/metrics/TestS3GatewayMetrics.java
S3 Object ACL requests has not been implemented in Ozone due to possible conflicts with the existing ACL model. Therefore, S3 put-object-acl request is processed as a normal put-object request. This causes object ACL requests to overwrite the current object, which is unexpected.
We need to explicitly throw NotImplemented for put-object-acl requests to prevent misuse.
https://issues.apache.org/jira/browse/HDDS-11833
Integration test.
=> HDDS-11833. Return NotImplemented for S3 put-object-acl request.

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/NSSummaryAdmin.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/OMAdmin.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/scm/ScmAdmin.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/segmentparser/RatisLogParser.java
Subcommands should not extend `GenericCli`, it is required only for top-level commands.
https://issues.apache.org/jira/browse/HDDS-11830
- Verified that parent commands (`ozone admin` and `ozone debug`) display these subcommands in their help.
- Verified that the subcommands show help when invoked without options.
```
$ cd hadoop-ozone/dist/target/ozone-2.0.0-SNAPSHOT
$ bin/ozone admin
Incomplete command
Usage: ozone admin [-hV] [--verbose] [-conf=<configurationPath>]
[-D=<String=String>]... [COMMAND]
Developer tools for Ozone Admin operations
-conf=<configurationPath>
-D, --set=<String=String>
-V, --version   Print version information and exit.
--verbose   More verbose output. Show the stack trace of the errors.
Commands:
...
namespace …
```
=> HDDS-11830. Subcommands should not extend GenericCli

.github/workflows/ci.yml
Summary: Add Maven cache in CI for more checks, which use Maven only for reading Ozone version from `pom.xml`.
Background:
Acceptance check intermittently seems to be [stuck](https://github.com/apache/ozone/actions/runs/12198919237/job/34037623484#step:5:1) before executing any tests:
```
Fri, 06 Dec 2024 14:42:43 GMT Run pushd hadoop-ozone/dist/target/ozone-*
Fri, 06 Dec 2024 14:42:43 GMT   pushd hadoop-ozone/dist/target/ozone-*
Fri, 06 Dec 2024 14:42:43 GMT   sudo mkdir .aws && sudo chmod 777 .aws && sudo chown 1000 .aws
Fri, 06 Dec 2024 14:42:43 GMT   popd
Fri, 06 Dec 2024 14:42:43 GMT   ./hadoop-ozone/dev-support/checks/acceptance.sh
Fri, 06 Dec 2024 14:42:43 GMT   shell: /usr/bin/bash -e {0}
Fri, 06 Dec 2024 14:42:43 GMT   env:
Fri, 06 Dec 2024 14:42:43 GMT     ...
Fri, 06 Dec 2024 …
```
=> HDDS-11877. Enable Maven cache for more checks

pom.xml
This change switches from `makeAggregateBom` to `makeBom`, which only affects the BOM built for the root module.
Description from [CycloneDX](https://github.com/CycloneDX/cyclonedx-maven-plugin/tree/master?tab=readme-ov-file#goals):
> * `makeBom`: creates a BOM for each Maven module with its dependencies,
> * `makeAggregateBom`: creates an aggregate BOM at build root (with dependencies from the whole multi-modules build), and eventually a BOM for each module,
It is a workaround for https://github.com/CycloneDX/cyclonedx-maven-plugin/issues/410, which causes unnecessary attempts to download Ozone snapshot artifacts from repository.apache.org.
https://issues.apache.org/jira/browse/HDDS-11882
```
mvn -B -DskipTests -Dskip.installnodenpm -Dskip.npx -DskipShade \
--log-file build.log \
-Pdist …
```
=> HDDS-11882. Do not create aggregate BOM

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v1/TestS3SDKV1WithRatisStreaming.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpointStreaming.java
`ObjectEndpointStreaming#put` does not parse the S3 object tags argument although ClientProtocol#createStreamKey already supported it.
https://issues.apache.org/jira/browse/HDDS-11691
S3 SDK integration testing for S3G with streaming enabled.
=> HDDS-11691. Support object tags in ObjectEndpointStreaming#put

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestDirectoryDeletingServiceWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDeletingServiceIntegrationTest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/AbstractKeyDeletingService.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/DirectoryDeletingService.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestDirectoryDeletingService.java
When a large amount of data is deleted, we may see slow progress in clearing it out due to the large backlog of pending deletes, even if all deletion services run for their full intervals and collect their maximum number of entries. To speed up deletion further, more threads will need to be configured. This PR helps to support multi-threaded deletion for the directory deleting service.
Approach:
By default, we have configured 10 threads. We have a directory supplier class that has a synchronized get() function, which each thread calls to get a parent directory's info and then process it. Concurrently, threads call this get() and process the directory until remainNum > 0.
https://issues.apache.org/jira/browse/HDDS-11605
=> HDDS-11605. Directory deletion service should support multiple threads

hadoop-ozone/dev-support/checks/_lib.sh
_acceptance (s3a)_ downloads Hadoop source tarball for running contract tests.  Currently it uses `archive.apache.org` directly.  This PR changes the URL to use `closer.lua`, which checks mirrors first.
https://issues.apache.org/jira/browse/HDDS-11885
https://github.com/adoroszlai/ozone/actions/runs/12232729746/job/34120102070#step:6:21
=> HDDS-11885. Download Hadoop for S3A test from mirrors if available

.github/workflows/populate-cache.yml
`native` check intermittently times out at:
```
[INFO] --- properties-maven-plugin:1.2.1:read-project-properties (read-property-from-file) @ hdds-rocks-native ---
Error: The operation was canceled.
```
With `--debug` we can it's downloading dependencies:
```
[INFO] --- properties-maven-plugin:1.2.1:read-project-properties (read-property-from-file) @ hdds-rocks-native ---
[DEBUG] Resolving artifact org.apache.maven:maven-core:pom:3.9.9 from [apache.snapshots.https (https://repository.apache.org/content/repositories/snapshots, default, releases+snapshots), central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] Using transporter WagonTransporter with priority -1.0 for https://repository.apache.org/content/repositories/snapshots
[DEBUG] Using connector …
```
=> HDDS-11889. Include Maven dependencies for hdds-rocks-native in cache

.github/workflows/ci.yml, dev-support/ci/maven-settings.xml, hadoop-ozone/dist/src/main/compose/common/s3a-test.sh
_acceptance (s3a)_ runs some Hadoop AWS contract tests using Ozone as the object store.  Hadoop POM defines Apache snapshots repo without disabling it for release artifacts.  This is fixed in HADOOP-19360, but not yet released.
This PR adds a workaround for HADOOP-19360 in Ozone, to disable access to snapshot repos while compiling and running Hadoop tests.  This is achieved by defining mirrors with `blocked=true` in Maven settings (see [MNG-7117](https://issues.apache.org/jira/browse/MNG-7117)).
The option `--no-transfer-progress` is removed so that we can see dependency downloads.  It can be restored once we are sure that this round of problems with the Maven repo is over.
https://issues.apache.org/jira/browse/HDDS-11909
1. Downloaded and extracted Hadoop 3.4.1 sources
2. Compiled …
=> HDDS-11909. Intermittent timeout building Hadoop in s3a test

hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java, hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/rocksdiff/TestRocksDBCheckpointDiffer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestOMSnapshotDAG.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDiffManager.java
Snapshot diff currently doesn't fallback to full snapdiff if DAG has been pruned and rather returns the partial delta sst file list which could lead to wrong snapshot diff result. 
Instead we need to check if all the sst files of source snapshots have been visited as part of the dag traversal.
https://issues.apache.org/jira/browse/HDDS-11893
Adding unit tests & integration tests
=> HDDS-11893. Fix full snapshot diff fallback logic because of DAG pruning

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/WritableRatisContainerProvider.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/MockPipelineManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconPipelineManager.java
PipelineManagerImpl lock optimization reduces AllocateBlock latency
The following are the issues discovered in our production environment:
When applying for a block in the Ratis replica, there may be jitter in the P99 latency due to obtaining a read lock
The main parts that hold write locks:
```
org.apache.hadoop.hdds.scm.pipeline.WritableECContainerProvider#allocateContainer
```
EC pipelines are frequently created and closed because there is only one container in each EC pipeline. When the container is full, the creation of new ones will be closed. When creating a pipeline, a write lock at the pipeline manager level will be held, while when applying for a Ratis block, a read lock at the pipeline manager level will be held.
The purpose of this optimization is to unlock. When creating and …
=> HDDS-11413. PipelineManagerImpl lock optimization reduces AllocateBlock latency

hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java, hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDiffUtils.java, hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/rocksdiff/TestRocksDBCheckpointDiffer.java
Snapshot diff DAG traversal should not skip node based on prefix presence. 
Consider the case 
Snap1 has 1, 2, 3 files
Say 1,4 compacted to => 5
And 5, 6 => 7
Snap 2 has 7, 2, 3 file.
Now diff b/w Snap1 & Snap2 would be in 4 & 6 sst files.
Consider 1 had +k & 4 had -k
Now 5 would have neither of these files.
But as per this condition:
https://github.com/apache/ozone/blob/b11b80707d4e6721c06966936ad87063ec107da6/hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java#L1009-L1016 traversal on would skip node 5 thus traversal would never reach 1,4. We should not have this optmization check. This would end up not using the compaction even though it is not there.
https://issues.apache.org/jira/browse/HDDS-11908
Unit tests
=> HDDS-11908. Snapshot diff DAG traversal should not skip node based on prefix presence

hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedRocksDB.java, hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/compaction/log/CompactionFileInfo.java, hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/CompactionNode.java, hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java, hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDiffUtils.java, hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/rocksdiff/TestRocksDBCheckpointDiffer.java, hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/rocksdiff/TestRocksDiffUtils.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDiffManager.java
Snapshot diff should not filter SST Files based by reading SST file reader and instead should rely on rocksdb's liveMetadataFile which also includes tombstone entries. 
When creating dag compaction log as well, key ranges should also look at liveMetadataFile.
https://issues.apache.org/jira/browse/HDDS-11914
Existing Unit tests and adding more
=> HDDS-11914. Snapshot diff should not filter SST Files based by reading SST file reader

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/CodecBuffer.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChunkBufferImplWithByteBufferList.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/IncrementalChunkBuffer.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/utils/BufferUtils.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/utils/MockGatheringChannel.java
- Pass `byte[]` to `GatheringByteChannel.write(..)`.
- Check `< 0` instead of `<= 0`.
HDDS-11860
=> HDDS-11860. Improve BufferUtils.writeFully.

hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancerStatusInfo.java
Fix flaky TestContainerBalancerStatusInfo.testGetCurrentStatisticsWhileBalancingInProgress
https://issues.apache.org/jira/browse/HDDS-11927
=> HDDS-11927. Fix flaky TestContainerBalancerStatusInfo.testGetCurrentStatisticsWhileBalancingInProgress

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/repair/om/TestFSORepairTool.java
`TestFSORepairTool` starts a new cluster for each test case, which is required due to the tool's design. To reduce the test runtime, I removed some redundant and less critical test cases, and made some adjustments.
[HDDS-11863](https://issues.apache.org/jira/browse/HDDS-11863)
CI: https://github.com/sarvekshayr/ozone/actions/runs/12277072838
Before:
```
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 146.798 s - in org.apache.hadoop.ozone.repair.om.TestFSORepairTool
```
After:
```
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 32.014 s - in org.apache.hadoop.ozone.repair.om.TestFSORepairTool
```
=> HDDS-11863. Speed up TestFSORepairTool

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/bucket/InfoBucketHandler.java
Change the bucket-name for bucket info/ls for linked buckets from **_bucketName_** to **_name_**, to keep it consistent with source buckets info/ls output
https://issues.apache.org/jira/browse/HDDS-11926
Tested manually on docker -
```
bash-5.1$ ozone sh volume create vol1
bash-5.1$ ozone sh bucket create vol1/buck1
bash-5.1$ ozone sh bucket link vol1/buck1 vol1/linkbuck1
bash-5.1$ ozone sh bucket ls vol1
[ {
"name" : "buck1",
"listCacheSize" : 1000,
"creationTime" : "2024-12-16T05:18:18.730Z",
"modificationTime" : "2024-12-16T05:18:18.730Z",
"sourcePathExist" : true,
"bucketLayout" : "FILE_SYSTEM_OPTIMIZED",
"owner" : …
```
=> HDDS-11926. Use "name" in bucket info JSON for links, same as regular buckets

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/OpenKeyCleanupService.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestOpenKeyCleanupService.java
Ratis may reject request when callId and clientId is same for different request(Assume it as a replay). To avoid such replay issue we need to ensure callId is different for different requests sent from openKeyCleanupService in each interval.
https://issues.apache.org/jira/browse/HDDS-11807
New integration test
=> HDDS-11807. Make callId different for each request in openKeyCleanupService

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogStateManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestDeletedBlockLog.java
In few cases when some transactions are problematic, that leads to block other transactions to be processed until it reaches max retry. To overcome this bottleneck we can give each transaction to get chance before same transaction being retried again.
https://issues.apache.org/jira/browse/HDDS-11712
New unit test
=> HDDS-11712. Process other DeletedBlocksTransaction before retrying failed one

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/OzoneSecretKey.java
Since the `OzoneSecretKey` doesn't have to implements `Writable`, we can remove the related unused methods in the class. thanks!
Please take a look at [HDDS-11907](https://issues.apache.org/jira/browse/HDDS-11907) for more details.
It tested by the CI.
=> HDDS-11907. OzoneSecretKey does not need to implement Writable

dev-support/pom.xml
Enable sortpom in dev-support module.
[Sortpom](https://github.com/Ekryd/sortpom/) plugin was added as part of #7555.
This PR enables the plugin for dev-support module.
It also sorts the pom of  dev-support module.
HDDS-11950
Out of order Property
```
[INFO] --- sortpom:3.0.1:verify (default) @ ozone-dev-support ---
[INFO] Verifying file /Users/nvadivelu/Codebase/Github/ozone/dev-support/pom.xml
[ERROR] The line 27 is not considered sorted, should be '    <failIfNoTests>false</failIfNoTests>'
[ERROR] The file /Users/nvadivelu/Codebase/Github/ozone/dev-support/pom.xml is not sorted
```
=> HDDS-11950. Enable sortpom in dev-support module.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/SCMBlockDeletingService.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/ScmBlockDeletingServiceMetrics.java, hadoop-ozone/dist/src/main/compose/ozone/.env, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java
When there are many DNs, and if any DN is slow in processing. It is difficult to identify which DN is having issue unless we check the log deeply and can take long time. For fast debug in this PR, metrics are added in SCM per datanode to show how many delete command sent to datanode and how many response received or timedout. This will help in understand which DN is slow or having problem in much efficient way.
https://issues.apache.org/jira/browse/HDDS-11711
Updated test in TestBlockDeletion
=> HDDS-11711. Add SCM metrics for delete commands sent and response received per datanode

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/BlockDeletingServiceMetrics.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestDeleteBlocksCommandHandler.java
This PR adds the following metrics for datanode w.r.t. deletion:
- Total no. of delete transactions processed
- Total no. of delete transactions skipped for deletion
- Total no. of delete commands received in DN
- Total no. of delete commands discarded in DN due to queue being full
https://issues.apache.org/jira/browse/HDDS-11779
Tested manually
=> HDDS-11779. Add DN metrics to show deletion progress

hadoop-ozone/dist/src/main/compose/xcompat/lib.sh, hadoop-ozone/dist/src/main/compose/xcompat/test-new.sh, hadoop-ozone/dist/src/main/compose/xcompat/test-old.sh
`xcompat` test is now one of the longest, due to increasing coverage.  This change splits it into two suites based on cluster version: `compat-new` for cluster running current code, and `compat-old` for testing current client with various old cluster versions.
https://issues.apache.org/jira/browse/HDDS-11934
CI:
- `test-old.sh`: https://github.com/adoroszlai/ozone/actions/runs/12327584447/job/34409960056
- `test-new.sh`: https://github.com/adoroszlai/ozone/actions/runs/12327584447/job/34409959998
- `compatibility` Robot tests: https://github.com/adoroszlai/ozone/actions/runs/12327584447/job/34409960208#step:6:24
=> HDDS-11934. Split compat suite to old/new

hadoop-ozone/recon-codegen/src/main/java/org/hadoop/ozone/recon/codegen/SqlDbUtils.java, hadoop-ozone/recon-codegen/src/main/java/org/hadoop/ozone/recon/schema/SchemaVersionTableDefinition.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconSchemaManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/upgrade/ReconLayoutFeature.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/upgrade/ReconLayoutVersionManager.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/persistence/AbstractReconSqlDBTest.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/persistence/TestSchemaVersionTableDefinition.java
- **What Happens Now:**
- During a fresh install, all tables, including the schema version table, are created for the first time.
- When the schema version table is created, it is initialized with the latest SLV (Software Layout Version), indicating that the schema is already at the latest state.
- The Recon Layout Version Manager will detect this value, and no upgrade actions will be triggered since the metadata of all tables is already up-to-date.
- **What Happens Now:**
- In clusters being upgraded where the schema version framework was not present previously:
- The schema version table is newly created while other tables already exist.
- The MLV (Metadata Layout Version) is initialized to `-1`, indicating the starting point of the upgrade framework.
- Only the necessary upgrade …
=> HDDS-11846. [Recon] Recon Schema version_number column is always set as -1.

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/duBreadcrumbNav/duBreadcrumbNav.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/pages/diskUsage/diskUsage.less
HDDS-11957. Make breadcrumb scrollable for long path names in DiskUsage page
* We use a breadcrumb to show the current path for which we are displaying the DU data
* When the path is long it causes the text to wrap to next line which is not ideal behaviour for a breadcrumb.
* This PR removes the wrapping behaviour and overflows to scroll instead.
* **Minor change**: The breadcrumb separators are changed to a `/` (slash) to follow path separator conventions instead of a right arrow
https://issues.apache.org/jira/browse/HDDS-11957
https://github.com/user-attachments/assets/f6cc61ed-1a66-444d-8246-7d2f335d6584
=> HDDS-11957. Make breadcrumb scrollable for long path names in DiskUsage page

hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/TestOzoneDelegationTokenSecretManager.java
Fix tests to renew/cancel TestOzoneDelegationTokenSecretManager with OM Ratis enabled.
In ratis, create/renew token doesn't add token to store until `validateAndUpdateCache`.
Add `addToTokenStore` to the tests.
https://issues.apache.org/jira/browse/HDDS-11869
CI:
https://github.com/chungen0126/ozone/actions/runs/12396367209
=> HDDS-11869. Enable OM Ratis in TestOzoneDelegationTokenSecretManager

hadoop-ozone/dist/src/main/smoketest/compatibility/write.robot, hadoop-ozone/dist/src/main/smoketest/createmrenv.robot, hadoop-ozone/dist/src/main/smoketest/debug/ozone-debug-ldb.robot, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/bucket/CreateBucketHandler.java
Currently, one must use the enum used in the code to define the layout in the `ozone sh` command (`OBJECT_STORE` or `FILE_SYSTEM_OPTIMIZED`). This could be more helpful.
Adding the more commonly used terms `obs` and `fso` to the CLI.
https://issues.apache.org/jira/browse/HDDS-11964
Some of the existing robot tests have been updated to use the new options.
=> HDDS-11964. Allow ozone sh bucket create to take obs and fso as options.

hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/GenericTestUtils.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/repair/om/TestFSORepairTool.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneRepairShell.java, hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/repair/ldb/TestTransactionInfoRepair.java
Code cleanup in `TestFSORepairTool`, `TestOzoneRepairShell`, and `TestTransactionInfoRepair`.
- `TestOzoneRepairShell` should shutdown cluster, close client.
- Reduce mocking.
- Test `ozone repair`, not subcommands.
- Less strict ordering of test cases in `TestFSORepairTool`.
- Reduce duplication by extracting method for executing `ozone repair om fso-tree` with/without `--repair` flag.
- Use static import for assertions.
- Use `assertThat` instead of `assertTrue` where applicable, for better failure message.
- Improve usability of `SystemOutCapturer`, `SystemErrCapturer` and reduce duplication.
https://issues.apache.org/jira/browse/HDDS-11961
https://github.com/adoroszlai/ozone/actions/runs/12399956746
=> HDDS-11961. Improve existing repair tests

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ComponentVersion.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/ClientVersion.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/Version.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/Versioned.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/upgrade/LayoutFeature.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/validation/VersionExtractor.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/validation/TestVersionExtractor.java
Currently LayoutVersion & ClientVersion classes don't have a common base class even though they represent some sort version in the overall system. We should unify both these classes under one single interface which would help us perform some set of operations on the common base class in the request validator framework.
https://issues.apache.org/jira/browse/HDDS-11963
Added new unit tests & existing unit tests
=> HDDS-11963. Unify client version and layout version under one interface to accomodate in the request validator framework

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java
`testHSyncKeyOverwriteHSyncKey` and `testHSyncKeyOverwriteNormalKey` are frequently failed under the ratis enabled mode, this pr fixed it by waiting for double buffer cache to flush.
Please check [HDDS-11870](https://issues.apache.org/jira/browse/HDDS-11870) for more details, thanks.
It can be tested by CI.
=> HDDS-11870. Fix TestHSync overwrite cases for OM Ratis enabled

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChecksumCache.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OzoneFSUtils.java
The Freon log seems to be flooded by `HSync` message, this information might be helpful for debug, it would be better to keep it in degbug mode. Please take a look, thanks!
[HDDS-11857](https://issues.apache.org/jira/browse/HDDS-11857)
run the provided command in the docker services can see the msg doesn't show under normal mode.
```c
$ sudo docker compose exec -T scm ozone freon ockg -n10 -t1 2>&1 | grep -o -e 'Ignoring ozone.fs.hsync.enabled' -e 'Initializing ChecksumCache' | sort | uniq -c
7 Initializing ChecksumCache
```
=> HDDS-11857. Freon log flooded by HSync message

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/cli/GenericCli.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/cli/GenericParentCommand.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/cli/AbstractMixin.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/cli/AbstractSubcommand.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ScmOption.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ScmSubcommand.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/container/ContainerCommands.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/container/InfoSubcommand.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/container/ListSubcommand.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/NSSummaryAdmin.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/container/InspectSubcommand.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/FreonReplicationOptions.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/quota/QuotaRepair.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/quota/QuotaStatus.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/quota/QuotaTrigger.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/Handler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/ReplicationOptions.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/bucket/BucketCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/keys/KeyCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/prefix/PrefixCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/snapshot/SnapshotCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/tenant/TenantUserCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/token/TokenCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/volume/VolumeCommands.java
`GenericParentCommand` provides a way to access `GenericCli` methods from sub-subcommands.  However, its usage is tedious and comes with boilerplate code that needs to:
- implement `GenericParentCommand`
- define methods manually
- define member variable for `@ParentCommand` (injected by picocli)
Adding new methods to `GenericParentCommand` becomes harder the more implementations we have.  The interface needs to be implemented on all sub-command levels.
Currently only very few implementations exists.  Some subcommands access top-level command via similar parent chain, but without implementing `GenericParentCommand`.
Picocli keeps track of the command hierarchy and allows accessing the top-level command directly via `CommandSpec`.
Changes in this PR:
- Introduce new …
=> HDDS-11878. Use CommandSpec to find top-level command

hadoop-ozone/dist/src/main/compose/test-all.sh
Acceptance Test test-all script fails to delete old result directories.
The fix deletes the directories recursively.
HDDS-11995
Manually tested the fix
Before fix
```
╰─❯ ./test-all.sh
rm: /Users/nvadivelu/Codebase/Github/ozone/hadoop-ozone/dist/target/ozone-2.0.0-SNAPSHOT/compose/result/compatibility: is a directory
rm: /Users/nvadivelu/Codebase/Github/ozone/hadoop-ozone/dist/target/ozone-2.0.0-SNAPSHOT/compose/result/ozone: is a directory
rm: /Users/nvadivelu/Codebase/Github/ozone/hadoop-ozone/dist/target/ozone-2.0.0-SNAPSHOT/compose/result/ozone-balancer: is a directory
rm: /Users/nvadivelu/Codebase/Github/ozone/hadoop-ozone/dist/target/ozone-2.0.0-SNAPSHOT/compose/result/ozone-csi: is a directory
rm: /Users/nvadivelu/Codebase/Github/ozone/hadoop-ozone/dist/target/ozone-2.0.0-SNAPSHOT/c …
```
=> HDDS-11995. Acceptance Test test-all script fails to delete old result directories.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/cli/GenericCli.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManagerStarter.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/cli/OzoneAdmin.java, hadoop-ozone/csi/src/main/java/org/apache/hadoop/ozone/csi/CsiServer.java, hadoop-ozone/insight/src/main/java/org/apache/hadoop/ozone/insight/ConfigurationSubCommand.java, hadoop-ozone/insight/src/main/java/org/apache/hadoop/ozone/insight/LogSubcommand.java, hadoop-ozone/insight/src/main/java/org/apache/hadoop/ozone/insight/MetricsSubCommand.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestBlockTokensCLI.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManagerStarter.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServer.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/Gateway.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/BaseFreonGenerator.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/DNRPCLoadGenerator.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/DatanodeSimulator.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/Freon.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/HsyncGenerator.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/RandomKeyGenerator.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/SCMThroughputBenchmark.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/OzoneRatis.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/OzoneShell.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/s3/S3Shell.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/tenant/TenantShell.java
Replace `GenericCli#createOzoneConfiguration` calls with `GenericCli#getOzoneConf`.
`GenericCli#getOzoneConf` is getting called before `picocli` injects the command-line Options `configurationOverrides` and `configurationPath`, so the `OzoneConfigutation` object is created before `picocli` updates these Options.
To update the `OzoneConfigutation` object with `configurationOverrides` and `configurationPath`, this PR changes the `configurationOverrides` and `configurationPath` instance variables to methods.
HDDS-11992
CI Run: [12523963928](https://github.com/nandakumar131/ozone/actions/runs/12523963928)
=> HDDS-11992. Replace GenericCli#createOzoneConfiguration calls with getOzoneConf.

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotPurgeRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotPurgeResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotPurgeRequestAndResponse.java
Duplicate snapshot purge request causes NPE.
The fix would be add a check if the snapshotInfo is not null before adding to updatedSnapshotInfos map. 
https://issues.apache.org/jira/browse/HDDS-11997
Added a unit test for duplicate snapshot purge request which repros the issue
=> HDDS-11997. Duplicate snapshot purge request causes NPE

hadoop-ozone/dev-support/intellij/runConfigurations/ScmRoles.xml, hadoop-ozone/dist/src/shell/ozone/ozone, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestBlockTokensCLI.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestNSSummaryAdmin.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestReconfigShell.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestScmAdminHA.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestTransferLeadershipShell.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/OzoneAdmin.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/NSSummaryAdmin.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/OMAdmin.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/reconfig/ReconfigureCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/scm/ScmAdmin.java, hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/scm/TestDecommissionScmSubcommand.java
Move OzoneAdmin from `hdds-tools` to `ozone-tools` in preparation of enabling interactive shell.
https://issues.apache.org/jira/browse/HDDS-11993
CI:
https://github.com/adoroszlai/ozone/actions/runs/12506093384
=> HDDS-11993. Move OzoneAdmin to ozone-tools

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ContainerBalancerCommands.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ReplicationManagerCommands.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/SafeModeCommands.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/cert/CertCommands.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/container/ContainerCommands.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DatanodeCommands.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/StatusSubCommand.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/pipeline/PipelineCommands.java, hadoop-ozone/dist/src/main/smoketest/admincli/container.robot, hadoop-ozone/dist/src/main/smoketest/admincli/datanode.robot, hadoop-ozone/dist/src/main/smoketest/admincli/pipeline.robot, hadoop-ozone/dist/src/main/smoketest/admincli/replicationmanager.robot, hadoop-ozone/dist/src/main/smoketest/admincli/safemode.robot, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/reconfig/ReconfigureCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/scm/DeletedBlocksTxnCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/container/ContainerCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/ldb/RDBParser.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/ldb/RDBRepair.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/om/OMRepair.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/quota/QuotaRepair.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/bucket/BucketCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/keys/KeyCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/prefix/PrefixCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/snapshot/SnapshotCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/tenant/TenantUserCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/token/TokenCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/volume/VolumeCommands.java
Intermediate subcommands (ones that only group other subcommands) do not need to implement `Callable`.  Currently they show "missing subcommand" error as action.  The same can be achieved by using picocli built-in behavior.
https://issues.apache.org/jira/browse/HDDS-11880
Ran some of these without subcommands:
```
$ ozone admin cert
Usage: ozone admin cert [-hV] [COMMAND]
Certificate related operations
-V, --version   Print version information and exit.
Commands:
info   Show detailed information for a specific certificate
list   List certificates
clean  Clean expired certificates from the SCM metadata.
$ ozone admin container
Usage: ozone admin container [-hV] [COMMAND]
Container …
```
=> HDDS-11880. Intermediate subcommands do not need to implement Callable

hadoop-hdds/annotations/pom.xml, hadoop-hdds/client/pom.xml, hadoop-hdds/common/pom.xml, hadoop-hdds/config/pom.xml, hadoop-hdds/container-service/pom.xml, hadoop-hdds/crypto-api/pom.xml, hadoop-hdds/crypto-default/pom.xml, hadoop-hdds/docs/pom.xml, hadoop-hdds/erasurecode/pom.xml, hadoop-hdds/framework/pom.xml, hadoop-hdds/hadoop-dependency-client/pom.xml, hadoop-hdds/hadoop-dependency-server/pom.xml, hadoop-hdds/hadoop-dependency-test/pom.xml, hadoop-hdds/interface-admin/pom.xml, hadoop-hdds/interface-client/pom.xml, hadoop-hdds/interface-server/pom.xml, hadoop-hdds/managed-rocksdb/pom.xml, hadoop-hdds/pom.xml, hadoop-hdds/rocks-native/pom.xml, hadoop-hdds/rocksdb-checkpoint-differ/pom.xml, hadoop-hdds/server-scm/pom.xml, hadoop-hdds/test-utils/pom.xml, hadoop-hdds/tools/pom.xml
Enable sortpom in hadoop-hdds sub-modules : `annotations`, `client`, `common` & `config`.
Sortpom plugin was added as part of #7555.
This PR enables the plugin for `hadoop-hdds` sub-modules. (part 1)
Sorting all the sub-modules under `hadoop-hdds` creates a big change, which will be hard to review. So, breaking this into multiple PRs.
This PR also sorts the pom of `hadoop-hdds` and the following sub-modules.
```
annotations
client
common
config
```
HDDS-11951
`hadoop-hdds/pom.xml`
```
[INFO] --- sortpom:3.0.1:verify (default) @ hdds ---
[INFO] Verifying file /Users/nvadivelu/Codebase/Github/ozone/hadoop-hdds/pom.xml
[ERROR] The line 55 is not considered sorted, should be '    <new.property.one>one</new.property.one>'
[ERROR] The file …
```
=> HDDS-11951. Enable sortpom in hadoop-hdds sub-modules : annotations, client, common & config.

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/BaseFileChecksumHelper.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/ECFileChecksumHelper.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/checksum/ReplicatedFileChecksumHelper.java
The `blockChecksumForDebug` would throw exception due to some of the checksum data is not a single CRC, it would be better to use `toMultiCrcString()` to avoid exception for debug information.
Please check [HDDS-8175](https://issues.apache.org/jira/browse/HDDS-8175) for more details, thanks.
- follow the [Command Line Interface](https://ozone.apache.org/docs/edge/interface/cli.html)
- create key `README.md` into  /vol1/bucket1/
```shell
ozone sh key put /vol1/bucket1/README.md README.md
```
- then verify the exception didn't throw in `DEBUG` mode after `checksum` command.
```shell
ozone sh key checksum /vol1/bucket1/README.md
```
The result is belowed, please take a look.
```shell
2025-01-01 12:08:15,364 [main] DEBUG checksum.CrcComposer: crcPolynomial=0x-12477ce0, …
```
=> HDDS-8175. getFileChecksum() throws exception in debug mode.

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/resources/webapps/ozoneManager/om-overview.html
In the Ozone Manager UI, it would be better to add leader readiness in it to provide more detail information. Please take a look, thanks and happy new year!
[HDDS-11726](https://issues.apache.org/jira/browse/HDDS-11726)
Please check the attachment to confirm.
=> HDDS-11726. Add leader readiness state to OM UI

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/RecoverSCMCertificate.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/RepairTool.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/ldb/SnapshotRepair.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/ldb/TransactionInfoRepair.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/om/FSORepairCLI.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/quota/QuotaTrigger.java
Introduce parent class for repair tools where common logic can be added later:
- Move up `out()` and `err()` from `RecoverSCMCertificate`
- Add methods to show informational and error messages
Additional minor cleanup:
- Ensure OM client is closed in `QuotaTrigger`
- Remove unused methods from `TransactionInfoRepair`
https://issues.apache.org/jira/browse/HDDS-12001
CI:
https://github.com/adoroszlai/ozone/actions/runs/12583280950
=> HDDS-12001. Create parent class for repair tools

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DecommissionSubCommand.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/HostNameParameters.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/MaintenanceSubCommand.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/RecommissionSubCommand.java
Reduce code duplication in decommission and maintenance subcommands.
- Specify `arity` to require at least one parameter, instead of checking explicitly.
- Extract duplicated "list of host names" parameter and logic.
- Reuse "show errors" logic.
https://issues.apache.org/jira/browse/HDDS-11990
Tested in `ozone-topology` env:
```
$ ozone admin datanode maintenance
Missing required parameter: '<host name>'
Usage: ozone admin datanode maintenance [-hV] [--force] [--end=<endInHours>]
[-id=<scmServiceId>] [--scm=<scm>]
<host name>...
Put a datanode into Maintenance Mode
<host name>...       One or more host names separated by spaces. To read
from stdin, specify '-' and supply the host names
separated by newlines.
--end=<endInHours>   Automatically end maintenance after the given hours.
By …
```
=> HDDS-11990. Use arity in decommission subcommands

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/OzoneRepair.java, hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/repair/TestOzoneRepair.java
- Skip the warning prompt when invoked without arguments or with help flags (`--help` or `-h`). The prompt is now displayed only if the command is about to execute an operation.
- Update the help message to emphasize that repair is an advanced operation requiring nodes to be stopped while it runs.
[HDDS-11945](https://issues.apache.org/jira/browse/HDDS-11945)
Tested the patch locally.
Before
```
bash-5.1$ ozone repair --help | -h
ATTENTION: Running as user hadoop. Make sure this is the same user used to run the Ozone process. Are you sure you want to continue (y/N)? y
Run as user: hadoop
Usage: ozone repair [-hV] [--verbose] [-conf=<configurationPath>]
[-D=<String=String>]... [COMMAND]
Operational tool to repair Ozone
-conf=<configurationPath>
-D, --set=<String=String>
-h, --help …
```
=> HDDS-11945. Improve startup message for ozone repair commands

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerStateManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerStateManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/states/ContainerStateMap.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/ContainerSafeModeRule.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/SCMSafeModeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/SafeModeExitRule.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestBlockManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestHealthyPipelineSafeModeRule.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestOneReplicaPipelineSafeModeRule.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestSCMSafeModeManager.java
ContainerSafeModeRule Refactor
Currently, the Safemode Rule validation is driven by processing of reports sent by Datanodes, this is unnecessary and this also introduces additional complexity as the `ContainerSafeModeRule` is maintaining the same information that the `ContainerManager` is maintaining.
Since the information about `Containers` are maintained at two different places, this can go out of sync and introduce bugs into `ContainerSafeModeRule` logic. (eg: [HDDS-5263](https://issues.apache.org/jira/browse/HDDS-5263))
We will move to a simpler model where `ContainerSafeModeRule` will not care about report processing but check `ContainerManager` to validate the rule.
This is part-1 of the change where we introduce logic to use `ContainerManager` for rule validation, this new logic is …
=> HDDS-11731. ContainerSafeModeRule Refactor.

hadoop-hdds/annotations/pom.xml, hadoop-hdds/container-service/pom.xml, hadoop-hdds/crypto-api/pom.xml, hadoop-hdds/crypto-default/pom.xml, hadoop-hdds/docs/pom.xml
Enable sortpom in hadoop-hdds sub-modules : annotations, client, common & config.
Sortpom plugin was added as part of #7555.
This PR enables the plugin for hadoop-hdds sub-modules. (part 2)
Sorting all the sub-modules under hadoop-hdds creates a big change, which will be hard to review. So, breaking this into multiple PRs.
This PR sorts pom of the following sub-modules.
- annotations
- client
- common
- config
HDDS-12006
`hadoop-hdds/container-service/pom.xml`
```
[INFO] --- sortpom:3.0.1:verify (default) @ hdds-container-service ---
[INFO] Verifying file /Users/nvadivelu/Codebase/Github/ozone/hadoop-hdds/container-service/pom.xml
[ERROR] The line 29 is not considered sorted, should be '    <property.one>one</property.one>'
[ERROR] The file …
```
=> HDDS-12006. Enable sortpom in hdds-container-service, hdds-crypto-api, hdds-crypto-default, hdds-docs

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockDataStreamOutput.java, hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/StreamBuffer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBlockDataStreamOutput.java
Unlike in Write Pipeline V1 writeChunk, XceiverClientMetrics#decrPendingContainerOpsMetrics is not called in the BlockDataStreamOutput#writeChunkToContainer which causes the pending ops to always increase.
https://issues.apache.org/jira/browse/HDDS-11998
Update `TestBlockDataStreamOutput` to check for `WriteChunk` `pendingContainerOpsMetrics`. Also slightly improve the tests.
=> HDDS-11998. XceiverClientMetrics#decrPendingContainerOpsMetrics should be called in BlockDataStreamOutput

hadoop-ozone/client/pom.xml, hadoop-ozone/common/pom.xml, hadoop-ozone/csi/pom.xml, hadoop-ozone/datanode/pom.xml, hadoop-ozone/dist/pom.xml, hadoop-ozone/fault-injection-test/pom.xml, hadoop-ozone/httpfsgateway/pom.xml, hadoop-ozone/insight/pom.xml, hadoop-ozone/integration-test/pom.xml, hadoop-ozone/interface-client/pom.xml, hadoop-ozone/interface-storage/pom.xml, hadoop-ozone/ozone-manager/pom.xml, hadoop-ozone/ozonefs-common/pom.xml, hadoop-ozone/ozonefs-hadoop2/pom.xml, hadoop-ozone/ozonefs-hadoop3-client/pom.xml, hadoop-ozone/ozonefs-hadoop3/pom.xml, hadoop-ozone/ozonefs-shaded/pom.xml, hadoop-ozone/ozonefs/pom.xml, hadoop-ozone/pom.xml, hadoop-ozone/recon-codegen/pom.xml, hadoop-ozone/recon/pom.xml, hadoop-ozone/s3-secret-store/pom.xml, hadoop-ozone/s3gateway/pom.xml, hadoop-ozone/tools/pom.xml
Enable sortpom in hadoop-ozone.
Sortpom plugin was added as part of #7555.
This PR enables the plugin for hadoop-ozone sub-modules.
Sorting all the sub-modules under hadoop-ozone creates a big change, which will be hard to review. So, breaking this into multiple PRs.
This PR sorts pom of hadoop-ozone.
HDDS-11952
`hadoop-ozone/pom.xml`
```
[INFO] --- sortpom:3.0.1:verify (default) @ ozone ---
[INFO] Verifying file /Users/nvadivelu/Codebase/Github/ozone/hadoop-ozone/pom.xml
[ERROR] The line 51 is not considered sorted, should be '    <property.one>one</property.one>'
[ERROR] The file /Users/nvadivelu/Codebase/Github/ozone/hadoop-ozone/pom.xml is not sorted
=> HDDS-11952. Enable sortpom in hadoop-ozone.

hadoop-hdds/client/pom.xml, hadoop-hdds/common/pom.xml, hadoop-hdds/container-service/pom.xml, hadoop-hdds/erasurecode/pom.xml, hadoop-hdds/framework/pom.xml, hadoop-hdds/hadoop-dependency-client/pom.xml
Enable sortpom in hdds-erasurecode, hdds-framework, hdds-hadoop-dependency-client
Sortpom plugin was added as part of #7555.
This PR enables the plugin for hadoop-hdds sub-modules. (part 2)
Sorting all the sub-modules under hadoop-hdds creates a big change, which will be hard to review. So, breaking this into multiple PRs.
This PR sorts pom of the following sub-modules.
- erasurecode
- framework
- hadoop-dependency-client
HDDS-12020
`hadoop-hdds/erasurecode/pom.xml`
```
[INFO] --- sortpom:3.0.1:verify (default) @ hdds-erasurecode ---
[INFO] Verifying file /Users/nvadivelu/Codebase/Github/ozone/hadoop-hdds/erasurecode/pom.xml
[ERROR] The line 29 is not considered sorted, should be '    <property.one>one</property.one>'
[ERROR] The file …
```
=> HDDS-12020. Enable sortpom in hdds-erasurecode, hdds-framework, hdds-hadoop-dependency-client.

hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServerConfigKeys.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/OzoneManagerServiceProviderImpl.java
This PR change is to update Recon OM Sync default configs values.
Default configs for recon om sync are recommended based on recent performance test and evaluation of recon om sync process and underlying tasks execution speed.
`Recommended configs default values:`
```
ozone.recon.om.snapshot.task.interval.delay -> 5s
recon.om.delta.update.limit -> 50000
recon.om.delta.update.loop.limit -> 50
```
Above are recommended and default configs for high write TPS workload in the range of approx 5k to achieve near real time sync between Recon and OM data.
https://issues.apache.org/jira/browse/HDDS-11949
Tested manually with existing Junit test cases.
=> HDDS-11949. Update Recon OM Sync default configs

hadoop-ozone/dist/src/shell/ozone/ozone, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/RepairTool.java
The check added in [HDDS-11727](https://issues.apache.org/jira/browse/HDDS-11727) only shows if the service is running. Show the PID of the process found to be running as well.
[HDDS-12011](https://issues.apache.org/jira/browse/HDDS-12011)
```
bash-5.1$ ozone repair om fso-tree --db /data/metadata/om.db
ATTENTION: Running as user hadoop. Make sure this is the same user used to run the Ozone process. Are you sure you want to continue (y/N)? y
Run as user: hadoop
Error: OM is currently running on this host with PID 7. Stop the service before running the repair tool.
```
```
bash-5.1$ ozone repair om fso-tree --db /data/metadata/om.db --force
ATTENTION: Running as user hadoop. Make sure this is the same user used to run the Ozone process. Are you sure …
```
=> HDDS-12011. Show PID of running service

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/duMetadata/duMetadata.tsx
HDDS-11987. Remove duplicate Quota In Bytes field from DU metadata
Currently the `/summary` endpoint provides a **Quota in Bytes** field which is the same as `/quota` endpoint **Quota Allowed** field.
We should use the /quota endpoint field only and remove the duplicate information we get from Quota in Bytes.
From the backend `quotaInBytes` is being set as a part of ObjectDBInfo class where is it set by the corresponding builder for bucket, volume. Refactoring this might cause breaking change, so we only remove the duplicate field from the UI as a part of this PR
https://issues.apache.org/jira/browse/HDDS-11987
=> HDDS-11987. Remove duplicate Quota In Bytes field from DU metadata

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestStorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/OzoneTestUtils.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestDeleteWithInAdequateDN.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestDeleteContainerHandler.java
Tests related to DeletedBlockLog needs to be tweaked to work with SCM Ratis enabled:
```
Error:  Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 225.079 s <<< FAILURE! - in org.apache.hadoop.ozone.container.common.statemachine.commandhandler.TestBlockDeletion
20468Error:  org.apache.hadoop.ozone.container.common.statemachine.commandhandler.TestBlockDeletion.testBlockDeleteCommandParallelProcess  Time elapsed: 45.39 s  <<< ERROR!
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 65.86 s <<< FAILURE! - in org.apache.hadoop.ozone.client.rpc.TestDeleteWithInAdequateDN
2897Error:  org.apache.hadoop.ozone.client.rpc.TestDeleteWithInAdequateDN.testDeleteKeyWithInAdequateDN  Time elapsed: 27.673 s  <<< FAILURE!
2898org.opentest4j.AssertionFailedError: …
```
=> HDDS-11989. Enable SCM Ratis in tests related to DeletedBlockLog

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestContainerCommandsEC.java
TestContainerCommandsEC needs to be tweaked to work with SCM Ratis enabled:
```
Error:  Tests run: 54, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 128.527 s <<< FAILURE! - in org.apache.hadoop.hdds.scm.storage.TestContainerCommandsEC
3244Error:  org.apache.hadoop.hdds.scm.storage.TestContainerCommandsEC.testOrphanBlock  Time elapsed: 34.199 s  <<< ERROR!
```
https://issues.apache.org/jira/browse/HDDS-12023
CI:
https://github.com/chungen0126/ozone/actions/runs/12621698130
=> HDDS-12023. Enable SCM Ratis in TestContainerCommandsEC

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestStorageContainerManager.java
TestStorageContainerManager needs to be tweaked to work with SCM Ratis enabled:
```
Error:  Tests run: 13, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 281.285 s <<< FAILURE! - in org.apache.hadoop.hdds.scm.TestStorageContainerManager
18332Error:  org.apache.hadoop.hdds.scm.TestStorageContainerManager.testOldDNRegistersToReInitialisedSCM  Time elapsed: 35.243 s  <<< ERROR! 
```
https://issues.apache.org/jira/browse/HDDS-12022
CI: https://github.com/chungen0126/ozone/actions/runs/12643884999
=> HDDS-12022. Enable SCM Ratis in TestStorageContainerManager

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerLayoutVersion.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueHandler.java
HDDS-11753. Deprecate file per chunk layout from datanode code.
* Mark FILE_PER_CHUNK as deprecated.
* Fallback to FILE_PER_BLOCK during DataNode startup if FILE_PER_CHUNK is configured.
https://issues.apache.org/jira/browse/HDDS-11753
Unit test; one test case was added.
=> HDDS-11753. Deprecate file per chunk layout from datanode code.

hadoop-hdds/interface-admin/pom.xml, hadoop-hdds/interface-client/pom.xml, hadoop-hdds/interface-server/pom.xml
Enable sortpom in hadoop-hdds-interface server, admin & client
Sortpom plugin was added as part of https://github.com/apache/ozone/pull/7555.
This PR enables the plugin for hadoop-hdds sub-modules. (part 5)
Sorting all the sub-modules under hadoop-hdds creates a big change, which will be hard to review. So, breaking this into multiple PRs.
This PR sorts pom of the following sub-modules.
- interface-server
- interface-admin
- interface-client
HDDS-12034
`hadoop-hdds/interface-server/pom.xml`
```
[INFO] --- sortpom:3.0.1:verify (default) @ hdds-interface-server ---
[INFO] Verifying file /Users/nvadivelu/Codebase/Github/ozone/hadoop-hdds/interface-server/pom.xml
[ERROR] The line 31 is not considered sorted, should be ' …
```
=> HDDS-12034. Enable sortpom in hadoop-hdds-interface server, admin & client

hadoop-ozone/dist/pom.xml, hadoop-ozone/dist/src/main/smoketest/s3/rclone.robot
This PR adds a robot test to validate the [rclone](https://rclone.org/s3/) tool with ozone
This PR depends on https://github.com/apache/ozone-docker-runner/pull/37 to install the rclone tool to the docker runner image
Although the default path to the rclone config works when running the robot test on the local machine, we explicitly use the `/tmp` dir to save the rclone config file as the default path is not writable when using the Github CI. 
https://issues.apache.org/jira/browse/HDDS-5045
Tested locally by running the robot test
~~CI will fail until https://github.com/apache/ozone-docker-runner/pull/37 is merged~~
CI: 
~~https://github.com/ptlrs/ozone/actions/runs/12306745127~~
~~https://github.com/ptlrs/ozone/actions/runs/12358744782~~ …
=> HDDS-5045. Create acceptance test for using rclone with s3 protocol

hadoop-ozone/dist/src/main/compose/common/s3-haproxy-secure.yaml, hadoop-ozone/dist/src/main/compose/ozone/docker-compose.yaml, hadoop-ozone/dist/src/main/compose/ozonesecure/test-haproxy-s3g.sh, hadoop-ozone/dist/src/main/compose/ozonesecure/test.sh, hadoop-ozone/dist/src/main/smoketest/s3/objectputget.robot
This PR:
1. Adds the docker compose setup where multiple secured S3 gateways sit behind HAProxy, a reverse-proxy.
2. Runs acceptance test for this secured S3 setup.
https://issues.apache.org/jira/browse/HDDS-7990
https://issues.apache.org/jira/browse/HDDS-12028
CI: 
~~https://github.com/ptlrs/ozone/actions/runs/12282892948~~
~~https://github.com/ptlrs/ozone/actions/runs/12302743602~~
~~https://github.com/ptlrs/ozone/actions/runs/12302743602~~
~~https://github.com/ptlrs/ozone/actions/runs/12656507658~~
https://github.com/ptlrs/ozone/actions/runs/12659812384
=> HDDS-7990. Add acceptance test to validate HA Proxy with secure Ozone S3 deployment

hadoop-ozone/dist/src/main/compose/common/s3-haproxy.cfg
HDDS-7307 and HDDS-7990 together cause [test failure](https://github.com/apache/ozone/actions/runs/12673824178/job/35321881300#step:7:14):
```
S3 Gateway Generate Secret                                            | FAIL |
7 != 0
...
```
The problem is that HA Proxy is not configured for the web admin port.
https://issues.apache.org/jira/browse/HDDS-12045
```
$ cd hadoop-ozone/dist/target/ozone-2.0.0-SNAPSHOT/compose/ozonesecure
$ ./test-haproxy-s3g.sh
...
s3-encrypted :: S3 Secret Generate test                                       
S3 Gateway Generate Secret                                            | PASS |
S3 Gateway Secret …
```
=> HDDS-12045. S3 secret admin test fails with HAProxy

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/OzoneAdmin.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/OzoneDebug.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/OzoneShell.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/Shell.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/s3/S3Shell.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/tenant/TenantShell.java
Subclasses of `Shell` override `execute()` to initialize tracing.  The goal of this task is to reduce this code duplication.
https://issues.apache.org/jira/browse/HDDS-12003
Started cluster in `ozone` compose environment with tracing enabled:
```
cd hadoop-ozone/dist/target/ozone-2.0.0-SNAPSHOT/compose/ozone
export COMPOSE_FILE=docker-compose.yaml:monitoring.yaml
OZONE_DATANODES=3 ./run.sh -d
```
Ran some commands in `ozone` compose environment with tracing enabled:
```
docker compose exec om bash
ozone freon ockg -n1 -t1 -p warmup
ozone sh key put /vol1/bucket1/passwd /etc/passwd
ozone admin container list
ozone s3 getsecret
```
Verified in Jaeger that traces got created:
CI:
https://github.com/adoroszlai/ozone/actions/runs/12649976634
=> HDDS-12003. Reduce code duplication related to tracing init

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneRepairShell.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/om/OMRepair.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/om/SnapshotChainRepair.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/om/TransactionInfoRepair.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/om/quota/QuotaRepair.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/om/quota/QuotaStatus.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/om/quota/QuotaTrigger.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/om/quota/package-info.java
`ozone repair om`
These commands make repairs to an individual OM instance.
- `ozone repair om quota`
The new location of `ozone repair quota` which is an online command (requires running OM).
- Add [HDDS-11727](https://issues.apache.org/jira/browse/HDDS-11727) check to see if OM is running in`ozone repair om snapshot chain` and `ozone repair om update-transaction`.
[HDDS-12039](https://issues.apache.org/jira/browse/HDDS-12039)
```
bash-5.1$ ozone repair om
ATTENTION: Running as user hadoop. Make sure this is the same user used to run the Ozone process. Are you sure you want to continue (y/N)? y
Run as user: hadoop
Usage: ozone repair om [COMMAND]
Operational tool to repair OM.
Commands:
fso-tree            Identify and …
```
=> HDDS-12039. Enhancements to ozone repair om commands

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/OzoneClientConfig.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/AbstractOzoneFileSystemTest.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
Return null when unsupported combine mode is passed and skip checksum compute.
https://issues.apache.org/jira/browse/HDDS-11969
Unit test
=> HDDS-11969. getFilechecksum() API fails if checksum type is NONE.

pom.xml
Bump `maven-remote-resources-plugin` to 3.3.0.  Fixes intermittent problem with build reproducibility (MRRESOURCES-150).
https://issues.apache.org/jira/browse/HDDS-12038
CI:
https://github.com/adoroszlai/ozone/actions/runs/12658002446
=> HDDS-12038. Bump maven-remote-resources-plugin to 3.3.0

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockDataStreamOutput.java, hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ByteBufferStreamOutput.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockDataStreamOutputEntry.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/BlockDataStreamOutputEntryPool.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/KeyDataStreamOutput.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/OzoneDataStreamOutput.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/io/OzoneOutputStream.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/client/io/SelectorOutputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemWithStreaming.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneFileSystem.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneFileSystem.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/CapableOzoneFSDataStreamOutput.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneFSDataStreamOutput.java, hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java, hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java, hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java, hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneBucketStub.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/OzoneDataStreamOutputStub.java
Support Ozone Streaming work with HSync and Hflush.
https://issues.apache.org/jira/browse/HDDS-11816
New integration test and existing test
=> HDDS-11816. Ozone stream to support Hsync,Hflush.

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/overviewCard/overviewStorageCard.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/storageBar/storageBar.less, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/storageBar/storageBar.tsx
HDDS-12036. Add storage indicators when reaching capacity
* Currently in Recon we do not have any quick indication for whether the storage is reaching it's capacity or not. This followed by the fact that Ozone storage is indicated by green colour is misleading.
* As a part of this we make two main changes:
* On the Overview page we are adding a red border
* In the tables, the "storage bar" progress-bar and percentage text will turn red when storage is almost full.
* The limit for the indication is set to above 80% i.e. when the storage is above 80% full, the above indicators will be shown.
* We also remove the older separation of colors for the progress-bar for different category of capacity usage and instead formatting the tooltip to clearly show the …
=> HDDS-12036. Add storage indicators when reaching capacity

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/scm/SCMRepair.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/scm/cert/CertRepair.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/scm/cert/RecoverSCMCertificate.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/scm/cert/package-info.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/scm/package-info.java
`ozone repair scm` -  These commands make repairs to an individual SCM instance.
- `ozone repair scm cert`
A dedicated subcommand for all certificate related repairs on SCM we may need now or in the future.
- `ozone repair scm cert recover`
The new location of `ozone repair cert-recover`
[HDDS-12041](https://issues.apache.org/jira/browse/HDDS-12041)
```
bash-5.1$ ozone repair scm
...
Usage: ozone repair scm [COMMAND]
Operational tool to repair SCM.
Commands:
cert  Subcommand for all certificate related repairs on SCM
```
```
bash-5.1$ ozone repair scm cert recover
...
Missing required option: '--db=<dbPath>'
Usage: ozone repair scm cert recover [-hV] [--force] --db=<dbPath>
Recover Deleted SCM Certificate from RocksDB
--db=<dbPath>   SCM DB Path …
```
=> HDDS-12041. Add ozone repair scm cert command and its subcommand

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/components/overviewCard/overviewCard.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/pages/overview/overview.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/overview/overview.tsx
HDDS-12049. Rename OM ID and OM Service ID to Ozone Service ID.
* Currently in Recon UI we show the Service ID as OM ID and OM Service.
* Both of the above is misleading - OM ID and Ozone Service ID are different and so we should show it properly i.e Ozone Service ID
* This PR addresses this issue.
https://issues.apache.org/jira/browse/HDDS-12049
Old UI:
New UI:
=> HDDS-12049. Rename OM ID and OM Service ID to Ozone Service ID.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemPrefixParser.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/om/OMDebug.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/om/PrefixParser.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/om/package-info.java
The prefix subcommand only works on OM using the FSO namespace so it should be under the om subcommand.
[HDDS-12054](https://issues.apache.org/jira/browse/HDDS-12054)
Tested the patch on a docker cluster and through `TestOzoneFileSystemPrefixParser.java`
```
bash-5.1$ ozone debug om
Usage: ozone debug om [COMMAND]
Runs OM related subcommands.
Commands:
prefix  Parse prefix contents
```
```
bash-5.1$ ozone debug om prefix
Missing required options: '--db=<dbPath>', '--path=<filePath>', '--bucket=<bucket>', '--volume=<volume>'
Usage: ozone debug om prefix --bucket=<bucket> --db=<dbPath> --path=<filePath>
--volume=<volume>
Parse prefix contents
--bucket=<bucket>   bucket name
--db=<dbPath>       Database File Path
--path=<filePath>   prefixFile Path …
```
=> HDDS-12054. Move ozone debug prefix to ozone debug om prefix

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/select/multiSelect.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/pages/datanodes/datanodes.tsx
HDDS-12043. Mark fixed column with disabled checkbox.
* In MultiSelect component, we pass a `fixedColumn` prop which decides the menu option which should not be selectable. This is useful to make table have at-least one column fixed even if other columns are deselected.
* But in the current implementation this disabled option is rendered with an active checkbox causing the confusion that the option is selectable.
* This PR modifies the option passed to have isDisabled explicitly set for fixedColumn and use that as the options to the menu.
* This will render the fixedColumn with a grey disabled checkbox, which provides proper feedback to the user that the column is not selected/fixed.
https://issues.apache.org/jira/browse/HDDS-12043
Patch was tested …
=> HDDS-12043. Mark fixed column with disabled checkbox

hadoop-ozone/dist/src/main/smoketest/compatibility/dn-one-rocksdb.robot, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/datanode/DatanodeDebug.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/datanode/container/ContainerCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/datanode/container/ExportSubcommand.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/datanode/container/InfoSubcommand.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/datanode/container/InspectSubcommand.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/datanode/container/ListSubcommand.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/datanode/container/package-info.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/datanode/package-info.java
The `container` subcommand and all commands under it run locally on a datanode, so they should be moved under the `datanode` subcommand.
[HDDS-12055](https://issues.apache.org/jira/browse/HDDS-12055)
```
bash-5.1$ ozone debug datanode 
Usage: ozone debug datanode [COMMAND]
Runs datanode related subcommands.
Commands:
container  Container replica specific operations to be executed on datanodes
only
```
```
bash-5.1$ ozone debug datanode container
Usage: ozone debug datanode container [-hV] [COMMAND]
Container replica specific operations to be executed on datanodes only
-V, --version   Print version information and exit.
Commands:
list     Show …
```
=> HDDS-12055. Move ozone debug container to ozone debug datanode container

hadoop-hdds/docs/content/integration/Hive.md, hadoop-hdds/docs/content/integration/_index.md
HDDS-11962. [Docs] Hive Integration
* Add a simple user guide for Hive users to access Ozone.
* This doc is built on top of #7588. Will rebase once the DistCp user doc is merged.
https://issues.apache.org/jira/browse/HDDS-11947
./hadoop-ozone/dev-support/checks/docs.sh passed.
=> HDDS-11962. [Docs] Hive Integration

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/cli/GenericCli.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManagerStarter.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/conf/OzoneGetConf.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/genconf/GenerateOzoneRequiredConfigurations.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/Shell.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/checknative/CheckNative.java, hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/conf/TestGetConfOptions.java
picocli allows setting custom out/err streams to [make testing easier](https://picocli.info/#_black_box_and_white_box_testing).  This PR updates subclasses of `GenericCli` (except `OzoneRepair`, which is being changed in #7653) to use these custom streams instead of `System.out/err`.  (Further PRs will take care of sets of subcommands to avoid too large patches.)
https://issues.apache.org/jira/browse/HDDS-12058
Tested some of the commands manually:
```
$ bin/ozone getconf -Dasdf=qwerty confKey asdf
qwerty
$ bin/ozone checknative                       
Native library checking:
hadoop:  false 
ISA-L:   false 
rocks-tools: false 
$ bin/ozone genconf /tmp
ozone-site.xml has been generated at /tmp
```
CI:
https://github.com/adoroszlai/ozone/actions/runs/12697388661
=> HDDS-12058. Use CommandLine out/err in GenericCli subclasses

hadoop-hdds/managed-rocksdb/pom.xml, hadoop-hdds/rocks-native/pom.xml, hadoop-hdds/rocksdb-checkpoint-differ/pom.xml, hadoop-hdds/server-scm/pom.xml, hadoop-hdds/test-utils/pom.xml, hadoop-hdds/tools/pom.xml
Sort POM for remaining modules in `hadoop-hdds`:
- `managed-rocksdb`
- `rocksdb-checkpoint-differ`
- `rocks-native`
- `server-scm`
- `test-utils`
- `tools`
https://issues.apache.org/jira/browse/HDDS-12068
https://github.com/adoroszlai/ozone/actions/runs/12725284390
=> HDDS-12068. Enable sortpom in remaining hdds modules

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/cli/AbstractSubcommand.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/container/UpgradeSubcommand.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneTenantShell.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/ldb/DBScanner.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/ldb/ValueSchema.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/RepairTool.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/Handler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/OzoneAddress.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/acl/AclOption.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/snapshot/SnapshotDiffHandler.java
`out()` and `err()` methods are defined in few different subcommands, it would be better to move it up to `AbstractSubcommand` to reduce code duplication. Please take a look, thanks.
[HDDS-12002](https://issues.apache.org/jira/browse/HDDS-12002)
It can test by integration tests.
=> HDDS-12002. Move up out() and err() to AbstractSubcommand

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/components/overviewCard/overviewCard.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/overviewCard/overviewStorageCard.tsx
HDDS-12042. Fix capacity count for cluster capacity card.
* In the new vs old UI we have a discrepancy in the details of the cluster capacity card.
* Mismatch between the Capacity report percentage:
* In the new UI we are calculating the percentage for the Overview page storage guage chart by choosing the floor value.
* In the old UI this is done as the rounded value.
* We are changing the new UI to use the rounded value instead of floor.
* Mismatch between the Pre-allocated size:
* In the new UI we are making use of the committed field from the storage report response.
* In the old UI we are not passing this value to StorageBar component, hence it is picking default value of 0.
* We should change the old UI to make use of the committed size. …
=> HDDS-12042. Fix capacity count for cluster capacity card.

hadoop-ozone/insight/pom.xml, hadoop-ozone/s3-secret-store/pom.xml, hadoop-ozone/s3gateway/pom.xml, hadoop-ozone/tools/pom.xml
Sort POM in `hadoop-ozone` submodules:
- `insight`
- `s3-secret-store`
- `s3gateway`
- `tools`
https://issues.apache.org/jira/browse/HDDS-12074
https://github.com/adoroszlai/ozone/actions/runs/12753377831
=> HDDS-12074. Enable sortpom in ozone-insight, s3-secret-store, s3gateway and tools

.github/workflows/ci.yml, hadoop-ozone/dist/src/main/compose/common/s3a-test.sh
`acceptance` and some other checks fail intermittently (when run with Maven 3.9.9, [example](https://github.com/apache/ozone/actions/runs/12770988974/job/35597951560#step:6:5238)) due to:
- Maven 3.9.x automatically picks up options from `MAVEN_ARGS` variable.
- With `--show-version`, version is shown in the output, even with `--quiet`.
- Property queries from POM (e.g. `ozone.version`) rely on only the value being output.
- GitHub started gradual roll-out of runners with Maven 3.9.9.
This fix removes `--show-version` from global `MAVEN_ARGS` to avoid unwanted content in output of property queries.
https://issues.apache.org/jira/browse/HDDS-12082
CI:
https://github.com/adoroszlai/ozone/actions/runs/12772268115
=> HDDS-12082. CI checks fail with Maven 3.9.9

hadoop-ozone/dist/src/main/compose/ozone/test.sh, hadoop-ozone/dist/src/main/smoketest/admincli/lease-recovery.robot, hadoop-ozone/dist/src/main/smoketest/compatibility/read.robot, hadoop-ozone/dist/src/main/smoketest/debug/ozone-debug.robot, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestLeaseRecoverer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/admin/om/lease/TestLeaseRecoverer.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/OMAdmin.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/lease/LeaseRecoverer.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/lease/LeaseSubCommand.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/om/lease/package-info.java
The `ozone debug recover` command that is currently used for lease recovery has a few problems:
- It modifies the cluster, so it should not be under `debug`.
- The name does not specify that it deals with leases.
- It uses a standard API from the `FileSystem` interface unlike other low level tools in this package.
The command is unique because it goes through the `FileSystem` interface but is not exposed through the `fs` command line in Hadoop or Ozone. For these reasons, we propose moving this command to its own Ozone subcommand: `ozone admin om lease recover`. This also allows other lease related subcommands (like querying of existing leases) to be added in the future.
[HDDS-12029](https://issues.apache.org/jira/browse/HDDS-12029)
```
bash-5.1$ …
```
=> HDDS-12029. Move ozone debug recover to ozone admin om lease recover

.github/workflows/ci.yml, .github/workflows/intermittent-test-check.yml, .github/workflows/repeat-acceptance.yml, .mvn/develocity.xml, .mvn/extensions.xml
This PR migrates the Ozone project to publish Build Scans to the the new Develocity instance at develocity.apache.org.
Additionally, this PR sets a projectId for use by Develocity.
https://issues.apache.org/jira/browse/HDDS-12083
N/A
=> HDDS-12083. Publish build scans to develocity.apache.org

hadoop-ozone/dist/src/main/compose/testlib.sh, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneDebugShell.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/replicas/ReplicasDebug.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/replicas/chunk/ChunkDataNodeDetails.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/replicas/chunk/ChunkDetails.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/replicas/chunk/ChunkKeyHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/replicas/chunk/ChunkType.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/replicas/chunk/ContainerChunkInfo.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/replicas/chunk/package-info.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/replicas/package-info.java
The `ozone debug replicas` subcommand is being added to handle commands for online debugging of data replicas. The existing `chunkinfo` command should be moved here.
[HDDS-12056](https://issues.apache.org/jira/browse/HDDS-12056)
```
bash-5.1$ ozone debug replicas
Usage: ozone debug replicas [COMMAND]
Debug commands for replica-related issues, retrieving replica information from
the OM and performing checks over the network against a running cluster.
Commands:
chunk-info  Returns chunk location information about an existing key
```
```
bash-5.1$ ozone debug replicas chunk-info /vol1/bucket1/key1
{
"KeyLocations" : [ [ {
"Locations" : {
"files" : [ "/data/hdds/hdds/CID-7aa01916-51f0-4222-b8fc-7e9150f4fa94/current/containerDir0 …
```
=> HDDS-12056. Move ozone debug chunkinfo to ozone debug replicas chunk-info

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMDBCheckpointServlet.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotManager.java
Currently while checking file links, the exclude sst file list & files already present in the current tarball is checked in the entries by sequentially iterating through the entries, for each and every file in the om data directory (snapshot directory, active om.db, compaction backup sst file). Now if the exclude list or files present in the tarball is really long order of 1000s and the total number of sst files are in the order of millions, the bootstrap is going to read timeout and might take hours. We need to optimize and not perform this unnecessary iteration to avoid this n^2 operation and do it in O
https://issues.apache.org/jira/browse/HDDS-12064
Existing unit tests modification
=> HDDS-12064. Optimize bootstrap logic to reduce loop while checking file links

hadoop-ozone/recon-codegen/pom.xml, hadoop-ozone/recon/pom.xml
Sort POM in submodules related to Recon:
- `ozone-recon`
- `ozone-recon-codegen`
https://issues.apache.org/jira/browse/HDDS-12092
CI:
https://github.com/adoroszlai/ozone/actions/runs/12803472654
=> HDDS-12092. Enable sortpom in Recon

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestStorageContainerManager.java
Speed up `TestStorageContainerManager` by combining test to reduce cluster creation time.
Before:
```
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 331.957 s - in org.apache.hadoop.hdds.scm.TestStorageContainerManager
```
After:
```
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 180.093 s - in org.apache.hadoop.hdds.scm.TestStorageContainerManager
```
https://issues.apache.org/jira/browse/HDDS-12088
CI:
https://github.com/adoroszlai/ozone/actions/runs/12793512097
=> HDDS-12088. Speed up TestStorageContainerManager

hadoop-ozone/client/pom.xml, hadoop-ozone/common/pom.xml, hadoop-ozone/csi/pom.xml, hadoop-ozone/datanode/pom.xml
Enable sortpom in hadoop-ozone client, common, csi and datanode.
HDDS-12021
CI : [12844555209](https://github.com/nandakumar131/ozone/actions/runs/12844555209)
=> HDDS-12021. Enable sortpom in hadoop-ozone client, common, csi and datanode.

hadoop-ozone/ozonefs-common/pom.xml, hadoop-ozone/ozonefs-hadoop2/pom.xml, hadoop-ozone/ozonefs-hadoop3-client/pom.xml, hadoop-ozone/ozonefs-hadoop3/pom.xml, hadoop-ozone/ozonefs-shaded/pom.xml, hadoop-ozone/ozonefs/pom.xml
Sort POM in the following submodules of `hadoop-ozone`:
- `ozonefs`
- `ozonefs-common`
- `ozonefs-hadoop2`
- `ozonefs-hadoop3-client`
- `ozonefs-hadoop3`
- `ozonefs-shaded`
https://issues.apache.org/jira/browse/HDDS-12104
CI:
https://github.com/adoroszlai/ozone/actions/runs/12845330637
=> HDDS-12104. Enable sortpom in ozonefs modules

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/utils/common.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/duMetadata/duMetadata.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/pages/overview/overview.tsx
HDDS-12016. Fixed duplicate entries when changing path in DU page
**Previously**:
* The Disk Usage metadata details are not being set properly. We are using an array of keys and an array of values as the data for metadata table from which we generate the table data by mapping.
* So if we change the path, specially while viewing the quota related details in the table i.e change table page and then change path - rows from second page will be repeated in the new path metadata causing it to be flaky.
* We made separate calls to the summary and quota APIs and set the state twice. This causes issues with syncing up state as APIs might return in different times.
**As a part of this PR**:
*  We are going to use an array of objects to avoid recalculation of data …
=> HDDS-12016. Fixed duplicate entries when changing path in DU page

pom.xml
Stop spending time analyzing generated code when validating import restrictions.  Saves around 6 seconds, which is not much for a normal build, but about 10% for local build when skipping tests.
https://issues.apache.org/jira/browse/HDDS-12093
```bash
mvn -DskipShade -DskipTests -Dskip.installnodenpm -Dskip.npx
```
Before:
```
[INFO] Apache Ozone HDDS Client Interface ................. SUCCESS [  5.458 s]
[INFO] Apache Ozone HDDS Admin Interface .................. SUCCESS [  1.606 s]
[INFO] Apache Ozone HDDS Server Interface ................. SUCCESS [  2.077 s]
[INFO] Apache Ozone Client Interface ...................... SUCCESS [ 11.998 s]
[INFO] Apache Ozone Storage Interface ..................... SUCCESS [  0.367 s]
```
After:
```
[INFO] Apache Ozone HDDS Client Interface …
```
=> HDDS-12093. Exclude generated code when verifying import restrictions

hadoop-hdds/docs/themes/ozonedoc/static/swagger-resources/recon-api.yaml
HDDS-11300. Update Swagger documentation for Recon APIs
The below API endpoints are missing from the swagger specification.
> GET /api/v1/volumes: Fetches all volumes in the cluster.
GET /api/v1/buckets: Fetches all buckets in the cluster.
GET /api/v1/containers/deleted: Fetches all the deleted containers in the cluster.
GET /api/v1/keys/open/summary: Fetches the summary of open keys in the cluster.
GET /api/v1/keys/deletePending/summary: Fetches the summary of keys pending deletion in the cluster.
GET /api/v1/keys/deletePending/dirs/summary: Fetches the summary of the dirs pending deletion in the cluster.
GET /api/v1/datanodes/decommission/info: Fetches the info about all datanodes being decommissioned in the cluster.
GET /api/v1/datanodes/decommission/info/datanode: Fetches the info …
=> HDDS-11300. Update Swagger documentation for Recon APIs

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/debug/TestLDBCli.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/ldb/RDBParser.java
```
ozone debug ldb --db <db> <subcommand> [other options]
```
Currently `--db` is accepted only directly after `ldb`, before any subcommand name or options.  The goal of this PR is to improve usability by allowing `--db` after subcommand or even after other options.
https://issues.apache.org/jira/browse/HDDS-12086
Updated integration test to cover three different positions of the option.
CI:
https://github.com/adoroszlai/ozone/actions/runs/12807326607
=> HDDS-12086. Allow --db option at leaf subcommand in debug tools

hadoop-ozone/recon/pom.xml, pom.xml
Build fails when files from `hadoop-ozone/dist/src/main/compose` (or similar directories) are open in VI due to the binary swap files it creates:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.3.0:copy-resources (copy-compose-files) on project ozone-dist: filtering hadoop-ozone/dist/src/main/compose/restart/.docker-compose.yaml.swp to hadoop-ozone/dist/target/compose/restart/.docker-compose.yaml.swp failed with MalformedInputException: Input length = 1 -> [Help 1]
```
This patch disables resource filtering for `.swp` files.  It also moves definition of non-filtered extensions to the root POM, so that it applies to all submodules, without having to duplicate.
https://issues.apache.org/jira/browse/HDDS-12124
```
gvim …
```
=> HDDS-12124. Disable resource filtering for VI swap files

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/ReadReplicas.java
Key names may include arbitrary number of `/` characters, such as `/volumename/bucketname/test1/test2`.
The read-replicas command assumes key names will be single level or not include any `/` characters. This results in failures when the command is run on multilevel keys.
This PR flattens the keynames by replacing `/` with `_`.
https://issues.apache.org/jira/browse/HDDS-12075
Also see discussion in https://github.com/apache/ozone/pull/7693
Manual testing:
```bash
bash-5.1$ ozone debug --verbose read-replicas /ockrwvolume/ockrwbucket/test1/test2/1
Volume Name : ockrwvolume
Bucket Name : ockrwbucket
Key Name : test1/test2/1
Creating directory : ockrwvolume_ockrwbucket_test1_test2_1_20250122073427
Successfully created!
Writing : test1_test2_1_block1_ozone-datanode-1.ozone_default
Writing …
```
=> HDDS-12057. Handle '/' in key names for the readreplicas command

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/repair/om/TestFSORepairTool.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneRepairShell.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/ReadOnlyCommand.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/RepairTool.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/om/FSORepairTool.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/om/SnapshotChainRepair.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/om/TransactionInfoRepair.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/om/quota/QuotaStatus.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/om/quota/QuotaTrigger.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/scm/cert/RecoverSCMCertificate.java, hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/repair/TestOzoneRepair.java, hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/repair/om/TestTransactionInfoRepair.java
1. Add `--dry-run` option to all `ozone repair` subcommands that modify state.  The new option currently defaults to `false`, so commands _perform repair by default_.  (Otherwise we'd need to use it as `--dry-run=false`.)
2. Implement dry-run mode where needed.
https://issues.apache.org/jira/browse/HDDS-11946
Added unit test to verify that each subcommand under `ozone repair` satisfies one of the following:
- has subcommands
- has `--dry-run` option
- implements `ReadOnlySubcommand` (currently only `QuotaStatus`)
Test failure before implementing `ReadOnlyCommand` in `QuotaStatus`:
```
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.261 s <<< FAILURE! - in org.apache.hadoop.ozone.repair.TestOzoneRepair
[ERROR] …
```
=> HDDS-11946. Require all ozone repair commands to support a --dry-run option

hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - OMComittedIndexMetrics.json
Having a chart to visualize peercommitindex of OMs would help to understand whether followers are lagging behind leader and also helps with troubleshooting OM bootstrapping issues
I added Ozone - OMComittedIndexMetrics.json file to the dashboards 
https://issues.apache.org/jira/browse/HDDS-12108
Tested in my local cluster manually. Attached screenshot to the jira.
=> HDDS-12108. Grafana Dashboard for OM CommitIndex

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/contract/AbstractContractGetFileStatusTest.java
`Assertions.assertThat` is overloaded, returning different assertion object depending on the argument.  Passing an instance of raw `Comparable` results in compile error.  Hadoop's `Path` used to implement raw `Comparable` before it was parameterized in HADOOP-16196.  Thus, compiling Ozone with old Hadoop that does not have HADOOP-16196 fails.
```
[ERROR] hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/contract/AbstractContractGetFileStatusTest.java:[404,13] cannot find symbol
symbol:   method isEqualTo(org.apache.hadoop.fs.Path)
location: class java.lang.Object
```
This can be improved by using more specific assertion factory method (e.g. `assertThatObject`).
https://issues.apache.org/jira/browse/HDDS-12130
CI:
https://github.com/adoroszlai/ozone/actions/runs/12929097463
=> HDDS-12130. Improve assertion compatibility with old Hadoop

hadoop-ozone/dist/src/main/smoketest/s3/MultipartUpload.robot, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3MultipartUploadCompleteResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3MultipartUploadCompleteResponseWithFSO.java
S3MultipartUploadCompleteRequestWithFSO seems to throw NPE when an empty file is being overwritten by non-zero file because omBucketInfo allows null value (null value is passed when non-update needed). This patch fix this by checking omBucketInfo before use.
https://issues.apache.org/jira/browse/HDDS-12131
I've added annotation for `@Nullable`.
Local compilation are passed and it'll be checked by CI. Let me know if more tests are suggested.
=> HDDS-12131. Overwrite an empty file with multipart-upload throws NPE

hadoop-ozone/dist/src/main/compose/common/replicas-test.sh, hadoop-ozone/dist/src/main/compose/ozone/test.sh, hadoop-ozone/dist/src/main/compose/testlib.sh
Acceptance test for `ozone debug read-replicas` is defined in `testlib.sh` to allow running in different compose environments.  Since it's not a generic funtion for all acceptance tests, this PR moves it out to a test script in `common`, which can also be reused.
https://issues.apache.org/jira/browse/HDDS-12089
CI:
https://github.com/adoroszlai/ozone/actions/runs/12937429292
=> HDDS-12089. Move execute_debug_tests out of testlib.sh

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/ContainerLayoutTestInfo.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestChunkInputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestInputStreamBase.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/read/TestKeyInputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestFinalizeBlock.java
Problem:
`TestChunkInputStream` and `TestKeyInputStream` repeat tests with default container layout, instead of testing with both `FILE_PER_BLOCK` and `FILE_PER_CHUNK`.
Causes:
- The tests set wrong string representation of the configured container layout (since HDDS-4552).  Test cluster always falls back to the default layout, `FILE_PER_BLOCK`.
- `KeyValueHandler` does not allow creating containers with `FILE_PER_CHUNK` layout, even if configured correctly (since HDDS-11753).
Fix:
- Change the tests to start the cluster only once, with the default layout.
- Set the layout in datanode configs right before creating data.
- Close existing containers afterwards, to ensure each test writes data to new container, created with the layout being tested. …
=> HDDS-12081. TestKeyInputStream repeats tests with default container layout

hadoop-ozone/dev-support/checks/install/hugo.sh
Bump Hugo to latest, 0.141.0.
Tweak artifact `arch` and `os` based on assets found at https://github.com/gohugoio/hugo/releases/tag/v0.141.0
https://issues.apache.org/jira/browse/HDDS-12098
```
Installed hugo in /home/runner/work/ozone/ozone/.dev-tools/hugo
...
hugo v0.141.0-e7bd51698e5c3778a86003018702b1a7dcb9559a linux/amd64 BuildDate=2025-01-16T13:11:18Z VendorInfo=gohugoio
```
https://github.com/adoroszlai/ozone/actions/runs/12892096067/job/35945572356
=> HDDS-12098. Bump Hugo to 0.141.0

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/AbstractOverReplicationHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/RatisOverReplicationHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestRatisOverReplicationHandler.java
When RM selects nodes to delete replicas from, it sorts the replicas by datanode UUID and then iterates the list. If a node is overloaded when it is selected for delete, then rather than holding that delete for later, it skips it and tries the next replica in the list. This can result in non-deterministic delete selection, which we want to avoid.
This PR changes that, so that the original replica is no longer skipped, but will be tried again on the next iteration.
https://issues.apache.org/jira/browse/HDDS-12115
A couple of new mis-replication tests added and a test which started failing after the change was modified to reflect the new intended behavior.
=> HDDS-12115. RM selects replicas to delete non-deterministically if nodes are overloaded

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java
We recently found that delete commands can run for a long time once picked off the queue, and the default of a 10 minute deadline on SCM and 30 seconds less deadline on the datanodes can result in currently running commands being seen as expired in SCM.
This PR is to make the defaults less aggressive - giving a SCM / RM timeout of 12 minutes and a datanode timeout of 6 minutes. That way, there is longer for commands to be processed before RM will resend them.
With the throttling that RM employs, there should not be a large number of commands on the queue anyway, as the goal of RM is to schedule only the number of commands which can be processed in a heartbeat or two.
Other related Jiras to this one are: [HDDS-12127](https://issues.apache.org/jira/browse/HDDS-12127), …
=> HDDS-12135. Set RM default deadline to 12 minutes and the datanode offset to 6 minutes

hadoop-ozone/dev-support/checks/kubernetes.sh, hadoop-ozone/dist/dev-support/bin/dist-layout-stitching, hadoop-ozone/dist/pom.xml, hadoop-ozone/dist/src/main/compose/testlib.sh, hadoop-ozone/dist/src/main/k8s/examples/testlib.sh, hadoop-ozone/dist/src/main/smoketest/.env, hadoop-ozone/dist/src/main/smoketest/testlib.sh, pom.xml
Similar to [HDDS-11105](https://issues.apache.org/jira/browse/HDDS-11105), generate report for Robot tests by running rebot in ozone-runner container. This reduces the number of dependencies that have to be installed locally for running tests in Kubernetes environment. Please take a look, thanks!
[HDDS-12099](https://issues.apache.org/jira/browse/HDDS-12099)
It can be tested by CI (downloading artifacts)
https://github.com/chiacyu/ozone/actions/runs/12976631919
=> HDDS-12099. Generate kubernetes Robot report in container

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/app.tsx
HDDS-12084. Persist currently selected UI type after refresh
* Currently the state of the UI that is selected i.e old or new is lost if we refresh the page.
* This PR uses the session storage to store the selection state and persist it across refresh.
* Session storage will persist the state for existing session (i.e when page is visited) and clear when page is closed ensuring we do keep the data even after we close the page.
https://issues.apache.org/jira/browse/HDDS-12084
https://github.com/user-attachments/assets/0159e1ca-ebd6-403e-b9f7-034336a2f022
=> HDDS-12084. Persist currently selected UI type after refresh

hadoop-ozone/dist/src/main/smoketest/basic/links.robot, hadoop-ozone/dist/src/main/smoketest/basic/ozone-shell-lib.robot, hadoop-ozone/dist/src/main/smoketest/ozone-lib/shell.robot, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/REPL.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/shell/Shell.java
Support batch mode in Ozone CLI subcommands which already have `--interactive` mode enabled, by adding repeatable `--execute <cmd>` option.
This allows running multiple commands with the same invocation, like:
```
ozone sh \
--execute 'volume create /vol1' \
--execute 'bucket create /vol1/bucket1'
```
Update Robot tests to utilize batch mode in few test cases.
(Initially I wanted to use input redirection.  It is still supported, but Robot tests are not great with here-docs.)
Also fix a warning from `TailTipWidgets` when running without TTY.
https://issues.apache.org/jira/browse/HDDS-11837
CI:
https://github.com/adoroszlai/ozone/actions/runs/12871125080
=> HDDS-11837. Support executing multiple commands in Ozone CLI

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerReplicaOp.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerReplicaPendingOps.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ECUnderReplicationHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestMoveManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestContainerReplicaPendingOps.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestECContainerReplicaCount.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManagerScenarios.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java
When RM schedules a delete of a container on a datanode, it should keep track of that delete until either:
1. A ICR / FCR is received which confirms the container is removed.
2. The datanode goes dead.
Currently, RM expires the delete attempt after 10 minutes and while it should resend the command to the same datanode on retry it may not (eg [HDDS-12115](https://issues.apache.org/jira/browse/HDDS-12115)) or in other scenarios that cause the datanode ordering to change.
With this change, the expiry still occurs and the command can get dropped on the datanode, but in the ContainerReplicaPendingOps expiry thread, it no long removes the pending delete from the pending list. Instead it will trigger a notification to RM which will then resend the same command with a new deadline until it has …
=> HDDS-12127. RM should not expire pending deletes, but retry until the delete is confirmed or node is dead

hadoop-hdds/framework/pom.xml, hadoop-hdds/hadoop-dependency-client/pom.xml, hadoop-hdds/server-scm/pom.xml, hadoop-ozone/common/pom.xml, hadoop-ozone/httpfsgateway/pom.xml
Most Hadoop dependencies are used via helper modules `hadoop-hdds/hadoop-dependency-*` (added in HDDS-3312).  However, `hadoop-hdfs-client` is used directly in several modules.  It should be added to `hadoop-dependency-client`, on which Ozone modules should depend.
https://issues.apache.org/jira/browse/HDDS-12141
CI:
https://github.com/adoroszlai/ozone/actions/runs/12989998157
=> HDDS-12141. Replace direct dependency on hadoop-hdfs-client

hadoop-ozone/ozonefs-hadoop3-client/pom.xml
I tried running Trino together with Ozone over OFS but encountered a Protobuf shading incompatibility between the [Trino Hadoop library](https://github.com/trinodb/trino-hadoop-apache/tree/master) and the Ozone Hadoop client:
```
2024-12-27T09:09:30.178Z    DEBUG   hive-hive-0     org.apache.hadoop.fs.ozone.BasicRootedOzoneFileSystem   Ozone URI for OFS initialization is ofs://ozone-om-1
2024-12-27T09:09:30.183Z    WARN    hive-hive-0     org.apache.hadoop.ozone.om.helpers.OzoneFSUtils Ignoring ozone.fs.hsync.enabled = true because HBase enhancements are disallowed. To enable it, set ozone.client.hbase.enhancements.allowed = true as well.
2024-12-27T09:09:30.184Z    DEBUG   hive-hive-0     org.apache.hadoop.fs.ozone.BasicRootedOzoneFileSystem   hsyncEnabled = false …
```
=> HDDS-12116. Customizable Protobuf shaded prefix in ozonefs-hadoop3-client.

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/RepairTool.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/TransactionInfoRepair.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/om/FSORepairTool.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/om/SnapshotChainRepair.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/scm/cert/RecoverSCMCertificate.java
Offline repair tools check if Ozone service, e.g. OM is running.  This PR centralizes the check, so that tools only need to declare which service they apply to.
https://issues.apache.org/jira/browse/HDDS-12010
https://github.com/adoroszlai/ozone/actions/runs/12986816805
@sarvekshayr @Tejaskriya
=> HDDS-12010. Refactor check for running service in ozone repair

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/fs/SpaceUsageSource.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/DbVolume.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/HddsVolume.java
This aims to provide slightly more info to identify issues like completely full volumes.
Related: [HDDS-12151](https://issues.apache.org/jira/browse/HDDS-12151) and [HDDS-12150](https://issues.apache.org/jira/browse/HDDS-12150).
https://issues.apache.org/jira/browse/HDDS-12162
- Verified in the test output that available (and used) space is now printed. e.g.:
- `TestHddsVolume#testOverUsedReservedSpace`:
```
2025-01-29 15:35:02,159 [main] INFO  volume.HddsVolume (HddsVolume.java:<init>(134)) - Creating HddsVolume: /var/folders/ns/ls79bcr17wg7r__2j8lqkz6m0000gn/T/junit-8615142427860431562/hdds of storage type: null, capacity=400, used=0, available=300
```
- `TestHddsVolume#testOverUsedHddsSpace`:
```
2025-01-29 15:35:02,388 [main] INFO  volume.HddsVolume (HddsVolume.java:<init>(134)) - …
```
=> HDDS-12162. Log available space of HddsVolume and DbVolume upon Datanode startup

.github/workflows/ci.yml, dev-support/ci/integration_suites.sh, hadoop-ozone/dev-support/checks/native.sh, pom.xml
Integration check runs subsets of tests concurrently in splits.  The list of splits is currently defined by both root POM (as profiles) and in the workflow definition (as matrix variable).  The goal of this change is to remove the hard-coded list from the workflow definition, and generate it dynamically as part of the `build-info` check (like acceptance check suites).
Add `test-` prefix to be able to identify test suite profiles.  Add `-tests` suffix for other type of test profiles (`stable`/`native`).
https://issues.apache.org/jira/browse/HDDS-12143
_integration_ check has the same splits as on `master`:
https://github.com/adoroszlai/ozone/actions/runs/13005461028
=> HDDS-12143. Generate list of splits for integration check dynamically

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/duBreadcrumbNav/duBreadcrumbNav.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/plots/duPieChart.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/pages/diskUsage/diskUsage.less, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/pages/diskUsage/diskUsage.tsx
HDDS-12085. Add manual refresh button for DU page.
* Currently the V2 UI doesn't have a refresh button to reload new data that might get added, the whole page needs to be refreshed.
* This PR introduces the refresh button to load the data which was present in v1 UI.
https://issues.apache.org/jira/browse/HDDS-12085
=> HDDS-12085. Add manual refresh button for DU page.

hadoop-hdds/common/pom.xml, hadoop-hdds/framework/pom.xml, hadoop-hdds/hadoop-dependency-client/pom.xml, hadoop-hdds/hadoop-dependency-server/pom.xml, hadoop-hdds/hadoop-dependency-test/pom.xml, hadoop-hdds/interface-client/pom.xml, hadoop-hdds/interface-server/pom.xml, hadoop-hdds/pom.xml, hadoop-hdds/rocks-native/pom.xml, hadoop-hdds/rocksdb-checkpoint-differ/pom.xml, hadoop-hdds/server-scm/pom.xml, hadoop-hdds/tools/pom.xml, hadoop-ozone/csi/pom.xml, hadoop-ozone/datanode/pom.xml, hadoop-ozone/dist/pom.xml, hadoop-ozone/fault-injection-test/network-tests/pom.xml, hadoop-ozone/httpfsgateway/pom.xml, hadoop-ozone/integration-test/pom.xml, hadoop-ozone/interface-client/pom.xml, hadoop-ozone/ozone-manager/pom.xml, hadoop-ozone/pom.xml, hadoop-ozone/recon/pom.xml, hadoop-ozone/s3-secret-store/pom.xml, hadoop-ozone/s3gateway/pom.xml, pom.xml
- Remove unnecessary `compile` scope (which is the default one)
- Do not set scope in `dependencyManagement`
- Define versions in `dependencyManagement`
- Remove unnecessary `version` definitions from submodules
- Add missing `groupId`
See individual commits for easier review.
https://issues.apache.org/jira/browse/HDDS-12176
CI:
https://github.com/adoroszlai/ozone/actions/runs/13070451993
=> HDDS-12176. Trivial dependency cleanup

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/AvailableSpaceFilter.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/CapacityVolumeChoosingPolicy.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/MutableVolumeSet.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/StorageVolume.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeInfo.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeUsage.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestCapacityVolumeChoosingPolicy.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestHddsVolume.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestReservedVolumeSpace.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestRoundRobinVolumeChoosingPolicy.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestVolumeSet.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainer.java
Reduce the number of separate `getAvailable`, `getCapacity()`, `getScmUsed()` calls.  Instead, use `getCurrentUsage()` to fetch all 3 values together.  Goals:
- reduce number of lock acquisitions when reaching `CachingSpaceUsageSource` and provide consistent view of the 3 values
- reduce duplication, e.g. `volumeInfo.map(VolumeInfo::get...).orElse(...)`
- reduce the interface exposed by various volume-related classes
https://issues.apache.org/jira/browse/HDDS-12163
CI:
https://github.com/adoroszlai/ozone/actions/runs/13086838004
=> HDDS-12163. Reduce number of individual getCapacity/getAvailable/getUsedSpace calls

.github/workflows/ci.yml, hadoop-ozone/dev-support/checks/_build.sh, hadoop-ozone/dev-support/checks/compile.sh, hadoop-ozone/dev-support/checks/repro.sh
Logs of most checks are uploaded as artifacts at the end, but logs of `build` and `compile` checks are only visible in GitHub UI.
(Most of this is extracted from #7497.)
https://issues.apache.org/jira/browse/HDDS-12142
Downloaded artifacts from CI:
https://github.com/adoroszlai/ozone/actions/runs/13051118776
```
$ unzip -t build.zip 
Archive:  build.zip
testing: failures                 OK
testing: output.log               OK
No errors detected in compressed data of build.zip.
$ unzip -t compile-11.zip 
Archive:  compile-11.zip
testing: failures                 OK
testing: output.log               OK
No errors detected in compressed data of compile-11.zip.
```
=> HDDS-12142. Save logs from build and compile checks

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/duMetadata/duMetadata.tsx
HDDS-12073. Don't show Source Bucket and Volume if null in DU metadata
* Disk Usage metadata table provides us with two fields Source Bucket and Source Volume which are populated for a linked Bucket and Volume respectively.
* However for a non-linked bucket/volume this field will be null and it shows up as empty fields in the UI. This should not happen and we should not show the fields if it is empty.
* This PR addresses this issue by adding extra checks for null values in this scenario.
https://issues.apache.org/jira/browse/HDDS-12073
Created a base volume and bucket as `/src-vol/src-buck`
Created a linked bucket from `src-buck`
Base Bucket metadata
Linked Bucket metadata
=> HDDS-12073. Don't show Source Bucket and Volume if null in DU metadata

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBTableStore.java
Addendum for #7797.  Get raw size from value, not iterator, which always returns 0.
https://issues.apache.org/jira/browse/HDDS-12186
N/A
=> HDDS-12186. (addendum) Avoid array allocation for table iterator

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLog.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestStorageContainerManager.java
In case of resetDeletedBlockRetryCount with --all option, scm takes [lock](https://github.com/apache/ozone/blob/12419fae1f0418793d952227364b04f1d2c3583b/hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogImpl.java#L126) and tries to get all the transaction with max retry and then updates DB with 0 count. In some large scale env this count can be huge which can lead to multiple problem.
i) Lock can lead to block all other normal operation.
ii) Since message is passed through ratis, which will fail because of size.
Instead of doing like above we should do this operation in batches to avoid long lock and ratis message size failure.
https://issues.apache.org/jira/browse/HDDS-11714
=> HDDS-11714. resetDeletedBlockRetryCount with --all may fail and can cause long db lock in large cluster

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsHAURLs.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/AbstractOzoneContractTest.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/TestOzoneContractFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/contract/TestOzoneContractLegacy.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestAllocateContainer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestContainerReportWithKeys.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestContainerSmallFile.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestGetCommittedBlockLengthAndPutKey.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMNodeManagerMXBean.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerMXBean.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestCpuMetrics.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestGetClusterTreeInformation.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/metrics/TestDatanodeQueueMetrics.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestDNRPCLoadGenerator.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestObjectStore.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestObjectStoreWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmBlockVersioning.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerRestInterface.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestScmAdminHA.java, hadoop-ozone/integration-test/src/test/java/org/apache/ozone/test/ClusterForTests.java, hadoop-ozone/integration-test/src/test/java/org/apache/ozone/test/HATests.java, hadoop-ozone/integration-test/src/test/java/org/apache/ozone/test/NonHATests.java, hadoop-ozone/integration-test/src/test/java/org/apache/ozone/test/TestOzoneIntegrationHA.java, hadoop-ozone/integration-test/src/test/java/org/apache/ozone/test/TestOzoneIntegrationNonHA.java, hadoop-ozone/integration-test/src/test/java/org/apache/ozone/test/package-info.java
Cluster startup/shutdown is the most time-consuming part of the test for several classes (30+ seconds for each of the following test classes).
```
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 43.108 s - in org.apache.hadoop.fs.ozone.TestOzoneFsHAURLs
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 35.312 s - in org.apache.hadoop.hdds.scm.TestAllocateContainer
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 36.292 s - in org.apache.hadoop.hdds.scm.TestContainerReportWithKeys
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 36.5 s - in org.apache.hadoop.hdds.scm.TestContainerSmallFile
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 36.365 s - in …
```
=> HDDS-12183. Reuse cluster across safe test classes

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/MultipartInputStream.java
`HDDS-12203. Initialize block length before skip`
* skip() in MultipartInputStream doesn't call initialize(), which means `length` isn't valid before use.
* Similar issue as https://issues.apache.org/jira/browse/HDDS-11220
https://issues.apache.org/jira/browse/HDDS-12203
Integration Tests
=> HDDS-12203. Initialize block length before skip

hadoop-hdds/docs/content/feature/ErasureCoding.md, hadoop-hdds/docs/content/feature/OM-HA.md, hadoop-hdds/docs/content/feature/Snapshot.md
The following documentations have been corrected
In OM High Availability document :
under OM Bootstrap sub-topic "existing OM’s" should not have " 's "
In Ozone Erasure Coding document :
under background , configurations and enable intel ISA-L sub-topics some conjunctions were missing
In Ozone Snapshot document:
spelling of instantaneous was wrong
https://issues.apache.org/jira/browse/HDDS-12200
tested locally using hugo serve
=> HDDS-12200. Fix grammar in OM HA, EC and Snapshot doc

hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/OzoneFSInputStream.java
`HDDS-12195. Implement skip() in OzoneFSInputStream`
* The skip() method is not implemented in `OzoneFSInputStream`. As a result, it defaults to `java.io.InputStream#skip`, which uses `read()` and slows down performance.
* Implement skip() in OzoneFSInputStream to delegate skip() to `inputStream`
https://issues.apache.org/jira/browse/HDDS-12195
Integration Tests
=> HDDS-12195. Implement skip() in OzoneFSInputStream

hadoop-hdds/docs/content/feature/Decommission.md, hadoop-hdds/docs/content/feature/Observability.md
1. In the Decommissioning feature in upstream doc for the OM decommissioning one grammatical mistake is there:
"Add **the OM NodeId of the to be decommissioned OM node** to the ozone.om.decommissioned.nodes. property in ozone-site.xml of all other OMs."
Here I corrected to "Add the OM NodeId of the OM Node to be decommissioned to"
2. In the Observability feature in upstream doc for the Grafana , there is a spelling mistake.
"Grana" is corrected to "Grafana"
https://issues.apache.org/jira/browse/HDDS-12212
Tested locally through hugo serve
=> HDDS-12212. Fix grammar in decommissioning and observability documentation

hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Datanode Chunk Read_Write Dashboard.json
I incorrectly used $_interval as the field for calculating the rate, due to issues with an older version of prometheus used in my sandbox. This should be $_rate_interval
Ref https://grafana.com/docs/grafana/latest/datasources/prometheus/template-variables/
https://issues.apache.org/jira/browse/HDDS-12112
Local sandbox
=> HDDS-12112. Fix interval used for Chunk read write Dashboard

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestSchemaOneBackwardsCompatibility.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestSchemaTwoBackwardsCompatibility.java
The ozone.block.deleting.container.limit.per.interval property, along with the test cases referring to this property, were removed as it is not used anymore by the block deletion logic.
The modifications done are as follows:
1. The ozone.block.deleting.container.limit.per.interval property has been removed from the ozone-default.xml file.
2. References to this property have been removed from the following files:
-       TestBlockDeletingService.java
-       TestSchemaOneBackwardCompatibility.java
-       TestSchemaTwoBackwardCompatibility.java
-       OzoneConfigKeys.java
https://issues.apache.org/jira/browse/HDDS-10607
The patch was tested by the following tests:
Integration (client)
Integration (container)
Integration (filesystem)
Integration (flaky)
Integration (hdds)
Integration (om) …
=> HDDS-10607. Remove unused ozone.block.deleting.container.limit.per.interval config property

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/pages/heatmap/heatmap.tsx
HDDS-12044. Fix Heatmap calendar closing on skipping years/months
*  Currently the DatePicker component is buggy and closes when the parent menu closes.
* As a result of this when we are skipping the years or months in the calendar the menu is out of focused and everything closes.
* This PR wraps the calendar component under a div instead of a menu item to prevent the default behaviour on blur as a workaround.
* It also removes unused imports from the heatmap.tsx file.
https://issues.apache.org/jira/browse/HDDS-12044
https://github.com/user-attachments/assets/e90781f6-13e6-4028-abb9-66ad468c7e86
=> HDDS-12044. Fix Heatmap calendar closing on skipping years/months

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/Storage.java, hadoop-ozone/common/pom.xml
Hadoop `FileUtil` requires `commons-compress` at runtime.  Remove a reference to it from `hdds-common` to reduce client's dependencies.
https://issues.apache.org/jira/browse/HDDS-12217
CI:
https://github.com/adoroszlai/ozone/actions/runs/13165660996
=> HDDS-12217. Remove reference to FileUtil in hdds-common

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMMXBean.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/container/TestScmApplyTransactionFailure.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestNode2PipelineMap.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestSCMPipelineMetrics.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/admin/om/lease/TestLeaseRecoverer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestDiscardPreallocatedBlocks.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestBucketLayoutWithOlderClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/ozone/test/ClusterForTests.java, hadoop-ozone/integration-test/src/test/java/org/apache/ozone/test/HATests.java, hadoop-ozone/integration-test/src/test/java/org/apache/ozone/test/NonHATests.java
Run few more integration tests with shared cluster to save time.
```
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.091 s - in org.apache.ozone.test.HATests$ScmApplyTransactionFailure
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.075 s - in org.apache.ozone.test.NonHATests$BucketLayoutWithOlderClient
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.932 s - in org.apache.ozone.test.NonHATests$DiscardPreallocatedBlocks
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.271 s - in org.apache.ozone.test.NonHATests$LeaseRecoverer
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.029 s - in org.apache.ozone.test.NonHATests$Node2PipelineMap
[INFO] Tests run: 2, Failures: 0, …
```
=> HDDS-12218. Add more to integration test with shared cluster

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/ContainerSizeCountTask.java
Currently, ContainerSizeCountTask logs an error when processing containers with negative sizes. However, these containers are already ignored from the count, meaning they do not cause any functional issues. The repeated logging of such messages results in excessive noise, making it difficult to diagnose real issues in Recon.
https://issues.apache.org/jira/browse/HDDS-12227?filter=-1
=> HDDS-12227. Avoid Clutter in Recon Logs by Reducing Log Level of ContainerSizeCountTask.

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/FileSizeCountTask.java
In the `FileSizeCountTask` class, the update logic in `writeCountsToDB()` is never reached because `isDbTruncated` is always passed as true. This means that records are always inserted without checking for existing records, leading to SQL exceptions due to duplicate primary key constraints.
Example of SQL Exception:
```
2025-02-06 12:57:03 Caused by: org.jooq.exception.DataAccessException: SQL [insert into "FILE_COUNT_BY_SIZE" ("volume", "bucket", "file_size", "count") values (cast(? as varchar(32672)), cast(? as varchar(32672)), cast(? as bigint), cast(? as bigint))]; The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'pk_volume_bucket_file_size' defined on 'FILE_COUNT_BY_SIZE'.
``` …
=> HDDS-12228. Fix Duplicate Key Violation Condition in FileSizeCountTask.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/fs/CachingSpaceUsageSource.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/fs/TestCachingSpaceUsageSource.java
`CachingSpaceUsageSource` may benefit from storing `SpaceUsageSource#snapshot` until individual values change, to reduce object creation.
https://issues.apache.org/jira/browse/HDDS-12180
Updated unit test.
CI:
https://github.com/adoroszlai/ozone/actions/runs/13108086955
=> HDDS-12180. Store snapshot in CachingSpaceUsageSource

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/reconfig/TestOmReconfiguration.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/acl/OzoneAuthorizerFactory.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/acl/OzoneNativeAuthorizer.java
Make `allowListAllVolumes` reconfigurable in OM, for testing with both settings without OM restart.
https://issues.apache.org/jira/browse/HDDS-12248
Added integration test.
CI:
https://github.com/adoroszlai/ozone/actions/runs/13204314582
=> HDDS-12248. Make allowListAllVolumes reconfigurable in OM

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java
Change log level in `SCMNodeManager#getNodesByAddress` to debug.
`SCMNodeManager#getNodesByAddress` is called from `BlockProtocolServer#allocateBlock` and `BlockProtocolServer#sortDatanodes`, in both the cases the client could be running on a node that's not a datanode. Because of this the SCM log file is flooded with `Cannot find node for address` messages.
```
2025-01-14 13:36:23,602 WARN [IPC Server handler 79 on 9863]-org.apache.hadoop.hdds.scm.node.SCMNodeManager: Cannot find node for address 172.xx.x.151
2025-01-14 13:36:23,602 WARN [IPC Server handler 78 on 9863]-org.apache.hadoop.hdds.scm.node.SCMNodeManager: Cannot find node for address 172.xx.x.152
2025-01-14 13:36:23,614 WARN [IPC Server handler 18 on 9863]-org.apache.hadoop.hdds.scm.node.SCMNodeManager: Cannot find node for …
```
=> HDDS-12292. Change log level in SCMNodeManager#getNodesByAddress to debug.

hadoop-ozone/dist/src/main/compose/ozonesecure/test.sh, hadoop-ozone/dist/src/main/smoketest/repair/bucket-encryption.robot, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHAWithFSO.java
TestOzoneShellHA and TestOzoneShellHAWithFSO are not run due `ClassNotFoundException` when starting MiniKMS (HDDS-11879).  KMS is required for only one test case.  This PR disables and re-creates it as Robot test.
Also fix:
- failures introduced while the tests were effectively disabled
- OzoneClient leak in TestOzoneShellHAWithFSO, as it starts two clusters, but stops only one
https://issues.apache.org/jira/browse/HDDS-12192
```
[INFO] Tests run: 30, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 78.721 s - in org.apache.hadoop.ozone.shell.TestOzoneShellHAWithFSO
[INFO] Tests run: 30, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 79.443 s - in org.apache.hadoop.ozone.shell.TestOzoneShellHA
```
https://github.com/adoroszlai/ozone/actions/runs/13123151647/job/36614089604#step:6:3987 …
=> HDDS-12192. Fix TestOzoneShellHA and extract set-bucket-encryption test case

.github/workflows/ci.yml, .github/workflows/repeat-acceptance.yml, hadoop-ozone/dev-support/checks/_diffoscope.sh, hadoop-ozone/dev-support/checks/_lib.sh, hadoop-ozone/dev-support/checks/acceptance.sh, hadoop-ozone/dev-support/checks/integration.sh, hadoop-ozone/dev-support/checks/kubernetes.sh
Some checks have few lines of shell script, mostly for preparing the environment.  This PR moves them to the check scripts, to allow running the scripts with less setup in other CI environments.
(This is extracted from #7497 for easier review, with slight modification.)
https://issues.apache.org/jira/browse/HDDS-12290
CI:
https://github.com/adoroszlai/ozone/actions/runs/13224407537
_integration (filesystem)_ still includes shaded `ozonefs` modules:
```
[INFO] Apache Ozone Tools ................................. SUCCESS [  2.837 s]
[INFO] Apache Ozone FileSystem Shaded ..................... SUCCESS [03:55 min]
[INFO] Apache Ozone FS Hadoop 2.x compatibility ........... SUCCESS [ 19.090 s]
[INFO] Apache Ozone FS Hadoop 3.x compatibility ........... SUCCESS [ 13.449 s]
[INFO] Apache Ozone FS …
```
=> HDDS-12290. Move custom logic from ci.yml into the check scripts

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ratis/RatisHelper.java
- XceiverClientRatis allows adding ratis data stream configuration.
- According to the discussion at https://github.com/apache/ozone/pull/7645, we can skip `sendForward` by adding `hdds.ratis.raft.datastream.skip.send-forward=true` on the client side, thus avoiding an invalid ratis transaction (current streaming write will generate an invalid streamInit transaction)
https://github.com/apache/ozone/blob/ab29a55eaea71db9f2912d2fc69c2865cad34af8/hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockDataStreamOutput.java#L206-L226
https://issues.apache.org/jira/browse/HDDS-12291
Existing Tests
=> HDDS-12291. XceiverClientRatis allows adding ratis data stream configuration

hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java, hadoop-ozone/dist/src/main/smoketest/recon/recon-taskstatus.robot, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServerConfigKeys.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/OzoneManagerServiceProviderImpl.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/spi/impl/TestOzoneManagerServiceProviderImpl.java
This PR change is to get rid of interval delay configs for Recon OM DB snapshot sync with active OM DB because these configs may not make much sense when OM write TPS is very high in the range of more than 5k.
Currently Recon sync with OM based on following configs:
ozone.recon.om.snapshot.task.interval.delay -> 5s
recon.om.delta.update.limit -> 50000
recon.om.delta.update.loop.limit -> 50
Above are recommended and default configs for high write TPS workload in the range of approx 5k to achieve near real time sync between Recon and OM data. However in future, TPS may achieve higher targets in OM and Recon needs to pull data continuously to keep lag and latency minimum. 
https://issues.apache.org/jira/browse/HDDS-11953
Tested with junit and integration tests of recon OM DB sync.
=> HDDS-11953. Improve Recon OM sync process based on continuous pull of OM data.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/OzoneRpcClientTests.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/RequestAuditor.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyDeleteRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyDeleteRequestWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeysDeleteRequest.java
Here is one example of current DELETE_KEY audit log. The dataSize is always 0.
2025-01-24 03:13:23,876 | INFO  | OMAudit | user=mi_staging.deploy@CORP.HULU.COM | ip=10.80.141.10 | op=DELETE_KEY {volume=hive, bucket=mi-staging.db, key=nova_upstream_collections_hive_temp_2025_01_24_03_09_24/_temporary/0/_temporary/attempt_20250124030924_0006_m_000147_3170, dataSize=0, replicationType=NONE, replicationFactor=ZERO} | ret=SUCCESS |
This task aims to have the real data size for deleted key, so that it's easy to calculate the total size of deleted keys in a period of time, which is useful when investigating Ozone space reclaimed different than expectation cases.
https://issues.apache.org/jira/browse/HDDS-12238
new unit test
=> HDDS-12238. Improve OM DELETE_KEY audit log to include key size

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/reconfig/ReconfigurationTestBase.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/reconfig/TestDatanodeReconfiguration.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/reconfig/TestOmReconfiguration.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/reconfig/TestScmReconfiguration.java, hadoop-ozone/integration-test/src/test/java/org/apache/ozone/test/NonHATests.java
Run the following tests on the same cluster as some other integration tests:
- `TestDatanodeReconfiguration`
- `TestOmReconfiguration`
- `TestScmReconfiguration`
to reduce test runtime.
https://issues.apache.org/jira/browse/HDDS-12249
Before:
```
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 36 s - in org.apache.hadoop.ozone.reconfig.TestDatanodeReconfiguration
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 35.293 s - in org.apache.hadoop.ozone.reconfig.TestOmReconfiguration
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 36.048 s - in org.apache.hadoop.ozone.reconfig.TestScmReconfiguration
```
After:
```
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.027 s - in …
```
=> HDDS-12249. Share cluster in reconfiguration tests

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDBConfiguration.java
It currently appears that the RocksDB LOG.old files can be generated without limit for OM, SCM, and Recon. I have observed these files filling up the disk, bringing down the Recon instance in a cluster.
The DataNode has this property to control them: hdds.datanode.rocksdb.log.max-file-num
Can we add a similar property for the other three? So:
hdds.scm.rocksdb.log.max-file-num
hdds.om.rocksdb.log.max-file-num
hdds.recon.rocksdb.log.max-file-num
One reasonable default value would be 10.
Fix done:
1. Already a support was added for this config so just the default is just changed from 1000 to 10
https://issues.apache.org/jira/browse/HDDS-12220
Below is the workflow link which passed successfully:
https://github.com/Gargi-jais11/ozone/actions/runs/13237283906
=> HDDS-12220. Limit OM/SCM/Recon RocksDB max user log files total size

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/CloseContainerCommand.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/ClosePipelineCommand.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/CreatePipelineCommand.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/DeleteBlocksCommand.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/DeleteContainerCommand.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/FinalizeNewLayoutVersionCommand.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/ReconstructECContainersCommand.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/RefreshVolumeUsageCommand.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/ReplicateContainerCommand.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/ReregisterCommand.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/SetNodeOperationalStateCommand.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeHeartbeatDispatcher.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeProtocolServer.java
As a part of SCM audits for datanode's heartbeats, the command.toString for the commands being sent to the datanodes are logged. For most commands this results in a short string, but for deleteBlocks command, all the delete transactions are also added. This leads to a very verbose audit log. 
SCM should add only the metadata response to the logs appropriately for each of the commands. 
https://issues.apache.org/jira/browse/HDDS-12175
Tested manually.
Before the change:
```
2025-02-05 17:12:56,748 | INFO  | SCMAudit | user=hadoop | ip=172.18.0.10 | op=SEND_HEARTBEAT {datanodeUUID=b8ca7816-1298-4f9b-b962-a8b43351fb30, term=3, command=[commandType: deleteBlocksCommand deleteBlocksCommandProto { deletedBlocksTransactions { txID: 4 containerID: 4 localID: 115816896921600004 localID: …
```
=> HDDS-12175. Audit logs in SCM shouldn't print delete txns

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
The message "no leader found" appears when the jmx endpoint is accessed  when no OM leaders are present, but this message does not help in troubleshooting the problem , so to improve the error log the message is changed to "There is no leader among the Ozone Manager servers. If this message persists, the service may be down. Possible cause: only one OM is up, or other OMs are unable to respond to Ratis leader vote messages".
https://issues.apache.org/jira/browse/HDDS-12234
This patch was tested using jmx endpoint for OM
Below is the workflow link which passes successfully.
https://github.com/sreejasahithi/ozone/actions/runs/13236312553
=> HDDS-12234. Improve error log No leader found when jmx endpoint is accessed

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/OzoneManagerServiceProviderImpl.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/DeletedKeysInsightHandler.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/NSSummaryTaskDbEventHandler.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/OmTableHandler.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/OmTableInsightTask.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/OpenKeysInsightHandler.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/ReconOmTask.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestOmTableInsightTask.java
This PR change is to reduce creation of too many local hashmap and other objects on repeated processing of OM events during delta sync of Recon with OM.
Some OM background tasks need code optimisations where the process method is creating static maps and other objects again and again with every run which are not needed, so that memory and GC overhead can be reduced.
https://issues.apache.org/jira/browse/HDDS-12110
Patch is tested using existing junit tests.
=> HDDS-12110. Optimize memory overhead for OM background tasks.

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OzoneFsServerDefaults.java
When running a YARN job on the Ozone FileSystem, a NullPointerException occurs, causing NodeManagers to fail during log aggregation.
Upon investigation, an ArithmeticException is thrown in AbstractFileSystem#create, caused by a 0 % 0 calculation:
```java
FsServerDefaults ssDef = getServerDefaults(f);
if (ssDef.getBlockSize() % ssDef.getBytesPerChecksum() != 0) {
```
Since HDDS-11227, FsServerDefaults has been extended by OzoneFsServerDefaults. However, most fields (including bytesPerChecksum) are initialized to zero, which triggers the 0 % 0 error:
```java
public OzoneFsServerDefaults(String keyProviderUri) {
super(0L, 0, 0, (short)0, 0, false, 0L, null, keyProviderUri);
}
```
In Hadoop’s `FileSystem`, the default `bytesPerChecksum` is 512. Changing `OzoneFsServerDefaults` so that …
=> HDDS-12312. NodeManager log aggregation to Ozone FileSystem fails.

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCloseContainerCommandHandler.java
Fix intermittent test failure:
```
AssertionFailedError: expected: <true> but was: <false>
...
at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:183)
at org.apache.hadoop.ozone.container.common.statemachine.commandhandler.TestCloseContainerCommandHandler.testThreadPoolPoolSize(TestCloseContainerCommandHandler.java:316)
```
This started happening with Ubuntu 24.04 runner ([example](https://github.com/apache/ozone/actions/runs/13259625320/job/37013543693?pr=7852#step:6:1621)).
Fixed by removing the part of the test related to `activePoolSize`.
- commands may be already handled by the time when the assertion is reached
- return value from `ThreadPoolExecutor#getActiveCount()` is approximate, anyway
- the value is only used for metrics …
=> HDDS-12309. Intermittent failure in TestCloseContainerCommandHandler.testThreadPoolPoolSize

.github/workflows/build-ratis.yml, .github/workflows/ci.yml, .github/workflows/close-pending.yaml, .github/workflows/comments.yaml, .github/workflows/intermittent-test-check.yml, .github/workflows/populate-cache.yml, .github/workflows/pull-request.yml, .github/workflows/repeat-acceptance.yml
Ubuntu 20.04 is being deprecated: https://github.com/actions/runner-images/issues/11101
Upgrade to 24.04.
Setup Java 11 for acceptance check.  (Java 11 was the default version for 20.04, while 24.04 comes with Java 17 by default.)  This only affects the GitHub runner, where Hadoop S3A contract tests are run.  We still use Java 21 for running Ozone in `ozone-runner` Docker image.
https://issues.apache.org/jira/browse/HDDS-12304
CI:
https://github.com/adoroszlai/ozone/actions/runs/13258221266
=> HDDS-12304. Bump GitHub Actions runner to ubuntu-24.04

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/LeakDetector.java
Whenever the Ozone client starts, it always logs 'Starting leak detector thread...'. I think this message should be at the DEBUG level.
```
$ hadoop fs -ls /
2025-02-14 04:50:58,937 INFO utils.LeakDetector: Starting leak detector thread OzoneClientObject0.
Found 1 items
drwxrwxrwx   - ozone ozone          0 2025-02-14 04:15 /tmp
```
https://issues.apache.org/jira/browse/HDDS-12328
I have tested this fix in my local cluster and confirmed that the log is suppressed.
=> HDDS-12328. Set the log for starting LeakDetector to DEBUG level.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/cli/GenericCli.java, hadoop-ozone/cli-shell/src/main/java/org/apache/hadoop/ozone/shell/keys/PutKeyHandler.java, hadoop-ozone/dist/src/main/smoketest/basic/ozone-shell-lib.robot
The handling of FileSystemException has been improved to provide more detailed and specific error messages. Previously, only file name would be displayed for the exceptions like NoSuchFileException, AccessDeniedException, or FileAlreadyExistsException.
This update ensures that the exception type is checked and accordingly the error message is given.
https://issues.apache.org/jira/browse/HDDS-12241
below is the workflow link that passes successfully
https://github.com/sreejasahithi/ozone/actions/runs/13289875378
=> HDDS-12241. Improve error message for FileSystemException

hadoop-hdds/config/pom.xml, hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/Config.java, hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigFileAppender.java, hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigFileGenerator.java, hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigGroup.java, hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigTag.java, hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigType.java, hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigurationException.java, hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigurationReflectionUtil.java, hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigurationSource.java, hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigurationTarget.java, hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/InMemoryConfiguration.java, hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/MutableConfigurationSource.java, hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/PostConstruct.java, hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ReconfigurableConfig.java, hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/StorageSize.java, hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/StorageUnit.java, hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/TimeDurationUtil.java, hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/package-info.java, hadoop-hdds/config/src/test/java/org/apache/hadoop/hdds/conf/ConfigurationExample.java, hadoop-hdds/config/src/test/java/org/apache/hadoop/hdds/conf/ConfigurationExampleGrandParent.java, hadoop-hdds/config/src/test/java/org/apache/hadoop/hdds/conf/ConfigurationExampleParent.java, hadoop-hdds/config/src/test/java/org/apache/hadoop/hdds/conf/TestConfigFileAppender.java, hadoop-hdds/config/src/test/java/org/apache/hadoop/hdds/conf/TestConfigFileGenerator.java, hadoop-hdds/config/src/test/java/org/apache/hadoop/hdds/conf/TestConfigurationReflectionUtil.java, hadoop-hdds/config/src/test/java/org/apache/hadoop/hdds/conf/TestConfigurationSource.java, hadoop-hdds/config/src/test/java/org/apache/hadoop/hdds/conf/TestReconfigurableConfig.java, hadoop-hdds/config/src/test/java/org/apache/hadoop/hdds/conf/package-info.java
Fixed checkstyle for license header and imports for hadoop-hdds/config module.
Enabled new checkstyle for hadoop-hdds/config module.
https://issues.apache.org/jira/browse/HDDS-12258
Testing not required.
=> HDDS-12258. Fix license headers and imports for hdds-config

hadoop-hdds/managed-rocksdb/pom.xml, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/JniLibNamePropertyWriter.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedBlockBasedTableConfig.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedBloomFilter.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedCheckpoint.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedColumnFamilyOptions.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedCompactRangeOptions.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedDBOptions.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedEnvOptions.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedFlushOptions.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedIngestExternalFileOptions.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedLRUCache.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedLogger.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedObject.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedOptions.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedReadOptions.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedRocksDB.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedRocksIterator.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedRocksObjectMetrics.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedRocksObjectUtils.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedSlice.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedSstFileReader.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedSstFileReaderIterator.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedSstFileWriter.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedStatistics.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedTransactionLogIterator.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedWriteBatch.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedWriteOptions.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/package-info.java
Fixed checkstyle for license header and imports for hdds-managed-rocksdb module.
Enabled new checkstyle for hdds-managed-rocksdb module.
https://issues.apache.org/jira/browse/HDDS-12262
Testing not required.
=> HDDS-12262. Fix license headers and imports for hdds-managed-rocksdb

hadoop-hdds/rocks-native/pom.xml, hadoop-hdds/rocks-native/src/main/java/org/apache/hadoop/hdds/utils/NativeConstants.java, hadoop-hdds/rocks-native/src/main/java/org/apache/hadoop/hdds/utils/NativeLibraryLoader.java, hadoop-hdds/rocks-native/src/main/java/org/apache/hadoop/hdds/utils/NativeLibraryNotLoadedException.java, hadoop-hdds/rocks-native/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedRawSSTFileIterator.java, hadoop-hdds/rocks-native/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedRawSSTFileReader.java, hadoop-hdds/rocks-native/src/main/java/org/apache/hadoop/hdds/utils/db/managed/package-info.java, hadoop-hdds/rocks-native/src/main/java/org/apache/hadoop/hdds/utils/package-info.java, hadoop-hdds/rocks-native/src/test/java/org/apache/hadoop/hdds/utils/TestNativeLibraryLoader.java, hadoop-hdds/rocks-native/src/test/java/org/apache/hadoop/hdds/utils/TestUtils.java, hadoop-hdds/rocks-native/src/test/java/org/apache/hadoop/hdds/utils/db/managed/TestManagedRawSSTFileIterator.java
Fixed checkstyle for license header and imports for hdds-rocks-native module.
Enabled new checkstyle for hdds-rocks-native module.
https://issues.apache.org/jira/browse/HDDS-12263
Testing not required.
=> HDDS-12263. Fix license headers and imports for hdds-rocks-native

hadoop-hdds/rocksdb-checkpoint-differ/pom.xml, hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/compaction/log/CompactionFileInfo.java, hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/compaction/log/CompactionLogEntry.java, hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/compaction/log/package-info.java, hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/graph/Edge.java, hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/graph/PrintableGraph.java, hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/graph/package-info.java, hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdb/util/RdbUtil.java, hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdb/util/SstFileSetReader.java, hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdb/util/package-info.java, hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/CompactionNode.java, hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/DifferSnapshotInfo.java, hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java, hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDiffUtils.java, hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/package-info.java, hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/compaction/log/TestCompactionFileInfo.java, hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/compaction/log/TestCompactionLogEntry.java, hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/graph/TestPrintableGraph.java, hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/rocksdb/util/TestSstFileSetReader.java, hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/rocksdiff/TestRocksDBCheckpointDiffer.java, hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/rocksdiff/TestRocksDiffUtils.java
Fixed checkstyle for license header and imports for rocksdb-checkpoint-differ module.
Enabled new checkstyle for rocksdb-checkpoint-differ module.
https://issues.apache.org/jira/browse/HDDS-12264
Testing not required.
=> HDDS-12264. Fix license headers and imports for rocksdb-checkpoint-differ

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/OzoneManagerServiceProviderImpl.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/OMDBUpdatesHandler.java
This PR is to fix the processing and consume of OM DB events by Recon when Recon was syncing with OM continuously in while loop.
When Recon sync with OM for incremental DB updates in a while loop continuously, It had a bug where OMDBUpdates handler was not clearing the DB update events consumed already in previous iteration in while loop.
https://issues.apache.org/jira/browse/HDDS-12325
Patch is tested by running existing Junit and integration tests and running following freon test:
```
ozone sh volume create volume1
ozone sh bucket create --layout FILE_SYSTEM_OPTIMIZED volume1/fso-bucket
ozone freon omkg -n=200000 -v=volume1 -b=fso-bucket
```
**After running above freon load, verified the OM DB `fileTable` count :**
`ozone debug ldb --db=/data/metadata/om.db scan …
=> HDDS-12325. Recon OM DB Incremental update events are not processed correctly.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/QuasiClosedContainerHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestQuasiClosedContainerHandler.java, hadoop-hdds/server-scm/src/test/resources/replicationManagerTests/quasi_closed.json
In [HDDS-12232](https://issues.apache.org/jira/browse/HDDS-12232) we changed the logic to move a container from QC -> CLOSED to require 3 replicas from unique origins rather than 2.
A further scenario is where a contain has replicas:
```
QC-BCSID10-Origin1
QC-BCSID10-Origin2
UNHEALTHY-BCSID10-Origin3
```
In this case, it can still close - we have seen all origins and the BCSID from them all.
In this case, the unhealthy replica somehow has a higher BCSID than the others, so we cannot close it:
```
QC-BCSID10-Origin1
QC-BCSID10-Origin2
UNHEALTHY-BCSID11-Origin3
```
Ultimately, when the Reconciler is added to the system, it would repair the replicas so they are all identical and then it would close.
https://issues.apache.org/jira/browse/HDDS-12326
New unit and scenario tests added.
=> HDDS-12326. Allow Quasi_Closed to Closed if there is an unhealthy replica <= highest BCSID

hadoop-ozone/dev-support/checks/_post_process.sh
`flaky-test-check` splits always return `completed with exit code 1`, even if there are no failed tests.
https://github.com/adoroszlai/ozone/actions/runs/13262417511
https://issues.apache.org/jira/browse/HDDS-12311
No `completed with exit code 1` in run where all passed:
https://github.com/adoroszlai/ozone/actions/runs/13271627157
Failed runs reported correctly for flaky test:
https://github.com/adoroszlai/ozone/actions/runs/13271802577
Regular CI:
https://github.com/adoroszlai/ozone/actions/runs/13271514006
=> HDDS-12311. flaky-test-check split exit code is always 1

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/tenant/TestSetRangerServiceVersionRequest.java
HDDS-12306. OmMetadataManager metrics are always zero
* Pass over the OMPerformanceMetrics object instance from OzoneManager, to be used by OmMetadataManagerImpl.
* Fixed a mock test error due to the change inside the OmMetadataManagerImpl constructor.
https://issues.apache.org/jira/browse/HDDS-12306
Existing UT. https://github.com/jojochuang/ozone/actions/runs/13267337134
=> HDDS-12306. OmMetadataManager metrics are always zero

hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/BadDataLocationException.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerException.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/exceptions/SCMException.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ha/NonRetriableException.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/InsufficientDatanodesException.java
This error occurs because the `SCMException` is thrown as a `RemoteException` to the Client (`StorageContainerLocationProtocolClientSideTranslatorPB`) from the server side (`StorageContainerLocationProtocolServerSideTranslatorPB`). We unwrap the exception using `RemoteException#unwrapRemoteException()`. This function expects a constructor with a `String.class` parameter, which is not present in `SCMException` and a few other Exception classes. This results in unwrap failure, and the commands are retried until the client exhausts the retry policy.
Currently, `SCMHAUtils#checkNonRetriableException()` is used to fail non-retriable commands. It fails to unwrap exceptions, resulting in incorrect retry logic. 
https://issues.apache.org/jira/browse/HDDS-10760
Manual testing with docker.
=> HDDS-10760. SCMExceptions resulting from admin CLI commands are treated as retriable.

hadoop-hdds/test-utils/pom.xml, hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/GenericTestUtils.java, hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/IntLambda.java, hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/JacocoServer.java, hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/LambdaTestUtils.java, hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/Log4j1Capturer.java, hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/Log4j2Capturer.java, hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/MetricsAsserts.java, hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/OzoneTestBase.java, hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/SpyInputStream.java, hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/SpyOutputStream.java, hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/TestClock.java, hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/TimedOutTestsListener.java, hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/package-info.java, hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/tag/Flaky.java, hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/tag/Native.java, hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/tag/Slow.java, hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/tag/Unhealthy.java, hadoop-hdds/test-utils/src/main/java/org/apache/ozone/test/tag/package-info.java
Fixed checkstyle for license header and imports for hdds-test-utils module.
Enabled new checkstyle for hdds-test-utils module.
https://issues.apache.org/jira/browse/HDDS-12266
=> HDDS-12266. Fix license headers and imports for hdds-test-utils

hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/cli-shell/src/main/java/org/apache/hadoop/ozone/shell/keys/DeleteKeyHandler.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OmConfig.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/OzoneRpcClientTests.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestObjectStoreWithLegacyFS.java, hadoop-ozone/integration-test/src/test/java/org/apache/ozone/test/NonHATests.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/handlers/BucketHandler.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/NSSummaryTaskWithLegacy.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpointStreaming.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/NSSummaryAdmin.java
- Move `ozone.om.enable.filesystem.paths` into `OmConfig`.
- Convert `TestObjectStoreWithLegacyFS` to be run with shared cluster (`NonHATests`).  This is included in the patch to start using the `setFileSystemPathEnabled` method.
- Update `TestOzoneRpcClient`, which sets the config during the test.
- Keep using `OMConfigKeys.OZONE_OM_ENABLE_FILESYSTEM_PATHS` in other tests to reduce the patch.
https://issues.apache.org/jira/browse/HDDS-12333
Before:
```
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 36.553 s - in org.apache.hadoop.ozone.om.TestObjectStoreWithLegacyFS
```
After:
```
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.747 s - in org.apache.ozone.test.NonHATests$ObjectStoreWithLegacyFS
```
CI: …
=> HDDS-12333. Move ozone.om.enable.filesystem.paths into OmConfig

hadoop-ozone/csi/pom.xml, hadoop-ozone/csi/src/main/java/org/apache/hadoop/ozone/csi/ControllerService.java, hadoop-ozone/csi/src/main/java/org/apache/hadoop/ozone/csi/CsiServer.java, hadoop-ozone/csi/src/main/java/org/apache/hadoop/ozone/csi/IdentityService.java, hadoop-ozone/csi/src/main/java/org/apache/hadoop/ozone/csi/NodeService.java, hadoop-ozone/csi/src/main/java/org/apache/hadoop/ozone/csi/package-info.java
Fixed checkstyle for license header and imports for ozone-csi module.
Enabled new checkstyle for ozone-csi module.
https://issues.apache.org/jira/browse/HDDS-12271
=> HDDS-12271. Fix license headers and imports for ozone-csi

hadoop-ozone/fault-injection-test/mini-chaos-tests/pom.xml, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/MiniOzoneChaosCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/MiniOzoneLoadGenerator.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/OzoneChaosCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/TestAllMiniChaosOzoneCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/TestDatanodeMiniChaosOzoneCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/TestMiniChaosOzoneCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/TestOzoneManagerMiniChaosOzoneCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManagerMiniChaosOzoneCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/failure/FailureManager.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/failure/Failures.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/failure/package-info.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/loadgenerators/AgedDirLoadGenerator.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/loadgenerators/AgedLoadGenerator.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/loadgenerators/DataBuffer.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/loadgenerators/FilesystemLoadGenerator.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/loadgenerators/LoadBucket.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/loadgenerators/LoadExecutors.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/loadgenerators/LoadGenerator.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/loadgenerators/NestedDirLoadGenerator.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/loadgenerators/RandomDirLoadGenerator.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/loadgenerators/RandomLoadGenerator.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/loadgenerators/ReadOnlyLoadGenerator.java
Fixed checkstyle for license header and imports for mini-chaos-tests module.
Enabled new checkstyle for mini-chaos-tests module.
https://issues.apache.org/jira/browse/HDDS-12272
=> HDDS-12272. Fix license headers and imports for mini-chaos-tests

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v1/AbstractS3SDKV1Tests.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/exception/S3ErrorTable.java
This ticket is to explicitly return the error of QUOTA_EXCEEDED instead of an internal error.
For internal error, clients will retry to send the same request, for 4xx errors clients will fail directly.
https://issues.apache.org/jira/browse/HDDS-12329
manual test
=> HDDS-12329. Specify S3 error for Quota Exceeded

.github/ci.md, CONTRIBUTING.md, dev-support/ci/selective_ci_checks.bats, dev-support/ci/selective_ci_checks.sh, dev-support/pmd/pmd-ruleset.xml, hadoop-ozone/dev-support/checks/pmd.sh, hadoop-ozone/httpfsgateway/src/site/site.xml, pom.xml
PMD checks enabled as one of the step of Basic verification pipeline.
Rationale behind this that PMD is the powerful widely adopted static analysis tool which can help us drastically improve code quality for the project.
Example of potential output can be found here: https://github.com/ivanzlenko/ozone/actions/runs/13354816303/job/37296119138
https://issues.apache.org/jira/browse/HDDS-12339
Run verification pipeline with and without enabled PMD rules.
=> HDDS-12339. Add CI check for PMD

hadoop-ozone/ozonefs-hadoop2/pom.xml, hadoop-ozone/ozonefs-hadoop2/src/main/java/org/apache/hadoop/fs/ozone/Hadoop27OmTransportFactory.java, hadoop-ozone/ozonefs-hadoop2/src/main/java/org/apache/hadoop/fs/ozone/Hadoop27RpcTransport.java, hadoop-ozone/ozonefs-hadoop2/src/main/java/org/apache/hadoop/fs/ozone/OzFs.java, hadoop-ozone/ozonefs-hadoop2/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java, hadoop-ozone/ozonefs-hadoop2/src/main/java/org/apache/hadoop/fs/ozone/RootedOzFs.java, hadoop-ozone/ozonefs-hadoop2/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java, hadoop-ozone/ozonefs-hadoop2/src/main/java/org/apache/hadoop/fs/ozone/package-info.java, hadoop-ozone/ozonefs-hadoop2/src/test/java/org/apache/hadoop/fs/TestOmKeyInfoWithHadoop2.java
Fixed checkstyle for license header and imports for ozone-filesystem-hadoop2 module.
Enabled new checkstyle for ozone-filesystem-hadoop2 module.
https://issues.apache.org/jira/browse/HDDS-12280
=> HDDS-12280. Fix license headers and imports for ozone-filesystem-hadoop2

hadoop-ozone/ozonefs-hadoop3/pom.xml, hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/OzFs.java, hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java, hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/RootedOzFs.java, hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java, hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/package-info.java
Fixed checkstyle for license header and imports for ozone-filesystem-hadoop3 module.
Enabled new checkstyle for ozone-filesystem-hadoop3 module.
https://issues.apache.org/jira/browse/HDDS-12281
=> HDDS-12281. Fix license headers and imports for ozone-ozonefs-hadoop3

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/utils/common.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/overviewCard/overviewSimpleCard.tsx
HDDS-12330. Convert Volume, Bucket and Key count to the nearest word
Currently in the Recon overview page the metrics for Keys, Buckets and Volumes are given as plain numbers. This causes issues while trying to read the value.
This PR adds commas to the number at every thousandth place making it easier to read in the UI
https://issues.apache.org/jira/browse/HDDS-12330
For the API response:
```
{
"pipelines": 32,
"totalDatanodes": 24,
"healthyDatanodes": 24,
"storageReport": {
"capacity": 202114732032,
"used": 4667099648,
"remaining": 182447632384,
"committed": 12000222315
},
"containers": 3230,
"missingContainers": 1002,
"openContainers": 5,
"deletedContainers": 4,
"volumes": 5,
"buckets": 1569,
"keys": 253123, …
```
=> HDDS-12330. Convert Volume, Bucket and Key count to use comma separated numbers

hadoop-ozone/recon-codegen/pom.xml, hadoop-ozone/recon-codegen/src/main/java/org/hadoop/ozone/recon/codegen/JooqCodeGenerator.java, hadoop-ozone/recon-codegen/src/main/java/org/hadoop/ozone/recon/codegen/ReconSchemaGenerationModule.java, hadoop-ozone/recon-codegen/src/main/java/org/hadoop/ozone/recon/codegen/ReconSqlDbConfig.java, hadoop-ozone/recon-codegen/src/main/java/org/hadoop/ozone/recon/codegen/SqlDbUtils.java, hadoop-ozone/recon-codegen/src/main/java/org/hadoop/ozone/recon/codegen/TableNamingStrategy.java, hadoop-ozone/recon-codegen/src/main/java/org/hadoop/ozone/recon/codegen/package-info.java, hadoop-ozone/recon-codegen/src/main/java/org/hadoop/ozone/recon/schema/ContainerSchemaDefinition.java, hadoop-ozone/recon-codegen/src/main/java/org/hadoop/ozone/recon/schema/ReconSchemaDefinition.java, hadoop-ozone/recon-codegen/src/main/java/org/hadoop/ozone/recon/schema/ReconTaskSchemaDefinition.java, hadoop-ozone/recon-codegen/src/main/java/org/hadoop/ozone/recon/schema/SchemaVersionTableDefinition.java, hadoop-ozone/recon-codegen/src/main/java/org/hadoop/ozone/recon/schema/StatsSchemaDefinition.java, hadoop-ozone/recon-codegen/src/main/java/org/hadoop/ozone/recon/schema/UtilizationSchemaDefinition.java, hadoop-ozone/recon-codegen/src/main/java/org/hadoop/ozone/recon/schema/package-info.java
Fixed checkstyle for license header and imports for ozone-recon-codegen module.
Enabled new checkstyle for ozone-recon-codegen module.
https://issues.apache.org/jira/browse/HDDS-12283
=> HDDS-12283. Fix license headers and imports for ozone-recon-codegen

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockOutputStream.java
`BlockOutputStream.failedServers` is not thread-safe, we can replace it with `CopyOnWriteArrayList<>()` to make sure it's thread-safe.
[HDDS-12331](https://issues.apache.org/jira/browse/HDDS-12331)
=> HDDS-12331. BlockOutputStream.failedServers is not thread-safe

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAUtils.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/utils/StorageVolumeUtil.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/upgrade/VersionedDatanodeFeatures.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HAUtils.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogStateManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHAManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMHANodeDetails.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/HddsTestUtils.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestSCMConfiguration.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestStorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestStorageContainerManagerHA.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecureOzoneCluster.java
Remove code paths for non-Ratis SCM.
After #7711, Ratis is always enable in SCM. Non-Ratis code is not used anymore, the non-Ratis code path can be removed from SCM.
HDDS-11867
CI Run: https://github.com/nandakumar131/ozone/actions/runs/13371649727
=> HDDS-11867. Remove code paths for non-Ratis SCM.

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/nssummary/SummarySubCommand.java
Ozone Recon - admin namespace summary CLI command is not giving complete output:
`ozone admin namespace summary /volume1/obs-bucket`
output:
```
`Connecting to Recon: http://recon:9888/api/v1/namespace/summary?path=/volume1/obs-bucket ...`
`[Warning] Namespace CLI is not designed for OBS bucket layout.`
`Bucket being accessed must be of type FILE_SYSTEM_OPTIMIZED bucket layout or 
LEGACY bucket layout with 'ozone.om.enable.filesystem.paths' set to true.`
`Entity Type : "BUCKET"`
```
The above output is incomplete it should also print information like
1. "numVolume"
2. "numBucket"
3. "numDir"
4. "numKey"
which is present in the **SummarySubCommand class** which the current code is not reading correct from correct json node.
https://issues.apache.org/jira/browse/HDDS-12335
Ran the CLI …
=> HDDS-12335. Fix ozone admin namespace summary to give complete output

hadoop-ozone/integration-test/dev-support/findbugsExcludeFile.xml, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestContainerOperations.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestStorageContainerManagerHA.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestStorageContainerManagerHAWithAllRunning.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestXceiverClientManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/container/metrics/TestSCMContainerManagerMetrics.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/node/TestDecommissionAndMaintenance.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/node/TestQueryNode.java, hadoop-ozone/integration-test/src/test/java/org/apache/ozone/test/HATests.java, hadoop-ozone/integration-test/src/test/java/org/apache/ozone/test/NonHATests.java
- Convert some HDDS integration tests to use shared cluster.
- Extract safe test case from `TestStorageContainerManagerHA` into a separate class, to be used with shared cluster.  Some trivial code cleanup in this test class, to avoid duplicating the problems.
- Move safe test cases from `TestQueryNode` to `TestContainerOperations` (which also tests `ScmClient`).
- Remove flaky tag from `TestDecommissionAndMaintenance`, passed 10x10 runs twice ([1](https://github.com/adoroszlai/ozone/actions/runs/13352899519), [2](https://github.com/adoroszlai/ozone/actions/runs/13358224366)).  This does not result in speed-up, but reduces run time of _integration (flaky)_, the slowest check currently.
https://issues.apache.org/jira/browse/HDDS-12349
Before:
```
Tests run: 4, Failures: 0, Errors: 0, …
```
=> HDDS-12349. Speed up some HDDS integration tests

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java
There are many unnecessary logs, like the one below, when SnapshotDeletingService is moving keys from the DELETED snapshot to the next Snapshot.
```shell
2025-02-18 12:46:26,676 INFO [SnapshotDeletingService#0]-org.apache.hadoop.ozone.om.helpers.OmKeyInfo: OmKeyInfo.getCodec ignorePipeline = true
2025-02-18 12:46:26,874 INFO [SnapshotDeletingService#0]-org.apache.hadoop.ozone.om.helpers.OmKeyInfo: OmKeyInfo.getCodec ignorePipeline = true
2025-02-18 12:46:26,999 INFO [SnapshotDeletingService#0]-org.apache.hadoop.ozone.om.helpers.OmKeyInfo: OmKeyInfo.getCodec ignorePipeline = true
2025-02-18 12:46:27,164 INFO [SnapshotDeletingService#0]-org.apache.hadoop.ozone.om.helpers.OmKeyInfo: OmKeyInfo.getCodec ignorePipeline = true
2025-02-18 12:46:27,338 INFO …
```
=> HDDS-12367. Change ignorePipeline log level to DEBUG in OmKeyInfo

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OmConfig.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/reconfig/TestOmReconfiguration.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java
Allow reconfiguring `ozone.om.server.list.max.size` without restarting OM.
Apply the limit to `ListOpenFiles` request, too.
https://issues.apache.org/jira/browse/HDDS-12293
Added test case in `TestOmReconfiguration`.
CI:
https://github.com/adoroszlai/ozone/actions/runs/13429986261
=> HDDS-12293. Make ozone.om.server.list.max.size reconfigurable

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestContainerOperations.java
- Use `storageClient` in place of `storageContainerLocationClient` and remove `storageContainerLocationClient` altogether in the test.
- The [comment](https://github.com/apache/ozone/blob/c0da9afea477bea4101fb2f3849d09b9b8591fb1/hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestContainerOperations.java#L230) // All nodes should be returned as they are all in service seems incorrect, one of the node is in DECOMMISSIONING state. The code is correct in asserting numOfdatanodes - 1, just the comment is misleading.
- Use `cluster().getHddsDatanodes().size()` instead of [hardcoded value](https://github.com/apache/ozone/blob/c0da9afea477bea4101fb2f3849d09b9b8591fb1/hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestContainerOperations.java#L266). …
=> HDDS-12387. Cleanup TestContainerOperations

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java
For the performance fix due to which tarball creation takes time, HDDS-12064 should help.  This PR just makes sure to 
1. closeArchiveEntry in case of Exception to avoid  `Suppressed: java.io.IOException: This archive contains unclosed entries.` when the operation fails midway due to client timeout etc
2. flush after adding each entry so it's visible to the client quicker
https://issues.apache.org/jira/browse/HDDS-10764
The issue is not easily reproducible, this is just a code refactor.
=> HDDS-10764. Tarball creation failing on leader OM node.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMNodeInfo.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/protocolPB/ScmBlockLocationProtocolClientSideTranslatorPB.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMBlockLocationFailoverProxyProvider.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMContainerLocationFailoverProxyProvider.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMFailoverProxyProviderBase.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SCMSecurityProtocolFailoverProxyProvider.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SecretKeyProtocolFailoverProxyProvider.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/proxy/SingleSecretKeyProtocolProxyProvider.java
There are a lot of duplicated SCM proxy provider logic in
- SCMBlockLocationFailoverProxyProvider
- SCMContainerLocationFailoverProxyProvider
- SCMSecurityProtocolFailoverProxyProvider
- SecretKeyProtocolFailoverProxyProvider
It's better to extract the logic to a separate class (e.g parent class) to prevent divergent implementation of this critical logic.
SingleSecretKeyProtocolProxyProvider is a proxy provider that just communicates with a single SCM, therefore it requires a special handling by exposing the getCurrentProxySCMNodeId().
https://issues.apache.org/jira/browse/HDDS-11768
Existing CI.
https://github.com/ivandika3/ozone/actions/runs/13470618964
=> HDDS-11768. Extract SCM failover proxy provider logic

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis_snapshot/OmRatisSnapshotProvider.java
On Large clusters with 1000s of snapshot, Sometimes bootstrap takes hours together and current log doesn't indicate which snapshot download is under progress. We need to find a way to print progress of bootstrap.
Overall ask in this jira would be to have some logging indicating the progress on bootstrap process.
Fix done :
1.  Included om db checkpoint name that is being downloaded in the logs.
2. Printing progress of the download after an interval of 30s .
https://issues.apache.org/jira/projects/HDDS/issues/HDDS-12288
Verified via stdout of "**TestOzoneManagerSnapshotProvider**" that the logs were printed while downloading the snapshot. 
Output of test logs:
1. This output shows the log including the om db checkpoint name
`2025-02-13 13:28:45,796 [main] INFO …
=> HDDS-12288. Improve bootstrap logging to indicate progress

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/OzoneRpcClientTests.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClient.java
Tests covering atomic key rewrite should handle the case where the feature is disabled via config ([HDDS-11378](https://issues.apache.org/jira/browse/HDDS-11378)). Please take a look, thanks!
[HDDS-12388](https://issues.apache.org/jira/browse/HDDS-12388)
=> HDDS-12388. Key rewrite tests should be skipped if feature is disabled

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/__tests__/datanodes/Datanodes.test.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/__tests__/datanodes/DatanodesTable.test.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/__tests__/locators/locators.ts, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/__tests__/mocks/pipelineMocks/pipelineResponseMocks.ts, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/__tests__/mocks/pipelineMocks/pipelinesServer.ts, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/__tests__/pipelines/Pipelines.test.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/__tests__/pipelines/PipelinesTable.test.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/__tests__/utils/pipelines.utils.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/tables/pipelinesTable.tsx
HDDS-9792. Add tests for Pipelines page
* This PR adds unit tests for the new Pipelines page, and the Pipelines Table component
* It also updates the imports from absolute import to use symbolic/alias import i.e from `@/__tests__` to the alias `@tests`
https://issues.apache.org/jira/browse/HDDS-9792
=> HDDS-9792. Add tests for Pipelines page

hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - DeleteKey Metrics.json
A system-wise deletion dashboard to track deletion progress is created in this PR. The existing dashboard is updated to include the below metrics:
SCM:
Deletion commands:
- No. of commands sent (numBlockDeletionCommandSent)
- No. of commands successful (numBlockDeletionCommandSuccess)
- No. of commands failed (numBlockDeletionCommandFailure)
Delete transactions:
- No. of transactions created (numBlockDeletionTransactionCreated)
- No. of transactions sent (numBlockDeletionTransactionSent)
- No. of transactions completed (numBlockDeletionTransactionCompleted)
- No. of transactions successful (numBlockDeletionTransactionSuccess)
- No. of transactions failed (numBlockDeletionTransactionFailure) 
- No. of  transactions skipped (numSkippedTransactions)
- Success percentage of delete …
=> HDDS-11512. Create Grafana dashboard for tracking system wide deletion

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/OzoneClientConfig.java, hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientCreator.java, hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientRatis.java, hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/client/HddsClientUtils.java, hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/BlockInputStream.java
Code for the hdds-client made compliant with PMD.FieldDeclarationsShouldBeAtStartOfClass verification rule.
It is done before enabling the rule itself to prevent us reviewing a very huge PR. 
https://issues.apache.org/jira/browse/HDDS-12411
Patch tested using standard verification pipeline.
=> HDDS-12411. Make hdds-client compliant with PMD.FieldDeclarationsShouldBeAtStartOfClass

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OmConfig.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/TestOmConfig.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFSBucketLayout.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFSInputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFSWithObjectStoreCreate.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemMetrics.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemMissingParent.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestContainerOperations.java, hadoop-ozone/integration-test/src/test/java/org/apache/ozone/test/NonHATests.java
Speed up the following filesystem tests by adding to `NonHATests`:
- `TestOzoneFSBucketLayout`
- `TestOzoneFSInputStream`
- `TestOzoneFSWithObjectStoreCreate`
- `TestOzoneFileSystemMetrics`
- `TestOzoneFileSystemMissingParent`
Fix `TestContainerOperations` to leave datanode in its original state, not in `DECOMMISSIONING`.
https://issues.apache.org/jira/browse/HDDS-12345
Before:
```
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 35.94 s -- in org.apache.hadoop.fs.ozone.TestOzoneFSBucketLayout
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 51.02 s -- in org.apache.hadoop.fs.ozone.TestOzoneFSInputStream
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 37.97 s -- in org.apache.hadoop.fs.ozone.TestOzoneFSWithObjectStoreCreate
Tests run: 3, …
```
=> HDDS-12345. Share cluster in filesystem tests

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFSWithObjectStoreCreate.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestDataUtil.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestBucketOwner.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestListKeys.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestListKeysWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestObjectStoreWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestRecursiveAclWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOmSnapshotFileSystem.java
The `TestDataUtil.createKey`  can be reused in many places to reduce the code redundancy, please take a look, thanks!
[HDDS-12348](https://issues.apache.org/jira/browse/HDDS-12348)
=> HDDS-12348. Reuse `TestDataUtil.createKey` method

hadoop-hdds/tools/pom.xml, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ContainerBalancerStatusSubcommand.java, hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestContainerBalancerSubCommand.java
Fix intermittent test failure:
```
Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.411 s <<< FAILURE! - in org.apache.hadoop.hdds.scm.cli.datanode.TestContainerBalancerSubCommand
org.apache.hadoop.hdds.scm.cli.datanode.TestContainerBalancerSubCommand.testContainerBalancerStatusInfoSubcommandVerboseHistory  Time elapsed: 0.127 s  <<< FAILURE!
AssertionFailedError: expected: <true> but was: <false>
...
at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:183)
at org.apache.hadoop.hdds.scm.cli.datanode.TestContainerBalancerSubCommand.testContainerBalancerStatusInfoSubcommandVerboseHistory(TestContainerBalancerSubCommand.java:305)
```
which occurs if balancer happens to be started at the start of the minute (`:00` seconds).  It is caused by relying on …
=> HDDS-12443. Intermittent failure in TestContainerBalancerSubCommand

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/QuotaRepairTask.java, pom.xml
Dependency on `org.codehaus.jackson` (Jackson v1) is only for Ranger, should not be used in Ozone itself.
- replace usage in `QuotaRepairTask`
- ban import
https://issues.apache.org/jira/browse/HDDS-12448
Tested import ban without the fix in `QuotaRepairTask`:
```
[ERROR] Banned imports detected:
[ERROR] 
[ERROR] Reason: Use Jackson 2 (com.fasterxml.jackson)
[ERROR] 	in hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/QuotaRepairTask.java
[ERROR] 		org.codehaus.jackson.map.ObjectMapper 	(Line: 60, Matched by: org.codehaus.jackson.**)
```
Existing tests: `TestOzoneRepairShell`, `TestQuotaRepairTask`.
CI:
https://github.com/adoroszlai/ozone/actions/runs/13602780164
=> HDDS-12448. Avoid using Jackson1

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMBlockProtocolServer.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/server/TestSCMBlockProtocolServer.java
This ticket is to add detailed allocated blocks for ALLOCATED_BLOCK operation.
https://issues.apache.org/jira/browse/HDDS-12410
```
2025-02-25 09:45:33,239 | INFO  | SCMAudit | user=hadoop | ip=192.168.240.9 | op=ALLOCATE_BLOCK {replication=RATIS/ONE, owner=omservice, size=268435456, blocks=[conID: 1 locID: 115816896921600001], num=1, client=, allocated=1} | ret=SUCCESS |  
```
=> HDDS-12410. Add detailed block info for ALLOCATE_BLOCK audit log

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmInfo.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/client/ScmClient.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/scm/protocolPB/StorageContainerLocationProtocolClientSideTranslatorPB.java, hadoop-hdds/interface-client/src/main/proto/hdds.proto, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocolServerSideTranslatorPB.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ContainerOperationClient.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/StorageContainerServiceProviderImpl.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/admin/scm/GetScmRatisRolesSubcommand.java, hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/scm/TestGetScmRatisRolesSubcommand.java
Remove `scmRatisEnabled` from `ScmInfo`.
Since Ratis is always enabled in SCM, there is no need for `scmRatisEnabled` in `ScmInfo`.
HDDS-12376
CI Run: https://github.com/nandakumar131/ozone/actions/runs/13410928769
=> HDDS-12376. Remove scmRatisEnabled from ScmInfo.

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMPerformanceMetrics.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/AbstractKeyDeletingService.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/OpenKeyCleanupService.java
This PR adds metrics in OM to measure how long each iteration of the deletion services are taking. Latency metrics for DirectoryDeletionService, KeyDeletingService, OpenKeyCleanupService are added.
https://issues.apache.org/jira/browse/HDDS-12442
Tested manually using docker with prometheus:
=> HDDS-12442. Add latency metrics for OM deletion services

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeClientProtocolServer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
#4788 added workaround to fix the thread rename issue caused by [HDFS-13566](https://issues.apache.org/jira/browse/HDFS-13566).
[HDFS-13566](https://issues.apache.org/jira/browse/HDFS-13566) is fixed by [HADOOP-18433](https://issues.apache.org/jira/browse/HADOOP-18433) in Hadoop 3.4.x (and in 3.3.6).
Since Ozone has upgraded to Hadoop 3.4.1, we should be able to remove the workaround added in #4788
HDDS-12470
CI Run: https://github.com/nandakumar131/ozone/actions/runs/13657993310
=> HDDS-12470. Revert workaround added by HDDS-8715 to preserve thread name.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/AbstractOzoneFileSystemTest.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestCloseContainer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/node/TestDecommissionAndMaintenance.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestDataUtil.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/OzoneRpcClientTests.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestListKeys.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestListKeysWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMDbCheckpointServlet.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmAcls.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmBlockVersioning.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDeletingServiceIntegrationTest.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneContainerUpgradeShell.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneDebugShell.java
TestDataUtil has several variants of createKey. This should be refactored to reduce duplication. `createKey(... String content)` can be removed, since we already have `createKey(... byte[] buffer)` functions to use. Please take a look, thanks!
[HDDS-12417](https://issues.apache.org/jira/browse/HDDS-12417)
=> HDDS-12417. Reduce duplication of createKey variants in TestDataUtil

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsConfigKeys.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/conf/OzoneConfiguration.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/TestHddsDatanodeService.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/TestHddsSecureDatanodeInit.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestDeleteBlocksCommandHandler.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestVolumeSet.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestVolumeSetDiskChecks.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestContainerImporter.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestSendContainerRequestHandler.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/UniformDatanodesFactory.java
Currently, the config keys moved from `DFSConfigKeysLegacy` are added as exceptions in `TestOzoneConfigurationFields`, which means they remain undocumented. To improve visibility for Ozone users, these keys are documented in ozone-default.xml.
https://issues.apache.org/jira/browse/HDDS-12430
Green CI: https://github.com/sarvekshayr/ozone/actions/runs/13673371113
=> HDDS-12430. Document the config keys moved from DFSConfigKeysLegacy in ozone-default.xml

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/TestHelper.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestReplicationConfigPreference.java, hadoop-ozone/integration-test/src/test/java/org/apache/ozone/test/NonHATests.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
- Allow updating server-default replication settings without restarting OM to speed up tests.  Cannot add to reconfiguration framework, because it applies property changes one by one, but these two settings must be changed at the same time (`EC/THREE` or `RATIS/rs-3-2-1024k` are invalid).  Later we may improve this by ignoring invalid configurations during the update.
- Add `TestReplicationConfigPreference` to `NonHATests` (using HA cluster is not really needed) and simplify it by refactoring to a single parameterized test, instead of using hard-coded bucket/key names for handling different scenarios.
- Add imports in `NonHATests` for all nested classes.
https://issues.apache.org/jira/browse/HDDS-12295
Before:
```
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 81.36 s -- …
```
=> HDDS-12295. Allow updating OM default replication config for tests

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/MismatchedReplicasHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/health/TestMismatchedReplicasHandler.java
If the container is in CLOSED state and the Replica state in SCM is OPEN/CLOSING state, we are force closing the Container without comparing the BCSID. We should not force close the replicas in OPEN/CLOSING state.
Changing the should close function to return the expected final state and setting force parameter based on the value returned.
https://issues.apache.org/jira/browse/HDDS-12428?jql=text%20~%20%22force%20close%22
Adding unit tests.
=> HDDS-12428. Avoid force closing OPEN/CLOSING replica of a CLOSED Container

hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - DeleteKey Metrics.json
[HDDS-12442](https://issues.apache.org/jira/browse/HDDS-12442) introduced latency metrics for KeyDeletingService, DirectoryDeletingService and OpenKeyCleanupService. These metrics would be useful on the deletion Grafana board.
https://issues.apache.org/jira/browse/HDDS-12474
Checked through local deployment of grafana:
=> HDDS-12474. Add latency metrics of deletion services to grafana dashboard

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/FilePerBlockStrategy.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/interfaces/BlockManager.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/impl/TestBlockManagerImpl.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/impl/TestFilePerBlockStrategy.java
The `putBlock` call for `OPEN` container cannot be used for the `CLOSED` container and needs some modification to update `bscId` and remove changes that are only applicable to `OPEN` container such a pending put block cache, hsync support. 
https://issues.apache.org/jira/browse/HDDS-12397
Added Unit Test.
=> HDDS-12397. Persist putBlock for closed container.

hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - Overall Metrics.json
Introduced a new Cluster Health panel to the existing Grafana dashboard.
The growth rate is calculated dynamically based on Prometheus metrics, using the following PromQL query:
`sum(rate(scm_node_manager_total_used[1h])) * 100 / sum(scm_node_manager_total_used)`
Here 1h can be changed based on user selection, but default it will show in last 1 hour, what is the growth rate.
This is how the new panel looks like in the Grafana "Ozone - Overall Metrics" Dashboard 
https://issues.apache.org/jira/browse/HDDS-12168
Tested locally via docker by running a freon workload
Below is the successfully passed workflow
https://github.com/sreejasahithi/ozone/actions/runs/13559737886
=> HDDS-12168. Create new Grafana panel to display cluster growth rate

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeProtocolServer.java
Use TextFormat#shortDebugString to flatten proto message in SCMDatanodeProtocolServer.
Currently we have a custom implementation to flatten the string generated by `proto#toString`, which is not required. We can use `TextFormat#shortDebugString` instead.
HDDS-12496
CI Run: https://github.com/nandakumar131/ozone/actions/runs/13716111984
Output 
Before the change:
```
2025-03-04 17:08:46,166 | INFO  | SCMAudit | user=dn/dn@EXAMPLE.COM | ip=172.19.0.6 | op=SEND_HEARTBEAT {datanodeUUID=7c397365-5024-4a6a-bd66-2afd462f074e, term=2, command=[commandType: closePipelineCommand closePipelineCommandProto { pipelineID { id: "4ba00bcb-43bb-4f4c-9aec-e7ebb664b9f3" uuid128 { mostSigBits: 5449368516760915788 leastSigBits: -7283191497801549325 } } cmdId: 1741107361521 } term: 2 encodedToken: "" …
```
=> HDDS-12496. Use TextFormat#shortDebugString to flatten proto message in SCMDatanodeProtocolServer.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestCloseContainer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestDataUtil.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestListKeys.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestListKeysWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMDbCheckpointServlet.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDeletingServiceIntegrationTest.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneContainerUpgradeShell.java
Improve `TestDataUtil#createKey` to avoid the need to pass `ReplicationConfig` unnecessarily:
- Allow `TestDataUtil#createKey(OzoneBucket, String, ReplicationConfig, byte[])` to be called with `repConfig=null`, in which case it should create the key using `OzoneBucket#createKey(String, long)`
- Change `createKey(OzoneBucket, String, byte[])` to pass null instead of `RATIS/ONE`
- Tests that call `createKey(OzoneBucket, String, byte[])` and start failing should be changed to pass `RATIS/ONE` explicitly.
- Change callers of `TestDataUtil#createKey(OzoneBucket, String, ReplicationConfig, byte[])` to not pass `ReplicationConfig`, unless necessary for the test.
[HDDS-12477](https://issues.apache.org/jira/browse/HDDS-12477)
=> HDDS-12477. Do not force RATIS/ONE replication in TestDataUtil#createKey

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ratis/ServerNotLeaderException.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/ratis/TestServerNotLeaderExceptionMessageParsing.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/RatisUtil.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/SCMSecurityProtocolServerSideTranslatorPB.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/ScmBlockLocationProtocolServerSideTranslatorPB.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/SecretKeyProtocolServerSideTranslatorPB.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/protocol/StorageContainerLocationProtocolServerSideTranslatorPB.java
This pr enhanced the content of `ServerNotLeaderException` by add `hostname` into the content (in example: 172.16.102.166). Please take a look.
[HDDS-12204](https://issues.apache.org/jira/browse/HDDS-12204)
Deploy and check the error output.
```shell
2025-02-13 13:30:29,329 [IPC Server listener on 9860] INFO ipc.Server: IPC Server listener on 9860: starting
2025-02-13 13:30:29,338 [main] INFO server.StorageContainerManager: ScmBlockLocationProtocol RPC server is listening at /0.0.0.0:9863
2025-02-13 13:30:29,338 [main] ERROR server.StorageContainerManagerStarter: SCM start failed with exception
org.apache.hadoop.hdds.ratis.ServerNotLeaderException: Server:f9732a56-9253-4537-ad92-51af5875dc2e(172.16.102.166) is not the leader. Could not determine the leader node.
```
=> HDDS-12204. Improve failover logging

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFSWithObjectStoreCreate.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestDataUtil.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestListKeys.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestListKeysWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestObjectStoreWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestRecursiveAclWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOmSnapshotFileSystem.java
Several callers of `TestDataUtil#createKey` just want to write some data, without any interest in the content being written. The goal of this task is to create a variant of the method which generates some small random `byte[] content` instead of accepting it via parameter. To let the caller verify data (e.g. via `readKey`), this variant of `createKey` should return the random content it generated. Please take a look, thanks!
[HDDS-12476](https://issues.apache.org/jira/browse/HDDS-12476)
Tested by CI.
=> HDDS-12476. Add TestDataUtil#createKey variant with small random content

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/diskbalancer/DiskBalancerService.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/diskbalancer/DiskBalancerServiceMetrics.java
Add metrics in DiskBalancerServiceMetrics to record the time spent on container move, for both success and failure case.
https://issues.apache.org/jira/browse/HDDS-12436
The patch was tested manually by running docker cluster and seeing the results at JMX endpoint and prometheus. At prometheus endpoint by querying for `disk_balancer_service_metrics_move_success_time_avg_time` and `disk_balancer_service_metrics_move_failure_time_avg_time` it shows the change in graph curves and the average time taken for the successful and failure moves respectively.
```
"name" : "Hadoop:service=HddsDatanode,name=DiskBalancerServiceMetrics",
"modelerType" : "DiskBalancerServiceMetrics",
"tag.Context" : "dfs",
"tag.Hostname" : "2757e35f9c78",
"FailureCount" : 6,
"IdleLoopExceedsBandwidthCount" : 0, …
```
=> HDDS-12436. [DiskBalancer] Add metrics for time spent by container move

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/container/metrics/TestSCMContainerManagerMetrics.java
Fix intermittent timeout in TestSCMContainerManagerMetrics.testReportProcessingMetrics.  Metrics would not be incremented if existing container could accomodate the key.
Also: code cleanup by using method from `TestDataUtil` to create the key.
https://issues.apache.org/jira/browse/HDDS-12489
Passed in 10x20 runs:
https://github.com/adoroszlai/ozone/actions/runs/13717057749
=> HDDS-12489. Intermittent timeout in TestSCMContainerManagerMetrics.testReportProcessingMetrics

dev-support/pmd/pmd-ruleset.xml, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOzoneAclUtil.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/security/TestGDPRSymmetricKey.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestDirectoryDeletingServiceWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/OzoneRpcClientTests.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestDeleteContainerHandler.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestFinalizeBlock.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAWithAllRunning.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmMetadataManager.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/fsck/TestContainerHealthTaskRecordGenerator.java
Added SimplifiableTestAssertion PMD rule.
https://issues.apache.org/jira/browse/HDDS-12450
existing tests
=> HDDS-12450. Enable SimplifiableTestAssertion check in PMD

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/server/YamlUtils.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/helpers/DatanodeIdYaml.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerData.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerDataYaml.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainer.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/helpers/TestDatanodeIdYaml.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerDataYaml.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestContainerImporter.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/container/upgrade/UpgradeTask.java
Use AtomicFileOutputStream to write YAML files and also clean up the code.
HDDS-12531
=> HDDS-12531. Use AtomicFileOutputStream to write YAML files.

hadoop-ozone/dev-support/checks/license.sh, hadoop-ozone/fault-injection-test/mini-chaos-tests/pom.xml, hadoop-ozone/integration-test/pom.xml, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneCluster.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/s3/awssdk/S3SDKTestUtils.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v1/AbstractS3SDKV1Tests.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v2/AbstractS3SDKV2Tests.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v2/TestS3SDKV2.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v2/TestS3SDKV2WithRatisStreaming.java, hadoop-ozone/integration-test/src/test/resources/log4j.properties, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/SignedChunksInputStream.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ObjectEndpoint.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/signature/StringToSignProducer.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/util/S3Consts.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/util/S3Utils.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/TestAuthorizationFilter.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectPut.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestPartUpload.java, pom.xml
From AWS Java SDK V2 2.30.0, The SDK automatically uses the CRC32 algorithm to calculate the checksum and provides it in the request. This will make default S3 PutObject and UploadPart requests to add a checksum trailer in the request body (e.g. `x-amz-checksum-crc32:ZS91yQ==`). 
The solution contains two parts:
1. Handle the trailer variants of the signature algorithm (e.g. `STREAMING-AWS4-HMAC-SHA256-PAYLOAD-TRAILER`) to also use `SignedChunksInputStream` and the `x-amz-decoded-content-length`
2. Change all `IOUtils#copy` to `IOUtils#copyLarge(final InputStream input, final OutputStream output, final long inputOffset, final long length, final byte[] buffer)` which specifies the length to `x-amz-decoded-content-length` so that the trailer is excluded. …
=> HDDS-12488. S3G should handle the signature calculation with trailers

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerSet.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/ContainerTestUtils.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestSchemaOneBackwardsCompatibility.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestSchemaTwoBackwardsCompatibility.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestStaleRecoveringContainerScrubbingService.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/ContainerImplTestUtils.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerDeletionChoosingPolicy.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerPersistence.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerSet.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestHddsDispatcher.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCloseContainerCommandHandler.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestDeleteBlocksCommandHandler.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestVolumeSetDiskChecks.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueHandler.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestContainerReader.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestContainerImporter.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestGrpcReplicationService.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestReplicationSupervisor.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestSendContainerRequestHandler.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/InMemoryTestTable.java, hadoop-hdds/tools/pom.xml, hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/container/upgrade/TestUpgradeManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/TestCSMMetrics.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/metrics/TestContainerMetrics.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/server/TestContainerServer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/server/TestSecureContainerServer.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/datanode/container/ContainerCommands.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/ClosedContainerReplicator.java
InMemoryTestTable is a class for testing.  It should be moved to test.
HDDS-12536
=> HDDS-12536. Move InMemoryTestTable to test.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/diskbalancer/DiskBalancerInfo.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/diskbalancer/DiskBalancerService.java, hadoop-hdds/interface-client/src/main/proto/hdds.proto, hadoop-hdds/interface-server/src/main/proto/ScmServerDatanodeHeartbeatProtocol.proto, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DiskBalancerManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DiskBalancerStatus.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DiskBalancerStatusSubcommand.java
As the status helps to reveal the disk balancer task state to user, add success move count and fail move count to status report.
https://issues.apache.org/jira/browse/HDDS-12435
The patch was tested manually on docker cluster by checking diskbalancer status command.
```
bash-5.1$ ozone admin datanode diskbalancer status
Status result:
Datanode                                 VolumeDensity        Status     Threshold(%) BandwidthInMB   Threads         SuccessMove     FailureMove    
ozone-datanode-1.ozone_default           0.010688673650023704 RUNNING    0.0002       10              5               2               0              
ozone-datanode-2.ozone_default           0.02164608881687885  RUNNING    0.0002       10              5               3               0              
```
=> HDDS-12435. [DiskBalancer] Add success move count and fail move count in status report

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/states/ContainerAttribute.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/states/ContainerStateMap.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/states/TestContainerAttribute.java
```java
//ContainerStateMap
private final ContainerAttribute<LifeCycleState> lifeCycleStateMap;
private final ContainerAttribute<String> ownerMap;
private final ContainerAttribute<ReplicationConfig> repConfigMap;
private final ContainerAttribute<ReplicationType> typeMap;
```
ContainerStateMap has four ContainerAttribute maps above. However, the ownerMap and the repConfigMap are unused. If these two maps are removed, the ContainerAttribute generic type T can be restricted to Enum for simplicity and efficiency.
HDDS-12532
=> HDDS-12532. Support only Enum in ContainerAttribute.

hadoop-hdds/common/dev-support/findbugsExcludeFile.xml, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/cli/GenericCli.java, hadoop-ozone/httpfsgateway/dev-support/findbugsExcludeFile.xml, hadoop-ozone/httpfsgateway/src/main/java/org/apache/ozone/fs/http/server/HttpFSServerWebApp.java, hadoop-ozone/httpfsgateway/src/main/java/org/apache/ozone/lib/service/instrumentation/InstrumentationService.java, hadoop-ozone/httpfsgateway/src/main/java/org/apache/ozone/lib/servlet/ServerWebApp.java
Fix some spotbugs problems in non-test code previously suppressed via config.
https://issues.apache.org/jira/browse/HDDS-12383
Verified `ozone` CLI exit code by running some successful and failing commands.
CI:
https://github.com/adoroszlai/ozone/actions/runs/13773992991
=> HDDS-12383. Fix spotbugs warnings in hdds-common & httpfsgateway.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneCluster.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/MiniOzoneHAClusterImpl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/s3/S3GatewayService.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v1/AbstractS3SDKV1Tests.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v2/AbstractS3SDKV2Tests.java
Remove S3 Gateway-specific details from `MiniOzoneCluster`, hiding it behind a more generic `Service` interface.
This allows moving S3 tests to a separate module in a follow-up (HDDS-12528).
https://issues.apache.org/jira/browse/HDDS-12527
CI:
https://github.com/adoroszlai/ozone/actions/runs/13808975185
=> HDDS-12527. Separate S3 Gateway from MiniOzoneCluster

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/StateContext.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CloseContainerCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/ClosePipelineCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CommandDispatcher.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CreatePipelineCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteContainerCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/FinalizeNewLayoutVersionCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/ReconstructECContainersCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/RefreshVolumeUsageCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/ReplicateContainerCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/SetNodeOperationalStateCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/StorageContainerNodeProtocol.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ContainerHealthResult.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/CommandQueue.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DeadNodeHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeHeartbeatDispatcher.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeProtocolServer.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/SimpleMockNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestCommandQueue.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/container/testutils/ReplicationNodeManagerMock.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestStorageContainerManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconNodeManager.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconNodeManager.java
Fix Raw use of parameterized class 'SCMCommand'.
HDDS-12552
CI : https://github.com/nandakumar131/ozone/actions/runs/13787862336
=> HDDS-12552. Fix Raw use of parameterized class 'SCMCommand'.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/TestContainerStateMachine.java
1. When same write log is retry and already existing operation in progress, return back existing future
2. Validate if write operation time crosses threshold, if crosses, mark statemachine as unhealthy
The trigger will be when next operation comes, check for existing operation if any timeout occurred. Here, lowest index checking should be enough as that is the first operation in-progress and to be completed for next one to be marked committed.
https://issues.apache.org/jira/browse/HDDS-12469
- Unit test case added
- Impact via existing integration test
=> HDDS-12469. mark statemachine unhealthy for write operation timeout

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/SafeModeCheckSubcommand.java
Show safemode rules status irrespective of whether SCM is in safe mode in verbose mode.
When --verbose is passed , it should show safemode status irrespective of safemode.
This can help in situations where someone force exits safe mode and is trying to track progress.
https://issues.apache.org/jira/browse/HDDS-12548
Tried it out on a docker compose cluster.
```
bash-5.1$ ozone admin safemode status
SCM is in safe mode.
bash-5.1$ ozone admin safemode exit
SCM exit safe mode successfully.
bash-5.1$ ozone admin safemode status
SCM is out of safe mode.
bash-5.1$ ozone admin safemode status --verbose
SCM is out of safe mode.
validated:false, DataNodeSafeModeRule, registered datanodes (=0) >= required datanodes (=1)
validated:true, HealthyPipelineSafeModeRule, healthy Ratis/THREE pipelines (=0) …
```
=> HDDS-12458. Show safemode rules status irrespective of whether SCM is in safe mode in verbose mode.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerStateManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerStateManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerReportHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerStateManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestIncrementalContainerReportHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestContainerPlacement.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerStateManagerIntegration.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestDeletedBlocksTxnShell.java
In the ContainerStateManager interface, some methods have both ContainerID and ContainerReplica as parameters.  In such cases, the ContainerID parameter can be removed since ContainerReplica already has a ContainerID.
HDDS-12572
By updating existing tests
=> HDDS-12572. Remove the ContainerID parameter when it has ContainerReplica.

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBStoreBuilder.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStore.java
The actual value of threadNamePrefix parameter in the db/table related classes is always an empty string.  Let's simply use the db name as threadNamePrefix and remove the parameter.
HDDS-12590
=> HDDS-12590. Used db name as the threadNamePrefix.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/QuasiClosedStuckOverReplicationHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationTestUtil.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestQuasiClosedStuckOverReplicationHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManagerScenarios.java, hadoop-hdds/server-scm/src/test/resources/replicationManagerTests/quasi_closed.json
This PR follows on from [HDDS-12483](https://issues.apache.org/jira/browse/HDDS-12483), which added under replication handling for quasi-closed suck containers. In that PR, we ensure that each origin has 2 copies, or 3 copies if there is a single origin. 
This PR handles over replication of quasi-closed stuck containers so the replica count is reduced to 2 per origin if the container has more than that.
https://issues.apache.org/jira/browse/HDDS-12566
New tests added.
=> HDDS-12566. Handle Over replication of Quasi Closed Stuck containers

hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OmConfig.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/TestOmConfig.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
To take advantage of the type safety and reduced boilerplate offered by configuration objects ([HDDS-1466](https://issues.apache.org/jira/browse/HDDS-1466)), this PR moves the definition of the ozone.om.user.max.volume parameter into OmConfig, and updates its single usage accordingly.
In addition to the steps described on [HDDS-12303](https://issues.apache.org/jira/browse/HDDS-12303), the following changes are also made:
- Removing the definition from ozone-default.xml, as it is now generated from the annotations.
- Removing the configuration key and default from OMConfigKeys, as there are no usages left.
- Removing the now unused imports from OzoneManager.
- Adding the full configuration key to OmConfig to allow keeping the validation unchanged in a straightforward way.
- Including the …
=> HDDS-12303. Move ozone.om.user.max.volume into OmConfig

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/states/ContainerAttribute.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/states/ContainerStateMap.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/states/TestContainerAttribute.java
ContainerAttribute currently only has ContainerID. However, the related methods in ContainerStateManager returns ContainerInfo but not ContainerID. If ContainerInfo is included in ContainerAttribute, it will save a map lookup (from id to info in containerMap) per returned entry.
HDDS-12591
=> HDDS-12591. Include ContainerInfo in ContainerAttribute.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java
In `SCMNodeManager`, we maintain `DNS` to `Datanode` mapping. This is currently using `UUID` to represent `Datanode`, we can replace the `UUID` with `DatanodeID`.
[HDDS-12551](https://issues.apache.org/jira/browse/HDDS-12551)
=> HDDS-12551. Replace dnsToUuidMap with dnsToDnIdMap in SCMNodeManager

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/CodecRegistry.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBStore.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/cache/PartialTableCache.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/cache/TableCache.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/cache/TableNoCache.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBTableStore.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/cache/TestTableCache.java
can create TypedTable with custom key and value Codec, this will be used for customized codec where it may be required to avoid some field for performance.
Also added TABLE_NO_CACHE type caching, so that TypedTable becomes light-weight in creation and operation; and complexity / threads present PARTIAL_TABLE_CACHE class can be avoided.
Sample:
1. 
```
// Use basic type for value codec like ByteString, and no conversion to protobuf
Table<String, ByteString> tbl3 = store.getTable(FILE_TABLE, String.class, ByteString.class,
StringCodec.get(), ByteStringCodec.get(), TableCache.CacheType.NO_CACHE);
```
2. 
```
// Use only conversion to protobuf type, but not Ozone object deserialization
Table<String, KeyInfo> tbl4 = store.getTable(FILE_TABLE, String.class, KeyInfo.class,
StringCodec.get(), …
```
=> HDDS-12582. TypedTable support using different codec

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/ContainerEndpoint.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestContainerEndpoint.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestContainerKeyMapperTask.java
**Problem:**  
When using FSO buckets, files with the same name uploaded into different directories were being merged into a single key record. This was because Recon’s container key mapping used only the volume, bucket, and file name as the unique identifier, which ignored the full directory path information.
**Reproducing the Issue:**  
The issue can be reproduced by creating a nested directory structure and uploading two files (testfile1 and testfile2) at different directory depths. For example, run the following commands:
```
ozone fs -mkdir -p ofs://om/volume1/fso-bucket/dir1/dir2/dir3
ozone fs -put -f testfile1 ofs://om/volume1/fso-bucket/dir1/
ozone fs -put -f testfile2 ofs://om/volume1/fso-bucket/dir1/
ozone fs -put -f testfile1 ofs://om/volume1/fso-bucket/dir1/dir2/
ozone fs -put …
```
=> HDDS-12589. Fix Incorrect FSO Key Listing for Container-to-Key Mapping.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeStateManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/states/NodeNotFoundException.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/states/NodeStateMap.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/SimpleMockNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManagerUtil.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestContainerPlacement.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestNodeDecommissionManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestNodeStateManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/states/TestNodeStateMap.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/ozone/container/testutils/ReplicationNodeManagerMock.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/NodeEndpoint.java
NodeStateMap currently uses UUID as keys. It is better to replace it with DatanodeID.
HDDS-12617
=> HDDS-12617. Use DatanodeID as keys in NodeStateMap.

hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - Ozone Manager RocksDB.json
HDDS-12446. Add a Grafana dashboard for low level RocksDB operations.
* Add a Grafana dashboard to expose Ozone Manager RocksDB statistics.
* Some of the metrics require ozone.metastore.rocksdb.statistics ALL or EXCEPT_DETAILED_TIMERS (default is OFF).
https://issues.apache.org/jira/browse/HDDS-12446
Please see the screenshots:
=> HDDS-12446. Add a Grafana dashboard for low level RocksDB operations.

hadoop-hdds/common/src/main/resources/ozone-default.xml
[HDDS-9273](https://issues.apache.org/jira/browse/HDDS-9273) changes the default volume choosing policy from `RoundRobinVolumeChoosingPolicy` to `CapacityVolumeChoosingPolicy`.
Update `ozone-default.xml` to reflect the new default value of `hdds.datanode.volume.choosing.policy` to `org.apache.hadoop.ozone.container.common.volume.CapacityVolumeChoosingPolicy`.
[HDDS-11735](https://issues.apache.org/jira/browse/HDDS-11735)
CI: https://github.com/sarvekshayr/ozone/actions/runs/13920274839
=> HDDS-11735. Update ozone-default.xml for volume choosing policy

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/fs/AbstractSpaceUsageSource.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/fs/DedicatedDiskSpaceUsage.java
The current logic for "hdds.datanode.dir.du.reserved" is as follows:
```
private long getRemainingReserved(){
return Math.max(reservedInBytes - getOtherUsed(), 0L); 
} 
```
which means if OtherUsed() is larger than reservedInBytes, then remainingReserved will be count to 0.
When we set a "hdds.datanode.dir.du.reserved" to 100GB, we actually want the disk to spare 100GB in case of "SPACE not enough exceptions".
But normally servers have a system level block reservation, which is 5%. So for a 10T disk, the system level reserved space is about 500GB, when we set the configuration to 100GB, the "remaningReserved" is calculated as 0, so for capacity and availabilty, reservation is not counted.
In current calculation logic ,in order to reserve a 100GB space, we need to set configuration to …
=> HDDS-12373. Use File.getUsableSpace() instead of File.getFreeSpace() to calcuate usedSpace in DedicatedDiskSpaceUsage

.asf.yaml
ASF moving to `.asf.yml` to manage GitHub Features.
https://issues.apache.org/jira/browse/HDDS-12630
If GitHub Discussions continue to show up :-)
=> HDDS-12630. Enable GitHub Discussions in asf.yml

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/util/SeekableIterator.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/ContainerEndpoint.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/ReconContainerMetadataManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/ReconContainerMetadataManagerImpl.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/spi/impl/TestReconContainerMetadataManagerImpl.java
Change-Id: I820e10912427c643b05d3e88a7c30094106fbd5a
Currently the Container mismatch API in recon loads up the entire ContainerMetaData from ContainerKeyPrefix table and figures out the container mismatches between OM & SCM. The implication is that the ContainerKeyPrefix table will have as many keys as there there in OM. In case there are too many keys even for loading a small page too many containers would be brought into memory and the result would be eventually discarded because of the page size limit. Instead of this we should implement an container iterator for the containerKeyPrefix table which would iterate on containers sequentially in a sorted fashion along with the scm containerManager iterator and diff would be figured out based on the merging these 2 container list. We can …
=> HDDS-12619. Optimize Recon OM Container Mismatch API

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/util/SeekableIterator.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/ContainerEndpoint.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/ReconContainerMetadataManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/ReconContainerMetadataManagerImpl.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestContainerEndpoint.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/spi/impl/TestReconContainerMetadataManagerImpl.java
Currently the Container mismatch API in recon loads up the first few ContainerMetaData records  from ContainerKeyPrefix table. Then from the scm containerManager all deleted containers are iterated and checked against the records loaded from containerPrefixTable. If a deletedContainer is not present in the loaded list the results turn out to be empty even though there could be some records present in the containerPrefixTable in the next few pages. This could lead to a wrong result by setting the lastKey to null in case it couldn't find any records corresponding to a deletedContainer.
Consider this example:
ContainerPrefixTable has containerIds
1..100 1000-1100
SCM has deletedContainerId
1000-1050
Now if an api call is made with lastKey as 50 and limit as 50
Now from the ContainerPrefix …
=> HDDS-12620. Fix OM Mismatch Deleted Container API

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/persistence/ContainerHealthSchemaManager.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/fsck/TestContainerHealthTask.java
This PR change is to handle ContainerHealthTask ConstraintViolationException during the running of ContainerHealthTask.
Currently ContainerHealthTask gets aborted when "pk_container_id" ConstraintViolationException being thrown on UNHEALTHY_CONTAINERS table. Since this is a composite key and task should not be aborted , rather Recon's container health task should update the other fields of table if "pk_container_id" ConstraintViolationException being thrown on UNHEALTHY_CONTAINERS table.
https://issues.apache.org/jira/browse/HDDS-12585
This patch is tested using existing junit and integration tests and running in local docker cluster.
=> HDDS-12585. Recon ContainerHealthTask ConstraintViolationException error handling.

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/missingContainers/missingContainers.tsx
This PR change is to change the label from `No. of Keys` to `No. of Blocks` as it was incorrect.
https://issues.apache.org/jira/browse/HDDS-12588
Patch is simple and tested manually by running the ozone and recon in docker cluster locally. Please refer below screenshot:
=> HDDS-12588. Recon Containers page shows number of blocks, not keys

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMDBCheckpointServlet.java
No logs to indicate checkpoint tarball in leader OM. 
Added logs to provide an initial estimate of the amount of data, number of files and snapshots to be transferred in the tarball stream.
Added progress indicator logs every 30s detailing # sst files and size of data trasferred per request. 
https://issues.apache.org/jira/browse/HDDS-12557
Manually tested with docker with a progress log interval of `500ms`
Leader OM: 
```
INFO om.OMDBCheckpointServlet: Estimates for Checkpoint Tarball Stream - Data size: 64190 KB, SST files: 48317, snapshots: 300
INFO om.OMDBCheckpointServlet: Transferred 91266 KB, #files 2774 to checkpoint tarball stream... // Will print every 30s. 
INFO om.OMDBCheckpointServlet: Completed transfer of 106103 KB, #files 3183 to checkpoint tarball stream. Checkpoint …
```
=> HDDS-12557. Added progress indicator for checkpoint tarball in leader OM

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OzoneAcl.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OzoneAclUtil.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmBucketInfo.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmKeyInfo.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmVolumeArgs.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOzoneAclUtil.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/AbstractRootedOzoneFileSystemTest.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/OzoneRpcClientTests.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientForAclAuditLog.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestBucketOwner.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerImpl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmMetrics.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAWithAllRunning.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOmSnapshot.java, hadoop-ozone/interface-storage/src/main/java/org/apache/hadoop/ozone/om/helpers/OzoneAclStorage.java, hadoop-ozone/interface-storage/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmPrefixInfo.java, hadoop-ozone/interface-storage/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmPrefixInfoCodec.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/key/acl/prefix/TestOMPrefixAclResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/acl/TestOzoneNativeAuthorizer.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/acl/TestParentAcl.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/common/CommonUtils.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/BucketEndpoint.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/S3Acl.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/containergenerator/GeneratorOm.java
Replace direct constructor usage of `OzoneAcl` with factory method.  This requires trivial, but somewhat large change.  It will make it easier to refactor the class later.
https://issues.apache.org/jira/browse/HDDS-12644
CI:
https://github.com/adoroszlai/ozone/actions/runs/13951163868
=> HDDS-12644. Create factory method for OzoneAcl

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeStatus.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/states/NodeAlreadyExistsException.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/states/NodeStateMap.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/ECPipelineProvider.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestCreateForReadComparator.java
Currently, NodeStatus implements Comparable but the implementation of the compareTo method is very specific to the use case in ECPipelineProvider but not a natural order. It is better to move the implementation to ECPipelineProvider.
HDDS-12626
=> HDDS-12626. Move the compare method in NodeStatus to ECPipelineProvider.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestAddRemoveOzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OMAdminProtocolServerSideImpl.java
HDDS-12646. Improve OM decommission check
* Improve edge case check
https://issues.apache.org/jira/browse/HDDS-12646
Added a test
=> HDDS-12646. Improve OM decommission check

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestCloseContainerHandlingByClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneClientMultipartUploadWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientWithKeyLatestVersion.java, hadoop-ozone/integration-test/src/test/java/org/apache/ozone/test/ClusterForTests.java, hadoop-ozone/integration-test/src/test/java/org/apache/ozone/test/NonHATests.java
Speed up some client integration tests by using shared cluster.
Also, fix intermittent failure caused by background key deletion (HDDS-12465), because it become more frequent with these new tests added.
https://issues.apache.org/jira/browse/HDDS-12341
Before:
```
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 66.09 s -- in org.apache.hadoop.ozone.client.rpc.TestCloseContainerHandlingByClient
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 66.91 s -- in org.apache.hadoop.ozone.client.rpc.TestContainerStateMachineStream
Tests run: 29, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 43.65 s -- in org.apache.hadoop.ozone.client.rpc.TestOzoneClientMultipartUploadWithFSO
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 38.03 s -- in …
```
=> HDDS-12341. Share cluster in client tests

hadoop-hdds/docs/pom.xml, hadoop-hdds/rocksdb-checkpoint-differ/pom.xml
When compiling with maven, the summary at the end shows that most module names have the prefix Apache Ozone .
```
[INFO] Apache Ozone HDDS Hadoop Server dependencies ....... SUCCESS [  0.482 s]
[INFO] Apache Ozone HDDS RocksDB Tools .................... SUCCESS [  0.362 s]
[INFO] RocksDB Checkpoint Differ .......................... SUCCESS [  0.599 s]
[INFO] Apache Ozone HDDS Server Framework ................. SUCCESS [  2.509 s]
[INFO] Apache Ozone/HDDS Documentation .................... SUCCESS [ 51.698 s]
[INFO] Apache Ozone HDDS Container Service ................ SUCCESS [  2.711 s] 
```
Two modules do not follow the standard:
```
<name>Apache Ozone/HDDS Documentation</name> 
<description>Apache Ozone/HDDS Documentation</description> 
<name>RocksDB …
```
=> HDDS-12661. Standardize Maven module names

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigType.java, hadoop-hdds/config/src/main/java/org/apache/hadoop/hdds/conf/ConfigurationTarget.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/StorageLocationReport.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeConfiguration.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/AvailableSpaceFilter.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/HddsVolume.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/MutableVolumeSet.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/StorageVolume.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeUsage.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestHddsDispatcher.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/TestDatanodeConfiguration.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestReservedVolumeSpace.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOzoneConfigurationFields.java
Refactor calculation of `minFreeSpace` for datanode volume.
Currently it is done by `MinFreeSpaceCalculator`, which exists only to avoid repeated lookup of the config setting needed for the calculation.  Of its 3 different usages, `AvailableSpaceFilter` and `StorageLocationReport` both create a new instance for each calculation, which defeats the purpose of storing config values.  Sharing the same instance of `MinFreeSpaceCalculator` from `HddsDispatcher` would require extensive changes.
This PR moves the definition of config properties, as well as validation and calculation, to `DatanodeConfiguration`, which I think is a better fit than `MinFreeSpaceCalculator`.  Config objects are for storing configs, they have methods for validation, and this specific type is already used by …
=> HDDS-12622. Refactor minFreeSpace calculation

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/HddsVolume.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/diskbalancer/DiskBalancerInfo.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/diskbalancer/DiskBalancerService.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/diskbalancer/TestDiskBalancerService.java, hadoop-hdds/interface-client/src/main/proto/hdds.proto, hadoop-hdds/interface-server/src/main/proto/ScmServerDatanodeHeartbeatProtocol.proto, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DiskBalancerManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DiskBalancerStatus.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DiskBalancerStatusSubcommand.java, hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestDiskBalancerSubCommand.java
It will be an estimation value, due to there are other activities going on, such as block deletion, new container creation, container replica deletion, new data ingestion.
This value will be an indicator for roughly how much time are still needed for the disk usage to become even.
Should Include this value in status report too.
The estimated time pending before disk usage become even is given for the happy path in status report.
https://issues.apache.org/jira/browse/HDDS-12437
Unit Test is written for the function in `testDiskBalancerService#testCalculateBytesToMove`.
Tested it manually by running locally on docker-cluster.
```
bash-5.1$ ozone admin datanode diskbalancer status
Status result:
Datanode                            VolumeDensity             Status          Threshold(%) …
```
=> HDDS-12437. [DiskBalancer] Estimate the total size pending to move before disk usage becomes even

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/TarContainerPacker.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestTarContainerPacker.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/Archiver.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMDBCheckpointServlet.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconUtils.java
Tarball creation code exists in:
```
hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/TarContainerPacker.java
hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java
hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconUtils.java
```
The goal of this change is to reduce duplication.  Extract from `TarContainerPacker` methods that are not specific to container, and reuse for other parts of Ozone.
https://issues.apache.org/jira/browse/HDDS-12636
CI:
https://github.com/adoroszlai/ozone/actions/runs/13973234227
=> HDDS-12636. Reduce code duplication for tarball creation

hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneAtRestEncryption.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerStateMachine.java
Creating an Ozone file in encrypted buckets requires requesting an encrypted key from KMS, which delays file creation and could cause unwanted failures. This PR helps load the EDEKs in a cache when OM starts up so that we don't have to reach out to KMS to get the EDEK while creating an encrypted file.
https://issues.apache.org/jira/browse/HDDS-12486
Added a unit test and tested on jojochuang/HDDS-11879 branch.
=> HDDS-12486. Warmup KMS encrypted keys when OM starts

hadoop-ozone/dist/src/main/compose/testlib.sh, hadoop-ozone/dist/src/main/compose/upgrade/README.md, hadoop-ozone/dist/src/main/compose/upgrade/test.sh, hadoop-ozone/dist/src/main/compose/xcompat/lib.sh
After HDDS-11333, we no longer have to manually update Ozone version number in xcompat and upgrade test scripts.  However, upgrade test also uses version number in directory names.  Any callbacks for the current version have to be in a directory exactly matching `ozone.version`, including `-SNAPSHOT`.  As part of the release process `-SNAPSHOT` is removed from `ozone.version`, and prior to this PR, the directory would also need to be renamed before the release.  To avoid that, this PR tweaks upgrade test to remove `-SNAPSHOT` from `OZONE_CURRENT_VERSION`.  Similar problem was fixed for xcompat test in HDDS-11134.
Also, remove obsolete step from upgrade test's documentation related to having to update `OZONE_CURRENT_VERSION` (this could have been removed by HDDS-11333). …
=> HDDS-12666. Remove -SNAPSHOT from OZONE_CURRENT_VERSION in upgrade test

hadoop-ozone/dist/src/main/assemblies/ozone-src.xml
HDDS-12365 added new files for developers, but they are missing from the source tarball.
https://issues.apache.org/jira/browse/HDDS-12671
```
$ mvn -Psrc -DskipRecon -DskipShade -DskipTests clean package
...
$ tar tzvf hadoop-ozone/dist/target/ozone-2.1.0-SNAPSHOT-src.tar.gz | grep -F -e .editorconfig -e .run
-rw------- root/root      2906 2025-03-12 23:12 ozone-2.1.0-SNAPSHOT-src/.editorconfig
-rw------- root/root      1621 2025-03-12 23:12 ozone-2.1.0-SNAPSHOT-src/.run/CsiServer.run.xml
-rw------- root/root      1699 2025-03-12 23:12 ozone-2.1.0-SNAPSHOT-src/.run/Datanode1-ha.run.xml
-rw------- root/root      1693 2025-03-12 23:12 ozone-2.1.0-SNAPSHOT-src/.run/Datanode1.run.xml
-rw------- root/root      2045 2025-03-12 23:12 ozone-2.1.0-SNAPSHOT-src/.run/Datanode2-ha.run.xml
-rw------- …
```
=> HDDS-12671. Include .editorconfig and .run in source tarball

hadoop-ozone/dist/src/main/compose/upgrade/compose/ha/docker-config, hadoop-ozone/dist/src/main/compose/upgrade/upgrades/non-rolling-upgrade/callbacks/2.0.0/callback.sh, hadoop-ozone/dist/src/main/smoketest/hsync/upgrade-hsync-check.robot
Fix failures in HSync upgrade test.
1. HDDS-12029 renamed `ozone debug recover` to `ozone admin om lease recover`, but missed its usage in upgrade test.
2. HSync is disabled in test cluster, so pre-finalization test fails, as client falls back to `flush()`, instead of hitting server with unsupported request:
```
Generate key for o3fs by HSYNC prior to finalization                  | FAIL |
0 != 255
```
```
Running command 'ozone freon dfsg -n 1000 --sync HSYNC -s 10240 --path o3fs://upgrade-hsync-bucket.upgrade-hsync-volume.omservice/ --buffer 1024 --copy-buffer 1024 -p dfsg
${rc} = 0
${output} = ...
2025-03-22 11:27:53,163 [shutdown-hook-0] INFO freon.BaseFreonGenerator: Successful executions: 1000
```
https://issues.apache.org/jira/browse/HDDS-12668
Together with HDDS-12662 on top of …
=> HDDS-12668. HSync upgrade test failure

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/RepairTool.java, hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/repair/TestOzoneRepair.java
We should not print the [warning message](https://github.com/apache/ozone/blob/7ee359daab84842a52258cc8b7ef115fa0ed4cb6/hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/RepairTool.java#L31) about which user the command is running as, since it is only relevant for offline repair. The method [RepairTool#serviceToBeOffline](https://github.com/apache/ozone/blob/7ee359daab84842a52258cc8b7ef115fa0ed4cb6/hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/RepairTool.java#L50) can be used to check whether the tool is online or offline and print the message accordingly.
[HDDS-12485](https://issues.apache.org/jira/browse/HDDS-12485)
Manually test and CI
```shell
bash-5.1$ ozone repair om quota start 
Into call() in repair tool and the service = null
ATTENTION: Running as …
```
=> HDDS-12485. Repair tool should only print user warning for offline commands

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/TestContainerStateMachine.java, pom.xml
In `TestContainerStateMachine`, some of the `when().return()` section are duplicated and can be reduced by wrapping into helper functions. Please take a look, thanks! 
[HDDS-12604](https://issues.apache.org/jira/browse/HDDS-12604)
CI
https://github.com/chiacyu/ozone/actions/runs/13966780708
=> HDDS-12604. Reduce duplication in TestContainerStateMachine

hadoop-ozone/cli-shell/src/main/java/org/apache/hadoop/ozone/shell/Handler.java
When the `--verbose` flag is passed, the command prints the OzoneAddress, which includes the volume, bucket, and key name. However, this disrupts the JSON output format and makes it difficult to parse.
Since, the print output is not essential we can remove it.
[HDDS-12686](https://issues.apache.org/jira/browse/HDDS-12686)
Before
```
bash-5.1$ ozone debug --verbose replicas chunk-info /vol1/buck1/key
Volume Name : vol1
Bucket Name : buck1
Key Name : key
{
"KeyLocations" : [ [ {
"Locations" : {
"containerPath" : "/data/hdds/hdds/CID-f9c2918d-2647-4673-ae26-4712146b9ceb/current/containerDir0/1",
"chunkInfos" : [ {
"chunkName" : "/data/hdds/hdds/CID-f9c2918d-2647-4673-ae26-4712146b9ceb/current/containerDir0/1/chunks/115816896921600001.block",
"chunkOffset" : 0
} ],
.....
```
After
``` …
```
=> HDDS-12686. Suppress OzoneAddress print output in --verbose mode

hadoop-ozone/dev-support/checks/_post_process.sh, hadoop-ozone/dev-support/checks/junit.sh
`mvn --fail-at-end` skips tests in dependent modules.  We should use `mvn --fail-never` to run as many tests as possible.  This applies only to post-commit test run, PR run should still `--fail-fast`.
Also: perform `mvn clean` before running tests to avoid confusion due to leftover classes and results (useful for local runs).
https://issues.apache.org/jira/browse/HDDS-12500
No failures:
```bash
$ ./hadoop-ozone/dev-support/checks/integration.sh -am -pl :hdds-config
...
[INFO] BUILD SUCCESS
$ echo $?
0
$ wc -l target/integration/summary.txt
0 target/integration/summary.txt
```
Introduced compile failure:
```bash
$ ./hadoop-ozone/dev-support/checks/integration.sh -am -pl :hdds-config
...
[ERROR] COMPILATION ERROR : 
[INFO] ------------------------------------------------------------- …
```
=> HDDS-12500. Do not skip JUnit tests in post-commit runs

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFileSystemMetrics.java, hadoop-ozone/integration-test/src/test/java/org/apache/ozone/test/ClusterForTests.java
Suspend key and dir deleting services for the duration of `TestOzoneFileSystemMetrics` to fix intermittent failure:
```
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.395 s <<< FAILURE! -- in org.apache.ozone.test.NonHATests$OzoneFileSystemMetrics
org.apache.ozone.test.NonHATests$OzoneFileSystemMetrics.testFileOps -- Time elapsed: 3.278 s <<< FAILURE!
AssertionFailedError: expected: <230> but was: <198>
at org.apache.hadoop.fs.ozone.TestOzoneFileSystemMetrics.testOzoneFileCommit(TestOzoneFileSystemMetrics.java:134)
at org.apache.hadoop.fs.ozone.TestOzoneFileSystemMetrics.testFileOps(TestOzoneFileSystemMetrics.java:93)
```
https://issues.apache.org/jira/browse/HDDS-12465
Passed 10x10 runs:
https://github.com/adoroszlai/ozone/actions/runs/13999277200
=> HDDS-12465. Intermittent failure in TestOzoneFileSystemMetrics

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/container/ListSubcommand.java, hadoop-ozone/dist/src/main/smoketest/admincli/container.robot, hadoop-ozone/dist/src/main/smoketest/balancer/testBalancer.robot, hadoop-ozone/dist/src/main/smoketest/freon/echoRPCLoad.robot, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneShellHA.java
Support listing containers in json array format. 
https://issues.apache.org/jira/browse/HDDS-12553
Additional robot tests.
=> HDDS-12553. ozone admin container list should output real JSON array

hadoop-ozone/cli-shell/src/main/java/org/apache/hadoop/ozone/shell/bucket/BucketUri.java, hadoop-ozone/cli-shell/src/main/java/org/apache/hadoop/ozone/shell/common/VolumeBucketUri.java, hadoop-ozone/cli-shell/src/main/java/org/apache/hadoop/ozone/shell/keys/KeyUri.java, hadoop-ozone/cli-shell/src/main/java/org/apache/hadoop/ozone/shell/prefix/PrefixUri.java, hadoop-ozone/cli-shell/src/main/java/org/apache/hadoop/ozone/shell/snapshot/SnapshotUri.java
The `OZONE_KEY_URI_DESCRIPTION` says "URI of the volume/bucket/key" which may suggest that it refers to three separate entities rather than a single key path.
To make this clearer, we are refining the URI descriptions.
[HDDS-12687](https://issues.apache.org/jira/browse/HDDS-12687)
CI: https://github.com/sarvekshayr/ozone/actions/runs/14057798994
=> HDDS-12687. Avoid ambiguity in URI descriptions

hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/MiniOzoneChaosCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/TestAllMiniChaosOzoneCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/TestDatanodeMiniChaosOzoneCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/TestMiniChaosOzoneCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/TestOzoneManagerMiniChaosOzoneCluster.java, hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/TestStorageContainerManagerMiniChaosOzoneCluster.java
1. Error in `FailureManager.stop()` causes cluster shutdown to be skipped in `MiniOzoneChaosCluster`:
```
[main] ERROR ozone.MiniOzoneChaosCluster (MiniOzoneChaosCluster.java:shutdown(139)) - failed to shutdown MiniOzoneChaosCluster
java.util.concurrent.CancellationException
at java.util.concurrent.FutureTask.report(FutureTask.java:121)
at java.util.concurrent.FutureTask.get(FutureTask.java:192)
at org.apache.hadoop.ozone.failure.FailureManager.stop(FailureManager.java:84)
at org.apache.hadoop.ozone.MiniOzoneChaosCluster.shutdown(MiniOzoneChaosCluster.java:134)
at org.apache.hadoop.ozone.TestMiniChaosOzoneCluster.shutdown(TestMiniChaosOzoneCluster.java:204)
```
This leaves test data around for each test run:
```
$ du -sh hadoop-ozone/fault-injection-test/mini-chaos-tests/target/test-dir/* …
```
=> HDDS-12694. Disable TestMiniChaosOzoneCluster after fixing init and shutdown

hadoop-ozone/dist/src/main/compose/upgrade/compose/non-ha/docker-config
HDDS-12668 fixed upgrade test failure related to hsync feature, which was reproduced only in `ozone-2.0` branch.
HDDS-12327 restored non-HA upgrade test, but without the hsync fix.
So we need to apply HDDS-12668 to the `non-ha` cluster.  This fixes test failure in `ozone-2.0` branch: https://github.com/apache/ozone/actions/runs/14090453425/job/39466405013
https://issues.apache.org/jira/browse/HDDS-12327
Applied to `ozone-2.0` branch, and ran upgrade test locally.
```
Using docker cluster defined in /home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-2.0.0/compose/upgrade/compose/non-ha/docker-compose.yaml
Executing test /home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-2.0.0/compose/upgrade/upgrades/non-rolling-upgrade/./driver.sh
... …
```
=> HDDS-12327. HDDS-12668. Fix HSync upgrade test failure in non-HA upgrade test

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneAtRestEncryption.java, pom.xml
HDDS-719 replaced classes from Hadoop, including `Whitebox`.  HDDS-12486 re-introduced usage of `Whitebox` in `TestOzoneAtRestEncryption`.
1. Replace `Whitebox` with `HddsWhiteboxTestUtils`
2. Ban `Whitebox`
https://issues.apache.org/jira/browse/HDDS-12705
CI (pending):
https://github.com/adoroszlai/ozone/actions/runs/14093616797
=> HDDS-12705. Replace Whitebox with HddsWhiteboxTestUtils

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java
when closing a pipeline, if the user is not super-user, the command just runs without an exception. it writes the exception to audit but not to the client console.
Added a line to throw the exception in closePipeline method
https://issues.apache.org/jira/browse/HDDS-12703
I tested by running in my local intellij ozone setup.
```
svenkataramanasam@22187 ozone_cdp % sudo -u hive sh ozoneadmin.sh pipeline close 42a68542-30e9-4eda-9ba3-7b587182fd52 
Access denied for user hive. SCM superuser privilege is required.
```
=> HDDS-12703. Close pipeline command should display error when closure fails

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/cli/GenericCli.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/ContainerBalancerStatusSubcommand.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/SafeModeCheckSubcommand.java, hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestContainerBalancerSubCommand.java, hadoop-ozone/dist/src/main/smoketest/balancer/testBalancer.robot, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/BaseFreonGenerator.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/om/FSORepairTool.java
Currently, the `--verbose` option of GenericCli is accepted only when placed immediately after `ozone admin`, `ozone debug` or `ozone admin`, unless explicitly defined in the respective subcommand classes.
The goal of this task is to improve usability by allowing `--verbose` to be placed anywhere in the command, including after a subcommand or other options.
[HDDS-12660](https://issues.apache.org/jira/browse/HDDS-12660)
Before adding ScopeType._INHERIT_ to `--verbose` option.
```
bash-5.1$ ozone admin safemode status
SCM is out of safe mode.
bash-5.1$ ozone admin --verbose safemode status          
SCM is out of safe mode.
validated:true, DataNodeSafeModeRule, registered datanodes (=1) >= required datanodes (=1)
validated:true, HealthyPipelineSafeModeRule, healthy Ratis/THREE pipelines …
```
=> HDDS-12660. Allow --verbose option of GenericCli at leaf subcommands

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/utils/ContainerLogger.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/diskbalancer/DiskBalancerService.java
Use ContainerLogger to log success container move action.
https://issues.apache.org/jira/browse/HDDS-12567
Tested manually by running on docker-cluster.
```
2025-03-27 04:33:43,292 | INFO  | ID=1039 | SrcVolume=/data/hdds3/hdds | DestVolume=/data/hdds1/hdds | Size=997195776 bytes | TimeTaken=2332 ms |
2025-03-27 04:33:43,874 | INFO  | ID=1037 | SrcVolume=/data/hdds3/hdds | DestVolume=/data/hdds2/hdds | Size=998244352 bytes | TimeTaken=2916 ms |
2025-03-27 04:34:41,345 | INFO  | ID=1050 | SrcVolume=/data/hdds3/hdds | DestVolume=/data/hdds2/hdds | Size=200278016 bytes | TimeTaken=383 ms |
2025-03-27 04:34:41,350 | INFO  | ID=1049 | SrcVolume=/data/hdds3/hdds | DestVolume=/data/hdds2/hdds | Size=200278016 bytes | TimeTaken=388 ms |
```
=> HDDS-12567. [DiskBalancer] Log success container move action

hadoop-ozone/httpfsgateway/src/site/site.xml
Ozone httpfs `site.xml` refers to Apache Hadoop. We should rename it to Apache Ozone.
[HDDS-12696](https://issues.apache.org/jira/browse/HDDS-12696)
CI:
https://github.com/chiacyu/ozone/actions/runs/14106171268
=> HDDS-12696. Replace link to Hadoop with Ozone in httpfs site.xml

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/StorageLocationReport.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/AvailableSpaceFilter.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/HddsVolume.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/MutableVolumeSet.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/StorageVolume.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/volume/VolumeUsage.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/SCMCommonPlacementPolicy.java
- Let volumes create their own `StorageLocationReport`, with `HddsVolume` adding extra items specific to it.
- Let `hasVolumeEnoughSpace` decide based on a `StorageLocationReport`.
- Fix `parameternumber` warning in `StorageLocationReport`.
https://issues.apache.org/jira/browse/HDDS-12670
~https://github.com/adoroszlai/ozone/actions/runs/14082163097~
https://github.com/adoroszlai/ozone/actions/runs/14083416514
=> HDDS-12670. Improve encapsulation of volume spare space check

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/tables/containersTable.tsx
The ContainerTable component renders keys under the provided container ID that might be missing, under-replicated, over-replicated or mis-replicated.
Currently due to non-unique keys between the elements, the Keys might get re-rendered when switching pages.
This PR fixes that issue
- Currently the `key` field required to uniquely identify a react element is `volume/bucket/key`.
- However for nested paths, this React `key` will be common as for paths like `vol1/buck1/dir1/key1` and `vol1/buck1/dir1/dir2/key1` they react key will be equal to `vol1/buck1/key1` on both the elements.
- This causes the Ozone Keys to be re-rendered/repeated multiple times as they are not uniquely identifiable in the UI.
- This PR changes the React key to use complete path …
=> HDDS-12603. Fix ContainerTable keys re-rendering issue

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/CommandForDatanode.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/AbstractContainerReportHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerReportHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/IncrementalContainerReportHandler.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconIncrementalContainerReportHandler.java
Clean up code in AbstractContainerReportHandler:
- Remove unused TimeoutException
- Replace Preconditions.checkNotNull with Objects.requireNonNull
- Standardize log messages
- Clean up javadoc/comments
HDDS-12529
=> HDDS-12529. Clean up code in AbstractContainerReportHandler.

.github/workflows/intermittent-test-check.yml
- Add time-limited run of tests in `flaky-test-check` to find which modules they are in.
- Build only those modules and their dependencies (`-am -pl`).
- Limit real test run to those modules (`-pl`).
https://issues.apache.org/jira/browse/HDDS-12587
Triggered 2x2 [run](https://github.com/adoroszlai/ozone/actions/runs/14076965592) of `TestConfigurationSource,TestHddsClientUtils`.
[`find-tests`](https://github.com/adoroszlai/ozone/actions/runs/14076965592/job/39421709849#step:6:20) found these in `hdds-config` and `hdds-client`, respectively:
```
[INFO] --- surefire:3.0.0-M4:test (default-test) @ hdds-config ---
[INFO] Running org.apache.hadoop.hdds.conf.TestConfigurationSource
--
[INFO] --- surefire:3.0.0-M4:test (default-test) @ hdds-client ---
[INFO] Running …
```
=> HDDS-12587. Detect test class module in flaky-test-check

hadoop-hdds/rocks-native/pom.xml, pom.xml
Fix build error that happens in `hdds-rocks-native` if `JAVA_HOME` is not set.
```
Failed to execute goal org.codehaus.mojo:native-maven-plugin:1.0-M1:javah (default) on project hdds-rocks-native: Error running javah command
...
Caused by: IOException: Cannot run program "${env.JAVA_HOME}/bin/javah" (in directory "hadoop-hdds/rocks-native"): error=2, No such file or directory
```
Also, fix the root cause of HDDS-10118 and HDDS-11054:
```
Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.0.2:copy-dependencies (copy-jars) on project hdds-rocks-native: Artifact has not been packaged yet. When used on reactor artifact, copy should be executed after packaging: see MDEP-187.
```
(HDDS-10118 was repurposed for another bug, HDDS-11054 only provided a workaround for the …
=> HDDS-12724. hdds-rocks-native build fails if JAVA_HOME not set

pom.xml
Bump hadoop-thirdparty from 1.3.0 to 1.4.0.
https://issues.apache.org/jira/browse/HDDS-12736
https://github.com/adoroszlai/ozone/actions/runs/14157653572
=> HDDS-12736. Bump hadoop-thirdparty to 1.4.0

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/SCMCommonPlacementPolicy.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerReportHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/IncrementalContainerReportHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DeadNodeHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/HealthyReadOnlyNodeHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMBlockProtocolServer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/TestSCMCommonPlacementPolicy.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/SimpleMockNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestContainerPlacementFactory.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementCapacity.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackAware.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackScatter.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRandom.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestDeadNodeHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelinePlacementFactory.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestStorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/node/TestDecommissionAndMaintenance.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/NodeEndpoint.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconIncrementalContainerReportHandler.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconNodeManager.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestEndpoints.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconIncrementalContainerReportHandler.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconNodeManager.java
The `getNodeByUuid` methods in NodeManager should be replaced by a new `getNode(DatanodeID)` method.
HDDS-12739
=> HDDS-12739. Replace the getNodeByUuid methods in NodeManager.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeStateManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/states/NodeStateMap.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/states/TestNodeStateMap.java
Both `nodeMap` and `nodeToContainer` have `DatanodeID` as keys.  They should be combined into a single map to avoid an additional map operation.
For example, adding a new datanode currently need two put operations.  If there is only one map, it will only need one operation.
HDDS-12717
=> HDDS-12717. Combine nodeMap and nodeToContainer in NodeStateMap.

hadoop-ozone/dist/src/main/compose/upgrade/test.sh
As discussed in HDDS-11107, this PR removes the unnecessary run_test_scripts invocation and simplifies the test.sh script.
https://issues.apache.org/jira/browse/HDDS-11107
Tested by running the GitHub Actions workflow on a forked repository.
=> HDDS-11107. Remove unnecessary run_test_scripts call in upgrade tests

hadoop-hdds/rocks-native/src/CMakeLists.txt
GitHub recently [upgraded](https://github.com/actions/runner-images/blob/ubuntu24/20250330.1/images/ubuntu/Ubuntu2404-Readme.md) to CMake 4, so native build fails with:
```
[INFO]      [exec] -- Configuring incomplete, errors occurred!
[INFO]      [exec] CMake Error at CMakeLists.txt:23 (cmake_minimum_required):
[INFO]      [exec]   Compatibility with CMake < 3.5 has been removed from CMake.
[INFO]      [exec] 
[INFO]      [exec]   Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
[INFO]      [exec]   to tell CMake that the project requires at least <min> but has been updated
[INFO]      [exec]   to work with policies introduced by <max> or earlier.
[INFO]      [exec] 
[INFO]      [exec]   Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
``` …
=> HDDS-12751. native build fails with CMake 4

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeConfiguration.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/TestDatanodeConfiguration.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestReservedVolumeSpace.java
When both `hdds.datanode.volume.min.free.space` and `hdds.datanode.volume.min.free.space.pecentage` are defined, `hdds.datanode.volume.min.free.space` will be used.
https://issues.apache.org/jira/browse/HDDS-12676
Update existing tests
=> HDDS-12676. Prefer minFreeSpace if minFreeSpacePercent is also defined

hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java
Remove unused config [ozone.manager.db.checkpoint.transfer.bandwidthPerSec]
Remove unused config [ozone.manager.db.checkpoint.transfer.bandwidthPerSec](https://github.com/apache/ozone/blob/7fb92b014428f78e40705a88f9ae6cb7198a5b8b/hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java#L321) from ozone-default.xml and OmConfigKeys.
https://issues.apache.org/jira/browse/HDDS-12748
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this.)
=> HDDS-12748. Remove unused config ozone.manager.db.checkpoint.transfer.bandwidthPerSec

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/AbstractContainerReportHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerReportHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/IncrementalContainerReportHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestUnknownContainerReport.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconContainerReportHandler.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconIncrementalContainerReportHandler.java
In this PR, we will
- change AbstractContainerReportHandler to abstract;
- remove the logger field and change the getLogger() method to abstract;
- move nodeManager up and remove the redundant containerManager from the subclasses; and
- add a new UnknownContainerAction enum.
HDDS-12738
=> HDDS-12738. Refactor AbstractContainerReportHandler and its subclasses.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/diskbalancer/DiskBalancerInfo.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/diskbalancer/DiskBalancerService.java, hadoop-hdds/interface-client/src/main/proto/hdds.proto, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DiskBalancerManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DiskBalancerStatus.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DiskBalancerStatusSubcommand.java, hadoop-hdds/tools/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestDiskBalancerSubCommand.java
As VolumeDensity is already covered by report sub command, we will show bytesMoved (bytesBalanced) in status command.
Besides, the meaning of VolumeDensity is clear to end user, but the real value indicating is not that straight forward. Use the estimated pending move size([HDDS-12437](https://issues.apache.org/jira/browse/HDDS-12437)) will help user to clearly understand how much data size need to move. And this bytesMoved is also a straight forward value, indicating the work disk balancer has done.
https://issues.apache.org/jira/browse/HDDS-12546
Added unit test to test bytesToMoveMB, bytesMovedMB and calculateEstimatedTimeLeft to show reasonable values when  bytesToMove and bytesMoved are less than 1MB.
As well as tested manually by running docker cluster locally.
```
bash-5.1$ ozone …
```
=> HDDS-12546. [DiskBalancer] Display bytesMoved instead of VolumeDensity in status output

hadoop-hdds/docs/content/security/SecuringS3.md
HDDS-9241. Create documentation for REST Secret Revoke command.
https://issues.apache.org/jira/browse/HDDS-9241
Doc only.
=> HDDS-9241. Create documentation for REST Secret Revoke command.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/datanode/RunningDatanodeState.java
When datanode can not connect to SCM or Recon, the following error will be throw, and the timeout exception can be reformat.
```
Error in executing end point task.
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:192)
at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.computeNextContainerState(RunningDatanodeState.java:191)
at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:231)
at org.apache.hadoop.ozone.container.common.states.datanode.RunningDatanodeState.await(RunningDatanodeState.java:50)
at …
```
=> HDDS-12639. Add info for timeout exception

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneDebugShell.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestReconfigShell.java, hadoop-ozone/integration-test/src/test/java/org/apache/ozone/test/NonHATests.java
Speed up TestReconfigShell and TestOzoneDebugShell by using shared cluster in `NonHATests`.
Remove a small part of `TestReconfigShell` that runs the command with stopped datanode.  (I think testing with `DECOMMISSIONING` node is enough.)
https://issues.apache.org/jira/browse/HDDS-12756
Before:
```
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 46.81 s -- in org.apache.hadoop.ozone.shell.TestOzoneDebugShell
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 47.26 s -- in org.apache.hadoop.ozone.shell.TestReconfigShell
```
After:
```
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.840 s -- in org.apache.ozone.test.NonHATests$OzoneDebugShell
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.076 s -- in …
```
=> HDDS-12756. Speed up TestReconfigShell and TestOzoneDebugShell

hadoop-hdds/common/pom.xml, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMStateMachine.java, hadoop-ozone/insight/src/main/java/org/apache/hadoop/ozone/insight/datanode/RatisInsight.java
Remove leftover references to `RaftServerImpl` and `org.apache.ratis.server.impl`.
https://issues.apache.org/jira/browse/HDDS-4517
https://github.com/adoroszlai/ozone/actions/runs/14236556569
=> HDDS-4517. Remove leftover references to RaftServerImpl

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/DBCheckpointServlet.java
In `DBCheckpointServlet`:
```java
LOG.info("Received excluding SST {}", receivedSstList);
LOG.info("Excluded SST {} from the latest checkpoint.", excludedSstList); 
```
In a cluster with large workloads and multiple snapshots, number of SST's per DB can be in the order of tens of thousands. This will just flood the logs during incremental bootstrap process.
Change the log level to debug and only print say 5 or 10 and print the total number of sst files to exclude under `LOG.info`
[HDDS-12711](https://issues.apache.org/jira/browse/HDDS-12711)
CI:
https://github.com/chiacyu/ozone/actions/runs/14141287743
=> HDDS-12711. Change log level to debug to print excluded SST Files during bootstrap

hadoop-hdds/docs/content/start/Kubernetes.md
HDDS-11038. Add documentation to the website with the Helm chart details.
* Add Helm Chart user doc to Ozone on Kubernetes doc.
https://issues.apache.org/jira/browse/HDDS-11038
Old doc site. Will need to copy to new site later.
=> HDDS-11038. Add documentation to the website with the Helm chart details.

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/duMetadata/duMetadata.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/diskUsage/diskUsage.tsx
Removed units from from Quota in Namespace since it should not be in bytes in Disk Usage metadata
https://issues.apache.org/jira/browse/HDDS-12037
New UI
Old UI
=> HDDS-12037. Removing unit from quota namespace

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsUtils.java
There're two identical line of below declaration, I think that one of them can  be removed.
```java
dnsInterface = conf.get(HDDS_DATANODE_DNS_INTERFACE_KEY); 
```
[HDDS-12757](https://issues.apache.org/jira/browse/HDDS-12757)
CI:
https://github.com/chiacyu/ozone/actions/runs/14224664936
=> HDDS-12757. Duplicated declaration of dnsInterface in HddsUtils

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java, hadoop-ozone/integration-test-s3/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v1/AbstractS3SDKV1Tests.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFSWithObjectStoreCreate.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/TestNormalizePaths.java
Fixed the bug when reading and writing keys starting with ‘//’ for FSO bucket and LEGACY  + ozone.om.enable.filesystem.paths=true bucket.
For detail; see https://issues.apache.org/jira/browse/HDDS-12758
https://issues.apache.org/jira/browse/HDDS-12758
CI:
https://github.com/xichen01/ozone/actions/runs/14242969366
=> HDDS-12758. Reading and writing double dash prefixes will result in an error.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneDebugShell.java
The existing test case `testLdbCliForOzoneSnapshot` was failing because the scan result was empty. This was due to the use of the keyTable column family, which is incorrect for FSO bucket layout. For FSO, the correct column family is fileTable.
The test case has been updated to use fileTable, and the issue is now resolved.
https://issues.apache.org/jira/browse/HDDS-10091
This patch includes updates to the test case. The [CI](https://github.com/priyeshkaratha/ozone/actions/runs/14290014926) has passed successfully with the updated test case.
=> HDDS-10091. TestOzoneDebugShell fails with FILE_SYSTEM_OPTIMIZED bucket layout

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerData.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerPersistence.java
Please see the jira for a description of the problem. This pull request tries to fix the committedSpace calculation for all cases:
1. When the size of the container after writing is less than max (5GB).
2. Size of the container after writing exactly equals max.
3. Size of the container after writing exceeds max.
4. The container was exactly full before writing.
5. When `committedSpace` is false before writing.
https://issues.apache.org/jira/browse/HDDS-12691
Added unit tests. Draft while CI is running in my fork.
Passed CI - https://github.com/siddhantsangwan/ozone/actions/runs/14258537275/job/39965460330
=> HDDS-12691. Calculation of committed space in Datanode seems incorrect

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsConfigKeys.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ratis/RatisHelper.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/StateContext.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/RatisUtil.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/upgrade/TestScmHAFinalization.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/volume/TestDatanodeHddsVolumeFailureDetection.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconAndAdminContainerCLI.java, hadoop-ozone/mini-cluster/src/main/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java, hadoop-ozone/mini-cluster/src/main/java/org/apache/hadoop/ozone/UniformDatanodesFactory.java
Speed up the building of MiniOzoneCluster by:
- by set a shorter `xxx.first.election.minimum.timeout.duration` to reduce the waiting time for the first election
- by set a shorter `hdds.recon.initial.heartbeat.interval` and `hdds.initial.heartbeat.interval` to reduce Datanode initialization time, let Datanode register with SCM as soon as possible
The overall time spent on integration testing was reduced by approximately 10% ~ 20%
https://issues.apache.org/jira/browse/HDDS-12772
https://github.com/xichen01/ozone/actions/runs/14290653637
existing tests
=> HDDS-12772. Speed up the building of MiniOzoneCluster

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/insights/om/om.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/views/missingContainers/missingContainers.tsx
Currently even after fixing the ContainerKeys the backend API in Recon. A column to denoting the full path for the key should be added to show the complete path in the UI page.
https://issues.apache.org/jira/browse/HDDS-12741
Manual testing for testing ui
=> HDDS-12741. Recon UI should show full path returned in the ContainerKeys API response

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/metrics/SCMPerformanceMetrics.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/SCMPipelineMetrics.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMBlockProtocolServer.java
Introduce detailed SCM metrics around the allocate block code flow.
https://issues.apache.org/jira/browse/HDDS-12463
Tested using a docker-compose cluster with monitoring add-ons
=> HDDS-12463. Add detailed SCM metrics for allocate block code path

hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/cli/ItemsFromStdin.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/container/ContainerIDParameters.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/container/InfoSubcommand.java, hadoop-ozone/cli-shell/src/main/java/org/apache/hadoop/ozone/shell/Shell.java
Generalize `HostNameParameters` to allow various parameters to be supplied via stdin.  Reuse in `ozone admin container info` for container ID list.
Avoid duplicate parsing of arguments in `Shell`, because the first one consumes inputs from stdin, and the command hangs waiting for further input.
https://issues.apache.org/jira/browse/HDDS-12408
Tested in `ozone` compose environment:
```bash
$ ozone freon ockg -n1 -t1
...
$ ozone admin container close 1
$ ozone freon ockg -n1 -t1
...
$ ozone admin container info -
1
2
^D
Container id: 1
...
Container id: 2
...
$ ozone admin container info --json - <<EOF | jq -r '.[].containerInfo.containerID'
> 1
> 2
> EOF
1
2
$ ozone admin container info --json 1 2 | jq -r '.[].containerInfo.containerID'
1
2
```
CI: …
=> HDDS-12408. Create mixin for ContainerID list parameters

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestHadoopNestedDirGenerator.java
Some of the declaration of in `TestHadoopNestedDirGenerator`#`spanCheck()` is redundant and can be removed, refactored as well.
[HDDS-12755](https://issues.apache.org/jira/browse/HDDS-12755)
CI:
https://github.com/chiacyu/ozone/actions/runs/14219163027
=> HDDS-12755. Redundant declaration in TestHadoopNestedDirGenerator#spanCheck()

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerImpl.java
Currently, SCM first fires the pipeline close command to DN and then, without waiting for ACK, removes the pipeline from its state map. 
Sometimes, we observed that the pipeline got removed from the DN but didn't get removed from SCM, so it caused the SCM to get stuck in safemode as SCM is expecting the pipelines from DN. So, first, we should remove the pipeline from the SCM pipeline statemap and then fire the close pipeline command to DN.
https://issues.apache.org/jira/browse/HDDS-12801
=> HDDS-12801. SCM should remove pipeline before DN.

hadoop-ozone/dist/src/main/license/bin/LICENSE.txt, hadoop-ozone/dist/src/main/license/bin/NOTICE.txt, hadoop-ozone/dist/src/main/license/jar-report.txt, hadoop-ozone/ozone-manager/pom.xml, pom.xml
Bump Ranger to 2.6.0.
https://issues.apache.org/jira/browse/HDDS-12461
CI:
https://github.com/adoroszlai/ozone/actions/runs/13968803766
=> HDDS-12461. Bump Ranger to 2.6.0

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerSet.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/WitnessedContainerDBDefinition.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/WitnessedContainerMetadataStore.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/WitnessedContainerMetadataStoreImpl.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStore.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestTypedTable.java
The key type of CONTAINER_IDS_TABLE is Long. It is better to use ContainerID.
Note that the binary encodings are the same for Long and ContainerID. It is compatible to replace Long with ContainerID in db.
HDDS-12770
Added new tests
=> HDDS-12770. Use ContainerID instead of Long in CONTAINER_IDS_TABLE.

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/containerlog/parser/ContainerDatanodeDatabase.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/containerlog/parser/ContainerLogFileParser.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/containerlog/parser/DBConsts.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/containerlog/parser/DatanodeContainerInfo.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/container/ContainerLogController.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/container/ContainerLogParser.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/container/package-info.java, hadoop-ozone/tools/src/main/resources/container-log-db-queries.properties
This update introduces multithreaded processing to efficiently parse and store container log files into the database. Each log file is processed in a separate thread, allowing multiple files to be handled concurrently. The logs are parsed, and the data, including container IDs, datanode IDs, and other related information, is collected into batches. Once a batch reaches a predefined size, it is inserted into the database. Synchronization is used to ensure thread safety when inserting data into the database, preventing potential race conditions.
Also created a ozone debug CLI command for the same.
`./ozone debug container container_log_parse --parse=<path to logs folder>  --thread-count=<num of threads>`
Below is a sample output of the command 
> pool-1-thread-1 is starting to process file: …
=> HDDS-12581. Multi-threaded Log File Parsing with Batch Updates to DB

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/AbstractContainerReportHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerReportHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/IncrementalContainerReportHandler.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconIncrementalContainerReportHandler.java
[HDDS-5249](https://issues.apache.org/jira/browse/HDDS-5249) has added synchronized (datanodeDetails) to ContainerReportHandler and IncrementalContainerReportHandler. Since ReconContainerReportHandler uses the super method in ContainerReportHandler, it is also synchronized.
However, ReconIncrementalContainerReportHandler is not synchronized.
HDDS-12825
=> HDDS-12825. ReconIncrementalContainerReportHandler is not synchronized on datanode.

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBConfigFromFile.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBSstFileLoader.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBSstFileWriter.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBTable.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabase.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/RocksDatabaseException.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedRocksDB.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedRocksObjectUtils.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/package-info.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SstFilteringService.java
When rocksdb throws a RocksDBException, we convert it to an IOException. It is better to add a new RocksDatabaseException. Then, callers is easier to tell the exception is from rocksdb.
This PR will also fix HDDS-12831, which is a findbugs warning.
HDDS-12830
=> HDDS-12830. Add RocksDatabaseException.

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmKeyInfo.java
OmKeyInfo#isKeyInfoSame is used by SnapDiffManager#isKeyModified to generate a MODIFY diff entry. 
We need to take into account for object tags so that the Snapdiff can detect the change in key object tags.
https://issues.apache.org/jira/browse/HDDS-12803
Unit test and manual snapdiff test for key with different object tags.
Previously it will result in `RENAME` diff entry (i.e. `R ./key1 ./key1`), after this change it becomes `MODIFY` diff entry (i.e. `M ./key1`).
Clean CI: https://github.com/ivandika3/ozone/actions/runs/14383134109
=> HDDS-12803. OmKeyInfo#isKeyInfoSame should handle object tags

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/checksum/ContainerChecksumTreeManager.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/KeyValueContainerUtil.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/checksum/TestContainerChecksumTreeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerReplica.java, hadoop-ozone/dist/src/main/smoketest/admincli/container.robot, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestCloseContainer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/checksum/TestContainerCommandReconciliation.java
1. The container checksum though generated during container close, is not being reported to the SCM. 
2. During DN restart we are not fetching the container checksum into `KeyValueContainerData` hence the SCM doesn't get the checksum.
https://issues.apache.org/jira/browse/HDDS-12745
Integration Test
=> HDDS-12745. Container checksum should be reported during container close and DN restart

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/OzoneRpcClientTests.java
Some of the `createkey()` in `OzoneRpcClientTests` can be replaced with `TestDataUtil.createKey()`. Please take a look, thanks!
[HDDS-12845](https://issues.apache.org/jira/browse/HDDS-12845)
CI:
https://github.com/chiacyu/ozone/actions/runs/14428478602
=> HDDS-12845. Reuse TestDataUtil.createKey in OzoneRpcClientTests

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/AbstractRootedOzoneFileSystemTest.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestStorageContainerManagerHAWithAllRunning.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestBCSID.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestHybridPipelineOnDatanode.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneAtRestEncryption.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestOzoneRpcClientWithKeyLatestVersion.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestReadRetries.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestSecureOzoneRpcClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/TestContainerReplication.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/TestContainerReportHandling.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/TestContainerReportHandlingWithHA.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/volume/TestDatanodeHddsVolumeFailureDetection.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestBucket.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconAndAdminContainerCLI.java
In many tests, we just want to create a key in the bucket, we can reuse `TestDataUtil.createKey()` in these tests. BTW, to avoid huge patch, the replacement of `OzoneRpcClientTests` would be done in another PR.
[HDDS-12524](https://issues.apache.org/jira/browse/HDDS-12524)
CI:
https://github.com/chiacyu/ozone/actions/runs/14418469711
=> HDDS-12524. Reuse TestDataUtil.createKey in more tests

hadoop-hdds/common/pom.xml, hadoop-hdds/framework/pom.xml, hadoop-hdds/hadoop-dependency-client/pom.xml, hadoop-hdds/hadoop-dependency-server/pom.xml, hadoop-hdds/test-utils/pom.xml, hadoop-ozone/dist/src/main/license/bin/LICENSE.txt, hadoop-ozone/dist/src/main/license/bin/NOTICE.txt, hadoop-ozone/dist/src/main/license/jar-report.txt, hadoop-ozone/ozone-manager/pom.xml, hadoop-ozone/ozonefs-hadoop2/pom.xml, pom.xml
Transitive dependencies (e.g. various Apache Commons libraries, Apache HTTP Client) use Apache Commons Logging API.  SLF4J provides a drop-in replacement with implementation over SLF4J.  The goal of this change is to replace `commons-logging` with `jcl-over-slf4j`.
https://issues.apache.org/jira/browse/HDDS-12806
https://github.com/adoroszlai/ozone/actions/runs/14401305621
=> HDDS-12806. Replace commons-logging with jcl-over-slf4j

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainer.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerCheck.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerPersistence.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainer.java
KeyValueContainer uses containerId for logging or creating error messages in many cases.  It should use containerData.toString() instead.
HDDS-12840
=> HDDS-12840. Avoid long containerId in KeyValueContainer

hadoop-ozone/dist/src/main/compose/common/hadoop-test.sh
Remove Hadoop 3.1.2 from acceptance test matrix.  Only test with 2.10.2 and 3.4.1.
https://issues.apache.org/jira/browse/HDDS-12152
CI:
https://github.com/adoroszlai/ozone/actions/runs/13025669367/job/36334632022
=> HDDS-12152. Stop testing with Hadoop 3.1.2

hadoop-ozone/cli-shell/src/main/java/org/apache/hadoop/ozone/shell/snapshot/ListSnapshotDiffHandler.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/ObjectStore.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/protocol/ClientProtocol.java, hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocol/OzoneManagerProtocol.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/OzoneManagerProtocolClientSideTranslatorPB.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/snapshot/ListSnapshotDiffJobResponse.java, hadoop-ozone/dist/src/main/smoketest/snapshot/snapshot-sh.robot, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOmSnapshot.java, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/protocolPB/OzoneManagerRequestHandler.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDiffManager.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/client/ClientProtocolStub.java
This change is to provide the pagination for list SnapshotDiff jobs API.
HDDS-8802
Existing unit test and manually tested on docker on local machine.
=> HDDS-8802. Added pagination support for ListSnapshotDiff jobs

pom.xml
Bump `maven-compiler-plugin` from 3.9.0 to 3.14.0.
Starting with version 3.10.0, `package-info.class` is generated for doc-only `package-info.java` ([MCOMPILER-205](https://issues.apache.org/jira/browse/MCOMPILER-205)), which breaks some S3 unit tests (see https://github.com/apache/ozone/pull/8299#issuecomment-2814875144 for details).  Therefore the new feature is disabled.
https://issues.apache.org/jira/browse/HDDS-11734
```
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.611 s -- in org.apache.hadoop.ozone.s3.endpoint.TestBucketAcl
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.134 s -- in org.apache.hadoop.ozone.s3.endpoint.TestMultiDeleteRequestUnmarshaller
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.152 s -- in …
```
=> HDDS-11734. Bump maven-compiler-plugin to 3.14.0

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/ClosePipelineCommandHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/AbstractFindTargetGreedy.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerTask.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/FindSourceGreedy.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/MoveManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/DeletingContainerHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/health/EmptyContainerHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/HealthyReadOnlyNodeHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineActionHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/RatisPipelineProvider.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/upgrade/TestHDDSUpgrade.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconNewNodeHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/DatanodeSimulator.java
`DatanodeDetails#toString()` includes UUID, hostname, IP. We should use `DatanodeDetails` object in log messages instead of its `getUuidString()`.
[HDDS-12846](https://issues.apache.org/jira/browse/HDDS-12846)
CI:
https://github.com/chiacyu/ozone/actions/runs/14493342437
=> HDDS-12846. Log DatanodeDetails instead of DatanodeDetails.getUuidString

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestContainerPlacementFactory.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementCapacity.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackAware.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackScatter.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRandom.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestDeadNodeHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelinePlacementFactory.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestStorageContainerManager.java
`DatanodeID#toString()` returns cached string form of `UUID`. It can be used instead of `DatanodeDetails#getUuidString()`. Please take a look, thanks!
[HDDS-12847](https://issues.apache.org/jira/browse/HDDS-12847)
CI:
https://github.com/chiacyu/ozone/actions/runs/14471193317
=> HDDS-12847. Use DatanodeID instead of DatanodeDetails.getUuidString

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/commontypes/package-info.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/CompleteMultipartUploadRequest.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/CompleteMultipartUploadResponse.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/CopyObjectResponse.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/CopyPartResult.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ListBucketResponse.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ListMultipartUploadsResult.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ListObjectResponse.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/ListPartsResponse.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/MultiDeleteRequest.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/MultiDeleteResponse.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/MultipartUploadInitiateResponse.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/S3BucketAcl.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/S3Tagging.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/package-info.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/util/S3Consts.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestCompleteMultipartUploadRequestUnmarshaller.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestMultiDeleteRequestUnmarshaller.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestObjectTaggingPut.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestPermissionCheck.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/metrics/TestS3GatewayMetrics.java, pom.xml
HDDS-11734. Specify namespace in `@XmlElement` annotations for correct XML deserialization
https://issues.apache.org/jira/browse/HDDS-11734
All mentioned failed unit tests pass.
=> HDDS-12867. Replace hard-coded namespace URL with constant S3_XML_NAMESPACE

hadoop-hdds/rocks-native/dev-support/findbugsExcludeFile.xml, hadoop-ozone/client/dev-support/findbugsExcludeFile.xml, hadoop-ozone/integration-test/dev-support/findbugsExcludeFile.xml, hadoop-ozone/s3gateway/dev-support/findbugsExcludeFile.xml
This PR removes unused findbugs exclusions and fixes a path to `TestKeyInputStream`.
[HDDS-12340](https://issues.apache.org/jira/browse/HDDS-12340)
CI:
https://github.com/kostacie/ozone/actions/runs/14534927524
P.S. Build's name contains 'HDDS-10247' instead of 'HDDS-12340' by mistake.
=> HDDS-12340. Remove unnecessary findbugs exclusions

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerSet.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OnDemandContainerDataScanner.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerSet.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOnDemandContainerDataScanner.java
The on demand container scanner was originally implemented as a static instance so that it could be easily triggered from anywhere in the code. This is now causing problems for reconciliation testing where multiple replicas exist in the same process. We are invoking on demand scans for each replica after it is reconciled, and these scans for different replicas are hitting the same container scanner concurrently. This is required for tests to pass in #7490.
Due to the layout of the datanode code, it is difficult to get items like this to all places where they are needed, which is why the on demand scanner was initially static. I have attempted to remedy this issue by adding a scan handler which can be triggered from the `ContainerSet`. `ContainerSet` was chosen because it is both created …
=> HDDS-12849. On demand container scanner should not be static

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java
The debug chunkinfo was missing file location for other data indexes or parity blocks.
This issue occurred due to recent changes introduced in [HDDS-11667](https://issues.apache.org/jira/browse/HDDS-11667), which added validation of the DatanodeID on all incoming requests to a datanode.
In the chunkinfo tool, we send both GetBlock and ReadContainer requests to all relevant datanodes. However, the requests were being constructed using a fixed datanode UUID, regardless of which datanode the request was actually being sent to. As a result, the UUID in the request didn’t match the UUID of the target datanode, causing these requests to fail validation and leading to missing file location information in the output.
This patch ensures that the datanodeUuid field is correctly set in the request, …
=> HDDS-12816. Ozone debug replicas chunk-info has incorrect or None in FileLocations

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBProfile.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedBlockBasedTableConfig.java, pom.xml
Added rocksdb options for tuning.
Added these 3 rocksdb options to DBProfile:
```
opts.max_background_jobs = 6;
options.compaction_pri = kMinOverlappingRatio;
table_options.cache_index_and_filter_blocks = true;
```
https://issues.apache.org/jira/browse/HDDS-12173
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this.)
=> HDDS-12173. Follow RocksDB basic tuning guide

hadoop-ozone/dist/src/main/compose/ozone/test.sh, hadoop-ozone/dist/src/main/smoketest/ozonefs/ozonefs-obs.robot
Currently, there are no automated tests validating the failure behaviour of `ozone fs` operations on buckets with `OBJECT_STORE` layout. Since OBS buckets do not support file system semantics, operations such as `mkdir`, `put`, `ls`, `rm`, `mv`, etc., are expected to fail with an `IllegalArgumentException`.
With these changes, behavioural regressions (like the ones below) that are not detected by the current CI can be identified:
- https://github.com/apache/ozone/pull/7122
- https://github.com/apache/ozone/pull/8288#issuecomment-2804412963
This patch adds a dedicated robot test suite to cover these negative scenarios, improving the overall test coverage for the ozone fs interface.
https://issues.apache.org/jira/browse/HDDS-12888
- Added robot tests (green CI: …
=> HDDS-12888. Add negative test cases for FS operations on OBS buckets

hadoop-ozone/dist/dev-support/bin/dist-layout-stitching
This pull request resolves HDDS-12893 by replacing `cp -n` with` --update=none` in the dist-layout-stitching script to eliminate the non-portable -n warning.
This PR updated the build script (hadoop-ozone/dist/src/main/bin/dist-layout-stitching) to replace all cp -n usages with` cp --update=none. `
[HDDS-12893](https://issues.apache.org/jira/browse/HDDS-12893)
-  Run the script on Ubuntu 22.04; no cp -n warnings appeared.
-  Test in Docker containers (Alpine Linux, CentOS 7); script executed without warnings.
(If this patch involves UI changes, please attach a screenshot; otherwise, …
=> HDDS-12893. cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/diskbalancer/DiskBalancerYaml.java
Use AtomicFileOutputStream to write DiskBalancerYaml file.
Because of the following reasons:
Using AtomicFileOutputStream prevents partial or corrupt writes by writing to a temp file and atomically replacing the original.
It will also be consistent with the other yaml files changed in [HDDS-12531](https://issues.apache.org/jira/browse/HDDS-12531)
https://issues.apache.org/jira/browse/HDDS-12879
passed existing tests.
=> HDDS-12879. Use AtomicFileOutputStream to write DiskBalancerYAML file

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/interfaces/Handler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/Receiver.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/ChunkManagerDispatcher.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/FilePerBlockStrategy.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/interfaces/ChunkManager.java
close the file descriptor in datanode after the fd is send to client. 
https://issues.apache.org/jira/browse/HDDS-12883
manual test with docker cluster, before the patch, there will be open block files output in "lsof" command after read key from local when short-circuit is enabled. With the patch, there is more open block files open after the key read.
=> HDDS-12883. Close file descriptor of block file in datanode

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/diskbalancer/DiskBalancerService.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/diskbalancer/policy/DefaultVolumeChoosingPolicy.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/diskbalancer/policy/VolumeChoosingPolicy.java
Currently it uses deltaSizes to record the pre-allocated and pre-deleted bytes of each volume due to there is selected container to move.
But deltaSizes is not aware by other activities, such as container creation, container moving command by container balancer. So there is chance that data volume will be over allocated due to this.
This task aims to use HddsVolume#committedBytes to replace deltaSizes, so that the space pre-allocated by disk balancer will be fully awared by HddsVolume.
https://issues.apache.org/jira/browse/HDDS-12431
Passed existing tests.
=> HDDS-12431. [DiskBalancer] Use committedBytes to reserve the space pre-allocated for container

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerSet.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/CoderUtil.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/util/GF256.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/util/RSUtil.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedRocksObjectMetrics.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedRocksObjectUtils.java, hadoop-hdds/rocks-native/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedRawSSTFileReader.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/DecommissionStatusSubCommand.java, hadoop-hdds/tools/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/UsageInfoSubcommand.java
Code for the rest of the hdds modules made compliant with PMD.FieldDeclarationsShouldBeAtStartOfClass verification rule.
It is done before enabling the rule itself to prevent us reviewing a very huge PR.
https://issues.apache.org/jira/browse/HDDS-12904
Patch tested using standard verification pipeline.
=> HDDS-12904. Move field declarations to start of class in hdds modules

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/utils/ContainerLogger.java
This PR adds a message to import and export logs in `ContainerLogger` as there was no log message telling about both importing and exporting a container.
[HDDS-9585](https://issues.apache.org/jira/browse/HDDS-9585)
CI:
https://github.com/kostacie/ozone/actions/runs/14635913888
=> HDDS-9585. Improved import/export log in ContainerLogger

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/WritableECContainerProvider.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/upgrade/SCMUpgradeFinalizer.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestBlockManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/MockPipelineManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestWatchForCommit.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/container/TestScmApplyTransactionFailure.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestLeaderChoosePolicy.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineClose.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestRatisPipelineCreateAndDestroy.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/storage/TestContainerCommandsEC.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/OzoneTestUtils.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestECKeyOutputStream.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/TestHelper.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCloseContainerByPipeline.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/freon/TestFreonWithPipelineDestroy.java
The `closePipeline(Pipeline pipeline, boolean onTimeout)` has been deprecated since https://github.com/apache/ozone/pull/5604/files#r1400539952 . We can remove it completely. Please take a look, thanks!
[HDDS-12912](https://issues.apache.org/jira/browse/HDDS-12912)
CI:
https://github.com/chiacyu/ozone/actions/runs/14679988038
=> HDDS-12912. Remove deprecated `PipelineManager#closePipeline(Pipeline, boolean)`

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMultiTenantManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMPerformanceMetrics.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMPolicyProvider.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneListStatusHelper.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SstFilteringService.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ha/OMHAMetrics.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/helpers/OMAuditLogger.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerDoubleBuffer.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis/OzoneManagerRatisServerConfig.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeySetTimesRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyAddAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyAddAclRequestWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyRemoveAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeyRemoveAclRequestWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeySetAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/acl/OMKeySetAclRequestWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/acl/OMVolumeAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/acl/OMVolumeAddAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/acl/OMVolumeRemoveAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/acl/OMVolumeSetAclRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/s3/S3SecretCacheProvider.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/OMRangerBGSyncService.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/AWSV4AuthValidator.java
Code for the ozone-manager module made compliant with PMD.FieldDeclarationsShouldBeAtStartOfClass verification rule.
It is done before enabling the rule itself to prevent us reviewing a very huge PR.
https://issues.apache.org/jira/browse/HDDS-12906
Patch tested using standard verification pipeline.
=> HDDS-12906. Move field declarations to start of class in ozone-manager module

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/client/io/SelectorOutputStream.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmBucketInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmDBAccessIdInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmDBTenantState.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmDBUserPrincipalInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmDirectoryInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmMultipartKeyInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmVolumeArgs.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OzoneAclUtil.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/RepeatedOmKeyInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/S3SecretValue.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/SnapshotDiffJob.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/SnapshotInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/GrpcOmTransport.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/protocolPB/grpc/GrpcClientConstants.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/security/GDPRSymmetricKey.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/security/OzoneDelegationTokenSelector.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/snapshot/SnapshotDiffReportOzone.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/util/RadixNode.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/util/RadixTree.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/web/utils/OzoneUtils.java
Code for the ozone-common module made compliant with PMD.FieldDeclarationsShouldBeAtStartOfClass verification rule.
It is done before enabling the rule itself to prevent us reviewing a very huge PR.
https://issues.apache.org/jira/browse/HDDS-12905
Patch tested using standard verification pipeline.
=> HDDS-12905. Move field declarations to start of class in ozone-common module

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmLCAction.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmLCExpiration.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmLCFilter.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmLCRule.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmLifecycleConfiguration.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmLifecycleRuleAndOperator.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/OMLCUtils.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmLCExpiration.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmLCFilter.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmLCRule.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmLifeCycleConfiguration.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmLifecycleRuleAndOperator.java
AWS doc about the Lifecycle configuration : https://docs.aws.amazon.com/AmazonS3/latest/userguide/intro-lifecycle-rules.html
Introducing the basic java objects of Lifecycle, and verification logic
- OmLifecycleConfiguration: Corresponding to the object of S3 Lifecycle, an S3 Lifecycle can contain multiple Rules.
- OmLCRule: Corresponding to the specific Rule in Lifecycle configuration, Rule is responsible for defining the action and filtering conditions. Objects that meet the filtering conditions will perform the corresponding action.
- OmLifecycleRuleAndOperator: Corresponding to the And element in Rule, the And element can contain multiple different elements, such as a prefix + a tag or multiple tags
- OmLCAction:  Define what a Rule does to the object, including: Transition (not …
=> HDDS-12808. Implement OM entities of lifecycle configurations

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBColumnFamilyDefinition.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBStore.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestInterSCMGrpcProtocolService.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/codec/OMDBDefinition.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmMetadataManager.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotManager.java
In OmMetadataManagerImpl, it creates tables by hardcoding the key/value types. Instead, it should use the table definition in OMDBDefinition.
HDDS-12900
=> HDDS-12900. Use OMDBDefinition in OmMetadataManagerImpl.

hadoop-ozone/dist/src/main/compose/testlib.sh
Fix `bad substitution` in bats test:
```
1..5
Using Docker Compose v2
/home/runner/work/ozone/ozone/hadoop-ozone/dist/src/test/shell/../../main/compose/testlib.sh: line 37: ${ozone.version}: bad substitution
Using Docker Compose v2
/home/runner/work/ozone/ozone/hadoop-ozone/dist/src/test/shell/../../main/compose/testlib.sh: line 37: ${ozone.version}: bad substitution
ok 1 Find test recursive, only on one level
Using Docker Compose v2
/home/runner/work/ozone/ozone/hadoop-ozone/dist/src/test/shell/../../main/compose/testlib.sh: line 37: ${ozone.version}: bad substitution
ok 2 Find tests without explicit filter
Using Docker Compose v2
/home/runner/work/ozone/ozone/hadoop-ozone/dist/src/test/shell/../../main/compose/testlib.sh: line 37: ${ozone.version}: bad substitution
ok 3 Find test by …
```
=> HDDS-12773. bad substitution in bats test

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/client/HddsClientUtils.java, hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/client/TestHddsClientUtils.java
In the client, in most cases when the specified volume or bucket name is shorter or longer than the allowed range, the resulting error does not include the name itself. This can make troubleshooting difficult in situations where the name is not implied by the context.
This PR addresses the difficulty by adding the name itself, and the resource type (volume or bucket), to the message of the innermost `IllegalArgumentException`.
In the case of buckets, also adding the volume name seems to have a disproportionate cost in terms of clarity (at each usage). Accordingly, this PR proposes to accept a bucket name as unique enough for debugging purposes. A user of the client may still choose to add this information as desired.
Since adding the name to the message could theoretically be used as an …
=> HDDS-12649. Include name in length validation error

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/tagging/S3DeleteObjectTaggingRequestWithFSO.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/tagging/S3PutObjectTaggingRequestWithFSO.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/tagging/TestS3DeleteObjectTaggingRequestWithFSO.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/s3/tagging/TestS3PutObjectTaggingRequestWithFSO.java
These requests S3PutObjectTaggingResponseWithFSO and S3DeleteObjectTaggingRequestWithFSO are setting the key name for FSO bucket keys as full path name. It should be just the file name.
https://issues.apache.org/jira/browse/HDDS-12892
Clean CI: https://github.com/ivandika3/ozone/actions/runs/14698516236
=> HDDS-12892. OM Tagging Request is incorrectly setting full path as key name

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBStore.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBTableStore.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestTypedRDBTableStore.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/recovery/ReconOmMetadataManagerImpl.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/containergenerator/GeneratorOm.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/om/FSORepairTool.java
Similar to [HDDS-12900](https://issues.apache.org/jira/browse/HDDS-12900), both `GeneratorOm` and `FSORepairTool` should use `OMDBDefinition` instead of hardcoding the key/value types.
After the above change, we may remove
- the getTable(..) methods with key/value types in DBStore, and
- the constructors with key/value types in TypedTable,  and
- the `codecRegistry` field from `RDBStore`.
HDDS-12922
=> HDDS-12922. Use OMDBDefinition in GeneratorOm and FSORepairTool

hadoop-ozone/dist/dev-support/bin/dist-layout-stitching
HDDS-12893 changed `cp -n` to `cp --update=none` to get rid of warning:
```
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
```
Now on Ubuntu 22.04 we get error:
```
cp: option '--update' doesn't allow an argument
```
Since `-n`, `--update=none` etc. are version/platform dependent, we can simply remove it and overwrite files.  The original reason for using `-n` was to not generate multiple lines of output from `cp` for the same target jar.  We can turn off verbose mode and avoid the problem.
https://issues.apache.org/jira/browse/HDDS-12917
CI:
https://github.com/adoroszlai/ozone/actions/runs/14702995761/job/41256275097#step:13:5932
=> HDDS-12917. cp: option '--update' doesn't allow an argument

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/AbstractRDBStore.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HAUtils.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBStoreBuilder.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestDBStoreBuilder.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStore.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMInstallSnapshot.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/recovery/ReconOmMetadataManagerImpl.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStorageContainerManagerFacade.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/freon/containergenerator/GeneratorOm.java
The `codecRegistry` field in RDBStore was removed by [HDDS-12922](https://issues.apache.org/jira/browse/HDDS-12922). We should also remove the CodecRegistry field from `DBStoreBuilder`.
HDDS-12833
=> HDDS-12833. Remove the CodecRegistry field from DBStoreBuilder.

hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestRatisPipelineProvider.java
Test case was failing intermittently because of the Mocked available healthy nodes counts. Sometimes its returning less value. Fixed with adding one dummy node to avoid this issue for this particular test case.
[HDDS-12915](https://issues.apache.org/jira/browse/HDDS-12915)
Tested via flaky github action - https://github.com/priyeshkaratha/ozone/actions/runs/14726818931
=> HDDS-12915. Intermittent failure in testCreatePipelineThrowErrorWithDataNodeLimit

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestDeletedBlockLog.java
OM uses KeyDeletingService to traverse the deletedtable data in rocksdb, packages the block information to be deleted, and sends it to SCM for recording. The SCM leader receives the record and records it in their rocksdb, and sends a draft request to other SCM follower nodes.
When the data read from om's deletedtable is too large, for example, it has exceeded 32MB, and the upper limit of the draft log size for SCM is 32MB, it will cause writing the draft log for SCM to fail.
```
java.io.IOException: Skip writing the deleted blocks info to the delLog because draft transaction fails. 88064 keys skipped
Caused by: org.apache.hadoop.hdds.scm.exceptions.SCMException:
org.apache.ratis.server.raftlog.exceptions.StateMachineException:
org.apache.ratis.server.raftlog.RaftLogIOException:
Log entry …
```
=> HDDS-11633. Delete message body too large, causing SCM to fail writing raft log

hadoop-ozone/dist/src/main/compose/upgrade/test.sh, hadoop-ozone/dist/src/main/compose/xcompat/clients.yaml, hadoop-ozone/dist/src/main/compose/xcompat/lib.sh
Since the `Ozone 2.0.0` image has been published, we should add `Ozone 2.0.0` to compatibility acceptance tests.
[HDDS-12728](https://issues.apache.org/jira/browse/HDDS-12728)
CI:
https://github.com/chiacyu/ozone/actions/runs/14734736285
=> HDDS-12728. Add Ozone 2.0.0 to compatibility acceptance tests

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueHandler.java
Ozone Datanode caches the used space of a volume in-memory and updates this cached value on:
1. Write chunk
2. Block Delete
3. Container Import
However we're not yet updating the cached value on container delete. This pull request adds code to do that in `KeyValueHandler`. The existing method `StorageVolume#decrementUsedSpace` is used to decrement the cached value.
https://issues.apache.org/jira/browse/HDDS-12925
Added a unit test to `TestKeyValueHandler.java.`
Successful CI - https://github.com/siddhantsangwan/ozone/actions/runs/14749188298
=> HDDS-12925. Update datanode volume used space on container deletion

.github/workflows/ci.yml
Fork timeout intermittently happens for subclasses of `OzoneRpcClientTests` (HDDS-12943), but surefire plugin cannot reliably kill forks (HDDS-10552).  With recent integration test speedups, the slowest split of integration check finishes in ~45 minutes, but timeout is still set to 150 minutes (2.5 hours).  This PR proposes to reduce timeout to 90 minutes (1.5 hours) to save some CI time in case of runaway fork.
https://issues.apache.org/jira/browse/HDDS-12944
https://github.com/adoroszlai/ozone/actions/runs/14771413562
=> HDDS-12944. Reduce timeout for integration check

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/integration-test-s3/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v1/AbstractS3SDKV1Tests.java, hadoop-ozone/integration-test-s3/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v2/AbstractS3SDKV2Tests.java
Currently listObjects ETag field is always null although ETag has been supported for a while. This patch will support it.
Context: A user was trying to use mountpoint-s3 using goofys (https://ozone.apache.org/docs/edge/interface/csi.html) but it specifically require the ETag in listObjects response otherwise it will fail.
https://issues.apache.org/jira/browse/HDDS-12916
Update the AWS SDK V1 integration tests to check ETag, also check that keys without ETag do not throw error.
Clean CI: https://github.com/ivandika3/ozone/actions/runs/14722543262
=> HDDS-12916. Support ETag in listObjects response

hadoop-ozone/dist/src/main/compose/ozonesecure-ha/docker-compose.yaml, hadoop-ozone/dist/src/main/compose/ozonesecure-ha/s3g-virtual-host.yaml, hadoop-ozone/dist/src/main/compose/ozonesecure-ha/scm-decommission.yaml
Some acceptance tests started failing with new Docker Compose version being rolled out by GitHub in runner version [20250504.1.0](https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20250504.1).
```
Executing test ozonesecure-ha/test-s3a.sh
Using Docker Compose v2
Error response from daemon: could not parse extra host IP  172.25.0.115: ParseAddr(" 172.25.0.115"): unexpected character (at " 172.25.0.115")
```
```
Executing test ozonesecure-ha/test-scm-decommission.sh
Using Docker Compose v2
Error response from daemon: could not parse extra host IP  172.25.0.117: ParseAddr(" 172.25.0.117"): unexpected character (at " 172.25.0.117")
```
It looks like our usage of [`extra_hosts`](https://docs.docker.com/reference/compose-file/services/#extra_hosts) is no longer valid.
This change …
=> HDDS-12974. Docker could not parse extra host IP

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/impl/AbstractTestChunkManager.java
`testFinishWrite` fails if external program `fuser` is not available.
```
Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.136 s <<< FAILURE! -- in org.apache.hadoop.ozone.container.keyvalue.impl.TestFilePerBlockStrategy
org.apache.hadoop.ozone.container.keyvalue.impl.TestFilePerBlockStrategy.testFinishWrite -- Time elapsed: 0.094 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
at org.apache.hadoop.ozone.container.keyvalue.impl.CommonChunkManagerTestCases.testFinishWrite(CommonChunkManagerTestCases.java:242)
```
```
java.io.IOException: Cannot run program "fuser": error=2, No such file or directory
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
at org.apache.hadoop.ozone.container.keyvalue.impl.AbstractTestChunkManager.is …
```
=> HDDS-12967. Skip CommonChunkManagerTestCases.testFinishWrite if fuser cannot be started

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServer.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/upgrade/InitialConstraintUpgradeAction.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/upgrade/ReconLayoutVersionManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/upgrade/ReconTaskStatusTableUpgradeAction.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/upgrade/ReconUpgradeAction.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/persistence/TestSchemaVersionTableDefinition.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/upgrade/TestInitialConstraintUpgradeAction.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/upgrade/TestReconLayoutVersionManager.java
This PR fixes a failure in the layout feature finalization step of Recon upgrades. Specifically:
- The upgrade actions previously used `ReconStorageContainerManagerFacade` to fetch the `DataSource`, but this added unnecessary coupling and complexity.
- Now, the upgrade framework directly uses `DataSource`, simplifying the upgrade action interface.
- During schema upgrades (e.g., adding columns in `ReconTaskStatusTableUpgradeAction`), we use `DSL.name()` for column references to avoid Derby-specific issues related to case sensitivity or delayed visibility of new columns.
- Removed the older instantiation path of `ReconLayoutVersionManager` that relied on `SCMFacade`, and refactored related test cases accordingly.
https://issues.apache.org/jira/browse/HDDS-12968
- Verified on a running …
=> HDDS-12968. [Recon] Fix column visibility issue in Derby during schema upgrade finalization.

hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - DeleteKey Metrics.json
In the "Percentage of successfully deleted blocks" panel of the deletion dashboard, the expression is:
```
"expr": "(block_deleting_service_metrics_processed_transaction_success_count / clamp_min(block_deleting_service_metrics_received_block_count, 1)) * 100",     
```
But it should be:
```
"expr": "(block_deleting_service_metrics_success_count / clamp_min(block_deleting_service_metrics_received_block_count, 1)) * 100", 
```
https://issues.apache.org/jira/browse/HDDS-12975
Manually tested using docker+grafana
=> HDDS-12975. Fix percentage of blocks deleted in grafana dashboard

hadoop-ozone/integration-test-s3/pom.xml, pom.xml
The `ozone-integration-test-s3` module has some undeclared direct dependencies on AWS SDK v2 modules. A warning is issued at build time about this:
```
[WARNING] Used undeclared dependencies found:
...
[WARNING]    software.amazon.awssdk:sdk-core:jar:2.31.25:test
[WARNING]    software.amazon.awssdk:regions:jar:2.31.25:test
[WARNING]    software.amazon.awssdk:aws-core:jar:2.31.25:test
[WARNING]    software.amazon.awssdk:auth:jar:2.31.25:test
```
This PR addresses these warnings by making the following changes:
- In the root POM, import the AWS SDK BOM instead of declaring a dependency on just the `s3` module.
- In `ozone-integration-test-s3`, add missing direct dependencies on its individual artifacts as listed in the warning.
https://issues.apache.org/jira/browse/HDDS-12689
- `mvn install …
=> HDDS-12689. Import BOM for AWS SDK, declare dependencies

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeStateManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/states/Node2PipelineMap.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestOneReplicaPipelineSafeModeRule.java
Use `DatanodeID` instead of `UUID` as key in `Node2PipelineMap`.
[HDDS-12971](https://issues.apache.org/jira/browse/HDDS-12971)
Updated existing tests.
=> HDDS-12971. Use DatanodeID in Node2PipelineMap

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/storage/ChunkInputStream.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/StringUtils.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/ratis/RatisHelper.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/Checksum.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/ChecksumData.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/common/OzoneChecksumException.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/ozone/common/TestChecksum.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmKeyInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/RepeatedOmKeyInfo.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/protocolPB/OMPBHelper.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/protocolPB/TestOMPBHelper.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/multipart/S3MultipartUploadCompleteRequest.java
- For checksum mismatched, throw OzoneChecksumException.
- For unexpected checksum type or inconsistent proto, throw IllegalArgumentException.
- For unexpected state, throw IllegalStateException.
Also the verifyChecksum methods in Checksum/ChecksumData always return true (in case of failure, it throws an exception). We will change them to return void.
When working on this issue, found a bug that the md5 checksum was stored in a `ByteString` with length 20 while the md5 only has 16 bytes.  The last 4 bytes are always zeros.  Will fix it in this PR.
HDDS-12954
By existing tests and also new tests.
=> HDDS-12954. Do not throw IOException for checksum.

hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/CompactionNode.java, hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java, hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/rocksdiff/TestRocksDBCheckpointDiffer.java
During the refactoring done in the [PR](https://github.com/apache/ozone/pull/8016) for [HDDS-12053](https://issues.apache.org/jira/browse/HDDS-12053), a couple of minor review comments from were left out:
1. Add back the java doc for CompactionNode constructor
2. Make getCompactionNodeGraph return ConcurrentMap instead of ConcurrentHashMap
These are addressed in this PR
https://issues.apache.org/jira/browse/HDDS-12973
Existing tests
=> HDDS-12973. Add java doc for CompactionNode constructor and make getCompactionNodeGraph return ConcurrentMap

hadoop-ozone/dev-support/checks/acceptance.sh
Try to workaround a concurrency bug in Docker Compose 2.35.1 by limiting parallel operations to 1.
This is temporary, until GitHub rolls out runner image with Docker Compose 2.36 or newer, or rolls back to previous working version.
```
fatal error: concurrent map writes
goroutine 38 [running]:
github.com/docker/compose/v2/pkg/compose.(*composeService).pullRequiredImages.func1.1()
github.com/docker/compose/v2/pkg/compose/pull.go:328 +0x236
...
```
https://docs.docker.com/reference/cli/docker/compose/#configuring-parallelism
https://issues.apache.org/jira/browse/HDDS-12996
https://github.com/adoroszlai/ozone/actions/runs/14900471630
https://github.com/apache/ozone/actions/runs/14900886395?pr=8412
=> HDDS-12996. Workaround for Docker Compose concurrent map writes

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/logs/container/ContainerLogController.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/logs/container/ContainerLogParser.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/logs/container/DuplicateOpenContainersCommand.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/logs/container/ListContainers.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/logs/container/utils/ContainerDatanodeDatabase.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/logs/container/utils/SQLDBConstants.java
This ozone debug CLI command helps to identify containers which were opened more than the required number by tracking the first three "OPEN" states and flag any subsequent "OPEN" state as problematic if it occurs on the same datanode or on a different datanode after these initial events.
This command provides the Container ID of such containers along with the count of OPEN states for each container.
Command is as follows:
`ozone debug log container --db=<path to db> list --duplicate-open=true`
sample output for the command:
```
Container ID: 2187256 - OPEN state count: 4
.
.
.
.
Container ID: 12377064 - OPEN state count: 5
Container ID: 12377223 - OPEN state count: 5
Container ID: 12377631 - OPEN state count: 4
Container ID: 12377904 - OPEN state count: 5
Container ID: 12378161 - OPEN …
```
=> HDDS-12776. ozone debug CLI command to list all Duplicate open containers

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconContainerManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconNodeManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconSCMDBDefinition.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStorageContainerManagerFacade.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/api/TestContainerEndpoint.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconNodeManager.java
The nodes table in ReconSCMDBDefinition uses UUID as the key. It is better to use DatanodeID.
HDDS-12994
By updating existing tests
=> HDDS-12994. Use DatanodeID in ReconSCMDBDefinition.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneManagerSnapshotAcl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
HDDS-12958. [Snapshot] Add ACL check regression tests for snapshot operations.
* Added basic tests to verify permission checks takes effect for various snapshot operations.
* Verifies that bucket owner can: create, rename and delete snapshots.
* Verifies that non bucket owner can not create, rename and delete.
* Verifies that user with bucket read permissions can: list snapshots, get snapshot info, snapshot diff, list snapshot diff jobs and cancel snapshot diff jobs.
* Verifies that user with no permissions cannot do any of the above.
* Fixed a few ACL check bugs in getSnapshotInfo, snapshotDiff and cancelSnapshotDiff.
TODO:
* Audit logs for getSnapshotInfo , snapshotDiff, cancelSnapshotDiff are missing. I was about to add it but my IDE crashed, so I …
=> HDDS-12958. [Snapshot] Add ACL check regression tests for snapshot operations.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/utils/CertificateCodec.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/Codec.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/CodecBuffer.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/CodecException.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/DelegatedCodec.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/Proto2Codec.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/Proto3Codec.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/StringCodecBase.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneSecurityUtil.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/container/common/helpers/BlockData.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/CertInfo.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/metadata/X509CertificateCodec.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/OmDBAccessIdInfo.java
For the db.Codec class (not to be confused with scm.ha.io.Codec), it is better to throw CodecException (a new class) than throw IOException.
We only change the CodeBuffer methods in this PR.  Will change the byte[] methods in HDDS-12989.
HDDS-12947
=> HDDS-12947. Add CodecException.

hadoop-hdds/docs/content/start/FromSource.md, hadoop-hdds/docs/content/start/RunningViaDocker.md
Add Docker Compose v2.32.1+ requirement to documentation
https://issues.apache.org/jira/browse/HDDS-12964
Run command locally
[Github Action Pass](https://github.com/Jimmyweng006/ozone/actions/runs/14819591010)
=> HDDS-12964. Add required docker compose version on Building From Sources Document

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/protocol/DatanodeID.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/CommandForDatanode.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DatanodeDeletedBlockTransactions.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLog.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/SCMBlockDeletingService.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/ScmBlockDeletingServiceMetrics.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/CloseContainerEventHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DeadNodeHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineActionHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineReportHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/RatisPipelineProvider.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestDeletedBlockLog.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestSCMBlockDeletingService.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestDeadNodeHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java
Use DatanodeID in SCMBlockDeletingService
Replace `UUID` with `DatanodeID` to represent a `Datanode` in `SCMBlockDeletingService`.
HDDS-13001
CI Run: https://github.com/nandakumar131/ozone/actions/runs/14922726548
=> HDDS-13001. Use DatanodeID in SCMBlockDeletingService.

hadoop-hdds/client/src/main/java/org/apache/hadoop/hdds/scm/XceiverClientGrpc.java
Use DatanodeID in XceiverClientGrpc
https://issues.apache.org/jira/browse/HDDS-12969
[CI Pass](https://github.com/Jimmyweng006/ozone/actions/runs/14943774662)
=> HDDS-12969. Use DatanodeID in XceiverClientGrpc

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerTask.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancerTaskIterationStatusInfo.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/DataMoveInfo.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancerStatusInfo.java
Use DatanodeID in ContainerBalancerTask.
Replace UUID with DatanodeID to represent a Datanode in ContainerBalancerTask.
HDDS-13002
CI: https://github.com/nandakumar131/ozone/actions/runs/14924339017
=> HDDS-13002. Use DatanodeID in ContainerBalancerTask

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMContext.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/SCMSafeModeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/SafeModeExitRule.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/SafeModeMetrics.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/SafeModeRuleFactory.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestBlockManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestBackgroundSCMService.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestSCMContext.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestSCMServiceManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestDataNodeSafeModeRule.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestHealthyPipelineSafeModeRule.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestOneReplicaPipelineSafeModeRule.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestSCMSafeModeManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestSCMSafeModeWithPipelineRules.java, hadoop-ozone/mini-cluster/src/main/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java, hadoop-ozone/mini-cluster/src/main/java/org/apache/hadoop/ozone/MiniOzoneHAClusterImpl.java
This PR aims to clean-up and refactor SCMSafeModeManager.
Changes made:
* Removed `EventQueue` argument from methods that were not using it.
* Removed all the SafeMode Rule Names declared in SCMSafeModeManager.
(Rule Names are moved to respective Rule definition in HDDS-11798)
* Removed methods that were added only for unit testing.
* Introduced static method to create `SafeModeStatus` instances
* Javadoc cleanup
HDDS-12949
CI Run: https://github.com/nandakumar131/ozone/actions/runs/14832934560
=> HDDS-12949. Cleanup SCMSafeModeManager

hadoop-ozone/cli-admin/src/main/java/org/apache/hadoop/ozone/admin/nssummary/DiskUsageSubCommand.java, hadoop-ozone/cli-shell/src/main/java/org/apache/hadoop/ozone/shell/ListLimitOptions.java, hadoop-ozone/cli-shell/src/main/java/org/apache/hadoop/ozone/shell/ListOptions.java, hadoop-ozone/cli-shell/src/main/java/org/apache/hadoop/ozone/shell/ListPaginationOptions.java, hadoop-ozone/cli-shell/src/main/java/org/apache/hadoop/ozone/shell/PrefixFilterOption.java, hadoop-ozone/cli-shell/src/main/java/org/apache/hadoop/ozone/shell/bucket/ListBucketHandler.java, hadoop-ozone/cli-shell/src/main/java/org/apache/hadoop/ozone/shell/keys/ListKeyHandler.java, hadoop-ozone/cli-shell/src/main/java/org/apache/hadoop/ozone/shell/snapshot/ListSnapshotDiffHandler.java, hadoop-ozone/cli-shell/src/main/java/org/apache/hadoop/ozone/shell/snapshot/ListSnapshotHandler.java, hadoop-ozone/cli-shell/src/main/java/org/apache/hadoop/ozone/shell/volume/ListVolumeHandler.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/logs/container/ListContainers.java
Improve `ListOptions` for better reuse.
`ListOptions` currently provides the following options:
```
-a, --all                 List all results
-l, --length=<limit>      Maximum number of items to list
Default: 100
-p, --prefix=<prefix>     Prefix to filter the items
-s, --start=<startItem>   The item to start the listing from.
This will be excluded from the result.
```
This change:
- extract `--prefix` (to `PrefixFilterOption`) to allow using `ListOptions` in commands with different / more complex filters (e.g. datanode list can filter by hostname, IP or ID)
- rename `ListOptions` to `ListPaginationOptions`
- create separate class `ListLimitOptions` for grouping `--length` and `--all`, since `--start` is not supported by `ozone admin nssummary` and `ozone debug log container list`
- reuse …
=> HDDS-12995. Split ListOptions for better reuse

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/audit/OMAction.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java
HDDS-13012. [Snapshot] Add audit logs for getSnapshotInfo, snapshotDiff and cancelSnapshotDiff.
* The three request handlers: listSnapshotDiffJobs, snapshotDiff and cancelSnapshotDiff do not record audit logs.
* Other OM request handlers also update metrics counter. I am leaving that [HDDS-13013](https://issues.apache.org/jira/browse/HDDS-13013)
https://issues.apache.org/jira/browse/HDDS-13012
=> HDDS-13012. [Snapshot] Add audit logs for listSnapshotDiffJobs, snapshotDiff and cancelSnapshotDiff.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/ChunkUtils.java
Remove the redundant FileLock during chunk write. 
Currently before chunk read and write, it will acquire a read or write lock from fileStripedLock in ChunkUtils, so that read and write are welly controlled in Datanode.
For chunk write, it further acquires an exclusive FileLock after acquire the write lock from fileStripedLock. As the FileLock mainly acts as inter-process lock purpose, to prevent another process from reading or writing to the same lock region, which is not a case in Ozone, there are no other processes which will read/write the same block file as Datanode. So acquire this exclusive FileLock after already holding the write lock from fileStripedLock is not necessary.
BTW, it took ~2ms to acquire a FileLock, ~0.15ms to acquire a LOCK from fileStripedLock.
And FileLock doesn't …
=> HDDS-12919. Remove redundant FileLock from ChunkWrite

.github/workflows/ci.yml
Connections to public address of GitHub runner are no longer allowed (https://github.com/actions/runner-images/issues/12178#issuecomment-2869825173):
```
Connection to localhost (127.0.0.1) 12345 port [tcp/*] succeeded!
Connection to 127.0.0.1 12346 port [tcp/*] succeeded!
Connect to pkrvmberfyhpb9w.ndtsheiqjcounhtwo050w5fsih.bx.internal.cloudapp.net:12347 failed
Connect to 10.1.0.18:12348 failed
```
breaking several integration tests:
```
org.apache.hadoop.ozone.recon.TestReconAndAdminContainerCLI
org.apache.hadoop.ozone.recon.TestReconScmSnapshot
org.apache.hadoop.ozone.recon.TestReconWithOzoneManager
org.apache.hadoop.ozone.s3.awssdk.v1.TestS3SDKV1
org.apache.hadoop.ozone.s3.awssdk.v1.TestS3SDKV1WithRatisStreaming
org.apache.hadoop.ozone.s3.awssdk.v2.TestS3SDKV2 …
```
=> HDDS-13027. Workaround for GitHub connection failures

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/checksum/ContainerChecksumTreeManager.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/checksum/ContainerMerkleTreeWriter.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/interfaces/Handler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/ContainerController.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/checksum/ContainerMerkleTreeTestUtils.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/checksum/TestContainerMerkleTreeWriter.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestContainerReconciliationWithMockDatanodes.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueHandler.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/checksum/TestContainerCommandReconciliation.java
Create a unit test framework that writes container data locally, and mocks an ozone client to operate directly on those containers. This will allow us to test multiple failure combinations across replicas using container scan and repair while running much faster than a miniozone integration test.
The major components of this change are:
- Migrate a test from `TestKeyValueHandler` into its own test class for unit testing scan and repair across replicas.
- Numerous fixes to the container repair code to fix bugs exposed by this test.
- Logging improvements to track reconciliation progress.
As part of the review, it will be helpful to pull #7490, which also incorporates this change, and run the tests there where they will pass with the scanner changes. Inspect the new log messages to make …
=> HDDS-12980. Add unit test framework for reconciliation.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/pipeline/Pipeline.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeDecommissionManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeStateManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/TestSCMCommonPlacementPolicy.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestContainerOperations.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestStorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/node/TestDecommissionAndMaintenance.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestMultiRaftSetup.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestOMSortDatanodes.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconScmSnapshot.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/ClusterStateEndpoint.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/NodeEndpoint.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/DatanodesResponse.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/fsck/ReconSafeModeMgrTask.java
NodeManager.getAllNodes() is used for obtaining the node count. It unnecessarily creates a list of all the nodes for just obtaining the size.
HDDS-13016
=> HDDS-13016. Add a getAllNodeCount() method to NodeManager.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/security/x509/certificate/utils/CertificateCodec.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/Codec.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/DelegatedCodec.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/Proto2Codec.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/Proto3Codec.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/StringCodecBase.java, hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/utils/db/Proto2CodecTestBase.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/SchemaOneChunkInfoListCodec.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/SchemaOneKeyCodec.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/metadata/BigIntegerCodec.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/metadata/OldPipelineIDCodecForTesting.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/metadata/OldX509CertificateCodecForTesting.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/SnapshotDiffJob.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/security/OzoneTokenIdentifier.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/codec/TokenIdentifierCodec.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/NSSummary.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/codec/NSSummaryCodec.java
A new CodecException is being added by [HDDS-12947](https://issues.apache.org/jira/browse/HDDS-12947), which also changes the CodeBuffer methods in this PR.
In this PR, we change the Codec byte[] methods to throw CodecException.
HDDS-12989
=> HDDS-12989. Throw CodecException for the Codec byte[] methods.

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/DBDefinitionFactory.java
`DBDefinitionFactory` accidentally throws `InvalidArnException` (specific to AWS KMS) instead of `IllegalArgumentException`.
https://issues.apache.org/jira/browse/HDDS-12966
https://github.com/adoroszlai/ozone/actions/runs/15020532853
=> HDDS-12966. DBDefinitionFactory should not throw InvalidArnException

.gitignore
Adds .vscode to .gitignore so that git can ignore it. Similar to .idea.
https://issues.apache.org/jira/browse/HDDS-13046
Git is ignoring .vscode after adding it to .gitignore.
=> HDDS-13046. Add .vscode to .gitignore

hadoop-ozone/fault-injection-test/mini-chaos-tests/src/test/java/org/apache/hadoop/ozone/MiniOzoneChaosCluster.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/ReconService.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconAndAdminContainerCLI.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconAsPassiveScm.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconContainerEndpoint.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconInsightsForDeletedDirectories.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconScmSnapshot.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconTasks.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManagerFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManagerHA.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestNSSummaryAdmin.java, hadoop-ozone/mini-cluster/src/main/java/org/apache/hadoop/ozone/MiniOzoneCluster.java, hadoop-ozone/mini-cluster/src/main/java/org/apache/hadoop/ozone/MiniOzoneClusterImpl.java, hadoop-ozone/mini-cluster/src/main/java/org/apache/hadoop/ozone/MiniOzoneHAClusterImpl.java
Remove Recon from `MiniOzoneCluster` interface, adding it as an implementation of `MiniOzoneCluster.Service` instead (like HDDS-12527 for S3 Gateway)
After this, Recon integration tests can be moved to their own submodule in the next subtask (like HDDS-12528 for S3 Gateway).
https://issues.apache.org/jira/browse/HDDS-12568
https://github.com/adoroszlai/ozone/actions/runs/15020426918
=> HDDS-12568. Implement MiniOzoneCluster.Service for Recon

hadoop-hdds/client/src/main/java/org/apache/hadoop/ozone/client/io/ECBlockInputStream.java, hadoop-hdds/client/src/test/java/org/apache/hadoop/hdds/scm/storage/TestBlockOutputStreamCorrectness.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/protocol/DatanodeID.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/pipeline/Pipeline.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineID.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/BlockDeletingService.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CreatePipelineCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/endpoint/RegisterEndpointTask.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/XceiverServerGrpc.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ec/reconstruction/ECContainerOperationClient.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/helpers/TestDatanodeIdYaml.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisorSchedulingBenchmark.java
Remove DatanodeDetails#getUuid usages from
- hdds-common
- hdds-client
- hdds-container-service
HDDS-13044
=> HDDS-13044. Remove DatanodeDetails#getUuid usages from hdds-common/client/container-service.

hadoop-ozone/integration-test-s3/pom.xml, hadoop-ozone/integration-test-s3/src/test/java/org/apache/hadoop/ozone/s3/S3ClientFactory.java, hadoop-ozone/integration-test-s3/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v2/AbstractS3SDKV2Tests.java, pom.xml
- Add verification for resumable download ETag validation in integration tests.
- Since S3AsyncClient is required for this functionality, refactored S3ClientFactory to support both sync and async V2 client creation with shared configuration logic.
https://issues.apache.org/jira/browse/HDDS-12914
[Latest CI](https://github.com/Jimmyweng006/ozone/actions/runs/15047263665)
[CI Pass](https://github.com/Jimmyweng006/ozone/actions/runs/15026061987)
=> HDDS-12914. Validate AWS S3 Transfer Manager Resumable File Download

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeTable.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/CommandForDatanode.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/SCMCommand.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/Table.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/NodeEndpoint.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/DatanodeMetadata.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconNodeManager.java
In ReconNodeManager,
- change `datanodeHeartbeatMap` to use DatanodeID  instead of UUID, and
- remove `inMemDatanodeDetails` since it is not needed.
HDDS-12993
=> HDDS-12993. Use DatanodeID in ReconNodeManager.

hadoop-ozone/client/src/main/java/org/apache/hadoop/ozone/client/rpc/RpcClient.java, hadoop-ozone/dist/src/main/smoketest/ozonefs/ozonefs-obs.robot, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
This reverts commit https://github.com/apache/ozone/commit/7a07625101d54b067d1acbee2e4057ea03587da3 due to a regression reported in [HDDS-12930](https://issues.apache.org/jira/browse/HDDS-12930).
Listing keys using the FS API (`fs -ls` command) should not be allowed for OBS buckets:
```
bash-4.4$ ozone sh bucket info vol1/buck1
{
"metadata" : \{ },
"name" : "buck1",
"listCacheSize" : 1000,
"usedBytes" : 15892,
"usedNamespace" : 1,
"creationTime" : "2025-04-29T06:02:09.195Z",
"modificationTime" : "2025-04-29T06:02:09.195Z",
"sourcePathExist" : true,
"bucketLayout" : "OBJECT_STORE",
"owner" : "hadoop",
"link" : false
}
bash-4.4$ ozone fs -ls ofs://om/vol1/buck1/testfile …
```
=> Revert "HDDS-11232. Spare InfoBucket RPC call for the FileSystem#getFileStatus calls for the general case. (#6988)"

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOmSnapshot.java
HDDS-13042. [snapshot] Add future proofing test cases for unsupported file system API
Ozone currently treats two groups of filesystem calls as unsupported:
setAcl, modifyAclEntries, removeAclEntries, removeDefaultAcl, removeAcl,
setXAttr, removeXAttr, append, truncate, concat, createSymlink
setPermission, setOwner, setReplication
Introduce tests that deliberately fail once these APIs are actually implemented—alerting developers to confirm that each operation produces the correct snapshot diff record.
https://issues.apache.org/jira/browse/HDDS-13042
Test only change.
=> HDDS-13042. [snapshot] Add future proofing test cases for unsupported file system API

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/SCMDeletedBlockTransactionStatusManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/AbstractFindTargetGreedy.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/FindSourceGreedy.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/DatanodeUsageInfo.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/DataNodeSafeModeRule.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeHeartbeatDispatcher.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestDeletedBlockLog.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestSCMDeleteBlocksCommandStatusManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java
We replace the UUID usage with DatanodeID in the server-scm except for
- the CommandQueue code ([HDDS-12550](https://issues.apache.org/jira/browse/HDDS-12550)) and
- ECContainerSafeModeRule ([HDDS-13052](https://issues.apache.org/jira/browse/HDDS-13052)).
HDDS-13051
=> HDDS-13051. Use DatanodeID in server-scm.

hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/TestSCMContainerPlacementRackAware.java
Replace != with assertNotEquals in TestSCMContainerPlacementRackAware.
HDDS-13043
CI: https://github.com/nandakumar131/ozone/actions/runs/15072229024
=> HDDS-13043. Replace != with assertNotEquals in TestSCMContainerPlacementRackAware.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java
processedTransactionSuccessCount and processedTransactionFailCount metrics shouldn't depend on log level.
https://issues.apache.org/jira/browse/HDDS-13057
=> HDDS-13057. Increment block delete processed transaction counts regardless of log level

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmAcls.java
HDDS-13061. Add ACL operation permission check tests.
* Verify that without proper permissions, getAcl, setAcl, addAcl, removeAcl all throws PERMISSION_DENIED.
* In addition, verify that audit log records the corresponding failures.
https://issues.apache.org/jira/browse/HDDS-13061
Unit test only.
=> HDDS-13061. Add ACL operation permission check tests.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/CommandForDatanode.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/replication/ReplicationManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMDatanodeHeartbeatDispatcher.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestSCMBlockDeletingService.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/SimpleMockNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestCloseContainerEventHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/replication/TestReplicationManagerScenarios.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestDeadNodeHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelinePlacementFactory.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/server/TestSCMDatanodeHeartbeatDispatcher.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestStorageContainerManager.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestContainerStateMachineFailures.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCloseContainerByPipeline.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCloseContainerHandler.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestDeleteContainerHandler.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconNodeManager.java
```java
//NodeManager
void addDatanodeCommand(UUID dnId, SCMCommand<?> command);
```
In this PR, we will change the type dnId to DatanodeID.  In the implementation, we will just get UUID and leave the further change to HDDS-12550.
HDDS-13060
=> HDDS-13060. Change NodeManager.addDatanodeCommand(..) to use DatanodeID.

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotUtils.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotUtils.java
HDDS-13064. [snapshot] Add test coverage for SnapshotUtils.isBlockLocationInfoSame()
* Add test cases to cover each and every cases in SnapshotUtils.isBlockLocationInfoSame().
* There is a hsync corner case where the code does not match the comment description. Fixed the code to match the comment.
https://issues.apache.org/jira/browse/HDDS-13064
New unit tests added in TestSnapshotUtils.java
https://github.com/jojochuang/ozone/actions/runs/15079727963/job/42394324040
=> HDDS-13064. [snapshot] Add test coverage for SnapshotUtils.isBlockLocationInfoSame()

hadoop-ozone/integration-test-s3/src/test/java/org/apache/hadoop/ozone/s3/S3GatewayService.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/OzoneClientCache.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/OzoneClientProducer.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3secret/S3SecretEndpointBase.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3secret/S3SecretManagementEndpoint.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/TestOzoneClientCache.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3secret/TestSecretGenerate.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3secret/TestSecretRevoke.java
Fix the problem that `@PreDestroy` is not called on `OzoneClientCache` instance.
- Use `@Singleton` instead of `@ApplicationScoped`
- Avoid static state
- Improve encapsulation (remove `setConfiguration` exposed for testing, use constructor injection instead)
- Create separate client for S3 secret endpoint, which does not have `S3Auth`
https://issues.apache.org/jira/browse/HDDS-11539
Existing tests.  Added debug log.
```
$ docker compose logs s3g | grep OzoneClientCache
s3g-1  | 2025-05-20 19:02:16,079 [qtp1658980982-156] DEBUG s3.OzoneClientCache: org.apache.hadoop.ozone.s3.OzoneClientCache@5b3f64: Created
s3g-1  | 2025-05-20 19:02:16,298 [qtp1658980982-156] DEBUG s3.OzoneClientCache: org.apache.hadoop.ozone.s3.OzoneClientCache@5b3f64: Initialized
s3g-1  | 2025-05-20 19:03:14,746 …
```
=> HDDS-11539. OzoneClientCache `@PreDestroy` is never called

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/replicas/ChecksumVerifier.java
This PR sets the datanode-id as the pipeline-id when a new pipeline is created for the checksums verification tool.
For a 3 way Ratis replicated key, the checksums tool returns the wrong results. 
The checksum verification for each key on each node is always the same for all three replicas. i.e., all replicas fail the checksums or none fail when one replica should. 
The checksums verifier provides incorrect results. 
This can be traced down to the way the pipeline is created for the checksum verification.  
https://github.com/apache/ozone/blob/1825cdf6057ae4ac2d0bcbdcfb0bed1302054e9e/hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/replicas/ChecksumVerifier.java#L62-L66 
When a client is created using this pipeline, it is cached …
=> HDDS-13073. Set pipeline ID in checksums verifier to avoid cached pipeline with different node

hadoop-ozone/integration-test-s3/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v1/AbstractS3SDKV1Tests.java, hadoop-ozone/integration-test-s3/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v2/AbstractS3SDKV2Tests.java
HDDS-13089. [snapshot] Add an integration test to verify snapshotted data can be read by S3 SDK client
* Tests the functionality to create a snapshot of an Ozone bucket and then read files from the snapshot directory using the S3 SDK.
The test follows these steps:
1. Create a bucket and upload a file via the S3 client.
2. Create a snapshot on the bucket using the Ozone client.
3. Construct the snapshot object key using the ".snapshot" directory format.
4. Retrieve the object from the snapshot and verify that its content matches the originally uploaded content.
Generated-by: GitHub Copilot o3-mini
https://issues.apache.org/jira/browse/HDDS-13089
Test only addition.
=> HDDS-13089. [snapshot] Add an integration test to verify snapshotted data can be read by S3 SDK client

hadoop-ozone/cli-admin/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/ListInfoSubcommand.java
The shell prompt ends up on the same line as the last line of output of `ozone admin datanode list --json` command.
https://issues.apache.org/jira/browse/HDDS-13100
https://github.com/sreejasahithi/ozone/actions/runs/15179615710
=> HDDS-13100. ozone admin datanode list --json should output a newline at the end of the list

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneManagerHASnapshot.java
HDDS-9210. Update snapshot chain restore test to incorporate snapshot delete.
* Add snapshot deletion operations to [testSnapshotChainManagerRestore](https://github.com/apache/ozone/blob/master/hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHASnapshot.java#L230)
* Generated-by: GitHub Copilot o3-mini
https://issues.apache.org/jira/browse/HDDS-9210
Test only change.
=> HDDS-9210. Update snapshot chain restore test to incorporate snapshot delete.

hadoop-hdds/common/pom.xml, hadoop-hdds/framework/pom.xml, hadoop-hdds/rocks-native/pom.xml, hadoop-hdds/rocksdb-checkpoint-differ/pom.xml, hadoop-hdds/server-scm/pom.xml, hadoop-ozone/ozone-manager/pom.xml, hadoop-ozone/recon/pom.xml, hadoop-ozone/s3gateway/pom.xml, pom.xml
Fix `Non-test scoped test only dependencies` warnings.  Some of these need to be suppressed, due to [MNG-6058](https://issues.apache.org/jira/browse/MNG-6058).
https://issues.apache.org/jira/browse/HDDS-13017
CI:
https://github.com/adoroszlai/ozone/actions/runs/15112804840
=> HDDS-13017. Fix warnings due to non-test scoped test dependencies

hadoop-hdds/common/pom.xml, hadoop-hdds/container-service/pom.xml, hadoop-hdds/framework/pom.xml, hadoop-hdds/rocksdb-checkpoint-differ/pom.xml, hadoop-ozone/cli-shell/pom.xml, hadoop-ozone/common/pom.xml, hadoop-ozone/csi/pom.xml, hadoop-ozone/datanode/pom.xml, hadoop-ozone/dist/pom.xml, hadoop-ozone/httpfsgateway/pom.xml, hadoop-ozone/insight/pom.xml, hadoop-ozone/interface-client/pom.xml, hadoop-ozone/recon/pom.xml, hadoop-ozone/s3gateway/pom.xml, hadoop-ozone/tools/pom.xml
Limit scope of some dependencies to `runtime`.
https://issues.apache.org/jira/browse/HDDS-12177
https://github.com/adoroszlai/ozone/actions/runs/15270128213
=> HDDS-12177. Set runtime scope where missing

hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/algorithms/ContainerPlacementPolicyFactory.java
The description of` ozone.scm.container.placement.impl` and `ozone.scm.container.placement.ec.impl `has been updated to show that the default property used is` SCMContainerPlacementRackAware`
https://issues.apache.org/jira/browse/HDDS-13075
https://github.com/sreejasahithi/ozone/actions/runs/15186737895
=> HDDS-13075. Fix default value in description of container placement policy configs

hadoop-ozone/cli-admin/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/ListInfoSubcommand.java, hadoop-ozone/cli-admin/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestListInfoSubcommand.java
The `ozone admin datanode list` command does not provide the output in json format when` --json `flag is used along with `--id `filter.
https://issues.apache.org/jira/browse/HDDS-13099
https://github.com/sreejasahithi/ozone/actions/runs/15179925820
Before:(--json flag was ingnored)
```
Datanode: 47f85235-fc2e-4a56-ba2c-5351456b2d13 (/default-rack/X.X.X.X/ozone-datanode-1.ozone_default/1 pipelines)
Operational State: IN_SERVICE
Health State: HEALTHY
Related pipelines:
97263595-69e5-42dc-83ab-67bb6379844c/RATIS/ONE/RATIS/OPEN/Leader
```
After:(--json flag is considered)
```
[ {
"datanodeDetails" : {
"level" : 3,
"cost" : 0,
"id" : {
"uuid" : "47f85235-fc2e-4a56-ba2c-5351456b2d13",
"id" : "47f85235-fc2e-4a56-ba2c-5351456b2d13",
"byteString" : {
"validUtf8" : true,
"empty" : false
}
}, …
```
=> HDDS-13099. ozone admin datanode list ignores --json flag when --id filter is used

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/MoveManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestMoveManager.java
Problem
The method that sends the delete command for container balancer is MoveManager#sendDeleteCommand().
It calculates deleteTimeout as moveTimeout - replicationTimeout, and then sends the delete command with an SCM expiration timestamp of current time + deleteTimeout. This is wrong, the delete expiration timestamp should actually be "The time at which the move was started + moveTimeout."
This PR changes the timestamp considered for calculating the timeout duration.
https://issues.apache.org/jira/browse/HDDS-13067
Existing tests, added a unit test in TestMoveManager
=> HDDS-13067. Container Balancer delete commands should not be sent with an expiration time in the past

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/SnapshotInfo.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/helpers/TestOmSnapshotInfo.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/KeyDeletingService.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/SnapshotDirectoryCleaningService.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotPurgeRequestAndResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestKeyDeletingService.java
Currently KeyDeleting Service runs over and over again even if the deep clean flag for snapshot is true. There should be a check if which should prevent keydeletingService from running if it has been already deep cleaned.
https://issues.apache.org/jira/browse/HDDS-13136
Additional unit tests
=> HDDS-13136. KeyDeleting Service should not run for already deep cleaned snapshots

hadoop-hdds/docs/content/tools/ContainerLogParser.md
This is a documentation for the Container Replica Debugger Tool(Container Replica Historical Timeline), which analyzes datanode container log files , extracts relevant information, and stores it in a temporary SQLite database. It also provides CLI commands to list containers based on different attributes.
https://issues.apache.org/jira/browse/HDDS-13071
NA
=> HDDS-13071. Documentation for Container Replica Debugger Tool

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/filter/ReclaimableFilter.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/filter/AbstractReclaimableFilterTest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/filter/TestReclaimableDirFilter.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/filter/TestReclaimableFilter.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/filter/TestReclaimableKeyFilter.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/filter/TestReclaimableRenameEntryFilter.java
Currently ReclaimableFilter expects the bucket info to be present while initializing the snapshot chain but it could so happen that the bucket could have been deleted with all the entries belonging to the bucket present in the deletedTable & deleted directory table. Reclaimable filter should always return a true if the bucket or volume is not present.
https://issues.apache.org/jira/browse/HDDS-13170
Additional unit tests
=> HDDS-13170. Reclaimable filter should always reclaim entries when buckets and volumes have already been deleted

hadoop-hdds/docs/content/interface/Python.md, hadoop-hdds/docs/content/recipe/Boto3Tutorial.md, hadoop-hdds/docs/content/recipe/PyArrowTutorial.md, hadoop-hdds/docs/content/recipe/PythonRequestsOzoneHttpFS.md
HDDS-13165. [Docs] Python client developer guide.
* Added interface/Python.md: overall Python client access introduction.
* Recipe: Access Ozone using PyArrow (Docker Quickstart)
* Recipe: Access Ozone using Boto3 (Docker Quickstart)
* Recipe: Access Ozone using HTTPFS REST API (Docker + Python Requests)
For interface/Python.md, the draft was generated using ChatGPT 4o using the prompt:
```
Create a user document in Markdown format for Python developers who want to access Apache Ozone. This document will be part of the Ozone Client Interfaces page: https://ozone.apache.org/docs/edge/interface.html.
📌 *Audience*: Python developers familiar with Python integration and Ozone. Skip the introduction.
📌 *Structure*:
Setup and Prerequisites:
Required libraries …
```
=> HDDS-13165. [Docs] Python client developer guide.

.github/workflows/ci.yml, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/conf/ReconfigurableBase.java, hadoop-ozone/ozonefs-hadoop2/pom.xml, hadoop-ozone/ozonefs-hadoop3/pom.xml, hadoop-ozone/ozonefs-shaded/pom.xml, pom.xml
- Fix dependency warning added in HDDS-12554.
- Fail the build for dependency warnings, to prevent the introduction of any more.
- Skip dependency analysis in `ozonefs-shaded` and `ozonefs-hadoop?` modules.  The former is a common dependency for the latter, but does not use any of its dependencies directly.  See HDDS-13058 for a list of problems.  So far I have not found a good way to make both `maven-dependency-plugin` and the build happy.  We could merge `ozonefs-shaded` and `ozonefs-hadoop3` to fix most problems, but only after Hadoop 2 support is dropped.
- Wait for successful build/dependency/license checks before starting integration check.  This adds only few minutes of delay, because it already waited for `basic`, of which `findbugs` was the slowest at 9 minutes, while build takes …
=> HDDS-12977. Fail build on dependency problems

pom.xml
Fix build [failure](https://github.com/apache/ozone/actions/runs/15530372634/job/43717857994#step:8:4649) in `populate-cache` workflow (which builds `ozonefs-hadoop*`, but skips `maven-shade-plugin` execution):
```
[INFO] --- dependency:3.8.1:analyze-only (analyze) @ ozone-filesystem-hadoop3-client ---
[ERROR] Unused declared dependencies found:
[ERROR]    org.apache.ozone:ozone-filesystem-hadoop3:jar:2.1.0-SNAPSHOT:compile
```
https://issues.apache.org/jira/browse/HDDS-13214
Will be tested after merge to `master`.
=> HDDS-13214. populate-cache fails due to unused dependency

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotCreateRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotCreateRequest.java
In-flight snapshots requests are not decremented when a snapshot create request fails for ex., because snapshot already exists. This causes new snapshot requests to fail even though snapshots have not reached the limit. 
Provided a fix for this issue.
https://issues.apache.org/jira/browse/HDDS-13150
Unit Test: `org.apache.hadoop.ozone.om.request.snapshot.TestOMSnapshotCreateRequest#testSnapshotLimitWithFailures`
Without this fix the test fails with 
```
// When snapshot_limit=2. We created 1 snapshot. 1 Snapshot create fails. We try to create a snapshot after a previous request fails.
[ERROR] org.apache.hadoop.ozone.om.request.snapshot.TestOMSnapshotCreateRequest.testSnapshotLimitWithFailures -- Time elapsed: 3.833 s <<< ERROR!
TOO_MANY_SNAPSHOTS …
```
=> HDDS-13150. Fixed SnapshotLimitCheck when failures occur.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/SCMBlockDeletingService.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/SCMDeletedBlockTransactionStatusManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/ScmBlockDeletingServiceMetrics.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestSCMBlockDeletingService.java, hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - DeleteKey Metrics.json, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestBlockDeletion.java
NumBlockDeletionTransactionCreated and NumBlockDeletionTransactionCompleted metrics are updated at each transaction level.
Whereas NumBlockDeletionTransactionSent, NumBlockDeletionTransactionSuccess and NumBlockDeletionTransactionFailure are updated depending on the transactions sent to DN. If the same transaction is sent to 3 DN(as blocks will reside in 3 DNs for Ratis-3), these metrics are updated 3 times.
By looking into below metrics it looks, 1731 transactions are sent and only 577 are completed. But actually 1731 = 577 * 3.
```
"name" : "Hadoop:service=StorageContainerManager,name=SCMBlockDeletingService",
"modelerType" : "SCMBlockDeletingService",
"tag.Hostname" : "ccycloud-3.obsdeletion-719.root.comops.site",
"NumBlockDeletionCommandSent" : 3,
"NumBlockDeletionCommandSuccess" : 3, …
```
=> HDDS-13103. Correct transaction metrics in SCMBlockDeletingService.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/ScmBlockDeletingServiceMetrics.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/placement/metrics/SCMPerformanceMetrics.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMBlockProtocolServer.java
In SCMPerformanceMetrics, deleteKeySuccess and deleteKeyFailure are not updated at the key level but at the request level from OM. These metrics should be updated at the key level to know the actual key count received from OM to SCM for deletion.
Also, we should add block count metrics(Number of blocks received from OM to SCM for deletion).
https://issues.apache.org/jira/browse/HDDS-13142
=> HDDS-13142. Correct SCMPerformanceMetrics for delete operation.

pom.xml
Restore definition of `copy-rename-plugin` with version, accidentally removed in HDDS-13179.
```
[WARNING] Some problems were encountered while building the effective model for org.apache.ozone:ozone-filesystem-shaded:jar:2.1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for com.coderplus.maven.plugins:copy-rename-maven-plugin is missing. @ line 331, column 15
```
https://issues.apache.org/jira/browse/HDDS-13243
No warning about missing version in build:
https://github.com/adoroszlai/ozone/actions/runs/15588817819/job/43902182649
=> HDDS-13243. copy-rename-maven-plugin version is missing

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDeletingServiceIntegrationTest.java
Currently OmSnapshotPurgeResponse acquires a write lock SNAPSHOT_DB_LOCK while deleting the directory. This lock is acquired to avoid race condition with SstFilteringService. If there are threads which have opened a snapshot which inturn acquires a readlock on a snapshot this doesn't let the transactions get flushed. In this test case we have a deleted snapshot which is not closing the referenceCounted info in snapshot. PurgeRequest would be eventually changed to acquire a SNAPSHOT_META_LOCK by @smengcl 's patch https://github.com/apache/ozone/pull/8555. 
https://issues.apache.org/jira/browse/HDDS-13244
Fixed failing unit test
=> HDDS-13244. TestSnapshotDeletingServiceIntegrationTest should close snapshots after deleting them

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMMetrics.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotInternalMetrics.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotMoveTableKeysRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotPurgeRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotSetPropertyRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotMoveTableKeysRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotPurgeRequestAndResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotSetPropertyRequestAndResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotRequestAndResponse.java
Added metrics internal snapshot garbage collection operations: SnapshotMoveTableKeys, SnapshotPurge and SetSnapshotProperty.
https://issues.apache.org/jira/browse/HDDS-13181
Unit Tests
=> HDDS-13181. Added metrics for internal Snapshot Operations.

hadoop-ozone/httpfsgateway/src/main/java/org/apache/ozone/fs/http/server/CheckUploadContentTypeFilter.java
HDDS-13168. Fix content type error response format in `CheckUploadContentTypeFilter.java`
The `CheckUploadContentTypeFilter` was modified to return properly formatted JSON error responses instead of using the generic sendError() method. When a data upload request lacks the required `application/octet-stream` content-type, the filter now returns a consistent JSON error response with the correct `application/json` content-type header.
This change ensures API consistency across all WebHDFS endpoints and makes error responses easier for clients to parse programmatically. Previously, error responses from this filter were not properly formatted as JSON, creating inconsistency with other API responses.
The specific changes include:
- Replaced the sendError() call with a proper JSON response …
=> HDDS-13168. Fix error response format in CheckUploadContentTypeFilter

pom.xml
Merge _integration (shell)_ (~12 minutes) into _integration (ozone)_ (~33 minutes) to reduce overhead of building the project.
https://issues.apache.org/jira/browse/HDDS-13257
Verified that tests from the old _integration (shell)_ split are now run in _integration (ozone)_, which finished in 40 minutes:
https://github.com/adoroszlai/ozone/actions/runs/15626723958/job/44022729282#step:13:5286
=> HDDS-13257. Remove separate split for shell integration tests

hadoop-ozone/dist/src/main/smoketest/debug/ozone-debug-tests.robot, hadoop-ozone/dist/src/main/smoketest/debug/ozone-debug.robot, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestOzoneDebugShell.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/replicas/ReplicasVerify.java
Currently, the output directory option isn't being used for the replicas verify command. In future, the support for writing the output into a file might be added (through [HDDS-13063](https://issues.apache.org/jira/browse/HDDS-13063)), but right now it isn't present.
So the option can be removed, added later if needed
https://issues.apache.org/jira/browse/HDDS-13248
Updated unit and robot test
=> HDDS-13248. Remove `ozone debug replicas verify` option --output-dir

hadoop-hdds/docs/content/interface/S3.md
HDDS-13207. [Docs] Third party systems compatible with Ozone S3.
* Split a section from #8042 and moved it to S3 doc.
* Include a few examples: Teradata, Starbust and Fluentd.
* Generated-by: Copilot Agent (Preview)
https://issues.apache.org/jira/browse/HDDS-13207
Doc only with links added.
=> HDDS-13207. [Docs] Third party systems compatible with Ozone S3.

hadoop-hdds/docs/content/feature/OM-HA.md
HDDS-13112. [Docs] Add a section "Automatic Snapshot Installation for Stale Ozone Managers" to OM HA doc
* Generated-by: ChatGPT, prompt:
```
https://ozone.apache.org/docs/edge/feature/om-ha.html
It is written in the user doc that OM bootstrap happens when adding a new OM. Ratis would trigger notifyInstallSnapshotFromLeader() if a follower OM falls behind the leader OM. We should update the doc to include this condition too.
https://github.com/apache/ratis/blob/c1da37cb455bbf94da267b3f2b9bf3884017e1ca/ratis-server-api/src/main/java/org/apache/ratis/server/leader/LogAppender.java#L109
/**
* Should this {@link LogAppender} send a snapshot to the follower?
*
* @return the snapshot if it should install a snapshot; otherwise, return null.
*/
default …
```
=> HDDS-13112. [Docs] OM Bootstrap can also happen when follower falls behind too much.

hadoop-hdds/docs/content/_index.md, hadoop-hdds/docs/content/start/OnPrem.md, hadoop-hdds/docs/content/start/StartFromDockerHub.md, hadoop-hdds/docs/content/start/_index.md
HDDS-13271. [Docs] Minor text updates, reference links.
* Reviewed the user doc and updated texts that aren't that relevant, add links that provide useful information.
* Update user doc index page: replace 'Hadoop' with 'Big data workloads'
Update Getting Started page: remove 'HDFS'
Add related pages in the docker getting start page for S3 developers to quickly navigate relevant pages.
In the On Prem page, add links to OM, SCM and DN for the interested readers.
https://issues.apache.org/jira/browse/HDDS-13271
User Doc
=> HDDS-13271. [Docs] Minor text updates, reference links.

hadoop-hdds/docs/content/recipe/PythonRequestsOzoneHttpFS.md
HDDS-13265. Simplify the page Access Ozone using HTTPFS REST API (Docker + Python Requests).
* The docker compose file is updated to include httpfs so the instructions can be simplified.
https://issues.apache.org/jira/browse/HDDS-13265
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this.)
=> HDDS-13265. Simplify the page Access Ozone using HTTPFS REST API

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/impl/BlockManagerImpl.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingTask.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeTable.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/SchemaOneDeletedBlocksTable.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestSchemaOneBackwardsCompatibility.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/Table.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/MapBackedTableIterator.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/TestRDBSnapshotProvider.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/InMemoryTestTable.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBTableStore.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestTypedRDBTableStore.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMCertStore.java
After [HDDS-13235](https://issues.apache.org/jira/browse/HDDS-13235), KeyValue became a final class, we no longer need `? extend KeyValue`.
We will leave some of the iterator related changes to HDDS-13276.
HDDS-13246
=> HDDS-13246. Change <? extend KeyValue> to <KeyValue> in hadoop-hdds.

hadoop-hdds/docs/content/interface/native-cpp.md, hadoop-ozone/native-client/libo3fs/o3fs.c, hadoop-ozone/native-client/libo3fs/o3fs.h
HDDS-13277. [Docs] Native C/C++ Ozone clients
* Draft written by ChatGPT 4o, reviewed and rewritten by hand.
* Steps confirmed running within Ozone docker.
* Two source code files slightly updated so that we can use Hadoop binary tarball directly (the old cold was written using Hadoop source code built binary)
https://issues.apache.org/jira/browse/HDDS-13277
Steps confirmed running within Ozone docker.
=> HDDS-13277. [Docs] Native C/C++ Ozone clients

pom.xml
Upgrade Commons BeanUtils to 1.11.0 due to CVE-2025-48734
https://issues.apache.org/jira/browse/HDDS-13287
https://github.com/rohit-kb/ozone/actions/runs/15702273193
=> HDDS-13287. Upgrade commons-beanutils to 1.11.0 due to CVE-2025-48734

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeTable.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/SchemaOneDeletedBlocksTable.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBBatchOperation.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStoreAbstractIterator.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStoreByteArrayIterator.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStoreCodecBufferIterator.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBTable.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/Table.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TableIterator.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/MapBackedTableIterator.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/InMemoryTestTable.java, hadoop-hdds/server-scm/pom.xml, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogStateManagerImpl.java
The Table related currently methods currently may IOException. It should throw more specific exceptions such as RocksDatabaseException and CodecException.
HDDS-13236
=> HDDS-13236. Change Table methods not to throw IOException.

hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - OM Snapshot.json
Since, `NumSnapshotPurges` metric was moved from `OMMetrics` to `OmSnapshotInternalMetrics` in HDDS-13256, updated the metric name in the OM Snapshot Grafana Dashboard. 
Added, `NumSnapshotPurgeFailures` , `NumMoveTableKeys` , `NumMoveTableKeyFailures` to the dashboard as well. 
https://issues.apache.org/jira/browse/HDDS-13256
Tested using docker.
=> HDDS-13256. Updated OM Snapshot Grafana Dashboard to reflect metric updates from HDDS-13181.

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/DBCheckpointServlet.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HddsServerUtil.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/TestRDBSnapshotProvider.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMDBCheckpointProvider.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSCMDbCheckpointServlet.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMDbCheckpointServlet.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOMDBCheckpointUtils.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMDBCheckpointServlet.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/OMDBCheckpointUtils.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotManager.java
- Removed the excludedSstFiles arg. (This was only added for debugging and never used. We already have toExcludeList and any file in this list will be excluded from the tarball)
- Move few common util methods to OMDBCheckpointUtils for use in HDDS-12984
- Change the received/excluded files data structure from List to Set. 
https://issues.apache.org/jira/browse/HDDS-13263
Just a refactor. Existing UT's should cover
=> HDDS-13263. Refactor DB Checkpoint Utilities.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerMetadataInspector.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/statemachine/background/BlockDeletingTask.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/AbstractDatanodeStore.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestBlockDeletingService.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBTable.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/Table.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestTypedTable.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogStateManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/block/DeletedBlockLogStateManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerStateManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SequenceIdGenerator.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineStateManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMCertStore.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestDeletedBlockLog.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/QuotaRepairTask.java
After [HDDS-13254](https://issues.apache.org/jira/browse/HDDS-13254), we may specific the iterator type to create KEY_ONLY/VALUE_ONLY iterators. In this JIRA, we change the SCM and datanode code to use it.
HDDS-13276
=> HDDS-13276. Use KEY_ONLY/VALUE_ONLY iterator in SCM/Datanode.

hadoop-ozone/integration-test-recon/src/test/java/org/apache/hadoop/ozone/recon/TestReconInsightsForDeletedDirectories.java, hadoop-ozone/integration-test-recon/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManagerHA.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestHSync.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestDataUtil.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/client/rpc/TestSecureOzoneRpcClient.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestObjectStoreWithLegacyFS.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerHAWithStoppedNodes.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/service/TestDirectoryDeletingServiceWithFSO.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/service/TestSnapshotDeletingServiceIntegrationTest.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneManagerHASnapshot.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotBackgroundServices.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDirectoryCleaningService.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/repair/om/TestFSORepairTool.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotSetPropertyRequestAndResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/snapshot/TestOMSnapshotCreateResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/snapshot/TestOMSnapshotDeleteResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestKeyDeletingService.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestOpenKeyCleanupService.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestFSODirectoryPathResolver.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/ReconContainerMetadataManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/ReconContainerMetadataManagerImpl.java
Similar to [HDDS-13246](https://issues.apache.org/jira/browse/HDDS-13246), we change `<? extends KeyValue>` to `<KeyValue>` in test.
HDDS-13292
This is a test change.
=> HDDS-13292. Change `<? extends KeyValue>` to `<KeyValue>` in test.

.github/workflows/ci.yml, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCloseContainerCommandHandler.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestReplicationSupervisor.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestTypedRDBTableStore.java, hadoop-ozone/cli-admin/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestListInfoSubcommand.java, hadoop-ozone/dev-support/checks/_post_process.sh, hadoop-ozone/dev-support/checks/junit.sh, hadoop-ozone/dev-support/checks/rat.sh, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOmMetrics.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOzoneManagerListVolumesSecure.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/service/TestSnapshotDeletingServiceIntegrationTest.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/repair/om/TestFSORepairTool.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotPurgeRequestAndResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotSetPropertyRequestAndResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/filter/TestReclaimableRenameEntryFilter.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconUtils.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/BucketEndpoint.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/metrics/TestS3GatewayMetrics.java
Fix several test failures that went unnoticed due to HDDS-13296.
This is currently on top of #8660, hence draft.
https://issues.apache.org/jira/browse/HDDS-13298
Ran each of the changed tests locally.
CI in progress:
https://github.com/adoroszlai/ozone/actions/runs/15757141918
=> HDDS-13298. Fix simple failures

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/Proto3Codec.java, hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/container/common/helpers/BlockData.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/SchemaOneChunkInfoListCodec.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestSchemaOneBackwardsCompatibility.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java
Before [HDDS-13235](https://issues.apache.org/jira/browse/HDDS-13235), KayValue.getValue() deserializes the byte data when it is invoked.  TestSchemaOneBackwardsCompatibility expects it will throw an exception since Schema One does not store the values.
[HDDS-13235](https://issues.apache.org/jira/browse/HDDS-13235) has changed it to deserialize the byte data before creating an KayValue object.  As a result, it will fail earlier.  
In the pull request, we change the codec to return null instead of throwing an exception for maintaining backward compatibility.
[HDDS-13301](https://issues.apache.org/jira/browse/HDDS-13301)
=> HDDS-13301. Fix TestSchemaOneBackwardsCompatibility.

.github/workflows/ci.yml, hadoop-ozone/dev-support/checks/integration.sh, hadoop-ozone/dev-support/checks/junit.sh
_integration (flaky)_ re-runs a few times, if necessary, until they pass, but `[ERROR]` appears in the log for each failure.  Example:
```
[WARNING] Flakes: 
[WARNING] org.apache.hadoop.fs.ozone.TestLeaseRecovery.testGetCommittedBlockLengthTimeout(boolean)[1]
[ERROR]   Run 1: TestLeaseRecovery.testGetCommittedBlockLengthTimeout:400->closeIgnoringOMException:123 expected: <KEY_UNDER_LEASE_RECOVERY> but was: <KEY_NOT_FOUND>
[INFO]   Run 2: PASS
[INFO] 
[WARNING] org.apache.hadoop.fs.ozone.TestLeaseRecovery.testGetCommittedBlockLengthTimeout(boolean)[2]
[ERROR]   Run 1: TestLeaseRecovery.testGetCommittedBlockLengthTimeout:390 expected: <3> but was: <0>
[INFO]   Run 2: PASS
[INFO] 
[INFO] 
[WARNING] Tests run: 103, Failures: 0, Errors: 0, Skipped: 0, Flakes: 2
```
This was flagged by …
=> HDDS-13307. integration (flaky) fails with all tests passing

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/metadata/DatanodeTable.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBTable.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/Table.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/TestRDBSnapshotProvider.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/InMemoryTestTable.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestDBStoreBuilder.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBStore.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestRDBTableStore.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestTypedRDBTableStore.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestTypedTable.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerStateManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerStateManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineStateManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineStateManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/upgrade/FinalizationStateManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerReportHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerStateManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestIncrementalContainerReportHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestUnknownContainerReport.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestContainerPlacement.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/OzoneDelegationTokenSecretManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/OzoneSecretStore.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/BlocksEndPoint.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStorageContainerManagerFacade.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/AbstractReconContainerManagerTest.java
All the implementations of the Table.close() method are noop.  We should remove it.
The patch of this PR is quite big due to the try-with-resource change for auto-closing Table.
HDDS-13294
=> HDDS-13294. Remove the Table.close() method.

hadoop-hdds/common/src/test/java/org/apache/hadoop/hdds/utils/db/CodecTestUtil.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStoreByteArrayIterator.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStoreCodecBufferIterator.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/Table.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/TypedTable.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestTypedTable.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/repair/om/TestFSORepairTool.java
When the value of a key is set to an empty byte[]/String, getting that key should return back an empty byte[]/String.
[HDDS-13254](https://issues.apache.org/jira/browse/HDDS-13254) might have accidentally changed this behavior. We should restore it and add tests to assert it. (Thanks @chungen0126 for pointing it out!)
HDDS-13317
By adding new tests.
=> HDDS-13317. Table should support empty array/String.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/shell/TestReconfigShell.java
```
org.apache.ozone.test.NonHATests$ReconfigShell.testDirectoryDeletingServiceIntervalReconfiguration -- Time elapsed: 0.138 s <<< FAILURE!
java.lang.AssertionError: 
Expecting actual:
"OM: Started reconfiguration task on node [localhost:15006].
OM: Reconfiguring status for node [localhost:15006]: started at Fri Jun 20 06:16:46 UTC 2025 and is still running.
"
to contain:
"SUCCESS: Changed property ozone.directory.deleting.service.interval" 
at org.apache.hadoop.ozone.shell.TestReconfigShell.testDirectoryDeletingServiceIntervalReconfiguration(TestReconfigShell.java:111)
```
The test failure occurs because the assertion is executed before the reconfiguration status has completed. As a result, the expected success message ("SUCCESS: Changed property …
=> HDDS-13306. Intermittent failure in testDirectoryDeletingServiceIntervalReconfiguration

.github/workflows/intermittent-test-check.yml
Remove automatic module detection from `flaky-test-check`.
1. It cannot detect some test classes, e.g. `TestOzoneIntegrationNonHA`.  This is due to having to use old Surefire plugin, because new version cannot reliably kill the fork.
2. With undetected module it has to build all modules.  `hdds-docs` runs `docs.sh` as part of the build, which truncates `output.log`.  This causes only the last iteration's result being kept in `OUTPUT_DIR`.
3. Manually setting the submodule is faster in all cases.
Thus I think it's best to remove `AUTO` as an option and make this input mandatory.
https://issues.apache.org/jira/browse/HDDS-13322
https://github.com/adoroszlai/ozone/actions/runs/15821433077
=> HDDS-13322. Remove module auto-detection from flaky-test-check

hadoop-ozone/dist/src/main/compose/compatibility/docker-config, hadoop-ozone/dist/src/main/smoketest/compatibility/dn.robot, hadoop-ozone/dist/src/main/smoketest/compatibility/lib.resource, hadoop-ozone/dist/src/main/smoketest/compatibility/om.robot, hadoop-ozone/dist/src/main/smoketest/compatibility/recon.robot, hadoop-ozone/dist/src/main/smoketest/compatibility/scm.robot, hadoop-ozone/dist/src/shell/ozone/ozone, hadoop-ozone/dist/src/shell/ozone/ozone-functions.sh
1. `OZONE_OPTS` applies to all `ozone` commands
2. each command (e.g. `ozone om` and `ozone sh`) has its own `OZONE_<component>_OPTS`
Currently setting options only for server processes needs to be done via (2).  Non-server commands also accept additional options via `OZONE_CLIENT_OPTS`.  This change introduces a similar new variable `OZONE_SERVER_OPTS` that will be applied to all server processes, but not to other commands.
https://issues.apache.org/jira/browse/HDDS-13325
Added assertion in existing test cases.
https://github.com/adoroszlai/ozone/actions/runs/15844757365/job/44665086087
=> HDDS-13325. Introduce OZONE_SERVER_OPTS for common options for server processes

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconUtils.java
Optimize memory footprint for listKeys API.
While constructing full path prefix in constructFullPathPrefix method, below code can be expensive:
`fullPath.insert(0, nsSummary.getDirName() + OM_KEY_PREFIX);`
Inserting at position 0 in a StringBuilder has O(n) cost because it must shift the entire buffer every time.
For deeply nested paths (e.g., /a/b/c/d/e/f/g/...), this compounds quickly.
https://issues.apache.org/jira/browse/HDDS-13324
Tested manually and with existing junit and integration test cases.
=> HDDS-13324. Optimize memory footprint for Recon listKeys API

pom.xml
This PR removes jackson1 exclusions in ozone-common, which reflects the root POM.
- groupId: `org.codehaus.jackson`
https://issues.apache.org/jira/browse/HDDS-13295
CI: https://github.com/echonesis/ozone/actions/runs/15847246951
=> HDDS-13295. Remove jackson1 exclusions in ozone-common

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/MetadataKeyFilters.java
KeyPrefixFilter support a list of positive prefixes and a list of negative prefixes at the same time. However, it always only has at most one prefix.
We also remove the MetadataKeyFilter interface since it only has one implementation
HDDS-13319
=> HDDS-13319. Simplify KeyPrefixFilter.

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/ContainerManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/NodeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/node/SCMNodeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/PipelineManagerImpl.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/pipeline/WritableECContainerProvider.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/HddsTestUtils.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/MockNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/SimpleMockNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/TestContainerManagerImpl.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/MockPipelineManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java
When finding a container for a block, the SCM needs to allocate a new container if the existing containers don't match requirements. Currently, the SCM just creates a new container without checking if the Datanodes in that particular pipeline have enough disk space (5 GB) for the new container.
This pull request adds a check for both Ratis and EC flows. The check happens at a single place in `ContainerManagerImpl`. If the SCM is unable to allocate a new container then a different pipeline needs to be tried - code to handle this already exists.
The logic for the check itself already exists in `SCMCommonPlacementPolicy#hasEnoughSpace` and I reuse that here. This existing logic has interesting behaviour for one particular case - it returns false if the exact amount of space is available. For …
=> HDDS-12468. Check for space availability for all dns while container creation in pipeline

hadoop-ozone/ozonefs-hadoop2/pom.xml, hadoop-ozone/ozonefs-hadoop3-client/pom.xml, hadoop-ozone/ozonefs-hadoop3/pom.xml
In this PR, some dependencies were removed or added to avoid maven warnings about both unused declared and used undeclared dependencies. 
`ozone-filesystem-hadoop3-client` has been changed because it depends on `ozone-filesystem-hadoop3` for which have been added new dependencies.
`org.apache.ratis:ratis-thirdparty-misc` has been added as `<ignoredUsedUndeclaredDependency>` because adding the dependency triggers the warning about an unused declared dependency, although without this dependency, an used undeclared warning also appears.
[HDDS-13058](https://issues.apache.org/jira/browse/HDDS-13058)
https://github.com/kostacie/ozone/actions/runs/15854984484
=> HDDS-13058. Fix dependency warnings in ozone-filesystem-hadoop*

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/OMClientResponse.java
After the drop of non-ratis support ([HDDS-11754](https://issues.apache.org/jira/browse/HDDS-11754)), we can remove OMClientResponse flushFuture which was only used for non-ratis case.
https://issues.apache.org/jira/browse/HDDS-13221
removed unsued code , ran unit tests
=> HDDS-13221. Remove Flush future from OMClientResponse

hadoop-hdds/docs/content/security/protect-in-transit-traffic.md
HDDS-13371. [Docs] Protect in-transit traffic
* Add a user doc page for protecting in-transit traffic under 'Security' page.
* Generated-by: Google Gemini Cli, Gemini 2.5 Flash; Prompt:
> Read the jira https://issues.apache.org/jira/browse/HDDS-13371 and implement it.
> Ozone traffic, whether between the cluster and client, or internal inside the cluster, may be transferred via Hadoop RPC (e.g. client to  Ozone Manager), via gRPC (Ratis write pipeline or client reading blocks from DataNode) or HTTP (web UI).
> Add a reference to "Network Ports" page so that interested reader can find out the type of transport used between roles.
Number of tokens used:
```
│  Input Tokens           399,316  │
│  Output Tokens            2,898  │
│  Thoughts Tokens …
```
=> HDDS-13371. [Docs] Protect in-transit traffic

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/ha/SCMContext.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/safemode/SCMSafeModeManager.java, hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/StorageContainerManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/block/TestBlockManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestBackgroundSCMService.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestSCMContext.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/ha/TestSCMServiceManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestDeadNodeHandler.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/node/TestSCMNodeManager.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineManagerImpl.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStorageContainerManagerFacade.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/scm/TestReconPipelineManager.java
- Convert `SafeModeStatus` to an enum, with 3 constants (combination of `safeMode=false`, `preCheckPassed=false` is invalid)
- Replace separate boolean fields in `SCMContext.Builder` and `SCMSafeModeManager` with instance of the new enum
- Check current state before state transition for non-force exit.
https://issues.apache.org/jira/browse/HDDS-13358
CI:
https://github.com/adoroszlai/ozone/actions/runs/16000960427
=> HDDS-13358. Refactor SafeModeStatus to an enum

hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/components/aclDrawer/aclDrawer.tsx, hadoop-ozone/recon/src/main/resources/webapps/recon/ozone-recon-web/src/v2/components/aclDrawer/aclDrawer.tsx
Set a unique key for the ACL table rows
- Currently the ACL table might have rows with repeated names which causes issues with rendering as React expects unique key for each row.
- The row key is set to the name of the user for the ACL which gets repeated in case there are multiple ACLs set for the user causing duplicate entries when switching between ACLs of different buckets.
- This PR fixes that by changing the row key to instead use a combination of the username, type and the scope of the ACL to ensure that the rows have a unique value
https://issues.apache.org/jira/browse/HDDS-13366
Before fix:
<video src="https://github.com/user-attachments/assets/500fdd1f-3186-4f2c-b816-7ddc4619618b" />
After fix:
<video …
=> HDDS-13366. Add unique key to ACL table rows.

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/key/AbstractOMKeyDeleteResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/AbstractS3MultipartAbortResponse.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/s3/multipart/S3MultipartUploadAbortResponseWithFSO.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/TestCleanupTableInfo.java
We need to ensure that abstract OM response class should NOT have CleanupTableInfo annotation since the OM response subclass CleanupTableInfo annotation values will override the parent CleanupTableInfo. The abstract class @CleanupTableInfo will tempt contributors to exclude it in the CleanupTableInfo of the subclasses. It is also difficult to keep track the inheritance if we have more than one level of subclasses (e.g. OMKeyCreateResponseWithFSO extends OMFileCreateResponseWithFSO extends OMFileCreateResponse)
Currently we have these abstract classes:
- AbstractS3MultipartAbortResponse
- AbstractOMKeyDeleteResponse
We can push the CleanupTableInfo of these abstract classes to the all the sub concrete classes. After we need to validate by tests to prevent adding the annotation on abstract …
=> HDDS-13362. Abstract OM response class should not be annotated with CleanupTableInfo

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/interfaces/ScanResult.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainerCheck.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/BackgroundContainerMetadataScanner.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/ContainerScanHelper.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/DataScanResult.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/MetadataScanResult.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerCheck.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestDataScanResult.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestMetadataScanResult.java
Hdds-13341: Renamed the method ishealthy in ScanResult.java to hasErrors 
Renamed the method ishealthy in ScanResult.java to hasErrors 
https://issues.apache.org/jira/browse/HDDS-13341
Ran Unit tests
=> HDDS-13341. Rename ScanResult.isHealthy() to hasErrors()

hadoop-hdds/docs/content/concept/VolumesBucketsKeys.md
HDDS-13381. Docs: Add user documentation for Volumes, Buckets, and Keys
* This commit introduces a new user documentation page that explains the core concepts of Volumes, Buckets, and Keys in Apache Ozone. It covers their overview, detailed explanations, and technical specifics, along with cross-references to related documentation.
* Generated-by: Google Gemini Cli + Gemini 2.5 Flash. Prompt:
> I want to create a dedicated user doc page for Volumes, Buckets and Keys under Architecture section. Gather everything you can find in the user docs, cross reference source code, and come up with a page that covers overview of each of the concepts, detailed explaination, and any nitty gritty details. Make sure to include reference links to other user docs for …
=> HDDS-13381. Docs: Add user documentation for Volumes, Buckets, and Keys

hadoop-hdds/docs/content/feature/OM-HA.md, hadoop-hdds/docs/content/troubleshooting/_index.md, hadoop-hdds/docs/content/troubleshooting/om-ha-snapshot-installation.md
HDDS-13268. [Docs] Advanced topics: troubleshooting OM snapshot installation.
* Added a Troubleshooting section to the user doc.
* Generated-by: Gemini Cli (gemini-2.5-pro). Prompt:
> Read jira https://issues.apache.org/jira/browse/HDDS-13268 and do as requested.
https://issues.apache.org/jira/browse/HDDS-13268
=> HDDS-13268. [Docs] Advanced topics: troubleshooting OM snapshot installation.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeConfiguration.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/TestDatanodeConfiguration.java
As mentioned in the issue, this PR will
- modify the default value of `hdds.datanode.volume.min.free.space.percent` based on `Datanodes.md`
- add Test for the default value checking
https://issues.apache.org/jira/browse/HDDS-13198
CI: https://github.com/echonesis/ozone/actions/runs/16096530965
=> HDDS-13198. Avoid warning due to wrong min.free.space.percent default value

README.md
As mentioned in the JIRA, this PR will
- add Apache Ozone logo on top of the README page
- provide a direct link to Apache Ozone official site while clicking the logo
- add some badges with community contribution statistics
The proposed REAME.md page would be:
https://issues.apache.org/jira/browse/HDDS-13375
CI: https://github.com/echonesis/ozone/actions/runs/16064042816
This PR includes the README.md modifications only.
=> HDDS-13375. Add Ozone logo to the Github README.md

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServer.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/fsck/ReconSafeModeMgrTask.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/scm/ReconStorageContainerManagerFacade.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/OzoneManagerServiceProviderImpl.java
This PR change is to update the health status of ReconContext to false and add an error code to indicate internal error if any component's dependencies failed to initialize properly. This will be used by ReconHealthCheckService to report the health status of Recon. Also improved logging for all components initialization. 
https://issues.apache.org/jira/browse/HDDS-13327
This patch is tested with existing junit and integration tests and manually using docker container cluster setup locally.
=> HDDS-13327. Improve log and error handling while starting Recon

hadoop-hdds/docs/content/tools/ContainerLogParser.md, hadoop-hdds/docs/content/tools/ContainerLogParser.zh.md
Improve the documentation for Container Replica Debugger Tool (ContainerLogParser.md) and add Chinese version of documentation.
https://issues.apache.org/jira/browse/HDDS-13162
https://github.com/sreejasahithi/ozone/actions/runs/15540002838
=> HDDS-13162. Improve Container Replica Debugger Tool documentation

hadoop-ozone/dist/src/main/compose/ozone-om-prepare/test.sh, hadoop-ozone/dist/src/main/compose/ozonesecure-ha/test-debug-tools.sh, hadoop-ozone/dist/src/main/compose/ozonesecure-ha/test-repair-tools.sh, hadoop-ozone/dist/src/main/compose/restart/test.sh, hadoop-ozone/dist/src/main/compose/testlib.sh, hadoop-ozone/dist/src/main/compose/upgrade/compose/ha/load.sh, hadoop-ozone/dist/src/main/compose/upgrade/compose/non-ha/load.sh, hadoop-ozone/dist/src/main/compose/upgrade/testlib.sh
Some acceptance tests use data directories mounted from the host to keep data between restarts. The goal of this change is to:
- reduce code duplication around directory creation and cleanup
- attempt clean with `sudo` if necessary
- suppress errors during cleanup
Most of this can be done by reusing `create_data_dirs` from `upgrade/testlib.sh`.
https://issues.apache.org/jira/browse/HDDS-13404
https://github.com/adoroszlai/ozone/actions/runs/16144325513
=> HDDS-13404. Improve persistent test data dir creation/cleanup

hadoop-hdds/docs/content/concept/OzoneManager.md
HDDS-13380. Docs: Enhance Ozone Manager documentation with cross-references
* Improved the Ozone Manager (OM) user documentation by adding internal links to related concepts and features explained in other documents. This helps clarify jargon and provides a more comprehensive understanding of OM's role and interactions within Ozone.
Specifically, added links for:
- Apache Ratis
- High Availability for Ozone Manager
- Storage Container Manager (SCM)
- Data nodes
- Block ID
- Block Token
- Internal ACLs
- Ranger
- Delegation token
- Recon
* Generated-by: Google Gemini Cli + Gemini 2.5 Flash. Prompt:
> Look at the "Ozone Manager" user doc. Tell me are there any jargons or keywords that look foreign and need more explanation?
> Cross reference the other user …
=> HDDS-13380. Docs: Enhance Ozone Manager documentation with cross-references

hadoop-hdds/docs/content/concept/StorageContainerManager.md
This commit adds a new section to the SCM user documentation explaining what Safe Mode is, how it works, and the conditions for exiting it. It also includes the default values for the relevant configuration properties.
HDDS-13379: Document SCM Safe Mode and its configuration properties.
* Generate explanations for "Safe Mode"
* Generated-by: Google Gemini 2.5 Pro/Flash, + Gemini Cli. Prompt:
> Is there any user doc that details what safe mode is and what conditions must be satisfied to get over the safe mode?
> Good. Looks like existing user doc does not explain it. Add this description to the "Storage Container Manager" user doc.
> Add the default value for the configuration properties mentioned.
> Looks good. Commit the current update.
Tokens used:
``` …
```
=> HDDS-13379. Document SCM Safe Mode and its configuration properties.

hadoop-hdds/docs/content/feature/OM-HA.md, hadoop-hdds/docs/content/feature/SCM-HA.md
HDDS-13373. [Docs] Add leader transfer command and service role listing command in the "OM High Availability" page
* Update OM HA and SCM HA user doc to include command lines for transfer leadership and get service roles, both are useful in the context of HA.
* Generated-by: Google Gemini Cli: Gemini 2.5 Flash; Prompt:
> Read the jira https://issues.apache.org/jira/browse/HDDS-13373. Implement it.
Number of tokens used:
> Input Tokens          361,864
> Output Tokens           2,336
> Thoughts Tokens         2,308
> ─────────────────────────────
> Total Tokens          366,508
> Total duration (API)   1m 17s
https://issues.apache.org/jira/browse/HDDS-13373
Draft prepared by Gemini Cli; Reviewed manually.
=> HDDS-13373. [Docs] Add leader transfer command and service role listing command in the High Availability pages

hadoop-hdds/docs/content/interface/Ofs.md
Provide a one-liner summary of the changes in the PR **Title** field above.
It should be in the form of `HDDS-1234. Short summary of the change`.
* Unlike httpsfs user doc https://ozone.apache.org/docs/edge/interface/httpfs.html we don't list the supported operation for Ofs.
This patch adds a table in the 'Ofs (Hadoop compatible)' page for supported operations.
The table has columns 'Operation', 'Description', 'Support' where 'Operation' is the exact operation name in the audit log, 'Description' is a few words of short description, and 'Support' is either Supported or Unsupported. Add footnotes for any caveats.
Adds a table for HDFS-specific operations that are not part of the general Hadoop FileSystem API and are therefore not supported by Ofs.
* …
=> HDDS-13409. Add supported operations for Ofs.

hadoop-hdds/docs/content/feature/Maintenance.md
HDDS-13369. [Docs] Maintenance mode.
* Create a Maintenance mode user doc.
* Generated-by: Google Gemini Cli, Gemini 2.5 Flash; Prompt:
> Read the jira https://issues.apache.org/jira/browse/HDDS-13369 and implement it.
> The command line CLI in the doc seems inaccurate. Check out the source code of MaintenanceSubCommand and fix the errors.
> The configuration properties in the doc seems wrong. Use the source code for ReplicationManager and look up properties relevant to maintenance mode, and update the doc.
> Add default values too.
> Are there any metrics relevant to maintenance mode and recommission? Mention them in the doc too.
Number of tokens used:
```
│  Input Tokens         1,296,322  │
│  Output Tokens            3,832  │
│  Thoughts Tokens …
```
=> HDDS-13369. [Docs] Maintenance mode.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/HddsConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/dist/src/main/compose/common/security.conf, hadoop-ozone/dist/src/main/compose/ozonesecure-ha/docker-config, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSecretKeySnapshot.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestSecretKeysApi.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestBlockTokens.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestSecureOzoneCluster.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/checksum/TestContainerCommandReconciliation.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/OzoneDelegationTokenSecretManager.java
After [HDDS-8829](https://issues.apache.org/jira/browse/HDDS-8829), dt is signed and verified by secret key generated and managed by SCM.
Secret key has following configurations and default values,
hdds.secret.key.expiry.duration 7d
hdds.secret.key.rotate.duration 1d
hdds.secret.key.rotate.check.duration 10m
dt has following configurations and default values,
ozone.manager.delegation.token.max-lifetime 7d
ozone.manager.delegation.token.renew-interval 1d
ozone.manager.delegation.remover.scan.interval 1h
It's possible a dt is created near the secret key rotation duration (1 day), in which case the dt could stay valid much longer than the secret key.
Say a secret key is created at June 1st, 00:00am.
A dt is created using this secret key at June 1st 23:59pm.
The secret key would expire at …
=> HDDS-13343. Consider delegation token lifetime for secret key expiry

hadoop-ozone/cli-admin/src/main/java/org/apache/hadoop/ozone/admin/om/UpdateRangerSubcommand.java, hadoop-ozone/dist/src/main/compose/ozonesecure-ha/docker-config, hadoop-ozone/dist/src/main/smoketest/admincli/lib.resource, hadoop-ozone/dist/src/main/smoketest/security/ozone-secure-tenant.robot, hadoop-ozone/dist/src/main/smoketest/upgrade/lib.robot, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/s3/tenant/OMTenantDeleteRequest.java
- ozone tenant delete fails with TENANT_NOT_EMPTY if user is assigned to the tenant, but OM deletes associated policies from Ranger first.
- Thus, after ozone tenant user revoke, the tenant is empty, but ozone tenant delete still fails, now due to 404 Not Found error from Ranger, when OM tries to delete policies.
https://issues.apache.org/jira/browse/HDDS-13361
Passed Existing Acceptance Test.
=> HDDS-13361. Attempt to delete non-empty tenant fails after revoke

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfig.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeConfiguration.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java
Background deletion configurations were initially chosen based on educated guesses and lacked validation on real-world workloads. I have now tested large-scale deletions involving millions of files and directories, on a real cluster. Based on the results, I'm updating the relevant property values to better reflect practical performance and scalability.
https://issues.apache.org/jira/browse/HDDS-11514
=> HDDS-11514. Set optimal default values for delete configurations based on live cluster testing.

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotCreateRequest.java
It is normal for a bucket to not have replication config, in this case the default config would be used. So this need not be logged as a warning message.
[HDDS-13387](https://issues.apache.org/jira/browse/HDDS-13387)
https://github.com/sreejasahithi/ozone/actions/runs/16110023140
=> HDDS-13387. OMSnapshotCreateRequest logs invalid warning about DefaultReplicationConfig

CONTRIBUTING.md
HDDS-13403. [Docs] Make feature proposal process more visible.
* Generated-by: Google Gemini 2.5 Pro + Gemini Cli. Prompt:
> read jira https://issues.apache.org/jira/browse/HDDS-13403 and implement it
https://issues.apache.org/jira/browse/HDDS-13403
User doc only change.
=> HDDS-13403. [Docs] Make feature proposal process more visible.

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconUtils.java
This PR change is to address the submission and scheduling of rebuild of NSSummary tree in Recon when triggered for rebuild and submitted to executor service.
Executor may not run scheduled task or remove executor service: org.apache.hadoop.ozone.recon.ReconUtils#triggerRebuild [here](https://github.com/apache/ozone/blob/master/hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconUtils.java#L404). 
After submit to executor service, if immediately shutdown before even executor service schedule task, this can cause non-execution of task.
https://issues.apache.org/jira/browse/HDDS-13428
This patch was tested using existing junit and integration tests.
=> HDDS-13428. Recon - Retrigger of build whole NSSummary tree task submission inconsistency.

hadoop-hdds/rocksdb-checkpoint-differ/pom.xml, hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/RocksDBCheckpointDiffer.java, hadoop-hdds/rocksdb-checkpoint-differ/src/main/java/org/apache/ozone/rocksdiff/SSTFilePruningMetrics.java, hadoop-hdds/rocksdb-checkpoint-differ/src/test/java/org/apache/ozone/rocksdiff/TestRocksDBCheckpointDiffer.java
Added metrics to monitor backup SST file pruning. Metrics being collected
* Total no. of backup SST files pruned.
* No. of backup SST files pruned in the last batch.
* Total no. of backup SST files removed by pruning threads.
* Total no. of compactions processed for pruning.
* No. of pending compaction logs in pruning queue.
* No. of pruning job failures.
https://issues.apache.org/jira/browse/HDDS-13125
Unit Test.
=> HDDS-13125. Add metrics for monitoring the SST file pruning threads.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/TestCloseContainer.java
The test was failing because we were not waiting for the ICR to be sent to SCM. The test now waits for the checksum to be reported to SCM through ICR.
https://issues.apache.org/jira/browse/HDDS-13346
Ran the test 200 times 20 x 10
https://github.com/aswinshakil/ozone/actions/runs/16179046215
=> HDDS-13346. Intermittent failure in TestCloseContainer#testContainerChecksumForClosedContainer

hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/EndpointBase.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestEndpointBase.java
The current [code block in EndpointBase.java](https://github.com/apache/ozone/blob/master/hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/EndpointBase.java#L298-L308) does not correctly handle custom metadata headers when the header names contain uppercase characters.
This may lead to unexpected behavior when clients send headers with capital letters.
* Normalize custom metadata header keys to lowercase at the beginning of processing.
https://issues.apache.org/jira/browse/HDDS-13429
https://github.com/hevinhsu/ozone/actions/runs/16282548652
=> HDDS-13429. Custom metadata headers with uppercase characters are not supported

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotManager.java
HDDS-8903. Add validation for ozone.om.snapshot.db.max.open.files.
* Add value validation for the config property. Not clear what a valid check is, so verify for non-negative number.
* Generated-by: Google Gemini 2.5 Pro + Gemini Cli. Prompt:
> Read jira https://issues.apache.org/jira/browse/HDDS-8903 and tell me what this is about?
https://issues.apache.org/jira/browse/HDDS-8903
mvn test -pl hadoop-ozone/ozone-manager -Dtest=TestOmSnapshotManager
=> HDDS-8903. Add validation for ozone.om.snapshot.db.max.open.files.

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/snapshot/OMSnapshotCreateRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMDirectoriesPurgeRequestAndResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/key/TestOMKeyPurgeRequestAndResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotRequestAndResponse.java
`OMSnapshotCreateRequest` creates new `OzoneConfiguration `for getting the cluster-level default replication setting when the default replication config for the bucket is not set. But it can get the same information from `ozoneManager.getDefaultReplicationConfig()` to avoid instantiation and config loading.
[HDDS-13430](https://issues.apache.org/jira/browse/HDDS-13430)
https://github.com/sreejasahithi/ozone/actions/runs/16269659671
unit tests
=> HDDS-13430. Avoid using new OzoneConfiguration in OMSnapshotCreateRequest

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java
This is a safety net to catch unchecked exceptions thrown as a result of NPE (e.g. from HDDS-10061) and other unexpected exceptions.
Apache Jira description, originally added by @swamirishi :
> When an unchecked exception is thrown right now DN doesn't return a false value back to the SCM. This can lead to the SCM not knowing about the txn status. Another throwable catch block should be added to catch all the exceptions thrown.
https://github.com/apache/ozone/blob/ece9330d8d0324abb1696e3441cb1eb562117d32/hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/DeleteBlocksCommandHandler.java#L327-L336
https://issues.apache.org/jira/browse/HDDS-13451
- n/a
=> HDDS-13451. Exception handling for unchecked exception for deleteBlock command from SCM

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/KeyValueContainerUtil.java
Print container DB path for diagnostics and debugging purpose when DB path doesn't exist in `parseKVContainerData` in case it (e.g. HDDS-10061) happens later again.
https://github.com/apache/ozone/blob/b40c95e9172ab35a86c5c9e655076a2394fe5ea4/hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/helpers/KeyValueContainerUtil.java#L236-L244
https://issues.apache.org/jira/browse/HDDS-13456
- n/a
=> HDDS-13456. Print container DB path when DB does not exist in parseKVContainerData

hadoop-ozone/integration-test-s3/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v1/AbstractS3SDKV1Tests.java, hadoop-ozone/integration-test-s3/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v2/AbstractS3SDKV2Tests.java
AWS SDK Java SDK V2 v2.31.66 adds the ability to presign HeadObject and HeadBucket, we can test for this whether this is supported and add the support if it's not supported yet.
S3G already support head bucket/object in current version, so I add an integration test follow [testPresignedUrlGet](https://github.com/apache/ozone/blob/master/hadoop-ozone/integration-test-s3/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v2/AbstractS3SDKV2Tests.java#L439) in ```AbstractS3SDKV2Tests```
https://issues.apache.org/jira/browse/HDDS-13393
https://github.com/hevinhsu/ozone/actions/runs/16364093333
=> HDDS-13393. Test Presigned HeadObject and HeadBucket support

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestSnapshotDirectoryCleaningService.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/SnapshotDiffManager.java
When directoryDeletingService runs on a snapshot it would create tombstones on AOS for subDirectories and subFiles in the DirectoryTable and FileTable thus full path resolution for a source snapshot will fail and this entry should be skipped since the parent directory object has been fully deleted. Thus any parent objectId that cannot be found on the active tree should be skipped.
https://issues.apache.org/jira/browse/HDDS-13436
Added integration test which would fail without the fix.
=> HDDS-13436. Snapshot Diff Error when DirectoryDeletingService deep cleans snapshot

hadoop-ozone/dist/src/main/compose/common/grafana/dashboards/Ozone - DeleteKey Metrics.json
The "Delete Key Success Latency (avg. time)" under "SCM Summary" wrongfully pointed to OM latency metrics. This is corrected to point to the latency metric from SCM performance metrics.
https://issues.apache.org/jira/browse/HDDS-13481
Manually checked in docker with grafana:
=> HDDS-13481. Fix success latency metric in SCM panels of deletion grafana dashboard

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/DBCheckpointServlet.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/HAUtils.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/RDBSnapshotProvider.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/TestRDBSnapshotProvider.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMDbCheckpointServletInodeBasedXfer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOzoneManagerSnapshotProvider.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMDBCheckpointServletInodeBasedXfer.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManagerHttpServer.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/ratis_snapshot/OmRatisSnapshotProvider.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/snapshot/OmSnapshotUtils.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotManager.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/OzoneManagerServiceProviderImpl.java
OM Follower changes to create and place sst files from hardlink file. This sets the default servlet provider as OMDBCheckpointServletInodeBasedXfer
https://issues.apache.org/jira/browse/HDDS-13070
Existing unit tests i.e TestOMRatisSnapshots/TestOMRatisSnapshotProvider
=> HDDS-13070. OM Follower changes to create and place sst files from hardlink file.

hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestECContainerSafeModeRule.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/safemode/TestRatisContainerSafeModeRule.java
In this PR, unit tests for `RatisContainerSafeModeRule` and `ECContainerSafeModeRule` have been added.
[HDDS-12000](https://issues.apache.org/jira/browse/HDDS-12000)
https://github.com/kostacie/ozone/actions/runs/16267148185
=> HDDS-12000. Add unit test for RatisContainerSafeModeRule and ECContainerSafeModeRule

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/types/ReconBasicOmKeyInfo.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/MultipartInfoInsightHandler.java
Recon OmTableHandlers currently rely on the full KeyInfo proto for key metadata. However, most of the fields in OMKeyInfo, such as KeyLocationList, FileEncryptionInfoProto, OzoneAclInfo, and FileChecksumProto, are not required and contribute to unnecessary serialization and deserialization overhead.
This inefficiency becomes significant for larger keys or multipart upload (MPU) keys, where the KeyLocationList can be very large. As a result, this can cause performance degradation for clients querying this API.
To address this, OMKeyInfo objects should be replaced with a lighter weight ReconBasicOmKeyInfo object (based on the KeyInfoProtoLight proto) introduced in [PR #8699](https://github.com/apache/ozone/pull/8699). This lightweight version includes only the necessary fields required for …
=> HDDS-13442. Replace OMKeyInfo with light-weight ReconBasicOmKeyInfo under OmTableHandlers

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/acl/OzoneAuthorizerFactory.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/acl/OzoneManagerAuthorizer.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/security/acl/OzoneNativeAuthorizer.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/acl/TestOzoneAdministrators.java
In the current code, OzoneAuthorizerFactory checks if (authorizer instanceof OzoneNativeAuthorizer) and then call configure(..), where OzoneNativeAuthorizer is an implementation.
In this PR, we add a new OzoneManagerAuthorizer interface so other implementations can get the configure(..) call. It is useful for adding new implementations.
HDDS-13435
=> HDDS-13435. Add an OzoneManagerAuthorizer interface.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/fs/ozone/TestOzoneFsSnapshot.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMRatisSnapshots.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/snapshot/TestOmSnapshot.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/reconfig/TestOmReconfiguration.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OzoneManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/SstFilteringService.java
This patch makes `ozone.snapshot.filtering.service.interval` reconfigurable to allow live enabling/disabling/restarting SST filtering service in addition to service interval reconfiguration.
A fix has also been included in this PR: any negative value (`<= 0`) for `ozone.snapshot.filtering.service.interval` would disable the `SstFilteringService` now. Otherwise it throws `IllegalArgumentException` from `scheduleWithFixedDelay`.
https://issues.apache.org/jira/browse/HDDS-13464
- Add reconfiguration test case. Example OM log output during reconfiguration:
```log4j
2025-07-21 19:28:38,278 [main] INFO  utils.BackgroundService (BackgroundService.java:shutdown(178)) - Shutting down service SstFilteringService
2025-07-21 19:28:38,278 [main] INFO  utils.BackgroundService …
```
=> HDDS-13464. Make ozone.snapshot.filtering.service.interval reconfigurable

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/checksum/ContainerMerkleTreeWriter.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/checksum/TestContainerMerkleTreeWriter.java
The container data checksum is calculated using only the checksums of the data in the container. If a container has all identical blocks, and replica 1 is missing the first block and replica 2 is missing the last block, the data checksums will be the same, and we will not detect a difference between them. This change adds block ID to the block checksum calculation. 
https://issues.apache.org/jira/browse/HDDS-13237
Added Unit tests.
=> HDDS-13237. Container data checksum should contain block IDs.

hadoop-ozone/dist/src/main/smoketest/s3/freon.robot, hadoop-ozone/freon/src/main/java/org/apache/hadoop/ozone/freon/S3KeyGenerator.java
HDDS-2453. Add Freon tests for S3 MPU Keys
* S3 bucket freon test and MPU key write are already implemented before.
* Added robot test for S3 key writes. S3 bucket freon generator robot test already implemented before.
https://issues.apache.org/jira/browse/HDDS-2453
Robot tests
=> HDDS-2453. Add Freon tests for S3 MPU Keys

hadoop-hdds/docs/content/_index.md
HDDS-13396. Documentation: Improve the top-level overview page for new users.
* The previous overview page was technically accurate but could be intimidating for newcomers. This change revamps the page to be more welcoming and informative by:
- Providing a clear, benefit-oriented introduction.
- Adding a comparison table to HDFS and S3 for better context.
- Highlighting a single, recommended quick-start path (Docker).
- Listing concrete use cases to illustrate practical applications.
* Generated-by: Google Gemini Pro 2.5 + Gemini Cli, Prompt:
> Read all the user documents for me (under /hadoop-hdds/docs/content), digest it, and tell me: do you think you have a good grasp of what Ozone is? What is missing that you think would be good to have?
> What else …
=> HDDS-13396. Documentation: Improve the top-level overview page for new users.

hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/api/OMDBInsightEndpoint.java
The PR introduces a `GET` `/api/v1/keys/deletePending/dirs/size-summary` endpoint to include `totalUnreplicatedDataSize` and `totalReplicatedDataSize` fields for tracking the total pending deletion size for FSO directories in OM.
- `totalReplicatedDataSize`: Total size of directories pending deletion with expected replicated size.
- `totalUnreplicatedDataSize`: Total raw size of directories pending deletion without replicated size.
https://issues.apache.org/jira/browse/HDDS-13188
Manual Testing:
```
bash-5.1$ ozone sh volume create vol1
bash-5.1$ ozone sh bucket create vol1/buck1 --layout=FILE_SYSTEM_OPTIMIZED
bash-5.1$ ozone fs -mkdir -p ofs://om/vol1/buck1/dir1/dir2/dir3
bash-5.1$ dd if=/dev/zero of=test.txt bs=1M count=1
bash-5.1$ ozone fs -put test.txt ofs://om/vol1/buck1/dir1/file1 …
```
=> HDDS-13188. Track total pending deletion size for FSO directories in OM via Recon

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/DirectoryDeletingService.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestDirectoryDeletingService.java
Currently while parallely processing deleted directory table, the main thread doesn't wait for all the threads to finish it's set of deleted directory which could lead to main thread prematurely rocksdb iterator and also leading to incorrectly marking the deep cleaned directories.
https://issues.apache.org/jira/browse/HDDS-13494
Added unit tests for the same.
=> HDDS-13494. DirectoryDeletingService incorrectly waits for all the deleted directories processing

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/ScmConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/OMConfigKeys.java
We think it would be reasonable to bump OM and SCM Ratis (Raft) segment size (`ozone.om.ratis.segment.size` and `ozone.scm.ha.ratis.segment.size`) default values from `4MB` to `64MB`. We are already using `64MB` on DNs for about 2 years:
https://github.com/apache/ozone/commit/fbe584c0cc6e33b737b9b6cf31ee592018d8e594
`ozone.om.ratis.segment.size` sets the size of the raft segment used by Apache Ratis on OM.
`ozone.scm.ha.ratis.segment.size` sets the size of the raft segment used by Apache Ratis on SCM.
`dfs.container.ratis.segment.size` sets the size of the raft segment used by Apache Ratis on DN.
https://issues.apache.org/jira/browse/HDDS-13504
- Existing tests.
=> HDDS-13504. Increase ozone.om.ratis.segment.size and ozone.scm.ha.ratis.segment.size default to 64MB

hadoop-ozone/cli-admin/src/main/java/org/apache/hadoop/hdds/scm/cli/datanode/ListInfoSubcommand.java, hadoop-ozone/cli-admin/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestListInfoSubcommand.java
Currently, the ozone admin datanode list command allows users to combine node selection options (e.g., --node-id, --ip, --hostname) with usage sorting options (e.g., --most-used, --least-used).
This combination leads to confusing command behaviour. For instance, 
`ozone admin datanode list --most-used=true --ip=<IP Address>`
will attempt to get all the nodes in increasing order of usage but then filter to a single node with the given IP. This provides a misleading output to the user since the user would expect all the Dns to be listed in an order based on their usage.
Hence we need to make node selection options and usage sorting options mutually exclusive for this command.
[HDDS-13486](https://issues.apache.org/jira/browse/HDDS-13486) …
=> HDDS-13486. Exclusivity Between Node Selection and Sorting Options in ListInfoSubcommand

hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedConfigOptions.java, hadoop-hdds/managed-rocksdb/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedRocksDB.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/TransactionInfoRepair.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/ldb/RocksDBManualCompaction.java, hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/repair/om/SnapshotChainRepair.java, hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/repair/TestTransactionInfoRepair.java, hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/repair/ldb/TestLdbRepair.java, hadoop-ozone/tools/src/test/java/org/apache/hadoop/ozone/repair/om/TestSnapshotChainRepair.java
We tried to use the offline RocksDB compaction tool to delete all the tombstones from the keyTable in OM DB. We used RdbUtil#getLiveSSTFilesForCFs to check for the LiveFileMetadata for the SST files on keyTable and confirmed that the numDeletions are all zero, meaning that all tombstones have been compacted away.
However, we saw that the compacted OM DB result in larger number of SST files (14332 -> 16111) and larger size (800GB -> 1.1T). We found out that the OPTIONS files before compaction and after the compaction are different. Notably the block_size is reduced from 16KB to 4KB. This might explain why there are larger number of SST files (due to file splitting) and the size increase (due to lower compression ratio on the smaller blocks).
One suspect is that RocksDB#open will simply …
=> HDDS-13422. Ozone tool should preserve previous RocksDB options

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/security/OzoneTokenIdentifier.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/security/TestOzoneTokenIdentifier.java
This PR addresses an OzoneTokenIdentifier bug where a `null` omServiceId field i.e when omServiceId is not set it  incorrectly deserializes as an empty string. Potentially, the problem can be that you might think a delegation token has been removed from RocksDB, but due to this bug, the token actually remains in RocksDB.a corner case previously not covered by tests.
[HDDS-13264](https://issues.apache.org/jira/browse/HDDS-13264)
https://github.com/sreejasahithi/ozone/actions/runs/16417716751
=> HDDS-13264. Fix OzoneTokenIdentifier to correctly handle missing omServiceId field

hadoop-ozone/dist/src/main/smoketest/s3/objectlist.robot, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/BucketEndpoint.java, hadoop-ozone/s3gateway/src/test/java/org/apache/hadoop/ozone/s3/endpoint/TestBucketList.java
[S3G] ListObjectsV2 should accept maxKeys=0
- Optimized Key Processing: In BucketEndpoint.java, a check if (maxKeys > 0) is introduced to wrap the key processing loop. This avoids unnecessary iteration and immediately returns an empty result, improving efficiency for this specific use case.
- Corrected Validation: The validation logic is adjusted to only reject negative values for max-keys, while correctly permitting 0.
https://issues.apache.org/jira/browse/HDDS-13447
[CI Pass](https://github.com/Jimmyweng006/ozone/actions/runs/16396222335)
=> HDDS-13447. [S3G] ListObjectsV2 should accept maxKeys=0

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/ContainerSet.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/impl/HddsDispatcher.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OnDemandContainerScanner.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ContainerImporter.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerSet.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestContainerReconciliationWithMockDatanodes.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOnDemandContainerScanner.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestContainerImporter.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/checksum/TestContainerCommandReconciliation.java
Currently there are no logs present which tell why an on-demand container scan was triggered.
This PR adds the reason for on-demand container scan at the respective locations.
[HDDS-13423](https://issues.apache.org/jira/browse/HDDS-13423)
https://github.com/sreejasahithi/ozone/actions/runs/16463299349
=> HDDS-13423. Logging reason behind triggering onDemand scan on containers

hadoop-ozone/integration-test-recon/pom.xml, hadoop-ozone/integration-test-recon/src/test/java/org/apache/hadoop/ozone/recon/TestNSSummaryMemoryLeak.java, pom.xml
Fix intermittent failure in `TestNSSummaryMemoryLeak`:
```
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 50.48 s <<< FAILURE! -- in org.apache.hadoop.ozone.recon.TestNSSummaryMemoryLeak
org.apache.hadoop.ozone.recon.TestNSSummaryMemoryLeak.testMemoryLeakWithLargeStructure -- Time elapsed: 14.14 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
...
at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:183)
at org.apache.hadoop.ozone.recon.TestNSSummaryMemoryLeak.testMemoryLeakWithLargeStructure(TestNSSummaryMemoryLeak.java:321)
```
https://issues.apache.org/jira/browse/HDDS-13514
Before: 6/100 runs failed
https://github.com/adoroszlai/ozone/actions/runs/16676152386
After: 100/100 runs passed …
=> HDDS-13514. Intermittent failure in TestNSSummaryMemoryLeak

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/checksum/ContainerChecksumTreeManager.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/dn/checksum/TestContainerCommandReconciliation.java
Currently the client will get an [IO_EXCEPTION](https://github.com/apache/ozone/blob/229e5c94eaf1f16b9dcfdb19d7cc5451d104a6dd/hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java#L794) result code when [requesting](https://github.com/apache/ozone/blob/8768d048160a6b3761ddc2938d7287f9cd609e04/hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/checksum/ContainerChecksumTreeManager.java#L366) the merkle tree of a peer that has not been generated yet. If the container is not open, have the peer build the merkle tree from metadata and return this instead. This change builds merkle tree if it's not available.
https://issues.apache.org/jira/browse/HDDS-12990
=> HDDS-12990. Generate tree from metadata when it doesn't exist during getContainerChecksumInfo call

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/protocol/commands/ReconcileContainerCommand.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/checksum/TestReconcileContainerTask.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestReplicationSupervisor.java
Use only container ID for equality in `ReconcileContainerCommand` so that we don't queue multiple reconciliations for the same container. 
https://issues.apache.org/jira/browse/HDDS-13086
=> HDDS-13086. Block duplicate reconciliation requests for the same container and datanode within the datanode.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/diskbalancer/DiskBalancerService.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/diskbalancer/policy/DefaultVolumeChoosingPolicy.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/diskbalancer/policy/DiskBalancerVolumeChoosingPolicy.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueContainer.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/diskbalancer/TestDiskBalancerService.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/node/TestVolumeChoosingPolicy.java
This ticket covers several key improvements to the Disk Balancer functionality, focusing on :
volumeChoosingPolicy,  ” threshold / 100 ” it should be normalized before using it in volumeChoosingPolicy
Rename VolumeChoosingPolicy to DiskBalancerVolumeChoosingPolicy
copyContainer failure should throw exception
https://issues.apache.org/jira/browse/HDDS-13547
Existing UT.
=> HDDS-13547. [DiskBalancer] Change VolumeChoosingPolicy to DiskBalancerVolumeChoosingPolicy

hadoop-ozone/dev-support/checks/sonar.sh, pom.xml
- Bump Sonar Scanner for Maven plugin to the latest version.
- Set SonarQube properties (address and project ID) to allow overriding (for internal builds).
- Also allow overriding the plugin version via environment variable.  (Not as property in `pom.xml`, to minimize CI workflow for future PRs bumping the version, since coverage check is skipped in pull requests.)
https://issues.apache.org/jira/browse/HDDS-13541
https://github.com/apache/ozone/actions/runs/16770890224/job/47490032778
=> HDDS-13541. Bump sonar-maven-plugin to 5.1.0.4751

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/keyvalue/KeyValueHandler.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestContainerReconciliationWithMockDatanodes.java
When reconciling a container with all peers, we should continue on to the next peer if we cannot reach one peer, instead of failing reconciliation.
https://issues.apache.org/jira/browse/HDDS-13519
Added UT
=> HDDS-13519. Reconciliation should continue if a peer datanode is unreachable

hadoop-hdds/docs/content/feature/Topology.md
HDDS-13138. [Docs] Update Topology Awareness user doc.
* Couple of things to update in the doc: default placement policy is changed.
* additional placement policies: SCMContainerPlacementCapacity
* Erasure Coding placement policy: SCMCommonPlacementPolicy
Generated-by: Google Gemini 2.5 Pro (Preview) Deep Research, with the prompt:
```
I want to update the Ozone's Topology Awareness user doc: https://ozone.apache.org/docs/edge/feature/topology.html
First, look at the resources online and Ozone source code, and find out any stale content in the user doc. Find new placement policies not mentioned in the doc. Find out what they do and provide examples to illustrate how they work. Best practices.
Second, update the doc based on the new information …
```
=> HDDS-13138. [Docs] Update Topology Awareness user doc.

hadoop-ozone/tools/src/main/java/org/apache/hadoop/ozone/debug/CheckNative.java
I was using `ozone debug checknative` to check if the rocks-tools lib is properly loaded but it always gives me `false`.
I later found that it was because RocksDB library wasn't loaded before attempting to load rocks-tools lib (ozone_rocksdb_tools). ozone_rocksdb_tools has a dependency on RocksDB library. A symptom is that it throws UnsatisfiedLinkError when debugging TestCheckNative. (Interestingly running the CLI in dist doesn't give any detail, could be because of the log level.)
The solution is to load RocksDB lib before loading rocks-tools lib, just like what [`ManagedRawSSTFileReader#loadLibrary`](https://github.com/apache/ozone/blob/cd308eaa85b0a75f2e263c313da320f33fd227ff/hadoop-hdds/rocks-native/src/main/java/org/apache/hadoop/hdds/utils/db/managed/ManagedRawSSTFileReader.java#L50 …
=> HDDS-13582. Fix checknative tool for rocks-tools

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/response/snapshot/OMSnapshotPurgeResponse.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/snapshot/TestOMSnapshotPurgeRequestAndResponse.java
[HDDS-13253](https://issues.apache.org/jira/browse/HDDS-13253) Creates a local data file (YAML) on snapshot create or every snapshot to track snapshot compaction metadata.  
This PR ensures that the local data file is removed along with the snapshot checkpoint on snapshot purge.
https://issues.apache.org/jira/browse/HDDS-13554
Updated existing Unit test.
=> HDDS-13554. Clean up snapshot local YAML file on Snapshot purge.

hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-ozone/integration-test-recon/src/test/java/org/apache/hadoop/ozone/recon/TestReconInsightsForDeletedDirectories.java, hadoop-ozone/integration-test-recon/src/test/java/org/apache/hadoop/ozone/recon/TestReconWithOzoneManagerFSO.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/ReconServerConfigKeys.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/spi/impl/OzoneManagerServiceProviderImpl.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/OMUpdateEventBatch.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/OMUpdateEventBuffer.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/ReconTaskController.java, hadoop-ozone/recon/src/main/java/org/apache/hadoop/ozone/recon/tasks/ReconTaskControllerImpl.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestOMUpdateEventBuffer.java, hadoop-ozone/recon/src/test/java/org/apache/hadoop/ozone/recon/tasks/TestReconTaskControllerImpl.java
This PR change is to keep Recon OM DB sync and events processing by OM tasks separate and in async fashion.
**Details of changes:**
Implemented event queue-based non-blocking solution for Recon task `reinitialization` that prevents OM delta updates from being blocked during task reprocessing.
**Architecture:**
1. **Buffer Events:** All OM delta updates are buffered in `OMUpdateEventBuffer` (20K capacity)
2. **Async Processing:** Dedicated thread continuously processes buffered events in FIFO order
3. **Blocking Reinitialization call:** reInitializeTasks() remains blocking call to ensure data consistency
4. **Overflow Handling:** When buffer is full → clear buffer → trigger full snapshot fallback
**Key Components Implemented:**
1. `OMUpdateEventBuffer` (New)
- 20K capacity blocking queue …
=> HDDS-8633. Separate Recon OM Synchronization and Tasks Processing.

hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/MapBackedTableIterator.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestKeyPurging.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManager.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/DirectoryDeletingService.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/KeyDeletingService.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/service/SnapshotDeletingService.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestKeyManagerImpl.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/service/TestKeyDeletingService.java
This reverts commit 918b2848ee3ebe13786327c3b06871701a07597e.
https://issues.apache.org/jira/browse/HDDS-13213
=> Revert "HDDS-13213. KeyDeletingService should limit task size by both key count and serialized size. (#8757)"

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestReplicationSupervisor.java
`TestReplicationSupervisor#testReconcileContainerCommandDeduplication` adds commands to the queue and then checks counters related to the queue's size. Events added to the queue are consumed in a different thread, so they may be removed before the test can check the queue counters. To fix this:
1. Add a term to the commands so they are [executed instead of dropped](https://github.com/apache/ozone/blob/1aef378d70f11ed7523c397903b3a26edf93c635/hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/replication/ReplicationSupervisor.java#L403) due the default term being 0.
2. Make the test block reconciliation execution while it checks the queue size. Note that [counters are not decremented until the currently processed task …
=> HDDS-13581. Fix Intermittent failure in TestReplicationSupervisor#testReconcileContainerCommandDeduplication.

.github/workflows/check.yml, .github/workflows/ci.yml, hadoop-ozone/recon/pom.xml
Explicitly install pnpm as part of build step and avoid npx
Ozone builds are failing as npx is not connecting to the npmjs registry.
Initial inspection points towards IP blacklisting. As a part of this PR we make the following changes:
- We directly install pnpm as part of the Recon builds using the frontend-maven-plugin
- Replace usage of `npx pnpm@<version>` with direct `pnpm ...` to avoid calls to npmjs registry
- We also remove node_modules from the cache as adding the pnpm store will ensure the next run can properly access the node modules via the centralized store reducing unnecessary caching
https://issues.apache.org/jira/browse/HDDS-13620
Patch was tested manually via the CI that runs on local fork …
=> HDDS-13620. Explicitly install pnpm and avoid npx usage in builds

hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestDatanodeStateMachine.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestKeyValueContainerData.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestSchemaTwoBackwardsCompatibility.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/TestStaleRecoveringContainerScrubbingService.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/helpers/TestDatanodeVersionFile.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/impl/TestContainerDeletionChoosingPolicy.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/interfaces/TestHandler.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestClosePipelineCommandHandler.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestCreatePipelineCommandHandler.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestDeleteBlocksCommandHandler.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueBlockIterator.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/TestKeyValueContainerMarkUnhealthy.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/keyvalue/impl/TestBlockManagerImpl.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestContainerReader.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/ozoneimpl/TestOzoneContainer.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestDownloadAndImportReplicator.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/replication/TestSendContainerRequestHandler.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/upgrade/TestDatanodeUpgradeToContainerIdsTable.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/upgrade/TestDatanodeUpgradeToHBaseSupport.java
Cleared test code in hdds-container-service from fields which could be converted to local variables.
The production codebase has been updated to comply with the PMD SingularField rule. Instances where compliance was not feasible have been suppressed. In more complex cases, TODO comments were added with corresponding Jira tickets to refactor those sections when converting the field to a local variable is not straightforward.
https://issues.apache.org/jira/browse/HDDS-13560
Patch is tested using existing automation. New tests are not required.
=> HDDS-13560. Convert redundant fields to local var in hdds-container-service module

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/StringUtils.java, hadoop-ozone/integration-test-s3/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v1/AbstractS3SDKV1Tests.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/KeyManagerImpl.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmMetadataManagerImpl.java
- Enforce spec-correct key-marker behavior:
- When upload-id-marker is absent, list keys strictly greater than key-marker.
- When upload-id-marker is present, include same-key uploads only if uploadId > upload-id-marker.
- Set nextKeyMarker/nextUploadIdMarker to the last element actually returned, not the lookahead.
- Use `getLexicographicallyHigherString()` to compute an exclusive seek start for marker handling in RocksDB scans.
- Align DB iteration bounds with page size (avoid over-fetch in the iterator) while still supporting truncation detection.
https://issues.apache.org/jira/browse/HDDS-13290
Add one corner cases test into s3 sdk v1 test
=> HDDS-13290. Correct the pagination semantic of listMultipartUploads

hadoop-hdds/docs/content/feature/Topology.md
Change-Id: Idd660a3e4cef13332ac796635f30f2ee63735b6a
HDDS-13578. [Docs] Add pipeline placement policy to Topology Awareness doc
* Generated-by: Google Gemini Cli 2.5 Pro + Gemini Cli.
* The previous documentation was ambiguous about the different placement and selection policies, leading to confusion.
This change restructures the document to clearly distinguish between:
- Pipeline Creation Policy (`ozone.scm.pipeline.placement.impl`)
- Pipeline Selection/Load Balancing Policy (`hdds.scm.pipeline.choose.policy.impl`)
- Closed Container Replication Policy (`ozone.scm.container.placement.impl`)
This aligns the documentation with the behavior discovered in the source code.
https://issues.apache.org/jira/browse/HDDS-13578
=> HDDS-13578. [Docs] Add pipeline placement policy to Topology Awareness doc

hadoop-hdds/docs/content/security/SecuringTDE.md
The create bucket commands in the doc mentions --key option instead of --bucketkey for creating encrypted bucket. This change is to correct it.
Replaced --key with --bucketkey 
https://issues.apache.org/jira/browse/HDDS-13631 
Tested in my local cluster
=> HDDS-13631. Encrypted bucket creation correction on --key option

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/helpers/BasicOmKeyInfo.java, hadoop-ozone/interface-client/src/main/proto/OmClientProtocol.proto, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/protocolPB/TestOzoneManagerRequestHandler.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicOzoneClientAdapterImpl.java, hadoop-ozone/ozonefs-common/src/main/java/org/apache/hadoop/fs/ozone/BasicRootedOzoneClientAdapterImpl.java
Similar to [HDDS-12094](https://issues.apache.org/jira/browse/HDDS-12094), `ofs.listStatusIterator()` returns FileStatus objects that don't recognise a file is encrypted.
Internally, the method relies on BasicOmKeyInfo returned from OM, which does not have FileEncryptionInfo, and it has no way to tell if a file is encrypted or not.
To keep BasicOmKeyInfo lightweight, added an `isEncrypted` field to BasicOmKeyInfo to identify encrypted files.
[HDDS-13615](https://issues.apache.org/jira/browse/HDDS-13615)
CI: https://github.com/sarvekshayr/ozone/actions/runs/17359661478
=> HDDS-13615. ofs.listStatusIterator() reports files in encrypted buckets as unencrypted

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/server/SCMClientProtocolServer.java, hadoop-ozone/cli-admin/src/main/java/org/apache/hadoop/hdds/scm/cli/ContainerBalancerStartSubcommand.java, hadoop-ozone/cli-admin/src/main/java/org/apache/hadoop/hdds/scm/cli/ContainerBalancerStopSubcommand.java, hadoop-ozone/cli-admin/src/test/java/org/apache/hadoop/hdds/scm/cli/datanode/TestContainerBalancerSubCommand.java
When a container balancer start or stop command fails due to invalid states or options passed, although a suitable error message is printed, the exit code of the command was still 0 which is mis-leading. 
This PR changes the behaviour to throw an exception to client too, making the exit code non-zero
https://issues.apache.org/jira/browse/HDDS-13546
Added unit test coverage
=> HDDS-13546. Exit code should be non-zero if balancer commands fail

hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/OmUtils.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/ha/GrpcOMFailoverProxyProvider.java, hadoop-ozone/common/src/main/java/org/apache/hadoop/ozone/om/ha/HadoopRpcOMFailoverProxyProvider.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/TestOmUtils.java, hadoop-ozone/common/src/test/java/org/apache/hadoop/ozone/om/ha/TestOMFailoverProxyProvider.java
This should be put off until https://github.com/apache/ozone/pull/7262 got merged.
OM Client should normally skip send request to listener OM to reduce the latency introduced by communication with listener OM. 
https://github.com/apache/ozone/pull/7262#pullrequestreview-3171311111
https://issues.apache.org/jira/browse/HDDS-13537
=> HDDS-13537. Client skip send request to listener OM

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConfigKeys.java, hadoop-hdds/common/src/main/resources/ozone-default.xml
Updated default value of `ozone.om.snapshot.compaction.dag.prune.daemon.run.interval = 10min (1h previous value)` to keep up with AOS rocks DB compaction under production workloads triggering a compaction every few minutes.
https://issues.apache.org/jira/browse/HDDS-13638
Existing tests should not fail
=> HDDS-13638. Update the default backup SST pruning interval to 10min.

pom.xml
HDDS-13620 changed frontend build, but properties to skip it in profiles were not updated.  Thus, Recon frontend is always built.
```
$ mvn -DskipTests -DskipRecon -am -pl :ozone-recon clean verify
...
[INFO] --- frontend:1.15.1:install-node-and-pnpm (Install node and npm locally to the project) @ ozone-recon ---
...
[INFO] Installed pnpm locally.
...
[INFO] --- frontend:1.15.1:pnpm (install frontend dependencies) @ ozone-recon ---
...
[INFO] Done in 1.5s
...
[INFO] --- frontend:1.15.1:pnpm (Build frontend) @ ozone-recon ---
...
[INFO] ✓ built in 11.84s
...
[INFO] Apache Ozone Recon ................................. SUCCESS [ 23.734 s]
```
https://issues.apache.org/jira/browse/HDDS-13659
```
$ mvn -DskipTests -DskipRecon -am -pl :ozone-recon clean verify
...
[INFO] --- …
```
=> HDDS-13659. Recon frontend build not skipped with skipRecon

hadoop-hdds/docs/content/interface/S3.md
Update s3 user documents for presigned URL.
* Replaced the "unsupported APIs" list with a clear "supported APIs" list to make the documentation easier to understand.
https://issues.apache.org/jira/browse/HDDS-13676
Doc only
=> HDDS-13676. Update S3 docs for presigned URL

hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OMPerformanceMetrics.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/key/OMKeyCreateRequestWithFSO.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/response/TestCleanupTableInfo.java
As part of performance improvements, new metrics to capture latency for major sub-operation in key creation are introduced. This will help in understanding where more time is spent during key creation and make it easier to troubleshoot slowness.
[HDDS-13510](https://issues.apache.org/jira/browse/HDDS-13510)
CI: https://github.com/sreejasahithi/ozone/actions/runs/16717200562
Sample outputs of the metrics over Prometheus for a total of 2000 keys created.
=> HDDS-13510. Add latency metrics for key creation operation

hadoop-hdds/common/src/main/resources/ozone-default.xml, hadoop-hdds/docs/content/feature/Snapshot.md
HDDS-13526. [Docs] Update snapshot related configuration properties
* A few configuration properties were missed from the last doc update. Add them according to ozone-default.xml
* Generated-by: Google Gemini Pro 2.5 + Gemini Cli
https://issues.apache.org/jira/browse/HDDS-13526
The new properties added are all coming from ozone-default.xml
=> HDDS-13526. [Docs] Update snapshot related configuration properties

hadoop-ozone/integration-test-s3/src/test/java/org/apache/hadoop/ozone/s3/awssdk/S3SDKTestUtils.java, hadoop-ozone/integration-test-s3/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v1/AbstractS3SDKV1Tests.java, hadoop-ozone/integration-test-s3/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v2/AbstractS3SDKV2Tests.java
Refactor test cases for better organization and code reuse.
* Grouped related test cases using `@Nested` for clearer test structure.
* Extracted common object setup to reduce duplicated code, including:
* S3 bucket creation
* `SdkHttpClient` creation
* `S3Presigner` creation
* Constants extraction:
* Bucket name
* Content for upload
* `Duration` for presigned url expiration
* Introduced a shared helper method (`openHttpURLConnection`) for reuse across tests.
https://issues.apache.org/jira/browse/HDDS-13678
https://github.com/hevinhsu/ozone/actions/runs/17721451820
=> HDDS-13678. Refactor presigned URL integration tests

hadoop-ozone/ozonefs-hadoop3/pom.xml, hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java, hadoop-ozone/ozonefs-hadoop3/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java, hadoop-ozone/ozonefs/pom.xml, hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/OzoneFileSystem.java, hadoop-ozone/ozonefs/src/main/java/org/apache/hadoop/fs/ozone/RootedOzoneFileSystem.java
`OzoneFileSystem` and `RootedOzoneFileSystem` use `Strings.isNullOrEmpty` unnecessarily, `Boolean.parseBoolean` already handles both cases (`null` and empty).
```
$ jshell
jshell> Boolean.parseBoolean(null)
$1 ==> false
jshell> Boolean.parseBoolean("")
$2 ==> false
jshell> Boolean.parseBoolean("asdf")
$3 ==> false
jshell> Boolean.parseBoolean("false")
$4 ==> false
jshell> Boolean.parseBoolean("true")
$5 ==> true
```
https://issues.apache.org/jira/browse/HDDS-13689
CI:
https://github.com/adoroszlai/ozone/actions/runs/17801676456
=> HDDS-13689. Remove unnecessary usage of Guava from ozonefs

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/StateContext.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/ClosePipelineCommandHandler.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/CommandDispatcher.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/XceiverServerRatis.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/statemachine/commandhandler/TestClosePipelineCommandHandler.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/hdds/scm/pipeline/TestPipelineClose.java
When DN ratis identifies issues with a pipeline, it triggers close pipeline action for below cases:
- When follower is slow
- When leader is not elected and remain in candidate for longer duration
- Any other issue in pipeline like disk out of space trigger failure
This keeps triggering close pipeline action, even though close actions are queued in DN command queue. If there is any issue in DN pipeline closure, it can result in huge such action every HB.
There is an optimisation that within one HB, it will avoid duplicate pipeline close action.
With this change, repeated triggers across HBs are also prevented by checking the command queue before adding new close actions.
[HDDS-13618](https://issues.apache.org/jira/browse/HDDS-13618)
Added a unit test in `TestClosePipelineCommandHandler`.
=> HDDS-13618. Avoid frequent pipeline close action from DN

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/report/DiskBalancerReportPublisher.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/statemachine/DatanodeStateMachine.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/states/endpoint/HeartbeatEndpointTask.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/diskbalancer/DiskBalancerService.java, hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/ozoneimpl/OzoneContainer.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/report/TestReportPublisher.java, hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/states/endpoint/TestHeartbeatEndpointTask.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/scm/node/TestDiskBalancerDuringDecommissionAndMaintenance.java
In **HeartbeatEndpointTask** there are two reports sent to scm by DN for diskBalancer, one is by addReport using **DiskBalancerReportPublisher**  and second is by  **addDiskBalancerReport** . 
DiskBalancer Report should be sent actively only when diskBalancer is running or paused by node state and if diskBalancer is stopped then report should only be sent if there is any changes since last published report.
Proposed Solution: 
Remove **addDiskBalancerReport** .
https://issues.apache.org/jira/browse/HDDS-13665
Passed Existing tests.
=> HDDS-13665. [DiskBalancer] Cleanup for multiple DiskBalancerReport sent to SCM

hadoop-hdds/docs/content/feature/Topology.md
HDDS-13575. Update Erasure Coding section in the Topology Awareness user doc
* Add EC section in the topology awareness user doc
* Generated-by: Google Gemini 2.5 Pro + Gemini Cli
https://issues.apache.org/jira/browse/HDDS-13575
=> HDDS-13575. Update Erasure Coding section in the Topology Awareness user doc

hadoop-ozone/ozonefs-shaded/pom.xml
Ozone and Ratis both depend on Netty, possibly different versions.  Ratis shades Netty, so version mismatch should not cause any problems.  However, HDDS-12462 changed usage of Netty native libraries in Ozone FS Shaded jars, adding libs from Ozone-specific version of Netty for Ratis.  This causes runtime error if Netty in Ozone is ahead of the one in Ratis, e.g. if Ozone FileSystem fat jar is used in secure environment:
```
NoSuchMethodError: Method org.apache.ozone.shaded.org.apache.ratis.thirdparty.io.netty.internal.tcnative.SSL.setCurvesList0(JLjava/lang/String;)Z name or signature does not match
```
With this PR, we add both sets of native libraries to the shaded jar.
https://issues.apache.org/jira/browse/HDDS-13699
Reproduced the problem by upgrading Netty only in Ozone, but not in …
=> HDDS-13699. Possible Netty version mismatch in ozone-filesystem-shaded

hadoop-ozone/integration-test-s3/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v1/AbstractS3SDKV1Tests.java, hadoop-ozone/integration-test-s3/src/test/java/org/apache/hadoop/ozone/s3/awssdk/v2/AbstractS3SDKV2Tests.java, hadoop-ozone/s3gateway/src/main/java/org/apache/hadoop/ozone/s3/endpoint/BucketEndpoint.java
S3 Gateway rejects "list multipart uploads" request with `max-uploads > 1000`.  On the other hand, `max-keys` for "list keys" is simply capped at 1000 without error.  `max-uploads` should be lenient, too.
This fixes behavior with `S3AFileSystem`, which uses `max-uploads=5000` by default:
https://github.com/apache/hadoop/blob/3baa288982333fbbc3839cf55baaf36f49e0f7b6/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/Constants.java#L476
https://github.com/apache/hadoop/blob/3baa288982333fbbc3839cf55baaf36f49e0f7b6/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java#L662
https://github.com/apache/hadoop/blob/3baa288982333fbbc3839cf55baaf36f49e0f7b6/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java#L5297 …
=> HDDS-13706. Limit max-uploads at 1000

hadoop-hdds/server-scm/src/main/java/org/apache/hadoop/hdds/scm/container/balancer/ContainerBalancer.java, hadoop-hdds/server-scm/src/test/java/org/apache/hadoop/hdds/scm/container/balancer/TestContainerBalancer.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestContainerBalancerOperations.java
`stopBalancer` should be idempotent - meaning that if the balancer is already in a STOPPED state, invoking the stop command again should simply return successfully with exit code 0 and perform no action.
Currently, it instead throws the following error:
```
Caused by: org.apache.hadoop.hdds.scm.container.balancer.IllegalContainerBalancerStateException: Expect ContainerBalancer as running state, but running state is actually STOPPED
```
This behavior is fixed so that repeated stop calls are handled gracefully.
[HDDS-13694](https://issues.apache.org/jira/browse/HDDS-13694)
Tested in `TestContainerBalancer#testStartBalancerStop`. 
CI: https://github.com/sarvekshayr/ozone/actions/runs/17828304300
=> HDDS-13694. Container Balancer Stop Command Fails with Error as Already Stopped

hadoop-ozone/freon/src/main/java/org/apache/hadoop/ozone/freon/BaseFreonGenerator.java
System time with monotonic time was mixed to calculate duration, which is leading to some big number and causing OOM. In this PR we are making only monotonic time for calculating duration in freon.
https://issues.apache.org/jira/browse/HDDS-13709
Verified manually in docker
=> HDDS-13709. Fix freon streaming command with duration.

hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/container/common/transport/server/ratis/ContainerStateMachine.java
The `ContainerStateMachine.notifyLogFailed` throws an NPE when a `null` value for the `failedEntry` parameter is passed to it. This is because the `failedEntry` is dereferenced without a null check.
This PR adds a null check for it.
https://issues.apache.org/jira/browse/HDDS-13711
CI: https://github.com/ptlrs/ozone/actions/runs/18054346254
=> HDDS-13711. Handle null failedEntry in notifyLogFailed to avoid NPE.

hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/scm/net/NodeSchema.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/ByteArrayEncodingState.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/ByteBufferEncodingState.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/EncodingState.java, hadoop-hdds/erasurecode/src/main/java/org/apache/ozone/erasurecode/rawcoder/RSRawDecoder.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/HttpConfig.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/server/http/HttpServer2.java, hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/LogLevel.java, pom.xml
Some code copied long time ago from Hadoop references `HadoopIllegalArgumentException`.  Use Java's built-in `IllegalArgumentException` instead.
https://issues.apache.org/jira/browse/HDDS-13719
CI:
https://github.com/adoroszlai/ozone/actions/runs/18087181224
=> HDDS-13719. Replace HadoopIllegalArgumentException

.github/workflows/check.yml, .github/workflows/ci.yml, hadoop-ozone/csi/pom.xml, hadoop-ozone/dev-support/checks/javadoc.sh, hadoop-ozone/mini-cluster/pom.xml, pom.xml
Fix Javadoc aggregation build failures
* Skip Javadoc for problematic modules: The build failed with cannot find symbol: class OneofDescriptor errors when processing Protobuf-generated sources in the hadoop-ozone/csi module. Instead of attempting complex global source exclusions, **this fix disables Javadoc generation entirely for the csi module**. The same property is also applied to the **mini-cluster module** to avoid issues where its main sources depend on test utilities.
* Excluding all 'package-info.java' files from the aggregation to prevent 'package has already been annotated' errors from conflicting definitions.
[HDDS-13143](https://issues.apache.org/jira/browse/HDDS-13143)
[CI Pass](https://github.com/Jimmyweng006/ozone/actions/runs/16860070232) …
=> HDDS-13144. Fix mvn javadoc:aggregate goal.

hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMHAAdminPrivileges.java, hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/om/TestOMHALeaderSpecificACLEnforcement.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/bucket/OMBucketCreateRequest.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/request/volume/OMVolumeCreateRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/TestOMClientRequestWithUserInfo.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/bucket/TestOMBucketCreateRequest.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/request/volume/TestOMVolumeCreateRequest.java
HDDS-13635 Move ACL check in OMVolumeCreateRequest and OMBucketCreateRequest to pre execute
Moved the ACL check to the preExecute methods. That reduces the number of ACL checks across the cluster, as well as avoids the case when ACL has been changed in the middle of the request, and one peer would suddenly fail. Drawback: the rejection would appear only in the access log on the current leader. 
(https://issues.apache.org/jira/browse/HDDS-13635)
UT/manually with HA cluster
=> HDDS-13635. Move ACL check in OMVolumeCreateRequest and OMBucketCreateRequest to pre execute

hadoop-hdds/framework/src/main/java/org/apache/hadoop/hdds/utils/db/DBConfigFromFile.java, hadoop-hdds/framework/src/test/java/org/apache/hadoop/hdds/utils/db/TestDBConfigFromFile.java
Changed the log to debug from warning for showing message if file doesn't exist since log floods on startups.
HDDS-13735
Tested using docker and existing testcases.
=> HDDS-13735. DBConfigFromFile warns about trying to read from ""

hadoop-ozone/dist/src/main/compose/ozone/monitoring.conf
Currently exporting the traces in a docker environment fails as the Jaeger endpoint URL is incorrect. 
This PR sets the correct endpoint URL.
https://issues.apache.org/jira/browse/HDDS-13741
CI: https://github.com/ptlrs/ozone/actions/runs/18241559029
Tested the docker environment manually. Jaeger UI shows the exported traces.
=> HDDS-13741. Invalid OTEL_EXPORTER_OTLP_ENDPOINT, must be full Jaeger URL

hadoop-ozone/dist/src/main/compose/ozone/monitoring.yaml, hadoop-ozone/dist/src/main/k8s/definitions/jaeger/jaeger.yaml, hadoop-ozone/dist/src/main/k8s/examples/ozone-dev/jaeger-statefulset.yaml
Jaeger v1 is going EOL soon. 
This PR upgrades the docker images to v2.
Documentation on Jaeger v2 images: https://www.jaegertracing.io/download/#container-images
https://issues.apache.org/jira/browse/HDDS-13742
CI: https://github.com/ptlrs/ozone/actions/runs/18242248102
Tested locally:
=> HDDS-13742. Upgrade Jaeger to v2

hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotLocalData.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotLocalDataYaml.java, hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/OmSnapshotManager.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotLocalDataYaml.java, hadoop-ozone/ozone-manager/src/test/java/org/apache/hadoop/ozone/om/TestOmSnapshotManager.java
This is a refactoring patch. Snapshot Defragmentation was previously called Snapshot Compaction during development and in the design doc. It is renamed because the Snapshot Compaction name can be easily confused with RocksDB Compaction, which is a different concept.
It is cleaner to have a separate refactoring jira like this to rename all the occurrences of "compact" that are related to [HDDS-13003](https://issues.apache.org/jira/browse/HDDS-13003) into "defrag".
> compaction -> defrag
compacted -> defragged
uncompacted -> not defragged
https://issues.apache.org/jira/browse/HDDS-13751
- Existing tests.
=> HDDS-13751. Rename all occurrences of "compact" related to HDDS-13003 into "defrag"

README.md
Updated docker quick start section in README to be in sync with latest [changes](https://ozone.apache.org/docs/edge/start/startfromdockerhub.html.).
- The Docker quick start section in the [README](https://github.com/apache/ozone/blob/master/README.md) is out of date. [This](https://ozone.apache.org/docs/edge/start/startfromdockerhub.html) page is more up to date, hence updated the README file to be in sync with that.
- Also added detailed steps on how to use the AWS S3 cli after setup via docker.
https://issues.apache.org/jira/browse/HDDS-13707
N/A
=> HDDS-13707. Update docker quick start section in README
